### ISSUE TITLE
New Ink/Stitch translation on Crowdin: Dutch (NL)

### ISSUE THREAD

**Issue by Rrreutel** [inkstitch/inkstitch#1001]
Hi maintainers,

I've translated Ink/Stitch to Dutch on Crowdin. It's 100% complete, but not reviewed and not checked in the UI. (I mailed the inkstitch-l10n email address without reply, that's why I submit this issue instead.)

I tried following the steps to create a test-branch to test the translation, but I probably lacked the permissions to create a branch. Maybe you could start a test-build for it instead? Then I can check the UI. What would be a good way to get my translations reviewed on crowdin?

**Comment by kaalleen** [comment]
Wow, thank you. I approved your translation and will inform you when you will be able to test.
The main branch will not be build properly anymore, so we might need to migrate the translations to an other branch for you to be able to test them. I think windows would still be working with the main branch (not sure). On which operating system are you?

**Comment by Rrreutel** [comment]
Either linux or Windows is fine. (I think the latest successful build is just for MacOS)

**Comment by kaalleen** [comment]
Ok, then it's not good for our purposes.

I've included your translations in a working developement branch. Since I don't know which operating system you will prefer, here the links for both of them:

- Windows: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-windows-nl_NL.zip
- Linux: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-linux-nl_NL.zip

**Comment by kaalleen** [comment]
By the way... since we are here :) and you will run through most of the Ink/Stitch functions to see your translation ... if you discover any errors in this branch, it'd be really curious about them.

**Comment by Rrreutel** [comment]
Thanks, will test it tomorrow and let you know.

**Comment by Rrreutel** [comment]
I used the Linux version of the Ink/Stich plugin you prepared to test the translation on Ubuntu 20.04, in combination with Inkscape 1.0.2 (1.0.2+r75+1). 
During testing I fixed a bunch of translations on Crowdin for which the context became clearer to me in the UI. They can be approved as far as I'm concerned. 

One larger issue I found was that the simulator UI remains in English, despite translated items being present in Crowdin (e.g. #: electron/src/renderer/components/Simulator.vue:218, keyword 'realistic').

![simulator_english](https://user-images.githubusercontent.com/5664169/106397420-91e52c80-640d-11eb-8df8-752b4d98514e.png)

Not all translations from main/messages.po on crowdin seem to be used: e.g. A dialog after choosing 
Extensions->Ink/Stitch->Install thread color palettes for Inkscape (#: templates/install.inx:3)
is in English while translations are present on Crowdin:
![thread_palettes_EN2](https://user-images.githubusercontent.com/5664169/106397701-f785e880-640e-11eb-8020-502570a78ada.png)

Some smaller issues:

The Extensions > Ink/Stitch menu items are translated as expected, except for 1 menu-item in that list that I cannot find either on Crowdin or in the sourcecode: it is called 'Reorder'. Maybe it originates from Inkscape? (I couldn't screenshot the menu on Linux).

An item in the PDF generation is in English (red), where it should be translated, just like the one slightly below it (green): 
![export_PDF_estimatedtime_EN2](https://user-images.githubusercontent.com/5664169/106397598-94945180-640e-11eb-9373-aa66ba8c6884.png)

I haven't had time to put the code changes you included to the test like you requested, but haven't seen unexpected exceptions/errors so far.

**Comment by kaalleen** [comment]
Hey, thanks for your feedback.

1. Electron apps seem to have an issue with the translations. I haven't noticed it until now, thanks for the hint.
    Inkscape will send a shortened locale name version, such as nl. While our translations file would match on nl_NL. So it won't match. For now I fixed it to work with the long locale name only (system language). This isn't the best solution, since the language set in Inkscape should be working as well. I'll look into it.

2. Reorder is a new extension from this branch. Since it hasn't seen the main branch it doesn't appear in the translation file yet. But I will double check if the translation notation is properly checked. Lex wrote this extension long ago and it had to be removed because of some changes in Inkscape. Inkscape 1.0+ enables us to get it back.

**Comment by kaalleen** [comment]
Btw. I updated the Inkscape1.0 branch to include your translation updates.

**Comment by lexelby** [comment]
Oh hi!  I replied to your email and was wondering why I never heard back -- I'm guessing my message fell victim to a spam filter somewhere along the line. I tried to give you write access to this repo so you could push a branch, but I think I guessed your GitHub account name incorrectly.  I'll get you added now.  (@kaalleen I'm happy to grant folks write access if they want to contribute, and you can too.  You're an admin, so feel free to grant access any time.)

Thank you so much for doing all this translation work, and for the excellent feedback above!

**Comment by lexelby** [comment]
BTW @kaalleen, is something wrong with builds on the main branch?

**Comment by kaalleen** [comment]
Yes, for a long time now. The build process is fixed for the inkscape 1.0(+) branch. It would be really nice if we could merge this branch for the next release. It would make it a lot easier to be working on the code. The new extensions for font creators will also only work with the updated inkex version (it offers an improved way of selecting files). The inkscape 1.0 branch has been tested by some people by now and it seems to work fine.

**Comment by Rrreutel** [comment]
> I tried to give you write access to this repo so you could push a branch, but I think I guessed your GitHub account name incorrectly.

Thanks, I couldn't trace your mail, not even in spam, but I got the Github invitation this time. looking forward to contributing a bit when I have some time. Not a hardcore developer, but comfortable enough with git, maybe I can do some testing every now and then.   

> Thank you so much for doing all this translation work, and for the excellent feedback above!

My daughter (and myself ;-) just started out with a Brother embroidery machine, and she's more comfortable with Dutch than with English or German.

**Comment by lexelby** [comment]
Oh!  I had no idea the inkex 1.0 version worked.  That's incredible news!  I'll give it a test when I get a chance.

**Comment by lexelby** [comment]
@Rrreutel I blame email gremlins.  Thanks again for your contribution, and anything you care to do in the future is appreciated.  We're pretty relaxed here and work to avoid having anyone feel pressured to contribute more if they don't want to.
