### ISSUE TITLE
Params popup does not appear

### ISSUE THREAD

**Issue by Elmarievdm** [inkstitch/inkstitch#1003]
I am running macOS Big Sur 11.1  I have installed Inkscape and the Inkstitch extension.  I follow the tutorial of the circle in the beginning step by step but the Params window/popup does not appear.  Please help

**Comment by kaalleen** [comment]
Does this info help: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur ?

**Comment by asuma4** [comment]
i have this issue and no the link wont help

**Comment by kaalleen** [comment]
What exactly do you mean by Params window/popup ... the simulator or the params themselves?

**Comment by 3Adavis3** [comment]
I am having the same issue with windows.  I click Params and I get a box that says it is opening it, once that goes away nothing else appears.  I have looked on the website.  It shows this "Extensions > Ink/Stitch > Params"  When I go to Extensions>Ink/Stitch I do not have a Params to look under. I am attaching a jpeg of what my file folder looks like.  
![File View](https://user-images.githubusercontent.com/79180840/108148917-cc062d80-709f-11eb-8871-971133f4a1f9.jpg)

**Comment by kaalleen** [comment]
Sorry for the late answer. I somehow must have missed your post. I hope your installation works with the updated Ink/Stitch version. If not, please reopen this issue or create a new one.
