### ISSUE TITLE
Question about auto_fill crossing border error message

### ISSUE THREAD

**Issue by stickliesel** [inkstitch/inkstitch#1011]
When creating the stitch file as described in the quick start guid following error message is shown the file ist not created/stored:

path10: Fehler: Füllung: Form ist ungültig. Das kann passieren, wenn sich die Außenlinien selbst überkreuzen.

Can you please tell us what the issue seems to be here and what we have to do to successfully create the stitch file.

Thank you.

**Comment by kaalleen** [comment]
Ah yes, this has been a bad issue for us lately. Make sure to convert your circle to a path. If the error still exists (most likely), run the function break apart objects while the circle is selected. You can find it under Extensions > Ink/Stitch > Fill Tools.

Hope it helps.

**Comment by kaalleen** [comment]
I'll close this issue. The new release (v2.0.0) should have fixed this issue. Please reopen, if the error still occurs.
