### ISSUE TITLE
Additional Steps on Mac Big Sur

### ISSUE THREAD

**Issue by binkie24** [inkstitch/inkstitch#1015]
I’ve done the additional steps on my Mac because I have Big Sur. Every time I open Inkscape, it force closes and give me an error. Uninstalling and reinstalling does nothing. I’m not sure what needs to be done now. 😫

**Comment by kaalleen** [comment]
Hm, looks like it somehow damaged your Inkscape installation. Maybe we can try to reset Inkscape.

Open Finder
Click on "go" in the main menu and choose "go to folder"
Enter the path to the inkscape configuration files: `~/Library/Application Support/`
Delete the folder org.inkscape.Inkscape

This will remove all your settings and also Ink/Stitch. From there you can start the installation again, once you have Inkscape running again. Hope it helps.

Some users reported it would be important to have Inkscape closed while installing Ink/Stitch. I don't know if that's true - but it doesn't hurt to follow their advice.

**Comment by binkie24** [comment]
> Hm, looks like it somehow damaged your Inkscape installation. Maybe we can try to reset Inkscape.
> 
> Open Finder
> Click on "go" in the main menu and choose "go to folder"
> Enter the path to the inkscape configuration files: `~/Library/Application Support/`
> Delete the folder org.inkscape.Inkscape
> 
> This will remove all your settings and also Ink/Stitch. From there you can start the installation again, once you have Inkscape running again. Hope it helps.
> 
> Some users reported it would be important to have Inkscape closed while installing Ink/Stitch. I don't know if that's true - but it doesn't hurt to follow their advice.

That helped! Thank you so much!
