### ISSUE TITLE
Embroidery file repositories

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1020]
Hi folks,
with the increasing amount of InkStitch users there is an increasing amount of people who might like to share their designs in both SVG source and machine formats.

Anyone know where ? Most platforms I have seen do not appeal to me. I personally would suggest making platforms such as thingiverse, but that would only attract makers. 
 greetings ! Daniel
PS: I do not ask for myself since I do have our EdTech wiki, but I would like to encourage people in the 3-4 facebook groups to share and to suggest one or more "places" that are both friendly (minimal advertising), sustainable and easy to use.

**Comment by kaalleen** [comment]
I love this idea. It would be so nice to have a platform for free and open Ink/Stitch embroidery files such as openclipart.org
It feels very tempting to create a platform which is especially made for it. :D I also don't know an existing platform which could offer all what we need.

**Comment by wwderw** [comment]
In the short term, could have an example repo on here.  Not that robust for a long term solution, but at least it would give something up and running initially.

**Comment by danielkschneider** [comment]
I have seen some people using Github to deposit 3D printing files in STL format and they actually even display. Anyhow, an example directory would be nice in any case, but it's not the same thing as a place where anyone could share (including ugly designs). Also, using Gitub is not easy.

There exists some media repository software that one could use and that would have been easy 20 years ago. Now, the problem is that you need both AI and human power to fight spam as soon as the search engines pick up something of interest. So it's not just a technical question.

**Comment by MK-12-20MM** [comment]
I have been a user of Ink/Stitch i think now for almost a couple of years.   I have a board which has a resource repository. So in a nut-shell as far as user communities, there are few facebook groups and some sub-reddits.  I don't like facebook due to privacy and reddit is not good for interaction.  I just spun this site  up recently ( I all ready had hosting and licensing - collecting dust). I don't know if this discussion is for an official site or inkstitch enthusiast sponsored,.  Things are WIP but there be no selling or users slammed with ads. Repository is for members only and any uploads will be moderated. Just want to make sure that it's not a wild west show and provide some protection to user content.   I think that since I am close to retirement some form of donation for hosting/licensing costs would be in the future.  

I want to avoid self promotion..  I won't post the link at this point, as my site as no relationship to development here. Also there is a discussion area here so I don't want to step on any toes.  Not sure if there is interest in other user groups.

**Comment by kaalleen** [comment]
That is really a nice offer. Thank you for that. I hope you are not disappointed when I say, that I would really love an open platform. The uploads must be members only and svg files need sanitizing, but it would be great to have the files accessible for the public. If you don't mind, I really would like to offer an other solution, on which I actually have been working on last weekend. I just didn't find a lot of time to be looking into it during the week, it had been really busy.
I do like the GitHub idea for an open embroidery file repository. The downside would be the accessability for people who are not used to work with GitHub. Which means, we need an other way to gather the svg files. What I would have in mind is a platform to upload the files in a simple way (a file manager that I have been working on last weekend). It could be possible to push the uploaded files into a GitHub repository later and create a website where they are searchable and free to download (best and easiest option would be to offer everything with a public domain license). The website can either be created through GitHub (no comments possible, I am afraid) - or on the webspace where the files are being uploaded.
What do you think?

**Comment by MK-12-20MM** [comment]
> That is really a nice offer. Thank you for that. I hope you are not disappointed when I say, that I would really love an open platform. The uploads must be members only and svg files need sanitizing, but it would be great to have the files accessible for the public. If you don't mind, I really would like to offer an other solution, on which I actually have been working on last weekend. I just didn't find a lot of time to be looking into it during the week, it had been really busy.
> I do like the GitHub idea for an open embroidery file repository. The downside would be the accessability for people who are not used to work with GitHub. Which means, we need an other way to gather the svg files. What I would have in mind is a platform to upload the files in a simple way (a file manager that I have been working on last weekend). It could be possible to push the uploaded files into a GitHub repository later and create a website where they are searchable and free to download (best and easiest option would be to offer everything with a public domain license). The website can either be created through GitHub (no comments possible, I am afraid) - or on the webspace where the files are being uploaded.
> What do you think?

No I wouldn't be disappointed at all.  Most mainstream software hasn't got on board with uploading or dealing with SVG sanitization. Plus dealing with potential copyright issues could be a headache. 

What you indicate and working on sounds great. +10.  I think a gitpage (even though there are caveats) would be a great start. 

I wasn't thinking of anything Ink/stitch official.. I think my comment could of been better written or wasn't clear. My 1st thought would be if that aspect was true, what would happen if something happened, like dying. LOL. That would not be good. I would not want to host anything official.

Probably more along the lines to what I was thinking, supporting or referencing other sites here as **other resources** or user groups.  For instance there are various groups on facebook/Reddit. I think I have the 1st dedicated board (cough- whether it goes anywhere is another question... :) ).   

For example https://edutechwiki.unige.ch/en/InkStitch has links for support/user groups.  Could that be possible (inkstich.org) as other resources?  At the same time - it could be not worth the entanglement or hassle.  Probably would need some basic guidelines and disclaimers for site submission.

In any case, I am good,

- for all development/contributors - thanks for all the work. 

If you want some external testing with the repository (when your ready), hit me up..

**Comment by kaalleen** [comment]
Thanks for your support and ideas. inkstitch.org has a "Get Help" section (which links to the faq page) where you can find some links to external resources, such as the facebook groups: https://inkstitch.org/docs/faq/
If you know more resources that we should set links to, I will be pleased to add them in - or give you access to do it yourself, if you wish so.

I had no time yet for the embroidery file project. But it is still on my list ;)

**Comment by tyrosinase** [comment]
On 3/20/21 1:50 PM, Kaalleen wrote:
>
> Thanks for your support and ideas. inkstitch.org has a "Get Help" 
> section (which links to the faq page) where you can find some links to 
> external resources, such as the facebook groups: 
> https://inkstitch.org/docs/faq/ <https://inkstitch.org/docs/faq/>
> If you know more resources that we should set links to, I will be 
> pleased to add them in - or give you access to do it yourself, if you 
> wish so.
>
> I had no time yet for the embroidery file project. But it is still on 
> my list ;)
>

I have some pretty strong feelings about directing people to a Facebook 
group versus here.

(And not just because I still can't join it.)

**Comment by kaalleen** [comment]
I do not plan to create an embroidery file database anymore. This is mostly due to legal reasons (websites need an address etc.) and also for maintenance reasons. Still, I do love the idea and would be willing to help if somebody is picking up on this.

**Comment by lexelby** [comment]
I actually think thingiverse could be a decent choice.  I've seen things on there that aren't 3d print files.  I don't see a reason why we shouldn't upload embroidery files.

**Comment by lexelby** [comment]
I do agree that this is not something we should do officially as part of this project.  I'm gonna close this issue, but we can still use this as a comment thread if folks want to organize something.
