### ISSUE TITLE
big sur issue

### ISSUE THREAD

**Issue by rockypandor** [inkstitch/inkstitch#1021]
followed all instructions but i keep getting this message when trying to use params and really unsure what to do 
<img width="541" alt="Screenshot 2021-02-05 at 22 23 00" src="https://user-images.githubusercontent.com/78623774/107095669-203c2280-6801-11eb-9de5-1280d9fb87d8.png">

**Comment by kaalleen** [comment]
It's difficult to see the issue from your screenshot. Did you follow the additional steps for big sur?
https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

**Comment by dxh2389** [comment]
I am having the same issues. Is the command accurate on the additional steps section or do I need to edit it for it to work?
<img width="960" alt="Screen Shot 2021-02-12 at 1 41 37 AM" src="https://user-images.githubusercontent.com/78956149/107752793-12d8d980-6cd4-11eb-8e04-f457ff451131.png">

**Comment by kaalleen** [comment]
In rare cases you will need to edit the path. In your case it looks like it didn't take the whole path, but tried to split it up into pieces.

To the command: you always will have to write `xattr -r -d com.apple.quarantin ` followed by the path of your inkscape extensions folder. You can look it up in Inkscape > Preferences > System.

If you don't want to type in the hole path, click on open to open it with Finder. Move one folder up and drag and drop the extension folder into the command line. This will write out the path to the folder for you.

**Comment by dxh2389** [comment]
> In rare cases you will need to edit the path. In your case it looks like it didn't take the whole path, but tried to split it up into pieces.
> 
> To the command: you always will have to write `xattr -r -d com.apple.quarantine ` followed by a space and the path of your inkscape extensions folder. You can look it up in Inkscape > Preferences > System.
> 
> If you don't want to type in the hole path, click on open to open it with Finder. Move one folder up and drag and drop the extension folder into the command line. This will write out the path to the folder for you.

I copied the path of the folder and it still keeps splitting the path into two. Any other advice?

**Comment by dxh2389** [comment]
https://www.youtube.com/watch?v=LseVdw_9_Iw

Good things happen to those that wait here is the solution I guess. I had to copy both commands into the terminal just like this video and then the program started working
