### ISSUE TITLE
lib/gui/simulator apparently meant to also run stand-alone - but doesn't appear to work

### ISSUE THREAD

**Issue by incase** [inkstitch/inkstitch#1024]
My understanding of the inkstitch code base is very limited, but it appears that the simulator is meant to support running standalone as well:

`
if __name__ == "__main__":
    stitch_plan = stitch_plan_from_file(sys.argv[1])
    show_simulator(stitch_plan)
`

stitch_plan_from_file seems to read the stitch plan by using the pyembroidery read() function, which in turn would support basically any of the support import formats pyembroidery supports.

Would it be possible to provide a standalone version of the simulator GUI that takes any pyembroidery supported input format and simulates the stitches in it? It appears as if this should be possible, but I tried my best to achieve this and ended up with an import of the main inkstitch.py file, which broke this for me, as it would also try to read `sys.argv[1]` - but expect and SVG file there. My use case would be to look at the generated embroidery file to see the actions actually requested from the machine. For example, while the SVG might have cuts in it, the DST output format doesn't actually support them directly (some machines interpret multiple no-movement-jump-stitches as a cut though) - So seeing what is actually exported would be a useful debugging tool for embroidery issues.

**Comment by kaalleen** [comment]
Yes, it should be possible. Try if this is working for you in a terminal `PYTHONPATH=/usr/share/inkscape/extensions python -m lib.gui.simulator /path/to/embroidery_file.ext`
