### ISSUE TITLE
AutoFill: Add Separate Checkboxes for Tie In | Tie Out

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#1032]
I have somme dreams for Inkstitch. If it is possible!
In the params window possibility of choosing tie on the beginning and /or on the end of an object. Ties are useless for exemple on the beginning of an object with underpath.
The value of lenght of stitches are too small according to me. 1.5 mm for underpath is terrible if you have some thing to undo! Normal stitches on a running stitch  is for me 2.5mm
Underpath without any tie in the autofill of satin columns. It is really an useless   work to have to suppress them in each group of satin columns for exemple when creating letters for a font.
May be it will be possible to consider these idea!
I add the problem of fonts which have so narrow strokes that every body thinks the font does not work.
![largeurcol](https://user-images.githubusercontent.com/54963659/107853412-31df8480-6e16-11eb-9936-10dc2cdfea0b.jpg)

Thanks for all your work on Inkstitch

**Comment by kaalleen** [comment]
Just to confirm if I understood everything you asked for correctly

- [ ] AutoFill: set default stitch length (traversal between sections) from 1.5 to 2.5
- [ ] AutoFill: 2 checkboxes for ties: tie start | tie end
- [ ] AutoRoute Satin: disable ties for "AutoSatin Running Stitch"

> I add the problem of fonts which have so narrow strokes that every body thinks the font does not work.

This issue I have already worked on in the inkscape 1.0 branch. I hope it will lead to the desired result :)

**Comment by tyrosinase** [comment]
While you're adding checkboxes on satin: a checkbox for center-walk underlay only being one layer (i.e. "go to the other end of this column and start from there"). Or if you want to get fancy, a box like bean etc. have where you can say "center-walk 3 times" or "1 time" (current behavior being 2).

**Comment by lexelby** [comment]
I'd like to make sure we keep tie-ins enabled by default, even for auto satin.  Especially on a commercial multineedle, you have to tie in every time you start sewing after a color change or thread trim.  Otherwise, it's likely the thread will never catch and stitches won't be formed.  Then the machine halts because it thinks there's been a thread break.

**Comment by Augusa** [comment]
Do you think that all my letters will bring problems to commercial multineedle because they have no ties on the start? I am afraid! On other softwares I used it is always possible to choose how I want. May be the problem is that there is no way to choose default values?

**Comment by lexelby** [comment]
Having a way to choose default values would be a good idea, yes. :+1:

I only have experience with two machines that could trim the thread and then keep sewing: a Janome MC 400E and my commercial multineedle.  On both, if I didn't have tie in, the top thread might not catch the bobbin thread for quite a few stitches, like 10 or more.  Once it does, the first few stitches might be loose.

Is there a reason you want to avoid tie-in stitches?  I might be missing something, or maybe we're talking about different things?

**Comment by Augusa** [comment]
@kaalleen I confirm your propositions 

@lexelby I think the fewest stitches possible is always the best when I digitalize! I have only experience on my embroidery machine which does not cut thread and has only one needle! It works without any problem without tie on the beginning. The difficulty is that now a tie on the beginning is only possible with a tie on the end and ties in the middle of a group of satin columns are ugly. I always try to hide them at the end of the last object. I have prepared my fonts with only one tie at the end of each letter. Hope it will work for everybody. Otherwise, users will have to set params for their machines. Finally, it is not possible to find a universal solution. I had a look in Stich Era where you have to choose every params on each object. Satin columns and letters from the lettering are by default without anything. It was similar in older softwares I used. But of course, I don’t know what is the best solution. It was completely obvious for me but I am not at all a specialist! So, decide what you think to be the best.

**Comment by lexelby** [comment]
I think it makes sense to have separate options for tie in and tie out.  I also think it makes sense too have some kind of global configuration so that you can tap Ink/Stitch that you usually don't want tie-in on anything.

I do want to enable tie-in by default, though.  I think beginners would be confused if the thread did not catch at the start of sewing, if we didn't have tie-in stitches.

**Comment by Augusa** [comment]
I have learned completely alone and of course I started with running sitches without ties. It was not a long time before understanding the necessity of ties!

**Comment by kaalleen** [comment]
So we will aim to do these two things?!

- [ ] AutoFill: set default stitch length (traversal between sections) from 1.5 to 2.5
- [ ]  AutoFill: 2 checkboxes for ties: tie in | tie out (both enabled by default)

**Comment by lexelby** [comment]
The reason I set the default stitch length to 1.5 is that longer settings tend to cut the corners, sometimes even outside the shape.  It's a terrible solution to that problem, though.

**Comment by kaalleen** [comment]
Oh, heh, good to know. So this comes down two implement two checkboxes for the ties only.

**Comment by lexelby** [comment]
Yeah, and maybe fixing the code for the running stitch in autofill :)

**Comment by kaalleen** [comment]
Lockdown stitches select box has been added to params.

**Comment by tyrosinase** [comment]
Q: How do lockdown stitches affect imported designs? Like, if I open a PES that already has lockdown stitches built in, it comes in as manual stitch placement but does Ink/Stitch know enough to not add *more* lockdown?

**Comment by kaalleen** [comment]
Yes, no worries. Manual stitches are always excluded from lockdown stitches. This has not changed.
