### ISSUE TITLE
Fill: Shape is not valid. This can happen if the border crosses over itself.

### ISSUE THREAD

**Issue by ninjawarrior7** [inkstitch/inkstitch#1036]
Hi, 

I received this error, pls help. Thank you

path46: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.

**Comment by kaalleen** [comment]
You can try if the function Extensions > Ink/Stitch > Fill Tools > Break apart fill objects ... helps you to resolve the error.

This error will be shown if there are loops in your path. Sometimes the loops are very small and sometimes not even visible. You can run the troubleshoot extension to get a pointer to the troublesome node.
