### ISSUE TITLE
Path rendering blank

### ISSUE THREAD

**Issue by maskedman5** [inkstitch/inkstitch#1039]
Hi all,

I'm having an issue with a path that only renders the outline of the path but nothing inside. Its a sailboat so imagine the outline draws in the PES/Preview, but all the sails and things inside the design are absent. Oddly enough after making some random edits, it worked once, but then I scaled the design down to fit on a 3.94" hoop and its back to being blank. Any thoughts?

Original:
![image](https://user-images.githubusercontent.com/74874573/107969263-88b39e00-6f7d-11eb-8a63-55312044a139.png)

Output:

![image](https://user-images.githubusercontent.com/74874573/107969178-69b50c00-6f7d-11eb-9139-88cde65c116c.png)

Original SVG & PES Files here:
[Archive.zip](https://github.com/inkstitch/inkstitch/files/5982710/Archive.zip)

**Comment by tyrosinase** [comment]
It's trying to do a fill which really isn't going to work on something that size. If you turn off auto routing you'll get some of the interior bits which is probably still not what you want.

Try removing the fill, adding a dashed stroke, and see if that's closer to what you want.

Ideally what you *really* want is probably satin stitches, but that's not something that the automated process is going to get you. You'll need to either break up and re-combine all the appropriate line segments, or just manually trace things. I've got a little tutorial here that may help (specifically applying to alphabets/fonts, but the principle is the same): https://silverseams.com/2020/03/monogramming-without-a-font/

**Comment by maskedman5** [comment]
Thanks Tyrosinase! I broke it apart and it worked out. The mast really should be a satin, but it was passable as-is. Need to work up to the satins!

**Comment by kaalleen** [comment]
Since this is solved, I will close the issue. Please reopen if I have been too fast with this action.
