### ISSUE TITLE
Save embroider or save as

### ISSUE THREAD

**Issue by Sudu76** [inkstitch/inkstitch#1040]
Hi all,

I am having issue with saving the file. I am getting read-only files when I am saving in both the way (embroider or save as). I need PES or DST but can not get any of them. I use Mac Catalina. 

Also my preview will not show in original colours. (Black looks like Grey). 
Kind help appreciated.
Thanks

**Comment by kaalleen** [comment]
Huh, that is odd. Do I understand it correctly that the files you are saving through Inkscape are correctly saved but read-only?

About the colors there is to say, that DST doesn't save color information. Every time you open a dst file the colors will change randomly.

**Comment by kaalleen** [comment]
Not enough info
