### ISSUE TITLE
Params Not Working (Windows)

### ISSUE THREAD

**Issue by 3Adavis3** [inkstitch/inkstitch#1041]
I put a comment on another issue, but I think it was closed and I can't find it....

I click on Params and a dialogue box says it is opening it and then it closes the box and does nothing.  I looked on the website and it says that I should see this "Extensions > Ink/Stitch > Params" - I am attaching what I see because I do not show Params as an option in my  folders.  What am I missing?

![File View](https://user-images.githubusercontent.com/79180840/108149514-03290e80-70a1-11eb-9230-d43c955c05a0.jpg)

**Comment by kaalleen** [comment]
It's difficult to say. From your description I am not certain... when you open Inkscape, do you have the Ink/Stitch menu in your extensions? From what I can see in your installation path it looks ok so far and the menu should appear.

So I assume you have the menu and click on params and nothing happens?
Can you describe your exact steps what you did before you click on params?
Did you create a square or circle or some other object?

**Comment by 3Adavis3** [comment]
I shut my computer 100% down and restarted the program and it is working now.  Thank you.
