### ISSUE TITLE
Nothing is opening in Ink/Stitch for High Sierra

### ISSUE THREAD

**Issue by fugueink** [inkstitch/inkstitch#1043]
My apologies if this is the wrong place for this. I've never been able to figure out how GitHub works.

First, I wish to emphasize that I am only interested in converting embroidery files into SVGs. I am a hand-embroiderer.

I've just installed the Ink/Stitch for macOS High Sierra (inkstitch-v1.26.2-osx-high_sierra-x86_64-en_US, I am running macOS 10.13.6, which is the highest my hardware allows) into my Inkscape 1.0.1 extensions folder. The extension shows up in the menu in Inkscape.

I downloaded three free embroidery designs in three formats chosen at random (DST, EXP, PES). None of them will go into Inkscape. The first two shrink my Inkscape window, show me nothing in the drawing (I also can't resize the window), and the objects list shows that both the entire thing plus the colorblock it contains are visible. I've tried zooming both to the selection and the drawing, and I see nothing.

With PES, it's different. I get the following error:
![PES error window](https://user-images.githubusercontent.com/1401986/108212752-42387d80-70fc-11eb-8d5b-d3748e36b43c.png)

Am I doing something wrong? Is the software somehow to blame? Any help would be appreciated!

Thank you!

**Comment by kaalleen** [comment]
This is definitely the right place for your message and also definitely an error on our side. Thanks for reporting your issue.
I am not sure what is going wrong here though. We will need to have a closer look into it.

**Comment by fugueink** [comment]
Thanks for responding!

Is there anything else I can tell you that would help?

**Comment by kaalleen** [comment]
Actually yes :)
I am preparing an updated version for high sierra. I am very curious if it will be working for you without this issue.
When you are willing to try it out, I can lead you to the download.

**Comment by fugueink** [comment]
Sure, I'm willing!

I will warn you, though, that my computer is rapidly dying (it's twelve years old), so if it doesn't work, it may be me and not you. But certainly I'm willing to try.

**Comment by kaalleen** [comment]
Great. Here is the link: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-en_US.zip

**Comment by fugueink** [comment]
Unfortunately something is significantly wrong with my Inkscape. I don't know whether it's Inkscape or my rapidly dying computer or what.

I'll let you know if I get it working again, but I have my doubts. Unfortunately it looks like I may even be computerless for a bit.

I'll keep you posted. My apologies!

**Comment by kaalleen** [comment]
Ink/Stitch 2.0.0 comes with an update for High Sierra. This hopefully solves this issue. I'll close this issue now, but if this still pops up, please reopen and have us informed.
