### ISSUE TITLE
Inkstitch fails to open file, if the path contains sepcial characters

### ISSUE THREAD

**Issue by jos-webservices** [inkstitch/inkstitch#1044]
We just tried to open a file where the path included a german special character "ä". Inkstitch fails to load the file with below mentioned error. Renaming the folder path and removing the special character fixes the issue (as a workaround).

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 68: invalid continuation byte

**Comment by kaalleen** [comment]
Thanks for reporting this issue. Yes, Ink/Stitch is known to have it's issues with special characters like äüö, etc.
We hope these issues will be all gone soon. Until then you will have to avoid these characters.

**Comment by kaalleen** [comment]
I'll close this issue now, because it should be fixed with Ink/Stitch 2.0.0
Please reopen, if you are still having trouble,
