### ISSUE TITLE
Missing license text

### ISSUE THREAD

**Issue by donaldr3** [inkstitch/inkstitch#1047]
It looks like you've only got a licensing header in  inkstitch/LICENSE. The license header is an important part of licensing your work, but it should go at the top of your source files, not replace the actual license. Instead, /LICENSE should have the full text of the GPLv3. You can check out <https://www.gnu.org/licenses/gpl-howto.en.html> for more information on using GNU licenses.

**Comment by TechnologyClassroom** [comment]
I can help with this by making a PR if you would like.

**Comment by kaalleen** [comment]
That's a great offer. Thank you. We would like to receive your PR.
