### ISSUE TITLE
Inkstitch error when saving files

### ISSUE THREAD

**Issue by Tragland1** [inkstitch/inkstitch#1048]
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 514: invalid start byte

**Comment by kaalleen** [comment]
Are you on a older macOS version?

**Comment by kaalleen** [comment]
I am not sure, but is it possible you tried saving your file with a special character in its name? Or your path had a special character? Ink/Stitch is known to have it's issues with it.

**Comment by kaalleen** [comment]
This should be fixed in the upcoming version. Please reopen, if this problem still exists.
