### ISSUE TITLE
Underlay for Just Stroke Satin Stitching?

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#105]
I do have a work around for this, but I was thinking for ease of use, is there anyway to have the ability to assign underlay when doing the Stroke satin option?  Maybe allow for the same underlay tabs that we are able to use for ColumnSatin?

Unless I'm just missing it, if I am, I apologize.

**Comment by X3msnake** [comment]
You mean when you do a Satin with a single line but bigger line weight?

In my PC, if i draw a single 2mm thick line and go to params, Underlay tab show on windows, but it does not apply, only once you click on custom satin column and stroke again then it gets greyed out.

**Comment by lexelby** [comment]
I'm closing this now since we have Convert To Satin.  It's not perfect at converting everything, but it's quite good for most lines.
