### ISSUE TITLE
Feature request: Infill with adaptive angle

### ISSUE THREAD

**Issue by JakesWorkshop** [inkstitch/inkstitch#1050]
I am moving this here from the discussion section as it seems to be the more appropriate place. 

A feature I very much miss is creating a fill stitch with an adaptive angle like in the custom satin column.
Maybe it would be possible to create a new Type of stitch that combines the techniques used for fill stitch and satin stitch or expand the Satin column function with a few features?

The idea is to create a new object similar to the satin column or the filled area but with rungs to specify the angles and have it embroidered like the fill stitch with selectable running stitch length, spacing and staggering.
An option to offset every second or third row from the inner curve towards the middle would also be very handy to avoid too high density at the inner curve.

I hope this illustration shows what I mean a little bit better
![image](https://user-images.githubusercontent.com/76558525/108595604-17ab2680-7381-11eb-8e1c-98921a0944ef.png)
Here I roughly sketched out what I think the stitch path this function produces should be like. 

I'm looking forward to hear what you are thinking of this idea. I think it would be a great addition.

**Comment by Augusa** [comment]
I like very much this idea. It is really missing. Now you can get it manually. I explain my method (but in french) here : https://lyogau.over-blog.com/2020/05/remplissages-en-courbure-et-remplissages-textures-avec-inkstitch.html

**Comment by JakesWorkshop** [comment]
A big thanks to you @Augusa 
after reading your blog post I used a similar technique as a workaround to produce the staggered stiches, although it is very time consuming and not very accurate.
![image](https://user-images.githubusercontent.com/76558525/108624239-fd864c80-7443-11eb-9dc7-16e6ef9a690d.png)
As you described I created a satin stitch plan and then cut the path to create something roughly like the staggered effect.
![image](https://user-images.githubusercontent.com/76558525/108624269-36262600-7444-11eb-84c9-f8c704711532.png)
Maybe it would already be enough if such staggering is added to the satin feature?

**Comment by lexelby** [comment]
I would really love to have a radial fill option, either like you describe here or just as an option for fill stitch.

If you or anyone else are interested in coding this, by all means please do :)

**Comment by lexelby** [comment]
I think #2431 adds something very similar to what you're asking for here.  I'd love it if you gave it a test run!  You can find downloads for the development version here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-split-satin-stagger

**Comment by JakesWorkshop** [comment]
That looks a lot like what I needed! I will test it and give some feedback as soon as I can. Thank you for posting!

**Comment by kaalleen** [comment]
Closing. The next release (3.1.0) will add a stitch called S-Stitch (as mentioned above). This will do what was requested in here.
