### ISSUE TITLE
macOS build version error

### ISSUE THREAD

**Issue by kp1911** [inkstitch/inkstitch#1059]
Is anyone else facing this error? It's driving me crazy, I can't seem to make inkstitch work i've tried on 2 devices now :(

[3044] Error loading Python lib '/Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/.Python': dlopen: dlopen(/Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/.Python, 10): Symbol not found: _getentropy
  Referenced from: /Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/.Python

**Comment by kaalleen** [comment]
Which macOS version are you using? Is it possibly El Capitan?

**Comment by kp1911** [comment]
> Which macOS version are you using?

Hi there, yes I was but also tried on big sur and this is the error i'm getting:

/Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/inkstitch: /Users/xxx/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/inkstitch: cannot execute binary file

**Comment by kaalleen** [comment]
El Capitan will not be working. We have no release for it.

The big sur error is new to me. I don't know what the issue might be. Could you describe all your steps for the installation so far?

**Comment by kaalleen** [comment]
There is a new Ink/Stitch version out there, even a release for el capitan.
Since this refers to an older version of Ink/Stitch I am going to close this issue. Please reopen, if you are still having trouble with the new version.
