### ISSUE TITLE
E Stitch Option?

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#106]
I got to thinking, especially since we were talking about the bean/backstitch run stitch type at one point, what about an option for the E stitch?

I know I use this a lot for baby clothes appliqué designs.

If we aren't able to implement this, I do know of a way around it, I was just curious if it's something that we could do.

**Comment by X3msnake** [comment]
Sorry for my ignorance, but what is a E Stitch?

**Comment by wwderw** [comment]
> Sorry for my ignorance, but what is a E Stitch?

It's a run stitch type that looks like this:

**Comment by wwderw** [comment]
> Sorry for my ignorance, but what is a E Stitch?

It's a run stitch type that looks like this:

![e stitch](https://user-images.githubusercontent.com/24878362/36709412-573d7f68-1b3d-11e8-9f96-556d7fa9966c.PNG)

It's biggest purpose is for a simple (and yet deceivingly strong) cover stitch for applique items.  Mainly for baby cloths as their skin tends to be more sensitive (on average) when something is stitch heavy.  

Unless you use a "cover" after embroidery (usually heat pressed) to help soften everything.

**Comment by lexelby** [comment]
Yup, can do.  The stitch pattern looks pretty simple.

**Comment by wwderw** [comment]
[estitch.zip](https://github.com/lexelby/inkstitch/files/1761146/estitch.zip)

Here is an example.

Maybe have (in this example the stitching that is going up and down) change length due to width of the stroke or have it as an option in params if that would be too confusing with the Stroke satin needs.  Thoughts?

**Comment by kaalleen** [comment]
Closing this, because we already got this feature. Please reopen if needed.
