### ISSUE TITLE
Apply and Quit Not Working

### ISSUE THREAD

**Issue by embroiderforsons** [inkstitch/inkstitch#1060]
I have installed Inkscape and Institch on two different computers, a Surface Pro 4 and an HP Pavilion and have the same problem. In the Lettering Module when I click "Apply and Quit" the text is not generated in Inkscape. Also, it takes up to two or more minutes for the stitch out of the text to appear.  I have uninstalled and reinstalled several times and have the same issue.

**Comment by MK-12-20MM** [comment]
I am just a user - FYI 

Lettering is placed at the top of document area. If you are zoomed out it might be hard to see. To check and see if its been created open the objects panel and you should see and object with "Ink/Stitch Lettering" just select that that that object should be highlighted. 

![test](https://user-images.githubusercontent.com/10312448/109419524-81d05680-7993-11eb-980c-6823c8565af3.PNG)


Can't help you with performance but I know that on one of my (windows) laptops with avg requirements running inkscape can be a tad sluggish. 

Not sure if there any minimum recommended requirements when using the extension. In any case processor and ram - and even performance settings (Power) in windows will impact application response, in my experience with inkscape.

**Comment by embroiderforsons** [comment]
Thank you so much. Your solution works!!!
