### ISSUE TITLE
permission denied embroidery

### ISSUE THREAD

**Issue by v39mwrld** [inkstitch/inkstitch#1062]
hey guys, I'm using ink stitch on Mac OS Catalina and I've had it work before. now recently anytime I'm done a project and want to use the embroidery extension under ink stitch to finish the project, I get a permission denied message. I havent been able to figure it out. thanks!

**Comment by v39mwrld** [comment]
I even uninstalled and reinstalled all the software and extensions.

**Comment by kaalleen** [comment]
Are you using the embroider function included in the Ink/Stitch menu? Try to use `File > Save a copy ...` instead
It is reported to have less errors.
