### ISSUE TITLE
Offset Fill Stitch

### ISSUE THREAD

**Issue by X3msnake** [inkstitch/inkstitch#107]
Since we have the freedom to think outside the box

Here is a sugestion, implement a algorithm similar to the one used in cnc machining for offset pockets, and use it for a offset stitiching.

![image](https://user-images.githubusercontent.com/11083514/36731025-5521b198-1bc1-11e8-94bb-57fed03fb8fb.png)

Here's a paper i found about the kind of algorithm involved
https://seant23.files.wordpress.com/2010/11/anoffsetalgorithm.pdf

@lexelby do you think it would be doable?
@wwderw do you know if any comercial software has such feature. do you think this would be interesting to have?

**Comment by lexelby** [comment]
Sure, it's doable.  However, I don't think we need to implement this in inkstitch at all.  Inkscape comes with an extension, gcodetools, that does this with the press of a button.  You could take the results from gcodetools and turn them into running stitch using inkstitch's Params extension.  No need for special code in inkstitch :)

This really highlights what it's so cool that inkstitch is an extension for inkscape.  We get all of the awesome functionality of inkscape and its extensions for free.

**Comment by wwderw** [comment]
The offsets (and insets) that I'm used to (and the ones that I know exist in embroidery software, there may be others, I've got some software that even after yrs of use, I still barely scratch the surface) are more like your contour dockers or dynamic/linked offsets etc.

**Comment by X3msnake** [comment]
@lexelby 

I Say use it as an extension since that way we could take advantage of the carfull spreading of the stitching like the one on the fill

----*----*----*----*----
--*----*----*----*----*-
*----*----*----*----*---

And allow to use underlay (the standart way) and allow the user to just have the design outlines like it currently happens for fill...
