### ISSUE TITLE
Inkstitch acts like it's installed but is not working?

### ISSUE THREAD

**Issue by vrchimp** [inkstitch/inkstitch#1091]
Hi,

Inkstitch appears in the extensions menu and acts like it's installed however when I attempt to change the palette no options for sewing machines and stuff appear, I also cannot change a shape into a param as I am trying to follow the youtube tutorial. When I select param it says it will do it but nothing pops up afterwards. Help is appreciated thank you!

**Comment by MK-12-20MM** [comment]
Hi @vrchimp 

Just FYI - I am Inkstitch user and not a dev.

Don't know if you ran the command - Inkstitch -> Install add-ons for Inkscape.  This will install Manufacturer Thread palettes so the palettes can be utilized in Inkscape. 

If you already have completed this action, then you may have a different issue. 

Your second issue. Not sure on that one. You might want to let the parms dialog run a bit or give it some time. Are your menu items greyed out? Doesn't sound the case.  In a nut-shell you might have to provide a little more information or specifics on your second issue. Also a thought, you might want to indicate what operating system you are using.  This will help narrow things down. Hopefully this helps.

**Comment by kaalleen** [comment]
No further feedback. I'll close this issue now. Please reopen if you are still having issues with the installation.
