### ISSUE TITLE
Problem syncronising the stitches to the needle cycle

### ISSUE THREAD

**Issue by skinnybottom** [inkstitch/inkstitch#1094]
Hi
Great project and fantastic design, thanks for sharing.  I have built one and it almost works, but am having trouble synchronizing the stitches to the needle cycle.  Can you suggest a simple way to do this.  My maths is rubbish so there is no hope of me calculating it properly.
Thanks
Aaron

**Comment by lexelby** [comment]
I'm not sure since I've never made one, but I think people often use switches for this.  When the needle hits a certain part of its cycle, it bumps a switch that tells the arduino that it's time to move the hoop.  Standard cnc machine limit switches would probably work nicely for this.
