### ISSUE TITLE
Extend options for multiple underlay fill

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#110]
Ability to use 2 layers of underlay (either with their own stitch angle) for fill objects.

Help with the ability to do "knockdown" stitches for items with a lot of pile such as towels.

**Comment by lexelby** [comment]
Thinking on this, we could take it up to another level.  What if you could specify a number of passes of underlay?  I'm thinking the options would be "passes" and "angle between passes".

For example, say you set passes to 3, fill underlay angle to 70, and angle between passes to 30.  You would get one later of underlay at 70 degrees, then one at 100 degrees, and finally one at 130 degrees.

We could get even more ambitious and offer the same options for the top stitching.  Obviously this would make it quite easy to create a bullet proof patch, so the designer would need to keep density in mind -- but of course they should be doing that anyway. :)

The coding effort for two layers of underlay versus X passes each separated by a set angle is about the same.

**Comment by wwderw** [comment]
What about also adding in their own offset amount as well for each pass?  That way the first 2 could be the contour (neg inset) and the 3rd could just be a regular underlay?

**Comment by kaalleen** [comment]
Just an update for this issue:
Multiple underlay will be possible with the next release.
Only possibly setting will be the stitch angle. This has to be extended with the new UI
