### ISSUE TITLE
Issue with Colors on PES Export

### ISSUE THREAD

**Issue by maskedman5** [inkstitch/inkstitch#1105]
I sometimes feel like InkStitch is losing its mind with colors. Often, my resulting stitch file will have the totally wrong colors compared to what I selected in InkScape - and it seems to have a mind of its own: for example I just had a very simple 3 color design where all the colors were outputting perfect - I changed the stroke color of two inkstitch lettering objects, and now a bunch of other objects have been switched to silver applique on the output file (but are correct in InkScape). In other instances, I have managed correct the issue by manually changing an objects color to something else and back again, or even re-arranging the order of objects, but this doesn't always work. Is there a bug around this entered and/or a workaround? 

In the attached, for example, if I remove any of the flag, pole or burgee groups of objects, the colors render fine to PES (the error appears to occur with other file formats as well). But if all three, the colors are incorrect. I have attached screenshots and the source files. 

Original in InkScape
<img width="1152" alt="Screen Shot 2021-03-26 at 1 38 45 PM" src="https://user-images.githubusercontent.com/74874573/112671628-cf2bd080-8e38-11eb-93de-fb7db00a30f7.png">

Resulting PES File
<img width="1179" alt="Screen Shot 2021-03-26 at 1 38 52 PM" src="https://user-images.githubusercontent.com/74874573/112671630-cfc46700-8e38-11eb-8a9e-80f674f3091f.png">

Original Source Files:

[Archive.zip](https://github.com/inkstitch/inkstitch/files/6213470/Archive.zip)

**Comment by tyrosinase** [comment]
On 3/26/21 1:42 PM, maskedman5 wrote:
>
> I sometimes feel like InkStitch is losing its mind with colors. Often, 
> my resulting stitch file will have the totally wrong colors compared 
> to what I selected in InkScape - and it seems to have a mind of its 
> own: for example I just had a very simple 3 color design where all the 
> colors were outputting perfect - I changed the stroke color of two 
> inkstitch lettering objects, and now a bunch of other objects have 
> been switched to silver applique on the output file (but are correct 
> in InkScape). In other instances, I have managed correct the issue by 
> manually changing an objects color to something else and back again, 
> or even re-arranging the order of objects, but this doesn't always 
> work. Is there a bug around this entered and/or a workaround? I can 
> share a file if it's helpful.
>
> In the attached, for example, if I remove any of the flag, pole or 
> burgee groups of objects, the colors render fine to PES (the error 
> appears to occur with other file formats as well). But if all three, 
> the colors are incorrect. I have attached screenshots and the source 
> files.
>

It looks fine on my machine (with a mostly-Sulky palette loaded) but I 
haven't put it in the actual machine. I've noticed that the Brothers 
seem to have a few "special" colors that show up as wacky things - I 
have a pink that always comes up with a little scissors logo (what I'd 
take to be an "engage the overlocker seam trimmer" command which is 
certainly not a thing the PE800 does), and I can't remember what colors 
call up a couple of different fancy zigzag seam types (again, the PE800 
is not a combo machine but apparently it shares some firmware bits). Is 
that the sort of thing you're seeing?

It still stitches out normally, though I maybe should start documenting 
the exact colors that trigger these so the devs can code around it in 
case combo or commercial machines do treat it differently.

**Comment by maskedman5** [comment]
So in the images above, if I hide/delete the triangular flag on the right side, all the colors in the blue flag are correct. In another version, I added a gold #214 border to the file - when I have that gold just with the triangular flag on the right, I get the scissors icon, but when I hide the triangular piece and just do the external box with the blue flag, it just comes up as the correct color 214. See below for two files that have the same external box in color 214, but depending on what other objects are included, the machine shows it as a normal color or a special scissors icon. 


![IMG_4197](https://user-images.githubusercontent.com/74874573/112896305-3c936780-90ac-11eb-8947-eb2c96b0dc38.jpg)
![IMG_4198](https://user-images.githubusercontent.com/74874573/112896444-66e52500-90ac-11eb-992d-fef76479fbfb.jpg)

**Comment by tyrosinase** [comment]
Oh hey, you know what? Try ungrouping everything. Ink/Stitch sometimes loses its mind on groups of different-colored objects (really I think it's Inkscape itself; copying a group and then doing a "paste special" will choose attributes based on the group(?) and none of its components, even on a group of same-colored items). I bet that's what's going on.

(This thought brought to you by the absolute rainbow of colors chosen on a single-layer PES where I grouped something and copied it, something I almost never do. Normally I color-group on layers.)

**Comment by maskedman5** [comment]
That didn't seem to help. BTW, when ungrouping things or moving layers into a group, the scale & rotation properties of the group are applied to the layer moved in or out. Is there a way to see those properties outside the XML and/or a way to change this behavior? Know thats an InkScape question but can't find a good answer....

With respect to this defect, I think there is absolutely a problem with the Deep Gold color #214 in the Brother Embroidery palette (color code: e8a900/1) - as changing that color fixes the problem shown above. Can anyone else replicate this issue and/or look at the code in Inkscape for the defect? It seems to export that color as "appliqué"

**Comment by lexelby** [comment]
I have a couple theories about what's going on here.

First of all, I don't know of any outright bugs along these lines, but I definitely would not rule that out.  Anyway, on to the theories.

As I think you both know, PES files have a limited palette of colors.  Basically, there's a set PES color palette, and it's fairly limited.  Ink/Stitch doesn't get to encode an RGB color directly, it has to pick the closest color from the palette and encode that color's number in the file.

Ink/Stitch does its best to match the colors in your SVG to the PES color palette.  Theory 1: that color matching code may not be very good.

Things get complicated if you have to colors that are close but not exactly the same (example: 255,0,0 vs 254,0,0 -- two nearly indistinguishable reds).  Ink/Stitch assumes that if you use those to different reds, you really do intend to trigger a color change.  It encodes the first object as red in the PES file.  But after that, it marks red as "used" and avoids using it again.  It will choose the next closest red from the PES palette for the next object, and that may well be quite different.  Theory 2: you might have very slight color variations that are forcing Ink/Stitch to choose suboptimal PES colors.

As to the scissor and applique thing, it sounds like certain PES colors are "special" and have different meanings, as @tyrosinase was saying.  We should figure out which ones and make Ink/Stitch avoid using them.

**Comment by lexelby** [comment]
Aaand I found a bug in Ink/Stitch!

Let's say you have three objects, in order: one red, one yellow, and then another red.  The two reds are identical so they should get to use the same color from the PES thread palette...

Except they don't get to.  Ink/Stitch forces the second one to be different.

Maybe that's part of the problem you're seeing?

**Comment by tyrosinase** [comment]
On 3/31/21 7:11 PM, Lex Neva wrote:
>
> Aaand I found a bug in Ink/Stitch!
>
> Let's say you have three objects, in order: one red, one yellow, and 
> then another red. The two reds are identical so they should get to use 
> the same color from the PES thread palette...
>
> Except they don't get to. Ink/Stitch forces the second one to be 
> different.
>
> Maybe that's part of the problem you're seeing?
>

I was about to say: hooboy yeah I have definitely exercised this bug 
today. I have a thing I'm doing that is a tackdown stitch in blue, and 
then five more stitches alternating red/green. And I had a bunch of them 
to do, so I grouped twelve of them in a 5x7 hoop, and as I mentioned 
earlier the colors just went wild. Clearly the thing was trying to do 72 
different colors, and it ran out: as I'm puttering along doing it I 
realize my screen is showing 65 color changes and I just assumed there 
were five colors per object so I'm thinking "huh, I must have had five 
stray objects, that's weird, I'll have to watch for duplicates." And it 
choked on the last object: the last few colors were the various zigzag 
stitches and trims, and it actually showed the final object on the 
preview screen, but it wouldn't stitch it out. (Despite yes, stitching 
68 of 65 colors...)

Some of that is clearly Brother firmware and/or PES format quirk, but 
definitely it wasn't happy about the multiple colors. (The PDF correctly 
says there are only three thread colors, FWIW.) And apparently I've 
never run into this color-changes limit before, despite the weird way I 
use an embroidery machine.

**Comment by lexelby** [comment]
Hah, wow!  Yup, that'll do it.  Thanks for confirming this bug :)

**Comment by maskedman5** [comment]
> I have a couple theories about what's going on here.
> 
> First of all, I don't know of any outright bugs along these lines, but I definitely would not rule that out. Anyway, on to the theories.
> 
> As I think you both know, PES files have a limited palette of colors. Basically, there's a set PES color palette, and it's fairly limited. Ink/Stitch doesn't get to encode an RGB color directly, it has to pick the closest color from the palette and encode that color's number in the file.
> 
> Ink/Stitch does its best to match the colors in your SVG to the PES color palette. Theory 1: that color matching code may not be very good.
> 
> Things get complicated if you have to colors that are close but not exactly the same (example: 255,0,0 vs 254,0,0 -- two nearly indistinguishable reds). Ink/Stitch assumes that if you use those to different reds, you really do intend to trigger a color change. It encodes the first object as red in the PES file. But after that, it marks red as "used" and avoids using it again. It will choose the next closest red from the PES palette for the next object, and that may well be quite different. Theory 2: you might have very slight color variations that are forcing Ink/Stitch to choose suboptimal PES colors.
> 
> As to the scissor and applique thing, it sounds like certain PES colors are "special" and have different meanings, as @tyrosinase was saying. We should figure out which ones and make Ink/Stitch avoid using them.

**Comment by maskedman5** [comment]
Thanks all. I think we are on to something here. Really appreciate everyone's help, and even more appreciative to whomever eventually tracks down this bug and fixes it!

BTW, two comments to the above posts, for what its worth:

-With respect to two similar colors, this bug occurs sometimes when items are the EXACT same color, so not sure thats the issue, but maybe in the underlying code who knows

-With respect to the Brother firmware or PES glitch above, I validate my files in a PES viewer called Stitch Buddy before sending to the machine. I have seen both parts of this issues (both colors being totally messed up AND that certain colors are marked appliqué) in BOTH stitch buddy AND on the Brother machine, leading further credence that something is up with the output file for InkStitch.

**Comment by tyrosinase** [comment]
On 4/2/21 11:44 AM, maskedman5 wrote:
>
> -With respect to two similar colors, this bug occurs sometimes when 
> items are the EXACT same color, so not sure thats the issue, but maybe 
> in the underlying code who knows
>
Yeah, the 12-up file I had so much fun with had only three colors, and 
the PDF generator correctly recognized it as 72(!) color changes between 
three colors. The PES file... not so much. Not sure if that means the 
bug is only in PES generation or what, but certainly *parts* of 
Ink/Stitch are recognizing that the colors are the same.

**Comment by Grzy7316** [comment]
I am also running into issues with colors when exporting to PES - I had oinly 6 colors  in the SVG , but when attempting to export to pes, it wound up having each section as a different color

**Comment by tyrosinase** [comment]
I'm wondering what's triggering this, because it doesn't *always* happen (I think; maybe sometimes it's just getting closer than others and I haven't noticed because I've been using mine in "CNC sewing" mode more than "like a normal person embroiders" mode lately, and the colors don't really matter in the former).

My problem designs lately seem have had that one yellow in them, the one that shows up as a trim of some sort on the screen, but I'll have to see if that's actually a pattern or if I just happen to be choosing that yellow a lot.

(On that note, I also need to finish my "document all the special-function colors in PES" project.)

**Comment by kaalleen** [comment]
Closing in favor of #2668
