### ISSUE TITLE
Renaming menu entries

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1109]
![image](https://user-images.githubusercontent.com/63351363/112956238-89288280-9140-11eb-915d-203ced8989b0.png)

1) You should know that it is not possible to organize the menus. They are sorted alphabetically and this is different from language to language. The only solution would be to add a letter common to all languages ​​in front of the text 

For example :
A - Params
B - Satins Tools
.....
Y - Preferences
Z - About

But this is not very conventional. I think it is better to wait for a possible evolution of Inkscape on this subject. 
Otherwise it would have been very nice to have the most used tools at the start of the menu. I don't know...

2) About "Import Thredlist" and "Install thread color..", shouldn't a "Color thread management" (or other name) menu be created?

3) About "Reorder", don't you want to rename it to something more understandable and to avoid giving false hope to users (who thinks it re-stack objects in a smart way so that there are less stitch jumps). My idea would be something like "Re-stack objects in order of selection" (or other name). And maybe put that in an "Edit" menu. I am sure that one day there will be new help tools ;-)

4) Could we rename "Font tools" ? I'm afraid the beginner will try to go to this menu to do a text embroidery. This menu is more intended for the creator of a new font. Maybe we could call it: Font administration or New font management. I don't know the right words in English ...

Thank you for your attention :-)

**Comment by kaalleen** [comment]
@lexelby what do you think?

**Comment by lexelby** [comment]
I agree, it would be nice if we could reorder menus!  And I like the ideas in 2-4.
