### ISSUE TITLE
Thoughts about inkstitch (buildroot)

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#111]
* How can we optimize it (building)?
  * Docker (linux-x32, linux-x64 and macOS)?
  * Appveyor (Windows x32 Windows x64)?

* build and distribute the finished packages: deb, rpm, dmg, msi / nsis ?
  * serving (separate) dependencies like libembroidery (python) for all systems
(see shapely-win-package)
  * Installation via a repository (shapely-win-package):
    -> so we can use pre/post and install/update scriptlets (some systems)
    -> ship system depended requirements (ourselves)

It would take a lot of work in the background, but it would be worth for everyone!

My opinion is that we should switch from static build to more dynamic build.
Does anyone have other or better thoughts?
Best regards,
AkiraNorthstar

EDIT: added / rewrite, so it should be clearer what i mean (i hope...)

**Comment by wwderw** [comment]
My biggest thing is portability.

When running Inkscape in my Windows VMs, I use the binary archive.  On Linux I use AppImage.

I just bundle in the desired version of Inkstitch that I want within that portable instance of Inkscape.

This gives me the greatest flexibility from one system to another.

All of my production software is never installed via the repos (Inkscape, Krita, Synfig (and their extensions/plugins) are all AppImages and I use a run file for virtualbox for VMs).

I personally would rather a bigger self contained file, then have to worry about dependency issues.

I'm probably odd man out on that, I just place a very high value on portability.

**Comment by X3msnake** [comment]
My view is the same as @wwderw 

The easier it is to install the better. but as we currently are download unzip drag&drop anyone can do.

@AkiraNorthstar

- I don't know enough to understand the differences advantages or disavantages between static and dynamic, can you point me in the right direction to understand it better?
- How much time would this consume 
- What are the advantages it can bring.
- Does it allow for better development and faster implementation? less bugs?

**Comment by wwderw** [comment]
One other thing thing that I wanted to add too, this is easier and "safer" for people to experiment with development builds and/or get the latest and greatest.

Repos tend to freeze at a certain point that have to wait until the next OS version to get a newer version.  Or go the compiling route, which some do, I don't tend to because I don't like unnecessary packages on my system.

As far as testing goes, it's easy to drag and drop, test, and then reload the stable version back into it.

I'm not opposed to adding options, I would just really not want to lose the portability aspect of it.  That is perhaps the biggest draw (at least for me) to this extension that there is.

**Comment by AkiraNorthstar** [comment]
I've got forgotten to say: it is only for the "buildroot".
So the we compile every time all the same things, it make none sense to build all the stuff again, and again, if a line has changed in inkstitch... This thoughts are not for the end product.

**Comment by wwderw** [comment]
> So the we compile every time all the same things, it make none sense to build all the stuff again, and again, if a line has changed in inkstitch... This thoughts are not for the end product.

I hate being coding ignorant.  I'm sorry about that.

I would say do whatever is the most efficient to make the building easier if it results in the same end product.  

If the front end work is worth it on the back end and someone is willing/able to do it, I would say go for it.  The more efficient something is typically the better and if this helps get versions out quicker, I'm all for it.

**Comment by AkiraNorthstar** [comment]
@X3msnake: 
Static build (short): you can compile all needed things in one binary if you wish....
Dynamic build: only compile "the function" of a library in the binary, but you have install the used library(ies) within the binary.

Better explainations:
[Static build / dynamic linking](https://en.wikipedia.org/wiki/Static_build)

**Comment by AkiraNorthstar** [comment]
@X3msnake:

> How much time would this consume
actually: [Build](https://travis-ci.org/lexelby/inkstitch/builds/346891068?utm_source=github_status&utm_medium=notification) with one change in code!

What are the advantages it can bring / Does it allow for better development and faster implementation? 
Faster builds....

**Comment by X3msnake** [comment]
@AkiraNorthstar 

I make @wwderw words my own

> if someone is willing/able to do it, I would say go for it. The more efficient something is typically the better and if this helps get versions out quicker, I'm all for it.

**Comment by AkiraNorthstar** [comment]
Closed - other optimizations to Ink/Stitch have made this conversation superfluous.
