### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by embroiderforsons** [inkstitch/inkstitch#1118]
Does Inkstitch work with the fonts that appear in my drop down list? Can they be digitized, and saved to vp3.

**Comment by LaureFR38** [comment]
If you want to embroider text you have to use this menu :
![image](https://user-images.githubusercontent.com/63351363/113472176-8dff7600-9461-11eb-90ac-3852d1095e0e.png)

And you will be able to use only the fonts present in this menu :
![image](https://user-images.githubusercontent.com/63351363/113472191-b2f3e900-9461-11eb-9a35-0f6f4d7f3a82.png)

If you want more police, you have to create the police yourself by following a specific protocol. Each letter must be transformed into a satin column. A team of enthusiasts are working a lot to add new fonts (the ones you see on my print screen)

**Comment by lexelby** [comment]
I think the French word for "font" gets translated as "police"...

**Comment by LaureFR38** [comment]
> I think the French word for "font" gets translated as "police"...

That's right. But I have the English version installed. It's better to make screen prints that you understand 😛

**Comment by embroiderforsons** [comment]
These are the only fonts I see. How do I get the ones you have?
![16174607455581476050186646156296](https://user-images.githubusercontent.com/79768771/113481664-c2c2fb80-9468-11eb-9519-4eebfd96982b.jpg)
Tbese

**Comment by embroiderforsons** [comment]
Also, you have four things I do not have in my Extensions. How do I get 1) Font Tools 2) Install thread color Palette, 3) Preferences and 4) Reorder?

**Comment by embroiderforsons** [comment]
I am trying to manipulate the Inkstitch Lettering like the Inkscape text on the right. Can this be done with Inkstitch? Since I will be embroidering the decal I am digitizing.
![16174620289304176580557552506667](https://user-images.githubusercontent.com/79768771/113482251-bbe9b800-946b-11eb-87e9-e717837c55b7.jpg)

**Comment by embroiderforsons** [comment]
Ok, I found a video that shows a Text menu and it seems to work with Put Text on Path. I got to the Text menu by entering shift+control+t.

**Comment by embroiderforsons** [comment]
Sorry for all of the inquiries, I am learning this application bit by bit. Please look at my photos and if you can helo, how do I get Inkstitch to stop after putting those tiny threads between each letter? Is this some kind of param command? Thank you.
![20210403_210209](https://user-images.githubusercontent.com/79768771/113495500-380deb00-94c0-11eb-959e-70dfa74225a7.jpg)
![20210403_210209](https://user-images.githubusercontent.com/79768771/113495508-45c37080-94c0-11eb-99cb-fa1b01f5547c.jpg)

**Comment by tyrosinase** [comment]
On 4/3/21 9:05 PM, embroiderforsons wrote:
>
> Sorry for all of the inquiries, I am learning this application bit by 
> bit. Please look at my photos and if you can helo, how do I get 
> Inkstitch to stop after putting those tiny threads between each 
> letter? Is this some kind of param command? Thank you.
>
`Extensions > Ink/Stitch > Commands > Attach Commands to Selected 
Objects` and then choose the Trim Thread command.

Your format and machine have to support thread trims though; my Brother 
PE800 doesn't, for instance. If I want it to do a trim I have to make 
each letter a different color. Alternately, you can change up the order 
of the letter stitching so that it gives you longer jump threads that 
are easier to get a hold of to manually cut (just make sure you're not 
stitching over those long jumps). In both cases it's going to do a 
tackdown on either end of that jump, which may or may not affect how 
those letters look.

**Comment by lexelby** [comment]
The lettering extension also has an option to add trims between each letter.

**Comment by kaalleen** [comment]
> Also, you have four things I do not have in my Extensions. How do I get 1) Font Tools 2) Install thread color Palette, 3) Preferences and 4) Reorder?

These are all features of the new upcoming version, it will be out there soon.

**Comment by B-ellanna** [comment]
https://github.com/embroiderforsons New version is out. You can now enjoy our work on the pre-digitized fonts :).
