### ISSUE TITLE
Random error : "Satin column: A rung doesn't intersect both rails."

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1120]
When the rung isn't sticking out of the rails but they're just sitting on it, inkstitch doesn't seem to like it. It detects this in random error. 
Can we do something? I am bored because the French team which has just added a lot of new fonts did not overflow the rungs enough and we have this kind of error randomly. They'll go crazy if they have to correct every rail of every letter.

You will find a file which allows to highlight the error and a video which shows the behavior with me (watch the video first) :

[rungOnRail.zip](https://github.com/inkstitch/inkstitch/files/6252137/rungOnRail.zip)

**Comment by lexelby** [comment]
I've thought about having Ink/Stitch extend the rungs a little bit and figure out where they should intersect, if one or two don't quite intersect.  @kaalleen what do you think?

**Comment by kaalleen** [comment]
It's worth a try. I don't know how time consuming this would be.

**Comment by LaureFR38** [comment]
@lexelby  it's weird, the satin column in the lettering preview works. In Params and Simulator it doesn't work. And it's even stranger,  by copying the element for example 5 times, in the batch there will be at least 1 element for exemple which works, so sometimes inkstitch behaves well while the rung is always the same. Wouldn't there be rounding or something else?

**Comment by lexelby** [comment]
Yes, this is definitely caused by rounding issues.

I do like the idea of having Ink/Stitch extend the rungs a little.  But @kaalleen is right, that will take some time to implement.

For now, we can probably fix the font SVGs myself with a little Python script, or someone else if they get to it first.  @LaureFR38 which fonts have this problem?

**Comment by LaureFR38** [comment]
Unfortunately, I don't know how to answer. It depends on the mood of the designer and if he had put on his glasses or not the day he made a few characters ....
