### ISSUE TITLE
Auto-Route Satin Starting Point Command Is Not Deleted

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1122]
There are reports, that auto-route starting points are not deleted after auto-route has been executed.
I cannot reproduce this by myself at the moment. Need to investigate.

**Comment by LaureFR38** [comment]
Just the group that contained the command marker and the connector (which they are well deleted)

**Comment by lexelby** [comment]
Ah!  I think I've seen that before.
