### ISSUE TITLE
Ideas for Transfer params

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1123]
"This function transfers Ink/Stitch parameters from the first selected element to the rest of the selection. Please select at least two elements."

1)  If I have 10 elements for which I want to set the parameters of another element (the master), I must select the master then the 10 others one by one, I cannot make a selection frame. Whereas if I selected my 10 elements with a selection frame and lastly the master, it would be more practical.
Should it be :
This function transfers Ink/Stitch parameters from the LATEST selected element to the rest of the selection. Please select at least two elements.

2) Should this function be with "Remove embroidery settings" and be called "Copy embroidery settings" ? But I don't know which menu.

Thank you for your attention

**Comment by kaalleen** [comment]
Actually you can use box select either way. Doesn't matter if copy from derives from the frist or lasst object. Try it out, it really doesn't matter.

I first named it copy params. I like to name it params because of the prams dialog is named params too. I changed it to transfer, because keyboard shortcut codes with c are all taken. So a shortcut with t is still available and naming it transfer will make it easier to remember.

**Comment by lexelby** [comment]
I wonder if it would be useful to have "copy Params" and "paste Params" extensions...

**Comment by LaureFR38** [comment]
@kaalleen Sorry that's right I can use the shift key while I make a selection frame. I had forgotten.

@lexelby Transfer makes a copy then paste. Maybe keeping just copy and paste instead of transfer is more of a standard logic than transfer ... It could make an "Edit" menu with copy, paste and delete.
Taking the example of Inkscape, there is also a duplicate (copy then paste) so can be called transfer in duplicate? (Ctrl+Shift+D is  maybe free...)
I don't know what makes the most sense for users to immediately understand their use.

**Comment by lexelby** [comment]
> I don't know in English but in French the notion of transfer has more the meaning of taking the parameters in one place and moving them to another.

Yeah, the implication in English is very similar.
