### ISSUE TITLE
Path for "Install thread color palettes for Inkscape"

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1124]
I do not see the full path in 2. When I click on 2, window 1 does not open the place of 2. So in the end if I click on Install, I do not know where it will go ... (Me yes but shhh)

![image](https://user-images.githubusercontent.com/63351363/113507832-0abb4e80-954d-11eb-931e-bbc7ade36b2d.png)

1) Can you make more text appear in the path?

2) Can you make it so that when the window opens it shows the path location?

3) For inexperienced users, add a "default" somewhere so that he doesn't have to ask himself the question
 and you just have to click on install ...

**Comment by kaalleen** [comment]
Still needs to be done:
2. Can you make it so that when the window opens it shows the path location?
