### ISSUE TITLE
Missing lib c after installation on Catalina

### ISSUE THREAD

**Issue by yieselle4** [inkstitch/inkstitch#1127]
Hello. I have installed Inscape and done everything but when I got to try and go to params on Ink/Stitch I run into a message that says... 
"Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected." 

<img width="695" alt="Screen Shot 2021-04-04 at 7 39 50 PM" src="https://user-images.githubusercontent.com/81942055/113531395-892fe480-957d-11eb-8c35-c6c320aa5a44.png">

I have Inkspace 1.0.2 Ink/Stitch 1.29.1 and a Macbook Pro. I'm not sure what to do. Thank you.

**Comment by tyrosinase** [comment]
Big Sur? Try this: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

**Comment by yieselle4** [comment]
> Big Sur? Try this: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

I have Catalina and I followed the Catalina steps already.

**Comment by kaalleen** [comment]
Looks like Catalina needs this extra step now too. Try to run the additional Big Sur command.

It's really time for our next release. This won't be necessary soon. Sorry for your trouble.

**Comment by yieselle4** [comment]
> Looks like Catalina needs this extra step now too. Try to run the additional Big Sur command.
> 
> It's really time for our next release. This won't be necessary soon. Sorry for your trouble.

Thank you very much this worked for me.
