### ISSUE TITLE
A menu to store practical commands

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1129]
How about putting "re-stack objects" and "transfer param" together in a new menu?
When I compare it to standard software, there is the edit menu which contains the copy / paste commands (so like duplicate) and selection commands (a bit like restack).
There are more and more entries in the menu and when you are a beginner it scares you. It is better to hide more things to show the essential which is params, lettering, tool fill and satin and command...
What could we call this new menu? Edit?

**Comment by kaalleen** [comment]
@lexelby what do you think?

**Comment by lexelby** [comment]
Sure :)
