### ISSUE TITLE
Font in "Print to PDF" dialog and printout  is too large in Russian localization

### ISSUE THREAD

**Issue by AlexxNB** [inkstitch/inkstitch#1131]
We touch this issue previously in #1112, but I decided separate it.

![изображение](https://user-images.githubusercontent.com/10389013/113608069-b7cbbf00-9652-11eb-920a-dbf549647ca9.png)

Font Barlow, which used on PDF Export page is not compatible with Cyrillic letters. So default font of the browser being used instead. It is not condensed and a little bit bigger, that is why most of phrases doesn't fit in single line. 

Possible variants:
* use another font with extended glyphs to support most of languages. (ex. Fira Sans Condensed is pretty match Barlow). But it will not solve the problem for Chinese,Japanese, Armenian and other languages.There aren't any universal font for all languages. Partial solution also may be using  [web safe fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp).
* specify font for each language when building
* allow user to choose font for PDF export

For now I can make some phrases shorter, but it is not a solution here.

**Comment by lexelby** [comment]
Is this a situation where specifying multiple fonts in the CSS will help?  Will the browser fall back to the second font if the first one doesn't have Cyrillic?

**Comment by AlexxNB** [comment]
Yes, but fallback font should be very-very similar to main font, because they will show together. Look at my picture - there are places where digits and Latin letters rendered with Barlow font and Cyrillic ones with my system font:

![изображение](https://user-images.githubusercontent.com/10389013/113714393-03cd4100-96f1-11eb-860c-1cc872902c3a.png)

Best solution is to use specified by translator(or somebody else) font for each language, then won't be any difference between Latin and non-Latin letters.

**Comment by lexelby** [comment]
I like that idea!  We can make a translation string of "fallback font" with a translation note that explains what it's for.

**Comment by lexelby** [comment]
Though we will still need to have that font included with Ink/Stitch, so that the electron browser is not trying to fetch it remotely.

**Comment by AlexxNB** [comment]
Haha, just saw that used 6 styles of Barlow font =) https://github.com/inkstitch/inkstitch/tree/main/print/resources

Possible way is separate font settings to the files like `font_default.css`, `font_ru.css`, `font_ab.css` and [include](https://github.com/inkstitch/inkstitch/blob/6335bd438ebf8203c54cdac3490c5500bd305973/print/templates/index.html#L9) only needed font based on translation string "pdf output font" (not fallback, it should replace default font at all). 

Also translator should make PR and add font(s) he wants and `font_xx.css` to the repo.

**Comment by kaalleen** [comment]
I don't know if we need to add it to the translations if translators will have to make a pull request anyway.
But I like the idea of separated css files for some languages. Would you care to generate a PR for this?

**Comment by AlexxNB** [comment]
> I don't know if we need to add it to the translations if translators will have to make a pull request anyway.

Agreed. 

> Would you care to generate a PR for this?

I'll try to worok with styles when have success on build the extension locally.

**Comment by AlexxNB** [comment]
It wasn't easy, but I write the Dockerfile for building extansion in right environment:
```dockerfile
FROM nikolaik/python-nodejs:python3.6-nodejs14-slim

COPY ./requirements.txt /deps/requirements.txt

RUN  apt update && apt install -y \
        git \
        make \
        build-essential \
        gettext \
        python-wxgtk4.0 \
        pkg-config \
        libgtk-3-dev \
        libglib2.0-dev

RUN pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/debian-10 wxPython

RUN cd /deps && git clone --depth 1 https://github.com/inkstitch/pyembroidery.git \
     && pip install -r /deps/requirements.txt \
     && pip install pyinstaller 


WORKDIR /src
VOLUME /src

CMD make
```

Usage:
```shell
# run once or when depndencies need to be rebuilded.
docker build -t inkstich-env .

# run make script:
docker run --rm --name InkstitchEnv  -v $PWD:/src -e BUILD=linux -it inkstich-env make dist
```

But with implementation I have a troubles. My idea is to add including `locale.css` in `index.html` template. And then in function `def resources(resource)` check if resurce is `locale.css` and then return a file based on current locale `locale_xx.css` or `locale_default.css`, if no file for locale. I don't know how to determine the locale in this place =) It is better if somebody else will implement this feature =)

**Comment by kaalleen** [comment]
Ok, thanks for putting your time into it. I can have a look when I find the time.
I am not sure if that will be before the next release though.

**Comment by kaalleen** [comment]
Alternatively we could think about a font which supports cyrillic letters as well. But maybe soon we will have the same issue with japanese (we actually just recently got some translations into japanese) or some other letter systems. So separating the css files might still be necessary and our way to go.

**Comment by AlexxNB** [comment]
> Ok, thanks for putting your time into it. I can have a look when I find the time.

I think I just need a best way to get current build's locale here: https://github.com/inkstitch/inkstitch/blob/132c6aba2f9ae572faca32c0c794199b8df893f0/lib/extensions/print_pdf.py#L99 .  Global or environment variable here maybe? Or a way to get it from gettext?

> But maybe soon we will have the same issue with japanese
Also Chinese, Arabian and other popular languages. So approach with different styles is much better, course.
