### ISSUE TITLE
Problem with Params in Inkstitch

### ISSUE THREAD

**Issue by idkwhattodolol** [inkstitch/inkstitch#1137]
I have a question.
I would like to open params in Inkstitch to adjust the mesurements and see how its gonna embroider it.
When I try to open it I can adjust those things but I can't see how its gonna embroider. It just loads and does nothing. 

Did someone have the same problem and can help me out?
Thanks.

**Comment by tyrosinase** [comment]
Usually when it doesn't display a preview on mine, that means it's throwing an error in the background. Does it display an error box when you close the Params box?

**Comment by idkwhattodolol** [comment]
No, it doesn't.

**Comment by tyrosinase** [comment]
Is it opening the preview box at all? I've never had it not do that unless it's throwing an error. (Or if I get impatient for my not-high-performance machine to figure out a really large/complex shape.)

**Comment by idkwhattodolol** [comment]
No, it just loads all the time.

**Comment by idkwhattodolol** [comment]
@tyrosinase What did you do when the error popped up at your programm? Maybe it solves my problem as well.

**Comment by MK-12-20MM** [comment]
Just a thought: 
Run the troubleshooter on your design - Ink/stitch > Troubleshoot > Troubleshoot Objects with no objects selected.  See if any errors pop up.. If some are detected then corrections will be needed (there are other options in the inkstitch menu to clean things up- This will indeed slow down the parms dialog as tryosinase suggested.

**Comment by idkwhattodolol** [comment]
Ok, thx. I will try.

**Comment by tyrosinase** [comment]
It varies a lot. I am super-good at accidentally adding a fill to something that should not be filled. Or sometimes I don't notice when Inkscape likes to put a random break in a line when it does a few repeated outsets (great for making a second, outer satin rail when you want the inner to hug a fill, for instance).

There's actually a fairly large number of cases when Ink/Stitch doesn't notify you about a problem until after you give up and close the params/preview. Now that I think about it, I should probably open an issue on those cases.

**Comment by idkwhattodolol** [comment]
@tyrosinase @MK-12-20MM 
Thanks guys, it worked.
