### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by latsami** [inkstitch/inkstitch#1141]
Hello,
I have issues with running Ink/Stitch on Arch Linux.

I have this error when running the Params, or the Troubleshoot Objects commands.

    /usr/share/inkscape/extensions/inkstitch/bin/inkstitch: /usr/share/inkscape/extensions/inkstitch/bin/inkstitch : Cannot execute binary file

The extension is now is this folder, but it was before in my `~/.config/inkscape/extensions` folder. I just wanted to check if it would solve the problem...

Any clue?

**Comment by lexelby** [comment]
Is it possible that you grabbed the Mac version by mistake?  Or maybe you're running a 32-bit Linux?

What does it say when you run `file usr/share/inkscape/extensions/inkstitch/bin/inkstitch`?  You may need to `sudo apt-get install file`.

**Comment by kaalleen** [comment]
Oh hey, I use arch too. That is how I noticed that you can also install Ink/Stitch directly from the user repository if you wish: https://aur.archlinux.org/packages/inkstitch (english only)

**Comment by lexelby** [comment]
WHOA!  That's cool!
