### ISSUE TITLE
Inkstitch Terminal Codes have Bricked Inkscape

### ISSUE THREAD

**Issue by BradADe** [inkstitch/inkstitch#1150]
Hello, I recently installed inkscape and the inkstitch plugin and after entering the commands in terminal as the walkthrough tells you to do, I can no longer get inkscape to open, even after uninstalling and reinstalling. Is there a reversal command for those or another way of fixing this? Thanks in advance.

**Comment by tyrosinase** [comment]
When that has happened to me I just renamed my `/home/$USER/.config/inkscape/extensions` folder to `extensions.bad`, and gradually moved extensions from there back to a new `extensions` until I found the problem child. (The folder may be in a different spot depending on your OS.)

Of course if Ink/Stitch is your only extension, you can just delete the folder altogether and reinstall.

**Comment by kaalleen** [comment]
This is pretty old. I'm closing it. Please open a new issue if there are still similar problems.
