### ISSUE TITLE
Calculating the satin column is not always perfect

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1164]
![image](https://user-images.githubusercontent.com/63351363/115950831-e57f8780-a4dd-11eb-876c-a3d9429c6364.png)

**Comment by lexelby** [comment]
Satin columns can be really confusing...

In test 1 and test 3, you have no rungs.  In this case, Ink/Stitch uses the svg path nodes as if they were rungs.  In the code, it actually constructs fake rungs!

As soon as you have one rung though, it ignores the path nodes entirely and only uses your rungs.  It does its best, but test 2 requires it to guess a lot.
