### ISSUE TITLE
Crowdin - Which translation file to translate?

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#1165]
![image](https://user-images.githubusercontent.com/63351363/115969343-c3692200-a53c-11eb-8a40-e0445df706d2.png)

The translations between the main and the master are different. 

@lexelby, which will be used ?

If there is one that is no longer useful, can it be deleted?

**Comment by lexelby** [comment]
Oh, "master" is old and should not be used.  We changed the branch name to "main" to avoid problems with the English word "master" (it is a reference to slavery).

I'll see if I can delete it in crowdin.  Thanks!

**Comment by lexelby** [comment]
I got rid of the "master" one.  There was quite a bit of overlap in the two files, and the translations for "master" should carry over to "main".
