### ISSUE TITLE
Issue with Stroke Size going to Satin

### ISSUE THREAD

**Issue by BriceBrown** [inkstitch/inkstitch#1169]
<img width="1680" alt="Screenshot 2021-04-26 at 22 26 15" src="https://user-images.githubusercontent.com/39029681/116146352-b08e5300-a6de-11eb-980e-fe6a2d096728.png">
<img width="1680" alt="Screenshot 2021-04-26 at 22 26 51" src="https://user-images.githubusercontent.com/39029681/116146370-b5eb9d80-a6de-11eb-88dd-ed6169904078.png">

As you can see the stroke size of the shape is then scaled up to a HUGE amount when doing a satin column in the params column. This issue also arises in the stroke to the satin regular panel.

**Comment by tyrosinase** [comment]
I thiiiink this gets fixed in a newer release (one of the devs could say for sure), but in the meantime, Apply Transforms (https://github.com/Klowner/inkscape-applytransforms) will fix shapes that this happens to.

**Comment by kaalleen** [comment]
This issue should have been fixed with v2.0.0. Therefore I am going to close this issue.
Please reopen if you are running into the same problems with the newest update.
