### ISSUE TITLE
Error shape is not valid

### ISSUE THREAD

**Issue by hoesgarth** [inkstitch/inkstitch#1170]
"path1291: error: Fill: Shape is not valid.  This can happen if the border crosses over itself." im having a hard time finding the invalid shape. is there an email i can send my svg file to since i cant upload it in this message?

**Comment by hoesgarth** [comment]
nevermind! i figured it out by testing each fill shape individually in params until i found the problem shape

**Comment by tyrosinase** [comment]
For future reference: you can rename the .svg to a .txt and upload it.

Also, under Troubleshooting there is an option called Troubleshoot Objects that will (usually) find the problem shape.
