### ISSUE TITLE
Over spaced borders on ink stick params

### ISSUE THREAD

**Issue by Evan-launchpadduo** [inkstitch/inkstitch#1177]
I have a problem where the borders on my SVGs. They appear much larger and not spaced out. Does anyone have a fix for this.![image](https://user-images.githubusercontent.com/72927778/116642353-a5386300-a93c-11eb-9305-c1324183930d.jpeg)

**Comment by Evan-launchpadduo** [comment]
[Croc V2.svg.zip](https://github.com/inkstitch/inkstitch/files/6402850/Croc.V2.svg.zip)

here is the file in question. I would appreciate any help thanks :)

**Comment by tyrosinase** [comment]
This is probably going to be the same issue as #1169; there's a workaround there and I'm going to interpret lexelby's thumbs-up as confirmation that it's fixed in a future release.

**Comment by tyrosinase** [comment]
(Interesting that both cases are happening on Mac; I haven't seen it on my Linux install in quite some time.)

**Comment by kaalleen** [comment]
Yes, the transforms are causing one issue here. But even with the soon updated Ink/Stitch version it will still not be looking good. You should think about converting your outlines into real satin columns. The zig zag stitch isn't really capable of doing nice edges.

For the old Ink/Stitch version apply your transform. Then select your outline, remove the fill and run Extensions > Ink/Stitch > Satin Tools > Convert Line to Satin.

**Comment by kaalleen** [comment]
The new version is out. Zig-zag sizing should be working much better now.
