### ISSUE TITLE
Stroke Params

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1178]
https://github.com/inkstitch/inkstitch/blob/77a1ad3830b684dfa95b2f5a7bb643581397a43d/lib/elements/stroke.py#L23

@lexelby can this be renamed into stroke or running stitch (at least in the user visible string)?

**Comment by lexelby** [comment]
I think the user visible string can be.  This is one of the parts of the Params code that I don't like.  I want to get rid of it when we switch to electron.

**Comment by kaalleen** [comment]
Sounds like a good idea :)

I will create a pull request then to just change the string for now.
