### ISSUE TITLE
Inkscape AppImage 1.0.1+ does not run on Debian 10/Ubuntu LTS

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1184]
Not actually an Ink/Stitch issue, but I figured I'd put it here on the off chance people actually read the issues before creating a new one.

It's a wontfix, because they've decided to wait for Debian 11 (wtf). The ppa version *should* work for Ubuntu LTS, but that doesn't seem to work for Deb10 (for me, anyway). There's an incompatibility in the gnome file dialog handling that will cause it to hard-close.

The Inkscape 1.0 AppImage version seems to be okay so far, though I seem to recall having issues with it that drove me back to 0.92. We'll see. It's here: https://inkscape.org/release/1.0/gnulinux/

**Comment by tyrosinase** [comment]
I've successfully compiled Inkscape from scratch and things are fine so far. It only took 147 DuckDuckGo searches in two languages to figure out all the dependencies.

I've also been told the Flatpak version works on Deb10 but I stubbornly refuse to install another package manager. That's probably what normal people should do, though.

**Comment by kaalleen** [comment]
I'm going to close this issue due to it's age. If you do not agree, write up your protest and I'll reopen the issue :)
