### ISSUE TITLE
Error Message on Mac 

### ISSUE THREAD

**Issue by itsmar47** [inkstitch/inkstitch#1185]
I installed the new 2.0 version of Inkstitch and everything seemed to go very smooth., until I did the test portion of the installation.  After drawing a circle, select path, I went to INKSTiTCH the PARMS and received the following error message.  “inkstitch.app” cannot be opened because the developer cannot be verified.macOS cannot verify that this app is free from malware.  Safari downloaded this file today at 7:09 PM from github-releases.githubusercontent.com."

What do I do to fix it?
Thanks

**Comment by tyrosinase** [comment]
It is complaining that no one on the Ink/stitch team has Apple Developer credentials. If I was paying closer attention to when 2.0 was coming out, I would have made sure *somebody* had them. (Seriously you guys, tell me where to Venmo/Paypal/whatever the payment to, I'll cover it for this year.)

Anyway, if you go to the Apple Menu, System Preferences, Security & Privacy, General tab, you should find and "open anyway" option. (If it doesn't show up, try to open it again in Inkscape to refresh it.) That should override Gatekeeper, as I understand it. If that doesn't work, searching for something like "override gatekeeper" will probably find other ways to do it.

**Comment by kaalleen** [comment]
Follow the install instructions: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

@tyrosinase is right. This happens, because we haven't bought a license from apple, which would be necessary to undergo this message. Thanks to Lex this will change with the very next release. We plan to include a macOS installer and the release of apple notarized code.

**Comment by tyrosinase** [comment]
OhhhHHHHhhh, so the additional steps are still necessary even with 2.0?

**Comment by kaalleen** [comment]
Yes. It just has become a little bit less, since they don't need to fix the missing library.

**Comment by itsmar47** [comment]
Tyrosinase - I don't see what you are talking about on the Apple - Security/Privacy window.  
<img width="657" alt="Screen Shot 2021-05-05 at 2 26 12 PM" src="https://user-images.githubusercontent.com/83679186/117190893-f49fe880-adad-11eb-84be-9cba3a46a4f7.png">

I tried searching for Gatekeeper but noting came up.

I tried the old fixes for Big Sur but I just keep going back and forth between the 2 error message.   This is the very same situation I was having prior to Version 2.0.  I've never been able to get Inkstitch running on my MacBook.  

Thanks

**Comment by tyrosinase** [comment]
Hmm, it might be in the FileVault section; you do have to have tried to run the thing recently for it to show up; they expire in an hour.

(I'm sort of flying blind here, we haven't had a MacBook in a few years now and I can't even remember which OS version it had.)

Although if you're running Inkscape 1.0, and you've followed the current directions kaalleen pointed to, it sounds like maybe you have a different problem, and that's definitely above my pay grade.

**Comment by Marif91** [comment]
Si cela peut vous être utile https://youtu.be/F_r7zbU62tU entre 4mn et 6mn et 12s...

**Comment by itsmar47** [comment]
I found File Vault and everything seems to be working.  Thanks for your help.
