### ISSUE TITLE
Error in windows 10 inkstitch v2.0

### ISSUE THREAD

**Issue by Gabiczr** [inkstitch/inkstitch#1186]
After the installation of the new version of inkstitch with the antivirus deactivated i got this error and i tried also to install again the inkskape the latest version of it and i have the same error...what could go wrong ...

Ink/Stitch experienced an unexpected error. 

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\lettering.py", line 420, in effect
  File "lib\extensions\lettering.py", line 48, in __init__
  File "lib\extensions\lettering.py", line 151, in set_font_list
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
Uh, thank you for reporting this. It seems to be a bug in wxpython for windows in combination with python 3.8(+). But this info may not be very interesting for your.

I am not sure how to bypass it yet. I would be interested about your system language and your language settings in Inkscape. Does the params window work for you?

**Comment by Gabiczr** [comment]
hello, thanks for the replay, i've checkt also the language to see if its that the problem but is setted right in bouth sides :(, and with the old version of inkstitch is working but with this one i got this error ...

**Comment by danielkschneider** [comment]
Hi I got the same message. Windows 10 in English, Inkscape set to English, InkStitch English, Windows parameters to Switzerland. I did not yet test the french version. (No problem under Ubuntu in English).

**Comment by Gabiczr** [comment]
For me on Windows bisede this, one on lettering i also  got this on i try to do parameters...

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
@Gabiczr @danielkschneider 
This branch here is supposed to fix this issue. Can you confirm?

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186

**Comment by danielkschneider** [comment]
> @Gabiczr @danielkschneider
> This branch here is supposed to fix this issue. Can you confirm?
> 
> https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186

Cool, this seems to work with this configuration: Windows 10 in English, InkScape in English, InkStitch in French and also InkStitch en English. thanx kalleen !

**Comment by danielkschneider** [comment]
> https://discuss.wxpython.org/t/wxpython4-1-1-python3-8-locale-wxassertionerror/35168
> 
> Looks like you are not supposed to speak English in Switzerland ;)
> 
> > Also, this error does not effect operations other than this message
> 
> Do I understand it correctly, that lettering and params still work and only display the message in the end?



> https://discuss.wxpython.org/t/wxpython4-1-1-python3-8-locale-wxassertionerror/35168
> 
> Looks like you are not supposed to speak English in Switzerland ;)
> 
> > Also, this error does not effect operations other than this message
> 
> Do I understand it correctly, that lettering and params still work and only display the message in the end?
yes that was it. Everything worked OK, but for each operation tried I did get that error (but I have seen that you already fixed this)

**Comment by kaalleen** [comment]
Thank you for the good news and running the test :)

**Comment by Gabiczr** [comment]
YES it's workingggg. Thank you guys thank you ! I wish you all a wonderful evening!

**Comment by rivens623** [comment]
I also received a similar message:

`Ink/Stitch Version: v2.0.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\stitch_plan_preview.py", line 27, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 78, in new_color_block
  File "lib\stitch_plan\stitch_plan.py", line 177, in __init__
  File "lib\stitch_plan\stitch_plan.py", line 212, in color
  File "lib\threads\color.py", line 29, in __init__
TypeError: 'NoneType' object is not iterable`

**Comment by kaalleen** [comment]
@rivens623 This is an other error. Do you possibly still have the svg file which is causing the issue?
I'd love to have a look at it. (See also #1124)

**Comment by rivens623** [comment]
@kaalleen - I don't remember which svg file caused it, I had it happen again on another file and I ended up running Extensions > Ink/Stitch > Fill Tools > Break Apart Fill Objects and it resolved the issue.

**Comment by kaalleen** [comment]
Ok, thanks for the feedback. If that ever happen again, I'd be curious to see the svg file if possible.

**Comment by topfengoscherl** [comment]
Hello, since updating to InkStitch 2.0.0 (windows) and trying to open the "Params" window I've been getting the same error:

```
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

Changing the language of my windows system fixed this issue. I reverted the language change to confirm it.

Previous language settings (caused the error):
- Windows: English (Austria)
- InkStitch: English
- InkScape: English

Current language settings (fixed the error):
- Windows: English (USA)
- InkStitch: English
- InkScape: English

Thanks for this thread, I would have never been able to fix this on my own in a million years. Happy stitching! :)

**Comment by kaalleen** [comment]
@topfengoscherl thanks for your feedback. The above mentioned fix has been merged into the main branch and will be included in the next Ink/Stitch release. So you will then be able to return to Austria ;)
