### ISSUE TITLE
AV detection linked to inkstitch.exe 

### ISSUE THREAD

**Issue by JohnDownard** [inkstitch/inkstitch#1188]
I installed and used Inkstitch2.0 on Inkscape1.02 successfully for a few hours then it stopped working (no errors). After deleting both Inkscape & Inkstitch and reinstalling from scratch (with same result) I saw a Windows Defender alert (trojan - Win32/Wacapew.C!ml), it removed the threat by removing Inkstitch.exe. I extracted just this exe from the install zip and the threat was again detected. Is this file infected on the distribution media?
![Defender-Inkstitch](https://user-images.githubusercontent.com/83720075/117176054-620c4300-adc7-11eb-9dab-80536a299a1b.jpg)

**Comment by kaalleen** [comment]
There has been a discussion about this on an older release. See #710
