### ISSUE TITLE
No scroll bar on palette selection

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1189]
Not sure if this is an Inkscape issue or something Ink/Stitch has introduced, but I have a small crisis in that I use Sulky but I can only see down to Fufu Rayon before it disappears off the bottom of my screen.

Okay, crisis averted, I don't have to buy an entire new set of threads: I moved most of the palettes out of the directory (why have I never done that before, actually).

**Comment by kaalleen** [comment]
I'm afraid there is nothing we can do about it. This is an Inkscape issue. Good you found your own solution ;)

**Comment by tyrosinase** [comment]
Do you know if there's an open issue in Inkscape? Because if not I'll report it, but I'm not sure how to explain it to them since it's not something I have seen on any other Inkscape menu and I am pretty sure they'll just tell me it's an Ink/Stitch problem if I can't give more detail.

**Comment by kaalleen** [comment]
If I am understanding right, you are talking about this color palette list here: https://inkscape-manuals.readthedocs.io/en/latest/palette.html ?

I have those small arrows on top and the bottom of the list which allow me to scroll. If you are not using the newest Inkscape version, it may also help to test this one first? Anyway, if you mean that list, Ink/Stitch has no influence on it at all. It could be filled with any color palette, which you have placed into the inkscape palette folder.
