### ISSUE TITLE
Satin stitch zigzag feature

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1190]
The new satin is nice for actual satin, but no longer works to make a zigzag stitch by setting a wide spacing between points. Can we have a checkbox to use the old style? I make a lot of zigzag tackdowns that way, and I'm not even sure it's just a cosmetic problem to have it work the new way.

In a perfect world, satin would have a setting for the actual stitch and each underlay for number of repeats, so I could do a center underlay 1 time to run out to the end of something, a zigzag underlay twice to support the stitches, and then a single satin stitch to come back to the starting point. Or a zigzag underlay once, satin stitch zero to do the tackdown I just tried to do.

**Comment by lexelby** [comment]
I'm sorry, I actually have no idea what you mean... What new satin?

**Comment by tyrosinase** [comment]
New satin on the monarch, old satin on the sunset moth. 
![image](https://user-images.githubusercontent.com/9473609/117218911-21fe8d80-add2-11eb-8b6f-7af4b44457f0.png) 
![image](https://user-images.githubusercontent.com/9473609/117218971-4a868780-add2-11eb-83e4-a4086fbc2926.png)

**Comment by tyrosinase** [comment]
It makes sense, the pure-perpendicular satin is probably better for normal satin, but sometime you (well, I) just want a nice zigzag stitch.

**Comment by B-ellanna** [comment]
You can still use the zigzag stitch if you make a wide line, set the contour to continous and you stitch length. Its then in the stroke settings. I don't think Kall Een changed anything there.
ZigZag using a continuous line 2mm 0,7 mm scacing looks like this for me
![image](https://user-images.githubusercontent.com/64272979/117505485-63cf3580-af84-11eb-96da-57bce56ccfed.png)

**Comment by kaalleen** [comment]
Are we talking about the satin stitch angle?

/\/\/\/\/\/\/\/\/\/\ versus |\|\|\|\|\|\|\|\

Has that changed in satin column history @lexelby ?

**Comment by lexelby** [comment]
Yup, that's the difference we're talking about here.  Simple satin (Stroke) does the first one.  Satin Columns do the second one for the top stitch and the first one for zigzag underlay.

**Comment by tyrosinase** [comment]
Whaaaaaat? I never noticed the difference before, probably because I only ever used Stroke for tackdowns and Column for regular satins. But somehow I had got in my head that Stroke was going away in 2.0 so I went ahead and converted those tackdowns without ever trying it.

**Comment by Tina-Chris** [comment]
@tyrosinase Same here. I did not realize there is a difference^^

**Comment by tyrosinase** [comment]
Maybe we should just call the Stroke version "zigzag." 🤔

**Comment by lexelby** [comment]
I've been thinking of calling it "simple satin" or "legacy satin".  Way back in the day, there were no satin columns at all, just the simple zigzags!  

But "legacy" implies that satin column can do everything that legacy can, and that's not true yet, as you've shown us.  The stitch direction is not quite the same.

**Comment by lexelby** [comment]
In any case, no, we don't have plans to get rid of Stroke-style satins.

**Comment by lexelby** [comment]
#2431 adds a Zig-zag option in the "satin method" drop-down menu.

**Comment by tyrosinase** [comment]
If I had a nickel for every time I got a running stitch when I thought I was going to get a zigzag since this change, I'd have a *lot* of nickels (and a lot fewer failed design tests).

(Yeah, clearly I should do more "one last time" previews, because clearly I am *really* good at accidentally clearing stitch params.)
