### ISSUE TITLE
Object "xxx" has an empty 'd' attribute

### ISSUE THREAD

**Issue by bengal987** [inkstitch/inkstitch#1192]
this is the message i receive when trying to run params,

path76: error: Object path76 has an empty 'd' attribute.  Please delete this object from your document.

My question is what is a 'd' attribute, and is there a way to tell which path is path76? My apologies if this is a simple question, I am still learning the program

**Comment by tyrosinase** [comment]
If you open the XML file (shift-ctrl-X, I think?) you can see the tree structure. If you highlight path76 there, it will select the corresponding object. Or you can just tab through the objects and it'll show the names in the bottom bar.

The 'd' attribute is the one that holds all the nodes, so it's probably a zero-node object. Inkscape likes to create those for its own mysterious reasons (well, 0.92 did, I haven't been using 1.0.x long enough to see whether it does or not).

**Comment by kaalleen** [comment]
If your list of paths is long, then it could be hard to find the empty object quickly. I would suggest you try the cleanup document extension, found in Extensions > Ink/Stitch > Troubleshoot > Cleanup document. This should remove the empty object.

**Comment by kaalleen** [comment]
I thought we could update the message. But description to solve will appear when the troubleshoot function is run.
