### ISSUE TITLE
installation inkstitch V2 windows 10

### ISSUE THREAD

**Issue by lynxys77** [inkstitch/inkstitch#1197]
![erreur](https://user-images.githubusercontent.com/83958709/117657672-22b06e80-b19a-11eb-9a00-df3af164a3f7.png)
Good morning all
after installing inkstitch V2 on windows 10, the extension does not display menu content.
I followed the way to install it
attached a screenshot, it's on a french windows

**Comment by Augusa** [comment]
C'est un problème d'antivirus. Sortez inkstitch.exe de quarantaine et signalez-la à votre antivirus comme exception à accepter.

**Comment by lynxys77** [comment]
j'ai desinstallé l'antivirus avant l'installation d'institch, c'est toujours pareil
