### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by courtneyb001** [inkstitch/inkstitch#1199]
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/stitch_plan_preview.py", line 27, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment]
I discovered how this can be reproduced:
* Select only an image or text element (non embroiderable object)
* Run a rendering extenion (e.g. stitch plan preview)

**Comment by kaalleen** [comment]
Reason of error message confirmed in #1226

**Comment by kaalleen** [comment]
This error will not show up in the next release. Images and text will be filtered out. Therefore I am going to close this issue. Please reopen if the same error appears in the upcoming version.
