### ISSUE TITLE
Params will not stay open

### ISSUE THREAD

**Issue by dragonlord66666** [inkstitch/inkstitch#1200]
I have Mojave, installed inkstitch 2 (replaced inkstitch 1) into my 1.0.2 inkscape but when I try to open params (extensions>inkstitch>params) it opens but after a few seconds it closes so I can't actually use it or do anything
I did remove inkstitch 1 by selecting all the files and deleting them and inkstitch 2 is all in it's own folder from the zip file

**Comment by kaalleen** [comment]
See #1205
