### ISSUE TITLE
Remove commands doesn't remove commands

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1204]
When I import a PES, it comes in with a bunch of trim commands. My machine doesn't trim, so they just get in the way while I'm editing, so the first thing I do with a new design is remove them all. (The second thing I do is convert all the color groups to layers, but that still works.)

Nothing happens when I run the menu option; it doesn't cause Inkscape to think the file has changed or anything.

**Comment by kaalleen** [comment]
Uh yes, you are right. I haven't noticed that before. It only removes the commands if the top layer is selected.
I should have a look at it when I find the time. Thanks for the hint.

**Comment by tyrosinase** [comment]
On Wed, May 12, 2021, at 2:29 PM, Kaalleen wrote:
> 


> Uh yes, you are right. I haven't noticed that before. It only removes the commands if the top layer is selected.
> I should have a look at it when I find the time. Thanks for the hint.


Oh, interesting, it does work if I don't select *any* items and everything's still in the same layer.

(I don't know why I am inclined to select-all and then run that, but for some reason that's been how I do it.)

**Comment by kaalleen** [comment]
Well yes, it should work if you do it like that. Thanks for bringing it up.
I wrote up a fix for this issue. Hope it works now.
