### ISSUE TITLE
STOP commands break jef format

### ISSUE THREAD

**Issue by Liligrenouille** [inkstitch/inkstitch#1207]
Bonjour, j'ai identifié un bug sur inkstitch au sujet des commandes que l'on ajoute aux objets. 

Lorsque j'ai fait ma première numérisation je n'ai pas regroupé les couleurs dans des super objets couleur. 
J'ai juste mis tous les objets dans l'ordre des couleurs dans un seul super objet. (les objets à l'écran avaient des couleurs différentes). Pour être sûre que la machine s'arrête j'avais ajouté des commandes cut et stop pour le dernier objet de la couleur. 
Ca a bien compilé en .jef mais lorsque je rouvrais mon .jef sur inkstitch, tout était de la même couleur et ma machine n'arrivait pas à lire le fichier. 
J'ai donc fait des tests pour identifier l'erreur. Lorsque je transforme mon fichier en pdf il n'y a aucun soucis, il identifie les différentes couleurs, les groupes et les arrêts.
J'ai donc fait des tests et trouvé que la commande STOP ne fonctionne pas correctement. En fait on ne peut ajouter la commande STOP qu'au tout dernier objet qui sera brodé.
Ce qui oblige à classer dans des sous objets les couleurs sinon à la compilation il regroupe tout en une seule couleur.
J'ai vérifié en faisant de multiples tests, si on met le STOP au dernier objet brodé, ça marche, si on met un stop n'importe où ailleurs ça ne fonctionne plus. (on le repère car l'icône ne sait plus créer d'aperçu quand il y a un STOP ailleurs). J'espère que c'est assez clair et que ça aidera. On peut facilement contourner le bug car la machine fait des stop automatiques par couleur. Très bon we à vous et merci pour ce super logiciel !

**Comment by Liligrenouille** [comment]
Quand j'ouvre les .jef générés avec inkstitch ça fonctionne. Mais quand j'essaye de les ouvrir avec stitchbuddy il m'affiche l'erreur suivante. 
<img width="409" alt="Capture d’écran 2021-05-14 à 19 34 51" src="https://user-images.githubusercontent.com/84186180/118310030-5965ec00-b4ee-11eb-81ce-0eefc0fe753f.png">

**Comment by kaalleen** [comment]
I think this could be connected to #1830
