### ISSUE TITLE
Shapely broken on Big Sur 

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#1210]
The error message has now changed for MacOS Big Sur:

```
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/break_apart.py", line 49, in effect
  File "lib/extensions/break_apart.py", line 99, in geom_is_valid
  File "shapely/geometry/base.py", line 731, in is_valid
  File "shapely/predicates.py", line 25, in __call__
  File "shapely/geos.py", line 584, in errcheck_predicate
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x10e317d00>
```

Removing the shapely folder still fixes the issue - Shapely speedups should probably just be removed on MacOS for now. It runs very slow though, so ideally that would be fixed in the future. 

Other than that, v2.0 seems like a huge step forward. Patterns that broke before are now working, and patterns generated by break apart fill objects no longer render black. There's some basic issues (needs to alert if the dimensions are something insane, not closing on errors), and some features that would be nice, but the reality is that it just isn't crashing as much. 

There is a serious issue with pathing for objects right now - text is resulting in massive jumps all around the screen - but that should be much easier to fix now that Inkscape actually shows the objects :)

**Comment by kaalleen** [comment]
Thanks for your feedback. I was thinking about removing the speedups library for macOS too. It is causing issues too often.

> though there's stray pixels now result in random threads

What does that mean?

> needs to alert if the dimensions are something insane

Can you give an example?

> not closing on errors

Can you give an example?

**Comment by ecc521** [comment]
@kaalleen 

Dimensions - If the SVG is something like 500 inches x 500 inches, that's never finishing. Since SVG dimensions are irrelevant for many things, that isn't all that uncommon. 

Stray pixels isn't just stray pixels actually - it's also affecting text generated by break apart fill objects. Basically, it's just jumping the entire screen when it only needs to jump to one character. 

Not closing - was a shapely error. Haven't had anything else error, so it might be broken MacOS speedup exclusive

**Comment by kaalleen** [comment]
Dimensions: You mean like a warning if shapes are too big?

Stray pixels: you mean small fill objects in the document? Could this be fixed by cleanup document in the troubleshoot section?

Not closing: what happened when? Which window did not close? Is this related to #1038 ? Yay, when I look at it now, I see that it is speedups related. I didn't made the connection yet.

**Comment by ecc521** [comment]
Dimensions - Correct. 

Stray pixels - Thank you - Set area to 4 and worked perfectly. 
However text is still a bit weird - I've got two lines of text a LONG distance apart, and Inkstitch jumps between the lines instead of the characters much of the time. Probably something with break apart fill objects not ordering things well. 

Not closing - Inkscape GUI did not close when I had the shapely speed up error. Not sure if this happens for other errors.

**Comment by kaalleen** [comment]
> I've got two lines of text a LONG distance apart, and Inkstitch jumps between the lines instead of the characters much of the time. Probably something with break apart fill objects not ordering things well.

Break apart doesn't attempt to put objects in order, it was only designed to make invalid fill  objects valid which most of the time works. For the order of fill objects we have no tools yet. But there is an old extension whic has found it's way back into Ink/Stitch: Edit > Re-Stack objects in order of selection: https://inkstitch.org/docs/edit/#re-stack-objects-in-order-of-selection

**Comment by kaalleen** [comment]
I am not really sure which of the issue you were facing are remaining. Could you update the title accordingly?
