### ISSUE TITLE
Problème avec la fonction lettrage sur inkstitch qui ne sont pas reconnu voir capture 25

### ISSUE THREAD

**Issue by auroremon** [inkstitch/inkstitch#1212]
![Capture252](https://user-images.githubusercontent.com/84244452/118373016-c348c900-b5b4-11eb-9cb8-3dc9302f12e4.PNG)
![Capture25](https://user-images.githubusercontent.com/84244452/118373021-ca6fd700-b5b4-11eb-8a42-b2407f968f98.PNG)
![Capture22](https://user-images.githubusercontent.com/84244452/118373046-e7a4a580-b5b4-11eb-8f26-58ad9130d564.PNG)
![223](https://user-images.githubusercontent.com/84244452/118373079-14f15380-b5b5-11eb-83b3-21de4e8bbe97.PNG)
 
J'ai un problème avec les lettrages dans inkstitch, ca ne marchait pas capture 252 et 25 j'ai essayé avec toutes les polices mais rien n'y fait. J'ai contacté le groupe français on m'a dit de convertir les fichier oek... en         →.svg   je l'ai fait et redémarrer mais ca en marche pas non plus.  J"ai désinstallé inkstitch a nouveau installé en convertissant les fichiers mais ça ne marche pas. 
 J'ai windows7 et j'ai les dernières version inkscape et inkstitch.

Si quelqu'un a une solution pour me permettre d'utiliser cette fonction bien pratique

**Comment by Augusa** [comment]
Votre fichier json semble avoir changé de nom. Essayez de le renommer comme au début
________________________________
De : auroremon ***@***.***>
Envoyé : samedi 15 mai 2021 19:46
À : inkstitch/inkstitch ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [inkstitch/inkstitch] Problème avec la fonction lettrage sur inkstitch qui ne sont pas reconnu voir capture 25 (#1212)


[Capture252]<https://user-images.githubusercontent.com/84244452/118373016-c348c900-b5b4-11eb-9cb8-3dc9302f12e4.PNG>
[Capture25]<https://user-images.githubusercontent.com/84244452/118373021-ca6fd700-b5b4-11eb-8a42-b2407f968f98.PNG>
[Capture22]<https://user-images.githubusercontent.com/84244452/118373046-e7a4a580-b5b4-11eb-8f26-58ad9130d564.PNG>
[223]<https://user-images.githubusercontent.com/84244452/118373079-14f15380-b5b5-11eb-83b3-21de4e8bbe97.PNG>

J'ai un problème avec les lettrages dans inkstitch, ca ne marchait pas capture 252 et 25 j'ai essayé avec toutes les polices mais rien n'y fait. J'ai contacté le groupe français on m'a dit de convertir les fichier oek... en →.svg je l'ai fait et redémarrer mais ca en marche pas non plus. J"ai désinstallé inkstitch a nouveau installé en convertissant les fichiers mais ça ne marche pas.
J'ai windows7 et j'ai les dernières version inkscape et inkstitch.

Si quelqu'un a une solution pour me permettre d'utiliser cette fonction bien pratique

**Comment by kaalleen** [comment]
How do you unzip the Ink/Stitch files? Which program do you use?

**Comment by Marif91** [comment]
Le problème a été résolu sur le groupe français, le fichier a été mal renommé par l'utilisateur et comportait une extension double (.svg.svg).

**Comment by kaalleen** [comment]
Ok, good. Maybe it'd be less work if the file is correctly unzipped (as the font library grows).

**Comment by CELIAIMBERT** [comment]
Il me semblait que Kaleen nous avait dit que Inkstitch 2.0 ne fonctionnait pas sous windows7!!!
