### ISSUE TITLE
werkzeug 2.0 closes inkstitch (manual install)

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#1213]
Looks like ```request.environ.get('werkzeug.server.shutdown')()``` (lib/api/server.py) [has been deprecated](https://github.com/pallets/werkzeug/issues/1752), and Inkstitch is failing with the message: 

```
/Users/....../inkstitch/lib/api/server.py:58: UserWarning: The 'environ['werkzeug.server.shutdown']' function is deprecated and will be removed in Werkzeug 2.1.
  request.environ.get('werkzeug.server.shutdown')()
```

Can't downversion alone, as flask 2.0 requires werkzeug 2.0. 

Is this some sort of logging that isn't getting disabled? I noticed something in the code about anything going to stdout crashing Inkscape.

**Comment by ecc521** [comment]
Can downversion to flask==1.1.4 werkzeug==1.0.1, and it no longer crashes.
Simulator is now not doing anything (and no errors) when trying to launch realistic preview, so I can't confirm that works as a fix. 

Furthest I've gotten as far as setting up a development environment so far - stuff like Stitch Plan Preview is actually working this time, and the menu isn't filled with duplicate options.

**Comment by kaalleen** [comment]
Oh yes, I've seen this one before. But I don't remember if I left a note about it or not. Thanks for doing it here.
Could you sort out your troubles with the simulator?

**Comment by ecc521** [comment]
I'm using node 15.8, so that wouldn't explain it. 
I haven't managed to sort out the simulator issues - haven't had a whole lot of time to look at it. 

What's the debugging workflow? Chrome DevTools + NodeJS inspect, or some other tool? There's no information to work off of right now.

**Comment by lexelby** [comment]
I always knew the shutdown thing was wrong, but I didn't know how to do it properly.  It looks like now they have examples, yay!

**Comment by kaalleen** [comment]
> What's the debugging workflow? Chrome DevTools + NodeJS inspect, or some other tool? There's no information to work off of right now.

@lexelby could you answer this question? Debugging is not my specialty :D

**Comment by lexelby** [comment]
@ecc521 It depends on what you're trying to debug.  For the electron parts, I use the chrome devtools.  If you're running out of a manual installation, then the devtools pop up automatically.

For Python stuff, things get a little more involved.  We use pydevd-based debuggers, so  PyDev or PyCharm.  I actually have a couple of free licenses for JetBrains that can be used to work on Ink/Stitch (but not other stuff), and I can give it to folks that work on Ink/Stitch.  I'd be happy to send one your way if you'd like, just say the word :)

The way it works is that you create a file named DEBUG in your `inkstitch` repo directory.  It can be empty so just `touch DEBUG` is fine.  If that file exists, Ink/Stitch will try to connect to your IDE's debugging server on startup.  If it's successful, then it triggers a breakpoint immediately and you can start debugging in your IDE.

The workflow I use is:

1. `touch DEBUG` -- I usually just leave this there.
2. Go to debugging mode in my IDE.
3. Click the button in my IDE to "start debug server".
4. Set some breakpoints.
5. Run an Ink/Stitch extension.
6. When my debugger shows that Ink/Stitch has connected, I hit "play" ("resume", I think), and then it goes until it hits a breakpoint.

Having the DEBUG file present also causes `debug.svg` to be written in some cases.  We have an entire `lib.debug` module that you can use to create SVGs that can help you debug the complex algorithms like fill stitch and the like.

**Comment by lexelby** [comment]
Oh, and I do `pip install pydevd==2.3.0`.  That seems to be the version that works with PyCharm.
