### ISSUE TITLE
ValueError: Sequences of multi-polygons are not valid arguments

### ISSUE THREAD

**Issue by Risticalex** [inkstitch/inkstitch#1215]
Hi, when i try to check if there's any errors with the shapes of my drawing, this message occurs. It's a really complex drawing with a lot of shapes. When i select only some of the shapes, the message disappear and the option works but when i select all the shapes, it fails everytime. Thanks in advance! 

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\troubleshoot.py", line 32, in effect
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 164, in shape
  File "shapely\geometry\multipolygon.py", line 62, in __init__
  File "shapely\geometry\multipolygon.py", line 177, in geos_multipolygon_from_polygons
ValueError: Sequences of multi-polygons are not valid arguments

**Comment by kaalleen** [comment]
Thank you for reprting your issue. This is a new one. Would it be possible to send the file which is causing it? It would be great to be able to have a look at it.

**Comment by kaalleen** [comment]
We also now have a mail address where you could send your file to: send-us-files@inkstitch.org

**Comment by Risticalex** [comment]
Hello, I have resolved the problem. It was a real complex drawing with thousands of shapes. To resolve it, I checked all the shapes one by one and find the ones that were problematic. I have deleted them and recreated them

**Comment by kaalleen** [comment]
Ok, that's good. Great you figured it out.

Do you think though, that it would be possible to recreate the error so we can fix it for an other Ink/Stitch release? That would be so great.

**Comment by jeffsamsr** [comment]
I happened to encounter the same error and noticed your un-answered request for a file.
[InkStitch Multi-Polygons Error.zip](https://github.com/inkstitch/inkstitch/files/6872882/InkStitch.Multi-Polygons.Error.zip)
This zip file contains:
InkStitch Multi-Polygons Error.png  (example image)
InkStitch Multi-Polygons Error.svg  (example Inkscape file)

I hope it helps.  Thanks!

**Comment by kaalleen** [comment]
Thank you so much. This really will be a great help for us!

Just a little info for you, so you can go on working on your file. If you run `Extensions > Ink/Stitch > Fill Tool > Break apart fill objects`, it will repair your broken shape. Usually you would want to redesign outlines like yours to become satin columns or even running stitch (depending on the size you will want it to stitch out). It would give much nicer stitching results.

**Comment by kaalleen** [comment]
I'll close this issue because there will be a fix in the upcoming release. Please reopen, if this is showing up again.
