### ISSUE TITLE
Ink/Stitch is confused by removable media

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1217]
Accidentally selected the PES that I had saved to a thumb drive (which I had since removed) instead of the source SVG when doing a File > Open Recent, and Inkscape threw an error.

```
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (linux)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "lib/extensions/input.py", line 46, in run
  File "lib/stitch_plan/stitch_plan.py", line 156, in extents
  File "lib/stitch_plan/stitch_plan.py", line 142, in bounding_box
ValueError: min() arg is an empty sequence

```

I mean, I get it, I too get a little tongue-tied when someone does something boneheaded and I'm trying to tell them what they did wrong without insulting them. But it should probably handle missing files more gracefully.

**Comment by kaalleen** [comment]
Ha, interesting. We have seen this error before, but never received any additional information. So thank you for removing your drive :D
