### ISSUE TITLE
Problème simulation inkstitch 2.0

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#1218]
Bonjour,

J'ai aidé un utilisateur à finaliser l'installation de inkstitch 2, il y avait deux fichiers en quarantaine... (antivirus avast).

Inkstitch fonctionne bien, sauf la simulation ! Sur un exemple simple : monochrome, 6 formes séparées sans croisement de lignes, la simulation renvoie le message contenu dans le fichier joint.

Merci pour votre aide !

[Erreurs rencotrées en prévisualistion - Exception in thread Thread.docx](https://github.com/inkstitch/inkstitch/files/6499020/Erreurs.rencotrees.en.previsualistion.-.Exception.in.thread.Thread.docx)

**Comment by kaalleen** [comment]
Sorry, I am not sure what has caused the error. It somehow cannot connect to the electron server.

**Comment by kaalleen** [comment]
I'll close this. The new version hopefully has fixed the issue. Please reopen if not.
