### ISSUE TITLE
Japanese is not displayed correctly.

### ISSUE THREAD

**Issue by ryosakamoto1** [inkstitch/inkstitch#1224]
Thank you for providing the Japanese version.
I installed the Japanese version and the pull-down menu is in Japanese, but the parameter setting screen is in English.
![inkstich](https://user-images.githubusercontent.com/85022199/120071280-83f89d00-c0c9-11eb-9a1d-7297eed0c035.png)

**Comment by kaalleen** [comment]
Hey there. Thank you for reporting your issue. The japanese translation is new in this version and almost complete. Thanks to the translators :)

The reason why you are seeing english in your params window is that Ink/Stitch cannot see your language setting for some reason. You can easily fix this in the Inkscape preferences as described here: https://inkstitch.org/docs/install-windows/#i-installed-inkstitch-in-my-native-language-but-the-dialogue-windows-are-displayed-in-english

**Comment by ryosakamoto1** [comment]
Thanks for your answer.
I'm sorry I didn't read the troubleshooting.
The language setting in Inkscape fixed the problem.
inkstitch is the best!
