### ISSUE TITLE
lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

### ISSUE THREAD

**Issue by RodoMog** [inkstitch/inkstitch#1228]
When I create a brother .pes file I get this warning:  

lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

Wondering if it is related to Norton somehow.  I tried  shutting it down temporarily when I unzipped the file and then recopied to the user directory.  Still had issues.  

 The pes file cannot be read by my machine.  Tried importing another random .pes file to the machine and it worked okay.

**Comment by kaalleen** [comment]
This issue seems to appear quite regularly with the new Inkscape version (1.1). There is a fix for the next Ink/Stitch release already out there: #1223 I must have overseen this beforehand.

Other than it is annoying to receive this message often, it doesn't harm functionality.

Thanks for reporting, we appreciate!

**Comment by gusvisser** [comment]
i got this error for first time and my pes file did not create stitches in a few objects they were supposed to be satin stitches
the left side five shapes were supposed to be the satin stitches
![ink pes](https://user-images.githubusercontent.com/85417086/120906152-4c7f7880-c614-11eb-87d2-49c4071f4be2.PNG)

**Comment by kaalleen** [comment]
@gusvisser Thanks for reporting your issue. Would it be possible to send us the svg file for inspection?
If you want to post it here, you will need to zip it first. GitHub doesn't allow direct uploads of svg file.
It is also possible to send the file to our newly created mail address send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
@gusvisser Thank you for the file. I had a look at it. While the top font still has the old "embroider_" attributes (which will be converted correctly), the bottom font and the "lines" already have the newer inkstitch namespaced attributes. I cannot seem to find any parameters set to the shapes on the left. Are you sure you applied satin stitch params to them?

I heard some people having issues with the combination of the newest Inkscape version (1.1) and Ink/Stitch 2.0. There seem to be some instabitities which I don't understand yet. The deprecation warning shouldn't be one of them. If it is too annoying though, I could lead you to a development build version where this has been fixed: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-etree-deprecation-warning

**Comment by kaalleen** [comment]
Can you observe special occasions when Inkscape is crashing while running Ink/Stitch functions?
