### ISSUE TITLE
Windows setlocale error

### ISSUE THREAD

**Issue by SurenVerma** [inkstitch/inkstitch#1232]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
Oh, we have seen this error before. This happens, when you have a language/country combination which wxpython thinks is uncommon. But there is a fix, just in case this is causing you trouble running any function. Download and install this development build: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186

It only differs from Ink/Stitch 2.0 in that point, that it fixes this issue.

**Comment by cindyyd** [comment]
![image](https://user-images.githubusercontent.com/85836061/121812909-66682d80-cc9c-11eb-93ab-3eed179ed95b.png)


Do I need to download all files? do I need to drag all files into extension folder in inkstitch?

**Comment by tyrosinase** [comment]
You should only need to download the zip file for Windows, for the language you need - "de_DE" for German, "en_US" for English and so forth. After that follow the steps for an upgrade here: https://inkstitch.org/docs/install-windows/

**Comment by gNoelster** [comment]
> Oh, we have seen this error before. This happens, when you have a language/country combination which wxpython thinks is uncommon. But there is a fix, just in case this is causing you trouble running any function. Download and install this development build: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186
> 
> It only differs from Ink/Stitch 2.0 in that point, that it fixes this issue.

Thanks! This really helped!

**Comment by Phlebas42** [comment]
Remark:
I also encounter this problem with a fresh installation of Inkscape 1.1.1 and InkStich 2.0.0.
Neither the en_US nor the de_DE InkStich extension was working.
The problem was that I have a Windows 10 en_US installation but using a German keyboard layout.
After changing Windows to de_DE InkStich started working. 

Just in case some else encounters the same problem.

**Comment by kaalleen** [comment]
I'll close this issue because there will be a fix in the upcoming release. Please reopen, if this is showing up again.
