### ISSUE TITLE
Problems to get Parameters do anything and no preview

### ISSUE THREAD

**Issue by Kiwibird12** [inkstitch/inkstitch#1233]
Hello,
I wanted to start to create my own embroidery patterns and downloaded inkstich two weeks ago. Today I found the time to work with it. I have problems to get my parameters running and the preview does not work. I work with Linux under Lunbuntu, have the latest version from 2020. My Inkscape version is 1.1. I don't get any errors via terminal so I can't really see where the problem comes from. Has anyone an idea what the problem is?

**Comment by kaalleen** [comment]
I am wondering, if you really are running the latest version. Ink/Stitch 2.0 has been released in 2021.
Maybe you could try Ink/Stitch 2.0 and see if it is running? https://inkstitch.org/docs/install-linux/#download

**Comment by Kiwibird12** [comment]
Yeah, I have version 2.0.0 of Ink/Stich installed.

**Comment by kaalleen** [comment]
Ok, then I just have been confused by the date you've mentioned. Are you talking about the params preview or the simulator?

What exactly happens when you call params?

**Comment by Kiwibird12** [comment]
Both are not working. I don't see the parameters & I don't see the simulator. That's what confused me the most. When I call the parameter I see for a few secs a circle that disappears again.

I can check later if it works for me.

**Comment by Kiwibird12** [comment]
I've checked it and I'm still using XL.

**Comment by kaalleen** [comment]
XL?

**Comment by Kiwibird12** [comment]
Xorg

**Comment by Kiwibird12** [comment]
Sorry, misunderstanding with my bf. It's X11.

**Comment by kaalleen** [comment]
Hm, ok.
Any clue through system protocolls?

**Comment by ninao-xyz** [comment]
I have the exact same problems.
Params panel takes almost 1 full minute to open, and the preview doesn't show up.
I'm running Solus linux kernel: 5.12.10-182.
Tested with the inkscape on the solus repos (v. 1.0.2) and with the appimage downloaded from official inkscape website.
same problem with the two.
Also the inkstitch version I was trying to use was this one: inkstitch-v2.0.0-linux-en_US

Also tested in a VirtualBox vm with win7, and it works fine in there, and that's how i'm using inkstitch at the moment.

**Comment by kaalleen** [comment]
I heard the Appimage version of Inkscape is causing problems with some extensions.
Any chance you can install inkscape in a different way and see if Ink/Stitch is working then?

**Comment by latsami** [comment]
Hello,
I have the same issue.

I've just updated my Linux with the latest Inkscape 1.1 (c4e8f9ed74, 2021-05-24) and the latest Inkstitch 2.0.0.

When I have no objects and I click on Params, I have an error saying there is no object to work with.

Then if I draw a line and click on Params. Nothing happens, not even an error when launching Inkscape from the command line.

**Comment by christophfink** [comment]
I’m faced with the same issue - exactly like @latsami described. (Inkscape 1.1 (c4e8f9ed74, 2021-05-24), Inkstitch 2.0.0)

**Comment by christophfink** [comment]
I now built inkstitch from current master - and it works.
