### ISSUE TITLE
TRIM COMMAND Not recognized.

### ISSUE THREAD

**Issue by VikkiInWonderland** [inkstitch/inkstitch#1235]
Hello I've read else where of someone else having problem with their brother embroidery machine not recognizing the trim command on jump stitch. Wondering if anything could be done about this issue? Thx

**Comment by kaalleen** [comment]
Depending on your machine it may not be able to make use of trim commands. If you observed different behaviour in other files, there may be an issue with Ink/Stitch. I am not completely sure if there has been an issue (@lexelby ?)

Alternatively you could use different colors to force the machine to trim and stop after an object. This is very common to do.

**Comment by VikkiInWonderland** [comment]
That's what I'm doing right now to go around it.  I was told if trim commands were saved on DST, brother WOULD recognize the trim command.. I am trying to find out if this is true, have you heard this?☻☺♥Thx for the help.

**Comment by lexelby** [comment]
@VikkiInWonderland What machine do you have?

Entry-level brother machines (under $1000 USD) don't have the ability to trim the thread and continue sewing.  They ignore the TRIM command entirely.

**Comment by lexelby** [comment]
Ah, I see in the discussion thread that it's an Innovis NS 1750D.  I'm afraid that machine doesn't have the ability to trim jump sttiches. :(  Sorry to disappoint!
