### ISSUE TITLE
Border crossing over itself

### ISSUE THREAD

**Issue by Evan-launchpadduo** [inkstitch/inkstitch#1237]
No matter what I try I cannot get my image to work in Params. I have tried the break apart fill objects but it turns my image into a blob. I have tried creating the image from hand with no luck. Does anyone know how I should go about making this.![image](https://user-images.githubusercontent.com/72927778/121070747-1ae5e900-c79d-11eb-82a5-d6c490b17e15.jpeg)

**Comment by Evan-launchpadduo** [comment]
The closest I've gotten is having the shapes stitched out. I can't figure out how to make stroke items think like the shape.![image](https://user-images.githubusercontent.com/72927778/121073137-27b80c00-c7a0-11eb-99e0-4a7281b978c3.jpeg)

**Comment by kaalleen** [comment]
> I have tried the break apart fill objects but it turns my image into a blob

Sounds as if you are still using an older version of Ink/Stitch. It maybe will lead to better results: https://inkstitch.org/docs/install-macos/#download
