### ISSUE TITLE
break_apart: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by leosar54** [inkstitch/inkstitch#1246]
Ink/Stitch a connu une erreur inattendue.

Si vous souhaitez nous aider à résoudre ce problème, veuillez soumettre un problème à https://github.com/inkstitch/inkstitch/issues et inclure la description complète de l'erreur ci-dessous :

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kaalleen** [comment]
Thank you for reporting your issue. This error hasn't been reported to us yet. It is definitely a bug in Ink/Stitch. It would be great to be able to have a look at the file to investigate the reason why this is happening. Could you upload your svg file here or send it to our mail address send-us-files@inkstitch.org ?
