### ISSUE TITLE
Embroidering with Inkscape and Ink/Stitch HELP!

### ISSUE THREAD

**Issue by danigani19** [inkstitch/inkstitch#1250]
I am trying to create an embroidery svg with inkscape by using ink/stitch. I have my design ready, click "extensions", "Ink/Stitch", "English", and then "Params", and then this message pops up:   

Inkscape has received additional data from the script executed. This script did not return an error, but this may indicate the results will not be as expected.

File "inkstitch.py", line 53
    print stdout.strip(),
          ^
SyntaxError: invalid syntax

I've tried repeating the steps but the same thing pops up everytime I try. What do I do?

**Comment by kaalleen** [comment]
> click "extensions", "Ink/Stitch", "English", and then "Params"

This menu doesn't belong to a recent Ink/Stitch version. Maybe an update can solve your issue. Make sure to remove all the old Ink/Sttich files before installing the new version.
