### ISSUE TITLE
Case sensitivity in extensions

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1251]
Copied an existing embroidery file over to the USB drive; it ended in .PES.

Realized I needed to make some changes, so I opened it in Inkscape, made the changes, saved it as an SVG on the main drive, and did Save A Copy As to the USB drive. Chose the existing file, hit save, and waited for the overwrite confirmation to come up. And waited. And then looked at the USB drive and realized I now had a .PES *and* a .PES.pes version. Amusedly read it out loud under my breath and accidentally summoned one of my cats.

(That last bit probably isn't Ink/Stitch's fault though.)

**Comment by kaalleen** [comment]
Hm, I am not sure if only the last bit is not Ink/Stitchs fault, but also the first part. I am not sure if we can do anything about it.
Try the same thing with an svg file (or whatever file format you like to choose). filename.SVG will result into filename.SVG.svg
Maybe this issue should be directed to the Inkscape issues instead?

**Comment by tyrosinase** [comment]
Oh huh, I didn't even think to check that. Yeah, submitted to the issues over yonder.
