### ISSUE TITLE
New install.  McAffee flags as virus

### ISSUE THREAD

**Issue by hamanjam** [inkstitch/inkstitch#1253]
New download and install.  As soon as I hit "params", I get a virus warning.  McAfee quarantines c:\users\<username>\AppData\Roaming\inkscape\extensions\inkstitch-v2.2.0-windows-en_US\inkstitch\bin for "jti/suspect.196612!3ddd30c9d482"

**Comment by kaalleen** [comment]
See https://github.com/inkstitch/inkstitch/issues/710#issuecomment-633033997
