### ISSUE TITLE
Issue on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by lalesculiviu** [inkstitch/inkstitch#1258]
Hello,

I installed yesterday Ink/stitch. If I go to Extensions > Ink/stitch > Params, I get: "Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected." and "Unable to access the X Display, is $DISPLAY set properly?" Could you tell me how to solve this?

GNU/Linux openSUSE Tumbleweed latest, Inkscape 1.0.2, Ink/Stitch 2.0.0.

**Comment by kaalleen** [comment]
Hm, looks like the access to your display is denied. How did you install Inkscape and Ink/Stitch?

**Comment by lalesculiviu** [comment]
I installed Inkscape with YaST (the default installer program for openSUSE), but Inkscape it working OK.

I installed Ink/Stitch by downloading the latest .zip archive and unpacking in ~/.config/inkscape/extensions/ .

**Comment by Tina-Chris** [comment]
Hi @lalesculiviu I've got the same configuration, and it works for me without issues. 
What path/form did you mark in inkscape before running params?

**Comment by kaalleen** [comment]
So it's not the AppImage version of Inkscape. No access to the display sounds like some sort of priviledge issue. Did you by any chance use root to copy paste the Ink/Stitch files (not sure if this would cause the issue though)?

**Comment by lalesculiviu** [comment]
@kaalleen , I installed Inkscape with the help of YaST package manager of openSUSE. I unpacked/copied the Ink/Stich files using my user account (not root).

**Comment by kaalleen** [comment]
@lexelby Any idea how to solve this issue (Unable to access the X Display, is $DISPLAY set properly)?

Linux users already have reported this issue earlier and I have no idea how to fix it. I don't know if this is a pyinstaller issue we can fix or if it is a local setup?

**Comment by lexelby** [comment]
Honestly, I have no idea.  My only guess is that this might have something to do with Wayland?

**Comment by kaalleen** [comment]
Hm, I don't know. @lalesculiviu can you run a test if starting inkscape through the command line with the following command helps?

`export GDK_BACKEND=x11 && inkscape`

**Comment by lalesculiviu** [comment]
@kaalleen , no, it does not, the same result.

**Comment by kaalleen** [comment]
Wow, you are fast.
It's not wayland then.

**Comment by kaalleen** [comment]
@lalesculiviu I hope you could solve your problem. We somehow lost focus on it. Since our last conversation there has been a new release. Therefore I'll close this issue here, but you can reopen the issue any time or create a new one, so we can figure things out.

**Comment by lalesculiviu** [comment]
@kaalleen , OK, I understood.
