### ISSUE TITLE
Inkscape & Ink/Stitch on mt MacBook Pro 

### ISSUE THREAD

**Issue by meme584** [inkstitch/inkstitch#1260]
MINE NOT WORKING AND I do all setting good can you pls help why I have this /Users/evahall/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/inkstitch: /Users/evahall/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/bin/inkstitch: cannot execute binary file
when I click on PARAMS something no right and is not working for me I have MacBook Pro

**Comment by kaalleen** [comment]
It cannot find the Ink/Stitch executable. Not sure what happened to your installation.
Which macOS version do you use?
