### ISSUE TITLE
Help, I don't know how to solve to this problem : Error 1079

### ISSUE THREAD

**Issue by MOMOrgan-D** [inkstitch/inkstitch#1263]
"[1079] Error loading Python lib '/Users/morganduguet/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib': dlopen: dlopen(/Users/morganduguet/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib, 10): Symbol not found: _futimens
  Referenced from: /Users/morganduguet/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/morganduguet/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib"

Did you ever have this error ?

**Comment by kaalleen** [comment]
Yes, we have seen this one before. But it has been with a previous version (Big Sur & Catalina).
It is possible though, that some issue may return.

Which Ink/Stitch version do you use?

**Comment by MOMOrgan-D** [comment]
I obviously had one of these previous version ! I installed "Sierra / El
Capitan" version and it works ! Thank you for your time
