### ISSUE TITLE
Trim commands get lost in translation

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1264]
If I open a PES, it shows up with trim commands. I can save it to JEF and the trim commands stick. So far, so good.

If I copy that into an existing SVG, the trim commands stay with it.

But If I import a PES directly into an existing SVG, the trim commands stop working.

(I had another situation where I copied something and not only did the trim commands stop working, they turned into images that stitched themselves out in the stitch plan. Still working on reproducing that reliably though.)

(Also I assume it's not specific to PES/JEF, just that that's my specific conversion these days.)

**Comment by kaalleen** [comment]
Hm, interesting. Which Inkscape version are you using?

I remember there have been issue with commands and imported embroidery files earlier. But when I now try to reproduce them with Inkscape 1.1 I am not able to do so. What exactly do you mean by they stop working? Are they disconnected from the objects?

**Comment by kaalleen** [comment]
I suppose this should be fixed by now. Please reopen if I am wrong.

**Comment by tyrosinase** [comment]
Whoops, the problem with subscribing to all updates is sometimes you don't notice when the comments are actually directed at you.

2.1.2, Inkscape 1.1. They stay as non-stitching objects, they just don't do anything.

**Comment by tyrosinase** [comment]
(Also users can't reopen issues unless they closed them themselves.)

**Comment by kaalleen** [comment]
Ouch, thank you for that info, I really wasn't aware of it and posted that phrase over a hundred times. I hope we didn't lose bug reports when I was wrong about it.

I suppose then there is still something wrong the the command links/ids. I'll have to check that again.

**Comment by kaalleen** [comment]
I think #2384 should fix this one too ...
Release: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-command-recognition

@tyrosinase when you ever see this again with a version released after today (current official release v3.0.1 will still have this issue), please comment on this issue here or open a new issue.
