### ISSUE TITLE
Installing Thread Colour Palettes for Inkscape

### ISSUE THREAD

**Issue by jumiclads** [inkstitch/inkstitch#1266]
On trying to install palettes I get this error.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\install.py", line 18, in effect
  File "lib\gui\electron.py", line 36, in open_url
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 87] The parameter is incorrect

I am using a full up to date Windows 10 Home version. and followed the instructions  correctly. Thanks.

**Comment by lexelby** [comment]
Hah! Thank you, Windows, for a very useful error message ;)

In all seriousness, @jumiclads, thank you for the bug report!  You can manually install the thread color palettes by copying the .gpl files into inkscape's palettes directory.

**Comment by kkiely0924** [comment]
I installed the linux version on a chromebook, and didn't see an error when I attempted to install palettes (but also didn't see the palettes upon restart). However I copied the .gpl files based on this recommendation and was able to move past this -- so thank you!
