### ISSUE TITLE
Feathered edges

### ISSUE THREAD

**Issue by rafcole** [inkstitch/inkstitch#1272]
Adjacent request to number 78 for color blending.

I'd like to feather the ends of my stitch paths to blend in with fabric grainlines. Manually creating zigzags creates an ok facsimile of what I'm after. Does this exist/has it been discussed?

Also, is it possible to add randomized spacing to stitches/row widths for more organic fills?

![Screen Shot 2021-07-11 at 7 59 58 PM](https://user-images.githubusercontent.com/39354464/125225062-76ffc980-e283-11eb-89dc-b1836ae292c2.png)

![Screen Shot 2021-07-11 at 8 00 10 PM](https://user-images.githubusercontent.com/39354464/125224977-59326480-e283-11eb-982f-d06f775d9489.png)

**Comment by rafcole** [comment]
Here's the effect I'm actually after

![Screen Shot 2021-07-11 at 7 59 58 PM](https://user-images.githubusercontent.com/39354464/125225062-76ffc980-e283-11eb-89dc-b1836ae292c2.png)

**Comment by kaalleen** [comment]
Thanks for your feature requests. We always appreciate to receive new ideas that can bring Ink/Stitch forward!

The rough/jagged edge option has been discussed long ago in issue #190 . Have a look at the discussion. Do you think we should have a second thought on this topic?

The other feature you are asking for has already been implemented (half way) and exists as a hidden feature in Ink/Stitch. It has a description on our website: https://inkstitch.org/docs/features/#color-blending

**Comment by rafcole** [comment]
The specific implementation would be for darning denim repair. This deserves it's own thread to kick around ideas but I'll try to summarize so I can get your immediate feedback. Doing denim repair on a manual darning machine is a one way ticket to a repetitive stress injury. I've repaired hundreds of pairs of jeans by hand and would like to develop a more automated open source workflow.

![Screen Shot 2021-07-17 at 6 17 37 AM](https://user-images.githubusercontent.com/39354464/126039151-b5ed726f-94dc-48bd-a0a3-0b15e6027660.png)


Example - patch a hole in the crotch of a pair of jean and reinforce the surrounding area. 
- For this discussion let's assume a mildly clever hooping/clamping -> photo upload -> inkscape template workflow has been worked out. 
- Now we need to draw out the areas for repair (low, medium and high density stitching). For patching a hole this would mean three concentric blobs. 
- The biggest would be low density stabilization stitching (Y columns only, lots of blending). Medium density (Y columns only). High density hole patching using underlay and fill to reweave the warp and weft (both X and Y).

![Screen Shot 2021-07-17 at 5 50 57 AM](https://user-images.githubusercontent.com/39354464/126039309-fb65f2d1-e3b3-4ed2-8abe-4eaef0f54671.png)

General principles for an invisible repair
- Sew with the grainline
- Significant blending at edges
- Multiple color matches to the existing wear pattern
- Highest density stitching first (lower density passes can go on top of the high density stitching, if the thread colors are different this will serve as a visual blend as well).

I've just played with tweak tool, it seems like the 'edge pull' functionality could work you could get the level of resolution required. Maybe there exists an extension to automate this that would only pull in the Y axis? Are there other path tools you'd recommend exploring?

![Screen Shot 2021-07-17 at 7 03 51 AM](https://user-images.githubusercontent.com/39354464/126039526-479dec3b-2eee-4dae-bd1c-123df06eb054.png)

**Comment by rafcole** [comment]
Further exploration - if one could get the Hatches path effect to implement on blobs like Roughen path effect it would meet the criteria. Not sure how to get there from here.

![Screen Shot 2021-07-17 at 7 32 37 AM](https://user-images.githubusercontent.com/39354464/126041102-5a1e5c0e-9892-4bdb-a7ff-ff3d3c67dc81.png)

Having trouble getting Roughen to behave

![Screen Shot 2021-07-17 at 7 58 37 AM](https://user-images.githubusercontent.com/39354464/126041153-d1902062-f1a5-4590-8471-88a69974c072.png)

**Comment by rafcole** [comment]
Workaround found. Using Hatches path effect  -> create single line path -> use running stitch instead of fill. It looks good enough that I'm going to go ahead and start building my machine.

Usage questions

1. How can I control whether the stitch is generated L > R vs L < R?
2. Are the node adjustments from Hatch editable via variable? I'd like to generate these stitch paths automatically

![Screen Shot 2021-07-17 at 9 22 53 AM](https://user-images.githubusercontent.com/39354464/126043666-ab652999-f7c9-4651-8f0f-792a24909593.png)

![Screen Shot 2021-07-17 at 9 24 32 AM](https://user-images.githubusercontent.com/39354464/126043668-57c42f64-f0a8-4481-929f-b7ab6b567802.png)

![Screen Shot 2021-07-17 at 9 26 22 AM](https://user-images.githubusercontent.com/39354464/126043679-928a9b43-a90b-47c7-a57d-d9485f00383c.png)

![Screen Shot 2021-07-17 at 9 33 38 AM](https://user-images.githubusercontent.com/39354464/126043690-2b4501c0-da79-4d21-ba66-053ce44b56c0.png)

![Screen Shot 2021-07-17 at 9 29 20 AM](https://user-images.githubusercontent.com/39354464/126043691-28af0bd1-02c4-4c0f-b71a-233a58858cfe.png)

**Comment by kaalleen** [comment]
Interesting use case. I really do like your approach using the embroidery machine for denim repair.

> 1. How can I control whether the stitch is generated L > R vs L < R?
> 2. Are the node adjustments from Hatch editable via variable? I'd like to generate these stitch paths automatically

I would like to start answering the second question. Inkscape comes with an xml editor. This is where you can edit the variables (Edit > XML Editor (Shift+Ctrl+X)). The variables for your path effect are in the defs section of your svg. The most important variable for your use case is called "direction".

Usually you can swap stitch direction with Path > Reverse. This is not possible when you do not convert your object into a path. But since you are willing to work on the variables, you can swap stitch direction by manipulating the "direction" variable of your path effect. The third directional value has to be swaped from positive to negative and vice versa. The value itself defines the density.

I assume, that you would want to use similar values for each repair. If so, you could also consider to save your repair pattern into a template and then adjust the shapes for each operation.

![hatch_variables](https://user-images.githubusercontent.com/36401965/126114313-a67ef9c8-f6b5-4614-89b7-bb683694e872.jpg)

> Dotted versus solid stroke seems to impact whether one can edit zig zag param effectively?

Yes. A dotted line indicates a running stitch. A solid line produces zig zags.

**Comment by Augusa** [comment]
Thanks for the idea to use hatches. I use it now to create irregular zigzag with a long and narrow rectangle. Then I turn object to path and finally with pattern along a path I have what I want. I use it for trying to embroider needle painting and next time for furstitch. Sorry for this link in french but many pictures to explain what I want to do. 
Hope once we will get this possibility of random zigzag easily in Inkstitch.
https://lyogau.over-blog.com/2021/08/approche-de-la-peinture-a-l-aiguille.html

**Comment by kaalleen** [comment]
Now possible in satin column. Since satin column will also have a staggered option and s-stitch in future releases, I think this is pretty much covered (for satins).
