### ISSUE TITLE
imperfect embroidery

### ISSUE THREAD

**Issue by saraheilis** [inkstitch/inkstitch#1273]
The embroidery looks great when running through params, but there are so many imperfections after going through the machine. Are there specific settings for the stitches and rows to make them look more like professional embroidery?

The settings mine are at in params under "autofill" are:
Max. fill stitch length = 3 m
Spacing between rows = 0.25 m
Running stitch length = 1.5 m 
Stagger rows this many times before repeating = 4
Underpath selected
Ties selected
All the others are 0

**Comment by lexelby** [comment]
Hi!  Machine embroidery can be very challenging.  There are a lot of variables that can lead to less-than-perfect results.

Could you post a picture of the results you're getting?  That might help us guess what's going wrong in your case.

**Comment by saraheilis** [comment]
There are some sections with missing stitches although there were no missing stitches in the params mock-up. After I added the white embroidered logo, there was also very sloppy edges along with the missing stitch sections.

![IMG_0447 2](https://user-images.githubusercontent.com/75462171/125551805-65ca5d3b-3dc6-4c53-b780-78b1230583d7.jpeg)
![IMG_0529](https://user-images.githubusercontent.com/75462171/125551815-0a7760b1-0fba-44f5-b52b-352cabe3b5a6.jpeg)
![IMG_0528](https://user-images.githubusercontent.com/75462171/125551829-7448c9a6-b5ea-4640-8888-e958c39e341a.jpeg)

**Comment by wwderw** [comment]
Have to remember with any machine embroidery software, fabric/needle/thread interactions are not really taken into account with the visual simulations.  The proof is always going to be in the stitchout.

From what I can tell, it looks like the swoosh in a fill stitch.  That's a lot of density in such a small area.  I would first see if it is possible to do this in a satin stitch, the swoosh really needs to be a satin stitch.  Depending on what the stitch width is (not the overall width, but the width of the individual objects that make up the letters) as those too may need to be satin stitching.  

Depending on the pathing that the autofill did and the fabric that is being used and the amount (or lack thereof) of stabilizer, all contribute to the final result.

My first inclination would be to start there.
