### ISSUE TITLE
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0815C3C8>> ignored

### ISSUE THREAD

**Issue by Zazouch** [inkstitch/inkstitch#1274]
Hello. 
I have this message that appears when I try to change the angle of my embroidery stitches (although it worked 2 days ago ...).
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree .__ del__ of <shapely.strtree.STRtree instance at 0x0815C3C8 >> ignored
However, if I make 1 simple rectangle, it works. But with a more complex pattern it doesn't work.
I select only 1 object, it is not locked.
I retraced my form, tried with 1 other, the problem is still there
Does anyone know where the problem is coming from?
Thank you so much.

**Comment by kaalleen** [comment]
Thank you for reporting your issue here. This is a really old issue which we weren't able to fix yet. Have a look at this issue here to see the discussion: #578
