### ISSUE TITLE
Installation issue on Windows: failed to execute script pyi_rth_win32comgenpy

### ISSUE THREAD

**Issue by chulaentrecosturas** [inkstitch/inkstitch#1275]
I was able to add the ink/stitch extensions but when I try to use them, I get a pop up that says: failed to execute script pyi_rth_win32comgenpy

Any idea on how to fix it?

![capture](https://user-images.githubusercontent.com/87448767/125691474-9b7b324b-bf06-4813-b7a4-d15048174eb5.png)
![capture2](https://user-images.githubusercontent.com/87448767/125691480-cebf0b9b-ace5-4ec3-a1c9-50e1a2eb36a8.png)

**Comment by kaalleen** [comment]
I am not really sure why this is happening to you. Anybody else?
... Or could you yourself get it running by now?
