### ISSUE TITLE
Windows: Error loading Python DLL

### ISSUE THREAD

**Issue by Steve934** [inkstitch/inkstitch#1281]
I loaded the software and when I go to extensions/ink-stitch I don't find that chioce. Is there another way to load them?

**Comment by kaalleen** [comment]
Oh sorry. Yes, this has been changed. The add-on installation is now necessary for the thread palettes only. That's why it has been moved to Extensions > Ink/Stitch > Thread Color Management > Install thread color palettes for Inkscape

**Comment by Steve934** [comment]
Sorry it took so long to get back to this.When I try to run the program I get "Error loading Python DLL' C:\Users\Steve\AppData\Roaming\inkscape\extensions\inkstitch\bin\python38.dll". LoadLibrary:PyInstaller:FormatMessageW failed.
Can you help?Steve    On Thursday, July 29, 2021, 01:14:43 PM EDT, Kaalleen ***@***.***> wrote:  
 
 


Closed #1281.

**Comment by kaalleen** [comment]
Uh, ok. Thank you for your respond. This looks similar to issue #1301 
Which Windows and Inkscape version do you use?

**Comment by Steve934** [comment]
I use windows 7, inkscape 1.1 and inkstitch2.0.0Steve
    On Thursday, August 5, 2021, 03:48:14 PM EDT, Kaalleen ***@***.***> wrote:  
 
 


Uh, ok. Thank you for your respond. This looks similar to issue #1301
Which Windows and Inkscape version do you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Steve934** [comment]
I'm going to be out of town again starting Tuesday, maybe I will hear something by the time I get back?Steve
    On Thursday, August 5, 2021, 04:53:50 PM EDT, Stephen Browne ***@***.***> wrote:  
 
  I use windows 7, inkscape 1.1 and inkstitch2.0.0Steve
    On Thursday, August 5, 2021, 03:48:14 PM EDT, Kaalleen ***@***.***> wrote:  
 
 


Uh, ok. Thank you for your respond. This looks similar to issue #1301
Which Windows and Inkscape version do you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaalleen** [comment]
Sorry, you never received more answers. Ink/Stitch has been updated in te meantime. I'll close the issue, but if you are still seeing the error, please reopen.

**Comment by Steve934** [comment]
No problem, I got a new computer and it worked.Thanks Steve
    On Sunday, April 10, 2022, 08:26:39 AM EDT, Kaalleen ***@***.***> wrote:  
 
 


Closed #1281.
