### ISSUE TITLE
Error Fill

### ISSUE THREAD

**Issue by HppPrinters** [inkstitch/inkstitch#1284]
PLease assist me with this issue. i do not know what i am supposed to do. i tried converting to paths but i cant save in embroidery formats

path4323: error: Fill: This object is made up of unconnected shapes.  This is not allowed because Ink/Stitch doesn't know what order to stitch them in.  Please break this object up into separate shapes.

**Comment by kaalleen** [comment]
Select fill objects and run Extensions > Ink/Stitch > Fill Tools > Break apart fill objects this should solve your problem.
