### ISSUE TITLE
Sometimes AutoFill underpath and starting position wont work

### ISSUE THREAD

**Issue by jeffsamsr** [inkstitch/inkstitch#1292]
Example files are in the zip archive:

[Fill Start And Underpath Not Working.zip](https://github.com/inkstitch/inkstitch/files/6903117/Fill.Start.And.Underpath.Not.Working.zip)

Files:
**Fill Start And Underpath Not Working.svg**  _(simple example Inkscape document)_
**Underpath Missing - Endpoint Ok.png**  _(Screen print of underpath issue)_
**Stitch Angle At 45 Underpath Appears.png**  _(Screen print of underpath working when only stitch angle set to 45)_
**Startpoint Wrong At Bottom Left.png**  _(Screen print of startpoint issue)_
**Stitch Angle At 45 Startpoint Correct.png**  _(Screen print of startpoint working when only stitch angle set to 45)_

This issue occurs mysteriously with some shapes and not others. The 45 degree stitch angle fix is also arbitrary.  Some other angles seem to work as well.

The shape in the example file is a piece from a "Trace Bitmap..." operation. Tweaking the shape might also resolve the issue, so I am not halted for now, but I just wanted to get an example of this odd behavior into the hands of those that can possibly resolve it in future revisions.

Ink/Stitch is very impressive!  Thanks!

**Comment by kaalleen** [comment]
At certain angles the autofill algorithm has problems to get through narrow areas. That's why it will fall back to just render simply an outline around the object. This is a bit confusing in your case. Maybe we need to have a second look at the code.
