### ISSUE TITLE
error message Error Loading Python DLL LoadLibrary

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1301]
We received the following error message from a user on YouTube:
Melanie Tierney
I keep getting this error message when trying to select params :
Error Loading Python DLL
LoadLibrary: The specified module could not be found

I hope one of you knows what is going on. I will link this thread on youtube. 
Tina

**Comment by kaalleen** [comment]
@Tina-Chris Do you know if this is still an issue? Sorry, that there has been no answer until now. I must have missed it.

**Comment by Tina-Chris** [comment]
I'm not sure. I asked on youtube, we will see.

**Comment by kaalleen** [comment]
No further info. There has been a new release after that, which has hopefully fixed the issue?!
