### ISSUE TITLE
Windows: setlocale()

### ISSUE THREAD

**Issue by syfauna** [inkstitch/inkstitch#1302]
wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment]
Have a look over here, this is where this issue has been discussed: #1232

**Comment by kaalleen** [comment]
I'll close this issue because there will be a fix in the upcoming release. Please reopen, if this is showing up again.
