### ISSUE TITLE
Windows installation: PYTHONPATH

### ISSUE THREAD

**Issue by nairbdryb** [inkstitch/inkstitch#1303]
when I select the Params option in the extension menu i get the following error:

Python path configuration:
  PYTHONHOME = 'C:\Users\isith\AppData\Roaming\inkscape\extensions\inkstitch\bin'
  PYTHONPATH = (not set)
  program name = 'C:\Users\isith\AppData\Roaming\inkscape\extensions\inkstitch\bin\inkstitch.exe'
  isolated = 0
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = 'C:\\Users\\isith\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\bin\\inkstitch.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\Users\\isith\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\bin\\inkstitch.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\isith\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\bin\\base_library.zip',
    'C:\\Users\\isith\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\bin\\lib-dynload',
    'C:\\Users\\isith\\AppData\\Roaming\\inkscape\\extensions\\inkstitch\\bin',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002178 (most recent call first):
<no Python frame>

**Comment by nairbdryb** [comment]
Solved: I updated inkscape by reinstalling it. as part of the install process you need to make sure "Add to path" is checked.

**Comment by kaalleen** [comment]
Great, thank you for your feedback. I didn't know the Inkscape installer on Windows would have this option.
