### ISSUE TITLE
Unwanted object exports on main head

### ISSUE THREAD

**Issue by bigredfrog** [inkstitch/inkstitch#1304]
As disucssed elsewhere in attempting to set up a dev environment 

https://github.com/inkstitch/inkstitch/issues/1293

I am consistantly seeing unexpected layer exports that I had not seen in my original SVG -> PES workflow on the release install, and can indeed not see then when jumping to the v2.0.0 tag, but do see them on everything recent.

I will look to isolate the issue a little more with screen captures and go from there, maybe with some commit binary chopping.

Issue is apparent in simualtion view, pdf export, save as .pes and in Stitch plan preview.

With the intended selected layers enabled ( so open eye on object selector ) I only have my basting rectangle and a very wide basting underlay turned on, so the live display in inkscape looks like

![image](https://user-images.githubusercontent.com/7328740/128095051-7e4fa6fc-75ba-4bc1-b57e-d6d0bac04c32.png)

However, what we see from the stitch plan preview has extra objects turned, on, note black outline and blue fill

![image](https://user-images.githubusercontent.com/7328740/128095151-965a804c-e8fa-4d4d-b979-2c28f2497de6.png)

Those extras are at least the following as below. sillouter, sillinner and border. Cutter may also be rendered, but no easy way to tell

![image](https://user-images.githubusercontent.com/7328740/128095241-05601e57-968c-4d86-84be-bec823151c22.png)

As you can see they should be off due to the closed eye.

If I turn those on ( eyes open ) in the objects then it looks like this in the normal SVG view

![image](https://user-images.githubusercontent.com/7328740/128095362-55cb7d50-0787-4110-8145-6035f157b99b.png)

I will continue to dig into the debugging side to slowly isolate further and see if I can tell when they get acted upon, ignoring their visible state. As commented in the normal release and the v2.0.0 tag built locally, it all behaves correctly.

**Comment by bigredfrog** [comment]
Making some assumptions on where these tags live, but if I checkout on 

dev-build-kaalleen-current-layer-issue, the export in GOOD

if I checkout on 

dev-build-kaalleen-style-tag

the export is bad

I will look at the commits between those two next to help build my understanding of the extension and see if I can see a smoking gun...

**Comment by bigredfrog** [comment]
Brute force binary chopped to commit in question is 11ce14f

Just binary chopped the commit range until I isolated the working / not working

https://github.com/inkstitch/inkstitch/commit/11ce14f083b6bd16bcec0534feb888f4fd9e3bc9

![screenshot-github com-2021 08 03-20_56_41](https://user-images.githubusercontent.com/7328740/128105397-16179535-8528-4533-a9a9-72dfac669597.png)

**Comment by bigredfrog** [comment]
Change in validation in this code

       if (node.tag in [EMBROIDERABLE_TAGS, SVG_GROUP_TAG] and
                element.get_style('display', 'inline') is None):

Must be too permisive.

Will add some in line A/B testing debug to exercise diagnostic options.

**Comment by bigredfrog** [comment]
I can confirm that the old check gives a different result, a rejection to four elements that the new test accepts the continuation of the function.

What I don't understand is why the first stansa in the test is returning false

        if (node.tag in [EMBROIDERABLE_TAGS, SVG_GROUP_TAG] and
                element.get_style('display', 'inline') is None):
            return []

where node.tag  is {http://www.w3.org/2000/svg}path

and the tags are
('{http://www.w3.org/2000/svg}path', '{http://www.w3.org/2000/svg}polyline', '{http://www.w3.org/2000/svg}rect', '{http://www.w3.org/2000/svg}ellipse', '{http://www.w3.org/2000/svg}circle')

It should be True

Will look to check base types

**Comment by bigredfrog** [comment]
OK, so that took longer than it should of

This test is effectively establishing a list of lists, not a concatenation of lists.

node.tag in [EMBROIDERABLE_TAGS, SVG_GROUP_TAG]

So it will never return true.

Now to see if I can work out how to put a submission up for the fix...

**Comment by bigredfrog** [comment]
Its a little more complicated as EMBROIDERABLE_TAGS is a list and SVG_GROUP_TAG is a single str

**Comment by bigredfrog** [comment]
I may of eaten my own tail. As I don't know what the original intent of the logic is here, I do believe the code is not doing what is intended but need some guidance from @kaalleen it is evident that making that a sane concatenation of tuples breaks the intentional logic.

**Comment by kaalleen** [comment]
Thanks for pointing this out. You are just so right about this.

I think it is time to ask you, if you want to contribute directly by uploading pull requests. We can send you an invitation, so you get write access to the Ink/Stitch repository.

**Comment by bigredfrog** [comment]
Still spelunking around, so no rush.

I am fine with having write access, and will look to follow norms, but at the moment, I am cornering issues more than fixing them.

I want to go after that color anomily once I can weild head cleanly.

I need to see if your fix "fixes" things for my example, as my own spin above, did not.

**Comment by bigredfrog** [comment]
Tested locally, change on head of main, looks good for stitch preview and pdf export.

Will close on commit of

https://github.com/inkstitch/inkstitch/pull/1305

**Comment by lexelby** [comment]
Great troubleshooting, thank you!

**Comment by bigredfrog** [comment]
Closing as MR is merged
