### ISSUE TITLE
Meistergram 900XL

### ISSUE THREAD

**Issue by seelady** [inkstitch/inkstitch#1311]
anybody know where to find a monitor for this machine

**Comment by lexelby** [comment]
Hi!  I hope you're able to find the part you're looking for.  We don't really do this kind of thing here, so I'm going to go ahead and close this.  If you're on Facebook, maybe try the Buy/Sell Used Embroidery Equipment group.  You also might want to check out sewmanyparts.com, I've gotten parts from them before.
