### ISSUE TITLE
EXP trim problem

### ISSUE THREAD

**Issue by cody82** [inkstitch/inkstitch#1315]
I am new to stitching and have the following problem with Inkstich v2.0.0 on linux.

Please have a look at this preview:
![image](https://user-images.githubusercontent.com/363688/128942580-9bc403d2-d373-4072-8e71-1a9f23183710.png)
Note: The black stitch is exactly on the edge of the red area.
But when exporting to .exp and stitching it on a Chicago 7, it looks like that:
![image](https://user-images.githubusercontent.com/363688/128942903-61c731f8-12c2-4949-b8fa-74791e6afb40.png)
There is a gap between the black border on the right side.
Decoding the exp shows that this is not the machine's fault but indeed it also looks like this in the exp:
![image](https://user-images.githubusercontent.com/363688/128943176-40ecd3cb-b51c-43db-8e7a-05f10a015a76.png)
So it looks like the different stitch types are shifted on the x axis. I think the preview should match the exported file.
What is the problem here?

**Comment by kaalleen** [comment]
Thanks for your report and the images. An interesting catch!

It is recommended to use a real satin column around your fill object instead of the zig zag. It has the two advantages, that you can adapt the shape independently and also the satin column looks much better especially around the edges.

To do so, duplicate your fill object and remove the fill while you add a stroke to it. Also set the width. Then run Ink/Stitch > Satin Tools < Convert line to satin

**Comment by tyrosinase** [comment]
I'm not sure that's the OP's problem here though... I'm now considering whether my own past problems with seemingly-asymmetrical pull compensation have really been the machine faithfully executing something with an unexpected offset in the X axis.

**Comment by kaalleen** [comment]
I didn't mean to say it was his fault. I just wanted to give an idea how to fix it on his side before someone gets the chance to work on the code.

**Comment by cody82** [comment]
@kaalleen I used the satin method you suggested and indeed the border is in the right place then. Thank you, I did not know what satin is.

But the problem is still there. But it does not happen with all shapes.If I just create a filled rectangle or circle the border is in the right place.

So here is the file where it happens:
[fogel2.zip](https://github.com/inkstitch/inkstitch/files/6970026/fogel2.zip)
Can anyone reproduce it?

**Comment by lexelby** [comment]
This definitely looks like a bug in the EXP export code.  I see that that machine can read only EXP. :(

**Comment by lexelby** [comment]
I wonder if we have a flawed understanding of how the exp format works.  I'm especially wondering about 0x80 0x00 0x07 0x00 for trim.  Can you measure how far the shift on the X axis is? If it's 0.7mm, then I'm highly suspicious.

**Comment by cody82** [comment]
I think you are right. The offset is about 0.7mm.
The decoder I used does not interpret 0x80 0x80 and 0x07 0x00 is just a normal stitch. Using another decoder(https://htmtopdf.herokuapp.com/embroidery/) the result looks right.

But at least the Chicago 7 obviously does not know about trim.
The web(https://edutechwiki.unige.ch/en/Embroidery_format_EXP) says 0x80 0x80 is END.

What is 0x80 0x80 0x07 0x00 actually supposed to do?

**Comment by lexelby** [comment]
Awesome!  It's supposed to trim the thread.  Most machines will trim anyway before a color change, but pyembroidery writes a trim instruction just in case.

If you're feeling adventurous, how about this: take the EXP written by ink/stitch, open it in a text editor, and change that 0x07 0x00 to 0x00 0x00.  Does that make it sew correctly?

**Comment by cody82** [comment]
I think the Chicago 7 has no trim function.
I completely removed 0x80 0x80 0x07 0x00 and this is the result:
![image](https://user-images.githubusercontent.com/363688/129410335-381d4632-3e47-4119-a99b-4b3b2f4143bb.png)
Not too much difference, but 0.7mm is not too much anyway.
Will have to check if the right file was stitched because I did not stitch myself. Files may got mixed up because of similar filename.

**Comment by lexelby** [comment]
The tough part is that the gap could also be caused by fabric distortion, which is totally normal. We might need to craft a special file to really nail down for certain whether then 0x07 matters.

**Comment by Tina-Chris** [comment]
@cody82 to your green stitch out, how does your exp exported file look like? like the one in blue on top, or different now?

**Comment by cody82** [comment]
@Tina-Chris No, it looks like the preview in the first picture. But as mentioned the decoder might be buggy.
I tried to stitch a test file with multiple 0x80 0x80 0x07 0x00 to see if the errors accumulate, but the machine failed to stitch it because of other reasons. So I will make a simpler test file in the next days.
Right now it is still not clear to me if the machine does not support the trim command or if the gap is just a result of mechanical inaccuracy.

**Comment by lexelby** [comment]
I tried to find an example of an EXP file "in the wild".  I went and downloaded a couple of the designs I had previously purchased from emblibrary.com, selecting EXP from the dropdown.  

Interestingly, I found no trim commands in the EXP files, even though the equivalent design in other formats definitely had trims.  Where I expected trims, I found only jumps.  It wasn't even a case where they forced 3 jumps to equsl a trim like in a DST file.  Maybe EXP doesn't actually have a trim command...?  The Chicago 7 definitely does not support trim commands in any case.

If it is indeed true that the EXP format doesn't actually have a trim command, then that easily explains the shifting you're seeing. The 0x80 0x80 0x07 0x00 could be interpreted as a relative move of 7 tenths of a millimeter in the X axis, and because all stitch commands in EXP are relative moves, the entire rest of the design would be off.

**Comment by cody82** [comment]
Here is my final test result:
![test2](https://user-images.githubusercontent.com/363688/129942956-4fbd1671-a56f-46e0-ad31-2070af9ea8d6.jpg)
The lines are shifted to the right from top to bottom but in Inkstitch they are aligned. So at least the Chicago 7 does not understand the trim command.

**Comment by lexelby** [comment]
Perfect.  I think that means the 0x07 needs to go.  Thanks for testing this out so carefully!

I'm not sure I understand the last bit.  When do you get garbage?  What were you expecting instead?

**Comment by cody82** [comment]
I did not try it myself. So I think the machine continues stitching but it does not move in X and Y direction anymore. It just stitches on the same spot which results in a big knot.

**Comment by lexelby** [comment]
That's weird... At what point in the design does it do that?

**Comment by cody82** [comment]
I think it does that on each trim/color change. But I can take a look at it myself to be sure. It does not happen on downloaded exp files that do not contain 0x80 0x80 0x07 0x00.

**Comment by cody82** [comment]
Summary:

This is a bug in the Chicago 7. It can not handle 0x80 0x80 0x07 0x00. There is a firmware update to fix this issue but it cant be applied by the user. An option not to export trims would be a good feature.
