### ISSUE TITLE
unconnect error on text from inkscape

### ISSUE THREAD

**Issue by BDCCC** [inkstitch/inkstitch#1316]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kaalleen** [comment]
Thanks for your error report. This one we have seen before and it has been fixed for the next release.
For now it could help if you reapply the color of your object.

**Comment by BDCCC** [comment]
What is the color only started out black and white. Will changing the color still fix it ? > Thanks for your error report. This one we have seen before and it has been fixed for the next release.
> 
> For now it could help if you reapply the color of your object.

**Comment by kaalleen** [comment]
Yes, it should fix the break apart function for your object.

Right now, I assume your object has no explicit style setting (which is very likely, especially if you started out with black and white).

**Comment by BDCCC** [comment]
I've done it all and I keep receiving a error message in Params saying "flowPara1393: object flowpara1393 has empty 'd' attribute, please delete this object from your document"

**Comment by kaalleen** [comment]
Ok. This is an other one. Try to run Extensions > Ink/Stitch > Troubleshoot > Cleanup document.

**Comment by kaalleen** [comment]
I'll close this issue, since it has been fixed for the next release. Please reopen, if the error still shows up in the next version of Ink/Stitch.
