### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by SAANNAWITHCOMPUTERISSUES** [inkstitch/inkstitch#1317]
So I wanted to emborder a design and I install ink stitch, my computer keeps saying its a virus and a threat,  also when I download it the files show as a file of a bunch internet explorer files, when I extract them and bring it into the ink scape extractions and then I restart the app and open it back up. after that ink stitch would be there depending if I did it right because it didn't show up the last time, But for some reason every time the ink stitch has gray areas and wont work for me at all. please help me or show me another better way.

**Comment by kaalleen** [comment]
This is most probably because your system thinks Ink/Stitch is a virus and deletes the most important files: see https://github.com/inkstitch/inkstitch/issues/710#issuecomment-633033997

**Comment by SAANNAWITHCOMPUTERISSUES** [comment]
I have no idea how to fix it

**Comment by kaalleen** [comment]
Try to follow this tutorial here: https://www.youtube.com/watch?v=vhgvshv6r6M
Go to minute 3:25
Hope it helps

**Comment by kaalleen** [comment]
I'm going to close this issue. If the provided answer didn't help, please reopen.
