### ISSUE TITLE
Attempt to add new font to Lettering

### ISSUE THREAD

**Issue by Project-Anonymous** [inkstitch/inkstitch#1320]
Hello, I am trying follow the instructions on the ink/stitch website (https://inkstitch.org/tutorials/font-creation/) to add a font to my lettering GUI. I've tried editing just a few glyphs and testing. Only issue is, when I go to test my new font in lettering, I get a fault: This font has no available font variant. Please update or remove the font.

What does this mean? What am I doing wrong? I can't seem to find what this error means or how to fix it. 

Thank you for any help!
-Project Anonymous

**Comment by kaalleen** [comment]
Hey you two. First, thanks for your videos on YouTube. I believe this is a great source for a lot of people to get started with Ink/Stitch.

The font needs to be in a folder containing the following files:
* →.svg
* font.json
* preview.png (300x20 px)
* (LICENSE)

The name of the svg file is very important for Ink/Stitch to recognize the font variant. It also defines the stitch direction (for the font to be stitched from right to left use ←.svg).

Hope this clears things up a little. If you have more questions, please come back to us. We are happy to help.

**Comment by Project-Anonymous** [comment]
Wow! Thank you so much!! We were not saving the SVG file as "→.svg," which is clearly in the instructions... I guess we just thought that was a placeholder for whatever you were going to name the font. 

Thank you again for helping us figure this out, now we can do a video on this subject and hopefully help others!!!

v/r, Project Anonymous
