### ISSUE TITLE
Yarn length measure

### ISSUE THREAD

**Issue by Nitrama** [inkstitch/inkstitch#1326]
Hey,

is there an option to find out how much thread is used for embroidery. I have seen such a function in other programs.

**Comment by lexelby** [comment]
This is a feature we've had on the back-burner for quite awhile.  I'll be honest though, I don't really know how to go about doing this.  So many things factor into the amount of thread used:

* tension, especially bobbin tension
* thickness of the fabric
* thread weight

For example, when sewing a satin, the loosest vs tightest bobbin tension could change the amount of thread used by up to a factor of 3.

And then there's another question, how do we test whether we got it right?  Do I measure a length of thread, roll it up on a spool, sew a design, and then measure what's left?  I'd have to factor in the length of thread used in the thread path on top... Am I overthinking this?

A question for you... What would you use a thread usage feature for?  How would it help you?

**Comment by tyrosinase** [comment]
I feel like it should be something like the time estimates in the PDF: you can set the factors for tension and number of stitches that it uses to calculate the guesstimate. Because tbh I'm pretty sure it's only useful in the sense of comparing to other designs that use the same calculation, but that still can be a useful thing.

**Comment by Nitrama** [comment]
> This is a feature we've had on the back-burner for quite awhile. I'll be honest though, I don't really know how to go about doing this. So many things factor into the amount of thread used:
> 
>     * tension, especially bobbin tension
> 
>     * thickness of the fabric
> 
>     * thread weight
> 
> 
> For example, when sewing a satin, the loosest vs tightest bobbin tension could change the amount of thread used by up to a factor of 3.
> 
> And then there's another question, how do we test whether we got it right? Do I measure a length of thread, roll it up on a spool, sew a design, and then measure what's left? I'd have to factor in the length of thread used in the thread path on top... Am I overthinking this?
> 
> A question for you... What would you use a thread usage feature for? How would it help you?

hey,

yes, you are thinking too much. 😅

I embroider and then sell that. I just want to know approximately how much thread I'm going to use (even if it's the smallest cost factor).

Personally, I always embroider with the same thread tension, fabric and thread.
It would be enough for me if a "standard" is inside and you can simply link it with a multiplier.

As an example.
In the export PDF it says that I use 1 meter of yarn. Now I embroider once and measure before 1 meter. And see that I only need half. So I give the export of the PDF simply 0.5 as a multiplier.

So everyone can simply write down how the multiplier for the different settings on his machine is. And I think that would be enough for the beginning.

**Comment by lexelby** [comment]
Okay, that's something to go on.  Thanks!

**Comment by lexelby** [comment]
And I am shocked to be told I am overthinking things.  SHOCKED, I tell you! ;)
