### ISSUE TITLE
Ink/Stitch experienced an unexpected error.

### ISSUE THREAD

**Issue by ven-stoich** [inkstitch/inkstitch#1327]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "wxString::Format("%.3f", 1.23).find(str) != wxString::npos" failed at ..\..\src\common\intl.cpp(1633) in `anonymous-namespace'::GetInfoFromLCID(): Decimal separator mismatch -- did you use setlocale()?If so, use wxLocale to change the locale instead.

**Comment by tyrosinase** [comment]
I bet this is the same thing as #1232, in which case there's a solution for it in that issue.

**Comment by ven-stoich** [comment]
Thank you very much...  








 >-------- Оригинално писмо --------

 >От: Tyrosinase ***@***.***

 >Относно: Re: [inkstitch/inkstitch] Ink/Stitch experienced an unexpected error.
 (#1327)

 >До: inkstitch/inkstitch  

 >Изпратено на: 22.08.2021 15:50



 
 
  
  
  
I bet this is the same thing as  #1232 , in which case there's a solution for it in that issue.  
   —
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS  or  Android .
