### ISSUE TITLE
Error - Params

### ISSUE THREAD

**Issue by Stef12341234** [inkstitch/inkstitch#1328]
Hi, I am still new to inkstitch. I just downloaded Inkscape and Inkstitch according to the steps on the website on my Win10 Laptop.  When I now followed this tutorial https://www.youtube.com/watch?v=U5htzWZSjA8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=4
I created a circle, 
object to path, 
Extensions - Ink/Stitch - Params 
Then I get the following Error below. Can anyone help me out what is wrong here? Thank you in advance!!

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

----
I have found that this should be the same problem #1232
However I still seem to do something wrong because I cant get it working(
I am sorry to ask such a basic question, but what do i have to do with the fixing file here https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186 ?
I downloaded it and extracted in the extensions folder. Then I was asked if I want to replace the old files and I said yes. Should i have first deleted the regular inkstitch file from the folder or extract both files in the extension folder separately without replacing? When i reopen now inkscape the inkstitch extention optins are grey and i cant click on them.
Thanks so much for your help!!

**Comment by Stef12341234** [comment]
I have found that this should be the same problem https://github.com/inkstitch/inkstitch/issues/1232
However I still seem to do something wrong because I cant get it working( 
I am sorry to ask such a basic question, but what do i have to do with the fixing file here https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186 ?
I downloaded it and extracted in the extensions folder. Then I was asked if I want to replace the old files and I said yes. Should i have first deleted the regular inkstitch file from the folder or extract both files in the extension folder separately without replacing? When i reopen now inkscape the inkstitch extention optins are grey and i cant click on them. 
Thanks so much for your help!!

**Comment by tyrosinase** [comment]
I'm not a Windows user but I've seen this problem go by a few times, such as #828 

I'm not sure if the extensions subdirectory issue has been fixed, but in case it's not you might try that.

**Comment by kaalleen** [comment]
Ink/Stitch should be able to live in a subdirectory now.

When you install a new Ink/Stitch version, it is best to remove the old files beforehand.
Greyed out menus in windows are mostly caused by your systems virus detection, it thinks Ink/Stitch is a virus and removes important files. In your virus programm you have to add Ink/Stitch to the white list if you don't want it to be deleted.

**Comment by tyrosinase** [comment]
You'd think by now I'd remember that the problem is almost always antivirus with Windows, but somehow I don't.

**Comment by Stef12341234** [comment]
Yeyy it works!! Thanks so much for your help! I really appreciate it! The problem really was the antivirus software deleting automatically one file of the inkstitch folder...
Thank you :D
