### ISSUE TITLE
Fill and Satin Columns

### ISSUE THREAD

**Issue by Lor19** [inkstitch/inkstitch#1332]
When I use fill and satin columns on the same document and go into params, there is an error message saying 'Object has a fill, but should not'.

If I uncheck the 'custom satin columns box' the image will render in params. However the satin column render incorrectly - with the two rails separate and all the rungs showing. I've tried everything and am desperate for a solution. Can anyone please help/

Thank you

**Comment by kaalleen** [comment]
Can you check in the fill and stroke panel if the fill is set to none (x)?

**Comment by kaalleen** [comment]
There hasn't been  an answer for a while. I'll close the issue. Please reopen, if you have more questions.
