### ISSUE TITLE
extensions save a copy error

### ISSUE THREAD

**Issue by AliShukur** [inkstitch/inkstitch#1333]
lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range
![2021-08-28 01_10_00-](https://user-images.githubusercontent.com/28509162/131193571-2bad0a8f-407a-41fb-91c7-126b906461a3.png)

**Comment by kaalleen** [comment]
Thank you for your error reports. This error has been reported several times after the last release. It usually comes up, when you try to render only text or images. Ink/Stitch can only work with them, when they have been converted to vector graphics.

* For text consider to use the Ink/Stitch lettering tool.
* For images you can either manually trace your image with the bezier tool or try the Inkscape Bitmap tracing function found in the path menu. If you use the tracing method, you may want to use the Ink/Stitch > Fill Tools > Break apart fill objects function afterwards.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
