### ISSUE TITLE
How do I fix this error message? lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

### ISSUE THREAD

**Issue by Tlembroid** [inkstitch/inkstitch#1335]
lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

I am receiving this error when I am trying to save my svg file to a PES

I am a beginner to Inkstitch and cannot figure out how to fix this.  Will it stitch ok or do I need to fix something?
I have attached the SVG and the PES file
[KAOS Tennis Ball 2 SVG File.zip](https://github.com/inkstitch/inkstitch/files/7094505/KAOS.Tennis.Ball.2.SVG.File.zip)
[KAOS Tennis Ball 2 PES file.zip](https://github.com/inkstitch/inkstitch/files/7094506/KAOS.Tennis.Ball.2.PES.file.zip)

I have since recreated the file and simplified it and still get the same error message.
I imported a tennis ball image, did a bitmap trace, created a fill layer and only did the fill layer for stitching, no outline or satin stitching.  It stitches fine, in Params, giving no errors, i go to save it as a PES and i always get this error, n matter the project
[Tennis Ball fill only 45 degree fill PES.zip](https://github.com/inkstitch/inkstitch/files/7095012/Tennis.Ball.fill.only.45.degree.fill.PES.zip)
[Tennis Ball fill only 45 degree fill  SVG.zip](https://github.com/inkstitch/inkstitch/files/7095015/Tennis.Ball.fill.only.45.degree.fill.SVG.zip)

**Comment by kaalleen** [comment]
Luckily this is only a warning and not an error message. It will be fixed in the next release.
Does it in your case actually prevent the pes file from being created or do you get a functioning embroidery file?

**Comment by LuciaStella13** [comment]
Hello!

I am also new to InkStitch; I have previously used embroidery software on my PC at work but needed something for my Mac at home.  I have received the same error message when saving to VP3 format.  The files show up in the folder, but I haven't tried them on my machine yet.  Is it safe to test them out?

Thank you!

Luz

**Comment by tyrosinase** [comment]
It'll be fine; "deprecation" just means "this is not the best way to do this because it may not be supported in the future," which is why it's only a warning.

If you open the VP3 (or PES) in Ink/Stitch you'll see what actually got written.

**Comment by LuciaStella13** [comment]
The VP3 looks correct when I open it in Ink/Stitch; my other embroidery software can read the file, too.

**Comment by kaalleen** [comment]
Nice, thanks for the feedback.
