### ISSUE TITLE
fill: ValueError: Sequences of multi-polygons are not valid arguments

### ISSUE THREAD

**Issue by rpgnobody** [inkstitch/inkstitch#1336]
Impossible to save a .PES file

nk/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 55, in effect
  File "lib\extensions\base.py", line 207, in elements_to_patches
  File "lib\elements\element.py", line 362, in embroider
  File "lib\elements\element.py", line 418, in validate
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 164, in shape
  File "shapely\geometry\multipolygon.py", line 62, in __init__
  File "shapely\geometry\multipolygon.py", line 177, in geos_multipolygon_from_polygons
ValueError: Sequences of multi-polygons are not valid arguments

**Comment by tyrosinase** [comment]
That happens on complex shapes sometimes; I think this should fix it: #1215

**Comment by rpgnobody** [comment]
it is not a complex file
[Logo RPG.zip](https://github.com/inkstitch/inkstitch/files/7117374/Logo.RPG.zip)

**Comment by tyrosinase** [comment]
It is, though it's perhaps not immediately obvious.

The stripes are all connected by a zero-width area, which Ink/Stitch can't figure out how to fit stitches into. If you select each color individually and hit Path > Union it will eliminate that area (though it will also clear any custom Ink/Stitch parameters you've set). It's maybe something Ink/Stitch should do for itself behind the scenes to get rid of this kind of invisible connection (@kaalleen?)

**Comment by rpgnobody** [comment]
problem solved
bad parameter in definition "style et contour"
thanks

**Comment by kaalleen** [comment]
> It's maybe something Ink/Stitch should do for itself behind the scenes to get rid of this kind of invisible connection (@kaalleen?)

Definitely yes. I'll reopen this issue until we get a chance to work on it.

**Comment by kaalleen** [comment]
I tested the file with the fix for #1215
Ink/Stitch then will give a crossing border issue. It can simply be fixed by using the break apart function.
Since we have an other open feature request to automatically perform the break apart function on invalid fill shapes, I think we can close the issue now.
