### ISSUE TITLE
Despite two colors I have 6 color changes - what to do?

### ISSUE THREAD

**Issue by trashmanb45** [inkstitch/inkstitch#1337]
Hallo,
I have filled a path in Inkstitch with one color, but in the preview this now leads to 6 color changes - ideally exactly one color change would be ideal (from black to pink)

I have already adjusted the order of the layers so that first one color should be stitched, then the other. But unfortunately, this has also brought nothing.

Can anyone tell me how to solve this?

Thank you very much for your support.
![inkstitch_minnie](https://user-images.githubusercontent.com/90352240/132577905-80e1781d-55b1-4e9d-88e1-7e4025a0d489.JPG)
![inkstitch_minnie_2](https://user-images.githubusercontent.com/90352240/132577908-90512b49-8189-4783-88d0-ccecad6c9928.JPG)

**Comment by aahulby** [comment]
Newbie here too. Having the same issue.

**Comment by kaalleen** [comment]
To stitch all elements of the same color at once, you will have to reorder them in the object panel. Ink/Stitch stitches them out in exactly that order (from bottom to top). A fast and easy way to order objects by color:

- select one object
- Right click -> Select Same -> (in your case:) choose "fill color"
  This will select all elements with the same fill color
- Last run: Ink/Stitch > Edit > Re-stack objects in order of selection

Repeat for the other color.

To optimize your stitch path even better, you can also manually select the option in desired order and run the re-stacking function after that.

**Comment by kaalleen** [comment]
I'll close this issue now. Please reopen if the provided answer wasn't sufficient.
