### ISSUE TITLE
Error `NoneType` during svg save as copy

### ISSUE THREAD

**Issue by songz** [inkstitch/inkstitch#1339]
# Reproduce

1. Unzip and open svg file: [logo-code.zip](https://github.com/inkstitch/inkstitch/files/7148605/logo-code.zip)
2. File  -> save a copy (Select Ink/Stitch: Brother Embroidery Format .pes)

Error Output:

```
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (linux)


Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/simulator.py", line 17, in effect
  File "lib/extensions/base.py", line 184, in get_elements
  File "lib/extensions/base.py", line 181, in get_nodes
  File "lib/extensions/base.py", line 168, in descendants
  File "lib/extensions/base.py", line 141, in descendants
  File "lib/elements/element.py", line 92, in __init__
  File "lib/elements/element.py", line 124, in get_param
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by kaalleen** [comment]
Thank you for the error report and especially your file.

@lexelby if we fix the above mentioned error, we face a very interesting issue. Objects in this file will not be rendered due to an issue with specified_style not recognizing the fill declared in a parent group with an inline style tag.

**Comment by lexelby** [comment]
Huh, I'm a little lost here.  First, I don't understand how this exception is happening in v2.0.0.  How can `self.node.get(INKSTITCH_ATTRIBS[param], "")` be returning None?

And can you explain a bit more about the style problem?  I thought the whole thing with specified_style was that it got everything, including styles on parents.....

**Comment by kaalleen** [comment]
It's trying to read the comment in the svg file. We still need to work on the element selection.

> I thought the whole thing with specified_style was that it got everything, including styles on parents.....

I thought so too... in this case it seems to fail - or I am missing something.
