### ISSUE TITLE
Nonexistent object crosses over itself

### ISSUE THREAD

**Issue by hoesgarth** [inkstitch/inkstitch#1343]
Troubleshooting objects indicates an object outside of my canvas crosses over itself and is preventing params.
<img width="1440" alt="Screen Shot 2021-09-16 at 11 34 40 AM" src="https://user-images.githubusercontent.com/83088905/133641809-db91297e-f404-4d16-8009-ced8e0cb6873.png">

**Comment by tyrosinase** [comment]
Sometimes you end up with a zero-item group, and you have to tab through (or look at the XML, but tab is usually easiest) until you see "Group of 0 items." Then just delete it.

Dragging the selector box doesn't catch them, but tab recognizes them.
