### ISSUE TITLE
Save .png as .jef fails

### ISSUE THREAD

**Issue by AlexandreBerchemin** [inkstitch/inkstitch#1345]
Hello,

I opened a .png file in inkspace. 
![kaamelott](https://user-images.githubusercontent.com/90931637/133840572-8091b843-a53a-468b-9dab-8fbefad2fe7e.png)

I then Saved as .jef format file and i get the following error message.
I run on Windows 10

Thank you for your help

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
This is a known problem: #1307 has some discussion about what to do next.

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.

**Comment by AlexandreBerchemin** [comment]
Thank you !

**Comment by AlexandreBerchemin** [comment]
> This is a known problem: #1307 has some discussion about what to do next.

I forgot to thank you for the link you shared. It helped me in solving the issue !
