### ISSUE TITLE
Params not working 

### ISSUE THREAD

**Issue by Parodi12** [inkstitch/inkstitch#1347]
Everytime I click params nothing happens , not even an error message. I can see the cursor loading for a second or two but after that nothing comes up . I haven’t been able to use this feature at all.

**Comment by kaalleen** [comment]
Are you on Linux?
https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds

**Comment by dool1002** [comment]
I am using Ubuntu (Linux) and I am experiencing the same problem. 
I tried using the suggested link with the command (via Terminal), still giving the same issue.

*** I believe Wayland is more server side and does not start by default on the client side. I could be mistaken.
*** I think it has to do with the Snap directories....

**Comment by kaalleen** [comment]
Permission error? Hm... could you check the permissions of the inkstitch executable (/home/unidul/.config/inkscape/extensions/inkstitch-v2.0.0-linux-en_US/inkstitch/bin/inkstitch)?

**Comment by dool1002** [comment]
Thanks for getting back to me:
The Inkstitch Properties is a follow:
Owner: Me
Access: Read and Write
Group: unidul
Access: Read-only
Others
Access: Read-only
Execute: [checked] Allow executing files as program
Security context: unknown

I hope this helps. Let me know if there is any other info that is required...

**Comment by kaalleen** [comment]
I know this is so long ago. So sorry you didn't get more answers. Could you solve your problem in the meantime?

**Comment by lexelby** [comment]
Let's go ahead and close this for now, but we can reopen if the problem still exists.
