### ISSUE TITLE
Satin stitch start stop

### ISSUE THREAD

**Issue by deenkay1977** [inkstitch/inkstitch#1349]
How do you change a stitch start n stop point?

**Comment by tyrosinase** [comment]
If you just want to start from the other end: `Path > Reverse`

**Comment by deenkay1977** [comment]
It starts and stops on a curved corner and I want it to start and stop on a straight side

**Comment by deenkay1977** [comment]
starts and stops on a curved corner and I want it to start and stop on a straight side 
![60833C29-DDE9-44BD-ACD0-CA3BC24CC173](https://user-images.githubusercontent.com/91089086/134055804-de5d03de-11be-46f9-a95e-b08217155ec0.jpeg)

**Comment by tyrosinase** [comment]
Oh, edit the lines to join them up again, then break them in a better spot. Or if you've done the Convert Line To Satin (or whatever that's called) recently and it's still in your undo history, undo it, break the line where you want it to start/stop, and then redo the line-to-satin.

**Comment by deenkay1977** [comment]
Ok I undid the convert to satin but I don’t know how to do the break the line

**Comment by tyrosinase** [comment]
Easy peasy: go in with the node editing tool, and just double-click on the line where you want the new node to be. Then click the break node button.

If you're not familiar with Inkscape this will walk you through a bit of that sort of thing, and show you what those tools and buttons are: https://silverseams.com/2020/03/monogramming-without-a-font/

(It's geared toward converting stuff into a mix of satin and bean/running stitches, so it does manually some of what Auto-route Satin will do automatically, but you don't have to worry about that at this point.)

**Comment by kaalleen** [comment]
I suppose this has been solved? If not, please reopen the issue.
