### ISSUE TITLE
Trim jump stitches?

### ISSUE THREAD

**Issue by Robotorium** [inkstitch/inkstitch#1354]
Hey hey, I have a Brother V3 which has an option to trim jump stitches. For whatever reason, it doesn't seem to detect jump stitches in the file, so it doesn't trim them. I've had one file where it did recognise them, and I thought it was because that file did contain one item that was satin (where I ticked "trim jump stitches") but I tried that again and it didn't detect the jump stitches again.

Any ideas? Thanks!

**Comment by claudinepeyrat06** [comment]
No idea, but I have the same problem with my V3 and inkstitch generated pes file. If I don't put a trim command, a jump is a jump whatever its length ( and I did activate the trim jump stitches on the machine).

**Comment by Robotorium** [comment]
Can I ask how you're putting a trim command?

Op wo 29 sep. 2021 19:54 schreef claudinepeyrat06 ***@***.***

**Comment by claudinepeyrat06** [comment]
select the object (s) you want to trim after
Inkstitch/Coommand/Add a command after selected object/ Cut thread after embroidery.

My inkstitch is in French so I translated back in English, but the real english name in the menus are probably different.

**Comment by Robotorium** [comment]
Brilliant! Merci beaucoup! Je suis Belge (néerlandophone) mais ça m'aide
beaucoup!

Op do 30 sep. 2021 08:29 schreef claudinepeyrat06 ***@***.***

**Comment by kaalleen** [comment]
I believe this issue has been solved? Therefore I'll close it now. Please reopen if I am wrong.
