### ISSUE TITLE
Linux, Menu not complete

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1357]
I have found the following Issue reported via our youtube account. 
If it would be windows, I would say it quarantained the Inkstitch installation, but for Linux, I have no idea. What additional Information do we need to look into this?

ich habe inkstitch auf Linux installiert. Leider stimmt etwas mit meinen Extensions nicht. Sie erscheinen zwar im Menu, aber wenn ich zB auf Ink/Stitch -> FillTools gehe, erscheint kein weiteres Menu. Also kann ich auch nicht die Funktion "break apart" 
auswählen. Bei "Visualize and Export" kommt nur der "Embroider" aber sonst nichts. Kannst du mir vielleicht weiterhelfen?

Thanks in advance for helping
Tina

**Comment by kaalleen** [comment]
I gues this is an issue of a corrupted file structure. Inkscape cannot seem to find the executable in a relative path to the inx files. It would be best to have a look at the file structure. The embroider and about extensions do not need the executable and will be the only ones still visible in the menu. Just as you described it above.

**Comment by Tina-Chris** [comment]
Meanwhile it worked out. We got this answer on youtube: 
Vielen Dank! Ich habs mittlerweile gecheckt. Ich musste eine Neuinstallation von der Webseite direkt machen. Die Version aus dem Softwarecenter war veraltet und deswegen hat es nicht funktioniert

**Comment by kaalleen** [comment]
Uh, interesting. Until now I only know, that Ink/Stitch can be found in the arch user resporsitory (an older version, yes).
Do you know which linux distribution has been used in this case?
