### ISSUE TITLE
Curved Fill

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1359]
Would be nice to have ...
Fills with not straight lines, but bend in a user defined way. I'd love that and mentioned it in my very first comment on GitHub :D 
I closed the old issue today, because it's about pattern fill (which we now have). So I am creating this new issue here - the curved fill should not be forgotten.

**Comment by AndyLV** [comment]
Hello together,

I extended the autofill method to be able to take also a line as an additional argument to create a curved fill.
![ParallelOffsetLines](https://user-images.githubusercontent.com/45293380/137500566-d6dd16bd-ac55-49c3-8bc5-8eafdf36b3ff.png)
However, regarding the integration into inkscape I'm unsure how to provide the shape (which should be filled) and the line to the new autofill method.
One possibility is to ask the user to select the shape together with the line when calling inkstitch params. However, currently, in params.py the line and the shape will become seperated from each other where a tab is created for each (autofill and satin/line). This has the drawback, that the autofill tab has currently no notice about the also selected line (if I got it correctly). Hence one would need to provide selected lines also to the autofill tab but what should happen with the satin/line tab? (preventing the creation of it might not always be desired, e.g. if the user selected a line which he intended to be stitched)

A different possibility might use a similar way like "selection_to_pattern": A new svg entry is created for the line which can then be queried from the autofill tab. However, this has the drawback that the line becomes a global one for all shapes which is probably not desired.

Ideally I would like to have something like making a line a child of a shape in inkscape's object view - however, I think this possibility does not exist?

Do you have any suggestions how to integrate the routine into inkscape?

Thank you very much in advance and kind regards,

Andy

**Comment by lexelby** [comment]
WOW!  I'm with @kaalleen, let's do it in the same way as patterns.

And let's get this thing in ASAP, because wow, this will be a game-changer!!  Your screenshot has me salivating, and I am really curious to see how you did it.

**Comment by AndyLV** [comment]
> The MultiLineString issue for guided autofill will appear, when the guide line has tiny little loops in it as it quickly happens when you use the pencil tool. I know, it wouldn't make sense to have a guide line with loops, but still we need to catch the issue.

The code shall take the longest segment, now. For tiny loops this should work - for larger loops it will create uncovered areas.

>Also I noticed there will be an issue if the guide line has a fill (which also doesn't make sense, but well ;))

Should be fixed

>We need to handle the case, when the guide line is shorter than the fill element. The guided fill will just stop at that point. Maybe we can prolong the lines into the direction of the stitch angle?

There was already a routine which extended the line but it was not working properly. The lines are extended along the direction of the first/last segment.

Regarding the style guide - I fixed all issues except the ones called C901 (too complex) so far.

**Comment by kaalleen** [comment]
> The code shall take the longest segment, now. For tiny loops this should work - for larger loops it will create uncovered areas.

Sounds like a good solution. In a test run I get `NotImplementedError: Multi-part geometries do not provide a coordinate sequence`

> There was already a routine which extended the line but it was not working properly. The lines are extended along the direction of the first/last segment.

Nice idea. Works out fine too :)

> except the ones called C901 (too complex) so far

Sometimes there is no way to fix it, because some methods are complex. If you really don't find a better (less complex) way, you can add an exception to your method (# noqa: C901) and make style will ignore it.

**Comment by AndyLV** [comment]
> Sounds like a good solution. In a test run I get NotImplementedError: Multi-part geometries do not provide a coordinate sequence

I tested it with nearly closed loops causing several geometry parts after offsetting. I think you tested it with really self-crossing lines. My problem is the following:
![Problem](https://user-images.githubusercontent.com/45293380/141521173-60b9b8e5-0d8e-41ed-bb9d-b037811de531.png)
The invalid input shape can be easily detected via the is_simple routine of Shapely. However, there are at least two possibilities A) and B) which would make the line simple. 
Do you have an idea how to get one of the two possibilities via Shapely?

**Comment by kaalleen** [comment]
Sorry for the late answer, I just didn't find the time.

You could use the shapely method "unary_unioin". I just wrote up a quick test as it could be used by the break apart function. But you can adapt it for your own code. Also I used shapely 1.8. . Shapely 1.7.0 doesn't need the .geoms for looping. I recently noticed that shapely 1.7.1 had some issue with unary_union, that's why I downgraded shapely to 1.7.0 in the main branch for now. So make sure you are using the correct shapely version. This will split up the line into multiple elements. That's maybe not what you want. But I am sure you will be able to adapt it for your needs.

```
            if element.get_style("stroke", "none") != "none":
                stroke = Stroke(element.node)
                linestring = MultiLineString([LineString(path) for path in stroke.paths])
                if not linestring.is_simple:
                    index = element.node.getparent().index(element.node)
                    union = unary_union(linestring)
                    for line in union.geoms:
                        # skip the loop
                        # alternatively it could be possible to change the direction of the loop an keep it
                        if line.coords[0] == line.coords[-1]:
                            continue
                        el = copy(element.node)
                        d = "M"
                        for x, y in line.coords:
                            d += "%s,%s " % (x, y)
                            d += " "
                        el.set('d', d)
                        el.set('transform', get_correction_transform(element.node))
                        element.node.getparent().insert(index, el)
                    element.node.getparent().remove(element.node)
```

**Comment by AndyLV** [comment]
Thank you for the hint - I added an additional routine which should transform a non simple Linestring into version A) in the picture above.
