### ISSUE TITLE
Change embroidery file back to svg? Inkscape/Inkstitch

### ISSUE THREAD

**Issue by hope722** [inkstitch/inkstitch#1366]
Hi! I created a design in Inkscape/Inkstitch with font and an image, I saved it as an embroidery file but now I want to add an outline around my design to make it a patch. Now, I know that I should save it separately as SVG before saving as Embroidery.
But....

Is it possible to reverse it?

**Comment by tyrosinase** [comment]
Not easily. But there's a tutorial on how to add outlines to existing designs (for knockdown stitching, but it's the same principle for a patch outline): https://silverseams.com/2020/09/knockdown-stitching/

**Comment by hope722** [comment]
Thank you, i'm testing it out now but my imported embroidery design have the jump stitches. how do i get rid of them b/c it's now part of the knockdown layer?

**Comment by tyrosinase** [comment]
After you duplicate the design to the knockdown layer, you'll need to delete the non-stitching things like command balloons. That step should probably be added in the tutorial.

**Comment by hope722** [comment]
I'm sorry, I'm new to this : ( how do i do that? I don't see it mentioned in the tutorial on removing jump stitches from imported designs. please help

**Comment by hope722** [comment]
i see where i can add commands but i dont see remove jump stitch or anything about command balloons

**Comment by tyrosinase** [comment]
If you don't want the trims at all you can just go to `Ink/Stitch > Troubleshoot > Remove embroidery settings`, check the `Remove commands` box, and `Apply`.

**Comment by hope722** [comment]
Thank you, I appreciate your time helping me : )
