### ISSUE TITLE
[feature request] random stitch length option box

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1371]
I would like to suggest the feature of a randomized stitch length as available in other embroidery digitizing software:

- 1st for the new split satin, 
- 2nd for the fill stitch. 

I imagine it to be a function of % of the chosen stitch length, but the outside should stay within the boundary. Thus we would be able to have 

- a more random fill in example for fur fills [example](https://www.wilcom.com/help/e4/es/en/MainHelp/Decorative/patterns/patterns00029.png) source https://www.wilcom.com/help/e4/es/en/MainHelp/Decorative/patterns/Creating_random_patterns.htm
- and not a empty line in the middle of a split satin [example for even distribution](https://www.embroideryhelp.net/hatch/files/digitizer/de/27134423/41828057/1/1526519175467/AutoSplitJump-1.png) and [example for random](https://www.embroideryhelp.net/hatch/files/digitizer/de/27134423/41828060/1/1526519700027/AutoSplitJump-2.png) 
source https://www.embroideryhelp.net/hatch/digitizer/en/user-guide/stitch-types/satin-stitch

Thanks, Tina

**Comment by kaalleen** [comment]
This could also be useful for running stitches. Which means it could be an option for every stitch type we offer ;)

**Comment by lexelby** [comment]
I think we have this now!  Is anything missing?
