### ISSUE TITLE
Optimized routing for pattern stitching

### ISSUE THREAD

**Issue by einsweniger** [inkstitch/inkstitch#1383]
Hi!

I've recently looked at sashiko embroidery, just because I like the patterns.
After hand drawing some of them myself and repeating the pattern multiple times, I've noticed some issues.

1. Even if the pattern could be drawn through one continuous stitch (there exists a eulerian trail), Ink/Stitch currently has no routing for that: so that unfortunately leads to very short discontinuous paths. (https://github.com/inkstitch/inkstitch/blob/2f35a4a192eb6aa3b68b715da6c1ba984084e0e5/lib/stitches/running_stitch.py contains no such optimizations.)

2. if I use the path I had drawn as a pattern and use that as a "pattern fill" on another path/object, Ink/Stitch can't deal with that. I've tried converting the the pattern back to an object, but that does not cut it (heh). The pattern is just placed as one object without it's repetitions. Since Inkscape just stores the pattern as a style, using that directly is pretty difficult, since it's just the style:`style="fill:url(#pattern1769);stroke:none"`, where pattern 1769 is just transformation and projection rules. And I guess that's a little difficult to recalculate that back to lines. But I might be wrong here.

I think I can contribute something for the first issue, if a PR is welcome. If so, should we make this an extra tab in stroke params, or as something completely seperate?

On the second, I don't know for sure, since I don't know any specifics about Inkscapes' representation on pattern fills. I guess the easiest solution would be to just create tiled clones and do an intersection with the path I want the pattern in, so that's not an ink/stitch issue anymore.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/699867/136702411-df16acdc-4828-4ad7-8e75-5f148d7de850.png">

**Comment by einsweniger** [comment]
Good to know you're rewriting Params, that's why I always like to ask before making any contributions! Thank you for giving me access, I'll contain everything into a feature branch once I grasp what I have to do. See you then :D

**Comment by lexelby** [comment]
Thank you for contributing, and have fun :D

**Comment by lexelby** [comment]
I just realized, there's a kind of terrible way to kind of do what you're looking for right now, if you're interested in a temporary solution to your pattern problem.  It goes like this:

1. Select the lines.
2. Run Convert Lines to Satin.
3. Select the satins.
4. Run auto-route satin.
5. Select all satins from the result.
6. Run Convert Satin to Line.

It's a hack, and some areas will likely get stitched twice, but it should work.

I almost didn't want to tell you though, because I really want to see what you code, it'll be way better :)

**Comment by einsweniger** [comment]
Just as a little update: I‘m still on this. I‘ve read a few papers, but mostly I‘m trying to cope with my new linux distribution and coaxing it to provide a good development environment 😓

@kaalleen if I read the link correctly, this is still a setup where I have to click a thing in Inkscape, instead of having a test that I can run and debug from cli, right?
Because that clicking stuff, I‘m trying to avoid: I’d rather have it scripted. Maybe I‘ll check if the inkext repo has a test setup that works for me, but it‘s also a possibility that I undestand something wrong in the dev setup :D

**Comment by kaalleen** [comment]
No, you are right. It still involves a lot of clicking.
Maybe the [debugging setup](https://github.com/inkstitch/inkstitch/issues/1213#issuecomment-850732481) puts you just one step further. A lot of the Ink/Stitch functions also can be run from the command line. So you may be able to setup a testing environment as you need it.

@lexelby can you help us out here a little?

**Comment by einsweniger** [comment]
I don‘t think lexelby can help (me) here, really. Except if they run nixos themselves, because I just switched recently and I‘m still figuring out how all moving parts click together to form a working dev env. That‘s unfortunately the next step for me, but I‘m getting there, little by little. But thank you for pointing me towards the other setup :3

**Comment by lexelby** [comment]
I don't know anything about nixos, I'm afraid.  Debugging, on the other hand, we have covered.  You can use either pydev or pycharm.  You create a file named DEBUG in the Ink/Stitch directory (empty is fine) and then start pycharm's or pydev's debug server.  Then run an Ink/Stitch extension in inkscape and it connects to the debugger.  

There's also a facility for creating an extra SVG (debug.svg) with paths or networkx graphs in it.  I used that to debug autofill.

**Comment by einsweniger** [comment]
I finally got a working setup, took a while to compile the dependencies and I had to lift the numpy dependency, because it failed to compile on my system. I hope it works nonetheless :fearful: 

Just to be safe: for development, we use `git clone --recursive`? Because, the manual install says to clone the inkstitch/pyembroidery manually :sweat_smile: 

I also followed the instructions and created the debug file, but then diverged a bit and followed the pycharm instructions for setting up the debugging (installing the `pycharm_pydevd` package and changing the code according to the instructions). At least so far it works, now maybe I finally can start working on this for a bit :3

**Comment by einsweniger** [comment]
Oh, one more question: which python version are we targeting? I'm on 3.10 and love the new features, but I'm not sure which versions we want to support on inkstitch? I'd rather not start coding with new features, just to redo everything later :D

**Comment by kaalleen** [comment]
3.10 won't work at the moment. 3.9.x should be fine.

**Comment by kaalleen** [comment]
We have auto route for running stitches now. It could be improved. But I think that's what has been asked for.
