### ISSUE TITLE
MacOS dylib issue

### ISSUE THREAD

**Issue by Trejobry000** [inkstitch/inkstitch#1384]
1272] Error loading Python lib '/Users/trejobry000/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib': dlopen: dlopen(/Users/trejobry000/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib, 10): Symbol not found: _futimens
  Referenced from: /Users/trejobry000/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/trejobry000/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/libpython3.9.dylib

**Comment by tyrosinase** [comment]
Check issue #1263 and see if that's the same problem/solution.
