### ISSUE TITLE
Inkscape - Major issues with Big Sur

### ISSUE THREAD

**Issue by jfk1972** [inkstitch/inkstitch#1392]
It seems as though every day I am running into a new issue running Inkscape on Big Sur. Yesterday I could simulate stitches in Inkstitch. Today I cannot.  Add this to the fact that I cannot RENDER, nor PUT TEXT ON PATH in Inkscape.  All of my software is updated.  I've wiped my MacBook Pro completely of all Inkscape and Inkstitch traces and reinstalled to no avail.  I hope this is an issue that can find a happy ending.

Thank you.

**Comment by kaalleen** [comment]
This has been ported to the Inkscape forum. Therefore I'll close this issue. If you see there is more for us to do, please reopen the issue.
