### ISSUE TITLE
Will not allow PES file to be created. 

### ISSUE THREAD

**Issue by getbehindmesatan** [inkstitch/inkstitch#1397]
lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: fix-1186 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitchable objects. You'll find a more thorough explanation in the comments of #1307, or a little tutorial on how to convert bitmaps into stitch objects at https://silverseams.com/free-patterns/embroidery-patterns/digitizing-with-ink-stitch/ .

**Comment by kaalleen** [comment]
This bug should not appear in the upcoming version anymore. Therefore I'll close the issue. Please reopen, if you ever see this again.
