### ISSUE TITLE
Manual Install: Can't add extensions

### ISSUE THREAD

**Issue by hdacosta400** [inkstitch/inkstitch#1398]
I'm trying to add an extension to the ink/stitch submenu, but my changes are not reflected in Inkscape, nor does modifying the contents of existing extensions. I have verified that I can pretty easiliy add an extension on vanilla Inkscape and have it render, so I am missing some kind of permission to do it on the ink stitch repo?

**Comment by hdacosta400** [comment]
For reference, here's my XML file:

`<?xml version="1.0" encoding="UTF-8"?>
<inkscape-extension translationdomain="inkstitch" xmlns="http://www.inkscape.org/namespace/inkscape/extension">
    <name>Sensor Grid</name>
    <id>org.inkstitch.sensor_grid</id>
    <param name="extension" type="string" gui-hidden="true">grid</param>
    <effect implements-custom-gui="true">
        <object-type>all</object-type>
        <effects-menu>
            <submenu name="Ink/Stitch" translatable="no" />
        </effects-menu>
    </effect>
    <script>
    {{ command_tag | safe }}
    </script>
</inkscape-extension>
`

I figured that the id and the command_tag linking to the python effect file had to be the same, so I added a python file called sensor_grid.py.

**Comment by kaalleen** [comment]
Thanks for the info. This is really, really interesting!
