### ISSUE TITLE
Embroidery won't show on machine

### ISSUE THREAD

**Issue by jinnyanctil** [inkstitch/inkstitch#1405]
Hi! I saved my embroidery without any problems on my mac although, it won't show up on my Janome. I've checked everything, the size, if it's .jef, if it's in the right file, etc. On inkstitch the embroidery looks perfect with the visualize feature. I don't know what could be the problem, thank you!

**Comment by kaalleen** [comment]
I am not really sure what is going wrong in your case. Can you open the jef-output in Ink/Stitch?

I've heard some machine don't like filled up usb-sticks and people need to erase some of the content. The design size is the most common issue,  but you already checked on that ... Which machine do you use?

I really don't know. Has anyone else an idea?

**Comment by kaalleen** [comment]
Closing. No further response.
