### ISSUE TITLE
Lettering tool doesn't open at all

### ISSUE THREAD

**Issue by pamstr** [inkstitch/inkstitch#1412]
Hi, 
I have a problem with Lettering Tool not opening at all. I am using Inkscape v1.1 on Debian Testing (Bookworm) and just upgraded Ink/Stitch to 2.0.0. 

I tried to run Lettering Tool for the first time and it simply does not open - cursor changes to "waiting style" for a while and then nothing, like a silent crash. Other functions seems to work as before (except small bug reported in #1335).

I would love to make this report more detailed, but simply I don't know how to even find what crashed. I ran Inkscape from terminal, no error shown. I looked for any error logs, cannot locate them. I reinstalled Inkscape, reinstalled Ink/Stitch it didn't help.

If you have a guide how to gather necessary information, I will be glad to provide them.

Best regards,
Pamela

**Comment by pamstr** [comment]
Oh, I didn't see it 🤦‍♀️. Thank you for pointing out the troubleshooting section @kaalleen. I'll try that solution too.

I'm not sure if I should close this issue or leave it as is with the logs for someone else - so I am leaving it to you.

Thanks again and truly, truly thank you for this amazing piece of software!
Pamela

**Comment by kaalleen** [comment]
I'll close the issue. Closed issues are searchable and also this is documented on the website ;)
