### ISSUE TITLE
deep dive into "convert line to satin"

### ISSUE THREAD

**Issue by asartori86** [inkstitch/inkstitch#1419]
Hi,
It has been almost one year that I have used your excellent program. Many thanks for all the efforts.

I am a bit puzzled by the way "convert line to satin" put rungs. If I have a "long path" and convert it to satin, I get "few" rungs. If, before converting, I **break path** at several nodes, the outcome is much better: typically, there are many more rungs, which, therefore, better follow the curvature. I "learned" where I should break the path during this year, but it does not always work.

I would ask if you can pinpoint where the algorithm is that converts a line to satin.

Thanks

**Comment by kaalleen** [comment]
Here you go: https://github.com/inkstitch/inkstitch/blob/main/lib/extensions/convert_to_satin.py ;)
Tell us if you need anything more.
