### ISSUE TITLE
Satin conversion difference between v 1.1.29 and 2.0.0.

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1425]
I got this error / object handling difference (?) reported on YouTube

Izlude Tingel
vor 1 Woche
hi again, sorry I took so long (got caught up in making stuff). i went and recorded it today, so here's a video link.  i think you should see it first before i post it there, just in case it's not a valid bug (maybe I'm missing a step in the new version?)  https://youtu.be/jZT5dUjevTw    quick note: inkscape version is irrelevant. inkstitch version is what seems to be the core issue. old plugin works with latest inkscape.

Can someone explain what is going on there?
Thanks
Tina

**Comment by kaalleen** [comment]
Do you think it could be possible to receive the svg file? I know it is just a simple square, but from the video I can't reproduce the error.

**Comment by Tina-Chris** [comment]
Which one was the email adress for files?

**Comment by kaalleen** [comment]
send-us-files@inkstitch.org 

Thank you :)

**Comment by kaalleen** [comment]
@Tina-Chris can you deliver this answer?

Thank you for the file. At first I didn't know to which issue the mail was referencing to, didn't know what to do with it and forgot about your mail.

Now I saw the thread on GitHub and found your mail back. Thank you for sending a file for your problem. It is always the easiest way to figure out what is going wrong.

Your square is a use tag (if that says anything to you). It is not a normal object. I wonder it was working at all in an older version.
If this happens again, you can use Ctrl+Shift+C to convert your shape into a real path (or Path > Object to path) and you'll be able to work with it.

Hope this clears things up a little.
