### ISSUE TITLE
Fehler bei Fehlerbehebung an Objekten // Error using troubleshoot objects

### ISSUE THREAD

**Issue by Bauschlumpf** [inkstitch/inkstitch#1429]
Hi,

beim Aufruf der Fehlerbehebung an Objekten kam es zu diesem Fehler.

When calling 'troubleshoot objects', this error occurred.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

Viele Grüße / Many kind regards
Bauschlumpf

**Comment by tyrosinase** [comment]
If it's not a native Inkscape SVG, try changing the color of the object (per #1316, which has more info if that doesn't work).

**Comment by kaalleen** [comment]
I'll close this issue, since it has been fixed for the next release. Please reopen, if the error still shows up in the next version of Ink/Stitch.
