### ISSUE TITLE
Using Ink Stitch on OS Monterey

### ISSUE THREAD

**Issue by Frankiesnake** [inkstitch/inkstitch#1431]
Is there going to be a new version of Ink Stitch for the Mac OS Monterey?

**Comment by kaalleen** [comment]
Yes, there will be a version for Monterey.

**Comment by nickolaianmiller** [comment]
Do you know when that might be coming out? You guys are doing great work here!

**Comment by kaalleen** [comment]
I hope this will be very soon ;)

**Comment by kaalleen** [comment]
The new version is released. I'd be curious to hear how it works for you on Monterey?
