### ISSUE TITLE
Confused??

### ISSUE THREAD

**Issue by Laarzz** [inkstitch/inkstitch#1432]
ib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
path131: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.

it wont let me see a preview of my design

**Comment by kaalleen** [comment]
Run Extensions > Ink/Stitch > Fill tools > Break apart fill opbjects...
Ink/Stitch doesn't like shapes which have crossing outlines. The above mentioned tool should solve this for you.

**Comment by kaalleen** [comment]
This will be solved in the next release. I'll close the issue now. Please reopen, if this still appears in the upcoming version.
