### ISSUE TITLE
wxpython: scrolledpanel

### ISSUE THREAD

**Issue by Laarzz** [inkstitch/inkstitch#1433]
wx/lib/scrolledpanel.py:225: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.

Any help?

**Comment by kaalleen** [comment]
This is just a warning and shouldn't prevent params from working. We have seen this warning and noticed, that it shows up if the params windows has a specific size (needs a scroll bar). The warning is part of wxpython which we currently use to display the params dialog.
