### ISSUE TITLE
Fill: only stitches ouline of a (complex) path

### ISSUE THREAD

**Issue by Waltax** [inkstitch/inkstitch#1452]
I am learning inkstich and after some simple projects , i created a path of a bitmap ([of a pow patrol cataract](http://clipart-library.com/img1/1453947.jpg)) .
after breaking up the dog remains mainly in one path. The other paths make up an eye and the borders.
after fixing a few overlapping borders params runs and gives a good preview for all objects, but the one that makes up most of the dog. This only gives an outline without any interior detail.

Is this caused by the complexity of the path? Reducing the nodes didn't solve this so far.

Here you can see the result of params (ony of the troublesome object) with in the right-lower corner the original object with its nodes.
<img width="832" alt="sky params" src="https://user-images.githubusercontent.com/61332719/142775392-80f50d95-a702-4d0f-b304-f67e99cb28e8.png">

**Comment by tyrosinase** [comment]
You're kind of going down the wrong road with this - you don't want to do a line-art design with fill stitch at all (other than if you want to fill in the line art). You want to convert the lines to satin stitch.

I believe the Ink/Stitch video channel (https://www.youtube.com/channel/UCJCDCFuT_xQoI55e10HRiRw) has instruction on this, or if you're not a fan of videos, there's a step-by-step with pictures at https://silverseams.com/tutorials/digitizing-with-ink-stitch/ .

**Comment by Waltax** [comment]
Thanks for the advise, converting to satin stitch will be most useful. Still i would like to be able to fill in the line-art in the future.

**Comment by tyrosinase** [comment]
The non-video tutorial goes into that a bit, yeah. (The video ones might too but I'm not a video person so I haven't watched them.)

**Comment by kaalleen** [comment]
I am always wondering, if we could handle this case just a little better?!?
