### ISSUE TITLE
select/ delete objects which are too small to embroider automatically

### ISSUE THREAD

**Issue by Waltax** [inkstitch/inkstitch#1454]
I'm not sure if this is an issue ore a project. 

I am working on digitizing drawings from my children. The edges between colors appear to make small areas of mixed color.
Troubleshoot highlights many of  these objects as too small to embroider, even tho simulations do show stitches to form them. I haven't tried to stitch the design yet, but i'd like not to have the small objects in the first place. 

As troubleshoot can detect and mark these objects, i would like to use this automatic detection to select them and delete them. 
Ideally i'd like to tweak the size that is detected and  inspect them quickly to see if i want to delete them, but an automatic deletion of all would probably suffice.

Does an option like this exist or can i create it?

Or am i over-engineering things and did i overlook an easy way to prevent the creation of small edge-areas ?

**Comment by kaalleen** [comment]
Try `Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...` Is that what you need?
