### ISSUE TITLE
Sprache in Englisch obwohl Deutsch 

### ISSUE THREAD

**Issue by BirgitSchr** [inkstitch/inkstitch#1460]
Hallo,

ich habe Inkstitch in deutscher Sprache heruntergeladen. Warum sind die Parametereinstellungen und die "Fehlermeldungen an den Objekten"  in englischer Sprache? Wo kann ich das ändern?
Danke

**Comment by Tina-Chris** [comment]
Gehe über das Menü Bearbeiten > Einstellungen > Benutzeroberfläche > Sprache (erfordert Neustart) und lege die Sprache direkt fest, statt auf Standardeinstellungen (oder Systemsprache?) zu lassen.
LG
Tina

**Comment by BirgitSchr** [comment]
Hallo und danke für die Antwort. Es hat funktioniert.
👍

Tina Chris ***@***.***> schrieb am Mi., 1. Dez. 2021, 11:46:
