### ISSUE TITLE
YouTube Question Text Module and Color Palette

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1464]
`Finde Ink-Stich super, allerdings ist es für mich schwer umzusetzen. z.B. erhalte ich beim Text-Modul von InkStich folgenden Anzeigentext in rot: "Diese Schriftart hat keine verfügbaren Textvarianten. Bitte aktualisieren Sie oder entfernen Sie die Schriftart." Weißt Du, wie man das macht? Des Weiteren kann ich die Madreira Rayon Farbpalette nicht auswählen, er zeigt mir keinen Pfad an, wo diese zu finden ist. bzw. ich weiß nicht wo ich diese Datei finden kann. Muss ich mir diese selbst irgendwo herunterladen und in einen bestimmten Ordner in InkStich ablegen? Solltest Du Zeit und Lust haben mir zu helfen, wäre ich Dir sehr sehr dankbar. Schönen Gruß auch!`
Deepl translation: 
I find Ink-Stich great, but it is difficult for me to implement. For example, in the InkStich text module I get the following display text in red: "This font has no available text variants. Please update or remove the font." Do you know how to do this? Furthermore, I can't select the Madreira Rayon colour palette, it doesn't show me a path where to find it. or I don't know where to find this file. Do I have to download it myself from somewhere and put it in a specific folder in InkStich? If you have the time and inclination to help me, I would be very grateful. Best regards!

Does someone know this Lettering Module Error message? I never experienced it. 
Also I tried to install a color paletet on my windows, I am not able to import a color palette, wither. C:\Program Files\Inkscape\share\inkscape\extensions\inkstitch-kaalleen-satin-patterns-windows-de_DE\inkstitch\palettes
![image](https://user-images.githubusercontent.com/64272979/144222790-5a849a1a-18c7-4ccf-a22e-d3e410a20104.png)
This gives me the following error
![image](https://user-images.githubusercontent.com/64272979/144222865-531018b8-65bf-4b9c-bd3d-88290eaf1e47.png)

Might it be because I did not install all the extensions Inkscape comes with (to save space on my Laptop)?  I only have 
![image](https://user-images.githubusercontent.com/64272979/144223034-de238181-8f75-4619-9e37-6423f5e35aab.png)
a small list.
Does this anyhow influence the inkstitch performance?
Thanks
Tina

**Comment by kaalleen** [comment]
I am not sure if that specific version already has this option. But it will be in the next release.
Use "Benutzerdefinierte Farbpalette installieren..." instead of "Garnliste importieren...".

"Garnliste importieren" importiert eine vordefinierte Farbwahl für ein spezifisches Design. Z.B. um eine zuvor geöffnete dst-Datei wieder richtig einzufärben.
