### ISSUE TITLE
Nothing readable, text in windows is all error

### ISSUE THREAD

**Issue by gyomonolith** [inkstitch/inkstitch#1465]
![error](https://user-images.githubusercontent.com/95377805/144295478-47951862-b1a0-45b7-bf41-04427585cda7.png)

Every single window looks like this...any idea how to fix this? Did I install it incorrectly? I'm lost.

Thanks!

**Comment by kaalleen** [comment]
Are you on Linux? How did you install Inkscape?
I faced this issue once, running `fc-cache -vf` helped. Next time I started an Ink/Stitch gui it took a while, then everything went back to normal. This may not help if you used flatpak or something.
