### ISSUE TITLE
Unable to Save PES

### ISSUE THREAD

**Issue by cbradshaw716** [inkstitch/inkstitch#1470]
I'm trying to create a PES file for a logo and I'm having 2, possibly unrelated issues. The first is a borders overlapping error but the biggest is that when I go to save, I get the following error message:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

I'm new to this so any help would be greatly appreciated. 
![Memorial Hermann Logo](https://user-images.githubusercontent.com/95539065/144716130-c3c3888d-f31b-46a3-84d6-d46a3a61bfa1.png)

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly give you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitch-able objects. You'll find a more thorough explanation in the comments of #1307.
