### ISSUE TITLE
Feature request: convert satin to fill

### ISSUE THREAD

**Issue by dgileadi** [inkstitch/inkstitch#1476]
Sometimes it turns out that a satin stitch wasn't the best choice after all (perhaps it's too wide or bunches the fabric), and it would be better as a fill. It would be really nice to have a command to convert a satin column to a fill. Even better if it could preserve the overall angle of the stitch.

**Comment by lexelby** [comment]
I think you might be able to get something close to this using Inkscape's Live Path Effects.  You would use the Fill between Strokes path effect, which would do the conversion for you.  You could optionally use Object to Path to make the conversion permanent, although I don't think that would be necessary as Ink/Stitch should be able to work with the live path effect.

**Comment by dgileadi** [comment]
That's a cool workaround!

**Comment by kaalleen** [comment]
The outline extension (will be introduced in the next release) can do that. It will be found in stroke tools though and you'll need to swap fill and stroke to finally have your fill object.
