### ISSUE TITLE
Tatami fill leaves gaps between segments

### ISSUE THREAD

**Issue by Hahajizzjizz** [inkstitch/inkstitch#1480]
For instance, I recently stitched out the letter Y.  The way it was routed meant that the lower half is joined to the upper half.  Is there a way to create an overlap in the area where the segments join?

**Comment by kaalleen** [comment]
Yes, either you set an expand value in the params dialog or you create your paths directly with an overlap.

**Comment by tyrosinase** [comment]
I think the person with the distinctive username means that it's all one fill, but there's some fabric shifting between when the two subsections happen and the gap doesn't get closed properly.

Underlay stitching should hold everything together in that case, and if it's already there but isn't holding a more sturdy stabilizer should do it.

**Comment by danielkschneider** [comment]
You could also envision to add a new parameter that would add a one or more extra lines at the junction. In particular fabrics like sweaters pull a lot (despite underpath and underlay)

**Comment by kaalleen** [comment]
I'll be closing this is favor of #1068
