### ISSUE TITLE
Warning: etree deprecated

### ISSUE THREAD

**Issue by helifino** [inkstitch/inkstitch#1482]
I get this popup seemingly at random, but most usually when exporting -
`lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
`

Versions:
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1348

Inkscape 1.1 (c68e22c387, 2021-05-23)

Inkstitch v2.0.0 (Windows) en_US

[text-test.zip](https://github.com/inkstitch/inkstitch/files/7698116/text-test.zip)

**Comment by tyrosinase** [comment]
That's fixed in the next release, but it's only a warning so the exported design should be fine.

**Comment by helifino** [comment]
I figured it probably was but couldn't find it when searching for (closed) issues.
