### ISSUE TITLE
Bug after trying to open "Params"

### ISSUE THREAD

**Issue by Oravann** [inkstitch/inkstitch#1483]
Like in the video https://www.youtube.com/watch?v=U5htzWZSjA8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=5 I drew a circle, converted it to Path ("Object to Path") and then opened the "Params" function of Ink/Stitch. And directly this error occurred:

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by Oravann** [comment]
Inkscape version:
Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20) 
Download from Ink/Stitch:
Version 2.0.0

**Comment by tyrosinase** [comment]
This is fixed in the next release, and #1232 has an interim fix.

**Comment by Oravann** [comment]
thank you :)

**Comment by Oravann** [comment]
When trying to save the file to .dst format I get this error with the version you mentioned:

lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

**Comment by tyrosinase** [comment]
That's also fixed in the next release, and isn't an error but a warning. The file should be correctly saved. (You can always open the .dst [etc] directly in Inkscape to confirm it. It will open like any other pre-created stitch file, as all manual stitch paths.)

**Comment by Oravann** [comment]
Thanks :)
I created my first stitch File and it worked !
