### ISSUE TITLE
TT Masters needs updated

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1486]
The tail of the capital Q needs a rung; it throws an error as shipped.

I fixed it and could submit a patch, but also it's got all kinds of wacky trims going on because it lacks satin routing. Is anybody else working on that, or should I update that before I submit it?

**Comment by Augusa** [comment]
We are working on a lot of fonts but not on TT Masters. Very good idea to update it. May be ask #claudinepeyrat06 who is working on fonts.

**Comment by kaalleen** [comment]
Has TT Masters been updated @claudinepeyrat06 @tyrosinase ?

**Comment by claudinepeyrat06** [comment]
i don't  think so.

**Comment by kaalleen** [comment]
I think tt masters got an update by now: #2221
