### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tru2You** [inkstitch/inkstitch#1488]
![IMG_20211215_024053471](https://user-images.githubusercontent.com/96178897/146175756-02e9f319-154a-43ce-83b9-dbf0a2726808.jpg)

**Comment by tyrosinase** [comment]
That looks like the same error as #1334, except that one was on a Mac. The same workaround may apply though.

**Comment by Tru2You** [comment]
Got it to work thru all that after fixing file up.. but now this.. What is this? Thanks for helping.
![IMG_20211215_085848086](https://user-images.githubusercontent.com/96178897/146231418-a7a0790e-b11d-4e6a-8393-aea738789fca.jpg)

**Comment by tyrosinase** [comment]
That's a warning only (that shouldn't have been passed through to the end user, but apart from that it's harmless).

**Comment by Tru2You** [comment]
Its harmless? It's not allowing me to embroider or save to pes file.i run preview and it stitches thru.

**Comment by tyrosinase** [comment]
It's *usually* harmless - is the pes file not being created at all?

**Comment by kaalleen** [comment]
This should be fixed by now. Please reopen if not.
