### ISSUE TITLE
Print PDF Specs...

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#149]
For lack of a better phrase, what are the specs for the print pdf function as far as what it needs from the web browser?

This only applies to the Windows version as I run a VM with no outside connection, as such, I only run the default IE 8, so I don't know if it's too old or if I need to do something else.  I get the top banner (print, settings, close), but that's it.

It works otherwise as I did try it out on a Win 10 rig (which I just refuse to go to) and it worked fine, so I'm thinking it's something to do with IE 8 or a setting that I need to tweak.

I don't use the VM for web browsing at all, so I would prefer to avoid installing a new browser if I can avoid it.  The only reason that I actually need this is due to tutorials, I like to do them in Windows as most people use Windows, but I just need to know what "min requirements" I need for that functionality for my VM.

**Comment by lexelby** [comment]
As far as I can tell, Print requires an html 5 browser.  @kaalleen might know more.  To my understanding, IE definitely won't cut it.   Depending on your version of Windows, Microsoft Edge might work just fine.  If so, set it as your default browser and you should be good to go.

If not, I'm afraid there's no option other than installing another browser like Firefox or chrome :(

**Comment by wwderw** [comment]
> If not, I'm afraid there's no option other than installing another browser like Firefox or chrome :(

I was figuring that that might be the case.  I'm trying not to go to Win 10 even within a VM.  But I can always add FF to it.

Thanks for letting me know.

**Comment by kaalleen** [comment]
Yes, I agree. IE8 is not capable to display inline svg images. Other html5 content might be possible by declaring them as display:block elements, but svg is essential for the print feature. This would be possible with with ie9 though. But then again we have css3 stuff in there, so I would at least recommend using ie10 or even 11. But Firefox or Chrome of course would do.

**Comment by wwderw** [comment]
I installed Vivaldi as that was the lightest modern browser that didn't just have installation stubs that still required internet access to download everything else (I don't know why they do that).  Or at least, they don't make it easy to find the full offline installer.

Worked without a hitch from there.

**Comment by lexelby** [comment]
Cool!  Vivaldi is my main browser as well, though I also test with Firefox.
