### ISSUE TITLE
Cannot convert to PES

### ISSUE THREAD

**Issue by lalaliaa** [inkstitch/inkstitch#1490]
I've tried Break Apart Fill Objects, Cleanup Document, Troubleshoot Document in order to get Params working just fine. When I go to convert it, I get this error and the PES file is never created. Interestingly never ran into this problem with Macbook. :/ 

Ink/Stitch experienced an unexpected error.

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 55, in effect
  File "lib\extensions\base.py", line 207, in elements_to_patches
  File "lib\elements\element.py", line 362, in embroider
  File "lib\elements\element.py", line 418, in validate
  File "lib\elements\fill.py", line 182, in validation_errors
  File "lib\elements\fill.py", line 142, in shape
  File "lib\elements\fill.py", line 129, in paths
  File "lib\elements\element.py", line 305, in parse_path
  File "lib\elements\element.py", line 301, in path
  File "inkex\paths.py", line 1123, in __init__
  File "inkex\paths.py", line 1139, in parse_string
  File "inkex\utils.py", line 203, in strargs
  File "inkex\utils.py", line 203, in <listcomp>
ValueError: could not convert string to float: '.08.08.32.11'

**Comment by tyrosinase** [comment]
This is a known bug but I can't find it offhand to see if there's a better workaround or even if one of the interim releases fixes it. But while you're waiting for a better answer from a dev, if you're feeling adventurous you can go in and edit the XML (Shift-Ctrl-X) and put spaces in so it's `.08 .08 .32 .11` and that will satisfy your current Ink/Stitch.

**Comment by lalaliaa** [comment]
Hmm, here's me being adventurous lol
I don't see the string you referenced in here; I do see it in the error code, but I have no way of editing that, afaik. 
Am I just blind? lol

![Screenshot (2)](https://user-images.githubusercontent.com/96254738/146436931-3dcc9b12-9d66-443a-bb1b-1fc64ef6c279.png)

**Comment by tyrosinase** [comment]
It ends up down in the attributes and whatnot, and now that I think about it you're probably better off opening the SVG file with a text editor (Leafpad, Notepad, etc.) to edit that sort of thing.

**Comment by lalaliaa** [comment]
Ok, found it!! Notepad was helpful. Replaced the file with the edits, and the pes file works! Thank you!

Am I gonna have to do this with every file from now on?

**Comment by tyrosinase** [comment]
I don't think so, but hopefully one of the devs will weigh in with actual knowledge beyond my "I remember this going by in a previous issue that I can't find now."

Was the file originally created in something other than Inkscape? Because IIRC it turns out that's valid SVG without the space, but that's not (normally?) how Inkscape creates it.

**Comment by lalaliaa** [comment]
o_O Actually bought it off Etsy, thinking all svg's are the same... 
I guess not! 
I've definitely never seen that error before, so makes a ton of sense all the sudden.

**Comment by tyrosinase** [comment]
Yep, it's a valid but pretty uncommon way to write the numbers. Does the SVG say what generated it, by chance?

**Comment by lalaliaa** [comment]
Seller got back to me: Adobe Illustrator.

**Comment by tyrosinase** [comment]
Oh good, just some obscure software no one's heard of. 🤪

Sometimes doing a single-object combine will cause Inkscape to rewrite the object, though not always. And it will be fixed in a future version - and may already be fixed in a pre-release (@kaalleen?)

**Comment by lalaliaa** [comment]
LOL that's what I said!!

**Comment by kaalleen** [comment]
We did not actively fix it, but we updated inkex. So it may be fixed without our knowledge. We need to test it.

**Comment by tyrosinase** [comment]
After Christmas I'm doing the big "look you've upgraded the same Debian install for seventeen years across three motherboards and four hard drives, maybe it's time to wipe and scratch-install" thing, so I'm going to (1) get a backup copy of Ink/Stitch installed in the laptop (the Pi, it's a Raspberry Pi, don't judge) and then (2) reinstall EVERYTHING from scratch including a bleeding-edge Ink/Stitch and then I'm going to break it in every way I possibly can. (Although I don't have Illustrator. I think the kid might have access to it through the college though. At minimum I can edit spaces out of SVGs until things break...)

**Comment by kaalleen** [comment]
Fixed. See #1338
