### ISSUE TITLE
Clone: source element not found

### ISSUE THREAD

**Issue by accebernelle** [inkstitch/inkstitch#1495]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 55, in effect
  File "lib\extensions\base.py", line 207, in elements_to_patches
  File "lib\elements\element.py", line 364, in embroider
  File "lib\elements\clone.py", line 99, in to_patches
  File "lib\elements\clone.py", line 164, in get_clone_source
IndexError: list index out of range

**Comment by tyrosinase** [comment]
Maybe a new error? `List index out of range` often means there's nothing Ink/Stitch recognizes as stitchable, but that's the first time I've seen it come out of `get_clone_source` (which may mean nothing, I'm a dev but not an Ink/Stitch dev).

If that's what it is, then the first response to #1414 will help you, and if that's not it then possibly the third response will be appropriate.

**Comment by accebernelle** [comment]
First response to #1414 did not work. Whole image was created using the Bezier tool; then each was converted to satin stitches and filled objects using the inkstitch extensions.

**Comment by kaalleen** [comment]
Looks like you are working with clones. The problems seems to be, that it is not finding the original element. Would you mind to send us your file. It'd be interesting to have a look at it in order to fix the issue.

**Comment by kaalleen** [comment]
Due to an inkex update we can in a later version search for the clone source differently. This will definitely outdate this issue. Therefore I'll be closing it now.
