### ISSUE TITLE
Switch to different color/needle, Multi-Needle machine

### ISSUE THREAD

**Issue by Swe92** [inkstitch/inkstitch#1499]
Hey!
I have been working in ink stitch now to make some files for my Toyota AD 820.
But i cant figure out how to make the color switch on a multi-needle machine.
Anyone that can help me with this?
And for the record haven't tried it out on the machine yet just because i want to know what i can do in the program before i start it.

**Comment by kaalleen** [comment]
I don't have a multi-needle machine. But I think a normal color change will work on that machine as wanted. @lexelby ?

**Comment by lexelby** [comment]
Should do, yes.  @Swe92 There is no specific "color change" command in Ink/Stitch.  It will stitch objects in the order that they appear in the SVG, from lowest to highest in the stacking order.  If the color of one object differs from the next, Ink/Stitch automatically inserts a color change command in the embroidery file.  Does that help?

**Comment by Swe92** [comment]
@kaalleen @lexelby Thanks for the answer to my question :)

**Comment by danielkschneider** [comment]
Yes it is all automatic. If you got more colors than needles, then you will have to either re-assign different colors to the same needle or have the machine stop and change the thread (that is somewhat more tricky).
