### ISSUE TITLE
Stitch Plan not appearing after Params have been properly applied

### ISSUE THREAD

**Issue by Crispy940** [inkstitch/inkstitch#1502]
Hello! I was working on a personal use project to have a logo embroidered and ran into an issue. After converting the object to a bitmap and making all necessary adjustments, I applied the Params and it worked. I went ahead and hit "Apply and Quit" and what usually happens is that a new object appears called "Stitch Plan". However, for this specific instance it did not appear. Does anyone know what might be causing this? Attached are screenshots of the Params fully functioning and what appears right after hitting Apply and Quit.
<img width="1629" alt="Getting to Params" src="https://user-images.githubusercontent.com/96603539/147307608-28fcb497-56b6-48e9-b8e8-ca055d34b80e.png">
<img width="1792" alt="Param Worked" src="https://user-images.githubusercontent.com/96603539/147307610-28b1e6f0-a373-4b0b-a454-3d377773715a.png">
<img width="1792" alt="Stitch Plan not Appearing under Layers" src="https://user-images.githubusercontent.com/96603539/147307614-48933aa8-c3fe-4eae-8d59-18f34d08b0a3.png">

**Comment by tyrosinase** [comment]
It's not the params preview that creates a stitch plan (at least not a permanent one, unless there's an option that I'm unaware of, which has happened before), but `Extensions > Ink/Stitch > Visualize > Stitch Plan`.
