### ISSUE TITLE
Not able to save any files

### ISSUE THREAD

**Issue by RMWOOD94** [inkstitch/inkstitch#1503]
I am new to Inkscape/inkstitch and am having trouble trying to save files. I have finally fixed my image to meet all the perimeters so it doesn't error out that way, but when I go to save, it just says it is unable to save in whatever format I try to save it in.

**Comment by tyrosinase** [comment]
What is the specific error message?

**Comment by kaalleen** [comment]
No more information. Please reopen if there is still an issue.
