### ISSUE TITLE
Cannot save a copy of image as a embroidery file for Brother formats

### ISSUE THREAD

**Issue by dvmpiper** [inkstitch/inkstitch#1506]
Hi, 

This is the error code I get when trying to save a copy of an image for use with Brother machines for embroidery:

lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

Thanks.

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly give you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitch-able objects. You'll find a more thorough explanation in the comments of #1307.
