### ISSUE TITLE
Probléme Déplacement Z par point

### ISSUE THREAD

**Issue by Mimi4953** [inkstitch/inkstitch#1507]
J'ai construit une machine générique avec un machine Omnia. J'ai remplacé le moteur à courant continu de" cette machine par un moteur pas à pas Nema 23. j'ai opéré avec sucés les réglages du driver et du GRBL.
Je rencontre une difficulté que je n'arrive pas à résoudre. Lors de la sauvegarde du fichier (je maitrise inkscape et Inkstitch), la fenêtre TXT file out put me propose de choisir un déplacement Z par point mais celui ci est limité à 10 mmm alors que la course de l'aiguille est de 130 mm pour un point.
J'ai essayé de résoudre le problème par des moyens mécanique et ai obtenu un sérieuse amélioration mais la vitesse du moteur reste lente (j'utilise CNCjs pour lire et transmettre le Gcode, un essai  avec Candle donne le même résultat), lors du déroulement du programme et est parfaitement correcte quand j’opère le retour à Z0.
Avez vous une solution car à chaque point la position de l'aiguille change et elle finit par rester dans le tissu lors des déplacements x et y (cela fonctionne correctement)?
Merci d'avance

**Comment by lexelby** [comment]
Hmmm... Can you set the steps per millimeter for the Z axis to a higher number?

**Comment by kaalleen** [comment]
> Hmmm... Can you set the steps per millimeter for the Z axis to a higher number?

I think that is exactly the problem. It wouldn't let you do it. We did not define min and max values and therefore it is taking the defaults. Seems like default max is 10. I created a PR to allow higher values.

**Comment by Mimi4953** [comment]
I thank you for your answer.
I have tried your solution but it doesn't match.
In french version the line is
gui-description="incrémenter la coordonnée z de ce montant par point si la fonction &#34;déplacement Z par point&#34; est activée" >5.0</param>
The syntax is different and you can see the reference to a function &#34 and I have not found where it is defined.
Thank you for your help

**Comment by kaalleen** [comment]
Have you tried Ink/Stitch v2.1.2 ?
