### ISSUE TITLE
Converting .svg file to .pes gets rid of format (canvas size, placement, etc) and leaves you with just the Stitch Plan

### ISSUE THREAD

**Issue by Crispy940** [inkstitch/inkstitch#1508]
Hello! I am working on a project for personal use and ran into this issue. I am working with a re-positional embroidery hoop, so I have been very careful with the placement of my object when working the file. After I have the object lined up the way I want it, I go ahead and convert it to a .pes file from a .svg file. The .pes file appears as the .svg did, with the correct canvas size and placement of the object. I go ahead and upload the .pes file into the embroidery machine what appears is just the stitch plan in the middle of the canvas. I then check the .pes file in the computer and turns out that the canvas size was reduced to just cover the stitch plan. 

I have tried re-formatting the canvas size and re-saving but that did not help. Is there a way to prevent this from happening? or is this just the way things work?

I appreciate any input! Please see below images so that you can see what I am referring to:

<img width="1791" alt="SVG File" src="https://user-images.githubusercontent.com/96603539/147840725-640cc86c-6699-4e37-bc23-d53497e66a5d.png">
<img width="1792" alt="Converted PES File" src="https://user-images.githubusercontent.com/96603539/147840727-90bf4d4a-5556-4f9f-bb60-722b63012238.png">
<img width="1791" alt="Reopened PES File" src="https://user-images.githubusercontent.com/96603539/147840731-668d679a-1b4e-44ed-a035-e60963d245c8.png">

**Comment by tyrosinase** [comment]
It's a limitation of the file format... PES doesn't include any info about hoop size, and the machine just centers whatever you give it. You have to do tricks with non-stitched tackdown rectangles to keep it placed where you want it, but fortunately that's fairly simple: https://silverseams.com/tutorials/using-a-5x12-hoop-on-a-5x7-embroidery-machine/

**Comment by Crispy940** [comment]
@tyrosinase Gotcha... Thanks for including that link, I will definitely check that out!

**Comment by lexelby** [comment]
Try the Origin command in the "add commands" extension.  It might help, but the machine might ignore it and center anyway.
