### ISSUE TITLE
Unexpected Troubleshoot Error

### ISSUE THREAD

**Issue by daisydaisydaisyy** [inkstitch/inkstitch#1512]
I was trying to troubleshoot multiple objects when I got the following error code:

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\troubleshoot.py", line 35, in effect
  File "lib\elements\polyline.py", line 101, in validation_warnings
  File "lib\elements\validation.py", line 32, in __init__
TypeError: __init__() missing 1 required positional argument: 'y'

The document is attached. I was trying to troubleshoot all of the fill layer. Thank you so much for all you guys do
[miku tag.zip](https://github.com/inkstitch/inkstitch/files/7798217/miku.tag.zip)
!

**Comment by tyrosinase** [comment]
It's the polyline above the left eye, the triangular shadow under the hairline. It shouldn't be throwing that error, but as a workaround if you convert it to a path it'll (shift-ctrl-c) it's valid (though doing that reverts any Ink/Stitch settings back to default).

**Comment by daisydaisydaisyy** [comment]
> It's the polyline above the left eye, the triangular shadow under the hairline. It shouldn't be throwing that error, but as a workaround if you convert it to a path it'll (shift-ctrl-c) it's valid (though doing that reverts any Ink/Stitch settings back to default).

THANK YOU SO MUCH @tyrosinase!!! That totally fixed my problem. THAT problem, anyways :,)

As another request, if you can answer this, I'm wanting to satin stitch the outline layer. What would be the easiest way of doing that?

**Comment by tyrosinase** [comment]
For future reference: troubleshoot only shoots the items you have selected, so I lassoed a bunch of pieces, troubleshot them, and if it didn't make the error I deleted them, until I narrowed it down to that one. Not something you generally have to do (the whole point of troubleshoot being that NORMALLY it points to the troubled item) but occasionally necessary.

This tutorial explains converting things to satin, both starting with an entire shape you want to convert (the eyes/brows) and adding satin outlines to existing shapes (the tears), and hopefully will help: https://silverseams.com/tutorials/digitizing-with-ink-stitch/
