### ISSUE TITLE
SVG Layer Manipulation

### ISSUE THREAD

**Issue by hdacosta400** [inkstitch/inkstitch#1515]
How does inkstitch actually generate new SVGs to render on Inkscape? Using the inkstitchExtension class, adding a new path looks like this for adding a Polyline object: `self.svg.get_current_layer().append(path)` . However, when I try something similar in Inkscape outside of the inkstitch environment, it does not work. What was done in order to make this possible?

**Comment by hdacosta400** [comment]
Additionally, how do you account for the coordinate system of Inkscape? Please let me know if this does not make sense and I can provide more examples.

**Comment by kaalleen** [comment]
Sorry for the late answer, I somehow must have missed this. If you want to develop your own extension you can read through the inkex documentation provided by Inkscape: https://inkscape.gitlab.io/extensions/documentation/source/inkex.html
