### ISSUE TITLE
pes file just created not opening up in inkscape

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#1517]
i am receiving this message after trying to open a just created pes file with inkstitch i did a complete system restart and tried again and same error

Gus Visser

nk/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: satin-patterns (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 57, in <module>
  File "lib\extensions\input.py", line 49, in run
  File "lib\stitch_plan\stitch_plan.py", line 154, in extents
  File "lib\stitch_plan\stitch_plan.py", line 140, in bounding_box
ValueError: min() arg is an empty sequence

**Comment by tyrosinase** [comment]
Are you trying to open it from `File > Open Recent`? If so, it's probably trying to reach a version that's on removable media that's been removed. It's a known bug in that it should give a better message. In the meantime, if you use `File > Open` to locate it, it should be fine.

**Comment by gusvisser** [comment]
it does not matter how i try to open it it will not read any embroidery files and this just started because i was always able to vdrag and drop them with out issues so is this a windows issue or an inkscape issue or a inkstitch and what can i do to resolve i run windows 10 and newest inkscape and inkstitch

**Comment by tyrosinase** [comment]
What happens when you double-click the file in a Windows window?

**Comment by gusvisser** [comment]
my pes files are associated with pedesign so if i double click it opens with pedesign  but if i tell it to open with inkscape same error

**Comment by tyrosinase** [comment]
But pedesign successfully opens it?

**Comment by gusvisser** [comment]
yes no problem opening up in other software but i need it back into inkscape for some experimenting

**Comment by tyrosinase** [comment]
Was it created in Ink/Stitch or pedesign? Because there's an open bug (#801) concerning non-native Ink/Stitch pes designs that cause that issue (in which case if you are able to send the devs the pes file that would probably help greatly).

**Comment by gusvisser** [comment]
it was created in inkscape with inkstitch

**Comment by tyrosinase** [comment]
I'm officially stumped. Hopefully one of the actual devs has a better idea.

**Comment by kaalleen** [comment]
Hm, difficult to say. This error appears whenever you try to open an embroidery file?

I am wondering if it is an error especially in the Ink/Stitch version you are using (I cannot remember though that the satin pattern branch had an issue like that). Would you mind to test a newer development version of Ink/Stitch? We are close to a next release, so we would like to hear some feedback anyway ;) Maybe try this branch over here, it is almost the current main: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

The installation process for windows has changed a lot though. If you have any questions, please ask. Click on "more" and "run anyway" if the installer warns you about us being evil or something like that.

**Comment by kaalleen** [comment]
No response, closing.
