### ISSUE TITLE
Issue when exporting PES

### ISSUE THREAD

**Issue by sebada001** [inkstitch/inkstitch#1519]
Hey! My first time trying to make a PES file. I keep getting an error everytime I export.

" lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree""
![Screen Shot 2022-01-05 at 5 30 12 PM](https://user-images.githubusercontent.com/96091031/148294140-26df2b86-d1a2-43de-b47c-ec31b9815bce.png)

I did troubleshoot, says no issues, i followed the basic guide. Tried lines, tried filling colors, changing size, everytime the same error. Mac Mojave.

**Comment by tyrosinase** [comment]
That's a known (and fixed in future releases) bug, and is just a warning. The file is created fine, the warning shouldn't have been surfaced.
