### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FoodieLuvr40** [inkstitch/inkstitch#1523]
I'm new to Ink Stitch and I'm trying to save pictures as a PES embroidery file to use on my Brother Embroidery Machine and this is the error message I get. Can anyone help me? 

lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\zip.py", line 47, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment]
That's a known bug; in the future I think Ink/Stitch will properly give you a non-error explanation. At the moment that's what it does when it doesn't have any valid stitch-able objects. You'll find a more thorough explanation in the comments of #1307.
