### ISSUE TITLE
Cannot open Params window - no error

### ISSUE THREAD

**Issue by jenniecahoon35** [inkstitch/inkstitch#1525]
Hello, 

I have recently installed the Inkscape application via the Microsoft Store (v1.1) and subsequently downloaded Inkstitch v2.0.0. I have extracted the zip to the extensions folder as per the installation instructions and can now see and navigate through the menu within Inkscape. 

When I draw a basic shape, convert object to path and attempt to select the Inkscape Params option it does nothing. There is a brief message on the bottom of the screen that says No objects selected. I have used Inkstitch on another laptop before with no issues. The only difference between using it previously is the laptop and how I downloaded Inkscape. 

There is no pop up error message and most of the other menu options open pop up boxes fine. I cannot save the file as an embroidery file ( as expected ) 

Can you assist me with this issue?

Thanks

**Comment by tyrosinase** [comment]
I'm not a Windows user so I can't be too helpful, but that sounds like an antivirus program has quarantined part of Ink/Stitch. If you poke around in some of the other issues where that's been the case (https://github.com/inkstitch/inkstitch/issues?q=is%3Aissue+windows+antivirus+), you can see if that sounds like what is happening.

**Comment by jenniecahoon35** [comment]
Hi Tyrosinase, 

Thank you so much for your response. This is exactly what was happening - Windows was operating in S mode and only allowing apps from the app store therefore blocking the inkstich exe file. I was able to remove this to allow it to run the exe. 

Appreciate your response.

**Comment by W-Joel** [comment]
I'm having the same issue on my Ubuntu 20.04.3 LTS OS (64-bit Gnome version 3.36.8) laptop. Does anyone have a suggestion that might help solve my issue?

Thank you
Joel

**Comment by kaalleen** [comment]
Which Inscape version have you installed and how did you install it?

**Comment by W-Joel** [comment]
I downloaded Ink/Stitch v2.1.2 RPM and extracted it into the destination folder of Inkscape as described in the video tutorial on inkstitch (https://inkstitch.org/tutorials/).

**Comment by kaalleen** [comment]
Oh, I meant Inkscape. The videos in the tutorial section are a bit old by now. We need to update them.

Have a look at here: https://inkstitch.org/docs/install-linux/
For ubuntu you'll need the deb package, not rpm. Also you need Inkscape > 1.0.2

**Comment by W-Joel** [comment]
I'm sorry, I misunderstood. I have Inkscape 1.1.2. I had to use the RPM because I couldn't get the DEB to extract. It only wanted to use the installer and the installer kept giving an error message.
Thank you Kaaleen! I really appreciate the help. :)
Joel

**Comment by kaalleen** [comment]
Is it now working for you?
What happens if you double click the deb package?
If that doesn't work, you can also try the installer script for linux.

**Comment by W-Joel** [comment]
Hi Kaalleen. Thank you for checking on me and my progress! :) 
I was away for an emergency for several days. Going to start working on this again today.
I'll reach out again with success or with a request for a little more assistance.
Thank you again! :)

**Comment by W-Joel** [comment]
I removed the inkstitch files from the extensions folder and rebooted. I then downloaded the .deb and attempted to install. It would not install. Screen shot attached. Any suggestions? Thank you!
[Screenshot from 2022-02-23 11-40-21](https://user-images.githubusercontent.com/99599228/155376423-c1118844-e674-4242-9985-bd24ab03caae.png)

**Comment by W-Joel** [comment]
I just downloaded the .tar.xz and installed it. The test drive of the params still isn't working. Is it possible my system is missing something else that Inkstitch needs to work properly? Thank you Kaalleen!
[Screenshot from 2022-02-23 11-51-04](https://user-images.githubusercontent.com/99599228/155377842-71d19882-3609-448d-8e6f-e377232989e2.png)

**Comment by kaalleen** [comment]
Oh, sorry to hear.
How did you install Inkscape? This could be important.
Are the other Ink/Stitch features working?

**Comment by W-Joel** [comment]
This last time - I downloaded the .tar.xz and installed it using the instructions in the video.
I'm not sure because I haven't learned how to use it yet. Everything appears to be installed and present. The params test from the installation video doesn't work.
Are there other tests you'd like me to try?
[Screenshot from 2022-02-28 11-49-43](https://user-images.githubusercontent.com/99599228/156032909-955033e5-e37b-464d-8765-cff4adddb519.png)

**Comment by buzzmandt** [comment]
How did you install inkscape (not inkstitch) on your Ubuntu system?
If you installed inkscape through the ubuntu software center it installs as a snap. Snap installs of inkscape will not work with inkstitch.

**Comment by buzzmandt** [comment]
open a terminal window
to uninstall the snap version of inkscape, if you haven't done so already from the software center, do
`sudo snap remove inkscape`
after that finishes install the deb version of inkscape with
`sudo apt install inkscape`

now you can install the deb version of inkstitch and it should all work as expected

**Comment by W-Joel** [comment]
Uninstalled and installed Inkscape from a terminal as shown above. Then ran the deb version on Inkstitch. I got this error.
[Screenshot from 2022-03-01 13-36-11](https://user-images.githubusercontent.com/99599228/156237026-cb04fbf7-5f62-4b90-88f0-34d2c3d06046.png)

**Comment by buzzmandt** [comment]
hmmm. did you run inkscape before you tried to install inkstitch? Honestly not sure, but maybe you need to run inkscape first to set up the required folder structure. then close inkscape and try to install inkstitch deb package again.

**Comment by W-Joel** [comment]
Inkscape first then Inkstitch. Tried sh. Got the following error.

joel@joel-G7-7588:~$ cd Downloads
joel@joel-G7-7588:~/Downloads$ sh inkstitch-2.1.2-linux.sh
Gtk-Message: 14:03:42.220: Failed to load module "canberra-gtk-module"

** (inkscape:154396): WARNING **: 14:03:42.221: Invalid option --user-data-directory
mkdir: cannot create directory ‘/extensions’: Permission denied
Installing Ink/Stitch to unable to create /extensions/inkstitch
tar: unable to create /extensions: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
error while extracting Ink/Stitch
joel@joel-G7-7588:~/Downloads$

**Comment by buzzmandt** [comment]
did you run inkscape after you installed it, before you tried to install inkstitch? Run inkscape so it can create the file structure needed by inkstitch before you try to install inkstitch. I'm only guessing but that might be the problem here.

**Comment by W-Joel** [comment]
Using the terminal I'm not able to remove Inkscape and it's mo longer listed in the Ubuntu software center. The terminal says is can't be found. I'm using  sudo remove inkscape. Any suggestions?

**Comment by buzzmandt** [comment]
in this order, in the terminal do
`sudo snap remove inkscape`
`sudo apt install inkscape`
`inkscape`

when inkscape runs select next, next, create new document
close inkscape
install the inkstitch deb package

**Comment by W-Joel** [comment]
Will not remove because it's can't be found...

joel@joel-G7-7588:~$  sudo snap remove inkscape
[sudo] password for joel: 
snap "inkscape" is not installed
joel@joel-G7-7588:~$ 
[Screenshot from 2022-03-01 14-42-17](https://user-images.githubusercontent.com/99599228/156245640-de1ad939-a524-498f-af30-66624498b482.png)

**Comment by W-Joel** [comment]
It's not removed.... It's still in my list of programs and runs. Please see screen shot and the previous screen shot.
[Screenshot from 2022-03-01 15-08-44](https://user-images.githubusercontent.com/99599228/156249317-da83d8aa-2f60-4f6b-a0fd-ec8dd5c54342.png)

**Comment by W-Joel** [comment]
joel@joel-G7-7588:~$  apt show inkscape
Package: inkscape
Version: 0.92.5-1ubuntu1.1
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 80.8 MB
Depends: python2:any, libatkmm-1.6-1v5 (>= 2.24.0), libc6 (>= 2.29), libcairo2 (>= 1.15.8), libcairomm-1.0-1v5 (>= 1.12.0), libcdr-0.1-1, libdbus-glib-1-2 (>= 0.88), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgc1c2 (>= 1:7.2d), libgcc-s1 (>= 4.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.41.1), libglibmm-2.4-1v5 (>= 2.54.0), libgomp1 (>= 4.9), libgsl23 (>= 2.5), libgtk2.0-0 (>= 2.24.0), libgtkmm-2.4-1v5 (>= 1:2.24.0), libgtkspell0 (>= 2.0.10), libjpeg8 (>= 8c), liblcms2-2 (>= 2.2+git20110628), libmagick++-6.q16-8, libpango-1.0-0 (>= 1.37.2), libpangocairo-1.0-0 (>= 1.14.0), libpangoft2-1.0-0 (>= 1.14.0), libpangomm-1.4-1v5 (>= 2.42.0), libpng16-16 (>= 1.6.2-1), libpoppler-glib8 (>= 0.18.0), libpoppler97 (>= 0.86.1), libpopt0 (>= 1.14), libpotrace0, librevenge-0.0-0, libsigc++-2.0-0v5 (>= 2.8.0), libstdc++6 (>= 9), libvisio-0.1-1, libwpg-0.3-3, libx11-6, libxml2 (>= 2.7.4), libxslt1.1 (>= 1.1.25), zlib1g (>= 1:1.1.4)
Recommends: aspell, fig2dev, imagemagick, libimage-magick-perl, libwmf-bin, python-lxml, python-numpy, python-scour
Suggests: dia, inkscape-tutorials, libsvg-perl, libxml-xql-perl, pstoedit, python-uniconvertor, ruby
Homepage: https://inkscape.org
Task: ubuntustudio-video, ubuntustudio-graphics
Download-Size: 14.9 MB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
Description: vector-based drawing program
 Inkscape is an illustration editor which has everything needed to
 create professional-quality computer art. You can use it to make
 diagrams and illustrations, technical drawings, web graphics, clip art,
 icons and logos. A collection of hands-on tutorials show you how to
 combine lines, shapes and text of different types and styles to build
 up a picture.
 .
 A selection of powerful vector graphics editing tools comes as
 standard. There is excellent support for paths, gradients, layers,
 alpha transparency and text flow control. An extensive library of
 filters allow you to apply realistic effects and extensions allow you
 to work with bitmaps, barcodes and printing marks, amongst other things.
 .
 Most of the common vector formats are supported, including PDF, Adobe
 Illustrator and AutoCAD files, and it has unrivalled support for the
 SVG web graphics standard.
 .
 Between the suggested packages:
  * dia: to export Dia shapes;
  * libsvg-perl: to import .txt files (txt2svg extension);
  * libxml-xql-perl: to use the shadow effect;
  * python-uniconvertor: enables several import/export extensions;
  * pstoedit: to work with eps files;
  * ruby: there are several extensions written in ruby;

N: There are 2 additional records. Please use the '-a' switch to see them.
joel@joel-G7-7588:~$

**Comment by buzzmandt** [comment]
Ok. Thank you. I see the problem now. Version too old. 

We can fix this.
In terminal do
`sudo apt remove inkscape`
Then do
`sudo add-apt-repository ppa:inkscape.dev/stable`
Then do
`sudo apt update`
Then do
`sudo apt install inkscape`
then do
`inkscape`

Hit next, next, new document

Close inkscape

Install the deb packag of inkstitch.

Now you should be good to go

**Comment by W-Joel** [comment]
YES!!!!!!!!!!!!!!!! SUCCESS :+1:  :-) Thank you so very very much!!!!!!!!!!!!!!
[Screenshot from 2022-03-01 16-13-09](https://user-images.githubusercontent.com/99599228/156257811-4fefdf81-b7ce-4d6d-be60-12e1071589df.png)

**Comment by buzzmandt** [comment]
Excellent. Happy stitching :)
