### ISSUE TITLE
installation problem!!!!

### ISSUE THREAD

**Issue by CELIAIMBERT** [inkstitch/inkstitch#1528]
Hi,
I'm having a problem installing the inkstitch latest version.

My computer give me this message: This program can only be installed on version of windows that suport these architecture : x64

Is there a possibility to solve this?

**Comment by kaalleen** [comment]
Could you check this release here? https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-windows-installer-32

**Comment by CELIAIMBERT** [comment]
Hi
It's ok for me

Now I have to look for how the filling function works because I can't do it

**Comment by kaalleen** [comment]
Thanks for the feedback.

Patterns... Did you find the way to do it or is it not working for you?

**Comment by CELIAIMBERT** [comment]
Yes I find the way.
Everything is working.

The new version make my keyboards lost but I've remake it and everything is ok for me.

Thanks a lot for this new version.

I'm so proud of the fonts we made!!!
💪🏼💪🏼💪🏼💪🏼

**Comment by kaalleen** [comment]
Yes, thank you. They are so nice to have!!!
