### ISSUE TITLE
Palette installation and use problems under Ubuntu (Debian)

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1529]
Hello, super kudos first for the new version :)

I installed the Debian package v2.1.0 on my Ubuntu 18. It was installed in /opt/inkstitch When I tried to install my own palette I got this error:
-----
Ink/Stitch ne peut pas automatiquement trouver votre dossier de palette . Veuillez installer votre palette manuellement.
Ink/Stitch a connu une erreur inattendue.

Si vous souhaitez nous aider à résoudre ce problème, veuillez soumettre un problème à https://github.com/inkstitch/inkstitch/issues et inclure la description complète de l'erreur ci-dessous :

Ink/Stitch Version: v2.1.0 (linux)
Traceback (most recent call last):
  File "inkstitch.py", line 62, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/install_custom_palette.py", line 38, in effect
  File "shutil.py", line 261, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/opt/inkstitch/bin/palettes/InkStitch Emoji Gunold No.gpl'
----

Then it got more messy (sorry I may have skipped a detail since I was eager to get it done ....)

I then installed the InkStitch Palettes and had to change permissions to the required directory. After that, InkStitch could not find this /opt/inkstitch/bin/palettes/ directory (alias /usr/share/inkscape/extensions/inkstitch/bin/palettes) since palettes are supposed to be in an inkscape directory, i.e. ~/.config/inkscape/palettes. The files have been copied there but on runtime Ink/Stich doesn't see them. 

So, as a workaround I just copied the files to the user palettes directory. That perfectly works  ~/.config/inkscape/palettes
- cheers ! Daniel
PS: By the way it is a good idea that shortcuts are now language independent, but maybe folks need to know that one should remove localized suffixes.

**Comment by kaalleen** [comment]
Ah yes. This will happen for rpm and deb installs. Thank you!!!

**Comment by kaalleen** [comment]
Ok, check this release if this solves the issue: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape-path
