### ISSUE TITLE
HUS file format request

### ISSUE THREAD

**Issue by bharper1408** [inkstitch/inkstitch#1530]
Love using InkStitch however a wider variety of file formats would be extremely useful, Thanks!

**Comment by kaalleen** [comment]
Yes, HUS has been a request for quite a long time. We would need to update our pyembroidery library, but we couldn't yet find the time to do so. Read here for previous discussions: #419

**Comment by kaalleen** [comment]
Closing in favor of previous issue. We'll be working on it... we just don't know when. We have some time troubles.
