### ISSUE TITLE
Cannot install on MacOS - Big Sur 

### ISSUE THREAD

**Issue by adriannees** [inkstitch/inkstitch#1531]
I'm getting the following error: 

"“inkstitch-v2.1.0-osx.pkg” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

**Comment by adriannees** [comment]
After allowing the software I attempted to install and received the following installation error: 

The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. 

I'm on an m1 macbook air so I suspect this software doesn't work with m1 macbooks?

**Comment by kaalleen** [comment]
It should work. But we just discovered, that the authorization for v2.1.0 failed. Before we never authorized our builds. Sorry for your trouble.

**Comment by kaalleen** [comment]
Can you open the installer with Ctrl+Click > Open?

**Comment by kaalleen** [comment]
Would you mind to test this version here?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-notary

**Comment by adriannees** [comment]
hmm it still failed for me. I was able to open the installer but on the last step it threw the same error
<img width="414" alt="Screen Shot 2022-01-13 at 3 54 20 PM" src="https://user-images.githubusercontent.com/5360063/149415032-b57e75a3-2542-4e1c-8276-18479c04f497.png">

**Comment by gopatrik** [comment]
same error ; M1 Mac pro.

**Comment by lexelby** [comment]
Sorry folks, Ink/Stitch definitely won't work on M1 macs, at least not until github actions offers an m1 mac build host type.  :(

**Comment by caryd** [comment]
I get the same thing and I am not on an m1.

**Comment by kaalleen** [comment]
It should work on M1 processors.
When you install Inkscape on M1 computers it should ask to install Rosetta2 (if it is not already installed). This will also help Ink/Stitch to run on these processors.

Can you confirm, that Inkscape has been installed **and run**, before you tried to install Ink/Stitch?

**Comment by grischard** [comment]
It runs on my M1 mac, but I can't confirm that installing and running inkscape is the only thing I've done.

**Comment by kaalleen** [comment]
Have you tried to install and open Inkscape before the installation?
