### ISSUE TITLE
Pattern mode workings

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1536]
Hi
I am playing with the great new pattern feature. **Patterns made from strokes do behave as expected** (as far as I can judge), i.e. points are generated where the strokes meet the ones from the fill.
According to the documentation, " pattern consists of strokes or fill areas (or both at the same time). Strokes will be used to add stitches, while patterns with a fill will remove stitches from the embroidery element."

**Patterns made from fills do not seem to work as expected**, i.e. only the first subpath seems to be taken into account. I point to two sample svg files (plus a simulation made with truesizer), one with a pattern that includes both strokes and fills and the other with only fills. In both cases only one subpath is filled, i.e. the one that sits in the upper right of the rice cracker.

So question: Is this a bug or by design (i.e. a "fill" pattern can only be a single shape) ?

1. http://tecfa.unige.ch/guides/embroid/emoji/AAA_EMOJIS/food_drink/food-asian/rice-cracker-twemoji-inkstitch.svg
2. http://tecfa.unige.ch/guides/embroid/emoji/AAA_EMOJIS/food_drink/food-asian/rice-cracker-twemoji-inkstitch.PNG
2. http://tecfa.unige.ch/guides/embroid/emoji/AAA_EMOJIS/food_drink/food-asian/rice-cracker-twemoji-inkstitch-fills.svg
3. http://tecfa.unige.ch/guides/embroid/emoji/AAA_EMOJIS/food_drink/food-asian/rice-cracker-twemoji-inkstitch-fills.PNG

**Comment by kaalleen** [comment]
It's by design. Just as fills cannot be made out of unconnected shapes. But when I think about it now... I wouldn't know why we shouldn't make it possible.

**Comment by danielkschneider** [comment]
Cool. I will try it out :) I had the suspicion that it had to do with the "fills can only happen in single polygons principle", but nice to hear that you saw the interest !

**Comment by danielkschneider** [comment]
Brilliant ! it does work for both patterns will only fills and patters with fills + strokes. Many thanks :)

![rice-cracker-twemoji-inkstitch](https://user-images.githubusercontent.com/2872643/149200755-19e2eb76-9856-4d15-b596-b198c9a84af8.PNG)
![rice-cracker-twemoji-inkstitch-fills](https://user-images.githubusercontent.com/2872643/149200760-3fcc20a7-e9c0-43a4-87fc-58a04a9e52fd.PNG)

**Comment by kaalleen** [comment]
Thanks for testing. I don't like the fuzzy edges since your fill pattern has also a stroke applied. I updated the branch once more, to apply first the fill patterns and then the stroke. Looks like some of the stroke stitches have been removed by the fill. This also opens new opportunities to add additional patterns into an area that has been freed from stitches through a fill pattern.

**Comment by danielkschneider** [comment]
Wow I can see. Likes flies that would sit on floating bits in a soup :)

**Comment by kaalleen** [comment]
Yes :D Well, the updated build isn't there yet. The windows build environment has a connection problem. So you can't try any updates yet (just in case you were up to do so).

**Comment by danielkschneider** [comment]
OK, thanx much again. Yes I did try the Windows version since I am at home now with windows. But I certainly can wait :)

**Comment by kaalleen** [comment]
It finished just now :)

**Comment by danielkschneider** [comment]
Amazing, you develop faster than I can install !!. So, yes (!) it does work under Windows. Not only with rice crackers, but rice balls too ;) Seriously, that's a serious achievement !!

![rice-ball-noto-inkstitch](https://user-images.githubusercontent.com/2872643/149212638-7fcd1e82-0249-42d6-89e4-b545abc8d4a9.PNG)

**Comment by kaalleen** [comment]
Oh thank you :) This looks much better now!!
