### ISSUE TITLE
Debian 10 missing GLIBC_2.29

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1537]
Thought I'd install Ink/Stitch real quick on my Deb 10 box before a wipe-and-reinstall. Took out the old Ink/Stitch, unpacked the tar.gz, opened Lettering to look at the nifty new fonts, got this:

`[8395] Error loading Python lib '/home/silver/.config/inkscape/extensions/inkstitch/bin/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by /home/silver/.config/inkscape/extensions/inkstitch/bin/libpython3.8.so.1.0)`

Seems bad! But also the reason for the wipe-and-install is that this is a horrifically crufty install that has been around since 2004(!), migrated across several motherboards and drives, and has basically been through my whole journey from total n00b to... slight-less-than-total n00b. I've followed a lot of instructions on questionable web pages to force-install drivers for other distros on this box because that was all that was available to run a cutting machine or whatever, so it's altogether possible it's just my janky setup. (Like, normally I'd just go "change the glibc version? Sure! What could go wrong?")

So anyway, if you want me to sit on the wipe until you get more info on the error, I can do that. Or we can just chalk it up to the cruft and ignore it until/unless someone else has the same issue.

**Comment by kaalleen** [comment]
Aiai, we feared this would happen. We updated the linux version used to build Ink/Stitch with.

**Comment by tyrosinase** [comment]
I'm going to update the Linux version *I* use to build (well, run, I don't usually build from scratch on the main machine) Ink/Stitch with, but I can hold off if you need a Deb 10 test machine for awhile.

**Comment by kaalleen** [comment]
I just figured out, that with ubuntu 18.04 as build environment the glibc version should meet your requirements. I could build a version for you. But we updated to a newer linux version, because there were strange issues in the wxpython gui applications (params, lettering), which made it unusable (all letters were just boxes). So this wouldn't be what I like to see in the release package.

**Comment by tyrosinase** [comment]
Eh, we could probably just put up a note in install telling Deb10 people to build from the dev instructions and that would be adequate. On the one hand we're slower to upgrade than your typical Ubuntu user, but on the other hand we usually know how to build packages ourselves. And on the gripping hand I might be the last Deb10+Ink/Stitch user standing.

Let me go build from the instructions to confirm it works.

**Comment by kaalleen** [comment]
Sure, you can do the manual install.
If you like to test the build: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-linux-version

**Comment by tyrosinase** [comment]
Same error (installing the tar.xz fwiw).

Meanwhile, battling the manual install (turns out Deb10's most current NodeJS is 10.24.0, so now I have nvm *and* npm, and now I'm up to the `make inx` but libgeos is being problematic - it's installed, but something can't find it so I'm hunting down path issues).

**Comment by tyrosinase** [comment]
Hmm, the manually-built one ends up with

```
Traceback (most recent call last):
  File "inkstitch.py", line 21, in <module>
    sys.path.remove(extensions_path)
ValueError: list.remove(x): x not in list
```

Not just on Lettering, but everything. (Well, not `About`, which does tell me I've got the Manual Install version.)

I don't think anaconda agreed with libgeos though, so I won't guarantee it's not a python versioning problem of some sort. (This machine is really a mess.)

**Comment by kaalleen** [comment]
> Same error

Ah well, ok.

The about extension is just a simple inx file, unconnected to any python script. So this one at least should always work.

**Comment by kaalleen** [comment]
Sorry... I didn't answer on the problem itself.  It means, that it needs the path to your system inkscape extensions to be in your paths, but it's not finding it. Which Inkscape version do you use and how did you install it?

The secret behind this is, that we don't use the inkex version shipped with Inkscape, but install a newer version with pip. So we need to make Ink/Stitch to use our version and not the other one.

**Comment by tyrosinase** [comment]
1.0.2 (e86c870879, 2021-01-15), and I'm going to guess from the age that it's the one I built from source (and then went "it works, don't touch it" and didn't mess with it nor Ink/Stitch much after that).

**Comment by kkiely0924** [comment]
So just figured I'd also weigh in..... started to watch this thread b/c I'm curious of any resolution. I'm on an up to date chromebook - Version 97.0.4692.77 (Official Build) (64-bit), but the linux version was running Deb 10 as well -- any luck with this? If there was a resolution up there that worked, I admit I'm not quite sure what to do, but wanted to double check I wasn't missing anything in the thread.

**Comment by tyrosinase** [comment]
I haven't messed with it more (I have the new version working on a Pi and have been using 2.0.x on Deb10), but my next step is to put the manually-built one back in place and see if changing the path can get Inkscape/Stitch to use the right inkex.

**Comment by kkiely0924** [comment]
Ok--closing the loop on my end-- I just went to 11 instead of continuing to mess around with it.

**Comment by tyrosinase** [comment]
Heh, I've actually put my upgrade off hoping to solve this first. But if it can't be fixed with a path change I think I'll write it off as not worth the trouble.

**Comment by kaalleen** [comment]
I'm closing it then. Open a new issue if this is still a problem.

**Comment by danielkschneider** [comment]
Same problem happened with Ubuntu 22 LTS when I tried out inkstitch_0.0.1.kaalleen.fill.to.satin.bridged.rungs_amd64.deb on Jan 8 2025. I took this as incentive to upgrade to 24 LTS ;) It now works.

(sorry did not copy the error message but it was the same except for system and version differences)
