### ISSUE TITLE
Bug in latest release for Mac (Monterey)

### ISSUE THREAD

**Issue by jfk1972** [inkstitch/inkstitch#1541]
After installing v2.1 on my Macbook, I checked Inkstitch to verify the installed version.  I get two "About" items, one indicating the prior version and one indicating the current version. I'm not sure how to determine whether V2.1 is actually installed. Screenshots of the relevant screens are attached.

![3B225E8C-D837-4619-A4ED-95050C325834](https://user-images.githubusercontent.com/45735397/149208317-8c39929c-99f4-4122-87b5-282c1cebeb12.jpeg)
![9C76B218-AD60-4627-ADE2-E80CD8B655B5](https://user-images.githubusercontent.com/45735397/149208335-3109704c-5145-4b8b-adf8-31cfe560300b.jpeg)
![2E01554D-00D3-424C-A598-91F33FFCAC19](https://user-images.githubusercontent.com/45735397/149208342-f9febf1e-65d9-4f96-b665-1e70841e1435.jpeg)

**Comment by tyrosinase** [comment]
I got that behavior (in Linux) when I renamed the extension directory and then forgot to take it out of the directory of extensions. :facepalm:

**Comment by kaalleen** [comment]
Yes :) Looks like you have both versions installed. Open the extensions folder through the inkscape preferences > system > user extensions. Then delete the old inkstitch version. The new one sits in a folder named inkstitch.

**Comment by jfk1972** [comment]
@kaalleen thank you. It looks like your suggestion was what I needed. Was the installer supposed to delete the old version or was I to do that?

**Comment by jfk1972** [comment]
@tyrosinase thank you for the reply. In a different way, your suggestion was right on track.

**Comment by kaalleen** [comment]
It will remove the old installation the next time you update Ink/Stitch. But we cannot predict how you named your folder previously before the installer existed, so for 2.1.0 you still will need to delete the old installation yourself.

**Comment by jfk1972** [comment]
@kaalleen thank you. I will close this issue.
