### ISSUE TITLE
Trouble installing on mac

### ISSUE THREAD

**Issue by MollyVincent** [inkstitch/inkstitch#1545]
Hi there,

I am trying to install your software onto my mac (M1 mac OS Monterey 12.0.1) but I keep getting the same error message (see attached screenshot)

I can see somebody else has has a problem with their mac too and you directed them to this page https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-notary
If this is the solution could you let me know which of the assets I should download?

Thank you so much for your help :-)
Molly

<img width="633" alt="Screenshot 2022-01-13 at 16 16 21" src="https://user-images.githubusercontent.com/97689897/149368686-4930e677-f209-496a-8a9f-f9ce5f71fe3a.png">

**Comment by rejbasket** [comment]
Hello,

the link that you've posted is older than the release you are using. It's not meant to fix the issue you are seeing. This is actually the first time we are seeing it and it would be very helpful if you could give us some more info. This is how you access the error log.

Run the installer again, and on the top most menu you will see the menu entry Window. Click on it, there will be an entry called Installer log. Send  the information there, after the error is occurred, to us. This would be helpful for us to solve this issue.  Thank you.

**Comment by MollyVincent** [comment]
Hi,

Thank you for your fast response. The installer log is saying this (screen shot attached too)

Jan 13 17:40:12 Mollys-MBP-2 Installer[16925]: Failed to load specified background image
Jan 13 17:40:12 Mollys-MBP-2 Installer[16925]: Top component package (null) not found or understood: treat as unsigned
Jan 13 17:40:29 Mollys-MBP-2 installd[2724]: PackageKit: ----- Begin install -----
Jan 13 17:40:31 Mollys-MBP-2 installd[2724]: PackageKit: PKInformSystemPolicyInstallOperation failed with error:An error occurred while registering installation with Gatekeeper.
Jan 13 17:40:32 Mollys-MBP-2 installd[2724]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “inkstitch-v2.1.2-osx.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/mollyvincent/Downloads/inkstitch-v2.1.2-osx.pkg, PKInstallPackageIdentifier=org.inkstitch.installer, NSLocalizedDescription=An error occurred while running scripts from the package “inkstitch-v2.1.2-osx.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cinkstitch-v2.1.2-osx.pkg\U201d.";
	    NSURL = "file://localhost/Users/mollyvincent/Downloads/inkstitch-v2.1.2-osx.pkg";
	    PKInstallPackageIdentifier = "org.inkstitch.installer";
	}
Jan 13 17:40:33 Mollys-MBP-2 Installer[16925]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jan 13 17:40:33 Mollys-MBP-2 Installer[16925]: Displaying 'Install Failed' UI.
Jan 13 17:40:33 Mollys-MBP-2 Installer[16925]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

<img width="1697" alt="Screenshot 2022-01-13 at 17 41 55" src="https://user-images.githubusercontent.com/97689897/149381527-71086265-4bd0-4110-a251-7cdfcfa813bd.png">

**Comment by rejbasket** [comment]
It looks like the installer log isn't helpful in explaining the issue. The Console app has the install log in full: located at /Applications/Utilities/Console.app or press (⌘) + spacebar to access the Spotlight Search and typing Console.
In the Console app on the left side is Log Reports. From there is an entry install.log. Send the information there. There should be the information of why the error occurred.  Again send this information.

**Comment by lexelby** [comment]
@rejbasket I think the problem is thr M1 mac. M1 uses the arm instruction set, which we're definitely not targeting.  I think we may need to wait for github actions to offer m1 macs?

**Comment by kaalleen** [comment]
We are aware, that logically the processor should be the problem. But we are so desperately trying, because I happen to know, that there are running M1 installs out there. But you may be right.

**Comment by lexelby** [comment]
Oh interesting!  I wonder how that works...

**Comment by rudys7** [comment]
I am joining this late, but I too am getting the same error message.  I have MacBook Air  M1, Monterey.  
This is the dialog in the instal log:
2022-02-03 21:49:15-06 MacBook-Air-2 Installer[10571]: Displaying 'Install Failed' UI.
2022-02-03 21:49:15-06 MacBook-Air-2 Installer[10571]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
2022-02-03 21:49:49-06 MacBook-Air-2 Installer[10571]: Package Removal: User opted to remove package.
2022-02-03 21:49:49-06 MacBook-Air-2 Installer[10571]: Package Removal: Successfully removed package.
2022-02-03 22:00:15-06 MacBook-Air-2 nbagent[1161]: NBStateController: Connection interrupted

Does this mean that I will not be able to run your program on my Mac?  

Thank you in advance for your assitance!

**Comment by kaalleen** [comment]
It should work because there is something called rosetta, it is installed on M1 computers along with Inkscape.

The installation usually fails for macOS users  when Inkscape isn't installed or hasn't been opened. It needs to be installed before the Ink/Stitch installation. Also it must have been opened just once, otherwise the extension folder hasn't been created yet and Ink/Stitch has no place to go.

**Comment by kaalleen** [comment]
Ink/Stitch has been updated in the meantime. If there are still installation issues, please open a new issue.
