### ISSUE TITLE
Feature request? Add a info message instead of error message.

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1551]
[2022-01-16 19:33:53,120] ERROR in app: Exception on /stitch_plan [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2073, in wsgi_app
  File "flask/app.py", line 1518, in full_dispatch_request
  File "flask/app.py", line 1516, in full_dispatch_request
  File "flask/app.py", line 1502, in dispatch_request
  File "lib/api/stitch_plan.py", line 22, in get_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 24, in stitch_groups_to_stitch_plan
IndexError: list index out of range

I got this error when setting the repeats of the placement and outline stitches to "0". (see attatched file)
I know it does not make sense to set it to "0", but instead of this error message above, could you display something along the line 
repetitions must be at least 1, 
how to fix this:
go to the params window and set the straight stitch parameter "repetitions" to 1 or more. 

[WideStrapExtender_Tina.zip](https://github.com/inkstitch/inkstitch/files/7877659/WideStrapExtender_Tina.zip)
c

**Comment by tyrosinase** [comment]
It should be a warning and not an error because I actually do like being able to set repeat to zero (though I didn't mean to on that design) for non-stitching items, just because I am the queen of accidentally converting a command object into a cute little stitched-out balloon in my design somehow.

**Comment by kaalleen** [comment]
Hm, I wonder how we should handle this. There are two options I believe:
* set minimum value to 1 while rendering the object
* allow 0 and do not stitch the object

**Comment by lexelby** [comment]
I think we should treat a value of 0 as 1.  People might think "zero repeats" just means "stitch it once and don't repeat it again".

**Comment by tyrosinase** [comment]
That, or have some kind of annotation, so "0" makes it say "do not stitch" next to it, "1" says "stitch once," and 2+ says "stitch N times."

That would be nice for bean too: when it's at the default "0" it could say "no reverse stitches" and "1" could say "3 layered stitches" or something. Bean isn't *that* ambiguous but it would help those of us whose brains suddenly go into second-guess mode: "wait, is 1 the default or 0? I CAN'T REMEMBER"
