### ISSUE TITLE
Mac OS Monterey 12.1 - Intel chip set. Failure to run software - Not in application folder 

### ISSUE THREAD

**Issue by Ceberus63711** [inkstitch/inkstitch#1556]
The screen shots attached show the successful process of the install. 

Ink stitch is not found in any of the application folders. 

When the small 3.5 floppy disk icon is actioned , nothing happens other than a bouncing icon. 

Please review this request and let me know what the devs need to investigate. 
<img width="1440" alt="Screen Shot 2022-01-22 at 8 27 27 PM" src="https://user-images.githubusercontent.com/98245471/150663673-215412b9-b36e-44e6-95a5-de4f370d0ed3.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 27 31 PM" src="https://user-images.githubusercontent.com/98245471/150663674-a3a7f592-1539-43a8-b917-266c072d9d91.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 27 37 PM" src="https://user-images.githubusercontent.com/98245471/150663675-860d63a4-cd33-4d60-8e96-50449e717fe9.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 27 45 PM" src="https://user-images.githubusercontent.com/98245471/150663676-e79795f8-05e8-4012-aed4-66f11f1f4852.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 27 49 PM" src="https://user-images.githubusercontent.com/98245471/150663677-5e287405-0392-49a0-8654-b3b60cc4cf85.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 29 31 PM" src="https://user-images.githubusercontent.com/98245471/150663679-3bf207b3-565e-476c-ba28-67707141b97e.png">
<img width="1440" alt="Screen Shot 2022-01-22 at 8 29 50 PM" src="https://user-images.githubusercontent.com/98245471/150663680-c76d6699-0de5-4928-8f47-a02eb6bce711.png">

Thank you.

**Comment by kaalleen** [comment]
It may seem to make sense to search for it in the applications menu. But Ink/Stitch actually is no application on it's own, but an Inkscape plugin. Open Inkscape and see if Ink/Stitch is part of the menu in the extensions section.

**Comment by Ceberus63711** [comment]
> It may seem to make sense to search for it in the applications menu. But Ink/Stitch actually is no application on it's own, but an Inkscape plugin. Open Inkscape and see if Ink/Stitch is part of the menu in the extensions section.

Thank you. This corrected my "problem". 

I did think it the was a stand alone program. 

The program is working correctly. Now I just have to learn how to use it. :)
