### ISSUE TITLE
rendering showing part of the object that doesn't exists

### ISSUE THREAD

**Issue by anibaljasin** [inkstitch/inkstitch#1558]
I'm using Inkscape 1.1.1 and ink/stitch 2.1.2 in Linux (ubuntu). I'm new to this software.

I use the clip tool to achieve the design I want and get something like this:

![rafa-ink](https://user-images.githubusercontent.com/14918358/150697232-3c55af9a-e147-4f76-b901-dedc3f1ec30f.png)

But then when I try to visualize how it is going to print it shows this:

![rafa-bor](https://user-images.githubusercontent.com/14918358/150697265-dd0f66a3-be08-433f-a357-e15dcc8e1a1b.png)

It shows more stuff below the heart that I already deleted, but I cannot get rid of it. 

Any idea what can I do to achieve the result I want?

If you need more info just let me know, I'm new to this and trying to improve my skills. Thanks!

**Comment by tyrosinase** [comment]
I don't think Ink/Stitch honors clips (the object still exists, it's just hidden). What you want instead is to dupe that heart and do a Path > Intersection on each shape, to permanently delete the parts you don't want to stitch. (And dupe the black to do a Path > Difference on the final heart to cut out the part under the other colors; Path > Break Apart to get rid of the other fills.)

You're also going to definitely want to convert that black outline to satin, not fill.

You can skip over the parts of this that convert from bitmap, but the parts after it are probably things you want to look at: https://silverseams.com/tutorials/digitizing-with-ink-stitch/

**Comment by anibaljasin** [comment]
Thank you it worked! I was able to remove each shape using the first technique you mention Path > intersection. Then when I did Path > Difference using the heart and the outline I lost the black outline, so I created a black heart, put it on the back and the boy above it, and do a Path > intersection.

Now I have this:
![image](https://user-images.githubusercontent.com/14918358/150699456-5fa0bfdb-f931-4916-85ff-b63e40e00740.png)


I didn't get the part about satin instead of fill, I know they are different types of lines, but why do you recommend one instead of the other?

**Comment by tyrosinase** [comment]
Fill will make a grid of stitches regardless of the orientation of the lines, where satin will (assuming your rungs etc. are correct) smoothly stitch relatively perpendicularly to the lines. Really, what it boils down to is just that satin draws lines, fill... fills.

Really, if you want to see the difference, crop down to a small piece of the detail and let it stitch out in fill, and compare it to the pictures in that link. It'll show you much better than I can tell you.

**Comment by anibaljasin** [comment]
Okay thanks! I'll try it, but your help worked!
