### ISSUE TITLE
Inside-out circle (transform glitch?)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1561]
Okay, how's this for weird?

Stitched out one side of a plush orca just fine, started to stitch the mirrored side and got... this. That's a circle.

![image](https://user-images.githubusercontent.com/9473609/151247819-d2b2d028-17b6-459c-b439-182b55a89265.png)

More accurately, it's a round path, since this is descended from a file from before Ink/Stitch handled circle objects.

But you (or at least I) can reproduce it: make a circle, convert it to a path, flip it vertically or horizontally with the toolbar, and it stitches out like this.

Now, caveat, this is on the Deb10 machine I haven't upgraded yet, still running that manually-built 2.0.0, so if the newer versions don't do this then it's no big deal.

Any trivial change, like a slight rotation or making the nodes corner then smooth again, eliminates the glitch.

**Comment by kaalleen** [comment]
Huh yes, that's weird... But yes, still reproducable :D

**Comment by kaalleen** [comment]
Not reproducible anymore. Closing.
