### ISSUE TITLE
auto_fill: NetworkXNoPath

### ISSUE THREAD

**Issue by SFemb** [inkstitch/inkstitch#1562]
error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.1.2 (osx)

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 246, in to_stitch_groups
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 74, in auto_fill
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 633, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 595, in travel
  File "networkx/algorithms/shortest_paths/generic.py", line 162, in shortest_path
  File "networkx/algorithms/shortest_paths/weighted.py", line 2117, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (140.81118031235286, 232.44094488189003) and (138.15368465696434, 232.2944660269735).

**Comment by kaalleen** [comment]
Hey there. Sorry for your trouble and thank you for reporting the error message. We are chasing this error for quite a while. Unfortunately, we didn't yet receive a svg file, which could enable us to reproduce the error easily. If you don't mind, we would be very happy to receive yours. You can either post it here wrapped in a zip-archive or send it to our mail address send-us-files@inkstitch.org

**Comment by SFemb** [comment]
Hi, thank you for the response! I don’t really know what happened, but I did try reinstalling inkstitch and closing the app and reopening it a few times.  Somewhere along the line it seemed to fix the problem and I didn’t get the error message anymore and everything was okay….so I’m not sure if it would be any help at this point. I can still send it if you’d like, please let me know. Thanks again!

**Comment by tyrosinase** [comment]
Okay, I have a file!

This little guy works interestingly: the problem child is the outer flame, but if you select it by itself it's fine, and Troubleshooting is happy with it. So clearly the problem only triggers when it's adjusting its end point based on the other colors. If you move the dark gold layer before the gold layer, it's happy.

![SilverSeams_CandleEmoji](https://user-images.githubusercontent.com/9473609/197230738-d8a4e855-06ae-42a6-a671-d91d9541105d.svg)

**Comment by tyrosinase** [comment]
It gets the same error, FWIW, when trying to do a contour fill, so I don't know if it's the underlay that's doing it or what.

![IMG_4039](https://user-images.githubusercontent.com/9473609/197301028-58682a59-2f3a-41c5-8240-94b85e96517d.JPEG)

And unrelated but fun: contour fill makes some weird-but-cool effects sometimes.

![IMG_4038](https://user-images.githubusercontent.com/9473609/197301857-e17e3aa7-61a7-40d0-815d-168922c08c13.JPEG)

**Comment by kaalleen** [comment]
Thanks for the file. The error is reproducible. We have an other issue with the same error. I'll close this one so we can discuss it in #2056
