### ISSUE TITLE
Installation Error macOS Catalina v10.15.7

### ISSUE THREAD

**Issue by emilieofgloom** [inkstitch/inkstitch#1563]
Hi,

I am receiving an installation error

![Screen Shot 2022-01-28 at 5 15 00 pm](https://user-images.githubusercontent.com/98576155/151497088-b7f310b2-e848-4030-bc11-a72dc1f132a1.png)

Does anyone have any insight?

Thanks!

**Comment by mnhouston** [comment]
same issue on BigSur macOS

**Comment by rejbasket** [comment]
The Console app has the install log in full: located at /Applications/Utilities/Console.app or press (⌘) + spacebar to access the Spotlight Search and typing Console.
In the Console app on the left side is Log Reports. From there is an entry install.log. Send the information there.

**Comment by mnhouston** [comment]
you want this info or i need to send the install download there?

**Comment by rejbasket** [comment]
Run the installer again to the point where it failed. Open the Console app as previously instructed and copy and paste the text here as a response. The information contained from the install.log will show how and where the install failed.

**Comment by emilieofgloom** [comment]
Hi all,

I solved the problem.

I had not realised that Ink/Stitch was an extension to InkScape. 

I was looking for an embroidery program and came across Ink/Stitch but didn’t see anything about InkScape. I thought it was a stand alone program.

So I didn’t even have InkScape installed! That was the issue.
