### ISSUE TITLE
copy objects to clipboard in inkscape starts inkstitch process which runs for a long time

### ISSUE THREAD

**Issue by doj** [inkstitch/inkstitch#1566]
I am using inkscape 1.1 on Linux, and inkstitch 2.1.2

If I cut or copy many objects from a layer (to the clipboard), inkscape becomes unresponsive. I see that an inkstitch process is started which is consuming 100% CPU. If I (repeatedly) "killall -9 inkstitch" then after several inkstitch process starts and kills, inkscape works again. The window title of inkscape now shows 'Memory document 4'.

I don't need to do anything special before this happens for me, I can simply open a SVG file with inkscape, select many objects in a layer, then press CTRL+c. I don't know why the inkstitch process is started as a result of copying objects to the clipboard, but the inkstitch process should at least not block inkscape, or at least finish whatever it is doing within a few seconds.

**Comment by kaalleen** [comment]
Hm, that is odd. Ink/Stitch cannot start itself when a pure Inkscape function is run. I have no idea what could cause this.
Do you also see this happening with recent Inkscape (and Ink/Stitch) versions?

**Comment by kaalleen** [comment]
Closing since there have been update to both Inkscape and Ink/Stitch. Please feel free to open a new issue if you are still having issues with this.
