### ISSUE TITLE
small fill not detected

### ISSUE THREAD

**Issue by PaulH95000** [inkstitch/inkstitch#1573]
Hello All,

I recently downloaded the latest version of Inkstitch for BigSur (MacOs) as well as updated to last available version of inskcape.

My problem is that small fill issues seem to not be detected while troubleshooting anymore.

Has anyone already had this issue?

Thanks !

**Comment by PaulH95000** [comment]
Also, my Inskcape other become totally unresponsive (can't click on anything in the software) and to have it working again i have to reinstall Inskcape. I'm not sure but it might be after I troubleshoot an object which should have small fill but is not detected. (I get the message that no errors are detected with the selected objects)

**Comment by Marif91** [comment]
Il faut paramétrer la taille des remplissages que tu souhaites éliminer, j'ai la même configuration que toi et pas de souci !

**Comment by kaalleen** [comment]
Probably fixed? I'm closing the issue. Please open new issue if you still have problems detecting small fills.
