### ISSUE TITLE
Can't install on Mac 12.1

### ISSUE THREAD

**Issue by brianrizzo** [inkstitch/inkstitch#1575]
Feb  7 22:58:53 BRIANsiMac Installer[30949]: Failed to load specified background image
Feb  7 22:58:53 BRIANsiMac Installer[30949]: Top component package (null) not found or understood: treat as unsigned
Feb  7 22:59:22 BRIANsiMac installd[764]: PackageKit: ----- Begin install -----
Feb  7 22:59:24 BRIANsiMac installd[764]: PackageKit: PKInformSystemPolicyInstallOperation failed with error:An error occurred while registering installation with Gatekeeper.
Feb  7 22:59:26 BRIANsiMac installd[764]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “inkstitch-v2.1.2-osx.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/brianrizzo/Downloads/inkstitch-v2.1.2-osx.pkg, PKInstallPackageIdentifier=org.inkstitch.installer, NSLocalizedDescription=An error occurred while running scripts from the package “inkstitch-v2.1.2-osx.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cinkstitch-v2.1.2-osx.pkg\U201d.";
	    NSURL = "file://localhost/Users/brianrizzo/Downloads/inkstitch-v2.1.2-osx.pkg";
	    PKInstallPackageIdentifier = "org.inkstitch.installer";
	}
Feb  7 22:59:26 BRIANsiMac Installer[30949]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Feb  7 22:59:26 BRIANsiMac Installer[30949]: Displaying 'Install Failed' UI.
Feb  7 22:59:26 BRIANsiMac Installer[30949]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by rejbasket** [comment]
Thank you for providing us the inkstitch log information. What stands out the most is the error related to the Gatekeeper: PKInformSystemPolicyInstallOperation failed with error: An error occurred while registering installation with Gatekeeper.
This error is occurred when the computer isn’t connected with the Apple authentication servers to check if the installer is notarised and signed, in which it has been. Also it could be possible the Gatekeeper has quietly crashed and isn’t running or even disable for some reason( i.e: updating your OS ). A reboot may fix this issue. Let us know if the issue persist or you may have fixed this issue.

**Comment by kaalleen** [comment]
Ink/Stitch needs Inkscape (current version 1.1.2 => https://inkscape.org/release/inkscape-1.1.2/) to be installed first. It is also a requirement, that Inkscape has been run at least once, before the Ink/Stitch installation.

Just to ensure, can you confirm that Inkscape is installed on your mac?

**Comment by kaalleen** [comment]
Close this, since we didn't get an answer back. Usually this error shows up, when Inkscape never run before the Ink/Stitch installation.
