### ISSUE TITLE
ZIP: add input field for custom file name

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1576]
So I thought I might export the Dinomouse font pre-rendered for non-Ink/Stitch people, and hid everything but the first glyph, did a Save As..., saved it as $GLYPH.zip, but realized all the filenames are dinomouse72.pes etc. inside the ZIP file.

I feel like if I'm renaming the ZIP that ought to rename everything inside it to match (and, uh, now I'm not sure if I don't have some of my freebies on the blog saved with unexpected filenames inside the zips, whoops). Would that be doable?

**Comment by kaalleen** [comment]
I am not sure how we can access the target file name from there. Maybe that's the reason for this behaviour. Do you know more about this issue @lexelby ?

**Comment by lexelby** [comment]
I'm afraid that's not doable at all, I'm sorry to say. :/  I'm pretty sure by the time you're providing a file name to save the zip as, the zip is already created.

We could have an option for the file name that you enter _before_ the zip is created, in the output extension preferences.  That would pop up when you click "save as", before the dialog to choose where to save the zip.  It might feel a little weird to specify the file name twice (once for the files _inside_ the zip and the second for the zip itself).

**Comment by tyrosinase** [comment]
I was afraid of that. Mostly the problem is that I was unaware of that behavior (I would have made sure I saved the SVG under a new name and then made the ZIP, which I probably mostly did anyway). Being able to export the fonts pre-rendered (basically the reverse of the letters-to-font tool) would solve the Dinomouse case but I don't care about non-Ink/Stitch users *that* much. 😜 

(But wait, the zip can't already be created because that's before the little prompt with all of the "what would you like *in* your zip?" options, isn't it?)

**Comment by tyrosinase** [comment]
Is there any hope for a fix for this? It would *really* streamline my workflow... currently I'm re-doing the jumping spider plushie, with a bunch of different eye styles and spot styles, so twelve variations. If I want them to have different filenames inside the zip, I have to save the SVG under a new name twelve different times, then Save A Copy As, then delete the extra dozen SVG's out of the directory. And that's a design I'm only doing in one hoop size. Don't even get me started on the pumpkins and all their faces and hoop sizes. 😩

![IMG_3387](https://user-images.githubusercontent.com/9473609/190879630-641c23f1-247b-4213-beea-674654591b39.JPEG)

**Comment by kaalleen** [comment]
Wow, that's nice looking!

I'm afraid there is still no better option than the one mention by lex (type in the filename twice). You could write a feature request to the inkex team if you like?

**Comment by tyrosinase** [comment]
Here's where I sheepishly admit I have no idea what inkex is or what I'd be asking them to do.

**Comment by kaalleen** [comment]
Oh, sorry. Inkex is the extension library from Inkscape. So you would basically ask the Inkscape people. I just expressed myself badly. What we are missing to make it happen is access to the file name during the save process. We have no possibility to acess it from our extension (as far as I know - but even Inkscape core extensions do make a second file name request before they do savings into a zip archive).

**Comment by kaalleen** [comment]
An other idea would be, that we grab the title element from the document properties if present.

So we would be searching for a file name in that order:
1. title attribute present? -> use that
2. has the svg file been saved? -> use that
3. fallback to default

But that are all workarounds and I'm not so sure what to think about them.

**Comment by lexelby** [comment]
I think @tyrosinase is saying that at least having an input box for the file name in the zip extension dialog would be a huge improvement, right?

@tyrosinase Are you running in Linux?  Or maybe windows subsystem for linux or mac?  This script `rename-zip.sh` can rename a zip file and its contents:

```
#!/bin/bash

zip="$1"
zip_prefix="${zip%.zip}"
new_zip="$2"
new_zip_prefix="${new_zip%.zip}"
temp_dir="$(mktemp -d)"

unzip "$1" -d "$temp_dir"
for file in "${temp_dir}"/*; do
    mv "$file" "${file/${zip_prefix}/${new_zip_prefix}}"
done

zip -j "${new_zip}" "${temp_dir}"/*

rm -rf "${temp_dir}"
```
You'd save your zip using the default file name, then rename it like this:

```
bash rename-zip.sh default_name.zip your_name.zip
```

That will rename `default_name.zip` to `your_name.zip` _and_ rename all the contained files accordingly.  It actually makes a new zip and keeps the old one there.  I hope that helps!

**Comment by tyrosinase** [comment]
Ooh, thanks, that works well. I kept meaning to write a Perl script, but...

An input box would be spiffy though.

**Comment by kaalleen** [comment]
Input field is now available.
