### ISSUE TITLE
Sacramarif has a kerning error

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1583]
It's probably about time for me to learn how the json files are set up and just submit a patch, but in the meantime: the "ll" in Sacramarif has a ker ning error.

![image](https://user-images.githubusercontent.com/9473609/154822578-dd7db476-c91d-4e41-a828-62db058e16c5.png)

**Comment by Marif91** [comment]
L'erreur sera corrigée dans la prochaine version, il faut transformer "l": 28 en "l": 21.

**Comment by Augusa** [comment]
It will be corrected in the next version. You just nead to add the line "l": 21, in the json file.

**Comment by tyrosinase** [comment]
Awesome, thanks.
