### ISSUE TITLE
Params crashing on v2.1.2, High Sierra, inkscape 1.1.2

### ISSUE THREAD

**Issue by syntactical** [inkstitch/inkstitch#1584]
Whenever I run the "Params" option under Extensions > Ink/Stitch > Params, the window opens briefly, then closes.  I'm on macOS High Sierra 10.13.6, have just installed Ink/Stitch v2.1.2 using the instructions found [here](https://github.com/inkstitch/inkstitch/issues/1205#issuecomment-840000923), and have just installed Inkscape 1.1.2.  The only thing I have not tried yet is uninstalling and reinstalling Inkscape, but I wanted to post this issue here.

Thank you,

**Comment by kaalleen** [comment]
Which processor type do you have?
Did you run the Ink/Stitch installer?
I am just wondering, because the linked issue didn't use the current installation routine yet.

**Comment by kaalleen** [comment]
No response, closing.
