### ISSUE TITLE
Missing Params Options 

### ISSUE THREAD

**Issue by goodlilfellaz** [inkstitch/inkstitch#1590]
Hi I only have 3 options and i don’t know why! And i don’t what i did wrong with the picture.
![image](https://user-images.githubusercontent.com/100501614/155867183-3aa158ec-05d0-48e6-8423-bbfe5d79d99b.jpg)

**Comment by kaalleen** [comment]
That's ok, since you have only fills it will only show you the fill options.

For more info on how to create the various stitch types read here: https://inkstitch.org/docs/stitch-library/
Or search on YouTube for videos. There are some videos out there that may help you with your task.
