### ISSUE TITLE
v2.1.2 .deb installer does nothing on Inkscape 1.1.2 (0a00cf5339, 2022-02-04)

### ISSUE THREAD

**Issue by amordesoul** [inkstitch/inkstitch#1592]
Installation appears to have finished but there is no Inkstitch in the extensions menu. 

OS 21.10 (impish)

**Comment by buzzmandt** [comment]
You have the snap version of inkscape. It doesn't work. Uninstall the snap version and install the apt repos version of inkscape.

**Comment by kaalleen** [comment]
No response, closing.
