### ISSUE TITLE
Nothing happens after apply and quit in params

### ISSUE THREAD

**Issue by SadraLhotmart** [inkstitch/inkstitch#1593]
Hi guys

Inkscape 1.1.2 (0a00cf5339, 2022-02-04)
Ink/Stitch V2.1.2 (Linux)

I have an issue with no error.
Extension installation seems ok
params opens
vizualisation seems ok
but when i click apply and quit, nothings more seems happen and there is no error.

does anyone ever sen that ?
do i somethings wrong ?
how can i find log or monitor that ?

https://user-images.githubusercontent.com/10673251/156280734-7fe03585-092b-4195-affc-1e6b295c99ec.mp4

**Comment by tyrosinase** [comment]
That's normal. The parameters are applied, but there's nothing that visibly happens to the SVG (though some things do happen in the file itself). You can go into `Visualize and Export > Simulator` to see what will happen when the SVG is turned into a stitch file. And Save As... [a stitch file format] is where the *real* magic happens.

(Well, technically the real magic happens after *that* when you put it on the embroidery machine and run it.)

**Comment by SadraLhotmart** [comment]
Ok i see.
I used it 2 or 3 years ago and it seems to work differently now so i lost all my spots.
thanks for your answer and your informs.
I have to keep testing thanks a lot and sorry for the inconveniences.
