### ISSUE TITLE
Windows 7 Missing dll file

### ISSUE THREAD

**Issue by smithdog** [inkstitch/inkstitch#1594]
Hi.

I have recently downloaded Inkstitch to complement Inkscape and gor the following error message

 The program can't start because
api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer.
Try reinstalling the program to fix this problem.

I have unistalled inkstitch and reinstalled and had the same error issue.

I have this installed on a windows 10 machine without any issue.

Can you help ?
![drawing](https://user-images.githubusercontent.com/100982828/156866122-30154353-bb46-4eae-b956-f6db0ba9a463.svg)
 Regards

Mark Smith
Western Australia

**Comment by Schnippsel** [comment]
Try this:
https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-api-ms-win-crt-runtime-l1-1-0dll-is/faffd6b5-b35b-4c41-bda0-fae33ed80b87

**Comment by kaalleen** [comment]
No response, closing.
