### ISSUE TITLE
After a new personal police...

### ISSUE THREAD

**Issue by terpene33** [inkstitch/inkstitch#1597]
Si vous souhaitez nous aider à résoudre ce problème, veuillez soumettre un problème à [https://github.com/inkstitch/inkstitch/issues](https://github.com/inkstitch/inkstitch/issues?fbclid=IwAR37NBAjZFPfSRbcHI94xKBCk-xtyqxIX06oKKEbhRGP0KdNTVLqWumzQtE) et inclure la description complète de l'erreur ci-dessous :
Ink/Stitch Version: v2.1.2-sierra (osx)
Traceback (most recent call last):
File "inkstitch.py", line 67, in <module>
File "inkex/base.py", line 147, in run
File "lib/extensions/lettering.py", line 428, in effect
File "lib/extensions/lettering.py", line 54, in __init__
File "lib/extensions/lettering.py", line 146, in update_font_list
File "lib/lettering/font.py", line 84, in __init__
File "lib/lettering/font.py", line 90, in _load_metadata
File "json/__init__.py", line 293, in load
File "json/__init__.py", line 335, in loads
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

**Comment by terpene33** [comment]
I have erase Inkstitch and inkscape and make a new install but it's the same error message.

**Comment by kaalleen** [comment]
How was your json file created? Did you use the Ink/Stitch extension to do so?

**Comment by lexelby** [comment]
@kaalleen We should probably be able to handle a JSON file with a unicode BOM...

**Comment by kaalleen** [comment]
Yes, definitely we should. Since we both do not have any time for Ink/Stitch at the moment, I was wondering, if more people are having the issue due to the way Ink/Stitch handles it right now.

**Comment by tyrosinase** [comment]
I don't know Python (yeah, I guess I should learn it) so maybe this is altogether invalid but would this work?

```
    def _load_metadata(self):
        try:
            with open(os.path.join(self.path, "font.json"), encoding="utf-8") as metadata_file:
                self.metadata = json.load(metadata_file)
        except IOError:
            try:
                with open(os.path.join(self.path, "font.json"), encoding="utf-8-sig") as metadata_file:
                    self.metadata = json.load(metadata_file)
            except IOError:
                pass
```

**Comment by kaalleen** [comment]
@tyrosinase Thank you for looking into it. I am not sure if we could just skip the utf-8 part and try utf-8-sig directly.

The way you set it up will not work though, because it actually can find and open the file - but cannot parse it. This means, it will not trigger the ioerror exception in our case here.

I am wondering, if you want (or already have) write access to the repository?
