### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by BrainDeadVin** [inkstitch/inkstitch#1600]
I have followed several tutorials including the one on inkstich's youtube. I tried following the "read me" file first. It wont install. If i went to a super old version i could get it to show up in my extensions list finally but not function. I am on windows 10.

**Comment by BrainDeadVin** [comment]
Heres the course of events for me

1. install inkscape itself, ensure its up and running
2. go to https://inkstitch.org/docs/install/ and hit windows
3. install v2.1.2 for windows
4.  "this is already installed" is my current error message but it also wont let me uninstall in in my settings. I tried to search and find any left over files from previous attempts and i deleted them all, same error

**Comment by kaalleen** [comment]
Uh, sorry for your trouble.

What you could do at this point is maybe trying a developer version which is supposed to override the old install during the installation routine: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kall-test/inkstitch-kall-test-windows.exe

**Comment by kaalleen** [comment]
No further response. The next to come Ink/Stitch version will overwrite existing Ink/Stitch installations. So I am going to close the issue.
