### ISSUE TITLE
Installation Failed Error when installing Inkstitch on Mac

### ISSUE THREAD

**Issue by sarjgig** [inkstitch/inkstitch#1604]
Hello! I'm trying to install inkstitch for my mac, which is running Big Sur 11.6.4. 

I downloaded the version for Big Sur from this site: https://inkstitch.org/docs/install-macos/

When I try to install it, it takes me almost all the way through the process. When it gets to "Validating Files" I get this error: "The Installation Failed: The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

I also tried to install the version for older OSs just in case and received the same error.

Any suggestions? Thanks!

**Comment by ezekielcreativeco** [comment]
I am having the same issue. Does anyone know a work-around?

**Comment by kaalleen** [comment]
Hey there, thanks for you feedback and posting your trouble. I am not quite sure, which steps you have done before trying to install Ink/Stitch. This may be something you've done already, but I'd like to confirm...

Ink/Stitch needs Inkscape (current version 1.1.2 => https://inkscape.org/release/inkscape-1.1.2/) to be installed first. It is also a requirement, that Inkscape has been run at least once, before the Ink/Stitch installation.

**Comment by sarjgig** [comment]
> Hey there, thanks for you feedback and posting your trouble. I am not quite sure, which steps you have done before trying to install Ink/Stitch. This may be something you've done already, but I'd like to confirm...
> 
> Ink/Stitch needs Inkscape (current version 1.1.2 => https://inkscape.org/release/inkscape-1.1.2/) to be installed first. It is also a requirement, that Inkscape has been run at least once, before the Ink/Stitch installation.

Hi Kaalleen, ah that's probably it. I went straight for Ink/Stitch. I'll try installing Inkscape first. Thank you!

**Comment by MATTALUI** [comment]
> Ink/Stitch needs Inkscape (current version 1.1.2 => https://inkscape.org/release/inkscape-1.1.2/) to be installed first. It is also a requirement, that Inkscape has been run at least once, before the Ink/Stitch installation.

Just wanted to confirm that this was the fix for me. Thanks!

**Comment by kaalleen** [comment]
Thank you for the feedback!
