### ISSUE TITLE
Compensation and stitch direction for fills in stitch patterns

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1606]
Hello !
it would be nice to have some parameters for fills in stitch patterns. The two most important ones are:
- compensation (workaround could be adding a stroke pattern on top)
- direction of the stitches (workaround is to change stitch direction of the fill pattern)

The following is a picture of a 45mm brocoli emoji and would like to have this feature. There is "white" surrounding the circles and the stitches are too long in the stem.
![20220114_193604](https://user-images.githubusercontent.com/2872643/159014176-990b1833-7756-491f-90ba-6e0142d7c60f.jpg)

SVG source code (with different stitch direction for the stem) is here: http://tecfa.unige.ch/guides/embroid/emoji/AAA_EMOJIS/food_drink/food-vegetable/brocoli-twemoji-inkstitch.svg

One also could envision to allow using satin columns to define stitch patterns

**Comment by kaalleen** [comment]
@danielkschneider Thanks for the feature request ... I am just not sure if I fully understand it :)

* Compensation means restrictions for the stitch length (maximum stitch length even within patterns)?
* Directions of the stitches... is supposed to do ... what :D

At the moment fills will remove stitches and strokes will add stitches. I am not sure what the function of satin patterns will be?
If you mean it the other way around... patterns apply to all stitch types, fills, satins and strokes.

**Comment by danielkschneider** [comment]
Hi, sorry I posted this before doing some serious thinking, so you can close this request :) 

- The goal of compensation would have been be to get rid of "blank" showing due to pull effect of the long stitches. It maybe could have be done starting and ending the large satin stitch like in the attached picture, i.e. backtracking before and after the stitch, but I suspect the result to be ugly. 
- Stitch direction can not be done, since as you say this feature subtracts (or adds) points. I would mean defining a new fill algorithm or stitching a second pattern on top of holes left.
![2022-03-20 19_27_58-_pattern-fill-feature-request svg - Inkscape](https://user-images.githubusercontent.com/2872643/159177366-0a70dd53-c1f7-4e87-bf41-782c605dd29e.png)

As a solution, I will try to experiment with a denser underlay fill and maybe use a 45 deg. angle.
