### ISSUE TITLE
extra lines parameter in fill joints

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1607]
Hi,
I would be nice to be able to add 1 or more lines where the fill lines for a path join, e.g. have a joint_extra_lines parameter in auto fill parameters.

Rationale: Dense fills that are larger than a few cm's often have a "blank" where the fills join. For simple polygons one could define entry and exit points, but then the pull effect would strongly affect the exit area. So, IMHO, being able to say that I want 1-2 extra lines where the joint is could be a more elegant solution to the problem.

I suspect that this feature request already exists, since newbies often complain about "blanks", but I didn't find one.
- greetings ! Daniel

PS: Picture taken from a french FB posting (not mine)
![fill-bad-joins](https://user-images.githubusercontent.com/2872643/159030958-6aad2438-4e40-4127-860e-9a2c16cd8c25.jpg)

**Comment by kaalleen** [comment]
Yes, there is already a feature request over here: #1068 
... and it is not an easy one ;)

**Comment by danielkschneider** [comment]
oh sorry, didn't see this. Yes, I imagine coordinating in a way that fit the two ends together nicely could be a problem. But still, it would be a really nice feature to have, even if the extra line(s) somewhat show :)

**Comment by lexelby** [comment]
I'm gonna go ahead and close this one in favor of #1068
