### ISSUE TITLE
Cross stitch is possible now with Inkstitch

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#1612]
@lexelby explains somewhere how to "branch" our running stitches even if we have no autorun. I use this trick to create cross stitch.
![20220325_233801](https://user-images.githubusercontent.com/54963659/160277257-38ae73b5-7b7e-4d3d-9723-4c17fc8165dc.jpg)
I hope once somebody will give us this autorun for running stitch. Cross stitch will be much easier and may be later  we will have something special for cross stitch.
I explain my strange method here in french but with a lot of pictures.
https://lyogau.over-blog.com/2022/03/faire-du-point-de-croix-avec-inkstitch-2.1-partie-1.html
https://lyogau.over-blog.com/2022/03/faire-du-point-de-croix-avec-inkstitch-2.1-partie-2.html

**Comment by kaalleen** [comment]
Whoa, nice. Thank you for sharing!!

**Comment by lexelby** [comment]
@kaalleen This is done now, right?

**Comment by kaalleen** [comment]
We have autorun yes... I somehow would like a specialized extensions for cross stitch someday though. But this could be an other feature request or re-frame this one?

**Comment by lexelby** [comment]
Might as well make a new one to avoid confusion, but it can reference this one.

**Comment by kaalleen** [comment]
Done
