### ISSUE TITLE
Reorder - indexerror (list index out of range)

### ISSUE THREAD

**Issue by latutioti** [inkstitch/inkstitch#1621]
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/reorder.py", line 19, in effect
IndexError: list index out of range

**Comment by kaalleen** [comment]
Thank you for the error report. This bug surely needs to be fixed. We really appreciate, that you went the extra step to inform us about your issue.

The reorder function serves to reorder path objects into the order in which you've selected them. This means you will need to select some path items before running the function. Could you describe your steps before running reorder?

**Comment by latutioti** [comment]
I selected the object went to the extension and selected the preview the browser opens but the preview does not generate. Then I tried to do a save as and that is when the message showed.

Get BlueMail for Android<https://bluemail.me>
On Apr 9, 2022, at 9:22 AM, Kaalleen ***@***.******@***.***>> wrote:

Thank you for the error report. This bug surely needs to be fixed. We really appreciate, that you went the extra step to inform us about your issue.

The reorder function serves to reorder path objects into the order in which you've selected them. This means you will need to select some path items before running the function. Could you describe your steps before running reorder?

**Comment by kaalleen** [comment]
Interesting. The error message looks as if you've called the reorder extension.
If you like, you can send us your file for inspection.
We have a mail address in case you don't want to post it here: send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Without more information we won't be able to trace down the issue. Therefore I'll close it.
Please open a new issue, if the error message shows up again. Make sure to include an SVG file.
