### ISSUE TITLE
Inkstitch not recognizing simple lines exported from Illustrator as SVG File

### ISSUE THREAD

**Issue by saturdaysage** [inkstitch/inkstitch#1623]
Inkstitch is not able to recognized any objects that are simple lines (two connected points) regardless of stroke weight or if it is dashed or not.

The SVG was created in Adobe Illustrator/AI with Pen Tool. If i recreate these lines in Inkscape it will Stitch correctly, but the art i am working with was created in AI.

<img width="749" alt="Screen Shot 2022-04-13 at 11 33 41 AM" src="https://user-images.githubusercontent.com/60530552/163228163-aee527e0-64fb-4e15-bffb-5dde3385eb74.png">
<img width="486" alt="Screen Shot 2022-04-13 at 11 31 22 AM" src="https://user-images.githubusercontent.com/60530552/163228167-894c2b6a-69cf-4311-a01c-afa7959d41e2.png">

I have attached a .ZIP with the AI file and SVG export from AI.

Thanks for any help

[Test-Inkscape-LineIssue.zip](https://github.com/inkstitch/inkstitch/files/8483129/Test-Inkscape-LineIssue.zip)

**Comment by saturdaysage** [comment]
So i found out that if I add one extra anchor point in illustrator to each of these lines then inkstitch recognized the lines as straight stitches, but it even makes the the strokes without dashed lines into straight stitches as well. 

Also it only recognized 5 out of the 7 lines when adding this extra anchor to each line.

**Comment by tyrosinase** [comment]
Documents that use Lines (versus Paths) are going to need quite a bit of massaging to turn them into something stitchable. `Object to Path` (Shift-Ctrl-C or equivalent) will turn them into paths, but then Ink/Stitch will just treat them as zigzags (anything not dotted) or running stitch (anything dotted).

If you want to preserve the specific dashes in the .ai file, you're going to need to to jump through some hoops to turn them into individual paths - probably on the Illustrator end just to be sure you're interpreting the dashes exactly as intended.

**Comment by saturdaysage** [comment]
Thank you, "Object to Path" did make my simple lines usable once in Inkscape. 

I'm curious why does Inkscape not recognize a line with two points, but it will recognize a line with 3 points? (see screenshot)

Also, it recognizes "dotted" or "solid" strokes when these shapes are more complex (i.e. the 'S' + the circle). Is it because these "lines/shapes" are more complex in Illustrator and it is translating it as a "path" rather than a "line"? If that is true, it still doesn't make sense why the more complex line (3 anchor points, zig zag shape) is still not registering the stroke and always making it a "running stitch."

Thanks for your patience!

design:
<img width="706" alt="Screen Shot 2022-04-13 at 12 11 23 PM" src="https://user-images.githubusercontent.com/60530552/163234626-df97d6d8-e5ae-4b19-8e26-be3be6b2fbec.png">

preview:
<img width="833" alt="Screen Shot 2022-04-13 at 12 11 57 PM" src="https://user-images.githubusercontent.com/60530552/163234639-4f17a57f-b822-4924-8a0a-0809df43b7cd.png">
