### ISSUE TITLE
Allow non parallel fill stitch to simulate perspective

### ISSUE THREAD

**Issue by chatelao** [inkstitch/inkstitch#1624]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2461532/163247985-f13f43c3-c751-4a7b-a8dc-74224df920ab.png">

It would help to simulate a perspective to add non-parallel fill stiches in a parallelogramm.

**Comment by lexelby** [comment]
Interesting.  Is this just a special case of your other feature request for interpolation?

**Comment by chatelao** [comment]
Extrapolation would solve the Problem too.

It was just my first idea to fill a non square area.

We could close this issue with reference to the Interpolation issue.

**Comment by chatelao** [comment]
Closed in favor to #1625
