### ISSUE TITLE
Dual color gradients

### ISSUE THREAD

**Issue by chatelao** [inkstitch/inkstitch#1626]
Allow color gradient to be converted to dual color stitching:

https://www.digitizingmadeeasy.com/embroidery-color-blending/
https://www.youtube.com/watch?v=PG4f_cNRIGI

**Comment by lexelby** [comment]
So, you create an object with a gradient fill, we replace it with two fill objects that simulate the gradient with thread?

**Comment by chatelao** [comment]
Yes, it would be nice, e.g. to get a sunset with a interwoven blend of red and Orange.

**Comment by kaalleen** [comment]
This is implemented now. Could be improved though ... but we have an other issue for that already.
