### ISSUE TITLE
Pattern Making Tutorial

### ISSUE THREAD

**Issue by yuntianyecornell** [inkstitch/inkstitch#1634]
Hi ink stitch developing team,

I am a student in Cornell Tech and I am working on a project using inkstitch. I wonder if it is possible to provide the document of creating patterns in this package? It would be great if you can share some document or tell me the key class/function in creating a pattern!

Thank you so much for your help!

**Comment by kaalleen** [comment]
This is being reworked at the moment, so this link leads to an active development branch, not the main repository: https://github.com/inkstitch/inkstitch/blob/feature_guided_fill/lib/patterns.py

Patterns in Ink/Stitch work in that way, that they take in existing stitch objects and remove stitches if it finds a fill with a pattern marker and add stitches where there is a stroke with a pattern maker.

Hope it helps?

**Comment by kaalleen** [comment]
No response. So I believe the answer was sufficient. Closing.
