### ISSUE TITLE
Feature - Satin from line - offset Angle, e.g. for eyebrows

### ISSUE THREAD

**Issue by chatelao** [inkstitch/inkstitch#1637]
IS
- Satin stiches are generated (very well) with 90° to the guiding line.

COULD
- Would some offset angle, e.g +20°, -30° etc. be.possible?

Classic example: Eyebrows

**Comment by tyrosinase** [comment]
Do you mean something different from what satin rungs already do?

**Comment by kaalleen** [comment]
No further response. I'm not seeing how rungs cannot do what is asked for. Therefore I'll close the issue. Please open a new issue if this doesn't fulfill your request.
