### ISSUE TITLE
cutwork

### ISSUE THREAD

**Issue by linaabate** [inkstitch/inkstitch#1640]
thanks for what you do, I ask you how can I install this version with cutwok in windows 10 and where do I find the sw? I would like to try to generate an example for bernina thanks

**Comment by chatelao** [comment]
Is this duplicate to #1639 ?

**Comment by kaalleen** [comment]
Cutwork is not a feature of the official release yet, but we have a development version where you can test it: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

There is also a description on our website: https://inkstitch.org/docs/cutwork/

I would really like to have a feedback on this feature, because I don't have a cutwork set myself and never really looked at a file for cutwork embroidery. So there is may be a lot of trial and error in the process until you get it right. So, if you collect some experience in that matter, it would be great to hear about it, so we can adapt our cutwork feature accordingly if necessary.

**Comment by linaabate** [comment]
thanks Kaleen, in the weeks we intend to try to make a test, and test with bernina's cutwork tool, if you need an original example file of bernina's cutwork ask me I will send you the file, thanks and see you soon

**Comment by kaalleen** [comment]
That'd be so great, thank you. Looking forward to hear your report :)

I just found this website here https://www.bernina.com/en-US/Learn-Create-US/Projects/Free-Downloads/More-Freebies/CutWork-Freebies
They actually provide free cutwork files, interesting.

**Comment by linaabate** [comment]
I found the instructions of Bernina's SW to make a Cutwork file, but I am Italian, you can still translate with Google, here is the sequence of embroidery design, I found interesting to understand the logic of the process. On my car I downloaded a CUTwork file in Exp format,. I loaded this in Inkstitch and analyzed the path and from this I understood how I have to proceed. I hope it can be useful to you I send you the files. (sorry but I help with Gugool to write this message, I hope you understand)
[Cutwork.zip](https://github.com/inkstitch/inkstitch/files/8565649/Cutwork.zip)
[ExpDesign4.zip](https://github.com/inkstitch/inkstitch/files/8565697/ExpDesign4.zip)

**Comment by SergheiSP** [comment]
Видео-черновик. Если имеются вопросы, спрашивайте
https://www.inkstitch.ru/data/cutwork/cutwork.html

**Comment by kaalleen** [comment]
Interesting, thank you both.

@linaabate It's not a problem to understand what you are writing ;) I'll have a look at the files as soon as I can!

**Comment by kaalleen** [comment]
I finally had a chance to test a Bernina cutwork tool. In #1988 I will add the cutwork needle information to the .inf file, so that the machine will actually know, that we are using a cutwork tool. Thanks again for your help @linaabate

**Comment by linaabate** [comment]
Thanks, if I can try I will send you the result, Thanks again

Da: Kaalleen ***@***.***> 
Inviato: venerdì 30 dicembre 2022 20:10
A: inkstitch/inkstitch ***@***.***>
Cc: linaabate ***@***.***>; Mention ***@***.***>
Oggetto: Re: [inkstitch/inkstitch] cutwork (Issue #1640)

 

I finally had a chance to test a Bernina cutwork tool. In #1988 <https://github.com/inkstitch/inkstitch/pull/1988>  I will add the cutwork needle information to the .inf file, so that the machine will actually know, that we are using a cutwork tool. Thanks again for your help @linaabate <https://github.com/linaabate>

**Comment by kaalleen** [comment]
Here you can find the developer release: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-cutwork-update
