### ISSUE TITLE
Plugin Unit Tests

### ISSUE THREAD

**Issue by chatelao** [inkstitch/inkstitch#1642]
Is there a place in the repo, I can find Unit / Integration tests of the plugin, to understand the codeflow?

Is it possible, to execute the plugin outside Inkscape, e.g. to profile or to write a command line version?

**Comment by lexelby** [comment]
Alas, no, we don't have unit or integration tests.  Sorry!  The best "entry points" to start with are the extension classes in lib/extensions/*.py.  Those correspond to menu items in the Extensions menu.

Yes, it's quite easy to run Ink/Stitch from the command line.  If you're running from a manual/development installation (from a git clone), you can run inkstitch.py with arguments and an SVG file.  It will run the extension and output a modified SVG file (except the Output extension which will output a raw binary embroidery design file!).  

You can see what command line arguments to use by looking in the INX files in a downloaded version of Ink/Stitch, or the templates/*.xml files in a git clone.  If you've never worked on an Inkscape extension, it might help to learn about the extension interface from their docs.

**Comment by chatelao** [comment]
Sounds great, I will have a look at it.

**Comment by chatelao** [comment]
@lexelby - could you just add one example / readme how to run one function from the command-line, so I could add other commands and test files mayself?

**Comment by chatelao** [comment]
@kaalleen do you maybe have a 1-2 line command to run Inkstitch outside Inkscape for testing?

**Comment by lexelby** [comment]
Sorry, this is still on my to do list, hoping to get this to you soon.

**Comment by lexelby** [comment]
Okay, here's an example of running the Stitch Plan Preview extension from the command-line in a manual installation.  I would recommend setting up a virtualenv or using pyenv.  Then do `pip install -r requirements.txt` to install all of Ink/Stitch's required Python modules.

Then you can do this:

```
PYTHONPATH=/usr/share/inkscape/extensions python3 inkstitch.py --extension=stitch_plan_preview --move-to-side=false --layer-visibility=1 --needle-points=true ~/path/to/your/svg
```

The results will be printed to standard output as a new SVG.

This example is for Linux.  For Windows or MacOS, adjust the PYTHONPATH to wherever Inkscape installs the shared extension modules (inkex).

**Comment by chatelao** [comment]
Thank you so much

**Comment by kaalleen** [comment]
Unit tests do not really exist yet, only for clones in the test folder. We hope to integrate more in future.
How to call Ink/Stitch from command line is documented on the website by now.
