### ISSUE TITLE
The color of the icons in the panel does not match the color of the objects.

### ISSUE THREAD

**Issue by SergheiSP** [inkstitch/inkstitch#1643]
If the icons displayed the color of objects, then productivity by determining the embroidery order would increase many times over
![Object](https://user-images.githubusercontent.com/98824663/165722539-cfa9b543-42c5-4845-b646-a43e821faf45.jpg)
.

**Comment by kaalleen** [comment]
Oh, this isn't meant to be the color of the objects, but the color of the small outline around the objects, when you have selected them with the node tool. You can update the color by clicking on it.

**Comment by SergheiSP** [comment]
I know that this outline color and the default color suits the outline color. Changing it doesn't make sense. But if it were the color of the object, then the objects could be combined by color or guided when determining the order of embroidery. Written, this is only a wish and a hint on how to make the work of creating a design much more efficient.

**Comment by lexelby** [comment]
I only wish we could do such things.  Unfortunately, that's part of Inkscape itself, and we can't change it.  Sorry!

**Comment by kaalleen** [comment]
Changing it makes sense, when you have an object with the exact same color as the outline. Then you may not be able to see the actual stitch path or path direction. This means you really don't want this color to match the object color at all. But I understand that you want an other, a new visual feature in the object panel which makes it easier to find the objects.

As Lex said, this is part of Inkscape and we cannot change that ourselves. If you want to, you can talk to the Inkscape people about your feature request over here: https://gitlab.com/inkscape/inbox/-/issues or here https://inkscape.org/forums/

**Comment by SergheiSP** [comment]
I'm afraid that my knowledge of languages will not be able to convey wishes to the Inkscape developer
