### ISSUE TITLE
Length of running stitch not exported.

### ISSUE THREAD

**Issue by Joeri213** [inkstitch/inkstitch#1645]
I have imported a sketch from fusion360 to inkstitch consisting of around 30 paths/lines. When I export it my machine (Pfaff creative 5.5) does obey to the order of the lines and the cutting commands which I gave it, but it chooses its own stitch length and doesn't use the one I select in my params. I've tried multiple lengths from 3 to 5mm, and tried multiple export formats which my machine reads. 
When I run a simulation it tells me it needs 1200 stitches with the 5mm stitch length, but my machine ignores it and gives it 2800 stitches. No matter what settings I use, I can't get it below 2800 stitches. 

Is this a software issue or could this be an issue specific to my machine?

**Comment by Joeri213** [comment]
It was a machine issue, solved it

**Comment by lexelby** [comment]
I'm very interested to hear what the issue was in more detail, if you don't mind sharing.  That sounds so weird!

**Comment by Joeri213** [comment]
When I thought I was loading my new file from the USB, I was actually saving/replacing my new file with the one already loaded into my machine. I hope this incredible noob mistake might help  others. 

flies away in shame.

**Comment by lexelby** [comment]
No shame allowed here, we're all learning.  I've done that exact thing so many times!
