### ISSUE TITLE
Lettering 

### ISSUE THREAD

**Issue by claudinepeyrat06** [inkstitch/inkstitch#1650]
I am part of the French team working on some of the Ink/Stitch embroidery fonts (not the lettering tool, the font files )

If you have issues using  the built in Ink/Stitch fonts , I would love to know about  it so that we can try to fix the problem. 

And thank you @tyrosinase  for mentioning some on your blog,  and let me know if you are aware of more.

**Comment by tyrosinase** [comment]
You're welcome, and thank *you*.

(And it was also reported #1583, not just buried in the blog -- I'm not a monster. 😆)

**Comment by claudinepeyrat06** [comment]
But I did find the problem you had with getting the glyph list  from sacramarif on your blog, and could fix the mix  up in the xml tags causing the problem.... 
I'm adding the glyph lists in the documentation, your job will be easier next time....
I do like your blog. Thanks again.

**Comment by tyrosinase** [comment]
Ohhhhh, that. I assumed that was something in my quick-and-dirty Perl dumper, and then never got around to tracking it down, so I didn't report it.
