### ISSUE TITLE
tangential fill error

### ISSUE THREAD

**Issue by viceversa3** [inkstitch/inkstitch#1653]
Hello,
I tried to fill a path with tangential fill, but got an error code. I think it's because there's a hole ni my shape
Here the message: "
path288: erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: feature_guided_fill (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 512, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 591, in do_tangential_fill
  File "lib\stitches\tangential_fill.py", line 503, in single_spiral
  File "lib\stitches\tangential_fill.py", line 513, in _spiral_fill
ValueError: Shape cannot be filled with single or double spiral!"
![tangential_fill_error](https://user-images.githubusercontent.com/105361070/167842073-9173975f-c03c-4673-99f8-9315d1183b92.svg)

And here the bad shape in an svg

Thanks for all the improvements made within Inkstitch :)

**Comment by viceversa3** [comment]
I'm sorry but Github is a bit labyrinthine for me, could please point me to the last version ?
Thanks a lot :)

**Comment by tyrosinase** [comment]
Are we supposed to be able to just unpack and run it, or is there something more involved? Because I'm getting:

 ```
./inkstitch 
Traceback (most recent call last):
  File "inkstitch.py", line 56, in <module>
AttributeError: 'NoneType' object has no attribute 'title'
[1019046] Failed to execute script 'inkstitch' due to unhandled exception!

```

when I try the Linux version (tar.gz archive if it matters).

**Comment by tyrosinase** [comment]
(My current install is built from source, FWIW, and in a different location.)

**Comment by viceversa3** [comment]
Thanks a lot, it worked as you can see (windows 11 and Inkscape 1.2 beta version : by the way Inkstitch can' t be attributed keyboard shortcuts with that version of Inkscape : it doesn't show in the list of menus to add shortcuts)

from left to right : autofill, guided fil and contour fill :) in fact, I'll embroider this test to decide, but as it's a small area, I think I'll stick to the autofill (but let's test it first before deciding)
![image](https://user-images.githubusercontent.com/105361070/168131089-8ce2a586-fce1-41e8-8471-1bc626e124d3.png)

**Comment by tyrosinase** [comment]
(Oh the answer to my question is "because you're trying to run inkstitch and not run an inkstitch installer, sheesh" or really, the root cause problem: failure to install adequate caffeine.)

**Comment by kaalleen** [comment]
Great, thank you for your feedback!
