### ISSUE TITLE
Copying Stop and Start Commands

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#1655]
Hi

I've always used Duplicate to duplicate my objects.
And I've always lost the stems of the Start and Stop Commands, doing so.
I even went as far as editing the svg file by hand because I need these Start and Stop Commands.
So this morning just before creating this issue I checked if someone else had similar problems
And lo! #1628 catches my eye.

Whereas @tyrosinase looses the Trim Command's stem Copy/Pasting, I loose the Start & Stop Command's stems Duplicating.

So I tried Copy/Pasting, and I retained my stems!
I adapted tyrosinase's Two Hearts to illustrate.
![tyrosinase bis](https://user-images.githubusercontent.com/64724381/168209312-70c937ed-c1eb-484c-8fb2-f6aa7da24b7b.svg)
Copy/Paste works fine for me (Inkscape 1.1, Inkstitch 2.1.2), Duplicate doesn't.

So I can use Copy/Paste as a work around to duplicate.
But where it doesn't work is in Cloning objects.
Cloning (grouped) objects with Start & Stop Commands loose their stems

**Comment by kaalleen** [comment]
Thank you for your report. I am afraid, this is not in our hands and something to ask the Inkscape team to fix for us. Although we are using the connector-tools definitely in a very unexpected way.

If you like to bring this forward you can talk to the Inkscape team here: https://gitlab.com/inkscape/inbox/-/issues

**Comment by njlvr** [comment]
The connector-tool is an Inscape item? I am surprised but what do I know.

I will have a look at their issues. I'll have to study the very unexpected way Inkstitch uses it if I want to convince Inkscape to change something.

Thanks

**Comment by kaalleen** [comment]
Closing as this is not an Ink/Stitch issue (but Inkscape).
