### ISSUE TITLE
Error: Dependency is not satisfiable: Inkscape (>=1.0.0) when Inkscape 1.1 is installed

### ISSUE THREAD

**Issue by amw2761** [inkstitch/inkstitch#1656]
I am new to Inkscape and Inkstitch. Installation of Inkstitch failed with the above error even thought Inkscape 1.1 is installed on my computer. I am running Linux Mint 20.3 "Una"/Cinnamon. Any advice on how to resolve this? Thanks.

**Comment by lexelby** [comment]
Do you have Inkscape installed as a snap?  I'm not even sure if Mint has snaps... Anyway, Ink/Stitch won't work with a snap version of Inkscspe.

**Comment by mmcclain03** [comment]
Hi amw2761 I"m experiencing same error & installed from synaptic which gave me older version (0.92.5) when dependency error shows it requires new version. 
The most recent version here if you want to give it another try :
 https://github.com/inkstitch/inkstitch/releases/tag/v2.1.2
hoping it will work for us both

**Comment by mmcclain03** [comment]
unfortunately I got same error after updating to newer version...

**Comment by amw2761** [comment]
I used the Linux Mint software manager to uninstall Inkscape 0.92.5 then install Inkscape 1.2 but v. 0.92.5 was apparently still there. Inkstitch found it during installation attempts. It was necessary to update 0.92.5 to 1.2 through commands in the terminal. Inkstitch then installed. Thanks for the feedback.

**Comment by mmcclain03** [comment]
np & thanks for the update & hope along with it. I ended up running deborphan and inkscape was right there along with a whole lot of misc ones so i'm ready to try again...
