### ISSUE TITLE
No Shortcut keys possible in Inkscape 1.2

### ISSUE THREAD

**Issue by Helisinus** [inkstitch/inkstitch#1664]
I updated my Inkscape from version 1.1.2 to version 1.2. Unfortunately I can't create shortcut keys now. In V1.1.2, for example, I had defined SHIFT+CTRL+P to call ink stitch parameters. Unfortunately I can no longer do this. Is there any solution to this?

**Comment by danielkschneider** [comment]
Location in English: 
![inkscape12-inkstitch-shortcuts](https://user-images.githubusercontent.com/2872643/171207466-b4a41d0f-6713-48ed-8d5e-612e4a9bc450.png)

if you want an example file: http://tecfa.unige.ch/guides/embroid/inkstitch/shortcuts/inkscape-1-2/  You can either copy the file in the right directory (see under system) or import.
