### ISSUE TITLE
text 

### ISSUE THREAD

**Issue by CaptainNoAction** [inkstitch/inkstitch#1669]
new to this. i tried to troubleshoot and got the error. any ideas what i have done wrong? thanks
![ts](https://user-images.githubusercontent.com/24485278/169680692-514cb87e-bc7f-48c4-b0cd-5af6b872ac5c.png)

**Comment by kaalleen** [comment]
Hit `Ctrl + Shift + C` and run `Extensions > Ink/Stitch > Fill Tools > Break apart objects ...`

But this wouldn't make nice embroidery lettering. If you want to save yourself some work, follow the error description and see, if you find a font in the Ink/Stitch font library (`Extensions > Ink/Stitch > Lettering`) that suits your needs. Those fonts ready are to use. The next Ink/Stitch version will come with even more beautiful embroidery fonts.

**Comment by CaptainNoAction** [comment]
Thank you. ctrl shift c worked. I looked at the extensions lettering but it does not have this font. I am not sure if it will work but will give it a go. Appreciate the help.
