### ISSUE TITLE
Consistency in font descriptions

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1670]
For consistency of font descriptions we could add some more variables in the json file to describe a font.

Possible values are
* purpose
* original size mm
* size range
* characters
* free text description

**Comment by tyrosinase** [comment]
Also feel free to change my descriptions; they're just "A $FONTCREATOR jawn" which only makes sense to Philadelphians.

**Comment by kaalleen** [comment]
We would love to see your beautiful fonts being included in Ink/Stitch. But sadly due to license concerns your fonts are not included into Ink/Stitch just yet. We know, that you have reasonable arguments that this should be possible and not a problem, but we would feel better, if the font authors personally agree to the modifications.

**Comment by tyrosinase** [comment]
Yeah, I haven't asked them (nor am likely to get a chance to by release time), but anybody else is welcome to track them down and do that.

**Comment by claudinepeyrat06** [comment]
Splitting the information would really help for more consistent description of  fonts.  And  also make clear  what goes in the font description and what goes to the font library description pages.

Another "concern" is the growing number of fonts,  would it be possible with variables in the json  to filter the fonts in the  lettering window  ? like showing only script font, or running stitch only, or   font with some size condition?

 I would also like to have easier ways to compare the  fonts, we do miss an easy way to compare font sizes.
