### ISSUE TITLE
corduroy look with guided fill

### ISSUE THREAD

**Issue by viceversa3** [inkstitch/inkstitch#1672]
Hello, I have tried to use the guided fill feature. This is a fairy's legs. My problem is that when you run a preview it's hideous : all the stitches holes are aligned and it's give's my shape a "corduroy" look, as if  the "stagger that many rows before repeat" had been set at 0. Unfortunatelly, I can't change that param.

Am I missing something ?

Thanks a lot for all your efforts to make an ever better Inkstitch (I'm in love with it)
![jambe_fee](https://user-images.githubusercontent.com/105361070/170318344-d6a3bdee-90a1-4410-bdbc-bce4d97e2e7c.svg)
.

**Comment by lexelby** [comment]
@AndyLV Well, I'm second-guessing my choice now. ;)  cc @kaalleen 

@viceversa3 Yes, the stagger setting doesn't work with guided fill.  Figuring out where to place the stitches is a pretty difficult problem, and we haven't yet figured out how to do it well without taking a minute or longer to run.  This is something we hope to work on in a future version.

**Comment by viceversa3** [comment]
Thanks a lot for answering me :) I'll wait for it to work. There will more designs to design so sure there will be a time where I'll use it :)

**Comment by lexelby** [comment]
Closed by the guided fill stagger pull request
