### ISSUE TITLE
Inkstitch 2.1.2 with Inkscape 1.2 on macOS Monterey- Params does nothing 

### ISSUE THREAD

**Issue by gmarzloff** [inkstitch/inkstitch#1673]
The full Extensions > Inkscape menu is visible and clickable, but nothing happens when I click Params after selecting a filled object.

Inkstitch 2.1.2 with Inkscape 1.2 (dc2aeda, 2022-05-15)  on macOS Monterey- Params does nothing

**Comment by kaalleen** [comment]
Uh, sorry to hear you are running into this. I am not sure why this would happen. Is this specific to the params dialog or are there troubles with other Ink/Stitch functions as well?

**Comment by gmarzloff** [comment]
Since posting this issue I also replaced my computer and don't have this issue anymore.
