### ISSUE TITLE
Positive Feedback

### ISSUE THREAD

**Issue by owendelong** [inkstitch/inkstitch#1674]
Just wanted to take a moment to thank you for this project and all the excellent work by the team behind it.

I'm relatively new to Ink/Stitch, having only used it for about a month and learning both InkScape and Ink/Stitch at the same time.

Sure, there are some warts here and there, but overall it has worked very well for me so far, and in many cases better than packages I've paid more than $2,000 for. I look forward to it's continued development and improvement. It has become my go-to digitizer for both my personal Brother Luminaire and for the 15 needle Barudan at my local maker space. (It was so wonderful discovering that this program supported the Barudan which is not widely supported in the commercial packages, especially on Mac).

My first major project with Ink Stitch was the T-Shirts for the 2022 Southern California Linux Expo Technical Team (which I lead).

It's so cool to be able to have open source shirts for our open source conference. The original artwork was done as a PNG in The Gimp. I converted it to Vector and optimized it for embroidery using Ink Scape and then digitized it for stitching using Ink/Stitch.
![T-Shirt 2022 (19x)](https://user-images.githubusercontent.com/1434446/170546525-53b167c7-518e-4b6a-a824-2cdc97079f72.svg)

I've attached the digitized SVG and you are welcome to use it as an example, tutorial, etc. if you like.

The Shirts turned out great. If any of you are at SCaLE this year (July 28-31, Hilton LAX), please make a point of stopping by the NOC and introducing yourselves to me.

**Comment by owendelong** [comment]
Here's a photo of one of the shirts... Stitching time about 1h10m on the 15-needle Barudan.
I'm pleased with the results.

![05C4BD4F-217F-4561-A933-26642E70D235_1_102_o](https://user-images.githubusercontent.com/1434446/170547440-d6f507a9-b858-4161-84b3-afaeb08c9932.jpeg)

**Comment by lexelby** [comment]
Thank you, it's really great to hear your experience. :D  I'm jealous of your Barudan, which makerspace?

Do you have any interest in letting us include your SVG in the repo in our examples directory?

**Comment by owendelong** [comment]
@lexelby Sorry for the delayed response... Somehow I missed the notification and I hadn't circled back here until I happened on it by accident recently. It's Maker Nexus 1330 Orleans Dr., Sunnyvale, CA, US.

**Comment by owendelong** [comment]
You are free to include the SVG in the samples directlory, though it is already in the socallinuxexpo/scale-network repository under graphics/19x T-Shirt Back.svg. You are welcome to copy it from there.

**Comment by lexelby** [comment]
Oh, I'd totally forgotten about this! Thank you :D

**Comment by owendelong** [comment]
Any time.
