### ISSUE TITLE
Inconsistent running stitch length on pre-release

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1676]
I was concerned by the strange sounds my machine was making, like the motor wasn't running at a consistent speed, until I realized it was that the *stitches* aren't a consistent length. Params are set to 2.5mm, and that's a little complicated by the fact that it's also repeat-2 (so there's two runs of stitching there), but it definitely slows down and speeds up based on curve tightness.

![IMG_1722](https://user-images.githubusercontent.com/9473609/170886377-f55bab19-1bb0-4ebf-a4ca-09e003a65c01.jpeg)

I am 90% sure I'm running this release, https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test
but I'm about to go give https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-guided_ripple
a shot.

**Comment by kaalleen** [comment]
The other release won't have an effect on the running stitches. Although it offers new options to the ripple stitches.

@lexelby  any ideas?

**Comment by tyrosinase** [comment]
Yup, I noticed. In the middle of stitching out dragons so I didn't get to play with the ripples but I did turn ripple on on one of the dragon outlines just to see what it did and went "ooooooh that's gonna be fun when I get time" so there's that.

**Comment by lexelby** [comment]
Ah, that's the new running stitch algorithm.  It would be in the guided ripple branch at least, and maybe the other one too.

The old algorithm would go along the path, plotting out stitches at the length you specify.  It would also add a stitch any time it found a sharp corner.  The thing is, it was actually pretty terrible at detecting the corners, and it could be easily fooled into rounding off a corner.

The new one is way better at that.  It starts by figuring out the bare minimum set of points in the line that it needs to avoid deviating far from the shape you gave it by more than a certain distance (currently hardcoded).  Then it fills in the remaining space between each of those points with evenly spaced stitches that are at _most_ the length you specify.  That's why you're seeing slightly shorter stitches.

Like it? Hate it?  Personally, I really like that it doesn't round off corners.

**Comment by tyrosinase** [comment]
Really mixed feelings, yeah. Didn't like the corner rounding (especially since I tend to make all my structural stitches 2-repeats and the algo doesn't pick the same place to cut corners), but the new way is really cranking up the stitch count on my detailed little dragons.

But also mostly I learned I am really sensitive to the sounds it makes while stitching out and the slowdowns trigger all my "SOMETHING IS WRONG WITH THE MACHINE" instincts. 😆

**Comment by kaalleen** [comment]
Maybe this is really depending on what you are trying to do. Which may raise the question if that should be an option in running stitch (more options, aiai). Asking the user for their main focus (stitch length or shape).

**Comment by tyrosinase** [comment]
Hmm, it's still making top-stitching weird. Not even sure what's going on with this one; that's a default 1.5mm stitch (because I cleared my params accidentally) but after it comes around the bend there it makes an extra-long hop which I think was actually a skipped stitch right before it. (Does the MC400E deliberately skip too-small stitches?)

![image](https://user-images.githubusercontent.com/9473609/177013975-59837326-970e-4608-80c7-2e5f3a9768a7.png)
![image](https://user-images.githubusercontent.com/9473609/177013987-1686e7d3-53a8-4621-91c5-83b4a17fcee0.png)

Naturally when I went back to that shape and cleared the params again to show you it displays just fine, which leads me to think maybe it's a skipped stitch. It's the square snap tabs on https://silverseams.com/embroidery-patterns/snap-tab-blanks/ though, FWIW. Shape shouldn't have changed, just params.

**Comment by lexelby** [comment]
Wow, that's weird.  The short stitches at the corner are on purpose; they have to be that short to satisfy the tolerance you set (or the default tolerance).  


I don't know about that skipped stitch though.  Can you run the stitch plan extension with "show needle points" enabled and paste a screenshot here?  I'd like to see what Ink/Stitch thinks.

I do think the MC400E has an option to ignore short stitches, but I'm not sure.  If it's there, is buried in one of the settings pages.

**Comment by tyrosinase** [comment]
Yeah, the short stitches didn't surprise me (as soon as I realized it was doing 1.5mm instead of 2.5mm, meaning it had reverted to defaults), but the long jump did.

And naturally I adjusted the params for what I needed at the moment, thinking just resetting them to default would make the problem show up again for troubleshooting, and... it didn't. It looks perfectly fine: some short (but not excessively short) stitches around the curve, then it immediately stretches out to the 1.5mm stitches on the straightaway, no giant leap between the two.

I didn't change the shape in between so I am not sure what it was doing that caused that hop, or why it stopped. It's the same on all five of the tabs on that run, I think. Wacky!

I guess I should run it on the machine, to see if there's a physical skipped stitch despite what the file says. It doesn't look *quite* like a double-length stitch but maybe it is.

**Comment by lexelby** [comment]
You know, I think that may well be a skipped stitch.  I see some bobbin thread in the green part.  Maybe your top tension is too high?  I've seen that cause the rotary hook to fail to catch the top thread occasionally.

The smoking gun for that would be a needle hole right in the middle of that long stitch.  Maybe you can see the hole if you pull the white thread aside?

**Comment by tyrosinase** [comment]
Not in squishy white JoAnn marine vinyl, nope, it seals right back up. (I hate it.) And yeah, the green leaves were the first things stitched on that, on a new bobbin, and I pulled and re-threaded everything and didn't see any more in all the other colors (including the green stem).

Now, could be an ongoing tension problem and I just never noticed skipped stitches before, but it was odd that they were all consistently skipping *that* stitch at that point, which made it jump out at me.

**Comment by lexelby** [comment]
Hmmm, I guess we have no way of knowing, unless you still have the PES file that made that stitchout.  

As to why it would always skip in that one spot, I was thinking maybe something to do with that sequence of stitches happened to make it more likely to skip?  I admit my theory is looking a little ragged at this point ;)

**Comment by tyrosinase** [comment]
The more I look at it, the more I'm convinced that's a skipped stitch.

If I try to recreate it I get this, which doesn't quite match up:

![image](https://user-images.githubusercontent.com/9473609/177439222-5173d3b9-98a7-41f0-833a-cc2188e50ed9.png)
![image](https://user-images.githubusercontent.com/9473609/177439322-e6e3a161-c126-46a0-9b6b-2a21c80b27ec.png)

And I begin to wonder: I was figuring it was a design problem because it happened on all of the fobs buuuuuut try this for a less-ragged theory about the sequence of stitches being the problem: what if it was getting the *hoop* hung up on something at that Y location on all of them? Critter's got a piece of vinyl on the back of the hoop for that step, after all. Just a little drag to cause that extra-short stitch, and then it jerks forward to the correct place and gets an extra-long. That would account for not being able to "recreate" that stitch file even though I didn't change the shape, only the stitch params.

More I think about it, the more sure I am that's what happened.

**Comment by tyrosinase** [comment]
(also look at that awful white vinyl: the pull compensation is *fine* on that center if I do it on ivory. Gotta be something chemical about true white marine vinyl that means nobody can make one that isn't spongy mush.)

**Comment by lexelby** [comment]
Ooh, I definitely like that theory

**Comment by tyrosinase** [comment]
I'm going to be an ungrateful wretch here and just say it: I'm rolling back to a version that doesn't have the stitch-tolerance option. It just keeps biting me when I pull up an old file and forget to change the stitch tolerance to 2mm before re-generating the stitch file, and I end up chewing up yet another project with stitches far too tiny for the ground.

I had gotten to where I rarely forgot, but then I tried to use NickAinley and its pushing-the-envelope 1mm bean stitch became a <0.7mm bean. The Janome (unlike the Brother) will reject a file if I have managed to turn a dashed line solid and produce an 0.265mm satin line, but it's like "sure, whatever you say boss" with that tiny bean. 😆

**Comment by george-steel** [comment]
We just got a really clear [example](https://www.facebook.com/groups/inkstitch/posts/6155652977802317/) of this happening in the facebook group. There's definitely an inkstitch bug.

![321437893_555390946484791_3840396733255850953_n](https://user-images.githubusercontent.com/633295/209481508-ab40612f-7793-43b2-bbeb-ddf5de7ac45a.jpg)

I looked into it and stitch-tolerance is currently implemented by first doing a running-stitch with unlimited length and the specified tolerance, then subdividing the too-long stitches, producing very short stitches when the tolerance would make stitches just over the set length.

I'll work on changing the implementation to a single pass which produces stitches one at a time when either the max length or the tolerance is hit.

**Comment by george-steel** [comment]
> The old algorithm would go along the path, plotting out stitches at the length you specify. It would also add a stitch any time it found a sharp corner. The thing is, it was actually pretty terrible at detecting the corners, and it could be easily fooled into rounding off a corner.
> 
> The new one is way better at that. It starts by figuring out the bare minimum set of points in the line that it needs to avoid deviating far from the shape you gave it by more than a certain distance (currently hardcoded). Then it fills in the remaining space between each of those points with evenly spaced stitches that are at _most_ the length you specify. That's why you're seeing slightly shorter stitches.
> 
> Like it? Hate it? Personally, I really like that it doesn't round off corners.

@lexelby I like the idea of shortening stitches on tight curves, but the current approach definitely has a lot of room for improvement.

Currently it does curve simplification (using the Douglas–Peucker algorithm, which also causes weird artifacts in contour fills) as an entirely separate pass, and then splits the resulting segments as lines. This causes a lot of stitches which are shorter than the need to be to get the correct tolerance, as well as creating a lot of stitch points which so not lie on the original curve, which causes unnecessary inaccuracies when reducing curve tolerance to get longer stitches. 

I'm going to try switching the curve simplification to use a version of [Zhao and Saafeld's incremental algorithm](https://cartogis.org/docs/proceedings/archive/auto-carto-13/pdf/linear-time-sleeve-fitting-polyline-simplification-algorithms.pdf). As this works in a single pass from the beginning of the curve to the end, this can be modified with a maximum stitch length which would make each round output a point after either the length or the tolerance has been hit. This would have the advantage of always producing points on the curve and not shortening stitches unless the full-length stitch would be out of tolerance.

@tyrosinase I think this approach could get the best of both worlds, getting the consistency of the old algorithm on gradual curves and the accuracy of the current algorithm on tight curves.

**Comment by tyrosinase** [comment]
LA LA LA LA I CAN'T HEAR YOU! 😆

(we're in the middle of making an offer on a house, there is already too much change in my life)

(seriously though, as long as my files with a tolerance at a million-billion (okay, 2mm) still have stitches stay consistent(ish) length when re-exported, I'm happy)

**Comment by lexelby** [comment]
@tyrosinase Good luck on the house!

@george-steel Sounds good, give it a go!  I considered Zhao-Saafeld but I chose Douglas-Peucker mostly because it did the job and it was already in Shapely.  I'm happy to use something else that gives better results.

**Comment by george-steel** [comment]
@lexelby  PR is up.
