### ISSUE TITLE
Inkstitch fails with unknown error when using Break Apart

### ISSUE THREAD

**Issue by thoughtfission** [inkstitch/inkstitch#1678]
shapely.geos - ERROR - TopologyException: found non-noded intersection between LINESTRING (537.871 800.212, 538.931 800.291) and LINESTRING (539.57 798.802, 538.788 800.326) at 538.81041924710496 800.28218864427947

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value

**Comment by kaalleen** [comment]
Thank you for your error report. This one was a bug in Ink/Stitch due to the shapely version used in the latest release. You could try a development version to see if this error still exist:

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by kaalleen** [comment]
Hopefully fixed in 2.2.0. If not please report in a new issue.
