### ISSUE TITLE
Trying to create .pes file but it hangs 

### ISSUE THREAD

**Issue by kjavar37** [inkstitch/inkstitch#1681]
Hello,

I'm using inkscape with the inkstitch extension on an Apple M1 and am having issues with it hanging when I save it as a pes. I'm fairly new to this stuff can anyone give any ideas how to resolve this?

Thanks

**Comment by kaalleen** [comment]
Do you have any success with the other Ink/Stitch options such as the Simulator (with nothing selected)?

**Comment by kaalleen** [comment]
No response, closing.
