### ISSUE TITLE
Won't save

### ISSUE THREAD

**Issue by kernnell** [inkstitch/inkstitch#169]
Hi guys amazing plugin. but i'm having an annoying problem, it saved a couple of times, to a couple of drives. but now it doesn't save anymore.

I'm writing C:\ in the directory field, noting happens wen i press apply, it doesn't save the selected .PES file anymore. 

Please help. Thanks

**Comment by kaalleen** [comment]
I believe you have an permission issue here, try saving to `C:\Users\Your-Name\Documents`. Or whatever folder you choose within your user files. Substitute `Your-Name` with your user name.

Hope it helps?

**Comment by kernnell** [comment]
Thanks Kaalleen, but saving to C:\Users\My-Name\Documents didn't help. Nothing gets saved. 
This is really frustrating, everything is done just needed to save ans transfer to the machine.

I really need help with this saving challenge :)

**Comment by lexelby** [comment]
Huh, that's weird!  I'm sorry you're having trouble.  Do you see any error messages?

It's especially interesting to me that it worked the first few times.  What happens if you try with a different SVG?  There are a couple of example SVGs packaged with Ink/Stitch. 

Another thing to try: does it work if you tell it to save in another format, like CSV?

**Comment by wwderw** [comment]
> It's especially interesting to me that it worked the first few times. What happens if you try with a different SVG? There are a couple of example SVGs packaged with Ink/Stitch.


I have to wonder if the latest Win 10 update did anything to it (if the OP is using Win 10).  I know the latest update (1803) on my dad's computer messed with his programs (lost activations to programs and even lost the activation to his OS, **his OS**) among other things.

This may not be the case, but whenever there is a recent update, especially on a Windows machine, but this came happen even on a Mac or Linux rig, that's where I tend to look first.  Rolling back that update, even there was indeed an update that happened right before the undesired lost of functionality happened.

Again, this may not be the case, just something I tend to look at around major updates that just recently rolled out.

**Comment by danielkschneider** [comment]
Hi
I tried to reproduce this (Win 10 Pro, build 17134) and permission do work for me. The only things that comes to mind are (a) browser restrictions and (b) write permission to this directory and (c) and an error in your SVG stitching code.

So:
* Did you check write permission to this directory
* Did you try with another browser
* Did you look at error messages from InkStitch ?
- greetings !

**Comment by kaalleen** [comment]
No answer for a long time. I will close the issue. If you are stille experiencing the problem, please reopen.
