### ISSUE TITLE
PeerTube Channel

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1690]
The videos on our YouTube channel do appear to have advertisement. How do we turn that off?!??

**Comment by Marif91** [comment]
Pourquoi veux-tu désactiver les vidéos ?

**Comment by Augusa** [comment]
advertisement = publicité. 
Je pense que le problème c'est d'empêcher la publicité!

**Comment by kaalleen** [comment]
Well, the thing is, that I don't want to sell lip gloss or nice holiday appartments. I just want to explain Ink/Stitch to users. Bothering them with advertising is not acceptable for me.

**Comment by tyrosinase** [comment]
I think that's the price you pay for them hosting it (and, theoretically, sending traffic to it).

There's always Peertube (though I admit I am emphatically not a video person and can't give any detail beyond "so *that* exists").

**Comment by kaalleen** [comment]
Yes, so right, I am all aware of that. It's just that I thought we ran a channel without advertisement - until I noticed otherwise.

I'll have a closer look at PeerTube. I know that blender and other open source projects switched over there for the very same reason.

**Comment by LochanLoch** [comment]
I see that [InkStitch](https://inkstitch.org/) is on US-GITHUB-xxx there was a bit time away the asking to get donations for things like web-space or a bit income for the hard coding all you guys did now over years.
Or the links from Project side to YouTube need a single frame so the Videos would be bigger and not in a tiny/small window.
For that what I think
![Bildschirmfoto_2022-06-16_21-03-21](https://user-images.githubusercontent.com/66974900/174147904-01152033-5d02-415e-ab90-10e42022b850.png)
my browser in full screen ;-) the yellow area is unused the red is navigation/useless Information for the video ;-)
using a video from there is without any spam advertisement ...

... nothing is useless ... :-)

**Comment by Augusa** [comment]
diode.zone looks to be very interesting.

**Comment by kaalleen** [comment]
Thanks :) At least I feel better with that choice.

**Comment by kaalleen** [comment]
@LochanLoch I think you can expand the video when you are watching it.
I am not sure if all the videos have advertisement. At least the new ones had. Do you think embedding removes advertisement?

**Comment by LochanLoch** [comment]
On Full Screen Yeah but its only an idea - in the moment someone use the "watch on YouTube" the advertisement start instant and old videos got it too maybe its a google hack to check browser id and piss open source users ;-)
> Do you think embedding removes advertisement?

Yes, it obviously still works. Just how long it stays that way. Who knows.
