### ISSUE TITLE
unexpected error on ink/stitch

### ISSUE THREAD

**Issue by lipeixin89** [inkstitch/inkstitch#1691]
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\break_apart.py", line 59, in effect
  File "lib\extensions\break_apart.py", line 144, in polygons_to_nodes
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by kaalleen** [comment]
Interesting. Would you mind to share the svg which was causing the issue?

**Comment by lipeixin89** [comment]
![nametagbernice-01](https://user-images.githubusercontent.com/107474740/174431825-b16af67a-e890-40a3-81e5-d6741c69eab6.svg)

Here it is, i was trying to create some nametags of my daughter's name

**Comment by lipeixin89** [comment]
![image](https://user-images.githubusercontent.com/107474740/174431855-0eacd18d-2661-4940-b8a1-4ef8549d5e52.png)

When I run in inkscape, it returns with this

**Comment by kaalleen** [comment]
Thank you. I tested your file with a newer dev version. It's working. So there is hope.
But I really would advice to use an other font. This font has a lot of holes in there and the stitch out will not look good.
Ink/Stitch has a lettering tool with a grwoing amount of fonts. Have a look in there, maybe you are lucky and find a font you like for your purpose. These fonts are embroidery ready.

**Comment by kaalleen** [comment]
Also your font is really really small, this is challenging in embroidery.
Have a look at the font library on the website and watch out for small fonts. There are some fonts, that are not included in the latest release, but if you want one of those, please ask and we can guide you how to use it already now.

https://inkstitch.org/fonts/font-library/

**Comment by lipeixin89** [comment]
Hi, thank you very much for your help. Really appreciate it :)

**Comment by kaalleen** [comment]
You are welcome :)
I'll close the issue, seems as if it has been fixed for the next release.
