### ISSUE TITLE
Remplissages texturés version 2.1.2

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#1698]
J'ai testé un anneau. Le centre est considéré comme une surface de la texture. Je souhaitais qu'il soit en remplissage automatique. 
Je n'ai pas trouvé de solution autre que celle d'ouvrir l'anneau.

Voici le dessin de l'anneau (en version fermée et en version ouverte) :
![Capture d’écran 2022-06-17 à 16 43 56](https://user-images.githubusercontent.com/65076100/174395681-54fd4a8b-1a2d-4b3b-9d77-414e47a41583.png)

et le résultat de la simulation de broderie :
![Capture d’écran 2022-06-17 à 16 43 30](https://user-images.githubusercontent.com/65076100/174395700-16924769-32e9-4815-b302-92a59e454983.png)

Merci !!

**Comment by kaalleen** [comment]
Thanks for your input. I wanted to avoid the restrictions that come with a fill shape (polygon). With the make valid branch I believe we should risk it. So a fix for this is included there.
