### ISSUE TITLE
inkstitch ne veux plus fonctionner correctement 

### ISSUE THREAD

**Issue by nadiadroneau** [inkstitch/inkstitch#1707]
Bonjour 
depuis quelque temps quand je veux créer mes fichiers Inkstitch ne me trouve aucune erreurs mais m'envoie un rapport ( si dessous ) qui m'empêche d'enregistré en format PES ou autres . Je peux seulement enregistré en SVG et c'est tout .
Es ce que quelqu'un pourrait m'aider s'il vous plait ?

* Ink/Stitch Version: make_valid (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 308, in validation_errors
  File "lib\elements\fill_stitch.py", line 261, in shape
AttributeError: 'Polygon' object has no attribute 'geoms
![griffes 15 15 ](https://user-images.githubusercontent.com/108232388/175826335-39f59b97-449f-4a89-b39f-d436d7f07148.svg)
'

**Comment by kaalleen** [comment]
Thank you for your error report - and the svg!!
A fix can be found in this release here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fixes_for_220

This is a test branch for the very next release.
So we'd be happy if you could try that out and report every bug you come across :)

**Comment by nadiadroneau** [comment]
Bonsoir Kaalleen 
Merci beaucoup pour le lien , c'est très gentil à vous .
Je l'ai télécharger et pour le moment ça fonctionne très bien .
Un ÉNORME MERCI pour tout le travail que vous faite pour nous tous et toutes  .

**Comment by kaalleen** [comment]
I'll close the issue now. It won't be a problem in the official release - thanks to you :)
