### ISSUE TITLE
Break apart fill objects isn't working with colored variable, i traced to bitmap

### ISSUE THREAD

**Issue by the-emblazer** [inkstitch/inkstitch#1708]
A picture of a bunny was working fine with trace to bitmap under the settings: multicolor/colors, nothing else was changed. then i had to break apart fill objects which I got a greeting with an error message that called itself not an error even though the message said it was an error (xD) here was the message: **shapely.geos - ERROR - TopologyException: found non-noded intersection between LINESTRING (307.636 704.371, 307.278 704.878) and LINESTRING (307.155 704.53, 307.392 705.112) at 307.28999984905789 704.8614086085048

Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\break_apart.py", line 54, in effect
  File "lib\extensions\break_apart.py", line 68, in break_apart_paths
  File "shapely\ops.py", line 152, in unary_union
  File "shapely\geometry\base.py", line 76, in geom_factory
ValueError: No Shapely geometry can be created from null value**

**Comment by kaalleen** [comment]
No response, closing. Most probably fixed.
