### ISSUE TITLE
satin stitch is stuttering

### ISSUE THREAD

**Issue by sk7fast** [inkstitch/inkstitch#1710]
its regular speed the first half, and then stutters
idk why 

pls help
;'(
thx <#
https://user-images.githubusercontent.com/108370461/176287378-6aa43ec6-caeb-4908-a6ca-e73e4b6df5cc.MOV
![Screen Shot 2022-06-28 at 2 04 11 PM](https://user-images.githubusercontent.com/108370461/176287546-4f753a02-205c-41bf-930e-318ef2a65b7a.png)

if the video is not loading, the satin stitch in the screenshot is going left to right, small to big, and halfway thru the stitch the embroidery slows down by like half speed, then goes back to regular speed with everything else.

**Comment by sk7fast** [comment]
thx for this program , im still learning it. hoping to learn gradient next

**Comment by kaalleen** [comment]
The machine will automatically slow down for long stitches. Your satin looks like it has very long stitches. If your machine would stitch it at the same speed, you would experience very bad pulling (distortion) on the fabric. Every stitch pulls and pushes the fabric, but this is especially true for long stitches. So it's good that your machine is clever enough to slow down ;)
Be careful not to use satin columns wider than 12 mm.

**Comment by sk7fast** [comment]
Wow okay thank you very much Kaalleen
