### ISSUE TITLE
stroke to satin

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#1711]
in the new release from kalleen it appears there is an issue with the satin tools as i converted a line to satin it broke the line in two parts then i  joined the rails of the two where they were split and than ran the params then it is not keeping all the rungs in right place 
![image](https://user-images.githubusercontent.com/85417086/176441355-715ea073-0997-4ec6-968d-d02f3f7adbea.png)
i tried a few times  and keeps doing it i am running newest inkscape and windows 10

**Comment by tyrosinase** [comment]
I've run into that too, but I assumed it's an Inkscape thing. When you merge two nodes, it's like it yanks that node segment out of its previous path, instead of combining the two entire paths. Do it on both the rails and you end up with a leftover rungs-only object.

**Comment by kaalleen** [comment]
Yes, I suppose there isn't much we can do about it. I would say the fastest way to do it is to select both satin, hit Ctrl+K to combine them and then merge the nodes.

**Comment by kaalleen** [comment]
... or we could ask the Inkscape team if for them that is wanted behaviour or not.

**Comment by gusvisser** [comment]
but if this only happens with the new version of inkstitch is it not an inkstitch issue then

**Comment by tyrosinase** [comment]
It happens with no Ink/Stitch involvement; that's what I did for the demo I submitted, just built a couple of three-subpath paths and connected 'em up. No Ink/Stitch params on them at all and it had the same behavior. Now, I didn't uninstall the extension so could be they'll come back and tell me they can't replicated it, but that seems unlikely.

https://gitlab.com/inkscape/inbox/-/issues/7261

**Comment by kaalleen** [comment]
Closing. Request has been send to the Inkscape team and we cannot do anything about it (just avoid breaking the satin too much during conversion). But I believe this is an other request somewhere else and on our list already.
