### ISSUE TITLE
ink stitch dark theme of Lettering Dialog (on a Mac)

### ISSUE THREAD

**Issue by Dicedude1** [inkstitch/inkstitch#1713]
Lettering Dialog window is black and hard to see / use in ink stitch ver. 2.1.2.  Does anyone know how to change the theme from black to white???   It is very annoying when using the Lettering feature in ink stitch.
Here's what I'm referring to:
![Lettering Window](https://user-images.githubusercontent.com/108488560/176916926-3b45e7aa-1710-446d-a161-29a8f18c20d8.png)

Thanks to all.....DiceDude1

**Comment by kaalleen** [comment]
Isn't it using the system theme? But I see what you mean. The description text is black. Maybe we should adapt there. I think the font images have been updated to have a white background (at least most of them).
