### ISSUE TITLE
PES Export (Save Copy As) Issue

### ISSUE THREAD

**Issue by sup-flues** [inkstitch/inkstitch#1719]
The Inkstitch PES export to Brother Embroidery machines is having an issue. At least i am pretty sure it is Inkstitch since the Brother Embroidery Machine handles included PES files without a problem. The files preview ok (see attached), though they show clipping at the top and bottom. Then when they are opened ("set") for editing, what remains is only the lower right corner of the vector image. It is not an oversize issue as these are all smaller than the max hoop size. Something is coming with the PES file that is telling the Brother to crop the image, I think. 

![IMG_3673](https://user-images.githubusercontent.com/108194207/177215900-35ca66e1-932f-4aae-a324-cc7249390f70.JPG)
![IMG_3674](https://user-images.githubusercontent.com/108194207/177215903-d1caca98-8f48-412e-93ca-508fefd6cfbf.JPG)
![IMG_3675](https://user-images.githubusercontent.com/108194207/177215906-304e3463-c399-4560-a8f7-0c6796114bfc.JPG)

VERSION: Inkscape 1.2 and Inkstitch (kaalleen-fixes_for_220-osx.

**Comment by kaalleen** [comment]
Thank you for that feedback. We are happy this didn't end up in the next release!
If you want to run a test, here is a fix: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-linalgstripping

**Comment by sup-flues** [comment]
This is awesome! Thank you so much. Everything is gold!

**Comment by kaalleen** [comment]
Thanks for the feedback :)
