### ISSUE TITLE
Saving Problems

### ISSUE THREAD

**Issue by kochy25** [inkstitch/inkstitch#1720]
i have had some saving problems with inkstitch.

The message i have got:

AutoSatin Running Stitch 1 (autosatinrun1): error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.1.2 (windows)

Traceback (most recent call last):
  File "lib\stitches\auto_fill.py", line 64, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 145, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 95, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 228, in to_stitch_groups
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 67, in auto_fill
  File "lib\stitches\auto_fill.py", line 264, in fallback
  File "shapely\geometry\base.py", line 868, in __getitem__
IndexError: tuple index out of range

**Comment by kochy25** [comment]
I have designed something like a Border with some text (Text was made with the Inkstitch plugin) inside. Nothing "Complicatet" i think. 
![Test2](https://user-images.githubusercontent.com/108870701/178150903-e886c6c5-caef-4291-ac38-8a9d3994d8e5.svg)
I have had the Bug while saving as *.exp file. 
I have saved the Border and the text in seperate files - and stitched seperate. That works.

**Comment by tyrosinase** [comment]
Yep, looks like you've added a fill. If you want to change lettering's color, you need to change the stroke color (and clear the fill, on these).

**Comment by kochy25** [comment]
First I tried to safe it with the original fill color as exp file but it don't work and gave me the error message. Then I change the color of the filling. No changes. At last (I don't have the last file) I change the stroke color - same as before.

**Comment by kaalleen** [comment]
![withoutfill](https://user-images.githubusercontent.com/36401965/178276710-15ec9730-621b-43c7-a7b7-b0c434630ef8.svg)

As @tyrosinase said, a fill doesn't work on satins. I updated your svg so it doesn't have a fill. Maybe you can work out from here. If you want to change the color of the satin, update the stroke color.

**Comment by kochy25** [comment]
thanks. but in black i have tried to save first - same error. 
I have saved the border in one file and the Text in an other file - works.

**Comment by lexelby** [comment]
@kaalleen You know, now there's not really any reason we have to outlaw a fill with a satin.  It's not gonna work the way they think, but it's no longer impossible for us to deal with, now that we can handle fill objects that are multiple disconnected shapes... 

Maybe this should be another "you get what you ask for" thing, and we can get rid of the often-confusing "satin can't have a fill" error.

**Comment by kaalleen** [comment]
I was thinking along these lines too :) At least it is, what you see on the screen.
