### ISSUE TITLE
The program won't download. Keeps asking is site safe? 

### ISSUE THREAD

**Issue by mangopoo** [inkstitch/inkstitch#1723]
Having issues with download.

**Comment by kaalleen** [comment]
Are you using windows with the edge browser?
If you have firefox installed, try with that one.

**Comment by kaalleen** [comment]
No respond. Closing.

**Comment by mangopoo** [comment]
You never replied in the first place!

Sent from my iPhone

On 17 Dec 2022, at 11:10, Kaalleen ***@***.***> wrote:

﻿

Closed #1723<https://github.com/inkstitch/inkstitch/issues/1723> as completed.

**Comment by kaalleen** [comment]
Are
