### ISSUE TITLE
Covert line to satin- MAC

### ISSUE THREAD

**Issue by CaptainNoAction** [inkstitch/inkstitch#1725]
So, I am teaching myself and starting small. I have a 2022 MAC Book Pro. I drew a line, set width to 2mm under stroke style, went to ink stitch, convert line to satin, and get an error "only simple lines can be converted to a satin columns".  I go to my PC and no issues. Any idea why? Thanks

**Comment by lexelby** [comment]
This likely means that your line has a fill set in addition to the Stroke settings.  Try disabling the fill and see if Ink/Stitch is willing to convert it then.

@kaalleen Maybe we should change this to `any`, not `all`, and have it convert whatever it can?

 ```
       if not all(isinstance(item, Stroke) for item in self.elements):
```

**Comment by CaptainNoAction** [comment]
Thank you. I "X" fill and kept color. I was able to convert to satin. Appreciate it.

**Comment by kaalleen** [comment]
That makes a lot of sense. Pushed it to the 220 update branch.
