### ISSUE TITLE
Missing file extensions on PC

### ISSUE THREAD

**Issue by CaptainNoAction** [inkstitch/inkstitch#1726]
New problem. I went to export and I only have 7 for general computer. No sewing format file extensions. I tried looking it up and dont see anything. I must be missing something simple. Thanks

**Comment by tyrosinase** [comment]
That usually means an overactive virus checker has silently quarantined part of Ink/Stitch. I'm not sure what the solution is... I run Linux, but I've seen it here in issues like #710 and #1438.

**Comment by CaptainNoAction** [comment]
Thanks for responding. I think that as well but my new macbook has the same 7 file extensions. Just checked. I will turn off Windows Defender and reinstall to see if they are there.

**Comment by CaptainNoAction** [comment]
Just reinstalled without all antivirus and defender off. Still the same. 

Ok, on the inkstitch screen there is an export with only 7. Tried the alt,ctrl,shift, s and I get all the file extensions. Odd but ok.
