### ISSUE TITLE
Simulator / Realistic Preview hangs

### ISSUE THREAD

**Issue by Aelesas** [inkstitch/inkstitch#1728]
Inkscape 1.2 64-bit / InkStitch v2.2.0 / Windows 10 Pro v 10.0.19043 Build 19043 - Simulator / Realistic Preview just hangs once initiated. Have to end process in task manager to gain back control of Inkscape.

Same issue on another PC with same parameters except it's Window 10 not the Pro.

**Comment by kaalleen** [comment]
Sorry, you haven't received much of a response to your issue. Time has passed and Ink/Stitch has received some updates.
Therefore I'm going to close the issue. If you are experiencing similar issues again, please feel free to open a new issue!

**Comment by Aelesas** [comment]
This is working on Windows 11 with 3.0.1, thank you.
