### ISSUE TITLE
PDF Export issue

### ISSUE THREAD

**Issue by Aelesas** [inkstitch/inkstitch#1729]
Inkscape 1.2 64-bit / InkStitch v2.2.0 / Windows 10 Pro v 10.0.19043 Build 19043
When trying to run PDF Export, receive the following:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lib\extensions\print_pdf.py", line 173, in run
  File "werkzeug\serving.py", line 865, in make_server
  File "werkzeug\serving.py", line 709, in __init__
  File "http\server.py", line 138, in server_bind
  File "socketserver.py", line 466, in server_bind
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

PS - it was just a test file of a circle with a stroke in order to keep it simple.

**Comment by kaalleen** [comment]
Does it work with Ink/Stitch v3.0.1?

**Comment by kaalleen** [comment]
Electron (on which the print pdf output is based upon) has been updated for 3.0.1
If this issue still shows up, please open a new issue.

**Comment by Aelesas** [comment]
Thank you. Sorry I didn't respond sooner. Yes, it seems to be working with 3.0.1 on Windows 11 now.
