### ISSUE TITLE
files  posted on inkstitch webpage dont work properly

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#1734]
as i downloaded a svg file on the hat and run it through the simulator i get complete different sewout so please what i happening i am trying to learn and understand the ripple but it appears to be hard to figure what it does when the image i post with this is the svg and then tried right away the simulator please help me out
![image](https://user-images.githubusercontent.com/85417086/179375299-60184903-4c2e-4b3d-adbd-496d1dc74fc7.png)

**Comment by kaalleen** [comment]
Hups, please try again. The file has been updated.

Although it is not complete (satin guided ripples are missing) this video here also may give some clues how ripple stitch is working: https://diode.zone/w/tPk1wDPfRWwehYrbhktRuu

**Comment by kaalleen** [comment]
Also have a look at the updated website: https://inkstitch.org/docs/stitches/ripple-stitch/
