### ISSUE TITLE
"Zero repeats" repeats one time

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1738]
Usually I put my working lines on a separate layer and then hide them, but sometimes I want to leave them visible but not have them stitch out, so I set them to repeat zero times. That has stopped working: they now try to stitch out.

I get that this may be kind of a DWIW thing, but I'd rather see the dialog pop up a "you know this won't stitch, right?" warning when you set it to zero repeats, vs. stitching things unexpectedly.

**Comment by lexelby** [comment]
I didn't realize this changed.  I thought we always treated 0 repeats as 1.

Can you use the "don't Stitch this object" command instead?

**Comment by tyrosinase** [comment]
I'm pretty sure that's a recent change, though I'll confess I hadn't used this file in awhile.

In theory, sure. In practice, the command bubbles had made it too much of of a nuisance. I suppose those collapse same as the trims though, so I could see how that goes. But it's much easier to be able to just check the dialog.
