### ISSUE TITLE
Fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by briangtiguy** [inkstitch/inkstitch#1742]
Hello, having a slight issue, the msg said to post it here. 

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![jake](https://user-images.githubusercontent.com/109565437/179648003-8964fd91-43c4-4a24-9bca-a9978275ea99.svg)

**Comment by tyrosinase** [comment]
This looks like the same bug as #1724 though I'm not sure what @kaalleen did to identify the problem paths there.

**Comment by kaalleen** [comment]
Actually should be already corrected in a development version. You can test it if you like: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

**Comment by chrisyelf** [comment]
I encountered this too and it seems fixed in dev version pointed by @kaalleen

**Comment by kaalleen** [comment]
I'll be using this to reference more issues of this kind to this one here. If you were looking for a solution with Ink/Stitch v2.2.0 please remove very small elements from your document.

**Comment by kaalleen** [comment]
Closing the issue, because it has been fixed for the next release. It can still serve as a reference for new issues of this kind.
