### ISSUE TITLE
will not install on my computer

### ISSUE THREAD

**Issue by Dswolves** [inkstitch/inkstitch#1744]
Good morning,

I've tried to install Inkstitch on my computer to add to inkscape and it keeps telling me that I need a 64 bit computer.  Mine is definitely 64 bit.  But there is something about the way that Samsung made my computer that every once in a while a program does not recognize it as a 64.  Do you know any way around this?  This is a brand new computer.

Thank you

**Comment by kaalleen** [comment]
Hm, that's a strange riddle. Actually we release the Ink/Stitch version for Windows in 32 bit (it will run on 64 bit as well), but that makes it unlikely to complain that your computer is not a 64 bit.

Maybe you can try to install the 32 bit version of Inkscape (https://inkscape.org/release/1.2.1/windows/32-bit/), it should be working too.

**Comment by kaalleen** [comment]
No response. Closing.
