### ISSUE TITLE
User Experience for Invalid Geometry

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#175]
Have it to where Ink/Stitch will catch "invalid" geometry errors and suggest tips on how to fix the error.

**Comment by lexelby** [comment]
#323 effectively a duplicate of this one, but I'm going to close his one since #323 has more detail on what a solution will look like.

**Comment by aloxyz** [comment]
Has this been implemented yet?

**Comment by kaalleen** [comment]
Yes, it's the troubleshoot extension.
