### ISSUE TITLE
Issue:  Saving .Svg to .Pes Format

### ISSUE THREAD

**Issue by SChushcoff** [inkstitch/inkstitch#1750]
[Inscape Bug Error Message](https://user-images.githubusercontent.com/109889172/180633540-c256f6b5-2fa1-41ae-beaf-a29dd3237979.png)

Above is the Inscape Bug Error Message I receive when I attempt to save a copy of my design from a .svg format to .pes format for a brother machine.  I am not receiving any Params, Troubleshoot, or Simulator/Realistic Preview Issues and I have cleaned up the document.  This is my first project and I honestly do not know what I'm doing, I have yet to even embroider anything.  I don't actually have an Embroidery Machine at the moment either, I'm just dabbling/learning something new.  I genuinely know nothing.  How I created the design was I took a photo on my phone of arranged flowers I had received, flipped the photo and cropped the part of the photo I wanted to use, then manually digitized the photo with the draw bezier since it was too detailed to make a bit map copy of, (can I do that?  Did I do that right?).  I then filled in the objects with 9 different colors and deleted the original photo entirely.  I added text as well which I also digitized and the black text is included in the 9 colors I mentioned.  The size of the design is 98.282 W by 168.569 H in mm, which I believe is the largest area space I can use on the machine I would like to buy in the future.  There are 298 Objects (Yikes, I know! I deleted several others!)  I previously received several errors of over laps and tiny object issues but they have all supposedly been resolved since then and I believe they have all been fixed as I am no longer getting any error messages and I am able to stitch preview the design.  I significantly simplified, reduced and used the process of elimination and the delete button to remove the errors.  Although the design is probably more detailed than it should be but again I'm not receiving any errors.  I also attempted to save by going to Extensions>Ink/Stitch>Visualize and Export>Embroider and when I do that it gives me instructions to File>Save a Copy>InkStitch: Brother Embroidery Format (.pes) which is how I receive the above message and why I am creating this issue.  Then it provides me with another message saying that it was not saved as a .pes format.  When I go to Extensions>Ink/Stitch>Visualize and Export>Embroider it also gives me the option to "Apply" but nothing happens besides the message closing.  I have read other issues similar to mine and I have attempted other solutions like uninstalling and reinstalling Inscape and InkStitch, set Objects to Path and Union Objects, Reset Preferences (not sure what I was supposed to do, just switched the numbers to zero, I'm not even sure why I did that) and changed the colors of the objects but nothing is working.  I originally grouped paths by fill color but since I pressed Union Objects it is now one image.  I've been fidgeting with it I just want to save it to .pes if possible.  The message mentions too many color changes but it stitches out one color at a time and there are 9 colors, even though it mentions 577 changes (0,255 out of bounds)?  Again, I have no idea what I'm doing.  I'm just testing out a new art form, this is literally my 1st Inkscape/Inkstitch design/project.  Thank you for your patience.

**Comment by SChushcoff** [comment]
Also, it seems to color change everytime the needle moves to a different path regardless of whether the color is the same or not, which it usuallyis, as I grouped the colors together and as I statedabove there are only 9 colors.  I'm using the latest version of both Inkscape and Inkstitch.  The main concern is that I want to save the .svg to a .pes format.

**Comment by kaalleen** [comment]
It's hard to tell what is going on without the svg file. Would it be possible for you to send the svg file so we can analyze the problem? If you can't post it here (for copyright reasons), you can also send us a mail to send-us-files@inkstitch.org

**Comment by kaalleen** [comment]
Thanks :) You actually do have a lot of color changes in your file. On each object you have an invisible stroke outline which hasn't the same color as the fill. So this makes two color changes for each object. Select everything except for the font and open the fill and stroke panel. Go to the stroke panel and remove the stroke.

**Comment by SChushcoff** [comment]
That did the trick!  Thank you so much!  I will close this issue now!

**Comment by tyrosinase** [comment]
If you go into `Extensions > Ink/Stitch > Visualize and Export > Simulator/Realistic Preview` you can watch where it makes color changes (and thread jumps) and that'll usually help you find mis-sorts.

Also, that hoop size doesn't sound like any PES-reading machine I know of; are you referring to a 4x4 machine using an SA434 repositionable hoop? Because that isn't the same as having a true 100x170mm machine: https://silverseams.com/tutorials/using-a-5x12-hoop-on-a-5x7-embroidery-machine/index.html Now, I do a lot of black magic myself to make larger-than-the-hoop things, so I won't say anything can't be done. But just be prepared for the need for said black magic.
