### ISSUE TITLE
Export only pattern in Visualize and Export > PDF Export?

### ISSUE THREAD

**Issue by cvick32** [inkstitch/inkstitch#1756]
I was wondering if there's a way to export the realistic view of a pattern without the extra information provided in the PDF Export tool.

All I really need is the pattern in PDF form, none of the other provided statistics etc.

Let me know if there's a way to do this or another work around.

 Thanks!

**Comment by kaalleen** [comment]
No sorry, currently this is not possible. I marked this as a feature request.

The only workaround I could think of right now is to make a screenshot. That's not very practical I know.

**Comment by gusvisser** [comment]
Once the Pdf is created in the pdf export then load that pdf back into inkscape and then you can delete unneeded pages and it is easy to delete all unwanted info on the page and then do a save as and choose pdf

**Comment by cvick32** [comment]
I tried re-importing the PDF, but there's definitely a decrease in quality. Additionally, there are issues with InkScape's groups that cause the PDF to render large black boxes behind the SVG.

**Comment by kaalleen** [comment]
That would be well possible with the updated stitch plan preview for the next version (3.1.0)
