### ISSUE TITLE
FSL Example

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#176]
This is what I was thinking for the FSL example.  Still have some work to do and the instructions to go along with it, but this what I was thinking.

![butterfly lace example](https://user-images.githubusercontent.com/24878362/40746415-04750784-6420-11e8-8ce8-45afc67fd3d2.png)

This is actually an FSL version of an applique design that I had created for my wife's nieces.  I thought would change it up a bit for this project and make it into an ornament.  The original applique version is this one here:

![butterfly applique](https://user-images.githubusercontent.com/24878362/40746537-4efaf21e-6420-11e8-93ed-f55516376653.jpg)

**Comment by lexelby** [comment]
Love it!
