### ISSUE TITLE
Support various lock stitches

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#1762]
Various stitch methods or thread weights may need various kinds (or length) of lock stitches.

(I remember we had an issue about them once and we discussed that it's not very simple to just adapt the lock stitch length, because it may miss the original pass if the stitching ends within a sharp curve. I can't find the issue right now.)

Let's try to find out which lock stitch types we need and should offer. Any help and ideas are appreciated.

**Comment by lexelby** [comment]
Yes, I would love it if someone other than me took a crack at this.  I have the feeling I might have been overthinking it and making it harder than it needed to be.

**Comment by danielkschneider** [comment]
Hello, I am no expert, but have two inputs:

1) Tack (start) and lock stitches according to Bonnie Nielson, Puch, Gruber Verlag, 2010. I redid the drawing of hers, so it should be ok to reuse, if the original is cited. 

2) A feature request for lock stitches that are compatible with heavy 12 thread (I will try to find some authority on that. In the meantime, maybe you could adapt lock stitch spacing to the density of the object. E.g. if distance between points is 0.4mm then distance between lock stitches could be 0.2.
Rationale: Using standard lock stitches with wt 12 thread will create heavy knots and lead to thread breaks or worse. Typical needle used is a 1.1mm topstitch (as opposed to a 0.75H-E)

![Selection_229](https://user-images.githubusercontent.com/2872643/182350792-da1e3f6c-bf26-4c0b-8779-af52a08b92d8.png)

![tack-and-lockstitches](https://user-images.githubusercontent.com/2872643/182350886-24b7c807-2eb0-453c-9ed4-b31c4d497f15.svg)

**Comment by kaalleen** [comment]
I totally forgot about this. I must say, that I cannot completely see, how each one of them is positioned to the oroiginal path.

**Comment by Tina-Chris** [comment]
I think @danielkschneider would need to clarify, or someone else with Bobbie Nielsons book.

**Comment by danielkschneider** [comment]
The book is not very explicit. It just says that tack stiches are done to connect the upper thread to the bobbin thread and that the machine will slow down. Lock stitches are knots so they have to be a bit closer. I can send you the page with some other tool (it's probably not allowed to show copies heres), e.g. email me at dks at arbores.tech
