### ISSUE TITLE
Fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by dccbv58** [inkstitch/inkstitch#1766]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![palette](https://user-images.githubusercontent.com/110531099/182572645-f73abf63-73bc-41cb-b326-ac69ece81463.svg)

**Comment by tyrosinase** [comment]
There's a development version that fixes this error (see #1742), but unless you're stitching at an enormous scale you're going to be disappointed by the results of that design. It's going to need a lot of manual cleanup (converting all the spokes to running stitches, etc). Take a look at https://silverseams.com/tutorials/digitizing-with-ink-stitch/ or some of the videos on the subject to get more info on digitizing.

**Comment by kaalleen** [comment]
Closing in favor of #1742
