### ISSUE TITLE
Installation of Version 2.2 on Windows 11

### ISSUE THREAD

**Issue by tiweintraub** [inkstitch/inkstitch#1769]
Just downloaded Ink Stitch v2.2 on my Win 11 machine. The software was installed but did not execute.  See screen shot for multiple errors.  
![Screenshot 2022-08-04 112732](https://user-images.githubusercontent.com/94466455/182914411-f69a0692-a808-421f-af23-0380373e5219.png)

**Comment by tyrosinase** [comment]
Are you trying to run Ink/Stitch directly? It's an Inkscape plugin - run Inkscape and Ink/Stitch will appear as menu options under Extensions.

**Comment by tiweintraub** [comment]
Ah..let me go try that now.

**Comment by tiweintraub** [comment]
Operator error on my part.  Installed Inkscape and InkStitch now works.  Thanks for the assist.

**Comment by tiweintraub** [comment]
> Are you trying to run Ink/Stitch directly? It's an Inkscape plugin - run Inkscape and Ink/Stitch will appear as menu options under Extensions.

Thanks for the assist

**Comment by tyrosinase** [comment]
It's an easy mistake. Luckily the fix is pretty easy too :laughing:
