### ISSUE TITLE
Ink stitch  rendering wrong display

### ISSUE THREAD

**Issue by Dicedude1** [inkstitch/inkstitch#1770]
Ink stitch is rendering the wrong display.  I have tried changing the stroke with to almost nothing to alot.  Neither has any effect .  Inkscape seems to be working properly .   Changed  both Ink stitch and Inkscape back one version, started and restarted computer, but no luck no matter what I tried.  Any ideas sure would be helpful,,,Thanks to ALL....Here's some snap shots:

STROKE and STYLE SETTINGS:
![Stroke and Style](https://user-images.githubusercontent.com/108488560/182915530-2a245477-28a5-4a71-aabf-881b29004d2a.png)

SETTINGS VIEW:
![Settings (Fill)](https://user-images.githubusercontent.com/108488560/182915623-63b817d0-6374-427c-96b9-02c7b3022f28.png)

PARAMS V IEW:
![Params View](https://user-images.githubusercontent.com/108488560/182915735-4f6eda3c-8440-45ca-88b9-9e3ee65604a0.png)

SIMULATOR/REALISTIC VIEW:
![Simulator:Realistic View](https://user-images.githubusercontent.com/108488560/182915792-77b31c04-f747-4949-a2c7-c184c9935a23.png)

**Comment by lexelby** [comment]
Hi!  I'm sorry, but I don't understand what's wrong.  What are you expecting in this case?

**Comment by tyrosinase** [comment]
I think the problem is that OP expects a running stitch because the dialog says running stitch. This confused me too the other day on a zigzag... the Method option should probably be "Running/Zigzag" instead.

Dicedude1: change the stroke type to a dashed line (any dash will do) and it will do a true running stitch. Otherwise it will do a satin-like dense zigzag (albeit sometimes a VERY narrow one).

**Comment by Dicedude1** [comment]
This is one of many YouTube videos I have watched and tried to emulate. This video: https://www.youtube.com/watch?v=fK0LtiIQXXI&t=226s.  (The video is just what I used to see if things are coming out right.)

As you can clearly see no matter what the combination that was used, none of the results looked anywhere like that of any of the videos I watched.

I completely removed ink-stitch, turned off the computer ,reinstall ink-stitch 2.2.0, even in stalled ink-stitch 2.1.2 but all the undesired outcomes persisted.   Hopefully someone will be able to see/find what it is I’m doing wrong. 

Things were working fine the day before, and that is what bothers me the most(if it’s not broke, don’t fix it is my philosophy).  Yet I can take an existing project, and add shape to it and it works just fine.  Take a image and trace it with inkscape and it doesn’t turn out.  Same things happen as shown in any the examples.

Something some where is being inherited when you add an object to an existing project and that object turns out right whenever you do the Params or the Simulator /  Realistic Preview.

I just can’t figure it out.  So if you know where the issue is or could help,  I would be most appreciative.

Thank You,
Dicedude1

ALL selected-Convert Stroke to Path(Params)
![ALL selected-Convert Stroke to Path(Params)](https://user-images.githubusercontent.com/108488560/183144274-719a4ea6-7e8c-413a-a2fe-ef7451828810.png)

All selected-Object to Path(Params)
![All selected-Object to Path(Params)](https://user-images.githubusercontent.com/108488560/183144338-b0e6b7d6-70e9-4c22-b98c-9ab53214b43f.png)

Custom satin Column(inkscape)
![Custom satin Column(inkscape)](https://user-images.githubusercontent.com/108488560/183144470-553f554d-6522-415d-b8ee-c1ff4a2627e7.png)

Custom satin Column(Params)
![Custom satin Column(Params)](https://user-images.githubusercontent.com/108488560/183144548-e6d35940-df54-45b2-b44f-5829d2e37602.png)

Dashes(inkstitch)
![Dashes(inkstitch)](https://user-images.githubusercontent.com/108488560/183144640-3f69e998-cac3-4988-90f1-0acc0c80ec0e.png)

Dashes(PARAMS)
![Dashes(PARAMS)](https://user-images.githubusercontent.com/108488560/183144695-501dbe4c-e57d-409f-8528-1883d93755fc.png)

Right Side of Heart(inkscape)
![Right Side of Heart(inkscape)](https://user-images.githubusercontent.com/108488560/183144774-f42f8978-6385-4a7f-8505-4fdbdcb6b567.png)

Right Side of Heart(Params)
![Right Side of Heart(Params)](https://user-images.githubusercontent.com/108488560/183144838-6b45d863-a10a-416d-90e3-ab10e29718be.png)

Nothing in these example comes out the way it should.  I suppose I could be over-looking something, but just haven't been able to find the mistake.   As a note: the above images contain "inkscape" and "Params".   This means the image is either viewed in  inkscape(created) or in ink-stitch(Params).
All line are done with the Bézier curve in inkscape(that may/may not make a difference in the Params view).

**Comment by lexelby** [comment]
The problem is that your shapes are too small.  They're much smaller than the examples you're working from, and that means that far fewer stitches fit.

**Comment by Dicedude1** [comment]
Finally saw the problem.... the problem was in inkscape, DOCUMENT properties.
