### ISSUE TITLE
inkscape/inkstitch issue

### ISSUE THREAD

**Issue by mikaylamilo** [inkstitch/inkstitch#1773]
path3665: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
This looks like the same as #1733, which is a known bug, but which the devs have been unable to duplicate... if you're willing to share the file that would greatly help. Here is fine if you're okay with it being public, or send-us-files@inkstitch.org if not.

(I feel like they need "send-them-files@" as an alias for when it's not a dev answering...)

**Comment by lexelby** [comment]
@tyrosinase Oh, but why does send-us-files@ have to go to just devs?  You're just as much a member of this project, so you count as "us" too. :)  If you want, I can add you to send-us-files@ so that you get the emails too.  Just send an email to send-us-files@ so that I know your address and I can add you.

**Comment by lexelby** [comment]
I'm going to close this in favor of #1733, which I've just fixed in #1727, but that shouldn't prevent comments.
