### ISSUE TITLE
Trying to import a pre-digitized font PES format- receive the error below

### ISSUE THREAD

**Issue by gee2526** [inkstitch/inkstitch#1774]
I tested with the original file and then  a sample file by re-naming the letters on both I am getting the error below.   

Ink/Stitch experienced an unexpected error.If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.1.2 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/letters_to_font.py", line 43, in effect
  File "lib/extensions/letters_to_font.py", line 73, in get_glyph_element
  File "lib/stitch_plan/generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery/PyEmbroidery.py", line 520, in read
  File "pyembroidery/PyEmbroidery.py", line 473, in read_embroidery
  File "pyembroidery/PesReader.py", line 39, in read
  File "pyembroidery/PecReader.py", line 26, in read_pec
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by tyrosinase** [comment]
Hmm, that may be the same issue as #1610, though that was a different file format. There's a test release in the comments there though, give it a try and see if it fixes your problem.

**Comment by gee2526** [comment]
thanks, I hit the link for the os updates. My Mac will not open the files.   says cannot scan for malware the software needs to be updated contact the developer.

<img width="491" alt="Screen Shot 2022-08-06 at 9 33 48 PM" src="https://user-images.githubusercontent.com/110750071/183271352-55503310-12fb-4b32-bf74-4bd9be0f5388.png">

**Comment by tyrosinase** [comment]
What happens if you download the ZIP version? (I am Linux not Mac so now I'm just throwing out wild guesses though, sorry. Some of the devs have Mac experience and can probably comment more intelligently.)

**Comment by gee2526** [comment]
<img width="271" alt="Screen Shot 2022-08-06 at 9 48 43 PM" src="https://user-images.githubusercontent.com/110750071/183271640-2531771a-bd59-4531-8545-5493a4db8f48.png">

same issue, developer cannot be verified 

No worries, thank you for trying to help.

**Comment by tyrosinase** [comment]
Oh, you know what, there's stuff on the installation page about that, which I had forgotten: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

Saving you a click, it just says "Ctrl+Click on the downloaded file and click on Open."

**Comment by kaalleen** [comment]
Oh, no no. Don't try this version. This was before the latest release. Rather install the latest release (2.2.0) and see if this solves the issue. I'm not sure though, because I never got a file for this error.

**Comment by tyrosinase** [comment]
Oh whoops, right, I should pay attention to dates, huh?
