### ISSUE TITLE
Inkstich contour line

### ISSUE THREAD

**Issue by Iamat66** [inkstitch/inkstitch#1775]
Hi,
if I embroider an object with a contour line, why does the contour line not begin at the end of the filling.
See the video 
Thanks

https://user-images.githubusercontent.com/110776112/183296180-7b53fd7b-5570-4287-934e-3ad81f55d485.MOV

**Comment by kaalleen** [comment]
Thank you for your request. For now you can duplicate the shape and use the first as the fill and the second for the outline. In most cases you will also need to adapt the outline to fit to the pulling and pushing that happens to the fabric when you stitch out the fill. So in any case it is a good idea to use two different objects for outline and fill.

**Comment by Iamat66** [comment]
Hi Kalleen’
Thanks for your reply.
It depend what I have to do, then I use 2 different objects fir outline and fill.

But when the motif is very small it is match easier to use only one object.

The avantage is that I need only 2 lock points : 1 begining the fill and 1 end of the outline when the outline begin exactly at the end of the fill.
That was the reason of my question.

**Comment by kaalleen** [comment]
You could break a path at a selected node, so it would have a start and end point. Then point the fill end command to the same spot.

**Comment by Iamat66** [comment]
Good idea Thanks
