### ISSUE TITLE
pull compensation for fill stitch

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#1776]
a feature request for adding pullcompensation in two direction one in the direction of the stitch angle and one perpendicular to it since there is more pull in the stitch direction we would want more adjustment there

Thank you and hope to hear from you if this would even be possible

**Comment by kaalleen** [comment]
Thank you for your feature request, We actually discussed this topic long ago. Have a look here at issue #179
More detailed info can be found in #178

**Comment by lexelby** [comment]
#179 somehow got co-opted to be a bug report and was closed... let's keep this as our "pull compensation for fills" request.
