### ISSUE TITLE
Windows 7: ImportError: DLL load failed

### ISSUE THREAD

**Issue by nicolasakura** [inkstitch/inkstitch#1782]
I cyrrently facing some issue like below,

I m fail to run "Break Apart Fill Objects".

I was import image from my galleries and complete step with "Path" & "Multicolor".
but when i tried to complete the following step : Extension >  Ink stitch >Tools : Fill > Break Apart Fill Objects, after select 'Simple' then press 'apply', an error table pop out with title :
"Unhandled exception in script" 

and error messege :
"Failed to excute script 'pyi_rth_win32api' due to unhandled exception: DLL load failed while importing pywintypes: The parameter is incorrect."

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pywintypes.py", line 128, in <module>
  File "pywintypes.py", line 118, in __import_pywin32_system_module__
ImportError: DLL load failed while importing pywintypes: The parameter is incorrect.

What should i do to settle this issue?

**Comment by kaalleen** [comment]
Sorry, that you never really received an answer. This is not a failure on your side, but a packaging issue on our side.

**Comment by kaalleen** [comment]
There has been an other Ink/Stitch release in the meantime. So I'm closing this issue. Please open a new issue if you are seeing this error again with the current version of Ink/Stitch.
