### ISSUE TITLE
Fill: ZeroDivisionError

### ISSUE THREAD

**Issue by type8008** [inkstitch/inkstitch#1787]
path5970: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
This looks like the same bug as #1764, which as of that report hadn't been duplicated by the devs... there are instructions there on how to send them a file with the problem.

(#1786, #1783, #1779, and #1777 all seem to be the same, plus a couple other potentials.)

**Comment by type8008** [comment]
I sent them My Svg file hopefully they can get it taken care of, how many devs are there? there like little angels flying around saving us from spending thousands of dollars.

**Comment by lexelby** [comment]
Haha, that's the goal.  Who really wants to spend that much on digitizing software?

Fortunately I do know what's wrong here and there's already a pull request with the fix.  The bug is triggered by a super-small OR super-thin fill shape.  If you don't want to wait for us to fix it, find the offending object and delete it.  It won't be big enough to actually show up in your design anyway.

In your case it's path5970.  Use Inkscape's Find tool to find it.

**Comment by type8008** [comment]
So basically I forgot to cleanup my document lol.

Thank You!!



On Aug 16, 2022, at 9:16 PM, Lex Neva ***@***.***> wrote:

﻿

Haha, that's the goal. Who really wants to spend that much on digitizing software?

Fortunately I do know what's wrong here and there's already a pull request with the fix. The bug is triggered by a super-small OR super-thin fill shape. If you don't want to wait for us to fix it, find the offending object and delete it. It won't be big enough to actually show up in your design anyway.

In your case it's path5970. Use Inkscape's Find tool to find it.

**Comment by lexelby** [comment]
Nah.  Ink/Stitch should handle things without blowing up :)

**Comment by kaalleen** [comment]
Closing in favor of #1829
