### ISSUE TITLE
Warning dialog when exiting params preview too fast(?)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1797]
Encountered a little oddity in 2.2.0 when I exited the params preview at exactly the wrong time (apparently):

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lib/gui/simulator.py", line 779, in run
  File "lib/gui/simulator.py", line 796, in update_patches
  File "wx/core.py", line 3402, in CallAfter
AssertionError: No wx.App created yet

Evidently I checked zigzag underlay and clicked apply-and-quit a little too fast. It was just the "probably nothing's wrong, but maybe something is" warning rather than an actual error, so FWIW.

**Comment by kaalleen** [comment]
I think this has been fixed?!?
I'll close the issue for now. I hope though, that you'll open a new one if this happens ever again :)

**Comment by tyrosinase** [comment]
I haven't seen it again in pre-releases, though it may just mean I haven't apply-and-quit at the right wrong time.
