### ISSUE TITLE
Machine Does Not React To Trim Command

### ISSUE THREAD

**Issue by type8008** [inkstitch/inkstitch#1798]
Ive Tried So many Times to Get my Machine to Trim In Certain Places, But it never works, Only When it Needs to Switch Colors Does It work.

**Comment by tyrosinase** [comment]
Some machines don't honor trim intra-color commands. My Brother PE800 is capable of trimming, but will only do it at the end of a color. Doesn't matter what the stitch file says.

It's a little frustrating, but my Janome does trim threads and most of the time it's overrated.

**Comment by type8008** [comment]
Yes but if it can trim at the end of a color can’t the script be written to trick the machine like it is the end of a color?

Thank You!!



On Aug 22, 2022, at 9:03 PM, Tyrosinase ***@***.***> wrote:

﻿

Some machines don't honor trim intra-color commands. My Brother PE800 is capable of trimming, but will only do it at the end of a color. Doesn't matter what the stitch file says.

It's a little frustrating, but my Janome does trim threads and most of the time it's overrated.

**Comment by tyrosinase** [comment]
Well, I do it in my designs by changing colors. 😆

In theory someone could reverse-engineer the firmware to make it react to the design file differently, but aside from that, I don't think there's anything that could be put in the design file to force it to.

**Comment by lexelby** [comment]
Yes, the script could be written in such a way.  Unfortunately the machine would stop after every fake color change and wait for you to change colors and press the start button before it continued.  The fact is, most entry-level single-needle embroidery machines can't trim the thread _and start sewing again automatically_, which is really important for saving time.

You can get the "fake color change" behavior by using the "stop" command in place of trim, at least for some file formats.
