### ISSUE TITLE
Fill: AttributeError: 'LineString'

### ISSUE THREAD

**Issue by kraftykaters** [inkstitch/inkstitch#1802]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![SCS-Logo (1)](https://user-images.githubusercontent.com/112126559/186764168-558ec0d2-2482-4e70-8cbe-a6b282376693.svg)

**Comment by tyrosinase** [comment]
That looks like the same as #1794, and the same situation as I explain in this comment: https://github.com/inkstitch/inkstitch/issues/1794#issuecomment-1221362680

**Comment by kaalleen** [comment]
Closing in favor of #1742
