### ISSUE TITLE
Import font support

### ISSUE THREAD

**Issue by rishadencykh** [inkstitch/inkstitch#1805]
Hello, i was using ink stitch for few days now and first of all thanks to all those behind this project. I just want to know if there is any easy way to incluce ESA Fonts or BX Fonts to ink stitch and start using it dorectly? Like select a bx font and start typing and saving it to .jef format?

**Comment by kaalleen** [comment]
No, sorry there is not an easy way. Ink/Stitch has a lettering tool though which allows direct typing and saving to the format you need. But it doesn't read esa or bx fonts, but specifically generated svg files. Do you have a program to convert the single letters into embroidery format? If so, you could make them accessible for the lettering tool in Ink/Stitch afterwards (with a fixed size): https://inkstitch.org/docs/font-tools/#letters-to-font

If you are interested into an analysis of at least the bx format, a small insight can be found here: https://github.com/EmbroidePy/pyembroidery/issues/150

**Comment by rishadencykh** [comment]
Thanks for your response. Will check embroidepy
