### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by FolknThread** [inkstitch/inkstitch#1809]
I get this error with my design, in Inkscape 1.1.2 (b8e25be833, 2022-02-05) when trying to simulate the attached file

path92658: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

![bug](https://user-images.githubusercontent.com/112395905/187201882-9648a28d-f19e-4822-83f9-7d0e4a710d8d.svg)

**Comment by kaalleen** [comment]
Thank you for your error report. This error will be fixed in a future version.

The build of the branch were it has been fixed is currently broken. Once we've updated it, I can lead you to a dev version which will be working properly with your file.

**Comment by kaalleen** [comment]
Closing in favor of #1829
