### ISSUE TITLE
osx - guided fill: repair_multiple_parallel_offset_curves - ValueError

### ISSUE THREAD

**Issue by Lady-Pink** [inkstitch/inkstitch#1811]
J'obtiens un message d'erreur alors que je veux faire un remplissage guidé

VOICI LE MESSAGE : 
 
path234: erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 566, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 677, in do_guided_fill
  File "lib/stitches/guided_fill.py", line 34, in guided_fill
  File "lib/stitches/guided_fill.py", line 240, in intersect_region_with_grating_guideline
  File "lib/stitches/guided_fill.py", line 196, in clean_offset_line
  File "lib/stitches/guided_fill.py", line 118, in repair_multiple_parallel_offset_curves
ValueError: max() arg is an empty sequence

VOICI LE FICHIER /
![dessin-1](https://user-images.githubusercontent.com/73549509/187542507-70cd96b3-c105-4f1c-89a1-38ce8141e69d.svg)

Merci
Francine

**Comment by kaalleen** [comment]
I think this has to do with the parallel offset error in shapely (version we have to use for macOS).
A workaround for now could be to change the strategy from parallel offset to copy.

**Comment by kaalleen** [comment]
> Right hand offsets are returned in the reverse direction of the original LineString or LineRing, while left side offsets flow in the same direction.

This is not true in the shapely version which we are using at the moment for macOS.

**Comment by kaalleen** [comment]
Closing. It should be working with the new release (v3.0.1) now. If not, it is worth a try to test same release with the build for older macOS systems. Please reopen a new issue if you are seeing this error again.
