### ISSUE TITLE
AttributeError: 'Point' object has no attribute 'geoms'

### ISSUE THREAD

**Issue by SkoZombie** [inkstitch/inkstitch#1816]
I can't preview my design and when I tried to trouble shoot it I get the message, I'll add the file

> Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.
> 
> If you'd like to help please
> - copy the entire error message below
> - save your SVG file and
> - create a new issue at https://github.com/inkstitch/inkstitch/issues
> 
> Include the error description and also (if possible) the svg file.
> 
> Ink/Stitch Version: v2.2.0 (windows)
> 
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 84, in <module>
>   File "inkex\base.py", line 231, in run
>   File "lib\extensions\troubleshoot.py", line 29, in effect
>   File "lib\elements\fill_stitch.py", line 321, in validation_errors
>   File "lib\elements\fill_stitch.py", line 274, in shape
> AttributeError: 'Point' object has no attribute 'geoms'

**Comment by SkoZombie** [comment]
![get_jacked_broken](https://user-images.githubusercontent.com/5300335/188827757-9e738a59-5e04-4bdc-ab85-2d1c05d62eb0.svg)

**Comment by SkoZombie** [comment]
Previewing the design also hangs, so it's a bit confusing from a UI/UX point of view as you don't know something has gone wrong.

I absolutely love this project btw, just wanted to share the bug to help fix things!

**Comment by tyrosinase** [comment]
I haven't seen the no-geoms thing on a Point before, but maybe try the dev version mentioned in #1742 and see if that fixes it like it does for Lines?

**Comment by kaalleen** [comment]
No, this won't fix it. Problem is `path18695` which is a circle with no radius. We didn't expect something like this. Thank you for your bug report. That was definitely helpful.

**Comment by SkoZombie** [comment]
@kaalleen I don't know how it happened, but glad I could help by triggering bugs!

I think one of the bigger issues might be that the preview window hangs if there's an error. I appreciate this might be part of the plugin architecture in inkscape but if there could be a warning like there is when there's a satin-ing error that would be super useful. This might be covered in another issue but may confuse some users is all :)

**Comment by MrMikeJ** [comment]
Hi, I am new to this. Just got pretty much same error (below).  Is a fix coming, or is there something I can do with the image to avoid the error?  Thanks in advance!   

File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

SVG image file: 

![Bush_Cheney_2000](https://user-images.githubusercontent.com/119086666/204066679-099309c3-1a1a-48bc-ab7b-9fadd3a86eb6.svg)

**Comment by MrMikeJ** [comment]
Hi again, Looks like you were actively working on 1727 and that solves my issue.  Thanks!  

Does it now have to go thru some steps to QA and release?  I didn't see any new version available to download for windows.

I'd be happy to try to test something if that will help. 

Please let me know and thanks.  

Mike.

**Comment by kaalleen** [comment]
This will be fixed in the next release. Right now I'm not sure to which branch I could point you to for testing.
To fix your issue, just remove "path142" from your document. You may also want to run Ink/Stitch > Troubleshoot > Cleanup document afterwards.

**Comment by kaalleen** [comment]
Here is a development release: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test
If you encounter any bugs, we'd love to hear about them :)
