### ISSUE TITLE
Convert Line to Satin fills path through centre

### ISSUE THREAD

**Issue by mcoms** [inkstitch/inkstitch#1819]
When I use the "Tools: Satin > Convert Line to Satin" feature and look at the simulator, the path is stitched as a lead in stitch, a series of jump stitches, and a lead out stitch, through the centre of the two lines, as opposed to a satin column. Adding more rungs manually doesn't help.

macOS 12.5.1
Inkscape 1.2.1_x86_64
Inkstitch inkstitch-v2.2.0-osx

![input](https://user-images.githubusercontent.com/517837/189479442-2752da84-8894-4541-a113-e238591faafc.svg)
![output](https://user-images.githubusercontent.com/517837/189479449-c401580e-0b27-4b6e-9046-28aa3ccc0037.svg)
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/517837/189479389-80cba6df-448f-4e8b-8d37-e1747b580a61.png">

With a more complex line, the effect is to "fill in" the shape:

![input2](https://user-images.githubusercontent.com/517837/189479771-6a04854b-a885-48cb-bb2c-49f6a2b4c7e6.svg)
![output2](https://user-images.githubusercontent.com/517837/189479774-ca5fa7bd-b21f-4436-bcd7-1ba1a5dbd516.svg)
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/517837/189479714-d2d21ba7-81a5-4b2b-9518-60389ae477ea.png">

[output2.pes.zip](https://github.com/inkstitch/inkstitch/files/9540140/output2.pes.zip)

**Comment by tyrosinase** [comment]
Shapely works differently than expected on a Mac, as was discovered in #1743, and one of the rails gets reversed. Selecting points on that rail with the node tool and doing a `Path > Reverse` is a workaround, and #1727 may fix it.

**Comment by mcoms** [comment]
Thanks @tyrosinase, that workaround solved the issue for me 🙂

Closing as duplicate of #1743.
