### ISSUE TITLE
Extension windows wont open on Mac OSMonterey 

### ISSUE THREAD

**Issue by JesusG31** [inkstitch/inkstitch#1821]
The extension seems to work but none of the windows will open like Params

**Comment by kaalleen** [comment]
None - or just params and lettering?

**Comment by JesusG31** [comment]
None. It spins for half a second and immediately stops and nothing happens

**Comment by kaalleen** [comment]
Ok, we will need more information to be able to help.

1. Which Inscape and Ink/Stitch versions are you using?
2. How did you install Ink/Stitch?
3. Which Mac do you have (processor: Intel or M1)?

**Comment by maureen771** [comment]
sam for me. 
I tried to install inkstitch on Mac Monterey.
I loaded the zip file but it directly decompress. I can't put all the files in the extensions as is it showed in the video for Mac.
please help me. 
I tried Every thing
<img width="2048" alt="Capture d’écran 2022-10-05 à 14 34 23" src="https://user-images.githubusercontent.com/115084561/194061332-7f03c36a-8bd1-4a10-ba3d-0bd41878c3da.png">
<img width="2048" alt="Capture d’écran 2022-10-05 à 14 35 05" src="https://user-images.githubusercontent.com/115084561/194061459-359a5e96-1afb-4c6a-826a-3a0137b2e50e.png">

<img width="2048" alt="Capture d’écran 2022-10-05 à 14 34 40" src="https://user-images.githubusercontent.com/115084561/194061389-446d0881-a37e-48f3-a9da-653a0b3fc994.png">

**Comment by kaalleen** [comment]
Closing, no further response.
