### ISSUE TITLE
Can't open Params: Error 29131. On Ubuntu 18.04.6

### ISSUE THREAD

**Issue by anneliseq48** [inkstitch/inkstitch#1823]
I'm running Ubuntu 18.04.6.

I downloaded and installed Inkscape from their website using terminal, and then an extension for Inkscape called Ink/Stitch. It's the extension that I'm having issues with. When I try to select 'Params' within Ink/Stitch I get this error:

[29131] Error loading Python lib '/opt/inkstitch/bin/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/inkstitch/bin/libpython3.8.so.1.0)

In my newbie (naive?) brain, I'm hoping if I found a way to get the 'GLIBC_2.29' that's 'not found' I might be able to get it working?

**Comment by tyrosinase** [comment]
Kiiiiiiiiind of? You really don't want to mess with the system glibc unless you know what you're doing, and so far the two of us that have had installs with older glibc solved the problem the brute-force way: upgrading to a newer OS version. #1537 is where we talked about it, FWIW.

**Comment by anneliseq48** [comment]
I did see your comment thread eventually (thank you) and was wondering why I was running an older version and hadn't already upgraded... turns out I'm getting a bunch of errors trying to do the upgrade now. Just gonna do a clean wipe and reinstall at this stage. Thanks!

**Comment by tyrosinase** [comment]
That's what I did, mostly because my OS had originally been installed in 2004 and had gone through a lot of upgrades and different hardware and was, shall we say, a bit crufty.
