### ISSUE TITLE
contour_fill: TopologicalError

### ISSUE THREAD

**Issue by adolan648** [inkstitch/inkstitch#1826]
path455: error: Error during autofill!  This means that there is a problem with Ink/Stitch.
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x2C1826B8>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 43.148654026600703 175.64633973223178
shapely.geos - INFO - Self-intersection at or near point 43.148654026600703 175.64633973223178

**Comment by tyrosinase** [comment]
This looks like the same as #1820 / https://github.com/inkstitch/inkstitch/issues/1807 / https://github.com/inkstitch/inkstitch/issues/1795 / https://github.com/inkstitch/inkstitch/issues/1789 / https://github.com/inkstitch/inkstitch/issues/1785, but I'm not seeing any answers in those issues. Could be one of the devs will have a better answer, but also it looks like some of the issues are still looking for example files. You can upload the SVG here, or email it to [send-us-files@inkstitch.org](mailto:send-us-files@inkstitch.org).

You can possibly work around it with `Extensions > Ink/Stitch > Tools: Fill > Break Apart Fill Objects` if you haven't tried that already.

**Comment by kaalleen** [comment]
Closing this in favor of #1916
