### ISSUE TITLE
fill: ZeroDivisionError

### ISSUE THREAD

**Issue by trenshaw** [inkstitch/inkstitch#1829]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment]
There is a dev release that will fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01) but it's being triggered by a too-small or too-thin piece in your SVG - often a traced bitmap in need of cleanup.

**Comment by kaalleen** [comment]
It often helps to use Extensions > Ink/Stitch > Troubleshoot > Cleanup Document 
This will remove small elements fromt he document - so you don't have to search for them by hand.

**Comment by pgcudahy** [comment]
Hi, I'm experiencing this error but the mentioned dev release is no longer available. Could you please point me to a new one?

**Comment by kaalleen** [comment]
Interesting, I didn't know the dev builds will be removed.
Here is a more recent build to test with: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-daniels-build
