### ISSUE TITLE
Some file formats export with no/not enough colors

### ISSUE THREAD

**Issue by jonnierose** [inkstitch/inkstitch#1830]
Hi all. So with some of the svgs I created, when I save a copy of them as a zip file or an individual embroidery file format, the resulting file/s does not  include both colors. I.e. visually it will be one color and only one color will be listed for some formats. dst. , exp. , jef., and xxx. formats tend to work, pes., vp3., pec., uo1 do not. Multiple different file readers show the broken color. I have tried changing the colors to ones I know all the formats can read, to no avail. I've screwed around with the troubleshooting features, messed with params, layers, nada. Recent reinstall of Ink/Stitch was not the fix. 
I've been having this issue for like two weeks and cannot for the life of me figure out the cause. Some files I make come out fine with no discernable differences to the broken ones. Can someone sanity check me I am losing my mind.
[another not working.zip](https://github.com/inkstitch/inkstitch/files/9636596/another.not.working.zip)
[broken pumpkin.zip](https://github.com/inkstitch/inkstitch/files/9636597/broken.pumpkin.zip)
[working colors.zip](https://github.com/inkstitch/inkstitch/files/9636598/working.colors.zip)
[Working Pumpkin.zip](https://github.com/inkstitch/inkstitch/files/9636599/Working.Pumpkin.zip)

**Comment by kaalleen** [comment]
Thank you for bringing this to our attention and all the files to play with. The problem here is the stop command which removes the following color (as it seems).

I'm not sure how to fix this best @lexelby . This could either be fixed in pyembroidery (EmbEncoder) or Ink/Stitch (by adding a color change after a stop command).

**Comment by lexelby** [comment]
Oh interesting!  I didn't think of the possibility of specifying a STOP command but actually intending a color change.  Yeah, we should fix this in Ink/Stitch, not PyEmbroidery.  I'll comment on the PR.
