### ISSUE TITLE
inkstitch params don't show anything when clicked

### ISSUE THREAD

**Issue by opya** [inkstitch/inkstitch#1835]
Hi first of all thank you for this excellent software. I'm trying to run the Inkscape version `Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)` and Inkstitch version 2.2.0 on Ubuntu 22.04, but each time I click on `Params` menu nothing happens, the same is true for button `Lettering`. `Ink/Stitch/Visualise and export/Simulator / Realistic preview` is working. Please tell me if you need more info.

**Inkscape version**: `Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d)`
**Inkstitch version**: 2.2.0
**OS version**: Ubuntu 22.04
**Python version**: Python 3.10.6

**Comment by kaalleen** [comment]
Do you have the snap version of Inkscape installed? If so, this could be a reason for your trouble.
You may want to try their ppa instead: https://inkscape.org/release/inkscape-1.2.1/gnulinux/ubuntu/ppa/dl/

**Comment by opya** [comment]
thank you for your response @kaalleen, forgot to mention that Inkscape was installed after adding the above ppa

**Comment by kaalleen** [comment]
Oh ok, that's not good news for us. But your issue is reproducable with your ubuntu version and we'll work on a fix.
Until then you may want to downgrade to an older Ink/Stitch version: https://github.com/inkstitch/inkstitch/releases/tag/v2.1.2

**Comment by opya** [comment]
Thank you @kaalleen `v2.1.2` i working as expected. I traced down to this dev release https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-pkg-inkscape-check which the last was working for me if this is any help to trace the problem. It's strange because the next one is this https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-typos which contains only a typo fix and `Params` button stopped working.

**Comment by kaalleen** [comment]
Thank you for your investigations. I think it could be wayland again. Have you tried the fix from the troubleshoothing section on our website?

https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds

In short:
Open Inkscape from the command line with the following command:

`export GDK_BACKEND=x11 && inkscape`

**Comment by opya** [comment]
this worked, thank you @kaalleen. Closing.
