### ISSUE TITLE
Trying to open "Params" causes crash on Ubuntu 22.04.

### ISSUE THREAD

**Issue by talljosh** [inkstitch/inkstitch#1845]
[Uploading inkstitch-crash.txt…]()
I'm running Ubuntu 22.04 using Inkscape from the Ubuntu repositories, which is Inkscape version 1.1.2. I have installed Ink/Stitch 2.2.0 from the official DEB package.

When I select Extensions > Ink/Stitch > Params, Inkscape freezes for a few seconds (including the spinner freezing), then presents the system "internal error" window. According to this window, there is some kind of crash in `/opt/inkstitch/bin/inkstitch`.

I have attached the (slightly redacted) crash file.

Needless to say, Ink/Stitch is very difficult to use when you can't edit stitching params.

**Comment by talljosh** [comment]
Here's the file, the upload seemed to work this time: [inkstitch-crash.txt](https://github.com/inkstitch/inkstitch/files/9711023/inkstitch-crash.txt)

`export GDK_BACKEND=x11` didn't help, it still crashes. However, when I download the Ink/Stitch repo (and install its Python dependencies) and link it as an Inkscape extension, I can open the Params dialog.

I don't know if it's related to this error, but system Python is 3.10 and the `requirements.txt` file does list a Python 3.8 linux wheel for wxPython.

**Comment by kaalleen** [comment]
Ink/Stitch releases bundle their python / python dependencies.
Sorry you didn't get any response earlier. Since this is referring to an outdated version I'll close the issue.
When you still have problems with the current installation, please feel free to open a new issue anytime.
