### ISSUE TITLE
Keyboard shortcuts do not work in latest Inkspace version 1.2.1

### ISSUE THREAD

**Issue by Martin-60** [inkstitch/inkstitch#1846]
Inkspace 1.2.1 64b / Windows 10 64b
Always going through the menu is not really good.... and disturbs the workflow.

![InkSpace-1 2 1 - Screenshot 2022-10-04 094249](https://user-images.githubusercontent.com/114981991/193763260-88e0b049-867e-421c-9637-c0b72d03e3a1.jpg)

Thank you.

**Comment by kaalleen** [comment]
Can you give us a little more detail about which exact keyboard shortcuts you are talking about?
Did you follow this instructions?
https://inkstitch.org/docs/customize/#download-and-import-custom-shortcut-keys

**Comment by Martin-60** [comment]
Yes - I do this according the instruction - I loaded the inkstitch.xml file from the web-side.  But nothing goes, for example:
Strg-Shift-P for the "Parameter" dialog window.
What I don't understand is that the InkSticht extension appears in the menu but is not displayed in the extension management. Could it be related to this?
![Extension-Menue-InkStitch-Screenshot 2022-10-04 224116](https://user-images.githubusercontent.com/114981991/193924090-7010dcfa-e637-4ef2-a475-8929d2921bb5.jpg)
![Install-Extension-Management-Screenshot 2022-10-04 223843](https://user-images.githubusercontent.com/114981991/193924123-dab58886-774a-49b3-a990-60905ee401de.jpg)

Thank you for your support.

**Comment by kaalleen** [comment]
No, that's not the reason. In the extension manager are only extensions listed which have been reviewed by the Inkscape team. Ink/Stitch is a bit too complex to ever be listed there.

Schau mal unter Bearbeiten > Einstellungen > Benutzeroberfläche > Tastenkürzel
Da kannst du dann nach "Parameter" suchen (unter Efffect). Wenn da kein Tastenkürzel vermerkt ist, dann hat der Import der Kürzeldatei nicht richtig funktioniert. Du kannst die Tastenkürzel aber auch manuell setzen. Dazu klickst du in das Feld unter Tastenkürzel direkt neben Parameter und tippst dann das Kürzel ein. Hilft das weiter?

**Comment by Martin-60** [comment]
Hallo Kaalleen,

Danke - das hat funktioniert, also manuell. Was mich wundert das sich jetzt ein zusätzlicher Eintrag "Parameter (keine Einstellung)" in der Auflistung findet - wenn der nicht benötigt wird - wie kann ich den wieder löschen?

Freundliche Grüße 
Martin

**Comment by kaalleen** [comment]
Das stört nicht und kann da bleiben - es war auch schon immer da. Alle Inkscape Erweiterungen kann man auf zwei Arten mit Tastenkürzeln aufrufen. Der Unterschied ist, dass einmal das Fenster mit den Einstellungen aufgerufen wird und das andere Mal ("keine Einstellungen") wird die Funktion einfach mit den zuletzt genutzten Einstellungen ausgeführt. Das funktioniert aber soweit ich weiß nur, wenn kein externes grafisches Interface genutzt wird - was bei den Ink/Stitch Parametern aber der Fall ist.
