### ISSUE TITLE
Issue simulating 

### ISSUE THREAD

**Issue by datrandomduggy** [inkstitch/inkstitch#1852]
Whenever I try to simulate the stich path it gets stuck on "rendering stich path" it just keeps loading but nothing happens inkscaoe itself also stops responding

**Comment by tyrosinase** [comment]
If you close the simulator it should show you the error it's getting - is that not happening?

**Comment by datrandomduggy** [comment]
If I close the simulator inkscape crashes

**Comment by tyrosinase** [comment]
Crashes as in throws an error, or crashes as in disappears?

What operating system are you using?

**Comment by datrandomduggy** [comment]
I'm using windows and I get the popup saying "inkscape has stopped responding"

**Comment by datrandomduggy** [comment]
hey, so i actually figured it out, turns out the issue was my image was just waaay to large when i scaled it down to a more reasonable size it ended up working just fine

**Comment by tyrosinase** [comment]
Ah, that'll do it; gigantic fills do take a long time and Windows probably got concerned.

I think there's an Electron-related simulator overhaul in the works; I will have to remember to try out absurdly large fills when I'm trying to find ways to break it in future. Thanks!
