### ISSUE TITLE
Install issue Mac

### ISSUE THREAD

**Issue by Frankyboy5** [inkstitch/inkstitch#1855]
Hi,

I'm excited to get started using Inkstitch... but I'm having a bit off trouble Installing the plugin.
Maybe/hopefully someone can help me get started.

I have a Mac (i7) with Monterey 12.5.1
I have installed Inkscape 1.2.1
I attached a 'word' file with the error message/code

[frozen importlib.docx](https://github.com/inkstitch/inkstitch/files/9742281/frozen.importlib.docx)

I also downloaded the ZIP file, unpacked it, an hit the unpacked file... then it looks like It's going to startup something and it shots down by it's self.

Thanks in advanced.

Frank

**Comment by kaalleen** [comment]
Delete previously downloaded Ink/Stitch files and try to follow the installation description from our website: https://inkstitch.org/docs/install-macos/

We provide a pkg installer for Ink/Stitch. No need to download the zip file and unpack it manually.

**Comment by Frankyboy5** [comment]
First of all, thanks for the quick reply.
I deleted the downloaded Ink/Stitch file, and tried it again with your link. Still the same result.

**Comment by kaalleen** [comment]
Can you describe the steps you did before the error message is popping up? The message is send by Inkscapes extensions manager - which shouldn't be interacting with Ink/Stitch. That is what is confusing about your error message.

**Comment by Frankyboy5** [comment]
Yes I can...
I download inkstitch-v2.2.0-osx.pkg
I start-up Ink scape
I double click, select My harddrive to instal on, Hit 'Install'
Than the installer is doing his thing, untill i get a pop-up with the following text and a 'Okay' button:
'Ink/Stich is an Inkscape plugin. Please install and run Inkscape before installing Ink/Stitch.' 
I hit the ' Okay' button... And then I get the message in 'installation failed'

I've also tried this proces while Inkscape is not launched (just for testing things out) same result.

**Comment by Frankyboy5** [comment]
Anybody maybe any ideas how to fix this issue? please?

**Comment by Frankyboy5** [comment]
I found out why it didn't install...
If I download a program, I always move them to a specific folder/location. 
So Inkscape was not in my 'apps' folder at the moment that I was trying to install Ink/stitch.
I now moved Inkscape back to the standard 'Apps' folder and the installation was successful.

**Comment by kaalleen** [comment]
Sorry for answering (too) late, I've been so busy this week. But glad you found your way through it. Not sure if I had thought of that. So, thank you for your feedback. It may be helpful to others too.

**Comment by kaalleen** [comment]
In order to create the extensions folder it is important, that Inkscape has been running BEFORE the installation (at least once) - but not during the installation. We maybe should update that error message. It's not very clear as it seems.
