### ISSUE TITLE
error occurred while renaming file 

### ISSUE THREAD

**Issue by melleo17** [inkstitch/inkstitch#1861]
I have tried several times to install ink stitch.  the first 2 times it loaded but would and I could select params but nothing would happen.  I uninstalled and have reinstalled but now getting this error message

![Capture](https://user-images.githubusercontent.com/115805849/195879348-c2c21cc7-da12-4c99-becf-a4261d6dbbec.JPG)

I also uninstalled inkscape and reinstalled it.  Please advise what to do to get past this MoveFile failed. Code 5
Thanks

**Comment by kaalleen** [comment]
Could you try to restart your computer and start the installation again - without opening Inkscape beforehand.

**Comment by melleo17** [comment]
I did this and it did install this time.  However, my Webroot says it detected malware and removed threat.  I can’t find the details on it though.  Maybe it is keeping file from loading?  Have others had this problem?  I opened Inkscape, drew a circle, chose object to path.  Went to extensions, ink/stitch, Params but nothing happens. Am I missing something?
Thanks for help!

**Comment by kaalleen** [comment]
Sorry that there hasn't been any further response from our side. I hope you could solve your issue. Ink/Stitch has released a new version (v3.0.1). When you can't install that one neither, please reopen a new issue.
