### ISSUE TITLE
Satins and double points

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1868]
More of a comment than a question, but:

I wasn't ready to put rungs on this shape yet so I just went "eh, I'll just break that point and join the resulting two with a segment for now so there's an even number for the satin and it won't complain" and it had an interesting effect.

That's the stitch plan with it there:

![image](https://user-images.githubusercontent.com/9473609/196551634-78b1c613-995d-4b90-853a-a378f2d036e9.png)

Not sure if anything actually needs done with this, since it's not likely to come up in a real shape, but I'm gonna throw it out there so we know what it looks like if someone has a weird result.

**Comment by kaalleen** [comment]
Thanks. Interesting to see. But yes, I don't think we need to take action on this.
I'll close the issue and hope we remember it when it comes up :)

**Comment by tyrosinase** [comment]
Oh, I forgot I had made this post. It actually does come up fairly often, when an inside curve has nodes/rung intersections too close to each other (such that when the stitch leaves one, it lands past the next one or even two when it comes back to that rail). Instead of doing short stitches to fill the space, it just skips past the whole thing.

The problem there is: rungs won't necessarily fix it. It's almost always an indication that some more rail tweaking needs done (as in the above example) but if Troubleshooting can detect it, it should maybe gives some hints.
