### ISSUE TITLE
autofill division by zero

### ISSUE THREAD

**Issue by SkoZombie** [inkstitch/inkstitch#1876]
I was trying to generate some oktoberfest style badges and managed to trigger a division by zero bug.

I had a look in the XML/ SVG and couldn't see anything obviously wrong.

Also, as with other crash bugs, the stitch preview window would just hang, so there's no feedback to the user that there's been a crash. I noticed as it was taking too long, and then when reproducing just watched my CPU to know when it had crashed.

The bug:
```
path8335: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (linux)


Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

```
The file:
![oktoberfest](https://user-images.githubusercontent.com/5300335/197502455-e5e48d36-c8fa-4329-83e0-aeb7af48ffbb.svg)

I'm running inkstitch 2.2.0 and Inkscape 1.2

**Comment by tyrosinase** [comment]
There is a dev release that will fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr https://github.com/inkstitch/inkstitch/pull/1727) but it's being triggered by a too-small or too-thin piece in your SVG. You can use `Extensions > Ink/Stitch > Troubleshoot > Cleanup Document` and that will generally find them for you.

**Comment by SkoZombie** [comment]
Hi @tyrosinase I can confirm the dev release you linked does fix this. Unfortunately Cleanup Document didn't help in this instance. 

I'm not sure on etiquette here, but happy to close the task as it's fixed by that PR.

**Comment by tyrosinase** [comment]
Yep, sometimes it's not so much a tiny object as a problem in a corner, depending on how those diamonds were generated/clipped, and Cleanup doesn't always pick up on those.

Glad it worked for you!
