### ISSUE TITLE
Issue when creating custom lettering

### ISSUE THREAD

**Issue by justandywu** [inkstitch/inkstitch#1880]
Hello! I've been trying to create a custom font for lettering, and I was trying to follow Project Anonymous' video: https://www.youtube.com/watch?v=KaUnlS-kW90

and this tutorial here: https://inkstitch.org/tutorials/font-creation/

I didn't do all the glyphs, but just a few, and I wanted to test if it was working and I got back this when I tried to select my font in lettering. 

I have no idea what to do, or how to interpret this and debug it. 

Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 328, in apply
  File "lib\extensions\lettering.py", line 273, in update_lettering
  File "lib\lettering\font.py", line 184, in render_text
  File "lib\lettering\font.py", line 106, in _load_variants
  File "lib\lettering\font_variant.py", line 60, in __init__
  File "lib\lettering\font_variant.py", line 72, in _load_glyphs
  File "lib\lettering\glyph.py", line 40, in __init__
  File "lib\lettering\glyph.py", line 86, in _process_bbox
  File "lib\lettering\glyph.py", line 86, in <listcomp>
AttributeError: 'NoneType' object has no attribute 'left'

![image](https://user-images.githubusercontent.com/8253155/198481145-6e793be3-6b7d-4782-a427-d8ef519eadcd.png)

Send help please!

**Comment by kaalleen** [comment]
Thank you for your error report. To analyze the problem, it would be very helpful to see your font file. Would you mind to post it here - or in case you cannot post it publicly, you could also upload it here: https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES ?

**Comment by justandywu** [comment]
I uploaded my svg file as issue1880-justandywu.svg.

I mainly only worked on the letters in hoodie.

**Comment by kaalleen** [comment]
Thank you for the file. The two last glyphs layers each have one path object with an empty d attribute. If you delete them, you should be fine.

**Comment by justandywu** [comment]
Hi @kaalleen 

Sorry I tried to fix some more things, but I ended up breaking more things. :(

I'm trying to generate JSON and for some reason I'm getting this error:

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\lettering_generate_json.py", line 84, in effect
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Inkscape\\etc\\custom fonts\\obviouscompanyembroidery\\font.json'


I also tried to remake the glyph file, but now it's having a different issue...  but now I can't generate the JSON

I don't know if this is something that you do, but is there a way to get on a call to troubleshoot? Otherwise we can just interact vs this
