### ISSUE TITLE
(Contour) Line to Satin - strange result, what am I doing wrong?

### ISSUE THREAD

**Issue by pandel** [inkstitch/inkstitch#1888]
Hi!

I am a beginner with Inkstitch and am loving it so far. As I am still learning, I tried to convert the outline of a shape into a satin stitch via "Line to Satin". The result that Inkscape shows seems reasonable, but if I open Inkstitch Params it gets weird.

First I did not combine the resulting paths and this is what was happening:

![Bildschirmfoto 2022-11-02 um 14 08 53](https://user-images.githubusercontent.com/12460002/199498529-a9d21e89-8242-4d40-8717-9ca29092a209.jpg)
![Bildschirmfoto 2022-11-02 um 14 05 22](https://user-images.githubusercontent.com/12460002/199498545-8e962b8c-517b-42d0-bbc2-c9a6c81206e4.jpg)
![Bildschirmfoto 2022-11-02 um 14 05 50](https://user-images.githubusercontent.com/12460002/199498565-dfc5019f-14ad-415d-9523-2adb47150478.jpg)

The second time, I first selected the two paths (named `path1` and `path2` in screenshot) and first combined them before trying to open `Params`. This time I only got the following message:

`Satin column: A rung intersects a rail more than once. Each rung should intersect both rails once.`

You might have seen the two rails crossing each other at the open end on the bottom left of the contour (see second screenshot). At first I thought, "... ok, it is rails crossing, not rungs, so what...", but I learned that this was the cause of the error. Sadly, after `Params` opened successfully, the result is the same as in the third screenshot. I absolutely don't understand what is going on here...

I am using:
macOS Monterey 12.6.1 / Intel machine
InkScape 1.2.1
Inkstitch 2.2.0

Can someone help me please? I can provide the SVG if someone wants to try what I did...

**Comment by pandel** [comment]
Ok, question: is it correct, that if I only remove the fill color of an object, the object is still being interpreted as if it was there? Then it could explain, what is happening here.

I hoped that I could remove the fill of a shape only leaving the contour and convert that contour to a satin. Seems as if this is not as easy as I thought...

**Comment by pandel** [comment]
After having seen this video (https://www.youtube.com/watch?v=9vjP3Nq3yTQ) I noticed that my Mac has the same problem with reversed rail lines.

Maybe you could show up a hint regarding this Mac/reversed rails problem on the homepage or under common issues.

For now I know how to fix it.

**Comment by lexelby** [comment]
Hi!  Sorry you got caught up by this bug.  We consider it a bug, and we plan to fix it by automatically reversing one of the rails if needed.  That will be in the next version.
