### ISSUE TITLE
Development version lexelby-smoothing does not run - missing so

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#1893]
When trying to call "Params":

ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
[15222] Failed to execute script 'inkstitch' due to unhandled exception!
![Bildschirmfoto vom 2022-11-05 12-57-35](https://user-images.githubusercontent.com/17491743/200118891-e3c045bc-b0f4-4f06-9969-1ee3da6725c9.png)

Claudines addrandom is still running fine!

**Comment by kaalleen** [comment]
Should be fixed
