### ISSUE TITLE
Load Params Present or set default in command line

### ISSUE THREAD

**Issue by zaka221** [inkstitch/inkstitch#1900]
Hi.
I have like 28k designs in svg. I write simple script in php to export svg>pes

**shell_exec('inkscape --export-width=100 --export-height=100 --export-type=pes --export-filename="'.$outputFilePath.'" "'.$inputFilePath.'"');**
And my question, is there a way load parm in CMD or set default, so i don't have to load my custom parm every time i close and open inkscape.
Thanks

**Comment by kaalleen** [comment]
No sorry, unfortunately there is no saving your default params yet - but it's definitely a future plan.

**Comment by kaalleen** [comment]
Closing in favor of #1069
