### ISSUE TITLE
Is there a download for Mac Ventura?

### ISSUE THREAD

**Issue by Gdiddy22** [inkstitch/inkstitch#1906]
trying to download the most recent version of the software. i was able to run inkscape. no luck running inkstitch on my current version of Mac ventura. it downloads fine but won"t convert to a file like tutorial videos i have watched said it would. I"m not able to drag the software into the inscape extensions folder.

**Comment by kaalleen** [comment]
The latest release should be working. But it seems as if you are following an outdated video tutorial.
We have install instructions on our website: https://inkstitch.org/docs/install-macos/
Get the version for monterey / big sur

**Comment by kaalleen** [comment]
Please not that on the Inkscape website there is the following warning for macOS users. I don't know which specific mouse events could cause problems.

```
Note for macOS users:

Do not update to macOS Ventura if you rely on Inkscape! There is an unresolved issue that currently affects all GTK3 based apps on macOS Ventura, making the app unresponsive to certain mouse events. (GTK is used by many different programs, and builds those programs' user interfaces for you to interact with.)
```

Were you succcessful with you installation?

**Comment by kaalleen** [comment]
No respond. Closing. Please open a new iussue if you are still having troubles to run Ink/Stitch.

**Comment by TracyD-66** [comment]
I am running Ventura and I can't get Live Path effects on my extensions. Can someone assist me with this?
