### ISSUE TITLE
gap between fill and borders

### ISSUE THREAD

**Issue by lelesi87** [inkstitch/inkstitch#1919]
Hello everyone,
I just started drawing on inkstitch for my mother, who is a old fashion seamstress of 60 years.

She was buying pes file and I decided to start looking into it to help her and spend some time together.

I've a problem with shape and borders... I fill a shape (without border) and then I create satin from lines  for the border.
In inkscape (inkstitch extention) the realistic preview is always perfect, but when  she goes and stitch it... the result is poor.

We actually have always gap bewteen fill and  the satin border.

Any suggestion ? :(

![WhatsApp Image 2022-11-19 at 17 22 11](https://user-images.githubusercontent.com/119076732/204045247-18c56b8b-4056-4c90-b5e6-f159615045f2.jpeg)
![WhatsApp Image 2022-11-23 at 19 05 47](https://user-images.githubusercontent.com/119076732/204045254-1535b689-525b-4f52-ba88-b39ea7671f88.jpeg)

**Comment by george-steel** [comment]
It looks like your stabalizer might be hooped too loosely. Try tigtening it before stitching.

**Comment by kaalleen** [comment]
Yes, this is coming from the thread pulling the fabric together: https://inkstitch.org/tutorials/push-pull-compensation/

You can work with different stitch angles to compensate a little, but you will also need to adapt your fill shape a little. Maybe also a better stabilizer can help to improve the stitch out.

If you want further improvement, also consider to turn the borders into a satin stitch.

**Comment by lelesi87** [comment]
> Yes, this is coming from the thread pulling the fabric together: https://inkstitch.org/tutorials/push-pull-compensation/
> 
> You can work with different stitch angles to compensate a little, but you will also need to adapt your fill shape a little. Maybe also a better stabilizer can help to improve the stitch out.
> 
> If you want further improvement, also consider to turn the borders into a satin stitch.

thank you  kaalleen for your reply!
Normally borders are already converted in satin.
is it possible that decreasing the density of the stitches , the gap is lighter?

**Comment by kaalleen** [comment]
> Normally borders are already converted in satin.

Your borders do really look like a fill stitch.

> is it possible that decreasing the density of the stitches , the gap is lighter?

It could help a little, but your gap is quiet big. I think you will have to adapt your elements shape as well. Sometimes it looks weired on screen, but you have to adapt to your stitch out. Pull the nodes of your shapes outward to fill the gap. Doesn't matter if they are overlapping with the border. I'm sure a future Ink/Stitch version will have a setting for pull compensation, but until then you'll have to change your shape manually.

Check if your hooping and stabilizers are ok and don't be afraid to experiment with stitch settings. You will learn a lot from that for later designs.

**Comment by lelesi87** [comment]
> > Normally borders are already converted in satin.
> 
> Your borders do really look like a fill stitch.
> 
Argh... I Always do convert lines in satin. I'll try to attaché picture of how It looks like on inkstitch.
Maybe the result Is poor because the size of the drawing Is very Little (2inch X 1.5inch)

> > is it possible that decreasing the density of the stitches , the gap is lighter?
> 

> It could help a little, but your gap is quiet big. I think you will have to adapt your elements shape as well. Sometimes it looks weired on screen, but you have to adapt to your stitch out. Pull the nodes of your shapes outward to fill the gap. Doesn't matter if they are overlapping with the border. I'm sure a future Ink/Stitch version will have a setting for pull compensation, but until then you'll have to change your shape manually.
> 

It Is so obviuos but i never tought about that !! Thank you, i'll try to play with shapes...

> Check if your hooping and stabilizers are ok and don't be afraid to experiment with stitch settings. You will learn a lot from that for later designs.

Okok... I Will try and come back to you with the result !

Have a great weekend !!!
