### ISSUE TITLE
Use marker instead of guides for origin

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#192]
In https://github.com/lexelby/inkstitch/issues/20#issuecomment-395492965, I had the idea of using Inkscape's Symbols tool together with the Connections tool to add command markers that Ink/Stitch can see.

We could use the same technique for the embroidery origin.  Instead of having to set up two guides and name them properly, one could just drag an icon to the right spot.  It'd be much easier from the user's perspective.

There's also a pretty good reason to do this from a code perspective.  The code involved in parsing the guides is pretty horrible, due to one or two bugs in how Inkscape includes the guides in the SVG.  I'd really love to be able to get rid of that code.

How would people feel about replacing the guides?

**Comment by X3msnake** [comment]
Go for it

**Comment by wwderw** [comment]
Go for it.

Would this method be better also for the custom stop in #124?

**Comment by lexelby** [comment]
Yeah, it definitely would.  Great idea.
