### ISSUE TITLE
Small canvas issues

### ISSUE THREAD

**Issue by SulliNeedsHelp** [inkstitch/inkstitch#1920]
It seems as if I’m the only person on earth experiencing this issue, I can’t find answers anywhere. When creating a design on a large canvas (200x200) params does what it’s supposed to do. However, working on a 3x4 or 4x4 canvas like what my embroidery machine needs, params does not do what it’s supposed to. The stitches are super thick, nothing is filled in properly, and it’s a huge mess. If someone knows how to fix this please let me know. Thank you!!

**Comment by tyrosinase** [comment]
What units is your canvas in?

**Comment by SulliNeedsHelp** [comment]
> What units is your canvas in?

Mm

**Comment by tyrosinase** [comment]
A "4x4" machine is usually 100mm x 100mm.

https://silverseams.com/embroidery-patterns/basting-boxes/index.html has a file that will put the canvas right in your preset page sizes.

**Comment by SulliNeedsHelp** [comment]
> A "4x4" machine is usually 100mm x 100mm.
> 
> https://silverseams.com/embroidery-patterns/basting-boxes/index.html has a file that will put the canvas right in your preset page sizes.

Thank you so much!!!!!! It worked :) I really appreciate it
