### ISSUE TITLE
Help with ink/stich not filling part of the design

### ISSUE THREAD

**Issue by alexsl2174** [inkstitch/inkstitch#1928]
Hi I have an issue with my ferret patch im trying to produce. So every color are put into path all are associated with a color in the botom. But when I come to look at the preview in the visualizer it skip two paw. Im not sure why since every other time this color is use in the design it does show on the visualizer.

![image](https://user-images.githubusercontent.com/79280782/204287359-a63a43c6-89d2-4d8b-88ad-04ba47ba70b6.png)
![image](https://user-images.githubusercontent.com/79280782/204287607-4abd34bf-27a9-420f-8faf-361de5ba8df4.png)
![practice 8](https://user-images.githubusercontent.com/79280782/204287667-dbc8e545-4302-4fb1-be1a-c28204ec0690.svg)

**Comment by kaalleen** [comment]
When Ink/Stitch is not able to render a fill correctly, it will fallback to an outline. This means, when you have an issue like that, you have to watch out for edges that are not clean or very small. Sometimes the Ink/Stitch Troubleshoot extension helps you with finding those spots. Here it is were you can find troublesome places in your svg:

![1926](https://user-images.githubusercontent.com/36401965/204337540-5e3d664f-80f3-46b1-b6a2-c66d17b52a95.png)

Consider to turn the black outline into satin stitches and also to not cut out every little part of the fill were the border is on top. Sometimes the stitch count will be even smaller when you don't.

**Comment by alexsl2174** [comment]
Hello my artist sent a revise version would this be better ?

**Comment by tyrosinase** [comment]
Sending your artist to https://silverseams.com/tutorials/digitizing-outlined-graphics/ so they can see what the requirements are for a design being more easily digitized may help.

**Comment by alexsl2174** [comment]
OK i had a chance to rework on the project yesterday and the simulation went great. Altough I still got a problem when i got to my machine to try to sew it. It said that the project was too large even tough it isnt. My hoop is curently a 4x4 hoop and i set my project for a 4x4 and so in inch it mesure 3.46in by 3.97in what am I suppose to do ?

**Comment by tyrosinase** [comment]
A "4x4" machine is usually 100mm x 100mm (some, particularly older ones, are ~98mm in one dimension).

There are pre-set page definitions at https://silverseams.com/embroidery-patterns/basting-boxes/ though that won't constrain Ink/Stitch.

And the Inkscape measurement of a design isn't the same as the stitch measurement, because Inkscape will count the width of the lines where the machine only cares about where the needle strikes - so if all your lines are 2mm wide, a 100mm basting box will be 102mm square to Inkscape but the machine will accept it because the needle hits at 0,0 and 100,100 and so forth.

All of which is to say, if you select the entire image, lock the proportions, and set the largest dimension to 100mm, it should be safely within the machine's maximum.

**Comment by schnoberts1** [comment]
Can Ink/Stitch log when this happens, perhaps with the name of the relevant layer from Inkscape?

**Comment by tyrosinase** [comment]
Getting the machine to agree with what colors are in the file is always an adventure.

Ink/Stitch comes with a palette that is the Brother thread colors. If you re-color your image using those, it should come across correctly, I think.

I have a custom palette that is my jumble of Sulky, Brother, and Madeira, so they don't come over to either machine correctly,I just go by the sequence number.You can print out the PDF version (or just bring it up on the screen if your computer is close enough) and match the sequence up to the thread number.

Oh, one more unrelated thing about Brothers and thread numbers: there's a bug in Brother firmware that certain colors in embroidery mode will cause it to display it as a sewing-mode stitch type. It's hard to explain, but don't panic if it shows a zigzag stitch for a particular pink, or a scissors mark for another color. It'll stitch normally, it's just the display. It shows the same thing even on embroidery-only machines.

**Comment by alexsl2174** [comment]
> Getting the machine to agree with what colors are in the file is always an adventure.
> 
> Ink/Stitch comes with a palette that is the Brother thread colors. If you re-color your image using those, it should come across correctly, I think.
> 
> I have a custom palette that is my jumble of Sulky, Brother, and Madeira, so they don't come over to either machine correctly,I just go by the sequence number.You can print out the PDF version (or just bring it up on the screen if your computer is close enough) and match the sequence up to the thread number.
> 
> Oh, one more unrelated thing about Brothers and thread numbers: there's a bug in Brother firmware that certain colors in embroidery mode will cause it to display it as a sewing-mode stitch type. It's hard to explain, but don't panic if it shows a zigzag stitch for a particular pink, or a scissors mark for another color. It'll stitch normally, it's just the display. It shows the same thing even on embroidery-only machines.


Thank ! Still being embroidered and it look great altough my brown was definitely not the right one on the tail it look great !

https://user-images.githubusercontent.com/79280782/205303300-488c75f7-cb74-4b39-90ba-9dc9f2aef17a.mp4

**Comment by tyrosinase** [comment]
Your patch will look much better if you convert those black outlines to satin (https://silverseams.com/tutorials/digitizing-outlined-graphics/) - you'll also want to change the angles of all those fills to help with pull compensation, and you'll definitely need to use stabilizer and a very stable fabric for patches.

You also have to be very careful about restarting after a "train wreck" - make sure the hoop re-calibrates because it can get knocked out of alignment and it won't know it (that's why it always returns to full zero when you power it on: that's the only position it can detect). I can't remember offhand how to make Brothers re-zero in the middle of a design, but you can always power down, wait fifteen seconds or more, and power back on and let it resume.

**Comment by alexsl2174** [comment]
Hi so you said to convert the black outline to satin stich and i agree from what i understood from a tutorial i watched the other day you do that by isolating those black in another layer than those that are suppose to be the fill color. Ill definitely look at you website after work. As for angle of fill i try to do that in some of the place mostly you should see in the ball there is 45° and -45° and others. For the fabric it was a upholstery fabric that is fairly sturdy and yes i did add stabilizer.I just finish reading...so actually i wish i would have power it down as soon as i realised it offset because i didnt know what to do to get it realignedOn Dec. 2, 2022 1:24 p.m., Tyrosinase ***@***.***> wrote:
Your patch will look much better if you convert those black outlines to satin (https://silverseams.com/tutorials/digitizing-outlined-graphics/) - you'll also want to change the angles of all those fills to help with pull compensation, and you'll definitely need to use stabilizer and a very stable fabric for patches.
You also have to be very careful about restarting after a "train wreck" - make sure the hoop re-calibrates because it can get knocked out of alignment and it won't know it (that's why it always returns to full zero when you power it on: that's the only position it can detect). I can't remember offhand how to make Brothers re-zero in the middle of a design, but you can always power down, wait fifteen seconds or more, and power back on and let it resume.

**Comment by tyrosinase** [comment]
Just putting it in a different layer won't convert it to satin. That'll group the colors, though (I almost always separate my colors into layers). What you're showing in that picture above is definitely still fill-stitch.

**Comment by alexsl2174** [comment]
Dont worry i believe you im just saying thats what i saw in a youtube tutorial. Do you think that because i use polyester thread (gutterman and other) other than specific thread for embroidery that it matter ? Also my needle was a universal schmetz but i have bought embroidery needle schmetz 90/14 the other day so i can switch since i still dont know why everything went wrong this morning On Dec. 2, 2022 3:43 p.m., Tyrosinase ***@***.***> wrote:
Just putting it in a different layer won't convert it to satin. That'll group the colors, though (I almost always separate my colors into layers). What you're showing in that picture above is definitely still fill-stitch.

**Comment by tyrosinase** [comment]
That can make a difference, yep. I generally use 75/11's, but a 90/14 should be fine. Slower machines like Brothers are very very forgiving of different thread weights; I went through almost an entire box of bobbins and only realized when I went to re-order that they were 60wt when the Brother wanted 90 (or the other way around? I always have to look it up). Proper embroidery thread will give you more sheen (rayon even more than poly) but I've run a fair amount of regular sewing thread, even 100% cotton (it's UV-reactive!), and having the right weight/needle size for the density will give you smoother coverage.

(Someone around here is probably an expert on tuning the fill and satin densities for different thread weights and needle gauges, but that is not me.)

**Comment by alexsl2174** [comment]
OK in that case i’ll switch to the embroidery needle but i’m not sure either way why is it that it kept just falling every say.... 30 minutes of sewing (again that needle was the universal 90/14)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by alexsl2174** [comment]
Hello im back and about to be ready to finally try another design (TLDR lost my embroidery needle i had just bought because i hapen to recycle them since ive put them in the box of my new embroidery machine wich i recycle)

I just wanted to make sure that i woudnt get streaky line when embroidered because that woudnt be too cute

![image](https://user-images.githubusercontent.com/79280782/205704667-d76ee1ab-b06e-4219-ad39-815bbdabb663.png)

**Comment by alexsl2174** [comment]
Umh i did check just now my mesurement. The nose itself in mm ist about 2mm by 2...but like how do i make anything bigger while still fitting on a 4x4 inch ?

**Comment by tyrosinase** [comment]
Embroidery machines aren't like printing things out on a laser printer - you have to compensate for what the thread is doing to the fabric. That's why you need stabilizer, and to hoop tightly: the tension of the thread tends to pull the fabric together.

The primary way to prevent it is with stabilization. The denser the stitching, the more stable the ground has to be. After that, you will need to turn up your pull compensation.

You're also limited in the size of things, when it comes down to it: your satin stitches can only be so narrow before they basically collapse on themselves (1.2-1.5mm, usually). You may run into that when you convert those black lines into satin (which, once again, really needs done - if your artist can give you the file with the strokes not collapsed into a fill object you're ahead of the digitizing game there), and you will probably have to make the inner outlines running or bean stitches.

You can gain a little more size in a 4x4 hoop by putting your design on the diagonal.

**Comment by alexsl2174** [comment]
I dont really want to do that since i told him i would make the conversion from drawing to whatever i need for the stiching. I understand the need to make it larger (the stroke i mean.) I'm just trying to wrap around everything to make sure that it can be converted as i tought it should be possible. On the Photoshop file i definitily have a fill shape which of course i do. So if i want stroke out of that then, do i go over to illustrator to use the pen tool to go trace on his lineart ? (with a widt of 1.5mm).
(Just want to emphase im not mad at all, just a tad anxious)

**Comment by tyrosinase** [comment]
There's a few different ways to do it: https://silverseams.com/tutorials/digitizing-outlined-graphics/

**Comment by alexsl2174** [comment]
Ok ok this time i do believe it should be a satin stich (i did read the tutorial but found a video from ink/stich wich was super helpfull). Ok the path isnt too perfect, ill probably do the path in illustrator because im use a bit more to the pen tool over there. (i didnt find how to breath the curve like i do over in illustrator, normally i just press alt i think then it create a break so i can do sharp angle)

![image](https://user-images.githubusercontent.com/79280782/205784282-41f1bcc9-a5f7-4c0d-8647-748e1432a672.png)

**Comment by alexsl2174** [comment]
Ok random question....why is it only 4*4? I feel like there is so much waste on the fabric plus it didnt went well again. The embroidery went too much on the same place because everything is too small sadly. At this point i dont know what to do anymore
