### ISSUE TITLE
Extension is downloaded but not working at all

### ISSUE THREAD

**Issue by sleepylizzz** [inkstitch/inkstitch#1932]
The extension shows active and is not grayed out but options do not work or open any dialogue box to change settings. I've followed multiple tutorials and tried different versions of both Inkscape and inkstitch currently have Inkscape v1.2 and Inkstitch v2.2.0. No error codes pop up no loading icon nothing, I'm at a total loss.

**Comment by kaalleen** [comment]
What is your operating system?

**Comment by Susansmithberger** [comment]
I am also haveing the same problem with Windows

**Comment by sleepylizzz** [comment]
> What is your operating system?

Running on Windows 10

**Comment by sleepylizzz** [comment]
> There are some outdated tutorials on YouTube. Please verify, if you did follow the steps on our website: https://inkstitch.org/docs/install-windows/
> 
> If you did do all these steps, most common issue is still, that the windows defender has detected Ink/Stitch has a virus and has removed it's executable. This means, you will need to add an exclusion: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

I have followed the recommendations and the extension still does not work.

**Comment by sleepylizzz** [comment]
> 
I found that the Windows Defender app wasn't on due to another Security app installed and running. I turned it on and added Inksctitch as an exclusion. But it didn't change anything turned it off and checked if it was getting affected by Norton but it wasn't either.

**Comment by MaxiN-maker** [comment]
#19232

I too have a problem with My extensions - I have installed Big Sur Processor 1.7GHz Dual-Core Intal Core i7

Running:

Rosetta 2 Updater:
Version: 1.0
Obtained from: Apple
Last Modified: 01/01/2020, 08:00
Kind: Apple Silicon
Signed by: Software Signing, Apple Code Signing Certification
Authority, Apple Root CA
Location: /System/Library/CoreServices/Rosetta 2 Updater.app

Inkstitch:
Version: v2.2.0
Obtained from: Identified Developer
Last Modified: 06/03/2023, 16:39
Kind: Intel
Signed by: Developer ID Application: Lex Neva (929A568N58),
Developer ID Certification Authority, Apple Root CA
Location: /Users/maxineneale/Library/Application Support/
org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app

Inkscape:
Version: 1.2.2
Obtained from: Identified Developer
Last Modified: 02/12/2022, 14:19
Kind: Intel
Signed by: Developer ID Application: Rene de Hesselle (SW3D6BB6A6),
Developer ID Certification Authority, Apple Root CA Location: /Applications/Inkscape.app

Messages I receive
![Extension  Preferences](https://user-images.githubusercontent.com/127307725/223723123-119f3afc-314b-4b48-a410-3cfe84025ca9.png)

![Inkstitch:Inkscape Trougle shoot messg](https://user-images.githubusercontent.com/127307725/223723128-a4c41062-3d97-4c5a-80e1-108aadff55e0.png)

![Additional data but with no objets ](https://user-images.githubusercontent.com/127307725/223723131-7ecca48c-008a-4048-8ed7-6707fa9fc3d6.png)

Any Ideas that can help me?

Thank you so much for any support that you can offer me.

All best wishes - Maxine

**Comment by rlevine** [comment]
Please forgive me for asking what might be an obvious question: are there any objects in the document? From this image, there doesn't seem to be anything drawn on the canvas. 

Try drawing a rectangle or other shape, select it, and then try Extensions -> Ink/Stitch -> Params

<img width="350" alt="Screen Shot 2023-03-08 at 10 31 50 AM" src="https://user-images.githubusercontent.com/2294569/223805250-7ab48dd9-74e4-4e17-92d4-dc0da778a1e2.png">

**Comment by kaalleen** [comment]
I'm going to close this. If there is still an issue with the installation, please open a new issue.
