### ISSUE TITLE
FillStitch not generating a FillUnderlay

### ISSUE THREAD

**Issue by ajgrinds** [inkstitch/inkstitch#1935]
I have left the settings as default and for some reason this isnt generating a fill underlay, only the horizontal stitches. As a result you can see fabric through the stiches.

Also, would this design look better as fill stitches or as a satin stitch?

![Untitled_edge](https://user-images.githubusercontent.com/38995121/205144677-4deef8ab-ef1a-422e-88dd-51de52c7b125.svg)

Edit: Sorry for the darkness. And yes I know I would have to remake the whole design if I wanted to satin stitch it.

**Comment by kaalleen** [comment]
Ink/Stitch is definitely having a hard time to use this as a fill stitch. I know, this is challenging to turn into a satin outline. But it would be the best for this type of motive.
