### ISSUE TITLE
cutwork_segmentation.py: Local Variable 'Parent' Referenced Before Assignment

### ISSUE THREAD

**Issue by xaglen** [inkstitch/inkstitch#1936]
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cutwork_segmentation.py", line 76, in effect
UnboundLocalError: local variable 'parent' referenced before assignment

**Comment by xaglen** [comment]
![heart_error](https://user-images.githubusercontent.com/10709823/205458119-82421114-6974-42dc-b5d0-2edd4136f3b0.svg)

**Comment by kaalleen** [comment]
Thank you for your feedback and the svg file. Definitely something we need to fix.

If you want to use the cutwork extension on your shape, you will need to remove the fill and add a stroke color.
