### ISSUE TITLE
dont know how to open Inkstitch

### ISSUE THREAD

**Issue by TheDopster** [inkstitch/inkstitch#1939]
I downloaded your version of inkstitch and i found the folder called inkstitch and found the extensions folder which then led me to another inkstitch folder as well as 2 files that are different called unins000 and I cant open anything inside the inkstitch folder as in there is no program inside of that just many other folders called bin, electrons, examples, font, inx, palettes, symbols, licsense and version which except for the last two can be opened as fodlers into many other folders and/or files.

**Comment by tyrosinase** [comment]
Ink/Stitch is a plugin for Inkscape. You'll need to install [Inkscape](https://inkscape.org/) first, and then install Ink/Stitch based on the instructions for your OS: https://inkstitch.org/docs/install/ Then, when you open Inkscape, Ink/Stitch will be there on the Extensions menu.

**Comment by kaalleen** [comment]
No respond. Closing. Please open a new issue if you still have questinos about it.
