### ISSUE TITLE
Problème conversion  SVG vers VP3

### ISSUE THREAD

**Issue by davdav212000** [inkstitch/inkstitch#1941]
Bonjour, j'ai un problème de conversion en VP3 avec Inkstich. Ma simulation en svg est parfaite mais en ouvrant le fichier vp3 que je cré avec Inskape je vois des décalages. Donc je pense que la conversion en vp3 qui n'est pas bonne. J'ai essayé le même fichier en PES pas de soucis. Sur la photo à droite la simulation en svg et à gauche le même fichier converti en vp3 par inkstich et réouvert. On peut voir des espaces plus grand dans le milieu du M qui ne sont pas sur le svg. Je retrouve ces espaces sur ma broderie.
![probleme VP3](https://user-images.githubusercontent.com/119803045/205501600-df11f69a-a303-4b6e-894f-b7e5c65587f9.jpg)

**Comment by kaalleen** [comment]
Thank you for your report and sorry for the late answer.
I think this is similar to #2066 so I'm going to close this is favor of the other issue.
If you do not agree, please feel free to protest and reopen this issue.
