### ISSUE TITLE
Connecting stiches

### ISSUE THREAD

**Issue by bcnx** [inkstitch/inkstitch#1948]
Hi,

complete newbie to embroidery here. I noticed that if you have different soreaded objects in your design, the different objects are interconnected by a straight line.Can that be avoided? It seems less professional if you see these lines.

Thanks!

BC

**Comment by bcnx** [comment]
To answer my own question: I just watched a tutorial video where they show the trim thread command, that's probably what I need. I just don't know if my machine supports that action, will have to try ...

BC

**Comment by kaalleen** [comment]
If not, you could also color your objects differently - or cut the jump stitches when sewing is done.

If possible also try if you can reduce the amount of jump stitches by better routing (reorder, define start-end-points, connecting elements with running stitches). This will be better than using a lot of trims.
