### ISSUE TITLE
Shapely/Mac rail direction issue

### ISSUE THREAD

**Issue by Saulthepop** [inkstitch/inkstitch#1957]
the old version had no problem converting a line into a satin stitch. but this new update its impossible. when adding the feature, the satin goes the wrong way and messes the whole stitch. could someone fix it please?

<img width="1440" alt="Screen Shot 2022-12-14 at 12 34 04 AM" src="https://user-images.githubusercontent.com/120555975/207546884-8187a1dc-a699-45dc-a199-4973865327a5.png">
<img width="1440" alt="Screen Shot 2022-12-14 at 12 33 45 AM" src="https://user-images.githubusercontent.com/120555975/207546903-34c6f7f3-41af-4b84-96d3-28f8de4f778a.png">

**Comment by tyrosinase** [comment]
Shapely works differently than expected on a Mac, as was discovered in https://github.com/inkstitch/inkstitch/issues/1743, and one of the rails gets reversed. Selecting points on that rail with the node tool and doing a Path > Reverse is a workaround, and https://github.com/inkstitch/inkstitch/pull/1727 may fix it.
