### ISSUE TITLE
Unable to view/select params

### ISSUE THREAD

**Issue by CarbonZodiac** [inkstitch/inkstitch#1968]
Heya! If this was already answered, I haven't been able to find it. 
I just downloaded Inkscape v.1.0.2, and then the latest version of Inkstitch. I installed Inkstitch in the extensions folder of Inkscape, and it registers in the extensions menu. However, even after transferring objects to paths, the params menu continues to be grayed out. I've uninstalled, reinstalled, tried different Inkscape versions, tried restarting Inkscape, turning PC itself off and back on again, starting objects from scratch, etc. I can't find specific information about what would fix this, so any advice would be appreciated! 
![IMG_7590](https://user-images.githubusercontent.com/120967199/208311223-54cc513e-2d66-4678-93e4-96fbcddb1e24.jpg)

**Comment by kaalleen** [comment]
Check if your virus programm deleted Ink/Stitch files?

**Comment by kaalleen** [comment]
No response. Closing.
