### ISSUE TITLE
"Error during autofill"

### ISSUE THREAD

**Issue by LucieMrc** [inkstitch/inkstitch#1975]
It worked with the same file when it was a smaller size, then I tried making the embroidery and the page bigger and I am unable to apply ink/stitch and export my file in .pes.

Error message :
"path952_74: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 564, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 632, in do_contour_fill
  File "lib/stitches/contour_fill.py", line 137, in offset_polygon
  File "lib/stitches/contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely/geometry/base.py", line 685, in difference
  File "shapely/topology.py", line 72, in __call__
  File "shapely/topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x1301c81f0>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 230.63617636744092 403.89158551462089
shapely.geos - INFO - Self-intersection at or near point 230.63617636744092 403.89158551462089"

![gargouille](https://user-images.githubusercontent.com/54845437/209343723-04035c60-a895-41d4-9875-832640962ad6.svg)

**Comment by tyrosinase** [comment]
That's a known bug (per #1916) but what's triggering it is that that's not really a suitable graphic for fill stitch. You'll need to convert it to something linear, either running stitch or satin depending on scale, before Ink/Stitch can do anything meaningful with it.

This blog entry touches on that (though it was written before Ink/Stitch auto-routed running stitches, which improves things greatly): https://silverseams.com/2021/08/centerline-tracing/
