### ISSUE TITLE
Under certaim conditions. Machine won't recognize .jef

### ISSUE THREAD

**Issue by WahlmanPiper** [inkstitch/inkstitch#1976]
I have a janome memorycraft 350e

All of the patches i've done has wirked flawlessly with to exeptions.

I once tried to do a bent piece.

The second time i tried to replicate a photo.

Both times objects were outside the canvas. (That i ofcourse deleted)

A circular shape for the bent piece that peaked outside before cutting into it. The same with the photos.

Both those times the machine has totally refused to recognize the .jef file and i dont know what to do.

**Comment by tyrosinase** [comment]
Janomes apparently recognize when there are stitches too close together and won't load the file, but they're not really clear about why not. For me it's always been a running stitch that accidentally got changed to a solid line, and the machine doesn't like the almost-zero-width "satin" that resulted.

**Comment by WahlmanPiper** [comment]
Ah i see. But thats good then i know how to troubleshoot

Den fre 23 dec. 2022 16:40Tyrosinase ***@***.***> skrev:

**Comment by kaalleen** [comment]
Closing. Please post more questions into a new issue if the answer didn't resolve all of your .jef problems.
