### ISSUE TITLE
Translating of the webpage to Danish

### ISSUE THREAD

**Issue by UrticaDesign2** [inkstitch/inkstitch#1979]
Hi,
I am Danish and I would like to help to translate the webpage to Danish, but I do not know how to start? I am new in Inkstitch and Github, but I have around 5 years experience with digitizing digital embroidery and I am building an online course about Inkstitch in Danish. I would love to have the webpage in Danish… And I can help…?
I think that I will learn and understand Inkstitch better in the proces…

**Comment by kaalleen** [comment]
Nice, thank you for your request. I invited you to join this repository and added danish language support to the website. The pages are copied from the english section, but marked as outdated. So you can check the status here: https://inkstitch.org/developers/localize/#website

You can either clone the gh-pages branch and edit locally or click on the "edit translation" link on the website (link above) to edit them online.

If you have more questions please ask.

**Comment by kaalleen** [comment]
Oh, the navigation bar can be translated here: https://github.com/inkstitch/inkstitch/blob/gh-pages/_data/navigation_da.yml

You only need to translate the titles in this file. The links should be correct already.
