### ISSUE TITLE
Auto-trim between separate areas

### ISSUE THREAD

**Issue by chrisyelf** [inkstitch/inkstitch#1983]
Hi,

Would it be possible to auto-trim between separate areas?

For example, this image 
![bee](https://user-images.githubusercontent.com/121562270/209833389-a5ccb5d0-7dad-419d-aa70-afd6260b64b3.svg)

adds unnecessary stiches between areas, making it look bad:
![image](https://user-images.githubusercontent.com/121562270/209833206-b79d9926-8f56-4fc5-a8c7-353ac2c61066.png)

Each vertical area should start at the top (or bottom) and be filled to bottom, them trim, then start another area etc.

**Comment by tyrosinase** [comment]
You're seeing the underpathing, which will be covered up by the fill itself. If you really don't want it, you can uncheck "Underpath" (on both fill and underlay).

You're also mixing a fill and outline (zigzag), so if you turn off auto-fill Ink/Stitch will take that to mean it should not fill the object at all. But if you separate the fill and outline into two objects (which you'll want to do anyway or you'll get two layered zigzags in spots), you can do that and it will do a simpler fill.

You can also attach commands to manually set the start and end of the fill, and to trim after each object (if your machine supports it).

**Comment by chrisyelf** [comment]
Thank you for your help! 

> But if you separate the fill and outline into two objects

I'll look into the tutorials and hope to find how to do this. Thanks again!
