### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 2102nic** [inkstitch/inkstitch#1984]
Hello, i'm writing here today because i want to address a problem that is occurring to me while using inkstich. I use it on macOS.
- when i go to extensions>ink/stitch>visualize and export>simulator/realistic preview both inkscape and inkstitch stop responding for the whole time the animation of stitching is rendering. they just stop working. i may understand inkstitching stop working because it's busy building the animation, but why stop inkscape?
- when i go to extensions>ink/stitch>visualize and export>simulator/realistic preview i expect the program to render something (an animation or whatever), so i expect my cpu and/or ram and/or gpu to "be stressed" even a little bit, but that doesn't happen, cpu usage remains at around 0,5% to 0,8%, gpu remains stable at around 15% usage and ram doesn't increase usage in the slightest. it's like it's rendering something using the littlest resources possible, don't get me wrong it's good sometimes but other times i just need it to finish rendering a little faster, so i'd like for it to use more resources (if possible) to make it faster. i don't really care if my processor uses increases 50% etc, i just want it to render in 5 minutes instead of 5 HOURS. Maybe that's not how that works, but for me is still strange that it's rendering something using virtually 0% of the hardware.
Sorry for bad english i'm not a native speaker.
Again i use macOS version 10.14.6 on a mac pro 5,1 with 2x6 core xeon x5690, 128 Gb ram and a rx560 gpu. don't know if the hardware matters but i just give the information nontherless.

**Comment by kaalleen** [comment]
1. That's the way Inkscape extensions work - Ink/Stitch is an Inkscape extension and there is not much we can do about it.

2. Oh yes, we have to admit that Ink/Stitch isn't very fast. It is single threaded, see also #836
There is also attempts to make the stitch plan calculation faster by caching it: #1732

**Comment by lexelby** [comment]
There is a bug that you may be running into.  If Ink/Stitch encounters an error while rendering the stitch plan, it will just sit there spinning forever until you exit out.  THEN it will tell you the error.

**Comment by kaalleen** [comment]
Closing. As mentioned there have been similar requests for point 2. And we do use stitch plan caching now.
Point 1 we cannot do (yet?!?).
Main rule, if it takes a longer, exit out to see if there are error messages.
