### ISSUE TITLE
stuck on Rendering stich plan

### ISSUE THREAD

**Issue by chrisyelf** [inkstitch/inkstitch#1987]
Hi,

With attached svg, inkstitch gets stuck on "Rendering stich plan" when running the simulator or trying to save as .pes
![bee-it](https://user-images.githubusercontent.com/121562270/209953881-1115d857-0206-4289-bf7d-9960db7bfac6.svg)

It does work with other svgs, wondering what's the issue with this one.

Thanks

**Comment by tyrosinase** [comment]
As I said, after you subtract the shapes, you'll sometime be left with a lot of tiny scraps. You *must* clean those up or Ink/Stitch will waste a lot of time trying to fit stitches into impossibly-small areas or (depending on your version) throwing an error behind the window that will not appear until you give up and close the preview.

**Comment by chrisyelf** [comment]
Got it, thanks Tyrosinase!

**Comment by chrisyelf** [comment]
I do believe there's something wrong with inkstitch.
I've run Troubleshoot > Cleanup document with larger thresholds (still stuck), then deleted all objects except one.
It still hangs on "Rendering stich plan" 
![bee-it-part2](https://user-images.githubusercontent.com/121562270/209984610-8405d0f5-c89d-48f7-9897-e1f86aba9725.svg)

**Comment by kaalleen** [comment]
Ink/Stitch shouldn't take that long, but it could help, if you brought your design down to a reasonable size.
Set the page size to your hoop size and adjust your design to fit into it.

**Comment by tyrosinase** [comment]
What Kaalleen said, plus you've got a fine outline on that that is going to cause issues (it should render, but it will come out as a too-small zigzag for a machine).

**Comment by chrisyelf** [comment]
Thank you both, I'll keep trying.
