### ISSUE TITLE
bug: filling one `path` object results in "out of zone" jumps

### ISSUE THREAD

**Issue by chrisyelf** [inkstitch/inkstitch#1990]
Hi,

With this continuous, but complex shape (a single `path` object)
![bee-outline](https://user-images.githubusercontent.com/121562270/210200597-2a9616ee-ff20-4bb7-8dcd-b83247976300.svg)

the stitch plan works fine except towards the end, when there are some jumps outside of the area:
![Screenshot from 2022-12-31 08-54-45](https://user-images.githubusercontent.com/121562270/210128471-4ac1b99c-bb28-4487-b391-9515d5cceb52.png)

Could inkstitch be smarter and avoid those jumps (to avoid thread outside the area) when generating the stiches?

Thanks

**Comment by lexelby** [comment]
Well, it certainly is supposed to avoid such jumps when filling a shape!  Even complex shapes.

I suspect your SVG has a few tiny objects in addition to the bee shape.  Then the jumps are Ink/Stitch sewing each object in turn.  If there really is just the one fill object, then you've found a bug.

**Comment by chrisyelf** [comment]
Thanks for your help! That makes sense.
I looked at the .svg source and it has only one `path` object.

**Comment by lexelby** [comment]
Hmm.  The other possibility is that you've enabled the legacy fill stitch mode, which has jumps.

**Comment by kaalleen** [comment]
The jumps are a result of the stroke outline. Remove the stroke.

**Comment by chrisyelf** [comment]
Thanks! Removing the stroke fixed it.
