### ISSUE TITLE
SVG with trim after objects, hidden, shows one visually when saving as PES

### ISSUE THREAD

**Issue by chrisyelf** [inkstitch/inkstitch#1993]
This happened on a more complex SVG, but managed to reproduce it with a simple one:

1. I've selected all 3 objects in a SVG
2. Attach commands to selected objs > Trim. All 3 show visually as scissors
3. Commands > View > Show|Hide. All 3 trims are hidden.

So far so good:
![3obj-trim](https://user-images.githubusercontent.com/121562270/210273080-47e42c91-d74e-4524-b5fc-75aa4a807b6f.svg)

Next, I save as PES. Open PES: One of the objects show a trim visually as scissors
Tried it both from command line and GUI Save as, same result:
```
inkscape 3obj-trim.svg -o 3obj.pes
inkscape 3obj.pes -o 3obj.png
```
(can't attach PES, attaching PNG instead)
![3obj](https://user-images.githubusercontent.com/121562270/210273092-89276748-7546-4ec3-82c5-482478260660.png)

Not sure if related to https://github.com/inkstitch/inkstitch/issues/1264

**Comment by tyrosinase** [comment]
I've noticed this too: view/hide is really hinky, especially if you hide the command objects and then add more trims later. Click view/hide and some will go away, others will reappear, but not even a simple toggle.

Also, I carefully added manual trims to the Bluenesia alphabet and *that* may have been a mistake.

**Comment by chrisyelf** [comment]
Maybe instead of toggle, have 2 separate commands: Hide and Show? That would be more clear for me as an user, and I guess implementation would also be more clear: just hide all, or show all. No need to remember previous state.

**Comment by kaalleen** [comment]
Toggle visibility does not remember the previous state. It just checks if the first command is visibile and toggles the state of all commands accordingly. So if the first command has an other visibility status than the rest, the worst thing that can happen is, that you need to run the function twice (repeat with Alt + Q). I think that should be sufficient?

@tyrosinase can you send a svg file which is behaving odd when toggling visibility? This extension is meant to toggle object commands only, not layer or global commands, is that the problem?

The problems you are seeing are also not caused by the toggle extension. Ink/Stitch won't save the command visibility into the embroidery file. So this information will be lost in that moment.

**Comment by kaalleen** [comment]
> Also, I carefully added manual trims to the Bluenesia alphabet and that may have been a mistake.

Maybe interesting for you: the next release will allow trim commands without using symbols (as a param).

**Comment by chrisyelf** [comment]
I can reproduce it with the SVG & steps described in 1st post. The SVG shows fine, it's only when opening saved PES when one trim is visible.

> you need to run the function twice

Just tried it (in the svg, before saving as PES). The 2nd time, all trims are shown again. Then toggled again. All trims are hidden (just like after 1st time). Save to PES, open PES, it still shows one trim.

> the next release will allow trim commands without using symbols (as a param).

Could I test this?

Thanks!

**Comment by kaalleen** [comment]
> Just tried it (in the svg, before saving as PES). The 2nd time, all trims are shown again. Then toggled again. All trims are hidden (just like after 1st time). Save to PES, open PES, it still shows one trim.

Then it works exactly as expected. It will never hide the trims when you open an embroidery file. It will not remember if they were hidden in the svg or not.

> Could I test this?

Yes sure why not, I'll post you a link soon.

**Comment by chrisyelf** [comment]
>  It will never hide the trims when you open an embroidery file. It will not remember if they were hidden in the svg or not.

I see, thanks for clarification. Then I should close this, but looking forward to test the release without using symbols. Hope that will work from the command line batch mode too (actions).

**Comment by tyrosinase** [comment]
I don't think my visibility has toggled like that (I tried to find a pattern and there didn't seem to be one) but I'll mess with it more and see. I do make liberal use of layers, so there's that.

And yeah, you have no idea how much I and my (not terribly slow, but clearly not optimized for whatever specific demands those dang symbols put on it) computer have been looking forward to getting rid of the trim symbols. :laughing:

**Comment by kaalleen** [comment]
Here you go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

This is a fresh build from the current main branch (doesn't include a build for older macOS systems).

**Comment by chrisyelf** [comment]
Thanks, that does work! to be clear, I did Select all objects, then Extensions > Inkstitch > Params and checked Trim after.

Would it be possible to do the same from command line batch process? I see `inkscape --action-list` shows `org.inkstitch.params`, but how could one set various fields in the command line? eg
`inkscape --batch-process --actions="select-all; org.inkstitch.params:?"`
