### ISSUE TITLE
problem with color conversion

### ISSUE THREAD

**Issue by 2102nic** [inkstitch/inkstitch#1995]
when i save a drawing in a embroidery format it heavily modify some colors, especially while saving files in .dst and .pec

example attached 
![Screenshot 2023-01-03 at 17 47 07](https://user-images.githubusercontent.com/121610658/210402857-52d0719f-73a6-438f-ba16-af02e324524a.png)

**Comment by tyrosinase** [comment]
Neither DST nor PEC save color information, so when embroidery software loads it, it just chooses its default colors (usually pretty garish) so you can tell the thread changes apart. Ink/Stitch will preserve the information in the SVG, so you can use the PDF to reference which thread color to use for each sequence number.
