### ISSUE TITLE
Satin Columns: thickness patterns

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#1999]
I see wonderfull new features coming in the next release of Inkstich.
Of course I wish to have something more. We will have randomized edges on satin columns. 
it wood be great to have also very regular columns like on the image. No idea if it is easy to create but I believe you are magicians!
![Capture d’écran 2023-01-04 231240](https://user-images.githubusercontent.com/54963659/210660977-66bf9054-5c23-4467-94a8-6306638b7a49.png)

**Comment by george-steel** [comment]
You might be able to do this with the "pattern along path" live path effect. It definitely works when using a running stitch or manual stitch pattern (which can be a zigzag shape). Not sure if it works with stain column lines or not. I'll try to add an example later.

Tagging this as docs-related for now as LPEs aren't mentioned at all in the documentation, so they're really easy to miss.

**Comment by Augusa** [comment]
We are able to do a lot of things in this way. But on Stitch Era you can just choose params on satin stitches and get different patterns that is my wish for Inkstitch exactly as we now get randomised edges.

**Comment by lexelby** [comment]
Neat idea!  Do I understand correctly that  you see this as an option for satin columns?

What if the satin already has varying thickness?  Does the pattern combine somehow?

**Comment by Augusa** [comment]
"Do I understand correctly that you see this as an option for satin columns?"
Yes, I see it as an option for satin columns. On my exemples it is a column with constant thickness. No idea about varying thickness, I just would have it to create quickly such different satin stitches.

**Comment by kaalleen** [comment]
Nice idea.

Path effects are mentioned in the workflow text somewhere and also in the running stitch section (added recently). Although it is possible to create the satin path like this, it is not working very well for satins.
