### ISSUE TITLE
Ubuntu 22.04 : Inkstitch works well except that "Parameter" window do not open 

### ISSUE THREAD

**Issue by sebast44** [inkstitch/inkstitch#2009]
after click on Parameter of inkstitch, turn for 1s, but no window open
thanks
Sébastien

**Comment by kaalleen** [comment]
Maybe I am wrong, but it's worth a try: https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds

**Comment by sebast44** [comment]
Thanks, this worked well.
