### ISSUE TITLE
the pcs file does indeed visualize but it's not perfect

### ISSUE THREAD

**Issue by fabricocouto** [inkstitch/inkstitch#2010]
![imagem_2023-01-12_123325959](https://user-images.githubusercontent.com/20323161/212110139-794ad7e4-2b39-4446-b69a-d9975c00366e.png)
the pcs file does indeed visualize but it's not perfect, most of the documentation for this file has been made available thanks to David and Josh, but this file is missing now in the code which hasn't been discovered yet

**Comment by kaalleen** [comment]
Do you have a sample pcs file?

**Comment by fabricocouto** [comment]
![image](https://user-images.githubusercontent.com/20323161/215007594-d39cd3ac-1e2b-44b8-b6be-3c179e776f37.png)
