### ISSUE TITLE
Received this error when I click on 'Params': ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Indigo94** [inkstitch/inkstitch#2013]
path7518: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

Here is the .svg file I am trying to embroider:
![ShyGuy](https://user-images.githubusercontent.com/19803037/212440976-457cd10d-8306-4d6c-81b5-5cdef9c5c98f.svg)

**Comment by Indigo94** [comment]
I was able to fix the issue by deleted the specified path7518 mentioned in the error (right leg, blue part), and redid it again. Maybe the nodes were intersecting or something.

**Comment by Indigo94** [comment]
The error is still a problem though.

**Comment by kaalleen** [comment]
Great, thanks for your feedback.
