### ISSUE TITLE
Different color for each letter in a font

### ISSUE THREAD

**Issue by justandywu** [inkstitch/inkstitch#2016]
Hello! 

I've been trying hard to find out how to create color switch commands for fonts/satin columns.

for example, if I had a font design:

H E L L O !

I'd want H- red
E - Blue
L - White
L- red
O- Blue
! - White

I don't know how to change the color of my satin column, so then my Baby Lock EMP6 sees the whole design as 1 color.

Is there a way to assign the color/change the color of a satin column so that when I export into a PES/PEC/DST file it will have color?

I'm very new to embroidery and learning so apologies if this is a stupid question.

**Comment by Marif91** [comment]
Dans la boîte à objets, tu changes la couleur de contour pour chaque lettre
![Capture d’écran 2023-01-16 à 17 40 21](https://user-images.githubusercontent.com/65076100/212728237-3d1a8696-8a27-46f2-a494-48f58fa99c26.png)

**Comment by justandywu** [comment]
![multicolor](https://user-images.githubusercontent.com/8253155/219928250-8a7d7c64-2a77-48c1-846b-36f8ca30e81e.PNG)

It looks fine in Params, but then when I saved the file, it said that I can't have fill stitches in my design? and then it removed the fill objects...

**Comment by kaalleen** [comment]
Sorry for the late answer. Could you resolve your problem?
It is hard to see from the image what was going wrong. Maybe a satin with a stroke and a fill stitch which didn't work (and won't look nice).
