### ISSUE TITLE
Params View does not open

### ISSUE THREAD

**Issue by ThGroth** [inkstitch/inkstitch#2024]
Hi,
I'm using inkstich only recently. Unfortenately the params View is not showing after selecting a shape and then Extensions->Ink/Stitch->Params 
The mouse cursor just switches to loading for a second and then nothing happens.
It seems not to depend on the selected object, I tried simple shapes as well as some other paths.

Inkstitch works fine apart from this behavior. I already stitched a few objects with this extension.

This problem is also described  #1525 for windows and Ubuntu 20.04.3. There a new installation seemed to has helped. In my case it didn't.

If I start inkscape from terminal I see the message 
```
WARNING: unknown type: inkstitch:collapse_len_mm
WARNING: unknown type: inkstitch:min_stitch_len_mm

```
I'm using ubuntu 22.04 and inkscape version Inkscape 1.2.2 (1:1.2.2+202212051552+b0a8486541) 
(I used to have an older version earlier, but updated to a more recent version to see if this helps)
Inkstich was installed using the .deb file.

Please let me know if there are further more verbose debug information I could provide to trace back this error.

**Comment by kaalleen** [comment]
Did you test this here: https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds
?

**Comment by ThGroth** [comment]
Not yet ;) 
But it indeed solves the problem.
Thanks.
