### ISSUE TITLE
Custom Satin Colum Will Not Render the First Few Times

### ISSUE THREAD

**Issue by st11x** [inkstitch/inkstitch#2026]
Hi,

I have a custom satin column in my file that when I set it with params, the screen doesn't refresh and still shows the running stitch (the default). I'll close and reopen a few times and sometimes it'll work. Other times, it is a combination of copying a section of the column (and rails) into a new file, make it render, then at some point, the entire column will render without any problems or modifications. 

Do you know why this is happening? Is there a cache or something? 

thanks
  Matt

**Comment by st11x** [comment]
I have been trying to replicate this consistently and now this path that used to work is completely failing. I am attaching the sample SVG file. This was the error when I ran troubleshoot objects.

So if you break apart the object, then combine, then run troubleshoot, everything is fine. But if you set it to Custom Satin via Params, it will not run and if you run troubleshoot again, you will get this error. 


![satin](https://user-images.githubusercontent.com/7398499/213953566-bc82eafa-1a3e-4f33-9130-4aaecfc9abf5.svg)


Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)


Traceback (most recent call last):
  File "shapely\speedups\_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\satin_column.py", line 443, in validation_errors
  File "lib\elements\satin_column.py", line 253, in rails
  File "lib\elements\satin_column.py", line 253, in <listcomp>
  File "lib\elements\satin_column.py", line 329, in rail_indices
  File "lib\elements\satin_column.py", line 329, in <listcomp>
  File "shapely\geometry\linestring.py", line 46, in __init__
  File "shapely\speedups\_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples

**Comment by st11x** [comment]
I stumbled upon a workaround that seems to be quite effective.

When you open the SVG that I attached, you need to combine all the objects under the layer. If you ran Params and Custom Satin, it would not work.

However, if you selected some or all nodes like this, press Ctrl+C to copy, 

![image](https://user-images.githubusercontent.com/7398499/213957585-4efc6ddf-6d60-4686-84dc-9e3b35db12ef.png)

then run the same Params -> Custom Satin, it works immediately. You don't even need to paste what you copied.

**Comment by kaalleen** [comment]
Interesting. Thank you for reporting this bug. This is very useful for us.

You can run Ctrl + L (simplify path) on your combined satin path. It will not alter the shape a lot, but will make it usable.

**Comment by st11x** [comment]
Thanks Kaalleen. I did simplify the path in Vectornator before moving over, this was the final one before it changes the shape. I'll try that in Inkscape and see if this is any better.  

I noticed that this same "fix" can be applied when there are other errors. For example, I tried added a Jump point to the whole design and it gave me an error and a stack trace too. But this copy fixes it.
