### ISSUE TITLE
EXP format is broken

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#203]
When exporting to EXP, the design is jumbled.  Recognizable chunks of the design appear, but it looks like there are random offsets strewn about in the design.  Blocks are all over the place, and it also seems to randomly jump in the middle of a color block multiple times (example: the satin around the outside of the bottle).

Colors are also off, but it may be that JEF is like DST and can't encode colors.

![exp_broken](https://user-images.githubusercontent.com/4446653/41494648-113ff58e-70e4-11e8-95a7-730c7d0a1475.png)

**Comment by tatarize** [comment]
EXP doesn't have color information. And I'm pretty sure the registration errors occur only during multiple jumps. There was some screwy code that made any jump beyond maximum distance get ignored and the way wilcom coaxed it to always work was to have every jump command consist of 0x80 0x04 0xXX 0xYY 0x00 0x00. I think lib embroidery writes the trims wrong, like they are supposed to be trim and move to another location, and it fails to export the location correctly instead defaulting to 0,0 losing that data. 

All the libembroidery uses a standard unit distance of mm and constantly converts it dividing by 10 into 1/10th mm (as standard through most embroidery) and multiplying by 10 which makes a number of bugs very easy like slight rounding errors that build up.
