### ISSUE TITLE
.dst title always set to "Untitled"

### ISSUE THREAD

**Issue by rlevine** [inkstitch/inkstitch#2042]
This is probably a feature request, but it's an omission that creates a nasty workflow problem on older Tajima machines.

An older embroidery machine that stores patterns in memory "slots" after retrieving them from a disc or floppy will not retrieve the source filename info for the pattern. Instead, it'll  label a stored pattern with the title text from the LA field in the header of the .dst file. (This is true of non-GUI Tajima machines, like mine. Not sure if this is true on more recent beasts.)

From a quick look at the code, it looks as if the write() method in DstWriter  looks for a metadata "name" field, doesn't find one, and sticks in "Untitled."  The upstream metadata load in InkStitchMetadata will only grab fields in the inkstitch namespace, and a title isn't there, so the header title is always defaulted.

My (very cursory) peek at the code didn't bring me any insight about where to add the title. EmbroiderSettings stuffs min_stitch_len_mm and collapse_len_mm into the xml data, but I know zilch about the architecture, so I can't tell where you might gracefully park code to load a title. Two ideas for a data value are either to grab it from the inkscape document props "title" metadata field, or if that's blank, just use the first 16 chars of the left side of the filename.

In any case, I'd love not to have 79 files in memory all named "Untitled." 

Thanks for listening, and thanks for building such a wonderful platform; it's fun to be exploring it!

Rick

**Comment by lexelby** [comment]
Oh interesting, I didn't realize any machines used that field!  I'm sure that's driving you nuts.

Your analysis is spot-on.  At minimum we should be able to get the file name into the LA field with a bit of code.  We could potentially have an option to set a title, but I kind of feel like the file name makes more sense anyway.  What do you think?

**Comment by lexelby** [comment]
"No no, the _other_ Untitled!"

At least you have a Tajima, I gather they're nice. :)

What you've laid out here is exactly right.  That's the same pattern object, so I think this should work.

Setting up a local development environment can be a bit of an ordeal.  If you just want to create this small PR and test it out, the easiest way would be to push a branch and let our CI build a pre-release for you.  Then you can download it from the releases section and install it on your machine to test it out.  And that way once it works you'll have your fix right away :)

I'll give you write access to this repo.  We generally name our branches like "lexelby/some-feature" so that we can tell them apart.

**Comment by rlevine** [comment]
Looks like I'll need access to pyembroidery, too, unless there's some git submodule magic I need to learn.

I'm whacking through setting up a local env. Anyone running pycharm on a mac who can give me some pointers? I 'm puzzling out how to get inkscape to see local code, which doesn't seem obvious from the manual setup doc.

On the Tajima, yes, it's fun. Mine is from 1997, and is pretty much a brute force beast. All told, it really does only four things: stitch, move, trim and select needle. But it can do them 24x7.

**Comment by rlevine** [comment]
Ok, I'm loading the right extensions on the inkscape side (the about item gives me a page saying "InkStitch Manual Install," but can't get the debugger to latch on. Sequence to start debugging? I've tried starting the debugger from the top level inksitch.py, but any attempts at connection to the process time out. My symbolic link is from the top level of the build tree, and the inkstitch extension menu in inkscape is populated, but starting an extension doesn't produce a dialog box.

**Comment by rlevine** [comment]
More... (Apologies for the noob questions, but I suspect this is something simple and obvious, and I can't see it from this chair. Hmpf. : )

"About" screen is definitely from my code, I can edit inkstitch_about.inx and `<label>` changes show up in the UI. I've touched a DEBUG flag file in the top level. Running an extension runs '../inkstitch.py' from the top level dir, a 'print' statement added right before 'debug.enable()' works. Adding the 'print' does cause it to spit out ' WARNING **: 18:01:48.663: Extension returned output that could not be parsed: Open failed' Hmpf.

**Comment by lexelby** [comment]
Oops, pyembroidery access added too. I'm sorry you're having trouble with the manual setup.  It's late here now but I'll try to take a look tomorrow.

**Comment by kaalleen** [comment]
Solved by yourself in #2049 :)

**Comment by rlevine** [comment]
:thumbsup: Thanks! I'll do better at housekeeping.
