### ISSUE TITLE
Error during Generate Palette / Split text operation

### ISSUE THREAD

**Issue by landriaultp** [inkstitch/inkstitch#2055]
Was following this procedure: https://www.youtube.com/watch?v=4bcRVoKvzAw&t=71s
while trying to Generate Palette / Split Text

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\palette_split_text.py", line 33, in effect
TypeError: float() argument must be a string or a number, not 'NoneType'

![draft](https://user-images.githubusercontent.com/61169106/216837247-4c44cf17-2770-4075-a5c7-58841588f209.svg)

**Comment by kaalleen** [comment]
Thank you for your error report and bringing this up to our attention. I updated the split text extension for the next Ink/Stitch release.

Here is your file with split text applied to it so you can go on right away:

![2055_modified](https://user-images.githubusercontent.com/36401965/217173537-95bf95f6-7e5c-408f-9cf9-22ff192d6657.svg)
