### ISSUE TITLE
Stitch plan extension

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#206]
As we implement direct saving of machine embroidery files using File -> Save (output extensions), perhaps we should retire the Embroider extension.  Instead, we could add a Stitch Plan extension that creates or updates the stitch plan layer whenever the user likes.

Currently, Embroider shows the stitch plan in the same spot as the embroidery vector objects and hides all other layers.  What if, instead, the stitch plan appeared off to the side, without hiding the design layers?  It would be another section outside of the official boundary if the SVG canvas.  Then you'd edit the embroidery objects on the left, run Stitch Plan, and see how the stitch-out changesb on the right.  It would look like a before/after view.

Another cool side effect of doing it this way is that it would be easy to manually edit stitches.  Just copy a path from the stitch plan and paste it into one of your design layers and you can edit it as a manual stitch object.

**Comment by wwderw** [comment]
That sounds cool.

I do like the thought of it being off to the side and be able to do a side by side comparison.

**Comment by X3msnake** [comment]
Agree with @wwderw
