### ISSUE TITLE
won't install in Linux

### ISSUE THREAD

**Issue by Irritantr** [inkstitch/inkstitch#2060]
![DeepinScreenshot_select-area_20230209134238](https://user-images.githubusercontent.com/56132908/217915613-f05383e8-f5aa-465f-844a-1733c32cec24.png)

**Comment by bianchifan** [comment]
Your Inkscape is too old.
Which Linux? Version?
With Inkscape 1.0 a bunch of changes were introduced, you should install an actual version.

**Comment by Irritantr** [comment]
Hi,

My Linux is mint 20.3 and inkscape is 20.3.

**Comment by Irritantr** [comment]
I ment to say my Linux Mint is 20.3 and Inkscape is 1.2.1.

**Comment by bianchifan** [comment]
> I ment to say my Linux Mint is 20.3 and Inkscape is 1.2.1.
That's my system, too.
But you'Re using a deb install while I use manual copy into .config of my HOME.

Maybe you have still an older inkscape somewhere which will be found by inkstitch.
If not, I have no idea and you must wait for the developers.

**Comment by kaalleen** [comment]
Hm, if the deb installer doesn't work (for whatever reason) try to use the tar.xz file instead. Instructions on the website: https://inkstitch.org/docs/install-linux/#installation
