### ISSUE TITLE
Params window does not open

### ISSUE THREAD

**Issue by ionutrogojan** [inkstitch/inkstitch#2061]
### System :
- Fedora 37
### Inkscape :
- 1.2.2 (b0a8486541, 2022-12-01)
### Ink/Stitch :
- 2.2.0 (linux)
#
### Issue :
- Selecting the params option from `Extensions` > `Ink/Stitch` > `Params` does not open the `Params` window. The entire Inkscape window seems to refresh itself and no error or other indication of an issue is presented. All the other options from the plugin work, the only exception being `Params`.
#
### Steps to reproduce :
1. Open Inkscape
2. Draw a shape
3. Click `Params` from `Extensions` > `Ink/Stitch` > `Params`

**Comment by kaalleen** [comment]
It could be the wayland issue: https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds ? (and would effect both, params and lettering)

**Comment by ionutrogojan** [comment]
That seems to have fixed it. Thanks!

**Comment by ionutrogojan** [comment]
so I made it easier for myself to launch the application and not have always write that and here's how to do it if you're on `Wayland` and the `Params` dialog is not showing.

1. Create a `launcher.sh` file and add the following code
```sh
#!/bin/bash
export GDK_BACKEND=x11 && inkscape
```
2. Create an `InkStitch.desktop` file inside of `/home/.local/share/applications` and add the following code
```sh
[Desktop Entry]
Type=Application
Name=InkStitch
GenericName=Embroidery Software
Comment=InkStitch Wayland workaround
Icon=/path_to_icon_file/inkstitch.svg
Exec=/path_to_launcher_file/launcher.sh
Categories=Graphics;
Terminal=false
NoDisplay=false
```
3. Enjoy :smile:
