### ISSUE TITLE
stitch out discontinuity in auto fill

### ISSUE THREAD

**Issue by rlevine** [inkstitch/inkstitch#2068]
I'm seeing a break in a stitched fill pattern where I don't expect one. This may be how I'm stitching out or a machine issue rather than an Ink/Stitch artifact, but it's consistent, and I'd value some feedback on how to correct it. 

I'm seeing a break in the fill pattern at the edges of adjacent patches, and it isn't in the simulation, as far as I can see. 

Fill and underlay are 90 degrees apart, 3mm max stitch 0.25mm row spacing, 4-row stagger, no expansion. It shows up on both knits and wovens I've tried

I've attached a pic of a segment of the simulation from params and the matching area in the stitch out. It's a client file, but I can provide the .svg file privately, if needed.

Rick

***

<img width="313" alt="fill_preview" src="https://user-images.githubusercontent.com/2294569/218374549-796e5d93-32b5-4b1c-a45a-b0a96c400436.png">

![fill_discontinuity](https://user-images.githubusercontent.com/2294569/218374567-2b68692f-aac7-4cb9-afef-b724636384e3.jpg)

**Comment by lexelby** [comment]
This is due to shifting and stretching of the fabric during stitching (referred to as "distortion").  Adding stabilizer can help.  We have another issue going where we're discussing ways we can counteract this in the code.

**Comment by rlevine** [comment]
Perhaps just a param to set an offset for fill patch edges where they’re adjacent?

**Comment by bianchifan** [comment]
> This may be how I'm stitching out or a machine issue rather than an Ink/Stitch artifact, but it's consistent,
Its a lack of experience ;)

> It shows up on both knits and wovens I've tried
I can only see knits...

... and knits are much more difficult than wovens!

1.
What sort of stabilizer did you use?
I recommend 3 Layers.
2 layers of tearaway stab fixed each other with glue spray.
Tauten the sandwich very hard in the frame, you should ply tambourine with it!
Glue spray on the top.
Put the knits upon, stretch slightly and press.
Cut an appropriate piece of AVALON, spray some (very little) glue on its back and put it on top.

These steps are absolutely neccessary.

Further, you should add a SOFT frame to your design, a simple surrounding with a long stitch length, 4-5 mm, not carefully worked out. Just to fix your knits and Avalon.

2.
At least you may rework your design.
Break it apart into several pieces and change the stitch direction.
Play with the params.
Try to find some values so every part will be stiched out completely without a break and a new start from the opposite.
If its not possible try to fill manally, guided fill.
Read the doku.
Have a look at the videos of LowTechLinux.
He put some vids on YT where he discusses your prob with the fills.

**Comment by rlevine** [comment]
@bianchifan, thank you very much for your notes! They're very helpful, please don't stop! I grabbed a can of Odif 505, and spent Sunday afternoon learning tricks to do with it. I'm still very much in that fun phase of learning about embroidery, where I don't know what I don't know, and sometimes don't even have the vocabulary to ask. It's like watching a basketball or football game and seeing the players running around, but not knowing enough to understand what their roles are and what they're actually doing. :) I do have textile experience, mostly in circular knitting and sewing automation, but I first touched an embroidery machine almost exactly a month ago. ("...lack of experience" is probably too kind!)

I'm not particularly trying to faithfully reproduce the sample design I posted. It's just an example that shows the behavior I'm trying to understand. (And my daughter likes dragons.) I can see that some of the people coming to Ink/Stitch (and to machine embroidery generally) are just looking for a "thread printer," and are mostly unaware of the limitations of the medium. I have an opposite perspective, in that I'm interested in deconstructing the medium of embroidery, specifically as it's modulated through Ink/Stitch, to understand what the strengths and weaknesses are, and to find the edges of the capability envelope. That's where interesting creation happens. 

So, a few questions about your generous answer:

  - Why do you use two layers of tear-away, rather than a single, heavier layer of cut-away?
  - Do you place your "soft frame" outside of the design, as a "basting" circle and then remove 
    it, or do you sew it as an underpath?
  - If the frame is outside the design, do you skip the lock stitches to make it easier to remove?

And I'll post more examples and more questions next.

**Comment by rlevine** [comment]
I think the answer to my question is "auto-fill doesn't do pull comp, yet." Auto-fill does its placement quite well, but the junction between patches is always present, even when we stabilize the crap out of the fabric. Here's a snapshot of a stitch out on 1000D cordura. The fabric isn't moving much. (!) The patch joins aren't obvious, but they're still there.

![1000d_cordura_no_stab](https://user-images.githubusercontent.com/2294569/220758921-8f87e40d-68ba-4881-931b-6392f93ce4ec.jpg)

I ran a test of some simple fills, jiggering the stop and start to force two patches. By manually moving the last course of fill stitches in the second patch that's sewn at the junction of two adjacent patches, the gap goes away. I'm sure this isn't a surprise to any of you! Left to right, 0) as stitched, 1) 0.1mm movement of the last course, 2) 0.2mm. This and all the following examples are on 230gsm synthetic fleece knit, one layer 2.5oz cut-away.

![test_pull_comp](https://user-images.githubusercontent.com/2294569/220755283-b07ffbaf-9a2b-4f43-8c85-49bb0807987d.jpg)

And, on my sample dragon, I can do the same trick. Both are fleece on 2.5oz cut-away, right is no pull comp, left is 0.1mm.

![hand_edited_pull_comp](https://user-images.githubusercontent.com/2294569/220755390-e916bfc7-66c9-4317-b263-684f88346e24.jpg)

And just for grins, some experimentation towards figuring our how to do sparse fills with the current build.

![sparse_fills](https://user-images.githubusercontent.com/2294569/220755438-3bfde86a-7550-4610-9f06-053a7bd3d218.jpg)

**Comment by lexelby** [comment]
Interesting... could you maybe make a diagram of what exactly you mean by "manually moving the last course of fill stitches"?

**Comment by rlevine** [comment]
Sure. This documents this test:

![test_pull_comp](https://user-images.githubusercontent.com/2294569/220979445-78ee6ff2-05a8-4d43-9e30-086a1f4f0972.jpg)

First, a screen capture of the stitching sequence for my test from the params simulator. I moved the stop/start to force the creation of two stitch blocks, meeting in the middle.

https://user-images.githubusercontent.com/2294569/220977100-7d9102cc-5c54-47a7-babf-56abec0e5321.mp4

Next, a diagram showing the sequence, and where I adjusted the stitches.

![pull_comp_sequence](https://user-images.githubusercontent.com/2294569/220977704-2e47ea70-f7ad-443b-aeda-26ff32ffe67d.png)

A diagram of the three versions I created, showing the stitches I changed.

![pull_comp_diagram](https://user-images.githubusercontent.com/2294569/220978059-0dd49a5b-298f-4f06-bc64-71554d8596cf.png)

And finally,  the .svg I started from, and and the modified version.

![3fill_test_starting_version_no_mods](https://user-images.githubusercontent.com/2294569/220978882-e2cd87c7-032f-426c-88eb-5774a21fd542.svg)
![6fill_test_manual](https://user-images.githubusercontent.com/2294569/220978921-2f7b8ab5-d079-475b-9fa0-0a588ce6b1d0.svg)

**Comment by bianchifan** [comment]
> * Why do you use two layers of tear-away, rather than a single, heavier layer of cut-away?

Because I can tear them away ;)  I never used cut away, because of the "sharp" edge which remains.

> * Do you place your "soft frame" outside of the design,

Of course!

> * do you skip the lock stitches to make it easier to remove?

yeah.. and do not forget a large stitch length, ~4mm

**Comment by rlevine** [comment]
:thumbsup:

Thank you!

**Comment by lexelby** [comment]
Awesome diagram, thank you!

This is really interesting.  I wouldn't have expected that just moving a row would remove the gap.  I wonder if that only works on some fabric / in some situations.  I wonder if in some cases that might just move where the gap is?

**Comment by rlevine** [comment]
I think it'll always be a crap shoot, but my intuition is that covering a 0.1-0.4mm gap might solve a lot of cases.

If I start listing the variables, the error contribution stack gets deep pretty quickly. Even with deterministic stitch placement, and dead nuts alignment from the origin, the worst-case round-off error for row spacing is almost 0.2mm. And then there's fabric and stabilizer variation, warp vs weft density, needle deflection, etc, etc. There's no panacea, but it could be a tool to solve a lot of cases, if used intelligently.

A default of bumping a row 0.2mm, and possibly tweaking the following row if the gap gets too big, should get a lot of cases that are well-stabilized. I'd be curious if we can get to a way to optionally add 1-3 rows towards the join. As you speculate, I also think that the problem with only moving a row and no 2nd-row tweak  is that in some cases, round-off error will open up a new gap.

**Comment by rlevine** [comment]
And my test wasn't on easy fabric. I'm intentionally playing with knit fleece because it's a more real-world test.

**Comment by lexelby** [comment]
I'm torn.  On the one hand, your result is interesting.  On the other hand, I'm worried that _only_ offsetting a row or two won't fix all cases, and dangling a new feature in front of users that _claims_ to fix the gapping issue will be really frustrating.

The industry standard seems to be to give the user the option to overlap by a couple rows.  I'd love it if we could do that.  My idea in #1068 could work, but it sounded like you tried to simulate it and got not-great results.  Did you see my question in [this comment](https://github.com/inkstitch/inkstitch/issues/1068#issuecomment-1441098863) asking for details?

As I mentioned in the other issue, the current auto-fill algorithm doesn't really allow for adding those extra rows.  Your idea of expanding the sub-polygons of a fill shape a bit would work -- if only we were using a method that broke the shape up into sub-polygons.  I'm not against rewriting the auto-fill algorithm to use that kind of approach, if we can figure out how to make it work.  That was the only way I could figure out how to do auto-fill _at all_ at the time, but I've learned a lot since then, and I think a simpler and more flexible algorithm might be possible.

We already know how to break the shape up into the sub-polygons (we do it for "legacy fill" in lib/stitches/fill.py).  I've been thinking that maybe we could follow an approach similar to what I used in auto-route-satin to find an order to stitch those polygons in.  In auto-route-satin, the algorithm looks like this:

1. Build a graph.
2. Find the shortest path from start to end.
3. Remove the edges in the shortest path from the graph.
4. Traverse the shortest path in order, doing a depth-first search at each node to traverse all of the remaining edges in the graph.
  * networkx's dfs_labeled_edges() gives us a list of edges in the order traversed, including backtracking from a leaf node in order to find more branches to traverse.
5. build a path of edges in the order visited by the depth-first search, including the backtracking edges.
6. stitch the satins in the order they're visited in the path created in the previous steps.  If an edge is visited more than once (due to back-tracking), the first N visits are under-pathing, and only the last is the "real" stitching.

I'm pretty sure this would work for auto-fill too.  It would dramatically simplify the algorithm and open the door for your approach of extending polygons.

**Comment by lexelby** [comment]
A diagram to hopefully clarify my terrible explanation:

![IMG_20230224_233617.jpg](https://user-images.githubusercontent.com/4446653/221338453-6b1767b5-5d02-420d-aa9a-36cf4783d5f3.jpg)

Now imagine each node is a sub-polygon that can be stitched all in one go with back-and-forth rows.  The last mention of any given node in the path is when you actually fill it with rows of stitches.  All the previous mentions are when you travel across it with underpath.

**Comment by rlevine** [comment]
I sympathize with the tension between offering a feature and wanting to avoid having people assuming it fixes all their problems!

I think the compensation issue is always going to be case dependent and is also something that can only be judged after seeing a stitch out for a specific combination of variables. Even worse, for someone who's expecting a tidy simulation, the preview is going to look wrong, with overlapping sections. 

I did follow your explanation, and thanks for the added diagram! (Coincidence; I was actually looking at networkx in my search for a way to visualize polygons while debugging. Ended up just grabbing geopandas and matplotlib and parsing the copied coord text from pycharm. :)

The observation I'll make about compensation is that it seems as if it's almost always about moving a block of stitches closer to or farther away from another block, when the fabric stretches or compresses to mess up the intended alignment. Dropping extra stitches into a gap is likely to match less well than moving a block into the right position, as the block already matches the the structure of the mating section. (Just thought of an analogy: when you're reaching out to put your cup on the coffee table, and someone moves the table, instead of changing your aim, you build an extension to the table. :)

And I understand that it's a major architectural whack to fills. I can also see that it has other advantages, such as being able to chop the block sequence into discrete parts so someone can adjust them manually, when automated adjustment fails.

I can't help thinking that this is equally an education issue as it is an implementation one, and also that my expectation, ie having the tools to do a job I understand, is different than that of someone coming to Ink/Stitch with a quick project and just wanting it to work. So I'm some ways, I may be a bad target customer.

**Comment by lexelby** [comment]
> I think the compensation issue is always going to be case dependent and is also something that can only be judged after seeing a stitch out for a specific combination of variables. 

Oh yes, most definitely.  Fortunately experienced folks are quite familiar with this.

> Even worse, for someone who's expecting a tidy simulation, the preview is going to look wrong, with overlapping sections. 

I'm not concerned with this at all.  Experienced digitizers know that what you create on the computer doesn't match what happens in real life.  Plus, this overlapping will only occur if the user enables "gap compensation" so they probably know why they're seeing overlap.



> The observation I'll make about compensation is that it seems as if it's almost always about moving a block of stitches closer to or farther away from another block, when the fabric stretches or compresses to mess up the intended alignment. Dropping extra stitches into a gap is likely to match less well than moving a block into the right position, as the block already matches the the structure of the mating section. (Just thought of an analogy: when you're reaching out to put your cup on the coffee table, and someone moves the table, instead of changing your aim, you build an extension to the table. :)

One thing that's worth considering here is what other software does.  They've had decades to figure out best practices.  I don't know if they have a row offsetting option like your idea...

> 
> And I understand that it's a major architectural whack to fills. I can also see that it has other advantages, such as being able to chop the block sequence into discrete parts so someone can adjust them manually, when automated adjustment fails.

If my new algorithm works, I definitely want to switch to it.  It's much simpler and it's bound to be _way_ faster than what we have now.

> 
> I can't help thinking that this is equally an education issue as it is an implementation one, and also that my expectation, ie having the tools to do a job I understand, is different than that of someone coming to Ink/Stitch with a quick project and just wanting it to work. So I'm some ways, I may be a bad target customer. 

Yup, a valid concern.  On the other hand your approach mirrors my own: I got into this to explore and learn as I go.  It's cool that Ink/Stitch is a maverick.  It's the only one with explicit support for diy embroidery machines, for example.

**Comment by rlevine** [comment]
> > Even worse, for someone who's expecting a tidy simulation, the preview is going to look wrong, with overlapping sections.
> 
> I'm not concerned with this at all. Experienced digitizers know that what you create on the computer doesn't match what happens in real life. Plus, this overlapping will only occur if the user enables "gap compensation" so they probably know why they're seeing overlap.

Great. I'm still feeling my way towards understanding who the audience is for Ink/Stitch. I'm encouraged by what I see; building tools towards a competent embroidery platform that empowers people who understand the medium, "experienced digitizers," to create what they can imagine. I'm also seeing some tension between that and the desire to make the tent larger, supporting people just starting, who might come in expecting a "thread printer" and gently leading them to the point where they start creating within the confines of the medium, instead of trying to make it do things that it can't. For instance, I'm having fun with the new random code, but I start wondering if the number of options in the param interface will be crossing a complexity or richness line. To help newer folks be successful, it might be interesting to include a library of "stock" presets, recipes for creating common, interesting effects, instead of them needing to understand and master the entire interface. 

(And btw, I'm impressed by how you, @kaalleen and others are being gentle, diplomatic and constructive replying to the folks who have just wandered into Ink/Stitch for the first time!)

> > The observation I'll make about compensation is that it seems as if it's almost always about moving a block of stitches closer to or farther away from another block, when the fabric stretches or compresses to mess up the intended alignment. Dropping extra stitches into a gap is likely to match less well than moving a block into the right position, as the block already matches the the structure of the mating section. (Just thought of an analogy: when you're reaching out to put your cup on the coffee table, and someone moves the table, instead of changing your aim, you build an extension to the table. :)
> 
> One thing that's worth considering here is what other software does. They've had decades to figure out best practices. I don't know if they have a row offsetting option like your idea...

I'm in complete agreement on this. I haven't seen row offsetting elsewhere; it was just a hack to test if  moving the block edge would solve my problem. Expanding or contracting an entire region of stiches is pretty much the standard approach to compensating for distortion, going back all the way to punching for Schiffli machines. 

An aside; I picked up a copy of Coleman Schneider’s 'Embroidery: Schiffli & Multi Head' from 1978. It's very apparent that just as we're chasing the capabilities of the mainstream embroidery software (ie trying to create the same kind of embroidery results as the current "industry standard" software) the current commercial software folks were chasing the capabilities that the traditional Schiffli designers and punchers did by hand. Here's an example - for a tight, even "geflect" fill over an area, a designer would draw the spacing lines, probably with the end points laid down using a stitching wheel, and a hand-drawn diagonal overlay (at 30 degrees in this example) that defined the stitch break points for the puncher. 

![schiffli_geflect](https://user-images.githubusercontent.com/2294569/221445685-5b68c189-7216-4d02-b138-72ae2747a71b.jpg)

In this pic, the left side is a sketch of what the designer would draw, and the tick marks on right side demonstrate how the puncher would use the designers cartoon to create fill stitches. The people implementing the first versions of today's digitizing software were trying to duplicate what the industry designers and punchers did very precisely with very little automation.)

> > I can't help thinking that this is equally an education issue as it is an implementation one, and also that my expectation, ie having the tools to do a job I understand, is different than that of someone coming to Ink/Stitch with a quick project and just wanting it to work. So I'm some ways, I may be a bad target customer.
> 
> Yup, a valid concern. On the other hand your approach mirrors my own: I got into this to explore and learn as I go. It's cool that Ink/Stitch is a maverick. It's the only one with explicit support for diy embroidery machines, for example.

Being able to see what the code is doing is a great way to learn; it's something that Ink/Stitch allows, and why I'm fascinated by it; I learn more, faster.

(And for more grins, here are an .svg and resulting .dst stitching the above example.)

![2background_fill](https://user-images.githubusercontent.com/2294569/221447311-4207c47f-cca6-484f-a772-36c2d859208b.svg)

[2background_fill.dst.zip](https://github.com/inkstitch/inkstitch/files/10835191/2background_fill.dst.zip)

**Comment by lexelby** [comment]
> Great. I'm still feeling my way towards understanding who the audience is for Ink/Stitch. I'm encouraged by what I see; building tools towards a competent embroidery platform that empowers people who understand the medium, "experienced digitizers," to create what they can imagine. I'm also seeing some tension between that and the desire to make the tent larger, supporting people just starting, who might come in expecting a "thread printer" and gently leading them to the point where they start creating within the confines of the medium, instead of trying to make it do things that it can't. 

Yup!  I wholeheartedly embrace that tension.  I want Ink/Stitch to be a flexible wild upstart of a platform for doing new things with machine embroidery and breaking into it without having to pay.  But I also want to support veteran digitizers who've been doing this for years.  It's fun trying to do both :)

> For instance, I'm having fun with the new random code, but I start wondering if the number of options in the param interface will be crossing a complexity or richness line. To help newer folks be successful, it might be interesting to include a library of "stock" presets, recipes for creating common, interesting effects, instead of them needing to understand and master the entire interface.

Oh yes, I'd definitely like to do that.  We're overdue for another UI revamp.  We experimented with Electron, but we're probably going to move away from that and pick yet another new UI framework, hopefully for good this time.  I would love to have an "advanced mode" akin to Prusa Slicer's, where some of the more esoteric options are hidden unless you ask for them.  Shipping a bunch of presets would be great too.

> 
> (And btw, I'm impressed by how you, @kaalleen and others are being gentle, diplomatic and constructive replying to the folks who have just wandered into Ink/Stitch for the first time!)

@kaalleen is the queen of that. :)  I've always wanted this project to be welcoming.

> I'm in complete agreement on this. I haven't seen row offsetting elsewhere; it was just a hack to test if moving the block edge would solve my problem. Moving, expanding or contracting an entire region of stiches is pretty much the standard approach to compensating for distortion, going back all the way to punching for Schiffli machines.
> 
> An aside; I picked up a copy of Coleman Schneider’s 'Embroidery: Schiffli & Multi Head' from 1978. It's very apparent that just as we're chasing the capabilities of the mainstream embroidery software (ie trying to create the same kind of embroidery results as the current "industry standard" software) the current commercial software folks were chasing the capabilities that the traditional Schiffli designers and punchers did by hand. Here's an example - for a tight, even "geflect" fill over an area, a designer would draw the spacing lines, probably with the end points laid down using a stitching wheel, and a hand-drawn diagonal overlay (at 30 degrees in this example) that defined the stitch break points for the puncher.
> 
> ![schiffli_geflect](https://user-images.githubusercontent.com/2294569/221445685-5b68c189-7216-4d02-b138-72ae2747a71b.jpg)
> 
> In this pic (both sketches from p104 in the book) the left side is a sketch of what the designer would draw, and the tick marks on right side demonstrate how the puncher would use the designer's cartoon to create fill stitches. The people implementing the first versions of today's digitizing software were trying to duplicate what the industry designers and punchers did very precisely with very little automation.)
> 

Whoa, cool!  I never got around to reading that book.

**Comment by kaalleen** [comment]
Closing. The feature request for pull compensation is still open: #1776
