### ISSUE TITLE
How do I have inkstitch not fill an object in 2 separate parts 

### ISSUE THREAD

**Issue by Cuber43** [inkstitch/inkstitch#2078]
![0D7187A8-28D0-46A0-93B3-06783D1C23F3](https://user-images.githubusercontent.com/125830761/219973645-6401e9bf-e73d-452d-95f3-dd85407ef53b.jpeg)

I can’t for the life of me figure out how to make it so that it doesn’t fill in two separate parts so that a line doesn’t for in the design. I’ve spent hours googling, watching YouTube, asking Reddit, I’ve tried messing with the angle and they start and stop points but nothing has fixed it at all. Does anyone know why I can do to fix this?!

https://user-images.githubusercontent.com/125830761/219973931-207ff179-6c24-46b5-8c1f-d0f7c5ff5dad.MOV

**Comment by kaalleen** [comment]
You could try to compensate this with better stabilizer. But also (as you already figured out) with start and stop commands and specific stitch angles. I'll attach a file for you were you can see the idea on how this could work. Ink/Stitch itself doesn't do pull compensation for this kind of problem (yet?)

![tatze](https://user-images.githubusercontent.com/36401965/220154060-f6ffd5ee-4a5d-4444-8019-1cc33393d1f2.svg)

**Comment by bianchifan** [comment]
Have a look at issue [#2068](https://github.com/inkstitch/inkstitch/issues/2068), same problem.

**Comment by kaalleen** [comment]
No further response. Closing.
