### ISSUE TITLE
Use webworker for realistic rendering

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#208]
I just learned about web workers, and they seem like a pretty good fit for realistic rendering.  The Print javascript could spawn a worker in page load to do the rendering in the background.  That way it would be ready by the time the user clicks the "realistic" checkbox and the rendering wouldn't slow down the browser experience for the user. 

OffscreenCanvas is probably useful here too.

**Comment by X3msnake** [comment]
Cool
![image](https://user-images.githubusercontent.com/11083514/41569165-9f12bbba-7361-11e8-9598-ef1cd2e12ea5.png)
