### ISSUE TITLE
Madiera Rayon Color

### ISSUE THREAD

**Issue by ncp1113** [inkstitch/inkstitch#2080]
I noticed on the Madeira Rayon palette that a color that was obviously gray (1151) was labeled Cadmium Orange. It is actually Silver Moon. I fixed it. I am attaching the new palette as a txt file because Github doesn't support gpl. 
[Madeira Rayon.txt](https://github.com/inkstitch/inkstitch/files/10785981/Madeira.Rayon.txt)

**Comment by kaalleen** [comment]
Oh nice, thanks!!
