### ISSUE TITLE
Inkstitch not displaying stitches after clicking on params.

### ISSUE THREAD

**Issue by rpspivey** [inkstitch/inkstitch#2082]
Equipment: Laptop computer with Windows 10 on laptop Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz with memory 16GB 
Software:  Inkscape is 1.2 , Python 3.11 , Javascript for Windows (build 1.8.0_361-b09)
Inkstitch 2.2.0 is  not showing stitch-out screen after clicking on graphic image and choosing params. 
I have uninstalled previous version of Inkscape and Inkstitch 
removed all folders that contained any files for both programs
re-installed Inkscape 1.2 and  Inkstitch 2.2.0 
Same issue - no stitch-out screen popup
There is no anti-virus program(s) running
Your help will be much appreciated!

**Comment by kaalleen** [comment]
Just to clarify. Are you saying that you see the params but not the simulator?
How long did you wait, do you run it on a big fill stitch?

**Comment by rpspivey** [comment]
Right, clicking on Params shows no simulator. I did notice in the
errors.log there are dependencies that are not found. I don't know how to
include them. Any clue?

**Comment by bianchifan** [comment]
drag& drop :)

**Comment by rpspivey** [comment]
> 

Would you like to elaborate further on "drag&drop" If this is an answer then drag what file to what location?

**Comment by kaalleen** [comment]
How long did you wait? Do you run it on a large fill stitch?

When the params window opens, you technically have everything you need for the simulator to run too. There could be two possible reasons why it is not showing up: 1. the calculation of your stitch out takes a long time, which means you'd need to wait longer or 2. there is a problem with your design and it cannot render. Try to run the stitch plan preview extension and see if it just takes long or errors out.

**Comment by bianchifan** [comment]
1. Click on a file which contains the error messages and drag it into the comment window
2. Mark the  errors displayed on the canvas, copy and paste them into the comment window

![Bildschirmfoto vom 2023-02-22 15-46-49](https://user-images.githubusercontent.com/17491743/220660397-dd2a3e38-2226-4492-a15d-8755328f8d26.png)

**Comment by rpspivey** [comment]
Inkscape does not display any output as in stitch plan preview or simulator or a stitch-out display when Params is chosen.
Here is the errors.log below. 

extension-errors.log

Extension "EPS Input" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: ps2pdf

Extension "XFIG Input" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: fig2dev

Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: gimp

Extension "Formula (pdflatex)" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: pdflatex

Extension "PostScript Input" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: ps2pdf

Extension "Optimized PNG" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: optipng

Extension "Export to PDF via Scribus" failed to load because a dependency was not met.
Dependency:
	type: executable
	location: path
	string: scribus

**Comment by rpspivey** [comment]
**[SOLVED] !!!!**  Even though there was no indication of an anti-virus program installed in Add or Remove Programs, there were SERVICES still running from a prior installation of Webroot Anti-Virus software.  I had to boot into SAFE MODE, go to C:\Program Files and delete the Webroot folder. Rebooted back into Windows 10 normally, installed Inkscape 1.2 and Inkstitch 2.2.0 and everything is working like it should. What a RELIEF!

**Comment by tyrosinase** [comment]
What if the real viruses were the antivirus programs we installed along the way? 😆
