### ISSUE TITLE
Current development releases by lexelby - fix prefs AND smoothing - make probs on Ubuntu 22.10

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2089]
When an existing design with defined "fill stitches" is loaded I can choose params in the case of "Ripple".
In the case of autofill or contour-fill I recieve an error.
Same error occurs when Trying to parm a new object, for ex. a simple circle or rectangle with a fill colour.
![Bildschirmfoto vom 2023-02-23 16-42-32](https://user-images.githubusercontent.com/17491743/221036655-824ba295-c38e-435a-8cf0-e036cbf09e49.jpg)
![Bildschirmfoto vom 2023-02-23 10-23-18](https://user-images.githubusercontent.com/17491743/221036666-51271cac-f68d-449e-9f07-fbadb19476d1.png)

**Comment by lexelby** [comment]
Got it, thanks!  I'll take a look.

**Comment by lexelby** [comment]
This is because I forgot to pack the tiles in the installation archive.  Oops!

**Comment by lexelby** [comment]
@kaalleen It's crashing because we pass an empty list of options for a param of type `combo`.  Do you think we can/should protect against that?

**Comment by kaalleen** [comment]
Hm yes, we maybe should. Although it'd always be our error - not user error.
