### ISSUE TITLE
Thread Color Management

### ISSUE THREAD

**Issue by hobbygirl** [inkstitch/inkstitch#2096]
I was following a tutorial on Youtube to create a color palette. https://youtu.be/4bcRVoKvzAw

The steps are:
open Inkscape
I imported a color palette and typed the color names.
I then went to extensions, inkstitch, thread color management, generate palette, split text.

I received the following error:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\palette_split_text.py", line 33, in effect
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by kaalleen** [comment]
Thank you for reporting this error. It has been fixed for the next release already. See issue #2055 where it has been first time reported.

Do you want to try a development release or rather wait for the next official release? I can also fix the file for you if you want to upload it here.

**Comment by hobbygirl** [comment]
Thank you so much. And yes, I will try the development release. 😊

**Comment by kaalleen** [comment]
Ok, great. We are working towards a new release, so we are happy if someone tries development releases and tests them. Any error which is showing up would be very, very interesting for us. This release contains some known issues though, but I think it is ok enough to post the link: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test

If you run an older macOS system none of these builds will work for you, but we can prepare one if you want us to.

**Comment by hobbygirl** [comment]
I will definitely test and report any errors I receive with details. 😊
