### ISSUE TITLE
Buttons in the simulate UI for speed up / slow down

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#21]
We have shortcut keys now:

* `+` or `=`: speed up
* `-`: slow down
* `r`: restart animation
* `q`: close

Make these more obvious, preferably with buttons with tooltips that mention the keyboard shortcuts.

**Comment by X3msnake** [comment]
Ctrl + Cursor UP - Speeds Up
Ctrl + Cursor DOWN - Slows Down

This is nice but is this intentional and just undocumented?

Would be cool if Ctrl + Left - restarted animation

**Comment by lexelby** [comment]
Yup, that's on purpose.  Actually, the up and down keys work even without control held down.  Left restarting might be nice, but ideally I'd like to make left and right move back and forward in time.  It's just a little tricky to do is all.

**Comment by X3msnake** [comment]
@lexelby that would be even more awsome

I noticed that +- on the numpad does not have any effect it would be great it it did, using +- on the write keyboard is kinda akward and up/down does not seam to work on windows
