### ISSUE TITLE
Locks and manual stitch placement?

### ISSUE THREAD

**Issue by rlevine** [inkstitch/inkstitch#2100]
Noob question. What's the history on explicitly disabling locks for manual stitch placement?

Even though I'm dropping the needle myself, I still need locks, and I don't want to add them manually every time. And I can just turn them off if I really don't want them.

ie, any reason not to change

```               
                # manual stitch
                if self.manual_stitch_mode:
                    patch = StitchGroup(color=self.color, stitches=path, lock_stitches=(None, None))
```
to

```               
                # manual stitch
                if self.manual_stitch_mode:
                    patch = StitchGroup(color=self.color, stitches=path, lock_stitches=self.lock_stitches)
```

in `lib/elements/stroke.py`? 

(With a corresponding update to the tooltip.)

**Comment by rlevine** [comment]
Probably should allow stop_after, trim_after and force locks, as well.

**Comment by lexelby** [comment]
The history is that we didn't allow disabling lock stitches per object in any way other than enabling manual stitch :)

**Comment by rlevine** [comment]
Cool! Any legacy concerns with enabling lock/trim/stop on manual stitches?
