### ISSUE TITLE
Mauvaises couleurs dans le fichier machine

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2106]
Je poste pour un membre du groupe facebook inkstitchfrance. Je n'arrive pas à comprendre le problème.

Elle a réalisé un motif contenant plusieurs couleurs. Quand elle l'enregistre en PES, il ne reste qu'une couleur, en JEF, il ne reste que 2 couleurs.

Je joins le fichier
![v5bis](https://user-images.githubusercontent.com/65076100/222810979-ab43ed50-4fa3-45ad-afaa-a28e03a0672b.svg)

Merci pour votre aide

**Comment by Marif91** [comment]
Je complète et je viens de découvrir qu'en supprimant les commandes du fichier, les couleurs sont de retour...

**Comment by bianchifan** [comment]
I just loaded your svg into my inkscape, there seem to be several probs..
1. wrong colors
I do not see any color definiton in the output files, I do not know why.
You should wail for the programmers.
But I can see that InkStitch generates 20 !! color blocks for both formats, for DST format as well (for campare).
For JEF  format 8 STOP cammands are included, that will result in 9 effective blocks when stitched out.
IMHO you should be able stitch your design just as you want.
For PES format every color block comes with a Command so you should be able to stich 20 different colors!!
But you must not change the color on every stop. You can remain and reduce the changes to 8, so you may stitch aot 9 colors as well.
At least you are lucky, some formats show very weired results.

2. Guided fill
I for myself have many problems with guided fill, I do not really understand.
What I can see so far is an unrecognized guide on the leaves.
They are stitched plain auto the guide lines are ignored.

Let's have a look on your leaves, f.e. feuille5.
First, the leave is defined, second the stop command. And then follow the guides, why?

**Comment by kaalleen** [comment]
I'll reopen this issue, stop commands should not lead to missing colors and it is definitely an issue within inkstitch that we should fix.

Thank you for reporting this issue. It is very valuable for us to receive such beautiful designs :)

It is possible that #1886 solves the issue.

**Comment by kaalleen** [comment]
@bianchifan this is a great example on how to use various stitch methods of the latest official release.It is well made. The issues you are seeing are actual Ink/Stitch issues. Ink/stitch handles stop commands wrong. The other issue you are seeing with the "guided fill" on the leaves are not actual issues. It is just a normal fill with stitch patterns applied. Just one of the blossoms is using guided fill.

The stop commands probably should have been trim commands though. But good for us as it reveals an Ink/Stitch problem.

**Comment by bianchifan** [comment]
>The other issue you are seeing with the "guided fill" on the leaves are not actual issues. It is just a normal fill with stitch patterns applied.
>
I didn't look very  deeply, I only saw the paths with markers.
Ok..the markers are pattern markers. But I do not see any pattern...
BTW, when I mark all leaves and open them in parameters I get a plain auto fill stitch.
when  close the params.. inkscape gets an internal error and closes, no more information.
For what the fuck are all those paths in the leavs groups??

> The stop commands probably should have been trim commands though. 

The stop command makes sense!
There are many embroidery machines out there which cannot trim and you're caused to do it manually, i.e. Singer, W6...
To get a chance for it.. you must place a STOP command ;)

**Comment by kaalleen** [comment]
I know that understanding the patterns can be a bit confusing, but try to be polite.
Have a look at the website: https://inkstitch.org/docs/stitches/patterns/ 
The patterns add or remove stitches from whatever element they are applied to. So if you use a stroke pattern on a normal fill stitch it would still look like a normal fill stitch, but with additional nodes where the pattern crosses the thread.

>  To get a chance for it.. you must place a STOP command ;)

That is interesting. Does your W6 actually handle stop commands?

**Comment by bianchifan** [comment]
> That is interesting. Does your W6 actually handle stop commands?
I'll check it later in a few days, currently my W6s are buried;)

> Je complète et je viens de découvrir qu'en supprimant les commandes du fichier, les couleurs sont de retour...
I felt myself free enough to add some more commands and varying some running stitches to get rid of a bunch of awful job stitches;)

[Fleus Marif91.pdf](https://github.com/inkstitch/inkstitch/files/10932850/Fleus.Marif91.pdf)
![Fleur Marif 1_](https://user-images.githubusercontent.com/17491743/224063141-af5b2cfe-a67e-4498-98a3-71469cb7fcc5.svg)
[Fleurs Marif91_ SF with colors.zip](https://github.com/inkstitch/inkstitch/files/10932859/Fleurs.Marif91_.SF.with.colors.zip)

**Comment by kaalleen** [comment]
Closing. The issue seems to be solved (20 exported color blocks in pes as well as in jef).
Please open a new issue if similar problems show up with current Ink/Stitch versions.

Colors in pes may differ from original, but there are open issues about this topic.
