### ISSUE TITLE
Colonnes satin 

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2108]
Je travaille sur Mac avec Big Sur, Inkscape 1.2.2 et Inkstitch 2.2.0
Quand je convertis une ligne en colonne satin, les deux rails sont toujours inversés comme dans l'exemple ci-dessous
![colonne satin](https://user-images.githubusercontent.com/65076100/222916909-1a294c8f-e927-4065-a068-35e6e6bbb18c.svg)

**Comment by kaalleen** [comment]
Oh that... Yes, that is also caused by the shapely version for macOS. Sorry about that.
We already fixed it for the next release.
