### ISSUE TITLE
Remplissage guidé avec décalage parallèle

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2109]
Je travaille sur Mac avec Big Sur, Inkscape 1.2.2 et Inkstitch 2.2.0

Le remplissage guidé ne fonctionne qu'avec l'option copier, quand je demande un décalage parallèle, j'ai le message suivant :

ath3911: erreur : Erreur pendant l'auto-remplissage. Cela veut dire que Ink/Stitch a un problème.

Si vous désirez nous aider à améliorer Ink/Stitch, veuillez SVP copier/coller ce message dans un nouveau rapport d'erreur (issue) ici: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 566, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 677, in do_guided_fill
  File "lib/stitches/guided_fill.py", line 34, in guided_fill
  File "lib/stitches/guided_fill.py", line 240, in intersect_region_with_grating_guideline
  File "lib/stitches/guided_fill.py", line 196, in clean_offset_line
  File "lib/stitches/guided_fill.py", line 118, in repair_multiple_parallel_offset_curves
ValueError: max() arg is an empty sequence
![remplissage guide](https://user-images.githubusercontent.com/65076100/222917340-888f40a9-2463-40e7-a740-430760d0d415.svg)
![Capture d’écran 2023-03-04 à 17 21 40](https://user-images.githubusercontent.com/65076100/222917366-455fc4f2-9699-4810-b3c0-7f14e6ba7124.png)

**Comment by kaalleen** [comment]
Thank you for your error report. This is really helpful especially when you send a file along.
We have seen this error before, have a look over here: #1811 
There is no fix other than that we had to change the shapely version shipped with the macOS release.

**Comment by kaalleen** [comment]
Turns out that on some systems the version for older macOS systems runs better, even for newer systems ...
Issue seems to be resolved with the newest update ... if someone still runs into the issue it is worth trying the build for older macOS systems as well.
