### ISSUE TITLE
Give Inkstitch branding guide visibility in the website

### ISSUE THREAD

**Issue by X3msnake** [inkstitch/inkstitch#211]
@kaalleen we need to give some visibility to the branding guide and respective files on the offical website, to make sure people have guidelines on how to use the brand. 

Any ideas how we should go about that? maybe define a section on the site for taht with a small sumary and link to the original brand development issue? #115

**Comment by kaalleen** [comment]
I am a bit short in time... so just a quick remark.

I edited the existing "tutorial" on the Ink/Stitch logo sample file and added a link into the tutorial navigation. The whole tutorial area isn't fully organized yet. But it's the best place where I can see it for now: https://inkstitch.org/tutorials/ressources/inkstitch-logo/

If you could write a small summary, I'd be thankful. I wouldn't know what to write ;)
If you rather have me to add it in, you can also post the summary here.

You can find the file here: https://github.com/lexelby/inkstitch/blob/gh-pages/_tutorial/inkstitch-logo.md

**Comment by X3msnake** [comment]
@kaalleen awsome work as always Master.

Thank you for your time. I will see if i can cook up some text for the section. I will upload directly save you the time ;)

**Comment by AkiraNorthstar** [comment]
Can we close this issue?
