### ISSUE TITLE
Satin column: Object has too few subpaths.

### ISSUE THREAD

**Issue by chanchan046** [inkstitch/inkstitch#2112]
Hello! beginner at all of this :) I made this patch and all 3 elements work separately. however, when i try and use param with everything i get this message : 

object2595: error: Satin column: Object has too few subpaths.  A satin column should have at least two subpaths (the rails).

I don't understand this as I said, everything works separately. I've tried rearanging the order of the boarder and changing the color and still don't understand. 

![Preview 3_4_2023 1_08_09 PM](https://user-images.githubusercontent.com/99788267/222924410-01ba9273-3576-4000-91aa-6555587e7180.png)
![Preview 3_4_2023 1_08_30 PM](https://user-images.githubusercontent.com/99788267/222924411-ee6f9e28-ae3c-452a-bcf5-58aaa131d089.png)
![Preview 3_4_2023 1_08_57 PM](https://user-images.githubusercontent.com/99788267/222924412-af637186-7654-4ed2-8463-72878c7e244d.png)
![Embroidery Params 3_4_2023 1_09_23 PM](https://user-images.githubusercontent.com/99788267/222924456-801dbf82-0854-48c1-8670-cd36e8b98ac1.png)
![_use me pes - Inkscape 3_4_2023 1_09_29 PM](https://user-images.githubusercontent.com/99788267/222924465-47d99315-a814-4374-8e1e-067b1c49e14e.png)

**Comment by kaalleen** [comment]
You are not supposed to use params on everything at the same time. You can see everything at the same time with the simulator or the print preview or pdf output. The params dialog will try to apply a not suitable stitch type on your strokes if you select them at the same time with a satin column. I know this is a bit confusing, but that is how it works.

**Comment by chanchan046** [comment]
Oh okay! Thank you so much for the help that makes sense!
