### ISSUE TITLE
Longueur des points en broderie ondulée

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2116]
Le fond de mon motif est constitué de 3 feuilles en broderie ondulée, la longueur de points est fixée à 4mm, MAIS après les premières lignes, la longueur des points est raccourcie. Pourquoi ce changement ?
Merci par avance,
Marif
![orchidees](https://user-images.githubusercontent.com/65076100/223219655-19b92752-6ceb-44d3-a820-7b977693ea7b.svg)
![broderieondulee](https://user-images.githubusercontent.com/65076100/223239582-410c0f49-3b09-4d93-b0c5-72c7ffceebea.jpg)

**Comment by bianchifan** [comment]
1st..excellent design!
Your problem depends on your chosen  "runnin' stitch tolerance"!
You have two paths of different length and a single stitch length of 4.
The algorithm must do two things: 
- it must find a  factor for the single stitch to meet the given length
- it must interpolate the length and transform path 1 into path 2.
For both aims are not possible to fulfill at the same time a couple of stitches have to be included and another couple have to be deviated, resulting often in a bunch of variations.
In your case the tolerance is 0.2 mm and the algorithm decides not only to shorten the lenght, it cuts it by half when the length exceeds 4.2 mm (for the reason you mast ask the developers).

![Bildschirmfoto vom 2023-03-07 15-27-15](https://user-images.githubusercontent.com/17491743/223461480-1239d456-d790-42b9-875f-cc67215a0039.jpg)

Have a look at a variant with a tolerance of 1mm!
![Bildschirmfoto vom 2023-03-07 15-36-40](https://user-images.githubusercontent.com/17491743/223462502-a25e94fa-7eab-4093-a9b9-1317f9e252ba.jpg)

**Comment by Marif91** [comment]
Merci @bianchifan  !!!
J'avais bien repéré le problème dans la simulation mais je n'arrivais pas à le comprendre. Je comprends mieux à quoi sert la tolérance. Bravo pour votre explication !
