### ISSUE TITLE
Current dev versions by Kaalleen do not save in any stitch format

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2119]
While the Glib prob with Linux Mint 20.3 seems to be solved I cannot save a design in  a chosen stitch format.
Last working version with emb-format-save for me me are:
claudine-addrandom
kaalleen-gradient-fill

![Bildschirmfoto vom 2023-03-07 14-12-06](https://user-images.githubusercontent.com/17491743/223468286-700e7dea-2829-45d0-813e-6bb24b96a748.png)

**Comment by rlevine** [comment]
Hmm. This picked up the pyembroidery change that I later reversed from my branch. Was this built on an earlier version? Not sure why it’s showing up elsewhere. It looks fine from here, but can one of you confirm that I haven’t merged anything into pyembroidery? Thanks.

**Comment by kaalleen** [comment]
Everything good, pyembroidery hasn't had any commits lately. The current main just links to a commit which is only on your comptuer :D And the broken link has made it's way into various development branches by now.

**Comment by rlevine** [comment]
Thanks!
