### ISSUE TITLE
Inkscape has received additional data (macOS Ventura)

### ISSUE THREAD

**Issue by Smiles1025** [inkstitch/inkstitch#2132]
New to both Mac and InkStitch **yikes**. 

Having an issue with InkStitch-->Params.
think i followed all the steps to install, but may be missing something or is it perhaps os version?
iMac 13.2.1 (22D68)

Traceback (most recent call last):
  File "numpy/core/__init__.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "numpy/core/multiarray.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "numpy/core/overrides.py", line 7, in <module>
ImportError: dlopen(/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: @loader_path/../../libopenblas.0.dylib
  Referenced from: <AA8DB9E1-AD3F-3749-8425-F68C3452DB9A> /Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: tried: '/Applications/Inkscape.app/Contents/Resources/lib/libopenblas.0.dylib' (no such file), '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libopenblas.0.dylib' (no such file), '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/../../libopenblas.0.dylib' (code signature does not cover entire file up to signature in <9112000D-375C-34F0-9A66-9D68F91A12CD> '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib' (signed 0x03D76000, expected 0x03DC57C0) for '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib'), '/System/Volumes/Preboot/Cryptexes/OS@loader_path/../../libopenblas.0.dylib' (no such file), '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/../../libopenblas.0.dylib' (code signature does not cover entire file up to signature in <9112000D-375C-34F0-9A66-9D68F91A12CD> '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib' (signed 0x03D76000, expected 0x03DC57C0) for '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib'), '/usr/local/lib/libopenblas.0.dylib' (no such file), '/usr/lib/libopenblas.0.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 25, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "inkex/__init__.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "inkex/extensions.py", line 34, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "inkex/elements/__init__.py", line 13, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "inkex/elements/_polygons.py", line 31, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "inkex/bezier.py", line 29, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "numpy/__init__.py", line 150, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "numpy/core/__init__.py", line 48, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/inkstitch"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so, 0x0002): Library not loaded: @loader_path/../../libopenblas.0.dylib
  Referenced from: <AA8DB9E1-AD3F-3749-8425-F68C3452DB9A> /Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so
  Reason: tried: '/Applications/Inkscape.app/Contents/Resources/lib/libopenblas.0.dylib' (no such file), '/Applications/Inkscape.app/Contents/Resources/lib/gdk-pixbuf-2.0/2.10.0/loaders/libopenblas.0.dylib' (no such file), '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/../../libopenblas.0.dylib' (code signature does not cover entire file up to signature in <9112000D-375C-34F0-9A66-9D68F91A12CD> '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib' (signed 0x03D76000, expected 0x03DC57C0) for '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib'), '/System/Volumes/Preboot/Cryptexes/OS@loader_path/../../libopenblas.0.dylib' (no such file), '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/numpy/core/../../libopenblas.0.dylib' (code signature does not cover entire file up to signature in <9112000D-375C-34F0-9A66-9D68F91A12CD> '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib' (signed 0x03D76000, expected 0x03DC57C0) for '/Users/smiles4grin/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libopenblas.0.dylib'), '/usr/local/lib/libopenblas.0.dylib' (no such file), '/usr/lib/libopenblas.0.dylib' (no such file, not in dyld cache)

[1565] Failed to execute script inkstitch

![bekind2](https://user-images.githubusercontent.com/127538698/224396310-e8a7cfed-af80-47e7-982c-72a3a1338111.svg)

**Comment by kaalleen** [comment]
Which Ink/Stitch version did you install?

**Comment by kaalleen** [comment]
Is this still an issue with Ink/Stitch v3.0.1?

**Comment by kaalleen** [comment]
Should be fixed with the newest release. Therefore I'm going to close the issue. Please send us your protest if I am wrong ...
