### ISSUE TITLE
Autoroute satin stitch not working properly

### ISSUE THREAD

**Issue by hajones2** [inkstitch/inkstitch#2139]
Hi! When I go to use the autoroute satin stitch function on my design, it makes the letter very small in the wrong part of the design. I've attached pictures of what it is doing. The bottom picture is what the letter should look like without the autoroute feature applied.

<img width="158" alt="Screen Shot 2023-03-12 at 11 20 56 PM" src="https://user-images.githubusercontent.com/127712611/224607046-a8d0b62a-5862-4717-9f7d-4ab4884ef17a.png">
<img width="107" alt="Screen Shot 2023-03-12 at 11 21 06 PM" src="https://user-images.githubusercontent.com/127712611/224607056-58bd85dc-7609-4954-8f0d-e43702a306c5.png">

**Comment by kaalleen** [comment]
Thank you for taking the extra step to report this issue. To be able to fix the issue we would need to have a look at the svg file though. Could you upload your svg?

**Comment by kaalleen** [comment]
Possibly related to #376

**Comment by kaalleen** [comment]
Try to select your satins and run `Path > Object to Path` (Shift + Ctrl +C)
Does this solve your issue?

**Comment by hajones2** [comment]
This worked perfectly. Thank you so much!

**Comment by kaalleen** [comment]
Thank you for your feedback :)
