### ISSUE TITLE
extra lock after trim?

### ISSUE THREAD

**Issue by rlevine** [inkstitch/inkstitch#2142]
I'm poking at my Tajima stop question, and hit some behavior I don't understand. 

I don't think this is operator error, but I always surprise myself!

This file has two small satin columns,  color change between them, locks allowed but not forced, and "Trim After" selected in params for the first column.

What I'm seeing in the preview and output files is two locks at the end of the first column, with the trim between them. I'd expect one lock, followed by a trim.

I discovered the issue stitching out; the machine completed the lock, trimmed, repeated the lock, and then did a machine-initiated trim because of the following needle change.

I'm running Ink/Stitch out of the main branch, so this is the new lock code.

Attached are the .svg file and a binary dump of the stitches in that area in the .dst file. (The .csv shows the same, obviously without the expansion for the .dst trim.)

<img width="1082" alt="Screen Shot 2023-03-14 at 5 16 32 PM" src="https://user-images.githubusercontent.com/2294569/225170783-22af5e4b-8c73-4fa1-9b7b-89bd2bb47f6d.png">

![trim_before_tack2](https://user-images.githubusercontent.com/2294569/225170723-67559744-070a-4bea-b5ae-a07ab97171ae.svg)

**Comment by kaalleen** [comment]
Hups, thank you :)

**Comment by rlevine** [comment]
Perfect! Thanks!

**Comment by rlevine** [comment]
Just what I expected to see.

<img width="592" alt="Screen Shot 2023-03-15 at 9 11 16 AM" src="https://user-images.githubusercontent.com/2294569/225372047-0c8e1f36-2f88-469a-a734-06a62d46d3a7.png">

**Comment by kaalleen** [comment]
Great, thank you for your feedback :)
