### ISSUE TITLE
Use Command markers for TRIM and STOP

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#215]
Much like with #192, use Command markers (Symbols) to denote STOP and TRIM.  This would replace the checkboxes in Params, "TRIM after" and "STOP after".  It would be visually obvious that a stop or trim happens after an object, unlike with the current checkboxes.

**Comment by wwderw** [comment]
Maybe scissors for a trim and a palm facing hand for the stop symbols?  I thinking stop needs a different symbol then the one using for "end" on the fill.  Or maybe a red square if the hand palm might not work.

**Comment by lexelby** [comment]
I love the scissors idea.  Maybe the symbol for "pause" in a media player, to differentiate it from the "stop" and "play" for fill stitch?  Or maybe the fill stitch one needs to be different.

**Comment by wwderw** [comment]
Pause symbol, I like that one as that is essentially what a stop is when it's not at the end of a design.

**Comment by lexelby** [comment]
Imagine we get rid of the "TRIM after" and "STOP after" checkboxes in favor of the symbol commands.  What should Ink/Stitch do with existing SVGs that still have those params set?

I'm thinking Ink/Stitch should still honor those params if they're set, but the Params UI won't show those checkboxes.  We'd also add a new extension, "Convert legacy TRIMs and STOPs" which would remove those old params and add in the equivalent Commands instead.  My hope is that there still should be relatively few SVGs out there that have the old commands.

Would this work?  Thoughts/ideas?

**Comment by lexelby** [comment]
I'm working on this, but I've hit a pretty nasty stumbling block.  I wish I'd noticed it before now.

Let's say you add a "fill end" command to an object and move it to where you want it.  You can use the Node tool to move the endpoint of the connector to set it exactly where you want it.  Great!

If you move either the command symbol object or the fill object, Inkscape will reposition  the connecting line to go between the two.  So far so good.

Problem is, if you run _any_ extension, it will also reposition all connecting lines in the document!  It tries to ensure that the connecting line goes between the centers of the objects.  This is no good if you've moved the connecting line to not go directly between the object centers.

You can get around this by never moving the connecting line's nodes yourself, and always rely on Inkscape's automatic positioning.  But for things like satin columns or running stitch, Inkscape will always have the line go directly to the center, since the object has no fill set.

I'm not sure what (if anything) to do about this.

**Comment by lexelby** [comment]
> But for things like satin columns or running stitch, Inkscape will always have the line go directly to the center, since the object has no fill set.

Okay, this isn't entirely true.  Inkscape effectively casts a ray out to from the symbol to the object and stops when it hits any part of the object.  So you can still get fairly good control for most objects just by moving the symbol around.

I guess this isn't the end of the world, but it is kind of obnoxious.  I can disable the automatic repositioning by removing the `inkscape:connection-type` attribute, but then there's no obvious way for the user to see which symbol belongs to which object, if they have moved the connectors or the objects.

Looks like we'll just have to leave this how it is.  Perhaps we can make a feature request to the Inkscape folks, along the lines of having some kind of offset for the endpoint of the connector.

**Comment by lexelby** [comment]
implemented in #224
