### ISSUE TITLE
Absturzbericht 

### ISSUE THREAD

**Issue by evils87** [inkstitch/inkstitch#2152]
Es ist ein unerwarteter Fehler aufgetreten. Das heißt, dies ist ein Fehler in Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern,
- kopiere die gesamte Fehlermeldung
- speichere die SVG-Datei ab und
- erstelle einen Fehlerbereicht (New Issue) auf https://github.com/inkstitch/inkstitch/issues

Sende die Fehlerbeschreibung und (wenn möglich) auch die SVG-Datei.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/troubleshoot.py", line 29, in effect
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment]
Danke für deinen Fehlerbericht. Der Fehler wird von sehr kleinen Elementen in deiner Datei ausgelöst. Wenn du sie löscht, sollte es wieder funktionieren. Je nach Design kann es sinnvoll sein, diejenigen Elemente auszuwählen, die behalten werden sollen, dann die Auswahl umzukehren und die Übrigbleibsel dann zu löschen.

Duplicate of #1742

**Comment by evils87** [comment]
Danke :)
