### ISSUE TITLE
About Radial Fill Stitch

### ISSUE THREAD

**Issue by Customexico** [inkstitch/inkstitch#2155]
Hello,
Do you have any good ideas on how to achieve a fan-shaped fill stitch like the one in this photo with Inkstitch?
Perhaps stitched on radial...
![image](https://user-images.githubusercontent.com/128409381/226431904-09869e2a-59b9-487b-a185-f6a30eb41d98.png)

**Comment by kaalleen** [comment]
Hm, the he closest you can get at the moment is a satin stitch with a maximum stitch length set. Sadly we only have a random option in the development branches to spread the split stitches. This would give you a more irregular look than the one that you are looking for.

**Comment by Customexico** [comment]
hanks for the reply. I see that it is currently not feasible....
I solved the problem by creating a program to edit the SVG file directly.
![image](https://user-images.githubusercontent.com/128409381/227705303-24758247-aa19-4d2b-bdd8-cc41dcb17e38.png)

**Comment by lexelby** [comment]
Nice!  I'm curious what your stitch placement looks like.  Would you mind enabling needle points in the simulator and taking another screenshot?

**Comment by Customexico** [comment]
Is this OK?
![image](https://user-images.githubusercontent.com/128409381/227725223-d1a5b27f-3818-4132-add3-339eec60a68a.png)

**Comment by lexelby** [comment]
Yes, thank you!  I wonder if you would mind sharing your program?  I'm interested in seeing your approach.  Even if it's just a one-off script specific to your situation, it would still be useful to take a look.

**Comment by Customexico** [comment]
OK. It is written in VB.NET.

Node placement, etc., is done manually.

Draw a symmetrical arc and use the Inkscape function to place the nodes equally spaced.
Copy this arc and place a shrunken arc below it.
![image](https://user-images.githubusercontent.com/128409381/227976587-15abf267-8d53-4c91-b876-cd671a0767d7.png)


Output the coordinates of the nodes of the upper arc and the lower arc to separate CSV files using ["Nodes to CSV"](https://github.com/camrbuss/nodes_to_csv).
![image](https://user-images.githubusercontent.com/128409381/227977186-90eea272-ad1c-4ede-9200-4c19cf1490f9.png)

--This is the end of the manual process.

The output CSV is imported into the program below and the SVG code is pasted into the SVG file to be edited.

The SVG code is output to the console for personal use and because it is an improvised program.

The program I created has been published below.
(To be honest, the coding is pretty rough...)
https://github.com/Customexico/Radial_Stitch-

![image](https://user-images.githubusercontent.com/128409381/227980815-3714b97b-b026-4852-ae16-76e9cea6a775.png)

**Comment by lexelby** [comment]
Thank you!
