### ISSUE TITLE
add helpful error message if inkstitch binary is run directly

### ISSUE THREAD

**Issue by jondale** [inkstitch/inkstitch#2161]
[edited by @lexelby] Ink/Stitch gives the confusing error message shown below if you try to run it directly.  We should detect this case and print a helpful hint rather than showing an ugly error.

---------------------

I'm trying to install this on 10 laptops for a makerspace to use with the embroidery machine so I have gone through this process multiple times on fresh installs and it seems the same error every time.

I've seen the references to this error when inkscape is installed via snap.  That is not the case here, however.  This is a fresh install of Ubuntu 22.04 where Inkscape is installed via apt using the inkscape ppa (also tried just the default repos).  

```
$ sudo add-apt-repository ppa:inkscape.dev/stable
$ sudo apt install inkscape
```

Inkscape version 1.2.2
Inkstitch version 2.2.0 installed via .deb

```
$ /usr/share/inkscape/extensions/inkstitch/bin/inkstitch
Traceback (most recent call last):
    File "inkstitch.py", line 62, in <module>
AttributeError: 'NoneType' object has no attribute 'title'
```

This seems fairly reproducible for me.  Any guidance?

**Comment by bianchifan** [comment]
I cannot follow..??
Ubuntu 22.04 ..got it.
Inkscape 1.2.2 via apt ..ok!
InkStitch via deb .. should work.

To catch a traceback you must first load an SVG, you must select a path to do something with and you must select an inkstitch command

You didn't specify anything :(

My advice:
Give a manual install a try!
Uncompress the tar.gz file into the users local inkscape config:
~/.config/inkscape/extensions/

This works like a charm and every user may choose an individual version.. InkStitch is under heavy development at time and a bunch of new fascinating features are waiting to be enjoyed!

**Comment by lexelby** [comment]
It's so cool that you're using Ink/Stitch for your makerspace!  Hopefully we can get you up and running.

```
$ /usr/share/inkscape/extensions/inkstitch/bin/inkstitch
```

The problem is that you're running inkstitch directly.  It's not a standalone program; it's an extension for Inkscape.  After installing it, you should be able to find an Ink/Stitch menu under the Extensions menu in Inkscape (you might need to restart Inkscape first).   That's your entry point.

I'm going to turn this issue into a feature request to add a hint about not running inkstitch directly, so users don't get this ugly error.

**Comment by jondale** [comment]
Thank you both for replying.  We're a little familiar with how it works and do classes on it to authorize use of the embroidery machine at the space.  It works fine on other systems (different OS or distro).

The reason that I tried running it from command line was to get an error message.  When running it in Inkscape itself, no window pops up and no error is shown.

I'm happy to try and get more information if I know what would be useful. The laptops ares basically a stock install of Ubuntu 22.04.  I do have a script that installs some other packages (freecad, kicad, kdenlive, arduino, etc) as well but it's pretty basic stuff.

My current solution, for the space laptops, is to use an AppImage of Inkscape.  Inkstitch seems to work just fine with that.   It is not ideal though.  I would much prefer to use Inkscape installed from the apt repo as it would require less manual intervention from me when upgrading.

**Comment by kaalleen** [comment]
Could you try to install the tar.xz version and post your path to the inkscape extensions if this is not working neither?

**Comment by kaalleen** [comment]
I think we do that now...
