### ISSUE TITLE
DST files: embriodery machine refuses monochrome patterns (CO: 0 in header)

### ISSUE THREAD

**Issue by felsgaertner** [inkstitch/inkstitch#2162]
Hello,

my machine (Singer Legacy SE300) refuses monochrome DST files. Using a hexdump viewer, the DST header contains *CO: 0*. After changing that value to at least 1 like *CO: 1* the machine opens the DST file. So at least this machine expects an integer greater than zero.

As I read from https://edutechwiki.unige.ch/en/Embroidery_format_DST, the CO value is the number of colors.  
The description is a bit misleading, as it also mentions color *changes*.

I would like to add three files in a ZIP archive for demonstration:
* Demo.svg - the original test vector file
* Demo-0.dst - the file as saved from InkStitch, with CO: 0 --> machine shows error.
* Demo-1.dst - the file modified for CO: 1 --> machine loads file.

Unfortunately GitHub does not accept my upload at this time. So I just add the hexdump output here:

Demo-0.dst:
~~~text
00000000  4c 41 3a 55 6e 74 69 74  6c 65 64 20 20 20 20 20  |LA:Untitled     |
00000010  20 20 20 0d 53 54 3a 20  20 20 20 31 33 33 0d 43  |   .ST:    133.C|
00000020  4f 3a 20 20 30 0d 2b 58  3a 20 20 32 34 38 0d 2d  |O:  0.+X:  248.-|
00000030  58 3a 20 20 32 34 38 0d  2b 59 3a 20 20 32 34 38  |X:  248.+Y:  248|
00000040  0d 2d 59 3a 20 20 32 34  38 0d 41 58 3a 2b 20 20  |.-Y:  248.AX:+  |
00000050  20 20 30 0d 41 59 3a 2b  20 20 32 34 38 0d 4d 58  |  0.AY:+  248.MX|
00000060  3a 2b 20 20 20 20 30 0d  4d 59 3a 2b 20 20 20 20  |:+    0.MY:+    |
00000070  30 0d 50 44 3a 2a 2a 2a  2a 2a 2a 0d 1a 20 20 20  |0.PD:******..   |
00000080  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
~~~

Demo-1.dst:
~~~text
00000000  4c 41 3a 55 6e 74 69 74  6c 65 64 20 20 20 20 20  |LA:Untitled     |
00000010  20 20 20 0d 53 54 3a 20  20 20 20 31 33 33 0d 43  |   .ST:    133.C|
00000020  4f 3a 20 20 31 0d 2b 58  3a 20 20 32 34 38 0d 2d  |O:  1.+X:  248.-|
00000030  58 3a 20 20 32 34 38 0d  2b 59 3a 20 20 32 34 38  |X:  248.+Y:  248|
00000040  0d 2d 59 3a 20 20 32 34  38 0d 41 58 3a 2b 20 20  |.-Y:  248.AX:+  |
00000050  20 20 30 0d 41 59 3a 2b  20 20 32 34 38 0d 4d 58  |  0.AY:+  248.MX|
00000060  3a 2b 20 20 20 20 30 0d  4d 59 3a 2b 20 20 20 20  |:+    0.MY:+    |
00000070  30 0d 50 44 3a 2a 2a 2a  2a 2a 2a 0d 1a 20 20 20  |0.PD:******..   |
00000080  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
~~~

So to fix this bug, I suggest to place the number of colors used into CO:, not the color changes. The question is - what meaning is correct?

Thanks.

**Comment by felsgaertner** [comment]
This is the ZIP file with the mentioned files: [Demo.zip](https://github.com/inkstitch/inkstitch/files/11044574/Demo.zip)

**Comment by bianchifan** [comment]
> Using a hexdump viewer, the DST header contains _CO: 0_.
> 

I do not know your SE300 machine.
I know that the EM200 comes from the same manufacturer as my W6 machines, maybe they are quite similar.
Normally, the EM200/Superb are feeded with "XXX" stuff.
Perhaps you may check it...

> As I read from https://edutechwiki.unige.ch/en/Embroidery_format_DST,

MAybe you should read more carefully, the decimal number following the CO command counts the number of COLOR CHANGE RECORDS!
zero change records -> only ONE color -> monochrome.
I never digitized a monochrome picture but i have a few monochrome files in my sewing pattern directory. they all contain "CO:  0" in the header.

_LA:2               
ST:   8484
CO:  0
+X:  450
-X:  449
+Y:  536
-Y:  535
AX:-  232
AY:-  281
MX:+    0
MY:+    0
PD:******
       ......_

**Comment by felsgaertner** [comment]
Ok, I might be the machine itself. If I change the number to non-zero, it works.

What do you mean with "XXX" - is that a DST control code?
> Normally, the EM200/Superb are feeded with "XXX" stuff.

Meanwhile I fix the files using this bash loop and the bbe (binary block editor) utility:
~~~shell
for a in *.dst; do mv "$a" tmp; cat tmp | bbe -e 's/CO:  0/CO:  1/' > "$a"; rm tmp; done
~~~

**Comment by bianchifan** [comment]
"XXX" is  a proprietary Singer format used on all actual Singer embroidery machines.

**Comment by rlevine** [comment]
As @bianchifan has said, the color field in the .dst file header is for the number of color _changes_ in the design, or more accurately, the number of commands to change needles. The machines for which the .dst format was originally created don't have any notion of colors, they're simply presented with a needle change command in the file, and they'll either stop and wait for the operator to change needle bars, or possibly rethread a needle, or they'll select the "next" needle from a list entered by the operator. 

However, I believe some machines that have since adopted the .dst format as a legacy compatibility format don't quite stick to the file spec. Some embroidery software will permit users to force a first color change at the beginning of the file, supposedly because some machines will require an initial color setting. A side effect of forcing an initial color change will be to always make sure the header color field in a .dst file is set to a positive integer.

Your Singer may be one of those machines, as I've seen other comments on the net about the machine refusing to read some .dst files. For whatever reason, there may be a check in the firmware for a non-zero value in that field.

@lexelby or @kaalleen, is there a way to force a color change that will result in an extra needle change being written to a .dst file?

**Comment by lexelby** [comment]
One thing about edutechwiki: the creator and some of the contributors are contributors here, so we shouldn't necessarily treat it as an independent source of truth.  We could all be wrong together ;)

I would be interested to see what DST files in the wild look like, especially files created by Tajima themselves.  Do they have CO set to 0 or 1 for monochrome files?  If there's any kind of agreement between files out there in the wild, they we should follow that convention.  Then we can add an advanced setting for singer machines if needed.

**Comment by rlevine** [comment]
I agree with @bianchifan; I have one of those prehistoric sewing robots!

Apologies I wasn't clear; I'm not suggesting changing how the file is encoded to .dst. I was looking for an action in Ink/Stitch that would create a color change in the .svg file without adding a second stitchable object in a different color.

@felsgaertner, can your Singer SE300 read the file if you save it as a .xxx file from Ink/Stitch? (Without hacking the CO field.) If so, that would be a way to deal with the unreadable .dst files.

However, I'm also curious about whether we're getting the header semantics correct when we're writing a .dst file. The command for a "color change" in a .dst file is the same as a "stop." They both produce a needle change record, with last byte 0b11000011. They're different opcodes in our .svg file, but by the time they're read from the .dst file by my Tajima machine, they both produce the same result: in manual mode, the machine will stop; in automatic mode, it'll change needles to the next needle I've specified in the console needle list. If I put two objects in my file, in different colors, and add a stop after each one, my machine will either stop or automatically switch needle bars three times.

What I would expect in the .dst header is that the CO field should contain the number of 0b11000011 needle changes in the file, ie the the count of stops plus the count of color changes in the .svg file.

The current implementation is using .svg command semantics when it writes the .dst header: 

```
    def count_stitch_commands(self, command):
        count = 0
        for stitch in self.stitches:
            flags = stitch[2] & COMMAND_MASK
            if flags == command:
                count += 1
        return count

    def count_color_changes(self):
        return self.count_stitch_commands(COLOR_CHANGE)
```

When `count_stitch_commands()` is fed a 5, the mask for color change, it only reports .svg color changes, not the .dst stop.change total. Pyembroidery does use NEEDLE_SET for formats that do not explicitly change colors, but are changing needles. Using that for .dst files, combining .svg STOPS and COLOR_CHANGEs might be a possible solution.

**Comment by rlevine** [comment]
> One thing about edutechwiki: the creator and some of the contributors are contributors here, so we shouldn't necessarily treat it as an independent source of truth. We could all be wrong together ;)
> 
> I would be interested to see what DST files in the wild look like, especially files created by Tajima themselves. Do they have CO set to 0 or 1 for monochrome files? If there's any kind of agreement between files out there in the wild, they we should follow that convention. Then we can add an advanced setting for singer machines if needed.

Cool! I'll reach out to the Tajima Pulse folks, and see if they'll answer a question about the format.

**Comment by lexelby** [comment]
> I was looking for an action in Ink/Stitch that would create a color change in the .svg file without adding a second stitchable object in a different color.

I think adding a stop command in the SVG should have that effect.

**Comment by lexelby** [comment]
> When count_stitch_commands() is fed a 5, the mask for color change, it only reports .svg color changes, not the .dst stop.change total.

You're right!  That's a bug in DstWriter.  It should count color changes AND stops and put the sum in the CO field.

**Comment by felsgaertner** [comment]
Thanks so far.

For now, I will test the XXX export.  
Will there be a new release of InkStitch that includes this PR?

**Comment by rlevine** [comment]
Hmm. You can tell I haven't used submodules! @lexelby: Main in inkstitch is protected. Do I need to do the bump as a separate PR?

**Comment by rlevine** [comment]
@felsgaertner The prerelease builds are here:

[https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rlevine-bump_pyembroidery](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rlevine-bump_pyembroidery)
