### ISSUE TITLE
Naked Emilio

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2164]
Someone on the Brother embroidery group (hi, Nan!) requested a plain slab serif font and Emilio 20's core worked great for that. It's pretty easy to just delete the frame on the finished text, but I decided hey, it's only the basic alphanumeric glyphs, might as well do it at the right-arrow file level. So here it is, if anybody needs it. If it goes into the distro it might need a different name (Emilio 20 Frameless?) versus just naked "Emilio," but that's an easy fix.

[emilio.zip](https://github.com/inkstitch/inkstitch/files/11063688/emilio.zip)

**Comment by tyrosinase** [comment]
(maybe my issue name wasn't the best choice, I just posted a link to FB with my biz account that came up with that in the preview, please don't suspend my account FB :laughing: )

**Comment by CELIAIMBERT** [comment]
Good idea!!!
I'm working on a applique embroidery version.
I've check you version and I have to work a little on the E and F to rearrange the satin columns but it will be ok quickly.

**Comment by CELIAIMBERT** [comment]
Here is the corrected version

[Emilio_20_simple.zip](https://github.com/inkstitch/inkstitch/files/11233035/Emilio_20_simple.zip)
