### ISSUE TITLE
Please select at least one stroke to convert to a satin column.

### ISSUE THREAD

**Issue by chubean** [inkstitch/inkstitch#2170]
Interesting issue.  I created a square pattern for satin stitch in a vector program on my phone.  It won't convert to a satin.  The only thing I can think of is, I used rotation on the phone to turn the artwork as I laid down nodes with the bezier tool.  If I copy manually with the bezier tool in inkscape, it will convert.  Just thinking out loud, but could the rotation when creating on the phone have caused the inability to convert?
Yes, I know the conversion to satin stitch looks a little wonky.  I will learn how to make that look better with practice.

![Screenshot from 2023-03-25 10-06-36](https://user-images.githubusercontent.com/128841154/227728834-806bdb9c-ecb8-4090-a0e1-9784d9fbc1a7.png)
![error](https://user-images.githubusercontent.com/128841154/227728850-b86e473d-bc00-435b-a20c-92edd8ef4f46.svg)

**Comment by chubean** [comment]
Well last ditch tried one more thing, path > break apart and it did with a fill and I removed the fill and it worked.  I guess not all strokes are created equal.  It looked like a stroke from all aspects (path in layers, no fill, same stroke properties as the other that would convert, etc.)

This isn't an issue with inkstitch.

**Comment by kaalleen** [comment]
Interesting, thanks for your input. Actually these two strokes have a satin column param. But I think we actually should allow the conversion to happen, even on fills and satin columns. This may prevent some confusion in the future.

**Comment by bianchifan** [comment]
I had this problem many many times in the last 3 weeks, but with "Live Path Effects".
The reason is a misplaced entry <inkstitch:satin_column="True">.
When you y to convert a stroke this entry will be written, successful or not.
When you run forward without a goback (CRTL z) or save your svg in this state you will run in this error every time.
If the error occurs and you like to get rid of you have to remove this entry manually from your svg.

Here is your svg in a working condition:  
![92edd8ef4f46](https://user-images.githubusercontent.com/17491743/227742440-f4bbd632-7e55-407c-bc11-85662a453cf3.svg)

**Comment by chubean** [comment]
@bianchifan I was confused when you guys said it had the satin column attribute. It makes sense now. I thought because the fail, nothing happened. I didn't realize it will write the attribute to the file. Makes sense. Thank you!

**Comment by chubean** [comment]
@kaalleen I wouldn't be mad at that :) thank you for all you do!!

**Comment by chubean** [comment]
@kaalleen Tested the newest pre-release, and it worked so snappy!  I do see that every now and then in conversion, one or two of the rungs come up short and I have to edit them in nodes to cross the rails.  Is there anyway that the rung could be lengthened slightly to avoid having to go back and alter after conversion?

**Comment by kaalleen** [comment]
>   I do see that every now and then in conversion, one or two of the rungs come up short

Do you have an example file for when this is happening?

**Comment by kaalleen** [comment]
@bianchifan does this happen when you use the live preview option from the extension dialog?
I think we have to turn that one off for the lpe satins. I suppose they do not expect us to be messing around with the path like that.

**Comment by bianchifan** [comment]
> does this happen when you use the live preview option from the extension dialog?

Indeed.
But there are more faults.
When I play with the buttons on and off (in life preview) Inkscape crashes a lot, sometimes with an error message (internal error, will close now) sometimes not, the actual SVG is written then in /tmp/.
With yesterdays versions I have less problems, I'll check it out later.

**Comment by chubean** [comment]
@kaalleen I tried to reproduce this, but couldn't. I do one thing in my workflow quite often so I probably made the issue. I ctrl+l to smooth the artwork. I do know that this happens when I use ctrl+l. I'm assuming I must have caused it with that since I couldn't replicate the issue.

**Comment by kaalleen** [comment]
Ok, I just couldn't imagine how this could happen. But actually running Ctrl + L on the result makes a lot of sense. I'll make them just a little bit longer.

**Comment by chubean** [comment]
That's awesome! Thank you!
