### ISSUE TITLE
Autoroute Running Stitch

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2192]
Dans le cas d'un arrangement automatique de points droit, la répétition de 2 n'est pas conservée à l'arrangement, par contre le point triple est conservé.
V1 : les 4 chemins
V2 : après arrangement automatique
![V2](https://user-images.githubusercontent.com/65076100/229561488-856a19d4-0f80-47da-b87a-7644df12230d.svg)
![V1](https://user-images.githubusercontent.com/65076100/229561493-4668faa9-ad8b-429d-add1-6f6dcd1de0de.svg)

Par contre si j'insère une commande de début et de fin au point de départ, ça fonctionne sur cet exemple... mais pas dans tous les cas...

**Comment by kaalleen** [comment]
Not sure if I fully understand your request. Is this related to #2151 ?

**Comment by Marif91** [comment]
Merci kalleen, 

Dans l'exemple de Gus (#2151) la forme rouge est en point droit et l'arrangement automatique donne une répétition à 2. Dans l'exemple que je présente, les 4 traits sont avec une répétition à 2 et l'arrangement automatique ne reproduit pas cette répétition partout, certains traits sont en point droit à la fin.

Avant arrangement la répétition des points est à 2
Après arrangement elle a été mise à 1
![Capture d’écran 2023-04-06 à 11 03 21](https://user-images.githubusercontent.com/65076100/230329920-ae8733f1-523b-4ae0-93d8-7a8b6546ea09.png)
![Capture d’écran 2023-04-06 à 11 05 05](https://user-images.githubusercontent.com/65076100/230329923-4021c09e-b0d0-4660-bd74-35edb09ba0d2.png)

**Comment by kaalleen** [comment]
Oh, I see now what you mean. Yes, that's a bit unfortunate. Actually, this is a bit of a code design problem how the auto-run method works. It needs an unequal number of repeats. So if the number is even, it will be reduced by one.

**Comment by Marif91** [comment]
Merci Kalleen pour tes réponses !
