### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by admwrk** [inkstitch/inkstitch#2195]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/object_commands.py", line 38, in effect
  File "lib/commands.py", line 397, in add_commands
  File "lib/commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

![booby](https://user-images.githubusercontent.com/12915747/230119633-c30b0812-63ed-4bf2-9bcf-2b81e4100f78.svg)

**Comment by kaalleen** [comment]
Thank you for sending a file along with the error message. That is always very useful. The next Ink/Stitch version will be capable to handle your file much better.

But try to redesign your file to use various stitch types. Your outlines e.g. do not work well with a fill. They are even too thin for a satin. You could use a running stitch with several passes (e.g. bean stitch). Have a look at the Ink/Stitch list of available stitch types in Ink/Stitch: https://inkstitch.org/docs/stitch-library/

This is a bit of work, but the results will be much more pleasing.

**Comment by kaalleen** [comment]
Solved in current Ink/Stitch versions (v3.0.1)
