### ISSUE TITLE
svg to inkstich file

### ISSUE THREAD

**Issue by FKbond** [inkstitch/inkstitch#2198]
![spaniel 1](https://user-images.githubusercontent.com/130062697/230378233-ec874e16-903d-4da4-a1b9-922258fc2f4f.svg)
![spaniel 1](https://user-images.githubusercontent.com/130062697/230378289-526114e9-5846-4509-b027-5957b30032fa.svg)

**Comment by kaalleen** [comment]
You've got quite of a challenging file. If you are just starting out with embroidery, I would suggest to start with something more simple. If you've got some experience, I'd suggest to use the bezier-tool and redraw everything for manual (or running) stitch.

What is your question to the file?

**Comment by kaalleen** [comment]
No further response. Closing.
