### ISSUE TITLE
Simulator: display count of color changes, trims and jumps

### ISSUE THREAD

**Issue by chubean** [inkstitch/inkstitch#2202]
Is there a way to show a numeric count on the visualize that tells color changes, trims and jumps?

**Comment by kaalleen** [comment]
Do you mean the simulator?

If you need it now, use the print pdf output.

**Comment by chubean** [comment]
Thank you, I have seen it in the pdf output.  Just wondered if it could be somehow in the simulator to avoid having extra steps to find it. :)
