### ISSUE TITLE
Gcode generator

### ISSUE THREAD

**Issue by moolight-seashell** [inkstitch/inkstitch#2209]
there is a way to generate a gcode that nevever stop the main motor,

for example if on turn mean 10 i have a safe moving zone between , let's say 0-4

actually i have something like that

G0  X... Y...
G0 Z10
G0 X... Y...
G0 Z20

but this is a lot faster because we d ont stop the motor each time

G0 X... Y... Z4
G0 Z10
...

**Comment by kaalleen** [comment]
Thank you for the info.
Is this a feature request or is it already working the way you want it to be?

**Comment by moolight-seashell** [comment]
this can be improved in the gcode generation, but i no longer need this anymore
