### ISSUE TITLE
LPE fails on objects other than Bezier

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2212]
Step 1: Create a path
- Bezier works fine
- Cirle/Square will display  a "satin column"  but thats all, no params possible
- Star will display also but params produce shitty mismatch

Step 2: LPE

Step 3: Params/Sim

original SVG
![Drawing-test](https://user-images.githubusercontent.com/17491743/230872754-5376bbb4-4e61-4b2d-a13f-bfabfc6b04f3.svg)

LPE result on screen
![Bildschirmfoto vom 2023-04-07 16-05-59](https://user-images.githubusercontent.com/17491743/230873081-d6653b33-7fe9-4589-ac62-8bfd35701f7c.png)

Result from params's sim
![Bildschirmfoto vom 2023-04-06 20-14-32](https://user-images.githubusercontent.com/17491743/230873359-77455d29-86ff-4956-928b-32be1e688a58.png)

result from realistic preview -> Nada, 1% CPU
![Bildschirmfoto vom 2023-04-06 20-15-56](https://user-images.githubusercontent.com/17491743/230873761-4832a900-0125-42eb-bb62-c6393136c37e.png)

When cancelled
![Bildschirmfoto vom 2023-04-06 20-13-21](https://user-images.githubusercontent.com/17491743/230874135-acba1da6-7ad8-4d51-a807-eb23421d0380.png)

Result from troubleshooter
![Bildschirmfoto vom 2023-04-06 20-17-22](https://user-images.githubusercontent.com/17491743/230874344-dc7e27c9-5bfc-435d-bd8e-9bdd4e5bf71e.png)

Step 4: Selecting only the circle
Nada, the circle is ignored

Step 5: Save SVG
![ssssss](https://user-images.githubusercontent.com/17491743/230875310-97875679-b2eb-47f8-89b7-747b8b9c2e54.svg)

Inkscape will display the SVG with rendered columns, all other graphic programs will not, only a single line
![Bildschirmfoto vom 2023-04-07 16-12-53](https://user-images.githubusercontent.com/17491743/230875972-2f4b03cd-3803-4c1a-a5d9-bb4beb58156e.png)

No params possible
![Bildschirmfoto vom 2023-04-07 16-15-50](https://user-images.githubusercontent.com/17491743/230876189-3f2ceed0-fa59-4123-adfa-db809c504aca.png)

Step 6: Delete circle, add square and star - Square will be ignored, star results very weired
![Bildschirmfoto vom 2023-04-07 16-21-41](https://user-images.githubusercontent.com/17491743/230876464-4ddfe658-f840-42fe-8b83-eb5666915c69.png)

star selected only 
![Bildschirmfoto vom 2023-04-07 16-33-33](https://user-images.githubusercontent.com/17491743/230877109-68e93ed6-f331-4788-a728-8b07d03fc679.png)

I tested dozens of varyations, only Beziers will work fine

**Comment by kaalleen** [comment]
Thanks for pointing that out! This was really helpful. At least the shape objects can be converted.

Live path effects are an Inkscape specific concept. They will not be displayed in other programs.

**Comment by kaalleen** [comment]
Hm, I am wondering. If we add the same shape (for example triangle) to several paths and transform them, they all we be updated. That's possibly not what we want. Means, we would need to add them several times into the defs section.
On the other hand it sometimes could be exactly what we want...
