### ISSUE TITLE
Auto Fill do not work properly...

### ISSUE THREAD

**Issue by Go2design** [inkstitch/inkstitch#2218]
I have a bug on Inkstitch !
Sometimes when I want to Auto Fill an object, some forms only fill the underlay (506 stitches).
And sometimes it works  (1199 stitches) !
So, I do not understand why...

Find here the file in attachement.

Can you help me ?
![BUG0](https://user-images.githubusercontent.com/89106584/231906363-fe7d4433-8fa7-430b-be5a-7a8a802524af.svg)

**Comment by kaalleen** [comment]
Fill stitch does not like little small corners. In your case though, it has problems with the little hole. When you remove it, it will run through.

**Comment by Go2design** [comment]
Thanks Kaalleen for you reply !
It is true, but the both « D » letters are identic (same shape and same number of nodes). One of them works and one of them fail… The only thing change is the position on the sheet.
Do you have an idea ?

**Comment by lexelby** [comment]
With shapes like this that have a lot of really tiny detail, the position on the canvas can actually have an effect on whether Ink/Stitch can properly do fill stitch.  That's why one works and one doesn't.

**Comment by Go2design** [comment]
Thanks Lexelby !
But if I compare the coordinates of nodes between the two shape, the AutoFill fail contains coordonates more than seven decimal.
Find here the data in attachement.
Any idea of this ?
![Nodes](https://user-images.githubusercontent.com/89106584/232942443-74504971-3368-4498-a3ac-a48e3b1a81d5.png)

**Comment by Go2design** [comment]
Any idea ? ;)

**Comment by Go2design** [comment]
It's works on Ink/Stitch 3.1.0 !!!
Thanks for your help !
