### ISSUE TITLE
Issue attaching "Trim thread after sewing this object" command to multiple objects

### ISSUE THREAD

**Issue by Vueldon** [inkstitch/inkstitch#2225]
I tried adding trimming to all of the objects from the "DESIGN LAYER>Boat>Outlines>Ropes" group, and it returned the **error below:**

> Ink/Stitch Version: v2.2.0 (windows)
> 
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 84, in <module>
>   File "inkex\base.py", line 231, in run
>   File "lib\extensions\object_commands.py", line 38, in effect
>   File "lib\commands.py", line 397, in add_commands
>   File "lib\commands.py", line 350, in get_command_pos
> AttributeError: 'MultiPolygon' object has no attribute 'exterior'

![Boat-Test-1](https://user-images.githubusercontent.com/54679363/232893775-f0127e78-b209-4482-8f17-619726513caa.svg)
(Pre-Edit Image attribution: <a href="https://www.vecteezy.com/free-vector/sailboat">Sailboat Vectors by Vecteezy</a>)

**Comment by Vueldon** [comment]
It seems that "Path62" and "Path50" within that group were both made up of multiple paths that needed to be split. After splitting them, the command functions normally.

Could an error message be added to direct attention to the path that needs split?

**Comment by kaalleen** [comment]
Thank you for your bug report and the svg file.

The next version of Ink/Stitch does not require that you split those up. But it still would be recommended. Actually, you should consider to turn them into running stitches. A fill stitch is not really the prefered stitch type for the ropes.

Your file pointed to a possible issue with cliped path though, that we need to investigate.
