### ISSUE TITLE
Inkstitch not working please help. Says no error but isnt working?

### ISSUE THREAD

**Issue by avagrace2156** [inkstitch/inkstitch#2238]
It says, "Inkscape has recieved additional data form the script executed. The script did not return an error, but this may indicate results will not be as expected: Traceback (most recent call last): File "numpy/core/__init__.py"........... and then a long message. I don't understand it.

**Comment by kaalleen** [comment]
Which Ink/Stitch version is this?

**Comment by kaalleen** [comment]
No further response. Closing.
