### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#225]
@lexelby 
Please insert an issue template as described [here](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) so we can isolate an existing problem faster.
It should include the following:
- Version of Ink/Stitch
- Bug, Feature request, ...
- System / OS / Architecture (e.g. x64/x32) and Language (e.g. english, german, etc...)
- Report (Error Message, Screenshot, etc)
- reproducibility of bug / glitch
- ...

Examples / Ideas:
[GitHub Issue Templates](https://github.com/stevemao/github-issue-templates/)
[Awesome GitHub Tempates](https://github.com/devspace/awesome-github-templates)

What do you think? Would it make sense to introduce this?

**Comment by lexelby** [comment]
To be honest, I'd actually prefer we not do this, at least not yet.  We're not getting an excessive number of bug reports, and we're not having trouble with folks providing insufficient detail.

I'd like to try to keep our project approachable at this stage.  Bug reports and feature requests are a way that we can invite people to become involved in the project.  That's easier to do if there's more of a human touch.

My concern is that folks may see an issue template form and become intimidated by the level of work.  They may even choose not to submit their bug report if they're too busy to fill out the form.  We need the bug report more than we need them to get all the details down on the first try.

**Comment by AkiraNorthstar** [comment]
I have not seen it like that before ... That's a good attitude.
That's right, it will be much easier to establish a contact.
Very good arguments, not to implement it!
You've convinced me!
I leave this request open, if you want you can close it.

**Comment by lexelby** [comment]
Yay! :)  If things change, like if we start spending a ton of time inefficiently working through bug reports, I'm happy to reconsider.
