### ISSUE TITLE
Integrate pyembroidery

### ISSUE THREAD

**Issue by tatarize** [inkstitch/inkstitch#226]
[Pyemboridery is stable now](https://github.com/inkstitch/pyembroidery), spent the last couple days fluffing up the formats it will load. Other specific formats would be pretty doable, or if it glossed over some of the ones in the current list, especially if part of the pyembroidery mandate.

Mandate was to satisfy #199 

Should fix issues #205, #204, #203. Make #124 / #160 doable, and make #24 an achievable goal, as it does do sequins though they only actually save in .dst (and apparently .u?? I don't currently write that).

**Comment by AkiraNorthstar** [comment]
Wow! You put a lot of energy into it - respect!
Add to that the detailed descriptions and essays of the different formats ...
Thank you!

**Comment by lexelby** [comment]
Awesome!  Thanks for all your hard work, @tatarize.

I'll get started integrating this soon.  I'll plan to pin to version 1.2.* so you can use major or minor version number bumps if you need to introduce backward-incompatible changes.

**Comment by lexelby** [comment]
I'm starting on this one now.  I'm going to integrate #228 and also a fix for a problem I discovered with trimming: on my brother machine that doesn't have trim capability, the extra jumps get sewn as stitches.

**Comment by lexelby** [comment]
Excellent progress so far!  My first try at having Ink/Stitch write using pyembroidery is working.  pyembroidery is definitely significantly easier to use than libembroidery.

Still lots of cleanup to do, but great progress so far.

**Comment by tatarize** [comment]
LibEmbroidery treats a lot of jumps as trims. Like the distinction it has is pretty sketchy. It records a bunch of commands that are clearly jumps and treated as jumps as trims. It could actually be that that brother machine was fed jumps and they got read as jumps. In theory it should have x and y encoding and has bits within the long-form which are flagged as trim or jump, and color changes are apparently a slightly different coding fe b0, then a flipping 2 or 1 byte for some reason. 

Wilcom didn't like the trims as they were encoded there so I fiddled with them to get it consistent on all programs I could find that loaded such things, as well as pes files I could find anywhere and brother's own software.  Such things might actually be able to trim but just quirks in libembroidery prevented it. 

Without fully testing the output formats on actual machines it's hard to know. And it might actually differ a bit from machine to machine.
