### ISSUE TITLE
PES versions?

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2264]
Out of the blue someone answered my olllld FB question in the Brother group by saying that their ULT2001, the Brother version of my Baby Lock, doesn't read PES files newer than 4.01.

I dimly remember talking about the version Ink/Stitch writes, but it's hard to search for that amid all the talk of *Ink/Stitch* versions... was that something we'd ruled out as to why it won't run Ink/Stitch designs larger than ~5x7? (It's a 160x260mm machine, and will run larger designs off cards, but I haven't yet found a larger design on MIL's floppies so that might have just been a limitation on the floppy disk interface.)

**Comment by kaalleen** [comment]
(If I am right) we are using pes version 1.0 ...
