### ISSUE TITLE
Macbook pro m2 with Ventura OS

### ISSUE THREAD

**Issue by Revolveriv** [inkstitch/inkstitch#2276]
Hi there, what should be done to to get the ink/stitch app working on a Ventura OS ?

**Comment by kaalleen** [comment]
Do you have any issues with it?

Inkscape states, that there is an issue with specific mouse events being unresponsive at times. Other than that I'm not aware that it wouldn't run.

After the Inkscape installation follor the instructions on our website: https://inkstitch.org/docs/install-macos/ and use the version for Monterey.

**Comment by kaalleen** [comment]
No further response. Closing.
