### ISSUE TITLE
Inkstitch "ValueError: too many values to unpack (expect 3)" when troubleshooting

### ISSUE THREAD

**Issue by MichaelHoncho** [inkstitch/inkstitch#2294]
I am a relatively new user and got this error message while doing a "troubleshoot" while trying to digitize this file for embroidery using inkstitch... I am following the instructions and posting it here. Hope this helps!

-Mike Honcho

![Duff Beer Label Traced By Color](https://github.com/inkstitch/inkstitch/assets/133608788/53b12907-5bcb-4b9b-a4a4-009707e738ee)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 32, in effect
  File "lib\elements\fill_stitch.py", line 329, in validation_warnings
ValueError: too many values to unpack (expected 3)

**Comment by kaalleen** [comment]
Thank you for your error report, you found a new bug. Troubleshoot tries to warn you, that your white shape consists of unconnected shapes. You can  remove the warning by selecting it and hit Ctrl + K
