### ISSUE TITLE
no shortcut after instillation v2.2.0, how to open it

### ISSUE THREAD

**Issue by sagarvermarke** [inkstitch/inkstitch#2300]
no shortcut after instillation v2.2.0, how to open it

**Comment by kaalleen** [comment]
Ink/Stitch in an Inkscape plugin. So you have to open Inkscape and then you'll see Ink/Stitch in Extensions > Ink/Stitch.

https://inkstitch.org/docs/basic-usage/

**Comment by kaalleen** [comment]
No further response. Closing.
