### ISSUE TITLE
Params - Fedora 38

### ISSUE THREAD

**Issue by yegnal** [inkstitch/inkstitch#2303]
Greetings;

I am unable to bring up the params dialog....   The params extension is visible, but nothings happens when selecting.

The simulator / realistic preview works with the object in question, but params doesn't load anything.....

I installed inkstitch using the .rpm from inkstitch.org and the software installer.  

Again, nothing happens when choosing params.  I also tried installing on an Ubuntu virtual machine and I get the same behavior...........

This is the inkscape that Fedora installed:

Name         : inkscape
Version      : 1.2.2
Release      : 7.fc38
Architecture : x86_64
Size         : 176 M
Source       : inkscape-1.2.2-7.fc38.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Vector-based drawing program using SVG
URL          : https://inkscape.org/
License      : GPLv2+ and CC-BY
Description  : Inkscape is a vector graphics editor, with capabilities similar to
             : Illustrator, CorelDraw, or Xara X, using the W3C standard Scalable Vector
             : Graphics (SVG) file format.  It is therefore a very useful tool for web
             : designers and as an interchange format for desktop publishing.
             : 
             : Inkscape supports many advanced SVG features (markers, clones, alpha
             : blending, etc.) and great care is taken in designing a streamlined
             : interface. It is very easy to edit nodes, perform complex path operations,
             : trace bitmaps and much more.

**Comment by michelD09** [comment]
Hello,
I have exactly the same problem with 
ubuntu : 22.04.
inkscape‌ : Inkscape 1.2.2 (1:1.2.2+202305151914+b0a8486541)
inkstitch : v2.2.0

**Comment by kaalleen** [comment]
@yegnal @michelD09  Can you try to install using the tar.xz archive? The rpm doesn't work well for Fedora.

**Comment by michelD09** [comment]
I didn't install it with rpm, but with deb.
I'll try to install with the tar.xz archive and give you feedback.
Thanks a lot for your help.

**Comment by kaalleen** [comment]
Oh, then you are maybe seeing the wayland issue: https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds

**Comment by yegnal** [comment]
OK so the Wayland issue was the culprit 
export GDK_BACKEND=x11 && inkscape  works...............

Thanks smuch

**Comment by michelD09** [comment]
with command : 

> export GDK_BACKEND=x11 && inkscape

I get :

> ** (org.inkscape.Inkscape:12444): WARNING **: 17:17:03.849: Parameter 'feed_rate' in extension 'org.inkstitch.output.txt.fr_FR' is visible but does not have a 'gui-text'.
> 
> ** (org.inkscape.Inkscape:12444): WARNING **: 17:17:04.262: Failed to find resource file 'inkex.py'. Looked in:
>     /home/ubuntu/.config/inkscape/extensions/inkex.py
>     /usr/share/inkscape/extensions/inkex.py

(repeated numerous times)
