### ISSUE TITLE
zigzag2satin problem with actual dev version

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2305]
With today's dev version (11:23) zigzag2satin does not work any more when smoothed..rungs are too small
![Bildschirmfoto vom 2023-05-18 19-23-38](https://github.com/inkstitch/inkstitch/assets/17491743/62bbd150-85a9-4872-9f38-b348981ecaa3)

**Comment by bianchifan** [comment]
Just found: the default for a stroke has changed to zigzag instead of running

**Comment by kaalleen** [comment]
The inkscape dialogs remember your last setting. This is sometimes useful, because people have different preferences. I would wish though, they had a reset button.
