### ISSUE TITLE
Janome output (.jef export)

### ISSUE THREAD

**Issue by grerov** [inkstitch/inkstitch#231]
Exported file for Janome looks different (incorrect) when opened in Janome Embroidery Editor.

It's fine when it's exported to .dst file and opened with editor. The only issue with this is with colors which are incorrect but are correct when exported to jef. I use Janome Memory Craft 500e machine.

If any screenshot would help let me know and I will attach it.

**Comment by tatarize** [comment]
Does this look right or is it messed up in the same way?

[pilot.zip](https://github.com/inkstitch/inkstitch/files/2187549/pilot.zip)

**Comment by grerov** [comment]
Unfortunatelly does not even open.

![image](https://user-images.githubusercontent.com/41140617/42619157-82f40d04-85b7-11e8-9dcc-739e6c4d4eba.png)

**Comment by tatarize** [comment]
Hm. Must mean the .jef format is miscoded in both libembroidery and pyembroidery.

**Comment by tatarize** [comment]
Okay, I dug up something that can detect the difference. Can you give me a copy of the failed color file (you might have to zip it up)?

**Comment by grerov** [comment]
I'm not sure...jef opened for me when I exported but is messed up. Colors are right.

![image](https://user-images.githubusercontent.com/41140617/42620189-89786a82-85ba-11e8-9519-7273ba478f52.png)

![image](https://user-images.githubusercontent.com/41140617/42620267-cdb6acc2-85ba-11e8-8b8d-84e8957f54fb.png)
[testiranje.zip](https://github.com/inkstitch/inkstitch/files/2187661/testiranje.zip)

**Comment by tatarize** [comment]
Jef has some proximal colors with a magic color lookup without the enhance bit. If you load up more colors are they all just kinda wrong or is it all over the map?

**Comment by grerov** [comment]
Colors are messed in dst file opened with editor. But bigger problem for me is that stitches are messed in jef. file. I'm not sure you can see but on my first picture red circle above JEF name stroke satin stitch is not even linked together on the right (marked that with yellow). It's even more visible on some other shapes or alphabets characters.

![image](https://user-images.githubusercontent.com/41140617/42626507-c957cdb8-85ca-11e8-9aa6-65bee7bd68f3.png)

**Comment by tatarize** [comment]
The DST file contains no colors. There's no mechanism by which it can be preserved. So that's generally out. The breaks in the jef file might be due to forced trims. Lib embroidery uses control code 80 04 xx yy for jump rather than 80 02 xx yy like wilcom seems to use. I'm unsure if that's because 04 means trim and jump or it's simply wrong. But, I'm not sure why those commands would get put in there anyhow. Why would inkstitch ask for a trim or jump in those locations?

**Comment by tatarize** [comment]
Looking at that I gotta say, yeah, it's eating the first or last stitch there. The difference with the jef file is pretty clear. Lemme run an analysis. 

DST:
"*","2133","JUMP","110.0","75.0","45.0","-75.0"
"*","2134","STITCH","155","0","45.0","-75.0"
"*","2135","STITCH","156","0","1","0"
"*","2136","STITCH","157","0","1","0"
"*","2137","STITCH","156","0","-1","0"
"*","2138","STITCH","155","0","-1","0"
...
"*","2652","STITCH","155","-3","-20","3"
"*","2653","STITCH","175","-2","20","1"
"*","2654","STITCH","165","0","-10","2"
"*","2655","STITCH","166","0","1","0"
"*","2656","STITCH","167","0","1","0"
"*","2657","STITCH","166","0","-1","0"
"*","2658","STITCH","165","0","-1","0"
"*","2659","TRIM","165","0","0","0"
"*","2660","STITCH","166","-10","1","-10"
"*","2661","END","166","-10","0","0"

JEF:
"*","2131","TRIM","65","150","0","0"
"*","2132","COLOR_CHANGE","65","150","0","0"
"*","2133","JUMP","110.0","75.0","45.0","-75.0"
"*","2134","STITCH","155","0","45.0","-75.0"
"*","2135","STITCH","156","0","1","0"
"*","2136","STITCH","157","0","1","0"
...
"*","2652","STITCH","150","-8","-20","3"
"*","2653","STITCH","170","-7","20","1"
"*","2654","STITCH","160","-5","-10","2"
"*","2655","STITCH","161","-5","1","0"
"*","2656","STITCH","162","-5","1","0"
"*","2657","STITCH","161","-5","-1","0"
"*","2658","STITCH","160","-5","-1","0"
"*","2659","END","160","-5","0","0"

You will notice stitch 2135 is identical and located ("156","0") in the same place. But, at the end Jef stops at 160,-5 and the dst goes to "165","0". So, yeah, for some reason the JEF doesn't make it all the way back around.
[results.zip](https://github.com/inkstitch/inkstitch/files/2188236/results.zip)

**Comment by grerov** [comment]
Yeah, and also stitches from 2652 to 2659 has different attribute values which possible is the reason why shape of stitches is so messed in jef format.

This is jef without trims at all

![image](https://user-images.githubusercontent.com/41140617/42633279-468a2a3c-85e0-11e8-87f6-9c72bea373e5.png)

**Comment by tatarize** [comment]
Ah, 

```
while(stitches)
    {
        dx = stitches->stitch.xx * 10.0 - xx;
        dy = stitches->stitch.yy * 10.0 - yy;
        xx = stitches->stitch.xx * 10.0;
        yy = stitches->stitch.yy * 10.0;
        flags = stitches->stitch.flags;
        jefEncode(b, (char)roundDouble(dx), (char)roundDouble(dy), flags);
...
```

The reason for the dx, dy, and xx yy is to account for the error. If you have part of a stitch, it's supposed to prevent the error from compounding. So it tracks the error. But, the error is introduced at the jefEncode(roundDouble()...) bit, and that error is categorically not accounted for. If it moves 14.5 to 15 or 14 either way the current known global position starts to drift causing compounding error. This would be especially pronounced in something that changes direction consistently in the same direction and thus would have the error on the same side... you know, like a damned circle.

This is the point where I'd be all haughty about pyembroidery but wouldn't you know it, I followed suit when I was transcoding it to java, and python. Turned them into ints during the writing process missing the error the rounding op might cause.

**Comment by lexelby** [comment]
I'm not seeing compounding in that code?  It looks like it recalculates xx and yy at each step, avoiding carrying through a rounded xx or yy value...

**Comment by tatarize** [comment]
Proper:
```
    xx = 0
    yy = 0
    for stitch in pattern.stitches:
        x = stitch[0]
        y = stitch[1]
        data = stitch[2]
        dx = int(round(x - xx))
        dy = int(round(y - yy))
        xx += dx
        yy += dy
        encoded_bytes = jef_encode(dx, -dy, data)
        write_int_array_8(f, encoded_bytes)
    if data != END:
        f.write(b'\x80\x10')
```
Wrong:
```
    xx = 0
    yy = 0
    for stitch in pattern.stitches:
        x = stitch[0]
        y = stitch[1]
        data = stitch[2]
        dx = x - xx
        dy = y - yy
        encoded_bytes = jef_encode(int(dx), -int(dy), data)
        write_int_array_8(f, encoded_bytes)
        xx = x
        yy = y
    if data != END:
        f.write(b'\x80\x10')
```

The files don't know where you are. They just sum up the difference in the dx and dy values and figure it out from there. It *seems* like you're doing the same thing, but you round those values *after* you calculated them, and you don't account for that rounding. And you need the sum of the rounded values so that you will perfectly match the file's expected global value.

**Comment by tatarize** [comment]
For an extreme example, suppose stitch 10000 times, each time you move +.333, +.333. It's not enough to move the needle a tenth of a millimeter so it *should* stitch 3 times in the same spot, then move over and down a tenth of a millimeter, and then stitch there three times. However, it actually stitches 10000 times in the same spot. It should have gone 30 millimeters.

**Comment by lexelby** [comment]
Oh of course!  I see it now.  Definitely makes sense as to why jef files look so... wobbly.

**Comment by tatarize** [comment]
The .dst writer in LE looks like:

```
    while(pointer)
    {
        /* convert from mm to 0.1mm for file format */
        dx = roundDouble(pointer->stitch.xx * 10.0) - xx;
        dy = roundDouble(pointer->stitch.yy * 10.0) - yy;
        xx = roundDouble(pointer->stitch.xx * 10.0);
        yy = roundDouble(pointer->stitch.yy * 10.0);
        flags = pointer->stitch.flags;
        encode_record(file, dx, dy, flags);
        pointer = pointer->next;
    }
```
Which certainly should fix the problems. Rounding the xx and yy makes sure they can only end up being integer increments. But, other writers like .exp, have the same flaw.

```
    while(stitches)
    {
        dx = stitches->stitch.xx * 10.0 - xx;
        dy = stitches->stitch.yy * 10.0 - yy;
        xx = stitches->stitch.xx * 10.0;
        yy = stitches->stitch.yy * 10.0;
        flags = stitches->stitch.flags;
        expEncode(b, (char)roundDouble(dx), (char)roundDouble(dy), flags);
```

Also, bothered to make those files, extreme example did exactly what I expected.

[jef-bug.zip](https://github.com/inkstitch/inkstitch/files/2188845/jef-bug.zip)

**Comment by tatarize** [comment]
This is fixed in pyembroidery and I raised an issue for libembroidery.

**Comment by lexelby** [comment]
@tatarize Could you please post a new version to PyPI with this fix?

I thought the fix was on PyPI already and just spent a long time trying to figure out why everything was wobbly when you'd already fixed it :(

**Comment by tatarize** [comment]
Should certainly be fixed in 1.2.12.

**Comment by tatarize** [comment]
Problem was dumber than I thought. Shoulda been fixed in 1.2.9 but, I didn't move the files into the directory I actually use for pypi updates. So the same files got uploaded again even with the newer version number. I'll suck less at that going forward.

**Comment by lexelby** [comment]
Ah, that explains it. :)  No worries, glad we got that sorted out.

**Comment by grerov** [comment]
Hi guys,

Thanks for all your effort - I really appreciate it!

I couldn't test it before as I was on vacation. Yesterday I tried latest version and unfortunately jef file doesn't open in my Janome Embroidery Editor software. It says "failed to open the file". It seems to me there is something wrong with export to jef format as before at least jef file was recognized by my software. Please check when you have time.

**Comment by lexelby** [comment]
Interesting!  I'm pretty sure @tararize tested some files with janome's software  so maybe this only affects a subset of JEF files saved by Ink/Stitch.  Would you be willing to post your file here for us to test with?  Both the SVG and the JEF would be helpful if you can do it.

**Comment by grerov** [comment]
Attached zip file with svg, dst (opens in software), jef (doesn't open in software). Both are exported with latest version of inkstitch.

[test.zip](https://github.com/inkstitch/inkstitch/files/2249463/test.zip)

**Comment by lexelby** [comment]
@grerov Are you running under Windows?  Did you use the File -> Save As method of exporting a JEF file?  If so this may be the same underlying problem as #258, and #260 may fix it.

**Comment by tatarize** [comment]
Hm. I tried opening the file under Customizer11000, Premier+™, Wilcom E3, Embird 2018 and it opened in all of them. Customer11000 is Janome software. I was hoping it would properly be fragile enough to fail if there was some flaw.

I'll check the exports from the various softwares and see if there's something I've got wrong. If you have a machine it might be able to be checked against that too. At least eventually. I'll flag the issue in pyembroidery. Knowing that it worked under libembroidery means that it's something somewhere. 

Could you also load the .dst and save it as a .jef with the software in question and send me that file. Whatever my error is, making the export more like that file will certainly be a step in the right direction. Without being detect errors locally it's a bit of a shot in the dark. But, with a presumed perfect specimen I'd know which way to conform.

**Comment by grerov** [comment]
I saved dst file as .jef and .jef+ in my software. Hope this would help. Still, when I come home I will try to load exported jef file directly to my machine to see if it loads there.

[test-dst2jef.zip](https://github.com/inkstitch/inkstitch/files/2256801/test-dst2jef.zip)

**Comment by tatarize** [comment]
[jef-tests.zip](https://github.com/inkstitch/inkstitch/files/2257065/jef-tests.zip)

Checking the code the most promising candidate was a bug in the hoop size. It would select the hoop that specifically gave coords as broken. Which makes it likely that that is what happened and could cause a crash/fail. If so test-hoop-fix and test-rejigger will work and all the rest will not load.

It would also explain the sort of random working/non-working dynamic where it seems to work sometimes but failed other times. I also included files for the other major differences. Though most of those I believe to be moot (but I don't have something crashing so better to throw everything at it to see). Also if rejigger works but rejigger-badhoop doesn't then it's most certainly hoop value bug I located. Also the bug only existed in the pyembroidery code and not libembroidery which is promising.

I notice your file says hoop 0x27 (39) must have added a bunch in the newer versions.

**Comment by grerov** [comment]
None of those 5 files loads. 

It worked (ok, it was not correct but file loaded) with version 1.10 (maybe also 1.11)...what has changed after that?

**Comment by tatarize** [comment]
pyembroidery changed after that, circa 1.14.0. I fixed all the little broken bits and cross referenced it in every bit of software I could find, and apparently there's some little bit somewhere that isn't correct and causing issues. I methodically checked it and missed a spot so it's an issue. 

[new-jef-tests.zip](https://github.com/inkstitch/inkstitch/files/2258606/new-jef-tests.zip)

Knowing none of those loaded narrowed down the places the bug could be and I double checked and the listed size seems incorrect, which is something Janome might care about but other folks might ignore. I also included my pure-janome copy that should load. And some switched header stuff that will be identical to the pure janome except for stitches (which should narrow it down). But, I'm hopeful it's the stitchcount imperfection.

**Comment by tatarize** [comment]
@grerov I think I fixed it. But, you're the only source for the crashes. The fix size and header and size should both work if I got it right.

**Comment by lexelby** [comment]
I'd like to establish a ground rule for our community: let's try to be patient with slow responses.  I know that I, for one, sometimes go days in a row without having any time for Ink/Stitch.  We're all volunteers here and we're giving what we have available.

I don't want anyone to feel any pressure to contribute more time than they desire to.  So let's let gerov respond when they want to.  I'm sure we can find someone else with the Janome software to help test if it comes to that.

**Comment by tatarize** [comment]
https://www.youtube.com/watch?v=aqNiC91xHoU

**Comment by tatarize** [comment]
Perfect. The pure-janome was janome's file. In the other ones, I switched the header with the pure janome header, fixed the size, and switched the header and fixed the size. So just fixing the size fixed it. Switching everything but not correcting the size left it crashing. And swapping the header and fixing the size also fixed it. --- Proved by correcting just the size error and stopping the crash and proved by changing everything except the size error and still crashing.

Sorry for the impatience. But, that's perfect. Even the crashing one proves the fix.

**Comment by grerov** [comment]
Nice. Glad you solved it. Thanks a lot!

**Comment by tatarize** [comment]
Yeah, not sure when the updating happens but 1.2.25 should fix it. Might be during install with the requirements. Downloading the most recent version of 1.2.x

 But, that'll work now. Though, there's a lot of stuff like exporting .u01 files and loading like a dozen other file formats, but I think those are specific hooks and and not my department.

If updating versions causes a new PyPi DL of pyembroidery it'll work.

**Comment by grerov** [comment]
Can we expect v1.16 for Windows also or are there any issues?

**Comment by lexelby** [comment]
@grerov sorry!  Looks like the build broke for Windows.  I've been pulled away by life stuff for the past few days but I hope to have this fixed soon.

**Comment by lexelby** [comment]
@grerov Okay!  v1.16.1 is out with a working Windows release: https://github.com/inkstitch/inkstitch/releases/tag/v1.16.1

If that doesn't fix the Janome issue, go ahead and open a new issue for that.
