### ISSUE TITLE
Display problem in Params preview

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2313]
I do not remember when introduced but it do stay meanwhile for several month.
I noticed it last year the first time when I zoomed into the preview ;)

When the graph touches the left border of the window(zoomed in or shifted left) there appear a lot of artifacs.

Normal view resulting from params
![Bildschirmfoto vom 2023-05-22 12-01-51](https://github.com/inkstitch/inkstitch/assets/17491743/342f38c0-7e20-4f2c-9979-da3214c39677)

Slightly shifted view
![Bildschirmfoto vom 2023-05-22 12-04-40](https://github.com/inkstitch/inkstitch/assets/17491743/be17f9b2-daf1-4b3c-9e58-fe8fa44ee49c)

Shifted and zoomed
![Bildschirmfoto vom 2023-05-22 12-05-33](https://github.com/inkstitch/inkstitch/assets/17491743/6d308d33-76f5-4628-83db-bbfd967d63e7)
![Bildschirmfoto vom 2023-05-22 12-05-53](https://github.com/inkstitch/inkstitch/assets/17491743/cd89cb3b-d3ab-4436-9571-5293684050ba)

**Comment by kaalleen** [comment]
Interesting. I cannot replicate though. Which linux distribution do you use?

**Comment by bianchifan** [comment]
Linux Mint 20.3.
Another point is the Hardware, Dell notebook Studio XPS with two Nvidia Graphic cards, one onboard and one dedicated. I'm using the Nvidia driver but it's old, Nvidia's support for Linux was abandoned last year.

**Comment by bianchifan** [comment]
No more probs with V 3.0.0 :)

**Comment by kaalleen** [comment]
Ok, thank you for your feedback :)
I close the issue then.
