### ISSUE TITLE
Comments in messages.po

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#232]
@lexelby 
It gets harder and harder to translate the newly inserted commands / dialogues, so that they fit in with their sense. With a python format (#, python format) you do it already. Would not it be better to do it with all words, dialogues and so on?

But I do not think about something like this:
\# /path/to/extension/extension.py: 10

Rather that the "origin" is called:
\# Extensions / Embroidery / Params / Auto-Fill / Dialog

It's an idea and maybe it helps other translators too.
What do you think about it?
Or do you have a better idea?

**Comment by lexelby** [comment]
I'm not sure I understand what you're asking for.  Are you requesting more descriptive comments for translation strings?

**Comment by AkiraNorthstar** [comment]
... A comment line where the word or sentence occurs.
Not as a note that this word occurs in the file messages.po and the line number xxx. (# inkstitch / messages.po: 123)
Where it "really" appears within the graphical interface (in which context it stands).

German is sometimes too precise (and that sucks!), depending on the word and context it must / can be exchanged for a fitting word.

Let's take the word: none
It can stand for: nothing. It can stand for: no. It can stand for: zero.
Depending on how it suits the whole.

I hope I wrote it more understandable than before.

**Comment by danielkschneider** [comment]
Yes context is always nice to have for translators. If I understand right, you can extract comments from the code and then use these for context. This would require indeed more descriptive comments for translation strings.

It also might help to have a quick way to upgrade the language file without having work with a development version. This way one could at least check by trying out everything. E.g. an "update language" checkbox in the in the "Install Addons". Probably, this  won't be possible since translations - if I understand right - use the English string as identifier and the latter can change.

@AkiraNorthstar btw the German translation looks very good. I just thought that I should complete the French translation and your German helped :)
Btw: I am not native french, at some point some native should go over it.

**Comment by lexelby** [comment]
Yes, as Daniel points out, it is definitely possible to add comments in the code that describe the text to be translated.  Our localization coffee actually already extracts those.  I just haven't been diligent in adding the comments! :)

 I'll try to do a run of commenting at some point soon.  It would help if you could make a list of strings that need more context and I'll prioritize those ones.

**Comment by AkiraNorthstar** [comment]
@lexelby : Ok, i can do that. Can i create a branch without "build all directly"? I think use of [ci skip] for travis. Or was it [skip ci]? I'm doing a new branch for testing, and if you like that I'll do the rest of the messages.po. Is that okay for you?

**Comment by AkiraNorthstar** [comment]
I tested it locally. The previous modularization makes it simpler / more concise. It would be enough for me to add the comments from babel / pybabel. Here's an example:
current:
``` makefile
messages.po:
	rm -f messages.po
	pybabel extract -o messages.po -F babel.conf --no-location --add-comments l10n --add-comments L10n --add-comments L10N -s .
```
``` po
msgid "Auto-Fill"
msgstr ""

msgid "Automatically routed fill stitching"
msgstr ""

msgid "Running stitch length (traversal between sections)"
msgstr ""

msgid "Underlay"
msgstr ""

msgid "AutoFill Underlay"
msgstr ""

msgid "Fill angle (default: fill angle + 90 deg)"
msgstr ""

msgid "Row spacing (default: 3x fill row spacing)"
msgstr ""

msgid "Max stitch length"
msgstr ""

msgid "Inset"
msgstr ""

msgid "Expand"
msgstr ""

#, python-format
msgid "%(id)s has more than one command of type '%(command)s' linked to it"
msgstr ""
```
modification:
``` makefile
messages.po:
	rm -f messages.po
	pybabel extract -o messages.po -F babel.conf --add-location=full --add-comments=l10n,L10n,L10N --sort-by-file .
```
``` po
#: lib/elements/auto_fill.py:11
msgid "Auto-Fill"
msgstr ""

#: lib/elements/auto_fill.py:14
msgid "Automatically routed fill stitching"
msgstr ""

#: lib/elements/auto_fill.py:33
msgid "Running stitch length (traversal between sections)"
msgstr ""

#: lib/elements/auto_fill.py:38
msgid "Underlay"
msgstr ""

#: lib/elements/auto_fill.py:38 lib/elements/auto_fill.py:43
#: lib/elements/auto_fill.py:54 lib/elements/auto_fill.py:60
#: lib/elements/auto_fill.py:70
msgid "AutoFill Underlay"
msgstr ""

#: lib/elements/auto_fill.py:43
msgid "Fill angle (default: fill angle + 90 deg)"
msgstr ""

#: lib/elements/auto_fill.py:54
msgid "Row spacing (default: 3x fill row spacing)"
msgstr ""

#: lib/elements/auto_fill.py:60
msgid "Max stitch length"
msgstr ""

#: lib/elements/auto_fill.py:67
msgid "Inset"
msgstr ""

#: lib/elements/auto_fill.py:78
msgid "Expand"
msgstr ""

#: lib/elements/element.py:232
#, python-format
msgid "%(id)s has more than one command of type '%(command)s' linked to it"
msgstr ""
```
Actually, you delete the messages.po and generate a new one, but where does the comment "#, python-format" come from? From babel / pybabel?
If the file [inkstitch/messages.po](https://github.com/inkstitch/inkstitch/tree/master/messages.po) is changed (in content), are the other languages changed / generated via the [inkstitch/git-hooks/pre-commit](https://github.com/inkstitch/inkstitch/tree/master/git-hooks/pre-commit) when building inkstitch? Locally no changes were found under inkstitch/translations. Only
``` bash
make locales 
```
generates locales in inkstitch/locales but not under inkstitch/translations.

Informations of pybabel (version 2.5.3) options i used:
```
-F MAPPING_FILE, --mapping-file=MAPPING_FILE, --mapping=MAPPING_FILE
                        path to the mapping configuration file
  --add-location=ADD_LOCATION
                        location lines format. If it is not given or "full",
                        it generates the lines with both file name and line
                        number. If it is "file", the line number part is
                        omitted. If it is "never", it completely suppresses
                        the lines (same as --no-location).
-c ADD_COMMENTS, --add-comments=ADD_COMMENTS
                        place comment block with TAG (or those preceding
                        keyword lines) in output file. Separate multiple TAGs
                        with commas(,)
--sort-by-file        sort output by file location (default False)
```
Summary:
We have only to change the line of generating the messages.po in Makefile.
Option -c and option -s have no effect (locally) on the final result - can you confirm that?
If do, we can remove the two options completley.

Happy hacking,
AkiraNorthstar

**Comment by AkiraNorthstar** [comment]
I think we can close this. (please reopen if needed)
