### ISSUE TITLE
v3.0.0 Linux Lettering, output from extension could not be parsed.

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#2323]
Running OpenSuse Tumbleweed, RPM install. Everything seems to be working fine except the lettering tool won't load. Popup says output from extension could not be parsed.

starting inkscape from terminal, then executing lettering returns the following.
```
/tmp/ink_ext_XXXXXX.svg9Q4Q51:1: parser error : Start tag expected, '<' not found
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon
^

** (org.inkscape.Inkscape:29121): WARNING **: 15:41:53.402: Extension returned output that could not be parsed: Open failed
```
Edit, for completeness I am running Wayland, tried X session same error.
Also for edit I run KDE Plasma (noted for the Gtk:ERROR output)

**Comment by kaalleen** [comment]
Can you test this version here?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-try-and-error

**Comment by buzzmandt** [comment]
Yes ma'am, I gave it really hard kick to the tires and it seems everything is working right in that one.  Starting in terminal it gave no errors when I did anything, and I threw at least half the kitchen sink at it.
I will continue to use this one until then updated version is released. Thank you very much.

**Comment by kaalleen** [comment]
Thank you for your feedback!
