### ISSUE TITLE
Issue with Husqvarna

### ISSUE THREAD

**Issue by Francesco-Rugg** [inkstitch/inkstitch#2324]
Hi, I'm very new to this and I have a problem with a logo that I'm trying to embroidery. 
My machine is an Husqvarna Viking Topaz 40
Every time that I try to do a circle I always get a fill that is oval and not perfectly round. 
These two photo shows what issues I have. 
All the objects are "fill", but only the outline is "satin".
In Inkscape the file is exported to   .vp3 format

![IMG_20230527_004421.jpg](https://github.com/inkstitch/inkstitch/assets/62062196/ceab62d0-e71d-4649-be6d-fa064acf1c8b)

![IMG_20230527_004446.jpg](https://github.com/inkstitch/inkstitch/assets/62062196/c3da1325-3d69-472c-a1c9-30a4a84554ad)

What I can do to avoid this?

**Comment by kaalleen** [comment]
This is due to pushing and pulling on the fabric during the stitchout. You'll have to adapt your shape on screen. Make it a bit wider in stitch direction and just a little bit smaller in the opposite direction.

https://inkstitch.org/tutorials/push-pull-compensation/

**Comment by kaalleen** [comment]
Closing, no further response. No Ink/Stitch issue.
