### ISSUE TITLE
Issue with Ink_Stich version v2.2.0

### ISSUE THREAD

**Issue by essaideconversion** [inkstitch/inkstitch#2326]
Dear,

Please find the error message received during converion of the file from JPG (vectorized) to PEC

see file attached

****

path569: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating

****

Thanks for return

-- 
Salutations
Bernard FERET
bernard.feret@free.fr
06.84.85.35.83
![paon vectorise](https://github.com/inkstitch/inkstitch/assets/134774982/f6c55077-d27b-4dc0-8941-c0b25f955e1a)

**Comment by kaalleen** [comment]
It is very well possible that this will render with the new ink/sttich version. Nevertheless you definitely will need to optimize your svg for embroidery and simplify as much as you can.

**Comment by kaalleen** [comment]
Closing since it will render with the latest release. Still it won't stitch out nicely and needs an embroidery friendly rework.
