### ISSUE TITLE
Auto-route satin issue

### ISSUE THREAD

**Issue by safire3002** [inkstitch/inkstitch#2328]
hi,

i've been trying to set up a font for the community for embroidering and my auto-route satin stitch menu option is giving me this issue:

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/auto_satin.py", line 69, in effect
  File "lib/stitches/auto_satin.py", line 351, in auto_satin
  File "lib/stitches/auto_satin.py", line 560, in add_trims
  File "lib/commands.py", line 396, in add_commands
  File "lib/commands.py", line 296, in add_group
  File "lib/svg/path.py", line 67, in get_correction_transform
  File "lib/svg/path.py", line 44, in get_node_transform
AttributeError: 'NoneType' object has no attribute 'getparent'

![InstrumentSerif-Regular-bug](https://github.com/inkstitch/inkstitch/assets/134817062/8a39da73-06c1-41fa-8917-4141c819779e)

**Comment by bianchifan** [comment]
You have to turn every single path into a satin stich before running autoroute.

![Bildschirmfoto vom 2023-05-28 13-42-28](https://github.com/inkstitch/inkstitch/assets/17491743/45cbb8fa-8eec-48d3-a28c-570b8de519fe)

![241454831-8a39da73-06c1-41fa-8917-4141c819779e](https://github.com/inkstitch/inkstitch/assets/17491743/c560b166-569e-486c-8dce-92e636cba120)

**Comment by bianchifan** [comment]
@Kaalleen
When you select several Paths and turn them into a satin it works on the first view..
But when you select a single path out of them afterwards this path suddenly converted back to a zigzag.

3paths converted all together
![Bildschirmfoto vom 2023-05-28 13-30-13](https://github.com/inkstitch/inkstitch/assets/17491743/43b654f3-aee1-4870-9e68-9f553f37fa14)

One path selected and parametarized again :(
![Bildschirmfoto vom 2023-05-28 13-40-47](https://github.com/inkstitch/inkstitch/assets/17491743/c48a42e1-92b0-42b4-89b6-052180ef5dd7)

But when all three paths are selected once more..
![Bildschirmfoto vom 2023-05-28 13-42-28](https://github.com/inkstitch/inkstitch/assets/17491743/28d81246-5640-49a3-a61f-68a02007e398)

**Comment by kaalleen** [comment]
@safire3002 There is a new version of Ink/Stitch. Could you try if your issue is still showing up in Ink/Stitch 3.0.0?

@bianchifan That's a bit unfortunate in user experience... If you select several elements with various parameters, the parameters will only be saved if you explicitly set them. To the left of the specific param there will be a pencil symbol when it is going to be saved. So in this case you'll have to disable and enable the satin column checkbox again....

**Comment by safire3002** [comment]
@kaalleen it was an issue yesterday when I installed 3.0 and tried it the same way, but I tried kind of what @bianchifan was saying and applied a satin stitch to each group one at a time instead with all of them selected at once, and it turned out almost every one of those groups was still a zigzag stitch instead of a satin stitch. no idea why. but once they were all converted and selected, it was able to auto-route them :)

thank you guys!!
