### ISSUE TITLE
Ink/Stich is an Inkscape plugin. Please install and run Inkscape before installing Ink/Stitch.

### ISSUE THREAD

**Issue by kgvol** [inkstitch/inkstitch#2329]
I'll start from the very beginning, I have a MacBook Pro 13 M1 with macOS Ventura 13.4. 
With little difficulty installed the current version Inkscape (1.2.2),  but when installing Ink/Stitck the above error appears. I tried to install Ink/Stitch both with the program running and closed.
No information on this topic was found, what could be the solutions to this problem?

**Comment by kaalleen** [comment]
You could try to use the zip install for Big Sur / Monterey: https://inkstitch.org/docs/install-macos/#installation-fails

**Comment by kaalleen** [comment]
No further response. Closing
