### ISSUE TITLE
Manual setup instructions could use some love

### ISSUE THREAD

**Issue by rumpeltux** [inkstitch/inkstitch#233]
I believe the [manual setup instructions](https://inkstitch.org/docs/install/) are too brief. I ran into a bunch of issues and here’s how I resolved them. I hope this is useful for future readers, or even better can be used to make the documentation better.

First, installing the requirements.txt using pip failed for me on Debian, because wxPython is complicated.
Removing it and installing the platform specific package (python-wxgtk3.0 I guess) solved this.

The install as directed [here](https://inkscape.org/en/gallery/%3Dextension/) is probably an outdated link. What worked for me was this:

    cd .config/inkscape/extensions
    ln -s /path/to/inkstitch
    for i in inkstitch/inx/inkstitch_*.inx; do ln -s $i; done
    ln -s inkstitch/inkstitch.py

Not sure if there’s a better way.

Next thing was this error:

    import libembroidery
    ImportError: No module named libembroidery

The .travis.yml helped me resolve this in the Embroidermodder-master/experimental directory:

    qmake swigpython.pro && make

I then copied `python/bindings/*libembroidery*` to the inkstitch directory and was finally able to run the extension :)

**Comment by lexelby** [comment]
That sounds about right.  Thanks for filling in the details here, and welcome to the project!

To be quite honest, I've let the manual installation instructions languish kind of on purpose.  The zip/tarball installation method is so much easier and eliminates any need for installing dependencies, and it works on any distribution.  I don't really want to try to support regular users installing manually.  That said, your tips here would save advanced Linux users some time, so please feel free to submit a PR for the docs and we can get that merged in.

In my mind, the only good reason to go through the effort of manually installing like you've done is if you want to develop on the Ink/Stitch code.  Then symlinking allows you a way faster iteration time.  

Are you by any chance interested in hacking on the Ink/Stitch code?  If so please let me know if you have any questions as you read through the code.  One of the "to do" items in the back of my mind is to write up some docs to help new devs understand the project, but I haven't gotten there yet.  Hopefully I can bridge the gap by directly answering questions instead :)



BTW, your esp-button repo looks neat!  I never did get around to installing micropython on any of my ESP8266es.  Someday maybe :)

**Comment by rumpeltux** [comment]
Agreed that the zip method is easier. Maybe this would better fit into a getting started guide for developers.

On my debian machine inkstitch wasn't working: when creating the embroidery file the process would hang and not do anything. I wanted to see if I can easily find out what’s wrong, but that didn't work with the zip method.

Once I installed it manually I couldn’t reproduce the bug anymore though and the tool was working fine for me :)

**Comment by kaalleen** [comment]
Welcome @rumpeltux and thank you for your remark on the documentation, which gave me the idea that it might be time to setup a developers section on the website. It is quiet basic yet with only your additions for manual install: https://inkstitch.org/developers/inkstitch/manual-setup/

**Comment by lexelby** [comment]
Awesome!  In my copious free time I hope to at some point add more to that developer section :)

**Comment by lexelby** [comment]
Closing this one because the docs have been updated.  For further developer-oriented questions, please do open another issue.  That'll help me know what to document.
