### ISSUE TITLE
Auto route running stitch

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2335]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/f795776b-60ab-4a42-bd22-03f65975fe39)
I am getting this error when trying to run auto route running stitch on inkscape 122 inkstitch 300 and windows 10

**Comment by gusvisser** [comment]
Yes i do wil post later

**Comment by gusvisser** [comment]
![AUTO RUN STITCH](https://github.com/inkstitch/inkstitch/assets/85417086/4b9a1e8b-f1ab-4aa7-b991-ea4a24ce73c2)
Here is the svg file as requested

Gus Visser

**Comment by kaalleen** [comment]
Thanks. This is fixed. But results will be better without the preserve order option.
