### ISSUE TITLE
V 3.0 Params not opening

### ISSUE THREAD

**Issue by BajaProg** [inkstitch/inkstitch#2338]
I just updated to V3 and it is installed in inkscape - ext- Ink/Stitch (about says v3.0)
but params is not opening. V2 worked great... small window says" params " working please wait then disappears.
I have deleted and reinstalled V3 same thing.
any ideas???
oh.. V3 works fine on my other laptop.

I'M running:
Device name	P208HKMM
Processor	Intel(R) Celeron(R) N4100 CPU @ 1.10GHz   1.10 GHz
Installed RAM	4.00 GB (3.81 GB usable)
Device ID	18D7E95E-3515-4703-B007-B071AB6814E9
Product ID	00329-00000-00003-AA588
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Comment by kaalleen** [comment]
Which operating system do you use?

**Comment by stephaniegemau** [comment]
Je viens de mettre à jour vers la V3 et elle est installée dans inkscape - ext- Ink/Stitch (à propos de la v3.0)
mais les paramètres ne s'ouvrent pas. La V2 a très bien fonctionné... une petite fenêtre indique que "params" fonctionne, veuillez patienter puis disparaît.
Windows 10 pro éduc, 64bits, x64

**Comment by kaalleen** [comment]
Are other Ink/Stitch methods working? If not, this is most could be a antivirus issue.

If yes... hm, maybe this is same issue as we've seen for the lettering? Could you try this version here and see if this works? https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-lettering

It is just a guess into the blue, so I could be terribly wrong about this.

**Comment by stephaniegemau** [comment]
J'ai essayé, j'ai même enlevé l'anti virus et les pare-feu Windows et toujours identique, je laisse tomber

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BajaProg** [comment]
Thanks for the help..  The trouble is on my work computer so could be anti-virus... I will try to get around that.

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎9/‎7/‎2022
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by kaalleen** [comment]
Could you try if anything else is working, such as the stitch plan preview ...

**Comment by stephaniegemau** [comment]
Yes , Can I try other thing

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BajaProg** [comment]
no luck with stitch plan preview... the selection window opens (live preview, apply close etc.) but nothing after.

nothing will open (lettering, preferences, simulator/ realistic preview) but the choices are all there.

**Comment by BajaProg** [comment]
oh I reinstalled V2.0 and everything works..
tried V3 again sadly still not working.

**Comment by kaalleen** [comment]
@BajaProg this is most probably a virus program issue. Sorry, I couldn't help.

**Comment by Cathcast85** [comment]
Bonjour,
J’ai téléchargé V3.0 sur trois ordinateurs Windows 10. Je n’ai pas d’antivirus. J’utilise uniquement Windows Defender. Les trois fois l’installation semble bien se passer, aucun message d’erreur, tout est conforme. Je redémarre mes ordinateurs, lance Inkscape, crée un objet brodable. Dans le menu des extensions je vois Inkstitch, les différents onglets sont présents lorsque je veux les activer ça ne fonctionne pas. C’est pareil sur les trois ordinateurs.

**Comment by kaalleen** [comment]
Windows defender is very well known to quarantine Ink/Stitch. You can however whitelist inkstitch.exe so it won't get deleted.

**Comment by stephaniegemau** [comment]
Ok mais pourquoi que une partie de inkstitch ne fonctionne pas? Toute la partie visualisation mais pas le reste?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kaalleen** [comment]
@stephaniegemau I think we are discussing different issues here. I got a feedback that nothing works (only some inkscape native windows open, but without functionality). This would indicate a virus program issue.

If for you only the params don't work, it'd be interesting if the linked version above has the same issue. Or if you see any error message when you try to run the params.

**Comment by Cathcast85** [comment]
Bonjour,
Comme vous le demandiez, j’ai désactivé Windows defender durant le téléchargement. Puis j’ai exclus Inkscape et Inkstitch comme ce que montre la photo 3.J’ai redémarré, lancé Inkscape , dessiné un objet brodable. Inkstich est présent dans le menu ( photo 2)mais si je veux utiliser les paramètres par exemple, une fenêtre s’ouvre( photo 1) puis se ferme sans que la fenêtre Inkstich se lance.
Voici le problème que je rencontre avec la version 3.0. Je fais partie du groupe facebook français Inkscape Inkstitch, nous sommes plusieurs sous Windows 10 à avoir ce problème.
Pour moi, le fait de désactiver Windows defender, d’avoir fait une exclusion pour Inkscape et Inkstitch n’a pas résolu le problème.
Cordialement,
Catherine Casteran

Envoyé par myMail pour iOS

dimanche 4 juin 2023 à 22:15 +02:00 de ***@***.*** ***@***.***>:

**Comment by kaalleen** [comment]
The photos were not send. I think you'll have to login to the GitHub website to send images.
Could you double check if the inkstitch.exe file is still within the inksatitch installation?

**Comment by kaalleen** [comment]
Does this happen only on windows 10 enterprise or education? Are the windows systems up to date?

Is nothing at all working? Params, simulator, lettering, stitch plan preview, etc?

**Comment by BajaProg** [comment]
Hi **@kaalleen** thanks for your suggestions (virus program issue) I will keep trying to fix this and reply back.

Seems odd the V2 worked fine on the same computer.

And yes the ink stitch menus are all there..

Trying to run params on a simple rectangle just does not open.

Is nothing at all working? Params, simulator, lettering, stitch plan preview, **No nothing**

I will keep trying

**Comment by kaalleen** [comment]
The menu will still be there, even if the virus program deleted the inkstitch.exe file. So you'll need to go to the inkscape settings and open the extensions folder through there. Enter the inkstitch folder and see if there is an inkscape.exe file in there.

**Comment by Wiiilmaa** [comment]
Same problem here on Windows 7 Professional, version 2.2.0 works great, On version 3 only a small window saying "Please Wait" pops up for a split second
There is no "inkscape.exe" file in the extension folder as asked in the previous answer, but there is an inkstitch.exe there. it can be startet from the commandline but immediately exits without messages. Are there some parameters i could pass to it to further investigate the problem?

**Comment by kaalleen** [comment]
Oh, yes, sorry. insktitch.exe of course...

Run Inkscape and an Ink/Stitch extension. After this has failed, open the event viewer in windows. Click on errors and search for application errors in the errors list and double click it. Post error message here.

**Comment by BajaProg** [comment]
Wow..  @kaalleen 

The numpy-fix version seems to be 100%  working.

Params is running fine now.. Everything is opening and stitching.

What was the issue ? Something with the pop-up box?
Might  there be a problem with future releases?

Thank you so much,
@BajaProg

**Comment by kaalleen** [comment]
Ink/Stitch is dependent in other python libraries. When they update, it is always possible that it breaks something on some systems. In this case newer versions of numpy seem to have issues with some CPU types. So now that we know that, we can downgrade numpy for now. Of course it is always possible that things break in other releases for whatever reason, then we'll need to find the reasons. But glad to hear this is working for now. And thanks for error reporting and feedback!

**Comment by stephaniegemau** [comment]
Bonsoir Kaalleen, je l'installe demain,je suis tombée très malade donc je n'ai pu rien faire depuis 1 semaine, sorry

**Comment by Cathcast85** [comment]
Bonsoir Kaalleen, j’essaye d’installer la nouvelle version samedi ou dimanche. Je vous tiendrai au courant et j’en profite pour vous remercier vivement pour tout ce que vous faites, pour vos réponses et votre aide. Un grand merci !

**Comment by kaalleen** [comment]
Thanks go to @rejbasket 

I wish you'll be better soon @stephaniegemau

**Comment by Cathcast85** [comment]
Bonjour Kaalleen,
J’ai installé la version  du lien https://github.com/inkstitch/inkstitch/releases/tag/dev-build-rejbasket-windows-numpy-fix
ET BIEN ÇA MARCHE !!! 👍👍👍👍👍👏👏👏👏🤩🤩🤩  UN GRAND MERCI ENCORE.

**Comment by Cathcast85** [comment]
Bonjour Kaalleen,
Je fais partie du groupe facebook français dédié à Inkstitch. Sur ce groupe, d’autres personnes ont le même problème que celui que j’avais. Puis-je communiquer le lien pour qu’ils l’essayent eux aussi? En vous remerciant pour votre réponse.

**Comment by kaalleen** [comment]
Yes, of course!

**Comment by stephaniegemau** [comment]
Hello, j'ai enfin pu installer la nouvelle version, un grand merci aux développeur et surtout à Kaalleen, tous fonctionne à merveille, je vais pouvoir m'amuser un peu maintenant.
