### ISSUE TITLE
Save pdf

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2340]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/103b2761-d389-4c6b-9d89-61b2c764e564)
in the save as there is not a pdf  option  only all files as of now have to enter the extension on the name 

running win 10

Gus Visser

**Comment by kaalleen** [comment]
Does this work for you?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-pdf-output-format

**Comment by gusvisser** [comment]
Wil check in weekend

Thanks

**Comment by gusvisser** [comment]
i checked it and that is working properly now

Thank You
Gus Visser
