### ISSUE TITLE
Huh, are these artifacts only showing up when you push the button?

### ISSUE THREAD

**Issue by michelebotte** [inkstitch/inkstitch#2342]
Huh, are these artifacts only showing up when you push the button?

Last weekend I learned, that the needle points never really worked in windows.
Here is a needle point fix (hopefully): https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-windows-npp
I'd like to hear if this works for you...

_Originally posted by @kaalleen in https://github.com/inkstitch/inkstitch/issues/2339#issuecomment-1573762774_

**Comment by kaalleen** [comment]
Thank you! I'm going to close this then :)
