### ISSUE TITLE
Inkstitch V3.0.0 Lettering doesn't work 

### ISSUE THREAD

**Issue by Gabiczr** [inkstitch/inkstitch#2345]
Hello,

Anyone have this error when you try to use the Lettering from inkstitch the 3.0.0 version 

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering.py", line 499, in effect
  File "lib\extensions\lettering.py", line 62, in __init__
  File "lib\extensions\lettering.py", line 187, in set_font_list
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

How can it be fixed this issue ?

**Comment by kaalleen** [comment]
Note to myself ... Same as #1186 (Ink/Stitch v2.0.0). I wonder why this is showing up again. The fix hasn't been removed ...

**Comment by kaalleen** [comment]
Could you test if this solves your issue?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-win-wxpython-version

**Comment by Gabiczr** [comment]
Hello,

Thank you very much for your hard work, now its working ! Thank you Kaalleen
