### ISSUE TITLE
New document

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2347]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/6d1f4b65-c83c-4986-822a-5faed37ef03c)

Every time when i start a new document and create my first object and want to apply params i get this message  then i click the ok button and go back to the params and then it opens properly 

running windows 10

Gus visser

**Comment by kaalleen** [comment]
Phew, thanks for reporting this. Fix one thing and break an other. When will this ever end :D
I created a pull request and will send you a link for a test when it finished building.

**Comment by gusvisser** [comment]
Sorry for all the inconvenience but better now so that soon there wil not
be too many more

**Comment by kaalleen** [comment]
Yes, so true!! I'm glad you discovered the issue.

Here you go: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-windows-no-elements

**Comment by gusvisser** [comment]
Everything appears to be working now

Thank you

You are AWESOME

Gus Visser
