### ISSUE TITLE
Something strange in two letters from the NAMSKOUTAGS font. Inkstitch 3.0

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#2353]
The letters O and U created i july 2021 comes with an extravagant jump stitch at the end of the first color. It was not the case in previous versions. In the letter O there are two overlapping nodes that do not exist in the creation file.
I send you one of my testfiles from 2021. You can see in the DST file that every thing was correct but now if I open the SVG file the error occurs.
![testfin2](https://github.com/inkstitch/inkstitch/assets/54963659/8bf76b06-e41c-4442-a6df-704f843de30f)
![Capture d'écran 2023-06-06 154916](https://github.com/inkstitch/inkstitch/assets/54963659/b25a643f-fe81-40fd-a87a-08bf4ed5c5d3)

**Comment by Augusa** [comment]
Screenshot from the jumpstitch
![Capture d'écran 2023-06-05 151748](https://github.com/inkstitch/inkstitch/assets/54963659/07fe042a-5e83-463c-981a-1f1565df60cf)

**Comment by kaalleen** [comment]
Thank you for reporting the issue with your font and sorry for that. The paths o and u paths actually do have an additional point in them which is responsible for the jump stitches. They must have been ignored previously. We may need to think about how to handle cases like this later on, but for now I think it's best just to fix the paths. I created a pull request to do exactly that.
