### ISSUE TITLE
Win10 install add-ons failure for V 1.13.0

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#236]
![2018-07-19 17_46_26-installation failed](https://user-images.githubusercontent.com/2872643/42954131-41192700-8b7c-11e8-86f3-677a3f2ca441.png)

Inskscape version: Inkscape 0.92.2 (5c3e80d, 2017-08-06)
inkstitch-v1.13.0-win32.zip

- greetings ! Daniel

PS: I removed all the extension files before unzipping

**Comment by danielkschneider** [comment]
Oh, and TRIM and STOP missing in the params->Autofill dialog

I don't know if I should have opened a different bug since it just might be a packaging issue.

![2018-07-19 18_07_54-preview](https://user-images.githubusercontent.com/2872643/42955913-e7910178-8b7e-11e8-8381-f6bd53228ad1.png)

**Comment by wwderw** [comment]
Stop and trim are in the attach functions part of the extension.  The failure of install add ons would have affected that.

**Comment by lexelby** [comment]
Not sure what's up with the add-on installer.  Could someone test v1.13.0 on windows and linux and see if this problem occurs for them?

**Comment by danielkschneider** [comment]
It does not happen on my Linux (Ubuntu 18.04). Only on Win 10 (on two different machines)

**Comment by wwderw** [comment]
It must be something with Win 10 itself.

Add-on installs just fine on my Win 7 VM.

![add ons](https://user-images.githubusercontent.com/24878362/43132913-d2e6f714-8f02-11e8-9207-9659674ad7eb.PNG)

**Comment by lexelby** [comment]
Alrighty.  I'll try in my win10 VM when I get a chance.

**Comment by AkiraNorthstar** [comment]
I get this error message too.

Windows 10 (1803) x64 without an antivirus program.

Tested with:
- inkstitch-v1.18.0-win32.zip
- Inkscape 0.92.3 (binary archive in 7zip format x64)
- Inkscape 0.92.3 (binary archive in 7zip format x86)

Manual installation of the files via drag and drop were successful.

Does one of you have a Windows 10 as x86 variant to test?

Maybe the x64 operating system prevents the copying of the desired files?

**Comment by AkiraNorthstar** [comment]
A test with VirtualBox and Windows 10 (1803) x32, inkstitch-v1.18.0-win32.zip, Inkscape 0.92.3 (msi installer x32) results in the same error as described above.
So it's fundamentally Windows 10-related.

**Comment by lexelby** [comment]
Yup, I'm able to reproduce it too.  I'll take a look.

**Comment by AkiraNorthstar** [comment]
Do you mean that it is the copy function?

**Comment by AkiraNorthstar** [comment]
Unfortunately, the error message still appears.
However, now comes another message:
![message](https://user-images.githubusercontent.com/16691957/44712049-2f570c00-aab0-11e8-86f0-4214a10ddbaf.png)
Translation of the dialogue text:
> The called script passed additional data to Inkscape. There was no error message returned by the script, but the result may be unusable.

All thread catalogs have been installed and can be used!
Only the Visual commands are not installed.

**Comment by lexelby** [comment]
Ah, sorry, I didn't yet actually _fix_ the problem. ;)  The branch is named `fix-windows-install` because that's what I'll be doing in that branch, but at the moment all I did was add an extra error message so that I can see what files it's trying to copy.

Thanks for posting your results! I think I know what the bug is now.

**Comment by JerryGavin** [comment]
I am having the same issue with Windows 7. The software was a new install on September 9th, so I believe it to be the latest version.
Thanks!
Jerry

**Comment by lexelby** [comment]
@JerryGavin Hi, and welcome to the project!  I'm sorry it looks like I fixed this and never got around to merging the fix!  Keep your eye out for a new release coming soon (hopefully today).

**Comment by lexelby** [comment]
I'm so glad to hear that!  We'd love to see what you've created.  And if you're interested in contributing to the project, we have lots of opportunities for folks with a variety of skill sets (not just programming).

I've just tagged version v1.19.0 for release.  Once the build process finishes, it will be posted to the releases page.
