### ISSUE TITLE
Params option not working (second edition)

### ISSUE THREAD

**Issue by megaceros1111** [inkstitch/inkstitch#2361]
Hello! Like in this closed thread from 2020: https://github.com/inkstitch/inkstitch/issues/828 :
"Params" will not open, "Convert Line to Satin" either, in fact no menus or actions will work. 
Clicking on anything in the Inkstitch menu will  open a tiny window that closes a split second after.

Inkstitch and Inkscape have updated since, so the troubleshooting of the closed thread does not apply.
I have tried many things, including instaling an older version of inkscape, but to no avail.

i am slowly loosing my sanity over this, if anyone has an idea of what i could do, please share :'>

**Comment by megaceros1111** [comment]
(found another thread treating this issue; i will go there: https://github.com/inkstitch/inkstitch/issues/1525 )

**Comment by kaalleen** [comment]
Which operating system do you use?

**Comment by kaalleen** [comment]
From the threads you were looking at I suppose this is linux.
Check out if this solution works for you: https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds

**Comment by kaalleen** [comment]
Ah no, nothing works... so ... does issue #1525 solves your issue?
