### ISSUE TITLE
AVG thinks there is malware in 3.0

### ISSUE THREAD

**Issue by MadTooler** [inkstitch/inkstitch#2363]
AVG is giving me a malware warning when I try to install 3.0 in windows 10 64b.  I assume it is a false find, but it would be nice to double check.

"inkstitch-v3.0.0-windows.exe" infected with "FileRepMalware [Misc]"

Please confirm if this is a valid find or if I should report as a false positive.

Thanks!

**Comment by MadTooler** [comment]
AVG happened to want to update, after which it now quarantines 3.0 upon a scan of the file before install.

**Comment by kaalleen** [comment]
Thanks for reporting. This is a false positive.

**Comment by MadTooler** [comment]
Good to hear.  I definitely would not expect any issue from a dedicated group like you at inkstitch.  I know with my open source projects I do use a lot of other sources, sometimes a bit concerned I may pass on something accidentally I would rather not.

I appreciate the hard work!!!  Using the 2.x release, this is a little something I tinkered with designing and testing today as a sample piece while I figure out neighboring fills and satin stitches for a more complicate project (added to a quilt block that was needed to replace an accidentally cut section, as a fun reminder to make the repair more fun than painful)... 
![bandaidOops](https://github.com/inkstitch/inkstitch/assets/16729670/61c1e2a2-4d14-4266-bc21-0069ccf0c105)
