### ISSUE TITLE
issue creating custom fonts

### ISSUE THREAD

**Issue by safire3002** [inkstitch/inkstitch#2364]
thanks again for helping me with my previous issue, guys. i wanted to solve this by myself, but my programmer friend and the inkstitch discussion group on facebook can't figure it out.

my previous font i made came up with numerous errors that were only remedied by me making a completely new svg file and copying and pasting each glyph back into its respective layer in the new file. i didn't create the svg file any differently than i did before with font forge. i'd rather not do that this time if i can help it.

with this new font i've made, i made sure to test it in lettering as i went with every 10 letters or so i made. everything was going great with the previews and i finished for the day, only to come back to it the next day not working and showing this error.

<img width="482" alt="Screenshot 2023-06-10 at 6 19 06 PM" src="https://github.com/inkstitch/inkstitch/assets/134817062/a86d305d-4840-46a5-a2bb-96a9a6da3068">

this looks to be the same kind of error that came up with my previous font. i'm attaching my file here to see if you guys can help me figure out what i'm doing wrong or if there's an issue with the software. i'm using 3.0. thank you for all of your help!
[Reenie Beanie.zip](https://github.com/inkstitch/inkstitch/files/11713534/Reenie.Beanie.zip)

**Comment by kaalleen** [comment]
Then I'm really glad you came here. Always when you see a traceback message, it is a bug in Ink/Stitch we'd love to know about. This will also save others from running into the same problem at a later time.

I'll create a pull request which fixes the issue. But you could also fix it in the font file:

The trim command for the `t` is broken. Remove it and your font will work fine. With the new trim options in the lettering tool, you could actually rely on these only or if you really want to enforce the trim commands you could as well use the trim option in the params dialog which is less likely to fail.

**Comment by kaalleen** [comment]
Btw. this is a nice ofl font. Which license wise could be part of the inkstitch standard fonts - just if you'd like to add it when you are finished ... ?

**Comment by safire3002** [comment]
@kaalleen thank you! you're reading my mind. i'm planning on uploading this and instrument serif to the fonts library as soon as i'm able to test them out on my embroidery machine. i want to digitize more of the google font library as well. just trying to do my part for the free and open source community!

**Comment by kaalleen** [comment]
What a nice response! Do you want to become a member of the inkstitch repository?

**Comment by safire3002** [comment]
@kaalleen yes please! currently in a facebook group and having them troubleshoot my font to make it better

**Comment by kaalleen** [comment]
Sounds great. If you need any help/instructions don't hesitate to ask.

**Comment by safire3002** [comment]
thank you!! so i've tested out my font without an underlay on the top example, and i was noticing how the threads were looking strange on the thin parts of the letters. added underlay stitches to the example on the bottom and it fills those spots out nicely, however the underlay is really obvious to see. do you know what could be causing this? 

someone on facebook said it was because i'm not using a small needle, but i'm using the smaller sized gold needles. they also said my thread was too thick but i'm just using regular guterman dekor embroidery thread.

![354055447_6273040132774419_2075908628836258201_n](https://github.com/inkstitch/inkstitch/assets/134817062/dbb83440-fbc5-49cf-a602-7c1291b61996)

**Comment by kaalleen** [comment]
What is the size of the satin columns (width)?

**Comment by kaalleen** [comment]
Did you try on less stretchable fabric or with better stabilization as well?

**Comment by safire3002** [comment]
@kaalleen just found some regular fabric to sew on! it looks much better. the width of the smallest parts of the satin columns is about .9 mm and the bigger parts are almost 3 mm.

![IMG_0733](https://github.com/inkstitch/inkstitch/assets/134817062/72a5f46a-4e38-4f1c-9ae6-7c3e55d37926)
![IMG_0734](https://github.com/inkstitch/inkstitch/assets/134817062/8c5e554c-7701-4551-ac53-ea15c8ea91be)
