### ISSUE TITLE
Connecting satin lines together  feature

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2368]
when we create a long curvy line then set a line width and have inkstitch convert it to a satin then it creates multy satin sections
now when we want to connect them together by selecting two satin sections in node mode and then connect the end nodes on the rails it leaves all the rungs in one path so we have to select both paths and use combine

I was wondering if it is possible to when we connect the rails together that it then also does the combine of the rungs automatically

**Comment by tyrosinase** [comment]
That's a bug in Inkscape itself, and is being tracked here: https://gitlab.com/inkscape/inbox/-/issues/7261

**Comment by lexelby** [comment]
Really, we should have this feature, and Convert Line to Satin should use it automatically to connect all the pieces.  I meant to do that all along but never got around to it.

**Comment by lexelby** [comment]
#2418 will fix this once and for all!

@gusvisser Once #2418 is merged, Convert Line To Satin will always produce only one satin.  Do you feel like it would also be useful to have a separate extension so that you can connect your own satins together into one?
