### ISSUE TITLE
Convert to gradient blocks does not work as expected

### ISSUE THREAD

**Issue by Wiiilmaa** [inkstitch/inkstitch#2369]
convert to gradient blocks converts a linear gradient into overlapping blocks with varying density. My expectation was: The first block starts with a high density on the left, transistioning to a low density on the right. The second overlapping block starts with a low density on the left and transitions to a high density on the right, keeping the overall desnity at a constant level.

The first problem only occured in one file so far, and a subsequent try lead to the correct orientation of the transitions!
~~What "Convert to gradient blocks" creates is a different thing i cannot find any use for:
The first block starts with a high density on the left side and transistions to a low density on the right side, the second block does the same resulting in double the line density on the left and a fraction on the right, constantly using both colors for 50 percent of the lines.~~
~~I would like really like to have the density shift on the second block reversed.~~

~~Let's assume the denity gradient has been reversed and take a look at the distribution of densities:~~
The density shift seems to be created by a linear increase in line spacing up th the factor given in the convert to gradient block dialog. The standard value is 2, which results in two overlapping blocks transitioning from the original linespacing (let's call it density 1) to twice the linespacing (Let's call that density 0.5). At both ends start and end of the two blocks overlap, resulting in a density of 1,5 (First block with original line spacing and half as much added by the second block), in the middle, the density is 1.33. The ends can be improved by increasing the  end row spacing, but the center is optimal at an endrow spacing of 3 resulting in a density of 1 in the middle, whjile the density at the ends is still at 1.33. 
I would prefer a linear density gradient going linearly from 1 to 0 on the first block and from 0 to 1 on the second one resulting in a combined density of one using a rowspacing of "original row spacing / density", but that would require changes in the fillstitch routines to achieve.

**Comment by tyrosinase** [comment]
Pretty old tutorial, but in the days before the gradient blocks (which I haven't played with myself yet) you could use some hidden features to do a linear density gradient. Not sure if they're still around, but: https://silverseams.com/2020/08/special-effect-fills-with-ink-stitch.html

**Comment by Wiiilmaa** [comment]
The hidden feature described there is the linear line-spacing gradient leading to the second problem i described earlier. This "hidden" parameter is no longer hidden and available in the params dialog now, andi it is used for the gradient blocks. Because of density being 1/spacing, no linear density gradients are possible.

**Comment by tyrosinase** [comment]
Ah, yeah, I see what you mean now.

**Comment by kaalleen** [comment]
Are you asking for exponential distances for fill stitch?

**Comment by Wiiilmaa** [comment]
To maintain a constant density of the combined stitches, a linear density gradient would be necessary, resulting in a distance proportional to 1/x which is not exponential, but similar. The perfect pattern would be a solid fill with its repeat patterns having each row assigned to one of the two colors according to the density. 
An Example with the current implementation and distance 0.25 to 0.75, with the 1:3 ratio resulting in a spacing of 0.25 in the middle and kind of 0.19 at the ends. It was stitched from left to right and the latter color is immediately very prominent being still quite dense and being stitched on top.
![Stickverlauf](https://github.com/inkstitch/inkstitch/assets/212255/01f82046-f27a-45d0-8b1d-b58e31913f39)

**Comment by kaalleen** [comment]
I've heard that for color gradients it would even look better, if they were applied to a curved fill instead of straight lines, so the pattern changes won't be so prominent. Anyways ... you seem to know what you are talking about. Do you know how to code?

**Comment by kaalleen** [comment]
Future Ink/Stitch versions will include a new stitch type for linear color gradient.
