### ISSUE TITLE
Inkstitch github organization does not have branding applied

### ISSUE THREAD

**Issue by X3msnake** [inkstitch/inkstitch#237]
Only owners can change this, so it must be you @lexelby 

![image](https://user-images.githubusercontent.com/11083514/42960738-9bc64888-8b84-11e8-8c0d-70ac8d4a3b66.png)

https://inkstitch.org/assets/images/tutorials/logo/inkstitch_colour_logo.svg

**Comment by lexelby** [comment]
Oops!  Nice catch.  I'll take care of it now.
