### ISSUE TITLE
Inkstitch 3.0 for capitan

### ISSUE THREAD

**Issue by stichdw** [inkstitch/inkstitch#2370]
Is Inkstitch 3.0.0 of the installer package inkstitch-v3.0.0-capitan-catalina-osx.pkg really working on Mac OSX Capitan? In my Capitan it  does not work. The version which I found inside this installer package is named "High-Sierra-Mojave-Catalina".
Can you tell me, how I have to install it, that your package really works on my Capitan Mac OS.

**Comment by kaalleen** [comment]
Sorry, we do not provide a version for el capitan anymore. So High Sierra, Mojave and Catalina is correct for this package.

If you could try a manual install, but be warned that this isn't very simple: https://inkstitch.org/developers/inkstitch/manual-build-old-macos/
