### ISSUE TITLE
python-colormath has been archived

### ISSUE THREAD

**Issue by bkmgit** [inkstitch/inkstitch#2378]
Python-colormath is one of the dependencies of inkstitch. It has been archived:
https://github.com/gtaylor/python-colormath
It seems to only be used in:
https://github.com/inkstitch/inkstitch/blob/92623d460d82f01c01353a5a5c992ec53baf7f41/lib/threads/palette.py#L8

where
```
from colormath.color_conversions import convert_color
from colormath.color_diff import delta_e_cie1994
from colormath.color_objects import LabColor, sRGBColor
``` 
are imported

A possible alternative is skimage:
https://scikit-image.org/docs/stable/api/skimage.color.html
which has
- [skimage.color.deltaE_cie76](https://scikit-image.org/docs/stable/api/skimage.color.html#skimage.color.deltaE_cie76)
- [skimage.color.rgb2lab](https://scikit-image.org/docs/stable/api/skimage.color.html#skimage.color.rgb2lab)

Can make a pull request if of interest.

**Comment by lexelby** [comment]
👍 Go right ahead.  Thanks for auditing our deps!

**Comment by bkmgit** [comment]
Scikit-image is quite large, though maybe useful for other image processing operations. Other alternatives are:
- [basic colormath](https://github.com/ShayHill/basic_colormath) which is much smaller but only offers CIE 2000 differences, currently CIE 94 is used though CMC in SciKit-image may be better
- [colour](https://github.com/colour-science/colour/) which has CIE 94 but not CMC

**Comment by bkmgit** [comment]
Another option is [colorspacious](https://github.com/njsmith/colorspacious)

**Comment by lexelby** [comment]
It seems like we're having trouble finding a replacement module that is still maintained and that we can use on all platforms.  I wonder, maybe we should just stick with python-colormath?  Yes, it is archived and no longer maintained, but is that really so bad for us?  Color profile algorithms aren't going to change all that much, and python-colormath works great for our purpose.  Can we just keep it?

@kaalleen what do you think?

**Comment by bkmgit** [comment]
The functionality that is needed is to convert from RGB to lab space.
Could implement this functionality directly.

basic-colormath also does RGB to lab space conversion.  Maybe possible
to add relevant distance metrics.  It is relatively new though.

Colorspacious is used by several other projects, such as Matplotlib.  It
may be difficult to add functionality, but if it stops being maintained,
there will likely be a replacement.

Python-colormath is available for adoption.  Maybe it can become part of
Inkstitch?

**Comment by kaalleen** [comment]
> Color profile algorithms aren't going to change all that much, and python-colormath works great for our purpose. Can we just keep it?

Well, as long as it works with the python version we use, we can continue to use colormath.

> Could implement this functionality directly.

How much work/code would that be?

**Comment by bkmgit** [comment]
Have implemented it directly, replicating what was in colormath, testing
would be helpful.  Formulae used can also be found at:
https://github.com/LeaVerou/color.js/blob/main/src/spaces/lab-d65.js#L32
May want to revisit choices made in colormath to best
suit fabrics, or allow options for these, see for example https://colorjs.io/apps/named/

Ink/Scape does not yet do color matching for monitors https://wiki.inkscape.org/wiki/index.php/Color_management
though there is a suggestion to use a C library [LittleCMS](https://www.littlecms.com/color-engine/)
LittleCMS is incorporated in [Pillow](https://pypi.org/project/Pillow/) 
- https://github.com/python-pillow/Pillow/blob/main/src/_imagingcms.c
- https://pillow.readthedocs.io/en/stable/reference/ImageCms.html#
though the color space transformations do not seem to be exposed directly.

[PyOpenCV](https://pypi.org/project/opencv-python/) also seems to do 
[color conversion](https://docs.opencv.org/3.4/de/d25/imgproc_color_conversions.html#color_convert_rgb_lab)


Other related tools listed at https://www.color.org/opensource.xalter

Having some kind of color  matching support seems useful to enable realistic previews.
Optionally, allowing the user to change the color matching algorithm and get a preview
seems like a good feature to have.  PyOpenCV, Pillow and Scikit image seem best suited for these,
but would need to either get a few changes incorporated upstream or add required functionality in
Ink/Stitch.

**Comment by lexelby** [comment]
Thanks for all your effort here.  I think the best path forward is going to be to stick with python-colormath unless something causes us to be unable to use it.  If that happens, then your code in #2449 is probably the way we'll want to go.  For now though, I'd rather stick with what we know works, so that we don't have to try to test that the new code does what python-colormath does.

**Comment by bkmgit** [comment]
Ok.  The main difficulties preventing packaging in Fedora, likely also Epel for CentOS and related distros are colormath and electron dependencies.  At least for Fedora have added all other Python dependencies.  Would not want to add colormath unless it is maintained, perhaps Inkstitch could adopt it if there is a strong preference for it?

**Comment by lexelby** [comment]
Why can't Fedora and Centos packages use a stable but unmaintained library?

**Comment by bkmgit** [comment]
Python deprecates functions and features quite regularly, so maintenance is required:
- colormath uses nose for tests which is deprecated.
- the last release of colormath, 3.0.0 uses numpy.asscalar which is also deprecated.

Certainly one could modify colormath so that it is better adapted for fabric, or include the necessary
features from colormath in inkstitch directly.

It does build https://copr.fedorainfracloud.org/coprs/fed500/inkstitch/build/8157600/ so can get it included
in Fedora, but  for it to remain, it would need to be maintained.  It is unclear  if it would be helpful to
maintain it and possibly adapt it to be more useful in Ink/Stitch or add the necessary functionality that
Ink/Stitch uses directly to Ink/Stitch/

Having Ink/Stitch packaged in Fedora would enable easier generation of RPM packages that also work on
CentOS, Alma Linux, RedHat and Rocky Linux using [Packit](https://packit.dev/).

**Comment by bkmgit** [comment]
Am happy to help maintain colormath, but it maybe better to create a fork inkstitch-colormath and have that in pypi if there is interest in adding functionality.

**Comment by kaalleen** [comment]
What do you think @lexelby ?

**Comment by bkmgit** [comment]
Created https://pypi.org/project/colormath2/ which can update as needed.

Also happy for https://github.com/inkstitch/inkstitch/pull/2449 to be merged.

**Comment by kaalleen** [comment]
Nice, thank you for taking the time and effort to maintain the library! Will you create a pull request to update the dependency? What exactly is #2449 needed for now that colormath has an update?

@lexelby can you have a look at this. I'm not really good at these colormath things.

**Comment by bkmgit** [comment]
Pull request to use colormath2 https://github.com/inkstitch/inkstitch/pull/3266

**Comment by bkmgit** [comment]
Closing as  https://github.com/inkstitch/inkstitch/pull/3266 was merged.
