### ISSUE TITLE
stringcase seems not to be maintained

### ISSUE THREAD

**Issue by bkmgit** [inkstitch/inkstitch#2379]
[stringcase](https://github.com/okunishinishi/python-stringcase) has a number of open issues that seem to take a long time to get resolved. It seems to be used only in one file https://github.com/inkstitch/inkstitch/blob/main/lib/extensions/base.py to do a snakecase conversion. It maybe worth replacing it with:
- [Casefy](https://github.com/dmlls/python-casefy)
- [caseconversion](https://github.com/AlejandroFrias/case-conversion)
- A custom function to do the conversion
Can implement one of the above if of interest.

**Comment by lexelby** [comment]
Any of those options is fine with me.  By all means, if you're interested in fixing this, pick whichever seems like the best choice to you.

**Comment by kaalleen** [comment]
Yes, thank you for checking the dependencies. For an easy task like this I'd love if we could avoid just an other dependency. If I had the choice, I'd prefer the custom method...

**Comment by lexelby** [comment]
I was leaning the same way, so let's go with the custom option.

**Comment by bkmgit** [comment]
Ok.
