### ISSUE TITLE
Trim command

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2381]
![sturgeon cree color 3](https://github.com/inkstitch/inkstitch/assets/85417086/5706791d-8afd-4afc-a852-c4ffe10d9630)
As i am applying the trim command it shows on all objects of the svg file then when i create the dst file a lot of the trim commands are not applied

![image](https://github.com/inkstitch/inkstitch/assets/85417086/806808a0-b5ec-4efc-af28-c00baef91b05)

**Comment by gusvisser** [comment]
I think i got it figured out after i applied the trim command i had to reorganize a little in the order and did this by selecting first object then shift select next items and reorder with inkstitch this brought all objects lower in the order and the commands went to the top in the order of the group this way the command does not stay with the object i had to delete the previous applied commands and reapply new trim commands 

hopefully this can be resolved in the programming that once a command is attached to an object that after reorganizing it still is attached to the object

Thank you
Gus Visser

**Comment by kaalleen** [comment]
Thank you!!

**Comment by HeadgarPT** [comment]
I've also noticed that when I save my file as PES or DST, most of the jump stitches disappear, converting to trim stitches that I didn't add the command for it. 

There are some objects that I would prefer JUMP rather then trim. Is this a bug or a flaw in my design?

**Comment by tyrosinase** [comment]
Someone more knowledgeable than me may come along to correct it, but I think that's controlled by `Extensions > Ink/Stitch > Preferences` and changing the Collapse Length.
