### ISSUE TITLE
thumbnail preview of .pes file

### ISSUE THREAD

**Issue by emanuele-em** [inkstitch/inkstitch#2383]
Is there a way to show up the thumbnail with the preview of the design? The file I'm intersted in are .pes

**Comment by HeadgarPT** [comment]
The only way I know he's using the software that comes with your machine, in my case, I use PREMIER+ for Husqvarna machine, and I set all PES files to open with Premier+. Then, I can see the thumbnail with the preview of the design.

**Comment by gusvisser** [comment]
It wil depend on what operating system you are but im using the freesierra software what is an explorer plugin

**Comment by kaalleen** [comment]
If you don't to use an other program and don't mind to store two files, you could also save as inkstitch png with the same file name to obtain the preview image.

**Comment by emanuele-em** [comment]
thank you but my situation is different, I have a linux laptop that is only a container for all .pes files, the machine is brother and pe design is the software (of course only on windows)
