### ISSUE TITLE
Embroidery Files strange

### ISSUE THREAD

**Issue by carolundy** [inkstitch/inkstitch#239]
I am not a coder, but an experienced digitizer. I use and teach the Bernina software made by Wilcom. I have just discovered inkstitch, and am very impressed with work done so far. I am having a problem though. After setting parameters for a single shape, the simulation looks fine. I then select and save as an embroidery format. I have tried with both exp and hus. The output file seem to be corrupted in some way. I have attached screen captures of my results. I hope this is the right place to post this problem. If not please let me know.
![embroidery nodes](https://user-images.githubusercontent.com/20661026/43063207-9467a7ae-8e9e-11e8-8843-96322552eb93.JPG)
![exp 2](https://user-images.githubusercontent.com/20661026/43063214-99d2a7ca-8e9e-11e8-9ecd-1637a5b49d2b.JPG)
![exp](https://user-images.githubusercontent.com/20661026/43063220-9cfe8a86-8e9e-11e8-9045-37ed02ec2495.JPG)

**Comment by X3msnake** [comment]
I think that is a known bug in the export library tagged in one of the broken file formats and being worked on

but @lexelby and @tatarize are the best ones to shed light on this

https://github.com/inkstitch/inkstitch/issues?q=broken+label%3A%22broken+file+format%22

**Comment by wwderw** [comment]
EXP is one of the formats that is being going over in the latest PR.

Here is one of my designs exported as an EXP from the latest PR.


![exp](https://user-images.githubusercontent.com/24878362/43073855-a7f063fa-8e40-11e8-88fc-129f51c1b5bc.png)

**Comment by carolundy** [comment]
Thanks, I will do a bit more reading.

**Comment by lexelby** [comment]
@carolundy Hi, and welcome to the project!  As @wwderw said, the next major release will have a ton of fixes for embroidery file formats.   I'm hoping to release it sometime this week.  Until then, PES and DST are known to be stable.  Sorry for the inconvenience.

**Comment by carolundy** [comment]
Thanks, that is great news. I was hoping to do some videos for my YouTube channel, when I am comfortable using the plugin. I wish I could write code. I will try to help if I can.

**Comment by wwderw** [comment]
> I wish I could write code.

I'm right there with you.  Like you, I'm just a digitizer (going on 24 yrs here).  I think it was you that posted to one of my videos about Ink/Stitch.

**Comment by carolundy** [comment]
Yes that was me. Great videos. Helped me make sense of the documentation. I
am a visual person.

**Comment by carolundy** [comment]
I have a Bernina 780, and an old Pfaff, that I can still use until the old
XP laptop dies, so EXP and VIP formats. I know people with other brands
e.g. Janome JEF I love the Bernina software, but it is not cheap, and it
doesn't support JEF. ( Made by Wilcom, who also make the Janome software so
can't include JEF)

**Comment by X3msnake** [comment]
@carolundy we have a official inkstitch youtube channel in need of some love, don't you want to make some official videos to upload ther instead?

**Comment by carolundy** [comment]
I will look at how I can help with the documentation. From my experience
teaching software, many of those wanting to learn are sewers first, and
computer operators second, so they need very clear step by step
instructions, and lots of pictures. That is why I use video. It also helps
with language issues. One of my course participants is Italian, and doesn't
speak a word of English,  but she manages to follow my videos.

**Comment by tatarize** [comment]
The HUS file looks like it's a result of compounding write position error. Which I must attribute to the bug already found that does exactly that within libembroidery identified in issue #231 with regard to .jef files. It was identified and determined to be common to nearly all the writers in libembroidery save .dst files. And an issue with embroidermodder.

If that assessment is correct. This is already fixed in pyembroidery.  It should no longer be a problem after the pull request.

The .EXP files suffered from a variety of issues (including the aforementioned compounding write error). They were rigorously tested in pyembroidery, and while I neglected to catalog the errors, these should also be rectified.

It is worth noting that pyembroidery will export .exp files but not read or write .hus (same with .vip) as they have a non-standard compression to them. This is just a technical issue though and may be overcome.

Notably others like .csd .emb .art have an encryption to them (.emb and .art also have zlib compression) but even with libembroidery giving proper the proper .csd decoding scheme that might pose legal issues with regard to the DMCA Title I (17 U.S.C. 1201).

**Comment by tatarize** [comment]
@carolundy Can you test this again with v1.14.0? The update should fix it. And we likely can start closing these issues with regard to formats. (unless we can't).

![star](https://user-images.githubusercontent.com/3302478/43247118-9f8c53a2-9068-11e8-88bf-c1ce714c1a23.png)

**Comment by carolundy** [comment]
Will do.

**Comment by tatarize** [comment]
Yeah, actual sew tests are the gold standard for this. Also, there's a chance that it might do something during the sew that could be functionally wrong or unexpected. Like if it double stitches at a place. While not massively fundamentally a problem that's stuff we'd like to know. Sometimes the commands on particular machines will be slightly different than what the software might suggest and eagle eyes might catch it. It's minor, but it's one of those things you only catch during sews.

**Comment by carolundy** [comment]
Have test sewn the EXP and was all good. Have also done VP3 on my Pfaff and was also without problems.
The next hurdle will be underpathing. I was kind of hoping that once made into an embroidery file that the seperate areas would show in objects in inkscape and I could then manually arrange the order and add start and end points and pathing objects, but no it is all one path. But that is for another topic, and something tells me it is not an easy one. I think you have solved this issue.
Thankyou for all your work.
Cheers Carol

**Comment by lexelby** [comment]
Hooray, I'm glad file exporting is working well for you!

Regarding underpathing, I'd love to hear more about what you're looking for.  Feel free to open an issue when you have time and we can talk it over.
