### ISSUE TITLE
Fill to stroke

### ISSUE THREAD

**Issue by KWhitt92** [inkstitch/inkstitch#2391]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\fill_to_stroke.py", line 83, in effect
  File "lib\extensions\fill_to_stroke.py", line 107, in _remove_elements
AttributeError: 'NoneType' object has no attribute 'getchildren'

![TrinketTraderSymbolErrorFile](https://github.com/inkstitch/inkstitch/assets/137945011/ec5948f0-ed98-410f-ad95-e5fea6510c18)

**Comment by kaalleen** [comment]
Thanks for reporting and sending an svg file. We definitely need to fix this issue. As long as it is there, remove the stroke and keep only the fill before running the extension again.
