### ISSUE TITLE
Would anyone like to present Ink/Stitch during Kieler Open Source und Linux Tage in Germany in September?

### ISSUE THREAD

**Issue by Moini** [inkstitch/inkstitch#2397]
Hi!

Would there be any contributors or enthusiastic users in your community who would like to give a talk or maybe even show off what one can do with Ink/Stitch in a little booth in Kiel on September 15/16 this year?

Find all info here:
https://kielux.de/211 (German, sorry)

**Comment by kaalleen** [comment]
Oh wie schön. Ich wäre so gerne dabei. Nur leider habe ich im September so gar keine Zeit.

@Tina-Chris ist das vielleicht was für dich?

**Comment by Tina-Chris** [comment]
Also ich könnte das schon machen. Ist von mir aus ja nur eine Stunde

**Comment by Moini** [comment]
@kaalleen Danke für's Rumfragen!

**Comment by Moini** [comment]
@Tina-Chris Oh, cool :) Hatte die Seite schon länger offen, und darum Deine Antwort noch gar nicht gesehen!

**Comment by Moini** [comment]
Nur Samstag wäre super, falls das ginge.

**Comment by Tina-Chris** [comment]
Hab auch gerade erst geantwortet. Wäre ich dann da alleine? Soll ich die
Sticki mitbringen?

Moini ***@***.***> schrieb am Fr., 30. Juni 2023, 19:43:

**Comment by Moini** [comment]
Samstags ist eher die Community da, während am Freitag eher Firmen etc. da sind. Allerdings ... ist Freitag abend das 'Social Event' (aka Grillen)... auch irgendwie schade. Mmmh :) 
Sagen wir mal so, ich würde mir 'länger' wünschen, und darum den Samstag, aber Freitag ist für Dich vielleicht auch ganz nett. 
Samstag gibt es andererseits gemeinsames Frühstück, und die Verlosung des Hauptgewinns. Schwierig :)

Schau Dir einfach mal an, was wir unter 'Aktionen' so haben, und entscheide, wie's Dir am besten passt.

**Comment by Moini** [comment]
Hast Du Matrix oder bist Du zufällig auch im Inkscape-Chat unterwegs?

**Comment by Moini** [comment]
Wenn Du einen Stand oder eine Demo machst, klar, unbedingt! Das wäre super cool, das sozusagen 'in Aktion' mal zu sehen.

**Comment by Tina-Chris** [comment]
Neither nor. Aber threema. Und im git gibt's glaub ich auch einen privaten
messenger?

Moini ***@***.***> schrieb am Fr., 30. Juni 2023, 19:49:

**Comment by Moini** [comment]
(was meinst Du mit 'alleine' - keine weiteren Leute von Ink/Stitch? - falls ja: das kommt darauf an, ob Du noch jemand anderen zum Mitkommen animieren kannst)

**Comment by Moini** [comment]
Threema hab ich wieder nicht... Wie finde ich den Gitlab-DM-Chat?

**Comment by Moini** [comment]
Du kannst mir sonst auch direkt eine Mail schicken, an kontakt@kilux.de

**Comment by kaalleen** [comment]
@Tina-Chris @Moini Wir können die Veranstaltung gerne auf dem deutschen Teil unserer Webseite ankündigen. Vielleicht zieht es ja dann noch den ein oder anderen Ink/Stitch Interessierten nach Kiel? Ich setze das gerne rein wenn ihr wollt. Machst du einen Stand?

**Comment by Tina-Chris** [comment]
Ich denke ja immer, the more the merrier. Teilen find ich besser!

bianchifan ***@***.***> schrieb am Mo., 3. Juli 2023, 14:46:

**Comment by Moini** [comment]
Hi Ihr drei! 

@kaalleen Klar, wenn von Euch jemand in Kiel vorbeikommt, wär das super, wenn Ihr das auch bei Euch ankündigen könntet! (und wenn es hilft, noch weitere Leute zum Mitmachen bei Euch zu finden, natürlich auch - das müsst Ihr intern absprechen)

@Tina-Chris Danke! Ich habe Dir eine Mail geschickt. Bitte schreib mir alle Fragen, die Du hast!

@bianchifan Als Veranstalter kann ich nur sagen, dass mehr Leute auf jeden Fall besser sind :) Ich weiß nicht, ob Ihr untereinander Eure Mailadressen habt? Sonst kann ich über kontakt@kilux.de gerne den Kontakt herstellen, falls Ihr Eure Adressen nicht hier auf GitHub veröffentlichen wollt.

**Comment by bianchifan** [comment]
Sodele..wie ist denn momentan der aktuelle Stand?
Ist die Geschichte nun fix?
Hintergrund: Auf eine Anreise ins Blaue habe ich keinen Bock mehr und das Buchen von "Liegeplätzen" auf Campingpläzen ist auch nicht mehr so easy wie vor 20 Jahren.
Jedenfalls gibt es momentan die komplette Fahrt per Bahn für < 50€, das kann nächste Wocjhe schon ganz anders aussehen...
Es wäre mir sehr daran gelegen, dass möglichst zeitnah fest zu zurren.

**Comment by Moini** [comment]
Hab noch nichts wieder gehört von @Tina-Chris - vermutlich muss sie arbeiten oder hat grad andres um die Ohren? Sie meldet sich bestimmt, sobald sie kann.

**Comment by Tina-Chris** [comment]
Ja, steht. machen wir! aber eher nur samstag und freitag optional bei mir

Am Mi., 5. Juli 2023 um 11:38 Uhr schrieb bianchifan <
***@***.***>:

**Comment by Moini** [comment]
Ich hab grad @Tina-Chris die folgenden Infos gemailt, aber ich denke, das könnte alle interessieren, darum packe ich hier noch eine Kopie rein:

Zur Entscheidungshilfe und zur weiteren Info:

* Vorträge dauern bei uns standardmäßig 50 Minuten, sind aber nicht sehr interaktiv. Vorträge werden auch gestreamt, d.h. man kann auch online zusehen und nicht nur vor Ort.

* Workshops sind variabel lang, meist 2 Stunden (inkl. Auf- und Abbau des eigenen Laptops, also etwa 1:45h reine Workshopzeit), und haben Platz für 10 Teilnehmer samt Laptop, mit Anmeldung. Falls dann noch ein paar Leute 'einfach zugucken' möchten, ist das möglich, aber die bekommen dann keinen Platz am Tisch mehr, sondern nur einen Stuhl und können mangels Mausablagefläche nicht wirklich mitmachen.

  Für das Eintragen eines Workshops oder Vortrags findest Du hier alle Infos und Links:
https://kielux.de/referenten-info


* In der Ausstellung bekommt Ihr einen Tisch (Ihr habt die Wahl zwischen mehreren Modellen, ich denke, die großen CoWorking-Tische entsprechen wohl am ehesten Eurem Platzbedarf und der nötigen Beinfreiheit), soviele Stühle, wie Ihr anfragt, eine Mehrfachsteckdose und WLAN. 

  Du kannst ja bei Gelegenheit nochmal schauen, welches Möbelstück Euch am ehesten passt, und uns auch mitteilen, wieviele Stühle Ihr braucht.

  Alle Infos für Aussteller sind von hier verlinkt:
https://kielux.de/aussteller-info (nochmal anzumelden brauchst Du Euch natürlich nicht)

* Für die Umhängebändsel brauche ich dann auch rechtzeitig vor der Veranstaltung einmal eine Liste aller Leute, die bei Euch am Stand stehen möchten.

* Für die Ausstellerliste auf der Webseite bräuchte ich von Euch ein Logo (gern als SVG) und eine Beschreibung bis 600 Zeichen, und einen Link.

**Comment by Moini** [comment]
Ach so, falls Ihr für den Stand noch irgendwas zusätzliches braucht (z.B. mehr Steckdosen), sagt gern Bescheid!

**Comment by kaalleen** [comment]
Also mit dem Logo kann ich schon mal aushelfen. Die Beschreibung wird Tina bestimmt lieber selber machen.

[Logo](https://inkstitch.org/assets/images/inkstitch-logo.svg) 

Ich wünsche allen die teilnehmen eine tolle Zeit. Das wird bestimmt schön :)

**Comment by kaalleen** [comment]
Ah der Link: https://inkstitch.org/de/

Allerdings ist der Text auf der Startseite etwas unbeholfen. Den könnten wir mal anpassen...

**Comment by bianchifan** [comment]
> Hab noch nichts wieder gehört von @Tina-Chris

Ich erwarte kein Update im Minutentakt...

> Ja, steht. machen wir! aber eher nur samstag und freitag optional bei mir

Meine Planungen betreffen ebenfalls den Samstag, z.Z. präferiere ich eine Nachtfahrt mit Ankunft um 5:00

@Moini 
Ich habe offensichtlich mehrere emails erhalten, leider habe ich z.Zt. Probleme mit dem Zugriff :(

**Comment by Moini** [comment]
@kaalleen Danke schon mal für Logo/Link, ich habe Euch vorläufig zur Liste auf der Webseite hinzugefügt:
https://kielux.de/aussteller - Text fehlt noch.

@bianchifan Sag gern hier Bescheid, wenn ich nochmal schicken soll.

**Comment by kaalleen** [comment]
Ah, es geht eigentlich nur um die Beschreibung von Ink/Stitch. Ich dachte es ginge auch um das Angebot vor Ort.
Na dann könnten wir doch einfach schreiben "Ink/Stitch ist ein Inkscape-Plugin für die Erstellung von Stickdateien." Das sagt doch eigentlich alles oder ist das zu kurz?

**Comment by Moini** [comment]
Ihr könnt in den Text alles reinschreiben, was Ihr wollt. Die anderen Aussteller waren bislang etwas faul, und da sie auch Sponsoren sind, haben sie denselben Text für beides. Ich fände es eigentlich ganz nett, wenn da stünde, was am Stand passiert - und auch gerne, wann man Euch dort antreffen kann, sonst kommen Leute am Freitag mittag und suchen vergeblich.

**Comment by kaalleen** [comment]
Das macht absolut Sinn. Ja, dann lass ich mal die Finger davon :D

**Comment by bianchifan** [comment]
Und wie geht es nun weiter?
Wie organisieren wir das ganze, wer macht was?
Meine W6 werde ich nicht ankarren, ich könnte aber z.B. Patches mit dem InkStiich Logo anfertigen oder Käppis versuchen zu besticken, für eine präsentation aber nur höchst ungern ohne Rücksprache.

**Comment by Tina-Chris** [comment]
Ich plane meine Pfaff mit zu bringen. Ich habe aber erst so richtig Zeit
Mitte August Zeit für detail Planung.

bianchifan ***@***.***> schrieb am Sa., 15. Juli 2023, 11:30:

**Comment by Moini** [comment]
Hi - habt Ihr zwischendurch kurz einmal für mich eine Info, welche Tischgröße Ihr braucht (siehe https://kielux.de/content/downloads/2023/Ausstellungsinfo_2023.pdf , letzte Seite) und wieviele Personen kommen? (2 vermutlich)

Einen netten kurzen Beschreibungstext für
https://kielux.de/aussteller
brauche ich auch irgendwann von Euch, ist aber etwas weniger dringend als die Standplanung.

**Comment by Moini** [comment]
@Tina-Chris @bianchifan  Wir basteln am Wochenende das Programm zusammen - möchtet Ihr noch einen Workshop einreichen? 

Sonst fülle ich den leeren Slot mit einem 'normalen' Inkscape-Workshop, fände es aber irgendwie auch schade...

**Comment by bianchifan** [comment]
> @Tina-Chris @bianchifan Wir basteln am Wochenende das Programm zusammen

I'm so sorry.... aber ich hatte für ca. drei Wochen keinen Zugriff auf meine emails (vermuteter Fremdzugriff), aufgrund einer Browser Neuinstallation war auch Github futsch, die email  für die inzwischen auch hier obligate Geräte Verifikation ging natürlich an das gesperrte Konto.

So wie ich Tina verstanden habe, ist sie bis Monatsmitte außen vor, von daher muss ich wohl oder übel alleine voran preschen :(
Was genau verstehst Du unter einem Workshop?
Der Interpretationsspielraum ist diesbezügl. recht groß..
Mein Notebook schmiert seit 3.0 recht häufig ab, wenn Elektron das Ruder übernimmt.
Ob ich bis Mitte September ein zuverlässiges Linux installiert bekomme ist fraglich, Nvidia hat den Support Anfang letzten Jahres eingestellt, Linux user sind für die nichts weiter als spinnerte Deppen.

Zur Tischgröße kann ich mit Bestimmt heit sagen, dass ein Stehtisch nicht ausreicht, Da passt keine Sticki drauf, es sollte schon ein Coworkingtisch sein.
Außerdem sollte da noch einige Stickereien Platz finden ;)

Zum Beschreibungstext lasse ich  mir übers WE etwas einfallen und stelle einen Vorschlag hier ein.
Letztes WE habe ich eine Disk mit Eurem Tux Boot kreiert, dann aber nochmal neu aufgesetzt, nachdem ich Montagabend die zugehörige SVG gefunden habe - mein nachgezeichnetes Tuxilein war mir nicht smart genug.
Gestern abend wollte ich noch Text einfügen, leider bereitet InkStich da Probleme.
Bevor ich die hier einstelle mache ich zunächst einen zugehörigen issue auf, hat ja noch etwas Zeit...

**Comment by Moini** [comment]
Hi @bianchifan - oh weh, ja, so ein Verlust ist eine Vollkatastrophe... Gut, dass Du wieder hier bist! (und himmel, wie genial ist das denn mit dem Sticktuxboot? :star_struck: )

Zu unseren Workshops haben wir auf der Webseite folgende Info:
https://kielux.de/referenten-info

Ihr könntet währenddessen mit den bis zu 10 angemeldeten Teilnehmern gemeinsam irgendwas machen - was auch immer Euch da vorschwebt. Also z.B. ein Hands-On-Tutorial zum Vorbereiten einer oder mehrerer Grafiken für's Sticken (wäre jetzt so meine Vorstellung), an geeigneten Beispielen, bei denen Ihr das vorturnt und die anderen machen mit und können bei Schwierigkeiten sofort um Hilfe bitten. Für 10 Stickmaschinen wär der Platz wohl im Workshopraum etwas knapp,  aber mit Laptop, Inkscape und InkStitch kann man ja auch schon viel lernen. Und falls die Stickmaschine einigermaßen transportabel ist, könnte man am Ende das ein oder andere Bild einmal sticken lassen (keine Ahnung, wie lange das dauert - ggf. dann auch am Stand?). Standarddauer ist 1:50 h, mehr auf Anfrage.

Ich könnte mir vorstellen, dass Leute für sowas auch aus größerer Entfernung anreisen würden. 
Hilft das als Info?

Was den Computer angeht, so seid Ihr ja zu zweit. 
Wenn alle Stricke reißen, können wir Euch vielleicht sogar einen Leih-Computer zur Verfügung stellen. Den muss halt bloß vorher jemand einrichten, mit dem, was Ihr braucht, lässt sich sicher irgendwie auch hinkriegen.

Coworkingtisch ist vermerkt. Und das Bild in unseren internen Kielux-Team-Chat verlinkt, ist ja echt zum Staunen :D (darf ich das später irgendwann auch für einen Post in unseren Social-Media-Accounts verwenden?)

**Comment by bianchifan** [comment]
> Also z.B. ein Hands-On-Tutorial zum Vorbereiten einer oder mehrerer Grafiken für's Sticken (wäre jetzt so meine Vorstellung), an geeigneten Beispielen, bei denen Ihr das vorturnt und die anderen machen mit und können bei Schwierigkeiten sofort um Hilfe bitten.

Einverstanden, ich damit aber warten, bis Tina wieder mit an Bord ist.

> falls die Stickmaschine einigermaßen transportabel ist, könnte man am Ende das ein oder andere Bild einmal sticken lassen (keine Ahnung, wie lange das dauert - ggf. dann auch am Stand?). Standarddauer ist 1:50 h, mehr auf Anfrage.

K.A. welche Pfaff Tina anschleppen wird, es sollte sich dabei m.E. um ein Heimgerät Handeln. Also 2teilig und IMHO gut transportabel. Eine 1.5 wäre das gleiche rot wie meine W6, eine 20.0 bis trala (Icon ausgenommen) sind ein wenig größer, aber eigentlich ebenfalls transportabel.
Zur Stickzeit, sie variiert recht stark, je nach Motiv.
Das TUX Boot z.B habe ich zum Sticken auf spezieller Stickfolie designed, das benötigt deswegen mehr stiche als für das Motiv eigentlich notwendig wären. Die reine Stickzeit wird von Inkstitch auf ca. 50min geschätzt. Ich habe 16 Farben bzw. -nuancen vorgesehen, das wären 15 Farbwechsel a' ca. 2 min. Wenn man die weißen Farben ohne weitere Nuancierung einfach durchstickt, kann man sich 5 Wechsel sparen und damit ca. 10 min. 
Man darf  getrost von 1:15 - 1:30 ausgehen, sofern alles unfallfrei abläuft.

Beim Referenten-Info bekomme ich z.Z. Seitenladefehler.. :(

Die Stickdatei konnte ich soeben überarbeiten, mit dem horizontalen Füllstich funzt sie jetzt. Ich präferiere ich allerdings ganz klar den zirkulären, leider funzt der nicht so wie gewünscht, da muss ich wohl noch einen weiteren issue aufmachen.
Den aktuellen Stand stelle ich aber einfach mal zu Diskussion...
Apropos..selbstverständlich kannst Du alles nutzen, was ich hier einstelle, es können und werden sich aber noch 
aber noch Details ändern...

Simulationsergebnis:
![Bildschirmfoto vom 2023-08-05 18-47-27](https://github.com/inkstitch/inkstitch/assets/17491743/4f8075a7-1752-402a-ae4f-99c7b2b8a8ce)

SVG:
![21 Kielux neu](https://github.com/inkstitch/inkstitch/assets/17491743/f565ace3-570d-43c8-9ef0-08f2a3e3ace4)

PDF:
[21_Kielux.pdf](https://github.com/inkstitch/inkstitch/files/12267759/21_Kielux.pdf)

**Comment by Moini** [comment]
@bianchifan Ist das eine feste Workshopzusage? Falls ja, für welchen der beiden Tage? (wir müssen das Programm planen, ... sorry für den Druck, es geht leider nicht anders ... ). 

Kannst Du trotzdem schon grob was eintragen, damit wir mit der Planung loslegen können? Es braucht nicht im Detail alles zu stimmen, nur so ungefähr. Du kannst das alles später noch bearbeiten (Titel + Inhalt + beteiligte Personen). Nur den Zeitpunkt müssen wir leider jetzt schon festlegen. @Tina-Chris hatte ja auch weiter oben schon geschrieben (glaube ich), wann sie am ehesten kann.

Die Kielux-Webseite funktioniert bei mir im Moment, vielleicht war der Link kaputt? https://kielux.de/referenten-info

Danke für die Erlaubnis für's Weiterteilen, ist super cool :) (und anderthalb Stunden, hui, ja - stimmt, ist wirklich recht komplex das ganze!)

**Comment by bianchifan** [comment]
> Ist das eine feste Workshopzusage? Falls ja, für welchen der beiden Tage?

Fest??? Naja, warten wir's mal ab..  Ankomme Samstag früh um 9:00, Kiel HBF ( so in etwa nach Reinhard Mey)

> Nur den Zeitpunkt müssen wir leider jetzt schon festlegen

Such Dir was aus! maybe 2h nach der Mittagspause? Dann könnte ich vielleicht halbwegs ankommen.



> Kannst Du trotzdem schon grob was eintragen, damit wir mit der Planung loslegen können?

Wenn Du derart drängelst kann ich nur ganz allgemein formulieren:  (Sinnvoller) Aufbau einer Stickdatei.
Viele Stickneulinge  wollen übersehen bzw. wollen teilweise auch nicht wahrhaben das es nicht damit getan ist, eine SVG einzulesen und als Stickdatei abzuspeichern und wundern sich über lausige Ergebnisse bzw. Fehlermeldungen.


> vielleicht war der Link kaputt?

Die Internetverbindung ist hier z.Zt. miserabel, ich wollte gestern (und auch heute morgen) noch einen weiteren issue anlegen, hat nicht geklappert, sind ins Nirwana entfleucht.

Ich habe das Tux Boot heute nachmittag noch mal überarbeitet.
Ich habe zur bestehenden 9,95cm Version (für 10x10 Rahmen) noch eine 12cm "Disketten-Version" hinzugefügt. Neben diversen kosmetischen Änderungen wie z.B. eine dem "Original" angepasste Schrift habe ich die Stickreihenfolge massiv geänder,t ebenso fast sämtliche Start- und Endpunkte. Dadurch ist es möglich dass auch auf Maschine, welche keine Sprungstiche schneiden, in einer Tour abgestickt werden kann. Alle Farben sind jetzt so sortiert, dass man auch mit weniger als 10 Farben hinkommt, wenn man die entsprechenden Farbwechsel einfach auslässt.

![21_Kielux_neu](https://github.com/inkstitch/inkstitch/assets/17491743/a6e337ce-0589-4624-861b-f52f926d6309)

![Bildschirmfoto vom 2023-08-06 20-17-23](https://github.com/inkstitch/inkstitch/assets/17491743/e1b0b181-ba6d-471e-94b9-aaee83d1d1e1)

Ich hoffe, wir bekommen noch das Problem mit dem zirkulären Füllstich auf die Reihe;)

**Comment by Moini** [comment]
Na, das ist doch schon mal ein Anfang, @bianchifan :) - sollte so erstmal ausreichen. Wie gesagt, ändern kannst Du das alles später noch. 

Trägst Du das bitte noch in den Vortragsplaner ein? Dann können wir unser Konferenzprogramm fertigstellen. 

Die anderen Vortragenden warten schon ungeduldig darauf, damit sie ihren Arbeitgebern mitteilen können, wann sie Urlaub brauchen.

**Comment by bianchifan** [comment]
> Trägst Du das bitte noch in den Vortragsplaner ein?

Vortragsplaner???! Vortragenden??
Bislang war die Rede von einem Workshop!
Nur nochmal zur KLarstellung nach meiner bisherigen Kenntnis:
Vortrag: 
Ein Referent steht vor einer Gruppe mutmaßlich Interessierter und quasselt so vor sich her und im nAschluss gibt es eine kurze Fragerunde, die meisten Zuhörer sind danach genauso schlau wie vorher.
Workshop:
Ein übersichtlicher Kreis Interessierter erarbeitet ein Thema, unterstützt von einem/r oder mehreren Tutor/-in/-en.

Ein Vortrag benötigt ein ausgearbeitetes Konzept, ein Workshop nicht unbedingt.
Ich hatte ursprünglich mal angeboten Tina Chris zu unterstützen und nicht mehr.
Heute abend trage ich jedenfalls noc nichts ein, ich habe noch andere Sachen zu erledigen.

**Comment by kaalleen** [comment]
Auch wenn ich nicht dabei sein kann. Hier ein paar kurze Gedanken zum Thema.

Ich denke mal es geht um den Programmplaner, der sowohl für Vorträge als auch Workshops gedacht ist. Ich glaube nicht, das Moini dir jetzt noch schnell einen Vortrag unterjubeln wollte :)

Wichtig in der Workshop-Beschreibung wäre bestimmt zu erwähnen, dass Inkscape und Ink/Stitch vorinstalliert sein sollten und das aufgrund der Kürze der Zeit die ganz groben Inkscape Basics bekannt sein sollten (z.B. wie male ich eine Bezier-Kurve oder wie setze ich Füllungen und Konturlinien).

Inhaltlich könnte man ja ein kleines, ganz einfaches Projekt umsetzen. Eine kleine Zeichnung vektorisieren, dabei ein paar Parameter kennenlernen und dann die Stichpfade optimieren (so wie du das schon vorgehabt hattest). Nebenher kann man wunderbar ein paar Kleinigkeiten über die Besonderheiten beim Sticken lernen (push/pull, etc). Eine Stickmaschine im Workshop würde wahrscheinlich zu viel Krach machen. Stattdessen kann das Projekt ja schon vorgestickt mitgebracht werden.

@bianchifan Wir können wir uns gerne vorher treffen, wenn du Unterstützung bei der Vorbereitung auf den Workshop brauchst und deine zeitlichen Ressourcen das überhaupt zulassen. Du wohnst ja glaube ich nicht allzu weit weg. Dann stehst du damit vorerst nicht ganz alleine da. Auf der anderen Seite ist Mitte August auch nicht mehr lange hin und ihr könnt euch dann zu zweit absprechen. Wie du magst ...

**Comment by Moini** [comment]
@bianchifan Ich hoffe, @kaalleen konnte Dich etwas beruhigen - stimmt alles :) 
Du kannst auch noch mal die verlinkte Webseite (https://kielux.de/referenten-info ) anschauen, da steht das auch alles beschrieben.

Die Einreichfrist ist allerdings seit 1.8. vorbei... Das Programm haben wir zwar noch nicht gemacht, weil auch noch andere etwas verschlafen waren, aber vermutlich am Freitag spätestens bauen wir das zusammen. Bis dahin *MUSS* was eingetragen sein, dann versuchen wir das alles unterzukriegen.
Es ist schon sehr eng, da wir dies Jahr glücklicherweise ziemlich viele Workshopeinreichungen hatten - und wir nur einen einzigen Raum für alle Workshops haben.

Euer Standplatz ist aber reserviert, zum Glück ist das Lautstärkelevel in der Ausstellung eh hoch ;-)

**Comment by bianchifan** [comment]
> aber vermutlich am Freitag spätestens bauen wir das zusammen. Bis dahin _MUSS_ was eingetragen sein, dann versuchen wir das alles unterzukriegen.

@Moini 
Ich war soeben in der Lage sowohl ein "Rednerprofil" anzulegen, als auch einen Workshop mit rudimentären Angaben.
Von mir zuhause aus war das nicht möglich, aus welchen Gründen auch immer, mehr als eine Registrierung war nicht drin.

Mit der neuen Inkscape Version habe ich so meine Probleme, Menus führen ein ziemlich dramatisches Eigenleben und klappen im im falschen Zeipunkt auf und zu. Außerdem werden teilweise Änderungen an Objekten in untergeordneten Gruppen durchgeführt, obwohl diese gesperrt sind.

@kaalleen 
Ich habe absolut nichts gegen ein Treffen einzuwenden, wenn das Wetter mitspielt und Du der Ansicht bist, das es hilfreich sein könnte. Ich war noch nie auf den Linuxtagen und habe keinen Schimmer, was da so abläuft.
Die Workshops, an denen ich bislang teilgenommen habe, wären von deutlich längerer Dauer und Ende offen.
IMHO sollte das Ziel sein, den Teilnehmers das Bewusstsein dafür zu vermitteln, dass die Erstellung einer Stickdatei Arbeit bedeutet und kein Selbstläufer ist. 
Um das in knapp 2h hinzubekommen...., da fehlt mir einfach die Erfahrung.

PS: Ich habe noch diverse Anmerkungen, dafür nutze ich habe das Hobbyschneiderin Forum, ansonsten verödet der thread dort noch ;)

**Comment by bianchifan** [comment]
Aktuelle kielux "Diskette", die Stickreihenfolge wurde weiter optimiert.
Sie kommt ohne die Notwendigkeit aus, Sprungstiche während des Stickvorgangs schneiden zu müssen, die Farben so sortiert, dass man bis zu Wechsel erübrigen kann und einfach durchstickt, wie z.B. alle Weißtöne ohne weitere Differnzierung.
Des weiteren wurde ein 12cm "CD"  hinzu gefügt.

![21_Kielux_neu](https://github.com/inkstitch/inkstitch/assets/17491743/9c7cd1ca-421d-4368-9e1d-004f66ddbeb0)

**Comment by Moini** [comment]
@bianchifan Supi, Danke! :) Wenn wir das Programm fertiggebastelt haben, bekommst Du eine Mail von uns. 

'Open End' könnten wir nur am Freitag nachmittag anbieten, aber da seid Ihr ja noch nicht da.

Sa ginge das nur, wenn Ihr als letzte drankommt, und auch dann müssen wir irgendwann den Raum aufräumen und abschließen, da Veranstaltungsende.

Die Gebäude im Hintergrund sind übrigens einer der beiden großen Werftkräne und die alte Metallgießerei.

**Comment by kaalleen** [comment]
@bianchifan du kannst mich unter kaalleen@inkstitch.org kontaktieren wenn du magst.

**Comment by Moini** [comment]
@kaalleen Das Programm ist veröffentlicht - wenn Ihr mögt, könnt Ihr den Workshop intern schon ankündigen + die Leute sich anmelden lassen:

https://kielux.de/programm

**Comment by kaalleen** [comment]
@Moini ja na klar. Da habt ihr ja ordentlich was auf die Beine gestellt. Der Link ist jetzt auf der Webseite. Ich wünsche euch eine gute Zeit und gutes Gelingen :)

Vielleicht wäre es sinnvoll den Link bei der Programmankündigung zur deutschen Ink/Stitch Startseite zu setzen? Dann müssten eventuelle Interessenten nicht erst die Übersetzung suchen, wenn ihnen das Englische nicht so geläufig ist: https://inkstitch.org/de/

**Comment by Moini** [comment]
@kaalleen Danke! 

Klingt sinnvoll mit der deutschen Webseitenversion - aber vielleicht war die Frage gar nicht an mich gerichtet, sondern an einen der beiden anderen (wer auch immer die Webseite übersetzt bei Euch) :smiley:

**Comment by kaalleen** [comment]
Wer immer die Möglichkeit hat, das im Veranstaltungshinweis auf der Kielux-Seite zu ändern :)

**Comment by Moini** [comment]
@kaalleen Ah, okay, jetzt hab' ich das verstanden. Das wäre dann @bianchifan - und bitte Bescheidgeben, nach Anpassung des Speakerprofils, damit ich die Seite neu generieren kann.

**Comment by kaalleen** [comment]
Ah, ist vielleicht auch nicht ganz so wichtig. Ist mir nur aufgefallen, da es ja eine Veranstaltung auf Deutsch ist.

**Comment by bianchifan** [comment]
> Das wäre dann @bianchifan -
???
Das kryptisch PW habe ich schon längst vergessen...

> @bianchifan du kannst mich unter [kaalleen@inkstitch.org](mailto:kaalleen@inkstitch.org) kontaktieren wenn du magst.
Tut mir leid, dass ich erst so spät reagiere, ich habe hier schn länger nicht mehr rein geschaut und meine der 1&1 mail check funktioniert nicht mehr, genauso wie diverse weitere Browser Erweiterungen.

Deine email habe ich noch, ich melde mich entweder heute abend später oder morgen vormittag.

**Comment by Moini** [comment]
> Das kryptisch PW habe ich schon längst vergessen...

Kein Problem, dann lässt Du es Dir eben nochmal zuschicken:

![image](https://github.com/inkstitch/inkstitch/assets/3240233/dfec626d-7e52-4678-8dda-b3491390a047)

**Comment by bianchifan** [comment]
@Moini 
War nicht wirklich ernst gemeint, die PW mail sollte noch gespeichert sein und ein neues anzufordern sollte ich auch noch schaffen.

**Comment by Moini** [comment]
@kaalleen Hab grad Euren Artikel dazu gesehen. Sehr schön :)

Kleiner Korrektur-Hinweis: Der Workshop dauert von 15 bis 17 Uhr (bzw. 16:50 solltet Ihr Schluss machen).

Und könnte mir noch jemand eine Standbeschreibung anliefern, bis 600 Zeichen?

**Comment by kaalleen** [comment]
Oh hups, keine Ahnung wie ich auf 16:30 Uhr gekommen bin. Habe ich korrigiert. Danke für die Anmerkung :)

Den Rest müssten die anderen Beiden machen. Da stecke ich ja nicht mit drin.

**Comment by Tina-Chris** [comment]
So. Ich hab endlich meinen CV fertig. Nu hab ich Zeit für die Planung.  @bianchifan magst du mir  als Nachicht im git oder so deine Telefonnummer schreiben? Dann können wir mal Videochatten?
LG
Tina

**Comment by Tina-Chris** [comment]
> @kaalleen Hab grad Euren Artikel dazu gesehen. Sehr schön :)
> 
> Kleiner Korrektur-Hinweis: Der Workshop dauert von 15 bis 17 Uhr (bzw. 16:50 solltet Ihr Schluss machen).
> 
> Und könnte mir noch jemand eine Standbeschreibung anliefern, bis 600 Zeichen?

Hier? Per Email? Irgendwie bin ich durcheinander wer wer ist und so.
LG
Tina

**Comment by Moini** [comment]
@Tina-Chris Ist mir eigentlich egal, wie - Du hast sowohl meine Mail, als auch meinen Tag hier. Beides funktioniert :)

 LG Maren

**Comment by bianchifan** [comment]
> @bianchifan magst du mir als Nachicht im git oder so deine Telefonnummer schreiben?

Schlecht...  :(
Ich hatte die letzten Wochen Probleme mit der Batterie und beim Wechsel heute ist hat sich ein Defekt eingeschlichen..es lädt nicht mehr.
Also nur noch für den absoluten Notfall zu  gebrauchen.
Beim Reservephone noch schlimmer..obwohl aus geschaltet war die Batt recht aufgebläht und hat den Rückdeckel abgesprengt, allerdings ließ es sich noch bedienen.
Nach dem eigentlich erfolgreichen Battwechsel lässt es sich nicht mehr einschalten.. also kein Phone für die nächsten Tage.

Die Zugbuchungen waren ebenfalls ein Desaster, ich kann nur hoffen, dass die Züge fahren und ich den Stand finde

**Comment by Moini** [comment]
@bianchifan Nur zur Info: ich habe Deinen Account auf der Kielux-Webseite deaktivieren müssen, da jemand in Deinem Namen dort vandaliert hat. Kontrolliere bitte, ob Du der einzige bist, der Zugriff auf Deine E-Mails hat.

**Comment by Moini** [comment]
Vielen Dank Euch beiden, @bianchifan und @Tina-Chris , dass Ihr auf der Kielux wart! Es war toll, zu sehen, was Ihr mit Ink/Stitch alles anstellt! Vielleicht sehen wir uns ja nächstes Jahr wieder!

**Comment by bianchifan** [comment]
Bei den Mails ist mir bislang noch nichts aufgefallen, allerdings habe ich in den letzten 4Wo Chengdu. In. 10 Benachrichtigungen über fehlges hlagene Login versuche erhLten.. LG MarkusDiese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.09.23, 23:04 schrieb Moini ***@***.***>:

   
  @bianchifan Nur zur Info: ich habe Deinen Account auf der Kielux-Webseite deaktivieren müssen, da jemand in Deinem Namen dort vandaliert hat. Kontrolliere bitte, ob Du der einzige bist, der Zugriff auf Deine E-Mails hat.
