### ISSUE TITLE
Website source? 

### ISSUE THREAD

**Issue by atrus6** [inkstitch/inkstitch#240]
There's a few misspellings/grammar wonkyness on the website, and it would be nice to just do a pr for a bunch of them. If not, I can make a list here!

**Comment by wwderw** [comment]
Change master branch to gh-pages and do a PR there.

**Comment by X3msnake** [comment]
Sure do a PR

me, @kaalleen @lexelby or @wwderw can review and approve it.

Thanks for your interest and investment in helping

**Comment by lexelby** [comment]
Welcome to the project, and thank you for contributing!

**Comment by lexelby** [comment]
Closing since we have an answer, but if you have any trouble, please let us know!
