### ISSUE TITLE
Recommended DST File Reader

### ISSUE THREAD

**Issue by landguth** [inkstitch/inkstitch#2401]
I want a reader which displays the commands and data in a embroidery machine *.dst file. NOT a reader which displays the graphic which the commands and data will produce. Thank you.

**Comment by kaalleen** [comment]
Have a look over here https://github.com/inkstitch/inkstitch/discussions/2146

**Comment by landguth** [comment]
Got it! Thanks.
    On Saturday, July 1, 2023 at 10:59:37 PM PDT, Kaalleen ***@***.***> wrote:  
 
 


Have a look over here #2146
