### ISSUE TITLE
Rungs for a converted line to satin

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2407]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/d4617b2c-1556-45db-aa37-82b5fdac1f65)
 I created a line and set a width then converted the line to a satin
since there are too many nodes on the rails i did a simplify path
then it gives me on most of the rungs also a handle  see attached image and if i want to manipulate them i get these curved lines as rungs 
i was wondering if something can be done about that i know i can select each rung and convert the segment to a line but that is annoying and time consuming

windows 10 inkscape 122 inkstitch 3

Thanks 
Gus Visser

**Comment by lexelby** [comment]
One thing to consider: Ink/Stitch can handle curved rungs just fine.  It will only care about where they intersect with the rails.

**Comment by bianchifan** [comment]
> Ink/Stitch can handle curved rungs just fine.

**!!!**
@gusvisser If you do not like them.. kill them and draw some new by hand ;)

**Comment by kaalleen** [comment]
Closing. There isn't much we can do about it and it doesn't hurt Ink/Stitch functionality.
