### ISSUE TITLE
Spec For DST File Coding

### ISSUE THREAD

**Issue by landguth** [inkstitch/inkstitch#2408]
Is there a spec available which details DST file coding?

**Comment by bianchifan** [comment]
[Embroidery format DST](https://edutechwiki.unige.ch/en/Embroidery_format_DST) doku of edutech wiki

All other dokus I knew are gone, maybe you can find something  in the webarchive ;)

**Comment by landguth** [comment]
This document is very detailed and complete. Well written. Thank you.
    On Monday, July 3, 2023 at 05:56:14 AM PDT, bianchifan ***@***.***> wrote:  
 
 


Embroidery format DST doku of edutech wiki

All other dokus I knew are gone, maybe you can find something in the webarchive ;)

**Comment by landguth** [comment]
I have viewing of Snap Control Bar turned on, but I do not see it. I have 2023 version. I don't know what is wrong. Help. Thank you.  Mark

**Comment by kaalleen** [comment]
In Inkscape 1.2 it is just a little icon on the right top corner with an arrow to expand options.
A lot of people were not happy with it so in 1.3 you'll be able to set it to "permanent" again in the preferences.

**Comment by landguth** [comment]
Got it. Thank you.
    On Sunday, July 9, 2023 at 02:47:10 AM PDT, Kaalleen ***@***.***> wrote:  
 
 


In Inkscape 1.2 it is just a little icon on the right top corner with an arrow to expand options.
A lot of people were not happy with it so in 1.3 you'll be able to set it to "permanent" again in the preferences.
