### ISSUE TITLE
impossible d'installer inkstitch

### ISSUE THREAD

**Issue by milkarion** [inkstitch/inkstitch#2412]
bonsoir! mon antivirus me signale que le fichier est infecte par "filerepmalaware"!
impossible de poursuivre son installation, j'ai installé une ancienne version trouvée sur un blog... 
avez vous une solution? Merci!

**Comment by kaalleen** [comment]
Most antivirus software have the option to whitelist specific files or folders. Which software do you use?

**Comment by kaalleen** [comment]
Closing. Please send more information if you are still having trouble with the installation.
