### ISSUE TITLE
The Params -> Preview doesn't match Visualize and Export -> Simulator

### ISSUE THREAD

**Issue by mapsedge** [inkstitch/inkstitch#2421]
The preview under the params menu looks great, and performs exactly how I'd expect it to. Visualize and Export does not, however. Even after re-applying the parms, closing Inkscape, re-opening Inkscape, the simulator does a section of the embroidery incorrectly. Which one do I trust: preview or simulator? I haven't tried embroidering it yet because I'm having a friend do it and I don't want to waste her time.

**Comment by bkmgit** [comment]
Thanks for reporting this. Can you share the file and screenshots?  What versions of Inkscape and Ink/Stitch are you using, and on wht operating system?

**Comment by tyrosinase** [comment]
On Mon, Jul 10, 2023, at 12:13 AM, Bill wrote:
> Which one do I trust: preview or simulator?
> 
Leaving the larger issue to someone else to answer, but: if you create the stitch file and open it back into Inkscape, you can see exactly how it's going to stitch out (modulo any differences in how your machine handles trims).

**Comment by mapsedge** [comment]
...and of course, now that I want it to happen, it won't, even after making changes I felt sure would mess something up.

If it ever happens again, I'll be here right away with the relevant info and screenshots.

**Comment by mapsedge** [comment]
> open it back into Inkscape, you can see exactly how it's going to stitch out

Didn't even think of that. Appears to be fine. Thanks for that tip.

**Comment by kaalleen** [comment]
When you want to get an impression of the stitch out, use the normal simulator, not the params simulator. The params simulator is meant to preview changes on the stitch settings, but it will ignore running stitches when you also have satin columns selected and you will see more jump stitches than you actually have.
When you save to a stitch file, it is possible that the stitch positions will be slightly changed, depending on the file format you choose. So opening the stitch file will possibly be your best option as @tyrosinase said. But keep in mind, that embroidery isn't very exact. So when you stitch out the file, there will be pushing and pulling at the fabric. This is something you will have to keep in mind when you create an embroidery file. What you see on screen is never exactly what you get. So it is possible, that you see gaps in the stitch out, that weren't there in the preview and you'll need to adapt the file accordingly.

**Comment by kaalleen** [comment]
Closing the issue, since there is no development task to do. Please open a new issue, if you have further questions or if you see any error message while using Ink/Stitch.
