### ISSUE TITLE
`fill="currentColor"` with inline CSS breaks ThreadColor

### ISSUE THREAD

**Issue by Enva2712** [inkstitch/inkstitch#2423]
I have an SVG that's defined within a react component, and the code I wrote there uses `fill="currentColor"` and inline styles passed to the root svg node b/c it's useful when rendering in the web

When trying to export as a dst, ink/stitch gives the following traceback:
```
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/output.py", line 57, in effect
  File "lib/stitch_plan/stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 115, in new_color_block
  File "lib/stitch_plan/color_block.py", line 16, in __init__
  File "lib/stitch_plan/color_block.py", line 51, in color
  File "lib/threads/color.py", line 36, in __init__
  File "lib/threads/color.py", line 36, in <genexpr>
TypeError: can't multiply sequence by non-int of type 'float'
```

tinycss2 [returns "currentColor" in this case](https://doc.courtbouillon.org/tinycss2/stable/api_reference.html#color) which causes [this line](https://github.com/inkstitch/inkstitch/blob/main/lib/threads/color.py#L36) to throw

A quick fix would be to make `currentColor` fallback to black (which wouldn't have effected my use case b/c afaik dst contains no color metadata), and a more complete solution would resolve the css cascade.

For reference, here are the svgs I was using; one with `fill="currentColor"`, and the other which I inlined the color to make it work
![logo](https://github.com/inkstitch/inkstitch/assets/18131608/7ec7bbf4-e745-4518-a939-1d7977f22d53)
![logo-nocss](https://github.com/inkstitch/inkstitch/assets/18131608/06b5ec35-15ca-4399-8fe8-9e94b1cffbbb)

**Comment by bianchifan** [comment]
I remember a liitle weakly deep in my brain that I once stumbled into the same problem.. IIRC I tried to to start the visualizer on a SVG found on the web but nothing happened...
InkStitch cannot render EVERY SVG that is possible to design, it can only render SVGs specially designed for stitching out/being embroidered!
Every pic you like to vectorize and every graphic you may find must be simplified into a structure possible to sew. 
Am embroidery machine is a CNC but the heart is a sewing machine.
The design should be made with INKSCAPE, the basis of InkStitch.
I never saw the attribute "currentColor" in an SVG created with Inkscape although Inkscape can handle it.

As you stated above, the DST format has no color information, only numbers.
And if it will have one like PES no embroidery machine can check if i.e. "Brother No 437" is feeded or noname darkbrown.

So... what's your problem? ;)

**Comment by kaalleen** [comment]
Nice catch, thanks!

currentColor is a valid css property that should be handled correctly. Anyway, I think until inkex is capable to resolve the css inheritance of currentColor, we should just render with a black color instead (use the easy fix) ... and get rid of tinycss2.

**Comment by Enva2712** [comment]
@kaalleen I thought inkex did implement cascade: https://inkscape.gitlab.io/extensions/documentation/_modules/inkex/styles.html#Style.cascaded_style

**Comment by kaalleen** [comment]
Actually we are using the specified_style which is using cascaded_style. Unfortunately this doesn't solve the issue. The currentColor property isn't well implemented into inkex yet. I'd like to be proven wrong though, if you see a way to make it work...
