### ISSUE TITLE
Fail to execute script

### ISSUE THREAD

**Issue by penanot** [inkstitch/inkstitch#2430]
Hi, does anybody have a solutions for this matter?

  File "inkstitch.py", line 62, in <module>
    extension_class_name = extension_name.title().replace("_", "")
AttributeError: 'NoneType' object has no attribute 'title'

i'm running on Windows 10.

Thank you.

**Comment by lexelby** [comment]
How are you launching Ink/Stitch?

**Comment by kaalleen** [comment]
Closing (no response). Please open a new issue if you are still having problems.

**Comment by Pragmateek** [comment]
Hello,

Same issue there with a fresh installation on Windows 11.
I'm running Ink/Stitch from command line (starting with a basic sample copy/pasted from https://inkstitch.org/docs/command-line/):
```
D:\Users\pragmateek\AppData\Roaming\inkscape\extensions\inkstitch\inkstitch\bin\inkstitch.exe  --extension=zip --format-dst=True --format-pes=True --format-threadlist=True Smiley.svg > output-file.zip
```
```
Traceback (most recent call last):
  File "inkstitch.py", line 163, in <module>
  File "lib\utils\io.py", line 14, in save_stderr
AttributeError: 'NoneType' object has no attribute 'fileno'
```

<img width="402" height="332" alt="Image" src="https://github.com/user-attachments/assets/53a228c0-f02a-41c8-bf57-ed199245c93a" />

**Comment by kaalleen** [comment]
The problem is reproducible in windows while things work fine with linux.
It's not the same issue as the one mentioned above. Can you open a new issue for this?
