### ISSUE TITLE
auto route start

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2435]
![auto run start](https://github.com/inkstitch/inkstitch/assets/85417086/a77d6e83-7129-469d-bb25-1e0d39c093c4)
as i was doing a project and was working with the start and stop command for the autoroute the stop command attaches to the object but the start command shows up in open space not attached to the object 

have to go in node select to grab the end node and drag it into right position on the object

is this an error or the way it is supposed to be 

running windows 10 inkscape 1.2.2 inkstitch 3.01

Thanks
Gus Visser

**Comment by kaalleen** [comment]
This is annoying, isn't it. Connectors do not work well on strokes.
You can drag the command as a whole, it will still work and start/end at the closest point to the end of the connector.

**Comment by kaalleen** [comment]
Closing, as there is nothing we can do about it.
~Maybe~ It will work better when Inkscape will update the connector tool.
