### ISSUE TITLE
broken link in autoroute_sashiko tutoral page

### ISSUE THREAD

**Issue by FractalLotus** [inkstitch/inkstitch#2439]
the link at the bottom ("You may wish to also try with this extension") does not work. 

Firefox reports "An error occurred during a connection to tesselace.com. SSL received a record that exceeded the maximum permissible length."

**Comment by bkmgit** [comment]
The domain seems not to have been renewed.  Project is available at https://d-bl.github.io/inkscape-bobbinlace/

**Comment by bkmgit** [comment]
Thanks for reporting this. Files seem to be similar to what is at https://web.archive.org/web/20210727161030/https://tesselace.com/tools/inkscape-extension/
