### ISSUE TITLE
Is there way to slow down embroidery machine via code?

### ISSUE THREAD

**Issue by kzuahelp** [inkstitch/inkstitch#2442]
Hello, I have old bernette 340 embroidery machine and I have quality problems with embroiding thin satin columns on high speed. I set slowest (~400stiches/minute) mode in machine settings, but I wat to make it slower in the hardest parts of embroidery. Like when you clicking start button. Can I make it by software or only way is hardware pwm hack?

**Comment by kaalleen** [comment]
To my knowledge there is no way to do it through the stitch file.
Somewhere here in the issue you may find a way for barudan machines though.
How thin are your satin columns?

**Comment by kzuahelp** [comment]
>  How thin are your satin columns?

3mm

**Comment by kaalleen** [comment]
3mm should be good. Wondering what makes it hard for your machine to stitch it out.
Maybe stitch density or thread tension?
