### ISSUE TITLE
Error 4053 - error loading

### ISSUE THREAD

**Issue by linalou1800** [inkstitch/inkstitch#2444]
"Inkscape has received additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected"

Message when trying to do anything with inkstitch..

**Comment by bkmgit** [comment]
Thanks for reporting this.  What version of Inkscape and Ink/Stitch are you using and on what operating system?

**Comment by kaalleen** [comment]
No further response. Closing.
Please open a new issue if you are still having trouble to run Ink/Stitch and add requested information (Ink/Stitch version / operating system).
