### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bkmgit** [inkstitch/inkstitch#2445]
Add a set of tests to ensure correct functionality.  For GUI testing, options include:
- [dotool](https://git.sr.ht/~geb/dotool)
- [ydotool](https://github.com/ReimuNotMoe/ydotool) 
- [xdotool](https://github.com/jordansissel/xdotool)

**Comment by kaalleen** [comment]
We started to use the inkex tester module.
I think that will be ok then? I'll close the issue. Please complain if I got this totally wrong.
