### ISSUE TITLE
Missing Commands

### ISSUE THREAD

**Issue by Obot11223** [inkstitch/inkstitch#2450]
I seem to be missing commands such as the one I'm trying to use right now: Edit, Re-stack objects in order of selection.

**Comment by kaalleen** [comment]
Huh, not sure what is happening there. Which operating system do you use and which version of Ink/Stitch?
Did you have previously an other version installed?

**Comment by Obot11223** [comment]
I found the problem, thank you. It seemed to need an update to 3.0.1. Was confused because the videos I was watching how to do things were from a year ago, which I thought I had updated within then, but guess not.

And to answer the question anyway, I'm on windows 10.
