### ISSUE TITLE
params

### ISSUE THREAD

**Issue by Snaxxwax** [inkstitch/inkstitch#2451]
traps: inkstitch[65224] trap int3 ip:7fde07f28295 sp:7fff27036f30 error:0 in libglib-2.0.so.0[7fde07eec000+85000]

I have never been able to open params in the inkstitch extension. This is the error that I get in the logs in ubuntu. I was told this is a segmentation fault, how do I fix this?

**Comment by kaalleen** [comment]
Can you specify which version of ubuntu you are running on?

**Comment by Snaxxwax** [comment]
Inkscape 1.3 (1:1.3+202307231459+0e150ed6c4)
Inkstitch 3.0.1
GLib version:     2.72.4
GTK version:      3.24.33
 glibmm version:   2.66.2
 gtkmm version:    3.24.5
  libxml2 version:  2.9.13
  libxslt version:  1.1.34
  Cairo version:    1.16.0
  Pango version:    1.50.6
  HarfBuzz version: 2.7.4
OS version:       Ubuntu 22.04.2 LTS

**Comment by kaalleen** [comment]
Can you test if it works when you open Inkscape with this command: `export GDK_BACKEND=x11 && inkscape` ?

**Comment by darkbeanbbq** [comment]
I've been having this issue for a while now and this command worked for me.
How can I use Ink/Stitch without having to type this to launch Inkscape every time ?

**Comment by Snaxxwax** [comment]
It works when I launch the app with that command.

**Comment by kaalleen** [comment]
>  How can I use Ink/Stitch without having to type this to launch Inkscape every time ?


Write it into a file and make it executable. Then you can simply click on it to run inkscape.

```
#! /bin/sh
export GDK_BACKEND=x11 && inkscape
```
