### ISSUE TITLE
MacOS error message

### ISSUE THREAD

**Issue by scary0408** [inkstitch/inkstitch#2454]
I keep trying to run the ink/stitch command after following tutorials but am getting an "Inkscape has received additional data..." black box pop up error. Would really like to troubleshoot.

**Comment by kaalleen** [comment]
Can you post the entire error message?
Can you verify if you downloaded the correct Ink/Stitch version for your macOS system?

**Comment by kaalleen** [comment]
No response. Closing. Please open a new issue if you are still having trouble.
