### ISSUE TITLE
stitch order in font out of order on stitchout

### ISSUE THREAD

**Issue by safire3002** [inkstitch/inkstitch#2455]
so i'm nearly done with my font, except for one issue: sometimes, my running stitch will suddenly go over my satin stitch instead of underneath. i've triple checked at this point, and it's not the order i have my satin layers in. the live preview shows up fine and the layer order is fine, however sometimes it will just happen that my running stitch goes over. it's very strange. 

is it my machine interpretation of the .pes file? i have a babylock ellure plus.

pictured below: if you take a look at the two p's, one stitches out in the wrong order and one stitches out in the right order. same p from the lettering dialog box. ignore my e on top, that just birdnested and i had to cut it out. i'll attach my font as well. thanks for the help!

![IMG_0849](https://github.com/inkstitch/inkstitch/assets/134817062/48016cfc-ef05-4f89-a4a8-92a3905b9892)
![IMG_0850](https://github.com/inkstitch/inkstitch/assets/134817062/d545550d-2ea5-4675-b0de-9d42f1ad94bd)
[Instrument Serif.zip](https://github.com/inkstitch/inkstitch/files/12210408/Instrument.Serif.zip)

**Comment by claudinepeyrat06** [comment]
Are you sure you want to have autosatin set to true in the json file ? it seems that you have already manually applied autosatin to each glyph  and have alreaded created all the runnng stitch underpaths , so you don't need autoroute to be called one more time. I suspect that if you modify the json file and set autosatin to false, you would get rid of this problem.

**Comment by safire3002** [comment]
Thank you so much @claudinepeyrat06 ! That fixed it. When I get time, I'll upload this new font to the library for everyone.
