### ISSUE TITLE
How to calculate the number of meters of embroidery thread?

### ISSUE THREAD

**Issue by telileovietnam** [inkstitch/inkstitch#2457]
Hello. How to calculate the number of meters consumed by each object or layer?. Thank you.

**Comment by kaalleen** [comment]
The print pdf output can display the estimated usage of thread. This value is not very accurate and depends on various parameters (stitch type, stitch length, etc.). Ink/Stitch simply calculates the path length and multiplies it with a customizable value (customizable in the settings of the pdf export).
