### ISSUE TITLE
Auto-reversed rails have strange side effects on rung-less satins

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2460]
I'm on the (a?) remove-stringcase-dependency release, FWIW.

![Bloops](https://github.com/inkstitch/inkstitch/assets/9473609/63e2f7d7-832e-4ba3-9a40-1e72af291fc6)

![image](https://github.com/inkstitch/inkstitch/assets/9473609/1cff1c9e-ead9-4eec-af12-121539860c1b)

![image](https://github.com/inkstitch/inkstitch/assets/9473609/b9da6279-867a-4c4b-814f-17d56fea7388)

Opened Params and noticed the tracking was a little off on this, and realized I had an odd number of nodes in one curve. (About which it hadn't warned me, interestingly.) Fixed that, and it improved the tracking but not completely. Properly reversing the rail fixes it.

**Comment by lexelby** [comment]
Oops!  Nice catch, thanks.  Fix coming shortly.
