### ISSUE TITLE
v 3.03 IndexError: tuple index out of range

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2463]
Edit: Pardon, typing error in title :((

When I tried to add some text to my "kielux disk" InkStitch's troubleshooter pointed out a bug message.
The lazy object is the needle frm the Logo, downsized and turned left about 90 degrees.
The weird thing:
Parameter's simulation works fine, but with CRTL Shift "L"  nothing happens, 01% CPU instead of 100%.
Same with a try to save a stitch file.

The NonSimulated design
![Bildschirmfoto vom 2023-08-04 14-53-15](https://github.com/inkstitch/inkstitch/assets/17491743/c4517695-a865-4bcc-973e-d3d804260279)

The isolated object in a seperate svg
![InkStitch Needle](https://github.com/inkstitch/inkstitch/assets/17491743/f9948b74-4aee-4fae-981c-b7d895d71137)

Param's result
![Bildschirmfoto vom 2023-08-04 14-41-30](https://github.com/inkstitch/inkstitch/assets/17491743/318cf7fc-7987-45e9-b3f9-44a1012eafca)

Sim's result
![Bildschirmfoto vom 2023-08-04 14-50-26](https://github.com/inkstitch/inkstitch/assets/17491743/b4f555c8-2c02-45ad-bac0-5ba455088976)

**Comment by kaalleen** [comment]
Does it work when you turn the running stitch back to a running stitch?

I'm not sure if I'd use two satins for the needle eye in that size. It would need testing, but maybe it could be indicated with a running stitch on top of a complete satin or you could use a pattern to place extra stitches.

I can't reproduce the error with the current main. So this is possibly fixed.

**Comment by bianchifan** [comment]
> Does it work when you turn the running stitch back to a running stitch?

Uiuiui.. I didn't checked the params after downsizing the paths, all running stitch infos gone lost...maybe it happens at copy time from one svg to another.
