### ISSUE TITLE
Paramétrage d'une forme avec fond et contour

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2465]
Sur le motif ci-dessous le path7 a un fond et un contour, je n'ai pas paramétré le contour, le menu Paramètres affiche correctement le résultat que je veux obtenir, par contre le dépistage d'erreurs m'indique une erreur, mais ne peut pas analyser la cause et afficher un message précis.

La sauvegarde au format de broderie est refusée. Si je supprime le contour du chemin 7 tout se passe correctement. 

Dépistage des problèmes sur tout le motif :
Ink/Stitch Version: 3.0.1 (osx)
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/satin_column.py", line 652, in validation_errors
  File "lib/elements/satin_column.py", line 1262, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1090, in do_satin
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

Enregistrement au format JEF :
Erreur sur  path7: Colonne satin: L'objet a trop peu de sous-chemins. Une colonne satin doit avoir au moins deux sous-chemins (les rails).

Merci d'exécuter Extensions > Ink/Stitch > Résolution de problèmes > Dépistage de problèmes avec des objets. Ceci indiquera la position erronée.

![fleurette](https://github.com/inkstitch/inkstitch/assets/65076100/1a3021a8-3708-451e-b031-657d63a95aa0)

**Comment by bianchifan** [comment]
Yesterday I had the same error in another situation..
Path7 is defined with both, fill color AND stroke color, for whatever reason inkstich changed the stroke into a half SATIN!
![Bildschirmfoto vom 2023-08-06 20-01-42](https://github.com/inkstitch/inkstitch/assets/17491743/7208848c-82fd-4ea8-9ccc-7d89b225e918)

You should edit your SVG with a n XML Editor, delete the entry inkstitch:satin_column or change the value to "False"

**Comment by Marif91** [comment]
> Yesterday I had the same error in another situation.. Path7 is defined with both, fill color AND stroke color, for whatever reason inkstich changed the stroke into a half SATIN! ![Bildschirmfoto vom 2023-08-06 20-01-42](https://user-images.githubusercontent.com/17491743/258659377-7208848c-82fd-4ea8-9ccc-7d89b225e918.jpg)
> 
> You should edit your SVG with a n XML Editor, delete the entry inkstitch:satin_column or change the value to "False"
> 
> EDIT: ![258654305-1a3021a8-3708-451e-b031-657d63a95aa0](https://user-images.githubusercontent.com/17491743/258659877-fe4642fa-48d8-462c-8d6a-6392c92dc981.svg) ![Bildschirmfoto vom 2023-08-06 20-21-22](https://user-images.githubusercontent.com/17491743/258659889-7dd5b985-fc7a-41f1-8a7a-d347be34eeeb.jpg)
> 
> Edit 2: For the yellow satin.. Do you you the "random" option?

Merci Bianchifran, il a été difficile de trouver l'erreur car ce motif fait partie d'un ensemble, je pense que inkstitch ne devrait pas accepter l'absence de paramétrage d'un chemin. 
Oui, j'ai les options "random" du satin, je les ai utilisées pour les pétales rouges.

**Comment by kaalleen** [comment]
This is really an annoying error. Happens most of the time, when a satin param is applied when simples strokes and satins are selected at the same time. We will see this being posted a lot until the next release. In development branches this shouldn't be a problem anymore. Therefore I'm going to close the issue. Please open a new issue, if this is seen in newer development releases.
