### ISSUE TITLE
Easy way to make an outline of a font file?

### ISSUE THREAD

**Issue by cvick32** [inkstitch/inkstitch#2466]
I'm trying to get just the outline of the "C" shown below:
<img width="89" alt="Screen Shot 2023-08-06 at 12 53 19 PM" src="https://github.com/inkstitch/inkstitch/assets/21297625/84edbb97-0536-463a-9dbf-26617035cd42">

I can't just get the stroke because the stroke follows the stitch the entire way around while I just want the outline of the whole object. Is there an automatic way to get the outline? Or will I have to manually trace around the font?

Ideally I would want something like this: 
<img width="105" alt="Screen Shot 2023-08-06 at 12 58 15 PM" src="https://github.com/inkstitch/inkstitch/assets/21297625/a23b1c36-c96f-4656-9c81-618fcf9ba596">

This is what I was able to do very quickly manually, but obviously I'm hoping for a little better :). 

Thanks for your help.

**Comment by lexelby** [comment]
How about you run Stitch Plan Preview, then increase the stroke width until it overlaps with itself, and finally do Stroke to Path?  I think that might mostly do what you want.

Alternatively, many of our fonts are based on a normal TTF font and you did find that font and use it.  Look in the font's directory in this repo and check its README file.

**Comment by tyrosinase** [comment]
You can do the same steps it would take to get a dieline or knockdown shape: https://silverseams.com/2020/09/knockdown-stitching.html but you'll end up with a slightly larger shape... doing an inset on it will shrink it back down, but you'll still end up with some distortion or bumpiness to clean up.

**Comment by cvick32** [comment]
Thank you both for your suggestions. The issue with both is that I'm really looking for a single path that defines the outline of the letter. 

I'm trying to engrave an embroidery font with this outline, that's why I need to have single outline. Otherwise, the engraver tries to run every stitch and things end up on fire.

**Comment by tyrosinase** [comment]
The knockdown stitch will give you that (obviously, don't do the hatching fill with the shape though).
