### ISSUE TITLE
v 3.01: Problems with circular Fillstich

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2469]
3rd try, the first  two from last WE  -> Nirwana :(

Circular Fillstitch work pretty fine on lots of geometrical objects but circles..
Nice results on triangles, rectangles. multiangles, poly whatever.., even with parts of a circle.

The more the shape of the object being filled equals to the shape of a circles, the less gets the density in the center, a full  circle shows a pretty hole.

For I like to choose the circ. fill for my "kielux Disk", I take y examples from there.

1. Multiangles with part of a circle

![Kielux 02](https://github.com/inkstitch/inkstitch/assets/17491743/007836b4-0d55-4e44-a200-fe75c3b8bbd8)

Result is pretty fine, same with circle parts less than a half cirle.

2.
![Kielux 05](https://github.com/inkstitch/inkstitch/assets/17491743/b6792ee2-cace-4cc3-9ef6-f363372b4452)

When the part of a circle shapes more than a half, the hole starts to grow, in this case the break is nearby the waterline.

3.
![Kielux 07](https://github.com/inkstitch/inkstitch/assets/17491743/ba218b3d-562e-4356-bf31-c7a8096f8e50)

And a really big hole with a full circle :((, my beloved favorite for the "kielux" project

**Comment by kaalleen** [comment]
Cannot reproduce with the file you've send in the other issue.
Can you send a file with the sky when has the hole at the center?

**Comment by bianchifan** [comment]
I posted it in the "kielux" issue..

Here's the actual version, just hit CRTL-SFT-L
![21_Kielux_neu](https://github.com/inkstitch/inkstitch/assets/17491743/69ba4b0c-25c5-4e12-9654-9500bd03f3f1)
