### ISSUE TITLE
Sewing order of fill and stroke wrong in Params simulator

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2473]
Normally i always create my outline and fill as seperate objects
I was asked to have a look at a file from someone else and here the fill and stroke were applied to same object in same color then if you open up params the params window shows that line gets sewn first and then the fill and when i open the object in the simulator it sews the fill first and then the outline

So i was wondering if the params window could show the proper sewout order because of the applying of the lockstitches if we see the line sew first we would apply lock stitch at start of line  and lock stitch at end of fill but these lock stitches should be applied in opposite order

Thanks
Gus Visser

**Comment by lexelby** [comment]
That's a bug!  I've labeled this issue accordingly.  Thanks!
