### ISSUE TITLE
Zaysy

### ISSUE THREAD

**Issue by zaysy** [inkstitch/inkstitch#2477]
Failed on  path1524: Error during autofill! This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 720, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 817, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 519, in single_spiral
  File "lib\stitches\contour_fill.py", line 531, in _spiral_fill
  File "lib\stitches\contour_fill.py", line 581, in _make_spiral
UnboundLocalError: local variable 'spiral_part' referenced before assignment

shapely.geos - INFO - Self-intersection at or near point 777.83830557177623 790.24361261761044
shapely.geos - INFO - Self-intersection at or near point 777.83830557177623 790.24361261761044
shapely.geos - INFO - Self-intersection at or near point 425.53412363747623 670.37805820052631
shapely.geos - INFO - Self-intersection at or near point 425.53412363747623 670.37805820052631
shapely.geos - INFO - Self-intersection at or near point 1238.3735431815151 215.44404248273298
shapely.geos - INFO - Self-intersection at or near point 1238.3735431815151 215.44404248273298
shapely.geos - INFO - Self-intersection at or near point 1128.7422795669077 454.50057592750738
shapely.geos - INFO - Self-intersection at or near point 1128.7422795669077 454.50057592750738
shapely.geos - INFO - Self-intersection at or near point 1141.5939758438135 356.76457555331552
shapely.geos - INFO - Self-intersection at or near point 1141.5939758438135 356.76457555331552
shapely.geos - INFO - Self-intersection at or near point 593.53564397416812 394.30967807480619
shapely.geos - INFO - Self-intersection at or near point 593.53564397416812 394.30967807480619
shapely.geos - INFO - Self-intersection at or near point 655.07626926873377 400.58097889056421
shapely.geos - INFO - Self-intersection at or near point 655.07626926873377 [400.58097889056421
![123](https://github.com/inkstitch/inkstitch/assets/53167022/565ebdcb-148b-441c-b17f-13ff26ec3516)

**Comment by gusvisser** [comment]
You would need to clean up your errors first after that it wil most likely work

Gus Visser

**Comment by kaalleen** [comment]
The error has already been fixed in the development branches and shouldn't show up in the next release.

But Gus is right, the design would need more work to the suitable for embroidery and not every shape will stitch out nicely as a fill / contour fill,
