### ISSUE TITLE
Contour fill still doesn't work on OSX

### ISSUE THREAD

**Issue by zourid** [inkstitch/inkstitch#2478]
When testing "development build of claudine/update_tt_masters_font" contour fill doesn't work at all. 
The other options seem to work fine. I used a simple square for testing. Thanks for the great extension.

**Comment by lexelby** [comment]
Strange, that branch doesn't touch the contour fill code... You're sure only that branch has the problem?

**Comment by zourid** [comment]
I tried to reproduce the error and reinstalled the official release InkStitch 3.0.1 for Monterey ( I am using an older 12-core Mac Pro running Monterey v12.6.8)

![image](https://github.com/inkstitch/inkstitch/assets/142331941/0f6bce4d-8c2c-4ab1-b60b-c3a64c14b724)

Contour Fill did not work on the official version either for me — all other fill methods worked fine.

But when I installed InkStitch 3.0.1 for High Sierra /.../ Big Sur everything worked fine including Contour fill.

![image](https://github.com/inkstitch/inkstitch/assets/142331941/88462f45-fb17-489a-aeb5-36f9f89579a8)

I guess the pre-release was probably compiled for Intel Macs (there is only one .pkg file).

I hope this helps.

**Comment by kaalleen** [comment]
What exactly do you mean with doesn't work?
Did you receive any error messages for the contour fill?

**Comment by zourid** [comment]
First, THANK you very much for this amazing extension.

So, for all other fill methods, it takes just a few seconds to fill in this simple square when I switch from one method to another (e.g., from Auto to Circular). But for Contour Fill, nothing happens, the preview does not change at all, even if I wait for minutes. No feedback, no error messages, nothing;  just no change from the previous preview screen.

This happens when I use the official 3.0.1 release for Intel-based Monterey or the pre-release I mentioned above (I guess it was compiled for Intel Macs?).

But when I use the 3.0.1 release for Big Sur (on my Intel/Monterey Mac) everything works just fine, including Contour Fill, in a matter of seconds. 

I hope I am not forgetting any steps before I call params; all I do is create a square and call params. 

If there is a way to look for a crash report (in case there is one) I will be happy to.

**Comment by zourid** [comment]
All recent releases have the same issue on OSX even on an M1 machine: Contour Fill does not work

Here is a square with Auto fill


![image](https://github.com/inkstitch/inkstitch/assets/142331941/35af1da3-6f6c-4021-a4d1-6329a52dd184)

same square with circle fill

![image](https://github.com/inkstitch/inkstitch/assets/142331941/b4d85fb3-706c-4787-9580-d6ef52f8584b)

and here is the same square with contour fill — nothing happens after waiting or restarting or starting the preview 

![image](https://github.com/inkstitch/inkstitch/assets/142331941/04c92cb8-7aad-437a-a9ec-8a3fd41279ae)

**Comment by zourid** [comment]
I am using a MacBook Pro with an M1 chip
![image](https://github.com/inkstitch/inkstitch/assets/142331941/7eb1f8a1-47d8-4a1f-892b-6e7a61b21f5a)

**Comment by zourid** [comment]
And here is the pre-release version of Ink/Stitch
![image](https://github.com/inkstitch/inkstitch/assets/142331941/239b7371-33e6-4663-8eed-213dd5e8280d)

**Comment by zourid** [comment]
I tried again all the latest pre-releases in the last two weeks by Kaalleen, Claudine, Lexelby, and Kall. 
When I do Ink/Stitch —> Params all fill methods work fine EXCEPT for Contour fill. All I get is a spinning wheel — no error messages, no crushes, just the spinning wheel.

I tried all four pre-releases  with a square object on two different Macs, an Intel-based Mac Pro and an M1-based MacBook Pro. 

The official release works just fine on these machines.

I will be happy to look for an error message but don't know where to look.
 
PS I like the new icons that the Kaalleen simulator features.

**Comment by kaalleen** [comment]
Could you apply settings with the contour fill (also when the preview isn't working) and run the stitch plan preview extension on that one? It may provide more information than params does.

Icons were introduced by Lex. Plans are to improve the params simulator even more.

**Comment by zourid** [comment]
I just tried again with the latest pre-release, and have a minor correction: after doing Params and choose Contour fill nothing happens, not even the spinning wheel. Nevertheless, I applied the settings and quit, as you suggested.

After running stitch plan preview I get the spinning wheel and Inscape hangs completely and had to force quit. I tried a couple of times. I am attaching the hang report if that helps (I had to zip it b/c '.hang' files can not be attached). 


[inkscape_2023-09-15-085958_COT-T205AMac.hang.zip](https://github.com/inkstitch/inkstitch/files/12620118/inkscape_2023-09-15-085958_COT-T205AMac.hang.zip)

**Comment by kaalleen** [comment]
Could you test the latest release (3.0.1)?

1. Test the build for Monterey
2. Test the release for older macOS systems

And report which one of these is able or not able to run contour fill?

**Comment by kaalleen** [comment]
> But when I use the 3.0.1 release for Big Sur (on my Intel/Monterey Mac) everything works just fine, including Contour Fill, in a matter of seconds.

Sorry, ok you already did... So the older releases work for you.

**Comment by zourid** [comment]
Thanks for following up. 

The problem started with the ** very first** pre-lease after official release v3.0.1

tiltled [development build of kall/test-notarization](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test-notarization)

 I tested it and this is where the code broke.

Unfortunately I do not know enough to check what changed between v3.0.1 and kall's build.

![Screenshot 2023-10-02 at 2 40 09 PM](https://github.com/inkstitch/inkstitch/assets/142331941/ee0b8483-5301-4a75-80f6-b310213d22bb)

**Comment by kaalleen** [comment]
Uh? In this case ... can you double check if 3.0.1 does work for you? The build for newer macOS systems?
I came to the believe that it doesn't work neither.
The notarization test branch is just a test branch and never gets merged into main. So this can't be relevant.
This is probably (we are not sure yet) a versioning problem in the combination of numpy, shapely and scipy and has nothing to do with our actual code. But we need to get the versions of our dependencies right.

**Comment by zourid** [comment]
Build 3.01. for older systems does not work on my old Mac Pro, but build 3.0.1 for new systems works on both the old Mac Pro (Intel-based) and the new Mac Book Pro (M1-based).

**Comment by kaalleen** [comment]
Would you mind test run this dev version here?
https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-shapely201

**Comment by zourid** [comment]
Hi Kaalleen
 
This version (dev-build-kaalleen-shapely201 <https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-shapely201>) runs great! Contour fill works fine again, and so does the Simulator/Realistic Preview.

Two minor issues:

— The param simulator lunches behind the main window (see screenshot)
— The text box with the number of stitches is not wide enough to accommodate the entire number (only the first 2 digits are visible).

Overall fewer crashes — often times after I close the param simulator and save my file Inkscape hangs and I have to force quit.

BTW, I tested the latest pre-release as well (development build of kall/test <https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test>) and has exactly the same minor issues.

Thank you for your hard work. I’ll be using this version of Ink/stitch from now on.

-gz

**Comment by kaalleen** [comment]
Thank you for your feedback. The simulator is in some sort of in between state. It is being worked on improving it further. It is still helpful to know what exact issues you encounter :)
Since the main issue from this thread is solved, I'll be closing the issue. You can of course always open new issues if you find new bugs.

**Comment by semireg** [comment]
I was able to use the [dev-build-kall-test](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test) version to work-around the broken contour simulation. Thanks!
