### ISSUE TITLE
Troubleshoot objects not working

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#2482]
![kilt5](https://github.com/inkstitch/inkstitch/assets/85417086/e36863a3-c944-48fe-9abe-b5959dbdc29b)
![troubleshoot](https://github.com/inkstitch/inkstitch/assets/85417086/84a2b6c7-2aab-4206-bc30-40d463196d50)

As i was having a look at a file from someone she got this error and then sent me the file and as i did a troubleshoot i got same error and no results on screen no matter which way i did a troubleshoot

windows 10 inkscape 1.3 inkstitch 3.01

Gus Visser

**Comment by kaalleen** [comment]
Thanks for the error report! As always we are very thankful for that.
I think this is already fixed in current development releases. Will check later.

**Comment by bianchifan** [comment]
It sucks with v.3.01 :(
but with lexelby's unelectron it works :)

![Bildschirmfoto vom 2023-08-19 23-41-58](https://github.com/inkstitch/inkstitch/assets/17491743/078817a6-8f45-477c-bca6-0c7c2196b81d)

![Bildschirmfoto vom 2023-08-19 23-32-41](https://github.com/inkstitch/inkstitch/assets/17491743/defd8ba3-d9ea-4e07-8871-bcce7e3ceb91)

**Comment by kaalleen** [comment]
Closing since this is fixed in current main. Thanks again for the error report.
