### ISSUE TITLE
Guided Fill follow guide rails

### ISSUE THREAD

**Issue by rfallara** [inkstitch/inkstitch#2484]
Seems like this should be possible but I am unable to determine how. I want to have the fill pattern follow the shape of an area instead of at a constant angle like auto fill. Guided Fill gets me close but the stitch direction would have to be perpendicular to the guide not parallel like the feature generates. Is this functionality possible?

It also seems like satin with rungs can get very close but I can't make satin lay down a standard fill pattern. Hope I am explaining the issue well
![InkstitchFillDirection](https://github.com/inkstitch/inkstitch/assets/6042999/a6ea5f5e-0c90-41a7-91cb-559603e199ff)

**Comment by kaalleen** [comment]
It's not yet possible in the current release. But chances are good, that the next release will have that options for satins :)

See #2431

**Comment by rfallara** [comment]
Thanks for the quick reply. Yes 2431 looks like exactly what I need. Really great work you all are doing here

**Comment by Marif91** [comment]
Est-ce que la broderie ondulée peut t'aider ?
![Capture d’écran 2023-08-25 à 23 04 41](https://github.com/inkstitch/inkstitch/assets/65076100/7cfa6a58-2113-4d3b-acee-48a5d32d3c76)

**Comment by kaalleen** [comment]
Closing. #2431 (staggered satin split stitches) has been merged and will be available in the next release.
