### ISSUE TITLE
Inkstitch not installing correctly with the install script nor archive on nixos linux

### ISSUE THREAD

**Issue by BestInfinity** [inkstitch/inkstitch#2485]
![image](https://github.com/inkstitch/inkstitch/assets/95188063/120d605d-c8c5-4bba-a18e-70d89abdfa30)
trying to do anything with inkstitch makes an error like this appear

**Comment by kaalleen** [comment]
Have a look over here: https://codeberg.org/tropf/nix-inkstitch

The next version hopefully has no electron anymore and will be easier to install.

**Comment by BestInfinity** [comment]
thank you so much! i've been searching for a fix for a while

**Comment by kaalleen** [comment]
You are welcome. I assume this did work out for you. So I'll close this issue. Please don't hesitate to open a new issue if you are still having problems.
