### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by pcgofpa** [inkstitch/inkstitch#2486]
Not sure if anyone is still maintaining the YouTube channel, if they are my wife mentioned that she would like to be able to find videos that cover different topics. 

Additionally, there should be a video with each release of the software to inform users of what features are being changed or bugs are being fixed in a given release. The most recent video is over a year old even though there was a software release in June.

**Comment by bianchifan** [comment]
https://inkstitch.org/tutorials/video/

**Comment by bkmgit** [comment]
@pcgofpa There are good videos at https://www.youtube.com/@LowTechLinux see also https://lowtechlinux.com

**Comment by pcgofpa** [comment]
Thank you both. I will point her in those directions and see if they have any of the topics she is looking for help with.
