### ISSUE TITLE
Realistic PNG Export

### ISSUE THREAD

**Issue by MasterCyph3r** [inkstitch/inkstitch#2490]
You'll have to forgive me if this has already been asked and answered. Is there a way to export the realistic stitch view as png with alpha channel. I see there is a save as png function but doesn't seem to preserve realistic view. My thoughts are maybe a PNG export in the sim/realistic view window would be awesome and very helpful for mockups :)

**Comment by bkmgit** [comment]
You can either take a screen shot if png is needed or use the print-pdf
option https://inkstitch.org/docs/print-pdf/ which even allows for
thread color matching for greater realism if pdf is ok.

**Comment by capellancitizen** [comment]
Realistic PNG export was added in #3019.
