### ISSUE TITLE
Cannot create VP3 file

### ISSUE THREAD

**Issue by Jewie171** [inkstitch/inkstitch#2492]
<img width="919" alt="Screenshot 2023-08-23 at 1 05 58 PM" src="https://github.com/inkstitch/inkstitch/assets/143021357/99f85cc5-3322-4e1a-8ca8-30fa84dfb391">

**Comment by kaalleen** [comment]
Does it still happens after an update to v3.0.1?

**Comment by kaalleen** [comment]
Closing. Refers to an older version of Ink/Stitch.

Please open a new issue if this is still happening with the current release version of Ink/Stitch.
