### ISSUE TITLE
Inconsistent render brightness at different zoom levels in realistic simulator

### ISSUE THREAD

**Issue by NeighNeighNeigh** [inkstitch/inkstitch#2497]
Hello, 

I've just starting to explore Inkstitch and discovered that on my machine (MacBook Air M2) when I enter the simulator the 'realistic rendering' is vastly different depending on which of the two zoom levels I am using. When zoomed in, the rendering is extremely over exposed (tbh when zoomed out it's still overexposed too, just not as extreme).

Pics attached demonstrating the issue.

<img width="1392" alt="SCR-20230902-uois" src="https://github.com/inkstitch/inkstitch/assets/4795315/6912c30a-0ffb-4bd9-8c15-25fee7ed5818">
<img width="1392" alt="SCR-20230902-uokg" src="https://github.com/inkstitch/inkstitch/assets/4795315/b433b2e4-4022-4f8f-8c2b-13321f7fa242">

**Comment by lexelby** [comment]
Wow, that's pretty terrible.  Thanks for letting us know!

**Comment by kaalleen** [comment]
Realistic rendering was reworked it is (in the stitch plan preview now). Therefore I'll close the issue.
Please open a new issue if there are any problems with the new realistic rendering methods.
