### ISSUE TITLE
Zigzag not detecting properly in development build (kaalleen/preferences-title)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2498]
I've noticed this on a couple of recent dev builds, but specifically right now I'm using https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-preferences-title and zigzags are coming up as running stitch even when they're 3mm wide. I was thinking I had seen where that was supposed to default differently for wider lines, is that wrong?

**Comment by kaalleen** [comment]
We found zigzag was a bad default for lines without dashes, because caused a lot of confusion and bad stitch outs. Therefore we decided that up from 3.0.0 every line should default to a running stitch and has to be set to zigzag explicitly if zigzag is the stitch type of choice. Is that what you wanted to know?

**Comment by tyrosinase** [comment]
Yes, but also no. 😂😭

**Comment by kaalleen** [comment]
Uhm, sorry ...
We've been careful not to break old files though :D

**Comment by tyrosinase** [comment]
Maybe that's what I remember reading. And these days I avoid leaving any zigzags in final designs (in fact, one reason I am on a dev build is the much better conversion to satin), but in the last few days I have learned that BOY OH BOY do I ever rely on that default during the design test phase.

**Comment by kaalleen** [comment]
Sorry to hear that. I'm afraid though there is not much we can do about it. I'm still confident, that it was the right choice to change a terrible default setting.
