### ISSUE TITLE
stitch_plan: TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by linneakcruz** [inkstitch/inkstitch#2501]
V3.0.1 Windows 11

params will not load the preview....

Error Message:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "lib\gui\simulator.py", line 790, in run
  File "lib\gui\simulator.py", line 811, in update_patches
  File "lib\stitch_plan\stitch_plan.py", line 32, in stitch_groups_to_stitch_plan
TypeError: can't multiply sequence by non-int of type 'float'

File:
![drawing](https://github.com/inkstitch/inkstitch/assets/43259389/ea337aea-65af-4287-999e-b30c59a0e6de)

**Comment by linneakcruz** [comment]
@kaalleen I haven't done or changed anything 🙃 it happened out of the blue. The only way for me to go around this issue, is to just open an older document (a document I made before I was having issues), and just scrape it. I've tried uninstalling it, and reinstalling it. Uninstalled it again and made sure my computer was wiped of anything related to the program and install it again. But it's still coming up 😭

**Comment by kaalleen** [comment]
Hm, ok ... Can you test this development build here and see if this changes anything?

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-stitch_plan_multiply_sequence_error

**Comment by kaalleen** [comment]
Ah no don't. There are other issues from an other development branch in there.

**Comment by kaalleen** [comment]
Scratch the last entry. It's back open for testing. The other problem is supposed to be fixed now ...
