### ISSUE TITLE
Replace Electron by GJS and/or PyGobject

### ISSUE THREAD

**Issue by bkmgit** [inkstitch/inkstitch#2510]
Would like to replace Electron by [GJS](https://www.gtk.org/docs/language-bindings/javascript/) and [PyGobject](https://www.gtk.org/docs/language-bindings/python/) to make it easier to package and distribute Inkstitch for Linux distributions.  Might you be willing to look at an example implementation? At present Electron is used for pdf export. Expect some of the javascript can be reused, though styling would need to be redone.

**Comment by lexelby** [comment]
wxPython (which we already use) has far more involved printing support than I had realized when I first created the pdf print support.  My current inclination is to try to move the pdf print support over to wxPython.  What do you think?

One thing that may be tricky is the realistic rendering.  Do you have any 3d graphics experience by any chance?

**Comment by bkmgit** [comment]
[wxPython](https://wxpython.org/) would be fine, a related library is [wxpdfdoc](https://github.com/utelle/wxpdfdoc).  Inkscape uses [cairo](https://cairographics.org/) which also has Python bindings, an alternative is [python-skia](https://github.com/kyamagu/skia-python).  [Poppler](https://poppler.freedesktop.org/) can also be used to create PDF output.

For realistic rendering, [PyOpenGl](https://pyopengl.sourceforge.net/) maybe worth trying. [PyGlet](https://pyglet.org/) is another OpenGl binding, though integration maybe more difficult.

[Inkscape documentation](https://inkscape-manuals.readthedocs.io/en/latest/export-pdf.html) suggests using [Scribus](https://www.scribus.net/) for high quality color matched pdf generation.

**Comment by kaalleen** [comment]
I'm still a fan of the idea to move the PDF output directly into Inkscape itself.

**Comment by lexelby** [comment]
Oh yeah, I forgot about the Inkscape idea :)

**Comment by bkmgit** [comment]
Inkscape uses [GTK](https://gitlab.com/inkscape/inkscape/-/blob/master/src/print.cpp?ref_type=heads#L92) for print output which will then use Cairo.  My initial interest is re-implementing the current functionality to remove electron but still make it easy for people to contribute.  3D rendering is more involved  as one would need to add some models for how threads would sit on the fabric, but the [current approach of adding filters](https://github.com/inkstitch/inkstitch/blob/main/electron/src/renderer/assets/js/simulator.js) is possible.

Tutorials on animation with Cairo:
- https://github.com/morgner/Cairo-Tutorial
- https://www.cairographics.org/cookbook/animationrotation/

The [simulator](https://github.com/inkstitch/inkstitch/blob/main/lib/gui/simulator.py) uses wxPython. This has a [Cairo
backend](https://github.com/wxWidgets/Phoenix/tree/master/wx/lib/wxcairo)

**Comment by lexelby** [comment]
I get that 3d would have a fixing learning curve, and approachability is a bit priority in this project.  I just feel like the current realistic view doesn't look all that good...

**Comment by bkmgit** [comment]
We can initially try other filters that give 3D effects in 2D.  It is
possible to write a custom filter.

There is open source 3D rendering software, see for example:
https://en.wikipedia.org/wiki/List_of_3D_rendering_software
https://www.ogre3d.org
https://github.com/google/filament

But experimenting with these, might be a next step.  They also require
more computational power, and would need time to plan features to be added.

**Comment by kaalleen** [comment]
Electronn will be replaced by wxpython. Let's try to evaluate further steps in a new issue.
