### ISSUE TITLE
Satin Column on Params

### ISSUE THREAD

**Issue by rsvp123** [inkstitch/inkstitch#2511]
Hello! 

I am trying to design a logo and I wish to use satin stitching but when I go to my extensions, inkstitch and then params It does not show me the satin column that is shown to all the individuals that I see doing tutorials so I am a little stuck. As you can see from the screenshot below, those are the only options shown to me. What should I do to be able to do satin stitching? 

<img width="469" alt="Screenshot 2023-09-11 170105" src="https://github.com/inkstitch/inkstitch/assets/144693818/637c6c43-9cd2-4b42-8240-4cb63bdcbddb">

Thank you in advance if you can help!

**Comment by gusvisser** [comment]
your object has all fill for a satin you need to create two rails and some rungs and combine them or you create a lineand set the width of the line you want your satin to be and then go to inkstitch satin tools convert line to satin and then apply the params
