### ISSUE TITLE
Params error?

### ISSUE THREAD

**Issue by UhOhItsDorian** [inkstitch/inkstitch#2513]
I'm totally new to Inkstitch and don't know anything about code either, so maybe it's a me problem, but I can't open params with seemingly anything. I get this error message:

> Ink/Stitch Version: v3.0.1 (windows)
> 
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 84, in <module>
>   File "inkex\base.py", line 250, in run
>   File "lib\extensions\params.py", line 786, in effect
>   File "lib\extensions\params.py", line 489, in __init__
>   File "lib\extensions\params.py", line 748, in create_tabs
>   File "lib\extensions\params.py", line 678, in get_nodes_by_class
>   File "lib\extensions\base.py", line 115, in get_nodes
>   File "lib\extensions\base.py", line 99, in descendants
>   File "lib\extensions\base.py", line 79, in descendants
>   File "lib\elements\element.py", line 170, in get_style
>   File "lib\elements\element.py", line 167, in _get_specified_style
>   File "inkex\elements\_base.py", line 628, in specified_style
>   File "inkex\styles.py", line 465, in specified_style
>   File "inkex\styles.py", line 428, in cascaded_style
>   File "inkex\elements\_svg.py", line 387, in stylesheets
>   File "inkex\elements\_meta.py", line 60, in stylesheet
>   File "inkex\styles.py", line 531, in __init__
>   File "inkex\styles.py", line 555, in append
>   File "inkex\styles.py", line 597, in __init__
>   File "inkex\styles.py", line 597, in <listcomp>
>   File "inkex\css.py", line 43, in __init__
>   File "cssselect\parser.py", line 543, in parse
>   File "cssselect\parser.py", line 558, in parse_selector_group
>   File "cssselect\parser.py", line 567, in parse_selector
>   File "cssselect\parser.py", line 621, in parse_simple_selector
> cssselect.parser.SelectorSyntaxError: Got pseudo-element ::-moz-range-thumb not at the end of a selector

The file in question (yeah it's a Mechanisms patch) - though this isn't the only file I'm having the issue with, it seems to be universal.
![Aurora4](https://github.com/inkstitch/inkstitch/assets/144854433/4365a2ce-965b-4dc6-bdd1-ba470f97aac4)

I've also tried updating the program and giving it exceptions on my antivirus.

**Comment by kaalleen** [comment]
Oh, this is an error coming from style settings in your files. You could try to open the files and remove the style attributes with `::-moz-range-thumb`. Seems as if cssselect isn't able to parse it.

**Comment by kaalleen** [comment]
I just noticed, that you did send a file along. Looks as if I answered too fast last time.
There is a whole bunch of css styles in there as if this was made for a complete website.

I guess your best option here is to just select everything copy and paste into a new document. Then you can start with the path conversions for embroidery.

**Comment by UhOhItsDorian** [comment]
That seems to have done it! Thank you so much, what a simple solution XD and I've been trying on and off to figure this out for months now! Thank you :'D

**Comment by kaalleen** [comment]
Great. Thank you for your feedback.
