### ISSUE TITLE
duplicate inkstitch commands

### ISSUE THREAD

**Issue by purplevann1** [inkstitch/inkstitch#2515]
I installed inkstitch 3.1, and now I have duplicates of all the commands in my menu.  I completely uninstalled inkscape 1.3, made sure all the files and folder were gone.  Then I reinstalled Inkscape 1.3.  I DID NOT install inkstitch.  The duplicate inkstitch commands were still in my extensions menu.
![Screenshot 2023-09-16 123553](https://github.com/inkstitch/inkstitch/assets/87343443/1ff78d0c-172e-45c7-a03c-746d9a39b563)

**Comment by kaalleen** [comment]
Looks like a previous version hasn't been removed.

First try to uninstall Ink/Stitch through your system. This will uninstall the newest Ink/Stitch version. Then in Inkscape go to Edit > Preferences. Then click on system and watch out for the user extension folder and open it. Delete the Ink/Stitch folder / files. Now reinstall the new version.
