### ISSUE TITLE
Importing digitized font into Ink/Stitch

### ISSUE THREAD

**Issue by brielleplost** [inkstitch/inkstitch#2520]
I'm having trouble importing an embroidery font purchased on Etsy into Ink/Stitch. I have downloaded the files, created a .-->svg file and JSON and created a custom font directory. However, when I open the "Lettering" function I get the following error: "This font has no available font variant. Please update or remove the font." Any help would be greatly appreciated! Thanks!

**Comment by claudinepeyrat06** [comment]
@brielleplost Is  your  svg file named  →.svg ?
If not, this is the problem.

**Comment by brielleplost** [comment]
> @brielleplost Is your svg file named →.svg ? If not, this is the problem.

It is. I have the svg file and json file in the folder. The font didn't come with a license so I don't have a license file in the folder.

<img width="333" alt="image" src="https://github.com/inkstitch/inkstitch/assets/145632734/fb31edb8-5409-4711-b99a-802ed4bae341">

**Comment by claudinepeyrat06** [comment]
@brielleplost The name of the file should be just  →.svg not Ellen→.svg
Correct that and it should work.

**Comment by brielleplost** [comment]
@claudinepeyrat06 Yep you're right! Thank you so much!
