### ISSUE TITLE
Params Crash - Mac OS Catalina 10.15.17 

### ISSUE THREAD

**Issue by spacedbitch** [inkstitch/inkstitch#2523]
Hi all! I've been having this issue since the newest release, unfortunately I haven't been able to work with the newest Inkstitch 3.0.1 yet. I've tried reinstalling both inkscape/inkstitch, ensuring the inkstitch extension is located within the inkscape extension's folder. It is consistent across different design files, though I've notice sometimes the crashed thread will be:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

but mainly, the below content is what I'm seeing come back in console for the crash report. I've removed some of the binary data as the message was too long.

Thank you so incredibly much for your time with this! 

Process:               inkstitch [7680]
Path:                  /Users/USER/Library/Application Support/org.inkscape.Inkscape/*/inkstitch.app/Contents/Resources/inx/../../MacOS/inkstitch
Identifier:            org.inkstitch.app
Version:               3.0.1 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           inkscape [7501]
User ID:               501

Date/Time:             2023-09-23 11:40:51.496 -0400
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        C0EB16AC-E55D-EB64-3C03-95856E4DA088

Sleep/Wake UUID:       4FA96E5A-FE36-47F9-81B2-E7D1C11988F3

Time Awake Since Boot: 65000 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: enabled

Crashed Thread:        8

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7680]

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff37ee295b __CFStringEqual + 182
1   com.apple.CoreFoundation      	0x00007fff37dc8e26 -[__NSCFString isEqual:] + 66
2   com.apple.CoreFoundation      	0x00007fff37de1216 -[__NSDictionaryM objectForKey:] + 172
3   com.apple.coreui              	0x00007fff515a4ed6 -[CUIStructuredThemeStore renditionWithKey:usingKeySignature:] + 190
4   com.apple.coreui              	0x00007fff515bb010 -[CUIThemeFacet _approximateRenditionForRenditionKey:] + 1091
5   com.apple.coreui              	0x00007fff515baa3a -[CUIThemeFacet renditionMetricsWithKeyAdjustment:] + 133
6   com.apple.coreui              	0x00007fff515b93fd CUICoreThemeRenderer::CopyMeasurementsForRendition(CUIRenditionKey*, CUIDescriptor const*, __CFDictionary const*, __CFArray const*, __CFDictionary*) + 111
7   com.apple.coreui              	0x00007fff5159c3c0 CUIRenderer::CopyMeasurements(CGRect, CGContext*, __CFDictionary const*, __CFArray const*) + 254
8   com.apple.coreui              	0x00007fff5159c288 CUICopyMeasurements + 288
9   com.apple.AppKit              	0x00007fff35144afe __72-[NSAppearance _copyMeasurements:context:options:requestedMeasurements:]_block_invoke + 67
10  com.apple.AppKit              	0x00007fff35103393 -[NSCompositeAppearance _callCoreUIWithBlock:options:requireBezelTintColor:] + 389
11  com.apple.AppKit              	0x00007fff35144a7b -[NSAppearance _copyMeasurements:context:options:requestedMeasurements:] + 188
12  com.apple.AppKit              	0x00007fff3537294c -[NSAppearance _alignmentRectInsetsForWidget:] + 229
13  com.apple.AppKit              	0x00007fff35372841 -[NSButtonCell _coreUIAlignmentRectInsetsForRect:inView:] + 195
14  com.apple.AppKit              	0x00007fff351bfd4c -[NSButtonCell _alignmentRectInsetsForRect:inView:] + 292
15  com.apple.AppKit              	0x00007fff351b19ca -[NSButton alignmentRectInsets] + 339
16  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001163b9394 wxWidgetCocoaImpl::GetLayoutInset(int&, int&, int&, int&) const + 52
17  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001162eefc8 wxWindow::MacGetTopBorderSize() const + 72
18  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x0000000116330646 wxWindowDCImpl::wxWindowDCImpl(wxDC*, wxWindow*) + 294
19  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001163f922b wxNativeDCFactory::CreateWindowDC(wxWindowDC*, wxWindow*) + 43
20  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001163f9560 wxWindowDC::wxWindowDC(wxWindow*) + 80
21  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001162ee720 wxWindow::MacDoRedraw(long) + 272
22  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001163b7926 wxWidgetCocoaImpl::drawRect(void*, NSView*, void*) + 742
23  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x00000001163b4896 wxOSX_drawRect(NSView*, objc_selector*, CGRect) + 86
24  com.apple.AppKit              	0x00007fff3528391f _NSViewDrawRect + 139
25  com.apple.AppKit              	0x00007fff35282c2e -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2170
26  com.apple.AppKit              	0x00007fff35282fbf -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 3083
27  com.apple.AppKit              	0x00007fff35282fbf -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 3083
28  com.apple.AppKit              	0x00007fff35282fbf -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 3083
29  com.apple.AppKit              	0x00007fff3528202a -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 1271
30  com.apple.QuartzCore          	0x00007fff4379472d CABackingStoreUpdate_ + 595
31  com.apple.QuartzCore          	0x00007fff437f43a1 invocation function for block in CA::Layer::display_() + 53
32  com.apple.QuartzCore          	0x00007fff43793c2a -[CALayer _display] + 2103
33  com.apple.AppKit              	0x00007fff35281a1a -[_NSBackingLayer display] + 537
34  com.apple.AppKit              	0x00007fff351e3507 -[_NSViewBackingLayer display] + 800
35  com.apple.QuartzCore          	0x00007fff43792cad CA::Layer::display_if_needed(CA::Transaction*) + 757
36  com.apple.QuartzCore          	0x00007fff43770fca CA::Context::commit_transaction(CA::Transaction*, double) + 334
37  com.apple.QuartzCore          	0x00007fff4376fbb4 CA::Transaction::commit() + 644
38  com.apple.AppKit              	0x00007fff35298041 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 266
39  com.apple.AppKit              	0x00007fff359b6920 ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
40  com.apple.CoreFoundation      	0x00007fff37e4313c __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
41  com.apple.CoreFoundation      	0x00007fff37e4306c __CFRunLoopDoObservers + 457
42  com.apple.CoreFoundation      	0x00007fff37e42604 __CFRunLoopRun + 884
43  com.apple.CoreFoundation      	0x00007fff37e41c33 CFRunLoopRunSpecific + 466
44  com.apple.HIToolbox           	0x00007fff36aafaad RunCurrentEventLoopInMode + 292
45  com.apple.HIToolbox           	0x00007fff36aaf6e4 ReceiveNextEventCommon + 359
46  com.apple.HIToolbox           	0x00007fff36aaf569 _BlockUntilNextEventMatchingListInModeWithFilter + 64
47  com.apple.AppKit              	0x00007fff350f83c9 _DPSNextEvent + 883
48  com.apple.AppKit              	0x00007fff350f6c10 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
49  com.apple.AppKit              	0x00007fff350e891e -[NSApplication run] + 658
50  libwx_osx_cocoau_core-3.2.0.0.0.dylib	0x0000000116394cda wxGUIEventLoop::OSXDoRun() + 186
51  libwx_baseu-3.2.0.0.0.dylib   	0x0000000116be4c5d wxCFEventLoop::DoRun() + 29
52  libwx_baseu-3.2.0.0.0.dylib   	0x0000000116b3051e wxEventLoopBase::Run() + 158
53  libwx_baseu-3.2.0.0.0.dylib   	0x0000000116afe6f3 wxAppConsoleBase::MainLoop() + 99
54  _core.cpython-39-darwin.so    	0x00000001157dfd81 meth_wxPyApp_MainLoop(_object*, _object*) + 209
55  Python                        	0x0000000101c0a012 cfunction_call + 130
56  Python                        	0x0000000101bc4f41 _PyObject_MakeTpCall + 353
57  Python                        	0x0000000101cb6e70 call_function + 768
58  Python                        	0x0000000101cb3b73 _PyEval_EvalFrameDefault + 26467
59  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
60  Python                        	0x0000000101cb6d07 call_function + 407
61  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
62  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
63  Python                        	0x0000000101cb6d07 call_function + 407
64  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
65  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
66  Python                        	0x0000000101bc56e1 _PyFunction_Vectorcall + 257
67  Python                        	0x0000000101bc7d36 method_vectorcall + 198
68  Python                        	0x0000000101cb6d07 call_function + 407
69  Python                        	0x0000000101cb3ca2 _PyEval_EvalFrameDefault + 26770
70  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
71  Python                        	0x0000000101cad349 PyEval_EvalCode + 73
72  org.inkstitch.app             	0x00000001010f4152 0x1010f2000 + 8530
73  org.inkstitch.app             	0x00000001010f454e 0x1010f2000 + 9550
74  org.inkstitch.app             	0x00000001010f2a14 0x1010f2000 + 2580

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff710bb872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71180425 _pthread_cond_wait + 698
2   libopenblas64_.0.dylib        	0x000000010373e23f blas_thread_server + 207
3   libsystem_pthread.dylib       	0x00007fff71180109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff7117bb8b thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff710bb872 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71180425 _pthread_cond_wait + 698
2   libopenblas.0.dylib           	0x00000001109c470f blas_thread_server + 207
3   libsystem_pthread.dylib       	0x00007fff71180109 _pthread_start + 148
4   libsystem_pthread.dylib       	0x00007fff7117bb8b thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff7117bb68 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff7117bb68 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff7117bb68 start_wqthread + 0

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff710b8dea mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff710b9160 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff37e43d07 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff37e427c1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff37e41c33 CFRunLoopRunSpecific + 466
5   com.apple.AppKit              	0x00007fff35299bf4 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff71180109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff7117bb8b thread_start + 15

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff7117bb68 start_wqthread + 0

Thread 8 Crashed:
0   libgeos_c.1.18.0.dylib        	0x000000010c0f6235 GEOSisEmpty_r + 36
1   libffi.dylib                  	0x00007fff6ed22905 ffi_call_unix64 + 85
2   libffi.dylib                  	0x00007fff6ed22244 ffi_call_int + 694
3   _ctypes.cpython-39-darwin.so  	0x0000000102172ca1 _ctypes_callproc + 1041
4   _ctypes.cpython-39-darwin.so  	0x000000010216c05b PyCFuncPtr_call + 1291
5   Python                        	0x0000000101bc54fa _PyObject_Call + 138
6   Python                        	0x0000000101d4a429 partial_call + 137
7   Python                        	0x0000000101bc4f41 _PyObject_MakeTpCall + 353
8   Python                        	0x0000000101cb6e70 call_function + 768
9   Python                        	0x0000000101cb3b73 _PyEval_EvalFrameDefault + 26467
10  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
11  Python                        	0x0000000101bc4da0 _PyObject_FastCallDictTstate + 304
12  Python                        	0x0000000101bc5ace _PyObject_Call_Prepend + 158
13  Python                        	0x0000000101c2889b slot_tp_call + 203
14  Python                        	0x0000000101bc4f41 _PyObject_MakeTpCall + 353
15  Python                        	0x0000000101cb6e70 call_function + 768
16  Python                        	0x0000000101cb3c06 _PyEval_EvalFrameDefault + 26614
17  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
18  Python                        	0x0000000101bcf1f7 property_descr_get + 119
19  Python                        	0x0000000101c0e1b7 _PyObject_GenericGetAttrWithDict + 183
20  Python                        	0x0000000101cb1fb2 _PyEval_EvalFrameDefault + 19362
21  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
22  Python                        	0x0000000101bc56e1 _PyFunction_Vectorcall + 257
23  Python                        	0x0000000101bc538e PyVectorcall_Call + 158
24  Python                        	0x0000000101cb3e54 _PyEval_EvalFrameDefault + 27204
25  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
26  Python                        	0x0000000101bc56e1 _PyFunction_Vectorcall + 257
27  Python                        	0x0000000101bc7d36 method_vectorcall + 198
28  Python                        	0x0000000101cb6d07 call_function + 407
29  Python                        	0x0000000101cb3ca2 _PyEval_EvalFrameDefault + 26770
30  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
31  Python                        	0x0000000101bc56e1 _PyFunction_Vectorcall + 257
32  Python                        	0x0000000101cb6d07 call_function + 407
33  Python                        	0x0000000101cb3c06 _PyEval_EvalFrameDefault + 26614
34  Python                        	0x0000000101cb7e32 _PyEval_EvalCode + 3282
35  Python                        	0x0000000101bc56e1 _PyFunction_Vectorcall + 257
36  Python                        	0x0000000101cb6d07 call_function + 407
37  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
38  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
39  Python                        	0x0000000101cb6d07 call_function + 407
40  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
41  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
42  Python                        	0x0000000101cb6d07 call_function + 407
43  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
44  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
45  Python                        	0x0000000101cb6d07 call_function + 407
46  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
47  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
48  Python                        	0x0000000101cb6d07 call_function + 407
49  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
50  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
51  Python                        	0x0000000101cb6d07 call_function + 407
52  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
53  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
54  Python                        	0x0000000101cb6d07 call_function + 407
55  Python                        	0x0000000101cb3b53 _PyEval_EvalFrameDefault + 26435
56  Python                        	0x0000000101bc57d5 function_code_fastcall + 229
57  Python                        	0x0000000101bc7dc0 method_vectorcall + 336
58  Python                        	0x0000000101d60ac6 t_bootstrap + 70
59  Python                        	0x0000000101d0cf39 pythread_wrapper + 25
60  libsystem_pthread.dylib       	0x00007fff71180109 _pthread_start + 148
61  libsystem_pthread.dylib       	0x00007fff7117bb8b thread_start + 15

Thread 8 crashed with X86 Thread State (64-bit):
  rax: 0x406a75e65a5e9b0c  rbx: 0x00007fc0470dda00  rcx: 0x000000011ceae680  rdx: 0x0000000000000000
  rdi: 0x00007fc047b80460  rsi: 0x00007fc047b80460  rbp: 0x000070000dffb7f0  rsp: 0x000070000dffb7d0
   r8: 0x000070000dffb7b0   r9: 0x0000000101bdfac8  r10: 0x0000000000000000  r11: 0x000000010c0f6211
  r12: 0x0000000000000002  r13: 0x0000000000000002  r14: 0x000070000dffb8e0  r15: 0x0000000000000002
  rip: 0x000000010c0f6235  rfl: 0x0000000000010202  cr2: 0x000000010c0f6211
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     13

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 30642
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=860.8M resident=0K(0%) swapped_out_or_unallocated=860.8M(100%)
Writable regions: Total=300.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=300.7M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                  224K        2 
CG image                           388K       13 
CoreAnimation                     13.6M      197 
CoreGraphics                         8K        1 
CoreImage                            8K        2 
CoreServices                       132K        1 
CoreUI image data                 1200K       23 
Dispatch continuations            8192K        1 
Foundation                           4K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           101.1M       99 
MALLOC guard page                   32K        8 
MALLOC_LARGE (reserved)            128K        1         reserved VM address space (unallocated)
SQLite page cache                   64K        1 
STACK GUARD                       56.0M        9 
Stack                             27.6M        9 
VM_ALLOCATE                      115.9M      226 
VM_ALLOCATE (reserved)            32.0M        1         reserved VM address space (unallocated)
__DATA                            37.0M      483 
__DATA_CONST                        89K        5 
__FONT_DATA                          4K        1 
__LINKEDIT                       423.1M      224 
__OBJC_RO                         32.3M        1 
__OBJC_RW                         1860K        2 
__TEXT                           438.3M      463 
__UNICODE                          564K        1 
mapped file                       65.3M       23 
shared memory                      632K       14 
===========                     =======  ======= 
TOTAL                              1.3G     1817 
TOTAL, minus reserved VM space     1.3G     1817 

@inkstitch-builds

**Comment by kaalleen** [comment]
Sorry you didn't receive an answer yet. Did you find out anything about the issue in the meantime?

**Comment by kaalleen** [comment]
Closing. Possibly outdated issue. You can still post questions in here if the issue still shows up.
