### ISSUE TITLE
handle self-intersecting stroke in Convert to Satin

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#253]
#252 introduced the Convert to Satin extension.  It contains a limitation that it won't work with paths that have portions of their stroke that intersect other portions.

Remove this limitation, possibly by automatically splitting the path into multiple parts and stitching the resulting satins together.

**Comment by X3msnake** [comment]
Why the limitation?

**Comment by lexelby** [comment]
Because the Shapely library function I'm using to do parallel offsets of lines handles this case weirdly.  If you curious, look kin the code for #252 which describes the limitation in more detail and links to a picture.

**Comment by lexelby** [comment]
What's your goal with these questions?  Please keep in mind that I didn't ask for help or proposals for solutions.

If this were easy to solve, I would have done so already.  If I'm not doing what seems obvious, that's probably because it's not going to work for some complicated reason.  If it took you a few minutes to come up with an idea, I very likely also thought of it too.

Making these suggestions and asking me why they won't work ("why not use...?") is a request for me to take the time to educate you on my thought process.  It's not respectful of the fact that I've spent many hours thinking about this already.  In addition, I almost always document these kinds of weird-seeming limitations in the code.  It's not a good use of my time to also explain here the reasons why all the obvious solutions don't work.  

I can't help but feel some discomfort when you jump in and make simple suggestions after I've already said that a problem is difficult.  A lot of the algorithmic problems involved in Ink/Stitch (and in anything like it) are quite challenging.  Jumping in with the first suggestion that pops into your head after I've already said the problem is challenging can come across as minimizing the significant effort I've already put into coming up with solutions and implying that the problem is "easy".

It is true that upon occasion, having another person bounce ideas off of me can spark a realization that I missed something obvious.  However, in doing so, you run a significant risk of hurt feelings as described above.  There's a very fine balance here, and I'm telling you how I'm feeling so that you have enough information to make an informed decision about when to make this kind of suggestion and when not to.



All that said, since I'm already here, I'll answer your question:

> why not use the inkscape action to convert stroke to paths?

Because Inkscape has the exact same limitation that Shapely does.

**Comment by X3msnake** [comment]
@lexelby OkOk i'll shut up, just trying to help.

Sometimes questions from us lesser knowlageble guys is a good thing i see it wasn't. sorry.
