### ISSUE TITLE
When creating my own font, I cannot get satin stitching.

### ISSUE THREAD

**Issue by Devilcow** [inkstitch/inkstitch#2536]
Hello, I used the tutorial on the website, and even read an article here about trying to get a Cyrillic font. 

I can get the Cyrillic characters, but they will not stitch in Satin. I've tried a few variations on the JSON file, but no matter what I do I cannot get the Cyrillic font in Satin stitching. 

Is there some process to force the statin? 

I've also tried just using the regular inkscape text, give it a stroke, and use that, but it then causes the satin to be an outline around the letters, and not just the letters in satin stitch?

Is it a feature in future development? 
Am I just intensely dense and not doing something? LOL

Thank you!

**Comment by bkmgit** [comment]
There are a number of tutorials on making fonts, for example:
- https://inkstitch.org/tutorials/font-creation/
- https://edutechwiki.unige.ch/en/InkStitch_-_design_letters
- https://www.youtube.com/watch?v=4bRyF_3Dkqs
Which one did you use? Can you attach the SVG file you created to this issue?

**Comment by bianchifan** [comment]
> I've also tried just using the regular inkscape text, give it a stroke, and use that, but it then causes the satin to be an outline around the letters, and not just the letters in satin stitch?

SVG???
Maybe the strokes were converted to satin..

For a satin column you need  two paths in same direction, if the node count is different you also need some "rungs".
All these pathes must be combined to a new path.

**Comment by Devilcow** [comment]
Okay, I tried again using a different base font (DejaVuSans) using the first link you sent me (the one I used originally).

(General steps I executed below)

- Using FontForge open the DejaVuSansFont.
- Select all Cyrillic characters.
- Invert selection, and clear characters.
- When prompted about Clearing characters that are referenced, I select "No to all" (keeping any linked characters).
- Use Element->Font Info->General and record the Em, Descent, and ascent sizes.
- Generate SVG file →.svg. While exporting the file, I get an error saying "...Missing - Points at Extrema..."I clicked "Generate".
- Open the file →.svg in Inkscape.
- Click Extensions->Typography->1 - Setup typographic canvas.
- Enter the Em, Descender, and Ascender values.
- Click Extensions->Typography->Convert SVG Font to Glyph Layers. (Stop after 150 chars). Note:  The guidelines for the characters seem to be doubled? two sets of ascender, descender, etc. The extra set is floating well above the sample character. 
- Delete the extra sets of guidelines.
- Go to File->Document Properties, click Scale +  then -.
- Save the file, as a backup as well as a working copy of the file.
- Click Extensions->InkStitch->Font Management->Generate JSON (I previously had set the custom font Dir)
- In the Generate JSON settings, I entered the Name of the original font, set Size to 25. Checked "Autoroute Satin" Unchecked "Reversable", Min/Max scale 0.5/10, and used the original Default Glyph.

I then opened a new session of InkScape. 
When I go to Extensions->InkStitch->Lettering and enter some cyrillic text, it shows the sample stitching as a fill stitch, and not a satin. 

The font is also huge (is this the EM setting?)


![→](https://github.com/inkstitch/inkstitch/assets/44623747/c4f6b0ef-292d-46fe-a331-0c6a1188748f)

Let me know if there are any steps I missed, or need to do in addition. 

Thank you!

**Comment by Devilcow** [comment]
Addendum;
I repeated the process, changing the font EM to 80, and still have the same result.
I know this is probably expected, but I figured I'd try to see if it helped.

**Comment by bianchifan** [comment]
OK...

bkmgit pointed out InkStitch Tutorial..there you will find a pic from augusa (Font master)
Please lokk at the "R", ther a a couple of rails with rungs, and that is what you need!

But how do look your's?

![Bildschirmfoto vom 2023-10-03 21-57-21](https://github.com/inkstitch/inkstitch/assets/17491743/238c6f5a-10c7-40ec-a9be-44585df88139)
One lonely path with an outline stroke, width 1px and a non defined fill, which results in a black fill!
Please excuse me, but that is shit.
I did a simple design of this letter without any rungs, just simple combined path with a minimum of nodes.

![Bildschirmfoto vom 2023-10-03 23-09-55](https://github.com/inkstitch/inkstitch/assets/17491743/6037c27e-5945-4a50-8979-aeaba05cf08c)

And the corresponding SVG
![Test](https://github.com/inkstitch/inkstitch/assets/17491743/b288f3d3-f19b-4eb8-8b60-2163a42c3d8c)

**Comment by kaalleen** [comment]
It'd be really nice if you could tell Ink/Stitch to convert a fill to a Satin column. But it is not as easy as that.

Satin columns need to be carefully created. A good start to learn about them is to look at other files (as @bianchiafan said above). I've heard that there are some videos out there on YouTube as well. And of course a good resource is our own website https://inkstitch.org/docs/stitches/satin-column/

@bianchifan I've learned that the word "shit" is quite harsh in the English speaking world. Although Germans use it a lot, I think it is best to avoid it in international conversations :D

**Comment by Devilcow** [comment]
I see, I had been considering making the characters from scratch, and it
seems like that may be a worth while approach. I'll go through the other
tutorial since it looks like it's more of what I want to get accomplished.

Thanks much for the help! Pleaser mark this issue as closed for the time
being. If I run into any new issues, I'll comment of the thread, but it
sounds like this isn't an issue so much as a user education issue.

Cheers! And thanks again!
Jesse

**Comment by bkmgit** [comment]
Any suggestions on how the documentation could be improved to make it
clearer would also be appreciated.
