### ISSUE TITLE
Problems with PDF/Electron

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2539]
Another problem with the SVG mentioned in [issue 2538](https://github.com/inkstitch/inkstitch/issues/2538) came up whithin the PDF export dialog.
It was not possible to select  a realistic view.
Sometimes I received a blank screen, sometimes a blank sheet and sometimes weired shit..
![Bildschirmfoto vom 2023-08-29 12-14-00](https://github.com/inkstitch/inkstitch/assets/17491743/217c32e9-10af-4754-9654-00d901028007)
![Bildschirmfoto vom 2023-08-29 11-29-31](https://github.com/inkstitch/inkstitch/assets/17491743/5def8c87-3d49-4524-87ad-fddabda647db)
![Bildschirmfoto vom 2023-09-26 12-21-06](https://github.com/inkstitch/inkstitch/assets/17491743/5069526a-130f-49d2-88b0-c6cee2d748e2)

**Comment by bkmgit** [comment]
PDF Generation worked with InkScape 1.2 and Ink/Stitch 3.0.1 on Fedora linux.  What version of InkScape did you use, on what operating system and how was it installed?
[SwanRealistic.pdf](https://github.com/inkstitch/inkstitch/files/12795300/SwanRealistic.pdf)

**Comment by bianchifan** [comment]
InkStitch 3.0.1
![Dell Studio Xps 1340](https://github.com/inkstitch/inkstitch/assets/17491743/bf8695a8-6198-46df-8e65-cd4481274f49)
Since Nvidia abandonded Linux support, Ubuntu does not work any more.
Last system working well: Linux Mint 20.3

Linux Mint 21.0 did not upgrade, did not install
Linux Mint 21.1 did not install
Linux Mint 21.2 did install but problems with VLC and Firefox and some other stuff

Linux Mint 20.3 too old for Inkscape 1.1 /  Inkstitch 3.0

**Comment by bkmgit** [comment]
Processor has lasted a long time:
https://ark.intel.com/content/www/us/en/ark/products/37266/intel-core2-duo-processor-p9600-6m-cache-2-66-ghz-1066-mhz-fsb.html
 Maybe check for other graphics card drivers. Noveau may work for you https://nouveau.freedesktop.org

**Comment by bianchifan** [comment]
Other graphiccard? IT's a notebook!
The problem is: there are two cards, onboard and dedicated.
No other card possible!
Noveau is installed,of course!

**Comment by bkmgit** [comment]
You might also consider a distribution that will work well with older hardware such as [Trisquel](https://trisquel.info/)

**Comment by kaalleen** [comment]
Closing as electron won't be a part of the next release anymore.
