### ISSUE TITLE
Problems with short, short stitches on underpathes/contour pathes

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2540]
For Kielux presentation last month I created a "Kielux Disk" in two versions, 10cm  and 12cm diameter.
For I liked to present "disks" i decided to create patches with "Madeira Cut&Iron away  Super Film".
But this film does not coorporate with my domestic embroider crap, it is designed for magnetic Mighty Hoops only.
At least  I managed to fix two layers in my plastic frame and switched from circular fill to autofill in two parts, vertical and horizontal. But this did cut my film sandwich..
1st try on felt with Avalon.. 2mm distance, 4mm length..but look at the underpath, shorter than 1mm!
![DSC05529](https://github.com/inkstitch/inkstitch/assets/17491743/361586ed-3b68-4b11-be43-d02f4ee1709a)

Without underpath it was better but not perfect.
![DSC05525](https://github.com/inkstitch/inkstitch/assets/17491743/f11b37a1-b37b-44e9-8af3-902db1cbafb0)

With the two parted fillstitch the film sandwich crashed, too much short stitches on the separation line...
..and once crashed the border did the same :(
![DSC05554 JPG](https://github.com/inkstitch/inkstitch/assets/17491743/677a60dc-cd88-4c09-8e52-75a4d168e27a)

**Comment by kaalleen** [comment]
That's not nice. Can you attach the svg?

**Comment by kaalleen** [comment]
Never heard of the issue again and there is no svg file to work on. We have improve handling for small stitches as well.
I'll close the issue for now. Please complain if you still see the issue with current dev versions (or any version greater than 3.1.0)
