### ISSUE TITLE
Underlay not filling in the main section of logo

### ISSUE THREAD

**Issue by aritchey6** [inkstitch/inkstitch#2548]
I cannot get the underlay to properly fill in the mule section of the attached logo. The fill stitches are working fine. 

![Logo_Black_NoGradient_NoTextShadow_Invert](https://github.com/inkstitch/inkstitch/assets/147642203/01acc057-ac09-4a0c-a95e-723018172cf7)

**Comment by kaalleen** [comment]
Parts of this design would look much nicer if they were actually better prepared for embroidery. But nevertheless... if you want to get the underlay on the mule, you could try to set the underlay inset to 0.2 (or more). That should do the trick (reducing narrow parts, so they won't be an issue anymore).

**Comment by aritchey6** [comment]
kaalleen, 

That worked, thank you for your help!

I am very new to digitizing embroidery designs. Would you mind giving me some guidance? How could I better prepare the design for embroidery?

**Comment by tyrosinase** [comment]
https://silverseams.com/tutorials/digitizing-with-ink-stitch/index.html will get you started.

I think there might also be video tutorials but I am not a video person myself.

**Comment by aritchey6** [comment]
I will check it out.  Thanks!
