### ISSUE TITLE
DST export not working via 'Save as...' dialogue under Windows

### ISSUE THREAD

**Issue by jdieg0** [inkstitch/inkstitch#258]
When saving an DST file under Windows via the 'Save as...' dialogue an incomplete file is saved. It only contains the [header](https://edutechwiki.unige.ch/en/Embroidery_format_DST#Header), e. g.:

```
LA:Untitled        
ST:    301
CO:  0
+X:  994
-X:  994
+Y: 1010
-Y: 1010
AX:+    0
AY:+    0
MX:+    0
AY:+    0
PD:******
```

Thus an error is shown when I try to reopen the DST file with Inkscape.

> Traceback (most recent call last):
> 
>   File "inkstitch.py", line 20, in <module>
> 
>     if script_name.endswith('.py'):
> 
>   File "lib\extensions\input.py", line 30, in affect
> 
>   File "lib\stitch_plan\stitch_plan.py", line 127, in extents
> 
>   File "lib\stitch_plan\stitch_plan.py", line 112, in bounding_box
> 
>   File "lib\stitch_plan\stitch_plan.py", line 251, in bounding_box
> 
> ValueError: min() arg is an empty sequence

Whereas if I generate the file via the 'Embroider' dialogue the complete file is saved and contains also the binary part.

I've tested this with the same SVG file both on Windows and macOS. When I follow the same documented [export procedure](https://inkstitch.org/docs/import-export/) on macOS both export methods work perfectly and I get complete, intact files.

----

Versions:
- macOS 10.13.6 (High Sierra); Inkscape 0.92.2 5c3e80d, 2017-08-06; Ink/Stitch [dev-build-lexelby-mac-build-mk2 b8dc825, 2018-08-02](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-mac-build-mk2)
- Windows 10 Pro 1703; Inkscape 0.92.3 2405546, 2018-03-11; Ink/Stitch [v1.14.0, d14880d](https://github.com/inkstitch/inkstitch/releases/tag/v1.14.0)

**Comment by lexelby** [comment]
Thanks!  Awesome bug report.

**Comment by tatarize** [comment]
While the header is ascii there is sometimes some actual binary that follows that header for the stitches. Given that header clearly says there's 300 stitches and a reasonable size area can you maybe zip the file and add it here. Also are you using the latest version and was there an error when exporting the corrupted version? If it was given an actual blank pattern it should have written a different header.

I totally get that loading up a file with zero stitches causes a crash on the inkstitch end, but is there also a flaw in my dst (data stitch tajima) writing functions?

**Comment by lexelby** [comment]
It seems really telling to me that Embroider works fine on windows, but File -> Save As -> DST doesn't.  To me that suggests this isn't a pyembroidery bug.  It'd be either an Ink/Stitch bug or an Inkscape bug.

**Comment by tatarize** [comment]
Didn't seem like it would be one of mine, but I've been expecting something and thus far nothing. I tested it all pretty extensively but I still figured something would come up.  Only good responses and even fully functional sew-outs. And no shoes seem poised to drop.

**Comment by lexelby** [comment]
My theory is definitely correct.  Windows is really a pain about converting \n to \r\n.  I'm still working through all of the places where I need to set binary mode -- almost there.

**Comment by lexelby** [comment]
@tatarize Sure, that makes sense, but it wouldn't have helped here.

The output extension has pyembroidery write to a temporary file, then it reads that file and writes it to standard out.  I could of course have had pyembroidery write directly to stdout but then I'd have lost the convenience of the `write()` function, so I decided not to bother.

And even then, stub.py _also_ reads from ink/stitch and prints the result to standard output.  Kind of a mess, but it's the only reliable way I could figure out to hook everything up in windows.

**Comment by tatarize** [comment]
Come to think of it, there's a pretty solid chance that passing it the wrong type of stream will crash anyway. It should take the fact that write is wanting to pass it bytes rather than text and crash. I'll have to double check but, throwing an error is throwing an error. My suggestion there might even be redundant. *shrug*, not my bad either way.
