### ISSUE TITLE
Getting Started with InkStitch

### ISSUE THREAD

**Issue by gwcSoftware** [inkstitch/inkstitch#2580]
New user of InkStitch ver. 3.01 on Windows 11.

I have downloaded and installed InkStitch and have tried to follow the introductory tutorials but I see major differences when running my version of InkStitch and the version in the tutorials.

When I try to verify that InkStitch is installed properly and create a simple circle object and convert it to a path and then activate InkStitch->Params I don't get the same visual stitches as the tutorial shows. I have tried to remove and reinstall InkStitch but still the same results.

![image](https://github.com/inkstitch/inkstitch/assets/6797698/c459b60b-7830-46b6-b3b2-620bdbd005e4)

Would like to know if what I am getting is correct. The resulting realistic visual shows that the circle is not completely filled correctly.

**Comment by kaalleen** [comment]
That looks really wild. Do you still have the svg? It would be easier to say what is going on when we could have a look at it.

**Comment by gwcSoftware** [comment]
Here's the svg.
![gwcInkStitch1](https://github.com/inkstitch/inkstitch/assets/6797698/fb8614cb-f973-4110-afd8-a321c6ee3278)

**Comment by kaalleen** [comment]
Your minimum stitch length is set to 10 mm. This setting deletes of lot of the stitches. If you set this value down (Extensions > Ink/Stitch > Preferences), you will get a less wild result.

**Comment by gwcSoftware** [comment]
Yes, that was the problem. That was the default setting for the svg file. I updated the setting in preferences for the current svg file setting.

Is there a way to have a preferences setting for the Simulator to have default settings for its options. Seems odd that if you start the Simulator to get a Realistic View and the option is not checked for Realistic View.

**Comment by kaalleen** [comment]
Ok good. I'll then close the issue as the initial question is resolved.
For the simulator preferences it would be nice if you open a new issue for that. So it'd be easier for us to keep track of feature requests.
