### ISSUE TITLE
 Incorrect Contour Results in Real Output

### ISSUE THREAD

**Issue by MikeloneD** [inkstitch/inkstitch#2585]
**Description:**

**Expected Behavior:**
When I create contours in Inkstitch and simulate them, the results appear correct and as intended.

**Actual Behavior:**
However, when I attempt to stitch the same contours in real life, the output does not match the simulated results. This discrepancy is causing issues with my embroidery projects.

**Additional Information:**

- I am using Inkstitch version 3.0.1.
- The embroidery machine I'm using is Brother Innov-is 2700.
- I have attached screenshots or photos to illustrate the issue.
- This issue occurs consistently and is not a one-time occurrence.

**Image Parameters Details:**

**Image 1:**

  Satin-Column:

    - Short Stitch Inset: 16
    - Short Stitch Distance: 0.4
    - Zig-Zag Spacing (Peak to Peak): 0.25
    - Pull Compensation Percentage: 0
    - Pull Compensation: 0.2
    - Trim After: true
  
**Image 2:**

  Satin-Column:

    - Trim After: true

**Possible Solution:**
I've tried adjusting various settings and exporting options, but I couldn't resolve the issue. It's possible that there is a problem with the way contours are translated from the simulation to the real output.

Thank you for your attention to this issue. I hope we can find a resolution to this problem as it is affecting my embroidery projects.

Inkscape SVG: 
![akatsuki](https://github.com/inkstitch/inkstitch/assets/79526351/e4bf3e28-df6a-43d1-bf06-7d48d79dded2)

PES FILE for Brother Innov-is 2700:
[akatsuki PES AND SVG.zip](https://github.com/inkstitch/inkstitch/files/13259856/akatsuki.PES.AND.SVG.zip)

Result on T-shirt Photo:
![photo1699193851](https://github.com/inkstitch/inkstitch/assets/79526351/d2929d51-b148-4c1b-bdfc-9b577c396a79)

**Comment by tyrosinase** [comment]
This is not a digitization problem, exactly, but a problem of when the perfect digital world meets the messy real world.

Every stitch pulls a little on the fabric. Satins pull toward their centerline, fills pull in the direction of the fill stitches. It always happens a little, but with inadequate stabilization it happens a *lot*. You have to make sure your stabilizer is drum-taut, and when you have a mushy fabric like t-shirt jersey, you have to make sure the stabilizer is heavy enough to hold against the pull.

Less dense fill helps a little, slowing down the machine helps a little, pull compensation helps a little, but none of it can compensate for a ground that's too susceptible to the stitches shifting it around. T-shirts are very prone to that, and they're not really great candidates for a solid-fill design.

**Comment by MikeloneD** [comment]
Thanks for the reply, I will try to reproduce the same embroidery on a sweatshirt, but I wonder is it normal for that white space to be left between the fill and the satin columns that act as the edges?

**Comment by tyrosinase** [comment]
For certain values of "normal," yup. The fill stitches are actually being made right where the satins go, just like it shows on the screen. They just get pulled inward afterward. Then the satins hit, in the same spot in the *hoop* but now a different part of the fabric has been pulled in to there.

Enough stabilization will stop it, even on T-shirts, but then you end up with a very rigid spot on your T-shirt and most people don't like the contrast, especially if the stabilizer shows through around the edges.

**Comment by MikeloneD** [comment]
Perfect, thank you very much, as soon as I have performed new tests with new fabrics and new stabilizers, I will publish updates on this report
