### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by VicTG68** [inkstitch/inkstitch#2599]
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/object_commands.py", line 38, in effect
![drawing-2](https://github.com/inkstitch/inkstitch/assets/124809828/2d68496c-a543-45f9-b3c8-af31eafa705c)

  File "lib/commands.py", line 397, in add_commands
  File "lib/commands.py", line 350, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by tyrosinase** [comment]
What steps did you do right before this error appeared?

**Comment by VicTG68** [comment]
I traced then went to commands.

**Comment by tyrosinase** [comment]
Thanks. I'm going to close this in favor of #2589 which is the same error, but you can continue to post here if you have more questions.

In the meantime, Troubleshoot will give you a starting place for the cleanup that will need done on this: you'll need to remove all the small fragments, break up the color layers into individual objects (which will eliminate the MultiPolygon message), and repair all the distortions that happened during tracing.

**Comment by tyrosinase** [comment]
Oh! Also you're on 2.2.0, and 3.0.1 should fix the error (though the cleanup will still need done).

**Comment by VicTG68** [comment]
Thank you
