### ISSUE TITLE
(Not an Ink/Stitch issue) svgfont2layers: TypeError: unsupported operand type(s) for -: 'float' and 'str'

### ISSUE THREAD

**Issue by K8ster** [inkstitch/inkstitch#2601]
I've followed the directions using fontforge, created & opened the SVG in inkstitch, but cannot seem to convert the SVG to glyphs. No layers. No glyphs. This is what I get when trying to great the glyphs:

 Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\svgfont2layers.py", line 114, in <module>
    SvgFontToLayers().run()
  File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 250, in run
    self.save_raw(self.effect())
  File "C:\Program Files\Inkscape\share\inkscape\extensions\svgfont2layers.py", line 54, in effect
    guidebase = self.svg.viewbox_height - baseline
TypeError: unsupported operand type(s) for -: 'float' and 'str'

I'm no programmer, but ChatGPT thinks there might be something wrong in the svgfont2layers.py file, specifically in the guidebase calculation. It seems that there's an attempt to subtract a string from a float, which is causing the error.

I've spent 2 hours trying to work through this on my own. I'm at a loss. If I'm doing something wrong, can you help me course correct?

**Comment by kaalleen** [comment]
Would you mind to share your svg font file as it was exported by fontforge?
If this can't be in the public, here is a link where it could go alternatively: https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by lexelby** [comment]
This error seems to be about an extension that isn't actually part of Ink/Stitch, I think?

**Comment by kaalleen** [comment]
Yes, right. Usually it works well on fontforge created files. So I am curious about the file and also we may able to help Inkscape to fix it.

**Comment by kaalleen** [comment]
No further answer. Since this is not referring to Ink/Stitch itself, I'm going to close the issue and hope that this issue may have been reported to the extension authors as well.
