### ISSUE TITLE
Error when applying Select Embroidery Elements

### ISSUE THREAD

**Issue by evilosis** [inkstitch/inkstitch#2605]
Hello.

Newbie here.
I receive the following error when I click Apply on Embroidery Elements.
If I change any of the settings or if I leave at Default and click apply, I get the same error.
I am running InkStitch as Administrator.
Python is installed and working.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\select_elements.py", line 47, in effect
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

File: 
![celtic_02](https://github.com/inkstitch/inkstitch/assets/6816125/62885ae8-f9bf-4aff-a261-aa752ad0b4fe)

I have added an SVG. I can confirm it is the same error on all SVG files that I test.

**Comment by kaalleen** [comment]
Hm, interesting. Did you follow the instructions in the help tab?
Possibly Ink/Stitch is guessing the wrong python path depending on the system settings.

**Comment by evilosis** [comment]
I looked in the help tab but could not find any reference to it, or python in the FAQ or manual.
Do you have any suggestions/pointers on how I can change the python path?

**Comment by kaalleen** [comment]
There is a text field in the select embroidery elements help tab. Enter your python path there.

**Comment by evilosis** [comment]
I didnt realise there was the Help tab in the Elements.
Thank you very much for pointing this out to me.

Worked perfectly. Thanks
