### ISSUE TITLE
Wrong colors in PES export

### ISSUE THREAD

**Issue by LasseSchnepel** [inkstitch/inkstitch#2612]
With my custom palette (see attached), I face the issue that the thread color on a PES export is wrong. At least it has the visually-wrong color both on my brother machine (NV2700) and in Bernina V9 creator. On the machine, a wrong name and wrong number is shown.

When I modify the PES file in Bernina software to have the intended color (RGB values, name and number), the color is shown partly correct on the machine (RGB color and number). Even though the name is still off, I would love inkstitch to put the correct number into the PES file.

Available workaround: Check index of requested color in the sequence and compare with inkstitch's PDF export which has a color list.

[InkStitch Madeira Cotona 30.txt](https://github.com/inkstitch/inkstitch/files/13399372/InkStitch.Madeira.Cotona.30.txt)

**Comment by bianchifan** [comment]
I have no skills with PES, I'm on DST only and there are no color numbers and names.
But when I like to export a PDF, I got mostly random stuff unless i do select the last tab in PDF dialog's setting menu and choose a design->thread color palette.
Same story when I liked to save a design in XXX format.

**Comment by kaalleen** [comment]
Closing in favor of #2668
