### ISSUE TITLE
Auto-route satin doesn't auto-reverse rails

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2615]
At least in the remove-empty-groups release, auto-routing satin doesn't auto-reverse rails, which leads to some really spectacular failures. (As a child of the 70's, someday I'm going to turn off auto-trim and actually stitch out some of the interesting string art.)

**Comment by claudinepeyrat06** [comment]
Thanks for the bug report, but hopefully it was fixed in the fix_cut_satin_for_sided_properties release.
I also loved the psychedelic look the bug created...

**Comment by tyrosinase** [comment]
Ohhhhh, somehow I thought that was already incorporated in the release I'm using. I shoulda checked. (Actually now that I think about it, maybe it came up on the laptop, which is on a slightly different release than the desktop I usually use.)

**Comment by tyrosinase** [comment]
Ohhhhh, somehow I thought that was already incorporated in the release I'm using. I shoulda checked. (Actually now that I think about it, maybe it came up on the laptop, which is on a slightly different release than the desktop I usually use.)
