### ISSUE TITLE
PROBLEME INSTALLATION INKSTITCH 3.0.1 SUR MAC SOMONA PUCE M1

### ISSUE THREAD

**Issue by Kro1309** [inkstitch/inkstitch#2616]
Bonsoir, 

Je possède un macbook Somona M1 et je ne parviens pas à installer  inkstitch 3.0.1 sur mon Mac.
J'ai pourtant installé Rosetta sur le terminal puisque cela peut être une des causes de l'échec de l'installation d'inkstitch.

Je suis parvenue à installer Inkscape 1.3 que j'ai ouvert.

Lors de l'essai de l'installation de Inkstitch 3.0.1, ce dernier commence l'installation des fichiers puis annonce un message expliquant qu'il fallait installer au préalable Inkscape et l'ouvrir... Chose faite mais pour autant ce message s'inscrit à chaque tentative d'installation...

Je vous remercie par avance de l'aide que vous pourrez m'apporter.
Cordialement
Mme Hanquez Caroline

**Comment by kaalleen** [comment]
Hm, do you possibly have Inkscape installed to an unusual location?

You could also install Ink/Stitch from the zip file if the installation fails: https://inkstitch.org/docs/install-macos/#installation-fails

**Comment by kaalleen** [comment]
@Kro1309 could you solve your installation issue?
