### ISSUE TITLE
Invisible files/unrecognised files 2 - Janome 15000

### ISSUE THREAD

**Issue by tspisak139** [inkstitch/inkstitch#2621]
The JEF file I just created will not show up in the directory on my USB stick.  Any suggestions?

I created my larger Inkstitch file and saved as JEF to USB.  I have a short filename (under eight characters and no spaces or special characters).  Files was originally 300x250 mm and I shrunk that down to 250x50mm to see if the overall size of the file is too big.  I can read one of my older files that I made/embroidered for a 500e in the same folder on the USB stick.

My older EmbroideryEditor software from my 500e doesn't have the larger hoop sizes so I can't see if the JEF file has any issues.

Rename txt to .jef if you'd like to see if you can open the file.

v1.31.1 Inkscape
v3.0.1 Inkstitch

![canik](https://github.com/inkstitch/inkstitch/assets/54811661/77ee22d5-5b19-4bfe-aa61-b787d02a7bd4)
[canik -jef.txt](https://github.com/inkstitch/inkstitch/files/13537730/canik.-jef.txt)

**Comment by bianchifan** [comment]
1st... 
Did you name your design canik.jef  or  canik.-jef, last one wouldn't be recognized.

2nd... 
My inkscape reads your design perfectly.
But some of my Android apps do not, your design does not fit any known Janome hoop.
It should be rotated by 90°.

**Comment by tyrosinase** [comment]
It's 9x12, not 12x9 -- Janomes won't auto-rotate a design to fit the hoop.

**Comment by tspisak139** [comment]
I just tried a jef rotated 90° and no luck.  Image is only 2x9 (50x250).  Do properties of Inkscape file need to match a hoop or just smaller.  I tried 23x30cm and 30x23cm properties with the logo rotated and centered in the field. File name never showed up on the display in the directory.  

An old file does show up in the folder on USB.  Do you need to save the file with a certain units of measure (px)?

**Comment by tyrosinase** [comment]
No, it actually doesn't even care what the page size is, only the embroidery-part size (if you reopen the raw stitch file you will see that the page is resized to the stitching; that's purely at the Inkscape end of things, not saved in the stitch file - at least, not for JEF files). Likewise it doesn't care about units of measure.

Are you saving them to the EMB directory/folder? The machine only looks there.

**Comment by kaalleen** [comment]
@tspisak139 did this help to solve your issue?

**Comment by tspisak139** [comment]
We finally figured it out.  The 15000 doesn’t just display all the file names and then tell you that the design selected doesn’t fit in the current hoop. Selecting the largest hoop and then for some odd reason, goto the 2nd page, the file shows up.

thanks for you help and for posting the videos that got me started.

**Comment by kaalleen** [comment]
Great, thank you for your feedback :)
