### ISSUE TITLE
macOS Ventura: InkStitch won't open on computer

### ISSUE THREAD

**Issue by jerrikasterling** [inkstitch/inkstitch#2631]
I am trying to add the InkStitch extension and I'm on a Mac running Ventura. I've tried downloading all of the different versions of inkstitch and none work. Whenever I try to change the location save it in Inkscape, I receive an error code. Even when I download it to my computer, I can't get it to open at all. When I try to go to extensions>ink/stitch>visualize and export, nothing happens at all. I'm not sure what I should do.

**Comment by Marif91** [comment]
Quel processeur avec ventura ?
J'ai Ventura et un processeur M2. Pour que cela fonctionne, j'ai installé Rosetta.

**Comment by kaalleen** [comment]
Can you post your error code?

**Comment by kaalleen** [comment]
@jerrikasterling could you solve the issue?
