### ISSUE TITLE
Installation issue (macOS Ventura)

### ISSUE THREAD

**Issue by lyndanorgaard** [inkstitch/inkstitch#2633]
Inkstitch failed to install on my MacbookPro, it may be because I am running Ventura and I did not see that OS on your list, (possibly too new). Do you have an updated version for Ventura?

**Comment by tyrosinase** [comment]
I am not a Mac person so disclaimer: I am just saying words I've seen before without really knowing what they mean, AI-style. :zany_face: 

That said: Ink/Stitch on Ventura requires the installation of Rosetta.

**Comment by Marif91** [comment]
Je confirme, sur Ventura pour obtenir l'ouverture des fenêtres il faut installer Rosetta. La procédure est décrite sur i
inkstitch.org

**Comment by kaalleen** [comment]
The Monterrey version should work for Ventura.
@lyndanorgaard did this help to fix your issue (https://inkstitch.org/docs/install-macos/#inkstitch-doesnt-run--is-greyed-out)?
