### ISSUE TITLE
letters to font: lxml.etree.XPathEvalError: Invalid predicate"

### ISSUE THREAD

**Issue by 63patti** [inkstitch/inkstitch#2634]
I have letter files in JEF but get stuck every time I try to convert them to font in the "letters to font" tool.  when i hit "apply" i get the following error message, despite following Low Tech Linux's instructions to a tee.  I have tried to do it on my old Macbook, this new macbook and a pc and none have worked.

"Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and.            (I don't have an SVG file for my letters, they are JEF)
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/letters_to_font.py", line 43, in effect
  File "lib/extensions/letters_to_font.py", line 76, in get_glyph_element
  File "inkex/elements/_base.py", line 435, in xpath
  File "src/lxml/etree.pyx", line 1597, in lxml.etree._Element.xpath
  File "src/lxml/xpath.pxi", line 305, in lxml.etree.XPathElementEvaluator.__call__
  File "src/lxml/xpath.pxi", line 225, in lxml.etree._XPathEvaluatorBase._handle_result
lxml.etree.XPathEvalError: Invalid predicate"

**Comment by kaalleen** [comment]
Interesting. Definitely a bug in Ink/Stitch and nothing you are doing wrong. I heard here and there that people had problems with the letters to font tool, but couldn't get hold of a file which was causing the issue and therefore no fix could be found yet.
If you could send your zipped font files (jef is ok) that would be a great help.
If you cannot upload them here for copyright reasons, you can upload it here https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by 63patti** [comment]
Hi Kaalleen,

I am not terribly computer literate so I know what a zip file is but i
don't know how to make my folder with my files in it into a zip file.  I
tried to upload the folder to the link you gave me but it actually uploaded
all the files individually.  I'm not sure how to cancel it.  I'm sure
that's not what you wanted me to do. I'm so sorry about that.  Hopefully
you can work with them though to help me.  The files are the font "cookie 1
inch"

just some more info, I prepared more than one font in the appropriate
format and none of them worked.

Thanks very much,
Patti

**Comment by kaalleen** [comment]
Thank you so much for uploading your letters. No problem with uploading the individual files. We can handle this.
I can import them though without any issues.

I think though, that your upload process might have fixed the issue for me :D This is because I see a potential issue in the name of the doublequote file. Was the orginal name of that file something like quotedbl_".jef ?

If so, in order to make it work, remove the " (rename to quotedbl_.jef) and then use the letters to font tool.
Rename the _ glyph to " afterwards.

**Comment by 63patti** [comment]
I will give that a try. I noticed on my end that not all the letters
uploaded so there may be some more issues. I will report back once I've had
a chance to fix the quote one.

Patti

**Comment by 63patti** [comment]
Hi Kalleen,
I tried your suggestion and it didn't work however I looked at some other
letters and symbols and cleaned them up in the same manner.  That didn't
work either so I removed the questionable symbols and tried again.
That didn't work either however I have less errors:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\letters_to_font.py", line 64, in effect
UnboundLocalError: local variable 'group' referenced before assignment

I uploaded the remaining files in my calibri 1 inch folder for you to look
at.

FYI. on my pc computer at one time actually got to the glyph stage but
that's as far as I could get before running into an error. Now those are
all gone and I can't get back to that step, which brings me to the problem
I am currently discussing with you.  On my Mac I have never been able to
get past the "letters to font" stage.

Thank you for your commitment to Inkstitch and to helping users be
successful.

Patti

**Comment by kaalleen** [comment]
This may be a stupid question, but did you choose jef as a file format?

**Comment by 63patti** [comment]
Lol, I bought the files as jef files.  That's not a stupid question.  I was
wondering if the jef format was the problem too.

**Comment by kaalleen** [comment]
So does it work when you set it to jef in the letters to font extension?

**Comment by 63patti** [comment]
No, on my Mac, which is brand new, it won't make the letters to font i.e I
don't get any glyph layers. I just get the error messages I sent you.

On my old p.c. I managed to get glyph layers and got to the json level but
then at some point got errors. That was a few months ago and I didn't reach
out for help at that time. I haven't been able to recreate that since
attempting to do it again last week.

I want it to work on my mac. So I'd like to focus on that. I am going to
reach out to the company I bought the font from and ask them to send me a
different format, perhaps pes, if you don't think you can help me with the
jef format.

I really appreciate you helping me though. Thank you.

Patti

**Comment by kaalleen** [comment]
I didn't mean that jef is problematic. I was just asking if you set the file format option in the letters to font tool to jef. Otherwise it won't find any matching files.

![letters-to-font](https://github.com/inkstitch/inkstitch/assets/36401965/d2ae415d-c04d-4e57-aab4-8f654ca45061)

**Comment by 63patti** [comment]
oh, yes, i did choose JEF.

**Comment by 63patti** [comment]
[image: Screenshot 2023-12-16 at 3.26.22 PM.png]


This is a different font than I was sending previously but the same
issues.  This is what my screen looks like when I try letters to font.

**Comment by 63patti** [comment]
and this is where i'm getting my  files from on my desktop
[image: Screenshot 2023-12-16 at 3.30.42 PM.png]

**Comment by kaalleen** [comment]
Oh ok, I see. Uploading images per mail doesn't work on GitHub. I'm afraid you'll have to login for that.

**Comment by 63patti** [comment]
<img width="1512" alt="Screenshot 2023-12-16 at 3 26 22 PM" src="https://github.com/inkstitch/inkstitch/assets/140123937/a8764270-9779-48ee-bc0f-8c03497aa079">
<img width="1276" alt="Screenshot 2023-12-16 at 3 30 42 PM" src="https://github.com/inkstitch/inkstitch/assets/140123937/fd2fd377-2037-4c28-9c51-ac0aff135d78">

**Comment by kaalleen** [comment]
Oh I see. Glad you send the error message along. It is an other error message. Is this the build for older macos systems? Looks like we didn't update inkex before the release for that one then.

**Comment by kaalleen** [comment]
(If this is for older macOS test if this works for you: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kall-test
Grab the file named inkstitch-231218.pkg 
As usual builds for older macOS systems are not signed and need this extra step: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by 63patti** [comment]
I tried the suggestions for my older macOS with no luck.  I got the same type of errors.
 I'm running Catalina on my old mac and I think maybe the file you linked is for an older operating system.

**Comment by kaalleen** [comment]
So sorry I had you test this. I should've tested this before. It still had the old inkex in there.
Ok, how about this version here?
https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-escape-label-names/inkstitch-20231228.pkg

**Comment by kaalleen** [comment]
I just noticed this got closed through merging a pull request related to this issue (a fix for the initial error where it failed on files with special chars). You can still answer in this thread. If that's inconvenient for you, feel free to open a new issue.

**Comment by 63patti** [comment]
Thanks Kaalleen, I thought you gave up on my issue. I haven't had a chance
to test your last link because I'm travelling and don't have my old MacBook
with me. Just my new one. I will return at the end of the month and will do
it then. I am looking forward to the new link being a solution, even if
it's not on my new MacBook.

Stay tuned...

Patti

**Comment by 63patti** [comment]
Hi Kaalleen,

I finally had a chance to use this link you provided on my new MAC and it
worked!  I was able to get all the way to Json and I can see the name of my
font in the lettering list.
When I type out a word it shows up in my new font however when I try to
"simulate/realistic preview" so that I can make a preview of the font for
the list nothing happens.  I can see the word and highlight it but the
simulation screen doesn't open up.
Any suggestions?

**Comment by kaalleen** [comment]
I'm afraid this is an issue of current dev releases. We are on to it. At the moment I'm afraid I can't tell you which other version to test, since we need to fix the build system.

**Comment by 63patti** [comment]
Okay, I will wait patiently.  I have discovered that the problem isn't with
my new font.  Since adding the link you sent the simulation isn't working
at all, even on older designs that previously had no issues with
simulation/preview in inkstitch.

Thank you for your perseverance helping me with my fonts :)
