### ISSUE TITLE
shapely 202: parallel_offset / offset_curve self intersection behavior

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#2660]
Just a note so we won't forget...

Shapely 2.0.2 uses geos 3.11 which isn't very well suited for convert line to satin and possibly other Ink/Stitch features.
Geos 3.12 will fix this for us. So we just have to wait for a shapely update.

Reference issue: https://github.com/libgeos/geos/issues/816

**Comment by lexelby** [comment]
I added a comment to that geos issue explaining our use case.  No idea if it will be useful to any of them but I figured it was worth a try :)

**Comment by kaalleen** [comment]
I could be wrong, but I think they already implemented it. Now it is on shapely to bring it to us.
