### ISSUE TITLE
Makefile:8: *** "No inkscape in PATH, consider installing it".  Stop.

### ISSUE THREAD

**Issue by louisgoldean** [inkstitch/inkstitch#2661]
I don't know how to fix this

**Comment by tyrosinase** [comment]
Ink/stitch is a plug-in for Inkscape (https://inkscape.org) and won't run without it. That's it saying it can't find it, so the first question is: have you installed it?

If so, the next step is finding out why it isn't in the path, and making sure Ink/stitch can properly find it: what were your installation steps?

**Comment by lexelby** [comment]
I'm not sure what Makefile generated that message, but it wasn't ours. Running `make` isn't part of installing Ink/Stitch.  What are you trying to do?
