### ISSUE TITLE
Problem with Satin Stitch

### ISSUE THREAD

**Issue by justandywu** [inkstitch/inkstitch#2662]
Hello, I don't know why this is happening but normally I don't have any issues with satin stitches, but for some reason my project right now is having these weird "fill/stroke" stitches when I'm trying to do satin stitches... I can't figure out why it won't work. I tried reversing my rungs, but nothing works.

![image](https://github.com/inkstitch/inkstitch/assets/8253155/6351759f-3e7a-4415-9783-ad44c24cb8ab)

**Comment by tyrosinase** [comment]
That looks "normal" for a very tiny object, did you mean to make it that small? A satin smaller than half a millimeter wide will look like that in preview.

**Comment by justandywu** [comment]
ohhh ok yeah you're right. It's definitely because my design is so small. I didn't realize it had gotten that small in the details! Thanks!

**Comment by tyrosinase** [comment]
Excellent! I've done that too, usually in other direction: not noticing my ruler was in cm and not mm until I went into a preview and was like "whyyyy is the stitching so dense?!"
