### ISSUE TITLE
Command line zip file creation throws error if no formats are specified

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2663]
Is it possible to create the Ink/Stitch zip file from the command line? I've poked around in the Inkscape docs but AFAICT it bases it on the extension, and choosing .zip triggers the native SVG+media compressed file.

(update: found a bug, it's further down)

**Comment by tyrosinase** [comment]
Maybe, I thought, I could just export each individual file type and then zip them all up manually but nope, the threadlist export also gets overridden by a different .txt. So close!

**Comment by tyrosinase** [comment]
Oh, thank you. I think you've mentioned this before, and I just couldn't find it with a search. Hopefully my subject line will be more clear to Future Me next time.

**Comment by kaalleen** [comment]
It's on the website now: https://inkstitch.org/docs/command-line/

**Comment by tyrosinase** [comment]
I have discovered a bug: if you don't select any formats as true (because you're hoping that'll do them all without you having to enumerate them on the command line), it throws an error: 

`Ink/Stitch Version: initial (linux)

Traceback (most recent call last):
  File "inkstitch.py", line 85, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/zip.py", line 88, in effect
AttributeError: 'Zip' object has no attribute 'errormsg'
`

It would be nice to not have to enumerate them, but it probably shouldn't throw an error if there aren't any.

**Comment by kaalleen** [comment]
That makes a lot of sense. I would suggest we change the command line zip export defaults to True and you'll have to set the ones you want to exclude to False. I think that you'd usually use the zip export to export many files at the same time and it seems to be a lot of work to have to write down all file formats when you simply want them all.

**Comment by tyrosinase** [comment]
Maybe not default to true, but default to all if none are specified?

(Either way works for me, I just feel like the latter is more expected.)

**Comment by kaalleen** [comment]
Hm, I'm not sure if this wouldn't be a bit unexpected for the gui part of the extension. If you do not select any of the listed file formats.

**Comment by tyrosinase** [comment]
True, the GUI should do something different. (Not sure what. What would people expect if nothing at all was checked?)

**Comment by kaalleen** [comment]
Hm, I cannot distinguish the two methods later in the process. We can only set different initial values if required.

**Comment by kaalleen** [comment]
> Not sure what. What would people expect if nothing at all was checked?

I suppose they should be informed that they need to select something?

**Comment by tyrosinase** [comment]
That's kind of my thought. So long as there's no logical reason to uncheck everything the GUI should balk at that point, so the only way to reach the "nothing is selected so everything should be put in the ZIP" point is via the command line.

**Comment by kaalleen** [comment]
Error message is fixed. Let's keep the defaults settings as is.
