### ISSUE TITLE
Fill to Stroke failing on certain filled strokes

### ISSUE THREAD

**Issue by BearOfTheSeas** [inkstitch/inkstitch#2675]
Hi, I'm attempting to use the fill to stroke on a number of linear fills in a file I found online, most are working perfectly but a minority are failing with the following error even though they are not discernibly different in width, complexity, etc from the objects that are working. The attached file contains two of these objects, attempting fill to stroke on either with the settings in the screenshot should reproduce the error.

Ink/Stitch Version: remove-old-troubleshoot-layer (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 85, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/fill_to_stroke.py", line 70, in effect
  File "lib/extensions/fill_to_stroke.py", line 128, in _get_centerline
  File "lib/extensions/fill_to_stroke.py", line 148, in _get_voronoi_centerline
  File "shapely/ops.py", line 218, in voronoi_diagram
AttributeError: 'NoneType' object has no attribute 'geom_type'

![petal 5](https://github.com/inkstitch/inkstitch/assets/45858319/4cbf2bac-98e0-4bef-923c-decc684e88bb)

<img width="462" alt="Screen Shot 2024-01-07 at 7 00 20 PM" src="https://github.com/inkstitch/inkstitch/assets/45858319/4c143861-fbc3-4560-8717-c4153f1e8543">

**Comment by kaalleen** [comment]
Oh nice. Thank you so much for posting this issue. Definitely a bug we need to fix.
In the meantime you can utilize `Tools: Fill > Break apart fill objects` to fix the issue on your side.

**Comment by BearOfTheSeas** [comment]
Thanks so much! While we're on the subject of fill to stroke, it would be really useful if the original object name was inherited by the resulting path (for one to one conversions, which should ideally not create a group at all) or by the resulting group (for one to many conversions.) Ideally this should be inherited as "objectname centerline" or similar when keep original is selected and simply "objectname" when it is not. I realize this is a bit picky but I think it would make the tool much more user friendly, especially when operating on large numbers of objects.
