### ISSUE TITLE
Freeze while saving .pes

### ISSUE THREAD

**Issue by Betansus** [inkstitch/inkstitch#2676]
Hi! When I try to save a file in my Brother .PES format the program freeze

Inkscape 1.3.2 (091e20e, 2023-11-25, custom)
InkStitch 3.0.1
Windows 11 Pro Versión	22H2

Thank you!

**Comment by kaalleen** [comment]
Can you give us more information? Does it only freeze on the export of specific designs? If so, it'd be great if we could have a look at the svg. Does it freeze on other Ink/Stitch features as well?

**Comment by tyrosinase** [comment]
Are you saving to removable media by chance?

**Comment by Betansus** [comment]
Hi! I was finaly able to save after restarting (in the original post I was using a recently instaled version), the only I can say is that I could save .svg normaly, only .pes failed. I will keep updating if I find something new. Thanks a lot!

**Comment by Betansus** [comment]
> Are you saving to removable media by chance?

no, local drive

**Comment by kaalleen** [comment]
Any success to pes already? Without a file it's difficult to help though.

**Comment by Betansus** [comment]
> Hi! I was finaly able to save after restarting (in the original post I was using a recently instaled version), the only I can say is that I could save .svg normaly, only .pes failed. I will keep updating if I find something new. Thanks a lot!

Now I Can. Thank you!
