### ISSUE TITLE
Autofill goes past underlay and causes breaking lines

### ISSUE THREAD

**Issue by IORoot** [inkstitch/inkstitch#2680]
Getting a missing stitch line at the bottom (or top) of a fill. Tried everything to fix.

So, the details:

- Using a Brother F440E.
- Yes, using stabiliser.
- I've tried changing the following settings:

1. Moving the start / stop positions of how the embroidery happens in ink/stitch.
2. Added 'expand' on the thread by 0.1mm
3. Changed the tensions on the machine. from 0.0 to 9.0
4. Changed the angle of the embroidery - this works, but the 90degrees makes the fill look weird.
5. Changed stitch length.
6. Changed row spacing.
7. Added a satin border outline.
8. Changed sizes.
9. Changed settings to the underlay.
10. Tried legacy fill (which actually does get rid of the issue)
11. Tried contour fill.
12. Made the dimensions of the graphic slightly shorter / taller.
13. rescaled the graphic to be smaller.
14. Rotated the design
15. Added -0.2 expand to the underlay - this sort of works, but it expands in all directions and then makes everything else messy.

Whatever I try, I just cannot get rid of the missed stitch lines at the top of the design. Every time I do it there's a small gap at the top (or bottom if I change the direction of the embroidery in ink/stitch).

What am I doing wrong? Why is there this missed lines every single time?

I've checked the stitches in the preview of ink/stitch and there's nothing to show that it's missing anything.

Just to be clear - I've added a start and stop point on all the attempts. Either from bottom to top, or top-to-bottom. There is no 'join' where it stops, moves to the other end and comes back. 
The machine just goes fully one way for each side.

My thought is that the fill is going a few lines PAST the underlay and those two or three lines make a small gap. However, I don't know if I can extend the underlay in one direction?

Any help appreciated!

![IMG_4606 Large](https://github.com/inkstitch/inkstitch/assets/8770616/5e2b6c54-5313-4e4b-8050-23762f56afc8)

![IMG_4607 Large](https://github.com/inkstitch/inkstitch/assets/8770616/c3f0bfbd-a2d7-479c-8e60-4afa3eca241d)
![IMG_4608 Large](https://github.com/inkstitch/inkstitch/assets/8770616/c30df000-e31a-4ea1-966a-4c4479392dda)
![IMG_4609 Large](https://github.com/inkstitch/inkstitch/assets/8770616/f753be4e-ce9b-4203-b824-feb0c7e7850c)
![IMG_4610 Large](https://github.com/inkstitch/inkstitch/assets/8770616/7dac4834-44da-4f02-bd02-dce6fb5c095c)
![IMG_4611 Large](https://github.com/inkstitch/inkstitch/assets/8770616/cc78cd74-a124-463e-913b-9debf25b78b9)
![IMG_4603 Large](https://github.com/inkstitch/inkstitch/assets/8770616/de346ccb-5ad3-4660-8d7f-9e21198b4e61)
![IMG_4604 Large](https://github.com/inkstitch/inkstitch/assets/8770616/40756c64-3388-4b1a-a948-c34eb8a3cf6f)
![IMG_4605 Large](https://github.com/inkstitch/inkstitch/assets/8770616/7a389c45-7c31-47b0-b722-a099519b2c9e)

![IMG_4612 Large](https://github.com/inkstitch/inkstitch/assets/8770616/68d9e472-ad02-43e0-9716-a00d6dcd02b9)
![IMG_4613 Large](https://github.com/inkstitch/inkstitch/assets/8770616/518aa2a2-612b-4dbe-887e-8ae8b7123ed8)
![IMG_4614 Large](https://github.com/inkstitch/inkstitch/assets/8770616/b1832241-8354-4b99-b33d-aad06eda1b40)
![IMG_4615 Large](https://github.com/inkstitch/inkstitch/assets/8770616/0842bcdf-7d8a-4f08-a15a-5ffb2113460b)
![IMG_4616 Large](https://github.com/inkstitch/inkstitch/assets/8770616/f5b6951a-81da-4609-bb30-f7f50d321577)

**Comment by kaalleen** [comment]
> I don't know if I can extend the underlay in one direction?

Yes, you can set the underlay inset to a negative value.

Can we see your the svg file?

**Comment by IORoot** [comment]
Hi kaalleen, thanks for the response.
I've had a little bit more success with the 'End Row Spacing' setting - but still not completely gone. The negative value for the underlay didn't change the outcome unfortunately - I tried with a few increasingly larger values to no avail.

However, the latest file I've created has it's start on the right part of the logo, working from top to bottom, and then the left part of the logo working upwards from bottom to top.
![logos_50mm_x_26mm_1_6_stitch_1_8_rows_2_2_ends](https://github.com/inkstitch/inkstitch/assets/8770616/cdaca82a-4e44-4e91-935c-0bdd3272a1d8)

Interestingly, with this setup of the stitching, it seems that the fill is going past the underlay by a couple rows at the bottom of the right hand logo section and at the top of the left section. Which leads me to suspect that the fill is just going past what it should at the very end of the object. However, I'm just guessing here.

I've added a 2.2mm end stitch to this file, that has mitigated some of it, but I still need to experiment to get rid of those lines.

**Comment by lexelby** [comment]
It's all about distortion.  Knit fabric is really the worst-case scenario, is so stretchy, so it stretches when you hoop it and it distorts during sewing.  Ink/Stitch is faithfully filling the shape as you defined it, and the machine is properly sewing the design, but the fabric shifts underneath it during sewing.

Can I recommend iron-on stabilizer?  It does wonders for knits. You'll still get some distortion but it will be much less severe.

**Comment by kaalleen** [comment]
I think here is an interesting lesson to learn. Smaller row spacing values do not necessarily lead to more coverage, but in any case to more distortion. On knit, always try to reduce your stitch count as much as possible. Also your stitches are relatively small. Increase stitch length and also increase your row spacing. You can reach more coverage and less distortion through better underlay. Just for the fun of it, try this modified svg (you don't have to go as crazy as that with the underlay, but I think it could be interesting to see): 

![2680_modified](https://github.com/inkstitch/inkstitch/assets/36401965/6983a984-ac37-4035-a456-b496df18622d)

**Comment by IORoot** [comment]
Kaalleen, thank you so much, that came out so much better than my attempts. 

So, just to make sure I understand and clarify. The problem was that:

1. I didn't have enough underlay, so you've added three layers of underlay (90, 45, -45) with a bigger row spacing (1.2mm) and some inset (0.3mm) to compensate any pull.

2. I was stitching too finely and you've increased the stitch length to (3mm) and increased row spacing to 0.3mm

Again, thank you so much - I've definitely learnt something here. I was making things finer, smaller and more detailed to try to find the problem and that wasn't necessary at all.

See below the result:

![IMG_4678 Large](https://github.com/inkstitch/inkstitch/assets/8770616/af22fc2a-f62c-4362-9a6b-a2f8b9fcbeda)

**Comment by IORoot** [comment]
Closed and solved by https://github.com/inkstitch/inkstitch/issues/2680#issuecomment-1896232802.
