### ISSUE TITLE
How to build Ink/Stitch for 64-bit Windows?

### ISSUE THREAD

**Issue by gwcSoftware** [inkstitch/inkstitch#2687]
### Discussed in https://github.com/inkstitch/inkstitch/discussions/2686

<div type='discussions-op-text'>

<sup>Originally posted by **gwcSoftware** January 14, 2024</sup>
I’ve been interested in trying to build Ink/Stitch for 64-bit Windows and would like to know if the current documentation for the manual build is the one to use. Any info to get started is appreciated.</div>

**Comment by kaalleen** [comment]
Recent development versions do have a windows 64-bit version attached. Latest release was still build on 32-bit only.

The build instruction for Windows is a bit outdated but still usable, while the manual install instruction for Windows is terribly outdated and needs an update. It is basically the same though and you could run `make manual` in case you prefer a manual install instead of building it.

**Comment by gwcSoftware** [comment]
Well, I tried following the manual build instructions and got as far as the requirements.txt for Ink/Stitch. I got the following errors:

$ python -m pip install -r requirements.txt
Collecting inkex@ git+https://gitlab.com/inkscape/extensions.git@b38c022b0394c7eb665c4a0927b226d2f5840fad (from -r requirements.txt (line 2))
  Cloning https://gitlab.com/inkscape/extensions.git (to revision b38c022b0394c7eb665c4a0927b226d2f5840fad) to c:\users\gilcl\appdata\local\temp\pip-install-tyyh4cx2\inkex_b7ecc77ccf3a4faa9fb60aabc1cd950e
  Running command git clone --filter=blob:none --quiet https://gitlab.com/inkscape/extensions.git 'C:\Users\gilcl\AppData\Local\Temp\pip-install-tyyh4cx2\inkex_b7ecc77ccf3a4faa9fb60aabc1cd950e'
  error: unable to create file tests/data/refs/render_barcode_qrcode__--text__Blue__Front__Yard__--typenumber__3__--correctionlevel__1__--modulesize__10__--drawtype__smooth__--smoothness__greedy.out: Filename too long
  fatal: unable to checkout working tree
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://gitlab.com/inkscape/extensions.git 'C:\Users\gilcl\AppData\Local\Temp\pip-install-tyyh4cx2\inkex_b7ecc77ccf3a4faa9fb60aabc1cd950e' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://gitlab.com/inkscape/extensions.git 'C:\Users\gilcl\AppData\Local\Temp\pip-install-tyyh4cx2\inkex_b7ecc77ccf3a4faa9fb60aabc1cd950e' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

gilcl@gwcAsusTufLT MINGW64 /d/InkStitch/inkstitch (main)
$ git status
Refresh index: 100% (979/979), done.
On branch main
Your branch is up to date with 'origin/main'.

**Comment by gwcSoftware** [comment]
It’s been awhile, so I’m rusty at my programming skills and I don’t normally mess with opensource projects! Always run into issues like this where things are out of date and spend more time getting set up to build than working on the project! If you have a working build for Windows 64-bit, then why not post it so that others can experience the project instead of dealing with getting all the dependencies together for building!

**Comment by kaalleen** [comment]
Sorry, I can't read minds. It would be easier to help if you speak about your purpose of building Ink/Stitch. If you just want to run Ink/Stitch on your computer, why not use 32bit official release. This should work perfectly well.

**Comment by gwcSoftware** [comment]
Well, If I want to add some features or just learn how to add something, I guess I would need to rebuild it wouldn't I! But, if you want to keep it secret, that's ok. I'll look for something else! I already have Ink/Stitch installed, that's why I am interested in maybe adding something to it!

**Comment by kaalleen** [comment]
> If you have a working build for Windows 64-bit, then why not post it so that others can experience the project instead of dealing with getting all the dependencies together for building!

This sentence made me assume you just wanted a pre-build 64bit version, which wouldn't be helpful for development at all. I'm not here to hide any secrets from you or any one else and I'd love if we could talk about your issue a bit more politely. We all put our free time into the projects and I like to spend my free time peacefully. Please bare with me if I am not able to keep everything up to date all the time. But here you go: http://localhost:4000/developers/inkstitch/windows-manual-build/

**Comment by gwcSoftware** [comment]
Ok, I’m sorry that I didn’t understand your reply about not being able to read minds. I thought that by stating that I would like to know how to build a Windows 64 bit version was pretty straight forward about what I needed. You wanting to know my purpose seemed to be too invasive as to why. 

Thank you for the link, I will try it out.

**Comment by gwcSoftware** [comment]
Ok, I didn't notice that the link provided is to your localhost device.

I cannot access the info.

**Comment by gwcSoftware** [comment]
Thank you for updating the manual build instructions. I have successfully built the project.

There are a few issues I'm trying to sort out. 

The first is in the build process right at the end where it tries to use 7Zip to compress the files, it indicates it can't find 7z. Initially, I didn't have 7Zip installed but after installing 7Zip, I still get the same error.

======
Successful compile (110.391 sec). Resulting Setup program filename is:
C:\Users\gilcl\AppData\Roaming\inkscape\extensions\inkstitch\win\inkstitch.exe
Creating zip
bin/build-windows-installer: line 29: 7z: command not found
make[1]: Leaving directory `C:/Users/gilcl/AppData/Roaming/inkscape/extensions/inkstitch'

=========


The second issue is after installing the Ink/Stitch , I am getting multiple duplicate menu entries when activating Ink/Stitch extension in InkScape. I did remove the previous version of Ink/Stitch as recommended.

I have even removed Ink/Stitch and InkScape and re-installed both and still get the multiple entries.

Also, besides the multiple duplicate menu entries, most all the entries are grayed out.

Just wanted to update, I am still working to resolve these multiple entries.

**Comment by kaalleen** [comment]
Thank you for the feedback. I understand that everything is working now?
I added a comment about 7zip and not to install the newly generated build when you have manual install in the extensions folder.

**Comment by gwcSoftware** [comment]
Yes, I am able to build and install. Haven’t tested fully but ok for now .

**Comment by gwcSoftware** [comment]
All is ok, was able to build for Windows x64.
