### ISSUE TITLE
Several problems when trying to run on Mac

### ISSUE THREAD

**Issue by fabulousrice** [inkstitch/inkstitch#269]
I have downloaded **Inkscape** just so I could attempt to run **Inkstitch**. 

However, as [many Inkscape users have pointed out](https://artplusmarketing.com/gimp-and-inkscape-on-retina-macs-do-not-work-9601c3052e86?gi=633f7b9461d3), Inkscape just "doesn't work" properly on recent Mac computers, especially on retina screens, and it's been the case since 2013 when Retina screens appeared.

On top of that, I have been getting what looks like error messages whenever I tried to follow Inkstitch tutorials (see image attached).

I would love to be able to help, but my conclusion at the moment is that to properly reach more users (and a lot of designers use Macs...), Inkstitch should run as an add-on on other more popular and less buggy vector software like Illustrator or even Blender.

![screen shot 2018-08-09 at 12 10 45 pm](https://user-images.githubusercontent.com/16789615/43972955-e9b873ec-9c8a-11e8-9c7e-db27b199ccfe.png)

**Comment by lexelby** [comment]
I'm sorry you're having trouble!  From that screenshot, it looks like you found a bug in Ink/Stitch itself, rather than Inkscape.  If you could copy and paste the contents of that top window (the traceback), that would really help us understand what went wrong and fix it.

**Comment by lexelby** [comment]
Closing for now, but if you have a chance to paste in that error message, we can definitely reopen this.
