### ISSUE TITLE
Params And Realistic Preview Won't Work At All

### ISSUE THREAD

**Issue by elifeasj** [inkstitch/inkstitch#2690]
Hey!! does anyone have problem wtih inkscape 1.3.2.... the version will not run inkstitch 3.0.1 the params or the realistic preview wont work or show up... the loading page will just show up and then nothing will happen if I don't force quit the application. When it comes to saving files in .jef the program will load the saving page and then nothing will happen it will get stuck...... I can't even save on a .jef file, only svg...
The applications runs on my MacOS Sonoma.

Can anyone help? :(

**Comment by elifeasj** [comment]
https://github.com/inkstitch/inkstitch/assets/90379003/d8fdf8d4-ba10-4494-8547-ba239001b151

The video link is here to see the problem..

**Comment by kaalleen** [comment]
Your design is pretty big. This will take a lot of time to calculate. Just to verify your system is working...
Can you create a new file and just draw a simple line, select it and run params or the simulator?

I'd recommend to set the page size to the size of the hoop you intent to use always as a first step. If you use Inkscape mostly for embroidery you could even setup a template to always begin with a good page size: https://inkstitch.org/docs/customize/
When you want this to become your default template, save it with the name `default.svg` into the Inkscape template folder.

**Comment by kaalleen** [comment]
No further respond. Closing.
