### ISSUE TITLE
Zizag on meander

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#2696]
![Capture d'écran 2024-01-16 003926](https://github.com/inkstitch/inkstitch/assets/54963659/ed9e3d12-7afd-4d2a-9559-a61a0dfa88fe)
Using meanders on this small rabbit I have tried zigzag to create a kind of fur
![20240115_231152](https://github.com/inkstitch/inkstitch/assets/54963659/26f5eca8-5ccc-46c0-a4fe-0fc12f6b3bb2)
Do you think it would be possible to add an option in meander params to use easily zigzag without using stitchplan
![rabbit](https://github.com/inkstitch/inkstitch/assets/54963659/2355b2d9-4768-4f9d-94fd-7bf9d8e68513)

**Comment by kaalleen** [comment]
That's so cute. Nice idea!

**Comment by Augusa** [comment]
Thank you very much for this new release. I am playing with!
