### ISSUE TITLE
Ink/Stitch extension not working on Mac (Sonoma 14.2.1)

### ISSUE THREAD

**Issue by thisisme664** [inkstitch/inkstitch#2697]
Hey there, 

I downloaded and installed Inkscape and the ink/stitch extension on my MacBook Air. Everthing seems to have been installed fine and I can see the ink/stitch extension in the extension drop down menu but any time I try to use any of the tools nothing really seems to actually work. 

It's a MacBook Air M2 running Sonoma 14.2.1 
Inkscape version installed - Inkscape 1.3.2 (091e20e, 2023-11-25)
Ink/stitch version installed - Ink/Stitch - 3.0.1 (osx)

Any insight? Did I download the wrong version of something?

**Comment by kaalleen** [comment]
It's probably due to a missing rosetta insdtallation.

https://inkstitch.org/docs/install-macos/#inkstitch-doesnt-run--is-greyed-out

**Comment by jennywagg** [comment]
Hi, I'm running into a similar issue. 

- M1 Mac on Ventura
- Inkscape 1.3.2
- Ink/Stitch 3.0.1 (osx)

I have an updated rosetta installation, and I've tried installing Ink/stitch into the user extensions folder and the Inkscape extensions folder. Still, the Ink/stitch extension crashes any time I launch it from the Inkscape application. It opens the gui, then I soon after get a message that ink/stitch has crashed.

<img width="1053" alt="image" src="https://github.com/inkstitch/inkstitch/assets/8674959/fb617b1b-5391-41ae-b207-f2a4fd91dfda">

**Comment by TerrieW** [comment]
I also have Sonoma 14.2 on my Mac. I have downloaded the latest versions of both Inkscape and Inkstitch for Mac. Even though Inkstitch is installed in the Inkscape extensions folder and shows up in the extensions drop down, nothing happens when I try to use it for a live preview of an embroidery. Is Inkstitch not compatible with Sonoma 14.2? If not, is there an update coming soon? Is there something I can do to make it work? I would appreciate any help I can get. It all worked fine on my previous computer running Monterrey.

**Comment by thisisme664** [comment]
> I also have Sonoma 14.2 on my Mac. I have downloaded the latest versions of both Inkscape and Inkstitch for Mac. Even though Inkstitch is installed in the Inkscape extensions folder and shows up in the extensions drop down, nothing happens when I try to use it for a live preview of an embroidery. Is Inkstitch not compatible with Sonoma 14.2? If not, is there an update coming soon? Is there something I can do to make it work? I would appreciate any help I can get. It all worked fine on my previous computer running Monterrey.

What ended up working for me was following the instructions Kaaleen posted for rosetta install

**Comment by TerrieW** [comment]
Thank you SO much, both of you, for your answers. I added it in my Terminal. It worked!! Your quick answer is much appreciated.

**Comment by kaalleen** [comment]
Thank you for the feedback!
