### ISSUE TITLE
Installing Ink Stitch Using Microsoft Intune Admin Center

### ISSUE THREAD

**Issue by cookdfierro** [inkstitch/inkstitch#2725]
I was looking for any tips, tricks, tutorials or best practices for installing Ink Stitch using Microsoft Intune admin center.

We were able to deploy InkScape using Intune and the new Microsoft Portal.  But the users would also like to use Ink Stitch.

**Comment by kaalleen** [comment]
I have no idea what the Microsoft Intune Admin Center is and how it works, sorry.
Is anybody else able to help out?

**Comment by kaalleen** [comment]
No further response. Closing.
Please continue to use this thread if you have more questions or open a new issue.
