### ISSUE TITLE
Thicknes of stitch is not changing

### ISSUE THREAD

**Issue by LeagueOfShards** [inkstitch/inkstitch#2727]
![sraka](https://github.com/inkstitch/inkstitch/assets/160267267/92756889-5c4f-4d54-b66b-d91426d95313)
![sraka2](https://github.com/inkstitch/inkstitch/assets/160267267/18dd60cb-bf1a-4c3d-8c35-7fbbd9c4815d)
 
I have set up two difference thicknes of stitch and still stitches has the same thicknes. What i can do with this?

**Comment by tyrosinase** [comment]
Go into `Extensions > Ink/Stitch > Params` and change the Running Stitch type to Zigzag.

Older Ink/Stitch defaulted to Zigzag for all non-dashed lines, and older *files* will still do that for compatibility, but newly-created ones have to have the stitch type explicitly set.
