### ISSUE TITLE
ResourceWarning in Select Elements

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2737]
Playing around with tartans (neat, btw!) and decided to try out the new Select stuff. It couldn't find my py3 (`~/.pyenv/shims/python3` if we're taking notes on possible locations) so I entered it, and got this:

```
subprocess.py:946: ResourceWarning: subprocess 229312 is still running
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Closed and reopened Inkscape in hopes it would terminate the subprocess but nope. (Also didn't realize "Apply" was going to attempt the Select rather than applying the directory choice, though that might be an Inkscape UI quirk.)

Not sure if that's just a pre-release thing or just my janky python situation, but there it is.

**Comment by kaalleen** [comment]
Thank you for trying the dev builds. Actually I wanted to tell you just now that now the build versions should work much better than a few days ago and that you could start trying to break them :)
This issue though should be fixed in main by now. I should rebase the tartan branch to fix it.

**Comment by tyrosinase** [comment]
Ooh nifty.

Doesn't get the ResourceWarning with that one, though it doesn't do any selecting (or deselecting, if I start with an active selection).

I did manage to segfault(!) Inkscape somehow once, but I can't reproduce that. Launching it from the command line doesn't show any useful error messages (just the usual unknown-type warnings; someday I should find where to shut that off).

And the two-rung detection works in Troubleshooting, at least, so I am off to fix fonts, woo hoo!

**Comment by tyrosinase** [comment]
Oh no, Troubleshooting, tell me which layer! 😂😭
![image](https://github.com/inkstitch/inkstitch/assets/9473609/a03cb45d-3b83-446e-b96b-491437a48565)

**Comment by tyrosinase** [comment]
Okay, DinoMouse is fixed, since that didn't take long maybe I'll just fix Emiliohhhhh no.

![image](https://github.com/inkstitch/inkstitch/assets/9473609/99b6b560-881b-4be9-8168-9e409e00bae1)

On second thought, maybe I'll just contemplate what it would take to write a third-rung-adding Perl script.

**Comment by kaalleen** [comment]
That's ... chaos :D Claudine said she is brave enough to face it, so no worries about Emilio, it will be fixed.

**Comment by kaalleen** [comment]
> Doesn't get the ResourceWarning with that one, though it doesn't do any selecting (or deselecting, if I start with an active selection).

So this is working if you do not have any previous selection?

**Comment by kaalleen** [comment]
The select elements extension should work now ok-ish.
Button will need to be pushed twice sometimes though.
At least no ResourceWarning is to be expected ... I think.
