### ISSUE TITLE
Error generating clipped object copy as pes

### ISSUE THREAD

**Issue by MayconGst** [inkstitch/inkstitch#2748]
![i382054](https://github.com/inkstitch/inkstitch/assets/59565757/6d2718d0-d868-4650-a6f9-5cdb8678fbbc)
![Captura de tela 2024-03-01 174130](https://github.com/inkstitch/inkstitch/assets/59565757/029a0a80-0714-4bc1-bf75-9e27ab5b7e30)

**Comment by kaalleen** [comment]
Thank you for the error report.

Best if you release the clip. Remove the blue square. Select the white square, use the node tool to remove the square outline to only have the inside remaining. Select all remaining paths and combine and set color. Then you'd have a "working file", yet it isn't optimized for embroidery.
