### ISSUE TITLE
Python error on OSX

### ISSUE THREAD

**Issue by Beakerboy** [inkstitch/inkstitch#275]
I'm running Inkscape 0.92.2 on OS X Yosemite 10.10.5. I installed inkstitch and the Embroidery extension appears just fine. However, when I select most of the actions, like "Live Preview" I am presented with the following error:

    [2279] Error loading Python lib '/Users/kevin/.config/inkscape/extensions/inkstitch/bin/.Python': dlopen: dlopen(/Users/kevin/.config/inkscape/extensions/inkstitch/bin/.Python, 10): Symbol not found: _getentropy
    Referenced from: /Users/kevin/.config/inkscape/extensions/inkstitch/bin/.Python (which was built for Mac OS X 10.13)
    Expected in: /usr/lib/libSystem.B.dylib
    in Users/kevin/.config/inkscape/extensions/inkstitch/bin/.Python

**Comment by Beakerboy** [comment]
Upgrading my operating system to highest Safari seems to have fixed this issue. However, I’m sure it exists for anybody it’s still running an older version of MacOS

**Comment by AkiraNorthstar** [comment]
Thanks for the feedback and welcome to Ink/Stitch.
Is there anything special about knowing about changes in Safari, that's important to us?

If you have any further suggestions or wishes, you can create them at [Wishlist / Issues](https://github.com/inkstitch/inkstitch/issues/).

**Comment by Beakerboy** [comment]
Speach-to-text flubbed “high Sierra” to “highest safari”. High Sierra is the newest version on MacOS. A google search says it might be an issue with older OS, Xcode, and the way the compileing configure script is written.

https://gitlab.com/gnutls/gnutls/issues/142

**Comment by AkiraNorthstar** [comment]
Is XCode 7.x and XCode 8.x shipped with HighSierra?
... Unfortunately I'm not up to date on macOS.

At the beginning of the year XCode 9.3x came out as a "beta / test version", is it already available as a final version?

In any case, we should change the system requirement to HighSierra.
Do we even have the prerequisites anywhere - shame on me - I do not know.
Thanks for the reference!

**Comment by Beakerboy** [comment]
I have no idea. A friend is having my business logo digitized for embroidery, so I started searching for open source embroidery software and found inkstitch. I already had Inkscape working, so I upgraded it to the recommended version, installed inkstitch and was given errors, so I’m reporting it.

Once the initial professional digitized version comes back, I’d like to use this to make any edits in the future. I’ll let you know if I come across any other problems. It looks like I’ll need to read some how-to guides.

**Comment by wwderw** [comment]
> Once the initial professional digitized version comes back, I’d like to use this to make any edits in the future. I’ll let you know if I come across any other problems. It looks like I’ll need to read some how-to guides.

Most professional digitizers (myself included) would allow for QC edits within a reasonable time of the original purchase.

If you are making edits with the raw stitch file (DST etc), those would be made at the individual stitch level.  I would suggest at that point to just redigitized using Ink/Stitch and that way any future edits would be object based compared to stitch by stitch.

**Comment by AkiraNorthstar** [comment]
That's fine.
If you have questions about ink/stitch at a later time, you can ask them anytime.
You are always welcome!

May I close this issue with your consent?

P.S .: Thanks @wwderw for your addition!

**Comment by AkiraNorthstar** [comment]
Yeah, you can do that. However, then you have several macOS packages that run on certain versions of macOS.  You would have to support 4 ~ 5 different macOS-Ink/Stitch-packages.

Then I would have a Windows 3.11 version of Ink / Stitch! :)

Well, it's not that bad. Apple does it like (now) Microsoft too. Update = new OS.
Apple is stricter, no 32-bit application will run under a new macOS at the end of the year.

And as a MacOS user you can not ignore the updates...

**Comment by AkiraNorthstar** [comment]
Where is the contribution from @wwderw ?

**Comment by wwderw** [comment]
> And as a MacOS user you can not ignore the updates...

Has Apple started forced updates with MacOS?  Other then issues like the root password issue that came out with High Sierra and that fix update was forced, I thought it was still optional and reversible for OS updates on Mac (I think it's a different story with iOS however).

Unlike Windows though, at least Mac has a tighter grip on hardware that helps with stability of updates (although they can still happen), it's the deprecation and removal of support that becomes the issue.  OpenGL is another thing that is being deprecated (and probably eventually removed) from Macs as well.

**Comment by wwderw** [comment]
>Where is the contribution from @wwderw ?

I removed it.  A digitizing suggestion really didn't have a place in a coding discussion.

**Comment by AkiraNorthstar** [comment]
You have the choice to install an update! However, I was asked "everywhere" if I want to update. After some time, you do that to be no longer asked. I think it's alright that you will be reminded. But there are some updates on which I had no influence. Whether this was security updates or not, I can not say. Maybe it was the installation in VirtualBox. If it seems that I have something against Apple, or against the update strategy, then I have to revise that.
I think it's a pity that a Mac is presented as a prestige object. It is a stable system, has many eyecandys, good ideas on board and the backbone is a unix like system. And not as vulnerable as other widely used systems. But that's mostly due to the users. I have been using linux for about 20 years and am satisfied with it.

> I removed it. A digitizing suggestion really didn't have a place in a coding discussion.

I thought that was fitting. It was a thought / note to this topic.

**Comment by globalcow** [comment]
Is it possible to test if a version build for macOS 10.12 Sierra (Travis: osx_image: xcode8.3) runs in High Sierra? I can test it in High Sierra, but I don't no how to trigger such a build in Travis.

**Comment by AkiraNorthstar** [comment]
I think that :
```bash
matrix:
  include:
    - os: linux
    - os: osx
        osx_image: xcode8.3
```
should be enough to enable XCode8.3.
That should be worth a test.

**Comment by Beakerboy** [comment]
@AkiraNorthstar Feel free to close whenever you feel the issue is resolved.

**Comment by globalcow** [comment]
I think, we could try to support high sierra as long as it is supported by apple. But it‘s too much work to support older versions in hindsight.

**Comment by AkiraNorthstar** [comment]
I close this issue because the basic problem is solved.
