### ISSUE TITLE
"Realistic Preview" always renders jumps

### ISSUE THREAD

**Issue by bkgoodman** [inkstitch/inkstitch#2751]
"Realistic" preview always renders jumps - even when "Show jumps" is disabled. Furthermore, when you subsequently deselect "Realistic" and it does back to "normal" preview, jumps are then rendered even if disabled.

1. Without "Realistic" or "Render Jumps" selected

![image](https://github.com/inkstitch/inkstitch/assets/473399/bd369a0a-f153-4532-a2d9-26c0bd3e7b49)

2. "Realistic" enabled ("Render Jumps" still disabled)- but jumps are still drawn

![image](https://github.com/inkstitch/inkstitch/assets/473399/1ea8297b-4dca-4451-9c1e-f3692ee1abca)

2. "Realistic" disabled  ("Render Jumps" still disabled) - but jumps are still drawn

![image](https://github.com/inkstitch/inkstitch/assets/473399/84881f5a-d56b-4793-9004-ddb27501d3c3)

**Comment by kaalleen** [comment]
Thank you for the error report. Looks as if it returns to default (render jumps) when the view is switched. When you deactivate and re-enable the jump stitch rendering it should display it correctly. Still this is a bug we need to fix.
