### ISSUE TITLE
making a new project with inkstich would like a conversation with @lexelby

### ISSUE THREAD

**Issue by gckushalWork** [inkstitch/inkstitch#2758]
HI @lexelby 

i am trying a new project with inkstitch as it core and would like to have 1 hr discussion with you regarding this project because what you have archived with inkstitch is really great please let me know if we can contact you.

we are small 4 member company based out USA we have entered the embroidery world newly and using your plugin and learning its varies features has been of great help so please let us know if we contact you for a small discussions     

Regards
Kushal G C

**Comment by gckushalWork** [comment]
Hi @lexelby  

we are trying to make programmatically convert an svg file into a dst output so people can upload an svg and directly get a good DST output for them to use in there machine. to be able to do that programmatically for satin stitch is becoming a bit of challenge hence we would like to get you on as consultant  for 1 hr or 30 mins. please do let us know if you can help us out 

regards
Kushal G C

**Comment by lexelby** [comment]
@gckushalWork I'm afraid I'm really not going to be able to chat with you directly about this.  You might be able to accomplish your goal by running Ink/Stitch from the command line, as in #1913, also discussed in #2663 and documented [here](https://inkstitch.org/docs/command-line/).

Satin is a tricky beast, and creating one in an automated fashion is doubly so.  You might get some luck by using Ink/Stitch's Convert Line to Satin, and I suppose you could run that extension through the command line.

Good luck with your project!
