### ISSUE TITLE
Error "unhandled exception in script"

### ISSUE THREAD

**Issue by vuhlyk** [inkstitch/inkstitch#2767]
on windows 10, Ink Stitch v3.0.1

![ghfhf](https://github.com/inkstitch/inkstitch/assets/162845035/c4445272-0ed9-40a7-a002-8b445ed40e95)

**Comment by tyrosinase** [comment]
Ink/Stitch is a plugin for Inkscape - install Inkscape first:  https://inkstitch.org/docs/install-windows/

(The error message will be made clearer in future releases, per #2582.)
