### ISSUE TITLE
Realistic View

### ISSUE THREAD

**Issue by krisyoung33** [inkstitch/inkstitch#2770]
Would there be anyway to toggle between the standard view and realistic view without being took to the simulator page. a bit like how we can toggle between normal and outlines in inkscape.

Reason being is that we do virtual proofs on garments for customers to see how their design will look so would be handy to drop a garment image in the background and toggle on realistic view to screen grab the virtual proof.

**Comment by kaalleen** [comment]
You mean within Inkscape?
It would be possible, but it slows down Inkscape so much, that we rather did not make this an option for the stitch plan preview.

**Comment by krisyoung33** [comment]
I've attached images from my Tajima pulse software to show how I have an outline view and a 3D/Realistic view but that I don't have to leave the page that I am working on the design.

I just toggle this view by pressing a key.

We only have 1 computer with the Tajima software on so means this is the only computer we can generate embroidery 
virtual proofs from, everyone else uses Inkscape so would be useful if they could pull up one of my DSTs and use Inkscape to mock up their own virtual proofs. 

![3D - Realistic View](https://github.com/inkstitch/inkstitch/assets/162927233/64c77f26-a602-4b7e-89e2-c6448715c37f)
![Outlines View](https://github.com/inkstitch/inkstitch/assets/162927233/46d69e13-14f4-4c4d-9260-08e029f7e152)

**Comment by capellancitizen** [comment]
This was added in 3.1.0, so I think this can be closed.
