### ISSUE TITLE
improve simulator rendering

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#278]
We've learned from @tatarize that wxPython's `DrawLines()` may be able to draw thousands of lines each frame.  This would simplify the Simulator rendering code and let us skip backward and even play in reverse.

@kaalleen I'm definitely not very good at graphics code, so if you want to take a shot at this, please feel free.  Go ahead and rip out my old code if the new way works better.

I might take a crack at this at some point but I've got a few other things that I'd like to get to first.

**Comment by lexelby** [comment]
Yay!  Just to be clear, it's fine with me if you want to use his code, so long as it has a compatible open source license attached.  I think he said he was going to post it in the EmbroidePy project.

**Comment by kaalleen** [comment]
Closing this, the simulator is updated already.
