### ISSUE TITLE
Text w/no fill won't save as PES

### ISSUE THREAD

**Issue by Tanner2059** [inkstitch/inkstitch#2787]
I am running this on my MAC 14.0 (23A344).  I have attached the file that would save.  I was creating a file that had the font without a fill and I continually received this error.  I have rebooted (no Inkscape update needed, checked), and when I added the fill back in the font, I was able to save the PES file.

It won't allow me to attach the PES file that works, so I have put it in my Google Drive...here are the links:

[PES file with fill](https://drive.google.com/file/d/1U1FjBUgMc8SlWxI7XZhwZc5LcDZGd8wF/view?usp=sharing)
[SVG file for converting with InkStitch](https://drive.google.com/file/d/11sdxBVIu-AXRbggRjilndiVYASjnBh5P/view?usp=sharing)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 133, in elements_to_stitch_groups
  File "lib/elements/element.py", line 558, in embroider
  File "lib/elements/fill_stitch.py", line 703, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 739, in do_legacy_fill
  File "lib/stitches/fill.py", line 18, in legacy_fill
  File "lib/stitches/fill.py", line 98, in intersect_region_with_grating
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by Marif91** [comment]
Il y a beaucoup trop de changements de couleurs et les points sont minuscules. 0,2mm pour un point droit c'est bien trop petit !

**Comment by Tanner2059** [comment]
Thank you!  I did the color changes so it would cut after each letter, the cut feature doesn't work (as noted in the program) on my domestic machine.  I will do less color changes and a >.2mm stitch.  The font is small, any recommendations for stitch length?

**Comment by tyrosinase** [comment]
You're going to run into serious readability issues at that size, especially with a fill-n-outline like that. Satin would be much much clearer.

I'd go with an applique (or patch, if you want to embroider before applying) to give you a cleaner field for the lettering.

Built-in font NickAinley is this small with regular-weight thread (40wt) and the usual 75/11 needle; you can size it down a bit if you use 60wt and a 65/9 or 60/8 needle (and any tension/speed adjustment your machine calls for with that thread), but I've never tried it so I can't tell you how much you'll be able to get away with.

![image](https://github.com/inkstitch/inkstitch/assets/9473609/e44a9b4a-4c33-4e30-b025-80b8578c0513)

Built-in Espresso Tiny, which requires 60wt thread and a 60/8 needle, gets this small. That's a .66mm satin, and if you try to stitch it over fill it will lose precision (not to mention regular thread and/or needle breaks).

(Not strictly embroidery-related but I'd also recommend the line breaks being
```Once a shirt
Now a bear
Hold it close
I'll be there``` so it scans properly)

**Comment by kaalleen** [comment]
I'll close this one as the error is fixed for  the next release and hints for better embroidery have been given. You can still post your questions here if you want to discuss this further.
