### ISSUE TITLE
localization of inkstitch.org

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#280]
The README.md and the pages on inkstitch.org are currently written in English only. We already have some other languages to work on. Unless there is nothing against it, we could also offer other languages on inkstitch.org.
I am not in the topic (gh-pages), so I ask myself the question how this can be meaningfully implemented. Is there any ideas or even concrete solutions?
Or in other words, are there any stumbling blocks to this project?

-----
German:
Die README.md und die Seiten auf inkstitch.org sind zur Zeit ausschliesslich in englisch geschrieben. Wir haben schon einige andere Sprachen an denen gearbeitet wird. Soweit nichts dagegen spricht könnten wir auch auf inkstitch.org andere Sprachen anbieten.
Ich bin nicht im Thema (gh-pages), deshalb stellt sich mir die Frage wie das sinnvoll umgesetzt werden kann. Gibt es dazu irgendwelche Ideen oder sogar konkrete Lösungen?
Oder anders gefragt, gibt es Stolpersteine zu diesem Vorhaben?

**Comment by AkiraNorthstar** [comment]
#86

**Comment by lexelby** [comment]
> I am not in the topic (gh-pages),

Do you mean you don't have access?  You should be able to see it -- just select gh-pages from the "branch" drop-down.  If you mean you don't have the ability to write to that branch, let me know and I'll fix that.

@kaalleen What do you think? is this possible?

**Comment by AkiraNorthstar** [comment]
That's alright, there are some things that I'm not so good translatable.
For example: sayings and the spoken language varies from the correct spelling (grammar).
And the google translator does not know some words ;-)

**Comment by kaalleen** [comment]
I will need some time to add multilingual support for inkstitch.org. We are a bit limited, since github pages do not support any multilingual plugins (https://pages.github.com/versions/).

> Other plugins are not supported, so the only way to incorporate them in your site is to generate your site locally and then push your site's static files to your GitHub Pages site.

***
Just as a reminder for myself - and maybe for you if you are interested: https://github.com/mmistakes/minimal-mistakes/issues/612 -> https://www.sylvaindurand.org/making-jekyll-multilingual/

Other plugins than those listed above cannot be officially used with github pages, it seems to be possible though: https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/

the mentioned modified version seems to be included to the main repository of this plugin by now: https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin/issues/86#issuecomment-276187549
so we might be able to use: https://github.com/Talentoday/jekyll-multiple-languages-plugin
***
I like the plugin version better (if possible) because it provides subfolders for language files, but if it involves to push the generated site files - this is not the way to go - because we don't want the translators to necessarily build the website locally.

This is all quiet a lot to do here, so I'll get back to it later.

There is also an other problem we might face here. If we translate to other languages, we need to keep them up to date. E.g. I was thinking lately to restructure the "stitch library", since more and more stitch types will be added. The users might want to see directly which stitch types are available and wouldn't want to mess with terms like "stroke".

Things like this can be a lot work if it has to be done with many language files. This is a very active project, so it's sometimes not easy to keep up with the English version. Well, I am sure @AkiraNorthstar will be very busy translating the website to german... but still I wanted to mention this as a (small) concern. Since it will not be as convenient as translating the inkstitch messages.po and translators have to figure out their own way to find updated parts - at least I don't know a better solution yet ;)

**Comment by AkiraNorthstar** [comment]
Could we make it static in the first step? Or is this more work than it already is?
In the example of [Setting up a Proper Multilingual Site](https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/) in the section "Adding a Page" looks very modular.
```mysite/
├ _i18n/
  ├ de/
    └ about.md
  ├ en/
    └ about.md
  └ ...
├ about.md
└ ...
```
That would mean that I first translate the "simple" parts and / or the important parts.
Of course, there is a time lag from the main English language to other languages.
For untranslated parts we could put a note that this entry still needs to be translated ....
I can already start the translation (local), no matter how it will do later or should I still consider something?

-----
German
Könnten wir es im ersten Schritt statisch machen? Oder macht dies mehr Arbeit als jetzt schon ist?
Im Beispiel von [Setting up a Proper Multilingual Site](https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/) in der Sektion "Adding a Page" sieht das sehr modular aus.
```mysite/
├ _i18n/
  ├ de/
    └ about.md
  ├ en/
    └ about.md
  └ ...
├ about.md
└ ...
```
Das hiesse, dass ich erstmal die "einfachen" Teile und / oder die wichtigen Teile übersetze.
Natürlich gibt es eine Zeitverzögerung von der Hauptsprache englisch in andere Sprachen.
Bei nicht übersetzten Teilen könnten wir einen Hinweis plazieren, dass dieser Eintrag noch übersetzt werden muss....
Die Übersetzung kann ich schon anfangen (lokal), egal wie wird das später machen oder sollte ich dennoch was beachten?

**Comment by kaalleen** [comment]
Oh yes, sure. Just go ahead :)
Even if we cannot achieve this file structure, we could still use your translations.

I didn't have the chance to have a closer look at this topic. I was just collecting links to see what might be possible. If you feel comfortable, you could also try to setup the multilingual stuff. If not - just start with the translation and we will integrate them later.

**Comment by AkiraNorthstar** [comment]
Can I run or build gh-pages locally for testing?

**Comment by lexelby** [comment]
Keeping in mind that I have no idea how Jekyll works or anything... I wonder if it would be possible to use Travis CI to do the multilingual build rather than having to do it locally?

**Comment by AkiraNorthstar** [comment]
Link for inspiration : [Integrate Translations and Magic](https://medium.com/glucosio-project/integrate-translations-into-development-process-with-travis-and-ci-magic-bdda43c0112f)

**Comment by lexelby** [comment]
Wow, neat!  This gives me some great ideas on how to fix our workflow that we were discussing in the other  PR.

**Comment by AkiraNorthstar** [comment]
That's right, I did not think about that when i read the article. Of course! That could also be helpful with the crowdin "issue".

**Comment by lexelby** [comment]
Yeah!  Maybe we should set up an automatic daily job on Travis to get the latest approved translations from Crowdin and commit them to master.  I also know how to make it skip if there are no actual changes to the translated strings.

**Comment by AkiraNorthstar** [comment]
@kaalleen and @lexelby :
Where can I put the translation(s)?
I just do not like messing up the gh-pages branch.

**Comment by kaalleen** [comment]
Wow, you've been active ;)

> Where can I put the translation(s)?

You could place them at the place, where we actually aim to store the final tranlsations ... it will be ignore it until we update the `_config.yml` to use it.
```
├ _i18n/
  ├ de/
```
The GitHub pages website is actually not build locally. GitHub creates static html pages from the files in the gh-pages branch. GitHub will automatically update the website when changes are done.

But of course you can build it locally if you want to. Have a look at https://jekyllrb.com/
You can find a quick setup for jekyll there. For the theme have a look here: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/ 
You can copy the gh-pages files into your local installation and run jekyll serve.

**Comment by AkiraNorthstar** [comment]
If I could push the translations into the project, then I do not need a local build. I don't know how and what is automatically implemented, so I'm very careful in actions such as "I push a file somewhere". 

...Not that I break anything, or mess things up...

By the way, thank you for your improvements to the README_eng.md!

Do the headers need to be changed (Title, excerpt and last_modified)?
```bash
---
title: "Install Ink/Stitch"
permalink: /docs/install/
excerpt: "How to quickly install Ink/Stitch."
last_modified_at: 2018-07-21
toc: true
---
```

What I noticed is that the markdown files have html tags.
For example, ```<br>```. I assume that these are needed to display the text correctly on inkstitch.org?
I have kept these and other tags exactly as they were in the origin file.

So, I have no other questions for now, I'll continue ... ;-)
Happy coding!

**Comment by AkiraNorthstar** [comment]
Have pushed some translations in [gh-pages](https://github.com/inkstitch/inkstitch/commit/cd1fb944563236ce59008e2f0f1f02cc62631960). 
I also tried to write without "Du" and "Sie".
@kaalleen  - If you have some time, it would be great that you read them and give a feedback. There's no hurry!

**Comment by AkiraNorthstar** [comment]
Can we add something like this as css scriptlet?
![grafik](https://user-images.githubusercontent.com/16691957/44662905-5ad5ea00-aa0f-11e8-84c2-7e06eb1efac8.png)
It would look better than "Ctrl + Alt + I" and could be used independently for any language.

Source:
```html
<html>
<head>
<style>

.keypad_off{
    color: #333333;
}

.keypad_on {
    color: #333333;
	border: 1px solid #999999;
	border-radius: 0.3em;
    padding: 3px; 
}

</style>
</head>
<body>
<h1>CSS Keyboard Shortcut Test</h1>
<div>
	<span align="center" class="keypad_on">Strg</span>
    <span align="center" class="keypad_off"> + </span>
    <span align="center" class="keypad_on">Alt</span>
    <span align="center" class="keypad_off"> + </span>
    <span align="center" class="keypad_on">F1</span>
</div>
<p>
<div>
	<span align="center" class="keypad_on">Ctrl</span>
    <span align="center" class="keypad_off"> + </span>
    <span align="center" class="keypad_on">Alt</span>
    <span align="center" class="keypad_off"> + </span>
    <span align="center" class="keypad_on">F12</span>
</div>
</body>
</html>
```

**Comment by kaalleen** [comment]
@AkiraNorthstar I've seen your translation - nice work! I haven't had the time to read through it, but I updated gh-pages to make them visible (at least if you know where to find it). I wasn't sure if this will work with the github pages setup so I did not include a language switcher yet, but you could try the following: https://inkstitch.org/de/ and click through the documentation. There are still many links not working yet, but I believe it's a good start for a multilingual website. What do you think?

> Can we add something like this as css scriptlet?

Sure we can add additional css. Have a look at https://github.com/inkstitch/inkstitch/blob/gh-pages/_docs/001-002-customize.md (https://inkstitch.org/docs/customize/), that's where I used it for testing (it's not in the german equivalent yet).

During the next days I will transfer the "original" to the "en" folder to keep the file system consistent.

**Comment by AkiraNorthstar** [comment]
Thank you for making the German area visible!
Markdown is difficult to read depending on the editor, so I prefer the "output view".
So I can better proofread and correct my mistakes / or find faster.

"\<key>\" - I didn't know that we have something like that ... nice!

Then we don't need any additional css snippets.
I wish you a nice weekend - relax! :)

**Comment by lexelby** [comment]
Do you need to be able to use the language plugin?  If so I could put some time into figuring out how to build the site on Travis instead of locally.

**Comment by AkiraNorthstar** [comment]
@lexelby can you please update the documentation "Manual Setup".
It has changed since the initial writing.
@kaalleen and @lexelby 
I think we should change the paths: "Extensions > Ink/Stitch > English > xxx" to "Extensions > Ink/Stitch > xxx" without any language in the docs.

**Comment by kaalleen** [comment]
@AkiraNorthstar don't fix the headers for the english version, they are fine without the en prefix for now. It might actually break things right now.

Why without the language? I think that's what the user has actually do and since we have language support we can write the specific language right there? If the Ink/Stitch structure will change we can remove it.

**Comment by kaalleen** [comment]
@lexelby No, we don't need the plugin anymore. We found our way around it ;)

**Comment by lexelby** [comment]
Okay, if you're sure.  Your comment above had me wondering if maybe the workarounds are too difficult and don't work well.  From what I can tell, getting the languages plugin working using Travis is actually quite easy:  https://ayastreb.me/deploy-jekyll-to-github-pages-with-travis-ci/

So if it would make your life easier, I can do it.  Then you could have other Jekyll plugins too!

**Comment by AkiraNorthstar** [comment]
Basically I have no problem with that under "Extensions> Ink / Stitch>"
several languages are available. The problem is the export dialog. In this stand all languages "Ink / Stitch: XXX Embroidery Format (.xxx)":
![ink_01](https://user-images.githubusercontent.com/16691957/44956233-d2e55980-aec0-11e8-9462-734e8e5617e4.png)
And these are just two languages!
I have already tried some ideas, unfortunately only with mediocre success.
Currently I delete * _en_US.inx by hand, but that's not great, if I want to look for something translated for the translation ....

**Comment by AkiraNorthstar** [comment]
> @AkiraNorthstar don't fix the headers for the english version, they are fine without the en prefix for now. It might actually break things right now.

I've seen - Sorry!

**Comment by kaalleen** [comment]
No problem, just thought I'll tell you before you start doing it multiple times ;)

I understand now, what you meant about the ink/stitch > language part. I thought you were only referring to the documentation. If it comes to the menu itself, I agree with you. It would be nice to not have to go through all the languages to see the actual functions or even the duplicated export files. But if I understood it correctly, it seemed to be the only method to realize the inx files localization.

@AkiraNorthstar do you think the github pages file structure is too complicated?
I actually like having the topics and translations close to each other. We can handle things more individually without a plugin. The tutorial listing "functions" I wrote myself, so I should be able to adapt it to the new situation (some day), we just have to add an additional filter. I am just not sure, what people not being familiar with the site may think.

**Comment by AkiraNorthstar** [comment]
At the moment I am trying to update the links or jump labels within a page.
Here's an example:
```bash
... [Kurzbefehle](/docs/customize/#shortcut-keys) ... 
```
In theory it should be
```bash
... [Kurzbefehle](/de/docs/customize/#Tastenkürzel) ...
```
Or do I understand something wrong?

> @AkiraNorthstar do you think the github pages file structure is too complicated?

Of course - NO!
And the basic structure is simple and effective, just as it should be!
Keep it simple and smart! = KISS principle

**Comment by kaalleen** [comment]
> Or do I understand something wrong?

Jain ;) Most of it is correct. In the last section of the link you use the exact headline where you want to link to. But it has to be slugified. "Tastenkürzel" would become "tastenkürzel" (it can actually take ä - I wondered if it could). Space is always replaced by - and capital letters will be lower case.
If you are not sure and the page you are linking to is already existent, you could have a look at the links in the table of contents on the right side.

> Of course - NO!

Ok, then we stay with our solution. Thank you to offer your help in this matter @lexelby .

**Comment by AkiraNorthstar** [comment]
@all Are you using a markdown editor, or is vim and co your daily companion?
Or in other way: Is there an "offline jekyll editor" with WYSIWYG feature?
Right now I'm using ReText, but I'm not so happy with it.

**Comment by lexelby** [comment]
No problem, let me know if you change your mind :)

**Comment by kaalleen** [comment]
Tutorial filter works now. @AkiraNorthstar I hope I did not confuse your workflow with adding a lot of files whit only german titles but english text in the content. I needed something to test upon. Same for posts.

> @ALL Are you using a markdown editor, or is vim and co your daily companion?

I am sorry, I don't know. Vim and co are a good choice for me, having jekyll locally running. So I never felt the need for an other editor.

Maybe this might help you (It's not a real recommendation, since I don't know any of them):
Linux: https://www.tecmint.com/best-markdown-editors-for-linux/
Windows: http://www.markdownpad.com/

**Comment by AkiraNorthstar** [comment]
>  @AkiraNorthstar I hope I did not confuse your workflow with adding a lot of files whit only german titles but english text in the content. I needed something to test upon. Same for posts.

"e bissle scho" - At the first moment, it's just about working with several people on a project. ;)
Fortunately we work with git - with svn ... chaos.

**Comment by AkiraNorthstar** [comment]
In the tutorials you forgot to rename the puff. How about Moulin Rouge? - just kidding!
Explanation: Puff is in german a "brothel"

**Comment by kaalleen** [comment]
I added a new "feature" to the website. It will list all pages that are not existent in a particular language or that will need updates (compared to the English version). The list can be found here: https://inkstitch.org/developers/localize/#localize-inkstitch-website

Hope this will help a little to keep everything up to date.

**Comment by AkiraNorthstar** [comment]
Cool feature! Is this page automaticly generated or by hand?

**Comment by kaalleen** [comment]
It's automatically generated. It orients on the permalink and the last_modified_at value, which on the other hand have to be set by hand in the front matter at the top of each page.
