### ISSUE TITLE
File format issue

### ISSUE THREAD

**Issue by Elliej1234** [inkstitch/inkstitch#2800]
Used inkstitch to change existing image into a file for embroidery- all looked fine on the simulator - saved as an svg and a pes as I need pes for my machine but the pes file is very distorted and not like the svg file.. not sure what I am doing wrong and why the files are so different? 
the saved svg file looks fine also, but the pes seems to mess it up?

**Comment by tyrosinase** [comment]
To expand on what kaalleen has said: is the file itself distorted, or the stitchout? If you reopen the PES in Ink/Stitch, does it look correct? Does it look correct on your machine's screen, if it has one?

**Comment by kaalleen** [comment]
I'll close this one. If you have more questions, you can still post them here.
