### ISSUE TITLE
Problem with AGS Γαραμου Garamond font

### ISSUE THREAD

**Issue by zourid** [inkstitch/inkstitch#2801]
It seems there is a spacing/kerning issue with AGS Γαραμου Garamond font only for certain Greek letters, specifically after the letters 
— Γ (worst case of extra space)
— Π
— Φ
— Ψ
(see blue dots in the attached).
Lower case letters are fine.
![Garamont](https://github.com/inkstitch/inkstitch/assets/142331941/114968a9-af62-4636-b54b-18f4a675a4e2)

**Comment by claudinepeyrat06** [comment]
<img width="495" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/3419fced-12ef-4bbf-bb8a-8741e41bd489">

I just pushed a fix for the kerning, if you find more  gliches later on, please tell.
