### ISSUE TITLE
Extension crash on Satin to Stroke

### ISSUE THREAD

**Issue by Qwertie-** [inkstitch/inkstitch#2811]
I seem to have created a broken file which can no longer render the preview or open params.

Steps that lead up to this:
* Drew path with pen tool
* Used "Stroke to Live Path Effect Satin"
* Duplicated paths and removed live stroke effect (This is the outline layer)
* After seeing preview no longer worked I ran "Convert Satin to Stroke" on one of the paths in the outline
* Error message came up

![Broken SVG](https://github.com/inkstitch/inkstitch/assets/6601505/ed51afd0-a84d-46c1-b2e8-3f0da375ac7b)

Error log:
```
Ink/Stitch Version: v3.0.1 (osx)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/convert_to_stroke.py", line 38, in effect
  File "lib/elements/satin_column.py", line 832, in center_line
  File "lib/debug.py", line 231, in decorated
  File "lib/elements/satin_column.py", line 898, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 629, in flattened_sections
  File "lib/elements/satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

```

**Comment by tyrosinase** [comment]
That should be fixed in a pre-release, but right now you can work around it by finding any objects that are single lines but flagged as a satin.

**Comment by Qwertie-** [comment]
How would I unflag them to make them regular running stitches?

**Comment by tyrosinase** [comment]
In Params, uncheck the selection on the Satin tab (or check the selection on the Running Stitch tab, they are linked). I'm not sure if Troubleshooting will find them on the current release, ISTR seeing it mentioned that it does on some of the pre-releases at least.

**Comment by tyrosinase** [comment]
(or, of course, if it's *supposed* to be a Satin, give it a second rail. Sometimes it happens when what should be two rails accidentally get joined together.)

**Comment by Qwertie-** [comment]
On this SVG the params tab was also not usable I believe. I ended up just deleting the layer and recreating it but using the satin to stroke tool first rather than removing the live path effect. I wonder if all of these issues are fixed in the latest development. Is there a guide to installing the latest dev version? I wouldn't mind testing it and reporting the results.

**Comment by tyrosinase** [comment]
You could mayyyybe have used Troubleshooting to clear params although I can't remember offhand if that's document-wide or if you can do it only on selected objects.

You can compile from branches somehow (that's above my pay grade) but also if you look on the main repo page under Releases there is just a wild number of test releases ready to go:

![image](https://github.com/inkstitch/inkstitch/assets/9473609/28e34384-fd97-4d16-8b89-647b4d90396d)

It's sometimes an adventure to decide which one to try out. There's quite a few different satin fixes in progress, and I'm not sure there's a release that incorporates more than one. The devs are pretty good about telling you whether a particular release is ready for testing, though. (I've been playing with tartans, myself - they're very cool. But they don't have the satin fixes, I don't think)

**Comment by kaalleen** [comment]
Any branch should be fine at the moment I think. This particular fix is pretty old, so it is included in all the dev releases.

**Comment by kaalleen** [comment]
I'll close this one. If you have more questions, you can still use this thread to post them.
