### ISSUE TITLE
Inkstitch not working after installing

### ISSUE THREAD

**Issue by ianv2026** [inkstitch/inkstitch#2821]
Hi there, I've recently installed InkStitch 1.29.1 on my old Macbook running Yosemite 10.10.5 with Inkscape 0.92.2. I downloaded InkStitch from this page https://github.com/inkstitch/inkstitch/releases/tag/v1.29.1, unzipped the folder and copied all the contents to the User Extensions folder. InkStitch shows up under my Extensions but when I try to open Params I get the error shown in the picture. I have removed the username from the path.

![Screen Shot 2024-04-02 at 9 33 07 PM](https://github.com/inkstitch/inkstitch/assets/79951031/1ee1e5e8-6912-4594-a468-872159afb4ce)

Thanks in advance for any help.

**Comment by kaalleen** [comment]
We never released a version which would work on Yosemite. The oldest macOS version we ever supported was El Capitan (which isn't supported in the latest release anymore). I suppose Ink/Stitch is just too young, sorry.
