### ISSUE TITLE
sponge stitch

### ISSUE THREAD

**Issue by cinkishop** [inkstitch/inkstitch#2824]
Hi all,
I'm new here and I hope to not be OT.
I'm learning to use inkscape and inkstitch and I would try to set up the sponge stitch (which I know is possible to embroider with the machine), but How?
Attached an example photo.

Thank you!
Cristina
![sponge](https://github.com/inkstitch/inkstitch/assets/166008976/c97c52f7-9b01-40d1-8468-050d2f843205)

**Comment by kaalleen** [comment]
For this stitch you'd need a special machine. The easiest way to mimic this would be to use microfiber cloth or a towel and use it as an appliqué.
