### ISSUE TITLE
save as .pes file could not be saved

### ISSUE THREAD

**Issue by msmith110** [inkstitch/inkstitch#2828]
every time I try to save a file as a copy in .pes format, it displays an error message that the file could not be saved. I redownloaded ink/stitch and it was not resolved. I have tried to clean up document, break apart fill objects, everything, and even tried it on simple objects. It was working less than 24 hours ago, but is not now not saving embroidery files. The file I am trying to save is simple with only two colors.

**Comment by tyrosinase** [comment]
Are you saving to removable media or a network drive by any chance? Inkscape is not thrilled about that; if you're using a USB drive you want to save to your hard drive and then copy to the stick.

If it's not that, what is the exact message it's giving you? Anything beyond "could not be saved"?

**Comment by msmith110** [comment]
I am saving it to my desktop which is linked to my icloud drive, but I also tried to save it to my documents which is not linked and it did not work. The error message attached. All it says is "could not be saved" 
![Screen Shot 2024-04-06 at 5 18 52 PM](https://github.com/inkstitch/inkstitch/assets/166256493/3672e469-dd6f-4414-8a4f-6dee6abbfffd)

**Comment by tyrosinase** [comment]
Hmm. Try saving it to a directory/folder without a space. That's been a problem in the past though I thought it had been fixed. Always possible it got reintroduced, though.

**Comment by kaalleen** [comment]
No further response. Closing.
You can still post your questions here or into a new issue.

**Comment by jaggre** [comment]
I'm having this same issue. I have tried saving it with all sorts of filenames and in various directories with and without spaces. Nothing seems to work.

**Comment by jaggre** [comment]
for anyone who comes looking for the solution later, I was able to resolve this by fully removing my inkstitch installation via the inkscape app preferences and reinstalling it.
