### ISSUE TITLE
Help Please!!

### ISSUE THREAD

**Issue by Mharris1543** [inkstitch/inkstitch#2829]
Hello, 
I’m trying to figure out this software. My main goal is to convert a jpg into a dst. I’ve tried everything. I have no idea how to finish this through because it keeps showing me these error messages…
![IMG_7053](https://github.com/inkstitch/inkstitch/assets/166259481/3a79dfc5-9f9b-406f-b4ff-f4f09865ea36)
![IMG_7054](https://github.com/inkstitch/inkstitch/assets/166259481/7972e5d8-a943-483d-9d34-5b8e93f36ab6)

**Comment by msmith110** [comment]
When I was first starting out, this tutorial on youtube was a LOT of help [https://www.youtube.com/watch?v=46kfuQWOPW0](url)

**Comment by Marif91** [comment]
Le commentaire est très clair : on ne convertit pas une image. On la traite d'abord pour la transformer en un fichier vectoriel et c'est la base du travail.
