### ISSUE TITLE
Backend Independent Run 

### ISSUE THREAD

**Issue by Simone2498** [inkstitch/inkstitch#2831]
I see that this software has a frontend part in Electron, and the backend provides all the computational functions. I'm wondering if this backend is structured in a way that can be run autonomously, passing the structures as parameters from another frontend different from Inkscape. I would like this project for my new hobby, but I wanted to prevent starting working on it and getting stuck after a few steps... :)

Thank you

**Comment by tyrosinase** [comment]
Yep, there's a page on it in the documentation: https://inkstitch.org/docs/command-line/
