### ISSUE TITLE
I can't see the translation, os windows, is that only me have this problem

### ISSUE THREAD

**Issue by abc8143** [inkstitch/inkstitch#2837]
Hi, dear friends, could you please take a look at this, I am confused for some days, this "msgfmt command not found" will influence translations or not?  this github action windows32 and 64 installation packages, I try many times to install, can't see the translation , is that only me have this problem

> bash bin/generate-translation-files
bin/generate-translation-files: line 10: msgfmt: command not found
bin/generate-translation-files: line 10: msgfmt: command not found
bin/generate-translation-files: line 10: msgfmt: command not found
...

only this word "edit" can see, 
![Snipaste_2024-04-10_03-23-57](https://github.com/inkstitch/inkstitch/assets/49285033/9380640c-49d0-45d9-b82f-c0e9386b0418)

**Comment by claudinepeyrat06** [comment]
i'm afraid it is simply because no one did the translation yet.

**Comment by abc8143** [comment]
> i'm afraid it is simply because no one did the translation yet.

no,,,no... I upload some translation last week, but if not set Chinese language, set another language is also only the word "edit" can see, is that only my machine have this problem? I really want to know (╥_╥)

**Comment by claudinepeyrat06** [comment]
if i set my inkscape language preference to chinese/CN, this is my screen : 
<img width="1165" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/0c8c0d64-d8a0-421f-ae51-b43322706450">
Hope it helps.

**Comment by abc8143** [comment]
> if i set my inkscape language preference to chinese/CN, this is my screen : <img alt="image" width="1165" src="https://private-user-images.githubusercontent.com/88194877/322636255-0c8c0d64-d8a0-421f-ae51-b43322706450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTMxMTcsIm5iZiI6MTcxMzI1MjgxNywicGF0aCI6Ii84ODE5NDg3Ny8zMjI2MzYyNTUtMGM4YzBkNjQtZDhhMC00MjFmLWFlNTEtYjQzMzIyNzA2NDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA3MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiN2UzNGM4NjFjYTVjNjM1Y2RlZmQxOTAxZjhjMDBiZjM5MjhhOTA3NjkyNThlMzMzNThiYWJlYTRjZDEyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHSj9nd2dd16_-RWF3cW-3cpgTdNcS8HIvPj1nXfyqc"> Hope it helps.


thank you, I think linux installation package is no problem, maybe this problem only exist on windows package,

**Comment by abc8143** [comment]
I think this "msgfmt" is the key to problem, but I don't know what to do, I have less knowledge about this 
![Snipaste_2024-04-16_15-37-02](https://github.com/inkstitch/inkstitch/assets/49285033/7b2d9252-c1c0-40c7-a714-9ed3aef31931)

**Comment by abc8143** [comment]
I'm really confused, the git bash on github action there is no the file "msgfmt.exe", but my machine git bash it has this file, no wonder I don't have this message output when I makefile local
` ls "C:\Program Files\Git\usr\bin"`
![Snipaste_2024-04-18_02-57-40](https://github.com/inkstitch/inkstitch/assets/49285033/ae8ead53-59f5-41b0-b4ff-55c42bdef1c3)

I also confused is that I rememer the installtion package can see translation is all correct last year, is that because this git bash version is change?

**Comment by abc8143** [comment]
great i find it
![Snipaste_2024-04-18_12-39-07](https://github.com/inkstitch/inkstitch/assets/49285033/64fa84ab-9e1c-4aaf-80cf-f6e441cdd570)

**Comment by rejbasket** [comment]
It seems that latest version of git for windows doesn't ship with msgfmt.exe, which is part of gnu gettext. The previous release versions includes msgfmt.exe. The git-for-windows/setup-git-for-windows-sdk@v1 is the proper fix for this issue for github's windows build runner. For windows manual install or local build downgrade git for windows to version 2.43.0. https://github.com/git-for-windows/git/releases/tag/v2.43.0.windows.1

> great i find it ![Snipaste_2024-04-18_12-39-07](https://private-user-images.githubusercontent.com/49285033/323467193-64fa84ab-9e1c-4aaf-80cf-f6e441cdd570.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Mzk2NDcsIm5iZiI6MTcxMzQzOTM0NywicGF0aCI6Ii80OTI4NTAzMy8zMjM0NjcxOTMtNjRmYTg0YWItOWUxYy00YWFmLTgwY2YtZjZlNDQxY2RkNTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExMjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmRmNDkxMTQzYWM5MTQ4ZTU3M2ZmZDY0ZmE5NTIzNGZlOGNjOTQ2ZmUxMGY3MGQzYzIwNzk1NmNkZmZlMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXZ9mxtc3Lp6jWVwiJVQmpCX4xEpLobDHaJuoLmYyJ0)

**Comment by abc8143** [comment]
> It seems that latest version of git for windows doesn't ship with msgfmt.exe, which is part of gnu gettext. The previous release versions includes msgfmt.exe. The git-for-windows/setup-git-for-windows-sdk@v1 is the proper fix for this issue for github's windows build runner. For windows manual install or local build downgrade git for windows to version 2.43.0. https://github.com/git-for-windows/git/releases/tag/v2.43.0.windows.1
> 
> > great i find it ![Snipaste_2024-04-18_12-39-07](https://private-user-images.githubusercontent.com/49285033/323467193-64fa84ab-9e1c-4aaf-80cf-f6e441cdd570.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0Mzk2NDcsIm5iZiI6MTcxMzQzOTM0NywicGF0aCI6Ii80OTI4NTAzMy8zMjM0NjcxOTMtNjRmYTg0YWItOWUxYy00YWFmLTgwY2YtZjZlNDQxY2RkNTcwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExMjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmRmNDkxMTQzYWM5MTQ4ZTU3M2ZmZDY0ZmE5NTIzNGZlOGNjOTQ2ZmUxMGY3MGQzYzIwNzk1NmNkZmZlMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXZ9mxtc3Lp6jWVwiJVQmpCX4xEpLobDHaJuoLmYyJ0)

I don't know I never been successful build on local (╥_╥)
![Snipaste_2024-04-18_20-28-32](https://github.com/inkstitch/inkstitch/assets/49285033/564fb442-1f61-4927-b651-cbcae41e2506)

**Comment by abc8143** [comment]
every time I download from github action, it can always build success,
