### ISSUE TITLE
"A satin column consists out of two rails and one or more rungs"

### ISSUE THREAD

**Issue by Qwertie-** [inkstitch/inkstitch#2841]
I've got this file which I can't render a preview of anymore, seemingly the satin stitches are broken. They were created with "Stroke to live path effect satin" and then the problem was immediately occuring

Error message when opening params:

> Failed on  path7: A satin column consists out of two rails and one or more rungs. This satin column may have a different setup.
> 
> Please run Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects. This will indicate the errorneus position.
> 

File:
![Plushie footpaws](https://github.com/inkstitch/inkstitch/assets/6601505/0a6b14f7-085b-45b5-a270-0c22c6f650e4)

**Comment by claudinepeyrat06** [comment]
Select path7 show paths effects
<img width="1408" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/657f065b-869d-4492-95fd-783d4c989083">
then increase the value in Fuse nearby ends till you see the gap in the rails  are closed.
<img width="1112" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/8421b5dd-16e2-43e1-b1f8-3cfb3ce9bd0b">
you probably need that for each of your satin path

**Comment by Qwertie-** [comment]
Ah right, I thought "repeated, stretched" would fuse the ends. This has got the preview working again, but the generated preview is coming out really weird for that bottom path7

<img width="803" alt="Screenshot 2024-04-17 at 08 38 29" src="https://github.com/inkstitch/inkstitch/assets/6601505/06e2abc7-b9f5-4dde-baa1-1d861f8c92ab">

Modified file:
![Plushie footpaws](https://github.com/inkstitch/inkstitch/assets/6601505/8be8d198-32b4-4db2-9f12-ec082ba12509)

**Comment by gusvisser** [comment]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/eddb2bcb-e932-4be7-91b6-b8e75e6f01d4)
Different fuse value is needed for different objects

Gus Visser

**Comment by kaalleen** [comment]
Maybe we should set it to a higher value by default? Is there any downside to it?
