### ISSUE TITLE
Circular fills aren't centered?

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2842]
Maybe it's my imagination and it never worked that way, but on dev build `tartan (linux)` circular fills aren't always centered.

A file like:

![circularfill](https://github.com/inkstitch/inkstitch/assets/9473609/dd7881cc-5209-48ff-a43c-09ad81a5c2e5)

used to be centered on the circles, even the black one (with the highlights cut out). Now I get:

![image](https://github.com/inkstitch/inkstitch/assets/9473609/68ef79bd-ef07-4129-b0d5-f5a7ab8cd186)

The center of the black shape is juuuuust slightly down and to the left. I can manually set the center, of course, but I haven't on older files and now I'm wondering: did something change, or have I just never encountered this before (does the center shift if the actual center is an open space or something and maybe I've just never done that before)?

**Comment by kaalleen** [comment]
Oh, this is the geometrical center (center of mass). You can set the center of the circle as a midpoint for rendering with the target command.

**Comment by tyrosinase** [comment]
Ah, so the internal gaps change this? I assumed it was just based on the outer edge, I guess. (And yep, I put in targets. Though then I discovered that targets have different setups than every other command, and made some of my post-processing utils flip out.)

**Comment by kaalleen** [comment]
Uhm, sorry for making your post process crazy ...

I think we can just add the geometrical center info tho the documentation?

**Comment by kaalleen** [comment]
Documented...
