### ISSUE TITLE
# stitches In Print PDF

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#285]
When I tested the stitch numbers for the simulator I found an issue with the print pdf preview.

Steps to reproduce:
* create a manual stitch path (count the nodes - this is the actual number of stitches)
* run embroidery > print
* compare # stitches to what you've counted

There is one too many in the print preview?! I might be wrong, because I got very confused by this issue during my process... but I tested with only two nodes and it showed three stitches in the preview.

**Comment by lexelby** [comment]
I can't reproduce this. :(  I could totally believe that such a bug could exist, but I can't seem to make it happen on my machine.  Can you post an example SVG here?

**Comment by kaalleen** [comment]
That's odd. I cannot reproduce it myself, although I was testing it several times, before opening this issue here. Well, I will close it now.

**Comment by lexelby** [comment]
I'm wondering if maybe one of your path nodes was doubled?  Inkscape makes it difficult to tell if that has happened...

**Comment by kaalleen** [comment]
Hm, I don't think so, because I double checked the node number in the status bar of Inkscape. I think, it would count doubled nodes. But for now, I think it was something that I did wrong in the test file. I should start to save my files, when I discover a strange behavior.
