### ISSUE TITLE
Recover automatically from disk cache corruption 

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#2867]
_Originally posted by @bianchifan in https://github.com/inkstitch/inkstitch/issues/2741#issuecomment-2045833572_

I wiped out the SSD of my XPS 13 from scratch with the UEFI Firmware in UEFI mode.., at least 13 partitons.

1. Trisquel could be installed easily but does not run due to lack of "free" WLAN drivers (closed firmware is nneded)
2. Ubuntu fresh install works so far, Inkscape runs perfect, InkStitch not :(
3. Same with Linux Mint 21.3
4. Same with Suse Tumbleweed

The tools section (Fills, Strike, Satin) seems to work, but when when stitches should be generated/simlated a database error occurs.
![Bildschirmfoto vom 2024-04-09 20-18-59](https://github.com/inkstitch/inkstitch/assets/17491743/9a04a58e-a73c-4094-a073-40463c5188c6)

Maybe caused by the GPU driver... on my old Dell Studio XPS 1340 InkStitch works fine!
( My XPS 15 is still disassembled)

**Comment by bianchifan** [comment]
This diskcache issue only occurs on my Dell XPS 13 9370 with Intel core I7-8550.
It also occurs on a Lenovo X1 Yoga, same CPU.

It does not occur neither on my XPS 15 nor on my old Studio XPS 1340.

**Comment by lexelby** [comment]
This may not necessarily have to do with your wiping and reinstalling.  It seems that your cache became corrupted.  Who knows how, but this is clearly a thing that can happen, so we should handle it better.

Ink/Stitch should catch this error and do some kind of automatic recovery, probably along the lines of deleting the cache and creating a new one

**Comment by bianchifan** [comment]
> This may not necessarily have to do with your wiping and reinstalling.

I just wanted to state a clean start from scratch.

**Comment by kaalleen** [comment]
Can you copy and paste the complete error message in here?
