### ISSUE TITLE
Proportionnal pull compensation for autofill

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#2870]
I see a lot of wonderfull new functions for the coming version but nothing about proportionnal pull compensation for autofill. It exists for satin and it is very helpfull. Why not for autofill? It is so important for beginners who get always gap between objects. It is also very helpfull for everybody to get good quality embroidery. Is it not important?
I edit my post because It was stupid without proportionnal pull compensation. 
It is terribly missing if we want to compare Inkstitch to other softwares.

**Comment by gusvisser** [comment]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/1832d947-8316-49d8-bdd0-2c950264400a)
There is pull compensation in the params for auto fill it is only called different
And inkscape has also tools available for expanding the object by set values of your choice

Gus Visser

**Comment by Augusa** [comment]
You are right. I mean proportionnal compensation. I will change my post.

________________________________
De : gusvisser ***@***.***>
Envoyé : jeudi 2 mai 2024 13:50
À : inkstitch/inkstitch ***@***.***>
Cc : Augusa ***@***.***>; Author ***@***.***>
Objet : Re: [inkstitch/inkstitch] Pull compensation for autofill (Issue #2870)


image.png (view on web)<https://github.com/inkstitch/inkstitch/assets/85417086/1832d947-8316-49d8-bdd0-2c950264400a>
There is pull compensation in the params for auto fill it is only called different
And inkscape has also tools available for expanding the object by set values of your choice

Gus Visser

**Comment by lexelby** [comment]
@Augusa I don't know what proportional pull compensation for fill actually means.  Could you draw a picture?

**Comment by kaalleen** [comment]
@lexelby Have a look over here: #178

**Comment by lexelby** [comment]
Looks like I made #179 and then it kind of got subsumed accidentally and closed?  But yeah, this totally seems doable, and 6 years is way too long to wait :)
