### ISSUE TITLE
Linux: Stitch plan: Realistic preview (png) doesn't work

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2905]
My first thread was closed while I was writing an answer..

> Does it update correctly with the next animated stitch?
Cannot test yet 'cause I've just installed a hot glueed System:
XPS 15 sticked together free wired with LInux Mint Live system from USB..

Just checked your special version for the upcoming meeting
 
> There is no realistic view mode in the simulator anymore. It can now be found in the stitch plan preview.
THX for pointing out, I've never used a stitch plan, I still do not understand why...
 
>  3. Missing switch for rendering jumps
>  I can see it in your images. It's the frog.
OK, so only one switch for both so far, for jumps and rendering jumps

Forgotten..
On my old XPS Studio with Core2Duo both cores are running.
On my new XPSs with Core I7 only ONE thread out of eight is running with InkStitch
Most other soft uses all four cores with min. one thread...
![Screenshot from 2024-05-13 19-18-48](https://github.com/inkstitch/inkstitch/assets/17491743/987c91a0-f5d0-4852-a2cd-b58953a6c636)

New faults with meeting version:
1. Stitch plan realistic fails with crash
2. Stitch plan realistic high quality fails with crash
 
![Screenshot from 2024-05-13 19-04-13](https://github.com/inkstitch/inkstitch/assets/17491743/e10a6a68-ce37-483f-90bd-11700ab1e828)

Realistic Vector is running (quite fast)

When simulator is started with an active stitch plan on the screen the sim also shows a realistic view but with poor quality and much too much jumps...
![Screenshot from 2024-05-13 19-20-46](https://github.com/inkstitch/inkstitch/assets/17491743/37595f12-415d-4119-afce-46855c08f30e)

**Comment by Marif91** [comment]
(Menu Paramètres) quelle valeur as-tu choisie pour tes sauts. 57000 points pour un petit gecko, c'est énorme !

**Comment by kaalleen** [comment]
> On my new XPSs with Core I7 only ONE thread out of eight is running with InkStitch

Ink/Stitch doesn't do multi-threading yet. There is a open request for that somewhere in the issues.

> Stitch plan realistic fails with crash

Thank you for pointing it out. I renamed your issue to follow up on this particular one. This is only happening on Linux in the packaged version. Not an easy one to fix.

> When simulator is started with an active stitch plan on the screen the sim also shows a realistic view but with poor quality and much too much jumps...

It renders the shapes of the realistic preview. I think we should add an option to apply an ignore layer command right away. Nobody wants to stitch out the realistic preview shapes :O
