### ISSUE TITLE
do_contour_underlay: IndexError: list index out of range (in dev tartan)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2914]
Got an unexpected oddity after I rotated a file to fit the hoop: it broke a contour BUT only when the item is grouped. (I wanted to keep it grouped since it's cloned in the full file.)

Note that I'm on a fairly outdated dev version, so if it's not happening on other versions I'll just grab a newer one.

```
Debian GNU/Linux 12 (bookworm)

Ink/Stitch Version: tartan (linux)

Traceback (most recent call last):
  File "lib/elements/element.py", line 608, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 574, in embroider
  File "lib/elements/element.py", line 647, in validate
  File "lib/elements/satin_column.py", line 700, in validation_errors
  File "lib/elements/satin_column.py", line 1519, in to_stitch_groups
  File "lib/elements/satin_column.py", line 1126, in do_contour_underlay
IndexError: list index out of range
```

And here is de bug:

![Debug](https://github.com/inkstitch/inkstitch/assets/9473609/8ef446b7-4fa9-4a83-b4aa-618cdf8fb7c5)

(Google Noto Emoji licensing, if anybody wants to use it. Note that you'll want to change the angle of the stripe fills if you change the orientation; wish that happened automatically but I know why it doesn't.)

**Comment by tyrosinase** [comment]
Oh, it isn't stitching out the clones, I must have a version without the clone fixes in it. Not sure if that's relevant (since it still crashes after the clones are deleted) but I guess I'm gonna upgrade regardless. I'll let you know what happens on whatever version I land on.

**Comment by kaalleen** [comment]
Thank you for the error report.

Problem seems to be path artifacts in the satins with zero length.
![Bildschirmfoto vom 2024-05-17 09-09-22](https://github.com/inkstitch/inkstitch/assets/36401965/0afa0c43-e6d0-432e-b5d7-78a5049ca085)

**Comment by tyrosinase** [comment]
Ah ha, thanks. Yep, the ever-popular "svg not produced in Inkscape has weird artifacts" issue. (Dang, looks like Inkscape proudly stomps on any previous source identification, otherwise I'd say that would be a handy thing to have Ink/Stitch put in the error message.)

I ungrouped it specifically to look for that kind of thing and then got distracted by the fact that it worked, ungrouped. (Which is still weird.)
