### ISSUE TITLE
bug dans le pdf

### ISSUE THREAD

**Issue by besnier-crea** [inkstitch/inkstitch#2919]
J'ai un bug au niveau du pdf de mon fichier. Les traverses apparaissent sur le pdf mais pas sur la visualisation dans paramètres. Une autre personne a testé mon fichier et ça fait la même chose chez elle aussi. Comme je débute dans inkstich, elle a vérifié mon fichier et n'a pas trouvé d'où venait le problème.  Elle m'a donc conseillé de venir vous en informer. Un grand merci aux développeur pour ce super travail que vous faites. 
![Capture d’écran 2024-05-15 à 21 14 28](https://github.com/inkstitch/inkstitch/assets/170090552/35d41eb3-0458-42d9-9fc2-137b71ab3705)
![Capture d’écran 2024-05-16 à 08 06 14](https://github.com/inkstitch/inkstitch/assets/170090552/b6e07648-aa59-4172-a036-557b881deab4)

**Comment by kaalleen** [comment]
Would you mind to show us the svg file?

**Comment by besnier-crea** [comment]
Voilà le fichier
![OISEAU FLEUR](https://github.com/inkstitch/inkstitch/assets/170090552/ac596130-dde8-4c31-9b51-c511aa6d7c15)

**Comment by kaalleen** [comment]
Thanks for the file and sorry for the trouble. This shoudn't happen, but luckily it is easy to fix for you until we get to fix the code.
The groups that are not within a layer do have the issue. So, if you move them all into a layer or convert them into a layer, you'll be fine.

**Comment by besnier-crea** [comment]
génial j'ai ajouté les calques et nickel. Merci beaucoup et bravo pour votre super travail ! 
![Capture d’écran 2024-05-19 à 07 37 01](https://github.com/inkstitch/inkstitch/assets/170090552/4875610d-1f19-4229-83ec-2b0c4819352c)

**Comment by besnier-crea** [comment]
![Capture d’écran 2024-05-19 à 07 39 24](https://github.com/inkstitch/inkstitch/assets/170090552/fde0867d-3598-4d19-9f21-01dd2ea9951d)

**Comment by kaalleen** [comment]
Thank you for the feedback and for reporting the issue. It has been very helpful!
