### ISSUE TITLE
Pattern are difficult to see with the stitchplan

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#2932]
I am trying pattern with the stitchplan in future version and the result looks to be very difficult to use. I send you my file and  a lot of pictures made with the current version in an article I wrote on patterns. It would be impossible with future version. 
Beginners will probably think the feature is not working and for everybody it is impossible to judje the result even with the best quality of stitchplan
![testtexture1](https://github.com/inkstitch/inkstitch/assets/54963659/71e4e79c-73ff-4276-8900-67d4f08a7295)
https://lyogau.over-blog.com/2022/01/nouveautes-inkstitch-2.1.html

**Comment by kaalleen** [comment]
Do you have better results with the realistic vector rendering mode?

**Comment by Augusa** [comment]
It does not produce better view and it is very slow. It is difficult to use if you want to modify very precisely. You have to open several times to see your improvements.

**Comment by gusvisser** [comment]
I also have to agree that the old version realistic preview and simulator is way better then in the development version

**Comment by tyrosinase** [comment]
Where even is the realistic preview now? I was going to try it out but I don't seem to have a realistic option at all (this is with satin-second-trial)

![image](https://github.com/inkstitch/inkstitch/assets/9473609/13ac5f6c-cd18-436a-8f34-d91c42e4d062)

**Comment by gusvisser** [comment]
It is in the stichplan preview and it has multiple options for the rendering in there

Gus Visser

**Comment by capellancitizen** [comment]
The changes to realistic rendering are my fault, unfortunately. I changed the filter to be faster and tried to keep it close enough to the original appearance, but if it looks that much worse for these applications it should be tweaked more. I'm busy for the weekend but I'll try to take a look at it later this week.

**Comment by tyrosinase** [comment]
> It is in the stichplan preview and it has multiple options for the rendering in there

Ah, thanks. A menu option I clearly never, ever use (except once in a blue moon when I want to edit the manual-stitch result for some effect).

**Comment by bianchifan** [comment]
> Beginners will probably think the feature is not working and for everybody it is impossible to judje the result even with the best quality of stitchplan ![testtexture1](https://private-user-images.githubusercontent.com/

Yeah!!
You are absolutely right.
No way to find some helpful information out of it, much much too fat.

**Comment by capellancitizen** [comment]
[patterns.zip](https://github.com/user-attachments/files/15528061/patterns.zip)
Older-style rendering:
![pattern-oldrealistic](https://github.com/inkstitch/inkstitch/assets/5505503/cb75ae8c-c154-4c4d-9a33-8c6069f72eae)
Newer-style rendering:
![pattern-newrealistic](https://github.com/inkstitch/inkstitch/assets/5505503/192b09fe-1668-4368-b904-142624b4379d)

Hm. Maybe just tweaking the lighting could get us some better contrasting results like the original rendering, but it does end up with a kinda moire-ish effect to it just by virtue of having so many stitches with their own lighting so close. I'll try to tweak it some and see if I can get something nicer.
