### ISSUE TITLE
Convert Line to Satin Crash

### ISSUE THREAD

**Issue by aflanders7** [inkstitch/inkstitch#2943]
When I click "cancel" after converting a line to satin, I get an error message saying that "Inkscape has crashed and will now close."  If I do not click cancel, there are no issues and the path correctly converts to satin stitch. I have tested this on several paths within different files and get the same result. The paths I have tried and resulted in the crash all consist of simple lines with multiple nodes. The crash only appears to occur if I click cancel before the process finishes running. Other times when I am delayed to click cancel, there is no crash and the line still ends up converting to satin.

**Comment by kaalleen** [comment]
Convert line to satin doesn't have a cancel button. Can you explain your exact steps?

**Comment by blalbaqr332** [comment]
Did you check if your Inkscape and Ink/Stitch are fully updated? Try reducing the complexity of your paths by minimizing the number of nodes, as complex paths can sometimes cause instability. Additionally, avoid clicking "cancel" during the conversion process to prevent crashes; instead, let the process complete

**Comment by kaalleen** [comment]
No further explanation. I'm afraid we won't be able to reproduce the crash with the given info. Closing.
