### ISSUE TITLE
Problems with the realistic previews of current dev versions

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2945]
The realistic preview works with small designs for me but with more complex designs, esp. sandwiched layers, I receive faults and crashes.
crash: program slips away..
Fault: progaram shows a message and stays alive ;)
Not all of them are reproducible.
I had several crashes with inkscape itself, libg, libgio, libgtk ....
I had several crashes with shapely: division by zero, unfortunately i couldn't catch them.

Two faults are reproducible, they appeared after I did some rework on my Kielux 12cm Disk when trying to do a non-vector rendering: GLIBCXX not found!

![Bildschirmfoto vom 2024-05-27 19-12-57](https://github.com/inkstitch/inkstitch/assets/17491743/46c42fb5-9ccf-408b-a43c-6995e28b081c)

Current version of my Lielux 12cm disk

![22_Kielux_12cm](https://github.com/inkstitch/inkstitch/assets/17491743/8a645441-580e-452a-821f-7548d0353046)

**Comment by kaalleen** [comment]
I think that's a problem of the older treffen version. There has been an update to that very same version or other newer dev versions. It should be fixed by now.

**Comment by kaalleen** [comment]
Since I believe the issue has been fixed in current main, I'll close it. Please complain if I am wrong.
