### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#295]
For reference: [Python Error OSX](https://github.com/inkstitch/inkstitch/issues/275)
Here we can gather the information and experience with the various macOS versions.
Furthermore, it should be noted here (if desired), which macOS versions we want to support.

At the moment, as far as we know, Ink/Stitch works best on macOS HighSierra (10.13+).

Is there another macOS version we should consider?

**Comment by wwderw** [comment]
The question is, how hard is it going to be to provide support retroactively for Mac?  

I certainly wouldn't do further back then what is officially supported by Apple, but with Mojave coming out (this fall?), that would mean Sierra soon would be the oldest that Apple will support?  I think their support cycle stops at n-2?

**Comment by lexelby** [comment]
Hi @stitchtry, welcome to Ink/Stitch!  I'm sorry you're having trouble.  I'm sorry to say that I don't know much about Macs, so it's hard for me to debug problems. :(

Does it work if you delete everything and install an earlier version?

**Comment by rigelrozanski** [comment]
Any news on installation or support with mac 10.14.1 ? - I'll give it a whirl if nobody knows yet

**Comment by Stitchtry** [comment]
Thanks @lexelby for your answer. 
As I tried Inkstitch, I had two versions, because there was an update of Inktitch in these days. But both didn't run. 
Now I have the plan to look for another computer for using inkstitch (and possibly some other programs witch didn't work with my mac), maybe learning Linux, maybe trying it with windows. But this is a big projekt for me so it takes time. First my son must find the power cable for the Hardware, : ) then I have to unterstand the system. 
Presently it is not as essential for me to use Inkstitch, so it's not the highest priority.

**Comment by Tinmonkey** [comment]
@rigelrozanski did you have any luck running this on 10.14.1?

**Comment by rigelrozanski** [comment]
yup it works!

**Comment by theepaleking** [comment]
having issues with the install, Inkstitch does not appear in the extension pulldown 
![screen shot 2019-01-05 at 12 24 46 am](https://user-images.githubusercontent.com/46391727/50720722-5934c680-1080-11e9-9c40-5dd79e99761b.png)

currently running mojave 10.14.2
![screen shot 2019-01-05 at 12 21 25 am](https://user-images.githubusercontent.com/46391727/50720701-e6c3e680-107f-11e9-926e-c03575a0a510.png)

The instructions seem straight forward enough
download the most current version of Inkscape 
![screen shot 2019-01-05 at 12 23 26 am](https://user-images.githubusercontent.com/46391727/50720716-373b4400-1080-11e9-8db7-04097a714ab8.png)

unpack the rar file in .config/inkscape/extensions
![screen shot 2019-01-05 at 12 22 28 am](https://user-images.githubusercontent.com/46391727/50720731-75386800-1080-11e9-9aa9-7836cd5c4cec.png)

and if that fails, drop it in Contents/Resources/share/inkscape/extensions
![screen shot 2019-01-05 at 12 30 49 am](https://user-images.githubusercontent.com/46391727/50720772-45d62b00-1081-11e9-8e5a-44e81a11f425.png)

im stuck in a corner over here... any suggestions?
thanks

**Comment by kaalleen** [comment]
Ups, there went something wrong.
Seems like you missed the .inx-files, they are important to keep.

I copied your file structure and modified it, so you can see how it should look like:
![inkstitch-files](https://user-images.githubusercontent.com/36401965/50723057-c7a57300-10d8-11e9-8bee-31ec3da82cb3.png)

Hope you have more luck this time ;)

**Comment by theepaleking** [comment]
@kaalleen it worked!! You're a GEM! I appreciate you a metric elephant ton!

**Comment by kaalleen** [comment]
I am a bit stupid about this, but could this link help to get Ink/Stitch working on various macOS versions?

I mean, could we use the osx_image key to force specific macOS versions - or does it cause trouble with the python version we are using?

https://docs.travis-ci.com/user/reference/osx#macos-version

I believe these are just the xcode variants @AkiraNorthstar was talking about.
Nevertheless, I thought it might help to mention it here.

**Comment by lexelby** [comment]
That might help, but I really have no idea.  I don't have a Mac to test on so it's really hard for me to work on the mac support :(

**Comment by kaalleen** [comment]
I will close this issue now. We have moved too far away from it by now.
macOS users can get recent information on our website.
