### ISSUE TITLE
Issue with Auto-Generated Lock Stitches in Ink/Stitch 3.0.1

### ISSUE THREAD

**Issue by blalbaqr332** [inkstitch/inkstitch#2951]
Hi everyone,

I'm experiencing an issue with Ink/Stitch 3.0.1 on Windows where the auto-generated lock stitches at the beginning and end of stitch sequences don't seem to be working correctly. Specifically, I'm noticing that:

Lock Stitches at Start: The lock stitches at the start of a sequence are either missing or not placed correctly, leading to loose threads that come undone easily.

Lock Stitches at End: The lock stitches at the end of a sequence appear to be overlapping with other stitches, causing thread buildup and a noticeable bump in the design.

I've tried adjusting the lock stitch settings in the parameters, but the issue persists. Here are the steps I've taken and the settings I'm using:

- Ensured the "Lock Stitches" option is enabled in the parameters.
- Adjusted the length and number of lock stitches.
- Tried different stitch types (running, satin, fill) to see if the issue is specific to one type.

Despite these adjustments, the problem remains. Has anyone else encountered similar issues with lock stitches in Ink/Stitch? Are there any specific settings or techniques to ensure proper placement and effectiveness of lock stitches? Any guidance or suggestions would be greatly appreciated.

Thanks in advance for your help!

**Comment by kaalleen** [comment]
Just to make sure. Did you read this page of the documentation?
https://inkstitch.org/docs/stitches/lock-stitches/

No lock stitches:
* Compare the distance between paths and with your minimum jump stitch length setting
* If you want to enforce lock stitches despite the minimum jump stitch length, enable force lock stitches

Misplaced lock stitches
* Can you provide an example of the result, preferably within an svg file

**Comment by blalbaqr332** [comment]
Thanks for the document link. It solved my issue. I appreciate your help.
