### ISSUE TITLE
message erreur pour saut en trait

### ISSUE THREAD

**Issue by besnier-crea** [inkstitch/inkstitch#2961]
Bonjour, j'ai des colonnes satins et je souhaite mettre les sauts en traits pour pouvoir les cacher derrière mais j'ai un message d'erreur et rien ne se passe. Ça m'est déjà arrivé sur un doc où seulement quelques sauts se sont matérialiser en traits . Je ne sais pas comment régler ce problème autrement.
![Capture d’écran 2024-06-03 à 11 42 28](https://github.com/inkstitch/inkstitch/assets/170090552/7ca0d32e-144f-4046-a9b9-5423f0bffeff)
![cup cake2 10x10](https://github.com/inkstitch/inkstitch/assets/170090552/da918f45-159c-4aff-bdb5-7cf722f332ec)

**Comment by besnier-crea** [comment]
je viens de télécharger une version plus récente et toujours le même message d'erreur. 
![Capture d’écran 2024-06-03 à 18 57 39](https://github.com/inkstitch/inkstitch/assets/170090552/94308706-89a5-43fd-ac3a-87b0828a101e)

**Comment by Marif91** [comment]
Je travaille avec besnier-crea, je constate encore le même problème avec la toute dernière version. Je joins le fichier de la partie qui pose problème et le message d'erreur :
ProductName:		macOS
ProductVersion:		13.6.1
BuildVersion:		22G313

Ink/Stitch Version: update-tartan-gui (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/jump_to_stroke.py", line 49, in effect
  File "lib/elements/fill_stitch.py", line 881, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 731, in shape
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/_geometry.py", line 805, in set_precision
shapely.errors.GEOSException: TopologyException: unable to assign free hole to a shell at 108.71884973260001 308.99342187600001

![cup-besnier-crea](https://github.com/inkstitch/inkstitch/assets/65076100/68038b5c-87b9-4c4b-a421-c2e0c070d203)

**Comment by kaalleen** [comment]
Thanks for posting the svg and the error message text.
I noticed that bug already and updated the update tartan gui branch.
Would you mind to test if it solves your problem (just redownload and install)?

**Comment by Marif91** [comment]
Merci Kalleen, ça fonctionne sur la dernière version (update tartan gui) !
