### ISSUE TITLE
Plan de broderie et export pdf

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#2966]
Quand un plan de broderie est présent sur la feuille de travail, l'export pdf n'affiche plus que ce plan de broderie. Les étapes de travail ne sont pas affichées.
Est-ce que l'export pdf pourrait ignorer le plan de broderie (je suis sur la version **dev-build-kaalleen-update-tartan-gui**) ?
<img width="911" alt="Capture d’écran 2024-06-04 à 21 38 32" src="https://github.com/inkstitch/inkstitch/assets/65076100/b16152ff-6a87-4fd9-91e2-c2c0f73fd938">
NB il s'agit du même fichier que hier pour le problème des sauts en traits.

**Comment by kaalleen** [comment]
Thank you for pointing this out. I prepared a fix.
