### ISSUE TITLE
Re-integrate Extension: Reorder by selection for Inkscape 1.0

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#297]
I have just found [release notes inkscape 0.93](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.93) UNRELEASED!
The whole context and further information can be found here:
[Boston Hackfest (in english)](https://inkscape.org/en/news/2018/05/22/2018-boston-inkscape-hackfest/)
[Boston Hackfest (in deutsch)](https://inkscape.org/de/news/2018/05/22/2018-boston-inkscape-hackfest-de/)
EDIT: [Inkscape 0.92.4 is a stability and bugfix release](http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92.4) UNRELEASED!

**Comment by lexelby** [comment]
As a note, 0.93 isn't released yet.  I'm pretty excited about the ability to rotate the canvas while you work on it.  xverbs and the embroidery LPE look interesting too.

This feature of 0.92.4 means I'll be installing it as soon as it's released:

> * Previously, the current selection was lost after running an extension. Now, whenever possible, Inkscape will try to keep the objects selected.

If that works as advertised we should definitely update our recommendation to 0.92.4!

This is also a bug that's especially problematic for embroidery, and I'm excited to see it fixed:

> * Deselecting a path with many nodes could take a long time

Okay, actually, I couldn't wait and now I'm running the bleeding-edge unreleased version :D

**Comment by AkiraNorthstar** [comment]
Had to mark it as "not released".
There are some things that are interesting - or would be interesting:
Object -> Path = 1x Contour + 1x Fill = 2 separated (independent) paths ....

**Comment by wwderw** [comment]
Just saw that the AppImage was released of this version.  I'll have to see how it handles.

**Comment by Moini** [comment]
Inkscape 0.93 has been renamed to Inkscape 1.0. 

For @lexelby: there are a lot of changes to extension handling, and I think they aren't finished yet. You can find the new extensions repository at https://gitlab.com/inkscape/extensions/ and follow development there.

The Inkscape command line is currently becoming more powerful, no idea how fast that development will go.

**Comment by lexelby** [comment]
Thanks for the heads-up, @Moini.

> For @lexelby: there are a lot of changes to extension handling, and I think they aren't finished yet. You can find the new extensions repository at gitlab.com/inkscape/extensions and follow development there.

Due to the way we package (using pyinstaller), Ink/Stitch fortunately will continue working even when Inkscape 1.0 is released.  The changes for extensions are entirely in the python helper libraries that Inkscape bundles.  The actual communication protocol between extensions and Inkscape remains the same.  That's great for us because it means we don't have to rush to support v1.0, and we don't have to sacrifice support for versions < 1.0.

This also means that we can switch over to the new Inkscape python helper libraries whenever we want, and they'll work fine with the _old_ Inkscape, too!

So far, the new python libraries are promising, with a few new features that we had to implement ourselves in Ink/Stitch.  That said, our implementations work fine, and transitioning to the new helper libraries would be a significant undertaking, so I'm in no rush to do it.  We'd also have to switch to Python 3, and who knows what trouble that might cause with PyInstaller...

**Comment by Moini** [comment]
Glad to read that :) 

Your extension is by far the most complex Inkscape extension I've ever seen, so it's good that this won't require any adjustments.

**Comment by AkiraNorthstar** [comment]
New Inkscape version available:
[Inkscape 0.92.4](https://inkscape.org/release/inkscape-0.92.4/)

**Comment by wwderw** [comment]
I saw that.

I was thinking about experimenting with the alpha of 1.0.  A lot of improvements under the hood for performance.  Nice thing about using both as an AppImage, I'm able to have both on my system without conflict.

**Comment by Moini** [comment]
For me, the AppImage still uses the same preferences file - which is not intended by developers, though.

**Comment by wwderw** [comment]
Hmm, I hadn't noticed that.  It picked up on some preferences based on some differences on my system compared to .92.

I have noticed some things though, but as of now, I'm chalking it up to running an Alpha version.  At this point, not a deal breaker, but if it's the same thing with stable, that may be something else.

**Comment by kaalleen** [comment]
>> Extensions developers can again rely on the order of inkex.Effect.selected.iteritems() reflecting the user's selection order properly

Uih, does this mean, we could have a reorder extension again?

**Comment by lexelby** [comment]
Both of these also sound really great for us:

> Previously, the current selection was lost after running an extension. Now, whenever possible, Inkscape will try to keep the objects selected.

> Extensions work faster now in documents consisting of a large number of objects. [To be confirmed.]

**Comment by Moini** [comment]
Oops, seems I need to remove the 'to be confirmed part' :flushed: . Yes, it's definitely faster.

Haven't tested the selection order myself, but would be glad if someone could.

**Comment by lexelby** [comment]
I tested on a pre-release version a few months back, and it worked great!  Barring a regression, it's good :)

**Comment by Moini** [comment]
Thanks, @lexelby :)
