### ISSUE TITLE
Cannot open application

### ISSUE THREAD

**Issue by Maufam1** [inkstitch/inkstitch#2971]
I am installing Ink/Stitch on Windows for the first time, but when I try to open up the application I receive the following error message. Please advise on how to resolve the issue. 

![image](https://github.com/inkstitch/inkstitch/assets/171956523/7b2ba33b-8564-42b8-9586-19334326c52d)

**Comment by kaalleen** [comment]
Seems as if you solved your issue. If anyone with the same issue finds this one here: Ink/Stitch is an Inkscape plugin.
Follow the installation instructions for your operating system on our website:
https://inkstitch.org/docs/install/
