### ISSUE TITLE
Invitation to join Kieler Open Source und Linux Tage Sept. 20 / 21 in Kiel

### ISSUE THREAD

**Issue by Moini** [inkstitch/inkstitch#2975]
Hi all!

The next Kielux open source conference is going to take place on September 20 and 21 in Kiel, in northern Germany.

I'd like to invite Ink/Stitch contributors to join us again this year with a booth, and maybe also with a talk or workshop.

You can learn more here:
https://kielux.de/220

For reference, last year's participants' conversation took place here: https://github.com/inkstitch/inkstitch/issues/2397

/CC @kaalleen @Tina-Chris @bianchifan

**Comment by kaalleen** [comment]
Oh schön, ich denke, da werden wir in diesem Jahr auf jeden Fall was auf die Beine stellen können :)

**Comment by Moini** [comment]
@kaalleen Jaaaa :) Das wär cool.

**Comment by kaalleen** [comment]
Wird es auch einen Inkscape Workshop oder Vortrag geben?

**Comment by kaalleen** [comment]
... und wer, der hier mitliest hat auch Lust zu kommen / vorzubereiten?

**Comment by kaalleen** [comment]
Zuerst dachte ich, dass man vielleicht Themen aufeinander abstimmen könnte. Aber das würde wahrscheinlich gar nicht so viel Sinn machen. Also ... reine Neugier :)

**Comment by bianchifan** [comment]
> ... und wer, der hier mitliest hat auch Lust zu kommen / vorzubereiten?

Wie ich schon auf dem Traffen angedeutet hatte, große Lust verspüre ich keine, auf so ein DB Chaos wie im letzten Jahr habe ich keinen Bock. 99€ pro Nacht in einer JH sind unverschämt und Campingplätze muss man heutzutage offenbar Monate im voraus online reservieren ;(

Davon abgesehen bastel ich so zwischen durch an einer aktualisierten Version von Kielux Patches und warte derzeit auf weitere Magnete, um die Iron away Folie bändigen zu können...

**Comment by kaalleen** [comment]
@bianchifan Kann ich verstehen. Kannst ja noch mal Bescheid geben, wenn du es dir anders überlegst und deine Kielux-Patches vor Ort zeigen willst :) Iron Away Vliese habe ich tatsächlich noch nie eingesetzt, nur Wash Away. Klappt das gut damit? Hört sich irgendwie störrisch an.

@Moini wir haben jetzt Folgendes überlegt:

@Tina-Chris, @rejbasket und ich werden am Sonntag einen Stand machen. Anstelle von einem Workshop oder einem Talk machen wir an dem Stand den ganzen Tag über kleinere Stickaktionen. So kann sich jeder, der Interesse hat, das Stick- und Digitalisierungsgeschehen genauer anschauen und uns Löcher in den Bauch fragen. Klingt das gut?

Das soll jetzt natürlich nicht heißen, dass wir nicht offen sind für weitere interessierte Menschen. Kommt, kommt alle dazu. Wir können jede Unterstützung gebrauchen ;)

**Comment by Moini** [comment]
@kaalleen Aber am Sonntag ist keine Kielux mehr :-( 

Alles andere hört sich ziemlich cool an, wär schön, wenn das auch am Samstag klappen könnte.

**Comment by kaalleen** [comment]
Oha, das war irgendwie nicht so schlau von uns :)
Na, dann machen wir das am Samstag. Ich weiß allerdings nicht, ob @Tina-Chris dann kommen kann.

**Comment by Tina-Chris** [comment]
Ja, Samstag geht auch.

Kaalleen ***@***.***> schrieb am Sa., 15. Juni 2024, 08:46:

**Comment by kaalleen** [comment]
So, für die Anmeldung noch ein paar Infos ... ich habe hier schon mal was zusammengestellt. @Tina-Chris wäre das so auch in deinem Sinne?

@Moini müssen wir die Anmeldung über die Kielux Webseite machen oder reicht es hier?

- 2x Bürotisch (wäre super, wenn das geht!)
- 6x Steckdosen: 2 Computer, 2 Stickmaschinen, evtl. Grafiktablets
- Logo: https://inkstitch.org/assets/images/inkstitch-logo.svg
- Link: https://inkstitch.org/de/
- Text:
  Ink/Stitch ist ein Inkscape Plugin zur Erstellung von Stickdateien.
  Stickdateien werden durch computergesteuerte Näh- oder Stickmaschinen ausgestickt.
  Das Ink/Stitch Projekt wird mittlerweile von einer bunten Community umgeben, in die sich jeder einbringen kann und soll.
  Wir freuen uns immer über Ideen, Bilder von angefertigten Projekten oder tatkräftige Unterstützung bei der Programmierarbeit.
  Auf den diesjährigen Kieler Open Source und Linux Tagen könnt ihr euch auf nette kleine Stickprojekte freuen, die wir direkt vor Ort umsetzen werden.
- Teilnehmer: TinaChris, RejBasket, Kaalleen (reichen die Namen so oder müssen die im Klartext sein?)

**Comment by Moini** [comment]
Super :D

Hier reicht auch, und Nicknames sind völlig okay (sind ja eindeutig genug). 
Ich warte dann noch auf das okay von @Tina-Chris :)

**Comment by Tina-Chris** [comment]
Kalleen hatte das mit mir schon abgesprochen! Passt!

Moini ***@***.***> schrieb am Sa., 15. Juni 2024, 20:45:

**Comment by Moini** [comment]
Danke - ich habe in den letzten Satz der Beschreibung noch ein 'am Samstag' eingefügt, damit Euch niemand am Freitag schon sucht - ist das okay so? 

-> https://kielux.de/aussteller (Ihr seid die ersten :D)

**Comment by Moini** [comment]
Eure Tischwünsche habe ich natürlich auch an unseren 'Standkoordinator' weitergegeben.

**Comment by kaalleen** [comment]
Super, danke. Passt so :)

**Comment by bianchifan** [comment]
> @bianchifan Kann ich verstehen. Kannst ja noch mal Bescheid geben, wenn du es dir anders überlegst 

Du bist mit von der Partie???
Ich werde es mir noch mal überlegen..
Evtl. reise ich per Rad bereits am Freitag an, Stand jetzt gibt es auf dem Kieler Campingplatz noch freie Plätze ;)
Abschreckend sind die Quartiere im Hamburger Raum..50€ für eine Übernachtung sind einfach nur Wucher.

> Iron Away Vliese habe ich tatsächlich noch nie eingesetzt, nur Wash Away. Klappt das gut damit?

Auf Iron Away bin ich in Amiforen gestoßen... Anleitungen dafür stammen von Madeira USA/UK ;)
Wash away hqabe ich verschiedene Toppings, als Vliesersatz ist mir nur Ultra Solvy bekannt, und die bekomme ich hier nicht.

> Hört sich irgendwie störrisch an

Das weniger, aber sie ist extrem fies glatt, einfach nicht greifbar.
Im normalen Rahmen rutscht sie so durch, letzes Jahr musste ich sie mit Pattes festkleben, hat aber auch nur in den Ecken gehalten, nicht auf den Seiten :(


> und deine Kielux-Patches vor Ort zeigen willst :)

Die sind frei verfügbar, die darf sehr gerne jede/r nach Gusto bearbeiten und aussticken...

------------------

> * Auf den diesjährigen Kieler Open Source und Linux Tagen könnt ihr euch auf nette kleine Stickprojekte freuen, die wir direkt vor Ort umsetzen werden.

Eigentlich sollte da aber auch ein wenig Werbung getrommelt werden, dei letztjährige Kielux fand doch relativ ernüchternd. 
Ich habe noch nie eine Linux!!! Messe mit so wenig Zuspruch erlebt :(

**Comment by bianchifan** [comment]
Zur verdeutlichung der Problematik, dass sich die Iron-away-Flolie nicht sachgerecht "trommelfest" im Stickrahmen fixieren lässt ein Stitchout vom letzten Sonntag...
Ursächlich für den extremen Verzug ist der flächendeckende zirkuläre Füllstich, wobei der Abstand im Zentrum ca. 2,3 mal größer ist als am Rand.
Das summasummarum katastrophale Resultat ist an der Konturunterlage für den abschließenden Satin gut zu erkennen;)
Aus unerfindlichen Gründen passt das Motiv noch so eben gerade in die Umrandung ..uff, uff,...puh..
![DSC05983](https://github.com/inkstitch/inkstitch/assets/17491743/93ee4352-a407-4d64-becc-833732f4c620)
![DSC05985](https://github.com/inkstitch/inkstitch/assets/17491743/d439cf02-b3df-4f58-bbf5-eaeb9341722e)
![DSC05984](https://github.com/inkstitch/inkstitch/assets/17491743/49a1fd59-b7b4-4c5d-b1de-aa79eac8e264)

**Comment by kaalleen** [comment]
Interessant, danke für den Einblick. Solltest du kommen, kannst du das Iron Away zur näheren Inspektion ja mal mitbringen :D

**Comment by bianchifan** [comment]
Ich schau mal.., sollte es nicht klappen, können wir ja kurz vorher im Unperfekt haus o.ä.. auf einen Kaffee treffen.

**Comment by kaalleen** [comment]
@bianchifan Das können wir mal machen, wobei wahrscheinlich eher nachher. Vorher wird es eng bei mir mit der Zeit.

@Moini ich habe ein wenig mit Stereogramm-Bildern rumgespielt (die waren ja mal irgendwann in den 90ern populär) und habe dabei herausgefunden, dass man die wunderbar mit einer durchgehenden Linie sticken kann. Meine Idee war jetzt, so ein Bild auf ein paar Taschen für das Event zu sticken und dann zu verteilen. Jetzt meine Frage... können wir das so einfach machen wenn da Kielux 2024 steht oder sollten wir besser was anderes drauf schreiben? Das Bild ist zeigt ein Papierboot.

![Tasche_detail](https://github.com/user-attachments/assets/75bc38ae-ad62-47ad-969c-419600b86c0f)

**Comment by Moini** [comment]
@kaalleen Na sicher könnt Ihr das machen - coole Idee! (und gut, dass Du dazu schreibst, was drauf ist... ich kann nicht 3D sehen... reiche das aber gleich mal zum Bestaunen an unser Team weiter :) )

**Comment by kaalleen** [comment]
@Moini sehr schön. Dann mache ich das so. Vielleicht kommen ja noch Motive dazu für die man nicht so schielen muss ;)

**Comment by Moini** [comment]
@kaalleen Wir haben auch noch keine... einige Schnarchnasen haben ihren versprochenen Vortrag noch immer nicht eingereicht, daher konnten wir noch nicht das Programm basteln. Ich gehe davon aus, dass es spätestens um 10 losgeht und frühestens um 18 Uhr endet. Wobei ja eigentlich immer Open End ist, nach dem Aufräumen wird meist nochmal gegrillt.

**Comment by Moini** [comment]
Das Programm ist übrigens in der Zwischenzeit veröffentlicht worden: https://kielux.de/p - kein Inkscape-Workshop diesmal, wir hatten schon fast zuviele Workshops. 

Darf ich Eure beiden letzten Fotos auf unseren Social Media-Kanälen verwenden? @bianchifan @kaalleen

**Comment by kaalleen** [comment]
Danke für die Info. Da schau ich mal rein, was ihr so für interessante Workshops und Vorträge auf die Beine gestellt habt.

Ja klar, das Bild kannst du verwenden.

**Comment by Moini** [comment]
Danke, @kaalleen !

**Comment by kaalleen** [comment]
@Moini Hier ist noch mal eine Tasche mit einem anderen Motiv (das man leichter erkennen kann).
Ein paar Schlüsselanhänger haben sich auch noch dazu gesellt (auch alle mit Inkscape und Ink/Stitch erstellt). Wenn du das Bild gebrauchen kannst, darfst du es gerne nutzen.

![kielux_schluesselanhaenger_und_tasche](https://github.com/user-attachments/assets/53a0d5c7-b42a-4040-b974-80272af2ca5e)

**Comment by Moini** [comment]
Oooh, die sind aber schön!!! Unbedingt kommen die in einen Social Post! :D

**Comment by kaalleen** [comment]
![Topflappen](https://github.com/user-attachments/assets/15c4fe06-f6e4-499e-a066-12596f5a2364)

@Moini ich habe dieses Paar Kielux-Topflappen gestickt und frage mich gerade, was man damit anstellen könnte. Meinst du, das wäre was für eure Verlosung?

**Comment by Moini** [comment]
Ob sich jemand traut, die zu benutzen? Die sind ja viel zu schön zum Soße-Drankleben-Haben... :scream: :heart: 

Aber klar, für die Tombola wären die ganz bestimmt geeignet, gute Idee! Dann würde ich Euch noch auf die Sponsorenliste an der Gewinnspielbox setzen.

**Comment by kaalleen** [comment]
Die Soße ist halt einfach Graffiti für das Boot ;)

Das klingt doch gut. Dann machen wir das so mit der Tombola.

**Comment by Moini** [comment]
Vielen Dank :) Dann seid Ihr als Verlosungssponsor mit dabei.

**Comment by Moini** [comment]
Hallo nochmal! 

Habt ganz, ganz vielen Dank, dass Ihr da wart! Ihr wart eine echte Attraktion auf der Kielux, die Leute haben sich so gefreut :) (und ich mich auch, ratet mal, wer meinen Avatar hier gemacht hat :heart_eyes: - DANKE!).

**Comment by kaalleen** [comment]
Ah wie schön!

Es war wirklich ein schöner Tag und eine nette Community die uns non-stop richtig gut beschäftigt hat :)
Auch euch als Team lieben Tag für die gute Organisation.

**Comment by eselspinguin** [comment]
Habt ihr eigentlich Interesse an ein paar Fotos von eurem Stand? Ich hab ein paar gemacht, als auch ein paar Interessierte dort standen. Und natürlich ein paar vom Sticken des OSM-Logos.

**Comment by Tina-Chris** [comment]
Oh ja, gerne, wir haben voll vergessen Fotos zu machen.!
Kann man die über die messenger Funktion von git privat schicken?

eselspinguin ***@***.***> schrieb am Mi., 2. Okt. 2024, 22:56:

**Comment by kaalleen** [comment]
Oh, das ist ja ein super liebes Angebot. Ich habe schon von überall her Ärger bekommen, weil ich überhaupt kein einziges Foto gemacht habe :D

Aber GitHub hat keinen Messenger so viel ich weiß. Ich rücke dafür aber auch gerne meine Mail-Adresse raus und leite dir @Tina-Chris die Bilder dann weiter. kaalleen [klammeraffe] inkstitch.org

Kannst du die per Mail schicken @eselspinguin ?
Ein Logo bekommt ihr ja auch noch von mir. Dann ist ja super, wenn wir schon im Austausch stehen.

**Comment by eselspinguin** [comment]
@kaalleen Mail ist raus :)

**Comment by tretkowski** [comment]
> Ob sich jemand traut, die zu benutzen? Die sind ja viel zu schön zum Soße-Drankleben-Haben... 😱 ❤️

Ich bin der glückliche Tombola-Gewinner der wunderschönen Kielux-Topflappen und werde Fotos schicken, sobald die ersten Soßen-Flecken dran sind 🙂

**Comment by Moini** [comment]
Die @jennifer@gruene.social (Mastodon-Kürzel) hat auch Bilder gemacht, habt Ihr sie schon gefragt, @kaalleen ?

Unsere vom Abschlussartikel könnt Ihr auch nehmen - eines ist von Jennifer gespendet, ggf. vorher fragen. https://kielux.de/223 (steht jeweils dran von wem).

**Comment by eselspinguin** [comment]
> Die @[jennifer@gruene.social](mailto:jennifer@gruene.social) (Mastodon-Kürzel) hat auch Bilder gemacht, habt Ihr sie schon gefragt, @kaalleen ?
> 
Die sind bei meinen Fotos schon mit dabei ;-)
Verwenden dürft ihr die natürlich gerne, sagen wir mal, ich gebe die unter CC BY-NC-SA 4.0 weiter. :)

**Comment by kaalleen** [comment]
> Ich bin der glückliche Tombola-Gewinner der wunderschönen Kielux-Topflappen und werde Fotos schicken, sobald die ersten Soßen-Flecken dran sind 🙂

@tretkowski Wie schön, dass du dich hier meldest. Ich freu mich total, wenn die Topflappen auch in Gebrauch sind :)

**Comment by kaalleen** [comment]
Ich schließe das hier mal, ist ja schon vorbei ;)
Bei Bedarf kann natürlich trotzdem weiter kommentiert werden.

**Comment by koyuawsmbrtn** [comment]
Hi, ich würde gerne meine Mutter mitnehmen wenn ihr für 2025 noch was geplant habt. Über Rückfragen würde ich mich freuen :)

**Comment by Moini** [comment]
@koyuawsmbrtn Du meinst, nach Kiel, als Standpersonal?

Die Kielux findet dieses Jahr vom 18.-20.9. statt, wobei die Ausstellung nur am 19. und 20. ist.

**Comment by koyuawsmbrtn** [comment]
Nein, ich würde einfach nur so kommen

**Comment by kaalleen** [comment]
@koyuawsmbrtn Dann bist du, bzw. deine Mutter bestimmt an einem Ink/Stitch Stand interessiert :)

Wir haben bisher noch nichts geplant. Ich hätte schon Interesse, es kann aber sein, dass ich in diesem Zeitraum gerade mit einem Umzug beschäftigt bin. Aber das Ganze muss ja auch nicht unbedingt nur an mir hängen. Ich kann dich gerne informieren, wenn wir genaueres wissen.

**Comment by Moini** [comment]
@kaalleen Ich hab mal für dieses Jahr einen neuen Issue aufgemacht: https://github.com/inkstitch/inkstitch/issues/3783 (und: Glückwunsch zum neuen Release, sieht sehr spannend aus!)

**Comment by kaalleen** [comment]
> Glückwunsch zum neuen Release, sieht sehr spannend aus!

Danke, ich bin echt froh, dass das geschafft ist :)
