### ISSUE TITLE
rejbasket/version-geos-update development version issues with contour, single and double spiral

### ISSUE THREAD

**Issue by buzzmandt** [inkstitch/inkstitch#2982]
The (I think) most recent development version, rejbasket/version-geos-update, is having issues with the contour fill, single and double spiral options.

Single spiral
![single](https://github.com/inkstitch/inkstitch/assets/76489837/e51e568a-4925-411d-952d-531a1c2f68fa)

double spiral
![double](https://github.com/inkstitch/inkstitch/assets/76489837/061dac18-f8c2-491c-b655-65c655eb39fe)

Reproduced several times as follows...
System font, bold, letter "U" (used DejaVu Sans and Hack with the same results)
object to path
params
uncheck underpath
Fill underlay, uncheck fill underlay
Fill stitch: Fill method, Contour Fill
Fill Strategy: Single spiral and/or double spiral

Inkscape 1.3.2
Opensuse Tumbleweed Linux
Inkstitch by RPM Linux version

**Comment by kaalleen** [comment]
That seems odd to say, but this behavior is kind of expected and would also appear in 3.0.1.
Single and double spirals are just not good at figuring out how to bridge narrow areas (yet).

I'll close this issue in favor of #1778
Thanks for the report anyway and for bringing this issue back to our minds!
