### ISSUE TITLE
Current dev versions can't handle multiple satin columns correctly

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2985]
While tinkering with my "fishbone" border I stumbled about seriuos problems with latest dev versions.
It seems that they do not store the parameter "inkstitch:satin_column  value:TRUE" in every selected path :(
![Bildschirmfoto vom 2024-06-10 15-36-01](https://github.com/inkstitch/inkstitch/assets/17491743/50fb6844-0522-4fe3-b0a5-95ad67c55e71)

I changed the strategy of construction from tiled clones to rotated Live Path Effects.
1st, I create a bunch of rotated "Clones".
2nd, I select every 2nd path and reverse them.
![Bildschirmfoto vom 2024-06-10 15-33-40](https://github.com/inkstitch/inkstitch/assets/17491743/e07ab3ca-f9fa-41cd-a480-1d9dd5a81a0e)

The Param's simulator looks fine.
![Bildschirmfoto vom 2024-06-10 14-10-50](https://github.com/inkstitch/inkstitch/assets/17491743/78e9bf98-64ac-4346-9abb-2527ed786b5b)

But the "CTRL-Shift-l" Embroider simulator does not.
![Bildschirmfoto vom 2024-06-10 14-06-43](https://github.com/inkstitch/inkstitch/assets/17491743/3d82f6db-13eb-4e79-9229-05df665eb005)

Only the original pattern, the first "Clone" and the first "reversed Clone" appear as satin stitchouts.
Same situation when saved as embroidery file.
![Bildschirmfoto vom 2024-06-10 14-19-36](https://github.com/inkstitch/inkstitch/assets/17491743/e311a6ab-5c7e-4d44-b960-2332262a99c0)

BTW: In some dev versions the simulator runs into nirwana when when a single path or group is selected, i.e. simulator-dark-theme...
![Bildschirmfoto vom 2024-06-10 15-56-56](https://github.com/inkstitch/inkstitch/assets/17491743/af0a19c6-d436-465d-8409-96a62e69beed)

[22_Kielux_12cm.svg.zip](https://github.com/user-attachments/files/15785663/22_Kielux_12cm.svg.zip)

**Comment by bianchifan** [comment]
problem found:
If you select a couple of paths and call the param's dialog the simulator ignores different parameter values and shows those of the first selected path.
For the param "satin column" I found the following:
IF one, only one paths within the selected bunch is defined as "satin column" the whole selection is displayed as satins and all other values won't be changed when saving the current values.
If the value "satin column" gets unchecked and then rechecked all values will be changed and saved.

**Comment by kaalleen** [comment]
I know this is confusing, but it has been Ink/Stitch behavior up from the beginning. Definitely something we need to change when we rewrite the params dialog.

The idea behind this is, that when you select multiple elements it will only save those params that actually have been changed before you apply. When you want to apply the "satin column"-param to all selected elements when some already have it applied, just uncheck and re-check the satin column checkbox. You can see which params will be applied when the pen beside a param setting is visible.

**Comment by kaalleen** [comment]
Closing (must be somewhere in the issues already).

It is planned to change behavior when the params editor is rewritten.
