### ISSUE TITLE
windows instller path

### ISSUE THREAD

**Issue by moolight-seashell** [inkstitch/inkstitch#2987]
iv'e move my inkscape installation but i cannot make the inkstiche ask how to install 

this is actually quite anoying

**Comment by moolight-seashell** [comment]
edit ok it look like i have inkscape listed as installed program even if it's not

**Comment by kaalleen** [comment]
Not sure if I understand your question.
Make sure to follow these steps: https://inkstitch.org/docs/install-windows/

**Comment by moolight-seashell** [comment]
ok ssry, i have an old install onf inkscape and inkstitch (with portable apps) and i move this install to a standard install.

or the inkstitch installer finds the path to the old installation.
as a result, when the installer is launched, it immediately says that it has all the necessary information to proceed with the installation without asking for the installation path

**Comment by kaalleen** [comment]
Usually the installer is capable to find the Inkscape extensions folder.
If you need to install in a different location, you can download the zip file for windows and extract it into the Inkscape extensions folder manually.
