### ISSUE TITLE
Filters not visible in realistic stitch plan preview

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#2988]
old one
![Bildschirmfoto vom 2024-06-12 10-46-57](https://github.com/inkstitch/inkstitch/assets/17491743/a21becee-77eb-4142-a9bb-2f198e23c5d0)

new one
![Bildschirmfoto vom 2024-06-12 11-26-06](https://github.com/inkstitch/inkstitch/assets/17491743/dc7f18e7-8795-4ffb-929e-819541438512)

_Originally posted by @bianchifan in https://github.com/inkstitch/inkstitch/issues/2978#issuecomment-2162604793_

**Comment by bianchifan** [comment]
System
![Bildschirmfoto vom 2024-06-12 13-04-19](https://github.com/inkstitch/inkstitch/assets/17491743/1e76d535-82e0-4161-9f14-3bdacf688470)

Four types of rendering

1. simple
![simple](https://github.com/inkstitch/inkstitch/assets/17491743/cdd2cc6d-0411-42ff-af39-cae070077db8)

2. realistic
![realistic bitmap](https://github.com/inkstitch/inkstitch/assets/17491743/6f5aab91-1600-472d-bce4-c4dad4111b24)

3. HQ
![realistic HQ](https://github.com/inkstitch/inkstitch/assets/17491743/ea0ba921-a61c-4823-bdc6-605e50dd778f)

4. Vector
![realistic vector](https://github.com/inkstitch/inkstitch/assets/17491743/bd73af76-8258-4ccc-9684-93613956ec0b)

**Comment by capellancitizen** [comment]
If you open the file in the XML view, can you see the filter declared under the defs element? The way the code works it should be added every time.

**Comment by bianchifan** [comment]
Within the paths..

>> style="fill: #262696; stroke: none; filter: url(#realistic-stitch-filter);"

Within defs1
![Bildschirmfoto vom 2024-06-12 16-59-15](https://github.com/inkstitch/inkstitch/assets/17491743/c929180f-4509-4694-9748-df697bdfe31d)

Complete SVG containing realistic view
[22_Kielux_12cm realistic stitch plan.zip](https://github.com/user-attachments/files/15807080/22_Kielux_12cm.realistic.stitch.plan.zip)

**Comment by capellancitizen** [comment]
![image](https://github.com/inkstitch/inkstitch/assets/5505503/5864bbc7-eb4f-40a6-97bd-23a8df465bf3)
It starts working again if you remove this whitespace. Not 100% why it started happening now, but it's probably easy to fix, at least.

**Comment by bianchifan** [comment]
> It starts working again if you remove this whitespace.

Ohhh yeah! You're right, that did the trick :((
But there's more than only a whitespace..

orig.
.
.
.
   link_styles="false" /><filter
   style="color-interpolation-filters:sRGB"
   id="realistic-stitch-filter"
   x="0"
   width="1"
   y="0"
   height="1"
   inkscape:auto-region="false">
      <feGaussianBlur
   edgeMode="none"
   stdDeviation="0.9"
   id="feGaussianBlur1542-6"
   in="SourceAlpha" />
      <feSpecularLighting
   id="feSpecularLighting1973"
   result="result2"
   surfaceScale="1.5"
   specularConstant="0.78"
   specularExponent="2.5">
        <feDistantLight
   id="feDistantLight1975"
   azimuth="-125"
   elevation="20" />
      </feSpecularLighting>
      <feComposite
   in2="SourceAlpha"
   id="feComposite1981"
   operator="atop" />
      <feComposite
   in2="SourceGraphic"
   id="feComposite1982"
   operator="arithmetic"
   k2="0.8"
   k3="1.2"
   result="result3"
   k1="0"
   k4="0" />
    </filter></defs><g
.
.
.

edited
.
.
   link_styles="false" /><filter
   style="color-interpolation-filters:sRGB"
   id="realistic-stitch-filter"
   x="0"
   width="1"
   y="0"
   height="1"
   inkscape:auto-region="false"><feGaussianBlur      <----
   edgeMode="none"
   stdDeviation="0.9"
   id="feGaussianBlur1542-6"
   in="SourceAlpha" /><feSpecularLighting             <-----
   id="feSpecularLighting1973"
   result="result2"
   surfaceScale="1.5"
   specularConstant="0.78"
   specularExponent="2.5"><feDistantLight      <---------
   id="feDistantLight1975"
   azimuth="-125"
   elevation="20" /></feSpecularLighting><feComposite   <-------
   in2="SourceAlpha"
   id="feComposite1981"
   operator="atop" /><feComposite             <--------
   in2="SourceGraphic"
   id="feComposite1982"
   operator="arithmetic"
   k2="0.8"
   k3="1.2"
   result="result3"
   k1="0"
   k4="0" /></filter></defs><g
.
.

and the result....
![Bildschirmfoto vom 2024-06-12 19-01-40](https://github.com/inkstitch/inkstitch/assets/17491743/5a7775cd-6ba0-41cb-886c-7325dae98dcb)

**Comment by bianchifan** [comment]
Yesterday evening I checked the latest dev versions, the realistic stitch filter works phantastic!
And its much faster.
![new realistic](https://github.com/inkstitch/inkstitch/assets/17491743/626cd1b5-3567-4207-b537-dc7339a3ad87)
