### ISSUE TITLE
How to transfer data to Toyota 850 ?

### ISSUE THREAD

**Issue by captcha1** [inkstitch/inkstitch#299]
How can I transfer data to a Toyota 850 embroidery machine ?

**Comment by AkiraNorthstar** [comment]
Welcome to Ink/stitch!

The Toyota 850 requires a floppy drive to transfer external designs. As far as I remember, this drive is available separately.

Which embroidery software do you use (except Ink/stitch)?
Which operating system is used?

Machines that use floppies require a driver that enables access to the contents of the floppy disk. Under Embird this is even installed to support many machines. Newer computers no longer have floppy drives, so it's getting harder and harder to link the machines to the computer in any way.

How did you transfer the designs before?

@wwderw has the longest experience with embroidery machines and the design of motifs, so I hope he can say something more about it.

**Comment by AkiraNorthstar** [comment]
I just see that there are Toyota 8xx machines that have a serial port on the back.
There are also USB adapters available.

Which interface do you have?

- FDD (floppy)
- Serial port
- USB

**Comment by wwderw** [comment]
There is a floppy to USB converter for the *AD860*, there may be one for your version and if your machine is a floppy based one, that is something that I would recommend getting.

Serial ports are getting to the same issue as floppy drivers in that not many computers have them originally (may be able to get cards to add that functionality), although workstations (computers with xeon processors and ECC ram still have them, at least my 2 yr old one does) do still have that input.  If your computer does not have a serial port and can't add a card to it to add that port, it could be possible to use a serial to USB cable.  Biggest thing here is that there is a difference between each one.  Not all will work for embroidery machines and typically those that do are usually on the more expensive side for what the cable is.

If it's USB, you should be golden.  The only thing that you *may* have to worry about is the USB device that you are using may be using too quick of a transfer rate or it's memory capacity (not filled memory, what it's capable of holding in total) may be too much for it to read.  Not all machines have that concern, but I've had some early PRs that did (back when they were floppy based as well, talking early aughts).

**Comment by captcha1** [comment]
It's a "Toyota ESP 850".  It was donated to a "Fablab" at a community college.

It has a serial port (with a USB to serial cable).  I fiddle a gtkterm a bit and it seems to be 9600 baud and some sort of binary protocol.

I don't see a floppy drive.

I plan to test it with Inkstitch (and Embroidermodder).  I use Linux, but other students will probably use Windoze.

I'm OK with a separate (CLI or GUI) program that takes a (DST?) file and transfers it to the Toyota.

**Comment by AkiraNorthstar** [comment]
@captcha1 Maybe this helps you a bit...

Machine Type                | Connection via       | Details
----------------------------|----------------------|-------------------------------
AD800/820/820A/830/850/860, | Serial Cable | Port=COM1/COM2
ESP9000, ESP9100 | (Type G, H, U, or V) | Protocol=Serial
|||Baud=9600, or 38400
|||Data bits=8
|||Stop bits=2
|||Parity=Odd, or None
|||Handshaking=Hardware

**Comment by wwderw** [comment]
>I plan to test it with Inkstitch (and Embroidermodder). I use Linux, but other students will probably use Windoze.

Embroidermodder is in alpha state.  Ink/Stitch has actually surpassed what Embroidermodder can do, at least what is available in the repos for that program.

>I'm OK with a separate (CLI or GUI) program that takes a (DST?) file and transfers it to the Toyota.

I am unaware of a dedicated embroidery program, GUI or otherwise, that runs on Linux that would allow for direct transfer.  Too many machines with different settings.  Maybe there is a basic transfer program that isn't embroidery specific that may work, that I don't know.

You are more then likely looking at a Windows program for that and typically something that is going to have some type of price tag to it.
