### ISSUE TITLE
Using Ink-Stitch with Janome MB4-S

### ISSUE THREAD

**Issue by pidanet** [inkstitch/inkstitch#2990]
Is it possible to use Ink-Stitch with Janome MB4-S Embroidery Machine? It uses JEF file format. Do you have any experiences with it?

**Comment by Marif91** [comment]
Un fichier jef ne pose pas de problème avec les machines Janome, celui que génère inkstitch est parfait pour la broderie.

**Comment by tyrosinase** [comment]
I use JEF all the time (MC400e and 550e though).

Janomes (and almost everything else) will also recognize Tajima DST files, but those have no color data so there's generally no reason to produce them when you can produce JEFs... but if you happen to receive DST, you don't need to convert them.
