### ISSUE TITLE
Installing without admin rights?

### ISSUE THREAD

**Issue by nluetzge** [inkstitch/inkstitch#2995]
I have my Inkscape installation locally and I'm trying to get this extension installed but its not possible with the package installer (Mac) and trying it through the source is a nightmare too because I have all of my python in conda environments and I'm a bit unsure how to handle this with the required installations... I have not tried it for long but was hoping there is another solution....

**Comment by rejbasket** [comment]
Inkstitch can be installed without using installer, use the zip file that is found on the inkstitch github website. Unzip and copy the app into the extensions folder of Inkscape, this shouldn’t require admin for the extension folder is located in the user folder. To install from source that requires a different approach, on the inkstitch website there are a several tutorials on how to use manual mode for developing inkstitch, as well how to build from source. They are slightly out of date, but for macOS the homebrew version of python is used but not required (pyenv is used for linux), and nodejs is not required anymore for current source code. I have no experience with conda, I can assume that installing from requirements.txt is possible with conda environments.

**Comment by nluetzge** [comment]
Thanks for some weird reason my config directory (~/Library/Application Support/org.inkscape.Inkscape/config) is only writeable by admin (even tho it is on the local directory) so I can't really do much there and I have not figured out how to change this...

**Comment by rejbasket** [comment]
That is very strange to have admin permissions for the Inkscape config directory. If you don’t have the admin password there is basically nothing you can do fix permissions issue. In order to have inkstitch to run, the app must be in the Inkscape extensions directory.

**Comment by nluetzge** [comment]
Yea I know what happened there but as you said there is no way for me to change it now, unless I manage to convince my IT to remove this folder (its a leftover from when Inkscape was not installed locally). Thanks anyway, now I know how I WOULD do it if things are set up correctly.
