### ISSUE TITLE
Panelization docs?

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2999]
I may be missing it somewhere, but I just poked around on the site because I wanted to link to the panelization how-to and... searching on "panelize" or "panelization" isn't turning it up.

I can probably write something up if it doesn't already exist, but I feel like it at least used to.

**Comment by kaalleen** [comment]
You are right. This hasn't been documented yet. It should be on this page here: https://inkstitch.org/docs/import-export/

And yes, sure, you are welcome to update it :)

**Comment by gwcSoftware** [comment]
A coincidence? I am currently working on a DIY Embroidery Machine project and was looking for information on how to export a g-code file for use in testing. I need to modify the Z-xx value in the gcode file and found the options when exporting the file. 
![image](https://github.com/inkstitch/inkstitch/assets/6797698/9b449aac-d438-44f3-9973-76a3e2690607) and 
![image](https://github.com/inkstitch/inkstitch/assets/6797698/15792331-9a28-4139-a362-1bafcfb13961)
My questions are:
1)  For the 'alternate Z value", can the option to set a value be added for this option?
2)  A more detailed explanation of the custom command would be helpful for each command. For example, what is the purpose of the 'STITCH' command. I saw the tool tip but don't understand how it is to be used!

Thanks for any help.

**Comment by kaalleen** [comment]
Oh nice, an other DIY embroidery machine project. It's always nice to hear about them!

1. You mean that the Z-value should go back and forth the value for `z travel per stitch`?
2. You can write into the STITCH field whatever you want. The %X, %Y and %Z will be replaced by the coordinates of the particular stitch.
    The default STITCH output for example would be represented like this
    ```
    G0 X%X Y%Y
    G0 Z%Z
    ```

**Comment by gwcSoftware** [comment]
After a little more thought on the Alternate setting, it's ok as is. 

Thanks for your explanation.

**Comment by kaalleen** [comment]
Ops, I did check the website and forgot that you wanted to update the panelization docs. So I already mentioned it, sorry for that.. But I barely scratched the topic, so you can still update the text go a little bit deeper into the topic.

**Comment by tyrosinase** [comment]
Oh, I'm not territorial at all, go right ahead. When I have a draft of anything, I'll put it in so everyone can see it/update it/use it.

**Comment by kaalleen** [comment]
Ok, that's good. I think I'm going to close this now, since it has been documented a little.
But feel free to add more text if you think it's needed whenever you want.
