### ISSUE TITLE
How to digitize text?

### ISSUE THREAD

**Issue by HyTronix** [inkstitch/inkstitch#300]
I'm sure I'm missing something, but if I draw... Anything, I can select all->path to object and then in the emroidery->params preview I can see how it would stich out, and it looks OK.

I can't however add any text and get it to show up.  How does one do this?

**Comment by lexelby** [comment]
Hi there, @HyTronix!  Thanks for using Ink/Stitch.

Text is a bit of a work in progress.  You can use Inkscape's text tool to add lettering, but it will be ignored by Ink/Stitch unless you do "object to path" first.  

Once you do that, the letters will become fill regions, and they'll be stitched with fill-stitch.  That's probably not what you want!  If you want satin-stitch lettering, you'll need to create the satins yourself ([instructions](https://inkstitch.org/docs/stitches/satin/)).

We have a pre-made embroidery font available: [inkstitch/embroidery-fonts](https://github.com/inkstitch/embroidery-fonts/tree/master/small-font).  There's also the Geneva fonts for Ink/Stitch on the EduTech wiki [here](http://edutechwiki.unige.ch/en/InkStitch_-_Geneva-simple_typefaces).

You can load these fonts up in Inkscape and then copy/paste in the letters you need.  Inkscape's Align/Distribute and Arrange tools can be useful for lining up the letters once you have them all pasted in.  Inkscape's built-in Extensions -> Arrange -> Restack can help with ordering too.

Ultimately we want to be able to do lettering automatically with built-in fonts.  That's discussed over in #142 if you're interested.  I'm sorry not to have a better answer for you regarding lettering, but we'd love to have your input on the feature design if you're interested in sharing.

-----------

@danielkschneider Do you think it would be a good idea to add your Geneva fonts to the ink/stitch embroidery-fonts repo?

**Comment by danielkschneider** [comment]
@lexelby I am not sure if it is a good idea to add my fonts, since they are not professional. After I made them I had a look at digitized fonts in Stitch Era and there is a huge difference in quality. But if you think that they can help for a while for the lack of other alternatives you could deposit this SVG (IMHO the  best version). Unfortunately I don't have time now to work on it....
https://edutechwiki.unige.ch/mediawiki/images/6/60/Typeface_geneva-simple-sans.svg

**Comment by lexelby** [comment]
Well, I certainly don't consider myself a professional digitizer, and my font is in there, so I feel like yours could be too. :)  I'll drop it in when I have a chance.

**Comment by lexelby** [comment]
I'm going to close this for now, but please feel free to reopen if you have any more questions, @HyTronix.
