### ISSUE TITLE
Apply preview width from simulator settings to png export

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#3017]
It would be nice if the line width from the simulator settings ( per #2992 ) applied to the PNG saved.

(png) ![CauldronHocusPocus_SilverSeams](https://github.com/inkstitch/inkstitch/assets/9473609/9ee60a82-54a2-4ad7-a47e-52e11fd051f6)
(simulator) ![image](https://github.com/inkstitch/inkstitch/assets/9473609/72c16a28-5fac-439e-a08d-5128585782e2)

It would also be nice if the background color was preserved, though that might already be mentioned in a different issue:

![image](https://github.com/inkstitch/inkstitch/assets/9473609/7c388699-e676-44b4-9848-777620b9fd5d)

(amusingly the background of that SVG is only dark because my file browser is dark-mode; Inkscape does its preview transparent. Which, actually, would probably be fine for my purposes since I can add a background when I make the preview montage.)

**Comment by bianchifan** [comment]
If you'll look at your PNG carefully you will notice that the "line" is a zigzag!

last weekend I stumbled upon this "feature".
In some cases (not reproducable) i opened an embroidery file (dst/xxx) which was defined as "manual stitch" but sim window and saved file showed up a zigzag...~200000 stitches instead of ~12000 ;)

**Comment by tyrosinase** [comment]
I think that's just pixelization... those are running stitches (some basting, some bean) and they're coming out normally.

![IMG_8337](https://github.com/inkstitch/inkstitch/assets/9473609/51ad4144-ec06-4e9b-93ab-79872b7e3533)

If you open an old Ink/Stitch SVG it does try to convert old-school default-zigzags to modern explicitly-set ones and might catch some too-narrow ones by mistake, but I wouldn't expect that to happen to a DST (or to something set as manual-stitch).

**Comment by tyrosinase** [comment]
(also send help I'm doing Halloween stuff in 95F/35C weather)

**Comment by bianchifan** [comment]
> I think that's just pixelization...

Maybe you're right, I hope so and the current PNG output is just horrible..;)
What I meant is shown below
![Bildschirmfoto vom 2024-06-23 11-39-30](https://github.com/inkstitch/inkstitch/assets/17491743/c4ce2b02-104d-4029-aca9-221e5c49194a)

The grid and the cirlce stitches should have a length of 4mm!
But they are converted to a tiny zigzag although method "Manual Stitch" is applied...

**Comment by kaalleen** [comment]
@bianchifan Can you send the svg file over?

**Comment by tyrosinase** [comment]
I've had that happen back in the olden days when solid meant zigzag regardless of line width, whenever I accidentally cleared the dashes on a stroke. The Janome will just go "nuh uh" and reject the file for having too-short stitches, but the Brother would gamely try to stitch it out. I learned to recognize it in a hurry, *nothing* else makes the machine sound like that.

**Comment by bianchifan** [comment]
> Can you send the svg file over?

No SVG, it was a DST I liked to modity to generate a repair file for a broken stichout (bobbin fill run out).

**Comment by kaalleen** [comment]
Huh, ok. A dst file shouldn't turn into zizags just like that. Did you copy a part of it over into a new svg file?

**Comment by bianchifan** [comment]
I read the DST from the USB stick into inkscape, it showed up correctly.
I turned off colors 2-20, only color 1 stayed on screen.
I identidied the node last stitched, broke the path apart and deleted the stitched part.
Then I turned colors 2-20 on again and saved all stuff as DST.

**Comment by tyrosinase** [comment]
@kaalleen, what's the status of line width in the ZIP version of the PNG? I was merrily exporting a new design today and suddenly it's back to skinny lines on simple PNGs. I can't figure out what I've done, it's set to .30 in the ZIP's params *and* in the Params params (Params shows correctly), and I haven't changed the Ink/Stitch install that I know of.

I must have poked *something* somewhere, and I seem to remember seeing some talk go by about the ZIP-screen param not being used yet, but other than the Params params I can't think what it would be using instead. I really liked the thick-lines render, I didn't mean to make it go away!

**Comment by kaalleen** [comment]
It should take the settings within the zip dialog into account?
`--png-simple-line-width`

**Comment by tyrosinase** [comment]
It seems to have some effect, but it's not matching the width in the preview screen. The ZIP version seems to be much narrower than the preview at the same width.

Here's the preview at 0.3:
![image](https://github.com/user-attachments/assets/ddc4b8b3-cc87-40bf-b7ae-3e0d62747f50)

And here's the ZIP's png, also at 0.3:
![image](https://github.com/user-attachments/assets/26074f8f-fc0d-48b1-8712-2f6cf3487574)

**Comment by kaalleen** [comment]
Hm, strange. Can you open a new bug report on this, so we won't forget about it?

**Comment by tyrosinase** [comment]
Done! (as #3289)

**Comment by kaalleen** [comment]
Thanks :)
