### ISSUE TITLE
Multi coloured satin  undersewing

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3025]
![image](https://github.com/inkstitch/inkstitch/assets/85417086/53a9e7f5-f7cd-4b2a-8e31-8fc10295b178)

feature improvement 
When we create a multi coloured satin and want to add an undersewing we need to go back into the params window what is no problem but when adding the underswing it is not staying within the the same color satin colom 

The only way we can accomplish this right now is that we add the undersewing by manually creating a running stitch and put it in the right order

Gus Visser

**Comment by kaalleen** [comment]
If you keep the original satin you can make the underlay from that one.
If you want multiple underlays for each color, you can use the inset settings in params to make them stay within the correct size.

That would be a bit tedious though and I think it is worth adding options to the multicolor extension.
I'm not sure though, if this will make it into the next release.
