### ISSUE TITLE
Erreur colonne satin

### ISSUE THREAD

**Issue by 94kate** [inkstitch/inkstitch#3026]
Ink/Stitch a rencontré une erreur inattendue. Ceci signifie qu'il s'agit d'un bug dans Ink/Stitch.

Si vous souhaitez aider, merci de 
- copier le message d'erreur en entier ci-dessous
- sauvegarder votre fichier svg
- créer un rapport d'erreur (issue) sur https://github.com/inkstitch/inkstitch/issues

Incluez la description de l'erreur et (si possible) le fichier svg.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
![dessin-1](https://github.com/inkstitch/inkstitch/assets/174200899/1aa5c93e-d49d-487a-9d47-b8e90056e92a)

**Comment by tyrosinase** [comment]
There are some problems with your satin. They'll be detected correctly in the upcoming version, but it will just tell you how to fix it:

![image](https://github.com/inkstitch/inkstitch/assets/9473609/7e90f4b0-8d0d-4382-ae6c-c6f597393c1b)

```
Troubleshoot

Warnings

These are problems that won't prevent the shape from being
embroidered. You should consider to fix the warning, but if
you don't, Ink/Stitch will do its best to process the
object.

Satin has no rungs
Rungs control the stitch direction in satin columns. It is
best pratice to use them.

Possible solutions
* With the selected object press "P" to activate the pencil
tool.
* Hold "Shift" while drawing a rung.

Too few subpaths
This element renders as running stitch while it has a satin
column parameter.

Possible solutions
* Convert to stroke: select the element and open the
parameter dialog. Enable running stitch along path.
* Use as satin column: add an other rail and optionally
rungs.

It is possible, that one object contains more than one
error, yet there will be only one pointer per object. Run
this function again, when further errors occur. Remove
pointers by deleting the layer named "Troubleshoot" through
the objects panel (Object -> Objects...).

```
