### ISSUE TITLE
Add warning when commands are applied to clones

### ISSUE THREAD

**Issue by IsabelBou** [inkstitch/inkstitch#3027]
When attaching visual commands to a cloned object with a fill stitch, a pop-up opens indicating "Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch."

InkScape Version: v1.3.2
Ink/Stitch Version: v3.0.1 (linux)

Error description:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/object_commands.py", line 37, in effect
  File "lib/elements/element.py", line 409, in shape
NotImplementedError: ('INTERNAL ERROR: %s must implement shape()', <class 'lib.elements.clone.Clone'>)

Here's a sample file where I replicated the bug (the circle on the right is the clone, commands cannot be attached to it):
![clone_bug](https://github.com/inkstitch/inkstitch/assets/67393544/f7adf16f-9c5c-4a1b-8168-39d4d186038f)

**Comment by kaalleen** [comment]
Thank you for the error report! This issue will be fixed in the next release.
Clones as of today won't respect start- and end commands though. If you want more control, you'll have to unlink the clone.

**Comment by capellancitizen** [comment]
Most commands wouldn't be particularly well-defined for Clones, other than maybe stop/trim after. In the short term at least it's probably easy enough to surface a nicer error if you try to attach a command to a clone element. Offhand, trying it with more recent `main` gives a traceback with:
```
  File "/home/[redacted]/inkstitch/lib/extensions/object_commands.py", line 37, in effect
    if element.node not in seen_nodes and element.shape:
  File "/home/[redacted]/inkstitch/lib/elements/clone.py", line 198, in shape
    return MultiLineString(path)
  File "/home/[redacted]/shapely/shapely/geometry/multilinestring.py", line 50, in __new__
    ... Omitted some shapely internals in the traceback ... 
TypeError: float() argument must be a string or a real number, not 'list'
```

**Comment by kaalleen** [comment]
@capellancitizen The error should be fixed. But a warning would be nice when they try to attach a command to a clone. Would you like to take a hand on it?
