### ISSUE TITLE
Inkscape Crashes when run

### ISSUE THREAD

**Issue by apollotg1** [inkstitch/inkstitch#303]
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path815', '--extension=params', 'C:\\Users\\apadilla\\AppData\\Local\\Temp\\InkscapePortableTemp\\ink_ext_XXXXXX.svgOYCBPZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "E:\PORTABLE APPS\InkscapePortable\App\Inkscape\lib\python2.7/subprocess.py", line 321, in __init__
    errread, errwrite)
  File "E:\PORTABLE APPS\InkscapePortable\App\Inkscape\lib\python2.7/subprocess.py", line 571, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by AkiraNorthstar** [comment]
Hello and welcome to the project!
Thanks for your report.
I have some questions regarding the error:
- Do you use diacritics as in # 118?
- Which version of Windows do you use?

**Comment by dsuguy2007** [comment]
I just downloaded the latest version of Inkscape and Inkstitch and installed. I'm getting the same message. I'm running Windows 10 Home. I downloaded Inkscape 0.92.3 64 bit windows. Does Ink/Stitch only work under the 32 bit version of Inkscape?

**Comment by lexelby** [comment]
Ink/stitch should work fine regardless of whether inkscape is 32 or 64 bit.  There's some kind of elusive bug here...

**Comment by lexelby** [comment]
Awesome!

**Comment by kaalleen** [comment]
This is most probably a antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.
