### ISSUE TITLE
Trying to export an Ink/Stitch file to .jef format

### ISSUE THREAD

**Issue by SubMnr4Evr** [inkstitch/inkstitch#3030]
I am new to the Ink/Stitch extension and was trying to save as a .jef file.  I did a trace patch of the attached picture and I then tried to save it as a .jef.  I continue to get this error message: 

There are no objects in the entire document that Ink/Stitch knows how to work with.

Tip: Run Extensions > Ink/Stitch > Troubleshoot > Troubleshoot Objects

Any help would be greatly appreciated.  Thank you in advance. 
![Submarine Dolphins](https://github.com/inkstitch/inkstitch/assets/174256512/0157406e-e667-45b3-a4b9-48b15b21e7c9)

**Comment by tyrosinase** [comment]
You've uploaded the PNG only, so it's hard to see exactly what is going on. You should be able to select the traced outline and `Extension > Ink/Stitch > Params` on it, and (eventually) get a fill-stitched preview - if not, then hopefully it will give us an error we can work with to track down the issue.

But over and above that: Ink/Stitch can't just take a traced image and immediately stitch it out. You will have a lot (a *lot* - that's a very complicated image) of manual work to turn it into an embroidery design. Look at https://silverseams.com/2020/03/monogramming-without-a-font.html for example - that's about letterforms, but the principle is the same for any design that should be a mix of running and (probably, depending on your scale) satin stitching.

You'll probably want to trace that image twice: once as a centerline, to use for all the running-stitch parts, and once as a regular traced image, from which you'll cut out two segments for each run of satin stitches. (That blog entry pre-dates Inkscape's centerline tracing ability, so doesn't mention it. But with that volume of running stitch, you'll probably want it.)

**Comment by kaalleen** [comment]
Most possibly this was an attempt to output the image file directy as an embroidery file.
I'm going to close the issue.
If the provided help didn't lead you to a working result, please feel free to post further questions into this thread.
