### ISSUE TITLE
Seg fualt on make manual

### ISSUE THREAD

**Issue by jdf400** [inkstitch/inkstitch#3039]
Is anyone getting a seg fault running make manual on OSx with python 3.12? Any help would be appreciated, looking to add a new font
```make manual
make inx
bash bin/generate-version-file
bash bin/generate-translation-files
python3 bin/generate-inx-files;
make[1]: *** [inx] Segmentation fault: 11
make: *** [manual] Error 2

**Comment by rejbasket** [comment]
This issue I have had using python 3.12, the python executable was seg faulting but only inside a virtual machine. In my case I used UTM, how I solved this issue was to recompile the home-brew package of python 3.12.

**Comment by jdf400** [comment]
This worked, to uninstall all versions of python and reinstall from scratch. Thanks!
