### ISSUE TITLE
Unable to find inkstitch in extension

### ISSUE THREAD

**Issue by annie-tacticombat** [inkstitch/inkstitch#3040]
Hello,

I've downloaded inkstitch-v3.0.1-windows.  The installation wizard didn't allow me to choose a path where to install the download to.  But it appears the location is correct after I checked in the inkscape system preference.  But regardless, inkstitch is not showing up in extensions.  Any pointers on how to get this to work would be appreciated.

![inkstitch_troubleshoot_3](https://github.com/inkstitch/inkstitch/assets/174637289/e4bdace4-6305-4c67-83a0-4b04688798f2)
![inkstitch_troubleshoot_2](https://github.com/inkstitch/inkstitch/assets/174637289/047882ff-f349-4c18-afc7-0ff0d38d0b96)
![inkstitch_troubleshoot_1](https://github.com/inkstitch/inkstitch/assets/174637289/323e9d53-1bb3-4dc5-9ea2-01ca2f9265e8)

Thanks
Annie

**Comment by gwcSoftware** [comment]
You did restart Inkscape? But take a look at this link for some trouble shooting ideas:
https://inkstitch.org/docs/install-windows/#troubleshoot

**Comment by Marif91** [comment]
La version de Inkscape me paraît très ancienne. Installez la version 1.3.2 disponible sur le site inkscape.org

**Comment by annie-tacticombat** [comment]
> La version de Inkscape me paraît très ancienne. Installez la version 1.3.2 disponible sur le site inkscape.org

Thank you, I installed 1.3.2 and it worked!
