### ISSUE TITLE
SVG to PES doesn't work (explained with screenshot of the svg file and messages appeared)

### ISSUE THREAD

**Issue by papelivan** [inkstitch/inkstitch#3042]
Hello my dear team, 
here I am uploading the same issue (that I have uploaded earlier today) but more analytically explained with screenshot and all messages. Thank you for trying to help/fix this issue. 
All these appear in my try to save the svg ready file to pes format. 
Thank you in advance.

[BUG SCREENSHOT AND MESSAGE FOR GITHUB.docx](https://github.com/user-attachments/files/16096798/BUG.SCREENSHOT.AND.MESSAGE.FOR.GITHUB.docx)

**Comment by kaalleen** [comment]
Today we released a beta version for the next release.
Would you mind to testrun your design with that version and see if the issue still shows up?

https://inkstitch.org/en/2024-07-04-3.1.0beta

**Comment by papelivan** [comment]
Well you guys are P E R F E C T!!!

**Comment by papelivan** [comment]
It worked and I saved the PES file it seems correct!!! I don't have the possibility to try it but I am waiting from a collaborator to check it and inform me if it opens and if it is ok!!! I appreciate it so so much, congratulations on your amazing work!

**Comment by kaalleen** [comment]
Thank you for your feedback! If you encounter any problems with the beta version, we will be pleased to hear about it :)
