### ISSUE TITLE
Stickreihenfolge anzeigen Script error

### ISSUE THREAD

**Issue by Helisinus** [inkstitch/inkstitch#3045]
Sorry, Da ich nicht weiß wie die entsprechenden Befehle in Englisch heißen beschreibe ich den Fehler in Deutsch.
Beim testen der neuen Funktion Stickreihenfolge anzeigen bekomme ich folgenden Fehler:
Es ist ein unerwarteter Fehler aufgetreten. Das heißt, dies ist ein Fehler in Ink/Stitch.

Wenn du uns helfen willst Ink/Stitch zu verbessern,
- kopiere die gesamte Fehlermeldung
- speichere die SVG-Datei ab und
- erstelle einen Fehlerbereicht (New Issue) auf https://github.com/inkstitch/inkstitch/issues/new

Sende die Fehlerbeschreibung und (wenn möglich) auch die SVG-Datei.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0beta (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex\base.py", line 252, in run
  File "lib\extensions\display_stacking_order.py", line 29, in effect
  File "inkex\paths\path.py", line 439, in transform
  File "inkex\paths\arc.py", line 321, in transform
ZeroDivisionError: float division by zero

![Zeichnung](https://github.com/inkstitch/inkstitch/assets/11804790/283788ee-a2c9-4360-8bf9-c82d0068edc7)

**Comment by kaalleen** [comment]
Danke dafür! Der Fehler passiert nur bei Objekten, die keine Pfade sind. Ich habe den Fehler für die nächste Version korrigiert (noch nicht in der beta-Version).

Zum weiteren Testen kannst du aber gerne weiter mit Kreisen oder Quadraten arbeiten. Es ist gut möglich, dass noch mehr solcher Fehler auftauchen.

Ich schaue mir das Ganze noch näher an, vielleicht müssen wir das sogar an das Inkscape-Team melden, da es das Arbeiten mit Objekten für Erweiterungen tatsächlich ein wenig schwierig macht.

**Comment by kaalleen** [comment]
I posted the error in the inkex issues. The actual issue with your file is, that the ry (y border radius) value was very close to zero (1.6217518e-12). They check for zero, but not for almost zero.
