### ISSUE TITLE
macOS (arm): geos/shapely

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#3047]
J'ai téléchargé la version 3.1.0 pour processeur arm.

**_J'ai d'abord testé le lettrage seul_**, j'obtiens un message à la sortie du lettrage, pour de nombreuses polices, c'est CE message :
<img width="485" alt="Capture d’écran 2024-07-04 à 22 20 12" src="https://github.com/inkstitch/inkstitch/assets/65076100/aebed39d-1098-4ada-92bb-62a8a531b0f2">
**A la suite de celà l'export pdf ne se lance pas, la simulation ne se lance pas, la carte de densité non plus...**
Par contre je peux retravailler le paramétrage du lettrage.

Avec la police Cooper, pour le même texte le message est plus long
<img width="480" alt="Capture d’écran 2024-07-04 à 22 53 31" src="https://github.com/inkstitch/inkstitch/assets/65076100/48a1518b-1348-4be8-90aa-33467391e239">

Pas de souci avec la police au point de croix, ni avec les polices au point droit.

**_Puis j'ai chargé un motif réalisé avec la version 3.0.1._** Pas de souci pour la visu, le pdf, la carte de densité...etc
Par contre si j'ajoute un lettrage les problèmes se reproduisent exactement de la même façon.

Je poursuivrai les tests demain !

**Comment by kaalleen** [comment]
Maybe we were a bit too excited about releasing an arm version as well. These are just warnings, but there is an other issue that isn't so easy to fix as shapely seems to be buggy for arm macOS systems (for now). We consider to remove the arm version for the next release and give it an other try someday later. Would you mind to run tests with the intel version of Ink/Stitch and see if you run into the same issues or not?

**Comment by Marif91** [comment]
Je teste en soirée !

**Comment by kaalleen** [comment]
Merci beaucoup :)

**Comment by Marif91** [comment]
Je viens de tester les mêmes procédures avec la version intel (Rosetta est installé depuis quelques mois sur ma machine).

Aucun des problèmes signalés ne s'est reproduit ! Merci Kaalleen !

**Comment by kaalleen** [comment]
This is supposed to be fixed now, therefore I'm going to close the issue.
The arm version might reveal more of those FloatingPoint issues due to the geos version used.
So whenever this shows up with a newer release, we'd like to hear about it.
