### ISSUE TITLE
underpath for red work

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3048]
As i am testing the Beta version i had no issues sofar but i noticed that the underpath for the auto route running is a dashed line 
And the underpath for the redwork is a solid line style same as the top stitching
I think it would be benificial to have the underpath for redwork also a dashed line style this way it would be easier to select the top sewing for if we decide to change from a single to a bean stitch or go from bean to single

and also noticed that on the conversion to auto route or redwork the line width is really small would be nice if we could set the line width or if it was a fixed line width at about 0.265 mm as good as i know that is about the width of a 40 weight thread what would then give a better visual

Running windows 10 

sofar i really like what i am seeing
Hats off to the development team

Gus Visser

**Comment by kaalleen** [comment]
You can select the underpath easily with the select embroidery elements selection. But a dashed line might lead to a faster, easier selection. So yes, I think we may set the underpath to a dashed stroke.

As for the line width, it takes the style of the first selected element in rendering order. Can you double check if that is valid for you?
