### ISSUE TITLE
S-Stich

### ISSUE THREAD

**Issue by Duplex4git** [inkstitch/inkstitch#3050]
the installation works - i can not find the S-Stich stich in the Satin

**Comment by kaalleen** [comment]
Thank you for the feedback. The S-stitch is a satin column method. So you setup a satin column and in params chose s-stitch as a method.

https://inkstitch.org/de/docs/stitches/s-stitch/#parameter

**Comment by Duplex4git** [comment]
There was a old version in the Background of my system - a new clean Installation remove my problem.Am 05.07.24, 17:31 schrieb Kaalleen ***@***.***>:

   
  Thank you for the feedback. The S-stitch is a satin column method. So you setup a satin column and in params chose s-stitch as a method. 
  https://inkstitch.org/de/docs/stitches/s-stitch/#parameter
