### ISSUE TITLE
macOS (arm): FloatingPointError geos/shapely

### ISSUE THREAD

**Issue by Bearviation** [inkstitch/inkstitch#3051]
From the error:

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79

Ink/Stitch Version: v3.1.0beta (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 158, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/convert_to_satin.py", line 61, in effect
  File "lib/extensions/convert_to_satin.py", line 75, in convert_path_to_satins
  File "lib/extensions/convert_to_satin.py", line 162, in path_to_satin
  File "lib/extensions/convert_to_satin.py", line 318, in generate_rungs
  File "shapely/geometry/base.py", line 599, in intersection
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/set_operations.py", line 131, in intersection
FloatingPointError: invalid value encountered in intersection

![simplelineerror](https://github.com/inkstitch/inkstitch/assets/170473005/2922c4a2-9e0e-41b1-9022-80f0d935aff9)

**Comment by kaalleen** [comment]
Thank you for the error report. I am assuming that you are using the arm version for macOS? Can you test if the same error shows up when you install the intel version? It should be working fine as long as you have rosetta installed - just like the previous releases.

**Comment by Bearviation** [comment]
I have the new M2 chip (Apple silicon) so am unable to test an Intel chip as this is the only computer I have.  I have never used Rosetta but is there a different version for ARM where I can test with Rosetta?John BauderOn Jul 5, 2024, at 12:45, Kaalleen ***@***.***> wrote:﻿
Thank you for the error report. I am assuming that you are using the arm version for macOS? Can you test if the same error shows up when you install the intel version? It should be working fine as long as you have rosetta installed - just like the previous releases.

**Comment by kaalleen** [comment]
You can install the Intel version. With rosetta installed it should run on your system (that's how all previous Ink/Stitch versions have worked).

**Comment by kaalleen** [comment]
Closing in favor of #3047 (as the problem has the same origin). Thank you for the bug report!

**Comment by kaalleen** [comment]
Thank you for testing the beta version. We actually just released beta2 and are searching for testers.
It would be great if you could try that one out and see if everything runs fine for you: https://inkstitch.org/en/2024-07-21-3.1.0beta2
