### ISSUE TITLE
Bitdefender antivirus found threat in inkstitch.exe

### ISSUE THREAD

**Issue by allerwelle** [inkstitch/inkstitch#3059]
Operating System = Windows 11
Bitdefender Total Security  Version 27.0.40.169
Inkscape Version = 1.3.2
Inkstitch = v3.1.0beta 

When I tried to test "text along Path ", Bitdefender antivirus found an infection with App Gen:Variant.Lazy.547185 in inkstitch.exe and moved the application to quarantine

Greetings from Germany, H. 
[Bitdefender.pdf](https://github.com/user-attachments/files/16116252/Bitdefender.pdf)

**Comment by kaalleen** [comment]
Virus softwares like to detect inkstitch as a false positive. I don't know about bitdefender on how to report false positives to them.
