### ISSUE TITLE
Issues downloading Multicolor Satin extension

### ISSUE THREAD

**Issue by BigTito44** [inkstitch/inkstitch#3060]
I've been wanting to incorporate multicolor satin in my designs however when I visit the inkstitch website it says that it is a now an extension and there's no download associated with it. I'm running Inkstitch 3.0.1 (osx) on Sonoma 14.5 and the multicolor satin isn't listed under Tools:Satin under Inkstitch in my window. Any help?

**Comment by tyrosinase** [comment]
Ink/Stitch itself is an extension, multi-satin isn't. But it's not in the current release, which you're on. The 3.1.0 beta is available, and if you install that it should show up on `Tools: Satin` without any additional downloading.

**Comment by BigTito44** [comment]
thank you!
