### ISSUE TITLE
Command line params fail on png-realistic in 3.1.0b

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#3064]
My command-line stuff fails on the beta, because of the new PNG exporting.

```usage: inkstitch [-h] [--output OUTPUT] [--id IDS]
                 [--selected-nodes SELECTED_NODES] [--notebook NOTEBOOK]
                 [--custom-file-name CUSTOM_FILE_NAME] [--format-pec PEC]
                 [--format-pes PES] [--format-exp EXP] [--format-dst DST]
                 [--format-jef JEF] [--format-vp3 VP3] [--format-xxx XXX]
                 [--format-u01 U01] [--format-pmv PMV] [--format-png PNG]
                 [--format-gcode GCODE] [--format-edr EDR] [--format-col COL]
                 [--format-inf INF] [--format-svg SVG]
                 [--format-threadlist THREADLIST]
                 [--format-png-realistic PNG_REALISTIC]
                 [--dpi-realistic DPI_REALISTIC]
                 [--format-png-simple PNG_SIMPLE]
                 [--png-simple-line-width LINE_WIDTH]
                 [--dpi-simple DPI_SIMPLE] [--x-repeats X_REPEATS]
                 [--y-repeats Y_REPEATS] [--x-spacing X_SPACING]
                 [--y-spacing Y_SPACING]
                 [INPUT_FILE]
inkstitch: error: argument --dpi-realistic: invalid int value: ''
```

The call (pay no mind to the Perlish filename noise) is:

`~/.config/inkscape/extensions/inkstitch/bin/inkstitch --format-pec=True --format-pes=True --format-exp=True --format-dst=True --format-jef=True --format-vp3=True --format-xxx=True --format-u01=True --format-pmv=True --format-png=True --format-gcode=True --format-edr=True --format-col=True --format-inf=True --format-threadlist=True --extension=zip --custom-file-name=$filename $dir\/$filename\.svg > $dir\/$filename\.zip`

and I'm guessing from the usage/error that maybe `format-png` is now being treated as `format-png-realistic`? If so, or if it's just defaulting format-png-realistic to True, it should probably also default to something average for the DPI rather than throwing the error.

(Yes, we had that whole discussion about how the formats should default and then I never went back and changed that call. I had already typed in *all* those formats, I wasn't going to let perfectly good typing go to waste. I guess I'll clean it up now since I want simple png.)

**Comment by kaalleen** [comment]
Right, you have `format-png-realistic` and `format-png-simple` now.
DPI values should be set to 300 by default.
