### ISSUE TITLE
inkstitch beta 3.10

### ISSUE THREAD

**Issue by dmsundukos** [inkstitch/inkstitch#3077]
Under stitch preview I tried the realistic and very realistic options and it does not change anything with the image.  The image still looks like a vector graphic.  I have all the parameters assigned.  Thank you.

**Comment by kaalleen** [comment]
Can you upload an example svg with the stitch plan preview inside?

**Comment by kaalleen** [comment]
Thank you for testing the beta version. We actually just released beta2 and are searching for testers.
It would be great if you could try that one out and see if everything runs fine for you: https://inkstitch.org/en/2024-07-21-3.1.0beta2

**Comment by kaalleen** [comment]
Closing as we don't have enough information to understand the reported problem.
You can still answer on this topic and we can reopen if necessary.
