### ISSUE TITLE
Satin: short stitches in corners

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#308]
On the inside of a sharp corner, stitches can pile up.  We can reduce the density by having some of the stitches fall short of the corner.  Ideally ink/stitch would do this automatically, perhaps with an option to disable.

**Comment by wwderw** [comment]
I would have an option to disable.  Main reason would be for puff foam.  By having those short stitches still there, chances of nubbies or the foam not exactly cutting the foam evenly can be an issue.

**Comment by lexelby** [comment]
Ah, good point.  Would you want it enabled by default, or disabled by default?

**Comment by wwderw** [comment]
Enabled by default, as regular embroidery use case would be more prevalent.

**Comment by ginobolliger** [comment]
Hello all
First of all, thanks a lot for your powerful Inkscape plug-in. I'm using it with an old 'Brother Super Galaxie 2000' but am not yet that experiences with all this stitching :-)
Probably, I am currently experiencing the same issue mentioned here when trying to stitch our sports club logo:
![grafik](https://user-images.githubusercontent.com/53125070/61582641-84b76400-ab2d-11e9-8563-3d2e87e3c646.png)
The stitches in the inside of the sharp corners get very dense:
![grafik](https://user-images.githubusercontent.com/53125070/61582672-ed9edc00-ab2d-11e9-856b-20e1c7b6a807.png)
Any idea/hint for me the work around this? Is there a better/more optimized way to place the rungs?
Best
Gino
[Logo 2 schrift embroidery 3.zip](https://github.com/inkstitch/inkstitch/files/3413896/Logo.2.schrift.embroidery.3.zip)

**Comment by wwderw** [comment]
That's a short stitch issue (or lack thereof).  

At this point, the only workaround that I could think of to suggest (unless able to make tweaks to the design itself, in other words more gradual angles and less sharp ones) would be to segment those corners.

So for instances, take the points underneath TV on the left.  Right now it's essentially one object, with segmenting your going from one object to six objects with overlaps at the points (always want to have overlaps as that helps deal with push/pull that happens at the machine, I would always suggest overlapping where two objects meet).

**Comment by tyrosinase** [comment]
On 7/20/19 5:39 PM, wwderw wrote:
> So for instances, take the points underneath TV on the left. Right now
> it's essentially one object, with segmenting your going from one
> object to six objects with overlaps at the points (always want to have
> overlaps as that helps deal with push/pull that happens at the
> machine, I would always suggest overlapping where two objects meet).


Ooh, you know what we need in the documentation, is a set of common
situations like this and the best practices for dealing with them.

(I would write them but (1) pretty new at this myself and (2) what I
have done is mostly not conventional embroidery.)

**Comment by wwderw** [comment]
Now that I think about it, could do capping at the corners versus the overlapping.

Now to make that look good, you'll take a few objects and in sections, but it's doable, just adds significantly to the time of it all.

It will also involve using run and manual stitches as well.

**Comment by kaalleen** [comment]
> Ooh, you know what we need in the documentation, is a set of common
> situations like this and the best practices for dealing with them.

https://inkstitch.org/tutorials/satin-edges/
@wwderw could you have a look at it? I am also not an expert in this matter.

**Comment by kaalleen** [comment]
@wwderw thank you for having a look into it. It's just that the capping doesn't work anymore and I am not sure what you were trying to do. Could you update it again?

**Comment by wwderw** [comment]
Give that one ago.

**Comment by ginobolliger** [comment]
@wwderw thanks for your hints!
I am currently experimenting by dividing into individual objects and some additional manual runs. I am quite satisfied with the results already. A bit more tweaking and then it should be good:
![grafik](https://user-images.githubusercontent.com/53125070/61596652-b2241080-ac06-11e9-98a1-764b5a2b2c5f.png)
![grafik](https://user-images.githubusercontent.com/53125070/61596669-dd0e6480-ac06-11e9-9299-07d9cdfc3d8e.png)

**Comment by Tina-Chris** [comment]
@kaalleen With the new pattern option, will this feature be able to be implemented easier? 
Thanks! Tina

**Comment by kaalleen** [comment]
@Tina-Chris Sorry, I somehow missed your question. A "short stitch line" could have been one option, but the request here was to set a default, which would be difficult if you have to add extra lines. So in #1695 I try to get the distance between the points on one rail to decide if a short stitch should be done or not.
