### ISSUE TITLE
Silent failure in Simulator (with bonus failure on stitch file save)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#3083]
I see
a bad moon a-rising
I see
trouble on the way

![BadMoon](https://github.com/user-attachments/assets/0f46f11a-2e0e-4421-9c69-e9b7c85800c0)

If you select the simulator, it just... doesn't.

If you try to save as (for example) .JEF, it actually throws an error:

```
Debian GNU/Linux 12 (bookworm)

Ink/Stitch Version: remove-duplicated-points (linux)

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 954, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1186, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 96, in circular_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 670, in find_stitch_path
  File "lib/stitches/auto_fill.py", line 594, in nearest_node
TypeError: 'NoneType' object is not iterable
```

(it's all circular-fill, so a pathing issue at that size is no surprise, but neither response is ideal. It succeeds at larger sizes.)

**Comment by tyrosinase** [comment]
(Noto Emoji, First Quarter Moon, if you're wondering)

**Comment by tyrosinase** [comment]
Removing the underpath makes it work, though I don't know if that's because the pathing fails in underpathing or if that changes the start point and just doesn't trigger the problem.

**Comment by capellancitizen** [comment]
I also had this issue when doing some dev recently: When there's an error starting the simulator it doesn't show. I worked around it with the debugger but of course it should actually show the end-user the crash message. Probably the use of `implements-custom-gui="true"`?

**Comment by kaalleen** [comment]
`show-stderr="true"` would show errors. implements custom gui is supposed to prevent the black box in windows, not sure how well that works. But we should use both of them for the simulator. There has been a problem with it once, that's why it doesn't have it in there now. But I guess it should be ok now.
