### ISSUE TITLE
Consider Azure Pipelines

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#309]
Microsoft just released Azure Pipelines, a CI/CD platform.  It's free for open source and looks to be designed to compete directly with Travis CI.

The most interesting part for us is that builds can run natively on Linux, Mac, and Windows, both 32-bit and 64-bit.  We could finally have a 32-bit Linux version!

@akiranorthstar this may interest you especially.

**Comment by lexelby** [comment]
I believe you have the necessary privileges to get azure pipelines going on this repo.  Feel free to give it a try :)

**Comment by AkiraNorthstar** [comment]
Prerequisites

* You need an Azure DevOps organization. If you don't have one, you can create one for free. If your team already has one, then make sure you're an administrator of the project you want to use.

 * **You need a GitHub account, where you can create a repository.**

I'm an admin?

**Comment by lexelby** [comment]
I think they mean an admin of an account on Azure.  But if you need to be an admin of inkstitch on GitHub let me know and I'll set you up :)

**Comment by AkiraNorthstar** [comment]
Can you please add "azure-pipelines.yml" (from Set up CI with Azure Pipelines branch) into the master branch. It only work if azure-pipelines.yml is in there....

**Comment by AkiraNorthstar** [comment]
Nice! you can also add a pipeline to an external git service (selfhosted gitea or gogs)...
At the moment you don't add azure-pipelines.yml into the master br.
I'll do some "basic" tests in azure, so i use my test-azure repo for that.
The main problem today is github - slow, slower....fast...slow...error

**Comment by lexelby** [comment]
I merged your #311, is that enough to get you going?

**Comment by lexelby** [comment]
Their docs claim we can use gitlab: https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/index?view=vsts

If that's true and all of this works, then we'd be able to migrate to gitlab!

**Comment by AkiraNorthstar** [comment]
At the moment I see it like this:
If you wanted to switch to gitlab for various reasons, appveyor could be responsible for the windows builds. Well, we would not be dependent on a single provider (Azure Pipelines + github).

Variety is the key - even if it is sometimes annoying to decide ...

Inkscape is currently building for the following [platforms](https://inkscape.org/en/release/0.92.3/platforms/). For the windows builds they use appveyor.
I looked at Appveyor couple of days ago and there we would have to switch a bit for the windows build. The advantage of gitlab would be - we would be closer to inkscape and its developers;).
We could contact the Inkscape developers and ask how they handle it.

I don't know why you want to change, everyone has his own experience with github.
Microsoft is now steering github - that should be clear to everyone.

My point of view:
Microsoft takes everything and returns only a bit of "open code" or "open services" to calm the masses.
I'm not saying that Microsoft is bad.

We are working on an open-source project Ink/stitch, for an open-source project called Inkscape.
Actually, we should also take "free" / "independent" services for compilation the binary code than.
It feels more natural for me.

Building Ink/stitch for other platforms then linux is great!
Of course we want to reach a lot of users - who doesn't want that!
Inkscape also builds for these platforms ...

I want to support you - no matter how, and why you choose something!

But you should show me the direction ... ;)

**Comment by AkiraNorthstar** [comment]
By the way and for information only, i am using (along with a friend) [gitea](https://github.com/go-gitea/gitea) and [drone](https://github.com/drone/drone) on my NAS to build upstream fedora packages.
Packages like kodi (xbmc) and several other packages for daily use.
Sure, it's just one distribution and one architecture (x86_64), but you can work with it properly.
For embedded devices like my sat-receiver (mipsel) i also build sometimes packages for test purposes,
with a Docker image on Ubuntu as a base.

**Comment by kaalleen** [comment]
> If that's true and all of this works, then we'd be able to migrate to gitlab!

Nice!

> We are working on an open-source project Ink/stitch, for an open-source project called Inkscape.
Actually, we should also take "free" / "independent" services for compilation the binary code than.

Exactly :)

**Comment by lexelby** [comment]
Wow, thanks for dropping in, @jeremyepling!

**Comment by lexelby** [comment]
@AkiraNorthstar After posting my comment above, I realized that using Microsoft's CI solution as a way to escape GitLab doesn't make any sense anyway ;)

**Comment by AkiraNorthstar** [comment]
Then we can close this...

**Comment by lexelby** [comment]
Wait, why are we closing this?  I do think Pipelines is worth a try since it can do all three platforms natively, all in one CI provider...

**Comment by AkiraNorthstar** [comment]
Yeah sure, we can keep this up if you want - at the moment I'm working on appveyor + miniconda. Then it would be easier (later) to port it to azure pipelines.

**Comment by lexelby** [comment]
From what I can tell, it looks like you can run a bash script in s build even on Windows which would make things easier.  It's a bit hard to tell from the docs though.

**Comment by jeremyepling** [comment]
You can run a bash script on Linux, macOS, and Windows. [This doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=vsts) has the details.

**Comment by AkiraNorthstar** [comment]
@jeremyepling thanks for the link!
Is there a way (similar to appveyor) to use / boot a system with an x86 or x64 architecture?
```
platform:
   - x86
   - x64
```
As I have read (or understood), always a x64 vmImage is used / started.
Which is basically fine, as an x64 system can also compile x86.

@lexelby 
> The most interesting part for us is that builds can run natively on Linux, Mac, and Windows, both 32-bit and 64-bit. We could finally have a 32-bit Linux version!

Do you mean native VM's (x32 and x64), or building x32 stuff on x64 VM?

**Comment by jeremyepling** [comment]
As you said, you can build x32 on x64 VMs and that's what Azure Pipelines supports. I'd recommend doing this with a [matrix](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts#matrix-1). If you want to run your builds on a x32 VM, you'll need to use a [self-hosted agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=vsts#install).

**Comment by lexelby** [comment]
Now that we have it with GitHub Actions, I think we can close this.
