### ISSUE TITLE
Converting line to satin

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3091]
![image](https://github.com/user-attachments/assets/f15f4a3f-5495-41a3-9a2f-2df95751d335)
Received this Error on a conversion of line to satin

Windows 10 inkstitch beta version

Gus Visser

**Comment by kaalleen** [comment]
Looks more like a params issue when you close the params window...
How did you close params (the x or apply or cancel)?

**Comment by gusvisser** [comment]
I did use the apply and quit while the player was still going

Gus Visser
