### ISSUE TITLE
Save As... and Save a Copy...  —  automatically generated file extension does not match the file format selected

### ISSUE THREAD

**Issue by zourid** [inkstitch/inkstitch#3093]
Save As... and Save a Copy... will automatically select an extension to match the last format used, but if a different file format is selected the extension does not change even when "Append filename extension automatically" is checked (see attached).

Also, if the file extension is deleted, no new extension is generated, even if a new format is selected.

Inkscape 1.4-beta
Inkstitch: tried several of the development builds released in the last week or so
Intel-based Mac

![Screen Shot 2024-07-18 at 12 36 55 PM](https://github.com/user-attachments/assets/22b41992-37e2-41ae-bf6b-c60bb09bcdf9)

**Comment by kaalleen** [comment]
As an extension we have no control about this. But I'm pretty sure, that the inkscape team would like to know about it. Can you file a bug report here?
https://inkscape.org/report/

**Comment by kaalleen** [comment]
I'll close this issue here, since there is not much we can do. But I saw, that you already opened an issue for the inkscape team. That's great to see.
