### ISSUE TITLE
New Brothread color palette 

### ISSUE THREAD

**Issue by Qwertie-** [inkstitch/inkstitch#3105]
It looks like the color palettes for New Brothread needs to be updated to include the new colors they sell currently.

Looking at the thread chart on [their website](https://newbrothread-official.com/products/polyester-machine-embroidery-thread-5000m-each-huge-spool-40wt-27-colors?variant=37210384760988) it looks like the "InkStitch Brothread 80" palette corresponds to the colors on the chart that start with an N (Maybe they started adding the N later?) and "InkStitch Brothread 40" is an incomplete list of the colors which do not start with N.

I'm happy to put up a PR to add the new colors in as this seems pretty easy. But I'm wondering if it would be preferable to merge these two color palets in to one and add the N to the ones which now have it? It doesn't look like there are any clashes either way since there is an N204 but there is no 204. Or to just extend the 40 color palette to include all the new colors. Guess it would also need a new name since it isn't 40 colors anymore.

**Comment by kaalleen** [comment]
Hm, I'm not sure about this. Maybe that's an other palette. I think they have put together various sets and if you own the one with 40 colors I could imagine that you'd wish to use the palette which contains only those. What do you think?

**Comment by Qwertie-** [comment]
Not too sure there is a great solution for everyone. They sell sets of a few different sizes, I've got the 63 color set which contains all of the 40 color set + some more, but none of the N colors. Presumably most people end up buying more colors over time and would end up with something diverged from the original pack. Perhaps extending the 40 color set to include the new colors make sense while keeping it split from the N colors makes sense.

**Comment by Qwertie-** [comment]
Looking in to it a little bit more, it looks like the New Brothered color codes match up with the Brother colors, so the 63 set they sell is essentially the exact same thing as the Brother color palette. And then the N colors being the same as the Janome color codes. So I guess it might not make sense to make any change here since you can just select the Brother or Janome palette.

**Comment by kaalleen** [comment]
Ok then. Thank you for the feedback. This may be useful information for others as well.
