### ISSUE TITLE
not compatible with Big Sur 11.7.10

### ISSUE THREAD

**Issue by CreasY23** [inkstitch/inkstitch#3109]
Hello, I work with an iMac Big Sur and have downloaded the revised program. My embroidery file that I created in the previous program opens but doesn't show me the preview or rendering. Kind regards, Yvonne
<img width="1933" alt="Bildschirmfoto 2024-07-25 um 10 40 43" src="https://github.com/user-attachments/assets/2b9317dc-6355-4b37-be0e-4717ffccc99e">
 P.S. If I'm in the wrong place, please give me an address I can contact. I think you can't see the error message properly either. I took a screenshot, but it is only shown here as text.
y.dieckmeyer@mail.de

**Comment by tyrosinase** [comment]
You're in the right place but you are correct, we can't see the error message. If you copy it as text from the error box you should be able to paste the full message.

Which version are you running ( `Extensions > Ink/Stitch > About` ) and are you sure you have the correct package (the second one on the page at https://inkstitch.org/docs/install-macos/ )?

**Comment by CreasY23** [comment]
I take the macOS Big Sur (and higher),… Version, install this and if the system ask me to deliver the preversion I put it into the bin.
Maybe I've forgot something to install, or do I have to install a new version inkscape as well.

Error massage_Fehlermeldung:

Traceback (most recent call last):
  File "inkstitch.py", line 113, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/debug/debug.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/svg/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/svg/guides.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/utils/__init__.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/utils/geometry.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "shapely/__init__.py", line 1, in <module>
ImportError: dlopen(/Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/shapely/lib.cpython-39-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libgeos.3.12.2.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

[10687] Failed to execute script 'inkstitch' due to unhandled exception: dlopen(/Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/shapely/lib.cpython-39-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libgeos.3.12.2.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

[10687] Traceback:
Traceback (most recent call last):
  File "inkstitch.py", line 113, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/debug/debug.py", line 16, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/svg/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/svg/guides.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/utils/__init__.py", line 8, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "lib/utils/geometry.py", line 10, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "shapely/__init__.py", line 1, in <module>
ImportError: dlopen(/Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/shapely/lib.cpython-39-darwin.so, 2): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libgeos.3.12.2.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

**first**

<img width="715" alt="Bildschirmfoto 2024-07-25 um 14 40 43" src="https://github.com/user-attachments/assets/d539f920-cce7-47c6-aa52-0ced2b11f236">

**and than**

<img width="626" alt="Bildschirmfoto 2024-07-25 um 14 41 09" src="https://github.com/user-attachments/assets/603a134c-5771-4242-bdc0-6e2dbacb2723">

**Comment by Marif91** [comment]
J'ai un Mac équipé d'un processeur intel et de Big Sur 11.7.10.

Le message d'erreur est clair, tu n'as ps chargé la bonne version de inkstitch (Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libgeos.3.12.2.dylib (which was built for Mac OS X 12.0))

Il faut charger l'autre version  :
![Capture d’écran 2024-07-25 à 17 22 53](https://github.com/user-attachments/assets/9aec3375-17f7-46cc-911c-649111af4db6)

Je viens de tester et ça fonctionne très bien sur les mac un peu anciens !

**Comment by CreasY23** [comment]
Many thanks for the help! I just went by the name Big Sur. For me it was the only point to orient myself. The name Big Sur doesn't appear in the third box, but now I know. I wish you a nice weekend.

<img width="662" alt="Bildschirmfoto 2024-07-27 um 13 40 21" src="https://github.com/user-attachments/assets/4af62140-d3ab-473d-8f7d-af7ec0df796e">

**Comment by CreasY23** [comment]
I'm sorry, but somehow I'm stuck. I have now started another download with High Sierra, Mojave and Catalina following instructions from Marif91. 
With this download my computer cannot start anything and refuses to install. Big Sur works, but the program is totally messed up. It doesn't render at all, there isn't even an error message and the mouse is completely crazy. It doesn't move visually, but the indicator on the lines tells me that the mouse is moving. I didn't download the first one, I don't have this computer. What should I do?
<img width="425" alt="Bildschirmfoto 2024-07-27 um 13 57 20" src="https://github.com/user-attachments/assets/b05f3bfb-003e-4ab7-b572-c1ddd5850cac">

**Comment by bianchifan** [comment]
> I don't have this computer. What should I do?

Unfortunately I cannot help you, I do not own any Mac I'm missing totally any Mac skills..

Do you have some GB free space?
Perhaps you like to install a virtual system via Virtualbox so you can check OS version made for other Macs?

Anyway.. owing to a brian fart I stole your design this morning and made some tiny changes.., I guess its a nice demo for the contour fill method..just an idea

![Nachtfalter](https://github.com/user-attachments/assets/1207a49e-9849-4af0-bece-3b80649f1b4d)
![Nachtfalter](https://github.com/user-attachments/assets/11316660-5c3e-4e81-8cfb-719fe822c60e)

**Comment by kaalleen** [comment]
> With this download my computer cannot start anything and refuses to install

I messed up the version names and you are totally right, the one which says Big Sur is actually Monterey and higher. We do not notarize the build for older systems. This means you will need to open them in a special way as described here: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

> Big Sur works, but the program is totally messed up. It doesn't render at all, there isn't even an error message and the mouse is completely crazy.

Did you manage to install the older macOS version or is this a description of the newer one or only Inkscape without Ink/Stitch?

**Comment by CreasY23** [comment]
An Bianchifan
Was soll das? Das ist mein Design, meine Idee, meine Entwicklung und so will ich es nicht haben. Sie können mich erst nett fragen und dann, wenn ich es erlaube etwas verändern. Ich frage um Hilfe und werde abgezockt. Ist mir egal, wer in ihr "Brian Gehirn gekackt" hat. Ich weiß was geht und was nicht geht. Ich brauche Hilfe beim Programm und nicht bei der Datei. 
Fragen Sie mich bevor Sie etwas machen! Urheberrechte sind bei mir!!!!!

**Comment by CreasY23** [comment]
Hallo Kaalleen,

ich habe inkstich installiert. Die High Sierra/Mojave... kann ich gar nicht installieren, denke die mittlere Version ist die richtige. Diese wird installiert mit allem drum und dran, nur sie funktioniert dann einfach nicht. Ich weiß nicht was "Arm" heißt eigentlich habe ich doch "Intel", soweit ich weiß?
BigSur 11.7.10 wird ja seit Herbst 23 nicht mehr supported, also denke ich das ist nicht die neueste Version und ich habe nur inkstich neu installiert nicht Inkscape.

Wie kommt diese Person "bianchifan" an meine Datei. Ich finde es nicht in Ordnung solch einen Text zu schreiben. Keinen Beitrag zu meiner Frage zu leisten und einfach mein Design zu nehmen. Woher hat dieser Mensch meine Datei? Macht ihr das hier so, dann werde ich mich hier nie wieder blicken lassen.

**Comment by CreasY23** [comment]
Hallo Kaalleen,

habe versucht mit deinem Link zu Öffnen, das ist die Antwort.

<img width="319" alt="Bildschirmfoto 2024-07-27 um 16 01 54" src="https://github.com/user-attachments/assets/18f8a327-f7dd-4d4e-86a8-e452d07f2b57">

 .... und es passiert wieder nichts, schade!

**Comment by kaalleen** [comment]
Für Big Sur brauchst du tatsächlich die dritte Version (High Sierra, Mojave, Catalina, Big Sur). Ich hatte mich zuerst vertan und die oberen beiden Versioen mit Big Sur gelabelt. Sie sind definitiv nicht für Big Sur geeignet und funktionieren erst ab Monterey. Wenn du also die Version für High Sierra, etc. heruntergeladen hast, kannst du den Installer wie beschrieben öffnen.

Ich finde, wir sollte hier auf jeden Fall höflich bleiben. Urheberrrechte zu schützen ist natürlich wichtig. Wenn dich stört, dass hier eine svg-Datei von deinem Design hochgeladen wurde, können wir die beiden Posts, den von bianchifan und deine Antwort darauf, löschen.

**Comment by CreasY23** [comment]
Hallo Kaalleen, danke für das Löschen! Ich versuche es dann noch einmal mit der dritten Version, hoffe ich kann sie installieren. Bis jetzt hat der Rechner nicht mitgemacht, mal schauen.

**Comment by CreasY23** [comment]
Hallo, leider komme ich nicht weiter. Ich habe alles neu installiert, incscape, inkstich (mit ctrl Taste, ging nicht anders) und bei der Auswahl _Parameter, für eine ganz einfache Fläche erscheint diese Fehlermeldung:

[8896] Failed to load Python shared library '/Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libpython3.9.dylib': dlopen: dlopen(/Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libpython3.9.dylib, 10): Library not loaded: @rpath/libintl.8.dylib
  Referenced from: /Users/yvonnedieckmeyer/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/Frameworks/libpython3.9.dylib
  Reason: Incompatible library version: libpython3.9.dylib requires version 12.0.0 or later, but libintl.8.dylib provides version 11.0.0

Ich habe die untere Version, für BigSur, genommen!?

Sorry, ich verstehe es einfach nicht.

**Comment by kaalleen** [comment]
Na, da kommen wir der Sache schon näher. Die Ink/Stitch Installation klingt so erstmal ok. Aber es sieht so aus, als wäre nicht die aktuelle **Inkscape** Version installiert. Ein Update könnte helfen.

**Comment by CreasY23** [comment]
Ok, ich habe gedacht das wäre eine neue Version! Da habe ich wohl nicht richtig hingeguckt. Lieben Dank, ich werde es noch einmal versuchen. :-)

**Comment by kaalleen** [comment]
Hat es geklappt?

**Comment by CreasY23** [comment]
Hallo KallEen,du liebe! Ich habe gerade soviel um die Ohren, das ich irgendwie noch nicht dazu gekommen bin InkScape neu zu installieren.Letzter Stand war ja, das es daran liegen sollte.Ich werde es bestimmt noch einmal versuchen, aber ich weiß nicht wann ich es schaffe.Sollte ich wieder auf Probleme stoßen melde ich mich. Momentan passieren gerade ganz andere Dinge in meinem Leben.Ich wünsche dir noch einen schönen Restsonntag.Liebe Grüße YvonneVon meinem iPhone gesendetAm 17.08.2024 um 17:53 schrieb Kaalleen ***@***.***>:﻿
Hat es geklappt?

**Comment by kaalleen** [comment]
Hat ja keine Eile, das rennt ja nicht weg :)
Dir auch noch einen schönen Sonntagabend!

**Comment by CreasY23** [comment]
Hallo Kaalleen,ich habe Inkscape neu installiert und es funktioniert. Habe das Motiv „Motte“ einfach nur geöffnet und die Parameter drüber laufen lassen und das Programm hat alles ohne Murren erledigt.Es hat etwas gedauert, aber er muss das ja auch alles rechnen und die „Motte“ ist zwar nicht groß, durch die Hintergrundinfos wohl doch etwas kompakter. Es ist ja immer ein Zentrum für jede Stickfläche angelegt, zu dem die Bögen ausgerichtet sind. Mal schauen, wann ich Zeit habe eine Stickprobe zu machen. 🙄Viele Grüße Yvonne Von meinem iPhone gesendetAm 18.08.2024 um 20:14 schrieb Kaalleen ***@***.***>:﻿
Hat ja keine Eile, das rennt ja nicht weg :)
Dir auch noch einen schönen Sonntagabend!

**Comment by kaalleen** [comment]
Sehr schön. Danke für die Rückmeldung!
