### ISSUE TITLE
Pas d'enregistrement de mes fichiers créés

### ISSUE THREAD

**Issue by Lady-Pink** [inkstitch/inkstitch#3110]
Bonsoir
Je suis sur iMac avec macOS Ventura
je fais des essais avec
la version inkstitch v3.1.0beta (osx) 2024-07-21 09:40
Version Inkscape : 1.3.2
Lorsque je créé mes fichiers avec Inkstitch , et que je veux :
- fermer mon fichier, cela ne fonctionne pas, je dois quitter Inkscape
Si je fais fichier /enregistrer sous /   ( par exemple rond.svg), mon fichier est enregistré  dans le repertoire avec le nom donné (par ex : Rond.svg). A l'écran, le fichier prend bien le nom donné
Je fais alors Fichier / Fermer , mais mon fichier Rond.svg reste  à l'écran ,  mais change de nom ! , il est renommé en "nouveau document 1.

Merci a toutes et tous pour tout ce travail que vous faites sur ce logiciel
Cordialement
Francine

**Comment by claudinepeyrat06** [comment]
Francine, 
Je  travaille aussi sur mac et j'ai ce genre de comportement parfois avec  inkscape qui s'embrouille dans la manière dont il appelle les  fichiers (en  haut de la fenetre) quand plusieurs fenêtres sont ouvertes en particulier s'il y a des documents non enregistrés. C'est un problème inkscape et pas un problème ink/stitch, du coup c'est auprès d'inkscape qu'il  faut le signaler. Je vais aller le faire, j'ai trainé à le faire, mais ça me rappelle à l'ordre. Tu  peux bien sur aussi le faire.
Tu dis aussi que tu n'arrives pas  à fermer un fichier inkstitch, (je suppose que  tu  veux dire un fichier  svg crée avec inkscape en utilisant l'extension inkstitch  ) est ce que  tu as vraiment un problème lié à l'utilisation d'inkstitch ou as tu le même problème si tu utilises seulement inkscape ?

**Comment by Lady-Pink** [comment]
Bonjour Claudinemerci de ton messagedésolée pour ma réponse tardive , je suis en vacancesapres avoir signalé mon problème, je me suis dit que c’était un problème Inkscape et que je n’avais pas du faire ma déclaration au bon endroitJ’ai tout désinstallé et réinstallé au cas où…. Toujours le même problème cela me « rassure » que tu rencontres le même problème 😏Comme toi, Je vivais avec , j’ai vu ton post , alors j’ai fait une remontée de dysfonctionnement en me disant 5 mn après que je ne l’avais certainement pas fait au bon endroit à mon retour , mi août, je ferai une remontée auprès de inkscapeJe ne suis pas devant mon écran, mais il me semble que je rencontre le même problème en travaillant un fichier seulement sur inkscapeje te confirmerai à mon retourpar contre, je travaille en général avec un seul fichier à l’écranJe te souhaite une bonne journée et de belles vacancesA bientôt pour mes retoursFrancineenvoyé : 26 juillet 2024 à 19:11de : Claudine Peyrat ***@***.***>à : inkstitch/inkstitch ***@***.***>cc : Lady-Pink ***@***.***>, Author ***@***.***>objet : Re: [inkstitch/inkstitch] Pas d'enregistrement de mes fichiers créés (Issue #3110) Francine, Je travaille aussi sur mac et j'ai ce genre de comportement parfois avec inkscape qui s'embrouille dans la manière dont il appelle les fichiers (en haut de la fenetre) quand plusieurs fenêtres sont ouvertes en particulier s'il y a des documents non enregistrés. C'est un problème inkscape et pas un problème ink/stitch, du coup c'est auprès d'inkscape qu'il faut le signaler. Je vais aller le faire, j'ai trainé à le faire, mais ça me rappelle à l'ordre. Tu peux bien sur aussi le faire. Tu dis aussi que tu n'arrives pas à fermer un fichier inkstitch, (je suppose que tu veux dire un fichier svg crée avec inkscape en utilisant l'extension inkstitch ) est ce que tu as vraiment un problème lié à l'utilisation d'inkstitch ou as tu le même problème si tu utilises seulement inkscape ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
