### ISSUE TITLE
Commands attached to cloned objects aren't executed in 3.1.0

### ISSUE THREAD

**Issue by ToonChopper** [inkstitch/inkstitch#3121]
If I add a command like trim to a group of stitch objects and clone the group, the command is not executed, which renders clones effectively unusable (unless you don't mind jump stitches). Also, after I run the preview on a cloned object, the command connector lines move back to their initial positions (i.e. to the positions in the original object).
System: Ubuntu 20.04

**Comment by capellancitizen** [comment]
There's some work underway to address this in (Draft) PR #3086.

**Comment by capellancitizen** [comment]
If you're open to testing a development build, you can see if the builds from my dev branch here fixes your issues: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-capellan-clone-commands
