### ISSUE TITLE
Inkstitch creating incomplete satin 

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3126]
![satin test](https://github.com/user-attachments/assets/94efd4f7-7306-4576-ab0c-d77ef1895c3f)
As i was creating satin coloms and then applied the params it is not putting all the stitches where they should be
on windows 10
inkstitch 3.1.0

Gus Visser

**Comment by claudinepeyrat06** [comment]
@gusvisser the minimum stitch length for  this file  is  1.5mm...... just decrease it  and  it  should  be fine

**Comment by gusvisser** [comment]
Thank you i just found out by playing with min stitch lenght and that solved it
