### ISSUE TITLE
this error code when ever i do troubleshoot 

### ISSUE THREAD

**Issue by electra0319** [inkstitch/inkstitch#3146]
im trying to use the font generator and its just not saving. keeps giving me errors and then says to troubleshoot but then i get this. im tearing my hair out and have tried a bunch of things but nothing is working. if someone could help me that would be incredible!
![Burinil](https://github.com/user-attachments/assets/3e71278a-1121-46f6-bed0-21cef1131f15)

heres the error code for the troubleshoot code

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex\base.py", line 252, in run
  File "lib\extensions\troubleshoot.py", line 34, in effect
  File "lib\elements\satin_column.py", line 763, in validation_errors
IndexError: tuple index out of range

to add im just trying to save the generated font text and a star

**Comment by kaalleen** [comment]
Thank you for the error report and for sending the file along. This is really helpful!

On the group `g20350` in `inside` there is a strange transform which reduces everything inside it to zero.
I would suggest that you remove the group and recreate the lettering.

**Comment by kaalleen** [comment]
Troubleshoot fixed in #3148
