### ISSUE TITLE
Apply clips on groups

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#3149]
Dear Inkstitch

I'm considering writing a svg crop function for Inkscape/Inkstitch because I can't find one and because Inscape's clip doesn't clip an embroidery.
I was going to write a function that loops through all elements in a file and detects intersections with a see-through polygon window. Elements that intersect with the window could be cut roughly with `Path / Cut apart`.
I think I could do that nicely with the Python Shapely library.
I suppose I'll have to make an Inkscape extension (`inkex.EffectExtension`)

So I'm looking for an example.
While browsing through the Inkstitch repository I find a file `break_apart.py` that defines an `InkscapeExtension` that breaks apart.
But `Path / Break apart` is an Inkscape function is it not?
How come (and why ?) Inkstitch defines break apart and Inkscape uses it even without installing Inkstitch?

How do Inkscape and Inkstitch work together?

**Comment by tyrosinase** [comment]
I'm not a coder (or rather, not an Ink/Stitch coder) but I can answer part of it: native `Path > Break Apart` will not carry the Ink/Stitch params over to the newly created objects.

Automating something like this: https://silverseams.com/tutorials/cropping-with-inkstitch.html would be pretty nifty.

**Comment by kaalleen** [comment]
The Inkscape clip should work just fine for embroidery elements. But it only works on stroke and fill stitch types and if applied directly to the element. When applied to a group it doesn't take it into account. So maybe that is something to consider.
Clipping satins may be a lot harder to do, since the clip could destroy the satin setup. So I'm not sure if and how we could handle that one.

**Comment by kaalleen** [comment]
Sorry I'm not sure if I can follow. Can you clarify with an illustration what you mean?

I think the most challenging part about a usable cropping method would be to still avoid jump stitches in the pathing. As when you crop normally you may split a path and leave a jump in between.
