### ISSUE TITLE
DST file not being read by embroidery machine

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3150]
I always have to load the dst file in other software and do a save as or export to DST for the embroidery machine where i mainly digitize for  
i have posted this in previous version of inkstitch also but it still remains an issue

Gus Visser

**Comment by kaalleen** [comment]
Yes, the old issue is still open: #2388
I'm not sure how to fix it. Hopefully somebody else knows.

I'm going to close this issue here, since it is a duplicate of the old one. But thanks for the reminder.
