### ISSUE TITLE
Inkstitch 3.01

### ISSUE THREAD

**Issue by Silko6501** [inkstitch/inkstitch#3157]
Bonjour, j'ai un gros problème d'incompatibilité de version Inkstitch. J'ai posté hier sur le groupe mais je n'ai eu qu'1 réponse. 
En allant sur "A propos" c'est la version 2.0 qui est marquée. Sous applications installées: j'ai Inkstitch 3.01 et Inkscape 1.3.2.  Avant Inkscape et Inkstitch fonctionnaient malgré des paramètres à double. J'ai voulu faire de l'ordre et depuis c'est seulement la version 2.0 qui fonctionne. Je n'arrive pas à désinstaller la version 3.01 et Inkstitch est inutilisable.
Merci de m'aider à réinitialiser Inkstitch. Je serais triste de ne plus pouvoir l'utiliser.
Patricia Loosli

**Comment by kaalleen** [comment]
Are you on windows? Can you share a screenshot of your extensions folder?

**Comment by Silko6501** [comment]
Bonjour, mon mari vient de réussir à réinstaller la dernière version de
Inkstitch. Tout est maintenant OK.  Merci pour votre message.

**Comment by kaalleen** [comment]
Ok, thanks for the feedback!
