### ISSUE TITLE
Embroidery Machine Running Continuously

### ISSUE THREAD

**Issue by FractalDecimator** [inkstitch/inkstitch#3163]
Hi,
I flattened my files from object to path and rendered DST file using Inkstich. While printing the design with an embroidery machine it's continuously stitching on the same place and stops prematurely. Other designs printed using other embroidery software work fine. I have attached the files for your reference.
![IMG-20240822-WA0026](https://github.com/user-attachments/assets/2199aef4-e898-49c4-81cd-50a97dcfc8ef)
![IMG-20240822-WA0030](https://github.com/user-attachments/assets/0459d565-ef63-4d0a-9d09-6b6550de268f)

**Comment by kaalleen** [comment]
Can you share your svg or dst file?

**Comment by FractalDecimator** [comment]
![Eka T-Shirt-Embroidery_Back](https://github.com/user-attachments/assets/0f299eec-09b9-402a-8818-11d1a3e67170)

**Comment by tyrosinase** [comment]
The density map (`Extensions > Ink/Stitch > Visualize > Density map`) confirms you've got some problem areas:

![image](https://github.com/user-attachments/assets/8b62302d-575e-4a38-af5c-d71742bae154)

The top dot has two objects overlain, so deleting one should solve that issue. The leaf shapes might be better served as a single shape with a simple stitch pattern, so the fills don't collide:

https://inkstitch.org/docs/stitches/patterns/

Aside from that, it looks like you've got some tension issues in the second picture - either something is dragging the bobbin thread, or the top thread isn't feeding through the tensioner. That might have been *caused* by the overstitching issues though (mine will gleefully buck the top thread out of the take-up lever if something interrupts the flow of things).

**Comment by kaalleen** [comment]
I'm going to close the issue as it is not an Ink/Stitch issue, but more a question of refining the design. You can still post questions to this thread if you don't find the given answer sufficient to solve your issues.
