### ISSUE TITLE
Lettering doubles up

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#3166]
I've had some cases where I get double instances of Lettering and I've finally nailed down how it happens.

![image](https://github.com/user-attachments/assets/2d8f3909-2099-4970-bb5d-8e111344b070)

If I pick a complicated lettering like Abril en Fleur, and click Apply and Quit before the preview starts to load, I get two instances of everything *inside* the lettering object.

**Comment by lexelby** [comment]
Nice, thanks for figuring this out!

**Comment by kaalleen** [comment]
I can't reproduce. @tyrosinase can you still reproduce the error?

**Comment by tyrosinase** [comment]
Yup, though I'm not on the most-most current pre-release version, just vanilla 3.1.0 (I gotta upgrade this week, because there's something else I owe you a test on).

You have to have a slowish computer, and change the lettering to (e.g.) Abril en Fleur and hit Apply-and-Quit immediately, while the original preview is still in the window. If your machine's too fast, maybe try a longer word?

![image](https://github.com/user-attachments/assets/070a7da5-4d79-4d6c-a05e-168a2537d344)

**Comment by kaalleen** [comment]
Ok, now I can reproduce. I didn't understand the switch the font part.
I just pasted a long text and click on apply as quickly as I could. Also I tried to first write a single letter first, wait until it renders and then paste the text. But I somehow didn't had the idea to switch the font afterwards.

**Comment by kaalleen** [comment]
Can you try this one here?

https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-lettering_scale_group
