### ISSUE TITLE
Hidden objects become visible when the cloned group is stitched although they are ignored in the original group.

### ISSUE THREAD

**Issue by ToonChopper** [inkstitch/inkstitch#3167]
Hidden objects become visible in the stitch plan when the cloned group is stitched although they are ignored in the original group.

**Comment by capellancitizen** [comment]
Alright, thanks. I'll take a look at it.

**Comment by capellancitizen** [comment]
I've fixed this in main. If you need this fix now and are comfortable with running a development build, you can download and run https://github.com/inkstitch/inkstitch/releases/tag/dev-build-capellan-fix-cloning-hidden-elements. Otherwise it will be included in the next release.
