### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#317]
I need some help to convert Makefile (linux) to a batch / cmd file that windows can execute.
Especially at the section: locales I get stuck.
It's been a long time since I've worked with batch files, maybe someone of you has more recent handling of it. For any kind of help I would be very grateful.
```bash
 .PHONY: locales
locales:
        # message files will look like this:
        #   translations/messages_en_US.po
        if ls translations/*.po > /dev/null 2>&1; then \
                for po in translations/*.po; do \
                        lang=$${po%.*}; \
                        lang=$${lang#*_}; \
                        mkdir -p locales/$$lang/LC_MESSAGES/; \
                        msgfmt $$po -o locales/$$lang/LC_MESSAGES/inkstitch.mo; \
                done; \
        else \
                mkdir -p locales; \
        fi
```
the current version of the .appveyor can be found [here](https://github.com/AkiraNorthstar/inkstitch/blob/master/.appveyor.yml).
The build can be viewed [here](https://ci.appveyor.com/project/AkiraNorthstar/inkstitch).

**Comment by lexelby** [comment]
I think this was back when we were dreaming of 3-platform support.  Now that we have it with GitHub Actions, I think we can close this.
