### ISSUE TITLE
Stitch plan preview with AppImage on linux

### ISSUE THREAD

**Issue by maikenbjerg** [inkstitch/inkstitch#3177]
Opened attatched .svg file and tried different options in the extension. When using the "Params", the window never show up.
This log came after using something else than params. Using Inkscape 1.3.2

From Inkscape error log:

Ubuntu 22.04.4 LTS

Ink/Stitch Version: v3.1.0 (linux) 2024-07-27 09:12

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/stitch_plan_preview.py", line 61, in effect
  File "lib/extensions/stitch_plan_preview.py", line 123, in rasterize
  File "lib/extensions/utils/inkex_command.py", line 220, in inkscape
  File "lib/extensions/utils/inkex_command.py", line 186, in call
  File "lib/extensions/utils/inkex_command.py", line 152, in _call
inkex.command.ProgramRunError: Return Code: -5: b"\n(inkscape:214521): GLib-GIO-ERROR **: 20:45:35.133: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'\n"
b''
args: ('Return Code: -5: b"\\n(inkscape:214521): GLib-GIO-ERROR **: 20:45:35.133: Settings schema \'org.gnome.settings-daemon.plugins.xsettings\' does not contain a key named \'antialiasing\'\\n"\nb\'\'\nargs: (\'inkscape\', -5, b"\\n(inkscape:214521): GLib-GIO-ERROR **: 20:45:35.133: Settings schema \'org.gnome.settings-daemon.plugins.xsettings\' does not contain a key named \'antialiasing\'\\n", b\'\', [\'/usr/bin/inkscape\', \'--actions=select-by-id: __inkstitch_stitch_plan__; query-x; query-y; query-width; query-height; export-id: __inkstitch_stitch_plan__; export-id-only; export-type: png; export-dpi: 300; export-png-color-mode: RGBA_16; export-filename: /tmp/tmp5ldh7ts5/temp.png; export-do\', \'/tmp/tmp5ldh7ts5/temp.svg\'])',)

![osaa_symbol_neon_rgb](https://github.com/user-attachments/assets/6533dcca-3782-4f52-810b-982a185f452a)

**Comment by kaalleen** [comment]
Hm, can you try the ppa version instead of the AppImage (Inkscape). Looks as if your system runs into issues with the AppImage.

https://inkscape.org/release/inkscape-1.3.2/gnulinux/ubuntu/ppa/dl/

**Comment by kaalleen** [comment]
No further response. Closing.
If this is still an issue, we will reopen.
