### ISSUE TITLE
Lettering Tool Won't Display Multiple Letters

### ISSUE THREAD

**Issue by cwengland1** [inkstitch/inkstitch#3178]
I downloaded a font from Etsy and followed a tutorial online to add it to my custom font directory. After I apply the lettering tool, it does not show up on my screen. It is listed as being on the layer, but it is not visible. HELP!

**Comment by kaalleen** [comment]
It is really hard to say what is going wrong without the font files. If you don't mind, can you send your zipped font folder to https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

We will use it for debugging only.

**Comment by kaalleen** [comment]
Closing as conversation hasn't been going on. You can still post answers or questions here if you couldn't solve your problem yet.
