### ISSUE TITLE
Issue with inkstich

### ISSUE THREAD

**Issue by Skmayfi** [inkstitch/inkstitch#3179]
![010](https://github.com/user-attachments/assets/72c4842d-a04e-4ae1-80e0-b5cd78249e06)
this in on windows

**Comment by Skmayfi** [comment]
The above is what ink stich started doing a couple of days ago I dont know what happened.  I must have changed something
but I dont know what. Please help

**Comment by tyrosinase** [comment]
Is that Letttering (or otherwise satin-stitching) that has acquired a fill color in addition to (or instead of) a stroke color? Or is it happening to all new objects?

**Comment by capellancitizen** [comment]
Would you be okay with attaching your .svg file? It would help us debug the issue.

**Comment by Skmayfi** [comment]
yes its lettering it should say Edward I have tried different fonts and it
still does this, I also tried some inkstich fonts and it was close to as bad

**Comment by Skmayfi** [comment]
Here is the svg

**Comment by kaalleen** [comment]
Sorry, uploads to GitHub can only be done through the website, not via mail. Could you try again?

If I have to guess, I would say that the font very small. So small, that the fill algorithm can't produce a nice looking path. So your best bet would be to use satins or even running stitch, depending on the real size.

Have a look at the font library if there is any font which looks similar and could work for you. It could take away a lot of work if this is true: https://inkstitch.org/fonts/font-library/
If you find a font, use it with the Ink/Stitch lettering tool: `Extensions > Ink/Stitch > Lettering`

The lettering tool has a font size filter. You can set the height of the font and it will list only the fonts which are possible to embroider in given size. It will also automatically adapt the scale value to the given size. The fonts are all tested in various sizes and won't be good if they are scaled further down on canvas without a manual adaption for smaller sizes. Small fonts are a bit tricky.

**Comment by Marif91** [comment]
Le changement est dans les préférences de Inkstitch. Voici 2 plans de broderie avec des préférences différentes. Dans le premier j'ai demandé la longueur de point minimale à 6mm, il ignore tous les points plus courts, dans le deuxième j'ai mis la longueur minimale à 0mm et tous les points sont exécutés !
<img width="783" alt="Capture d’écran 2024-09-05 à 12 06 06" src="https://github.com/user-attachments/assets/3ba553d7-b1d0-4507-b615-f033016e521f">
<img width="986" alt="Capture d’écran 2024-09-05 à 12 05 17" src="https://github.com/user-attachments/assets/7b5b3cce-2611-409d-aa03-331803d253af">

**Comment by kaalleen** [comment]
Although it might look better on screen, don't try to set the general minimum stitch length to zero. It may cause double stitches and produce bad outputs. It'd be better to keep the design within stitchable parameters.

I'm going to close the issue, since I do not really see anything we can do about it. If you disagree or have suggestions for improvements (or more questions on the design), you can still comment here.
