### ISSUE TITLE
Docs: X11 workaround is hard to discover

### ISSUE THREAD

**Issue by Vectornaut** [inkstitch/inkstitch#3189]
On my system, launching Inkscape in the usual way and then using a Ink/Stitch menu item like *About* or *Params* leads to an uninformative failure: Ink/Stitch either throws a system error or does nothing except make the *Extensions* menu hang for a few seconds. This is because Ink/Stitch only works when Inkscape is running under X11 rather than Wayland. It's very hard to discover this, because:
- Neither the setup section of the [user manual](https://inkstitch.org/docs/install/) nor the [beginner tutorial](https://youtu.be/Dkb5UvsZUNg) mentions it.
- The [relevant instruction](https://inkstitch.org/docs/install-linux/#inkstitch-dialogs-disappear-after-a-few-seconds) is buried deep in the troubleshooting guide.
- The symptom described in the troubleshooting guide ("Ink/Stitch dialogs disappear after a few seconds") doesn't match the symptom I experience.
- There are no instructions for checking whether the workaround is active.
  - For example, I missed the `export` part of the launch command in the workaround, so Inkscape still launched under Wayland. I eventually figured this out using [`xeyes`](https://askubuntu.com/a/1393619/). I would've gotten Ink/Stitch working sooner if this had been mentioned in the documentation.

### System details

* Operating system: Ubuntu 22.04
* Desktop environment: Gnome 42.9
* Windowing system: Wayland
* Inkscape version: 1.3.2 (1:1.3.2+202311252150+091e20ef0f)
* Ink/Stitch version: 3.1.0

**Comment by kaalleen** [comment]
The beginner tutorial videos are outdated, especially the install instructions. We are happy to receive updates though.

>  Ink/Stitch either throws a system error or does nothing except make the Extensions menu hang for a few seconds. 

Ok, until now we always got the disappears after a few seconds reports which have stopped after adding it to the documentation. So this seems to be new. How does your system error looks like, what does it say?

**Comment by kaalleen** [comment]
Workaround has been moved to a more discoverable section of the installation description.
