### ISSUE TITLE
install problem?

### ISSUE THREAD

**Issue by ashorts22** [inkstitch/inkstitch#3190]
I recently downloaded the update from July and now when I try to open the program it gives me a weird message. Then once I do get Into inkstitch it takes so so so much longer than before to load designs. 
<img width="492" alt="Screenshot 2024-09-11 at 1 01 05 PM" src="https://github.com/user-attachments/assets/66cd2197-99b5-4d19-94ad-72304071db54">

**Comment by kaalleen** [comment]
Looks like your inkscape preferences file got screwed up.
Go to `Edit > Preferences > System` and click on `Reset preferences`

**Comment by ashorts22** [comment]
Hi!! It’s not allowing me to even open the settings page.

**Comment by kaalleen** [comment]
Hm, ok... Can you then try if deleting the preferences.xml file manually? The location of the file is in the error message you've posted above.

**Comment by ashorts22** [comment]
Where do I access that

**Comment by kaalleen** [comment]
It's written into the error message:

/Users/alyssashorts/Library/Application/Support/org.inkscape.Inkscape/config/inkscape

and the file is named
preferences.xml

**Comment by kaalleen** [comment]
Could you solve your issue?

**Comment by ashorts22** [comment]
No. I just have to readjust the setting every time I open it.

**Comment by kaalleen** [comment]
Did you maybe delete the preferences file while inkscape was open? Can you try deleting it when it is closed?

**Comment by kaalleen** [comment]
The problem is that your preferences file somehow got corrupted. When you remove it from your harddrive Inkscape will recreate it the next time you run the program and hopefully will be able to save your preferences again.

The `preferences.xml` file is located in `/Users/alyssashorts/Library/Application Support/org.inkscape.Inkscape/config/inkscape`

When you delete the file I think it could fix your issue.

**Comment by kaalleen** [comment]
Did this solve your issue?

**Comment by ashorts22** [comment]
Sorry, I never fixed the issue but I have a work around and just reset the
setting every time. I don’t understand what you meant on how to fix it. But
i appreciate your time.
