### ISSUE TITLE
Attach Commands to Selected Objects on MAC version

### ISSUE THREAD

**Issue by pivi66** [inkstitch/inkstitch#320]
Hi,

if i try to attach a command to an object i get the following error message.

Traceback (most recent call last):
  File "inkstitch.py", line 24, in <module>
    # Probably not right, but we can at least try.
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/object_commands.py", line 120, in effect
  File "lib/extensions/object_commands.py", line 93, in add_commands
  File "lib/extensions/object_commands.py", line 30, in add_connector
  File "src/lxml/etree.pyx", line 2998, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 119, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 300, in lxml.etree._initNodeAttributes
  File "src/lxml/apihelpers.pxi", line 311, in lxml.etree._addAttributeToNode
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by pivi66** [comment]
This is the error when i use the version 1.19.0 copied to an empty extensions folder. 
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

Version 1.18.0 works. But with the commands issue. 
This is a different issue with the mac version.

**Comment by lexelby** [comment]
> if i try to attach a command to an object i get the following error message.

Whoops, that's definitely a bug!  I think this has nothing to do with Mac but is instead triggered by the translation code.  I've created #321 which should fix it.

**Comment by lexelby** [comment]
> Also when using the symbol function to drag a command on the drawing, the symbol is not displayed. (see Picture)

Huh, no idea.  It looks like maybe your symbol might have gotten placed into a layer that you've set to invisible?

> This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.

Whoa, that's weird.  I thought we fixed that issue long since.  If the new version with the translation fix doesn't also fix this problem, then I'll open a separate bug report.

**Comment by pivi66** [comment]
The unicode thing #321 works
![image](https://user-images.githubusercontent.com/22259914/45769156-0e14b600-bc3f-11e8-995b-0517752e5fb4.png)

But there is still the 1.19.0 error:

This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

This could be due to the new simulation window in 1.19.0

**Comment by lexelby** [comment]
Darn that's really weird.  I don't think it's due to the new simulation window.  @globalcow or anyone else with a mac, are you seeing this error with 1.19.0?

**Comment by kaalleen** [comment]
https://wiki.wxpython.org/wxPythonVirtualenvOnMac

This is seems to be an old issue ... the article at least is quiet old. Might it be of help?

**Comment by AkiraNorthstar** [comment]
inkscape 0.92.2? - We build actually with 0.92.3...

**Comment by globalcow** [comment]
Inkscape 0.92.3 is not yet available for macOS

**Comment by lexelby** [comment]
@AkiraNorthstar Yes, we do use inkscape 0.92.3 during the build, but the version doesn't really matter.  We're not linking against the Inkscape code or anything like that.  We just use (and bundle) inkex.py and the other option libraries.  They're designed to work with SVG files and not any specific version of inkscape.

**Comment by lexelby** [comment]
Looks like we have another person having this problem over in #322.  Let's let this issue for the Unicode bug and take the discussion of the framework error message over to #322.
