### ISSUE TITLE
Nothing happens when I run anything in Inkstitch

### ISSUE THREAD

**Issue by adean4087** [inkstitch/inkstitch#3203]
The program is there, its not greyed out, but it wont do anything. The simulator doesnt work. I cant preview the stitch plan. You hit ok/apply & nothing happens.

**Comment by tyrosinase** [comment]
What operating system and Ink/Stitch version are you using?

**Comment by adean4087** [comment]
> What operating system and Ink/Stitch version are you using?

The latest version. I double checked last night. I just downloaded for the first time a couple weeks ago. I'm also using a Macbook that is fully updated.

**Comment by tyrosinase** [comment]
That's usually a Rosetta issue, which I think is solved by `softwareupdate --install-rosetta --agree-to-license`.

If that's not it, then one of the Mac folks will have to jump in - they'll want to know exactly what flavor of macOS and processor you're on, I think.

**Comment by adean4087** [comment]
Thank you for your help. I will look into that.

**Comment by kaalleen** [comment]
Did the proposed solution fix your issue?

**Comment by mkurth0116** [comment]
I'm having the exact same issue. I guess I don't know what "Rosetta" is to know if that's the issue

**Comment by adean4087** [comment]
I ended up uninstalling it. I didn’t feel like downloading more things just for this program to work. Currently using Embrilliance instead.

**Comment by tyrosinase** [comment]
> I'm having the exact same issue. I guess I don't know what "Rosetta" is to know if that's the issue

There are two different processor families used on Macs, and Rosetta translates software written for one to work on the other. Here's an article (from 2020) about it: https://www.theverge.com/21304182/apple-arm-mac-rosetta-2-emulation-app-converter-explainer

```You don’t, as a user, interact with Rosetta; it does its work behind-the-scenes. “Rosetta 2 is mostly there to minimize the impact on end-users and their experience when they buy a new Mac with Apple Silicon,” says Angela Yu, founder of the software-development school App Brewery. “If Rosetta 2 does its job, your average user should not notice its existence.” ```

The flip side of that is, of course, if it isn't there to do its job, you notice its absence. 😉
