### ISSUE TITLE
auto-route running stitch error

### ISSUE THREAD

**Issue by einsweniger** [inkstitch/inkstitch#3205]
Heo!
I just tried to auto-route a running stitch and I broke it.
This could as well be a user-error, I might have done something wrong?

Running it with:

 - ☑ add nodes at intersections
 - ☐ preserve order of running stitches
 - ☐ trim jump stitches

<details>
<summary>gives this error message</summary>

```
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A335
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/auto_run.py", line 35, in effect
  File "lib/stitches/auto_run.py", line 123, in autorun
  File "lib/stitches/auto_run.py", line 160, in build_graph
  File "lib/stitches/auto_run.py", line 45, in __init__
  File "lib/stitches/auto_run.py", line 110, in _get_segments
  File "shapely/geometry/base.py", line 844, in project
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/linear.py", line 88, in line_locate_point
FloatingPointError: invalid value encountered in line_locate_point
```

</details>

After that I disabled the `add nodes at intersections` and inkscape crashed hard, unfortunately without an error message. After that, I tried again, and it worked with "add nodes at intersections" disabled

I can reproduce the above error message, but I cannot reproduce the crash. might have been something with inkscape.

![The offending svg](https://github.com/user-attachments/assets/35959906-e74f-4ea0-9d5d-9df22ab314e0)

**Comment by tyrosinase** [comment]
What version are you running? That error gets mentioned in #2705 and #2978 which implies that 3.1.0 fixed it, and of course the idiot in 2705 who first reported it (hi, I'm the problem, it's me) didn't record what file it happened in so I can't doublecheck.

Anyway, if you're not on the current version, upgrade and see if that fixes it. If it doesn't, can you either attach the SVG or, if it's not something you want public, send it to the devs? (I can dig up the address if you need it.)

**Comment by einsweniger** [comment]
I downloaded the latest version yesterday, the svg should be attached, you might not see it, if you use GitHub dark mode, tho. Black lines on transparent background 😅On 20. Sep 2024, at 16:13, Tyrosinase ***@***.***> wrote:﻿
What version are you running? That error gets mentioned in #2705 and #2978 which implies that 3.1.0 fixed it, and of course the idiot in 2705 who first reported it (hi, I'm the problem, it's me) didn't record what file it happened in so I can't doublecheck.
Anyway, if you're not on the current version, upgrade and see if that fixes it. If it doesn't, can you either attach the SVG or, if it's not something you want public, send it to the devs? (I can dig up the address if you need it.)

**Comment by tyrosinase** [comment]
Oh, the large gap at the end should have tipped me off. 🤦

It does work for me fwiw, on 3.1.0 Linux (though copypasting the version text doesn't):

![image](https://github.com/user-attachments/assets/e2a76f2b-dba6-45be-b875-04d53c8f7931)

Hopefully one of the devs can reproduce it though.

**Comment by einsweniger** [comment]
So, just to be sure: I should try to reproduce this, by installing the intel version of inkscape and the intel version of inkstitch? I’m pretty confident mixing arm/intel would be, … weird, at least. Just asking, to be sure 😅

**Comment by tyrosinase** [comment]
Yup, that's what the Rosetta is for.

**Comment by einsweniger** [comment]
intel version takes a long time to compute, but does so without any problems.
Inkscape v3.1.2 and inkstitch v3.1.0.

If none of the active devs have darwin-arm64 hardware, I can try to pinpoint the issue. If you have pointers on getting me started (what to test/where to look), that would be helpful!

**Comment by kaalleen** [comment]
Thank you for the offer. It should be fixed in current main already. It is caused by the geos version used. It caused problems for arm at the time of the last release, so it uses a different geos version from the other release packages.

Does it always take long or just the first time you used it?

**Comment by einsweniger** [comment]
I'd love to try the current version, but when you say "current main" is there a packaged pre-release for that? Right now, I want to avoid building inkstitch myself.

As for the timing, I can't pinpoint why this took so long the first time I tried it. I just tried to compare the intel Version with the native arm64 and they both took roughly the same time. Not sure what happened, but they both take about 3 secs to finish. I got no noticeable difference today. Sorry for the false alarm, there.

**Comment by kaalleen** [comment]
You can take one of the top releases from the release list.

It is expected that the intel version on arm processors will take longer the first time (this is when rosetta is doing its job). After that it shouldn't have a significant time difference anymore. So all good I guess.

**Comment by einsweniger** [comment]
I tried with the https://github.com/inkstitch/inkstitch/releases/tag/dev-build-claudine-add_magnolia_tamed_font pre-release,  unfortunately, it's not signed the way apple likes to have it and I can't open the .pkg, nor use the .app that's in the zip file. Maybe I"m not pressing the right buttons. Might be me, tho. It's late, idunno. I might try again tomorrow and build it myself.

**Comment by kaalleen** [comment]
Sorry, I should habe mentioned it. You can still open unsigned pkg files with a little trick:

https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by einsweniger** [comment]
no worries, I tried all the tricks that I know, I ended up downloading the pkg with wget. That way, it won't be flagged as quarantined. I can confirm that the auto route problem is gone with that pre-release, thank you!
