### ISSUE TITLE
Inkstich not working after installation

### ISSUE THREAD

**Issue by dbergstra** [inkstitch/inkstitch#3211]
Hi,

I've been trying to install Inkstitch v3.1.0 on my laptop running Ubuntu 24.04. I've been facing some issues that I'm not able to resolve. I've installed Inkscape 1.3.2 through an apt install. After that I've tried the following things:
1. Install the .db extension. The inkstitch extension is then present in /usr/share/inkscape/extensions
2. Download the tar and unpack in the .config/inkscape/extensions directory

With both options i installed Inkscape, openend Inkscape, closed Inkscape, installed extension, openend Inkscape etc.  

The result is in all cases the same. The extension does show up in the Extensions tab in Inkscape. And when I hover over "Inc/Stitch" I see all options you would expect. But when clicking on of the options for example "Params" or even "About", nothing happens.

Some assistance would be appreciated. Thanks in advance!

Dana`

**Comment by tyrosinase** [comment]
Can you try running it from the command line, and see if it shows you any errors there? ISTR running into this with a Debian install and there was something missing in python, but I've forgotten what it was.

**Comment by kaalleen** [comment]
This is most probably due to wayland. Try this workaround and start inkscape with `export GDK_BACKEND=x11 && inkscape`

**Comment by dbergstra** [comment]
Great thanks! The command `export GDK_BACKEND=x11 && inkscape` did the trick for me.
