### ISSUE TITLE
Mac 10.13.6 Need Access to screen issue

### ISSUE THREAD

**Issue by ponoproductions** [inkstitch/inkstitch#322]
![img_8807](https://user-images.githubusercontent.com/43433624/45801473-b16dc700-bc4f-11e8-82e8-f81e8ff0792d.jpeg)
![img_8806](https://user-images.githubusercontent.com/43433624/45801474-b16dc700-bc4f-11e8-892f-bb755ae62f54.jpeg)
![img_8805](https://user-images.githubusercontent.com/43433624/45801476-b16dc700-bc4f-11e8-9d4a-4e6735fb1bbc.jpeg)

Hello,

Recently discovered inkstitch extension for inkscape, and in order to get it correctly installed, I had to Fresh installed OS last night. My current OS version 10.13.6 High Sierra from 10.12.3 Yosemite on an Early 2011 Mac Book Pro.
After starting up inkscape and attempting to use inkstitch i received the above pictured "this program needs access to the screen" message while using PARAMS

After OS installed, and repeatedly receiving the above error, I decided to delete completely and conducted fresh re-install of inkscape 0.92.2 and fresh re-install of inkstitich, in attempt to rectify the error.

Unfortunately message still persists when i attempt to run the param and other selections in the inkstitch extension.

Hoping someone had else might have came across the same issue and are willing to share any thoughts or ideas. Any input / questions would be greatly appreciated.

Aloha! PONO

**Comment by AkiraNorthstar** [comment]
Reference: [#320](https://github.com/inkstitch/inkstitch/issues/320#issuecomment-422882424)

**Comment by globalcow** [comment]
I am facing the same error with ink/stitch 1.19.0, inkscape 0.92.2 and macOS 10.13.4
I also thought this problem was solved :-(

**Comment by lexelby** [comment]
Hi, and welcome to the project, @ponoproductions!

This is a bug we have seen previously. I thought we'd fixed it too. :(  Could you try with version 1.18.0?

**Comment by ponoproductions** [comment]
@lexelby Sure i would be happy to try 1.18.0 will LUK.

**Comment by ponoproductions** [comment]
@lexelby yes i would be happy to try to install 1.18.0... wondering where i might find the download for the older versions? Sorry totally noob.

**Comment by ponoproductions** [comment]
@lexelby Yes, I will LUK

**Comment by ponoproductions** [comment]
@lexelby OK 1.18.0 did not return errors for me... :) preview window opens and generates as expected it appears...

**Comment by lexelby** [comment]
Awesome!  That's great news.  I have some ideas about what might be going on with 1.19.0.

**Comment by lexelby** [comment]
I think I figured out what's wrong.  It might be an issue with pyinstaller 3.4 -- we already had problems on Linux with that version.

@ponoproductions Could you try this one?

https://github.com/inkstitch/inkstitch/releases/download/dev-build-lexelby-fix-mac/inkstitch-lexelby-fix-mac-osx-x86_64.tar.gz

@pivi66 You might also be interested :)

**Comment by ponoproductions** [comment]
@lexelby looks like this build is a success on my machine. Love the stitch preview slider addition by the way.  will stitch a patch up tonight to confirm a successful export to .JEF and LUK.

**Comment by ponoproductions** [comment]
@lexelby Success!
![img_8832](https://user-images.githubusercontent.com/43433624/45914544-296bf680-bde2-11e8-960a-14d9547bfadf.jpeg)

**Comment by AkiraNorthstar** [comment]
Looks very nice!
@lexelby we should have a showcase (user work) on inkstitch.org.

**Comment by globalcow** [comment]
> I think I figured out what's wrong. It might be an issue with pyinstaller 3.4 -- we already had problems on Linux with that version.
> 
> @ponoproductions Could you try this one?
> 
> https://github.com/inkstitch/inkstitch/releases/download/dev-build-lexelby-fix-mac/inkstitch-lexelby-fix-mac-osx-x86_64.tar.gz
> 

Works for me too!

There are some glitches in the new simulator window, hidden buttons and text overlaying. I attached a screenshot. However, everything works well!

<img width="620" alt="inkstitch-simulator-glitch" src="https://user-images.githubusercontent.com/2294737/45915778-7344f300-be5b-11e8-9d15-d6e74f1ac967.png">

By the way, is there a reason, that I have two ink/stitch menus? One in German and one in English?

**Comment by AkiraNorthstar** [comment]
> By the way, is there a reason, that I have two ink/stitch menus? One in German and one in English?

German: Zur Zeit gibt es dort noch keine richtige Lösung. Du kannst unter dem Inkstitch Verszeichnis die *en_US.inx Dateien löschen, dann hast Du keine doppelten Einträge unter: "Datei Speichern unter.." und im Erweiterungsmenü (Ink/Stitch -> Deutsch / Ink/Stitch -> Englisch).

**Comment by lexelby** [comment]
Awesome!  I'll combine both fixes and release 1.19.1 later today.

**Comment by pivi66** [comment]
Sounds gerat !

**Comment by lexelby** [comment]
Okay, v1.19.1 is out!  Thanks everyone for your help in testing.

@globalcow v1.19.1 also contains @kaalleen's fixes for the button squishing/overlaying issue that you're seeing.

> By the way, is there a reason, that I have two ink/stitch menus? One in German and one in English?

Given the way that Inkscape does internationalization of extension definition files, having multiple menus like that is the only feasible way we could provide translations for the extension menus.  If you'd like you can delete all the .inx files except for the ones in your language (e.g. en_US for English).  I think maybe that's what AkiraNorthstar said up there but I'm not sure :)

**Comment by globalcow** [comment]
>  I think maybe that's what AkiraNorthstar said up there but I'm not sure :)

Yeah, it is 😄 Thank you!

**Comment by lexelby** [comment]
> @lexelby we should have a showcase (user work) on inkstitch.org.

Great idea!  I've wanted something like that for awhile.  We have a gallery section with my stuff but I definitely want everyone else's there too.  Examples (especially closeups like @ponoproductions's above) will help people decide whether Ink/Stitch is worth downloading.

@kaalleen Do you think there's room on the site for a gallery?

**Comment by pivi66** [comment]
@lexelby 1.19.1 is working great job!

**Comment by lexelby** [comment]
Wonderful!  Glad to hear it!

**Comment by kaalleen** [comment]
> @kaalleen Do you think there's room on the site for a gallery?

Yes, sure. Existing gallery can be found here: https://inkstitch.org/tutorials/inspiration/
It's easy to add more in. But we need images and permissions for that.
