### ISSUE TITLE
From line with power stoke to satin collumn

### ISSUE THREAD

**Issue by antonfrancois** [inkstitch/inkstitch#3220]
Hello,

Thanks a lot for developing ink-stitch I had a lot of fun playing with it.

A feature I would like to be seen is the following. It is possible to change the width of a line with the path effect "[power stroke](https://wiki.inkscape.org/wiki/PowerStroke)". When I try to convert such a line to a satin column it fails with the error "Only simple lines may be converted to satin columns.". 
It would be neat to be able to convert directly such a "power" line it would be way simpler than having to create a "[Manual Satin Column](https://inkstitch.org/docs/stitches/satin-column/#4-manual-satin-column)" that require to construct two paths etc,.

1. Is it possible to implement this feature into Inkstich? 
2. Do you happen to know a workaround procedure to generate the outer-edges of the powerstoke to the two lines needed to make a Manual Satin Column ?  (I have tried something with converting the stroke of my power stroke to a path, but that's a dead end).

Cheers,
Anton

**Comment by kaalleen** [comment]
It should be relatively easy to convert a power stroke into a satin. Just convert it to a path (Shift + Ctrl + C) and break it open at start and end. Add some rails and apply satin params.

**Comment by antonfrancois** [comment]
That works indeed! Thanks a lot ! This trick will save me a lot of time.

**Comment by antonfrancois** [comment]
That works indeed! This trick will save me a lot of time. Thank you.
