### ISSUE TITLE
"inkstitch has stopped unexpectedly" / "inkstitch crashed with signal 5 in g_settings_get_enum()" under Ubuntu 

### ISSUE THREAD

**Issue by maehw** [inkstitch/inkstitch#3226]
Hi,

I wanted to try Ink/Stitch for the first time.

I installed the latest release (according to https://inkstitch.org/docs/install-linux/ from 27.07.2024) as deb package file for my Linux distribution (Ubuntu 22.04 LTS): [inkstitch_3.1.0_amd64.deb](https://github.com/inkstitch/inkstitch/releases/latest/download/inkstitch_3.1.0_amd64.deb) 

Unfortunately, when trying to perform the 2nd step from the [Basic Usage docs page](https://inkstitch.org/docs/basic-usage/) - inkstitch crashes more or less silently. I've only seen the following crash report pop up: 
![Screenshot from 2024-10-07 21-50-52](https://github.com/user-attachments/assets/9fa2d0a5-80ae-42f8-91eb-3abd7be25034)

This initially happened for a different file, but it is reproducible for the following minimalistic SVG file with a circle:
![circle](https://github.com/user-attachments/assets/f62789fd-7efe-4766-996b-d94d04bc0f9a)

The steps I made:
1. Open the file in Inkscape (or create a new SVG file and draw a circle)
2. Select the shape
3. From the menu, select: Extensions > Ink/Stitch > Params

An excerpt from the crash file:

```
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: ubuntu:GNOME
Date: Mon Oct  7 21:53:02 2024
DistroRelease: Ubuntu 22.04
ExecutablePath: /opt/inkstitch/bin/inkstitch
ExecutableTimestamp: 1722071641
ProcCmdline: /usr/share/inkscape/extensions/inkstitch/inx/../bin/inkstitch --id=path12 --extension=params /tmp/ink_ext_XXXXXX.svgRCY9U2
ProcCwd: /var/crash
ProcEnviron:
 SHELL=/bin/bash
 LC_ADDRESS=de_DE.UTF-8
 LC_NAME=de_DE.UTF-8
 LC_MONETARY=de_DE.UTF-8
 LC_PAPER=de_DE.UTF-8
 LANG=en_US.UTF-8
 TERM=xterm-256color
 LC_IDENTIFICATION=de_DE.UTF-8
 LC_TELEPHONE=de_DE.UTF-8
 LC_MEASUREMENT=de_DE.UTF-8
 XDG_RUNTIME_DIR=<set>
 LC_TIME=de_DE.UTF-8
 PATH=(custom, user)
 LC_NUMERIC=de_DE.UTF-8
 LD_LIBRARY_PATH=<set>
```

More details:

```
$ inkscape --version
Inkscape 1.1.2 (0a00cf5339, 2022-02-04)
$ uname -a
Linux redacted 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

Please let me know if you have any idea how I could assist debugging this - or fix it on my machine if this is a known bug.

**Comment by kaalleen** [comment]
It is known, that Ink/Stitch has problems with running on wayland. Can you test if starting Inkscape with the following command solves the issue?

`export GDK_BACKEND=x11 && inkscape`

**Comment by maehw** [comment]
Thanks, @kaalleen - that seems to do the trick.

And it outs me as a simple Linux user and not being an export.

TIL: "Wayland is a replacement for the X11 window system protocol and architecture with the aim to be easier to develop, extend, and maintain."

I event read about it on the [Install Ink/Stitch on Linux](https://inkstitch.org/docs/install-linux/) but was totally unaware of what it is.. and that it could affect me. So sorry for the issue report.

I suggest to elaborate on the doc page about

- what "has known issues" looks like in practice,
- a short description about "what wayland is" or "how to test if you're running(?) wayland in advance" (like in Ubuntu: Settings > About > Windowing System).

Maybe other Linux users just know.

Thanks!

**Comment by tyrosinase** [comment]
It's not just you. I know that it's a thing, but I have been using Linux for twenty years and only remember which one my machine uses (X11) when Kaalleen mentions the solution. (I am a [retired] developer, not a sysadmin though; spouse is a sysadmin but on servers where it really doesn't come up.)
