### ISSUE TITLE
Crashing continuously

### ISSUE THREAD

**Issue by sarawas** [inkstitch/inkstitch#3231]
Hi, It started crashing when attempting a bezier line with triangle out, then everytime I tried to open program again it crashed within a second or 2, managed to delete triangle, attempted to use 'star' with 3 sides for triangle, it crashed again. In total crashed 6 times, can't even use original svg now without crashing

<pre>
 0# boost::stacktrace::basic_stacktrace<std::allocator<boost::stacktrace::frame> >::init(unsigned long long, unsigned long long) in libinkscape_base
 1# Inkscape::Application::crash_handler(int) in libinkscape_base
 2# 0x00007FF6F34A21B2 in inkscape
 3# _C_specific_handler in ntdll
 4# _chkstk in ntdll
 5# _RtlRaiseException in ntdll
 6# _KiUserExceptionDispatcher in ntdll
 7# count_pathvector_curves(Geom::PathVector const&) in libinkscape_base
 8# Inkscape::LivePathEffect::LPEPowerStroke::doEffect_path(Geom::PathVector const&) in libinkscape_base
 9# Inkscape::LivePathEffect::Effect::doEffect(SPCurve*) in libinkscape_base
10# SPLPEItem::performOnePathEffect(SPCurve*, SPShape*, Inkscape::LivePathEffect::Effect*, bool) in libinkscape_base
11# SPLPEItem::performPathEffect(SPCurve*, SPShape*, bool) in libinkscape_base
12# SPShape::update_patheffect(bool) in libinkscape_base
13# sp_lpe_item_update_patheffect(SPLPEItem*, bool, bool, bool) in libinkscape_base
14# SPObject::emitModified(unsigned int) in libinkscape_base
15# SPDefs::modified(unsigned int) in libinkscape_base
16# SPObject::emitModified(unsigned int) in libinkscape_base
17# SPGroup::modified(unsigned int) in libinkscape_base
18# SPRoot::modified(unsigned int) in libinkscape_base
19# SPObject::emitModified(unsigned int) in libinkscape_base
20# SPDocument::_emitModified() in libinkscape_base
21# SPDocument::idle_handler() in libinkscape_base
22# Glib::IdleSource::dispatch(sigc::slot_base*) in libglibmm_2_4_1
23# _g_clear_list in libglib_2_0_0
24# _g_get_monotonic_time in libglib_2_0_0
25# _g_main_context_iteration in libglib_2_0_0
26# _g_application_run in libgio_2_0_0
27# 0x00007FF6F34A39AB in inkscape
28# 0x00007FF6F34A12EE in inkscape
29# 0x00007FF6F34A13E6 in inkscape
30# _BaseThreadInitThunk in KERNEL32
31# _RtlUserThreadStart in ntdll
</pre>
<details><summary>System info</summary>
Inkscape 1.3.2 (091e20e, 2023-11-25, custom)

    GLib version:     2.78.1
    GTK version:      3.24.39
    glibmm version:   2.66.6
    gtkmm version:    3.24.8
    libxml2 version:  2.11.5
    libxslt version:  1.1.38
    Cairo version:    1.18.0
    Pango version:    1.50.14
    HarfBuzz version: 8.2.2

    OS version:       Windows 10 22H2
</details>
![new watch svg 2024_10_12_15_51_21 0](https://github.com/user-attachments/assets/d79becc0-592e-4c58-826b-eaa630c2ac63)

**Comment by kaalleen** [comment]
Looks more as if that is an inkscape issue rather than Ink/Stitch problem. They are about to release a new version (supposedly today, maybe a few days more). So maybe you wait for the new version (or run the release candidate version) and install it. See if this helps with solving the issue and if it doesn't, go ahead and report at https://inkscape.org/report

**Comment by sarawas** [comment]
Thanks, I will do

**Comment by kaalleen** [comment]
Great. I'll close this. As there is nothing we can do as an extension. You are still welcome to add comments to this thread if there is more to discuss.
