### ISSUE TITLE
How to get my params to show up

### ISSUE THREAD

**Issue by SeasideCustom** [inkstitch/inkstitch#3249]
I just downloaded the Inkscape and Ink stitch yesterday. I have watched so many videos, but I'm not making any progress. I was doing a test run and added a simple circle and the went to Extension and clicked Ink stitch and params, and a white box openes and closes within a second. What am I doing wrong?

**Comment by Marif91** [comment]
tu travailles sur quel système ?

**Comment by kaalleen** [comment]
If this is Linux, try this workaround: https://inkstitch.org/docs/install-linux/#some-inkstitch-dialogs-disappear-after-a-few-seconds-or-dont-show-up-at-all

**Comment by kaalleen** [comment]
Closing. No further response.
