### ISSUE TITLE
Linux error missing bin/inkstitch

### ISSUE THREAD

**Issue by KitsuLilith** [inkstitch/inkstitch#3250]
critical **: 4:04:33.357: Script::execute():failed to execute program 'home/kitsune/.config/inscape/extensions/inkstitch/inx/../bin/inkstitch'.
              Reason: Failed to execute child process "home/kitsune/.cong/inkscape/extensions/inkstitch/inx/../bin/inkstitch" (No such file or directory)

I am running linux on on a samsung galaxy tablet with termux 11, using debian xfce4. I get this error when trying to use anything in the inkstitch menu. Thank you in advance for any help/

**Comment by kaalleen** [comment]
Did you follow the tutorial on our website?

**Comment by KitsuLilith** [comment]
> Did you follow the tutorial on our website?

Yes and tried the back end fix añd it didn't work.

**Comment by KitsuLilith** [comment]
Oh that must have been my mistake when writing it over. It says .config. my console will not let me right click. Sorry about that. 

> I'm assuming something happened while transcribing the errors but just in case:
> 
> `critical **: 4:04:33.357: Script::execute():failed to execute program 'home/kitsune/.config/inscape/extensions/inkstitch/inx/../bin/inkstitch'.`
> 
> is showing "inscape" in the path name, and:
> 
> `Reason: Failed to execute child process "home/kitsune/.cong/inkscape/extensions/inkstitch/inx/../bin/inkstitch" (No such file or directory)`
> 
> has ".cong" instead of ".config."
> 
> If that's the actual error you're getting, something strange happened in the install process.

**Comment by tyrosinase** [comment]
> Oh that must have been my mistake when writing it over. It says .config. my console will not let me right click. Sorry about that.

I figured it was something like this, though I couldn't figure out why you'd have to manually type it (probably because I glossed right over the "galaxy tablet" part; clearly I can spot errors in some text without even reading other text 🤷)

I use a Galaxy to do some SVG work (100% have forgotten the name of the app though) but I transfer the file over to a desktop box to add the embroidery bits. Kind of tempted to try Termuxing it now - have you run Inkscape successfully *without* Ink/Stitch?

**Comment by KitsuLilith** [comment]
> > Oh that must have been my mistake when writing it over. It says .config. my console will not let me right click. Sorry about that.
> 
> I figured it was something like this, though I couldn't figure out why you'd have to manually type it (probably because I glossed right over the "galaxy tablet" part; clearly I can spot errors in some text without even reading other text 🤷)
> 
> I use a Galaxy to do some SVG work (100% have forgotten the name of the app though) but I transfer the file over to a desktop box to add the embroidery bits. Kind of tempted to try Termuxing it now - have you run Inkscape successfully *without* Ink/Stitch?

Yes it runs inkscape beautifully. You just have to have a mouse and keyboard.

**Comment by lexelby** [comment]
I'm almost certain that the problem is that Ink/Stitch is not compiled for the type of CPU in your tablet.  Ink/Stitch is built for Linux systems running on Intel and AMD CPUs.  I'm pretty sure your tablet has an ARM64 CPU.  The "No such file or directory" is kind of a red herring, it actually means "no usable binary found".

**Comment by KitsuLilith** [comment]
I've solved it!! 
I went back and installed arch instead of debian and it works perfectly!

**Comment by tyrosinase** [comment]
> I'm almost certain that the problem is that Ink/Stitch is not compiled for the type of CPU in your tablet.

KitsuLilith may know for sure but I thiiiiiiink Termux does the same kind of magic emulation that Rosetta does for Macs. I could be wrong (and as a veteran of the Z80/68xx/6502 architecture wars I would sort of like to be; one should not simply be able to run a binary on the "wrong" CPU!)

**Comment by KitsuLilith** [comment]
You are correct I was using the one for computers and not the arm64. Once I switched to arch and used the one in the inkstitch on Android and tablet tutorial it all works right I can even right click in the console unlike in debian. Thank you all for your help even though it turned out to be user error on my part.

**Comment by kaalleen** [comment]
> KitsuLilith may know for sure but I thiiiiiiink Termux does the same kind of magic emulation that Rosetta does for Macs

No, it doesn't. But there is a special file in it's own repo (GitHub doesn't like huge file uploads), linked in the tutorial.

https://inkstitch.org/tutorials/inkstistch-on-android/

**Comment by lexelby** [comment]
Whoa, I didn't realize we had an ARM version!
