### ISSUE TITLE
varigated stitch lenght  feature request

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3265]
As i was exploring the newest development version i noticed that the varigated satin stitch lenght is not available anymore

I would like to ask if it would be able to be reimplemented since i really use it a lot and i find it gives the design a nicer look then  the regular fill with a repeat option

Thank you
Gus visser

**Comment by kaalleen** [comment]
I'm not aware that anything has been removed?

**Comment by gusvisser** [comment]
I got everything going 

idid a reinstall and it is working now

Sorry for the confusion

Gus Visser
