### ISSUE TITLE
Unexpected error when running convert line to satin

### ISSUE THREAD

**Issue by JochemPalmsens** [inkstitch/inkstitch#3267]
I got an error when selecting all the paths in the group "nerven" and running "convert line to satin".
Specifically, one of the "horz lijn boven" gives this error.

But while I'm here: it is a bit annoying that every time I run "convert line to stitch" it collapses all my groups! That takes me out of my workflow.

![kersentuin logo - BORDUREN - backup](https://github.com/user-attachments/assets/faed2823-d7a1-4310-b549-0726fd4494c1)

Message:

> Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.
> 
> Windows 10 version: 10.0.19045
> 
> Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04
> 
> Traceback (most recent call last):
>   File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
>   File "lib\extensions\convert_to_satin.py", line 142, in path_to_satin
> lib.extensions.convert_to_satin.SelfIntersectionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
>   File "lib\extensions\convert_to_satin.py", line 142, in path_to_satin
> lib.extensions.convert_to_satin.SelfIntersectionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 162, in <module>
>   File "inkex\base.py", line 252, in run
>   File "lib\extensions\convert_to_satin.py", line 61, in effect
>   File "lib\extensions\convert_to_satin.py", line 89, in convert_path_to_satins
>   File "lib\extensions\convert_to_satin.py", line 89, in convert_path_to_satins
>   File "lib\extensions\convert_to_satin.py", line 75, in convert_path_to_satins
>   File "lib\extensions\convert_to_satin.py", line 162, in path_to_satin
>   File "lib\extensions\convert_to_satin.py", line 263, in generate_rungs
>   File "lib\extensions\convert_to_satin.py", line 194, in get_scores
>   File "lib\utils\geometry.py", line 294, in unit
> ZeroDivisionError: float division by zero
> 
>

**Comment by kaalleen** [comment]
Thank you so much for the very helpful error report. The error is reproducible. That's good, so we can fix it.

About the collapsing group problem I'm afraid we as an extension can't do anything about it. But you can direct the request to the Inkscape team at https:/inkscape.org/report

**Comment by kaalleen** [comment]
Oh, if you need to fix the problem for yourself...
The line which is giving the error is doubled up. Select one of the two nodes and open the path (Shift + B). Then delete the node.

**Comment by JochemPalmsens** [comment]
Thanks for the feedback! Ah, I missed that. (Didn't even know that was a thing, but now I know what I did wrong.)

However, when I remove a path using the node editor "remove path between selected nodes" and run "convert to line to satin" two paths are created (on top of each other). So still not great.

But I got it working.
![WhatsApp Image 2024-11-03 at 12 17 49_34081ffd](https://github.com/user-attachments/assets/612d04aa-6a74-41eb-ab2c-89a9ef015ee6)

(There appears to be backlash in the machine on the Y axis, so got some ugly lines 😢 )

**Comment by JochemPalmsens** [comment]
@kaalleen Ok clear and insightfull.

It seems I need to use "gap compensation" in the parameters tab to compensate the distortion.
However, the effect is a bit weird: it seems like the gap compensation doesn't adhere to the path edges and places stitches _outside_ of the fill area path..

Should be empty circle
![afbeelding](https://github.com/user-attachments/assets/7e7c0701-cff6-442e-8347-c060d6b37354)

outside of outer edge
![afbeelding](https://github.com/user-attachments/assets/cd0237bd-799e-44de-b83a-725decbe84f9)

but maybe that's the point? Since due to the distortion it's actually stitches in-place? Or is it a bug?

**Comment by JochemPalmsens** [comment]
Nah, I think it's a bug: here there's no distortion that should be compensated this way
![afbeelding](https://github.com/user-attachments/assets/4aacec55-16e4-4436-97e0-562fe5730228)

**Comment by kaalleen** [comment]
Pull compensation lengthen the lines  in %. This means longer lines add more stitches than shorter lines. So these edges are expected behavior. That's not much of your problem though. Remove the holes and stitch your circles on top. It doesn't make sense to cut out the little holes from the filling, that will actually add extra stitches and stiffness - unnecessarily. That will also enable you to stitch the whole area in one go without moving from section to section. So you won't have line gaps in the first place.

**Comment by JochemPalmsens** [comment]
Thanks for your response. I'll try without the holes

However, about this (potential) bug and your answer to it:
I'm not sure if we are talking about the same thing? I didn't enable pull compensation (it's still at 0mm/0%) I just enabled "gap filling" and set it to 4 lines. 
I think the lines (edges) aren't properly generated, as they move outside of the path.

so even if I fix my issue by not having the holes, There might be an issue with "gap filling" that other will encounter?

**Comment by JochemPalmsens** [comment]
I removed the holes, but autofill is still dividing the fill in two areas: on from bottom right to middle and the follow-up from left top to middle. So there will still be a line due to the distortion in the middle (which will probably require gap-filling)...

![afbeelding](https://github.com/user-attachments/assets/130a5325-624d-4b11-9901-9638aaa6236c)

**Comment by kaalleen** [comment]
> I'm not sure if we are talking about the same thing? I didn't enable pull compensation (it's still at 0mm/0%) I just enabled "gap filling" and set it to 4 lines.

Oh, ok. I didn't realize that. So that isn't what we would expect.

> Is there a way not to have it jump? i.e. actually fill the whole area in one go/from one side to the end?

Set start and end commands, for example start top left corner and and bottom right.
