### ISSUE TITLE
set clip with tiling 

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3271]
I would like to ask if you could check if the cookie cutting with the tiling and set clip are still working because i tried it and did not seem to want to work and reread the tutorial on the webpage and followed all directions and cannot get it to work  
![image](https://github.com/user-attachments/assets/43719e7e-9215-4ce1-acad-17ff3ddb68cb)

Gus Visser

**Comment by kaalleen** [comment]
Clipping should still work. In current versions it doesn't work when the clip is applied to a group. This may change in the next version. I could check your file when you send it over.

**Comment by gusvisser** [comment]
Thank you for the info it resolved my issue Thank you

Gus Visser
