### ISSUE TITLE
error applying thread color palette

### ISSUE THREAD

**Issue by ricardoquesada** [inkstitch/inkstitch#3273]
ProductName:		macOS
ProductVersion:		15.1
BuildVersion:		24B83
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

```
Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/apply_palette.py", line 42, in effect
AttributeError: 'NoneType' object has no attribute 'nearest_color'
```

To reproduce it:

- Try to apply the Floriani or Isacord palette

![pal](https://github.com/user-attachments/assets/dd25ad79-22dd-465e-b619-f175ffb7cd71)

**Comment by kaalleen** [comment]
So strange, I cannot reproduce the error. @rejbasket can you?

**Comment by kaalleen** [comment]
Oh, that's interesting. I suppose you do not have the color palettes for Inkscape installed?
Does it work if you do?
