### ISSUE TITLE
 a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by staalplaat59** [inkstitch/inkstitch#3275]
I got a error report with the request to report it so here I am:
I included the svg file, I am new here so I hope I did this correct

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/auto_run.py", line 35, in effect
  File "lib/stitches/auto_run.py", line 123, in autorun
  File "lib/stitches/auto_run.py", line 160, in build_graph
  File "lib/stitches/auto_run.py", line 45, in __init__
  File "lib/stitches/auto_run.py", line 110, in _get_segments
  File "shapely/geometry/base.py", line 844, in project
  File "shapely/decorators.py", line 77, in wrapped
  File "shapely/linear.py", line 88, in line_locate_point
FloatingPointError: invalid value encountered in line_locate_point
![herta-vlag6xx kl](https://github.com/user-attachments/assets/3212cb6a-61cb-4384-9778-63239f3242b4)

**Comment by tyrosinase** [comment]
I think this is the same error as in #3205, though I'm not clear from the comments whether switching to the Intel/Rosetta setup is the fix, or using a prerelease version.

**Comment by staalplaat59** [comment]
I use ink/stitch  v3.1.0 (osx)  and inkskape 1.4 (e7c3feb1,2024-20-9)  don't think I use intel/rosetta (ore not that I know of)

**Comment by kaalleen** [comment]
Sadly we can't see which exact version you are using (intel or arm). So you might want to install a development version for arm and see if the bug still shows up?

Pick for example this file here: https://github.com/inkstitch/inkstitch/releases/download/dev-build-tyrosinase-update-dinomouse/inkstitch-tyrosinase-update-dinomouse-osx-arm64.pkg

Please note, that development versions are not notarized and need special treatment: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by staalplaat59** [comment]
ah sorry I downloaded the arm version for my machine has the M3 processor

I will downloade the new version of ink/stitch

**Comment by kaalleen** [comment]
Did it fix the problem?

**Comment by staalplaat59** [comment]
yes it did , 

sorry I thought I mentioned it

thank you
its a great program

is there a donate buton (I did not see any)

**Comment by kaalleen** [comment]
Ok, great. Thank you for the feedback :)
