### ISSUE TITLE
Inkstitch 3.1.0 on Ubuntu with latest Inkscape on Wayland crashes

### ISSUE THREAD

**Issue by reviczky** [inkstitch/inkstitch#3279]
Using the deb package from the release page (https://github.com/inkstitch/inkstitch/releases/tag/v3.1.0) the inkstitch extension shows up in the extension menu, however few of the options show a popup window and the preferences is not showing up at all.

![Screenshot From 2024-11-09 16-31-00](https://github.com/user-attachments/assets/504ce8f5-c11b-4454-bcca-39fe99c4583d)

All actions within the extension show console messages as well.
```
WARNING: unknown type: inkstitch:min_stitch_len_mm
WARNING: unknown type: inkstitch:collapse_len_mm
WARNING: unknown type: inkstitch:inkstitch_svg_version
```

![Screenshot From 2024-11-09 16-31-46](https://github.com/user-attachments/assets/f495d942-281a-467f-8d40-f4eac5c01949)

There is a crash report:
[inkstitch_crash.txt](https://github.com/user-attachments/files/17688616/inkstitch_crash.txt)

The machine is Ubuntu 24:10 with GNOME/Wayland and inkscape 1.4/1.5.

**Comment by kaalleen** [comment]
It's probably related to this: https://inkstitch.org/docs/install-linux/#some-inkstitch-dialogs-disappear-after-a-few-seconds-or-dont-show-up-at-all

**Comment by bkmgit** [comment]
Try using the .tar.xz file see:
- https://inkstitch.org/docs/install-linux/#installation
Start it from the terminal using:
```
export GDK_BACKEND=x11 && inkscape
```

The current build is done on Ubuntu 20.04, am happy to create a build on Ubuntu 24.04
for which the included libraries will likely support Wayland if you will test it.

**Comment by bkmgit** [comment]
The tar.xz file works on Fedora with Wayland.

**Comment by reviczky** [comment]
Thank you @bkmgit, I can confirm this works for me as well.

**Comment by bkmgit** [comment]
Welcome. Thanks for the feedback.
