### ISSUE TITLE
cannot write a .pes file

### ISSUE THREAD

**Issue by piscvau** [inkstitch/inkstitch#328]
I am on Xubuntu 18.04
When I do embroider 
I get the following error message:
Error writing to home/odile/Documents/travaux manuels/fleurs embroidery.pes:

**Comment by lexelby** [comment]
Ugh, it doesn't show an actual error description?  Sorry about that, I'll get that fixed.

It might be that the path doesn't exist or you don't have write access.

Another way to save PES files is to do File->Save Copy As and choose the ink/stitch PES format.  Does that work?
