### ISSUE TITLE
a bug in Ink/Stitch while running trouble shoot AND 

### ISSUE THREAD

**Issue by staalplaat59** [inkstitch/inkstitch#3283]
I have Ink/Stitch  for arm
-----------------------troubleshoot Objects-------------
![Uploading ostkurve tekst satin done 10x10.svg…]()

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/troubleshoot.py", line 34, in effect

----------------------stitch plan preview ---------------------------------------

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 603, in embroider
  File "lib/elements/element.py", line 680, in validate

**Comment by staalplaat59** [comment]
I think it’s a problem with the file , I can not save it to a other format, the original file had the measurements of about 30 x30 cm and then I had no problem. I reduced it to a 20 x 20 cm (that I can stitch) and a 10 x 10 (that I can test) svg file and then they both can not be saved to a stitch file (pes) and can not troobleshoot or do a stitch plan preview. (hope this helps)

**Comment by staalplaat59** [comment]
sorry I did not install last version, now I have "Ink/Stitsch Version: update-dinomouse (osx) 2024-11-06 17:45" and all problems are gone!

**Comment by kaalleen** [comment]
Thank you for the feedback.
