### ISSUE TITLE
Applying Palette: 'NoneType' object has no attribute 'nearest_color'

### ISSUE THREAD

**Issue by jonaskn** [inkstitch/inkstitch#3285]
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:	macOS
ProductVersion:	11.7.10
BuildVersion:	20G1427
CPU:				x86_64

Ink/Stitch Version: 3.1.0-high-sierra-catalina (osx) 2024-07-27 00:44

Traceback (most recent call last):
  File "inkstitch.py", line 162, in <module>
  File "inkex/base.py", line 252, in run
  File "lib/extensions/apply_palette.py", line 42, in effect
AttributeError: 'NoneType' object has no attribute 'nearest_color'

I am new to this. I already tried setting a  color through the color palette shown at the bottom of the inkscape window for each object.

**Comment by kaalleen** [comment]
Seems like this is a bug in the current Ink/Stitch version when you did not install the thread palettes. So installing them should fix the issue... (after an Inkscape restart).

https://inkstitch.org/docs/thread-color/#install-thread-color-palettes-for-inkscape

**Comment by jonaskn** [comment]
🙏
