### ISSUE TITLE
Removing commands only removes some commands

### ISSUE THREAD

**Issue by gusvisser** [inkstitch/inkstitch#3286]
![3 birds](https://github.com/user-attachments/assets/a608859d-6431-40a1-9abb-59f29dbf43b2)
I did receive a file from a friend and it has a lot of unneeded commands and it needed reorganizing so i wanted to remove all the start and stop commands but no matter what option i selected in the remove embroidery elements commands it only removed a part of them the rest i had to mannually select and remove

I dont know if it is a bug or something i did wrong

![image](https://github.com/user-attachments/assets/d3fb1597-83e1-4193-926e-31d3c91c9412)
and running windows 10

Gus Visser

**Comment by kaalleen** [comment]
Works for me. Which ones did you have to manually remove?

**Comment by gusvisser** [comment]
I did some checking yet and found that when nothing was selected i was able to remove all commands i wanted
as soon i have the layer selected it was only removing a few 
then tried to select different groups where they were located but no luck for auto removal only manually

Thanks 
Gus Visser
