### ISSUE TITLE
Crash when exporting

### ISSUE THREAD

**Issue by KungPhoo** [inkstitch/inkstitch#3290]
The following file crashes when I try to export an PES file. It said, I should create an issue, which do I here.
![Oma](https://github.com/user-attachments/assets/fe13c319-a795-4877-9d6f-b8d770d34bf7)

Best regards.

**Comment by LochanLoch** [comment]
Don't created with Inkscape is the first I saw. ...

**Comment by tyrosinase** [comment]
Upgrading to a current version of Ink/Stitch should fix the crash, but you'll also need to do a lot of work on the design before it's ready to export to a usable PES: by default everything is a fill and you'll need to convert it to almost all satin.

**Comment by kaalleen** [comment]
Closing since grandma seems not to be crashing with current versions. Please protest if I am wrong.
