### ISSUE TITLE
Error in circular fill

### ISSUE THREAD

**Issue by padcrafting** [inkstitch/inkstitch#3292]
I encountered a reproducible error when using a circular fill method in InkStitch. I am attaching the SVG. 
This is the error; it is triggered by deselecting Underpath. 

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		15.1
BuildVersion:		24B83
CPU:				arm64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:50

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 954, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1186, in do_circular_fill
  File "lib/stitches/circular_fill.py", line 97, in circular_fill
  File "lib/stitches/circular_fill.py", line 163, in path_to_stitches
TypeError: 'NoneType' object is not iterable

![drop_inkstitch_bug](https://github.com/user-attachments/assets/869614a5-5306-4679-baee-fb249b70a5d4)

**Comment by tyrosinase** [comment]
That is hopefully fixed by #3141 , though I think that's only in development versions right now. If you grab one of @kaalleen 's recent ones from https://github.com/inkstitch/inkstitch/releases you can see if that fixes it (and kaalleen may have a more specific recommendation for the most stable release).

**Comment by kaalleen** [comment]
Oh right, I forgot about the underpathing issue when start and stop isn't at the same outline. It might be responsable for more of the recently reported error messages.

As tyrosinase said, you can use a recent dev build (any of them should be fine at the moment) or you make sure it starts at the inside of the hole with a start command.

**Comment by kaalleen** [comment]
![Bildschirmfoto vom 2024-11-20 07-04-19](https://github.com/user-attachments/assets/bf56cc9b-3992-4eee-a7d8-e46e1ec56f98)

Like so. Color changed to make command visible.
