### ISSUE TITLE
PES or PEC file not shown on Innovis VM5100, DST shows "Too big for large embroidery"

### ISSUE THREAD

**Issue by Coo1dude** [inkstitch/inkstitch#3325]
Hello there!
As the title suggests, I've tried all three file formats (Which manufacturer lists) and the only one that even shows up on the USB is the DST file. When trying to open the DST file, it shows an error "The pattern is too large for the extra large embroidery frame." although in Inkscape I have my object set to 40 mm at its widest point, and the extra large embroidery frame is about 7x12 in. 

I found that the error of the files may be due to the pattern "being too large" but I am not quite sure how to scale my object down, or if I do scale it to an extremely small size, if the quality of it will be reduced.

Any help is appreciated,
Thank you!

**Comment by Coo1dude** [comment]
Upon closing the file, reopening just the plan SVG that my object is on, and scaling that appropriately it seems to have fixed my problems. I think that the document size (Which was the hoop template from Ink/Stitch) was a problem, even after resizing it. Putting it on a blank slate seemed to help.

**Comment by tyrosinase** [comment]
The document size doesn't matter (unless that changed when I wasn't looking), but if there was a stray object out in the wilderness off-page that might have triggered it. Copying the design to a fresh document might have left the extraneous bit behind.

`Zoom Drawing (4)` will generally turn those up, when the zoom doesn't zoom to where you expect it would. Or opening the PES in Inkscape directly, where it'll size the Inkscape page to the existing stitches.
