### ISSUE TITLE
Unable to Bring Up Parms Dialog for Text

### ISSUE THREAD

**Issue by mskressin** [inkstitch/inkstitch#333]
I created a design using just text. I converted the text to a Path. When I select the Embroider option it works fine. But if I try and bring up the Parms dialog, I get the following error "No embroiderable paths found in document.
Tip: use Path -> Object to Path to convert non-paths"

OS is Mac and I am using the latest version.

Attached is the file I am having trouble with:
[petethecatobj.svg.zip](https://github.com/inkstitch/inkstitch/files/2452510/petethecatobj.svg.zip)

**Comment by lexelby** [comment]
Awesome, you found a bug!  Thanks for bringing this to my attention.  I'll get a fix out in an upcoming release, but for now, there's a workaround.  Select all of the objects, then go into "Stroke and Fill" and explicitly set the fill to black.  That should make Params work properly.

**Comment by kaalleen** [comment]
This should be solved by now. For me everything renders fine, except for the last "e" in Pete, which is an image and cannot be handled by Ink/Stitch. So I am closing the issue. Please reopen if needed.
