### ISSUE TITLE
Guided fill hiccup

### ISSUE THREAD

**Issue by njlvr** [inkstitch/inkstitch#3335]
Hi people
I love the guided fill feature but there is one thing I can't seem to straighten out.
As the screen copy shows, in the upper corner there is come hiccup.
It does that on my embroidery machine and it even does that in the Realistic Preview (Which is great !)
But what Can I do to smoothen it out?
Adjusting my Guide Line helps but not always. I don"t know how to move it.
Trial and error is the only technique I know

Any ideas? Thanks
![shawl](https://github.com/user-attachments/assets/209230fa-6428-4b8e-93f7-f14a15976fbe)
![shawl](https://github.com/user-attachments/assets/b3da3b23-0afe-400a-9d50-3579155aa5c4)

**Comment by Marif91** [comment]
La ligne guide doit très largement dépasser au-delà de la forme à guider, sinon on repasse en remplissage automatique...

**Comment by njlvr** [comment]
En effet @Marif91. Ca marche comme une merveille. Merci!
