### ISSUE TITLE
38c3, any contributors going?

### ISSUE THREAD

**Issue by einsweniger** [inkstitch/inkstitch#3339]
I’d be interested in hacking on inkstitch with some of you, any one of you going to be at 38c3?

**Comment by kaalleen** [comment]
Oh, I'd love to go. But I don't see a chance to get off of work during the christmas holidays (ever). But I will enjoy watching some of the streams.

**Comment by kaalleen** [comment]
We are having an Ink/Stitch meeting in Essen on May 17th 2025. If you are interested in coming. It's more like a user meeting, less about development. But I guess there is some time left over after the meeting for a deep dive.

https://inkstitch.org/de/2024-10-08-Usertreffen

**Comment by einsweniger** [comment]
I'll see if I can come, have some nice few days!

PS: I made a valcro backed patch, turned out quite nice, except for the small font :D
![image](https://github.com/user-attachments/assets/3a4928d4-1584-4589-8de2-589d838a899e)

**Comment by kaalleen** [comment]
Enjoy the congress :)
