### ISSUE TITLE
UNEXPECTED ERROR

### ISSUE THREAD

**Issue by galimara** [inkstitch/inkstitch#3360]
Good evening

sorry for my english.
I'm having an error with inkstich, find the entire message below.

The error comes out when I try to remove "underpath", but only on 2 levels of the drawing (name level: "NERO DX" and "BIANCO DX")

![MOUNTAIN DONKEYS DEFINITIVO](https://github.com/user-attachments/assets/f88ed2ed-490f-4aaf-9714-222aa1bc3b6e)

Furthermore, it is impossible to export the file in .pes format as it still gives an error.

what can I do?

thank you very much and have a good evening

Mara

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
CPU:				x86_64

Ink/Stitch Version: v3.1.0 (osx) 2024-07-27 08:52

Traceback (most recent call last):
  File "lib/elements/element.py", line 641, in handle_unexpected_exceptions
  File "lib/elements/element.py", line 605, in embroider
  File "lib/elements/fill_stitch.py", line 961, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 1044, in do_auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 116, in auto_fill
  File "lib/debug/debug.py", line 166, in decorated
  File "lib/stitches/auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable

**Comment by tyrosinase** [comment]
This is fixed by #3141 in development and future releases. You should be able to install one of those to fix the problem (https://silverseams.com/2024/04/installing-pre-releases.html has some screen shots of how that works).

Or you can work around it in the existing release: if you break up non-contiguous shapes like this:

![image](https://github.com/user-attachments/assets/8f480c42-d61f-42ca-90f1-a1109adf94ff)

you are less likely to run into the bug.

I'm going to close the issue as a duplicate, but that doesn't turn off conversation - if you have trouble working around the issue or if you need help installing a development release, just ask.

**Comment by galimara** [comment]
thanks so much for the reply!

I looked at the solutions but unfortunately I can't understand anything.
(I'm not an IT expert and I don't speak English well).
I only know that I downloaded and installed version 3.1.0.

Can you tell me where and what I need to download?

Thank you so much and have a good evening

Il giorno sab 21 dic 2024 alle ore 19:22 Tyrosinase <
***@***.***> ha scritto:

**Comment by tyrosinase** [comment]
If you go to https://github.com/inkstitch/inkstitch/releases you will see a whole lot of test releases. It's sometimes a challenge to decide which one to pick, but you can usually go with kaalleen's most recent one, which is right at the top now.

![image](https://github.com/user-attachments/assets/d655b247-ec09-48e5-bccc-05612a398c52)

I checked Compare to 3.1.0 to make sure 3141 is among the things added in, and it is. Download the one appropriate for your machine (I am not a Mac person so I'm not sure there) and then you should be able to follow the instructions on https://inkstitch.org/docs/install-macos/ just like the original installation. If that gives you trouble, one of the Mac experts can probably step in and give you better instructions.

**Comment by galimara** [comment]
Ok, i’ll try now.
Many many thanks!!!




Il giorno sab 21 dic 2024 alle 22:27 Tyrosinase ***@***.***>
ha scritto:
