### ISSUE TITLE
Print PDF "Concern"?

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#337]
Now, I'm running the latest dev version for the auto route satin columns, but I don't know if it started before that PR or not.  So I don't know if it's related to that PR.

I'm working on some Xmas full embroidered ornament designs and I'm leaving notes of certain areas to where if they want a different color horse, alpaca, or reindeer to swap out the thread colors.

I noticed in some of the note boxes, if I make changes and I "re print" the pdf, sometimes I'll get (what I'm assuming to be html code) "span" and then other words, including the actual note itself.  I just delete what I don't want, but I'm thinking that since it doesn't affect all of the note boxes, it's something that shouldn't be there.

Anyone else notice this or am I just totally off my rocker?

**Comment by lexelby** [comment]
I haven't noticed this, but you're probably not off your rocker.  Could you post a screenshot?

**Comment by wwderw** [comment]
@kaalleen latest PR seemed to have done the trick.
