### ISSUE TITLE
exception when opening PHC files

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#345]
Moved here from: https://github.com/inkstitch/pyembroidery/issues/68

Pyembroidery supports PHC files, but Ink/Stitch chokes on them.  It assumes colors are defined, but the test file in the issue above seems to result in pyembroidery returning colors as None.

Ink/Stitch should properly handle colors that are None, perhaps by generating random colors.

```
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    extension.affect(args=remaining_args)
  File "/home/lex/repos/inkstitch/lib/extensions/input.py", line 32, in affect
    render_stitch_plan(svg, stitch_plan)
  File "/home/lex/repos/inkstitch/lib/svg/svg.py", line 111, in render_stitch_plan
    group.extend(color_block_to_paths(color_block, svg))
  File "/home/lex/repos/inkstitch/lib/svg/svg.py", line 69, in color_block_to_paths
    color = color_block.color.visible_on_white.to_hex_str()
AttributeError: 'NoneType' object has no attribute 'visible_on_white'
```

**Comment by lexelby** [comment]
@mgua You might be able to work around this by using the `pyembroidery-convert.py` script included with pyembroidery to convert the file to another format like DST.

**Comment by mgua** [comment]
Thank you very much. 
I see that the pyembroidery code has been fixed following first super-fast debug by tatarize.

I really appreciate. Thank you to all for your great job and committment.

Marco

**Comment by lexelby** [comment]
Oh, okay.  Maybe I was wrong a it is a pyembroidery bug after all.  I'll merge in his changes when I get a chance.
