### ISSUE TITLE
Ability to add in user details in footer of print out.

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#346]
I have a modified footer for the print-pdf to not only link to the project's site, but to also give the customer the ability to easily contact me through various venues.

Problem is, Cups and "Print to File" do not maintain links after "printing", so I'm curious for those on a Linux system what do you use (or what settings did you change for those 2 aforementioned programs) to keep the links active after "printing"?

**Comment by kaalleen** [comment]
If I am right, this is actually not a linux or cups matter, but depends on the browser you are using. Seems like you are using Firefox. You could use an addon for pdf printing that allows links to be preserved or use an other browser.

Do you think it would make sense to add a custom field to the footer template for personal information (like links to the designers website)?

**Comment by wwderw** [comment]
> You could use an addon for pdf printing that allows links to be preserved

That's a bummer that it can't be an option that's within FF itself.  I'm not fond of the addons (that seem worth their salt) for this purpose, as they usually need to have a ridiculously amount of permissions granted to them and/or they send the pdf to some online service to do the actual conversion.

Wonder if I can see about saving it as an html file, that would just open up in the browser and links should be preserved there.

>Do you think it would make sense to add a custom field to the footer template for personal information (like links to the designers website)?

I think so.

As to if it's manually inputted and then saved using the print extension function or if maybe it's pulled from the Metadata section of the SVG, depends on what would be the easiest to implement.

**Comment by wwderw** [comment]
I got around to trying the Vivaldi browser that I have in my Windows VM to see if Vivaldi supported retaining links out of the box and it does.  So it's definitely due to the browser being used.  Since I don't have an active internet connection to the VM, I know it's not sending it to some 3rd party cloud service for the conversion.

I'll leave this issue open and rename and add a feature request for adding in the ability for the user to input their own details easily into the footer.   HTTP and mailto links etc.

I would also mention on the website though about certain browsers when wanting to keep links when "printing to PDF" and try to suggest some browsers that will retain when "printing" and to mention those that don't etc (in a way that doesn't show preferential support to one or the other).

**Comment by lexelby** [comment]
Ah, wonderful!

Vivaldi is just Chrome under the hood.  My understanding is that Firefox won't save links in PDFs but Chrome and Safari will.

What kind of interface would you want for the custom footer?  Is it enough for Ink/Stitch to look for an HTML file in the config directory (~/.config/inkstitch)?  Or do you need a rich-text editing UI in the browser?

**Comment by wwderw** [comment]
I would go for something that would make it the easiest for those that aren't savvy with HTML code at all.

I was able to just edit the footer.html to get what I needed, so that wasn't a big deal for me (even though my knowledge of HTML is still in the '90s when we used Notepad to create web pages), but for others that may not be the case.

**Comment by lexelby** [comment]
@kaalleen is there some kind of easy jquery rich text editing plugin or something?

**Comment by wwderw** [comment]
> @wwderw yes, i know. It's hard to believe that Firefox can't do it out of the box.

For sure, it really needs to be done out of the box.  Now I can see extensions being used for other functionality, but I think retaining link should be one of those standard functions that is just expected.

>@wwderw Could you provide a list of information that you think should go additionally into the footer?

This is what I did on my custom footer:

![footer](https://user-images.githubusercontent.com/24878362/48139036-2a11fc80-e26b-11e8-8804-c17d3246ae76.png)

I think that should be the bare minimum:

Company Name (with the ability to enter a link (either for their site or for social media site if they don't have a main website)).

Email (and mailto link)

And may have at least one more link for a social media site (if they also have a main website).

Some may want to have a phone number (I prefer to directly everything via email, but others may also like to have a phone conversation or two as well).

Thoughts?

**Comment by kaalleen** [comment]
Seems like we actually need something like rich text ;)
I created a pull request. Could you run a test if it works for you?

**Comment by wwderw** [comment]
I haven't tested it out with a print pdf yet (have to go into the VM and use vivaldi for that) as I'm not able to test the links when setting everything up.

Not having gone to the actual print out, the only quirk that I have found was related to the "reset text" function.  I get this:

![reset quirk](https://user-images.githubusercontent.com/24878362/48314680-72465d00-e592-11e8-9ea7-4fa1f553c4c4.png)

Sometimes it'll change the footer to that read out (if it does do that, won't be able to make additional changes), sometimes it won't do anything on the footer (what it does most of the time), but in the settings dialogue it will still show this.

As far as the options not clearly showing up, I'm using a dark theme, so I'm sure that's where that is coming from.

**Comment by kaalleen** [comment]
Wow, you are fast ;) I noticed this problem with the translation markup not being used in jquery. Forgot I was not in the html part of the template. Should be "fixed" by now.

The option colors look terrible at your PC! Hm, not sure what to do about it. The color should be about black. I'll look into it tomorrow. Thanks for the hint.

**Comment by kaalleen** [comment]
@wwderw I could not reproduce your styling error, although I installed a dark theme. But I set colors explicitly to the button descriptions and hope this will make things better. Could you check if it looks better for you? If not I would be interested if this only happen to these buttons or all other buttons in the ui as well (like the save as default button, etc.).

**Comment by wwderw** [comment]
Wow, that made all the difference in the world.

I appreciate that.

My original intent wasn't actually to have you go through all that effort, it was more of let you know, so you didn't think the latest PR caused this issue.

Although my eyes really appreciate you doing this.  Thanks!

**Comment by lexelby** [comment]
I haven't had a chance to look at this yet, but feel free to merge once anyone clicks approve.
