### ISSUE TITLE
Multicolor

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#349]
Is it possible to great a file so the machine stops and then you can change the color?

**Comment by lexelby** [comment]
Hi @ARKopp, welcome to Ink/Stitch!  @wwderw's comments may have resolved your question, but just in case, I thought I'd chime in too.

Ink/Stitch processes the objects in your SVG in the order that they're stacked, from bottom to top.  That is, if you draw a fill object, then a satin, then a running stitch, then the embroidery design file (e.g. DST) will first sew the fill, then the satin, then the running stitch.

Ink/Stitch will pay attention to the colors you make the objects.  If that fill is red and the satin is green, then Ink/Stitch will automatically insert a color-change instruction in the embroidery design file.  In other words, just set objects to the colors you want them, and Ink/Stitch will take care of the rest.

Ink/Stitch also comes with an extensive collection of thread manufacturer color palettes.  You can install these palettes into Inkscape by running the `Install add-ons for Inkscape` extension.  Then you can assign objects colors from one of the thread palettes.  If you then use Ink/Stitch's "Print" extension, it will notice the palette you used and name the colors according to the manufacturer's thread names.

I hope that helps, and please let us know if you have any more questions.

**Comment by wwderw** [comment]
To answer your questions, yes you do the stop commands first then you either use embroider in the extension or you can use the "save as a copy" and find the stitch file that you are wanting from there (or export a bunch of versions contained in a single zip file).

Can you go into detail of your situation though?  Stop commands may or may not be necessary, depending on the machine that you are using, they may not even be read even if the machine in question can read DST files.  It may just be ignored by the machine.

What machine are you using and what are you trying to accomplish with multi-colors?  In general, just doing different top stitch colors shouldn't need a stop command, doesn't matter if it's a single needle or multi-needle.  I just want to make sure that's the best solution.

**Comment by wwderw** [comment]
Stop commands will more then likely be ignored by that machine.

There is sample digitized files, including the logo, that are among the files of the extension.  Export one of those as a DST or PES and load it in the machine and see how it handles.

You should just be able to digitize as normal, no stop commands.  When the machine reads a color change, it already interprets that as a stop command on single needle machines.

**Comment by wwderw** [comment]
Are you running it on a Mac?  That might be an issue with the Mac build.  I'll leave that to the smarter coder devs to determine.

**Comment by ARKopp** [comment]
Yes the first error is on Mac. On windows there is a different error ... 
<img width="614" alt="screenshot 2018-11-21 21 00 39" src="https://user-images.githubusercontent.com/4289157/48867156-8e899b80-edd5-11e8-9f95-e3f04b5f8cec.png">

**Comment by ARKopp** [comment]
it worked grate with the digitized version from the inkscape logo but I have no idea how to create a file like this and why it is like this .... 
<img width="614" alt="screenshot 2018-11-21 21 00 39" src="https://user-images.githubusercontent.com/4289157/48867580-de1c9700-edd6-11e8-868d-19d5e1b95bcc.png">

**Comment by wwderw** [comment]
This one is a little bit older as far as what exactly to do now.  Mainly with how one does a run stitch (want to use a segmented stroke, when I did this video originally it could be done either way).

This would give you an idea of how to digitize a design using Ink/Stitch.

[Tutorial](https://www.youtube.com/watch?v=FsbD8mnSAO4&list=PLMNtO24YQeCzjclRoMFO-fZFu4TrZUKs3&index=3)

**Comment by wwderw** [comment]
Personally, having digitized since I started working for my mom when I was 14 (quite a bit ago) and now a freelance digitizer, I firmly believe that it's best to digitize manually.  

The key thing is knowing what you are doing (and that comes with experience and trial and error and following designs that were digitized correctly while learning etc).

Because of that, I am biased towards manually digitizing and even the several thousand dollar digitizing programs that have made some advancements with auto conversion, the best method is still using the manual/semi manual tools that I've been using for more then a couple of decades.
