### ISSUE TITLE
Params issue?

### ISSUE THREAD

**Issue by HoneyPhantomhive** [inkstitch/inkstitch#350]
I'm so sorry if this is a dumb question--I'm totally new to Inkscape and Inkstitch.... as well as machine embroidery, for that matter :,) I was trying to use the 'params' command on a shape I'd imported from Illustrator as a DXF in an attempt to use a fill stitch (as shown in [this ](https://www.youtube.com/watch?v=hDm9OOTpAUA&index=6&list=PLMNtO24YQeCzjclRoMFO-fZFu4TrZUKs3)video), but it gave me this error message: 

**Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path4778', '--extension=params', 'C:\\Users\\Kristen\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgHPR4RZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 321, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 571, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified**

What can I do?

**Comment by wwderw** [comment]
It may not be related, but in my experience with exporting AutoCad files from Ai has been hit or miss.  Line segments everywhere.  It would usually take a few tries before my Statler Stitcher would read a DXF file correctly from Ai. 

I would try to save it out of Ai as an SVG file or an EPS file and so if those work and retain vector info.  If not, then I would recreate in Inkscape and apply Params to that.

**Comment by HoneyPhantomhive** [comment]
> It may not be related, but in my experience with exporting AutoCad files from Ai has been hit or miss. Line segments everywhere. It would usually take a few tries before my Statler Stitcher would read a DXF file correctly from Ai.
> 
> I would try to save it out of Ai as an SVG file or an EPS file and so if those work and retain vector info. If not, then I would recreate in Inkscape and apply Params to that.

I just recreated it in Inkscape (which took forever to figure out haha) but I still got this:

Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path825-4-9-3', '--extension=params', 'C:\\Users\\Kristen\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgTS51SZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 321, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 571, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by lexelby** [comment]
Hi @HoneyPhantomhive, thanks for trying out Ink/Stitch!  I'm sorry it hasn't yet worked for you.

Usually this error indicates some kind of problem with installing the extension.  It can especially happen if the folders in the ZIP archive are not extracted as is.  You should have an "inkstitch" directory under your extensions directory with all of Ink/Stitch's internal libraries underneath it in various directories.

Your extensions directory should just have a bunch of `inkstitch*.inx*` files and `inkstitch.py`.  If you have `inkstitch.exe` directly in your extensions directory, then something went wrong.

Maybe try deleting the Ink/Stitch files and reinstalling?  Hopefully we can get you up and running as soon as possible.

**Comment by HoneyPhantomhive** [comment]
@lexelby I deleted Inkstitch and just want to make sure I'm doing this right. I extract the files and then drag ALL of these to the extensions folder of Inkscape?

![image](https://user-images.githubusercontent.com/45114379/48684862-4cfcb480-eb79-11e8-92cf-39c2283013c4.png)

**Comment by lexelby** [comment]
Ah, I see the problem.  Grab the "win32" zip from here instead:

https://github.com/inkstitch/inkstitch/releases/tag/v1.20.0

Extract the contents of that into your extensions directory, restart inkscape, and that should do the job.  If you still get stuck, just let me know :)

**Comment by HoneyPhantomhive** [comment]
@lexelby THANK YOU SO MUCH!!! That fixed it!! Thank you!!

**Comment by lexelby** [comment]
Yay! Have fun!
