### ISSUE TITLE
Unexpected error launching Ink/Stitch.

### ISSUE THREAD

**Issue by srinath314** [inkstitch/inkstitch#359]
Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path10-5', '--id=path10', '--collapse_len_mm=3', '--hide_layers=true', '--output_format=txt', '--path=C:\\Users\\Srinath\\Dropbox\\BOOKS', '--extension=embroider', 'C:\\Users\\Srinath\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg41KWSZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 321, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 571, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by Paul-Kummer** [comment]
I'm getting a similar error on linux. I've tried deleting everything and reinstalling it, but maybe I'm missing something.

I found this thread on stack exchange, but haven't tried anything yet.
https://stackoverflow.com/questions/26807937/subprocess-popen-oserror-errno-8-exec-format-error-in-python

Tried to launch: inkstitch/bin/inkstitch
Arguments: ['inkstitch/bin/inkstitch', '--extension=install', '/tmp/ink_ext_XXXXXX.svg2EOETZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by lexelby** [comment]
Hi @Paul-Kummer!

Ah, that's a separate issue.  Your problem is likely caused by trying to run a 64-bit executable (inkstitch) on a 32-bit operating system.  It's possible to run a 32-bit program on a 64-bit operating system, but not vice versa.

I'm sorry you're having trouble.  We tried to build a 32-bit version of Ink/Stitch earlier this year, but we eventually stopped due to lack of development time and demand.

**Comment by Paul-Kummer** [comment]
You are correct, I am running in 32-bit. Thanks.

**Comment by amw4444** [comment]
Windows 10 64 bit Inkscape version .92

First I apologize I do not have the error and now that it’s fixed I don’t want to try and re-create it. It was an error on launch after clicking params. Last night when researching it I did find an entry but cannot find it now and unfortunately I’m too busy to go much farther I apologize.

I removed all Inkstitch instances this morning and set out to download the zip file I got to the “Opening inkstitch-v1.26.2-win32-en_US.ZIP“  dialog box where you can choose to “Open with” or “Save file“ I thought I wonder if this is the problem. Previously I had chosen “Open with” in all of my troubleshooting. Today I chose “Save file“ and proceeded with install and testing and this time it worked. I am a novice so I do not know if this had anything to do with it but I thought I would share it. If I can find the original error in my history file I will share it here. I have not gone much further than this so cannot verify if there won’t be other issues. I hope this is helpful to someone.
