### ISSUE TITLE
Params doesn't properly handle default black fill

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#362]
I am getting an error when clicking on Parameter only when the object is black. When I fill it with another color I get an error. 
<img width="601" alt="screenshot 2018-12-08 19 56 31" src="https://user-images.githubusercontent.com/4289157/49689688-00c3e500-fb25-11e8-9ec8-2f3af14c624c.png">

**Comment by lexelby** [comment]
That looks like a bug to me.  Would you mind posting that SVG here so that I can take a look on my end?

**Comment by ARKopp** [comment]
[buga.svg.zip](https://github.com/inkstitch/inkstitch/files/2660075/buga.svg.zip)
Here you go ....

**Comment by lexelby** [comment]
Oh interesting.  I wasn't able to create such a path, so I just assumed.  In any case, it's a bug and needs fixing :)

**Comment by ARKopp** [comment]
thanks for the fix
