### ISSUE TITLE
embroidery file import can produce paths with empty "d" attribute

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#363]
Getting this lately, importing .dst and export/params/simulate gives this error.
path6248: error: Object path6248 has an empty 'd' attribute.  Please delete this object from your document.

Might be something to do with original program?

**Comment by lexelby** [comment]
Ah, thanks!  It's a bug: the embroidery file importer shouldn't create empty paths.

**Comment by lexelby** [comment]
Any chance you could post an example DST that causes this problem?

**Comment by lexelby** [comment]
Perfect, thank you!  I see the error with those files and I've confirmed that #364 fixes it.
