### ISSUE TITLE
Getting Zig-Zag lines everytime starting prams

### ISSUE THREAD

**Issue by SchmetterlingK** [inkstitch/inkstitch#365]
Hi,

I just installed Inkscape and Ink stitch and I'm only getting Zig-Zag lines. If I do one line I get a Zig-Zag line. If I do two parallel lines I get two parallel Zig-Zag lines and it won't change if I go to the Satin Column tap. If I do a fill it says: "No embroiderable paths selected.Tip: use Path -> Object to Path to convert non-paths". And if I change parametes from default Prams is working and I get the following massage: "Legacy running stitch setting detected!"

I feel like I'm doing somethink wrong all over but I can't figure out what it is.

Thank you for your help. 
[Problem Ink Stitch.docx](https://github.com/inkstitch/inkstitch/files/2681648/Problem.Ink.Stitch.docx)

**Comment by SchmetterlingK** [comment]
Ok, now I figured out why the Satin Column and Fill Sticht didn't work. I didn't put the two lines together in one Objekt. But still the run stitch is a Zig-Zag stitch. Can you help me with that?

**Comment by lexelby** [comment]
Welcome, and thanks for trying out Ink/Stitch!  Perhaps the Params interface should try to give you a hint if you haven't combined the two lines into a single shape.  Sorry you got tripped up by that.

To get running stitch, draw a line and set it to dashed in the stroke settings panel.  Any dash setting will do the trick.

If a line is not dashed, it's a "simple satin", and you get a zig-zag that is the width of the line's stroke.

**Comment by SchmetterlingK** [comment]
Thank you for the help. 

I was watching the Wild West Designs Videos and there it was possible to have a line in running stitch. So I guess that changed.

**Comment by lexelby** [comment]
Yup, it changed a few months back.  Previously, any line with a stroke under 0.5 pixels was running stitch.  It was super confusing especially if you specified a stroke width in millimeters, because it would first convert it to pixels internally before comparing to 0.5 (96 pixels per inch).  I got rid of that and switched it over to dashed lines only.  Sorry for the confusion!

Have you seen our extensive tutorials on inkstitch.org?
