### ISSUE TITLE
Wil this machine work 

### ISSUE THREAD

**Issue by Matej1006** [inkstitch/inkstitch#367]
will this machine work 
![20181222_130118](https://user-images.githubusercontent.com/39615014/50374233-44215780-05eb-11e9-920c-16d4f2a6da03.jpg)

greatings Matej

**Comment by jameskolme** [comment]
Yes, looks like simple straight stitch machine. If possible, it is good thing to do some test runs, so machine is at least fully working.

**Comment by Matej1006** [comment]
yes it's works, it's from my grandmom, what kind of gear i must use for motorized this stitch machine i have NEMA23 and how is with endswitch for home comming?

Thanks and greatings Matej

**Comment by jameskolme** [comment]
Any synchronous method works, chain, timingbelt or maybe attach motor directly to main shaft.  Gearing what I have used most is 1:1. 
No home switch, otherwise homing would require to take out hoop every time. Presser foot don't rise that high without help.

**Comment by Matej1006** [comment]
what foot?

**Comment by jameskolme** [comment]
This foot, it keeps fabric down when needle comes up. 
![tikka tahti 1](https://user-images.githubusercontent.com/44113605/50377693-79996580-062a-11e9-85c9-38ea281d96fc.png)

**Comment by Matej1006** [comment]
foot can rise so that ring can fit under needle

**Comment by jameskolme** [comment]
Yes, but it is close call when fabric and stabilizer is included.

**Comment by jameskolme** [comment]
Christmas and happy new year.

If program is not running all motors are disabled, everything can be moved by hand.

**Comment by Matej1006** [comment]
Hello I watch yesterday a video on improve speed and can figured how to  acheved that

**Comment by jameskolme** [comment]
More speed can be obtained simply using less micro stepping on sewing machine stepper, this equals more power.

**Comment by Matej1006** [comment]
i was  now looking here in topic: G-code output format that you change motor from normal stepper to stepper with encoder. i have now nema23. if i make same change to stepper with encoder can i get out more stitch/min and what method are which two method you mean old and new

**Comment by jameskolme** [comment]
With encoder stepper, speed can be doubled and probably way more than that. This is huge leap to faster  stitching. 

Old type, goes like this: move,sew,move,sew,move,sew.....

New idea, goes like this: move and sew needle up motion,sew needle down motion,move and sew needle up motion,sew needle down motion,move and sew needle up motion,sew needle down motion...

So, sewing machine keeps moving continuously and movement is done when needle is out of fabric. This will allow much more stitching speeds. Sewing cycle is only half compared to old type and much more smooth to sewing machine and motor.  This method that makes most cense, unfortunately requires to make better suited pressing foot, I have done 2 of those with mixed results.

**Comment by Matej1006** [comment]
so this new type you steal testing any

**Comment by Matej1006** [comment]
will this gears work?

https://www.ebay.com/itm/25-Chain-Drive-Sprocket-9-40T-Bore-5-12mm-Pitch-1-4-6-35mm-For-04C-Chain/273358118364?ssPageName=STRK%3AMEBIDX%3AIT&var=572728033797&_trksid=p2057872.m2749.l2649

https://www.ebay.com/itm/25-Chain-Drive-Sprocket-9-40T-Bore-5-12mm-Pitch-1-4-6-35mm-For-04C-Chain/273358118364?ssPageName=STRK%3AMEBIDX%3AIT&var=572728033828&_trksid=p2057872.m2749.l2649

**Comment by jameskolme** [comment]
Probably yes, those will do. It would be much nicer if timing belt was used, something like 5M type. Ordering correct length belt is little bit guess work sometimes and chain is way easier on length. Search ebay using 5M timing belt key words.

**Comment by jameskolme** [comment]
You can order both same size, it will work. I had lower gear ratio, when I was testing and was not sure what happens.

**Comment by Matej1006** [comment]
yes but when i check if motor work i see that main motor were making 1.5 rotation instead of one rotation

**Comment by jameskolme** [comment]
That can be changed easily for different gearing on GRBL settings using $102 setting. Example if direct 1:1 gearing is used $102 setting should be (motorsteps * microstepping)/10 Assuming full motor revolution is used as 10mm
