### ISSUE TITLE
Print Out Issue

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#368]
![print out error](https://user-images.githubusercontent.com/24878362/50527218-93b0c900-0aac-11e9-8ab4-386c93cb66c0.png)
Any ideas on what would cause that to show up on the Approval sheet?

**Comment by wwderw** [comment]
Ok, it seems to be tied to using Metadeta info.  If it's all blank, everything works (it seemed to also affect the stitch plan views (not the realistic view)).

**Comment by lexelby** [comment]
What do you mean by metadata info?  The custom footer?

**Comment by wwderw** [comment]
No, the file metadata info.  Here:

![metadata](https://user-images.githubusercontent.com/24878362/50530755-68d36e80-0ac6-11e9-9c62-68272168fbe2.png)

**Comment by wwderw** [comment]
Yes.

It will put the text like shown, it will also keep the regular stitch rendering from showing up in the approval sheet (but tick realistic and it pops up) and in the thumbnails of the operator's view don't show up either (regardless if realistic is ticked or not).
