### ISSUE TITLE
Stitch plan not showing up

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#369]
What happened, I accidentally deleted stitch plan and now it newer shows up again.  I can export normally, but new document or restarting inkscape will not fix this, so I possibly brake something.

**Comment by lexelby** [comment]
Huh, even a new document doesn't fix it?  Do you get any kind of error message when you run Embroider?

Does Simulate work?

**Comment by jameskolme** [comment]
Simulate works and no errors, copying fresh copy of inkstitch did't work either. Reinstalling inskcape works,  so it possibly was just me. I have bad habit to brake programs just by using them. 

I was feeling like stitch plan was generated, but it just newer show anywhere.

**Comment by lexelby** [comment]
Darn, I guess now that you've reinstalled, you can't reproduce the problem?  If you ever see this happen again, I'd like to see the SVG if you'd be willing to post it.  I wonder if the stitch plan layer is there but just transparent or something.

**Comment by lexelby** [comment]
You can attach an svg if you zip it first.

**Comment by kaalleen** [comment]
Hm, no we are fine.
But this might be interesting for @danielkschneider

**Comment by lexelby** [comment]
Oh sorry!  I was mistaken and thought reigi was talking about our docs.

**Comment by kaalleen** [comment]
Hm, maybe we should think about changing the embroider function a little bit. Since we can save the stitch file through Inkscape directly, embroider could be renamed to "show stitch plan" or something like this. It might not be necessary to save a file every time you want to inspect the output?
But I might be mistaken and for special cases, the "embroider" extension still makes a lot of sense...

**Comment by wwderw** [comment]
> Since we can save the stitch file through Inkscape directly, embroider could be renamed to "show stitch plan" or something like this.

I like that idea.

I know now, since we are able to use the regular "save as (copy)....", I only have it spit out a CSV when I went to see the stitch plan.  Which I typically do when I do outlines as that makes everything easier to see when I'm able to just see the stitch plan.

**Comment by lexelby** [comment]
I've been thinking along those lines too.  If we did that I'd make it so you can save "debug" formats directly as well, like CSV.  

Now that we have such an awesome simulator (thanks @kaalleen!) I find that I almost never use Embroider.  I just run simulate a bunch with a hotkey.
