### ISSUE TITLE
Autoroute for Running Stitch

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#373]
Let's say we want e.g. this https://openclipart.org/detail/288569/floral-hearts-line-art image to be embroidered with running stitch. Just for fun I tested how it would look like:

![running-stitch-order](https://user-images.githubusercontent.com/36401965/50735867-88991f80-11b5-11e9-8ce0-36ec7e07049f.png)

It would be a hell of a job to get the stacking order right. Is there a possibility to achieve an autoroute routine just as the one we have for satin columns?

In combination with the [centerline trace plugin](https://github.com/fablabnbg/inkscape-centerline-trace) it would be a great tool to quickly achieve line art embroidery from images.

**Comment by lexelby** [comment]
I was just thinking along these lines the other day, actually.  At @wwderw's urging, I added support for running stitch in Auto-Route Satin before releasing it.  I'm not sure without looking at the code  but I _think_ there's nothing to stop you from running auto-route with _only_ running stitch objects.

What happens if you run center-line trace on that image and  set all the resulting lines to dashed, then run auto-route on it?  It might just work.  With such a big image, it might take an hour or two to run though...

**Comment by lexelby** [comment]
On second thought, no it won't work.  The running stitch support in auto-route satin is intended for travel between satins.  It won't break up a running stitch in the middle in order to connect to another one.

I'll think on this a bit.  It might be possible to adapt auto-route satin to fit this use case.  If not, it should be fairly easy to write an extension specifically to handle auto-routing huge numbers of running stitch objects like this.

**Comment by kaalleen** [comment]
That'd be nice! :)

**Comment by B-ellanna** [comment]
Just a note from me, I was just thinking about the same. It took me ages to properly route a line drawing, and this would be so awesome!

**Comment by LochanLoch** [comment]
"easy" test a star ... 107path and its possible to draw it in a single line but I found no auto importer to do it right ;-)
![AtomStern107TeileSVG](https://user-images.githubusercontent.com/66974900/100650173-ce2fda00-3343-11eb-8dd7-425c799319c0.png)

**Comment by B-ellanna** [comment]
Do you mean that it does not work to have it automatically with an easy method? I'm not sure about the meaning of your text?

**Comment by B-ellanna** [comment]
https://www.geeksforgeeks.org/python-program-for-dijkstras-shortest-path-algorithm-greedy-algo-7/ I have no idea if this helps but I thought I contribute this anyway. Maybe we can use it for this kind of work?

**Comment by lexelby** [comment]
Oh, certainly.  We already use dijkstra in the auto-route satin code.  I don't think there will be any new programming puzzles to solve for Auto-Route Running Stitch, someone just needs to write it.

**Comment by Tina-Chris** [comment]
https://github.com/Daekkyn/inkscapeOptimizePath A french user came across this path optimizer, could we integrate it in inkstitch?

**Comment by Tina-Chris** [comment]
![image](https://user-images.githubusercontent.com/64272979/172455448-8ed00f04-2c0b-483e-8ad6-636f23b883df.png)
Well I just tried the extension you programmed on your original image. It took like 5 minutes to calculate and it gives only 11 jump stitches. Its such a huge leap foward :)

**Comment by kaalleen** [comment]
Whoa nice. Thank you for sharing!

**Comment by lexelby** [comment]
I'm impressed it only took 5 minutes!

**Comment by sup-flues** [comment]
Autoroute for Running Stitch #373 is an extension that can be added to Inkstitch? How does one go about loading into Inckstitch ?

**Comment by Tina-Chris** [comment]
> Autoroute for Running Stitch #373 is an extension that can be added to Inkstitch? How does one go about loading into Inckstitch ?

You can install a development version. It's included there, then you can beta test the feature.

**Comment by tyrosinase** [comment]
Non-git-expert translation for "install a development version": go to Releases, in the right column of the main page, follow the link below the current release that will be like "+361 releases," and then try to guess which of the releases is the right one. Under Assets, it'll have the various flavors of downloads.

(I'm sure there's a way to actually tell which one includes which patch, but I've decided to reserve my limited technical cognition for other subjects than the extradimensional hydra that is git branching. Currently trying to stumble through Google-translated Chinese sites to build a mass storage gadget image for that knockoff Pi Zero.)

**Comment by sup-flues** [comment]
Thanks Tina-Chris and tyrosinase. You say that I can install a development version and that there is a "Releases" link somewhere. I could not find either. I see the extension script for the Autoroute Running Stitch but don't know how I would install that since the Inkstitch extension is not in the Inkscape extensions directory where all of the other extensions are located, nut instead is installed in the user directory and does not look to have a sub-extension directory under the main Inkstich application. Any direction as to how to install the development version and where to find it would be most appreciated.

**Comment by kaalleen** [comment]
Try this one here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fixes_for_220

This is a test release for the upcoming version.
It is still in active development and we update it as soon as error reports come in. Any bug report is appreciated :)
Installation is pretty much the same as the official release. When you are a macOS user please note, that we did not notarize the development version. You can still install with a little trick: https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

**Comment by sup-flues** [comment]
Thanks kaalleen. My Mac is running 10.13 but looks like 10.15 is required. Will test on a newer Mac.
[24195] Error loading Python lib '/Users/skyle/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libpython3.8.dylib': dlopen: dlopen(/Users/skyle/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libpython3.8.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/skyle/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libpython3.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/skyle/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch/inkstitch.app/Contents/MacOS/libpython3.8.dylib

**Comment by kaalleen** [comment]
Oh sorry, yes you are right. In the dev-releases we do not support older macOS versions.

**Comment by sup-flues** [comment]
Tried it on a Mac OS 10.15 machine and got: "Ink/Stich is an Inkscape plugin. Please install and run Inkscape before installing Ink/Stitch." Then "The installation failed". I tried it using the DMG and Zip files. Running inscape 1.2. May have something to do with the way mac partitions volumes - OS and other.

**Comment by kaalleen** [comment]
Huh, that's not supposed to happen if you installed (and run!) inkscape before the Ink/Stitch installation.
Can you verify your extensions path? In the Inkscape preferences go to Sytem and post the path for the extensions here.

**Comment by sup-flues** [comment]
/Users/scottkyle/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch
/Applications/Inkscape 2.app/Contents/Resources/share/inkscape/extensions
/Applications/Inkscape 2.app/Contents/Resources/share
/Applications/Inkscape 2.app/Contents/Resources/share/inkscape

**Comment by sup-flues** [comment]
I did download the zipped extension as I said and just thought I would drag that over the current inkstitch extension and it works fine. So, this should work for now. Thank you all. Much appreciated!
