### ISSUE TITLE
QR code 

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#374]
I get access to embroidery machine with jump trim (wohoo!), so how to use it best way possible is something that I never would attempt to do on manual scissors. Inkscape can make QR code, that is nice, after ungrouping and combining blocks to shapes , image is way more simple. I was planning to do fill and add jumps manually. Unfortunately shapes are too complicated and results are:

path22980: error: shape is not valid.  This can happen if the border crosses over itself.
shapely.geos - INFO - Ring Self-intersection at or near point 432.77353080519987 400.28739158207992

I don't think there is any crossing over, just to complex shape. It works if nothing is combined together, but then results are many many many individual boxes and adding trims on correct places would make anybody mad. Any hints how to actually do this?

**Comment by lexelby** [comment]
Jealous!  I wish I had access to such a machine :)

You're going to love how easy this is.  Instead of fills, do each square as a satin.  Then select them all and do Auto-Route Satin Columns with trims enabled.  Ink/stitch will figure out the optimal stacking order and produce a stitch plan with a minimum of trims (so it doesn't take forever).

Let us know how it goes!

**Comment by lexelby** [comment]
Pretty much as you described, yeah.  We talked about QR codes a couple months back, and I made this one:

[inkstitch-qr-code-lex.zip](https://github.com/inkstitch/inkstitch/files/2731072/inkstitch-qr-code-lex.zip)

I made this one by creating a satin for one pixel, then copy/pasting it to over and over for each pixel of the QR code.  Then I set up a grid (you can see it in this SVG) and snapped the pixels to the grid squares to get them all lined up.

When I originally made this, auto-route satin didn't exist, so I laboriously organized the stitch path, one pixel at a time.  You can just select them all and run auto-route satin on them and it'll reorganize them and add trims as it sees fit.

Hope that helps :)

**Comment by jameskolme** [comment]
Ok, thanks for confirming, sometimes I get lost on things :) 

There is problem on stitching QR code, your excample or mine, trimming is not happening. First it looked like it works, but Janome machine makes auto trimming, if jump is more than 3-50mm (distance can be set). Setting this  distance over 20mm it newer trims anything or did it hmm, not enough anyway. This is too long program to pinpoint what is happening, so I made shorter program, only 3 lines, with manual trim points.  

First line ends, machine trims 2-3 times
Second line ends, jumps to third line, no trimming
Third line ends, trims again 2-3 times. 
[saksi.zip](https://github.com/inkstitch/inkstitch/files/2736753/saksi.zip)
[3 viivaa.zip](https://github.com/inkstitch/inkstitch/files/2736851/3.viivaa.zip)

I made similar program with autoroute satin and let's see what happens 
[3 satin autoroute.zip](https://github.com/inkstitch/inkstitch/files/2736860/3.satin.autoroute.zip)

Made 3 satins and after auto route, everything scales down and now there are 4 trim points. First layer shows what I was trying to do. 

Unfortunately I can't test this on machine, because it gives empty d error:
path64448: error: Object path64448 has an empty 'd' attribute.  Please delete this object from your document.

Last effort, setting trim manually on satin
[3 satin manual.zip](https://github.com/inkstitch/inkstitch/files/2736953/3.satin.manual.zip)
All goes well until I try to load program to machine, it says: file is damaged, do you want to delete it. Copied 3 times new file and it newer works. Every other program works on same memory stick. 

Well this went complicated fast, any ideas? I can do testing.

**Comment by lexelby** [comment]
Ah... this is where I run into difficulty since I don't have a machine that can do trims.  I just don't know how it really works.

Some machines like Janome and Brother have that feature you described, "trim jumps more than X distance".  The thing I don't understand is this: do they trim _any_ jump longer than X, or just ones with a TRIM code in the embroidery file?  Or both?  Maybe they always obey a TRIM code in the file.  Or maybe they only obey a TRIM code if the jump after it is more than X.

Thank for doing experiments!

**3 vivaa.svg**: Something isn't quite right with those trim symbols.  It looks like maybe you tried to set them up yourself using Inkscape's Symbols tool.  The problem is, Inkscape doesn't truly support attaching connectors to lines; it only wants to attach them to filled shapes.   If you look in the SVG, the connecting lines between the trim symbols and the lines aren't actually connected to your 3 lines.  The `inksacpe:connection-end` attribute isn't set.

Try selecting the lines and do **Ink/Stitch -> Commands -> Attach Commands to Selected Objects**.  That'll set up the trims properly.

**3 satin autoroute.svg**: Whoa, you found a bug!  Nice work!  I've opened #376 for this.  To avoid the bug, set your document units to pixels in File -> Document Properties before running Auto Route.

> Unfortunately I can't test this on machine, because it gives empty d error:
path64448: error: Object path64448 has an empty 'd' attribute. Please delete this object from your document.

Ah, another bug.  This one I knew about and have fixed as part of #364.  For now, hide the Stitch Plan layer before exporting a JEF file.

**3 satin manual.svg**: That one look to be constructed correctly.  No idea why the machine says it's corrupted.  Perhaps our file writing library doesn't encode TRIM commands in JEF files properly.  Can your machine accept any other format, like DST?

Sorry you keep running into trouble with this!

**Comment by jameskolme** [comment]
> do they trim any jump longer than X, or just ones with a TRIM code in the embroidery file? Or both? Maybe they always obey a TRIM code in the file. Or maybe they only obey a TRIM code if the jump after it is more than X.

Janome, there are 3 settings for trimming: off, auto and manual setup

Auto
Every jump over 3mm is automatically trimmed, machine makes this happen, not program.
Color change and program end is trimmed automatically too, not program.

Manual
Minimum jump distance without trimming off/3mm-50mm can be adjusted.
Trim at end of program or color change yes/no.
Read trim points from program yes/no.

I don't understand why trim points are not read from program on auto setting, that is default setting for trimming. 

>  3 viivaa.svg It looks like maybe you tried to set them up yourself using Inkscape's Symbols tool. 

Yes I did. New try and it works, well sort of. I did disable auto trim distance completely for testing. Using Janome .jef format, nothing were trimmed, clearly trim command is not going trough on this program. Janome supports .dst directly, this time everything did get trimmed perfectly and only onetime for same spot. 

3 satin manual.svg is also trimmed using symbols tool and directly exporting this to .dst, machine don't even show this file. .jef file machine wants to delete because of errors.

Doing same treatment as 3 viivaa.svg, this time using attach commands, .dst not showing and .jef error.
Deleting trims completely and still  .dst not showing and .jef error. Must be one ill embroidery file :)

But sure if I make new file, it should work, short answer to this is nope. 
[3 satins more.zip](https://github.com/inkstitch/inkstitch/files/2741870/3.satins.more.zip)
What is happening here? Only thing I can think is my memory stick is bad, nothing works does not compute. Original QR programs and everything else reads just fine. 

I must now find memory stick that is not lost or bend badly, hopefully it fixes something... maybe...

**Comment by jameskolme** [comment]
Testing more and all I can do is line and sating, using only one line method. But why did first ever tested QR code worked. USB memory is fine, I can copy and move files, formatted just to be safe side, no errors. 

I have noticed that G-code comes out every time perfectly, only file type I can see what's is going on :)

**Comment by lexelby** [comment]
Okay, I opened #377 for the JEF trim issue.  I'm at least glad one of the files worked as a DST...

> I have noticed that G-code comes out every time perfectly, only file type I can see what's is going on :)

Try setting the output format to CSV.  That'll show you every command that's going into the file.

Could you post one of your DSTs that the machine won't read?  I'll take a look and see if it's actually broken.

**Comment by jameskolme** [comment]
Trying to be clever, switch back to version 1.20.0 

First it did work and managed to make few simple shapes that work on machine ok. Sooner or later same behavior started again, now with different numbers. Trying to figure out what I do, when this starts to happen. Only difference is commands, newer used those before.  

```
> Traceback (most recent call last):
> 
>   File "inkstitch.py", line 52, in <module>
> 
>     if stdout:
> 
>   File "inkscape\share\extensions\inkex.py", line 283, in affect
> 
>   File "lib\extensions\embroider.py", line 80, in effect
> 
>   File "lib\extensions\base.py", line 200, in elements_to_patches
> 
>   File "lib\elements\element.py", line 268, in embroider
> 
>   File "lib\elements\stroke.py", line 183, in to_patches
> 
>   File "lib\elements\stroke.py", line 77, in paths
> 
>   File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
> 
>   File "lib\elements\element.py", line 208, in parse_path
> 
>   File "lib\elements\element.py", line 204, in path
> 
```
>   File "inkscape\share\extensions\cubicsuperpath.py", line 163, in parsePath
> 
>   File "inkscape\share\extensions\simplepath.py", line 118, in parsePath
> 
> Exception: Unexpected end of path

**Comment by jameskolme** [comment]
YES, attach command to selected objects, that's when all goes wrong. Never used any of these commands. Should I use those start/end positions?

**Comment by lexelby** [comment]
Thanks for poking at this so hard!  I've been really busy the past few days but hopefully I'll have time to look at this again soon.

**Comment by lexelby** [comment]
> -Trim command on last object makes these long error messages.

Wow, that's a really precise description, thanks!  I'm not able to reproduce the crash, though. :(  Can you post an SVG that causes that crash when you run Embroider?

**Comment by jameskolme** [comment]
This should be ready to go :)

There is 3 satin lines, probably not important. I added trims using attach command to selected objects, usually running embroider twice will cause error and this will happen on save as export as well. 

[equal satin.zip](https://github.com/inkstitch/inkstitch/files/2772469/equal.satin.zip)

**Comment by lexelby** [comment]
Thanks!  I'll check that when I get a chance.

Note that running Embroider twice may not do what you expect.  The first time you run Embroider, the stitch plan gets added to your SVG.  The second time you run Embroider, the stitch plan itself will be treated as part of the design!  Stitch plan paths are set as "manual stitch" in case you want to modify individual stitches.

**Comment by lexelby** [comment]
I'm about to test sew a QR code.  I find it perversely amusing that I'm able to scan the 400E's preview screen with my QR code scanner and it registers properly :D

**Comment by jameskolme** [comment]
Yes embroider is not meant to be used twice generally, I should said it clearer, running embroidery twice results same error than exporting using save as copy function.  Exporting to DST and JEF everything, seems to have some error discovery benefits.  

Is your QR code still working after embroidery? Mine was too small to recognize and no trims.

**Comment by jameskolme** [comment]
Autoroute trim function is not working correctly, so I was thinking what about autoroute and then attach trims, well maybe not :)
![snipsnip](https://user-images.githubusercontent.com/44113605/51438882-ab016180-1cba-11e9-848f-33e77d3005e6.png)

Maybe I could delete trims that are not needed, hmm, really like to test this.

**Comment by jameskolme** [comment]
This can be done completely using manual methods, only "few" simulations and direction swapping was needed, huh! 
![qrcode](https://user-images.githubusercontent.com/44113605/52180548-57c9fb80-27f0-11e9-9c4a-cfac5f988ab5.png)
Thread is actually white, now it is only matter of getting text to work and maybe do patch edges.

**Comment by lexelby** [comment]
![img_20190202_130841](https://user-images.githubusercontent.com/4446653/52182955-33125b80-27d1-11e9-8058-dd747ce15966.jpg)

**Comment by jameskolme** [comment]
Wow, so tiny and my phone reads it. Somehow I was sure it should be big, because there will be dimensional errors everywhere. Probably good contrast is most important thing for machine reading. 

Yes, autoroute ends up plenty of places to trim, good but not that good.  Doing it manually and using some running stitches makes things actually pretty fast. 

Is there anyway of showing what corner stitch starts and ends? I used simulate to show me every start/stop. There is definitely something to learn when doing it manually, takes some time to do, but machine time is far less. I really consider of making quick access keyboard buttons for this sort of thing, keyboard shortcuts  are not enough :)

**Comment by jameskolme** [comment]
So quick access buttons happened, if anyone is interested this USB keyboard, it is nothing more than arduino pro micro, 8 buttons and 8x 10Kohm resistors.  https://www.arduino.cc/en/Tutorial/KeyboardAndMouseControl 
![quick1](https://user-images.githubusercontent.com/44113605/52424885-8d7a2780-2b03-11e9-9a4f-2c72ca1ad722.png)
![quick2](https://user-images.githubusercontent.com/44113605/52424888-8fdc8180-2b03-11e9-9bed-f806551f2052.png)

**Comment by jameskolme** [comment]
It seems like I failed my QR code: 
https://www.qrcode-monkey.com/6-reasons-why-your-qr-code-is-not-working

Inverting colors is bad idea and maybe little bit more free space around is good idea. 
![bad_qr](https://user-images.githubusercontent.com/44113605/52971913-cf3b8580-33c1-11e9-9dcc-44ffc614e887.png)
Surprisingly few devices was able to read this, DOH!

**Comment by lexelby** [comment]
Aww, that's a shame.  It looks great!

**Comment by jameskolme** [comment]
Yes, doing it other way round works really well. It´s not ideal to stitch white background, but seems to work, if needed. Background alone takes 17000~ stitches, actual QR only few thousand :)

**Comment by jameskolme** [comment]
Doing background 90 degrees different to mace and end result is sharp like full HD. 
![qr_sharp](https://user-images.githubusercontent.com/44113605/53418489-9cf0e000-39e0-11e9-92be-867d8eca2de6.png)

Small hint, if someone else is doing QR codes manually and playing Inkstitch Tetris like I do. Using 4 premade pixels with known end corner, makes things pretty fast to do. Copy/paste suitable pixels and join stop to start with dot line if needed. 

![qr_idea](https://user-images.githubusercontent.com/44113605/53418667-f6f1a580-39e0-11e9-8758-a8730e27413f.png)

**Comment by lexelby** [comment]
Oooh, that is a seriously awesome result!
