### ISSUE TITLE
Color-Blending with Gradient Fills!

### ISSUE THREAD

**Issue by blackflyingcarpet** [inkstitch/inkstitch#375]
I was wondering if there is a way to do a fill with color-blending in inkstitch!?
Also i tried to find a way to fade the spacing between rows when selecting fill parameters!

**Comment by wwderw** [comment]
Sem-manual digitizing is the way that I would do it.  

Now, the question is, are you talking a true blend or a faux blend?  Depends on how much math you want involved in doing the blend.

**Comment by lexelby** [comment]
Hi blackflyingcarpet, welcome to Ink/Stitch!

Gradients are a feature I hope to have in the future but it's not quite ready yet.  Sorry to disappoint!

You can fake a blend using existing features, as @wwderw suggested.  In fact, he created an example: https://github.com/inkstitch/inkstitch/blob/master/images/examples/True%20Blend.svg

There's also a Faux Blend example in that directory that's a bit simpler and still gives a good result.

**Comment by lexelby** [comment]
There's also a hidden alpha-level feature that actually does fade the spacing between rows exactly as you said.  It may be a bit buggy, but I think it works for relatively simple fill shapes.  You can find a tutorial on using it here: https://github.com/inkstitch/inkstitch/issues/78#issuecomment-379561862

**Comment by blackflyingcarpet** [comment]
Thanks for the fast response.
I think i will give the hidden alpha-level feature a try.
If someone is intrested, i could post results!

**Comment by lexelby** [comment]
Please do!  I'd also like to hear about your experience and whether it does what you're expecting.

**Comment by blackflyingcarpet** [comment]
In the first place i might have to tell that i´m a absolute newbie to embroidery-programms.
Still i managed to enter the xml-code to the editor, was actually unexpeced easy!
Then i had some trouble finding out how to change the direction of the fade. I ended up turning the rectangle upsidedown after i applied: extensions>ink/stitch>embroider. This did the job for me.
I saved in pes. format and just gave it a try.


![img_0579](https://user-images.githubusercontent.com/46501164/50912904-7af0cd80-1433-11e9-9813-9286cbfbc60e.jpg)
![img_0581](https://user-images.githubusercontent.com/46501164/50912905-7b896400-1433-11e9-9e7e-5f7c291642fa.jpg)

**Comment by lexelby** [comment]
Nice work!

> i´m a absolute newbie to embroidery-programms.

Me too, and here I am writing one! ;)  Ink/Stitch is the first and only embroidery design program I've used.

**Comment by wwderw** [comment]
Speaking as someone that has a small fortune invested in digitizing software as a freelance digitizer, Ink/Stitch is able to hold it's own.  

Especially for those, like myself, that like using more of a manual/semi-manual  method of digitizing.

The biggest reason for that overwhelming expense is this is a very niche market that depends on software interacting with machines (and a variety of machines with different formats).  RIP programs are also quite expensive as well for pretty much the same reason.

I really only know of one commercial embroidery plugin though that would be akin to Ink/Stitch (goes for $3500~ for either DRAW or Ai).

It can definitely hold it's own.

**Comment by kaalleen** [comment]
Closing this in favor of #78
