### ISSUE TITLE
Add accents to embroidery fonts

### ISSUE THREAD

**Issue by FFY00** [inkstitch/inkstitch#385]
Hey, is it possible to add accents to the current fonts? I am interested in `, ´ and ^.

**Comment by lexelby** [comment]
Hi there!  Great idea, thanks.  There are already directional double-quote marks, so you may be able to just use those and delete one from each, as a temporary workaround.

**Comment by FFY00** [comment]
Yeah, thanks :grin:.

I have a non-related question which I don't know if is worth an new issue. How is your multithreading support? I have a simple patch with 13 letters and it has been a few hours since I started computing the output file. Is there any way to increase the thread count?

Thank you so much for all of your work! Without inkstitch, open source embroidery would not exist. If I can help with anything just let me know.

**Comment by lexelby** [comment]
> How is your multithreading support?

Nonexistent. :)  Ink/Stitch is completely single-threaded, for a variety of reasons.  Notably, Auto-Fill choses its starting point to be as close as possible to the last stitch in the previous object.

> I have a simple patch with 13 letters and it has been a few hours since I started computing the output file. Is there any way to increase the thread count?

Uh oh, that's not good!  I think this is more likely to be a bug than a simple performance problem.  Did it ever finish computing?  If you'd be willing to post the SVG here, I"d love to see if the same thing happens on my end.

> Thank you so much for all of your work! Without inkstitch open source embroidery would not exist. If I can help with anything just let me know.

I'm glad you like it, and thanks for the offer!  We're always looking for volunteers, and there's a lot to do.  If you're the technical writer sort, there's always more work to be done on the [Ink/Stitch website](https://inkstitch.org/).  See the [gh-pages branch](https://github.com/inkstitch/inkstitch/tree/gh-pages) for the source.

If you're interested in programming, I'm always looking for more help.  Even if you don't have time to contribute a pull request, reviewing mine would be very much appreciated.  And if you find areas of the code that are hard to understand as a newcomer, I definitely want to know so I can fix it.

If you speak another language, we're always looking for translation help.  See our [crowdin page](https://crowdin.com/project/inkstitch) to get started.

Even just reporting bugs and feature requests is very helpful.  The more folks that use Ink/Stitch, the more unique workflows we're exposed to and the more we learn about the user experience.

Thanks :)

**Comment by kaalleen** [comment]
Ther are a lot of fonts with accents now. Therefore I'll close this issue.
