### ISSUE TITLE
corrupted JEF and DST output with "save as" in non-US locale

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#387]
Described in detail in #364.  See the chart in https://github.com/inkstitch/inkstitch/pull/364#issuecomment-457930350 and the mention of decimal separators here: https://github.com/inkstitch/inkstitch/pull/364#issuecomment-457936088

It seems that DST and JEF files get corrupted on @jameskolme's system when using "Save As", but not when exported with "Embroider".  Changing the decimal separator from `,` to `.` (locale settings) seems to fix DST but not JEF.

**Comment by lexelby** [comment]
@jameskolme Could you please post some example broken files that Ink/Stitch produces but your machine says are corrupted?

1. File -> Save As, DST file, with decimal separator set to `,`
1. File -> Save As, JEF file, with decimal separator set to ','
1. File -> Save As, JEF file, with decimal separator set to '.'

If I understand your description correctly, all three of the above result in corrupted files, right?

**Comment by lexelby** [comment]
Oh, and for each of the above, could you also post a version made with the Embroider extension that is not corrupted?  Then I can compare the corrupted with the non-corrupted and hopefully I can spot the difference.

BTW, in case you're curious, I know it seems like an open and shut case of locale issues, but I really can't find anywhere in the code where we'd be writing a floating point number as a string (either with a `.` or `,` separator), so I'm still baffled. :)

**Comment by jameskolme** [comment]
Now I'm puzzled, no matter what I do machine will open everything, Janome preview software refuses to open save as versions. I did get pretty nasty errors when opening files on machine before. 
[Test.zip](https://github.com/inkstitch/inkstitch/files/2844613/Test.zip)

Error is failing, but like I mentioned before, if embroidery contains only running stitch, files are ok as far as I can test. 
[line.zip](https://github.com/inkstitch/inkstitch/files/2844689/line.zip)

**Comment by lexelby** [comment]
Okay, here's one problem: the files produced with Save As have a line feed at the end of the file (`0x0a`, a.k.a. `\r`), and they shouldn't.  I'll get that fixed soon.  That could be the entire problem for the Janome preview software.

**Comment by lexelby** [comment]
Does this one open properly in the Janome preview software?

[fixed.zip](https://github.com/inkstitch/inkstitch/files/2853707/fixed.zip)

**Comment by jameskolme** [comment]
Yes file works ok.

**Comment by lexelby** [comment]
Awesome!  That's the same file you gave me, but with the extra carriage return at the end removed.  Looks like that's what's causing the problem, then.
