### ISSUE TITLE
How to fill logo without fill? not an issue

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#390]
Some learning curve here, not the first time to think same dilemma. Question goes like this, how would you make this Z logo, size is 20mmx20mm? Too big for satin, but I think just doing fill is no good either. I´m doing this just for learning, it helps if learning happens using interesting shapes.

![z80](https://user-images.githubusercontent.com/44113605/53100158-f2844300-352f-11e9-978d-6645d374b8f9.png)
(Yes, I know how to fix second Z :) ) 

Original stamp
![z80_orig](https://user-images.githubusercontent.com/44113605/53101888-4e9c9680-3533-11e9-8db0-7371b72f60d8.png)

**Comment by lexelby** [comment]
Personally, I would try satins anyway.  The diagonal lines will definitely be fine as satins.  The widest parts of the triangle bits is probably about 10mm, right?  Kind of wide for a satin but not unheard of.  I would use all three kinds of underlay together to lift up the stitches.

If that doesn't work, another option is fill stitch with a 1-2mm satin border.

**Comment by jameskolme** [comment]
Ok, thanks. Wide part is close to 10mm

![z80_tri](https://user-images.githubusercontent.com/44113605/53120236-0fce0700-355a-11e9-83a3-0892e6791a2a.png)

Actually satin will work, needs just some tweaking. Thinking how inkstitch calculates satin spacing, correct value is 0.4mm for 0.3mm spacing. This is why I have failed similar shapes many times, shape make actual sating spacing 0.2mm and that's no good.  Then it is just matter of using some negative pull compensations to get gaps too wide, oops. 
![z80a](https://user-images.githubusercontent.com/44113605/53123405-a6ea8d00-3561-11e9-9df3-4c7ac190eea9.png)

**Comment by lexelby** [comment]
Yeah... Clearly I need to rethink the satin algorithm because 0.4 should mean 0.4 regardless of the angle of the rail.

**Comment by wwderw** [comment]
12.1 mm is typically the widest satin stitch that you would want.  On the machines I'm aware of, they actually automatically thread trim at 12.1mm.  You would have to turn off trims to make it go wider (usually only done with puff).

Those thin diag parts should be fine for satin stitching and just do fill for the wider ones.  Using a variety of stitch types is to be expected if approaching it from a production stand point first.

Other option, if still wanting to keep satin even with the wider area, but don't want to turn off trims, always do "split stitches".  Inserting a needle penetration at a certain spot to break up the long stitch width.  I typically only do this for more "texturing" then anything, but it is another option.
