### ISSUE TITLE
installing inkstitch

### ISSUE THREAD

**Issue by SarahShep** [inkstitch/inkstitch#391]
Hope someone can help me.  I am installing inkstitch and I got all the files in the right place and I see inkstitch in the extensions.  However, when I choose Extensions, inkstitch, embroidery it brings me to a window asking for Output file format and I selected Pfaff Embnroidery format VP3, then it ask me for a Directory and no matter if I leave it blank or I put in there the error is the same after hitting Apply. 

(No embroiderable paths found in document.
Tip: use Path -> Object to Path to convert non-paths.

What do I need to put into the Directory field.
Sarah

**Comment by wwderw** [comment]
If I'm not mistaken this error here:

"(No embroiderable paths found in document.
Tip: use Path -> Object to Path to convert non-paths.

Is usually related to not having converted primitives to paths or are using text without having converted to objects.  Does your file have text and/or primitives (circle, star, rectangle that were created using those tools)?

As to what to put in the Directory field, put where you want the file to be exported to.  If you leave it blank, last time I'm aware of, it will export to the inkstitch folder.  I don't know if that has changed in later versions (depending on what version you have), but last I recall, that's where it puts it.

You could alternatively use the "Save As Copy" function and select the appropriate stitch file to save as and it will save by default in the same directly as the main SVG file is saved to.

I personally use the "Save as Copy" function unless I need a txt csv file, then I would go through embroider.

**Comment by lexelby** [comment]
Hi @SarahShep, thanks for trying out Ink/Stitch!

What @wwderw said is spot on.  Ink/Stitch is designed to treat certain objects in your SVG document as "instructions" for how it should create stitching.  It's not designed to operate on objects such as Text, Rectangles, Circles, etc -- just plain Path objects.

I'm wondering if the error message might have thrown you off.  Did the word "path" make you think of a "path" like a "directory path"?  Perhaps we could change the error message to make it more clear.

**Comment by SarahShep** [comment]
So should I select an object first then select the embroidery button.

**Comment by lexelby** [comment]
Yes, you can select one or more objects to embroider just them.  You can also run Embroider without anything selected.  If you do that, it will assume you mean everything in the whole document.  It looks like you didn't have anything selected based on the error message above.

You might find our tutorials at https://inkstitch.org helpful.  They can give you an idea of what kinds of SVG objects Ink/Stitch is looking for.

**Comment by kaalleen** [comment]
I'm closing this issue now. Please reopen if it is still needed.
