### ISSUE TITLE
AI svg file can't save as PEC or PES with inkStitch

### ISSUE THREAD

**Issue by mnesnay** [inkstitch/inkstitch#392]
Hi,
When I bring in my svg file from AI, I can't convert it/save as a PEC or PES file. I have 32-bit inkstitch extracted into my inkscape extensions folder and have anti virus allowing this folder (windows defender too). When I hit save as and select pes/pec, the windows prompt screen comes up and stalls for ten or more minutes.

Should I try a different file format? All my objects from AI are converted to outlines/paths and then saved as a svg. Thank you.

**Comment by wwderw** [comment]
Ai's SVG format isn't quite as robust as Inkscapes.  It doesn't have the XML abilities to have the info for the Ink/Stitch plugin to parse to generate the embroidery file.

You'll still need to digitize the file and apply the embroidery info to the individual objects from within Inkscape.

Just like if you were to digitize an Inkscape SVG file for embroidery and bring that same file into Ai, it's quite possible that all that embroidery info would be lost, especially if you saved that SVG file from within Ai.

**Comment by lexelby** [comment]
Hi @mnesnay, thanks for trying out Ink/Stitch!

Ink/Stitch is designed to be used on files designed in Inkscape.  We do occasionally see weird behavior on files designed in Ai that are imported into Inkscape.  You may be able to solve the problem by copy-and-pasting the shapes into a new document in Inkscape.

May I ask, what are you hoping to do by importing an Ai file?  I think we could do a better job of making Ink/Stitch's purpose clear in the documentation.  Ink/Stitch is not intended as an "auto-punch" tool that can handle any SVG you throw at it.  Instead, it expects you to create certain kinds of objects in your SVG that act kind of like "stitching commands", instructing Ink/Stitch to do a satin stitch here, fill stitch there, running stitch there, etc.

You might find our tutorials useful: https://inkstitch.org/

**Comment by kaalleen** [comment]
@mnesnay Could you solve your issue?
