### ISSUE TITLE
Embroider name ordering, not a bug

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#393]
Running embroider several times for same file works great, but naming could be improved. Now we are getting new file types and it confuses windows :) 
![name_issue](https://user-images.githubusercontent.com/44113605/53581182-c5660f00-3b85-11e9-987e-ea07e3b80020.png)

**Comment by kaalleen** [comment]
It might be confusing, but this is actually how it is supposed to be. The newly saved file will have no "number ending". All other files are backups of the previous versions ... just in case you want them back. Simply remove the number and use the file as is.

https://inkstitch.org/docs/basic-usage/#step-6---stitching-out-the-design
(Maybe this website section needs an update too... "save as" is not even mentioned)

**Comment by jameskolme** [comment]
Oh ok, I was assuming latest and greatest file is with big number, my mistake. That was quickly fixed :)

**Comment by lexelby** [comment]
Ultimately I'm hoping to have Embroider no longer output files, instead leaving that to "Save As".  Embroider would become "Preview Stitch Plan".
