### ISSUE TITLE
Connections exploding when scaling or moving

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#394]
Possibly Inkscape issue?

Exploding connection lines can happen if  design is scaled down or simply moved. Sometimes this happens when opening scaled down design. Most of the time everything keeps connected, but end result shows there are some trims that newer worked, any ideas? 

I have tried using best selecting commands (select all, etc) to make sure everything is selected and nothing is hidden or locked. Every attach command line leaves behind. Only fix I know is just attach everything back again. This is not first time this happened, but can´t repeat so far. I´m puzzled because why there is this one white bean line disconnected also. 

![abrt_1](https://user-images.githubusercontent.com/44113605/53584247-e2054580-3b8b-11e9-9e19-4f02ab80f439.png)

End result, this is huge and black lobster is definitely not trimmed.
 
![abrt](https://user-images.githubusercontent.com/44113605/53588149-f6017500-3b94-11e9-84b3-508f9660d4fa.png)

Can anyone else explode this? Just move design with plenty of trims.
[abrt.zip](https://github.com/inkstitch/inkstitch/files/2916375/abrt.zip)

**Comment by jameskolme** [comment]
Inkscape is very likely to crash when doing this. Noticed one behavior, if moved, some of the connecting lines leave behind but not trim buttons. If trim buttons are moved, lines jump pack, so is this refresh issue? I try to ask Inkscape forum this one. 
 
![jump](https://user-images.githubusercontent.com/44113605/53630437-be3c1100-3c18-11e9-90c2-09555e31b3c8.png)

**Comment by jameskolme** [comment]
Found problem but don´t understand it, left scissor is bad. Originally did copy right scissor from left, but now it can be simulated again, if scissor is hidden and there are still some connecting lines flying around.

**Comment by jameskolme** [comment]
Using XML editor to spot difference, working scissor style:
fill:none;fill-opacity:1;stroke:#000000;stroke-width:0.30000001;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1

Not working style line is way different:
display:inline;fill:none;fill-opacity:1;stroke:#000000;stroke-width:0.29993531;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1

**Comment by jameskolme** [comment]
Maneged to pinpoint error to single shape. Manually removed display inline away, not sure what it is or where it came from, no help.  Why I can´t duplicate other shape and just go, error comes back. 

This is what Inkstitch gives out, most likely this is just error from something already happened. 
```
Traceback (most recent call last):

  File "inkstitch.py", line 62, in <module>

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\simulate.py", line 17, in effect

  File "lib\extensions\base.py", line 180, in elements_to_patches

  File "lib\elements\element.py", line 268, in embroider

  File "lib\elements\satin_column.py", line 765, in to_patches

  File "lib\elements\satin_column.py", line 690, in do_zigzag_underlay

  File "lib\elements\satin_column.py", line 613, in walk_paths

  File "lib\utils\geometry.py", line 109, in unit

ZeroDivisionError: float division by zero
```
Error shape file:
[error.zip](https://github.com/inkstitch/inkstitch/files/2920602/error.zip)

**Comment by jameskolme** [comment]
Found workaround that makes absolutely no sense at all, this works only on complete image. Keep both scissors under same group, originally scissors were on separate groups.

**Comment by lexelby** [comment]
To be honest, the connection support in Inkscape seems to be a little touchy.  I've seen situations where the lines go the wrong way as well.

We're not really using the connection support properly, since it's not designed to work on shapes that aren't closed.  I wish it didn't explode like you're seeing, but I don't think there's much we can do about it :(

**Comment by kaalleen** [comment]
Closing this issue now (it is related to #585 )
