### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#395]
Travis CI was recently acquired and subsequently had a big round of lay-offs.  It's possible that Travis might go under, or they might change their business model to no longer support open source, or similar.

It might be worth revisiting #309 or another solution.

**Comment by wwderw** [comment]
I would say that it wouldn't hurt to have a backup option just in case, but this is another one of those wait and see, but I would definitely have a backup option.

I know they always say, nothing will change blah blah blah and in some cases, know that's not the case (acquisition of the Substance suite of programs).  I would definitely have a back up and maybe have it mirrored on that backup just in case.  Probably wouldn't hurt anyway to do that.

**Comment by kaalleen** [comment]
We are using the GitHub actions now.
