### ISSUE TITLE
problems launching ink stitch

### ISSUE THREAD

**Issue by katrinaux** [inkstitch/inkstitch#398]
Sorry for opening an Issue. I found the solution in an other issue.
The order of the folders in extensions were not correct. I reorganized like described in the other issue-answer and could now install it. :-)

Tried to launch: inkstitch/bin/inkstitch
Arguments: ['inkstitch/bin/inkstitch', '--extension=install', '/var/folders/cc/006z18v96dn2sbf0c5ypt8l00000gp/T/ink_ext_XXXXXX.svgDO43XZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by katrinaux** [comment]
Hallo, sorry I am very new to all of this and just saw that the question was already asked. But the answers do not help me.

I have deleted and decompressed the folder into extensions several times and made sure to decompress it right inso the extension folder. It took a while but I can now see the ink/stitch in the extensions of Inkscape. But now it always tells me the error above.

I have a 64bit system and the high Sierra 10.13.6 running on my Mac.

I hope you can help me.
Greetings,
Katrin

**Comment by kaalleen** [comment]
> Sorry for opening an Issue. I found the solution in an other issue.
> The order of the folders in extensions were not correct. I reorganized like described in the other issue-answer and could now install it. :-)

Glad you got it working :) I am closing this issue now. If you have more questions just reopen it or create a new issue!

For others that might find this issue while looking for help...

The file structure should be as follows:
```
/path/to/inkscape/extensions/
                             inkstitch.py
                             inkstitch_embroider.inx
                             <lots more inx files>
                             inkstitch/
                                       bin/
                                           inkstitch
                                           <tons of code library files and folders>
                                       examples/
                                           <svg files>
                                       palettes/
                                           <.gpl files>
                                       symbols/
                                           inkstitch.svg
```
More information can be found as a text on our [homepage](https://inkstitch.org/docs/install) or as a [video tutorial](https://inkstitch.org/tutorials/resources/beginner-video-tutorials/) on YouTube.
