### ISSUE TITLE
Inkstitch will not launch

### ISSUE THREAD

**Issue by jdmaddox** [inkstitch/inkstitch#400]
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=g826', '--extension=params', 'C:\\Users\\maddo\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg0N3CYZ']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jameskolme** [comment]
Start Inkscape and go to extensions, inkstitch starts over there. Some embroider compatible shapes are required to use inkstitch, so this might be helpful: https://inkstitch.org/docs/basic-usage/#step-1---draw-an-object

**Comment by kaalleen** [comment]
Looks like something went wrong with your file structure, while copying Ink/Stitch into your Inkscape extension folder.

Have a look at this issue here: #398 , it might already help you to solve your problem?

**Comment by kaalleen** [comment]
This is most probably a antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.
