### ISSUE TITLE
contour of font not stichable

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#403]
i would like to stich only the outline of a letter but that does not work with my machine. What adjustment can i make?

**Comment by lexelby** [comment]
Try this:

1. Create your text using Inkscape's text tool with whatever font you like (not Inkscape's Lettering extension).
2. Convert the text to a path (Path -> Object to Path)
3. Select the objects.
4. Open the Stroke/Fill panel.
5. Disable the fill.
6. Set the stroke to a dashed line (any dash will do).

A dashed line tells Ink/Stitch that the line should be stitched as running stitch.  You can then use the Params dialog to adjust details about the stitching, set as Bean Stitch, etc.

**Comment by ARKopp** [comment]
thanks! cool so easy.
