### ISSUE TITLE
convert outline into satin stich

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#405]

**Comment by ARKopp** [comment]
I want to turn the outline of a letter into a satin stich with the line to satin tool. Some letters work some letters dont work .

**Comment by lexelby** [comment]
The "Convert to Satin" extension needs some work.  Currently, it gets confused by closed paths and paths that come close to touching themselves.

You can work around this issue by breaking up the path into multiple sections first.  In the future Ink/Stitch will do that for you automatically if needed.

**Comment by ARKopp** [comment]
ok got it opened the line a bit and now it works! With one "E" I still had problems but then I just copied another e.
