### ISSUE TITLE
fill stich before satin stich 

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#406]
How can I define the order that fist the file stich and then the Satin Stich.

**Comment by kaalleen** [comment]
Open the objects dialogue (which you can find under 'Objects > Objects...'). You will see a list of all objects in your svg document. The way they are ordered is the stitching order from bottom to top. Change the order of the objects with the up and down symbols of the panel - you could also set custom shortcut keys for this matter if you like.

**Comment by ARKopp** [comment]
ok thanks got it! Thanks! Danke!

**Comment by ARKopp** [comment]
https://www.dropbox.com/s/gtx3z0d3jr1nknx/Screenshot%202019-03-11%2018.58.58.png?dl=0

**Comment by ARKopp** [comment]
<img width="1191" alt="Screenshot 2019-03-11 18 58 58" src="https://user-images.githubusercontent.com/4289157/54146236-d0dff280-442f-11e9-9e11-c78a2ad75a1a.png">
