### ISSUE TITLE
Inkstitch error after add-on install?

### ISSUE THREAD

**Issue by cluster7** [inkstitch/inkstitch#408]
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=simulate', 'C:\\Users\\sheil\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgATFKYZ']
Debugging information:
```
Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by kaalleen** [comment]
Welcome to the project. Sorry you are having trouble to get Ink/Stitch running.

Could you confirm your file structure?
It should be as described in #398 

You will also find links that might help you to get Ink/Stitch running.
Hope this will help you to solve your problem. If you then still have trouble, ask whatever you need to know ;)

**Comment by kaalleen** [comment]
This is most probably an antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.
