### ISSUE TITLE
simulating GNU.svg throws error

### ISSUE THREAD

**Issue by JensKorte** [inkstitch/inkstitch#410]
I tried to simulate printing of https://de.wikipedia.org/wiki/Datei:Official_gnu.svg

Inkscape 0.92 r15371 from Devuan Ascii. inkstitch-v1.22.1-linux-x86_64.tar.gz

path1526: Fehler: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 174, in to_patches
  File "lib/elements/auto_fill.py", line 136, in fill_shape
  File "lib/elements/auto_fill.py", line 128, in shrink_or_grow_shape
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 137, in shape
  File "lib/elements/element.py", line 286, in fatal
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

shapely.geos - INFO - Self-intersection at or near point 385.29027091398115 350.07769848464596

**Comment by jameskolme** [comment]
There is way to many lines crossing and small shapes on this image, little bit cleaning and it should work just fine.

![gnuu](https://user-images.githubusercontent.com/44113605/54277088-8083a480-4597-11e9-8506-50dad342ba3d.png)
This is not ready for embroidery, but no errors, long way to make it look like original image still.

**Comment by lexelby** [comment]
Hi @JensKorte, thanks for trying Ink/Stitch!  Thanks for the bug report.  Ink/Stitch definitely should not be crashing like that.  

Regarding the SVG you're using:  Ink/Stitch isn't intended to be run on existing, unmodified SVG files.  Instead, you use an SVG file as a medium to create commands that tell Ink/Stitch how to generate stitches.

You might find our tutorials at https://inkstitch.org/ helpful.

**Comment by JensKorte** [comment]
> You might find our tutorials at https://inkstitch.org/ helpful.

Thanks, I will have a look at it.

**Comment by lexelby** [comment]
I'm reopening this because any stack trace is a bug, regardless of whether the user was doing something I didn't expect them to.

**Comment by lexelby** [comment]
same as #467
