### ISSUE TITLE
feature request: versions in bug report

### ISSUE THREAD

**Issue by JensKorte** [inkstitch/inkstitch#411]
When reporting #410 I realized I have to copy inkscape and ink/stich versions by hand. It would be nice if the versions would be listed in the beginning or at the end of the bug report and I can choose to copy or not.

**Comment by lexelby** [comment]
Great idea!  We need to up our bug-report output in general, to make it easier to report stuff.  Thank you for going the extra mile to create your bug report!

**Comment by kaalleen** [comment]
Ink/Stitch version has been added to bug output and will be included up from the next release.
