### ISSUE TITLE
Adjacent fills 

### ISSUE THREAD

**Issue by MK-12-20MM** [inkstitch/inkstitch#412]
Not sure if this is an issue or my finagling or just not proper implementation on my end. 1st of all thanks for a great extension.  

 Using: 
Inkscape 0.92.4 (5da689c313, 2019-01-14)
Inkstitch-v1.22.1
Janome 400e

There seems to be always gaps when there is adjacent fills butted together. SVG and stitch plan and emulation look as desired but actual output may vary. Maybe this is bad implementation on my behalf.  Have attached a test I was using but have had this occur even when overlaying 2 objects even up to 1mm.   

![IMG_20190315_124301](https://user-images.githubusercontent.com/10312448/54453430-4b0cc180-4725-11e9-9118-edf505d8c834.jpg)
![IMG_20190315_124302](https://user-images.githubusercontent.com/10312448/54453458-5829b080-4725-11e9-8d95-989c47c54c2c.jpg)
![IMG_20190315_124608](https://user-images.githubusercontent.com/10312448/54453462-5b24a100-4725-11e9-9266-01c1ba8b179c.jpg)

 
[test3.zip](https://github.com/inkstitch/inkstitch/files/2972388/test3.zip)

**Comment by MK-12-20MM** [comment]
Also - vid of simulation ...

https://youtu.be/GJwPS3QZ7IA

**Comment by wwderw** [comment]
That is what is referred to as push/pull.  That can happen with any software.

How one digitizes those objects (overlapping a small portion, changing up stitch angles (it helps having different angles) etc) can affect the severity of it.  It's also possible to compensate with more stabilizer.

What is being stitched on also plays a part.

**Comment by jameskolme** [comment]
params/autofill there is value line called expand, it expands shape to compensate push/pull and should close gaps. 

Black line shows original fill shape edge
![fillgap](https://user-images.githubusercontent.com/44113605/54458614-1290d600-476d-11e9-9c5b-30b9f2cf7e5d.png)

**Comment by MK-12-20MM** [comment]
Thanks for your assistance. I looked over the push-pull compensation again https://inkstitch.org/tutorials/push-pull-compensation/#.  It makes better sense.

 I have seen the expand option but have not tried it, I will give it a shot. 

I have tried overlapping objects or is that the wrong approach, even though mileage and results may vary considering all the variables?   For example (the last image in the opening post) the 2 objects were overlapped 1 mm (increasing or pushing the nodes out in the object) or this concept below.

![app](https://user-images.githubusercontent.com/10312448/54460991-39351980-4739-11e9-9edd-0b396a0cf146.PNG)

Kind of gun shy with too much stitching or overlapping  as my previous over zealous attempts ended up with a broken needle and my wife will ring my neck if I break her new machine.  :)   Thanks for the tips.

**Comment by wwderw** [comment]
Overlapping is one method (perhaps the most common) used.  If your breaking needles etc, I would check your density settings.  Density and stitch angle could also affect push/pull as well even with an overlap.

Another option when it's dealing with 2 fills is to actually have a satin outline stitch, that helps mitigate the need to overlap 2 fills in areas.  Having a satin outline stitch (if size and the design itself allows for an outline stitch) also helps give a finished look around the fill edges as well.

**Comment by MK-12-20MM** [comment]
Good tips. Thanks and appreciated. Had only one incident with the broken needle but the cringe factor is still there. :)  I am going to close this as its more user error or experience factor.
