### ISSUE TITLE
Horizontal Movement not transferring in pattern

### ISSUE THREAD

**Issue by CannarWilm** [inkstitch/inkstitch#413]
Hi,

I'm running into an odd problem and I cannot figure out if I am doing something wrong or whether this is a bug. When we create a .PES file and import it to our brother Innov-is 955 machine the pattern does not work properly. I have attached the source file, the output pattern and some pictures to illustrate the problem. We are using Windows that is kept up to date.

When the pattern has been embroidered and transferred to the machine, it appears to lose all horizontal movement information. The carriage seems to go up and down only. You can see in the picture of the embroidery the red column that was created by a small amount of the pattern. The blue plastic lid indicates where the pattern should be.

The other pictures show how the pattern appears (correctly) on my screen when I select it on the machine. You can also see that, when I go to the layout menu, the square taken up by the pattern shows correctly for a second or so and then changes to just a line, even though the correct dimensions of the pattern still appear.

I'm not sure what I'm doing wrong. I have tried to create a simpler pattern and had the same issue. Annoyingly we have used the software to create a successful pattern once before.

![2019-03-17 16 27 04](https://user-images.githubusercontent.com/48653165/54494445-302b8000-48d2-11e9-8222-3642d2d14800.jpg)
![2019-03-17 16 27 32](https://user-images.githubusercontent.com/48653165/54494475-944e4400-48d2-11e9-944a-1b84ed901ba2.jpg)
![2019-03-17 16 27 41](https://user-images.githubusercontent.com/48653165/54494476-987a6180-48d2-11e9-9472-0099a24ffd66.jpg)
![2019-03-17 16 27 58](https://user-images.githubusercontent.com/48653165/54494479-9dd7ac00-48d2-11e9-82d7-1ed501ed430f.jpg)
![2019-03-17 16 28 01](https://user-images.githubusercontent.com/48653165/54494480-a16b3300-48d2-11e9-86da-3ea25db4d579.jpg)

[Shirt Logo.zip](https://github.com/inkstitch/inkstitch/files/2975415/Shirt.Logo.zip)

**Comment by lexelby** [comment]
Well, that sure is weird!  When I get a chance, I'll try your PES on my brother SE400 and see if I see the problem too.

In the meantime  does your machine support DST files?  If so, could you try exporting as DST instead and see if it sews properly?

**Comment by CannarWilm** [comment]
It says that it supports that format and I tried to use it. However the machine didn't recognise the file properly saying that the pattern was too big for the machine.

**Comment by lexelby** [comment]
Huh.  Definitely something wrong with the file exporting code on Windows, then.  I did change that recently to fix another bug.  I'll try to look at it soon, but in the meantime, you might have some luck going back a few versions of inkstitch.

**Comment by CannarWilm** [comment]
Thanks :D

**Comment by kaalleen** [comment]
@CannarWilm Could you give us an update? Is it still happening?

**Comment by CannarWilm** [comment]
Hi,

we did fix the problem but for the life of me I can't remember how. I think we may have switched software (sorry).

**Comment by kaalleen** [comment]
Ok, no need to be sorry and thanks for the feedback!
Since no one else has reported an issue like this, I will close it now.
It can be reopened if anybody experiences something similar.
