### ISSUE TITLE
Auto-route trims not trimming enough

### ISSUE THREAD

**Issue by jameskolme** [inkstitch/inkstitch#417]
Long time suspecting this and finally noticed whats going on, sometimes trims are missing. Using auto-route leaves last object without trim, if same color still continues, we have some loose ends left behind. 

I use auto-route like this frequently, one object group finished before moving next. 

Four separate autoroute groups on this image.
![autoroute 1](https://user-images.githubusercontent.com/44113605/54816479-faedac00-4c9c-11e9-9fd6-ea28ef5a2b4c.png)

Just thinking, but is this already fixed and my current "revamp fill" version is missing this, must be lettering trims.

**Comment by lexelby** [comment]
I think this is already fixed in the #399 branch.  Could you give it a try and close this if so?  If it's still broken in #399 then definitely let me know so I can fix it :)

**Comment by jameskolme** [comment]
Yes, indeed this is already fixed.
