### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by DreadKnight** [inkstitch/inkstitch#422]
I'm using KDE Neon distro, with latest release of InkStitch https://github.com/inkstitch/inkstitch/releases/tag/v1.22.1

But the UI looks flat and dark for some reason:
![krap](https://user-images.githubusercontent.com/587487/55323017-7eba4c00-5486-11e9-8dd2-d71361bc07e0.jpg)

Any suggestions on how to fix that? Or perhaps this issue happens to others as well?

**Comment by wwderw** [comment]
What are your theme settings?  I'm running Kubuntu and I don't have that type of concern depending on the settings that I use.  

I attribute it to Inkscape being GTK based while KDE is QT. I could be off in that regard, but that's what I'm thinking.

**Comment by lexelby** [comment]
I think @wwderw's right on.  That looks like it's the GTK theme you've set.  It can be a little confusing/difficult to set your GTK theme while in KDE, and I can't remember offhand how to do it.

**Comment by DreadKnight** [comment]
There was probably some caching issue. I've re-applied the Adwaita-Dark theme and the UI shows white and non-flat as before now, way more usable, though I wish it had a dark version as well, so perhaps I should close this and make a new request for a dark theme (since that's the direction of things regarding UIs for economical, technological and health related reasons).

**Comment by DreadKnight** [comment]
Did more testing, found the KDE settings easily. The UI looks bad with Adwaita-Dark and GTK3 dark theme preference.
![dark](https://user-images.githubusercontent.com/587487/56184276-32444400-6022-11e9-9baf-e85b1aaf6947.jpg)

**Comment by lexelby** [comment]
Awesome, glad you figured this out!

I don't think it makes sense to add theme support directly to Ink/Stitch, and TBH, I don't even know how to go about that.  Does it work for you if we just rely on you setting the system-wide GTK theme?

**Comment by DreadKnight** [comment]
@lexelby That's the whole problem actually, as it switches to a dark theme and displays rather awful.
If it would stick to being light all the time, this would be less of an issue, although I prefer dark themes all around.

**Comment by wwderw** [comment]
I'm pretty sure that QT based isn't going to play well with GTK3.

I do also prefer dark themes (it may help to pull out blue light as well for the lighter areas, if eye strain is a concern) and this is the settings that I use for Kubuntu.  It doesn't make the Ink/Stitch UI dark though, but it's what I use to allow for darker UI for everything else and still make Ink/Stitch UI usable.

Some settings actually make it to where it's unusable.  Not just not attractive to look at, but can't see input numbers and can't see thread simulation all that well, especially if using darker thread colors.

![Kubuntu Settings](https://user-images.githubusercontent.com/24878362/56357230-bcb2b200-61a0-11e9-9e9a-6c3ad0e602ba.png)

**Comment by lexelby** [comment]
Huh.  I'm not sure what Ink/Stitch is doing that might be causing it to switch to a dark theme...

**Comment by wwderw** [comment]
> Huh. I'm not sure what Ink/Stitch is doing that might be causing it to switch to a dark theme...

Some of these were user created themes, so I think the them itself was "forcing" it.
