### ISSUE TITLE
realistic rendering always renders entire design

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#423]
When you check the "realistic" box for one of the color blocks, it now renders the entire design as opposed to just that color block.  What I'm expecting (and how I think it used to work?) is that it should only realistically render that one color block.

@kaalleen did this change recently?

**Comment by kaalleen** [comment]
Uh, I am not aware of changing anything at realistic rendering behavior.
Will have to have a look into this.

**Comment by kaalleen** [comment]
Oh, I know what happened. It happened in release 0.12.0.
Fix will have to wait until after work.
