### ISSUE TITLE
Running Stitch routed Inside Fill Area not around border

### ISSUE THREAD

**Issue by furicks** [inkstitch/inkstitch#425]
When filling multiple blocks the running stitch travels around the perimeter of the fill. If the fabric has been stretched by previous operations which almost always happens the running stitch shows up outside of the fill. Other programs I have worked with will route the running stitch through roughly the middle of the fill area. This way the running stitch is very likely to be covered by the fill area. 

![image](https://user-images.githubusercontent.com/5166589/55442658-91637c80-557d-11e9-8600-a409ed39a429.png)

![image](https://user-images.githubusercontent.com/5166589/55442601-52cdc200-557d-11e9-8c8f-139deab6b631.png)

**Comment by lexelby** [comment]
Hi, @furicks!  Thanks for trying out Ink/Stitch.

Yes, routing running stitch inside the fill shape is a much-desired feature (#257).  And as it happens, we're very actively in the process of developing exactly that feature over in #409!  I'm hoping to have a new version of Ink/Stitch ready for release by the end of the week.

If you're anxious to try it, you can grab the testing version [here](https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-revamp-fill).  And if you do that, we'd really love to know how it goes for you.  You can swing by #409 and leave your feedback if you feel so inclined.

**Comment by lexelby** [comment]
I'm going to close this issue now just so that we don't have confusion between this one and #257.  Feel free to reply here, in #257, or in #409, whatever suits you.
