### ISSUE TITLE
Naming issue when creating zip files

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#430]
Even when I do `Save As...` and remove the .zip from the filename to be created, the files inside the archive end up named `[].zip.pes` and so forth. (The archive's filename still gets the `.zip` so I assume that's getting added in again after I take it out, but before the stitch filenames get generated from it.)

![2019-04-09--1554823088_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/55812671-62876200-5ab9-11e9-8259-ecb1d5942574.png)

**Comment by tyrosinase** [comment]
(also "Append filename extension automatically" doesn't change the behavior, either for internal files *or* the archive file)

**Comment by kaalleen** [comment]
Thank you for reporting this issue. There is a new development build, which should take care of it. You can download and test it here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-fix-zip-files-naming

You might want to wait for @lexelby to approve it.

**Comment by lexelby** [comment]
Oh interesting!  This must be the difference between doing 'Save As...' and 'Save Copy As...'.  Thanks for the quick pull request, @kaalleen.  I'll join the discussion there.
