### ISSUE TITLE
Incomplete macOS Manual Setup Instructions

### ISSUE THREAD

**Issue by Katee** [inkstitch/inkstitch#434]
The [Manual Setup](https://inkstitch.org/developers/inkstitch/manual-setup/) page is missing a few instructions I found necessary to get things to work on macOS.

By default `bin/generate-inx-files` was not able to use the inkscape python files which caused `ImportError: No module named inkex`. I modified `bin/generate-inx-files` to include `sys.path.append("/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/")` with the other `sys.path.append` entries. (I'm not sure if it is possible to automatically determine the location of `Inkscape.app`. Inkscape could also have been installed in `/Users/$USER/Applications`).

Once the `*.inx` files where generated and linked I encountered `ImportError: No module named shapely` when using Ink/Stitch inside Inkscape. This was caused by a mismatch between the version of Python used by Inkscape inside XQuartz and the Python installation I had installed the dependencies for. I fixed this by:
1. Finding the location of Inkscape's `preferences.xml` (Edit > Preferences > System > User extensions). For me the location was `/Users/$USER/.config/inkscape/preferences.xml`.
1. Closing Inkscape (very important as Inkscape **over-writes `preferences.xml` on close**).
1.    Editing `preferences.xml` so that `<group id="extensions" />` included the `python-interpreter` attribute. For me this ended up being
    ```
  <group
     id="extensions"
     python-interpreter="/usr/local/bin/python" />
    ```
    where `/usr/local/bin/python` is the output of `which python`. If your default installation is python3 this will need to point at your version of python2.

**Comment by lexelby** [comment]
Thanks a bunch for figuring this out!  I don't have a mac to test with, so it's really useful to have a developer with a mac join the project.  Welcome, and have fun :)

BTW, if you're interested, I'm looking for a mac user to test #432.
