### ISSUE TITLE
Just Wanted To Say....

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#439]
How much I'm loving this project.

I've been using it exclusively in my freelance digitizing work since the beginning of the New Year.  Finally made it possible for me to only go into my Windows VMs for nostalgia only and not a necessity for day to day work.

Latest digitizing customer sent me this comment after they did a test stitch out (I was still using the dev fill revamp version, even though it was in the stable branch by then (have it loaded now):

>...the design stitched out great. We also ran it in 60 weight thread and it looked even crisper.

**Comment by lexelby** [comment]
That just made my day. :D  It's so awesome that you're able to use Ink/Stitch exclusively!! @kaalleen maybe we need a little testimonials/quotes section at the side of the main inkstitch.org page ;)

@wwderw do you know of any other professional digitizers that have tried out Ink/Stitch?

**Comment by wwderw** [comment]
>@wwderw do you know of any other professional digitizers that have tried out Ink/Stitch?

A couple that have tried it, I've known far more individual users, that still maybe embroiderers by trade, just not freelance digitizers.  For the freelancer's, based on only my own experience, it's hard to break them from commercial closed source programs.  I think that's the biggest stumbling block.  Some may have tried earlier own to break free and open source wasn't up to snuff (in embroidery, this is the only viable embroidery program out there) at all and that I think is what put them off.

From what they've relayed to me is that they like the beginnings of it and it shows promise, just that there are some functions that they would like to see implemented or some functions more polished. 

Lettering seems to be the biggest one across the board, I still mainly semi-manually digitize all my lettering, but I can definitely understand that.

**Comment by lexelby** [comment]
Yeah, that pretty much matches with my impression of the state of our project.  I feel like we're not polished enough for mainstream adoption yet, and trying to push too many folks to try Ink/Stitch now could potentially hurt our image for the future.

That said, I feel like we're surprisingly close!  We've come a long way, and there aren't too many must-have features that are missing.  It's exciting :)

**Comment by tyrosinase** [comment]
I am not (yet?) a pro digitizer, but I think it greatly helped that I was already a hardcore Inkscape user. If I was learning Inkscape *and* digitizing (*and* how to use the machine itself) at the same time, that might have been different, but as it was Ink/Stitch was absolutely a natural step.

Admittedly, my only experience with "pro" digitizing software is the occasional bit of helping Mom keep her antiquated rig (the one I just inherited, but haven't tried to use yet) running. And she did a lot more just resizing (Melco Sizer, mostly) than digitizing.

But so far the only limitations I've run up against are in my machine, not the software. And y'all know, I have *not* limited myself to ordinary embroidery (in-the-hoop plushies, paper piercing/card embroidery, etc.)

**Comment by wwderw** [comment]
> But so far the only limitations I've run up against are in my machine, not the software. And y'all know, I have not limited myself to ordinary embroidery (in-the-hoop plushies, paper piercing/card embroidery, etc.)

These features aren't necessarily limitations in the traditional sense.  The user can get around them if doing everything semi-manually, which is perhaps the most powerful toolset out there (and the toolset that I'm glad that this project focuses on, I remember the original extension from 2010 by someone else, it was all about the auto conversion), but that does require user knowledge/ability to be much higher.  Unfortunately, a lot of people are used to more convenience features and some of those do need to be there to compete (lettering being one and since lettering can be done without having to auto convert the lettering itself, it doesn't hurt quality of output) with the commercial programs.

Most of the people out there in the commercial world are used to using Ai (me) or DRAW (comes bundled in with my preferred commercial application, although I never installed it after X5 as I didn't care for DRAW), so using Inkscape is going to have some learning curve to it.  I haven't found something that the closed source programs could do that Inkscape couldn't in my normal workflow, but some were very very different from the closed source programs.

>That said, I feel like we're surprisingly close! We've come a long way, and there aren't too many must-have features that are missing. It's exciting :)

It really does seem like we are close.  And there are a lot of people that I think would benefit from this program.  A program like this really is needed to be out there.  The fact that it's cross platform (especially with Linux) puts it ahead of the pack as well as most digitizing programs are Windows only (although with DRAW again having a Mac version, I wonder if those that come bundled with DRAW will also have a Mac version).

**Comment by HoneyPhantomhive** [comment]
Absolutely agree. I started embroidery with little to no money after buying the machine-- it's been amazing to find a free software with such amazing capabilities. Thank you so much for creating this wonderful software!!

**Comment by lexelby** [comment]
> Absolutely agree. I started embroidery with little to no money after buying the machine-- it's been amazing to find a free software with such amazing capabilities. Thank you so much for creating this wonderful software!!

YAY!  THIS, this is why I'm here.  This is what I'm really aiming for.  Ever since I got my first machine as a gift and didn't want to pay $billions (or anything) for digitizing software, I've wanted to make a viable free alternative.  I'm so glad it's working for you!

**Comment by lexelby** [comment]
I would really like to include these two quotes on inkstitch.org if you two are up for it:

> I've been using it exclusively in my freelance digitizing work since the beginning of the New Year. Finally made it possible for me to only go into my Windows VMs for nostalgia only and not a necessity for day to day work.

> I started embroidery with little to no money after buying the machine-- it's been amazing to find a free software with such amazing capabilities. Thank you so much for creating this wonderful software!!

@wwderw @HoneyPhantomhive would that be okay with you two?  Is it okay if we mention you by name? (just GitHub user names is fine)

If not, it's fine, I totally understand if you don't want that level of "publicity" :)

**Comment by wwderw** [comment]
I wouldn't have a problem with it.

**Comment by dcwhyme** [comment]
Howdy, I'm Daniel and I too use Ink/Stitch for most all my digitizing work. I usually don't embroider the patterns afterward, but (after getting over the learning curve moving from a commercial digitizing suite) I've yet to have a customer have a problem from designs digitized in it. Digitizing isn't my primary focus in life (more born out of necessity to enable some new product lines for my retail store) but I do take on the occasional project from others when workload allows. Lately, I've been teaching a few local embroiders how to use the software, and most all are amazed that you can produce such great work with software that doesn't take selling a kidney to purchase.

I'll second wwderw's opinion on the lettering module leaving a bit to be desired, but that's not really an issue for most of the work I do (when it is, it's not really a huge inconvenience to hand digitize). For others though, that's the majority of their business. 

Something I found when I wrote software for a living is many people don't care what they have to pay for a critical piece of their infrastructure, so long as it just works and they can get help when they need it. Support options with a lot of open source products can be lacking, versus support from somebody you are shoveling money to. Not trying to say anything there - it's just an unfortunate and (even these days) common misconception. Another issue when trying to foster adoption is workflow - when you work in a program day in and day out, it becomes a second home. You learn the keyboard shortcuts, you learn to pick the correct tool from the toolbar instinctively, etc. Moving to a completely different application means adapting your workflow (sometimes easier said than done). Any way you cut it, it's a scary proposition for some when talking about their bread and butter. It's terrifyingly easy to waste significant amounts of time when "jumping ship" from one application to another.

That said, once I learn this Git thing, brush back up on Python and get a bit more free time, I wouldn't mind throwing my hat into the ring and submitting a patch or two here and there.

**Comment by wwderw** [comment]
> Lately, I've been teaching a few local embroiders how to use the software, and most all are amazed that you can produce such great work with software that doesn't take selling a kidney to purchase.

This is a big misconception from the people that I deal with as well.  In my experience, it also tends to be a generational mentality as well.  My parents are those that think if it's worth it's salt, it should have a price to it.

I think what adds to that is in the licensing for open source, it states that the software is "as is" and that there are no promises, including no promise that it while actually do what they say it will do.  While I understand why that's in there, it does put up a big mental roadblock.  And there are far more people (myself included) that can't code to fix something, so the advantage of it being open source doesn't help them in that regard as well.

>... the lettering module leaving a bit to be desired, but that's not really an issue for most of the work I do (when it is, it's not really a huge inconvenience to hand digitize). For others though, that's the majority of their business.

Lettering is really a huge thing.  Typically the first thing that I teach people when I do teach them, manual, semi-manual digitizing lettering.  Now, nothing I do involves Team Names or anything like that for my day to day work, but there are a lot of people that sometimes only have lettering software.  Lettering I think is probably the biggest hold back, then support for multi-decoration methods to help entice with the masses.

>Honestly though, Ink/Stitch is still miles away from its nearest FOSS competitor

This is so true and it's also the only one available on all 3 platforms.  The nearest one to Ink/Stitch is Windows only and it hasn't seen active development since 2006 and it is severally limited.  It's only value to me, is as a teaching aid due to it's minimalist GUI.

>Something I found when I wrote software for a living is many people don't care what they have to pay for a critical piece of their infrastructure, so long as it just works and they can get help when they need it. Support options with a lot of open source products can be lacking, versus support from somebody you are shoveling money to.

Absolutely, if talking about in a business environment where efficiency is the key, it has to do everything that they need it to do, when they need to do it (this very thing is what played a part in my leaving the Windows system after having only known that system since I was 5 yrs old back in the DOS days).

If it doesn't do all that, there has to be a clear cut way to get support and quickly (sometimes extremely quickly).  While even with commercial software, I always tried to search for the answers first before dealing with the official support, not everyone is like that (I would probably speculate that most aren't, because that would dip into efficiency as well).

Which also plays into this:

>Moving to a completely different application means adapting your workflow (sometimes easier said than done).

The unfortunate side effect to that is that people also think that the program can't do what they need it to do, because the workflow is vastly different.  It's not that it may not be able to do it, it's just that it requires doing things differently then what they are used to.

Just like going from Windows/Mac to Linux, there has to be the desire to want to switch (if they were used to something else), or better hope that they are able to pick up things quicker with tech, if the desire isn't high up there.

**Comment by dcwhyme** [comment]
Are you the Wild West Designs guy on Youtube @wwderw btw? If so, your the one who turned me onto Ink/Stitch in the first place. I spent a few days looking into alternatives back around January, only to find a suggested Youtube video on my homepage when trying to find a documentary to settle down for the night with. Anyway, if that was you, thanks. I probably wouldn't be here if not for your ambassadorship.

**Comment by wwderw** [comment]
> Are you the Wild West Designs guy on Youtube @wwderw btw?

That's me.

**Comment by kaalleen** [comment]
I updated the landing page with the quote of @wwderw. If you want any corrections, just send me a note.

**Comment by lexelby** [comment]
Yay, looks great!

**Comment by HoneyPhantomhive** [comment]
> I would really like to include these two quotes on inkstitch.org if you two are up for it:
> 
> > I've been using it exclusively in my freelance digitizing work since the beginning of the New Year. Finally made it possible for me to only go into my Windows VMs for nostalgia only and not a necessity for day to day work.
> 
> > I started embroidery with little to no money after buying the machine-- it's been amazing to find a free software with such amazing capabilities. Thank you so much for creating this wonderful software!!
> 
> @wwderw @HoneyPhantomhive would that be okay with you two? Is it okay if we mention you by name? (just GitHub user names is fine)
> 
> If not, it's fine, I totally understand if you don't want that level of "publicity" :)

Sorry, this is SUPER late! But that would be fine

**Comment by kaalleen** [comment]
Thank you!! The website is updated, including your quote :)
