### ISSUE TITLE
Self Intersection / Non Simple Polygons

### ISSUE THREAD

**Issue by Katee** [inkstitch/inkstitch#444]
Currently Ink/Stitch does not handle self intersecting paths for fills. This can be frustrating when using an existing SVGs (e.g. #374, #410). The error message includes [x, y] to find where an intersection happens. However, this isn't a superb user experience. Some programs provide feedback on where self intersection is present (for example Fusion 360 highlights self intersecting T-splines).

A solution for doing fills with self-intersection would be to first break the polygon into multiple simple polygons. [Partition of a Non-Simple Polygon into Simple Polygons](http://www.cis.southalabama.edu/~hain/general/Theses/Subramaniam_thesis.pdf) has a solution to this, and [simplepolygon](https://github.com/mclaeysb/simplepolygon) is an MIT licensed version in Javascript. For fills, I believe this could happen completely transparently to the user. However, it could also be implemented as a menu item and allow users to add params to the (now separate) objects / paths. 

Although polygon partitioning could likely be built upon to handle self intersecting auto satin columns (#253, #254), that is a more complicated problem. I believe fills have a single solution, whereas satin columns have multiple potential solutions (for example: go over the intersected area multiple times, go over it once the first time it is encountered, go over it only the last time, etc).

Note: I don't think simplepolygon will work exactly out of the box, for example I believe it would only handle this self-intersecting hourglass on the right. The left one has a duplicate point at the intersection that would [cause an error](https://github.com/mclaeysb/simplepolygon/blob/master/index.js#L47).
![Screen Shot 2019-04-21 at 7 31 42 PM](https://user-images.githubusercontent.com/80069/56476859-1e5a7100-646c-11e9-9d49-361addc6ac8f.png)

**Comment by lexelby** [comment]
Great analysis!  This is definitely one of the lurking problems that I've been struggling with.  It's one of the rough edges we need to sand down if we want more folks to take Ink/Stitch seriously.

A related problem to self-intersection is SVG paths with disjoint shapes. Of course we can detect this and break the subpaths up into separate shapes and fill them individually, but what order should Ink/Stitch stitch them in?  More about this [here](https://github.com/inkstitch/inkstitch/issues/360#issuecomment-442285840).

That's where I always get hung up.  And that's where your idea really shines:

> However, it could also be implemented as a menu item and allow users to add params to the (now separate) objects / paths.

We could just give the user an extension, "fix this shape".  It would remove any self-intersections and partition into separate paths if needed, and leave ambiguities like ordering in the hands of the user.  It's exactly in keeping with the direction we've been going with things like auto-satin.  Automate the bits that are hard for the user and free them up to exert artistic control where it matters.

**Comment by lexelby** [comment]
An interesting note about the hourglass: if you draw the right on and run Inkscape's "Union" operator on it, it will turn it onto the left one.  I wonder if Inkscape uses that simplepolygon algorithm.  I don't think Shapely can do this out of the box.

**Comment by Katee** [comment]
Huh, Inkscape handles both of these shapes. For the one on the right it immediately breaks apart with "Union". For the one on the left, "Union" + "Break Apart" is needed.

I haven't read it closely, however there is definitely some similar looking code in Inkscape `src/2geom/path-intersection.cpp`.

**Comment by Katee** [comment]
Also see `src/livarot/int-line.cpp` in Inkscape (look for "Booleen", a lot of that code is en Français).

Even after using "Union" a shape that was self intersecting will cause Ink/Stitch to return an error. Only after breaking it apart can it be filled correctly.

I think it is worth documenting how to solve the self-intersection error, perhaps a link to a page on the website when that error is encountered would save some frustration for users. Previously the solutions I have seen given are either to remove (#410), or rebuild the geometry (#374).

In the longer term, either using code like Inkscape's/simplepolygon/etc (or using Inkscape's code directly from Ink/Stitch) to fix this in a cleaner way might still be helpful.

**Comment by Katee** [comment]
Oh, here is the left and right shape again, except with non-sharp control points:
![Screen Shot 2019-04-21 at 9 38 42 PM](https://user-images.githubusercontent.com/80069/56480355-b74ab580-6487-11e9-9608-2372c963f6e1.png)

The left one includes two control points at the cross over (one for each direction of line that passes over).

**Comment by lexelby** [comment]
Oh, I didn't realize the one on the left was shaped like that, I thought it was two separate paths.

> or using Inkscape's code directly from Ink/Stitch

I was about to say that I didn't think this was possible, but it looks like it may be soon!  It looks to me like they're turning lib2geom into a standalone library with python bindings: https://gitlab.com/inkscape/lib2geom/tree/master/src/python

That could really open some doors for us if we can get it working.

**Comment by lexelby** [comment]
BTW, there's #323 as well.  I'm not sure if it makes more sense to do #323 first or just to go straight for an extension that can convert an invalid shape to multiple valid shapes.  I do think #323 would be relatively easy given Shapely's `explain_validity()`, though.

**Comment by kaalleen** [comment]
See #859 (automatically apply make_valid to fill shapes if not valid)

Troubleshoot extension and better fill shape handling already has been realized.
