### ISSUE TITLE
Strange Simulation Issue

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#445]
On Kubuntu 18.04 and using official releases of 1.22, 1.23, and 1.24, the thread simulation when going through Params doesn't show up.  No error msg is given on if something is wrong with the object in question.

When I try to run Simulate on it's own, I get this dialogue on all of those same versions mentioned above:

![Simulate Issue](https://user-images.githubusercontent.com/24878362/56536220-1e697800-6523-11e9-8b75-bc9afb61c30c.png)

Haven't don't any updates on machine between last time it worked and now.  Now, these all were fresh downloads as I was migrating to the latest release and then when the issue first appeared, I downloads the previous gen and then I tried the gen before that one when it didn't work as well.  Could something have happened within the repo itself?  Or am I totally loosing my mind?

**Comment by wwderw** [comment]
Ok, I did various other objects and they worked as expected on those versions, so it is definitely a "wrong shape" type of issue, but I'm not getting any error msg when applying from Params on those 3 versions, so either the error is something that doesn't have an error msg for or something happened with the display of error msgs.  I dunno.

**Comment by lexelby** [comment]
Ah, this is a bug!  This can happen when an object is set as a satin column in Params but it only has a single subpath.  It should print a useful error message rather than blowing up.

**Comment by kaalleen** [comment]
Ink/Stitch will print a useful error message, if a satin column only has one single subpath.
Closing the issue.
