### ISSUE TITLE
pes file

### ISSUE THREAD

**Issue by shancarter963** [inkstitch/inkstitch#449]
I have just discovered InkStitch, and I'm excited about the possibilities!  I've run into a few snags, though, and being a newbie, I'm not sure if I'm doing something wrong, or if I've encountered a bug.  

I have a Brother SE425, and I'm working with Inkscape 0.92.3 (2405546, 2018-03-11) on Windows 10, and InkStitch 1.24.0.  I can create a standard circle and convert it to PES format, and it shows up in my preview on my machine.  I tried converting a design, and it looks like it transfers, because it shows memory taken up, but there's no preview.  I have converted it to all one color, I have tried shrinking it, I have tried using DST format, and I'm still not getting what I expect.  (DST format shows a file name, rather than a preview, and says the design is larger than the embroidery hoop, even though I had it set to about 2.5" x 4".  PES format shows absolutely nothing on the machine except that memory is taken up.)  

Again, I am a newbie, so I may have missed a step, but it seems to do the simulation/conversion fine.

I started with the SVG file, converted to paths, converted everything to one color, and then I tried both Simulate and Embroider.  They seem to be pretty close to the same to me, not sure what the difference is, except that Embroider actually creates the file.  Is that right?  So I tried using Embroider (using the PES format), and I also tried using the "File", "Save As" menu to save it.  There's a difference of 60 bytes between the two files.

Once the file is created, I attach my machine and copy the file over to it.  The memory used number changes, but there's nothing in the preview window to select.  

The ZIP file attached contains the original SVG (already converted to paths) and the PES file it generates (when using the "Embroider" option).  

[backrub.zip](https://github.com/inkstitch/inkstitch/files/3129655/backrub.zip)

Can you please take a look at it and tell me if I'm missing a step?  Or if, perhaps, there's something wrong with my SVG file?  I created the design in Silhouette Studio 4.1, Business Edition, and saved it as SVG, so maybe there's something in their file format that is causing a problem?

**Comment by tyrosinase** [comment]
The Brother "4x4" hoop isn't really 4x4... IIRC it's slightly wider than 4", but slightly shorter than 4". It will load on my PE800, but only in the 5x7 hoop.

Turn your design 90 degrees and it should be fine, or make it a smidge smaller. 99mm x 99mm is usually safe.

I don't quite understand why the Brethren won't at least let you open it and scale it down in the machine, but here we are.

**Comment by shancarter963** [comment]
Actually, it *is* rotated... Did it not show up that way on your machine? Maybe I should play with basic rectangles first and see what my max measurements are, then straight text, then modify this again...

I would have thought 4” would be small enough on that long dimension, as the hoop measures pretty close to 5”, but I’ll try going a little smaller.  If 4” is considered the max, then there’s likely a buffer that I need to account for...  🤔

Thanks for the input.


Shan

Shannon Carter
512-922-8619<tel:512-922-8619> (m)

Sent from my iPhone... Please excuse any "creative" spelling or obvious autocorrect issues. 😇

On Apr 29, 2019, at 9:20 PM, Tyrosinase <notifications@github.com<mailto:notifications@github.com>> wrote:


The Brother "4x4" hoop isn't really 4x4... IIRC it's slightly wider than 4", but slightly shorter than 4". It will load on my PE800, but only in the 5x7 hoop.

Turn your design 90 degrees and it should be fine, or make it a smidge smaller. 99mm x 99mm is usually safe.

I don't quite understand why the Brethren won't at least let you open it and scale it down in the machine, but here we are.

**Comment by tyrosinase** [comment]
Counter-intuitively, the "long" dimension of the embroider-able area is the short dimension of the physical hoop.

**Comment by shancarter963** [comment]
You were right.  I should not have rotated it.  I put it back to a landscape view, and then shrunk it to 3.9” and it now shows up.  Thanks for your help.

Shan

Shannon Carter
sscarter.shan@live.com<mailto:sscarter.shan@live.com>
(512) 922-8619 (m)
