### ISSUE TITLE
Satin Column: NetworkXUnfeasible

### ISSUE THREAD

**Issue by chrisond** [inkstitch/inkstitch#452]
Hello inkStitching-Community!

I am new  as well in digitizing as in stitching itself.
Great tool! But I still feel forced to report a problem after facing it over and over again.

- the path is made out of a stroke with corners
- path directions are aligned
- it s a geometric form (icosahedron basicly)
- I have simplified, rectified and united the path (and tried without these options before 
resulting in the same error message)
- I used satin tools\automatic satin column (or something similar)...

...the machine let's us know: 

Traceback (most recent call last):
  File "inkstitch.py", line 54, in <module>
    stderr = stderr.strip()
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/auto_satin.py", line 51, in effect
  File "lib/extensions/auto_satin.py", line 81, in auto_satin
  File "lib/stitches/auto_satin.py", line 306, in auto_satin
  File "lib/stitches/auto_satin.py", line 437, in add_jumps
  File "site-packages/networkx/algorithms/connectivity/edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

Hmmm...
I am working on MacOS High Sierra 10.13.6 (17G6030).

Cheers

chrisond

**Comment by chrisond** [comment]
Sorry, I forgot screenshot looks like this:
![Bildschirmfoto 2019-05-02 um 18 55 28](https://user-images.githubusercontent.com/50116536/57092580-fbea1280-6d0b-11e9-9f9f-e3798505d51b.png)

**Comment by tyrosinase** [comment]
Break it into separate paths, then re-combine matched pair paths. Otherwise Inkstitch won't know which paths to pair up.

You'll also need to reverse some more of the sub-paths; that triangle in the left side is mismatched, for instance.

**Comment by chrisond** [comment]
Whoops, fast reply, 

thanx, I ll try out!

**Comment by chrisond** [comment]
Ok, done. Broke and recombined as you can see in the screenshot and additionally I fixed non-aligned paths:

![Bildschirmfoto 2019-05-02 um 23 22 58](https://user-images.githubusercontent.com/50116536/57108138-29e24d80-6d32-11e9-83f3-3dc0e68d4fbc.png)

Than, after hitting Auto-Satin-Function,  I get the same error message again (see above) :(

**Comment by chrisond** [comment]
Should I open the matching lines? Each path is closed at the moment. And somewhere in the tutorials an end and a beginning is demanded. Rungs? What do you think, tyrosinase?

**Comment by jameskolme** [comment]
Yes, open paths, if still errors, try only one shape. This should work without rungs, equal number of nodes is present.

**Comment by tyrosinase** [comment]
Yep, sometimes it works with closed paths (provided the start and end nodes happen to line up internally) but even in that case I always open the paths just to keep it from breaking down the line.

I have also learned that sometimes Inkscape decides to randomly break nodes (usually when doing inset/outset work) in the middle of a path, so if a Satin function throws an error I select the path and look for an odd number of nodes.

**Comment by kaalleen** [comment]
Welcome @crisond to the project. Thank you for posting your issue here. It is always good to know about messages with a traceback when they occur in Ink/Stitch - because they actually shouldn't.

The problem you are having here is, that you are trying to run the auto-route satin tool on a non-satin column path. The path in the image you were posting is surrounding a shape wwith a fill color, which will indicate to Ink/Stitch, that you want to use a fill stitch.

What you need for the auto-route satin tool to work is a satin stitch. Which means that you need two "rungs" - not with "füllung" applied to it, but use a "kontur". With an easy design like this, it might even be easier to just redraw the shapes. Lock your underlaying image (the original) and use the bezier curve tool to redraw the shapes. In the tab "Muster der Kontur" you can enlarge the stroke width. Now choose the satin tool "Konvertierung Linie zu Satinstich". This will automatically convert your stroke into a satin column. Once you have converted everything into a satin column you are able to use the auto-route satin tool. But for your design you might also consider to sort your satin columns carefully in the object panel. Because it really matters which column comes first and which one will be the last to be stitch out. The auto-route satin tool also has the option to keep the order that you've set before.

As an inspiration you could use this quick catch of your pattern:

Redraw:
![redraw](https://user-images.githubusercontent.com/36401965/57162843-bd2d8880-6def-11e9-9284-907e1759b318.png)

Convert line to satin:
![redraw01](https://user-images.githubusercontent.com/36401965/57162849-c3236980-6def-11e9-87b8-5c05a5db02f4.png)

Then you only need to fix the order of the columns.

I hope this could clear things up a little.

**Comment by chrisond** [comment]
People,

thank you so much for your answers, general hints and feedback!
Cool place to be. Yes, next week I will follow kaalleens detailed instructions and 
punch through my first stitch.
I will close this issue now.

**Comment by lexelby** [comment]
Awesome discussion here, thanks all :)

I'm glad you've got your answer, but I'm going to reopen this.  As @kaalleen says, you should never see a traceback, so this is an inkstitch bug.

**Comment by chrisond** [comment]
Hi everybody...
back in town and stuck again...arrrgh...
Today I followed kaalleen's instructions (see above) and manually shaped the icosahedron.
![Bildschirmfoto 2019-05-13 um 22 10 02](https://user-images.githubusercontent.com/50116536/57651783-6cc3e100-75ce-11e9-8f9b-b362d92d00c9.png)

You can bet, I checked it more then once before dropping it here and path direction, intersections and so on are okay. Still no output.
So I decided to play with less complex (or redundant) shapes, shapes - I supposed - that are difficult to fail with...

![Bildschirmfoto 2019-05-13 um 22 19 46](https://user-images.githubusercontent.com/50116536/57652117-2b800100-75cf-11e9-8722-26b0d853d288.png)

far wrong...
so good decision by lexelby to reopen this issue!

**Comment by jameskolme** [comment]
Would you share this simple shape to investigate?

**Comment by chrisond** [comment]
Pleasure,
but stupidly I deleted yesterdays version of the A-shape. The same bug occurrs 
with this new version:

[test_A.svg.zip](https://github.com/inkstitch/inkstitch/files/3177278/test_A.svg.zip)

For readability the errpr message again:

Traceback (most recent call last):
  File "inkstitch.py", line 54, in <module>
    stderr = stderr.strip()
  File "inkscape/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/simulate.py", line 17, in effect
  File "lib/extensions/base.py", line 181, in elements_to_patches
  File "lib/elements/element.py", line 268, in embroider
  File "lib/elements/satin_column.py", line 780, in to_patches
  File "lib/elements/satin_column.py", line 683, in do_contour_underlay
  File "lib/elements/satin_column.py", line 599, in plot_points_on_rails
  File "lib/elements/satin_column.py", line 561, in calculate_spacings
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/satin_column.py", line 291, in flattened_sections
  File "lib/elements/element.py", line 286, in fatal
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

As you can see,the message is exactly the same, whereas the shape is just similar.
I did the A with Bezier and the rungs with the pencil-tool (even if I don't think it matters). One Layer on a 30-mm-square-document. Path-directions are aligned, I added rungs temporarily (in the old version) without effect. You can see my computer system information in the first comment of this issue. Inkscape (mediated by something called X11) works in general (in other cases). Didn't change any Inkscape-settings apart the once recommended in inkstitch-tuts. Hmmm, guess that's it. If you need further infos, don't hesitate.
Thanks for your interest!!!!

**Comment by jameskolme** [comment]
Current version what I use for this is inkstitch-v1.25.0-win32-en_US

I get this error message: path1389: error: satin column: One or more of the rungs doesn't intersect both rails.  Each rail should intersect both rungs once.

So what was wrong, all lines are under same path, if that makes any sense? Inkstitch is probably confused by several lines without proper intersection. Just compare my fixed file, it should be obvious what was wrong. One satin lines with rungs should be combined, if there are many satins in this combined group, Inkstitch will fail to understand. What is wrong is error message. 

[test_A_fix.zip](https://github.com/inkstitch/inkstitch/files/3177368/test_A_fix.zip)

**Comment by jameskolme** [comment]
How to fix this is quite simple:
select all and under **path/break apart**
Now select only ingredients for one satin with rungs and **path/combine** 
It would be recommended to test result after one, just to make sure everything is good to go.
repeat path/combine for every satin lines.

**Comment by chrisond** [comment]
Ok, means just combine the rungs and satin lines of each,hmm, "rail", instead of combining rails.
Yeah, jameskolme, works...I will go back to the basic tutorials .)

Thanks!!!

**Comment by kaalleen** [comment]
The posted files gives a proper error message by now.
I will close the issue. Please reopen if the error shows up again.
