### ISSUE TITLE
Live Links in Print-PDF

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#454]
Since everything is bundled in to the extension and it doesn't matter the system web browser, is there anyway to be able to keep links live in the print-pdf function?

Without have to bundle something that sends it off to a cloud service to convert and sends back (there are quite a few things that I have NDAs attached to and this would be no bueno in a lot of respects, but I can't have that configured at all)

If not, well, I'm used to Firefox not being able to.

**Comment by lexelby** [comment]
Darn, I guess that's a casualty of switching to electron. :(

I'll see what we can do.  One option might be to have an option to open in an external browser so you can continue to use Firefox.

**Comment by wwderw** [comment]
Oh no, Firefox doesn't do it, that's what I was saying, I'm already used to it, I just thought I would see since it won't matter about the system browser anymore.

No worries if it can't be.  I would just leave well enough alone unless someone else wants that functionality of using an external browser.

**Comment by kaalleen** [comment]
Links will stay alive within the electron pdf output. No external services needed... if that was the question you were asking.

**Comment by wwderw** [comment]
It's not so much within the electron portion, it's when exporting to the actual PDF that the links are dead.

**Comment by lexelby** [comment]
Are you sure?  @kaalleen seems to be right, as far as I can tell.  Or at least, the "Ink/Stitch" link in the default footer works.

**Comment by wwderw** [comment]
Nope.  When I do Save PDF and I open the resulting PDF, links are dead.  Or at least Okular doesn't read them as live.

I can't get Print to actually do anything to try a Print to PDF option there, so the only open that I have is Save PDF.

**Comment by lexelby** [comment]
This is so weird.  It totally works for me in okular.  What version of okular are you using?

Can you post an example PDF that doesn't work?  Could just be a simple running stitch if need be.

**Comment by wwderw** [comment]
[Okular Live Links.zip](https://github.com/inkstitch/inkstitch/files/3146127/Okular.Live.Links.zip)

Attached includes a video screen capture of what version I'm running of Okular (using Kubuntu 18.04 although I do have 2 computers running Neon, they may have a newer version if it's that) and my attempt to use the links.

Plus the PDF itself.

**Comment by lexelby** [comment]
Wow, I honestly don't know what's going on here.  That very PDF's links work fine for me in that exact version of Okular (1.3.3).  When I run my mouse over them, I get a pointer-finger mouse cursor, and when I click a link, it opens it in Konqueror.

I see in your video that it doesn't even show you the pointer-finger mouse cursor.  Have you tried clicking a link even though you don't get the mouse cursor?

What happens if you try a different PDF viewer?

**Comment by wwderw** [comment]
I was clicking the links in Okular.  That video doesn't have sound, that's why it doesn't come across as such.

Opened it up in Acrobat Pro in my Win VM and it worked.

What DE are you running?  I have to wonder if it's because I used a minimal install of Kubuntu 18.04 that it didn't do some utility that stripped away the ability for Okular to use links.  In the morning when back at the shop, if I remember, I may try it in KDE Neon and see if it works there.  No minimal install option, but it does depend on if they installed whatever utility is missing (if that's what the cause is).

**Comment by wwderw** [comment]
I feel so stupid.

It is determined by what you have selected up in the tool bar among these options: "Browse", "Zoom", and "Selection".

"Browse" and "Selection" both will work on the links, however, "Zoom" will not.

Guess which one this dummy had it on when trying all this?

Since I do nothing but view with Okular, I never had a reason to even look at what was select as I've always gotten the behavior that I otherwise wanted.

All is right in my little world now.

Thanks!

I have to wonder if this was my problem when we were using system browsers versus the bundled one.

**Comment by lexelby** [comment]
You only get to feel stupid if you think _I'm_ stupid too. ;)  I actually suspected this was a "[mode error](http://www.usabilityfirst.com/glossary/mode-error/)", and I even _looked_ for the mode switch button and couldn't find it.

I don't want Ink/Stitch to make users feel stupid like that.  It's really hard to design software that doesn't, but it's so worth it.  We have a long way to go, but at least we're working at it :)
