### ISSUE TITLE
issue with inkstitch

### ISSUE THREAD

**Issue by praveen9i** [inkstitch/inkstitch#455]

**Comment by praveen9i** [comment]
Simulate is not working nor any of the options is not working - below is the error report

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path14', '--id=path12', '--extension=simulate', 'C:\\Users\\prave\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgRPM20Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by lexelby** [comment]
Hi!  Thanks for trying Ink/Stitch.

Most often, this error message means that something went wrong during the installation process.  Here's a video showing how to install on Windows: https://www.youtube.com/watch?v=U5htzWZSjA8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=4

If that doesn't help, reply back and we'll help troubleshoot further.

**Comment by kaalleen** [comment]
This is most probably an antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.
