### ISSUE TITLE
verbose error message:  use Path -> Object to Path to convert

### ISSUE THREAD

**Issue by JensKorte** [inkstitch/inkstitch#457]
It would be kind, if you add "select object and" after Tip: to the error message:

No embroiderable paths selected.
Tip: use Path -> Object to Path to convert non-paths before embroidering.

I am new to inkscape and made the mistake to not select the object.

**Comment by lexelby** [comment]
Awesome idea, thanks!

**Comment by JensKorte** [comment]
>  It can't work with objects like text, rectangles, or circles.

I used a png to have an object that doesn't work. Maybe "picture, " can be added, but your explanation is helpful.
