### ISSUE TITLE
better error message needed for objects with unconnected fills

### ISSUE THREAD

**Issue by Zino007** [inkstitch/inkstitch#463]
I tried to enter some text or insert image, change everything to curves but when I try to generate jef embroidery file, program says this error message. Exactly (or near) this coordinates, there is no image, curve or stitch...:(

path34: error: shape is not valid.  This can happen if the border crosses over itself.

shapely.geos - INFO - Hole lies outside shell at or near point 510.2733628248601 243.16541830829613

any help with this.? I am new one in this program and I need (would like to) make embroidery file with jef extension with some text or image in it... thanks for any advice. J.

**Comment by jameskolme** [comment]
`program says this error message. Exactly (or near) this coordinates, there is no image, curve or stitch...:(`
I think location is given using pixels and if template uses different measurement system, coordinates are just random numbers. Not tested this, but I use millimeters and error coordinates point to location that is nothing to do with any errors, most likely blank space. Would this be possible? @lexelby 

`shape is not valid. This can happen if the border crosses over itself.`
This is the problem, line crossing is happening somewhere. You can select smaller pieces and simulate to pinpoint places that do work and fix the problem.

**Comment by lexelby** [comment]
Hi @Zino007, thanks for trying Ink/Stitch!  This is an area of Ink/Stitch that we are actively improving.  In fact, in #465, the wonderful @kaalleen is adding an extension that will tell you exactly what part of your shape is causing the "shape is not valid" error.

It's a work in progress, but you can try it now if you'd like.  Here's where you can download it: https://github.com/inkstitch/inkstitch/releases

Install and restart Inkscape, and you'll get a new "Explain Validity" menu item in Ink/Stitch.

The "Hole lies outside shell" error can happen if you have a shape in your SVG that has two separate unconnected areas, for example a letter "i".  Try selecting it and doing "Path -> Break Apart".

I hope that helps. We clearly need better error messages.
