### ISSUE TITLE
Tried to launch: inkstitch\bin\inkstitch

### ISSUE THREAD

**Issue by cmarendish** [inkstitch/inkstitch#464]
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path815', '--id=path817', '--extension=simulate', 'C:\\Users\\chris\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgVWN21Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by jameskolme** [comment]
Have you extracted all files and subfolders to this folder? 
C:\Users\chris\AppData\Roaming\inkscape\extensions
If yes, I don´t have any idea what can cause this :/

**Comment by lexelby** [comment]
Hi! Thanks for trying Ink/Stitch.

Most often, this error message means that something went wrong during the installation process. Here's a video showing how to install on Windows: https://youtube.com/watch?v=U5htzWZSjA8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=4

If that doesn't help, reply back and we'll help troubleshoot further.

**Comment by kaalleen** [comment]
This is most probably an antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.
