### ISSUE TITLE
Converting satin column back to running stitch worked only halfway

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#466]
I have a mutant hybrid path. It was a satin column that I decided to convert to a bean outline when stitching a smaller version. As best I can remember: I converted the line to dashes, joined the two top nodes so it was a single path, and that was it. Went in to Params and the checkbox was unchecked and everything was grayed out. Checked the box, changed bean to 1, and the preview renders fine. Apply and leave, try to embroider or simulate and it throws an error (an unpretty one, I'm a version behind). Go back to Params and the checkbox is unchecked again, everything is grayed out. Looked at the XML, and I can guess why (though not how it got this way):

`    <path
       embroider_bean_stitch_repeats="1"
       id="path365"
       style="display:inline;opacity:1;vector-effect:none;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:#00ff00;stroke-width:0.25400001;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:0.25400001, 0.25400001;stroke-dashoffset:0;stroke-opacity:1"
       d="m 133.495,281.67564 1.12725,-4.00942 -1.1977,-6.05445 1.62042,-5.32399 -1.62042,-7.79881 1.40906,-6.31069 -1.40906,-7.94547 1.40906,-4.12701 -1.40906,-6.49052 1.33861,-2.32246 -1.41586,-2.60809 -1.41586,2.60715 1.33861,2.32246 -1.40906,6.49053 1.40906,4.12701 -1.40906,7.94547 1.40906,6.31069 -1.62042,7.79882 1.62042,5.32399 -1.1977,6.05444 1.12724,4.00941"
       inkscape:connector-curvature="0"
       embroider_satin_column="True"
       embroider_contour_underlay="True"
       sodipodi:nodetypes="ccccccccccccccccccccc" />`

An older sibling of that file with the path still in satin looks like

`      <path
         id="path7553-2"
         style="display:inline;opacity:1;vector-effect:none;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:#00ff00;stroke-width:0.2942383px;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1"
         d="m 50.607777,280.27694 -1.44065,-5.12414 1.53069,-7.73774 -2.07093,-6.80421 2.07093,-9.96711 -1.80081,-8.06523 1.80081,-10.15454 -1.80081,-5.27443 1.80081,-8.29508 -1.71077,-2.96816 1.71077,-3.33261 m 0.2875,67.72445 1.44066,-5.12415 -1.5307,-7.73775 2.07094,-6.80421 -2.07094,-9.9671 1.80082,-8.06523 -1.80082,-10.15454 1.80082,-5.27443 -1.80082,-8.29507 1.71078,-2.96816 -1.71078,-3.33261"
         inkscape:connector-curvature="0"
         embroider_satin_column="True"
         embroider_contour_underlay="True"
         sodipodi:nodetypes="cccccccccccccccccccccc" />`

if that helps.

**Comment by tyrosinase** [comment]
I want you to know I resisted the temptation to title this "Feature request: satinbean stitch." Mostly because I dunno what I would want/expect that to look like. :laughing:

**Comment by lexelby** [comment]
Thank you!  I know I've seen this before but I couldn't quite pinpoint what was going wrong.  Your description should point me in the right direction.
