### ISSUE TITLE
UnicodeDecodeError in lib/elements/element.py

### ISSUE THREAD

**Issue by matn2** [inkstitch/inkstitch#467]
path1065: Fehler: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 200, in to_patches
  File "lib/elements/auto_fill.py", line 161, in fill_shape
  File "lib/elements/auto_fill.py", line 153, in shrink_or_grow_shape
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/fill.py", line 137, in shape
  File "lib/elements/element.py", line 286, in fatal
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)

shapely.geos - INFO - Hole lies outside shell at or near point 328.9375342319467 538.94927608749674

**Comment by kaalleen** [comment]
Welcome to the project @matn2 and thank you for reporting this error back to us. It is always good to know, when a traceback is shown to the user.

The error occurring to you is actually an encoding issue within an error message. I am assuming that you are using a language other than English. This error should not appear and we need to fix it.

Here is what you can do to fix the actual problem you are having. It seems as if you have a combined shape with non-connecting parts. Hit "Ctrl+Shift+K" to split up your object. If you have holes which should stay, select the outer and the inner shape and recombine with "Ctrl+K".

**Comment by stoffsuchti** [comment]
Ah this could be the explanation for the problem that i faced today, when intried Inkstitch

**Comment by lexelby** [comment]
I ♥⃑ unicode.  Clearly Ink/Stitch does not. ;)  Thanks for reporting this bug!  We really appreciate it.

**Comment by kaalleen** [comment]
This issue is still present when we merge pr #481

The path name from the error message was "path1065" (didn't contain any umlauts) and could be displayed. A possible cause could be the translated string, which has umlauts. Which would mean the error lies somewhere in the i18n part. What do you think?

**Comment by lexelby** [comment]
Ah, I bet you're right.  `_()` returns a Unicode string, and it looks like Ink/Stitch isn't handling it right afterward.

**Comment by kaalleen** [comment]
The latest addition to the above mentioned pull request is supposed to solve this issue.
I've read that python 3 handles this encoding stuff better, so we won't have to deal with it anymore after a python version update.
