### ISSUE TITLE
Tiny fill shape causes exception: LineString is not iterable

### ISSUE THREAD

**Issue by pneumaticdeath** [inkstitch/inkstitch#471]
path1020-8: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 210, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 231, in build_travel_graph
  File "lib/stitches/auto_fill.py", line 274, in process_travel_edges
TypeError: 'LineString' object is not iterable****

**Comment by pneumaticdeath** [comment]
I've discovered that if I just expand the size of the SVG it simulates fine, but then it's too big for my design.

**Comment by pneumaticdeath** [comment]
[Logo_draw5.svg.gz](https://github.com/inkstitch/inkstitch/files/3247296/Logo_draw5.svg.gz)

this is the file, gzipped.

**Comment by jameskolme** [comment]
Yest it is first phone button, with the problem, it is quite small for fill. Surprisingly every other button does work. I would recommend to use satin stitch for small shapes. 

Not that many stitches at all. 
![tinyfill](https://user-images.githubusercontent.com/44113605/58799529-32b68f80-860e-11e9-842c-275e4d50d522.png)

**Comment by lexelby** [comment]
@pneumaticdeath What version of Ink/Stitch did you have installed when you got the above traceback?

**Comment by lexelby** [comment]
Never mind, I was able to reproduce the bug and fix it.
