### ISSUE TITLE
10362 error

### ISSUE THREAD

**Issue by ewilmar** [inkstitch/inkstitch#475]
hi, I'm pretty new to anything code related, giving things a google I think the problem may have to do with pythons?? (who would have thought it would been snakes)
I've been doing freehand lines that i simplify to the point that they really shouldnt be a problem. When I run a command through the inkstitch extension to 'convert line to satin'. I get this message:[10362] Error loading Python lib '/Users/emilewilmar/.config/inkscape/extensions/inkstitch/bin/.Python': dlopen: dlopen(/Users/..../.config/inkscape/extensions/inkstitch/bin/.Python, 10): Symbol not found: _getentropy
  Referenced from: /Users/..../.config/inkscape/extensions/inkstitch/bin/.Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/..../.config/inkscape/extensions/inkstitch/bin/.Python

**Comment by kaalleen** [comment]
Welcome to the project @ewilmar !
Sorry you are having troubles with Ink/Stitch.

May I ask if any other function is working and which macOS version you are using?

**Comment by ewilmar** [comment]
the main functions of inkscape work great through xquartz
xquartz11? whatever the latest is
inkstitch-v1.24.0-osx-x86_64-en_US
Inkscape-0.92.2-1-x11-10.7-x86_64
![Screen Shot 2019-06-13 at 2 00 30 PM](https://user-images.githubusercontent.com/51741774/59398936-2dafc800-8de6-11e9-9406-a4c1eacd78cf.png)

**Comment by ewilmar** [comment]
however no other functions of inkstitch seem to work

**Comment by ewilmar** [comment]
the main functions of inkscape work great through xquartz
inkstitch-v1.24.0-osx-x86_64-en_US
Inkscape-0.92.2-1-x11-10.7-x86_64Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch/bin/inkstitch
Arguments: ['inkstitch/bin/inkstitch', '--id=path3803', '--extension=params', '/var/folders/j0/6xcg23vx5vj90y67dh189vq80000gn/T/ink_ext_XXXXXX.svg8AZN3Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
this was just in opening the parameters for inkstitch on one of the lines

**Comment by kaalleen** [comment]
Hm, this is bad news. Ink/Stitch for macOS currently works only with High Sierra (10.13) and higher. Your version is 10.11 and is not supported. Sorry for that!

**Comment by ALPHAMOTIF** [comment]
Update to something a bit newer it will solve the issue, I had the same running on El Capitan
