### ISSUE TITLE
Unknown unit: %

### ISSUE THREAD

**Issue by bkolb** [inkstitch/inkstitch#476]
I have a pretty simple svg file containing 2 path elements forming a cloud.

If I try to set parameters on any of the objects I do not see any preview.
If I try to simulate I am getting the following error message:

```
Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 200, in to_patches
  File "lib\elements\auto_fill.py", line 161, in fill_shape
  File "lib\elements\auto_fill.py", line 153, in shrink_or_grow_shape
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "lib\elements\fill.py", line 108, in shape
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "lib\elements\fill.py", line 102, in paths
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "lib\elements\element.py", line 208, in parse_path
  File "lib\svg\path.py", line 9, in apply_transforms
  File "lib\svg\path.py", line 40, in get_node_transform
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "lib\svg\units.py", line 109, in get_viewbox_transform
  File "site-packages\backports\functools_lru_cache.py", line 113, in wrapper
  File "lib\svg\units.py", line 100, in get_doc_size
  File "lib\svg\units.py", line 78, in convert_length
ValueError: Unknown unit: %
```

I am using inkscape 0.92.4 as well as inkstitch 1.25.0. The OS is Win10_64

I attached the svg file and renamed it to `.log` so github accepts it.
[cloud.svg.log](https://github.com/inkstitch/inkstitch/files/3290498/cloud.svg.log)

**Comment by jameskolme** [comment]
I have to say this little shape is interesting, unfortunately I can´t figure out what is wrong. Everything seems to be where it should and still not working.

**Comment by bkolb** [comment]
I have the same issue, even if I delete any of the two paths...

**Comment by kaalleen** [comment]
Open a new documenta and copy the cloud into there. It should work then.

The problem is, that in  there is no unit defined (such as mm vor px) and Ink/Stitch cannot figure out the real size of it. Maybe it should just assume something?!? But in this case it would result into a very small shape, which wouldn't work nicely neither.

You should also consider to use a satin column instead of the outline around the cloud (zig-zag-stitch). It would give you a much better result.

**Comment by tyrosinase** [comment]
If you go into Document Properties the problem really is the units: Inkscape doesn't have a % unit for the SVG itself. I edited the file with Leafpad and replaced the % with mm and it opened happily (although then it decided the color designations didn't work and I had to fix those).

What created the shape? Not Inkscape, I assume.

**Comment by bkolb** [comment]
Thank you for your suggestions. I will check again. 
Indeed, I was using Affinity Designer on my Mac to create the SVG and then opened it in Inkscape/stitch. 

I first tried to use the inkscape bitmap tracing feature on the original cloud png. But the result was really bad (from an svg perspective) As I am more familiar with the Affinity Designer I continued there.

Nevertheless, It would be great if a proper error message could be added hinting at the problem. At least on your website here: https://inkstitch.org/docs/error-messages/

**Comment by lexelby** [comment]
Hi @bkolb, welcome and thanks for trying out Ink/Stitch!  I'm sorry you're having difficulty.

It looks like your SVG is technically valid (per the SVG spec) but it's not set up in a way that Ink/Stitch is designed to handle.  As @kaalleen pointed out, the `<svg>` tag has its `width` and `height` attributes set to `100%`.  I really don't understand what that's supposed to mean... 100% of what?  I'm guessing this is probably valid but I can't find any documentation on what it means.

I'm guessing 100% means "normal size".  By default (or maybe by common convention?), SVGs are interpreted as being 96 pixels per inch.  If I set the `width` to `1179` and the `height` to `750` (taken from the `viewBox`), then Ink/Stitch can handle your SVG just fine.

Ink/Stitch uses SVGs, but it's really only intended to work with the SVGs that Inkscape produces.  We don't intend for our users to work in another SVG editor like Affinity, and unfortunately errors like this can make it difficult.  I'm sorry, I know that it can be hard to leave behind your proficiency with Affinity and learn Inkscape!

I do want us to fix things like this when we can.  In this case, I think I can make Ink/Stitch do something intelligent when faced with "100%" for a width or height.  We don't like anyone to see a traceback under any circumstances.
