### ISSUE TITLE
Empty Ink/Stitch menu

### ISSUE THREAD

**Issue by caseysucks** [inkstitch/inkstitch#479]
I just downloaded both and nothing else is showing up besides these two options. I've tried to redownload, restart my computer and extract it multiple times and nothing has changed. When I tried extracting it to C:\Program Files\Inkscape\share\extensions I got a tiny bit further but once again still not working. Photo below is what shows up when I mouse over it showing just that small little grey rectangle next to it but nothing else. Pls help :o
![image](https://user-images.githubusercontent.com/51941288/59654088-7e5a5480-9149-11e9-96c9-58195848e8f6.png)

**Comment by kaalleen** [comment]
Huh, have you solved your issue by now?

**Comment by kaalleen** [comment]
No answer for a long time. I am going to close the issue. For people who find the issue later, it probably happens, when you have downloaded the wrong version of Ink/Stitch. Make sure, the version  you download fits to your operating system. On our website you can find all the links you need: https://inkstitch.org/docs/install/#quick-setup
