### ISSUE TITLE
enable fill underlay by default 

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#480]
It's rare that one would want to disable fill underlay.  We should enable it by default to save time and to provide a good recommended setting for beginners.

related to #453

**Comment by kaalleen** [comment]
Is this still the plan? If yes... Will we simply change the default or will we somehow try to keep old files as is (it could otherwise break files where underlay wasn't planed in the first place)?

**Comment by lexelby** [comment]
Very good questions.  I'm wary of breaking existing designs...

It seems like you have the right concerns in mind.  I trust you to come up with a good plan for this.

Sorry I haven't been around much lately.  I've been spending almost all of my available time sewing face masks on my machine for medical workers.  It may be awhile before I'm back, but I'm keeping an eye on what you're up to :)

**Comment by kaalleen** [comment]
Ok, I will think of something. Let's just not break existing designs ;)

Oh, masks. At work I have sewn more than 200 masks in the last few weeks. We are really in need of those at the moment. But doing so at work, I really didn't want to spend my free time with it as well ;) I am an occupational therapist, working with drug addicted people. We are not really in focus of people who are wanting to help. So we rather started our own mask projects.

**Comment by lexelby** [comment]
Oh wow, what a cool job!  And really important work.  I work for fastly.com, and while my code builds, I lean over and put a mask on the embroidery machine to sew.  That just leaves all the prep work for my evenings ;)
