### ISSUE TITLE
What's the state of play on Inkstitch on ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#483]
https://opensource.com/article/19/6/raspberry-pi-4

Pi 4 snuck up on me, but once it hits my friendly local Micro Center I am thinking I could replace my (nine-year-old) desktop machine with a Pi... except last I checked, Inkstitch didn't [easily] run on ARM. I'm thinking it was one of the dependencies, and I vaguely remember giving up on it when I hit the point where I needed to manually compile something and read the line "this took 48 hours on a 3B+."

Anybody messed around with doing this more recently?

**Comment by lexelby** [comment]
I don't think we're likely to support arm, if only because GitHub Actions doesn't have an arm option.  Sorry!

**Comment by tyrosinase** [comment]
Forgot I had this open but I am about 80% sure I got it to compile successfully (albeit slowly) via the manual process at some point. I should try it again with the current version because a tiny evil part of me want to install it on the one that emulates a USB to make my machine wireless, just so I can send bitmaps to it and have it auto-digitize them.
