### ISSUE TITLE
Convert a line into a satin column (maybe with a specified thickness)

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#49]
On selected object:

Step | inkscape verb | Action
------------ | ------------- | -------------
01 | ObjectToPath | Convert selected object to path (Shift+Ctrl+C)
02 | DialogFillStroke | Edit objects' colors, gradients, arrowheads, ... (Shift+Ctrl+F)
03 | | Fill=0 / Stroke = 20/25 pixel)
04 | StrokeToPath | Convert selected object's stroke to paths (Ctrl+Alt+C)
05 | DialogFillStroke | Edit objects' colors, gradients, arrowheads, ... (Shift+Ctrl+F)
06 | | Fill=0 / Stroke = 1 pixel)
07 | ToolNode | Edit paths by nodes (F2)
08 | EditSelectNext | Select next object or node (Tab)
09 | SelectionReverse | Reverse the direction of selected paths (useful for flipping markers)
10 | SelectionBreakApart | Break selected paths into subpaths (Shift+Ctrl+K) we are already on first node (step 08)
11 | SelectionBreakApart | Break selected paths into subpaths (Shift+Ctrl+K) first & last (opposite of first node ?)

Step 03 + 06:
I don't know if there a possibility to passing parameters into DialogFillStroke
Step 11:
We have to find out the opposite node (starting from the first), select booth and do a SelectionBreakApart

Edit: Even i don't know if all verbs available in extensions / phython scripts
Edit2: with inkscape devel builds replace StrokeToPath -> StrokeToPathLegacy

**Comment by lexelby** [comment]
....What?  What is it that you're trying to do here?  What are verbs, and how does one use them to automate inkscape?

**Comment by AkiraNorthstar** [comment]
I'm sorry, i should have wrote with more details.
Inkscape have command line actions, they called verbs.
Not all functions (GUI) are accessible via command line.
Start a terminal and type: inkscape --verb-list
for getting all command line functions.
That was not my question or hint. Is it possible to implement the above mentioned functions via a python / script?
I hope that it is now clearer what I wanted to write.
Sorry again for the incomprehensible above!

**Comment by lexelby** [comment]
Oh, I see now.  Well, the tricky thing here is that the extension would actually be running a separate copy of inkscape to execute the verbs.  The extension can't do things to the existing running copy of inkscape.

In effect, verbs let the extension use inkscape as a command-line SVG processor.  But the stuff you've described above actually may be easier to just do in Python, so there's no need to execute inkscape verbs.

What is your ultimate goal?  It sounds like you want to convert a single line into a satin column of a specified width?  That sounds like a nice time-saver and it would be useful for new folks to see how to make a satin column.  Of course, satin columns can be more complex than that and can have varying width, but at least this would give the user a good base to start from.

Can we change this into a feature request for what you're actually looking for?  Something like "add an extension to convert a line into a satin column with a specified thickness".  Then we can leave the implementation details to whoever takes on this task.

**Comment by lexelby** [comment]
> Is it possible to implement the above mentioned functions without using the command line via python?

Oh sorry, I didn't actually answer your question.  Yes, this kind of thing is possible in Python without using verbs :)

**Comment by AkiraNorthstar** [comment]
My fault, i edit the text two times... 
Yes, we can change it to a feature request.
