### ISSUE TITLE
You guys, I freakin' *love* Ink/Stitch.

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#490]
It lets me do such RIDICULOUS things with my li'l sewing robot. 

![IMG2724Crop](https://user-images.githubusercontent.com/9473609/61016494-c8f07a80-a35d-11e9-9ba5-aeaf388703f3.png)

**Comment by lexelby** [comment]
Wow!!!

**Comment by ndrwclrk** [comment]
Amazing!

**Comment by DreadKnight** [comment]
Awesome!
