### ISSUE TITLE
Husqvarna teardown

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#491]
Someone, knowing I have a Designer 1+ that I have been tempted to kitbash into something that works without the crazy parallel-port-dongle-based proprietary card system, sent me a link to this: https://www.element14.com/community/docs/DOC-92888/l/the-eiectronics-inside-04-retro-computerized-sewing-machine-teardown

It's a non-embroidery Viking of the same vintage as mine, looks to be built on the exact same frame. He doesn't go into a *lot* of detail on the electronics, but it's an interesting overview.

**Comment by ndrwclrk** [comment]
I LOVED that video!  I'm going to watch a whole bunch more on that channel.  Thanks for introducing it to me.
