### ISSUE TITLE
InkStitch Add Ons

### ISSUE THREAD

**Issue by Blindsay0917** [inkstitch/inkstitch#492]
I installed the add ons as instructed on the tutorial, but the color palette isn't working; it isn't showing up at all.

**Comment by kaalleen** [comment]
Hey there, I don't know what went wrong., but I got a few questions to find out the reason of your issue:
* Which operation system are you using?
* Did you restart Inkscape after installing the addons?

If you had a restart and the additional color palettes still don't show up, you could also install the palettes manually (it still would be interesting for us, why the installation didn't work out for you - so consider this to be only a workaround so you can actually use the color palettes).

Within the files you copied to the Inkscape extensions folder you find a folder named `inkstitch` which contains several folders again. Copy the content of the `palettes` folder and paste it into the palettes folder of your inkscape installation (which is a sibling of the extensions folder).

I hope this description is understandable?!? Don't hesitate to ask further questions if it's not.

**Comment by kaalleen** [comment]
No answer for a long time. Closing the issue. We haven't heard about it since then.
Please reopen if a problem with this issue shows up!!!
