### ISSUE TITLE
Tutorial Translations

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#493]
I just had a comment left on my YouTube channel about translations of the instructional videos.  This particular one was asking if there were any in French.  My 2nd language is more Spanish leaning.

I thought I would post this in here if there is anyone that might be able to help with that.  Or if someone might come across this issue later on that might be able to help out with it.

**Comment by Augusa** [comment]
I am able to translate to french if you explain me the way to do it. I suppose you want subtitle for the video.

**Comment by kaalleen** [comment]
@Augusa Thank you for offering your help!

These are not @wwderw videos (so this is probably not the solution for this specific issue), but if you are willing to translate subtitles for Ink/Stitch tutorial videos you can find all the subtitles for the beginner tutorials on this page (underneath each video): 

https://inkstitch.org/tutorials/resources/beginner-video-tutorials/
