### ISSUE TITLE
Locking stitch

### ISSUE THREAD

**Issue by merlinjanssen** [inkstitch/inkstitch#494]
not sure if that exists, but is there a locking stitch? i know of customers that complain because the embroidery does not keep well under wear because there's no lock stitch

**Comment by lexelby** [comment]
Hi, and welcome to Ink/Stitch!

I'm a bit puzzled by your question.  Ink/Stitch does add locking stitches at the start of the design and before/after every jump, color change, and trim.  It places 5 stitches in close proximity before continuing on.  Do you think that's not enough to hold your designs together?

**Comment by ALPHAMOTIF** [comment]
Easy fix for this is to place a few VERY CLOSE manual stitches that work like a backstitch right after each part of the design, having said that I have found that the locking stitches hold pretty well, you just need to make sure you embroider with balanced tension or they will not properly tie off.

**Comment by wwderw** [comment]
Lock stitches are what all embroidery machines do, those are actually done at the main "body" of the embroidery objects.  If it's a lock stitching issue, I would do what @ALPHAMOTIF mentioned and look at your tensions.  If you don't have an upper and lower tension gauge, I would suggest getting one of each.

Tie in and Tie off stitches (the stitches that apply at the beginning and end of embroidery objects that are not connected to other objects) are provided by Ink/Stitch and even more so then a lot of other commercial products (even objects that are connected to other objects still get tie in and tie off stitches in Ink/Stitch).  The exception are if you are using manual stitches.

Are you using any manual stitches in your designs?  If so, tie in and tie off stitches will need to be added manually where applicable.

Are you running these designs in another program that has a small stitch filter?  If so, take a look at the settings of the small stitch filter and see if it's the settings of that filter that may be removing the tie in and tie off stitches that were originally there.

Also this here:

> does not keep well under wear

What is the actual complaint?  Is it loose stitches overall, but the ends of objects are still in their strong or is it actually stitches coming out from the ends of the objects?  What is it exactly?

**Comment by merlinjanssen** [comment]
I was asking cause the guy that sells us the machine (older swf 15 needle one head) is paying for embroidery service which I hope as a graphic artist and your program – to do myself, he had issues receiving files with no lock stitch and customers complaining about the embroidery coming out after wearing it short time, he’s got a guy in india doing it now 

Sent from Mail for Windows 10

**Comment by wwderw** [comment]
> I was asking cause the guy that sells us the machine (older swf 15 needle one head) is paying for embroidery service which I hope as a graphic artist and your program – to do myself, he had issues receiving files with no lock stitch and customers complaining about the embroidery coming out after wearing it short time, he’s got a guy in india doing it now

Have you run the file on your machine to see if it has lock stitches in it?  Do the lock stitches show up on your machine?

Other thing is slow down simulate to a crawl and see if there are 4 to 5 stitches placed in a tight grouping in areas that you would expect to have.

Preferably test it on a machine.

If it shows up on your end, either on your machine and/or through simulate, I would actually then wonder if your customer is opening the file and  resaving it within their own program.  If that's the case, then their software could be running it through a small stitch filter that could be removing the tie in/ tie off stitches from the file.

**Comment by kaalleen** [comment]
I'm closing the issue now. Please feel free to reopen the topic if needed.
