### ISSUE TITLE
There seem to be an issue with trims for the vp3 format

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#495]
I have a Husqvarna viking Topaz 50 machine, which does trims. When doing designs in inkstitch, my trims does not work as I expect (they do not trim at all). 

Using the free version of Premier (Husqvarna/Pfaff embroidery software), it tells me there are no trims in the vp3 file. Using the free version of truesize e4, I get to know there are only two trims in the vp3 file (a file with two colors). 

However, saving the same inkstitch file to formats like dst or pes, truesizer tells me there are 8 trims, not the 2 it tells me for vp3. This is more in line with the trims shown for the design by inkstitch and my expectations.

Is this lack of trims in vp3 files a known issue? I can provide example files if wanted, but I first need to understand if this issue is a real one and a new one, so I do not report an already known thing.

--- Mats ---

**Comment by lexelby** [comment]
Hi there, and thanks for trying out Ink/Stitch!  It is certainly possible that trims don't work in VP3 files.  We haven't had anyone to test, so we had to guess based on example files, and we might have gotten it wrong.

Example files would be really helpful.  Could you create two VP3 files, one with a trim and one without? Bonus points if they're both the same other than the trim :)

**Comment by MatsIBengtsson** [comment]
Hello, Thank you. The program is good. The alternatives are very expensive. Seem Ink/Stitch can do most of what I need, so I hope to stay with it. Some stuff is hard for me, being new to both machine, embroidery and Ink/Stitch at same time. Documentation is good, yet some feature are hard to find both since I do not know what to expect, and some of the features are hidden in a mixture of inkscape and Ink/Stitch.

Anyway, enclosing a zip file containing a number of files [outline cat face p0.0-006.zip](https://github.com/inkstitch/inkstitch/files/3423505/outline.cat.face.p0.0-006.zip). 

1. The inkscape svg file which contains the design, as done with inkscape and Ink/Stitch (done more or less from scratch, however, the paths are imported from a drawing done in illustrator). That does not seem to have ill effects.
2. The vp3 file as created by Ink/Stitch (outline cat face p0.0-006.vp3). It does not manage to convince my embroidery machine to do any trimming, neither does it make Wilcom truesize believe it should.
3. A screen dump of Wilcom truesize interpretation of the vp3 file created by Ink/Stitch (Wilcom truesize interpretation of InkStitch vp3 file.PNG). It seem to accurately describe all trims not occuring (color changes are trimmed, but they are always trimmed independent on what commands the vp3 file contains, so likely not due to a trim command in Ink/Stitch vp3 file)
4. The dst file created by Ink/Stitch. It convinces Wilcom truesize that there are trim commands defined in the file, just as claimed by Ink/Stitch.
5. The vp3 file created by taking the Ink/Stitch dst file into Wilcom truesize, and export as a vp3 file (outline cat face p0.0-006 wilcom from dst.VP3). That vp3 file, according to Wilcom, does contain a number of the wanted trim commands (not all of the ones defined from the beginning in the dst file, but many). It convinces my embroidery machine to trim the thread in many of the wanted places. Side note: Taking the Ink/Stitch vp3 file and saving from Wilcom truesize as vp3 does not produce any visible trims. It does add one extra line, likely a start thread, so something is missing in the vp3 file as saved by Ink/Stitch.
6. A wilcom truesize screen dump of its interpretation of the vp3 file Wilcom truesize created using the Ink/Stich dst file (Wilcom truesize interpretation of InkStitch dst file saved as vp3 with lines.png). With lines showing the differences between Wilcom truesize view, and final results on the embroidery machine:
   - Wilcom was almost right. There is an extra start thread it expects, which does not show up (encircled in black in the screen dump). Wilcom expects same extra thread when just saving the InkStitch vp3 file using Wilcom truesize. Likely something I have extra in my svg file.
   - Three threads which are not trimmed, although Wilcom expects them to be (shown as three black lines on the screen dump). One up in top left corner of the eye, and two connecting to and from the nose.

**Comment by kaalleen** [comment]
See #516

**Comment by embroiderforsons** [comment]
Has this issue been resolved. The pic on the left is Inkscape (result with trim commands) and on the right is Premier2 not picking up the trim commands I did in Inkstitch. My machine is a Viking/Husqvarna Topaz 40 which only uses vp3 and hus files.


![20210405_110601](https://user-images.githubusercontent.com/79768771/113590472-b1145c00-9600-11eb-80fb-0c5b9accf590.jpg)
![20210405_110940](https://user-images.githubusercontent.com/79768771/113590498-bb365a80-9600-11eb-82ca-6db39cbcb855.jpg)

**Comment by embroiderforsons** [comment]
![20210405_112258](https://user-images.githubusercontent.com/79768771/113590934-4a437280-9601-11eb-8113-94a218afa077.jpg)
Inkstitch with trim commands showing.

**Comment by kaalleen** [comment]
No, sorry. It is still an open pull request.

**Comment by embroiderforsons** [comment]
Wow, ok thanks.

**Comment by Tina-Chris** [comment]
I also wanted to know on what the vp3 issue is hanging, I could offer to test on my machine different test files.
Tina

**Comment by kaalleen** [comment]
I am not sure. Here just some links to the ongoing discussion:
#516 
https://github.com/inkstitch/pyembroidery/pull/73
https://github.com/inkstitch/pyembroidery/pull/76

I believe we are waiting for an answer and are having issues with updating our pyembroidery version.
It would need a lot of work, which I don't really feel up to. Lex also is a bit short on time. Any help would be appreciated.

**Comment by embroiderforsons** [comment]
Just to let you know I actually saved my files in a different format and my
machine did the embroidery. I have a Husqvarna Viking Topaz 40 machine.
