### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Tbarile** [inkstitch/inkstitch#496]
I’ve been placing all my images that I’ve created as SVG files and nothing seems to be working. Constant code errors that I keep looking up that are unable to be answered. Been watching videos on how to digitize and save as PES step by step but nothing seems to be working. It won’t even show that an object is there but always for it to be traced.  Not too sure on what to do next if anyone has tips please send them my way!

**Comment by kaalleen** [comment]
Hello @Tbarile and welcome to the project. Sorry you are having trouble with Ink/Stitch.

We would really like to help you getting started with Ink/Stitch, but to understand your problem better, we need some more information.

Could you exactly describe your steps to create an embroidery files and when which error messages in this workflow occur.

Additionally (or alternatively) it would be of help to understand your issue, if you could post an so created (not working) svg-file, so we can have a look at it. To upload SVG files, create a zip container for the graphic(s).

**Comment by kaalleen** [comment]
I'm closing the issue now due to it's age and no further respond.
Please reopen the issue, if you are still having issues with Ink/Stitch.
