### ISSUE TITLE
Change to make available realistic view of embroidery easier to find for beginners

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#500]
This suggested change is to make it easier for beginners to find functionality that already exist. It comes after a discussion in another thread ( #426), but was unrelated to that discussion, it was just an implementation decision. So below is a repeat of what was already stated in #426.

Change suggested: 

- Make the realistic preview capability easier to find without having to go through the web documentation. 
- Preferably by mentioning already in the print command that it is a preview command that can be printed, and already there also mentioning that realistic rendering can be output during that preview, and also make that a tickbox choice already when selecting that command.

My normal way of finding a feature when not searching for it on web is to look at the list of commands available. Any extra level before seeing further commands that does not immediately appear hides commands through levels. 

In spite of that, if not making it visible directly in the menu, at least make the Realistic preview tickbox choice always visible, so it is easier to find.

Below follows the user experience description leading to the change request:

- I was a new user of Ink/Stitch. I was looking for a "trueview" functionality, and could not find it. I went through all the menues and options and settings in Ink/Stitch. Nothing there. I went through the preview print out file, nothing there either. So I concluded it did not exist. And used Premiers free version for trueview. 
- Then I found a web page which explained how to do it in Ink/Stitch: Go into the print preview, and select the "trueview" checkbox, whatever it was called. Nice! Now I knew, I thought. 
- Next time I used Ink/Stitch, I tried it. No such option available in print preview options. No such command in the print preview menues. I turned on all pages through the options to find it. No such page or command in any print preview page. But I had seen the web page describing it. I had to go and find the video showing how to use it. With the video up, I went back into print preview. And lo and behold. If I rest my cursor close to the end of the page, probably any page, there is an otherwise invisible menue, where I can select a checkbox. And then it works.
- I normally scroll my documents. Meaning I have the mouse out right, not in the view-port. I have plenty of space to move the mouse left before it hits the view-port. I would not put the mouse there to try to get a menu option visible, unless I saw a video telling me that I have to put it there in order to see the menu I am trying to find. That is the reason with current implementation I was not able to find it, even when knowing it was there.
- So now I can access "trueview" in Ink/Stitch. And it will work as long as I remember that I have to start a command first, and then scroll past the menues displayed in the output of that command, and invoke an invisible drop down menue after the output I hoped would contain my "trueview".

![image](https://user-images.githubusercontent.com/15014932/61990369-8ad2a680-b03f-11e9-9de4-305ab9e9c351.png)

**Comment by kaalleen** [comment]
Hey @MatsIBengtsson !
Thank you for your input and describing your experience while trying to display the realistic preview. Of course it wasn't our intention to make it so hard for you to find this feature.

I created a pull request to (hopefully) solve your issue. It does two things.
* The buttons at the bottom of the preview canvas will always be visible.
* The print extension in the menu was renamed to "Print / Realistic Preview".

You can preview the changes by downloading one of these files: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-visible-realistic-button (This release might introduce other errors that you haven't experienced before. This is not due to the above mentioned changes and are meant to be solved in an other pull request.)

By the way the rebuild of Ink/Stitch into an electron app might help the user experience in this matter. We will be able to also integrate the realistic preview into the simulator directly.

**Comment by MatsIBengtsson** [comment]
> Hey @MatsIBengtsson !
> Thank you for your input and describing your experience while trying to display the realistic preview. Of course it wasn't our intention to make it so hard for you to find this feature.
 
Thanks. Of course. I am grateful for Ink/Stitch. Me having problem finding the command was due to the number of levels to reach it, and the way I use the browser. Now when I have found it, it works for me. So my comment was with regards for those unfamiliar with Ink/Stitch.

> I created a pull request to (hopefully) solve your issue. It does two things.
> 
> * The buttons at the bottom of the preview canvas will always be visible.
> * The print extension in the menu was renamed to "Print / Realistic Preview".
> 
> You can preview the changes by downloading one of these files: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-visible-realistic-button (This release might introduce other errors that you haven't experienced before. This is not due to the above mentioned changes and are meant to be solved in an other pull request.)

Sounds dangerous. I think I prefer to wait until there is a new stable release, if that is ok?
> 
> By the way the rebuild of Ink/Stitch into an electron app might help the user experience in this matter. We will be able to also integrate the realistic preview into the simulator directly.

Sounds good about Electron and integrated simulator.

**Comment by kaalleen** [comment]
> I think I prefer to wait until there is a new stable release, if that is ok?

Yes sure, that's fine by me ;)

**Comment by MatsIBengtsson** [comment]
> > I think I prefer to wait until there is a new stable release, if that is ok?
> Yes sure, that's fine by me ;)

Now I have learned to download and install temporary releases, so I did this one as well.

Looked perfect to me.
