### ISSUE TITLE
Ink/Stitch hijacks printing sometimes

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#501]
Once in awhile I still use Inkscape for things other than Ink/Stitch (I know, right?) and every once in awhile Ink/Stitch (1.25.0) gets jealous. I *think* I've narrowed it down to printing. I wandered off to the printer just now, and when I came back the two patterns I'd printed were merrily going to town trying to become satin stitches.

It will go through a dozen or so different error pop-ups before giving me control back (with the file now a "Memory Document"); I'm guessing somehow Ink/Stitch is trying to run its print-to-embroidery-file functions.

![2019-07-27--1564273097_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/62000742-b049c980-b0ac-11e9-8e78-e951d6918d04.png)

**Comment by lexelby** [comment]
I've totally seen this!! Even with the "memory document" thing.  It's definitely not every time you print because I just printed something from inkscape yesterday and it didn't happen.

**Comment by lexelby** [comment]
What kind of shape is path8743? For a non-embroidery svg it's weird that inkstitch is trying to process it like a satin column.  I'm wondering if that path has an attribute `Embroider_satin_column`?

**Comment by tyrosinase** [comment]
> What kind of shape is path8743? For a non-embroidery svg it's weird
> that inkstitch is trying to process it like a satin column. I'm
> wondering if that path has an attribute |Embroider_satin_column|?

It does, and is now a single dotted line - the object is a bit of
top-stitching I copied over from the embroidery-design version into the
paper pattern for conventional sewing. So Ink/Stitch is right that it's
not currently a valid embroidery option, but somebody needs to tell it
that my LaserJet can't do a satin stitch anyway. ;-)

**Comment by tyrosinase** [comment]
Oh, seeing #466 closed reminds me: if I remember correctly that path is a descendant of the "satin-bean" path. Doesn't look like this version has both satin and bean set, but certainly the path has a troubled history. I should go in and clear all the embroidery bits from the XML before reusing it next time.

(It's the wing stitching for the little plush dragons that have inadvertently become a staple of my Etsy shop, so it comes up a lot.)

**Comment by kaalleen** [comment]
Hm, maybe we need an extension to clear embroidery information from selected objects?

**Comment by tyrosinase** [comment]
That'll help (and will be useful for fixing satin-bean situations), but one would only know to do it (if one even knew that was the problem) *after* it had flipped out on print at least once. The ideal solution would be for Ink/Stitch to not try to embroider things that are going to printers in the first place.

Plus, I don't always want to clear the embroidery information: I often have objects that I both print (to cut appliques) and embroider (to stitch placement lines for them).

**Comment by lexelby** [comment]
I know this sounds like a cop-out, but I really don't think Ink/Stitch is to blame here. :(  There's really no way an extension can wedge itself into the print process, so Ink/Stitch definitely isn't hijacking anything.   I think I remember reading that there's the possibility to write "print extensions" for Inkscape, but Ink/Stitch definitely doesn't define any of those in its .INX files.  I'm sorry to say, I think this is an Inkscape bug.

**Comment by tyrosinase** [comment]
On 8/3/19 11:29 PM, Lex Neva wrote:
>
> I know this sounds like a cop-out, but I really don't think Ink/Stitch
> is to blame here. :( There's really no way an extension can wedge
> itself into the print process, so Ink/Stitch definitely isn't
> hijacking anything. I think I remember reading that there's the
> possibility to write "print extensions" for Inkscape, but Ink/Stitch
> definitely doesn't define any of those in its .INX files. I'm sorry to
> say, I think this is an Inkscape bug.
>

Yeah, I'm not sure what is really happening. Maybe "printing hijacks
Ink/Stitch sometimes" is more accurate. I mean, there's a print-to-file
option, which I assume shares code with the save-as-PDF option, which I
guess might somehow bleed over into the save-as-embroidery-file option,
but that starts to feel like quite a stretch. And I haven't looked at
Inkscape code at all, and Ink/Stitch only here and there.

I guess I'll track what happens when I print objects with-embroidery
attributes and objects without, and see if I can pin down a pattern at
least.

**Comment by lexelby** [comment]
> Maybe "printing hijacks Ink/Stitch sometimes" is more accurate.

Yeah, that's kind of what I'm thinking.  Especially with that business about "memory document", it seems to me like Inkscape is perhaps writing off the end of a buffer and corrupting memory, then it gets terribly confused.

**Comment by tyrosinase** [comment]
The plot thickens: I opened a PDF in Inkscape to copy some text out of it because my viewer wasn't cooperating. No other Inkscape open, and presumably USPS does not embed any Ink/Stitch data in its Priority Mail labels. Ungrouped it, selected the item, pasted it into email, and came back to a Memory Document with a dialog. Only two dialogs this time, which is slightly different from the behavior on the dragon pattern above.

I have no idea why Inkscape would think it needed to embroider a tracking number into an email, but clearly it did.

![2019-08-06--1565122978_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/62574921-9146f680-b867-11e9-89fe-9fd80f0838f8.png)
![2019-08-06--1565122972_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/62574922-9146f680-b867-11e9-80aa-ea9013d8d200.png)

**Comment by lexelby** [comment]
> presumably USPS does not embed any Ink/Stitch data in its Priority Mail labels.

They totally should!

The plot is even thicker.  That's not an Ink/Stitch extension that it ran, it's some other extension (ink2canvas).  I call shenanigans.

**Comment by tyrosinase** [comment]
Oh hey, you're right. I just skimmed it and took screenshots because Ink/Stitch *should* be the only extension I have. PLOT TWIST!

(Apparently it writes SVG to HTML5 which... I don't ever remember having a need for that. Maybe I'll clean out the ol' extensions directory and see if the Memory Documents stop.)

**Comment by tyrosinase** [comment]
Another data point: just saved one document as a ZIP file and another one I had loaded switched over to a memory document (and informed me I needed to install UniConverter).

Haven't seen the memory document thing for awhile.

**Comment by kaalleen** [comment]
Closing it now. Please reopen if needed.
