### ISSUE TITLE
inkstitch non funziona

### ISSUE THREAD

**Issue by linaabate** [inkstitch/inkstitch#508]
Windows 10 inkscape 0.92.4 ma inkstitch non funziona, messaggio di errore quando si lancia il comando params (vedi file allegato)

![Errore 2019-08-04 020438](https://user-images.githubusercontent.com/53667538/62417913-8e2bea80-b65c-11e9-9cd3-4e131856a83f.png)

**Comment by lexelby** [comment]
Hi there!  I don't speak Italian, but I think I know what's going on.  Try deleting that `traceback.pyc` file and run Params again.

@X3msnake any chance you could help bridge the language gap? :)
