### ISSUE TITLE
running Ink/Stitch commands in own builds does not work, makes testing harder

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#512]
When I import a build I have done into incscape, or that somebody else has done, the Ink/Stitch commands all runs, but returns an error message stating that unexpected message existed.

That prevents for example Params to apply changes. If I install latest official Ink/Stitch patch I have, then this works. Since I am testing new Ink/Stitch extensions, which are working as part of other extensions, this becomes a test issue.

Is this a know issue, and is there an easy solution?

**Comment by kaalleen** [comment]
Are you refering to the decode error?
If so, then it should be fixed by now.

**Comment by kaalleen** [comment]
Reference: #503

**Comment by lexelby** [comment]
Could you paste the error message here, or upload a screenshot?

**Comment by MatsIBengtsson** [comment]
> Are you refering to the decode error?
> If so, then it should be fixed by now.

Hello, yes likely. But then if I understand it right, I need to get the #503 into my build to get that build working for me while testing. And that build is from an older master.

Do I do that using what is called rebase? It seems that should be avoided if you have already uploaded commits, but maybe it is ok if I upload new commits after?

**Comment by lexelby** [comment]
Yup, rebase is the right tool here.  I do it all the time, it's totally fine :)

with your branch checked out:

```
git fetch origin
git rebase origin/master
git push -f
```

**Comment by MatsIBengtsson** [comment]
> Yup, rebase is the right tool here. I do it all the time, it's totally fine :)
> 
> with your branch checked out:
> 
> ```
> git fetch origin
> git rebase origin/master
> git push -f
> ```

Great! I am new to github, so I am quite uncertain on what is right to do. Then I know, I will try it.

**Comment by lexelby** [comment]
My favorite is `git rebase -i origin/master`.  You can reorder commits, collapse commits together, reword commit messages, and even delete commits.

**Comment by MatsIBengtsson** [comment]
> My favorite is `git rebase -i origin/master`. You can reorder commits, collapse commits together, reword commit messages, and even delete commits.

Ah, yes, collapse commits is what I would really have liked to do. I am using a gui, will try to find how to find that "-i" through the gui. But right now, I am keen to see if things are still there in my commit after my first rebase attempt. :)

**Comment by lexelby** [comment]
If not, do `git reflog` to find out the commit id your branch was on before rebase, and do `git reset --hard id`.  Or before you push, you could do `git reset --hard origin/your-branch`.

**Comment by MatsIBengtsson** [comment]
> If not, do `git reflog` to find out the commit id your branch was on before rebase, and do `git reset --hard id`. Or before you push, you could do `git reset --hard origin/your-branch`.

I was reading earlier today on the git reset -hard command as well. I bet all of that is in my gui, just need to understand what is what and find how to use it.

**Comment by MatsIBengtsson** [comment]
> My favorite is `git rebase -i origin/master`. You can reorder commits, collapse commits together, reword commit messages, and even delete commits.

Ok, did find it, so I have it. Guess it is too late this time, but at least now I know it is there and can use in the future if I remember to :).

**Comment by MatsIBengtsson** [comment]
After testing, #503 as stated solved it.
