### ISSUE TITLE
Extension for Special Stitches

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#514]
We now have a possibility to see warnings for stitches (when needle points are too close, when too many needle points stress an area of the stabilizer or the fabric, when we have too high thread density in an area).

That is good. But on top of that, I find myself looking for where are the jump stitches, where are the trim stitches, and where do I have really long stitches. Basically, a wish to be able to ask the simulation to only show me stitches that are not normal stitches (stops, jumps, color_changes, ...) plus the ones where difference in needle points exceed a certain distance.

Are others also looking for the same or similar things? Is this a feature to add?

**Comment by lexelby** [comment]
I would definitely find that useful!

**Comment by MatsIBengtsson** [comment]
> I would definitely find that useful!

Great, a first version of that already exist. The previous work I did on the simulators made it quite easy to add to the embroidery_simulator. If you look at the buttons in the bottom of enclosed picture, you find the first implementation part. (jump by commands and by stitch blocks).
<img width="1444" alt="embroidery simulator new buttons" src="https://user-images.githubusercontent.com/15014932/62800799-9a90c700-bae4-11e9-9934-d1826bf45e20.PNG">

**Comment by lexelby** [comment]
This is mostly complete other than highlighting long stitches.  I haven't seen anyone else looking for that feature, but if they do, we can open a new feature request.
