### ISSUE TITLE
There was a build error in osx, build subpart 6, but not the others

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#515]
The build error referred electron, but I do not know if that was the issue or not. Build is at (https://travis-ci.org/inkstitch/inkstitch/jobs/568683689)

**Comment by lexelby** [comment]
> Get https://github.com/electron/electron/releases/download/v4.1.3/electron-v4.1.3-darwin-x64.zip: dial tcp: lookup github.com: no such host

This looks like some kind of temporary network issue.  that kind of thing happens sometimes with travis.  If you restart the build, it will probably work fine the second time around.

**Comment by MatsIBengtsson** [comment]
> > Get https://github.com/electron/electron/releases/download/v4.1.3/electron-v4.1.3-darwin-x64.zip: dial tcp: lookup github.com: no such host
> 
> This looks like some kind of temporary network issue. that kind of thing happens sometimes with travis. If you restart the build, it will probably work fine the second time around.

Hello, thank you, I did, and it worked. Just wanted to be sure you were aware in case this was of interest for you. I will wait until they are persistent next time :)
