### ISSUE TITLE
Thought about needle distance in fills and satin columns

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#517]
Both fills and satin columns use some kind of underlay, which is automatic. Then for fills a fill. For the case of underlays both for fills and for satin columns, I find those underlays for symmetric shapes are very prone to use the same needle points on both "way away and way back". 

Specially for the underlays, with long distances between points, there are possibilities to place the needles more apart. And the placement is automatic. So question is, can it be done? Is it something to strive to improve in program? As a beginner, I assumed the defaults would sort of think of such things.

Below are three pictures. All of the nose of the cat I have shared earlier. One picture show the embroidery simulation after 152 stitches, and one after 285 stitches. There are no visible difference. The other one is for needle distance warnings, basically, all needle points from stitch 145 and forward are reusing existing needle points with very small differences. Likely due to the symmetry and thus the calculations. Likely not due to lack of space?
![fill after 152 stitches](https://user-images.githubusercontent.com/15014932/62606815-48418180-b8fd-11e9-980d-1f0180495a1f.PNG)
![same fill after 285 stitches](https://user-images.githubusercontent.com/15014932/62606826-4bd50880-b8fd-11e9-9621-a46c02ed0357.PNG)
![needle distance warnings, no new needle points after 145 stitches](https://user-images.githubusercontent.com/15014932/62606834-51325300-b8fd-11e9-9b2c-792312d2f295.PNG)

**Comment by lexelby** [comment]
Hmm, I don't fully understand what's going on here.  Could you post an SVG with this object in it?  And maybe also a DST just so I can be sure I see the stitches as you do?

**Comment by MatsIBengtsson** [comment]
> Hmm, I don't fully understand what's going on here. Could you post an SVG with this object in it? And maybe also a DST just so I can be sure I see the stitches as you do?

For the svg, sure, actually as I mentioned, it is already available, it is my "standard" svg (my first try with Ink/Stitch). See inside enclosed zip. [outline cat face p0.0-006.zip](https://github.com/inkstitch/inkstitch/files/3477142/outline.cat.face.p0.0-006.zip)

**Comment by lexelby** [comment]
I think I know why almost every needle point is duplicated.  The reason: the nose is duplicated. ;) `path144` and `path148` appear to be exact duplicates of each other.

**Comment by MatsIBengtsson** [comment]
> I think I know why almost every needle point is duplicated. The reason: the nose is duplicated. ;) `path144` and `path148` appear to be exact duplicates of each other.

Great! Thank you. Good find. Simple solution. Sorry for bothering. Need to repeat it was my first Ink/Stitch drawing. *BLUSH*

Leads me to the thought if it would be good to see a warning on that, or an object list somewhere? You have added validation checkings lately. Possibly there? 

I do not think there exist an incscape list which identifies the different groups today in an easy way? Selecting the area selects both objects, selecting it from top does not show the deselected object beneath. inkscape layer command does show it. Adding trim if selecting the area hints on two trims being added.

I checked using the new "next stitch block" function in the simulator window (thus working for all simulators). It did pick it up, and steps through the nose around 150 stitches, then again, showing a slight intensity change after second turn. So the information is already in Ink/Stitch, not only in incscape.

**Comment by lexelby** [comment]
Oh, I think you might be missing out on one of the key features of Inkscape that most (all?) of us use for Ink/Stitch.  Version 0.92 and higher have the Objects panel, available in the Objects menu.  That shows you layers and all of the objects in them in a heirarchical view.  It makes it really easy to see things like this double nose.

**Comment by MatsIBengtsson** [comment]
> Oh, I think you might be missing out on one of the key features of Inkscape that most (all?) of us use for Ink/Stitch. Version 0.92 and higher have the Objects panel, available in the Objects menu. That shows you layers and all of the objects in them in a heirarchical view. It makes it really easy to see things like this double nose.

My bad in wording. I have found the Objects panel, but thank you anyway. In Illustrator it is in the layer view, so I used the wrong terminology. I should have seen it myself... :)
