### ISSUE TITLE
Is there a way to deploy and build code in inkstitch which fetches my branch of pyembroidery

### ISSUE THREAD

**Issue by MatsIBengtsson** [inkstitch/inkstitch#518]
Need to change both pyembroidery and inkstitch at same time. I would like for the automatic build in inkstitch to use my changes in pyembroidery when building.

Is that doable?

**Comment by lexelby** [comment]
Yup!  At the command line in your ink/stitch directory, it looks like this:

```
$ cd pyembroidery
$ git fetch origin
$ git checkout your-branch
$ cd ..
$ git add pyembroidery
$ git commit -m "use my branch of pyembroidery"
$ git push
```

Ink/stitch uses pyembroidery as a submodule.  It saves a pointer to a specific commit (or branch, or tag) in the ink/stitch repo.

**Comment by MatsIBengtsson** [comment]
> Yup! At the command line in your ink/stitch directory, it looks like this:
> 
> ```
> $ cd pyembroidery
> $ git fetch origin
> $ git checkout your-branch
> $ cd ..
> $ git add pyembroidery
> $ git commit -m "use my branch of pyembroidery"
> $ git push
> ```
> 
> Ink/stitch uses pyembroidery as a submodule. It saves a pointer to a specific commit (or branch, or tag) in the ink/stitch repo.

Super! Thank you. In mean time, I managed to get pyinstaller working locally as well. Prefer your more officially correct method though.

**Comment by MatsIBengtsson** [comment]
> > Ink/stitch uses pyembroidery as a submodule. It saves a pointer to a specific commit (or branch, or tag) in the ink/stitch repo.
> Super! Thank you. In mean time, I managed to get pyinstaller working locally as well. Prefer your more officially correct method though.

I did a try. It said I updated the pyembroidery submodule, but then I got build errors. Any idea what I did wrong?:

```
5.65s$ git submodule update --init --recursive
Submodule 'pyembroidery' (https://github.com/inkstitch/pyembroidery) registered for path 'pyembroidery'
Cloning into '/home/travis/build/inkstitch/inkstitch/pyembroidery'...
error: Server does not allow request for unadvertised object 75f4bed22b55228a7d210e63fa8fc3aec54f4820
Fetched in submodule path 'pyembroidery', but it did not contain 75f4bed22b55228a7d210e63fa8fc3aec54f4820. Direct fetching of that commit failed.
```

**Comment by MatsIBengtsson** [comment]
> I did a try. It said I updated the pyembroidery submodule, but then I got build errors. Any idea what I did wrong? I am now in a squeeze. The default pyembroidery build is incompatible with the inkstitch/pyembroidery one (input calls a subroutine which has been renamed). So it is neccessary to build with inkstitch/pyembroidery to be able to test:

Solved it, I did not do as you said. I missed to get the pushed branch for pyembroidery to connect to my push of Ink/Stitch. Seem I finally got passed that point.
