### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by SCHIAVINATTO** [inkstitch/inkstitch#522]
I would like to help in the translation of this excellent program, and also help in its dissemination in Brazil, where we have a lot of difficulty. I am willing to help with whatever I need.

**Comment by lexelby** [comment]
Welcome to the project!  We're really happy that you want to help out.  Instructions on how to contribute translations are [here](https://github.com/inkstitch/inkstitch/blob/master/LOCALIZATION.md).  The more folks we can reach, the better!

**Comment by lexelby** [comment]
I'm going to go ahead and close this now, but if you have any trouble getting started with translation, please let us know!
