### ISSUE TITLE
1.26.0 Created Black only color stop in PEC & PES

### ISSUE THREAD

**Issue by Wakko019** [inkstitch/inkstitch#523]
1.25.0 Used to create a PES from an Inkscape created file, all the color stops appear as their respective colors after save and opening in PES or PEC (in Inkscape or in Sew What Pro Embroidery editor).

1.26.0 created and saved files appear as 1 color stop composed of all the different sections (fill, bean, satin) in Inkscape/Inkstitch and Sew What Pro.

I do not know if this is some sort of user error on my part, as I am not versed in code.
If you need more information let me know (and possibly how to provide it to you), I am using windows 10, Inkstitch works using version 1.25.0 but does not work in 1.26.0 is the gist.

**Comment by lexelby** [comment]
Thanks!  I see the problem as well.  This bug must have slipped through in the 1.26.0 release.  I'll try to get 1.26.1 released with a fix ASAP.

**Comment by lexelby** [comment]
Found it!  Thanks again for bringing this to our attention.  Version 1.26.1 is building now and should be posted to the releases page soon.
