### ISSUE TITLE
When importing PES font letters, nothing embroiders

### ISSUE THREAD

**Issue by rocketmannate** [inkstitch/inkstitch#530]
Hello! I am trying to create words using a PES font that I downloaded. Whenever I import the letters in PES form, they import correctly and my preview/simulation looks exactly as it should. When I save the project to a PES file and try to use it on my machine, however, it only stitches one stitch and then ends the program. The data appears to be there, because the preview on my embroidery machine looks correct, but after several attempts I cannot get it to work. Is there any known cause or solution for this?

The font I am currently using can be found at the link below, but the issue does not seem to change with other fonts. 
http://fivestarfonts.com/free-font-teachers-pet

**Comment by tyrosinase** [comment]
On 8/20/19 3:39 PM, rocketmannate wrote:
>
> Hello! I am trying to create words using a PES font that I downloaded.
> Whenever I import the letters in PES form, they import correctly and
> my preview/simulation looks exactly as it should. When I save the
> project to a PES file and try to use it on my machine, however, it
> only stitches one stitch and then ends the program. The data appears
> to be there, because the preview on my embroidery machine looks
> correct, but after several attempts I cannot get it to work. Is there
> any known cause or solution for this?
>
Whenever this has happened to me, it's because the project was outside
the hoop size in Inkscape. Even though the design *would* fit in the
hoop, and the machine (a PE-800) will display the preview just fine, it
gets extremely confused by designs that were generated off in the
distance and selecting them will actually crash my machine sometimes.

Set your page size to 4x4/5x7/etc, and make sure the design falls
entirely on the "paper."

**Comment by rocketmannate** [comment]
Ah, yes. That solved the problem. Thanks!

Is there a Facebook group for Inkstitch users? If not, do you mind if I create one? I would love to help with the project, but I don't have any coding abilities. I would love to create/moderate a group for users to learn and collaborate if that would be helpful.

**Comment by lexelby** [comment]
Sure, go right ahead!  There's also plenty to help with here if you're interested.  We have an entire website with instructions and examples (https://inkstitch.org/), and it's a huge effort to keep it up-to-date with the latest features.  @kaalleen has done a lot of work on it.

If you're multi-lingual, we also have a tool set up for adding translations over at https://crowdin.com/inkstitch.

**Comment by tyrosinase** [comment]
It might be worth getting a forum that isn't here, but if it's Facebook that includes me out.

**Comment by rocketmannate** [comment]
> It might be worth getting a forum that isn't here, but if it's Facebook that includes me out.

I also don't mind helping to start and moderate a forum in another platform other than Facebook, I'm just most active on Facebook. Contact me on my 

> Sure, go right ahead! There's also plenty to help with here if you're interested. We have an entire website with instructions and examples (https://inkstitch.org/), and it's a huge effort to keep it up-to-date with the latest features. @kaalleen has done a lot of work on it.
> 
> If you're multi-lingual, we also have a tool set up for adding translations over at https://crowdin.com/project/inkstitch.


I don't mind helping in other ways, too. I'm self-employed and this is my busy time of year, so I can't commit to any deadlines right now, but in the fall and winter I can help with other things that are time-constrained.

Is there someone I can contact via email to find ways to help in a less public forum?

**Comment by tyrosinase** [comment]
Is the website a git repo somewhere? I don't know a lot of the answers but I am pretty good at folding other people's answers from the conversations here into the more formal documentation.

**Comment by rocketmannate** [comment]
Here's the link to the new Facebook group. I'm still pretty new to this, and won't have a lot of the answers. Any experts who are willing/able to join would be appreciated!

https://www.facebook.com/groups/369667580374203/

**Comment by lexelby** [comment]
If there were deadlines in this project I'd have been fired long since. ;)  My one rule here (aside from the code of conduct, of course) is that no one is allowed to make anyone feel badly in any way about the amount they contribute.

Email would be fine, `inkstitch at lex dot gd`.  I'm just finishing up my vacation and my free time is about to go way down, so please don't be alarmed if it takes me a few days to respond :)

**Comment by lexelby** [comment]
@tyrosinase Yup!  This repo, in fact.  It's hiding in the `gh-pages` branch.  I'm afraid I've barely looked at it, so I don't really know how it works. @kaalleen and others have really done wonders on it.

**Comment by jameskolme** [comment]
> 
> 
> It might be worth getting a forum that isn't here, but if it's Facebook that includes me out.

Agreed, github is not that user friendly after all. I try this translation thingy and maybe download fresh copy of ink stitch, it seems I have fallen behind badly.

**Comment by kaalleen** [comment]
@tyrosinase if you want to help with the website a good staring point would be the tutorial section. This section still hasn't gotten a lot of attention and I don't find the time to produce more content there. Of course you can work on any other part of the website too. This is just meant to point out, where the website still needs a lot of work. If you are willing to add content but have troubles to get into it, please just ask ;) I know the structure can be a little confusing.

**Comment by tyrosinase** [comment]
On 9/3/19 10:12 AM, Kaalleen wrote:
> @tyrosinase <https://github.com/tyrosinase> if you want to help with
> the website a good staring point would be the tutorial section. This
> section still hasn't gotten a lot of attention and I don't find the
> time to produce more content there. Of course you can work on any
> other part of the website too. This is just meant to point out, where
> the website still needs a lot of work. If you are willing to add
> content but have troubles to get into it, please just ask ;) I know
> the structure can be a little confusing.

Today I learned how to check out a single branch from a git repo. 🎉
