### ISSUE TITLE
Unexpected error lauching Ink/Stitch - any help?

### ISSUE THREAD

**Issue by FabyoAW** [inkstitch/inkstitch#532]
Tried to launch: inkstitch/bin/inkstitch
Arguments: ['inkstitch/bin/inkstitch', '--id=path10', '--extension=convert_to_satin', '/tmp/ink_ext_XXXXXX.svgXCYW6Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/snap/inkscape/5874/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/snap/inkscape/5874/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by lexelby** [comment]
Hi there, thanks for trying inkstitch!  I wonder, are you on a 32-bit Linux system?  Or perhaps you're running on an ARM processor, like a raspberry pi?

**Comment by FabyoAW** [comment]
Hello lexelby,

I'm using Ubuntu 16.04 LTS 64 bit on a Samsung RV411 notebook, Intel® Core™ i3 CPU M 380 @ 2.53GHz × 4

Thanks for help. I'm also trying to help with translation.

![image](https://user-images.githubusercontent.com/54363047/63438971-9ed1b400-c403-11e9-8e4a-7889a9cab503.png)

**Comment by lexelby** [comment]
Strange, the inkstitch Linux build should work fine.  Could you look in your Inkscape extensions directory at `inkstitch/bin/inkstitch`?  That should be a normal Linux executable.  You can run `file inkstitch` in a terminal in that directory to verify. Also, could you run `uname -a` and post the result of both commands here?

**Comment by FabyoAW** [comment]
Hello lexelby there's no inkstitch directory inside inkstitch/bin.
About commands:
~/snap/inkscape/inkstitch/bin$ file inkstitch
inkstitch: Mach-O 64-bit x86_64 executable
~/snap/inkscape/inkstitch/bin$ uname -a
Linux SamsungRV411 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by FabyoAW** [comment]
Can someone explain why I have two different snap directories: one read-only at 'computer' and other, writable, at 'personal folder'?

I've tried to uncompress the Extension files at the Inkstitch directory at the writable snap directory, but I'm not sure it's the right place, or where exactly the extension must be within the directory structure...

**Comment by lexelby** [comment]
Mach-O means that you've accidentally installed the Mac build, whoops!  On the plus side, the fact that you got the "exec format error" message means that you _did_ install Ink/Stitch in the correct extensions directory.  Just clean it up from that directory (`rm -rf inkstitch*`) and grab a linux tar.gz file from the [latest release](https://github.com/inkstitch/inkstitch/releases/tag/v1.26.2) and you should be good to go.

As far as snap, I'm afraid I don't have any experience with snap, so I'm not sure what's going on.  Sorry!

**Comment by FabyoAW** [comment]
Shame on me! Just fine now, thanks lexelby!

**Comment by lexelby** [comment]
This is a shame free zone. :)  Have fun with Ink/stitch!
