### ISSUE TITLE
multihoop

### ISSUE THREAD

**Issue by linaabate** [inkstitch/inkstitch#535]
I have a big embroidery that is wrong with my hoop, is there a possibility to have multihoop mode?
If not, can I get advice on how to proceed? thank you

**Comment by wwderw** [comment]
By this, I think you mean that your design is bigger then a single hooping and it requires multiple hoopings?

If this is the case, typically you would want to have spots that would make it easier to have a "break" from one hooping to the next.  You don't want to have seams (especially with fills) that show up.

Brother PR machines are the only ones that have somewhat of this type of functionality with the 14" x 14" hoop.  I say somewhat, because, their software it will do an auto split of where you do one half the stitching and then flip it over for the 2nd half. 

The good thing with it though, is that the software will only save 1 file that the machine knows to split (so it must do something in the file itself), but it's only the PES file and thus only usable with the Brother machines (specifically the PR models that support that size hoop and have the snowman function).

Long story, best bet is to break up the design to have it work with multiple hoopings.  At least right now.

**Comment by linaabate** [comment]
Yes, you think well,
my machine is Bernina 590 allows the multihoop but the division of the embroidery is done by the sw that automatically tells how many hoops are needed, cuts the embroidery, which is the sequence of the hoops, giving reference points for the exact positioning of the various pieces of embroidery inside the hoops (I hope the translation is understandable I am not very good with English) thanks

**Comment by wwderw** [comment]
My mom has a Bernina, but I'm not familiar with it's software.

That is definitely more then what the Brother PR version does.  This would all have to be done manually.

It's doable, something that have to be done with the commercial machines, but it is all manual.

What specific file format does it use when having to do this operation?  I would imagine that it would be the Bernina specific file format (.art I think?)  If I'm remember that file format correctly, that isn't one of the supported formats in Ink/Stitch as far as the direct exporting (the pyeembroidery backend may have some support for it, but that backend wouldn't be so much digitizing especially with regard to this, it would be more for reading and converting between formats).

**Comment by linaabate** [comment]
the native format of the machine's sw file is .ART, but to transfer the file with the embroidery to the machine is .EXP, however the sw that is used by Bernina is by Wilcom

 

Da: wwderw <notifications@github.com> 
Inviato: lunedì 2 settembre 2019 15:58
A: inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc: linaabate <lina.abate2004@libero.it>; Author <author@noreply.github.com>
Oggetto: Re: [inkstitch/inkstitch] multihoop (#535)

 

My mom has a Bernina, but I'm not familiar with it's software.

That is definitely more then what the Brother PR version does. This would all have to be done manually.

It's doable, something that have to be done with the commercial machines, but it is all manual.

What specific file format does it use when having to do this operation? I would imagine that it would be the Bernina specific file format (.art I think?) If I'm remember that file format correctly, that isn't one of the supported formats in Ink/Stitch as far as the direct exporting (the pyeembroidery backend may have some support for it, but that backend wouldn't be so much digitizing especially with regard to this, it would be more for reading and converting between formats).

**Comment by lexelby** [comment]
This is a really good idea, and I hope Ink/Stitch can support it in the future.  I created this feature request last year: #182

I think @tyrosinase recently described splitting designs for the brother repositionable hoop.  I also have a repositionable hoop for my brother SE400 but I've only used it for sewing lots of copies of a small design.

**Comment by wwderw** [comment]
> the native format of the machine's sw file is .ART, but to transfer the file with the embroidery to the machine is .EXP, however the sw that is used by Bernina is by Wilcom

I believe the ART format can be sent directly if there is a direct connection to USB/Serial to the machine (more then likely USB, they tended to adopt that quicker then the commercial machines, my PRs are USB, while my Barudan (but it's older, 2009) does not).  Or does it do the conversion directly on the fly without user visually seeing it?

Interesting thing, even though Wilcom does provide the stitch engine for Bernina software, Wilcom software can't write to the ART format anymore (unless that's changed with the latest E4 update) using their own software.  I think that stopped with v.4 of the ART format.

**Comment by wwderw** [comment]
> but to transfer the file with the embroidery to the machine is .EXP

Come to think about it, the Brother software only saves to PES files.  So there must be something fundamentally written into the file format in order for it to know what to do etc.  I know I just cant bring in a 14 x 14 design and expect it to know what to do.  

I'll have to check tomorrow, but I do think I can do it manually at the machine, but it would just be right at the center line, regardless of the design and how it is setup, so chances of hard seams are very likely., is it possible to do that manually at the Bernina machine?  I don't know though, the Bernina function is a lot more involved, perhaps not.

**Comment by tyrosinase** [comment]
It must be steam-engine time: https://silverseams.com/2019/08/30/figuring-out-a-5x12-hoop/

Of course, editing the designs that I'm doing this with is much easier because I'm in "computer-aided sewing machine" mode rather than "conventional embroidery design" mode. You can see the two-foot-long critter I'm in the process of sewing now, and another view of that initial (stabilizer-only) test here:
https://mastodon.art/@silverseams/102708905175186745

**Comment by lexelby** [comment]
It never ceases to amaze me, what you manage to do with an embroidery machine!  Maybe sometime if you had a moment, could you share some thoughts on #182?  I'm really interested to hear what ways Ink/Stitch might be able to provide you with tools to make it easier to split a design and to work with a split design.

**Comment by tyrosinase** [comment]
I figure I'll have to split a few more designs to get an idea of what works and what doesn't.

I am operating at the disadvantage of having almost no experience with commercial designs/software so sometimes I end up reinventing the wheel (a good example of this is https://silverseams.com/2019/03/27/queen-of-unfinished-projects/ versus https://silverseams.com/2019/04/06/monday-shop-drop/ where you can see what happened when I used Ink/Stitch's lettering and went OHHHH THAT'S WHAT MY JUMP THREADS SHOULD BE DOING).

So clearly the solution is that someone needs to give me a Brother PR machine, Wilcom software, etc. to broaden my horizons. Let me go open an issue for that...

**Comment by linaabate** [comment]
Hi everyone, wilcom's sw is Hatch, and its format is. EMB for portal on a USB key of the machine is saved in .EXP format. The .ART format has various levels, .art level A, .art level B, etc. etc. Level A has inside all the information that allows you to modify the embroidery later. For the other levels there are restrictions, for example you can't make changes or don't allow the recalculation of the points I enlarge or reduce the embroidery.
The sw that produces the .ART format is Bernina Embrodery software 8 produced by Wilcom.

**Comment by linaabate** [comment]
Hi everyone, wilcom's sw is Hatch, and its format is. EMB for portal on a USB key of the machine is saved in .EXP format. The .ART format has various levels, .art level A, .art level B, etc. etc. Level A has inside all the information that allows you to modify the embroidery later. For the other levels there are restrictions, for example you can't make changes or don't allow the recalculation of the points I enlarge or reduce the embroidery.
The sw that produces the .ART format is Bernina Embrodery software 8 produced by Wilcom.

 

Da: wwderw <notifications@github.com> 
Inviato: lunedì 2 settembre 2019 16:53
A: inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc: linaabate <lina.abate2004@libero.it>; Author <author@noreply.github.com>
Oggetto: Re: [inkstitch/inkstitch] multihoop (#535)

 

but to transfer the file with the embroidery to the machine is .EXP

Come to think about it, the Brother software only saves to PES files. So there must be something fundamentally written into the file format in order for it to know what to do etc. I know I just cant bring in a 14 x 14 design and expect it to know what to do.

I'll have to check tomorrow, but I do think I can do it manually at the machine, but it would just be right at the center line, regardless of the design and how it is setup, so chances of hard seams are very likely., is it possible to do that manually at the Bernina machine? I don't know though, the Bernina function is a lot more involved, perhaps not.

**Comment by kaalleen** [comment]
Closing the issue in favor of #182 (Automatic splitting of designs for small machines)
