### ISSUE TITLE
XMLSyntaxError: Specification mandates value for attribute outter

### ISSUE THREAD

**Issue by skies2law** [inkstitch/inkstitch#539]
No matter what I try to do following tutorials step by step I get one error code after another.  I've uninstalled and reinstalled.  I get to work for one step and when I try to do the same step again on a new page I get error codes.  This one was for just installing the add ons.  I tried to recreate the simple circle and up pops the error codes.  Can someone direct me to solutions.

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=install', 'C:\\Users\\skies\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgHJ2T7Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by lexelby** [comment]
Hi there!  Thanks for trying inkstitch.  I'm sorry that your experience has been pretty terrible so far.

You're definitely not the only person that's having this problem and I'm trying to get a better understanding of what's going wrong.  I'm wondering, would you be willing to post a screenshot of your Inkscape extensions directory where you unzipped the inkstitch ZIP? That would help me understand and I might be able to get you to and running.

Ultimately we want to use this intimation to create a standard installer to make this easier.

**Comment by jameskolme** [comment]
@lexelby would it be possible to include such an error message that shows the current folder location for important Inkstitch files? This would rule out user installation errors or at least it should.

**Comment by patpeazy** [comment]
Hello, 

I am new to ink stitch and I don't know anything about code. The errors messages are a foreign language to me. I have looked at the tutorials, but none of them answer my questions. I mainly get an error of the border crossing over itself. I have looked for the duplicates or nodes hiding on top of each other and have even figured out how to find the node that is having the error in the XML. However, I do not know what to do to fix the node. I have used a SVG file I made from illustrator and I read that they don't translate well into inkstitch. If I create my SVG file in inkstitch would it solve the problem? I have grouped like colors together and converted object to path and that has not worked either. Below is the error code I am getting. 

Traceback (most recent call last):
  File "inkstitch.py", line 44, in <module>
    print >> sys.stderr, traceback.format_exc()
  File "inkscape/share/extensions/inkex.py", line 279, in affect
  File "lib/extensions/base.py", line 210, in parse
  File "inkscape/share/extensions/inkex.py", line 202, in parse
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
XMLSyntaxError: Specification mandates value for attribute outter, line 82, column 13 (line 82)
![Badguys svg-path121-4294966387](https://user-images.githubusercontent.com/55466215/65327260-79aa9f80-db81-11e9-97cd-8645bdc3cdbd.png)

**Comment by kaalleen** [comment]
@patpeazy I know, this is a while ago.
Do you still have the svg file causing the issue?
It might help us to figure out, what went wrong here.

**Comment by kaalleen** [comment]
Since we did not receive a file, I would say from the issue, that this can only be solved by importing the svg file instead of opening it directly with Inkscape. Ink/Stitch now (with the upcoming release) will give this information when receiving an xml error such as this.

Therefore I will close this issue now. Please reopen, if this solution is not satisfying or can be improved.
