### ISSUE TITLE
Params not appearing

### ISSUE THREAD

**Issue by Little-cat-z** [inkstitch/inkstitch#540]
I just downloaded the latest release of Inkstitch and Params is not appearing on the Inkstitch extension menu. Has the workflow changed, or did I mess up the install?

![Untitled](https://user-images.githubusercontent.com/22893883/64971706-0f8ab580-d876-11e9-9247-2666993b16f8.jpg)

**Comment by wwderw** [comment]
Based on the picture it looks like your missing more then just Params.  Here is mine:

![Params](https://user-images.githubusercontent.com/24878362/64978515-4dd6a380-d87b-11e9-94b9-22a5333d9a78.png)

Were all the files moved over into the necessary directory?  I know some were as it's showing up in your extension lists, but your missing quite a few.

**Comment by Little-cat-z** [comment]
I tried clearing out the extensions folder and re-extracting the inkstitch directory. That didn't work, so I emptied the extensions folder again, updated inkscape from 0.92 to 0.92.4, then re-downloaded inkstitch and extracted into the extensions folder. That still didn't work. My Ink/Stitch menu is limited to:
Commands
Lettering
Satin Tools
Troubleshoot Objects

**Comment by Little-cat-z** [comment]
Instead of extracting Inkstitch directly into the extensions folder, I extracted it somewhere else and copied it over. That seems to have resolved it.
