### ISSUE TITLE
Printing / web preview does not work on macOS

### ISSUE THREAD

**Issue by Chris1717** [inkstitch/inkstitch#545]
When trying to print / web preview an inkstitch valid objects a blank app called "inkstitch-gui" shows up. Nothing elese happens. "inkstitch-gui" is only quit able.

Inkscape: Inkscape 0.92.2 5c3e80d, 2017-08-06

Inkstitch: inkstitch-v1.26.2-osx-mojave-x86_64-de_DE

**Comment by kaalleen** [comment]
Sorry you are having issues with Ink/Stitch and thank you for reporting them back to us!

Sadly this is a known issue. We have no ideas how we can get the print preview working in macOS since we converted it to an other gui system. If you have any idea what we could do about it, help would be much appreciated. The print preview as well as the whole future gui system relies on electron.

**Comment by Chris1717** [comment]
I would love to support the project.
I tried your "Manual Setup" for macOS. It is not working on a clean system. The description is not complete. I'm now stuck at "make inx":

Traceback (most recent call last):
  File "bin/generate-inx-files", line 17, in <module>
    from lib.inx import generate_inx_files
  File "lib/inx/__init__.py", line 1, in <module>
    from generate import generate_inx_files
  File "lib/inx/generate.py", line 3, in <module>
    from .extensions import generate_extension_inx_files
  File "lib/inx/extensions.py", line 5, in <module>
    from ..extensions import extensions, Input, Output
  File "lib/extensions/__init__.py", line 1, in <module>
    from auto_satin import AutoSatin
  File "lib/extensions/auto_satin.py", line 3, in <module>
    import inkex
ImportError: No module named inkex
make: *** [inx] Error 1

**Comment by lexelby** [comment]
Welcome

**Comment by kaalleen** [comment]
Closing the issue now. Print preview should be working on macOS Catalina since version 1.27.2

Older macOS systems are sadly not supported at the moment (possible solution: older Ink/Stitch versions without the print preview or manual install).
