### ISSUE TITLE
Ink/stitch+inkscape freezes when attempting to apply params

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#546]
Not sure what im doing wrong but I just spent about an hour trying to digitize some text im using the default params for the satin columns along with a center walk underlay but it keeps freezing inkscape+ink/stitch.. the simulation works fine so theres no issues with the design itself (im assuming) and ive been able to apply params in the past before (for the most part, sometimes it freezes randomly on certain paths) but for this one its not working whatsoever.. not sure what i'm doing wrong.. Im using the latest ink/stitch release on MacOS

Here is example video: https://drive.google.com/file/d/1K06nMGoqTKMwGtZTxvvHPPFBEE4V6W42/view?usp=sharing

normally, when applying params it loads for just a few seconds then it applies them. in the video i only waited about 30 seconds but I tried waiting 14 mins just now and its still stuck.. ive tried ungrouping the groups as well but that didnt work either... It also freezes when i try applying params to the objects individually

UPDATE: I was able to make the params work by importing the SVG into a new file in inkscape but when saving it as a digitized file my machine was not able to read the file correctly. It would show up on my machine as a regular .pes file but when I select the file my machine quickly turns off and shows an error message. I tried re-saving the file a few different times in Inkscape making changes each time (ungrouping, deleting excess paths, etc.) but still the file was corrupt. I had to import the .pes file into "Sew What Pro" resized and re-save under a different name to eventually get it to work

**Comment by wwderw** [comment]
I can't help with the params issues as I don't have a Mac to test anything out on.  However, I may have a suggestion for this:

> It would show up on my machine as a regular .pes file but when I select the file my machine quickly turns off and shows an error message.

Do you happen to have any commands (depending on the machine, the trim command may be fine, but I'm thinking something like "stop" command or more of those "esoteric" commands that aren't used often) attached to objects?

If Sew What Pro doesn't have the ability to insert certain functions ("stop", "frame out" etc), when you save from that program, it may remove that extra info automatically.  Now, on my PR machines, I have gotten the screen to essentially reboot after selecting a file that had a "stop" command in it that didn't come from PE Designs (Brother's software).  No error msg, but the screen blanked and rebooted.  In the pattern selection menu it did look like a regular PES file.

That is what makes me wonder if something similar is going on here, but it would depend if you are entering other functions such as "stop" or "frame out" etc.  "Trim", like I said, should be ok, but that would depend on the model of machine that you are using.  Typically even if "trim" isn't supported within a color block on a single needle machine, it should just overlook the command and not send out an error msg.

**Comment by tyrosinase** [comment]
My PE-800 will freeze and quasi-reboot on two different cases: trim commands, and also when the embroidery file's dimensions fit within the hoop but the design was generated too far from zero in Inkscape.

Lettering is a pretty likely candidate for that since, at least for me, it defaults to generating way up high on the Y axis.

**Comment by fnavas00** [comment]
@wwderw  I don't ever use commands when using ink/stitch.. I dont really understand the function of them to be completely honest. But ive never had issues like this before so I dont know what could be causing this

**Comment by kaalleen** [comment]
I'll close the issue due to it's age. Ink/Stitch has evolved quite a bit. If anything like this happens again, please open a new issue.
