### ISSUE TITLE
Export Thread Change Chart

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#550]
I just, for the nth time, uploaded a zip file to WordPress without remembering to put the source SVG in it... I might be the only person who *wants* to distribute the source (the subtitle of the blog is "Open Source Sewing") but if it's not too difficult to add that feature I'd use the heck out of it.

**Comment by lexelby** [comment]
Definitely not difficult!  Great idea, too.  I like the idea of encouraging open source designs.

**Comment by tyrosinase** [comment]
And then can you put in the print instructions, and the picture of the finished project, and...

**Comment by lexelby** [comment]
Love it!  Thread change chart, perhaps?  Instructions for your amazing plushies!  The sky is the limit.

**Comment by lexelby** [comment]
Love it!  Thread change chart, perhaps?  Instructions for your amazing plushies!  The sky is the limit.

**Comment by tyrosinase** [comment]
On 10/4/19 11:08 PM, Lex Neva wrote:
>
> Love it! Thread change chart, perhaps? Instructions for your amazing
> plushies! The sky is the limit.
>
>
I joke, mostly: I could put the picture and instructions right in the
source SVG (yay layers and the fact that bitmaps and text just get
ignored during Embroider).

Although sometimes I do put instructions in the print version's thread
change steps, and it would be nice to have that saved out into the ZIP
for those who are just using the pre-gen embroidery files.
