### ISSUE TITLE
How is it possible to help for translating the website to french?

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#551]
I translate a very little part of the software to french. I imagine how it would be great to find all your explanations in french.
I use Inkstitch because I like the idea of an embroidery freesoftware. Now I succeed to create real designs and I do the most possible to show Inkstitch to french  embroiderers. 
I don't know to proceed for translating the website.

**Comment by lexelby** [comment]
@kaalleen do we have documentation on that?

@augusa The website is served out of the `gh-pages` branch.  Currently we have German and English, so it might be possible to guess how another language could be added.

**Comment by CatherineH** [comment]
Je peux essayer a traduire les descriptions, mais je vais avoir besoin d'aide avec la grammaire.

**Comment by Augusa** [comment]
I am not at all able to help in the technical part!

**Comment by kaalleen** [comment]
@Augusa Appreciate your offer to translate the website to French!!
I prepared the page to be ready for french translations.

On this page you find the pages listed, that need translations: https://inkstitch.org/developers/localize/

Jump to the french part.
From there you can work yourself through the list and click on the file paths from where you will land at the corresponding source file in our GitHub repository. If you are granted write access (@lexelby?!) you can change the files directly on GitHub and update the English text directly into your translation.
With every update don't forget to also change the date at the top of the file. This will help you to keep track of which files are already done (since they will disappear from the localize page).

If you rather work with a local copy of the website you might find the README file helpful:
https://github.com/inkstitch/inkstitch/tree/gh-pages

I hope this will help you to get started. If you need more information, please ask. I know that the description above might be a little too short.

**Comment by Augusa** [comment]
I tried with "Basic Usage". I hope my work is correct but if I see later something wrong, will it be possible to correct it. You say "they will disappear from the localize page.
Thanks for your help
________________________________
De : Kaalleen <notifications@github.com>
Envoyé : jeudi 10 octobre 2019 11:42
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating the website to french? (#551)


@Augusa<https://github.com/Augusa> Appreciate your offer to translate the website to French!!
I prepared the page to be ready for french translations.

On this page you find the pages listed, that need translations: https://inkstitch.org/developers/localize/

Jump to the french part.
From there you can work yourself through the list and click on the file paths from where you will land at the corresponding source file in our GitHub repository. If you are granted write access (@lexelby<https://github.com/lexelby>?!) you can change the files directly on GitHub and update the English text directly into your translation.
With every update don't forget to also change the date at the top of the file. This will help you to keep track of which files are already done (since they will disappear from the localize page).

If you rather work with a local copy of the website you might find the README file helpful:
https://github.com/inkstitch/inkstitch/tree/gh-pages

I hope this will help you to get started. If you need more information, please ask. I know that the description above might be a little too short.

**Comment by kaalleen** [comment]
Yes, of course. No worries!
Hm, maybe I should automatically add a link to the source at the end of every page.
So everyone can find it easily, even if the translation is up to date.

**Comment by kaalleen** [comment]
Ok, each page has now a link to the page source in the articles footer (right beside the "updated" info). Hope that is of help!

**Comment by Augusa** [comment]
Thank you.
I try your link to translate index which I did not find in localization. I just have the idea to start with the biginning! Does it change anything to use the link or to open the file in localization?

-------- Message d'origine --------
De : Kaalleen <notifications@github.com>
Date : 11/10/2019 19:01 (GMT+01:00)
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>, Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating   the website to french? (#551)


Ok, each page has now a link to the page source in the articles footer (right beside the "updated" info). Hope that is of help!

**Comment by kaalleen** [comment]
No, it should be exactly the same link.
Haven't noticed that the index page didn't show up though.

**Comment by Augusa** [comment]
Of course a new question!
I translated several files and clicked on "Propose file change". Now I ask me if I have something else to do. I don't find the translated files. As you said they disappeared. Can you explain me how to go on? The most difficult is not the translation but to understand how to work with github!

**Comment by kaalleen** [comment]
I don't see any changes at the files. From where did the files disappear?
Are you member of the Ink/Stitch repository?
I'd all be easy to understand if you are.
@lexelby could make you a member and you will be able to change the files in the gh-pages branch right away.

**Comment by lexelby** [comment]
Oh shoot, I forgot to add Augusa.  I'm not at my computer right now, but @kaalleen, you can actually add people too.  I made you an owner awhile back :)

**Comment by kaalleen** [comment]
Oh, I wasn't aware I was supposed to have this privilege, so I didn't bother to try it out, sorry ;)

But still, not sure if that is really the case?!?
In the "[people list](https://github.com/orgs/inkstitch/people)" I am listed as a member and there is no button to invite somebody? Am I looking at the wrong place?

**Comment by kaalleen** [comment]
Nevermind :) Found the right place.

**Comment by Augusa** [comment]
Thanks for the invitation. But now I need help to work correctly and not loose my translations. Is-it possible to explain me exactly what I have to do. I don't understand what are fork, branch and so on. The whole part "documentation" was translated. I don't want to redo it without being completly sure it works.


________________________________
De : Kaalleen <notifications@github.com>
Envoyé : mercredi 16 octobre 2019 07:29
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating the website to french? (#551)


Nevermind :) Found the right place.

**Comment by lexelby** [comment]
Oh, I don't think you need to redo it all!  It looks like your changes may be right here in a series of branches: https://github.com/Augusa/inkstitch/branches

**Comment by lexelby** [comment]
We can probably reconstruct your translation from that.  My free time is severely limited right now but hopefully sometime with git knowledge can help reconstruct your changes.

**Comment by Augusa** [comment]
It's  good news for me and for Inkstitch.
Now I wait for your help. I think I wait for having the right method before going on with translation.
Thank you

-------- Message d'origine --------
De : Lex Neva <notifications@github.com>
Date : 16/10/2019 13:03 (GMT+01:00)
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>, Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating   the website to french? (#551)


We can probably reconstruct your translation from that. My free time is severely limited right now but hopefully sometime with git knowledge can help reconstruct your changes.

**Comment by Augusa** [comment]
@kaalleen or @lexelby Please tell me if my new try with  Update 003-001-manual-stitch.md is correct. I have a few time to translate now. 
Thanks

**Comment by kaalleen** [comment]
Looks good. The website already updated and shows your changes. I am not sure, why it is showing the outdated info though, since you updated the date correctly. Could be an error on my side or a caching issue. I will have a look into it when I find the time. 
You are doing a good job here.

**Comment by danielkschneider** [comment]
@kaalleen and @lexelby you got this nice french community going. Over 80 participants in their facebook group. Some with high embroidery skills, some absolute beginners. 
In case they also want to take over localization of the software strings on crowdin, please let them (I don't know if one needs special permission to approve translations that I have got). But I'll continue doing it until someone with better french is willing to pick it up :)

**Comment by lexelby** [comment]
We don't have to grant them anything to let them translate the software on CorwdIn.  We just have to approve translations, so just make sure they ask us or you to do so :)

**Comment by kaalleen** [comment]
@Augusa One file I forgot to mention so far: https://github.com/inkstitch/inkstitch/blob/gh-pages/_data/navigation_fr.yml

This file is for the menus. Just translate the title strings, links are already set correctly.

**Comment by Augusa** [comment]
@kaalleen<https://github.com/kaalleen> and @lexelby<https://github.com/lexelby>
I have create a huge stupidity. I recovered the page workflow and the index but now for this 2 pages the french appears at the place of english and english at the place of french. I am very sorry because I don't see how to repare myself this mistake and I don't dare to do anything because I am affraid to do worth.
Do you think it is possible to repare my stupidities?
Sorry


________________________________
De : Kaalleen <notifications@github.com>
Envoyé : samedi 19 octobre 2019 10:59
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating the website to french? (#551)


@Augusa<https://github.com/Augusa> One file I forgot to mention so far: https://github.com/inkstitch/inkstitch/blob/gh-pages/_data/navigation_fr.yml

This file is for the menus. Just translate the title strings, links are already set correctly.

**Comment by kaalleen** [comment]
No worries. Nothing here that cannot be fixed ;)

GitHub will save the history of changes for each file, so everything you do can be reversed if necessary. In this case though I simply swapped the files to keep your translation.

**Comment by Augusa** [comment]
Thank you very much.

-------- Message d'origine --------
De : Kaalleen <notifications@github.com>
Date : 20/10/2019 08:18 (GMT+01:00)
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>, Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating   the website to french? (#551)


No worries. Nothing here that cannot be fixed ;)

GitHub will save the history of changes for each file, so everything you do can be reversed if necessary. In this case though I simply swapped the files to keep your translation.

**Comment by Augusa** [comment]
Something new today. I translate several files which works fine but after translation the file 003-000-stitch-library.md makes an error 404 in the page Stitch library. Can you have a look to this problem, please.
Thanks
________________________________
De : Kaalleen <notifications@github.com>
Envoyé : dimanche 20 octobre 2019 08:18
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Augusa <lyogau@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] How is it possible to help for translating the website to french? (#551)


No worries. Nothing here that cannot be fixed ;)

GitHub will save the history of changes for each file, so everything you do can be reversed if necessary. In this case though I simply swapped the files to keep your translation.

**Comment by kaalleen** [comment]
Closing this now. Thank you @Augusa for all your hard work at the website. Please reopen, if you have more questions that you think fit into here!
