### ISSUE TITLE
Design not properly tracing on machine

### ISSUE THREAD

**Issue by spenceryeager** [inkstitch/inkstitch#553]
Hello,

Is there a way to define the "bounds" of the design inside of Ink/Stitch? When I digitize my design, set the origin point of the design to the center, make the document size equal to that of the design itself, and save the .DST file to a floppy disk (that's how my machine reads the information), the machine will not trace the design properly. Instead of tracing in the center of the hoop, where the design is intended to be, the machine will move entirely to the rear left corner before having to manually stop the machine. I'm not sure what is causing this issue, and am wondering if I am missing a step in the digitizing process. If there is any additional information needed, I can provide it.

**Comment by tyrosinase** [comment]
On 10/13/19 7:23 PM, spenceryeager wrote:
> Is there a way to define the "bounds" of the design inside of
> Ink/Stitch? When I digitize my design, set the origin point of the
> design to the center, make the document size equal to that of the
> design itself, and save the .DST file to a floppy disk (that's how my
> machine reads the information), the machine will not trace the design
> properly. Instead of tracing in the center of the hoop, where the
> design is intended to be, the machine will move entirely to the rear
> left corner before having to manually stop the machine. I'm not sure
> what is causing this issue, and am wondering if I am missing a step in
> the digitizing process. If there is any additional information needed,
> I can provide it.


I don't know about DSTs, but I know on my PES-based machine that it's
particular about the origin point. I have to leave it in the lower left
of the Inkscape page, and make sure my design falls entirely within the
hoop size (though it doesn't care about portrait vs. landscape) even
though the machine will center the design in the hoop no matter where it
is on the Inkscape page. E.g. if I am embroidering a little 1x1" polo
design I can stick it clear out at X+6 Y+4 and it will center it in the
hoop, but if I put it at X+6.5 Y+4 it won't work (and in fact will crash
my machine... which seems like a pretty extreme response 🤷)

So, long-story-short, try putting the origin back in the lower left of
the page on Inkscape.

**Comment by spenceryeager** [comment]
> 
> On 10/13/19 7:23 PM, spenceryeager wrote: Is there a way to define the "bounds" of the design inside of Ink/Stitch? When I digitize my design, set the origin point of the design to the center, make the document size equal to that of the design itself, and save the .DST file to a floppy disk (that's how my machine reads the information), the machine will not trace the design properly. Instead of tracing in the center of the hoop, where the design is intended to be, the machine will move entirely to the rear left corner before having to manually stop the machine. I'm not sure what is causing this issue, and am wondering if I am missing a step in the digitizing process. If there is any additional information needed, I can provide it.
> I don't know about DSTs, but I know on my PES-based machine that it's particular about the origin point. I have to leave it in the lower left of the Inkscape page, and make sure my design falls entirely within the hoop size (though it doesn't care about portrait vs. landscape) even though the machine will center the design in the hoop no matter where it is on the Inkscape page. E.g. if I am embroidering a little 1x1" polo design I can stick it clear out at X+6 Y+4 and it will center it in the hoop, but if I put it at X+6.5 Y+4 it won't work (and in fact will crash my machine... which seems like a pretty extreme response 🤷) So, long-story-short, try putting the origin back in the lower left of the page on Inkscape.

When you say "hoop size", are you saying that you set your document size to be the size of the hoop you are using?

**Comment by tyrosinase** [comment]
On 10/13/19 8:46 PM, spenceryeager wrote:
>
>
> When you say "hoop size", are you saying that you set your document
> size to be the size of the hoop you are using?
>

I do, though I don't think that affects anything other than keeping me
from forgetting what I'm doing.

**Comment by spenceryeager** [comment]
> 
> On 10/13/19 8:46 PM, spenceryeager wrote: When you say "hoop size", are you saying that you set your document size to be the size of the hoop you are using?
> I do, though I don't think that affects anything other than keeping me from forgetting what I'm doing.

Okay, thank you! I will try your suggestion of leaving the origin point at the corner of the document or where ink/stitch places automatically and see if that helps

**Comment by wwderw** [comment]
If the DSTs are going on machines (like Brothers) that have hoops calibrated to the design field size, I would highly suggest that you make your Inkscape design field the size of the hoop that you are intending to use.  Doesn't matter if you are using PES or DSTs or any other format that a Brother (or similar machine) may use.

If using something like a Barudan, then it doesn't matter, because those machines are intended to be manually calibrated with each design.

I have both Brother and Barudan and I still make the Inkscape design field the same size of the inner bounds of the hoop (including pressure feet margins).  I don't think it matters otherwise where the origin is, but I do think design field size, as was already mentioned) would help the most.

**Comment by kaalleen** [comment]
@spenceryeager Is this still an issue with the new Ink/Stitch version (v1.28.0)?

**Comment by lexelby** [comment]
We're going to close this now, but if you're still having this issue, please do feel free to reopen it and we'll take a look.
