### ISSUE TITLE
Convert SVG to PES

### ISSUE THREAD

**Issue by arather1** [inkstitch/inkstitch#554]
Hello! I am trying to convert an SVG image to PES using Ink Stitch. When I try to convert my image to a path, the bottom menu says, "No objects to convert to path in the current selection." Since I can't convert to a path, I can't open the Params correctly either. I was initially using a SVG that I created in Photoshop, but I saved it as an Inkscape SVG, and it didn't fix it. Any help would be much appreciated!

**Comment by danielkschneider** [comment]
Probable you don't have a drawing, but a raster image.
If that is the case, try converting this to a drawing by tracing it. https://inkscape.org/en/doc/tutorials/tracing/tutorial-tracing.html
- greetings

**Comment by arather1** [comment]
This solved my problem! Thanks a bunch, Daniel!
