### ISSUE TITLE
Export Realistic Preview as PNG Image

### ISSUE THREAD

**Issue by markusikul** [inkstitch/inkstitch#558]
How to import a SVG file and convert it into a PNG effect by embroidery from the command line linux,?

**Comment by kaalleen** [comment]
Not sure what you mean exactly?

Right now, we do not support a png export through our embroidery extension at all (maybe through the print preview, but this doesn't count here). With Inkscape you can export to png. But I am not sure what a png effect would be?

**Comment by tyrosinase** [comment]
It sounds like "convert an SVG file into a realistic embroidery preview PNG from the command line" to me.

**Comment by kaalleen** [comment]
Oh, I see, thank you. That makes sense.

**Comment by capellancitizen** [comment]
This has been implemented in the intervening time with the realistic PNG export option.
