### ISSUE TITLE
Print/Export PDFs straight to save to folder

### ISSUE THREAD

**Issue by tyleralberti** [inkstitch/inkstitch#560]
Hi guys, Im using a Macbook Pro running OSX Mojave with Inkscape 0.92 and current version of Inkstitch, and Im having issues with the Inkstitch GUI window that pops up after I click Print / Realistic Preview, where the window opens but nothing displays, has anyone else had this issue ? 

Ive attached a screenshot -

**Comment by tyleralberti** [comment]
<img width="1680" alt="Screen Shot 2019-10-28 at 8 09 57 am" src="https://user-images.githubusercontent.com/1744370/67642754-b2951b80-f95a-11e9-9486-5d5bc0d9d934.png">

**Comment by lexelby** [comment]
I'm afraid this is a known issue with Ink/Stitch on Mac. :(  Try opening http://localhost:5000/ in your browser while that blank window is open.

Right now, we don't have anyone who has both a Mac and the skills/interest in helping us debug this issue.  Once we find someone, hopefully we can figure out the problem.

**Comment by fnavas00** [comment]
I really wish I knew about programming id love to help you guys out with "Ink/Stitch" anyway I could @lexelby if you ever need anyone to do some 3D animations or artwork let me know

**Comment by lexelby** [comment]
We're starting to redo the entire UI and I'm sure we'll need some artwork, so I'll let you know!

**Comment by fnavas00** [comment]
What do you mean by the UI?

**Comment by lexelby** [comment]
The Params window, Simulator, Lettering tool, and Print PDF.  The ultimate goal is to combine all of those into one coherent interface.

**Comment by stoffsuchti** [comment]
@lexelby you are the extension making look more like a „normal“ embroidery Software?

**Comment by lexelby** [comment]
Maybe?  Not exactly, though.  Ink/Stitch will continue to use Inkscape for the core vector editing.

**Comment by jhstory** [comment]
what needs to be setup on mac to help with this issue? i would be willing to help and have looked at developers docs: https://inkstitch.org/developers/inkstitch/manual-setup/ but this doesn't look up to date.

i have inkscape 1.0 beta 2 with inkstich installed. i'm getting same issue of blank or white screen when inkstitch-gui is rurn.

**Comment by lexelby** [comment]
Oh, thank you for the offer!  I did finally discover what was wrong and have a fix cued up.  Now I just need to fix up our build system so that a new release is built properly.  My time has been pretty severely limited lately but I'm hoping to get this done and get a new version released the last week of January.

**Comment by bkgoodman** [comment]
I am having this with Sierra, too. localhost:5000 said it "could not connect" (with the inkstitch-gui window open).

If you need more help debugging please let me know. Thanks for all your work! Our Makerspace wants to get an embroidery machine but doesn't want to blow $2k on software to let us really create - so I think Inkstitch is really going to be a big deal for us!!

**Comment by lexelby** [comment]
Thanks for the offer of help!  We've already figured out the problem and put a fix in place.  Keep an eye out for a release with a fix soon.

> If you need more help debugging please let me know. Thanks for all your work! Our Makerspace wants to get an embroidery machine but doesn't want to blow $2k on software to let us really create - so I think Inkstitch is really going to be a big deal for us!!

Ooh, where's your makerspace?

**Comment by bkgoodman** [comment]
Excellent, Thanks!
MakeIt Labs
Nashua, NH
[http://www.makeitlabs.com](http://www.makeitlabs.com)

**Comment by lexelby** [comment]
Whoa, seriously?!  I'm less than an hour from there, in central(ish) MA!  I've been keeping an eye on the makerspaces nearby to see if one had a machine, but so far I think yours will be the only one.

**Comment by bkgoodman** [comment]
Open house is every Thursday night - come on down! 
We're also very actively trying to figure out what kind of machine to get - so any input/expertise would be appreciated!

**Comment by lexelby** [comment]
I already sent you folks an email along those lines :)

**Comment by tyrosinase** [comment]
There's a makerspace back in Wichita that has a long-arm quilter and, IIRC, an embroidery machine. I will definitely be looking into that when we move back there.

(Pretty sure some Philly ones have machines but (1) they all have long waitlists for membership and (2) not sure if schlepping stuff on the train or driving into Philly is worse.)

(j/k driving into Philly is totally worse)

**Comment by bkgoodman** [comment]
I'm not a quilter - but I was talking about (in the context of getting an embroidery machine) - that getting a long-arm quilter is one of the things that would attract other "makers". We typically focus more on stuff like lasers, 3d printers, auto, metal, woodwork - but there's a big community of makers interested in the "softer" stuff, too. I'm kind of hoping the embroidery stuff will be a fore into that.

**Comment by kaalleen** [comment]
> I am having this with Sierra, too.

Actually, our new release will not be working on Sierra at all :(
For now, we only support Catalina. The reason is, that our new build system won't work for Sierra. It might be possible in the future: https://github.com/inkstitch/inkstitch/pull/573#issuecomment-557895200

**Comment by tyrosinase** [comment]
I'm not a quilter either but a computerized longarm quilter is basically a giant embroidery machine and I'm very curious about playing with one. (But I'm concerned that if I hang out in the local quilting shop learning how to use one I *will* end up being a quilter, so I haven't done it there.)

**Comment by KaiBuskirk** [comment]
I purchased a Laptop PC to run Next to my Mac...
Instead of in browser preview for the Mac 
Can we just Print/Export pdfs straight to save to folder then review pdf in acrobat
I push the file over to my PC for 
Print Preview and save it back to my primary folder ... it’s def the long way around but in workflow it’s doable...
Would love a chat!
Setting up a cloud based distributed MakerSpace CO-LAB would love to help
Cheers
[k]ai

**Comment by lexelby** [comment]
> Can we just Print/Export pdfs straight to save to folder then review pdf in acrobat

I'm afraid that's not possible. :(  The PDF is exported by the GUI component which is based on Chrome Browser.  We effectively do "print to PDF" behind the scenes.  Without the GUI, we don't have the ability to export a PDF.  Sorry!

**Comment by kaalleen** [comment]
> Setting up a cloud based distributed MakerSpace CO-LAB would love to help

Sounds interesting? How does it work?
