### ISSUE TITLE
Is it possible to use re-positional hoop with "ink/stitch"

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#561]
Is there any way of finessing a design on ink/stitch to work with a re-positional hoop? I bought a hat hoop frame on amazon for $70 that requires a SA434 overlap hoop to work.. now I need to spend another $20-$30 for a re-positional hoop to see if the hat frame will even work with my machine.

**Comment by wwderw** [comment]
I think you mean multi-positional.  For instance, the hoop that you specifically referenced won't allow for some home machines to stitch bigger then a 4 x 4 field at any one given time, but will allow for multiple designs that fit within that hoop space to be stitched out without needing to be re hooped.

If this is what you mean, you wouldn't use Ink/Stitch any different then you would any other 3rd party software with working with this type of workflow.

Either segment one larger design into smaller portions (not bigger then 4 x 4 portions) and/or manually add (at the machine) each individual design, stitching out one at a time. 

I mentioned 3rd party software, typically Brother has software that usually allows for auto segmenting designs (not always the best places to segment designs and leave "harsh" seams), but I don't know if they do for the single needle home machines.  I know they do for the PR line, I would assume something like that would be available for their home line, but I'm speculating.

**Comment by lexelby** [comment]
I would love to support these kinds of hoops, since home users with small machines area really or bread and butter.  Check out #182 for some ideas.

**Comment by fnavas00** [comment]
I wish there was more videos of this online.  Especially INK/STITCH videos!! The concept is pretty straight forward but in practice it never results the way i'd like. Especially trying to align multiple designs. I've only tried this a few times in the past but I digitized a piece of art in ink/stitch and exported each layer individually as PES files.. in my mind i thought it would arrange the files like the objects are arranged in inkscape (i.e. it would maintain the same shape and position on the X,Y axis withing the 4x4 page border) but for some reason the objects always come out centered or they are slightly bigger. Sure you could manually align/size the designs but it never comes out perfect.. idk maybe i did something wrong.

**Comment by lexelby** [comment]
Try using the Origin command, in the commands/add command extension.

**Comment by wwderw** [comment]
The old fashion way is to print out a picture of the entire design and then mark the substrate accordingly for the placement.  Still takes practice to get a workflow down that works for you, but doable.  No matter what machine one has, there is always going to be a customer that's going to want a design that exceeds the bounds of the biggest hoop

**Comment by kaalleen** [comment]
Closing the issue in favor of #182 (Automatic splitting of designs for small machines)
