### ISSUE TITLE
auto-fill gets stuck at the end

### ISSUE THREAD

**Issue by DreadKnight** [inkstitch/inkstitch#563]
Heya, I have this file and I keep receiving an error when I try to see simulation for all the shapes or when I try to export, though all the shapes work just fine individually. Here's the stuff I get:

>sq (path1280): error: Error during autofill!  This means that there is a problem with Ink/Stitch.

>If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

>Traceback (most recent call last):
  File "lib/elements/auto_fill.py", line 218, in to_patches
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 64, in auto_fill
  File "lib/debug.py", line 125, in decorated
  File "lib/stitches/auto_fill.py", line 568, in path_to_stitches
  File "lib/stitches/auto_fill.py", line 533, in travel
  File "site-packages/networkx/algorithms/shortest_paths/generic.py", line 172, in shortest_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 163, in dijkstra_path
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 472, in single_source_dijkstra
  File "site-packages/networkx/algorithms/shortest_paths/weighted.py", line 738, in multi_source_dijkstra
NetworkXNoPath: No path to (259.91566874868806, 185.0848408813873).

Here's the svg file as a zip: [epolet patrat comandant.zip](https://github.com/inkstitch/inkstitch/files/3794208/epolet.patrat.comandant.zip)

**Comment by DreadKnight** [comment]
I've managed to bypass the error by moving the end point of the 4th rectangle to a place near where the diamond like shape starts...

**Comment by lexelby** [comment]
Thank you!  I was able to reproduce that error using your SVG.  Now I just have to figure out why it happens :)

**Comment by lexelby** [comment]
Whew, that's a tough one.  The auto-fill algorithm seems to get stuck on the border of the hole in the diamond.  It's already finished filling the entire shape, so it has nowhere that it can underpath to escape.  I thought that the algorithm wasn't able to get stuck like that, but apparently I've missed something.  I'll have to do more research.

It makes sense that changing the ending point of the previous shape (the 4th rectangle) helps.  That's effectively the same as setting the starting point on the diamond, and nudging it a little is probably enough to avoid getting stuck at the end.  Obviously I don't want you to have to do that, though :)

BTW, if it's all the same to you, you can just combine that last rectangle with the diamond shape to make one big fill shape.  I'm guessing you probably have them separate for a reason though.

**Comment by DreadKnight** [comment]
@lexelby I have a talent for bumping into issues; should probably report them way more often though.
I'm aware I can merge shapes for a while now. Initially got a bad impression that I couldn't because I had some errors in a file and didn't knew how to troubleshoot the problem, but it's all good now overall.

**Comment by lexelby** [comment]
We definitely appreciate when you do have a chance to report issues. :)  And we know it takes effort to do so!

**Comment by kaalleen** [comment]
@lexelby can this be closed? I think it was fixed through #606 ?

**Comment by kaalleen** [comment]
The provided file works in Ink/Stitch v.1.28.0
