### ISSUE TITLE
Janome File Reading 

### ISSUE THREAD

**Issue by MK-12-20MM** [inkstitch/inkstitch#565]
I don't think this is an Inkstitch issue, but something more along the lines that I am missing something or considerations with the machine I use. @lexelby has the same machine (Janome 400E).  No issues with Inkstitch or errors but a lot of times a get **"Do you want to delete the damaged or unknown data"**  when the machine reads the file.  You can see the file in the folder on the machine but it's greyed out. Apparently the machine does not like something in the file after reading the jef file. 

 Work around has been by placing for example a run stitch in other areas of the field.  I thought maybe the field area (document size > hoop size) but even making this smaller and or equal to hoop size does not eliminate.  Pretty much trying all kinds of stuff in the past few months to isolate what I am doing wrong to cause this.  I can always work around by adding more sacrificial stitches  off to the side or other areas,  but it's an annoyance at best.  I know it has to do with hoop vs design but but even large designs that take up majority of the hoop area, this issue pops up. 
![IMG_20190331_102620](https://user-images.githubusercontent.com/10312448/68087889-6137d100-fe1f-11e9-9554-0e8a9900c3c6.jpg)
 Obviously I am missing something.  Thanks..

**Comment by lexelby** [comment]
I have good news and bad news!

The good news is that I totally see this problem with my machine too.  The bad news is that I have no idea what's doing it so far. :(

On one design, I had the Origin command added with Commands->Add Commands.  If I delete it, that design no longer shows as corrupted.

I think this may have to do with the dimensions.  Maybe if a design has any stitch more than 4 inches from the origin in the x or y direction, it shows as corrupted?  If you have the time to do some scientific experiments and narrow this down, that would be really cool!

**Comment by MK-12-20MM** [comment]
I did play around with this and if you cancel the the error popup on the machine the response is a hoop size. 

 So I think janome is looking at the content size and document size to determine which loop to use. Most of the time I use the large hoop (200mm x 200mm).  So putting a 10x10 mm square at the edge and moving it in towards the center it picked it up or worked when the content was inside 140x140 mm hoop.   So I think that if you are using the larger hoops and the 400e thinks this content can fit in a smaller hoop, but if the content is outside the hoop (region) the machine thinks you should be using, then it chokes.  I think for the smaller hoops this may not matter as my test content was small and there a smaller hoops available. Just seems to be a problem if your content is smaller than the 140x140mm hoop but placed outside that region when using the 200mX200m size.  But when I get a chance I will move smaller document size to the 140x140 and see if the same effect occurs.   

 Pretty much makes sense what you are doing with the origin.  I found in document properties resizing to content as well will fix this.  Seems the machine insisting on what hoop based on content size no matter what and calling files bad if you don't comply. 

I am just starting out with this stuff so maybe there is a better explanation as I don't know if other machines force compliance in some form or to what extent.

**Comment by lexelby** [comment]
Interesting!  As far as I can remember, JEF files have some bits that say which hoop sizes the design fits in.  Maybe we're screwing that calculation up...

**Comment by MK-12-20MM** [comment]
Just wanted to elaborate more how I got to this.

To get to what I stated above (usecases) and what you indicated about the origin, I  did a small small square in each each of the corners in separate files, one square upper left, one upper right etc for example. None of them would work for each of the corners using the 200x200 mm hoop.  I figured the the lower left would work assuming the  default origin is 0,0  of the svg and that square would be closest to the origin, which of course did not work.

 That's when I started moving one square closer in increment files to the center of the hoop, in 10mm increments until the content was inside 140x140mm hoop size to not reject the file. I have never paid much attention when using the bigger hoop but when it worked for this test the hoop size indicated by the machine was 140x140mm even though the hoop was the big one and document size was 200x200 mm.

**Comment by MK-12-20MM** [comment]
One thing I did notice - 400e supports these hoops..

Q20b Hoop (200 x 200 mm) (7.9" x 7.9") 
RE20b Hoop (140 x 200 mm) (5.5" x 7.9") 
SQ14b Hoop (140 x 140 mm) (5.5" x 5.5") 
RE10b Hoop (optional) (40 x 100 mm) (1.5" x 5.5")

in the jefwriter... 

# These are in mm, embroidery units are 1/10 mm
HOOP_110X110 = 0
HOOP_50X50 = 1
HOOP_140X200 = 2
HOOP_126X110 = 3
HOOP_200X200 = 4

**Comment by jameskolme** [comment]
I have Memory Craft 500 and this error was maybe too common at some point. Not sure is this correct assumption, but bad file comes from oversize or miss placed embroidery design. Yet I have a different hoop set to work with. The best fix is to use hoop size templates from Inkscape. Making sure everything fits like it should Janome reader is really good software to preview, but templates are what works for me.

**Comment by lexelby** [comment]
Nice spotting in the code, @mk-12-20mm.  I think you're really onto something with this being about hoop sizes.

One thing that may help your understanding: by default, if you don't add Ink/Stitch's Origin command symbol, it will use the center of the canvas as 0,0 rather than the SVG origin.

**Comment by tyrosinase** [comment]
On 11/4/19 8:19 AM, Lex Neva wrote:
>
> Nice spotting in the code, @MK-12-20MM
> <https://github.com/MK-12-20MM>. I think you're really onto something
> with this being about hoop sizes.
>
> One thing that may help your understanding: by default, if you don't
> add Ink/Stitch's Origin command symbol, it will use the center of the
> canvas as 0,0 rather than the SVG origin.
>

Given the number of times that this issue gets raised (and the fact that
Brothers just crash inexplicably), maybe Ink/Stitch should figure the
center of the *design* when there's no Origin set?

(also how did I never notice there was an Origin command? Now I need to
see how/if it affects Brothers, which seem to like to center designs
regardless)

**Comment by MK-12-20MM** [comment]
Thanks (@lexelby )  for the info about default origin. Learn something new.. :)


The info about the hoops I got from the Janome site looks like they have 

RE10b Hoop (optional) (40 x 100 mm) (1.5" x 5.5")

But is actually  for the inch measurement:
3.9” x 1.6”

I have not played with command origin yet. Using the template if your content is smaller than 140x140 MM and moved outside the 140 region it will choke. Canceling the delete data the response from the machine is the RE10b hoop (that does not make sense). Now if the content is above 140 regardless of placement the big hoop is chosen by the machine and proceeds. 

Maybe my thought process is wrong for this since I am learning this stuff, as if I am using the large hoop I should be able to place the content regardless of what size anywhere within the hoop boundary and not forced to center it as I may not want the content centered.  Maybe a wrong assumption.

**Comment by lexelby** [comment]
@tyrosinase Well.... I have to admit, now that you say that, I might be remembering wrong. ;)  It might put the origin at the center of the design already.  I'll have to look.

**Comment by lexelby** [comment]
It's in output.py if anyone has a chance to look.

**Comment by MK-12-20MM** [comment]
Looks like it to me - comment indicates that is the default  and code is  simply dividing doc size by 2 for each dimension to center the origin point as I take it (if no origin command is assigned) 

`def get_origin(svg):
    origin_command = global_command(svg, "origin")

    if origin_command:
        return origin_command.point
    else:
        # default: center of the canvas

        doc_size = list(get_doc_size(svg))

        # convert the size from viewbox-relative to real-world pixels
        viewbox_transform = get_viewbox_transform(svg)
        simpletransform.applyTransformToPoint(simpletransform.invertTransform(viewbox_transform), doc_size)

        default = [doc_size[0] / 2.0, doc_size[1] / 2.0]
        simpletransform.applyTransformToPoint(viewbox_transform, default)
        default = Point(*default)

        return default
`

**Comment by MK-12-20MM** [comment]
Interesting side note:

I messed  with the editor in the machine as you can change hoop sizes with the built in designs. I used one of the petite which was 34x34mm.  I changed the hoop to the big one as it came up with SQ14b by default.  Moved it to upper left in the editor.  The machine resized it to like 96mm x 97mm (design size indication in the pattern information screen).  Just moving it around a bit farther from center the larger it got. If you put it back to center it was the original size.  I tried the resize option which works but pushing it out to the edge of the hoop made it larger just like above.

**Comment by kaalleen** [comment]
> Given the number of times that this issue gets raised (and the fact that
> Brothers just crash inexplicably), maybe Ink/Stitch should figure the
> center of the *design* when there's no Origin set?

#576 Should change the output behavior to do exactly this.
Testing appreciated :D

**Comment by MK-12-20MM** [comment]
Thanks. Will give the solution some test runs on my machine.

**Comment by kaalleen** [comment]
Great, the files can be downloaded here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-design-size-output

The windows build fails at the moment, this is not an issue of this branch but an overall problem.

**Comment by MK-12-20MM** [comment]
I saw that. No problem here, I can do linux as well. :)

**Comment by MK-12-20MM** [comment]
Confirmed that the fix (Janome) will "The output should use the center of the design rather than the center of the document".  Observed that design will always be centered on origin regardless of document size, design size and placement by to avoid the Janome "Do you want to delete the damaged or unknown data"

Thanks
