### ISSUE TITLE
Crashes Brother SE600

### ISSUE THREAD

**Issue by callieko** [inkstitch/inkstitch#566]
The file seems fine (the preview is accurate on both my computer and my machine) and I had no errors within inkscape but when I select it on my sewing machine to start the embroidery, the machine crashes and does a hard reset. I've updated my ink/stitch to the latest version and tried several exports of the same file. I'm using Inkscape 0.92.4 on Windows 7 and I have a Brother SE600. Workflow:

1. Design created in Inkscape
2. Save as .pes
3. Move to flashdrive and safe eject
4. Turn on machine and select USB as embroidery source
5. Select my file
6. Machine crashes and asks me to restart the machine

**Comment by tyrosinase** [comment]
On 11/3/19 6:55 PM, callieko wrote:
>
> The file seems fine (the preview is accurate on both my computer and
> my machine) and I had no errors within inkscape but when I select it
> on my sewing machine to start the embroidery, the machine crashes and
> does a hard reset. I've updated my ink/stitch to the latest version
> and tried several exports of the same file. I have a Brother SE600.
> Workflow:
>

Move the design closer to the origin of the page. Brothers get
super-confused when a design fits in the hoop but is placed too far out,
Inkscape-wise. It does fine rotating horizontal designs to vertical, but
it loses its mind trying to relocate a design into the hoop. 🤷

**Comment by callieko** [comment]
That was the problem exactly. I wasn't totally clear on how the canvas space translated to hoop space but it's pretty clear now. Moved it to the center and no problems. You guys have an impressively active project here.
