### ISSUE TITLE
G-code : Z : alternate value

### ISSUE THREAD

**Issue by JustGand** [inkstitch/inkstitch#567]
Could it be possible to alternate Z value instead of going down all the way ?

To have :
>G0 X0.0 Y0.0
>G0 X-6.113 Y-3.844
>G0 Z2.0
>G0 X-6.846 Y-4.000
>G0 Z0.0
>G0 X-7.580 Y-4.157
>G0 Z2.0
>G0 X-6.846 Y-4.000
>G0 Z0.0
>G0 X-6.113 Y-3.844
>G0 Z2.0

instead of :
>G0 X0.0 Y0.0
>G0 X-6.113 Y-3.844
>G0 Z2.0
>G0 X-6.846 Y-4.000
>G0 Z4.0
>G0 X-7.580 Y-4.157
>G0 Z6.0
>G0 X-6.846 Y-4.000
>G0 Z8.0
>G0 X-6.113 Y-3.844
>G0 Z10.0

It would not result in any difference as g-code machines' Z are hardwired (as it's wrong to have the sewing machine motor run backward).
And it has two pros :
1/ the g-code visualisation would be easier to understand.
2/ when homing, it would avoid a lot of unwanted stitches when Z is zeroing.

**Comment by lexelby** [comment]
Great idea!  Totally doable.

**Comment by JustGand** [comment]
Do you think it is to be implemented in the foreseeable future ?
I ruined a pretty long embroidery because the machine homed at the end (my mistake), and by the time i managed to hit the reset button, i had at least 100 stitches on the same place ...

**Comment by jameskolme** [comment]
Placing G92 Z0.0 before M30 should reset Z to 0. Alternating Z value would be better option still.

**Comment by JustGand** [comment]
@jameskolme that's such a good idea !
