### ISSUE TITLE
Weird color conversion on brother

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#568]
Not really a bug (probably) but ye olde Brother PE-800 came up with an interesting thread color for me today: 
![image](https://user-images.githubusercontent.com/9473609/68223455-d25fbb80-ffba-11e9-9b97-69744a216e4b.png)

According to the print preview, the color (converted from an imported PES using Madeira colors) is 255, 178, 178, and I wonder if 255 is a special indicator for Brother/PES.

Stitched out normally, FWIW, so it doesn't really matter.

**Comment by wwderw** [comment]
Those symbols are indicative a stitch type then thread color.  That is strange.

**Comment by tyrosinase** [comment]
On 11/5/19 4:16 PM, wwderw wrote:
>
> Those symbols are indicative a stitch type then thread color. That is
> strange.
>

Right? It's particularly odd because my machine is embroidery-only. I
mean, I'm sure there's plenty of commonality in the computer bits, but
still.

The fact that the thing displayed a correct color on the little
thread-spool preview is interesting. As is the fact that it went ahead
and stitched it normally. It may very well just be a bug in the Brother
display processing.

**Comment by tyrosinase** [comment]
I found another magical color!

For what it's worth, this one is f3930aff within Inkscape; I'm using the Brother embroidery palette (more or less) but I didn't actually set a thread color on this, it's just whatever Inkscape decided when I converted the bitmap. Apparently it means something special within PES but, again, the PE-800 stitches it out like it's an ordinary color.

(Also these are ear savers, I'll have the files up on the blog for these, plain ones, and delivery truck ones tomorrow or so.)

![IMG_20200507_155117](https://user-images.githubusercontent.com/9473609/81338565-d8724a00-907a-11ea-9161-801bec7a57b3.jpg)

**Comment by tyrosinase** [comment]
Honestly having the machine (which does not do intra-color trims) tease me with that icon is NOT FAIR.

**Comment by hellomynameisslim** [comment]
also having this wierd issue ive just started using ink stitch so it could just be me but
![image](https://user-images.githubusercontent.com/76883322/103465360-cd0a1800-4d08-11eb-9b2e-64d91f934ffb.png) that is turning into this 
![image](https://user-images.githubusercontent.com/76883322/103465375-e743f600-4d08-11eb-83da-47256d8898cb.png)

**Comment by tyrosinase** [comment]
Color conversions are always weird; I spent some time in the print shop world in the early days of desktop publishing, and RGB<->CMYK conversions have gotten *some* better but not a lot. It's a multidimensional space, and colors that are mathematically close aren't always close to the human eye. Grays are particularly subject to this: something can be close mathematically but not remotely "gray."

The 30-color Brother palette amplifies this: there's just not that much to choose from. You see some of the same thing with http://threadchart.info/threadchart.php?f=MADEIRA7:

![image](https://user-images.githubusercontent.com/9473609/103576615-69672280-4ea1-11eb-9e1b-54fbcb498533.png)

Literally none of those choices have the bluish cast of the original. But if you fix the algorithm there, you break it in another area.

**Comment by tyrosinase** [comment]
I guess these colors probably get converted to the same thing in PES format, but the stitch-type-as-color at the very top also results from a Sulky Rayon:
240	200	180	                 Pastel  Mauve   1113

I'm still inclined to think it's a bug in the Brother firmware though, since the little colored-spool preview is trying to hit the right color. As long as it doesn't cause issues with the combo embroidery/sewing machines (which mine is not) I don't think it needs to avoid that "color" in PES (at least, not on my account).

**Comment by kaalleen** [comment]
Closing in favor of #2668
