### ISSUE TITLE
Error when saving any Embroidery Format. 

### ISSUE THREAD

**Issue by gbenton629** [inkstitch/inkstitch#572]
Hello, for some reason after I have finished my embroidery design and go to save it I receive the error seen in the screen capture. I have tried saving all different embroidery formats and still receive the error. I also tried reinstalling inkstitch and still got the same error. Anyone have any ideas what may be the issue?
<img width="462" alt="Screen Shot 2019-11-09 at 12 43 03 PM" src="https://user-images.githubusercontent.com/57570796/68533196-276d3b80-02f3-11ea-8de8-85a190f5f6a7.png">

**Comment by lexelby** [comment]
Ouch, that looks like a bug in Ink/Stitch.  I'm sorry you're running into this!

The problem appears to be that there's some weird data in your SVG that Ink/Stitch doesn't know how to deal with.  Maybe it's in an object name, or maybe it's hidden in one of the XML attributes inside the SVG file.

If you're interested in uploading your file here, it would help us find and fix the bug, and we might also be able to fix your file to get you unstuck.

You can also try starting a new SVG in Inkscape, copying your design from your original SVG, and pasting it into the new one.  That might fix the problem.

**Comment by gbenton629** [comment]
hmm that's interesting. I tried making a new file with just a circle in it and I get the same error when attempting to save as any embroidery format. I've uploaded the file anyway if you want to take a look. 


[drawing.svg.zip](https://github.com/inkstitch/inkstitch/files/3828760/drawing.svg.zip)

**Comment by Kuscka1** [comment]
@gbenton629 I had that a few months ago, best to uninstall all, get a fresh copy of Inkscape and Inkstitch. It solved it for me. 

*Note 
Just clear all files manually should it still be there after uninstall. Bugs will try to keep bugging.. clear everything.

**Comment by gbenton629** [comment]
@Kuscka1 awesome, I’ll give that a try and see what happens! Thanks!

**Comment by lexelby** [comment]
Could you also try with the current stable version of Inkscape (0.92)?  I _think_ Ink/Stitch should work perfectly fine with Inkscape 1.0 beta, but maybe there's some issue I don't know about.

**Comment by lexelby** [comment]
I was right about one thing: this is a bug in Ink/Stitch.

I was wrong though: this is not bad data in your SVG or anything like that.  Sorry about that!

I've created #573 which I think will fix this problem.  A Mac version is currently building and will be posted here when it's ready: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lneva-stdout-encoding

Until then, you have two options to work around this bug:

1. Use Inkscape 0.92 -- though I know that installing Inkscape below version 1.0 on a Mac is _way_ more complicated.
2. Use the Embroider extension instead of Save As.  The Embroider extension will also output a machine embroidery file, and it shouldn't trigger this UTF-8 bug.

**Comment by gbenton629** [comment]
@lexelby I got the embroider extension working so this work around will work great for now, thanks again for all the great support!

**Comment by lexelby** [comment]
Glad to hear it :)

**Comment by Kuscka1** [comment]
My turn to walk into the same and print issue. My fingers forever has to itch, now I need to reinstall again. Word of caution stay away from the Install addons for Inskcape in the Inkstitch area - it installed the thread manufacturer color palettes and visual commands which proof to be the old ones overwritting the content on the fresh Ink/stitch version. Messed up my printing as well.

le sigh - reinstall all.
