### ISSUE TITLE
How to change the starting/ending point on a run stitch?

### ISSUE THREAD

**Issue by buriacarrington** [inkstitch/inkstitch#574]
I'm using a svg and I would like to know how to change it.

**Comment by kaalleen** [comment]
With the path selected go to 'Path > Reverse'. This will swap the direction of your path and also the starting and ending point for running stitch.

Seems like our documentation doesn't mention it. Sorry for that, I will add this bit information soon.

**Comment by FelisucoVFR** [comment]
It is in the tutorial videos. Its worth to see them.
