### ISSUE TITLE
Huge delay (45 seconds!) when using the most important Ink/Stitch menu items

### ISSUE THREAD

**Issue by simon-budig** [inkstitch/inkstitch#575]
Hi all.

I experience some huge delays (45 seconds) when invoking certain menu items. These delays make Ink/Stitch hugely frustrating to use for me.

I am using Inkscape 0.92.4 (5da689c313, 2019-01-14) as of debian sid, Ink/Stitch Version is inkstitch-v1.26.2-linux-x86_64-en_US.tar.gz as distributed on github. Desktop Environment is XFCE.

The following menu points are affected:

Ink/Stitch -> Lettering
Ink/Stitch -> Params
Ink/Stitch -> Simulate 

When invoking these a new process "inkstitch" appears in the process list and takes up 100% CPU for 45 seconds.

The commands in Ink/Stitch -> Commands and Ink/Stitch -> Satin Tools seem unaffected.

Ink/Stitch -> Print / Realistic Preview behave a little different. It is faster in popping up the window with an initial rendering (takes about 5 seconds), but then takes about 55 seconds until it becomes responsive.

These delays are really frustrating, I hope you can give me a hint on what is going wrong here...

Thank you.

**Comment by lexelby** [comment]
Yikes!  That's not good.  Thanks for trying Ink/Stitch and for telling us about this.

My normal first thought would be that maybe your design is really complicated, and it's taking Ink/Stitch awhile to generate stitches.  But that's definitely not what's going on if you're having the problem even with Lettering, since that extension doesn't generate a stitch plan at all.

I wonder if you're experiencing a problem we had awhile back.  I never saw it personally, but my understanding is that something would go wrong in the XML parsing and an SVG would get filled with hundreds of thousands or even millions of empty lines.  Could you try running your SVG through `grep -P '^\s*$' | wc -l`?

If that doesn't show anything interesting, would you be willing to post your SVG here so we can take a look?

**Comment by lexelby** [comment]
Another related question: do you get this delay even when running Lettering on a brand new blank document?

**Comment by simon-budig** [comment]
Yes, this also happens with Lettering on an empty document, I also previously had the impression that this is unrelated to document complexity.

I've strace'd the "inkstitch" process on startup and it seems to take a really long time to deal with the fonts on my system. I am observing the following syscalls at a rate of about two per second (the timestamps are relative, i.e. they show the duration between two successive syscalls):

     0.471263 munmap(0x7f28e46c6000, 19064160) = 0
     0.000801 openat(AT_FDCWD, "/usr/share/fonts/opentype/noto/NotoSansCJK-DemiLight.ttc", O_RDONLY) = 14
     0.000054 fcntl(14, F_SETFD, FD_CLOEXEC) = 0
     0.000019 fstat(14, {st_mode=S_IFREG|0644, st_size=19064160, ...}) = 0
     0.000031 mmap(NULL, 19064160, PROT_READ, MAP_PRIVATE, 14, 0) = 0x7f28e46c6000
     0.000031 close(14)                 = 0
     0.473648 munmap(0x7f28e46c6000, 19064160) = 0
     0.000815 openat(AT_FDCWD, "/usr/share/fonts/opentype/noto/NotoSansCJK-DemiLight.ttc", O_RDONLY) = 14
     0.000063 fcntl(14, F_SETFD, FD_CLOEXEC) = 0
     0.000026 fstat(14, {st_mode=S_IFREG|0644, st_size=19064160, ...}) = 0
     0.000115 mmap(NULL, 19064160, PROT_READ, MAP_PRIVATE, 14, 0) = 0x7f28e46c6000
     0.000042 close(14)                 = 0
     0.468253 munmap(0x7f28e46c6000, 19064160) = 0
     0.000789 openat(AT_FDCWD, "/usr/share/fonts/opentype/noto/NotoSansCJK-DemiLight.ttc", O_RDONLY) = 14
     0.000066 fcntl(14, F_SETFD, FD_CLOEXEC) = 0
     0.000026 fstat(14, {st_mode=S_IFREG|0644, st_size=19064160, ...}) = 0
     0.000035 mmap(NULL, 19064160, PROT_READ, MAP_PRIVATE, 14, 0) = 0x7f28e46c6000
     0.000036 close(14)                 = 0

Maybe the fontconfig/freetype libraries bundled with your extensions have troubles with these fonts? Do they properly cache the information they've gathered from reading/parsing these fonts?

**Comment by simon-budig** [comment]
Ok, it is definitely connected to font handling. I've just uninstalled the Noto CJK-Fonts from my system and that has cut down the slowdown from 45s to about 7s. Which is still a lot, but a little bit more bearable.

But the time probably is spent with parsing fonts again and again which should be avoidable.

**Comment by simon-budig** [comment]
I've attaced an strace log (created with a small shell wrapper around the inkstitch binary). This time the timestamps are relative to the startup time.

At the timestamp 1.519038 fontconfig initialization seems to start. It then spits out some warning about problem of the configuration files (probably because the versions as shipped by inkstitch mismatch to the configuration files intended for my system-wide fontconfig library).

 It then starts reading and parsing fonts and is finished with that at the 6.862467 timestamp (about 5 seconds for just parsing fonts). It then tries to write the fontconfig cache and fails due to permission problems (and inkstitch really shouldn't try to write the fontconfig cache to a location also used by my system-wide fontconfig installation!).

Ink/Stitch really needs to make sure that the libraries shipped by it must not interfere with potentially different versions of these libraries installed on the system.

**Comment by gamboz** [comment]
I have a similar problem on the same versions of inkscape + inkstitch on a debian bullseye/sid,
and uninstalling noto fonts gave me similar improvements. However I do not have warnings or errors related to Fontconfig in my strace.

**Comment by lexelby** [comment]
Wow, that's painful.  Thank you for stracing, @simon-budig!  I agree, Ink/Stitch should not be doing this.

Ultimately, I think our upcoming roadmap for Ink/Stitch will alleviate this problem.  Right now, we're in the process of transitioning from wxPython to Electron for our GUI.  Once we entirely transition to Electron, hopefully we'll get to stop bundling font libraries with the python side of Ink/Stitch.  Presumably Electron doesn't also exhibit this ridiculous behavior :)

That said, I'm sorry that I don't have a solution other than waiting, but I do think we're on the right track to fix this.

**Comment by lexelby** [comment]
I'm pretty sure we fixed this long since.  If that's not the case, please let us know!
