### ISSUE TITLE
Change from 1.22.1 to 1.26.2 doesn't work save as zip

### ISSUE THREAD

**Issue by SchmetterlingK** [inkstitch/inkstitch#579]
I'm working with version 1.22.1 and now I wanted to change to version 1.26.2 the simulation ist working but I cant save the file to emroidery. I get this error if I use the Extension-Inkstitch-embroidery  (if I use "save as" everythink is working. But I can't save as zip, there is a zip but I can't open it the error say it ist not valid).

So here the error: 

Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\embroider.py", line 86, in effect

  File "lib\extensions\embroider.py", line 49, in get_output_path

  File "encodings\utf_8.py", line 16, in decode

UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 26: invalid continuation byte

What did I wrong? If I cange back to the old version everything is working fine again.

**Comment by kaalleen** [comment]
Thank you for reporting this back to us and sorry for your troubles.
There is nothing you did wrong, you just ran into a bug in Ink/Stitch.
I think this issue will be fixed in the next release through #573 (@lexelby ?)

**Comment by lexelby** [comment]
That's correct.  We're just waiting to release until our bills system works :(

**Comment by kaalleen** [comment]
Closing the issue. It should be resolved, since version 1.27.2 is released.
