### ISSUE TITLE
Command connectors with a fill color errors

### ISSUE THREAD

**Issue by aStarHen** [inkstitch/inkstitch#580]
In my last 2 projects, every time I use the Print function, both the regular and realistic previews include artifacts from commands, visible fills, and satin stitch rails. The first two projects I made did not have this issue. I haven't changed my version of Inkscape or installed anything new, so I'm stumped.

I'm using Inkscape 0.92.4 on Windows 10.

![image](https://user-images.githubusercontent.com/57885306/69024583-022e9c00-0989-11ea-846e-2c919b8bfcda.png)
![image](https://user-images.githubusercontent.com/57885306/69024600-183c5c80-0989-11ea-9d96-4c68998385cf.png)

P.S. InkStitch is my new favorite thing ever. Thank you for all your hard work! :)

**Comment by lexelby** [comment]
First of all:  I love your design!  Thanks for using Ink/Stitch :)

That's a known bug.  I have a fix in but we can't release yet because the build system is broken, so we can't produce a Windows version yet.   Hoping to have that fixed soon!  Workaround: set the commands invisible in Inkscape.  They'll still work but they won't be visible in the print view.

I also see another bug.  Your objects are not in a layer, and Ink/Stitch is getting confused and leaving them in rather than hiding them like it should.  You can see the rungs in your satins poking out, for example.   Ink/Stitch should handle objects that aren't in a layer.  Workaround: create a layer and put your objects into it.

Sorry for these bugs!  Thanks for telling us what you saw, keep the bug reports coming :)

**Comment by aStarHen** [comment]
Ah, delightful, that did the trick! Putting everything in a single layer hid the commands but not the satin rungs, but doing multiple layers for different elements worked. Thank you!
![image](https://user-images.githubusercontent.com/57885306/69075376-e530b200-09f6-11ea-810a-5fcfde636f01.png)

**Comment by lexelby** [comment]
I love the way you designed the lamp shade to give it texture and dimension.  Any chance for a photo of the finished product? :)

**Comment by aStarHen** [comment]
Thank you! I'll stitch it out at my favorite makerspace later this week and post a pic, for sure.

**Comment by tyrosinase** [comment]
On 11/18/19 1:34 PM, aStarHen wrote:
>
> Thank you! I'll stitch it out at my favorite makerspace later this
> week and post a pic, for sure.
>

You have a makerspace with an embroidery machine?! I've been saying all
along that they need them (I sometimes refer to mine as a "textile-based
3d printer").

**Comment by lexelby** [comment]
I refer to mine as a 2.5d printer :D

**Comment by tyrosinase** [comment]
JoAnn Fabrics is apparently approaching this from the other direction: they're putting Glowforges into their classroom areas, along with longarm sewing machines and Cricuts.

I approve (other than the JoAnn closest to me lost its building and I have not heard any whispers of a new location for it).

**Comment by aStarHen** [comment]
I was finally able to stitch out the design (was sick for a few weeks, ugh). The machine was having some tension issues, but it came out pretty good nonetheless. Praise Inkstitch!
![image](https://user-images.githubusercontent.com/57885306/70378440-f843ed00-18e5-11ea-83e0-63b4b7136690.png)

**Comment by lexelby** [comment]
Love it!

**Comment by kaalleen** [comment]
@aStarHen  Nice! Would you mind if we add this to our artwork gallery? I am trying to catch some images for it. It still hasn't a lot of content...

**Comment by kaalleen** [comment]
If you accidentally add a fill color to the connector (this can happen, if you try to fill color a group), Ink/Stitch will return a error message. This will be fixed if we merge the svg-objects branch.

**Comment by kaalleen** [comment]
Solved via #643

**Comment by aStarHen** [comment]
> @aStarHen Nice! Would you mind if we add this to our artwork gallery? I am trying to catch some images for it. It still hasn't a lot of content...
> 
> Edit: Forgot the link, here it is: https://inkstitch.org/tutorials/inspiration/

@kaalleen Absolutely! Go for it! I have some other samples, but I haven't taken really good pics of them. If you want more, though, let me know and I can do that. So sorry for the late reply! I kept meaning to respond and forgetting...

**Comment by kaalleen** [comment]
I took even longer to ask the question ;)

This is great, thank you. If you have more images you'd like to share, we would really appreciate it. It would be so nice, if the inspiration page fills up with nice examples.
