### ISSUE TITLE
Can InkStitch be used with Computer controlled Sewing Machines

### ISSUE THREAD

**Issue by PadamSethia** [inkstitch/inkstitch#581]
I was looking for an open source software that works with Computer controlled sewing machines , what that does is you give a file that has the path of how to sew and the machine follows that path.
Is this possible with this ?

Thanks!

**Comment by lexelby** [comment]
Hi there, welcome to Ink/Stitch!  It sounds to me like you're describing an embroidery machine.   That is a sewing machine that can move a frame around under the needle to sew along a path.  That's exactly what Ink/Stitch is for. :)

What sewing machine brand/model are you looking at?

**Comment by PadamSethia** [comment]
Not exactly an embroidery machine  , I looking to make it work on Juki LZ 2290 ASR  - they have a software for this PM -1 - which is overly expensive to buy . So I was hoping if Ink Stitch would replace that

**Comment by lexelby** [comment]
Oh sorry!  My mistake.  I hadn't heard of that kind of machine before.

My guess is that Ink/Stitch won't work with that machine, but what file formats does it read?

**Comment by PadamSethia** [comment]
I'm not sure actually , just had a demo of the software . Didn't notice the format . 
Anyways thanks!
