### ISSUE TITLE
Single-line alphabets

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#582]
I made one but won't have a chance to contemplate adding it to Ink/Stitch until January. So if anybody else wants to turn it into a PR I wouldn't complain.

https://silverseams.com/2019/12/02/free-svg-alphabet-handwritten-monoline-script/

**Comment by kaalleen** [comment]
Nice work! What will be the license of the font?

**Comment by lexelby** [comment]
@tyrosinase any thoughts on licensing this alphabet?

**Comment by tyrosinase** [comment]
Oh, I had completely forgotten I did anything with this font. (I don't even have it installed in my own Ink/Stitch right now.) I should finish the uppercase, and actually make it an Ink/Stitch font (this pre-dated the ability to do so, at least for me).

Probably I am going to have to partner with someone who is less anxious about sending request emails to total strangers, because I think it's another that might not be up to standards here.

**Comment by kaalleen** [comment]
Closing this as the license on this one really may be an issue. Please protest, if that's not the case!
