### ISSUE TITLE
Error during autofill!  (NetworkXNoPath: No path to [...])

### ISSUE THREAD

**Issue by SacroMars** [inkstitch/inkstitch#583]
Context: I have a project that is layered bones with a dogs name in it, the object on the outermost edge by itself appears to function properly, but any time it's grouped with other objects of a different color, results in the following error that doesn't allow a full simulation or me to save the file as a .pes.

path843: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):

  File "lib\elements\auto_fill.py", line 218, in to_patches

  File "lib\debug.py", line 125, in decorated

  File "lib\stitches\auto_fill.py", line 64, in auto_fill

  File "lib\debug.py", line 125, in decorated

  File "lib\stitches\auto_fill.py", line 568, in path_to_stitches

  File "lib\stitches\auto_fill.py", line 533, in travel

  File "site-packages\networkx\algorithms\shortest_paths\generic.py", line 172, in shortest_path

  File "site-packages\networkx\algorithms\shortest_paths\weighted.py", line 163, in dijkstra_path

  File "site-packages\networkx\algorithms\shortest_paths\weighted.py", line 472, in single_source_dijkstra

  File "site-packages\networkx\algorithms\shortest_paths\weighted.py", line 738, in multi_source_dijkstra

NetworkXNoPath: No path to (272.5980158023096, 103.22246243632).

**Comment by lexelby** [comment]
Thanks for reporting your problem!  This is a tough one.  It's a bug in the Auto-Fill code, and I haven't figured out how to solve it yet.  Ink/Stitch can get "stuck", where it wants to underpath but it's already filled the entire shape with tires of stitches so there's nowhere left to go, hence "no path".

To work around this bug, you can try setting a slightly different starting or ending point on the fill shape using "add commands to objects".  Try changing them around until the problem goes away.

I'm sorry this is a pain, and obviously you shouldn't have to do it at all!  I'll try to figure out how to make the code avoid this situation.

**Comment by SacroMars** [comment]
Thank you for your help. I have decided to try recreating the file from the
beginning, as my design has changed up a bit. I'll definitely try your fix
if it happens again. I understand the development process and how some
weird bugs pop up as I went to school for programming. I love the software,
by the way, so thank you and everyone else involved in it.

Marlene

**Comment by lexelby** [comment]
Oh great!  If you're interested in getting back into programming and want to dig into Ink/Stitch's code, let us know if we can help :)

Also, I see there was a typo above.  "Tires of stitches" should be "rows of stitches".  It paints itself into a corner.

**Comment by SacroMars** [comment]
I'm always interested in getting back into programming! xD

Sorry, for the long time between replies. I've been pretty busy with work
and everything. Your fix worked, by the way!

**Comment by SacroMars** [comment]
[image: image.png]

**Comment by lexelby** [comment]
Yay! On both counts.  We've tried to make the Ink/Stitch source code as easy to learn as possible but if you find anything confusing, please let us know so we can add comments or documentation.

**Comment by kaalleen** [comment]
This issue has been addressed by @lexelby in this commit: https://github.com/inkstitch/inkstitch/commit/9bb4686df702be6e930aa1216cc9e254ae9e5b01

I will close the issue now. Please reopen, if the error shows up again
