### ISSUE TITLE
Exploding Command Connectors

### ISSUE THREAD

**Issue by marie071183** [inkstitch/inkstitch#585]
When adding more than 1 design to a project (mostly embroidery files) the program adds stray stitches to the project. It is causing an issue with layout and design. They can be removed by Breaking the object, however that raises another issue of your design being split and it can be messed up easily. Please help fix this frustrating issue. I can provide images if needed.

**Comment by lexelby** [comment]
Hi there!  Thanks for trying Ink/Stitch, and thanks for reporting your problem.  

I haven't actually tried using File -> Import on embroidery files before.  I'm sorry it's causing you problems!  Images really help, if you have a chance.  Hopefully it should be an easy fix.

**Comment by marie071183** [comment]
![SCREENSHOT](https://user-images.githubusercontent.com/58568903/70381631-a4ec9180-191b-11ea-8f82-1a712fb80a69.png)

**Comment by kaalleen** [comment]
Thanks for reporting the issue! I am able to reproduce this behavior.

Ink/Stitch doesn't misplace the connectors, if you drag and drop the files into an Inkscape document directly from your file browser. Maybe it can serve as a workaround for you at this point.

**Comment by marie071183** [comment]
![SCREENSHOT](https://user-images.githubusercontent.com/58568903/70391690-de69df00-19a5-11ea-9e0a-b093e5e2a3c1.png)
This was with drag and drop. The sketches did not show till the 3rd image added.

**Comment by lexelby** [comment]
Whoa.  That's pretty nasty!  Thanks again for reporting this.

**Comment by kaalleen** [comment]
Hm, right. It doesn't make a difference if you drag & drop or import the files.
I am wondering if this is an Inkscape error? It always happens to the previously imported design(s), not the newly inserted one.

**Comment by marie071183** [comment]
What's really strange is if you ungroup the image the scratches will disappear. However, it can mess up your design by doing that if you are not careful. I had to do lettering the other day and I got some slippage while moving them around.

**Comment by lexelby** [comment]
What if instead of ungrouping, you select everything and move it a little bit?  That may make everything snap into place.

**Comment by kaalleen** [comment]
Tested with Inkscape 1.0. This seems to solve the issue.
I will close the issue now, but if this issue shows up again, please reopen!!
