### ISSUE TITLE
inkstitch and machine speed

### ISSUE THREAD

**Issue by Dany36500** [inkstitch/inkstitch#587]
Hi,
I test ink stitch, it s not so easy but I done some good design.
But I have a problem, when I want to do bigger design, the speed of the machine is low, and I con't modify this parameter up in the machine (I can go lower but not higher....)
Could be possible to choose the speed in inkstitch or the speed is calculating with other parameters defined by the embrodery parameters ...
If you can help me ;p

**Comment by wwderw** [comment]
By bigger, are you by chance using wider satin stitches?  If it wider satin stitches (or wider any stitch other then fill stitches), then that is what the machine is doing to protect itself.  When you start getting stitches closer (or beyond if trims are turned off, if your machine supports trims) then 12.7mm wide (or it can be 12.1, depends on the individual machine), it will slow down. 

Now, there is an advanced feature in Inkstitch that will allow a very specific brand of machine to have the pattern control the speed (it won't change how the machine handles the above situation however, but you can control the speed).  If you export a CSV file, versus a stitch file, open that up and wherever you want to control speed, you swap "STITCH" out with either "SLOW" or "FAST", depending on which one you want.  Then you the CLI Pyeembroidery library and convert that CSV file to a Barudan U?? file.  This file format and functionality will only work on Barudan machines (I use this a lot on my, how I know it exists).

Any time you make an edit to the file, you will have to go through this process again to add that functionality in there.    Unless you have a Barudan machine though, this process won't work for you.  I highly expect it has to do with what I mentioned at the beginning and that's hardcoded into the machine itself.  Only way around that would be to change those really wide stitches to either split stitches (if wanting to keep satin) or change those satin stitches to fill stitches.  Just depends on the design and the individual objects.

**Comment by tyrosinase** [comment]
On 12/13/19 10:03 AM, wwderw wrote:
>
> By bigger, are you by chance using wider satin stitches? If it wider
> satin stitches (or wider any stitch other then fill stitches), then
> that is what the machine is doing to protect itself. When you start
> getting stitches closer (or beyond if trims are turned off, if your
> machine supports trims) then 12.7mm wide (or it can be 12.1, depends
> on the individual machine), it will slow down.
>
Relatedly, this will happen if you size up a design without re-doing the
stitches themselves - i.e. if you scale up something in Inkscape that
uses manual stitching, or if you scale it up on the machine itself.
Bigger stitches are always slower stitches.

(If that's what's happening, I've generally had good results scaling
designs by turning Manual Stitch Placement off and letting Ink/Stitch
decide the new stitch points. For linear designs, obviously, not for
fill stitching.)
