### ISSUE TITLE
Ink stitch won’t respond with simulate, print features. 

### ISSUE THREAD

**Issue by patpeazy** [inkstitch/inkstitch#590]
Hello, 

Ink stitch won’t simulate or save my file, which was made in ink stitch. Not sure what the issue is all of the other features work fine. Is there something I’m doing wrong?

**Comment by lexelby** [comment]
Hi there!  Thanks for trying Ink/Stitch.  I'm wondering, are you by any chance on a Mac?

**Comment by patpeazy** [comment]
I’m using both Mac and windows.

**Comment by kaalleen** [comment]
Do you get any error message when you try to execute these functions?
