### ISSUE TITLE
Error when saving DST filetype

### ISSUE THREAD

**Issue by hwilson10** [inkstitch/inkstitch#591]
Hello, 
I am trying to save an embroidery file as a tajima DST file and I am having trouble getting it to work.  After reading through the DST file format I have noticed that pyembroidery saves the header with a slight error.  It saves the first few lines as AX ..., AY ..., MX ..., AY, ... instead of as AX ..., AY ..., MX ..., MY ... I have included an image of this.  I have also noticed that there is an extra 5 appended to the values saved in these fields and there is a missing space before the values in these fields.  

In the file attached is an image of a working dst file (right side), and the same dst file loaded into inkstitch then resaved as a dst of a different name (left side)
![Annotation 2019-12-16 183842](https://user-images.githubusercontent.com/17091802/70952136-62216c80-2033-11ea-820f-35e050b4f758.png)

I attempted to work on the python scripts on my own however I cant figure out how to compile and I am sure I am not well enough experienced in python compilation and inkscape extensions to do so.

Thanks in advance for any help.

**Comment by lexelby** [comment]
Interesting!  Thanks for digging into this so much.  Should be easy to fix given your description.  I guess maybe some (most?) machines ignore the header, which could explain why we haven't noticed this before.

As to building Ink/Stitch, _we_ can't even do it right now. :( We're in the process of trying to fix our broken build system.  Once we do, I'll throw together a test build of a fix so you can give it a go.

Does your machine accept any other formats?

**Comment by hwilson10** [comment]
Thanks for the reply,

Unfortunately no the machine is an older one and doesn't accept anything other than DST so I am quite out of luck for the moment.  Looking forward to the test build though.

**Comment by lexelby** [comment]
You seem pretty savvy... Maybe you can fix your files with a hex editor?  I'm sorry to even suggest such a thing but I just hope we can get you unstuck :(

What OS are you on?

**Comment by hwilson10** [comment]
I am currently using windows 10, and a hex editor is actually exactly how I found the original problem.  

As of right now I have no problem using the machine as I can manually adjust the header or write a script to add the appropriate changes, I am trying to sort it out for someone who isn't very tech savvy however and the thought of adding a second program to make the files run is quite frustrating to them.

**Comment by lexelby** [comment]
Okay, got it.  I think this actually may be another manifestation of a bug we already know about in the windows version.  Fix pending, but of course there's the issue of our build system.

 I may have a workaround though.  The bug triggers when you use File -> Save As.  Instead, try running the Embroider extension.  It's a little less user friendly because it always saves the DSTs in a predetermined folder, but if my hunch is right, at least the files will be well-formed.

**Comment by hwilson10** [comment]
Unfortunately after running the embroider extension to save as DST the files have the same problem with their header.  If it helps with finding any bugs, after reading through the source the error seems to be in the pyembroidery DstWriter.py script.  The image attached shows a typo in the lines which should output the AX,AY,MX,MY header portion. 

Also as for the extra 5 which is appended at the end of the values in this header portion, it appears that the numbers just aren't rounded following a division by 2 which could potentially leave a .5 decimal place that the file would then store, also noted in image.

![Annotation 2019-12-17 113427](https://user-images.githubusercontent.com/17091802/71015205-34830480-20c1-11ea-97dc-6aff32760cbc.png)

Thanks again

**Comment by lexelby** [comment]
Darn.  And thanks for digging into the code!  I think your analysis is spot on.

**Comment by kaalleen** [comment]
@lexelby I copied an update from EmbroidePy into our pyembroidery repository.
It should fix the issue!?!
