### ISSUE TITLE
French localization misses top-level menu items

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#592]
Hi everyone,

This may be just an issue related to different versions using different strings. 

When I switch to the French version in version v1.26.2, the top level menu items are not translated (Commands, Embroider..., Lettering, etc.) but they are in the translation file as far as I can tell. I initially thought that this was due to missing strings for the new menu structure. The same problem also arises for the German translation which is also quite complete.

I now just tried switching the translation file, i.e. I manually created a *mo from a *po I got from the master branch https://github.com/inkstitch/inkstitch/tree/master/translations. Same problem, which is strange since I can find the labels in this *po file I got from the master. E.g.
#: templates/install.inx:3
 msgid "Install add-ons for Inkscape"
 msgstr "Installer des extensions pour Inkscape"

Anyhow, since I am not developer, I cannot tell if this is "normal" and will be automatically fixed in the next release or if you will have to change something in the code.

- cheers ! Daniel

PS: Switching languages in InkScape is difficult per se. May require killing the preference file, rebooting plus some extra magic I do not understand... but that's a different issue. Also, you do seem to have quite a lot of users in France, e.g. ~200 members in a Facebook group.

**Comment by lexelby** [comment]
Wow!  I didn't think we had that many users _period_.  I'll try to look into the translations issue soon.  I suspect this may be another symptom of the fact that our Travis-based build system is falling apart.

**Comment by kaalleen** [comment]
@danielkschneider is this issue solved with the new version?

**Comment by kaalleen** [comment]
This is quiet a while ago and we haven't heard of an issue like this since then.
I will close this issue now. Please reopen or create a new issue if this happens again.
