### ISSUE TITLE
mac os download hundreds of verifications.

### ISSUE THREAD

**Issue by carrabre** [inkstitch/inkstitch#593]
Hey - on the latest version of MacOS you have to verify the developer acct hundreds of times to get it to work - still haven't gotten it there yet.

<img width="406" alt="Screen Shot 2019-12-22 at 3 46 16 PM" src="https://user-images.githubusercontent.com/40183833/71327781-5241d680-24d2-11ea-8103-38637108b3b3.png">
<img width="414" alt="Screen Shot 2019-12-22 at 3 45 42 PM" src="https://user-images.githubusercontent.com/40183833/71327782-5241d680-24d2-11ea-9057-d03215dc96a6.png">
<img width="410" alt="Screen Shot 2019-12-22 at 3 46 07 PM" src="https://user-images.githubusercontent.com/40183833/71327783-5241d680-24d2-11ea-9eba-dbaa9718ec19.png">

**Comment by iCoops93** [comment]
I am Having the same issue, cleared what feels like 40 requests so far.. did you get it to work in the end?

**Comment by lexelby** [comment]
Sorry folks, that must be aggravating. :(  I really don't know much about MacOS at all.  If anyone knows what we need to do to sign our app, and help would be appreciated!

**Comment by kaalleen** [comment]
This isn't the most convenient way, but you could avoid those requests if you download Ink/Stitch through your command line instead of using the browser.

The newest development version has some improvements for the mac release. This is only for Catalina. I think this is the macOS version you are using, otherwise you wouldn't see so many requests.

You can download Ink/Stitch with this command (english version):
```
curl -LJO https://github.com/inkstitch/inkstitch/releases/download/dev-build-lneva-stdout-encoding/inkstitch-refs-heads-lneva-stdout-encoding-osx-en_US.zip
```

**Comment by dubchild** [comment]
I'm currently having this issue. I have verified dozens of files and i still can't get this piece of junk to work. Apparently this is still an issue 5 months later??????? GOOD WORK GUYS!

**Comment by X3msnake** [comment]
@dubchild this is a Open Source project, if you have knowlage on how to fix this for MAC please be our gues. Complaining and being rude is not the answer.

You have at least 4 work-arounds i can see.

1 - Get a Windows or Linux Machine and dedicate it to run this awsome free and OpenSource software
2 - Try running the windows version of inkstitch trough wine or get a linux/windows virtual machine to run inkstitch and this software inside it
3 - Learn programming and contribute back a better version 
4 - Don't use the software

**Comment by kaalleen** [comment]
It's mentioned above, but for people coming later reading this issue, I want to set a link to our website for the best way to install Ink/Stitch on macOS at the moment:
https://inkstitch.org/docs/install/#macos

Please keep in mind, that we are doing our best. But without throwing a yearly fee into the apple feature for signing apps, we cannot provide a better installation procedure for macOS users.

**Comment by kaalleen** [comment]
Steps to solve are documented on our website.
