### ISSUE TITLE
Error saving as .PES

### ISSUE THREAD

**Issue by MasonDod** [inkstitch/inkstitch#594]
I'm trying to save my first (woohoo!) embroidery file as .pes, but I am receiving this message:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 40: invalid start byte

I have no idea what this means, please help. Thank you!

-Mason

**Comment by lexelby** [comment]
Hi there!  This is a known bug that we're actively working on.  Fortunately there's a workaround!  Instead if using File->Save As to save your PES, try the Embroider extension.  It saves a copy of the file too, and it should avoid the bug.  Let me know if that doesn't help.

**Comment by MasonDod** [comment]
It worked! Thank you :)
