### ISSUE TITLE
brother bes-916ac

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#595]
Look at my new friend!

![IMG_20191228_121031](https://user-images.githubusercontent.com/4446653/71548230-3aa69a00-2979-11ea-935b-362ce2ee9ad6.jpg)

I got a really nice deal on this machine from a person the next town over :D

**Comment by Jwolter0** [comment]
I picked one up as well. Maybe we should start a club.

**Comment by lexelby** [comment]
Aw, I'm afraid I donated mine to a makerspace a couple years back.  I got a desktop model instead (brother pr655), partly to save space, partly because the 916ac was super finicky.

It served me well though. I estimate that I sewed and donated around 2000 masks on it during the height of the pandemic.  I still remember many of its quirks, so let me know if you have any questions.

I recommend replacing the floppy drive with one of those floppy emulators that takes a specially-formatted USB drive.
