### ISSUE TITLE
Font making questions

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#597]
As promised, I've been working at putting my little single-line font into a format that Lettering can handle. It's going pretty well.

However, kerning is gonna be a *lot*. Is there an alternative that says "the start point of this letter is X px to the right for letter-spacing purposes"? Anything followed by a "j" is going to be the same (largish negative) kerning value, anything followed by an "a" will be the same (smallish negative) value, etc.

The first line is how it's coming out with no kerning set up: "correctly" with zero letter spacing. The second line is how it's supposed to be.

![2019-12-29--1577596005_1920x1080_scrot](https://user-images.githubusercontent.com/9473609/71552656-563c8f80-29cf-11ea-9b1b-a2cf24c2afe0.png)

**Comment by Augusa** [comment]
I have a very small experience with kerning. But you can see an exemple of kerning when opening a json file from a font of Inkstitch. You need to create pairs of letters as you want them.

**Comment by kaalleen** [comment]
For everyone who is finding this issue in future. You'll find a tutorial on how to generate Ink/Stitch fonts here: https://inkstitch.org/tutorials/font-creation/
