### ISSUE TITLE
Clarification please - command object placement

### ISSUE THREAD

**Issue by claypipe** [inkstitch/inkstitch#598]
I am not sure if it is my operator error, if my machine is incorrectly set, or if it is a missing capability with my machine, but ...

I added trim after commands to a design but the machine failed to obey them.
I noticed that all the trim command objects were together at the top of the list of objects.  Is this correct or should they be moved to be next (before?, after?) the sewn object?

Ta

**Comment by wwderw** [comment]
It is going to depend on the machine that you are using and sometimes it does depend on the format as well.

For instance, Brother PR machines will obey them in the PES file format if they fall outside a certain range, if it's within that range and despite there being a trim command, they will do a jump.

Now, if you are using a single needle home machine, particularly older versions, they don't allow for trims except at the end of a color block, before changing thread.

**Comment by claypipe** [comment]
Thanks for that.  Mine is a fairly new Brother Inovis machine.  I will experiment.
What about the positioning of the "trim after" commands in the list of objects?  Any ideas?

**Comment by lexelby** [comment]
If your machine accepts DST format, try that.  Despite DST being a really weird file format internally, it seems to be the most widely-understood one that Ink/Stitch supports.

 Having your commands appear at the top of the object list is totally fine.  In fact, they can even be in a different layer.  What matters is whether Inkscape thinks they are attached to the object in question.

Try moving one of your trim commands.  If the connecting line follows it as you move it, you're good.  Copying and pasting commands does not work, unfortunately -- it detaches them from the target object.
