### ISSUE TITLE
Ink/Stitch is greyed out in Inkscape 

### ISSUE THREAD

**Issue by zacrizy** [inkstitch/inkstitch#600]
Hi there! New user here so it's likely user error. 

I've got a few things that aren't working and I'm wondering what I'm doing wrong. 

First thing: I can't see the nodes when I use the shape builder tool (standard circle, star, square shapes) or an imported SVG file, and can only see them if I draw the shape out manually using the pen tool (is that normal?) Also, Using a pen tool shape, I follow the steps that are shown on the YouTube tutorial (https://www.youtube.com/watch?v=qXntE1X1RIw) but when I go to the Ink/Stitch extension, everything is greyed out and I can't select anything. Help??

<img width="1079" alt="Screen Shot 2020-01-07 at 2 46 15 PM" src="https://user-images.githubusercontent.com/59624898/71928110-80731780-315c-11ea-86aa-286d71d71950.png">

Downloaded  the latest beta version of Inkscape 1.0 to be used on Mac iOS 10.14.3 
Installed InkStitch inkstitch-v1.26.2-osx-mojave-x86_64-en_US.tar.gz

Ultimate goal is for me to bring in SVGs to convert to embroidery file to be used to create an embroidery using a Brother machine.

**Comment by lexelby** [comment]
Hi there!  I hope you figured things out?  I have no idea what would cause everything I'm the menu to be greyed out.  If your fixed that I'd love to hear how :)

**Comment by zacrizy** [comment]
@lexelby 
Yes! As I suspected it was 1000% user error. I forgot that I was installing Inkscape on my older computer which is running Mojave, not Catalina, so when I'd downloaded the Inkscape version, I'd downloaded the wrong one. Because of that, Inkscape wasn't working well on my computer all together, and the Ink/Stitch version I'd downloaded was supposed to work with the older version of Inkscape so it wasn't even letting me access it. 

I've since downloaded the right version of Inkscape and it's working! I was able to do my first embroidery last night :) Looking forward to learning how to use Ink/Stitch to do even more!


![IMG_4033](https://user-images.githubusercontent.com/59624898/72165898-dda1df80-338d-11ea-8301-7e53ec7a0146.jpg)

**Comment by lexelby** [comment]
Yay!  Welcome to our community :)

**Comment by saundercorb** [comment]
@zacrizy hi, i am having the same issue my old computer is mojave I've downloaded inkscape 1.0.1 and inkstitch v.126 mojave and the inkstitch v.129 osx version and both still leave the extenson to inkstitch greyed out. what extensons should  be using that you used that worked. 
than you
