### ISSUE TITLE
Param "flattening" design in preview

### ISSUE THREAD

**Issue by wandernat** [inkstitch/inkstitch#601]
Sorry if this is the wrong place to put this question. 

I'm making a simple star (my first project) and when I open Params and look at the preview, the design looks flattened or as if it's somehow been turned horizontal instead of vertical. 

Here's my design (created with bezier tool):
<img width="417" alt="Screen Shot 2020-01-17 at 5 24 58 PM" src="https://user-images.githubusercontent.com/17934147/72650372-58e73080-394e-11ea-8d99-2cb5b826717d.png">

Here's what the Params preview looks like (bean stitch, 1 repeat):
<img width="450" alt="Screen Shot 2020-01-17 at 5 27 07 PM" src="https://user-images.githubusercontent.com/17934147/72650468-a368ad00-394e-11ea-98a6-077027edede5.png">

Since that's difficult to see, here's a param preview with satin stitch:
<img width="450" alt="Screen Shot 2020-01-17 at 5 28 24 PM" src="https://user-images.githubusercontent.com/17934147/72650518-cabf7a00-394e-11ea-8cef-4b5115dd4c71.png">

And here's a link to my svg file if you want to try and replicate the issue itself:
https://share.getcloudapp.com/04ugdO7k

**Comment by kaalleen** [comment]
Interesting! Thank you for reporting this bug to us!

Something went wrong with the viewbox attribute on which we seem to rely on.

For now I will give you the corrected document. I adapted the viewbox attribute only.
You will have to remove the .log from the file name to be able to use it.

I just wonder, how this could happen?

[star-emb.svg.log](https://github.com/inkstitch/inkstitch/files/4080381/star-emb.svg.log)

**Comment by lexelby** [comment]
@kaalleen What I don't get is why it looks fine in Inkscape and other svg viewers.  Seems like maybe Ink/Stitch is handling the viewbox wrong somehow...

**Comment by wandernat** [comment]
Thank you for your responses. I just did what I should have done before: I created a new file and re-created the star from scratch using the same process. This time it works fine. In the first star, I must have accidentally typed a key or selected something that made everything weird the first time. My apologies, I know now to do this first in the future before submitting an issue.

I can now continue to make the star (my first Ink/Stitch project). If I do encounter this issue again, I will let you know.

**Comment by kaalleen** [comment]
> My apologies, I know now to do this first in the future before submitting an issue.

No, no, thank you for reporting it to us! Actually we desperately need people to submit issues like this and bring them to our attention. As @lexelby said, there is most probably something we are doing wrong, when all other svg viewers are able to display it correctly.

**Comment by lexelby** [comment]
Yes!  Definitely keep reporting things like this. :grinning:
