### ISSUE TITLE
Circles often getting "border crosses over itself" error

### ISSUE THREAD

**Issue by anula** [inkstitch/inkstitch#610]
I am trying to get started with Inkstitch and, following one of the video tutorials I tried to generate a filled circle.
(I am using the default Inkscape coming with Ubuntu 18.04 LTS, its version is 0.92.3. Inkstitch I installed today, so it is probably v1.26.2)

My steps are following:

- Click on "Create circles, elipses ... (F5)"
- Create a circle
- Click "Path -> Object to path"
- Click "Extensions -> Ink/Stitch -> Simulate"

More often than not, I get the following error message:
```path5420: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.```
The Troubleshooting tool's idea to Union or Break apart the object doesn't really do anything (since it is just a circle).

If I move some nodes around to create a "skewed circle" (![this](https://user-images.githubusercontent.com/4399755/73936371-ffd24300-48e2-11ea-9065-baa28891666c.png)) Simulation starts working. Sometimes it just works from the very beginning. In both cases, I can see that in addition to the nice horizontal lines like in this tutorial: https://youtu.be/Dn1cVOxlX8c?t=109 I am getting those long running stitches across, like here:
![skewed_simulate](https://user-images.githubusercontent.com/4399755/73936424-1d9fa800-48e3-11ea-94f0-2931e3aaea81.png)
![circle_simulate](https://user-images.githubusercontent.com/4399755/73936421-1d071180-48e3-11ea-9d9d-9bdb6522592d.png)

I am guessing that maybe these stitches are the reason for the error, when they overlap. Is it possible?
All in all, I have two questions here: why circles sometimes just don't work and where those additional stitches come from.

Any help greatly appreciated.

**Comment by tyrosinase** [comment]
Aren't those just underpathing, which is normal?

I got the same error on a circle yesterday, which I solved with Union (Ctrl-+) which Inkscape will happily do with a single shape. I'm guessing it fixes whatever infinitesmal rounding error is causing the top node to trigger that, but I don't actually know.

**Comment by danielkschneider** [comment]
Hi
no the circle is not a circle, since InkScape will allow you to modify the circle into an arc after drawing it. If you look at the original circle just after drawing it you will see three control points. The one to the right allows you to open the circle. You will see that there are two points. After inserting the circle and after transforming it to a path the two points still will be there. If you don't believe me, do:
 extensions -> Visualize Path -> Number Nodes ....
 CTRL-Z after that to come back.

I don't have a good method to get rid of this extra node except transforming the shape with CTRL-L or otherwise and then repairing it. My usual node editing tricks won't work. Incidentally I also made a remark about this and similar problems in issue #603 (not the right place).  I'll have another look.

**Comment by tyrosinase** [comment]
Oh, to be clear: the circle I was dealing with had already been transformed to a path (Object-to-Path, Shift-Ctrl-C). Four fairly ordinary nodes, but the top node just makes Ink/Stitch unhappy somehow. Division by zero or something, I assume.

Union doesn't change the apparent status of any of the nodes, but in the XML one discovers that it's now got a transform on it (why, Inkscape, WHY) and that seems to bump Ink/stitch off whatever it was high-centered on.

**Comment by danielkschneider** [comment]
Ha good idea to look at the source code, but I maintain my theory about a node that sits on top of each other. I saved the file as plain SVG to get rid of the InkScape stuff, but the double node is still there: Let me copy the whole SVG code:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg8"
   version="1.1"
   viewBox="0 0 148 105"
   height="105mm"
   width="148mm">
  <defs
     id="defs2" />
  <g
     transform="translate(0,-192)"
     id="layer1">
    <path
       style="fill:#919400;fill-opacity:1;stroke:#de0000;stroke-width:1;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1"
       d="M 27.122398,204.45879 A 10.767694,10.462947
	  0 0 1 16.354704,214.92173 10.767694,10.462947
	  0 0 1 5.5870094,204.45879 10.767694,10.462947
	  0 0 1 16.354704,193.99584 10.767694,10.462947
	  0 0 1 27.122398,204.45879 Z"
       id="path1307" />
  </g>
</svg>
`
So, editing the source code is another option.

**Comment by tyrosinase** [comment]
Yeah, I do wonder about that spare node, but it's still around after a Union and isn't causing trouble after that.

OTOH, sometimes it ends up on top of the first node, and sometimes the last, so if it *is* causing the issue that might explain why some [converted] circles work without further nudging.

**Comment by lexelby** [comment]
This kind of thing is a source of constant confusion.  I have an idea for how to automatically clean up "invalid" shapes.  If it works how I think it will, these kinds of errors may mostly go away.

Regarding the running stitch inside the shape, as @tyrosinase mentioned, that's underpathing.  Ink/Stitch uses that to get from one section of the shape to another when doing fill stitch.  It gets covered by rows of stitches that come later.  You may notice that it's zig-zaggy in places.  Inn/Stitch tries to avoid having the underpath go in the same direction as the fill stitch rows to ensure that it does not disrupt the fill stitch pattern.

You can disable underpathing in Params   If you do, it will travel around the border of the shape instead.

**Comment by kaalleen** [comment]
I'll be closing this issue now. Fill shape handling for minimal overlapping borders has been improved. Please reopen, if the problem still exists within the next release.

**Comment by lexelby** [comment]
@kaalleen Shapely 2.0 will have a function to repair an object and make it valid!  Looks much more reliable than the buffer method.  I can't wait!

**Comment by kaalleen** [comment]
Wow, great! This could also simplify the break apart function a lot!

**Comment by lexelby** [comment]
It might!
