### ISSUE TITLE
JEF export failure in Inscape 1.0beta

### ISSUE THREAD

**Issue by janecaldwell** [inkstitch/inkstitch#611]
Macbook Air
OS: 10.14.6 Mojave

Recently upgraded to Inkscape 1.0beta in preparation for OS upgrade to Catalina.

When saving files as .JEF format, Inkscape generates the error message:
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte

This occurs whenever I attempt to save a digitized design as JEF. SVG format saves fine. If I execute "embroider," it WILL write JEF format to a file. Saving directly to JEF however has 0% success rate.

Other than this, Inkstitch seems to work quite nicely in Inkscape 1.0! Quite a relief, since I'm hitting a point where I need to do an OS upgrade soon-- but have put it off so I can keep digitizing. Inkstitch is awesome!

**Comment by lexelby** [comment]
Hi there!  Thanks very much for reporting this, we completely depend on our users for bug reports. Also thanks for trying out Ink/Stitch :)

Fortunately, we're aware of this problem and have a fix in the works.  Keep an eye out for a new release soon.

And yes, we fully support Inkscape 1.0, with the exception of the file saving issue of course :)

**Comment by kaalleen** [comment]
Closing the issue now.
Unicode errors should be eliminated by now.
Please reopen if I am wrong.
