### ISSUE TITLE
[probably not a bug] auto-thread cutting jump stitches

### ISSUE THREAD

**Issue by ancientpower** [inkstitch/inkstitch#612]
Do jump stitch cuts for fills have to be manually defined with commands or are they supposed to be automatic?

I have a machine that can automatically cut thread (Brother SE425) and I'm not sure if it's a quirk with the machine that it doesn't cut jump stitches in embroidery mode for whatever reason, or if it's an issue with my understanding of how inkstitch works.

**Comment by ancientpower** [comment]
Okay, I added trim commands and it still doesn't trim despite the machine allegedly being able to do so. I'm guessing this is just a weird issue with Brother's software ignoring the commands inserted by inkstitch?

**Comment by danielkschneider** [comment]
Did you try DST format ? I may be wrong, but I do have the belief that PES ignores trim commands. I got a Brother machine too and I most often use DST. I don't know if all Brother machines  do support DST. Also a warning: DST does not seem to have color information and you'll see randomly picked ones.

**Comment by ancientpower** [comment]
I've taken a design with multiple fills and inserted jump stitch trim commands, saved it as both PES and DST, and my machine doesn't automatically trim either of them. The machine has an automatic cutting function and there's a button to enable it in embroidery mode, but it doesn't seem to do anything even for the built-in designs. I think it may be some oddity with Brother's firmware.

**Comment by tyrosinase** [comment]
On 2/7/20 7:52 PM, ancientpower wrote:
>
> I've taken a design with multiple fills and inserted jump stitch trim
> commands, saved it as both PES and DST, and my machine doesn't
> automatically trim either of them. The machine has an automatic
> cutting function and there's a button to enable it in embroidery mode,
> but it doesn't seem to do anything even for the built-in designs. I
> think it may be some oddity with Brother's firmware.
>

My Brother PE-800 doesn't trim at all except end-of-color so I'm not
100% sure, but I seem to remember running across something mentioning a
trim length setting in one of the higher-end machine's menus and that it
defaults to a fairly long setting (on the theory that not trimming
something that's a jump stitch is better than trimming a bunch of
extra-wide satin unexpectedly).

**Comment by lexelby** [comment]
Hi there! Welcome to our community, and thanks for trying ink/stitch :)

If the se425 is anything like the se400 (and I'm pretty certain it is) then I'm sorry to say that it doesn't support trimming jump stitches.  I started it on an se400 and in fact still have it sitting on a shelf. :)

Yes, it can trim the jump stitches in lettering, but there's a catch.  It's treating every letter as a separate color, so it will cut the thread and wait for you to change to a different color.  You can restart it, but you probably should hold onto the thread because this machine can't "catch" the loose thread and pull it to the underside, at least not consistently.

When last I checked, the cheapest machine that supports jump stitch trimming is the Eversewn Sparrow X, but don't be fooled! It's pretty terrible at it.  Half the time it comes unthreaded after a trim.  Check Amazon for my review if you're curious.  The next cheapest is the Janome 400e, which is okay at trimming but sometimes leaves a bit of thread on top.  Not too hard to trim manually.

**Comment by ancientpower** [comment]
Ah, that's a shame. Very strange of them to have such an arbitrary technical restriction since it's clearly possible given how you can make a bunch of differently colored fills and have it cut (but unfortunately pause) after each of them.

Anyways, thanks for the clarification (and the work on inkstitch). I can't really afford to upgrade right now so I suppose I'll have to live with manually cutting the stitches. Though, this kinda makes me want to give a shot at splitting subsequent fills of the same color and rigging something together to automatically start them.

**Comment by lexelby** [comment]
Sorry :(

It's not as arbitrary a limit as you're suggesting.  It's not enough to just hit the start button after a color change.  This machine isn't designed to be able to start sewing again without a human holding the end of the thread to get it started.  It can sometimes do it, but other times it makes a rat's nest or pulls the thread out of the needle.  Trust me, I had very similar thoughts when I was starting out. :)

Best to make your jumps as long as possible, surprising though that may sound. That allows you to get your scissors up under the thread so you can trim it easily.

**Comment by tyrosinase** [comment]
On the rat's-nest note, I am probably alone in this but I would *love* a checkbox to not have start/stop tackdowns. It's sometimes a battle to correctly edit them out manually (especially with bean stitches) and it's far easier for me to deal with dropped stitches than with the little knobs of thread my machine creates.

I mean *yes*, no normal person is using an embroidery machine to topstitch dragon wings and crests and whatnot, but I am and those nests *show*.

![ArtDragon_Watermark](https://user-images.githubusercontent.com/9473609/74087069-071a5d80-4a57-11ea-8136-f2e6bbdf2bce.png)

**Comment by lexelby** [comment]
Until we add an option for that, you can fake it by adding a tiny manual-stitch path right before the first object for a given color.  Manual stitch doesn't do tie-in it tie-off.  As long as it's close to the next object, then the next object also will not have tie-in.

**Comment by tyrosinase** [comment]
On 2/8/20 9:43 AM, Lex Neva wrote:
>
> Until we add an option for that, you can fake it by adding a tiny
> manual-stitch path right before the first object for a given color.
> Manual stitch doesn't do tie-in it tie-off. As long as it's close to
> the next object, then the next object also will not have tie-in.
>

Yeah, that's how I usually do it now. Sometimes I even keep the paths in
the right order so that actually works. 😆
