### ISSUE TITLE
Font/design search (kinda offtopic)

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#614]
If it comes down to it I can construct the letters from scratch, but: I'm looking for either the design or the fonts here.

(It was my mother's, and I'm making memory quilts for my nieces. Since I can't figure out how to split this particular one, I figured I'd reproduce it for each of them on her machine, as "Somebody special _called_ me Grandma.")

![image](https://user-images.githubusercontent.com/9473609/74592069-a7d6c300-4feb-11ea-8fb7-89becaac73eb.png)

**Comment by wwderw** [comment]
Fonts are typically special to the digitizing software in question, so if you actually get fonts, you'll have to have the program that it's written for.  If you are talking about alphabets (raw stitch files that happen to be letters, arrangement and kerning is done by "you") that's something else and can be problematic if they don't have the stitch files that can be scaled to the desired size as raw stitch files are usually fixed.

It looks like the top two lines are the same font, so I would used use the "d" from "Somebody" and the "e" you can get from three words, so plenty of options.

Changing the tense of "calls" is probably going to prevent finding an exact pattern match.

**Comment by tyrosinase** [comment]
On 2/16/20 12:51 AM, wwderw wrote:
>
> Fonts are typically special to the digitizing software in question, so
> if you actually get fonts, you'll have to have the program that it's
> written for. If you are talking about alphabets (raw stitch files that
> happen to be letters, arrangement and kerning is done by "you") that's
> something else and can be problematic if they don't have the stitch
> files that can be scaled to the desired size as raw stitch files are
> usually fixed.
>
Alphabets is probably what I mean, though if I could find someone with
the program it would work. Bad habit left over from my typesetting days
(where they're not actually "fonts" either, the gentleman who taught me
the trade - a Baskerville - would remind me).

And I'll be doing it in the same size, so that's no worry - basically,
going to take panels from the un-stitched part of the sweatshirt and
re-create it almost exactly. (Or exactly, if comes down to it. The key
part is that I don't have two of the design. Dangit Past Karen, you
should have bought her two of those sweatshirts!)

> It looks like the top two lines are the same font, so I would used use
> the "d" from "Somebody" and the "e" you can get from three words, so
> plenty of options.
>
Yes, except (and I didn't mention this) all I have is Mom's sweatshirt,
bought at an Arkansas craft show almost two decades ago.

**Comment by wwderw** [comment]
If that sweatshirt has the design on it, take a picture of the design as flat as it can be.  Bring that into Inkscape (I usually keep template layers like this on the uppermost layer with opacity down, so the bottom layers will bleed through, I wish there was a template system in Inkscape like in Ai) and then digitize.  Unless there is something else that I'm missing, which is quite possible.

**Comment by tyrosinase** [comment]
Yeah, that was my terrible "take a bunch of snapshots of all the pieces of clothing to play around with arrangement" that should really never have seen the light of day. 😆

(or more accurately SHOULD have seen the light of day instead of me tossing them over a chair-back in our poorly-lit dining room for the pictures)
