### ISSUE TITLE
Ink Stiich issue - won't launch

### ISSUE THREAD

**Issue by sewgood** [inkstitch/inkstitch#617]
I have installed and reinstalled Ink Stitch several times now. If I do not 'Install add on's" then I am able to launch Ink Stitch but have issues that it does not recognize the shape (circle or rectangle - have selected and used object to path). Once I install the add on's  I receive the message below. I have read the other issues that pertain to this but am not sure how to change the file structure. 

![image](https://user-images.githubusercontent.com/61353396/75094903-68fdbb80-555d-11ea-9cff-044a53165725.png)
 

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=rect4518', '--extension=install', 'C:\\Users\\User.000\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgWA0LG0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 321, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 571, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by kaalleen** [comment]
Looks like inkstitch.exe got deleted. Antivirus programs often think it's a virus and remove it from the system. If you whitelist the file, Ink/Stitch will hopefully run properly.

**Comment by sewgood** [comment]
I have looked in the .zip file and my virus software and see no .exe file. Can you please send just the file so I can add. I also looked in the windows FR and DE .zip files and see no executable for Ink Stitch.
Thank you.

**Comment by kaalleen** [comment]
Have a look into the subfolders inkstitch/bin
Can you find it there?

**Comment by sewgood** [comment]
Thank you,
Found there. Works now, so excited to find out all it can do.

Cindy
