### ISSUE TITLE
Problem with under path and jump stitches. Can I manually create underpathing?

### ISSUE THREAD

**Issue by amordesoul** [inkstitch/inkstitch#623]
I tried using the "auto-route satin" feature to shorten the distance of the jump stitches on my design containing several satin columns (as in the dashed lines in the bottom elephant in the screenshot below). 
![image](https://user-images.githubusercontent.com/7471258/75377958-cf0d7a00-58a0-11ea-9d98-8671f473f8c3.png)

I received the following error message: 

```
**Traceback (most recent call last):

  File "inkstitch.py", line 44, in <module>

    print >> sys.stderr, traceback.format_exc()

  File "inkscape\share\extensions\inkex.py", line 283, in affect

  File "lib\extensions\auto_satin.py", line 54, in effect

  File "lib\stitches\auto_satin.py", line 313, in auto_satin

  File "lib\stitches\auto_satin.py", line 351, in build_graph

  File "lib\stitches\auto_satin.py", line 204, in __init__

AttributeError: 'Polygon' object has no attribute 'geoms'**
```

Looking through previous GitHub posts, the "object has no attribute" bit indicates that InkStitch doesn't play nice with SVGs/paths created outside of Inkscape. I did start this SVG file using Infinite Design (an Android app). 

InkStitch has allowed me to create the design using this file thus far. Is it possible to work around this? Is it possible to manually create the under path using a dashed line somehow? Below are the first few satin columns of my design so you can see the jump that I'm trying to get rid of...

![image](https://user-images.githubusercontent.com/7471258/75378720-2fe98200-58a2-11ea-8f7e-5714b0042d9d.png)

**Comment by wwderw** [comment]
Sure, you can create your own underpathing.  Can either set it to manual or have it as regular run stitches.  If you are going a  zig zag underlay, you'll need to do manual stitches or know the exact distance between the points (and this really on works if everything is consistent throughout the object (which based on your last example, it is not)) to make sure that it has "loft".

Since this is also coming from an outside program, be mindful of layers/order of the objects as well.  Sometimes it's easier to take that outside file (I'm saying outside file in this case, just to mean that it's coming from a different program, not necessarily that it was done by someone else) and just digitize "on top" of it versus trying to retro fit to work in embroidery.  Makes for more time, but all the parts a more manageable.  Even though that file may be vectors, how files are setup for embroidery may make it very hard to use it for anything else, unless make sure to save a copy of the unaltered file.

**Comment by lexelby** [comment]
> Looking through previous GitHub posts, the "object has no attribute" bit indicates that InkStitch doesn't play nice with SVGs/paths created outside of Inkscape. I did start this SVG file using Infinite Design (an Android app). 

I don't think that's what's going on in this case.  It looks like you've found a bug in Ink/Stitch, sorry about that!  I'll take a look at it when I next have a chance.

It might help us debug if you could post your SVG here, if you're willing?

**Comment by lexelby** [comment]
Oh never mind, this bug is actually going to be fixed in the upcoming version of Ink/Stitch.  Keep an eye out for a release. :)

**Comment by lexelby** [comment]
Here it is!  This one should work for you, @amordesoul:

https://github.com/inkstitch/inkstitch/releases/tag/v1.27.2

**Comment by amordesoul** [comment]
Thanks to you both for sharing your expertise.

SUCCESS! Or at least 99% success.

Note: you can ignore everything italicized below. Either installing the update or something in my workflow caused some of my custom satin columns to be converted back to a stroke stitches or just lose the params info. Reapplying the params for custom satin column fixed the problem. I thought I would include it my post in case it was something useful to the developing team.
_Custom satin columns are being deleted when using auto-route satin columns. Instead of auto-routing a running stitch up the middle of the satin column, it's deleting everything from the column except one line and converting that to a dashed line running stitch._ @lexelby - Github doesn't like .svg's but here is a link to it in my G Drive: https://drive.google.com/file/d/1kWpRwZ6-eGOb8NXbclgR6RstRR_Aon8D/view?usp=sharing

Also noteworthy: Checking off "Preserve order of satin column" produces some strange behavior if all paths within a layer are not selected. The position of the paths are reordered in relation to other unselected paths. However, it does preserve the order of the selected paths as intended.

@wwderw  - I realized my mistake when trying to manually create the running stitch. I was viewing the simulation from Params instead of the Simulate window and the dashed line was being interpreted by inkstitch as part of the custom satin column. I've now manually created running stitches and gotten exactly the results I had in mind (at least in simulation, I haven't actually embroidered any of this yet).

**Comment by lexelby** [comment]
Yay!  I'm glad you were successful.

Yeah, I could see how the "preserve order" behavior could be confusing.  When I wrote that, I wasn't sure what to do if the user selects objects from different layers.  The thing is, Ink/Stitch may need to break up satins and add travel stitches, and I wasn't sure what layers to put those in.  

My solution was to have it bundle up all the satins and running stitch together in a group and put that group where the first satin was in the stacking order.  I'd love to hear what you expected instead, I might have missed a good alternative.
