### ISSUE TITLE
how to install 1.27.2?

### ISSUE THREAD

**Issue by autosewer** [inkstitch/inkstitch#624]
Hi
I just downloaded and unzip all the files ,deleted all my previous inkstich files in my extensions folder and put the new ones, but nothing is showing in inkscape, I just followed instructions from the website, but obviously I am doing something wrong, any help? thank you! (I am newbie!)

**Comment by kaalleen** [comment]
Links on the homepage weren't correct, since the download files got different names after we have changed our build system. Maybe you could just try again?

Which operating system are you using to run Ink/Stitch?

**Comment by autosewer** [comment]
Ok I tried again with no luck, I am using Ubuntu 16.04 ,Inkscape 0.91 so I download and unzip, I get a folder called inkstitch-master I go inside and copy everything to my user extensions folder,didn't work then I tried putting everything in Inkscape extensions folder, same result, I am pretty sure I am doing something wrong :)

**Comment by lexelby** [comment]
Ah!  You grabbed the source code rather than the release archive.  Try this:

https://github.com/inkstitch/inkstitch/releases/download/v1.27.2/inkstitch-refs-tags-v1.27.2-linux-en_US-ff55eccaa4069d9cbcd2dd74890e3797.zip

**Comment by lexelby** [comment]
@kaalleen I see what you mean about different file names.  I'll set if I can fix that...

**Comment by autosewer** [comment]
I knew i was doing something dumb :) Thanks a lot!
