### ISSUE TITLE
Download and install not working

### ISSUE THREAD

**Issue by sandraball** [inkstitch/inkstitch#627]
My 2 attempts March 1, 2020 to DL the inkstitch 1.27.2 file contained errors in all files and I was unble to transfer/ extract the plug-in to inkscape extensions. When I attempted March 2nd, one of the *.py files was rejected by my virus SW citing a security risk. I do not know if I am doing something wrong or if there is something wrong with the files themselves.

**Comment by kaalleen** [comment]
@sandraball Sorry for the late response. We see virus software complaining about Ink/Stitch a lot on Windows Systems. We don't know how to prevent them from be alarmed about our Plugin and usually tell users to white list the Ink/Stitch folder within the virus software.
Hope this will help you to solve your issue and get Ink/Stitch working!

**Comment by kaalleen** [comment]
Same issue as #613 
The problem can be discussed there, if more questions are present.
