### ISSUE TITLE
Something strange in Satin Column page

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#630]
The panel "Info" just after the little duck
_Info: Rungs have to be **shorter** than the satin column itself. Otherwise Ink/Stitch will switch directions or you receive the following message: error: satin column: One or more of the rungs doesn't intersect both rails. Each rail should intersect both rungs once.
This **shorter** sounds very strange?_
https://inkstitch.org/docs/stitches/satin-column/

**Comment by lexelby** [comment]
Hmm, I think this is old information.  Here's what that's about:

Ink/Stitch has to figure out which of the lines in a satin column are the rungs and which are the rails.  It sounds easy but it's actually a little tricky for a computer program to get the right answer every time.

It used to do it like this:

_The rails are the two longest lines.  The rungs are everything else._

That meant that the rails had to be longest -- a short, very wide satin would not work!

Now it does it like this:

_The rungs are the lines that intersect exactly two other lines.  The rails are everything else._

That works for everything including short, wide satins.

@kaalleen I think we can get rid of this note in the docs?

**Comment by kaalleen** [comment]
When was it supposed to change? I just had a test on it, it still seems to be the rule?

![satin-column_rails_and_rungs](https://user-images.githubusercontent.com/36401965/76146376-7608c780-6092-11ea-8cc6-71eab61812fe.png)

But I still think it should be rephrased to be understandable. It is only relevant, if there are exactly two rungs.

**Comment by lexelby** [comment]
Ah yes!  I forgot about the two rungs situation.  How about we just say, "avoid having exactly two rungs" instead?  Much easier to understand and remember.

**Comment by kaalleen** [comment]
Good idea! The website is updated, just needs an update in French as well. @Augusa ... could you have a look at it? It's already included in English: https://inkstitch.org/fr/docs/stitches/satin-column/

**Comment by Augusa** [comment]
It's translated.
