### ISSUE TITLE
simplestyle error

### ISSUE THREAD

**Issue by fnavas00** [inkstitch/inkstitch#632]
So all day today I was working on digitizing a design. I use ink/stitch on Windows 10. The original design was an SVG created in Adobe illustrator. I don't recall whether or not I created outlines from the letters (AKA in inkscape: object to path). I had 0 error messages with the original file but I didn't like how a certain part of the text stitched out so i downloaded some fonts, and within inkscape I typed out some text... converted that text to a path (object to path) and that's when I got this error message: 

_

> Traceback (most recent call last):
> 
>   File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
> 
>   File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 586, in effect
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 322, in __init__
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 551, in create_tabs
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 481, in get_nodes_by_class
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 167, in get_nodes
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 159, in descendants
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 159, in descendants
> 
>   File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 145, in descendants
> 
>   File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
> 
>   File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 148, in has_style
> 
>   File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\simplestyle.py", line 179, in parseStyle
> 
> ValueError: dictionary update sequence element #6 has length 3; 2 is required

_

**After getting this specific error message it will basically corrupt the file and ink/stitch will no longer work for that SVG if you save it.**

I attempted to create a new file, repeat the process of typing the same text, converting the text to path and creating satin columns. Then I get the same error message. I repeated the process a few times using different variations each time.. creating new files, restarting inkscape, typing different text, using different fonts.. same results. At this point I am worried and thought maybe something is wrong inkscape or the plug-in so I re-installed inkscape and downloaded the latest ink/stitch update.

To make sure I installed the new update correctly. I created a new file.. and created two satin columns one manual (two combined parallel lines) and one with the pencil stroke( ink/stitch > satin tools > convert line to satin column) I hit the params, plug-in works fine. . 

I repeated the process of converting text to path (object to path) and got the same error message mentioned above. Heres when I got the theory that maybe the function "Object to path" is causing these issues... so i opened a new file, with the polygon/ellipse tool I created 1 circle and 1 hexagon, then converted those two objects to paths and got these error messages:

**Circle  (Object to path)**

> _path3803: error: Fill: Shape is not valid.  This can happen if the border crosses over itself._

**Polygon  (Object to Path) :**

> _Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x05F841E8>> ignored_

within this same file, I created a circle and hexagon shape using the bezier pen, hit the params and they work perfectly fine.

for some odd reason, the object to path error messages don't always happen. It seems the more complex the object is the more likely these error messages are to appear

**Comment by lexelby** [comment]
The circle and polygon error messages are ones we've seen before, and we're working on a fix.  The one you're getting for text... that's a new one.  I haven't every seen that before!  Could you post an SVG that has that error so that I can see what the style in that shape looks like?

**Comment by tyrosinase** [comment]
On 3/8/20 9:08 AM, Lex Neva wrote:
>
> The circle and polygon error messages are ones we've seen before, and
> we're working on a fix. The one you're getting for text... that's a
> new one. I haven't every seen that before! Could you post an SVG that
> has that error so that I can see what the style in that shape looks like?
>

I've gotten the "length 3; 2 is required" error at least once, and now I
can't remember the circumstances. I poked at the XML and nothing jumped
out at me; a few Unions fixed the problem. I thiiiiink it was on a
stroke-to-path'd object but I wouldn't swear to it now.

I can be even less helpful upon request. 😉

**Comment by lexelby** [comment]
Haha, thanks.  If you ever see it again, I want a copy of the offending object :)

**Comment by fnavas00** [comment]
Sure thing, I first noticed the error message when trying to convert the text  "Serving Daily" to path using the font [Ananda ](https://www.dafont.com/ananda-2.font)Black from Dafont. In this file I used a different font called spacejunk:XL I am not sure if the file will ever work again or maybe the issue could depend on your system I am sure SVG's are very complex but its still not working f
[corrupt file inkstitch.zip](https://github.com/inkstitch/inkstitch/files/4303278/corrupt.file.inkstitch.zip)

or me. I've even tried importing the SVG into a new file but still facing the same error.

**Comment by tyrosinase** [comment]
On 3/8/20 9:59 AM, fnavas00 wrote:
>
> Sure thing, I first noticed the error message when trying to convert
> the text "Serving Daily" to path using the font Ananda
> <https://www.dafont.com/ananda-2.font>Black from Dafont. In this file
> I used a different font called spacejunk:XL I am not sure if the file
> will ever work again or maybe the issue could depend on your system I
> am sure SVG's are very complex but its still not working f
> corrupt file inkstitch.zip
> <https://github.com/inkstitch/inkstitch/files/4303278/corrupt.file.inkstitch.zip>
>
> or me. I've even tried importing the SVG into a new file but still
> facing the same error.
>

Have you tried a Union on the object (just the one by itself, not
combined with anything)? Sometimes that manages to shed whatever cruft
has accumulated on an object. Fonts and paths-to-object seem
particularly prone to weird little curlicues, and Union sometimes helps
clear those out.

**Comment by kaalleen** [comment]
Within the "S" we find style attributes which will confuse the simplestyle function:
```
font-family:'spacejunk:XL';
-inkscape-font-specification:'spacejunk:XL';
```
```
  File "/usr/share/inkscape/extensions/simplestyle.py", line 179, in parseStyle
    return dict([[x.strip() for x in i.split(":")] for i in s.split(";") if len(i.strip())])
```
The `:XL` will make a third value, where there are only supposed to be 2.

**Comment by lexelby** [comment]
To me that looks like a bug in simplestyle.  :(  I guess we'll have to implement our own version.
