### ISSUE TITLE
Inkstitch 1.27.2 with Sierra

### ISSUE THREAD

**Issue by ValBe06** [inkstitch/inkstitch#634]
I have a mac computer with sierra OS on it. 
I install Inkscape 0.92 with the extension of Inkstitch 1.27.2. Inkstitch was in my extension menu, but I had the following issue report : 
I delete inkstitch 1.27.2 and install the sierra version, and then I had ... nothing No extension in Inkscape 
Can someone help me, please ? 

![IMG_0083](https://user-images.githubusercontent.com/60555630/76168837-74630080-6173-11ea-931b-96fc2b0fa3b6.jpeg)

**Comment by kaalleen** [comment]
Hello to the Ink/Stitch project @ValBe06 !
First I have to bring bad news to you. Our newest version (Ink/Stitch v1.27.2) sadly doesn't work on macOS Sierra.

But you can get a former Ink/Stitch version (as you have tried). It has some issues with macOS Sierra (such as a blank print pdf screen) but most functions will work. Ok let's see how to get you started.

I had a false download link on the website. So, let me post the right one here. Download this version (french): https://github.com/inkstitch/inkstitch/releases/download/v1.26.2/inkstitch-v1.26.2-osx-sierra-x86_64-fr_FR.tar.gz and extract it as you have done with the newest version before.

It is very important, that the files are directly inside the extensions folder of Inkscape. You will see a lot of .inx files, a .py file and a folder named "inkstitch". Once you have done so, the extension should show up in Inkscape on restart.

Come back to us, if you are still having problems with the installation or having any other issues.

**Comment by ValBe06** [comment]
Thank you so much Kaaleen ! At first sight, it seems working. Just tested parameters et simulation, for the moment no bugs ! Still have to test embroidery and save ... (which did not work previously)

**Comment by kaalleen** [comment]
Great, let us know if you have been successful!
