### ISSUE TITLE
Can we use one of the patch photos as an example image for the Inkscape Beginners' Guide?

### ISSUE THREAD

**Issue by Moini** [inkstitch/inkstitch#635]
Hi @lexelby ,

I'm currently working on adding examples to https://inkscape-manuals.readthedocs.io/en/latest/why-use-inkscape.html and I would like to include one of your example patch photos (the 'I love Vectors' one) into the list.

However, the guide is CC-By-SA licensed, and your repository here is GPL (and they are incompatible).

Would you consider licensing the photo as CC-By-SA for us, please?

**Comment by lexelby** [comment]
Absolutely!  


<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />The image below is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

![01-i_heart_vectors](https://user-images.githubusercontent.com/4446653/82128013-ad2be100-9785-11ea-9d3e-4bc4604bcaba.jpg)

**Comment by lexelby** [comment]
Let me know if you need any others.

**Comment by Moini** [comment]
Cool, thank you very much, @lexelby ! This is a very nice example of what can be created with Inkscape and with community-driven extensions.
