### ISSUE TITLE
Threads to layers feature suggestion

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#636]
I've been ganging some bought designs lately and I had a realization: you know what would be super-helpful? Being able to import a stitchfile and having each color change assigned to a different layer.

**Comment by lexelby** [comment]
You get pretty close to that if you just do File -> Open on a DST or PES or whatever.  Each color is a group, not a layer, but check this out: in the Objects panel, you can toggle a group into a layer and vice versa by left-clicking the little symbol to the left of it.  I figured that one out by accident.  That's also when I learned that you can nest layers in Inkscape.

**Comment by tyrosinase** [comment]
On 3/10/20 11:15 AM, Lex Neva wrote:
>
> You get pretty close to that if you just do File -> Open on a DST or
> PES or whatever. Each color is a group, not a layer, but check this
> out: in the Objects panel, you can toggle a group into a layer and
> vice versa by left-clicking the little symbol to the left of it. I
> figured that one out by accident. That's also when I learned that you
> can nest layers in Inkscape.
>

That actually does the trick, thanks! I had poked at those little
toggles and for some reason couldn't figure out what they were doing.
(The Objects panel is pretty opaque; I confess I usually ignore it and
use the XML panel for re-ordering things. Not sure what that says about
me that I think XML is easier to understand but here we are.)

**Comment by tyrosinase** [comment]
Okay, I wrote up the process (aimed at folks who don't regularly use Inkscape *or* Ink/Stitch). Feel free to snag it for the documentation. https://silverseams.com/2020/03/ganging-embroidery-designs-with-ink-stitch/
