### ISSUE TITLE
G-code cut/pause command required.

### ISSUE THREAD

**Issue by krsshtx** [inkstitch/inkstitch#649]
To make thread colour change possible.
Looks like there is no command addded to g-code after "attach commands to selected objects" like cut (scissors) or pause. Both has no effect.

**Comment by lexelby** [comment]
Great idea!

Out of curiosity, have you made a homebrew embroidery machine that can change colors?

**Comment by krsshtx** [comment]
> Out of curiosity, have you made a homebrew embroidery machine that can change colors?

No, just need an interrupt to change thread.

Can only dream about multi-needle mechanics. 
TFMX looks good https://www.sewmanyparts.com/pages/DownloadManuals/default/1/

**Comment by kaalleen** [comment]
The stop command should be working with the next Ink/Stitch release.

What about cut? Do you have the possibility to tell your self made machine to cut the thread?
If so (wow) ... which G-Code command would you need for this purpose?

**Comment by krsshtx** [comment]
No, i don't. I don't know.
May be jameskolme can tell:
https://github.com/EmbroidePy/pyembroidery/issues/34#issuecomment-431798861

> What about cut? Do you have the possibility to tell your self made machine to cut the thread?
> If so (wow) ... which G-Code command would you need for this purpose?

**Comment by kaalleen** [comment]
Hm, I think this would be pretty advanced for a self made embroidery machine. Maybe we should skip this function until somebody comes up with a machine able to cut the thread.
The updated gcode writer should respect the stop (pause) command. Let's wait for the next release, so you can try if it is working for you.

**Comment by krsshtx** [comment]
I've tried attach commands -> stop(pause machine) on text. 
4 pause marks were added to every letter. 
After embroidery file was written no new commands was there.
Bad luck.
