### ISSUE TITLE
Updater extension

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#65]
Let's add another extension that upgrades inkstitch to the latest version.  It would download the latest tarball/zip for the current platform and unzip it on top of itself.

This should work fine on Linux and Mac.  Not sure if Windows will balk at replacing the currently-running executable.

**Comment by AkiraNorthstar** [comment]
The whole tarball, or only .inx and .py (compiled .py files)?

**Comment by lexelby** [comment]
Theoretically I could try to ship just the files that changed.  In practice, that will be tricky and it's probably not worth the time, since the tarball isn't unmanageably huge.

**Comment by wwderw** [comment]
>  Not sure if Windows will balk at replacing the currently-running executable.

There were some Windows programs that did this when I was running Windows on bare metal.  The only time that it would balk is if it needed admin privileges and they weren't on the admin account (which unfortunately, most of the time, most Windows users are on the full admin account).

**Comment by lexelby** [comment]
Updating is now super easy, so I don't think we need an updater extension.
