### ISSUE TITLE
Problems with v1.27.2 - High Sierra (either installation or "non fix")

### ISSUE THREAD

**Issue by Gibbosenior** [inkstitch/inkstitch#650]
Hi, I'm very new to this. Installed Inkscape and inkstitch on my 2011 iMac (running High Sierra 10.13.3) on 23 of March. Learning fast, but couldn't get Print/Realistic preview to work. Saw your update v1.27.2 and I think I've installed it correctly, (just copied files to extension folder and restarted Inkscape) 
Print/Realistic preview still gives blank page.
It also feels like everything has slowed down, but that's just subjective.
It's such a great tool it would be good to get it all running correctly

**Comment by kaalleen** [comment]
Hm, this interesting. I thought it wouldn't work on High Sierra at all.

We changed our build system right before the newest release. Sadly it only supports macOS Catalina. Also we don't really have a lot experience with Apple systems. So we appreciate any help we can get on this topic.

**Comment by Gibbosenior** [comment]
I’ll be whatever help I can, but I’m certainly not an expert! (And its not always easy to tell whether a problem is a glitch or just my incompetance.)
Basic info. 
Inkscape required something called XQuartz to run on my Mac, (which I assume is a modern equivalent of the “Virtual PC” that was required to get any Windows software to run on a Mac back in the day.) It was installed as part of my downloading inkscape. I then installed Inkstich, (pretty much in line with the Tutorial videos, (but I don’t think the version references quite matched the video.)) On opening Inkscape/inkstich most things seem to run more or less as per the Tutorial Videos, with the exception of the Print/Realistic preview. Which opens a new window with a header bar of “ Inkstich-gui” but the window remains blank.

I have had a few other issues, (trying to save one design to .dst format returning errors even though “simulation" runs ok, solved by running “embroider" which then saved ok,) but they are probably not “Mac related”

I’ll try to keep a more accurate log of what works and what doesn’t, but let me know how else I can be useful.

**Comment by kaalleen** [comment]
I am still confused it works in High Sierra at all. This would be good news :)
Hm, just to confirm, have you removed all extension files before adding the new version?

**Comment by Gibbosenior** [comment]
If you’re confused I stand no chance!! But as you say still good news.

As to removing all extensions prior to installing v1.27.2. No I’m afraid I didn’t. Displaying my ignorance again, but I had thought of 1.27.2 as an upgrading patch, rather than a whole new install so just dumped it into the extensions folder along with the existing.

Since your message I’ve been through looking for duplicate files and deleting the older version. On a very brief test, things still seem to run as before, (No Realistic Preview/Print, the same blank page opens, subjectively it feels like the the slowdown has been reversed, but otherwise no change.)

Would you like me to try removing all InkStitch extensions and reinstalling just v1.27.2 from scratch?

I wouldn’t want to lose access to what I have (even without the Print, its gold dust for me!) but assumedly I can go back and reinstall the older version if we can’t get v1.27.2 to work.

**Comment by kaalleen** [comment]
Oh, I really don't want to break your running system ;)
I could ask a friend to run a test. I will report.

**Comment by kaalleen** [comment]
I had someone test Ink/Stitch on High Sierra. No luck at all. So be careful with what you've got ;)

**Comment by Gibbosenior** [comment]
Hi, 
Thanks for the info. Situation may be resolved soon as my ancient MacBook has to be replaced so I will have access to Catalina!
Thanks for taking the time to test.
