### ISSUE TITLE
Keyboard Shortcuts with or without "(No preferences)" ?

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#652]
I want to create a keyboard shortcut for the window : Ink/Stitch>Commands>Attach commands to selected object
Two actions are displayed, with or without "(No preferences)".

I choose with "(No preferences)" :
\<bind
     key="KP_Add"
     modifiers="Ctrl,Shift"
     action="org.inkstitch.commands.fr_FR.noprefs"
     display="true" \/>

But when I make the keyboard shortcut it doesn't work. The file preferences.xml are read !

If I choose :  org.inkstitch.commands.fr_FR, the file is NOT read.

It's ok ? It looks like it's reversed...

**Comment by kaalleen** [comment]
It should work this way:
* No preferences would execute the function without asking you to specify which commands are to add (it will take the last settings)
* Without "no preferences" should open the dialogue window for you to choose the commands to add.

I am not sure if this answers your question?

**Comment by LaureFR38** [comment]
You answered my question. This is exactly what I wanted to know. 

No preferences mean : Do not ask user preferences again (it takes the last parameters to save in preferences.xml)
Before, I thought it meant not reading preferences.xml ;-)

Perfect ! Thank you so much !
