### ISSUE TITLE
Error with Ink/Stitch>Print "match_palette"

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#656]
Hello,

I'm trying to help someone from the French Inkstitch Facebook group.
She draws one full shape with bezier, she puts a color from the default palette of Inkscape.
When she runs Ink/Stitch> Print, the following error is displayed:

Traceback (moste recent call last):
File "d:\a\inkstitch\inkstitch\inkscape.py" line 44, in <module>
File "d:\a\inkstitch\inkstitch\share\extensions\inkex.py" line 483, in effect
File "d:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py" line 279, in effect
File "d:\a\inkstitch\inkstitch\lib\threads\catalog.py" line 45, in match_and_apply_palette
File "d:\a\inkstitch\inkstitch\lib\threads\catalog.py" line 66, in match_palette
ValueError: max() arg is en empty sequence

Can you help us, please ?

**Comment by LaureFR38** [comment]
I think the problem is due to her installation which is separated into 3 directories under Windows:
- C:\Program Files (x86)\Inkscape 
- C:\Users\<user_name>\AppData\Roaming\inkscape (is almost empty)
- C:\Users\<user_name>\AppData\Local\VirtualStore\Program Files (x86)\Inkscape\share

We have created new palettes and I think she has not put them in the right place.

I'll keep you informed.

**Comment by lexelby** [comment]
Wow, never seen that one before.  Thanks for reporting this bug.  It's definitely a bug in ink/stitch.  They shouldn't see a traceback like that even if they did something "weird" with the installation.

**Comment by lexelby** [comment]
Looking at the code, it's expecting to find the pre-packaged palette files that are bundled with Ink/Stitch.  The directory is empty and that's triggering a bug in the code.

It expects to find the palette folder one level above where inkstitxh.exe is.  So if inkstitch.exe is in `.../inkstitch/bin/inkstitch.exe`, there should be a directory at `.../inkstitch/palettes/` full of *.gpl files.

**Comment by LaureFR38** [comment]
It works after installing "like everyone else does".

Now, the installation is clean:
- C:\Users\<user_name>\Desktop\inkscape\
- C:\Program Files (x86)\inkscape\

A new gpl file has been put into "C:\Users\<user_name>\Desktop\inkscape\palettes"
Unused gpl files in "C:\Users\<user_name>\Desktop\inkscape\palettes" have been deleted.
Nothing has been changed in "C:\Users\<user_name>\Desktop\inkscape\extensions\inkstitch\palettes"

Thanks for looking!

(sorry for my English)

**Comment by LaureFR38** [comment]
Do I close the subject or leave it open for the discovered bug?

**Comment by lexelby** [comment]
Oh good, glad everything is working for you now!

Let's leave this here so we remember to fix the bug.

**Comment by LaureFR38** [comment]
I also noticed :

If I put a gpl file with bad syntax (one error with only two RVB number) in the directory "C:\Users\\<user_name>\AppData\Roaming\inkscape\extensions\inkstitch\palettes", I get the following error when I run Print: 

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\print_pdf.py", line 279, in effect
  File "d:\a\inkstitch\inkstitch\lib\threads\catalog.py", line 97, in ThreadCatalog
  File "d:\a\inkstitch\inkstitch\lib\threads\catalog.py", line 15, in __init__
  File "d:\a\inkstitch\inkstitch\lib\threads\catalog.py", line 27, in load_palettes
  File "d:\a\inkstitch\inkstitch\lib\threads\palette.py", line 19, in __init__
  File "d:\a\inkstitch\inkstitch\lib\threads\palette.py", line 52, in parse_palette_file
ValueError: invalid literal for int() with base 10: ''


I thought that the files of this directory were not read but only used when we click on "Install add-ons for inkscape"

Is it the same bug ?

**Comment by kaalleen** [comment]
@LaureFR38 No, this is a different error, thanks for mentioning it. Ink/Stitch reads the file for the print output to find matching colors, so it can name the colors in the output correctly.

I created a pull request to fix these errors - which basically means to ignore them. We just don't want to see error messages but the print output, even when we don't know how to name the colors.

**Comment by LaureFR38** [comment]
@kaalleen 
I created my own color palette (with unknown brands). I put this file in: "C:\Users\<user_name>\AppData\Roaming\inkscape\extensions\inkstitch\palettes"
So I must also put it in: "C:\Users\<user_name>\AppData\Roaming\inkscape\palettes"
else the name of the color are no longer displayed in the pdf.
When I will want to add a new color, I have to think to modify these 2 files in these 2 directories. 
If that's correct then it's not very practical...

I also noticed another error :
In my drawing, if I put a color from an Inkstich palette and another color from another Inkstich palette, then in the PDF file the names of the colors are no longer displayed. We cannot mix the pallets ?

**Comment by kaalleen** [comment]
Hm, I will have to look into the code. I am not really sure, if it has to be in both places...?!?
Maybe @lexelby knows more.

I think mixing palettes is not possible at the moment. You could update the thread names in the PDF output though. I know, this isn't the best workflow. But I don't know how to improve it right now.

The color palette name is not being saved into the object by Inkscape when you chose the color. So (in my understanding) our way to find out which palette was used, would be to search for matching colors in the palette files. The file with the most matching colors is chosen as the color palette. @lexelby please correct me, if I am wrong. I haven't spend a lot of time with the color palette issues yet.

**Comment by LaureFR38** [comment]
Thank you for your reply. Let me give you details:

The Inkstich palette directory is : "C: \ Users <nom_utilisateur> \ AppData \ Roaming \ inkscape \ extensions \ inkstitch \ palettes "
The Inkscape user palette directory is : "C: \ Users <nom_utilisateur> \ AppData \ Roaming \ inkscape \ palettes"

Inkscape display in the bottom right the palettes available in the user directory of Inkscape (not Inkstitch).
After installing Inkstich, you must copy the palettes of Inkstitch in the user directory of Inkscape (Install Add-Ons for Inkscape), otherwise it is not displayed at the bottom right..
I think that when printing, the inkstitch palettes should not be read. When drawing, the Inkscape user palettes are read. So it should be the same for printing. 
Why go look in Inkstich, it is confusing ? There is no more information in inkstitch than in inkscape.
What do you think ? Am I wrong ?

I understood that you shouldn't mix the pallets. So I could make a palette file that contains the colors I want to mix ;-) I will forward the information to the French Facebook group.

**Comment by kaalleen** [comment]
Oh, I see. Maybe it is because we wanted to exclude not thread related palettes? @lexelby what would you think if we check on the inkscape directory instead (possible?) and search for matching colors only in palettes with the prefix `inkstitch`? Does it make sense?

**Comment by LaureFR38** [comment]
For me it would be great. And I will call my file inkstitch_myColors.gpl.

**Comment by kaalleen** [comment]
Ok, I think it's doable. I just noticed Ink/Stitch palettes are named InkStitch***. So that would be the naming rule (e.g. `InkStitch_myColors.gpl`).

I updated #660 to do this. If you want to do a testrun on it, here are the builds: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-threadlist-output

macOS builds are missing due to some other error in our build system.

**Comment by LaureFR38** [comment]
I confirm that the following errors have disappeared:
- missing pallet error in inkstitch
- synthase error in the gpl file in inkstitch

Thank you so much !

Keep staying :
- No longer read the Inkstich palettes but only Inkscape (so as not to have to duplicate the gpl files)

**Comment by kaalleen** [comment]
Ups, sorry for that. Now it should be working?!?

**Comment by LaureFR38** [comment]
![test1](https://user-images.githubusercontent.com/63351363/79641212-5d61f600-8196-11ea-95b3-35e2bd3f5828.jpg)
![test2](https://user-images.githubusercontent.com/63351363/79641251-9ac68380-8196-11ea-84dc-351cca37a600.jpg)

**Comment by LaureFR38** [comment]
Yes ! Perfect !
Merci :-)

**Comment by LaureFR38** [comment]
Yes ! Perfect !
You have solved 3 problems.
Thank you !

Be careful when creating the palette file, you must put a tab and not a space between the RGB values ​​because InkStitch does not accept it (while Inkscape accepts the space and the tab)
Do not forget to write correctly ;-)

**Comment by kaalleen** [comment]
This should be fixed by now too?!?

**Comment by lexelby** [comment]
Hi folks!  I developed the palette-matching feature without having a very firm grasp on how people would actually use it, so this is really helpful.  Here's what I was thinking when I created it:

1. Digitizers want to be able to have thread manufacturer names and numbers on the print-out so their customers/users know what colors they recommend.
2. Multiple manufacturer thread palettes may have the same color, especially black (0,0,0).  We don't want a print-out to say "Gunold black" and "Madeira Red" on the same print-out.  So it finds the palette that has the most number of threads that match and assumes that that is the palette you used when you created the design.
3. Not everyone will do "Install Ink/Stitch Add-Ons for Inkscape" to install the palettes.  This is especially the case when you open an SVG that someone else created.  We still want thread manufacturer names in the print-out.
4. Because of 3, we do palette-matching using the `*.gpl` files bundled with Ink/Stitch rather than the ones in the Inkscape extension directory.
5. I never thought of someone deleting the palettes bundled with Ink/Stitch! (oops)

4 is a good default, but it's a total pain for you to have to put your palette in two places!  Seems to me like Ink/Stitch should read _both_ locations when doing palette-matching.  Would that work?

**Comment by LaureFR38** [comment]
I understand, and you are right.

What do you think of the following rule that could satisfy everyone :

nbInkstitch = number of colors found in the most matching InkStitch gpl file.
nbInkscape = number of colors found in the most matching InkScape gpl file.

IF nbColorInkstitch> = nbColorInkscape THEN it is the GPL file of Inkstitch which will be used ELSE it will be the GPL file of Inkscape

**Comment by kaalleen** [comment]
You can still chose your own palette in the print settings if Ink/Stitch didn't make the correct guess.

If @lexelby agrees to the current version, it will be so, that if a filename exists in both places, the one in the Inkscape folder is the one to be chosen.
