### ISSUE TITLE
Lettering module: ensure consistent character set

### ISSUE THREAD

**Issue by jwildeboer** [inkstitch/inkstitch#658]
Problem: some symbols are not always available. For example the # (hashtag) and @ symbol are not always included.

Ink/Stitch Medium Font: Has @ but not # 
Ink/Stitch Small Font: Has @ but not # 
TT Director: Has no @ but has # 
TT Masters: Has @ but no # 

Solution: define supported characters and include them in all used stitch fonts.

I hope at least @ and # can be included by default, as they are quite useful when stitching Hashtags and Twitter/email addresses :)

It's a minor issue, but I wanted to make sure it doesn't get lost completely. I LOVE Ink/Stitch! I just want it to be a little more perfect :)

I am using current release version on both Mac OS and Linux.

**Comment by kaalleen** [comment]
Thanks for bringing this up to our attention, it makes totally sense. It will be a common combination of characters to use. I created a pull request to solve this issue.
