### ISSUE TITLE
use of u"→" in fonts code causing ascii codec error?

### ISSUE THREAD

**Issue by machow** [inkstitch/inkstitch#672]
Hey--thanks for this incredible extension!

When I try to add text with inkstitch, I get the following error:

```
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 241, in apply
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/lettering.py", line 195, in update_lettering
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 122, in render_text
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font.py", line 95, in _load_variants
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font_variant.py", line 52, in __init__
  File "/home/runner/work/inkstitch/inkstitch/lib/lettering/font_variant.py", line 56, in _load_glyphs
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 61: ordinal not in range(128)
```

It looks like this occurs when it tries to handle the `u"→"` in [this file](https://github.com/inkstitch/inkstitch/blob/1e0280db10cbb987842648f78f37bb9acc827305/lib/lettering/font_variant.py#L28-L31). Any idea what might be going on? I'm not totally sure what python version inkstitch is using, but if there's an easy way to programmatically run / test this extension code, I'm happy to dig deeper :).

Here is the docker file I'm using to run it:

<details>

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y inkscape unzip python-lxml hicolor-icon-theme --no-install-recommends && \
    rm -rf /var/cache/* && \
    rm -rf /var/lib/apt/lists/*

ADD ./inkstitch-refs-tags-v1.27.2-linux-en_US-ff55eccaa4069d9cbcd2dd74890e3797.zip /root/.config/inkscape/extensions/inkstitch.zip

RUN cd /root/.config/inkscape/extensions \
    && unzip inkstitch.zip

VOLUME /images
WORKDIR /images

ENTRYPOINT ["inkscape"]
```

</details>

I run it using these commands my mac, in order to forward X11:

```
xhost + 127.0.0.1
docker build -t inkscape .
docker run -it -v images:/images --rm -e DISPLAY=host.docker.internal:0 inkscape
```

**Comment by lexelby** [comment]
Cool trick with Docker!  Ink/Stitch is using Python 2.7.  I'm not sure what's up with this error... it's strange that no one else has seen it.  In any case, it's a bug, and we'll get to the bottom of it.  Thanks for reporting this!

**Comment by kaalleen** [comment]
Hm, seems to be a general issue now.
Haven't experienced it before, but working on the last pr i got this for the new exception header:

```
Traceback (most recent call last):
  File "inkstitch.py", line 56, in <module>
    print >> sys.stderr, _("Ink/Stitch experienced an unexpected error.")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 44: ordinal not in range(128)
```

**Comment by lexelby** [comment]
I don't think that's the same thing?  That's a different section of the code.

**Comment by machow** [comment]
Ah, I think this is an issue with how ubuntu is setup in docker. It looks like `sys.getfilesystemencoding()` is ASCII, so it hits the issue when opening a file with a unicode name. Installing locales and putting this in the Dockerfile fixed it...

```
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

In case it's useful, here are the SO overflow posts I checked out:

https://stackoverflow.com/questions/9500173/python-open-unicode-filename-behaviour-different-across-oses

https://stackoverflow.com/questions/27931668/encoding-problems-when-running-an-app-in-docker-python-java-ruby-with-u

Seems like something that has to be handled in the OS, rather than inkscape so will close the issue--thanks for taking a look :).

**Comment by lexelby** [comment]
Reopening, Ink/Stitch definitely shouldn't crash even if your locale is set differently.  Thanks for tracking this down!

**Comment by kaalleen** [comment]
> I don't think that's the same thing? That's a different section of the code.

I was wondering all the time, why it didn't crash on my testings before. But when @machow mentioned the locales it all makes sense. The only thing that has changed was, that I've done the translation.
