### ISSUE TITLE
Mac OSX Catalina Security Issue after installation....any workarounds?

### ISSUE THREAD

**Issue by dubchild** [inkstitch/inkstitch#677]
Literally every single file in this extension is being caught in the OSX security filters which makes it impossible to use. This appears to be a known issue but I can't find any information on how to fix it. I have approved dozens of files and am beyond frustrated, having wasted several hours already. This issue was reported back in December and has not been addressed thus far. This is very disappointing because this seems like a great project to be a part of. Any workarounds? Thanks.

**Comment by kaalleen** [comment]
We have information for the macOS install on our website: https://inkstitch.org/docs/install/#macos
It is basically the way you download the program files that matters on macOS systems if the files will be trusted or not. We sadly cannot support any better solution for now without investing money into the macOS development environment. Hope you will have success.

**Comment by lexelby** [comment]
Thanks for cleaning up your issue, much appreciated!

I'm sorry, I know this is incredibly frustrating.  It's frustrating for us too, because we have no regular contributors that have a Mac, so we aren't able to make much progress on Mac-specific issues.  I don't know of a workaround either.

If you know how to fix this kind of thing, or if you'd like to do some research / experimentation, that would be incredibly helpful! For now, we're pretty much stuck waiting for someone with the equipment and know-how to fix this.

**Comment by lexelby** [comment]
Oh hey, I didn't realize there was any kind of workaround.  Thanks, @kaalleen!

**Comment by lexelby** [comment]
I'd still be very interested in any info anyone can share about how to do proper code signing for Mac, though.

**Comment by dubchild** [comment]
Thanks for the information. It's very unfortunate that this issue is unlikely to ever be resolved properly. I'd like to help but I don't have much time to devote to something outside of my expertise like this. 

I would be willing to help provide logs and diagnostic info if desired. Unfortunately, I am running into serious issues with Inkscape at every turn, so I'll continue looking for a more stable solution. 

Have you guys tried contacting someone from other Inkscape extension project that might be able to help?

**Comment by dubchild** [comment]
FYI, the video you guys have up on Youtube for installing on OSX is out of date and misleading. It is not helping anyone to have that video still available and recommended when users can't install it that way right now. Having the new info on the website is great, but you should recognize that there is contradictory information elsewhere that is causing undue confusion.

**Comment by lexelby** [comment]
Please understand that we're all doing our best here. :)  This is a free-time/side project for all of us, and as I'm sure you can imagine, given the current pandemic situation, we're all a bit out of sorts.  

I never said this problem won't be solved!  Eventually perhaps one of us will get a Mac or someone who can help will come along.

Anyway, thanks for your input, and please remember: this is a community of volunteers.  Please be kind with your feedback.

**Comment by dubchild** [comment]
Please don't take my comments personally. I apologize for coming across rude but please let me explain a little better from the point of view of a Mac user that was told Inkstitch is a great solution:

The website and video marketing materials got me hyped up, but the installation process really let me down. It's a terrible user experience for Mac users and it's exactly why I won't be using your software.

It's been a known issue with file permissions for like six months. Maybe you guys should try to actively recruit someone that can fix it. There is tons of talent on here! I know you can do it!

**Comment by lexelby** [comment]
I get it, I do!  This is a serious problem and we want it fixed.  But please try to understand our point of view too: this isn't a product, we're not marketing it, and you pay nothing for it.  We're going to do the best we can, and no more.  This is a fun project for us, and we all have day jobs that actually pay the bills.  It will just take some time to fix this, that's all.

**Comment by dubchild** [comment]
I appreciate your point of view. I support a lot of FOSS projects that I use. Currently I can't use Inkstitch and that's the problem. I really WANT to use Inkstitch because it looks awesome. But I can't use it because it doesn't work. File permissions could be fixed if you guys asked another Inkscape project for help. Can you try that, please?

**Comment by lexelby** [comment]
Do you think you might have time to go find someone to help?  If so that would be a huge contribution to our project and I personally would be very appreciative of your work.  Right now I don't have the time available to do that (see also: pandemic).  But it's a great idea and all we need is someone with the time available to do it :)

**Comment by dubchild** [comment]
I would be happy to ask around. I am a designer and web developer by trade. I'm not an extension developer at all but I'm afraid I might have to become one because so many projects I want to use are currently broken on OSX.

**Comment by lexelby** [comment]
Thank you!
