### ISSUE TITLE
Fails to run Inkstitch, Spawn error.

### ISSUE THREAD

**Issue by atrophy** [inkstitch/inkstitch#678]
Running under "Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)", Ubuntu 20.04 "Focal"
Inkscape installed via apt (not snap).

Ink/Stitch installed from "inkstitch-refs-tags-v1.27.2-linux-en_US-ff55eccaa4069d9cbcd2dd74890e3797" (Most recent as of time of writing)

Installation seems to succeed, InkStitch is in the extensions menu however on clicking on any of the menu items a dialog appears momentarily (Too quickly to read or successfully screenshot I'm afraid) and nothing happens with no visible errors.

When running Inkscape from the terminal, I can see the error whenever an Inkstitch menu item is clicked:
> Can't Spawn!!! spawn returns: Failed to execute child process “” (No such file or directory)

I've double and triple checked the directory structure in the extensions folder and all seems good.

**Comment by kaalleen** [comment]
Sorry you are having trouble installing Ink/Stitch. Sadly I have to say, that I have no idea what is going on here. Haven't seen this one before?!?

**Comment by tyrosinase** [comment]
Ooh! I know this one!

Permissions problem on the extensions folder.

**Comment by kaalleen** [comment]
Could you solve your issue?

If not, could you test a newer developer version, just pick one as you like.
Example: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-break-apart-v2

**Comment by kaalleen** [comment]
@tyrosinase changing permissions solved the issue in your case?

**Comment by tyrosinase** [comment]
Not specifically in Inkscape, but it matches the pattern with other apps and plugins..

We have a running joke around our household (I am a dev, husband is a sysadmin): it's *always* a permissions problem in Linux.

**Comment by kaalleen** [comment]
We have a new release, does this issue is still present in v1.28.0?

**Comment by atrophy** [comment]
Confirmed working on Ubuntu 20.04
