### ISSUE TITLE
Ink/Stitch v1.27.2 windows not generating Params preview window

### ISSUE THREAD

**Issue by kitchenwarehelmet** [inkstitch/inkstitch#685]
Hi. I'm absolutely out of my depth here. Installed Ink/Stitch according to the tutorial, tried running the test suggested (circle to path, run params) and am getting the same invalid shape error as others... when I try running it with a rectangle I don't get that error - but in neither do the underfill values self populate as described in the video, and in all occurrences the preview window looks more like command prompt. In some cases this causes Inkscape (0.92.3) to go non-responsive.

I've already tried reinstallation - resulting in the same issue.

![image](https://user-images.githubusercontent.com/64818564/81028113-188ace80-8ebb-11ea-92cd-59868d469e0e.png)

**Comment by kitchenwarehelmet** [comment]
Rebooting and restarting - now I have a preview window, that does not change as I change values in the Autofill and Autofill underlay windows... I do also have this blank inkscape window with a red close button...


![image](https://user-images.githubusercontent.com/64818564/81028558-f2662e00-8ebc-11ea-952b-7341dfca23ba.png)

**Comment by kitchenwarehelmet** [comment]
When I close out of preview and params windows...
![image](https://user-images.githubusercontent.com/64818564/81028614-2e00f800-8ebd-11ea-99e2-889de1d7938d.png)

**Comment by kitchenwarehelmet** [comment]
And on second attempt - back to no preview window.

**Comment by kaalleen** [comment]
Hm, this is clearly a bug in Ink/Stitch. Could you save the file when it's causing the error and post it here? Then we can analyse it and hopefully see what is going on here.

**Comment by kitchenwarehelmet** [comment]
Save the file, you mean the svg of the rectangle? I didn't save it this morning. If it happens again I can.

**Comment by kaalleen** [comment]
That'd be nice, thank you.

Is it possible, that your object was really big and the simulator wasn't finished reloading it? For big fill shapes it needs some time to load and if you stop the operation before it finished loading it shows an error like this. I have seen it just recently. What do you think?
