### ISSUE TITLE
Bean stitch option

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#69]
description of bean stitch: https://www.mrxstitch.com/bean-stitch/

**Comment by wwderw** [comment]
I'm all for it.  I use a bean stitch (aka back stitch (depending on software used)) when needing to do thicker outlines, but can't be thick enough for satin, but thicker then traditional run stitch outlines.

If a bean stitch is possible, would it be possible to do a motif run and/or motif fill?

**Comment by lexelby** [comment]
Anything is possible :) (kinda)

Bean stitch is easy; you just step back to the previous stitch and forward again.  Motif is an entirely different animal and would require some much fancier code.

On the other hand, you can do a motif run with inkscape's "pattern along path" features. There's one such feature that is a live path effect, but you'd have to render that back down to normal paths using "object to path" in order for inkstitch to see it.  There's also a "pattern along path" extension that will produce normal paths that inkstitch can see.

Motif fill would be really complicated for me to code.  I have some ideas, but it would be a major project.  Perhaps use inkscape's pattern fill feature?

**Comment by wwderw** [comment]
That'll work for the motif run (I'm so behind on my Inkscape usage, been an Ai fan for a very loooonnnggg time, know that program much better).

**Comment by X3msnake** [comment]
@wwderw this guy as some neat tutorials on inkscape. https://www.youtube.com/channel/UCEQXp_fcqwPcqrzNtWJ1w9w

**Comment by tatarize** [comment]
I had considered this for pyembroidery, it would be rather trivial to add. Toggle Bean Stitch On, then all the stuff after is bean stitched. But, figured it was out of scope, and you'd be unable to see the bean stitch if it processed it in the backend.

**Comment by lexelby** [comment]
Yup, I agree that it's best for this to be in Ink/Stitch rather than pyembroidery.

Should be an easy feature to add, but I'm currently overloaded.  I'd be happy to review a PR if you're motivated to add bean-stitch functionality.  This'd be a great feature to start out on to get familiar with the codebase :)

I was thinking of adding an integer parameter, defaulting to 1 for normal stitch, 2 for "two stitches forward, one stitch back", and higher numbers to backtrack more times for each stitch.

**Comment by lexelby** [comment]
This was implemented in a recently-released version.
