### ISSUE TITLE
Textured fill

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#692]
![image](https://user-images.githubusercontent.com/63351363/81468692-62d4be00-91e1-11ea-9e3d-17f9f8555196.png)
![image](https://user-images.githubusercontent.com/63351363/81469227-32425380-91e4-11ea-9dfa-b1347634072f.png)
![image](https://user-images.githubusercontent.com/63351363/81469323-ac72d800-91e4-11ea-8ebe-0e8a850dcc50.png)

To do a textured fill : I do a normal fill with "Maximum fill stitch length = 9999999999999".
Then I apply a texture.

To apply the texture : I use "Path> Cut Path" but on a big filling Inkscape V0.92 crash ! Less problem with Inkscape V1.
After cutting the paths you have to join them, I use "Join selected nodes".

I'm looking for another way to do it (in Inkscape or with an extension).
I want nodes on the blue path at each intersection with the green path.

Do you have an idea?

(I can make a video if necessary about my first way.)

**Comment by kaalleen** [comment]
Woah, nice job! I have no better way to offer :(
Would be nice to put a tutorial together for our website. What do you think?

If I remember right, we were planning to implement it for Ink/Stitch through the pattern fill in the color panel. Actually this would be so great to have!

Maybe you are interested to read through a very old issue (#33).

**Comment by kaalleen** [comment]
Also interesting to see for this sort issue are the tutorials of @Augusa : 

http://lyogau.over-blog.com/2019/10/inkstitch-essai-de-point-programmable.html
http://lyogau.over-blog.com/2020/04/point-fourrure-avec-inkstitch.html

It's really interesting what she is up to do with Ink/Stitch. But you probably know it already ;)

**Comment by LaureFR38** [comment]
I know this blog. I learned a lot from it when I discovered Inkstitch. Today I speak almost every day with @Augusa via Facebook ;-)

**Comment by LaureFR38** [comment]
I discovered Inkscape and Inkstitch 2 months ago. So I have a beginner's look, and I find more and more Inkscape tips to facilitate the creation of embroidery. It would be interesting to list them because many people are beginners like me in the use of Inkscape. I increasingly think that Inkscape is a wonderful tool.

**Comment by kaalleen** [comment]
Oh, sounds great!!! I've kinda been waiting for someone to say something like this ;)

If you want to work on the website you are greatly welcome to do so!
Have a look at this pretty incomplete section on the website: https://inkstitch.org/docs/inkscape-tips/
The source for this site can be found here: https://github.com/inkstitch/inkstitch/blob/gh-pages/collections/_docs/en/004-003-inkscape-tips.md

To be able to work on it, it'd be easiest if I made you a member of this repository. Interested?

**Comment by LaureFR38** [comment]
@kaalleen Why not ! 
But I have a few questions:
- Do I only contribute for my language? I speak very bad English, you must have noticed. Optionally, I can ask other people from the French Facebook group to help me translate.
- Will someone check what I write? I'm a beginner, I can be wrong and say mistakes ...

![image](https://user-images.githubusercontent.com/63351363/81508928-69f5ec00-9307-11ea-959a-d10bcfbd95c7.png)


Can I get help with a file? I continue to find solutions for filling with texture. I'm having performance issues with Inkscape. Can you check if you can do this?

If it works for you, you can generate manual stitch embroidery :-)

**Comment by kaalleen** [comment]
No, I can't. My computer is just too slow to do this. And when I prepare a pattern like this I can see it building like a very slow stitch simulation ;) But still, I like the idea. It just shows, that there are possibilities to play around with Inkscape and get good results. If I don't join the points, but set the dashed stroke on your pattern, I get the following result:
![patterned_fill](https://user-images.githubusercontent.com/36401965/81578579-4a180400-93ab-11ea-8294-8e79838d1562.png)

**Comment by lexelby** [comment]
I really want to have pattern fill someday!

Your method is pretty much how I was thinking of having the code do it.  I was thinking of starting with normal fill stitch, perhaps with a slightly wider fill stitch length than normal.  Then overlay the pattern like you did and add extra stitches at the intersection points.

Why add extra stitches?  We could use only the intersection points, but for bigger patterns, that will make stitches that are far too wide.  I'm pretty sure that even if we have the normal staggered fill stitch pattern, if we add stitches at the intersection points with the pattern, the pattern will jump right out and be plainly visible.

@kaalleen This could be as simple as doing a Shapely intersection operation...

**Comment by kaalleen** [comment]
Hm, interesting. I thought about it once and even started to write some code for it - and lost the code later on. Seemed to be too difficult for my coding knowledge. What I had managed to do was to extract the fill pattern from the defs tag and move it to the right place. But I would have needed to create a tiled pattern out of it, before I could search for the intersections ... ... and gave up. Maybe it's time to give it a second chance?!?

**Comment by kaalleen** [comment]
@LaureFR38 
I invited you to become a member of the Ink/Stitch repository.

> Do I only contribute for my language? I speak very bad English, you must have noticed. Optionally, I can ask other people from the French Facebook group to help me translate.

Yes, sure, start with the french site and someone will do the translation later on. At least I can try ;)
I am not the best English speaker myself, but somehow I manage to keep the english version (more or less) up to date. I don't want to know how many mistakes I have made.
Sometimes I "force" my husband to proofread (English is his native language), but I don't always want to bother him with it. He is not really interested into embroidery.

> Will someone check what I write? I'm a beginner, I can be wrong and say mistakes ...

Yes, sure. Don't worry to make mistakes. We are all doing our best and mistakes belong to the process.

Just some notes ... when you update a page on the website, always update the date in the top as well. This helps us to keep track of outdated translations. This actually works only for the english pages, but when I adapt them to your work, I will update the date accordingly.

The source of each page is linked in the page footer (Link: View page source on GitHub). So you can find it easily to make your changes.

When you need help to set up new pages (e.g. for a tutorial) I can help you with that - or upload images as you need them. Don't hesitate to ask whatever you need.

**Comment by kaalleen** [comment]
Fill patterns will be implemented in the next release.
