### ISSUE TITLE
Paramétrage sur sélections multiples

### ISSUE THREAD

**Issue by Marif91** [inkstitch/inkstitch#697]
Bonjour,
Je rencontre une difficulté avec des courbes de Bézier obtenues par interpolation.

J'ai créé deux lignes de Bézier, puis j'en ai créé 8 autres par interpolation. Pas de fond, contour pointillé. Je souhaite appliquer les mêmes paramètres à toutes les courbes c'est-à-dire répéter 2 fois le chemin, la simulation de broderie est bonne. Quand je quitte la simulation, une fenêtre de dialogue vide s'affiche et le logiciel plante. J'ai refait une dizaine de fois la manipulation en relançant Inkscape...

S'agit-il d'un bug de inkstitch (je suis sur mac Mojave) ?

Merci !!!

**Comment by LaureFR38** [comment]
Bonjour Marif91. Connais-tu le groupe Facebook Français Inkstitch ? Nous nous entraidons sur ce groupe, et serions heureux de t'y accueillir : https://www.facebook.com/groups/811488062586111/
Concernant ton problème, je crois qu'il serait intéressant que tu partages ton fichier.

**Comment by LaureFR38** [comment]
J'ai essayé de reproduire ton problème. Ca marche pour moi avec Inkstitch v1.27.2.
I tried to reproduce your problem. It works for me with Inkstitch v1.27.2.

![ezgif-3-ff1e79258096](https://user-images.githubusercontent.com/63351363/81526424-d993c780-9357-11ea-9adb-2e28c3f06521.gif)

**Comment by kaalleen** [comment]
@Marif91 We currently do not support Mojave anymore. You may want to try an older Ink/Stitch version: https://inkstitch.org/fr/docs/install/#macos . Watch out for the Mojave download. This version doesn't support the print output for pdf. You will only receive a blank window if you try it.

Maybe the Ink/Stitch version isn't your problem at all since your simulator was working. But I am afraid, I wouldn't know what caused the crash. I am wanting to try the current version with Mohave on a friends computer, but the viruses out there make it hard for me to do the testings.

**Comment by Marif91** [comment]
Bonjour,

Après de nombreux essais je me suis aperçue que ce n'étaient pas les lignes qui posaient problème. La machine plante **si j'interromps une simulation en cours**, au moment d'enregistrer les paramètres, la machine plante.

Merci

**Comment by Marif91** [comment]
Merci pour votre réponse Kaalleen,

Je vais faire la mise à jour vers Catalina.

Merci !!

**Comment by carolineruaud** [comment]
Bonjour, excusez moi de vous déranger. J'ai fait un dessin a broder, j'ai fait toutes les étapes pour le broder mais au moment de l'enregistrement ça me met une erreur 
![16036316791824292452070707101917](https://user-images.githubusercontent.com/73427348/97108215-5deec280-16cc-11eb-8274-62bc044987ee.jpg)

**Comment by Augusa** [comment]
Personnellement je n’utilise plus cette ancienne méthode d’enregistrement. Je fais enregistrer sous et je choisis le format machine que je veux.


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : carolineruaud<mailto:notifications@github.com>
Envoyé le :dimanche 25 octobre 2020 14:14
À : inkstitch/inkstitch<mailto:inkstitch@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :Re: [inkstitch/inkstitch] Paramétrage sur sélections multiples (#697)


Bonjour, excusez moi de vous déranger. J'ai fait un dessin a broder, j'ai fait toutes les étapes pour le broder mais au moment de l'enregistrement ça me met une erreur
[16036316791824292452070707101917]<https://user-images.githubusercontent.com/73427348/97108215-5deec280-16cc-11eb-8274-62bc044987ee.jpg>

**Comment by carolineruaud** [comment]
Malheureusement quand je fais enregistrer sous il n'y a pas le .pes qui est que dans broder. C'est pour ça que je demande ici.

**Comment by Augusa** [comment]
Il y a le .pes. De toute façon pour le cas bien mystérieux où vous ne l’auriez pas enregistrez en n’importe quoi et convertissez ensuite.


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : carolineruaud<mailto:notifications@github.com>
Envoyé le :dimanche 25 octobre 2020 14:19
À : inkstitch/inkstitch<mailto:inkstitch@noreply.github.com>
Cc : Augusa<mailto:lyogau@hotmail.fr>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [inkstitch/inkstitch] Paramétrage sur sélections multiples (#697)


Malheureusement quand je fais enregistrer sous il n'y a pas le .pes qui est que dans broder. C'est pour ça que je demande ici.

**Comment by carolineruaud** [comment]
Effectivement j'ai trouver pour l'enregistrer en .pes par enregistrer sous. Seulement ça ne veut pas enregistrer 
![Uploading 16036326126496740213504525203847.jpg…]()

**Comment by carolineruaud** [comment]
![Uploading 16036326592401390748930321593959.jpg…]()

**Comment by Augusa** [comment]
C’est que vous avez des corrections à apporter. Je vous conseille si vous pouvez le groupe facebook français Inkscape Inkstitch. Vous aurez plein de doc en français et un tas de gens pour vous aider ! A bientôt


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : carolineruaud<mailto:notifications@github.com>
Envoyé le :dimanche 25 octobre 2020 14:30
À : inkstitch/inkstitch<mailto:inkstitch@noreply.github.com>
Cc : Augusa<mailto:lyogau@hotmail.fr>; Comment<mailto:comment@noreply.github.com>
Objet :Re: [inkstitch/inkstitch] Paramétrage sur sélections multiples (#697)


Effectivement j'ai trouver pour l'enregistrer en .pes par enregistrer sous. Seulement ça ne veut pas enregistrer
