### ISSUE TITLE
localization strings for 1.28.0 missing

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#702]
Hi. Firstly congrats for the new version. A lot of folks will appreciate this :)

The new french strings are missing from the interface. Maybe a little "build" problem ? I do believe that all strings are approved.

Also  LaureFR38 would like to help translating. I told her to create an account and then ask you for the authorizations. Is that the correct way to do it ?

**Comment by lexelby** [comment]
Right now our translation import job is failing and I haven't had a chance to fix it yet.  Hopefully soon, sorry for the lack of French!

I think anyone with a github account can propose translations in crowdin.  Is that not working?

**Comment by danielkschneider** [comment]
Ok I just wanted to make sure that you are aware and also provide some information to your huge french fan club :)

I did not know that anyone with github account can propose translations in crowdin. We will try :)

**Comment by lexelby** [comment]
You're configured as a Proofreader, which means you can accept translations. Theoretically, once you accept them, they get pulled in by the nightly build, once it starts working :)

**Comment by danielkschneider** [comment]
right :) But we will add a second proofreader later since I am less reliable. Some folks do InkStitch every night, that is not my case....

**Comment by lexelby** [comment]
I've just set you as a manager.  Feel free to deputize folks as proofreaders :)

**Comment by danielkschneider** [comment]
Thanks !

**Comment by danielkschneider** [comment]
Hi. An other (small) thing left to fix. "Stroke" is not in the translation. - Daniel 

![inkstitch-stroke2](https://user-images.githubusercontent.com/2872643/82230398-f6b63080-992b-11ea-9e94-88611e26d11c.png)
![inkstitch-stroke](https://user-images.githubusercontent.com/2872643/82230408-f9188a80-992b-11ea-8f92-510c95681a7c.png)

**Comment by kaalleen** [comment]
Thanks. Strokes should now be translatable.

**Comment by danielkschneider** [comment]
thanx to you :)
