### ISSUE TITLE
Support Color File Formats (EDR, INF, COL)

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#703]
Looking at the pyembroidery repository I noticed, that there are color file formats present.
Maybe we also could support them?

Reference: https://github.com/EmbroidePy/pyembroidery/pull/78

**Comment by LaureFR38** [comment]
Will there be .INF? .EXP needs this file to display the correct colors.
Or you talk about other things ?

**Comment by kaalleen** [comment]
Yes, EDR, INF and COL are listed in the reference. Sorry, the link wasn't correct, edited original post to display a better link.

**Comment by JSEHV** [comment]
Any change these changes/improvements can be implemented? 

At the moment I can't load .exp files without the correct .inf file in my embroidery machine.
By Bernina this file also seems to be used to generate the icon/miniature on the display in the files list.

**Comment by kaalleen** [comment]
No sorry. It will take some time to transfer changes from the Embroidepy pyembroidery repository to ours. We would welcome anybody who wants to integrate these formats into Ink/Stitch.
