### ISSUE TITLE
Ink stitch options all greyed out 

### ISSUE THREAD

**Issue by Noobembroider** [inkstitch/inkstitch#712]
Hello! So I'm new to Ink stitch. I downloaded the latest version of Inkscape and Ink stitch and put that in the extensions folder. I know I did it properly because it shows in the extensions menu but the options are all greyed out even after making the simple circle I made into a path as instructed by the tutorial video. I tried searching up if others had the same issues but could not find any. 

![Screenshot_2020-05-19 Upload and share screenshots and images - print screen online Snipboard io](https://user-images.githubusercontent.com/65589184/82294683-25f09000-9974-11ea-8038-a298ceac8884.png)

**Comment by LaureFR38** [comment]
Several people have had the same problem. The anti-virus had quarantined an Inkstitch file.

**Comment by Noobembroider** [comment]
> 
> 
> Several people have had the same problem. The anti-virus had quarantined an Inkstitch file.

I saw those threads but my anti virus never alerted or told me it quarantined anything...

**Comment by magnustron** [comment]
I had the same when copying inkstitch into the extensions folder and keeping it in its own subfolder there. There was actually a warning issued by inkscape on the console when doing this:
```
** (org.inkscape.Inkscape:17209): WARNING **: 21:59:19.026: Failed to find resource file 'inkstitch/bin/inkstitch'. Looked in:
[...]
```
In principle this should be a new feature of the extensions system to keep extensions in their respective subfolders: https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0#Adjusting_folder_structure

**Comment by Noobembroider** [comment]
> 
> 
> I had the same when copying inkstitch into the extensions folder and keeping it in its own subfolder there. There was actually a warning issued by inkscape on the console when doing this:
> 
> ```
> ** (org.inkscape.Inkscape:17209): WARNING **: 21:59:19.026: Failed to find resource file 'inkstitch/bin/inkstitch'. Looked in:
> [...]
> ```
> 
> In principle this should be a new feature of the extensions system to keep extensions in their respective subfolders: https://wiki.inkscape.org/wiki/index.php/Updating_your_Extension_for_1.0#Adjusting_folder_structure

Oh ok! I took all the files out of the subfolder and it worked! Thank you so much! :)
