### ISSUE TITLE
Ignore Path-Objects If D-Attribute Is Empty

### ISSUE THREAD

**Issue by Noobembroider** [inkstitch/inkstitch#720]
This bug has recently got to me. It was fine with a previous file but once started working on a new design this comes up 

path996: error: Object path996 has an empty 'd' attribute.  Please delete this object from your document.

I tried restarting my program and even reinstalling Inkstitch but it is still the same thing.

**Comment by lexelby** [comment]
@kaalleen Like with the one-node path, it seems like it would be useful got Ink/Stitch to be able to ignore some paths if they don't look useful.  Maybe we need to throw an exception, IgnoreObject, and catch it higher up to a cancel converting it to Patch objects...

**Comment by lexelby** [comment]
@Noobembroider Try the Objects panel, that may help you find the invisible inject that the error is referring to.  I think the Objects panel can be accessed from the Objects menu but I can't remember for sure.  Sorry this problem is causing trouble for you!

**Comment by Noobembroider** [comment]
@lexelby Thanks for the reply! But I'm not exactly too sure what I'm supposed to do in the objects panel? I tried going layer by layer and selecting everything to see if there's any specks I'm missing but that's not it. The stitch simulator and params only work if any or all of my objects are selected, but if nothing is selected it's as if it's picking up something from the great beyond that I can't seem to find at all.....I hope this makes sense!

**Comment by Noobembroider** [comment]
Oh another issue I have is that sometimes after reopening a file, sometimes there's random breaks in my paths that I know I did not put so I have to look for it either by eyeing for them in my custom satin column stitches or if it's a filled area, select it and click union again.

**Comment by lexelby** [comment]
You're looking for an object named path996.  It may be that you can only find it in the XML view.  It's like a little invisible poison pill, not shown or selectable but able to trip Ink/Stitch up something awful.

If all else fails, select everything, copy, and paste into a new SVG.

**Comment by Noobembroider** [comment]
Ahhhhh it worked! This was definitely frustrating to figure out haha. Thank you so much for all the hard work ya'll do for this amazing extension!!!

**Comment by kaalleen** [comment]
I am reopening this, because we should handle these objects better (as proposed by @lexelby)
