### ISSUE TITLE
Feature request : Textured fill (intersection with a pattern)

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#724]
(Click on images to enlarge)

See the method I use to make a textured fill :
![2020-05-29 13_46_33-intersection svg - Inkscape](https://user-images.githubusercontent.com/63351363/83256961-b8cecd00-a1b3-11ea-9849-7320b561810e.png)

The problem is that it is not optimized, the computer becomes very slow.
See the method I would like to use:
![2020-05-29 13_48_07-intersection svg - Inkscape](https://user-images.githubusercontent.com/63351363/83257108-f895b480-a1b3-11ea-9dd2-30ebee646a5b.png)

Is it possible to create a new function using the Inkscape code (src / path / path-boolop.cpp - bool_op_slice) ? Instead of cutting the path into several sub-paths, you just have to add nodes to the path. 
There may not be a lot of changes to make in the source code, can it be fast?
What do you think ? 

Also to use this new functionality, it would be interesting to be able to put 0 instead of 999999 for the stitch length. And it could be interesting in other use cases.

I hope you will like my proposal.

**Comment by lexelby** [comment]
Definitely possible, and I think Ink/Stitch will be able do it much faster than Inkscape.  I don't know when we'll have a chance to do this but we definitely want to :)

**Comment by LaureFR38** [comment]
I know you've been thinking about it for a long time. 
But based on the "CutPath" function of Inkscape (which I think has been improved since v1 because it goes much faster) I thought that there were perhaps only a few lines to modify without thinking too much. Improvement may always be possible later. But it may be more complicated than I think.

**Comment by lexelby** [comment]
I'm afraid it's not that simple. :(  Inkscspe is written in C++ but Ink/Stitch is written in Python.

Also I'm spending almost all of my free time sewing face masks for those in need so I haven't had any time to work on Ink/Stitch.

Enjoy your coffee ;)

**Comment by LaureFR38** [comment]
You don't have to justify yourself. It's already great what you have done and we can never thank you enough!

In this case maybe I can go to Inkscape github and ask if there isn't an extension that can do that.
