### ISSUE TITLE
UnicodeDecodeError in input.py

### ISSUE THREAD

**Issue by tonilatenz** [inkstitch/inkstitch#725]
I installed inkscape/inkstitch on a new laptop, inkscape works - open some files too, but import a stitchfile doesn't run... I got the following error:

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 14: invalid start byte

Thanks for some helping tips.

BR
Tanja

**Comment by kaalleen** [comment]
Thought this was fixed a while ago?!? ... but do you have a file name with special chars which you wanted to import?

**Comment by tonilatenz** [comment]
sorry, no. Its a file, I imported often at my old Laptops Inkscape. 
Its a Letter to create a name, for exsample:
"SK-15-700 lower a"

**Comment by tonilatenz** [comment]
sorry, no. Its a file, I imported often at my old Laptops Inkscape. 
Its a Letter to create a name, for exsample:
"SK-15-700 lower a"

**Comment by tonilatenz** [comment]
maybe is it possible, the version inkscape 1.0 isn't compatible with inkstitch?
Could anybody help me please? 
thanks so much..

**Comment by tonilatenz** [comment]
further in can't open all of my jef.-files - only few files, I'd bought, got opened...
Many letter-files are impossible (there were bought) and all of my own builded/created jef.-files doesn't be open.

**Comment by kaalleen** [comment]
This is a bug and needs to be fixed, but it might take a little while until we get to it.
Could you try if it opens when you remove spaces from the filename?

**Comment by tonilatenz** [comment]
I'd tried it, but the file doesn't get open. For example, I try the file "bear.jef", too- its the same mistake..
May its a problem with the new inkscape 1.0?
I create all of my files on the 0.92.
Thank you so much, Kaalleen.

**Comment by kaalleen** [comment]
My guess would be, that your filenames are not utf-8 encoded. The next python version (to which we want to update as soon as possible) will have not as many encoding errors as we are facing right now.

Out of curiosity... Does opening the files works with Ink/Stitch 1.27.2 (https://github.com/inkstitch/inkstitch/releases/tag/v1.27.2)?

**Comment by tonilatenz** [comment]
Error-Code with Ink/Stitch 1.27.2:
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 14: invalid start byte

Doesn't work, too.

Now I'd tried the inkscape 0.92.5 with ink/stitch 1.28.0:
Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 14: invalid start byte

and inkscape 0.92.5 with ink/stitch 1.27.2:

Traceback (most recent call last):

  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>

  File "d:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect

  File "C:\hostedtoolcache\windows\Python\2.7.17\x86\lib\encodings\utf_8.py", line 16, in decode

UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 14: invalid start byte

Is there another posibility?

**Comment by LaureFR38** [comment]
@tonilatenz 
The coding problem also concerns the directories. 
Does the file directory contain the letter "ü", or the parent directories? 
Look at the full path to your file, the problem should be around the 14th character.

I have Inkscape 1.0 and Inkstitch 1.27.2. I have the same error if I put a "à" on my file or my directory. Except that the "byte" for me is "0xe0" which corresponds to "à".

@kaalleen 
It's the same problem as here: https://github.com/inkstitch/inkstitch/issues/691

**Comment by tonilatenz** [comment]
Thank you so much - that's it!
I had an "Ü" in the path - now it works at the 0.92.5 / 1.27.2.
At next, I would try the 1.0 Inkscape...
Thank you all for your help and have a nice weekend.

**Comment by kaalleen** [comment]
This error is hopefully fixed in the next version to come.
Please reopen if this is not the case.
