### ISSUE TITLE
Cant use Inkstitch on Ubuntu 20.04

### ISSUE THREAD

**Issue by jasenator** [inkstitch/inkstitch#733]
Inkscape has been installed successfully, I have added the extracted folder to the extension folder for the Inkscape application, however, all systems are grayed out.

in your troubleshoot, it says that an incorrect version may have been installed. however, your information does not indicate which version of Linux it is to be installed on.

I am running Ubuntu 20.04 and I need this to work on this program, please I need a fix for this problem thank you

senator

**Comment by kaalleen** [comment]
It doesn't matter which linux version you have installed. We do not support 32bit though.
On our website you'll find links to the versions for the various operating systems: https://inkstitch.org/docs/install/#1-download

**Comment by tyrosinase** [comment]
Check your ownership/permissions; could be the user Inkscape is running under doesn't have access to the extension.

**Comment by Qbalonka** [comment]
Hi,

I just discovered this project an hour ago and I really want to try it, but I can't get it to work. I seem to have a similar problem as jasenator. The options in Inkstitch extension menu are grayed out for some reason.
I am using the newest stable version of Inkscape on Arch. Other extensions work as intended.
I am not able to figure out what may be the reason of this issue. Could somebody please look into it? Thank you.

**Comment by jasenator** [comment]
I would like to use this on ubuntu as this system has the capacity to do so, I have loaded it on a laptop that uses windows 10 and it works as intended but I would prefer it on my Ubuntu system. It is grayed out so I am unable to use this software

**Comment by jasenator** [comment]
Sorry to answer the question about the user and the latest update, I am using both the latest Inkscape and Inkstitch all are correct. and I am the admin for the system. 

Thanks

**Comment by tyrosinase** [comment]
You're not running as root though, right? 😧

My Inkstitch directory (`/home/silver/.config/inkscape/extensions/inkstitch`, for example, has permissions `drwxr-xr-x 8 silver silver`

**Comment by guenterjonsson** [comment]
I have installed latest versions of Inkscape and Inkstitch. It is a 64bit system. Extensions can be chosen but inkstitch shows fractions of a second a window but doesn't work out. After changing permissions on the inkscape folder recursive (chmod -R 777 inkscape/) still no result. 
Thanks for any help.

**Comment by kaalleen** [comment]
Do you have Ink/Stitch in a subfolder by any chance? Inkscape 1.0 allows to have extensions in subfolders. Ink/Stitch instead still relies on the old Inkscape version where this wasn't possible. We haven't updated yet.

**Comment by lexelby** [comment]
@kaalleen Folks can't just put Ink/Stitch in a subfolder on Inkscape 1.0, unfortunately.  We'll have to change the INX files to work with that.

**Comment by LochanLoch** [comment]
I installed again Inkscape 1.01 out of buster-backports and found in system the filesystem.
After I copyed **all** extracted files from 1.28.0 InkStitch **zip** file in the path: /home/**USERNAME**/.config/inkscape/extensions 
inkstitch worked for me.
But my system is a Debian ;-)

**Comment by rivens623** [comment]
I updated to the latest stable release of Ubuntu, Inkscape, and InkStitch, and when selecting the Embroider option and no matter which way/setting is selected, the processing window appears and disappears suddenly. (Can't tell if there is an error message or not it is so quick).  Also after choosing the Embroider option, I go to 'Save As' and choose both a VP3 file type or ZIP, with all options selected, and Inkscape says that the file could not be saved. I also went through all the troubleshooting options within Ink/Stitch, and no results.

**Comment by kaalleen** [comment]
Could anyone having the "suddenly disappears" issue try to run Inkscape through following command?

`export GDK_BACKEND=x11 && inkscape`

I would like it to be approved before I write it up as a option on our faq page. This will only be a temporary solution until we transtitioned fully to the electron interface.

**Comment by kaalleen** [comment]
This issue has been documented on our website. Unsure if it is still an issue.
