### ISSUE TITLE
G-code : Z : alternate value doesn't work

### ISSUE THREAD

**Issue by JustGand** [inkstitch/inkstitch#741]
Whether i select "Alternate Z value" or "Z travel per stitch" the output is the same : the Z value increases for each stitch.

<img width="324" alt="Capture d’écran 2020-06-13 à 16 31 23" src="https://user-images.githubusercontent.com/46919259/84571457-81efde00-ad93-11ea-8e0a-c62356bfb80a.png">

Result :
```
(STITCH_COUNT:2139)
(EXTENTS_LEFT:-47.024)
(EXTENTS_TOP:-25.528)
(EXTENTS_RIGHT:47.024)
(EXTENTS_BOTTOM:25.528)
(EXTENTS_WIDTH:94.048)
(EXTENTS_HEIGHT:51.057)

G90 (use absolute coordinates)
G21 (coordinates will be specified in millimeters)
G0 X0.0 Y0.0

G0 X-30.837 Y-14.902
G0 Z2.0
G0 X-30.642 Y-15.626
G0 Z4.0
G0 X-30.446 Y-16.350
G0 Z6.0
G0 X-30.642 Y-15.626
G0 Z8.0
G0 X-30.837 Y-14.902
G0 Z10.0
G0 X-30.313 Y-16.843
G0 Z12.0
G0 X-30.442 Y-14.837
G0 Z14.0
G0 X-30.054 Y-16.791
G0 Z16.0
G0 X-29.813 Y-14.788
G0 Z18.0
```

I'm using the latest release v1.28.0

**Comment by LochanLoch** [comment]
Save As InkStitch G-Code gave me same output and I thought the Z value is the secure layer for grinding.

**Comment by kaalleen** [comment]
Pyembroidery has been updated. It should be working with the upcoming release.
I am going to close this issue now. Please reopen if problem still exists.
