### ISSUE TITLE
Stitch preview is OK but DST JEF and other too looks bad in exported file.

### ISSUE THREAD

**Issue by LochanLoch** [inkstitch/inkstitch#744]
First - I love InkStitch - Inkscape and so on. You guys did a great job.
Second I am not a natural English writer so it could sometimes a bit funny ;-)

In my holidays I bought before a Janome MC 500 E and was trying to get my own ideas in work.

One was a Testfile to check the Janome itself her accuracy on paper.

The other was my name in a self made font ...

There my fun start.
Building it in Inkscape worked easy making with inkstitch the E-Satin looks fine.

But in the real world it looks funny ... checking out the jef or dst files made from inkscape show a bad accuracy in the file. I do it in the special named layer.

Than I checked out a pice of a  [Schmetterling](https://garne.madeira.de/downloads/stickdateien/) import is fine and testing too - but exporting it made a jef file with other nodal points. Not so bad as my E-Satin Stitch but notable other. I don't use a scale on a layer.

Please check it out if its only the both export formats or a general export problem from inkstitch.

AH ... here too not supported file type. 
[testsegmente.svg.txt](https://github.com/inkstitch/inkstitch/files/4794291/testsegmente.svg.txt)
[A-965619_Schmetterling_Ausschnitt.svg.txt](https://github.com/inkstitch/inkstitch/files/4794297/A-965619_Schmetterling_Ausschnitt.svg.txt)
So I made a .txt at the end ... download and rename and it should work.
![ausschnitt](https://user-images.githubusercontent.com/66974900/84934346-796f0e80-b0d7-11ea-944a-1e2cbebd3f72.png)

What is the **testfile** you guys use to check the compatibility with ink stitch?
I can share my Paper Test :-) if you guys interested - it based on old plotter test DIN32866 I don't have only an old Hoischen.
[Testgrafik.zip](https://github.com/inkstitch/inkstitch/files/4794355/Testgrafik.zip)

happy with the new hobby but hope I must not go back to winblond.

**Comment by LochanLoch** [comment]
In that File I tested the Versions I had in my download.
If you will watch rename to .svg 
[testsegmente.svg.txt](https://github.com/inkstitch/inkstitch/files/4801126/testsegmente.svg.txt)

**Comment by lexelby** [comment]
Thank you!  Those SVG files will really help.  One of us will take a look when we have a chance.

My previous machine was a Janome 400e, and it was really nice.  You chose well :)

**Comment by LochanLoch** [comment]
No chance just now ;-) got a nice and helpfully explanation from @tatarize and will try to live with that limitation of Ink Stitch.
