### ISSUE TITLE
Ink Stich runs and closes too quickly to see the error message 

### ISSUE THREAD

**Issue by chrischrisjnr** [inkstitch/inkstitch#748]
Nothing more to add about the error as it is as the title suggests

**Software**
Running on Ubuntu: 20.04 LTS
Inkscape: 1.0 (6e3e5246a0, 2020-05-07)
Ink Stitch: Latest version

**Hardware**
Macbook air 2011
2 GB Ram
250 GB SSD
i5 Intel

All I made was a circle as per the installation video and nothing worked. I also tried a few lines and got the same error

**Comment by igoiko** [comment]
Hi,
I have had the same problem with almost the same configuration.
My problem was that a some point apparmor does not allow the execution of the addon. Looking at syslog i found the lines about apparmor rules denied the execution of inkstich.
As i didnt want to deal with apparmor rules and snap i ended by download the sources of inkscape and compile it in my pc, remove the snap package and now works well.

**Software**
Ubuntu 20.04 LTS 
Inkscape 1.0 (snap)  
InkStich: 1.28_en_US (~/.config/inkscape/extensions/)

**Comment by chrischrisjnr** [comment]
Hi,
Great work on finding a solution. What you did to resolve the issue is beyond my skill set but I hope the devs see your comments and are able to rectify the issue for other users.
