### ISSUE TITLE
Auto-route satin columns breaks column without rungs

### ISSUE THREAD

**Issue by matthijskooijman** [inkstitch/inkstitch#755]
I have a satin column without rungs (just two straight lines with 2 nodes each). When I autoroute this, in a particular combination with another satin column and have "Preserve order of satin columns" checked, this produces a new column with an unequal number of nodes, and no rungs added.

Problem is shown below. Left is the original, right after applying autoroute with "Preserve order of satin columns" set. The vertical satin is on top, the diagonal and problematic one is on the bottom.

![image](https://user-images.githubusercontent.com/194491/85989132-6837d300-b9f0-11ea-900b-5fa145e1f701.png)

Removing the extra node (the one above and left of the one pointed at by the troubleshooting arrow) fixes the pattern and makes it simulate as I would expect it to.

Here's the problematic SVG file (gzipped to make github allow it):

[autoroute bug.svg.gz](https://github.com/inkstitch/inkstitch/files/4844544/autoroute.bug.svg.gz)

This was tested with version 1.28.

**Comment by matthijskooijman** [comment]
Adding a single rung to the diagonal column prevents this problem from occurring.

**Comment by lexelby** [comment]
Oops, it's supposed to handle this fine and add rungs to the resulting satins.  Thanks for the report!

**Comment by kaalleen** [comment]
Tested wwith latest development branch. It's working fine there.
