### ISSUE TITLE
Auto-route satin columns puts running stitch over satin stitch

### ISSUE THREAD

**Issue by matthijskooijman** [inkstitch/inkstitch#757]
With a particular combination of satin columns, and applying auto-route with "Preserve order of satin columns" set, I see a weird routing where the vertical column of the "P" is split into two columns (to facilitate a jump to the next column to the right, I think), but then a small running stitch is added from the split to the top of the column that starts below the split. This ends up with some extra stitches on top of the lower split, which looks wrong.

![image](https://user-images.githubusercontent.com/194491/85995130-3cbbe500-b9fe-11ea-856e-4e9fe1096583.png)

![Peek 2020-06-29 11-37](https://user-images.githubusercontent.com/194491/86019907-840a9b80-ba27-11ea-8dc0-098f424287d9.gif)

It seems that reversing the path direction of the vertical satin column prevents the problem from occuring.

Here's the SVG showing the problem:

[autoroute-bug.svg.gz](https://github.com/inkstitch/inkstitch/files/4844871/autoroute-bug.svg.gz)

**Comment by lexelby** [comment]
Your issue reports are really helpful, thank you!

I'm not going to be able to test this one out until I have some time to sit in front of my computer, so please don't be alarmed if it takes days (or weeks, thanks COVID-19).

**Comment by matthijskooijman** [comment]
No hurry, I just ran into this and know how helpful a detailed and reproducible bug report is, so I spent some time minimizing the example. I also am very familiar with not getting around to all those things on your list all the time, there's just too much of life :-p

Hm, I also just noticed that even though I had uploaded more details, GH seems to have lost them somewhere. I'll re-add them in a minute :-)

**Comment by kaalleen** [comment]
Problem doesn't seem to persist anymore. Please open a new issue if this ever happens again!

![auto-route result](https://github.com/inkstitch/inkstitch/assets/36401965/cf8ccf6c-d30d-4fc7-93a4-0098921e7a09)
