### ISSUE TITLE
Should satin spacing be applied at thread angle?

### ISSUE THREAD

**Issue by matthijskooijman** [inkstitch/inkstitch#759]
When making a satin stich, you specify the zigzag spacing, which is the space between needleholes on both rails of the satin column (though I recall reading somewhere it is really measured on the center of the column, rather than the rails, but that's not so relevant here I think).

This means that the spacing is measured along the axis of the rail. However, stiches are not necessarily perpendicular to the rail, they might actually be angled. I tried this with a letter "N" today, where I made the stitches on the diagonal part of the letter vertical rather than perpendicular to the line of the N itself. The end result was much too dense bit of stitching.

The reason for this, I think, is that stitch density is determined by the space between stitches, on the axis perpendicular to the sitches themselves. As an illustration. contain two satin columns, one of which is plain and straight, and the other has the rails shifted so the stitches and up at an angle:

![image](https://user-images.githubusercontent.com/194491/86012868-c9769b00-ba1e-11ea-97de-970a395fdbd0.png)

The spacing between threads in the middle of the satin stitch is about half of the rail spacing in the straight case:

![image](https://user-images.githubusercontent.com/194491/86013940-02633f80-ba20-11ea-927b-d00333426402.png)

In the angled case, it's a bit more tricky to measure exactly in the middle, but the spacing is a obviously a lot less:

![image](https://user-images.githubusercontent.com/194491/86014133-3b031900-ba20-11ea-85a4-bd956ebd19c6.png)

Angle is 24°, so the spacing along the stitch axis is `rail_spacing * sin(24°)`. Reversing that, if I want 0.4mm stitch spacing, I get `rail_spacing = 0.4 / sin(24°) = 0.4 / 0.407 = 0.98`. Manually changing the spacing of the left column to 0.98mm gives the spacing you would probably want to see:

![image](https://user-images.githubusercontent.com/194491/86014170-45bdae00-ba20-11ea-99a5-fe146f62c029.png)

Which is indeed about 0.2mm in the middle of the stich: 
![image](https://user-images.githubusercontent.com/194491/86014282-6980f400-ba20-11ea-9646-600ab5aebbfe.png)

Would this be a correction to be applied in the satin stitch automatically? 

Note that for the common perpendicular case, the angle is 90°, and sin(90°) is 1, so the original value would be used.

**Comment by lexelby** [comment]
Great question, and your analysis is spot on.  It's exactly as you say.  For your angled case, if you measure distance along the center-line of the satin, it will be approximately the spacing you chose.

We've gone back and forth on this.  What you're seeing now is based on a brand new satin algorithm as of a few months back.  The previous algorithm would try to measure the spacing based on the distance between needle penetrations on each rail.  Since that will differ between the two rails when going around a curve, it would choose one of the rails and the other one would become too dense.

The problem came when you had a funnel or "V" shape.  The distance traveled along the rails would be as you specified, but the actual threads would be much closer together.  In effect, density would arbitrarily vary based on whether your rails were parallel or not.

The new algorithm tries to compensate for that, but you've provided a really awesome example of how it can fail.  Thank you, I hadn't thought of that!

I'm not really sure what to do.  Maybe the algorithm should consider the angle that the stitches cross the center-line and do some trig to come up with a compensation factor?  I'd love to hear your input.

**Comment by matthijskooijman** [comment]
> Maybe the algorithm should consider the angle that the thread crosses the center-line and do some trig to come up with a compensation factor? I'd love to hear your input.

Yeah, something like that would make sense to me. You probably need to look at the average angle of at least two threads, though (i.e. each alternating thread has a different angle), maybe more (and/or maybe keep a running total of spacing or something, since the spacing on an individual stitch is not so important, it's the collective spacing that counts, I guess).

I haven't looked at the algorithm itself, so I can't really comment more in-depth (also, I've only done a little embroidery and just finished my first simple pattern made with inkstitch, so I can't really fall back on any significant domain experience :-p).

**Comment by lexelby** [comment]
Good ideas, thanks!  If you do have any interest in looking at the code, this part is in the SatinColumn class defined in lib/elements/satin_column.py.  The guts of it are in a function named plot_points_on_rails or something like that. I'm happy to answer any questions you might have about how it works.

As to looking at the angles of pairs of threads, fortunately that isn't necessary.  The zig-zags of a satin aren't shaped like `\/\/\/\/`, they're more like `|\|\|\|\`.  It figures out the `|` parts and then just connects them together with the `\` parts.

**Comment by matthijskooijman** [comment]
> As to looking at the angles of pairs of threads, fortunately that isn't necessary. The zig-zags of a satin aren't shaped like \/\/\/\/, they're more like |\|\|\|\. It figures out the | parts and then just connects them together with the \ parts.

Ah, that probably makes it easier (though I wonder: Doesn't that mean that by default, the average angle is just short of 90°? OTOH, the absolute value of the stitch density is probably not too relevant here, it's mostly important to adjust for relative changes due to changing angles.

**Comment by lexelby** [comment]
Not sure I understand your question.  The angle between the thread and the center line depends on how your rungs are angled.  Usually people tend to make it around 90 degrees but not always.

Now that I've thought about this some # more, I realized that I've run into this density issue you've described here before, and I didn't have a good explanation for it.  Thank you again :)

**Comment by matthijskooijman** [comment]
I mean that with `\/\/\/\/`, the average angle between to adjacent stitches is 90°. With with`|\|\|\|\`, the average angle is actually slightly less than 90°. IOW, if you would do both of these, with the same needle-to-needle spacing, the latter would result in slightly more dense stitching.

Another way to explain this is that with the former, (I think) you use slightly less thread than with the latter, so the stitching is more dense (I haven't done the math to prove this, but I expect it will turn out to be a factor of sin(avg angle) more). This could actually also be a way to compensate for these angles (and maybe merge in the existing correction for stitch width?): Sum stitch lengths and compare them with distance (or surface) between the rails to see if the density is correct? I haven't really thought this through, though.

**Comment by LochanLoch** [comment]
OK I made the svg [Satin24Grad.svg.txt](https://github.com/inkstitch/inkstitch/files/4865807/Satin24Grad.svg.txt) and can't resist to show mine problem [#744](https://github.com/inkstitch/inkstitch/issues/744) too in same svg :-) - please download and delete .txt at the end of the file - happy measuring.

**Comment by lexelby** [comment]
I believe version 3.0.0 solves this, yay!
