### ISSUE TITLE
Pdf function not saving or printing

### ISSUE THREAD

**Issue by stitchfit** [inkstitch/inkstitch#766]
Hello, 
I was wondering if there was a solution for this particular problem. I'm able use most parts of the Inkstitch extension in Inkscape. Params works, and I can save and convert the file to an embroidery file for my machine. Also, using the "save as" function in Inkscape, I'm able to save a basic image of my file as a pdf. However, my problem is that the "save as" and "print" buttons in the Inkstitch "print/pdf" function haven't worked since I updated Inkscape. Both buttons turn green when I hover over them, but they do nothing when I click on then. I don't get an error message and no matter how long I wait, nothing pops up. I liked being able to get the stitch layout and realistic renders for my embroidery. I hope there is a fix. Sorry, I'm new to this.

**Comment by hbrown66062** [comment]
I have the same issue. Inkstitch runs fine but won't let me save my work in any embroidery machine format. Here is the dialogue (typed) from the error messages:


**Message One (occurs when attempting to save as any Embroidery machine format - PES, PEC, etc.):**  Traceback (most recent call last): 
File "inkstitch.py", line 52, in <module>
 stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 8: invalid start byte

**Message Two (occurs after hitting OK on dialogue one):**  File C: \Users\myname\OneDrive\Document\Paths\Circle Test.pes could not be saved.

**Comment by schweigel** [comment]
> Hello,
> I was wondering if there was a solution for this particular problem. I'm able use most parts of the Inkstitch extension in Inkscape. Params works, and I can save and convert the file to an embroidery file for my machine. Also, using the "save as" function in Inkscape, I'm able to save a basic image of my file as a pdf. However, my problem is that the "save as" and "print" buttons in the Inkstitch "print/pdf" function haven't worked since I updated Inkscape. Both buttons turn green when I hover over them, but they do nothing when I click on then. I don't get an error message and no matter how long I wait, nothing pops up. I liked being able to get the stitch layout and realistic renders for my embroidery. I hope there is a fix. Sorry, I'm new to this.

same problem here
