### ISSUE TITLE
Split satins

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#77]
An option for satin columns to split the column into several side-by-side columns.  Inkstitch would just divide each normal satin stitch into X equal stitches.

**Comment by kaalleen** [comment]
Closing this in favor of #77

**Comment by lexelby** [comment]
This is #77!

**Comment by lexelby** [comment]
That said, this is done, so we can keep it closed :)

**Comment by kaalleen** [comment]
Oh, sorry. Did too much of this ;)
I meant in favor of #513
