### ISSUE TITLE
AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'"

### ISSUE THREAD

**Issue by alanbaltic** [inkstitch/inkstitch#770]
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x246AEF30>> ignored

No idea what this means or why I get it.

**Comment by kaalleen** [comment]
See #770
