### ISSUE TITLE
Error when trying to save as a pes

### ISSUE THREAD

**Issue by holanuni** [inkstitch/inkstitch#773]
When I try to save it it says that the files is read
 only file system does anyone know how to save it

**Comment by gilfeig** [comment]
@holanuni same issue. did you figure this one out?

**Comment by ecc521** [comment]
This issue is not specific to pes files. Can this bug report be renamed to something along the lines of "Unable to write ./filename.xxx: Read only filesystem" to make it easier to find?

**Comment by kaalleen** [comment]
This should not happen when you save through File > Save a copy ... (the only way to save files in Ink/Stitch v2.0.0).
Therefore I am closing this issue. Please reopen, if you are still having trouble with saving your files.
