### ISSUE TITLE
Create SVG objects from stitch results

### ISSUE THREAD

**Issue by Jahfry** [inkstitch/inkstitch#776]
This is going to be an odd request, and way outside the scope of the extensions. But I figure I'll toss it in here as something to keep in mind. Or ... if this is already possible and I missed it in the tutorials just let me know. 

I found Inkstitch while looking for a way to create graphic designs that -look- like embroidered patterns. Inkstitch does everything (and more) that I'd need except for 1 thing. It doesn't actually generate paths from the stitches. 

I do realize that's not the intent. But it would be a really interesting thing for us graphics types. 

What I'd look for is the ability to take the vector results from a stitched pattern and export them back to Inkscape as full vector paths. I can simulate a border stitch pretty well using Inkscape's "Generate from Path" extension. But nothing as precise as what you're generating for stitch simulations. 

I haven't had any luck getting the PDF print option working but my guess is, if "realistic" isn't checks, that you are already generating full vectors for the PDF so it might be the data I'm looking for is already there. 

I don't know if the "realistic" version is a bitmap or vector export but being able to export "realistic" as an option to Inkscape but I'm assuming that's not feasible. Just the not-realistic view would be fine.

**Comment by kaalleen** [comment]
Closing. Import realistic view would be possible, but slows down Inkscape too much, so I rather not set it as an option (don't want to risk people loose their designs because of that). Generating the normal stitch output has been an extension now for long.
