### ISSUE TITLE
Params menu won't open

### ISSUE THREAD

**Issue by abbiee0** [inkstitch/inkstitch#779]
Hi - Whenever try to select params, it says 'params working, please wait' for a few seconds, and then disappears and nothing else happens.
I am on windows and have tried redownloading ink/stitch four or five times. 
<img width="810" alt="Before" src="https://user-images.githubusercontent.com/69094597/89112474-f819d400-d417-11ea-882d-ba505600e6da.PNG">
<img width="807" alt="After" src="https://user-images.githubusercontent.com/69094597/89112476-fcde8800-d417-11ea-87dd-efade2eaebfd.PNG">

**Comment by Rhona7125** [comment]
I am having exactly the same issue and, like you, have re-downloaded both inkscape and inkstith and still getting the same problem !!

**Comment by kaalleen** [comment]
@bcarr1512 Could you run the command `ps ax | grep mutter` and paste the result here?

**Comment by bcarr1512** [comment]
Kaaleen--here's the results:

before starting inkscape

$ ps ax | grep mutter
   3648 ?        Sl     0:00 /usr/bin/Xwayland :0 -rootless -noreset
-accessx -core -auth /run/user/1000/.mutter-Xwaylandauth.BOFHR0 -listen 4
-listen 5 -displayfd 6 -listen 7
   4484 pts/0    S+     0:00 grep --color=auto mutter
$

-Brian

**Comment by kaalleen** [comment]
Ok, I see. Thank you.
Could you open Inkscape like this and see if the params dialogue works?

`export GDK_BACKEND=x11 && inkscape
`

**Comment by lexelby** [comment]
@kaalleen are you thinking this is a wxpython issue?  Maybe the solution is that we need to migrate to electron fully to support Wayland. :)

I've got a branch with some good progress toward moving Params to electron.

**Comment by kaalleen** [comment]
> @kaalleen are you thinking this is a wxpython issue?

Yes

> Maybe the solution is that we need to migrate to electron fully to support Wayland. :)

Yes ;)

Exactly what I thought. Until then, this solution should work.

**Comment by bcarr1512** [comment]
Morning!

Had the opportunity to give it a try--running v1.29.1 en_US:

$ export GDK_BACKEND=x11 && inkscape

** (org.inkscape.Inkscape:11925): WARNING **: 10:57:55.605: Parameter
'feed_rate' in extension 'org.inkstitch.output.txt.en_US' is visible but
does not have a 'gui-text'.
Unable to find: org.inkstitch.simulate.en_US.noprefs

** (org.inkscape.Inkscape:11925): WARNING **: 10:57:56.353: Unknown verb
name: org.inkstitch.simulate.en_US.noprefs
Unable to find: org.inkstitch.simulate.en_US.noprefs

** (org.inkscape.Inkscape:11925): WARNING **: 10:57:56.353: Unknown verb
name: org.inkstitch.simulate.en_US.noprefs
/tmp/ink_ext_XXXXXX.svg4P5IS0:1: parser error : Start tag expected, '<' not
found

But Params did run after I waited a bit and showed the simulation and the
window came up.  I was also able to run the simulation and create a vp3
file.  The .vp3 file work just fine in my machine.

-Brian

**Comment by Kbex1** [comment]
> Ok, I see. Thank you.
> Could you open Inkscape like this and see if the params dialogue works?
> 
> `export GDK_BACKEND=x11 && inkscape `

i can confirm that this helped me to open param menu, on inkscape 1.0.1  and ink/stitch 1.29.1 
(only to get stuck with the different problem :sweat_smile:  but i need to search first if this is a bug or not)
