### ISSUE TITLE
MacOS 10.15 extension errors

### ISSUE THREAD

**Issue by karattopp** [inkstitch/inkstitch#780]
Can you please tell me where I can find the missing pieces? Inscape won't start up after installing the Inkstitch extension because of missing dependencies

Extension "LaTeX (pdflatex)" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: pdflatex

Extension "XFIG Input" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: fig2dev

Extension "GIMP XCF" failed to load because a dependency was not met.
Dependency:
        type: executable
        location: path
        string: gimp

**Comment by kaalleen** [comment]
Sorry, for the late answer. I must have missed your issue. It is possible, that the last version had issues with a missing library. There is now a new version out there. Here are download and install instructions: https://inkstitch.org/docs/install-macos/
Please open a new issue if you are having issues with the new version as well.
