### ISSUE TITLE
The "Params" option doesn't works

### ISSUE THREAD

**Issue by adriano-dsj** [inkstitch/inkstitch#781]
I followed the steps of the tutorial on YouTube, but after converting to a path and accessing the "Inkstitch" extension, the "Parameters" option remains blocked. What should I do?

*** I'm a Linux (LMDE4) user ***

![prt_params](https://user-images.githubusercontent.com/51766024/89693143-036f7280-d8e4-11ea-9572-06be9481aadb.png)

**Comment by LochanLoch** [comment]
I think its not your failing - I made same easy circle - first had a line outside the second I made only fill - the first circle failed had 6knots. ;-( second circle was than valid with 6 knots too ... looks like we must work very clean with inkscape 1. Second circle was made only with **fill**. O I use the [lexelby fix save and print PDF buttons](https://github.com/inkstitch/inkstitch/tree/lexelby/fix-save-print-pdf) code. Its a bit slow but work ...

**Comment by kaalleen** [comment]
@LochanLoch Circles caused a lot of issues for some reason. We created an extension which can be found within the fill tools (break apart). This extension should be able to fix not working circles (and all kind of not working fill elements). An other way to figure out why a certain shape gives you an error is the troubleshoot extension.

@adriano-dsj do you have by any chance the Ink/Stitch extension in a subfolder of the Inkscape extensions folder? For Ink/Stitch the inx files have to go directly into the extensions folder. We haven't been updating to Inkscape 1.0 yet and we would need some modifications to our files to have subfolders working.

**Comment by LochanLoch** [comment]
break apart work well with a lot of symbols in inkscape - no need to make the object to a path any longer ... but work it always ;-) still testing.
