### ISSUE TITLE
project visibility from search

### ISSUE THREAD

**Issue by ghost** [inkstitch/inkstitch#785]
Some months ago i was looking for something like inkstich. searched for a few days on google and DuckDuckGo and all i found was a long dead project for stitching. I stumbled on inkstitch by searching for color pallets for inkscape. I guess the Search picked up the mention of the inkstich pallets. Though I would leave this a note. Glad I found the project and I am working through the tutorial now.

**Comment by lexelby** [comment]
Interesting!  What search terms did you use that didn't find us?
