### ISSUE TITLE
True Fonts to Embroidery Fonts

### ISSUE THREAD

**Issue by rishadnm** [inkstitch/inkstitch#789]
Hi, Started Using Ink/Stitch for few months now. A feature i miss is the ability to convert 'true fonts' to 'Embroidery Fonts' like in Wilcom ES. Donno if this feature already exist. We can get free fonts from lots of sites. but options to get free fonts is almost NIL. So is there any chance this featutre will be added any soon?

**Comment by rishadnm** [comment]
Or Can some one help me find free fonts for ink/stitch. Lettering tool have only few fonts

**Comment by kaalleen** [comment]
Ink/Stitch has no feature to turn text into an embroidery font easily. At the moment we rely on users to send new fonts, which we can then add to the lettering tool. In future we plan to make it easier for users to create new fonts. Right now it is not an easy task to do and we really are thankful for those users, who already created fonts for Ink/Stitch.

I'm sorry to say, but for now you will have to turn text into embroidery letters by hand or use one of the few fonts, that we already offer in the lettering tool.

**Comment by lyderichti59** [comment]
Hi, what would it take to automate the process of converting ttf fonts to embroidery fonts ?

Do you have a rough overview of the steps ? I haven't looked at the code yet, but I need this feature as well and might find some time to help you with enough context.
Thanks

**Comment by tyrosinase** [comment]
The process (well, *a* process) to do it manually is here: https://silverseams.com/2020/03/monogramming-without-a-font/ and also, to an extent here: https://silverseams.com/tutorials/digitizing-with-ink-stitch/ . It's automate-able to a certain extent, but there's gonna be *so* many edge cases.

**Comment by owendelong** [comment]
What would be a nice interim step would be to have an open repository or library where producers could easily place fonts they have converted and users could reliably go to look for fonts they want. An added bonus would be if it had a feature for requesting and upvoting requested fonts.
