### ISSUE TITLE
InkStitch functions crash InkScape

### ISSUE THREAD

**Issue by yDraigRP** [inkstitch/inkstitch#796]
I tried last weekend and it happened so I thought it was user error.  I then watched the video tutorial today and following the steps simply clicking on the params menu item for the round circle causes InkScape to freeze.  I get no error message and from the task manager I'm not maxing out any CPU or memory.

Windows 10, 64 bit, 8GB memory, Intel I7 CPU

Inkscape version: 1.0 (4035a4fb49, 2020-05-01)

InkStitch version is the latest from the downloads page as I installed it last weekend.

What am I doing wrong?

**Comment by kaalleen** [comment]
I'm going to close this issue due to its age. The last reply describes behavior of the wayland issue and can be avoided by starting inkscape through this command: `export GDK_BACKEND=x11 && inkscape`
