### ISSUE TITLE
InkStitch Dejavue Text

### ISSUE THREAD

**Issue by LochanLoch** [inkstitch/inkstitch#797]
Me again ;-)
Testing the new 1.29.1 Inkscape 1 under Debian.
I like DejaVue more the Unicode letters for LaTeX but to do them in InkStitch is great.
![Bildschirmfoto_2020-08-22_20-57-36](https://user-images.githubusercontent.com/66974900/90964805-25f8b280-e4c4-11ea-832d-ce0ceaa71890.png) Its really nice but I miss my ß or ü ö ä ;-) 
![Bildschirmfoto_2020-08-22_20-00-23](https://user-images.githubusercontent.com/66974900/90964831-6821f400-e4c4-11ea-9f39-1581c5e8e7ad.png)
![Bildschirmfoto_2020-08-22_19-58-55](https://user-images.githubusercontent.com/66974900/90964832-6ce6a800-e4c4-11ea-85d8-197da4603b94.png) so I played a bit and noticed a problem with
- path90621 [;]
- path95394 [!]
- path95394-1 [?]
the line made to a ----- Line solved the problems to start **Parameter** but are they really useful? Very short lines.
![Bildschirmfoto_2020-08-22_21-51-43](https://user-images.githubusercontent.com/66974900/90965122-a23fc580-e4c5-11ea-9526-4fc7f5a8c5ee.png)
And I miss the nice filling in K ... 
[ProblemDejaVue.svg.txt](https://github.com/inkstitch/inkstitch/files/5112905/ProblemDejaVue.svg.txt) <- the svg like picture above to play a bit :-)
I don't know how that work with the lettering I am not a developer - but I hope I can help a bit.

MfG
PaulMüller

**Comment by Augusa** [comment]
I created this font. As I am french I  created what I need ! You have forgottent à â â ê î ô û ü… ! My next project is to create the font to write back direction which does not yet exist. So it’s better not to use the two senses of writing. If I have time I’ll create letters missing for german. I will take a look to the different problems you noticed.
Thanks for using this font and for helping to improve it
Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : LochanLoch<mailto:notifications@github.com>
Envoyé le :samedi 22 août 2020 22:28
À : inkstitch/inkstitch<mailto:inkstitch@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :[inkstitch/inkstitch] InkStitch Dejavue Text (#797)


Me again ;-)
Testing the new 1.29.1 Inkscape 1 under Debian.
I like DejaVue more the Unicode letters for LaTeX but to do them in InkStitch is great.
[Bildschirmfoto_2020-08-22_20-57-36]<https://user-images.githubusercontent.com/66974900/90964805-25f8b280-e4c4-11ea-832d-ce0ceaa71890.png>Its really nice but I miss my ß or ü ö ä ;-)
[Bildschirmfoto_2020-08-22_20-00-23]<https://user-images.githubusercontent.com/66974900/90964831-6821f400-e4c4-11ea-9f39-1581c5e8e7ad.png>
[Bildschirmfoto_2020-08-22_19-58-55]<https://user-images.githubusercontent.com/66974900/90964832-6ce6a800-e4c4-11ea-85d8-197da4603b94.png>so I played a bit and noticed a problem with

  *   path90621 [;]
  *   path95394 [!]
  *   path95394-1 [?]
the line made to a ----- Line solved the problems to start Parameter but are they really useful? Very short lines.
[Bildschirmfoto_2020-08-22_21-51-43]<https://user-images.githubusercontent.com/66974900/90965122-a23fc580-e4c5-11ea-9526-4fc7f5a8c5ee.png>
And I miss the nice filling in K ...
ProblemDejaVue.svg.txt<https://github.com/inkstitch/inkstitch/files/5112905/ProblemDejaVue.svg.txt> <- the svg like picture above to play a bit :-)
I don't know how that work with the lettering I am not a developer - but I hope I can help a bit.

MfG
PaulMüller

**Comment by LochanLoch** [comment]
Sorry that I don't used your nice '`^ will check soon when I need for a friend :-)

Will wait for next update - If I can help I am LaTeX user.
