### ISSUE TITLE
Update to latest wxPython (4.0.1)

### ISSUE THREAD

**Issue by AkiraNorthstar** [inkstitch/inkstitch#80]
We're using an outdated version of wxPython in the Linux build.  4.0.1 contains some fixes that may be relevant, including one that may even mean we don't have to specify the LD_LIBRARY_PATH in `bin/build-dist` anymore.

original issue text follows:

----------------------------------------------

.travis.yml:
```
58      # wxPython doen't publish linux wheels in pypi
59      wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
60      pip install wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
```
You don't need wget to download .whl, so you can use pip for it:
```
58      # wxPython doen't publish linux wheels in pypi
59      pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
```
requirements.txt:
```
01 backports.functools_lru_cache
02 wxPython
03 networkx
...
```
To:
```
01 backports.functools_lru_cache
02 https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b2-cp27-cp27mu-linux_x86_64.whl
03 networkx
...
```
This works for me (fedora 27 x86_64).

You should also replace the wheel file to the latest version of wxPython (4.0.1):
https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.1-cp27-cp27mu-linux_x86_64.whl
Some changes:
This release is a quick hot-fix of some issues discovered in 4.0.0 just after the release, plus a bit of low-hanging fruit that was easy to squeeze in too. Changes in this release include the following:

    A fix for a segfault that happens upon startup on newer linux releases. (#648)

    Set LD_RUN_PATH for the wxWidgets part of the build so the wx libs that are loaded by other wx libs can be found successfully. (#723)

    Use wxApp::GetInstance to check if there is an existing wxApp object. (#720)

**Comment by lexelby** [comment]
Yeah, I tried having pip fetch the wheel itself, but I ran into all sorts of trouble with Python tls/sni support.  This was the only reliable way to get the build to work in Travis.  Kind of a pain :(

Thanks for the tip on wxpython 4.0.1!

**Comment by AkiraNorthstar** [comment]
We can close it - we always update from time to time...
