### ISSUE TITLE
Add trim ability for fonts without auto-route satin

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#800]
1)The two Fonts Geneva are nearly invisible if you use them in a large motiv for exemple A4. Strokes are too thin.

2) Some users want to have the thread cutted after each letter but it looks impossible.

3) How to help users who can write a text in lettering and then nothing more. The window with the simulation never appears. (Version 1.28 or 1.29). They can use other fonctions of Inkstitch

Thanks for help

**Comment by LochanLoch** [comment]
to 3. window with simulation open but update every new char :-( and that is very slow.

Is there a way to change the background color of simulation window?

**Comment by Augusa** [comment]
The point 3 has an answer. It was a bad result of unzipp which changed the arrows in the name of the fontfiles.

**Comment by kaalleen** [comment]
Point 1 should be solved with the new version (invisible letters).

Point 2 is still open  - fonts without autoroute will not add trims at all. For all other fonts trims should be added for each letter. Or is there an issue with those?

**Comment by kaalleen** [comment]
I'll close the issue. The feature has been added with #1866
