### ISSUE TITLE
Simulation: Failed to Execute Script Inkstitch

### ISSUE THREAD

**Issue by goldenKoi577** [inkstitch/inkstitch#803]
I updated both Inkscape and Inkstitch today and now everytime I try to use the simulation inkscape pops up an error message 'failed to execute script inkstitch'.  I dont know how to solve this problem, would love some help here. As I am very new to inkscape & inkstitch it probably is my fault

**Comment by kaalleen** [comment]
@goldenKoi577 Sorry you are having problems with Ink/Stitch. It is hard to tell what went wrong with your installation. Maybe you could answer some questions.
* Which operating system are you using?
* Which Inkscape version have you installed?

**Comment by goldenKoi577** [comment]
I use windows 10 (home) and i have installed inkscape 1.0

**Comment by carolineruaud** [comment]
Bonjour,

J'ai installé inkstitch comme indiqué sur votre vidéo mais quand j'utilise le chemin pour vectoriser je n'ai pas les mêmes options que vous. Même sans inkstitch cela n'apparaît pas. Je suis sous windows 10.

**Comment by Augusa** [comment]
Dans l'écrasante majorité des cas les problèmes viennent de ce que l'on a mal mis les fichiers dans l'extension qu'on ouvre dans Edition/Préférence/ Système. Après on obtient un dossier inkstitch et 65 fichiers dont le nom commence par inkstitch. Il ne faut pas mettre le fichier compressé mais son contenu.

________________________________
De : carolineruaud <notifications@github.com>
Envoyé : dimanche 25 octobre 2020 12:59
À : inkstitch/inkstitch <inkstitch@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [inkstitch/inkstitch] Simulation: Failed to Execute Script Inkstitch (#803)


Bonjour,

J'ai installé inkstitch comme indiqué sur votre vidéo mais quand j'utilise le chemin pour vectoriser je n'ai pas les mêmes options que vous. Même sans inkstitch cela n'apparaît pas. Je suis sous windows 10.
