### ISSUE TITLE
No preview images in print pdf

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#808]
I'm new to inkscape and not sure if I did some wrong configuration or if its a actual bug. I can't see my (albeit complicated) design and the Mini steps in the PDF Export option. I can view the thread color in the export and I can see the Steps. 
[Elche2.pdf](https://github.com/inkstitch/inkstitch/files/5163972/Elche2.pdf)

The params works for the file 
![Bildschirmfoto vom 2020-09-02 20-00-56](https://user-images.githubusercontent.com/64272979/92019662-442da080-ed57-11ea-8843-7440797e5884.png) and the simulator as well ![Bildschirmfoto vom 2020-09-02 20-04-23](https://user-images.githubusercontent.com/64272979/92019832-86ef7880-ed57-11ea-9c02-eeb949cc3f8c.png)

I could see it with an easier file (only a star).
[Stern_Inkstitch_Test.pdf](https://github.com/inkstitch/inkstitch/files/5164019/Stern_Inkstitch_Test.pdf)

I'm working on gnome/open suse (tumbleweed)

Help would be appreciated. Thanks a lot 
B-ellanna

**Comment by kayleighs** [comment]
I had the same issue. I changed the color to CMYK instead of RGB and it was able to render.

**Comment by kaalleen** [comment]
@Tina-Chris is this still happening?

**Comment by Tina-Chris** [comment]
I've got comments on the Facebook group of this happening from time to time. It has not happened to me since this digitizing, as I'm more busy with making the videos instead of digitizing myself.

**Comment by kaalleen** [comment]
Ok, maybe we can catch a svg file from there if someone is sreporting it again.
