### ISSUE TITLE
Lettering tutorial test + Kerning question

### ISSUE THREAD

**Issue by LaureFR38** [inkstitch/inkstitch#809]
Lettering tutorial test
====================================================

First, what do you think of this technique to create the svg containing all the satin column characters ?

1) Download software https://fontforge.org/en-US/
2) Download a font on https://www.dafont.com/
3) Open the font in FontForge
4) In FontForge : On the characters that don't interest you in table, right click>Erase (You can make a multiple selection)
5) In FontForge : Element>Fonte info>General>Em size, put value : 100 (in Inkscape 100px = 2.64cm, I think it's good to write in embroidery)
6) In FontForge : File>Generate Font, In format choose : SVG Font. Click generate.

Now, You have an svg file that contains tags: \<glyph> and \<hkern>. No path for the moment.

7) Copy the directory for example C:\Users\xxx\AppData\Roaming\inkscape\extensions\inkstitch\fonts\dejavufont. 
Rename the copied directory to mynewfont.
8) In directory mynewfont, modify the file font.json, edit value name and description (for the moment)

Now, You will see a new line appear in the lettering with the name of your font

9) Open your svg generate by FontForge with Inkscape
10) In Inkscape : Extensions>Typography>Convert SVG Font in glyph layer. In the popup, put the number of characters in your font, around 150 or more (it doesn't matter, you just have to put a number greater than the number of characters) You get a layer for each character. It's wonderfull ! Document size and guides are not good. You can remove the guides and change the size of the document, but be careful that this doesn't change the font size.

Now, you have to take care of each character to transform it into embroidery (satin column or straight stitch or ...). Don't forget to delete the paths that are not embroidery otherwise the lettering will not work.

11) In Inkscape : To correct a bug (?) and force the addition of the viewbox attribute of the svg tag : File>Document properties> Scale> Scale x : just click on button + then click on button -. Close popup.
12) In Inkscape : After transforming the characters into embroidery (You can transform just one character to test. But you will only use this character in the lettering.); File> Save as > Choose the file with the arrow going to the right in the directory C:\Users\xxx\AppData\Roaming\inkscape\extensions\inkstitch\fonts\mynewfont. 

Now, you can test your font with writing from left to right.
(You can clean the svg file by removing the tags \<glyph> and \<hkern>)

Kerning question
====================================================

If you read my text above, you will understand that the software FontForge generated me an svg which contains the tags \<hkern> and \<glyph>. 

For exemple : 
\<glyph glyph-name="T" unicode="T" horiz-adv-x="60" d="..............." />
\<hkern g1="T" g2="s" k="7" />

I see that there is a space of 7 between "T" and "s" and that horizontal advance of T is 60. (Or the space between "T" and "s" is 60+7, may be ?)

What is the unity of these values ? They change when I modify in FontForge : Element>Fonte info>General>Em size.

In font.json file in Inkstitch :
"leading": 24,
"letter_spacing": 1.5,
"word_spacing": 7,
"kerning_pairs": {
        "AA": -1.5 , "AB": -1.5, .........

What is the unity of these values ?

Is it not possible to make a link between these values?
This would easily fill the JSON file with the correct values ​​entered by the font creator.

------------------------
Thanks for reading me

**Comment by LochanLoch** [comment]
ty for tutorial

**Comment by lexelby** [comment]
Your tutorial looks great!  There's just one thing I would add.  Ink/Stitch does care about one of the guides: baseline.  There should be a "baseline" guide (labeled in English, sorry!!).  That tells Ink/Stitch where to line up your text.  Without a baseline, Ink/Stitch uses a default that works okay, but it's better if you tell it where the baseline of your font is.

**Comment by lexelby** [comment]
The unit for the `kerning_pairs` in font.json is millimeters.  I have no idea what the unit in FontForge is...

This is the first time I've heard of the term "horizontal advance".  I really don't know much about typography. :)  It looks like it's the width of the glyph (sort of...).

Ink/Stitch doesn't have a concept of a horizontal advance per glyph.  Instead it determines the width of the glyph automatically by looking at the vector objects in the GlyphLayer.  It spaces glyphs apart using the `letter_spacing` setting in the font.json.

This isn't actually a great way of doing it.  In the case of a satin column, Ink/Stitch may see a rung that extends out on the side past where the stitches will actually be.  Maybe Ink/Stitch should have the concept of a horizontal advance per glyph?  What do you think?

**Comment by tyrosinase** [comment]
On 9/18/20 4:09 PM, Lex Neva wrote:
>
> This isn't actually a great way of doing it. In the case of a satin
> column, Ink/Stitch may see a rung that extends out on the side past
> where the stitches will actually be. Maybe Ink/Stitch should have the
> concept of a horizontal advance per glyph? What do you think?
>
I would definitely go for this. Because connected script fonts (toward
which I am biased because I hate hate hate jump threads) don't really
have kerning per se, they just have a point where the stroke starts and
ends. I'm not sure horizontal advance is it, because some of them will
have loops and swoops fore *and* aft, but in any event just being able
to say how to connect the letters without having to have a kerning pair
for every possible combination would be a cool thing.

**Comment by Augusa** [comment]
@lexelby I use this tutorial for preparing a new font. It works fine. I have question for Inkstitch. Is it important that the page is a square? Fontforge produces a rectangle. Of course it is possible to change it. Is the place of  the letter important? It must be entirely in the square or not? The letters have to be at a precise distance from the edge of the square? Or as you said the only important thing is the baseline?
I suggest a place to tell the font on which somebody is working. It would be very stupid if 2 persons are creating the same font at the same time.

**Comment by lexelby** [comment]
> I would definitely go for this. Because connected script fonts (toward
> which I am biased because I hate hate hate jump threads) don't really
> have kerning per se, they just have a point where the stroke starts and
> ends. I'm not sure horizontal advance is it, because some of them will
> have loops and swoops fore *and* aft, but in any event just being able
> to say how to connect the letters without having to have a kerning pair
> for every possible combination would be a cool thing.
> 

Oh yes, I abhor jump stitches as well.  A script font is a great example of how Ink/Stitch's current method for determining a glyph's width won't work.  Even if Ink/Stitch went so far as to internally calculate all the stitches for each glyph to measure the real width, it _still_ wouldn't be correct, because the connecting satin is at an angle!  There has to be some overlap.  

So that's decided, we'll add horizontal advance per glyph.  No idea when, of course, but some day! :)

**Comment by lexelby** [comment]
> @lexelby I use this tutorial for preparing a new font. It works fine. I have question for Inkstitch. Is it important that the page is a square? Fontforge produces a rectangle. Of course it is possible to change it. Is the place of  the letter important? It must be entirely in the square or not? The letters have to be at a precise distance from the edge of the square? Or as you said the only important thing is the baseline?

The page can be whatever size you like.  The placement of the letter is not important.  I think it doesn't even need to be entirely in the page although I'm not 100% sure about that.  Distance from the edge of the page doesn't matter.  It doesn't have to be centered.  

All that matters is the baseline.  That's just so that Ink/Stitch knows how to line up all the letters relative to each other.

I hope that helps, let me know if I can clear up any other questions :)

**Comment by LaureFR38** [comment]
Here is what I understood from the information contained in a font :
![xml](https://user-images.githubusercontent.com/63351363/95200649-094bdc00-07df-11eb-9d44-d45354ce5ab5.jpg)

**Comment by LaureFR38** [comment]
@lexelby Now that the information provided makes sense, any idea how to use this for the json?
As today Inkstitch calculates its own width for each letter I cannot find a solution :-(

**Comment by Augusa** [comment]
Something important when using this method with Fontforge : It is necessary to transform the page as a square. Otherwise the baseline, ascender... are not stable.
