### ISSUE TITLE
Alternative MacOS installation

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#811]
Currently, the install instructions involve using cURL to download Inkstitch, in order to avoid problems with Gatekeeper. Gatekeeper can also be bypassed by removing the quarantine extended attribute from the application, allowing for an otherwise normal installation process.

After downloading and extracting to the extensions folder, one can simply run the following:
```
xattr -r -d com.apple.quarantine ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/
```

(Replace the path if your Inkscape extensions directory is non-standard)

The current instructions are probably quicker, however this is another option that may want to be posted.

**Comment by kaalleen** [comment]
Thank you for mentioning this other option. I will add this to the documentation soon.

**Comment by kaalleen** [comment]
Suggestion added to the website. I will close the issue now. Please reopen if corrections have to be made.
