### ISSUE TITLE
MacOS, clicking "x" button does not end inkstitch-gui process, locking up inkscape

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#812]
After clicking the x button on inkstitch-gui, inkscape still believes the tool is running, and it technically is. Explicitly quitting inkstitch-gui is necessary to return to inkscape. 

The culprit here is abiding by typical MacOS behavior, as shown in electron default setup, where we should not. (See https://github.com/inkstitch/inkstitch/blob/main/electron/src/main/index.js#L63)

The check for "darwin" should be removed. Failure to quit the application will lock up inkscape, forcing the user to explicitly quit inkstitch-gui, either through activity monitor, terminal, or the dock.

**Comment by sjmartian** [comment]
I'm new to Inkscape, but whenever I try to do it I get the same problem. The way I get around it is right clicking on the gui on the taskbar and quitting it there.

**Comment by ecc521** [comment]
That's exactly how I do it. But deleting two lines of code shouldn't be too much of a problem :)

**Comment by kaalleen** [comment]
I'll close this now (I believe this has been fixed). Please reopen if this is still current behavior.
