### ISSUE TITLE
inkstitch-gui should open in fullscreen if inkscape fullscreen

### ISSUE THREAD

**Issue by ecc521** [inkstitch/inkstitch#813]
At least on MacOS, inkstitch-gui does not go into fullscreen mode when opened, even if inkscape is fullscreen. This can make multi-finger-window-swipe navigation difficult to use, as some windows must be accessed via dock.

Not quite sure about the practicality of this, as I don't know all that much about inkscape's extension infrastructure, however if implemented, it would certainly be a nice QoL improvement.

**Comment by lexelby** [comment]
That would be great!  Unfortunately, as you guessed, Inkscape's extension system doesn't give us access to that information.

I'm going to go ahead and close this ticket since we can't do this, but know that we do appreciate your suggestion!  We want to hear about the rough edges in Ink/Stitch.
