### ISSUE TITLE
gaps in embroidery between rows

### ISSUE THREAD

**Issue by kaitngu** [inkstitch/inkstitch#818]
So I'm on a macbook pro, and when I load up designs into my embroidery machine, it leaves some gaps in the stitching between satin fill rows. 

It looks like this - 

________
________
________
\\\\\\\\\\\    (this is the underfill stitch)
________
________
________

Any tips? Is there some setting I can toggle to add some overlap?

**Comment by lexelby** [comment]
That's weird!  Can you post an example SVG?

**Comment by tyrosinase** [comment]
For satin you can increase the density by decreasing the peak-to-peak distance in Params, and for fill you can decrease the spacing between rows.

If satin is irregularly leaving spaces (say around curves/corners) you can often fix it with extra rungs or, worst case, by splitting up the column and having a extra-short peak-to-peak to cover segments with sharp turns, but I'm guessing by "satin fill" you mean fill. Fill should always be evenly spaced (unless you've done something deliberate with the secret features, but that involves editing the XML directly https://silverseams.com/2020/08/special-effect-fills-with-ink-stitch/).

Is the physical result different than the preview?
