### ISSUE TITLE
Help needed - can't convert my digitally drawn image to closed objects ready for embroidery

### ISSUE THREAD

**Issue by Guanuna** [inkstitch/inkstitch#820]
I designed an image and wanted to make it possible to embroider - it includes up to 10 colors and when I attempt to convert the image using trace bitmap, inkstitch shares that some borders might not be closed or might overlap (it appears that they do). I took a quick look at the nodes are there are hundreds on each layer that bitmap did - too much to do by hand. Is there ANY other way to take the image as it is and convert it to something capable of being embroidered by inkstitch?

**Comment by tyrosinase** [comment]
On 9/14/20 11:53 AM, Guanuna wrote:
>
> I designed an image and wanted to make it possible to embroider - it
> includes up to 10 colors and when I attempt to convert the image using
> trace bitmap, inkstitch shares that some borders might not be closed
> or might overlap (it appears that they do). I took a quick look at the
> nodes are there are hundreds on each layer that bitmap did - too much
> to do by hand. Is there ANY other way to take the image as it is and
> convert it to something capable of being embroidered by inkstitch?
>
Performing a Union (Path menu) will close any borders and remove any
overlaps, and goes a long way toward getting stuff cleaned u enough to
be stitchable. Simplify (also Path menu) will cut down on the nodes,
though it often *over*-simplifies. And you can tweak the settings for
the trace in preferences, so that it gets a more useful number of nodes
in the first place.

**Comment by Guanuna** [comment]
Although initially promising, I regret to say it didn't work. I still get a shape error supposedly due to the borders overlapping

**Comment by Guanuna** [comment]
Any other ideas? Should I skip the trace bitmap all together? Is there a way to eliminate that step and go directly from the SVG colored image to an inkstich accepted file?

**Comment by Guanuna** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/70546147/93112216-f37e4780-f674-11ea-8c83-91c854e01543.png)

**Comment by tyrosinase** [comment]
On 9/14/20 12:18 PM, Guanuna wrote:
>
> Although initially promising, I regret to say it didn't work. I still
> get a shape error supposedly due to the borders overlapping
>

Oh, I bet I can see the problem: depending on the scale, it's probably
trying to fill that dog and not being able to fit stitches in those tiny
spaces. One of the regular devs will have to confirm it, but I bet
that's the error it throws when it keeps trying to make a stitch and
runs into cases where one end of the stitch is in one tuft of hair and
the next one ends up in the next. Ink/Stitch knows that's not *quite* right.

That sort of texture is, unfortunately, not something a plain fill
stitch is good at. By default it's going to want to fill it in with
horizontal rows of stitches, when ideally what you want is a contour
fill to simulate the hairs. And that's really going to require a lot of
human judgment (i.e. lots of manual work).

You *might* be able to get away with setting the angle for each
individual patch (do a Break Apart), but it still might have some
trouble with the very rough edges (again, depending on scale). Simplify
may get rid of some of the jaggies, and you can also do fun things with
Inkscape's outset/offset tools. You can also make things fatter/blunter
by adding an outline: make sure it is set to rounded corners, and do a
stroke-to-object and then get rid of the interior outline. Tedious for
every little patch of dog fur in that, though.

At any rate, you can tell if a shape has an inherent problem or just too
much detail by blowing it up 10x or more and seeing if the fill works
better.

**Comment by Guanuna** [comment]
Thank you, this was helpful! I'll see what I can do
