### ISSUE TITLE
UnicodeDecodeError on macOS Mojave

### ISSUE THREAD

**Issue by kittyangel64** [inkstitch/inkstitch#826]
Just installed inkscape and inkstitch on macOS Mojave, am trying to save a file as a .vp3 to send to an embroidery machine and it comes up this this error then says it could not be saved, I have tried it on multiple SVG files, all of them have simulated without any errors. 

"
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 70: invalid continuation byte
"  

Not sure where to go from here or how to fix this, tried uninstalling and reinstalling with no success.

**Comment by kaalleen** [comment]
Thanks for reporting your error. This is actually an encoding error, which will disappear with one of the next releases when we finally finished the progress of updating our code.
Sadly there will be no updates for Mojave anymore and you are kinda bound to the old version. To get a more valuable error message you could consider switching to the english version.

https://inkstitch.org/docs/install/#macos

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 offers an update for Mojave. This will solve the issue.
