### ISSUE TITLE
Params option not Working

### ISSUE THREAD

**Issue by matchamatcha1** [inkstitch/inkstitch#828]
For anyone having the same issue, please check my comment below!

Hello! I'm having trouble accessing params from the Extensions tab, as it is grayed out. I tried reinstalling both Ink/Scape and Ink/ Stitch on windows (making sure they are the latest versions and unzipped the file in the right extensions folder). Any way to solve this? Thank you for taking the time to read this.

EDIT: I also forgot to mention that I enabled the InkStitch folder as a non-threat for my virus protections.

**Comment by matchamatcha1** [comment]
SOLVED: 

Took a look at the YouTube tutorial from InkStitch's channel that explains the installation process a little bit incorrectly, but this comment saved another 20 hours of searching for a solution for me.

"Robert Peters
1 month ago (edited)
Ok. I've been hammering on this for 24 hours and I think i found the problem. The instructions are bad.  When I unzipped the extension into my extension folder it created a folder matching the download name.  this is what the directions tell you to do.  It's wrong. You need to move everything FROM that folder directly to the Extensions folder.   So in the extensions folder you'll have a big list of files and an "inkstitch" folder.  Once i made this change suddenly i could work with the extension.   I hope this helps!"

**Comment by kaalleen** [comment]
Thanks for reporting your issue. We made the video with this in mind. Maybe we didn't point it out strongly enough, sorry for that. We will have this in mind when we update the video the next time. Also we hope this notice won't be necessary soon with a future update of Ink/Stitch.
