### ISSUE TITLE
Linux: libXss.so - Missing Library for Electron (Simulator)

### ISSUE THREAD

**Issue by kaalleen** [inkstitch/inkstitch#830]
Electron seems to be in need of the libXss.so (screensaver) library and won't work on linux if it is not installed.

**Comment by lexelby** [comment]
Weird, I wonder why it needs it and why it isn't included...

**Comment by kaalleen** [comment]
Doesn't really make sense why it would be needed. It seems to be a dependency of chrome somehow.
