### ISSUE TITLE
Merci Thank you

### ISSUE THREAD

**Issue by Duguest** [inkstitch/inkstitch#831]
Merci aux auteurs de ce programme ! Sans votre travail, je n'aurais pas eu le plaisir de m'aventurer à  construire une machine à broder. Maintenant, c'est fait. J'ai pu rassembler l'essentiel du matériel avant le confinement, une machine à coudre ELNA de 1947, des profils aluminium, une bobine de PLA, deux mètres de courroie, des poulies, des moteurs pas à pas, un ensemble Arduino Méga, avec sa carte d'interface, son afficheur et son lecteur de carte SD. La suite, dessins, impression, assemblage, sans trop de difficultés. Enfin, la compilation de Marlin pour rendre la machine autonome au fond du garage. L'expérience a été enrichissante, c'était une belle aventure.

Je suis impatient de voir évoluer les versions successives de INK-STICH.

Thank you to the authors of this program ! Without your work, I would not have had the pleasure of venturing out to build an embroidery machine. Now it's done. I was able to collect most of the material before confinement, an ELNA sewing machine from 1947, aluminum profiles, a PLA spool, two meters of belt, pulleys, stepper motors, an Arduino Mega set, with its interface card, display and SD card reader. The rest, drawings, printing, assembly, without too much difficulty. Finally, the compilation of Marlin to make the machine autonomous at the back of the garage. The experience was enriching, it was a great adventure.

I am impatient to see the successive versions of INK-STICH evolve.

Jean-Francois.

**Comment by lexelby** [comment]
I love hearing about home-made embroidery machines!  I'm glad you're enjoying Ink/Stitch!
