### ISSUE TITLE
Installation on Catalina (macOS)

### ISSUE THREAD

**Issue by Lynnsha89** [inkstitch/inkstitch#835]
Hey I’m using a Mac on Catalina and downloaded the extensions but it’s not showing embroidery. Please help

**Comment by kaalleen** [comment]
Could you describe your installation steps or confirm your process with the description on our homepage?

https://inkstitch.org/docs/install/#macos

Is the extensions not showing up in Inkscape or is it not working for some reasons, any error messages?
