### ISSUE TITLE
Param does not work for circles

### ISSUE THREAD

**Issue by AustralianSpaceTrash** [inkstitch/inkstitch#844]
Hi all - I am new to inkstitch and am having trouble to get Param working consistently for circles. At first I thought it was an issue to do with the size of the circle, but it happily works for other small shapes. Any guidance would be greatly appreciated!

**Comment by kaalleen** [comment]
Ah, the circle problem ;) Sorry about that, this can be annoying.

If this is the usual issue (border crossing) and not some other error message coming up, then we actually do have two solutions to offer.

* For circles it often works fine if you double click on the object (to get into the node edit mode) and then drag one node into any direction. While still dragging it press the escape button to release it to it's original position. This will alter the path slightly and should make it work in most cases.

* If the border crossing problem persists, you can make use of the fill tool "break apart fill objects". This should definitely work and should solve most (hopefully all) border crossing issues. 

An other option to inspect broken shapes is our troubleshoot extension (troubleshoot objects). This was invented to give you hints about what could be going wrong with your shapes and how you can solve the issues.

**Comment by kaalleen** [comment]
I will close this issue now. In the next (upcoming) release, this behaviour will improve.
Please reopen if you find is necessary.
