### ISSUE TITLE
Inkstitch "Troubleshoot" function sees "Border Crossing Itself" error after path rotation at specific angles

### ISSUE THREAD

**Issue by Huertaaj** [inkstitch/inkstitch#850]
1) In Inkscape create a horizontal OVAL and a horizontal RECTANGLE, convert them both to a path.  Run Inkstitch/Troubleshoot function.  No errors reported

2) Rotate the oval and rectangle and then run the Troubleshoot function again.  If the oval is rotated to specific angles a "Border Crossing Itself" error appears which does not allow Inkscape to process the file for embroidery.  This is repeatable (but not always).

The rectangle does not result in errors, but I have noticed this same error with other shapes that I have created, but not always repeatable.

3) Angles (degrees) that cause the error that I have tried so far that result in the "border crosses itself) error are...1, 2, 4, 5, 6, 7, 9, 12, 13, 15, 17, 18, 20, 22, 23, etc.  You can see that some specific angles are skipped and I have not tried fractions of angles.  However, it is not always repeatable since some angles such as 23 or others result in the error but other times no error results.  There is no pattern that I can see.

4) Lastly, Clockwise vs Counterclockwise rotation can report different results.  In the example images I'm submitting rotating to 22 degrees clockwise results in the error but rotating to 22 degrees counterclockwise does not result in the error.

![Capture_Border crosses itself error at certain angles__This one is at 22 degrees CLOCKWISE](https://user-images.githubusercontent.com/71040496/95692325-04c65f80-0bf3-11eb-8e51-3162d5bb7fa3.JPG)

![Capture_Border crosses itself error at certain angles__This one is at 22 degrees COUNTERCLOCKWISE](https://user-images.githubusercontent.com/71040496/95692337-0ee85e00-0bf3-11eb-920a-ca4b464ea89b.JPG)

**Comment by Huertaaj** [comment]
After more testing today I found that simply duplicating the oval followed by moving the duplicated oval (the clone) will result in this same error.

**Comment by ecc521** [comment]
The instructions provided tell you exactly how to fix this issue - instead of Troubleshoot, select Fill Tools, click Break Apart Fill Objects, and run it. 

Ink/Stitch should probably do this automatically, but the utility has worked fine for me.
