### ISSUE TITLE
Giving Inkstitch an other try.  Errors... 

### ISSUE THREAD

**Issue by lenerdo** [inkstitch/inkstitch#855]
![Screenshot 2020-10-16 030214](https://user-images.githubusercontent.com/17054318/96223505-0af26e00-0f5c-11eb-950a-be3234f4e589.png)

**Comment by lenerdo** [comment]
Error before crash

![image](https://user-images.githubusercontent.com/17054318/96223583-2c535a00-0f5c-11eb-8784-980e2d6347db.png)

**Comment by lenerdo** [comment]
![image](https://user-images.githubusercontent.com/17054318/96223754-6cb2d800-0f5c-11eb-90f8-4e6cd85c39ad.png)

**Comment by ecc521** [comment]
Windows may be different from MacOS, however what version are you using? The error message for me directs to "Fill Tools > Break Apart Fill Objects" which has always fixed border crossings.

**Comment by kaalleen** [comment]
Could you solve your issue with help of the break apart fill objects? Your design looks like it will produce a lot of small fill stitches if used like that. It might help to simplify your design. Although the newest Ink/Stitch version should be able to handle them better, it might not look great when embroidered like this.

**Comment by kaalleen** [comment]
No further respond. Closing.
