### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by presscafe** [inkstitch/inkstitch#858]
Tried to launch: inkstitch\bin\inkstitch Arguments: ['inkstitch\\bin\\inkstitch', '--id=image18', '--collapse_len_mm=3', '--hide_layers=true', '--output_format=dst', '--extension=embroider', 'C:\\Users\\Farouk Pandor\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgIR9NS0'] Debugging information: Traceback (most recent call last): File "inkstitch.py", line 35, in <module> extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE) File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__ errread, errwrite) File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child startupinfo) WindowsError: [Error 2] The system cannot find the file specified

**Comment by kaalleen** [comment]
Could you check if your virus programm deleted inkstitch files?
