### ISSUE TITLE
Run Break Apart Function Automatically on Overlapping Fill Shapes

### ISSUE THREAD

**Issue by Newbiestitcher** [inkstitch/inkstitch#859]
Hi, I made a very simple adobe illustrator design. I've imported it into Inkspace using several file formats, ie SVG, AI, EPS... etc and this doesn't seem to make a difference. I ungroup everything, then set object to path and then go to autofill using the params tool and all I get is error messages that this path is overlapping this path etc. So I've deleted all the paths which overlap, still, there is an "overlapping issue" to the point that I just delete the entire file one by one until there is nothing left because I'm still always getting this issue. So I went back into Adobe Illustrator and removed all overlapping paths in there, reimported it, and same issue! So frustrating. I also don't get the preview come up for me on the right hand side when in Params? Sometimes it is there when I make a simple circle or something within Inkscape itself, but not always. Also, I tried making my vector in Inkscape itself using the path tool and still, I get this "Overlapping issue" error messages all over again. Please can someone help? I've watched the youtube tutorials, I've followed them and looked at over guides and support online and now I'm just stumped. Is this even possible? Thank you in advance!

**Comment by ecc521** [comment]
At least on Mac, you can go under Fill Tools > Break Apart Fill Objects, and run it, and it should fix the overlapping borders. I tend to think Ink/Stitch should do this automatically, but I suspect a maintainer can tell me why that is a bad idea. 

<img width="1030" alt="Screen Shot 2020-10-21 at 10 39 34 PM" src="https://user-images.githubusercontent.com/42424091/96817887-4c689a80-13ee-11eb-926f-72f61cbc8c97.png">

**Comment by kaalleen** [comment]
Overlapping issues will be massively reduced in the next (upcoming) release. They still will pop up, if the shape visibly does overlap and would need to be treated as two (or more) shapes during the rendering process. In this case use `Extensions > Ink/Stitch > Fill Tools > Break apart Fill Objects` as mentioned above.

**Comment by kaalleen** [comment]
> I tend to think Ink/Stitch should do this automatically, but I suspect a maintainer can tell me why that is a bad idea.

The main reason why users wants to break objects apart themselves would be to manually decide about the order of the elements. Other than that, we have plans to break objects apart automatically in the future. But we haven't come to implement it. If anyone has the skills and the time, we appreciate any help we can get ;)

**Comment by kaalleen** [comment]
... actually I cannot find a feature request for this to run automatically - although we've talked about it in the past.

Let's make one here ;)

- [ ] Run break apart function automatically when shape is invalid

See also: https://github.com/inkstitch/inkstitch/pull/690#issuecomment-629699362

**Comment by kaalleen** [comment]
See also new shapely function `make_valid` as mentioned by @lexelby
