### ISSUE TITLE
Localization of README

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#86]
Add the README to CrowdIn and configure it to send the output somewhere useful.  It'd be especially cool to automatically add links to the translated versions in the main README.

**Comment by AkiraNorthstar** [comment]
@kaalleen and @lexelby:
I only have access to messages.po, is there anything i missed or i have to do?

**Comment by lexelby** [comment]
Not yet, but thanks for the reminder about this issue!  I created this well before the massive documentation effort.  Back then, README was all we had.  Perhaps we should close this and create a new issue, "localization of inkstitch.org"?  I know it would be a _huge_ effort but it'd be super cool if we could translate all the tutorials to other languages too.  Thoughts?

**Comment by AkiraNorthstar** [comment]
Yes, we should close this entry. And localization of inkstitch.org would be fitting from the topic. We should get there @kaalleen if you like that. @kaalleen knows the gh-pages well and makes a great job there. Maybe something is already prepared?
