### ISSUE TITLE
Saving as .pes

### ISSUE THREAD

**Issue by taymar7** [inkstitch/inkstitch#860]
I've gotten this error:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 18: invalid start byte

on two different Apple computers, one running Mojave and the other Sierra.
I'm trying to save as .pes but I am unable to when just a few days ago I had no problems at all.

![Screen Shot 2020-10-22 at 12 50 08 PM](https://user-images.githubusercontent.com/73312440/96922787-28946b80-1465-11eb-8e25-0fcf933e28fe.gif)

**Comment by kaalleen** [comment]
Sorry for this. It is an encoding error. Are you by any chance trying to save a file with special chars?
These errors should not appear anymore when we converted to the recent python version. But we are not there yet.

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 comes with releases for El Capitan/Sierra and High Sierra/Mojave. This will solve this issue.
Please reopen if that is not the case.
