### ISSUE TITLE
issue saving a file with the embroider tool.

### ISSUE THREAD

**Issue by annoyingproblem** [inkstitch/inkstitch#872]
I tried saving a project that I had made on the Inkscape platform, the params viewer had worked and everything it seemed my file was good to go. However, when I tried saving the file, leaving the directory blank as instructed, the error message "Error writing to ./final stitch.pes: Read-only file system" appeared, I repeated the process with a simple circle which once again, had been put through the params part and everything, yet the message still appeared. All help is appreciated, thanks!

btw final stitch was the name to the file I was working on.

**Comment by ecc521** [comment]
Try specifying an absolute directory path for output directory. 

@lexelby: Is this a duplicate? I also encountered this issue when setting up, and it is a rather confusing bug.

**Comment by ecc521** [comment]
<img width="387" alt="Screen Shot 2020-11-12 at 1 31 19 PM" src="https://user-images.githubusercontent.com/42424091/98980964-5bbd9e00-24eb-11eb-81c6-dd6fdecd4b7b.png">

**Comment by annoyingproblem** [comment]
Yeah this solved the issue

**Comment by lexelby** [comment]
Thanks for the debugging work, @ecc521!  Another way to save embroidery design files is "File -> Save Copy As" and choose one of the Ink/Stitch file formats from the drop-down.  I feel like that is a much better user experience, and ultimately we will probably retire the Embroider method.

**Comment by ecc521** [comment]
Wasn't aware of that feature, but I'll probably start using it. I'll need to test it out a bit to see how it does remembering directories.

**Comment by kaalleen** [comment]
I'll close this issue now. The embroider function will be removed in the upcoming release. We will fully rely on File > Save a Copy.
