### ISSUE TITLE
parasm not working

### ISSUE THREAD

**Issue by thooper1119** [inkstitch/inkstitch#881]
I just installed inkstitch but unable to get it to work properly;  every item that i select even parasm gives me an error message;  two are linked below, please help and thank you 
![ink stitch error 2](https://user-images.githubusercontent.com/74257712/98699026-88c35280-232b-11eb-9d17-1a20ab5155c0.PNG)

![ink stitch error1](https://user-images.githubusercontent.com/74257712/98699079-9973c880-232b-11eb-961d-f81106014053.PNG)

**Comment by kaalleen** [comment]
See #578 (and #1089) and sorry for the late answer.
Since this error is already in our bug list. I'll close the issue. If you have more questions, you can still post them here or in #578 and thanks again for reporting.
