### ISSUE TITLE
path issues

### ISSUE THREAD

**Issue by natmagnan** [inkstitch/inkstitch#896]
j'essaie de transformer un texte écris en police "Zapfino" et de le convertir en broderie grave à ink stitch. mon texte est "Les Gaillards". seulement je n'y arrive pas car pour certaines lettres ( le "d" et le "e" ) ca me dis "erreur : Remplissage: La forme n'est pas valide. Cela peut arriver si la bordure se croise elle-même." Et je ne comprend d'ou cela vient. merci 
Nathan

**Comment by Augusa** [comment]
Ce message se produit lorsqu’un nœud est mal traduit dans Inkscape. Il faut faire une recherche d’erreur avec « dépistage de problèmes » à trouver dans « résolution de problème » et on bidouille sur le nœud jusqu’à le rendre acceptable.
Ajoutons que le travail sur une police est très particulier.
Si vous débutez il y a un groupe facebook en français consacré à Inkstitch où vous trouverez de l’aide pour ces mille petits tracas qu’on ne manque pas de croiser au début.
https://www.facebook.com/groups/inkstitchfrance
A bientôt et bonne découverte d’inkstitch

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : natmagnan<mailto:notifications@github.com>
Envoyé le :mercredi 18 novembre 2020 17:28
À : inkstitch/inkstitch<mailto:inkstitch@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :[inkstitch/inkstitch] path issues (#896)


j'essaie de transformer un texte écris en police "Zapfino" et de le convertir en broderie grave à ink stitch. mon texte est "Les Gaillards". seulement je n'y arrive pas car pour certaines lettres ( le "d" et le "e" ) ca me dis "erreur : Remplissage: La forme n'est pas valide. Cela peut arriver si la bordure se croise elle-même." Et je ne comprend d'ou cela vient. merci
Nathan
