### ISSUE TITLE
path847_5: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

### ISSUE THREAD

**Issue by wsjb** [inkstitch/inkstitch#900]
Trying to digitize an arabic script and this error is coming. Can you help?

path847_5: error: Error during autofill!  This means that there is a problem with Ink/Stitch.
Thanks 
Saima Wasim

**Comment by ecc521** [comment]
It looks like you didn't paste the entire message block. Can you make sure you pasted it all?
I'd assume this is (another..) ```min() arg``` problem, but it may not be.
