### ISSUE TITLE
Downloads onto Mac Catalina

### ISSUE THREAD

**Issue by MylahBatool** [inkstitch/inkstitch#901]
Hi, 

I'm really sorry if this has been answered elsewhere but I am having great difficulty downloading Inkstitch for Catalina. I tried through Terminal and it comes up in Inkscape as an extension but it is all greyed out. Originally I had dowloaded through your website and it gave me the error message of “‘xxxx’ cannot be opened, because the developer cannot be verified”, so I followed the instructions to download for Catalina through Terminal. Please can an updated video be made for this as it is all so confusing. Thank you so much.

**Comment by Marif91** [comment]
[install inkstitch catalina v2.pdf](https://github.com/inkstitch/inkstitch/files/5632200/install.inkstitch.catalina.v2.pdf)
J'ai fait un mode d'emploi en français, il est disponible en anglais sur le facebook anglais et en allemand sur le facebook allemand.

**Comment by ecc521** [comment]
The normal installation should work, but if that is having problems, try running the code I suggested in #811

**Comment by lexelby** [comment]
If someone can explain to me what I need to do to properly sign ink/stitch, I might be able to give it a go.  I just finally came into possession of an aged but functional macbook air and I've upgraded it to Catalina.  Haven't taken the plunge on big sur yet.

**Comment by ecc521** [comment]
First you need to pay Apple $99/year for a Developer account.
I stopped there.
