### ISSUE TITLE
macOS Catalina: Installation issue

### ISSUE THREAD

**Issue by taylort1143** [inkstitch/inkstitch#904]
I have installed it for my MacOS Catalina and have tried many times but this thing will just not work. What is going on?

**Comment by kaalleen** [comment]
Sorry for your troubles. A little more information about your installation process would be helpful to solve your problem.
Which steps have you done to install Ink/Stitch? Do you receive any error message? Or is Ink/Stitch not showing up in your menu - is it greyed out... etc.?

Here are updated instructions for the installation on macOS. Please notice the additional step for Catalina.

**Comment by taylort1143** [comment]
I have installed in by placing the files into the extensions as said when I look at the tutorial. No error messages pop up but the selections remain greyed out.

Best Regards,
Taylor Thompson

**Comment by kaalleen** [comment]
Sorry, I missed to send the link: https://inkstitch.org/docs/install-macos/

When the menu is greyed out it could be possible, that you accidentally chose the wrong file to download. On the website linked above you will find the correct link in the description.

An other possible reason could be a subfolder. It is really important for Ink/Stitch do have all the files directly in the extension directory. But you mentioned you took care about the file location. So my guess would be the first issue.

**Comment by taylort1143** [comment]
I downloaded for the MacOS Catalina and double checked to make sure I was using the current software. Should I try another version?

Best Regards,
Taylor Thompson

**Comment by taylort1143** [comment]
Hello, I followed the exact steps that were given to me and it still did not work. I double checked the version of my laptop as well and I have the right version. But it is still greyed out.

**Comment by taylort1143** [comment]
Hello?

**Comment by tyrosinase** [comment]
The folks that write Ink/Stitch also run embroidery businesses as a real job; things get a little busy this time of year.

I run Linux myself so I can't be of _too_ much help, but: Under Linux, Inkscape has an extensions directory (.config/inkscape/extensions) in the user directory, which ends up with a bunch of inkstitch* files directly in it as well as a subdirectory named inkstitch.

If those files aren't in the right place, or if the permissions on them are wrong then you get the grayed-out issue. I don't know how directly this sort of thing translates to MacOS, but if that sounds like something for which there's an equivalent maybe check that out.

**Comment by kaalleen** [comment]
Oh sorry for the late answer. There is a new version out there by now. I hope it works for you.

I'll close the issue now, because of the new version. But please reopen if you are still having issues.
