### ISSUE TITLE
PES file could not be opened

### ISSUE THREAD

**Issue by Anja2807** [inkstitch/inkstitch#907]
Hello together,
we try to open .PES files in Inkstitch but we get the following message.

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 26: invalid continuation byte

Du you have any idea?

br

Anja

**Comment by Anja2807** [comment]
Hello together,

we found the issue.
Problem solved. Maybe others have the same problem.
In the filepath of the pes files was an "ä" and this gave us the above error message. We made an "ae" out if it and then it is working.

br

Anja

**Comment by Lorenzoerro** [comment]
Hello Anja2807 ,

Could you tell me how I change the  ä  for ae? where is it?
