### ISSUE TITLE
Break Apart Fill Objects: handle fill-rule

### ISSUE THREAD

**Issue by cravingaburrito** [inkstitch/inkstitch#910]
Instead of retaining holes, Break Apart Fill Objects just fills everything in.
(top is before using the tool, the bottom is after, I'm on macOS Big Sur)
![Screen Shot 2020-12-06 at 2 12 29 PM](https://user-images.githubusercontent.com/75588705/101294571-167c4b80-37cd-11eb-9980-5fbda2e2bece.png)

**Comment by MK-12-20MM** [comment]
This worked for me. The caveat is that it will be all black at first.    In the objects menu - you will need to raise or lower the object and set the fill color appropriately.  

![cow](https://user-images.githubusercontent.com/10312448/101296465-71bc3700-37e9-11eb-9d64-9c8db9ab121e.JPG)

For example I set the path that is selected to the bottom (objects menu). So for each fill area you will need to adjust raise or lower the object. Plus remove the fill color temporarily to see what is going on.  If you have a fill layer object above the others, it will block the others.  This is complex object. If you use the break apart fill on complex shape you might have to manipulate some of the objects.  For organization, you can move each fill to another layer.

**Comment by cravingaburrito** [comment]
> This worked for me. The caveat is that it will be all black at first. In the objects menu - you will need to raise or lower the object and set the fill color appropriately.
> 
> ![cow](https://user-images.githubusercontent.com/10312448/101296465-71bc3700-37e9-11eb-9d64-9c8db9ab121e.JPG)
> 
> For example I set the path that is selected to the bottom (objects menu). So for each fill area you will need to adjust raise or lower the object. Plus remove the fill color temporarily to see what is going on. If you have a fill layer object above the others, it will block the others. This is complex object. If you use the break apart fill on complex shape you might have to manipulate some of the objects. For organization, you can move each fill to another layer.

**Comment by cravingaburrito** [comment]
I wanted the white sections to be negative space. Previous versions would preserve negative space, this method doesn't.

**Comment by kaalleen** [comment]
I am wondering if this is a fill-rule issue.
In the Fill and Stroke panel have a look for this symbol and enable it.
![fill-rule](https://user-images.githubusercontent.com/36401965/101398380-465f4800-38ce-11eb-94c5-aa2fea55b40d.png)

It still needs attention in development. Actually I was aware of it when I wrote the break apart extension. I should have added the rule into the style directly to avoid confusions. It still should render correctly.

Does this solve your issue?

**Comment by cravingaburrito** [comment]
> I am wondering if this is a fill-rule issue.
> In the Fill and Stroke panel have a look for this symbol and enable it.
> ![fill-rule](https://user-images.githubusercontent.com/36401965/101398380-465f4800-38ce-11eb-94c5-aa2fea55b40d.png)
> 
> It still needs attention in development. Actually I was aware of it when I wrote the break apart extension. I should have added the rule into the style directly to avoid confusions. It still should render correctly.
> 
> Does this solve your issue?

It did! Thank you!

**Comment by kaalleen** [comment]
I will reopen the issue as a reminder to handle the fill-rule by the extension itself.
