### ISSUE TITLE
Excessive delay (70 seconds) opening Inkscape -> Params

### ISSUE THREAD

**Issue by MarkMLl** [inkstitch/inkstitch#912]
Please could I re-raise issue #575. Debian Buster with either Inkscape 0.92.4 (from the stable repository) or 1.0.1 (from the backports repository) with Inkstitch 1.29.1 still suffers from a grievous delay when setting the parameters of a single or multiple objects.

This applies even immediately after Inkscape has been opened, and is working on a new document containing a trivial object (e.g. a rectangle) which has not been saved to an svg. I note the previous suggestion that it might be related to font handling, I could potentially explore that by running Inkscape in a container with minimal other software.

I was trying to demonstrate the Inkscape/Inkstitch combination to somebody the other day, and even if it turns out not to apply to whatever operating system etc. she runs it was embarrassing.

**Comment by MarkMLl** [comment]
I'm investigating this as a comparatively easy way of getting into the various problems. I've set up multiple Docker containers with variants of Debian Bullseye and as a first cut can report that using this testing methodology:

* Install Inkscape, check directory accessibility, install Inkstitch 1.29.1
* Run Inkscape, M (Deja Vu Sans Normal 12) in middle of page, object to path, Extensions -> Ink/Stitch -> Params

I see these response times:

* No GUI desktop (no LibreOffice): ~3 secs
* LXQT (has LibreOffice): ~3 Secs
* LXDE (has LibreOffice): ~3 Secs
* KDE (has LibreOffice): ~70 Secs
* Gnome (has LibreOffice): ~3 Secs

Noting what has been said earlier about the problem being related to fonts, my first inclination was to suspect that it was stuff brought in by LibreOffice, however the results above suggest that that is not the case.

Comparing installed package lists, all of the above appear to have fonts-noto-mono (which probably implies the availability of any necessary support infrastructure) but only KDE has the full fonts-noto metapackage.

**Comment by lexelby** [comment]
A very belated thanks for the extra detail!  I'm going to close this so that we have only one issue open for this problem.
