### ISSUE TITLE
can't zip files...

### ISSUE THREAD

**Issue by MatimataDesign** [inkstitch/inkstitch#914]
Dear all,

at first, I started to save my files on other formats... I tried to save as "more formats *zip"...
If I'd like to open it, theres an error named that the zip-folder is invalid...

Could you have an idea, whats my problem?

Thanks so much
BR
Tanja

**Comment by kaalleen** [comment]
Sorry to hear you are having trouble with the zip file. Hope you had no data loss because of it.

Right now I wouldn't know why it didn't work out. Would the normal single file export work for the same design?
Does it happen to fail for all zipped exports?

**Comment by MatimataDesign** [comment]
Hey Kaalleen,
no data got lost :O))
I could export the data only as single...that works fine..only the zipped export doesn't works...

Thank you very much for any answer...

**Comment by kaalleen** [comment]
There has been a fix for zip files a while ago. Therefore I'll close this issue. Please reopen if there are still issues.
