### ISSUE TITLE
Issues on Apple Silicon

### ISSUE THREAD

**Issue by chantagold** [inkstitch/inkstitch#917]
Just got a Mac Mini with the M1 chip and intend to use Inkstitich on it (though I have other machines to run it on now).

The inkscape install went without any issues and it works without issues. However, different story for Inkstitch. I followed the installation instructions for Big Sur, which led to inkscape crashing on launch every time after installation. I've run through the installation process twice and got the same behavior both times, so I don't think its user error.

Let me know if I'm missing some specific instructions or if I can provide crash dumps or anything else to help debug!

**Comment by kaalleen** [comment]
There has been new version since then, sorry for the late answer!! Ink/Stitch should run on apple silicon now, but Inkscape needs to be installed previously.
