### ISSUE TITLE
I'm investigating the root cause of "Border Crossing Itself" error.

### ISSUE THREAD

**Issue by stevensteichen** [inkstitch/inkstitch#918]
Admin, please delete this thread.
Sorry, found the real troubleshooting post.

**Comment by stevensteichen** [comment]
Picking back up. 
If I set Fill to 'none. The path(s) is correct, no BE. Setting Stroke to any Width is still correct. However, any Fill throws a BE, this is with or without any Stroke set. This in not a node issue that I've ever read as fill can't cross itself as fill is not a path. I get that if there exist a tiny loop it would be an issue but that would be on the path and all the nodes on the path are valid if Troubleshoot Object is to be trusted.  It's always reported as a node issue with the path. However, the path is valid. it's the fill that is interpreted as crossing itself.

If anyone can explain why Fill is a Border, I'd be very interested.

**Comment by kaalleen** [comment]
Nevermind and sorry for the late answer.
Are you still interested to dive into the Ink/Stitch code?
We really would need people with a developer background.

**Comment by stevensteichen** [comment]
> Nevermind and sorry for the late answer.
> Are you still interested to dive into the Ink/Stitch code?
> We really would need people with a developer background.

I'll pull down the code and review it. If it's in my wheel house and I can get a local build, I'll let you know if I have anything to contribute. This 'Border Crossing Itself' error needs to get resolved.

**Comment by kaalleen** [comment]
Great. If you need any help please let us know.
Right now we are working on an update which will touch a lot of files (#880).
It aims to finally use python 3 and recent Inkscape (inkex) versions.
It is almost everything working by now, except the build process has still it's issues. But for manual install it will be fine.

To solve the crossing border issue we need to use the "break apart fill objects" function under the hood. Difficulty here is to handle more than one object at once (if breaking apart results in multiple objects).

**Comment by kaalleen** [comment]
See also #859
