### ISSUE TITLE
Error using Inkstitch on Raspberry Pi - Raspberry Pi OS 

### ISSUE THREAD

**Issue by framboise314** [inkstitch/inkstitch#919]
Hi 
I installed Inkscape on the last / updated version of Raspberry Pi OS. Inkscape is version 0.92.4. 
I also install Inkstitch following the tutorial. Download the zip file, unzip in the extensions directory. All is well, no error message.
When using inkstitch on a simple form i get an error window saying "Inkscape has received additional data from the executed script. The script did not return an error, but this may indicate that the results are not as expected." and the error is :
/home/pi/.config/inkscape/extensions/inkstitch/bin/inkstitch: 1: /home/pi/.config/inkscape/extensions/inkstitch/bin/inkstitch: Syntax error: Unterminated quoted string
This error appears whatever is the option i choose in Extensions > Inkstitch ...
What do you think of this ?
regards
françois / www.framboie314.fr
![test_Pi400](https://user-images.githubusercontent.com/5877909/102112434-f9ccbd00-3e37-11eb-8959-bfcd254e4138.png)

**Comment by lexelby** [comment]
Sorry, we aren't planning to support raspberry pi.
