### ISSUE TITLE
High Sierra: UnicodeDecodeError

### ISSUE THREAD

**Issue by Kaesh92** [inkstitch/inkstitch#921]
Hey,
I'm kind of new in this business, but i like to use Inkstitch. I'm using it with my Macbook (High Sierra). 
Any time, when i try to safe in any embroidery file, i have these report:

"Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 40: invalid start byte"

What can I do?

thanks in advance (:

**Comment by kaalleen** [comment]
This is an encoding error which sadly exist in the latest build for High Sierra (we do not release new versions for high sierra anymore, sorry).
The error message you are receiving is actually only disugising a better error message.
You could try to use Ink/Stitch in english. If you were trying to save a file with a special char - this could cause an error like this as well. In this case the solution would be easy: use only common letters or numbers for your filename. If you really want to use special chars for it, rename it afterwards.

**Comment by kaalleen** [comment]
Right now we have a testrun to reintegrate a release for high sierra and mojave. If you are wanting to test if it's working (without your above described error) we would be happy to hear from you.

**Download files:**

English: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-en_US.zip
French: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-fr_FR.zip
German: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-de_DE.zip
