### ISSUE TITLE
High Sierra: UnicodeDecodeError

### ISSUE THREAD

**Issue by oliviagregory** [inkstitch/inkstitch#925]
Hey,

Whenever I try to save my file I get this error:

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte

I'm using a Sierra Mac, with an English program. I've checked that my file name doesn't include any weird letters but can't seem to solve the issue! Please let me know if there is something I can do

**Comment by kaalleen** [comment]
Would it be possible to share the file which is causing the issue? Maybe we can investigate what is causing the error.

**Comment by kaalleen** [comment]
Right now we have a testrun to reintegrate a release for high sierra and mojave. If you are wanting to test if it's working, we would be happy to hear from you. I believe/hope it will fix the error you are having.

**Download files:**

English: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-en_US.zip
French: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-fr_FR.zip
German: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-de_DE.zip

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 comes with an update for High Sierra/Mojave. This will fix this error.
