### ISSUE TITLE
Cant get install working... (new user)

### ISSUE THREAD

**Issue by GRIFFCOMMca** [inkstitch/inkstitch#935]
Hi, i found the videos on YouTube on how to install this as a plugin to Inkscape, however it doesn't seem to be able to do anything with any objects... below are the steps i followed.

- Windows 10, update 20H2 (64bit)
- Install Inkscape v1.0.1 64bit
- Download Inkstitch v1.29.1 (https://github.com/inkstitch/inkstitch/releases/download/v1.29.1/inkstitch-v1.29.1-windows-en_US.zip)
- Extracted all contents from the Inkstitch ZIP to the correct extensions folder (in my case C:\Users\ashley\AppData\Roaming\inkscape\extensions\inkstitch)
- Run Inkscape, create a circle (as youtube video), Object Properties shows as ID = path1917
- MENU Path > Object to Path (right click the same object, first selection is "Undo: Object to path" confirming it did action the path request)
- MENU > Extensions > Ink/Stitch > Params is grayed out (cant be selected)

Where is the issue here?

Many Thanks

![2020-12-24-inkstitch](https://user-images.githubusercontent.com/54428902/103116776-a297cb00-4635-11eb-8139-a1e1d5d76ece.png)

**Comment by tyrosinase** [comment]
On 12/24/20 10:13 PM, Ashley wrote:
>
> Hi, i found the videos on YouTube on how to install this as a plugin 
> to Inkscape, however it doesn't seem to be able to do anything with 
> any objects... below are the steps i followed.
>
>   * Windows 10, update 20H2 (64bit)
>   * Install Inkscape v1.0.1 64bit
>   * Download Inkstitch v1.29.1
>     (https://github.com/inkstitch/inkstitch/releases/download/v1.29.1/inkstitch-v1.29.1-windows-en_US.zip
>     <https://github.com/inkstitch/inkstitch/releases/download/v1.29.1/inkstitch-v1.29.1-windows-en_US.zip>)
>   * Extracted all contents from the Inkstitch ZIP to the correct
>     extensions folder (in my case
>     C:\Users\ashley\AppData\Roaming\inkscape\extensions\inkstitch)
>   * Run Inkscape, create a circle (as youtube video), Object
>     Properties shows as ID = path1917
>   * MENU Path > Object to Path (right click the same object, first
>     selection is "Undo: Object to path" confirming it did action the
>     path request)
>   * MENU > Extensions > Ink/Stitch > Params is grayed out (cant be
>     selected)
>
> Where is the issue here?
>

I'm not a Windows user, but I have seen this come up on the issues 
before. See if anything here helps you: 
https://github.com/inkstitch/inkstitch/issues/712

**Comment by GRIFFCOMMca** [comment]
Thanks, found the issue....

We used this directory "C:\Users\ashley\AppData\Roaming\inkscape\extensions\inkstitch" which created the issue, we moved all the files from "\inkstictch" to this "C:\Users\ashley\AppData\Roaming\inkscape\extensions" and it now works, so it appears in Windows cant use a containing subdirectory in the extensions folder for extensions, they have to be in the root of extensions (which would be messy if we had more than just this plugin, stored in that folder)

**Comment by kaalleen** [comment]
About it being messy, that's true. This is why since Inkscape 1.0 it is possible for extensions to be written in a way, that they can be placed into subdirectories. We haven't come to update it yet but we have a development version of Ink/Stitch prepared, where this behaviour will change. Which is a very good thing because many people run into this very same problem.
