### ISSUE TITLE
UnicodeDecodeError in input.py

### ISSUE THREAD

**Issue by GDAYDE** [inkstitch/inkstitch#938]
Bonjour,
Je viens d'installer Inkscape et le module Inkstitch, mais je n'arrive pas à ouvrir les fichiers PES, j'ai ce message d'erreur 👍 

Ink/Stitch a connu une erreur inattendue.

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 50, in affect
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc9 in position 23: invalid continuation byte

Que dois-je faire ? Merci de votre aide

**Comment by Marif91** [comment]
Je ne suis pas spécialiste de l'installation sur windows, mais je ne suis pas certaine que l'installation sur le disque D soit pertinente.

**Comment by GDAYDE** [comment]
merci pour votre réponse, inkstitch est installé sur le disque C, j'ai
suivi les instructions d'installation et j'ai bien mis l'extension
inkstitch dans le répertoire indiqué par inkscape...
je suis en train de chercher la solution à mon problème

*Ghislaine Daydé*
06 70 57 88 68

**Comment by kaalleen** [comment]
This is an encoding error. It is caused by special chars in your filename (or path e.g. your username). Special chars are characters such as é etc.

**Comment by GDAYDE** [comment]
merci pour votre réponse, effectivement, j'ai changé le chemin de mes
fichiers en supprimant les caractères spéciaux et tout va bien

*Ghislaine Daydé*
06 70 57 88 68
