### ISSUE TITLE
Duplicated visual commands do not work

### ISSUE THREAD

**Issue by nuclear-icebreaker** [inkstitch/inkstitch#947]
Good time of day everybody!
Today I stumbled upon something interesting in Inkstitch. I have twelve copies of same thing in my design. They are trim heavy - so I thought I will make one perfect and then duplicate it. Everything worked fine, except the trim commands on duplicated groups do not work...
PS Thanks for the great work on Inkstitch!

**Comment by kaalleen** [comment]
Duplicated commands will still be connected to their original object and not to the new one. This is more an Inkscape issue than an Ink/Stitch issue. As far as I can see it, we cannot really do anything about it, sorry.

**Comment by nuclear-icebreaker** [comment]
It is good to know.

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 will not error on duplicated visual commands, but only values the first one.
