### ISSUE TITLE
Is there a way to support the project (without developing for it)?

### ISSUE THREAD

**Issue by matou** [inkstitch/inkstitch#953]
Hi,

thank you for the ink stitch tool. It’s great to finally have something open source for embroidery. 

Is there a way to donate some money to the project? I couldn’t find anything on the website.

**Comment by kaalleen** [comment]
Wow, that's kind. We don't have a way to donate money. Best way to help us out for now would be to report errors and bring feature requests to our attention ;)

Happy embroidering 👍

**Comment by tyrosinase** [comment]
On 12/31/20 5:41 AM, Kaalleen wrote:
>
> Wow, that's kind. We don't have a way to donate money. Best way to 
> help us out for now would be to report errors and bring feature 
> requests to our attention ;)
>

I was thinking earlier: can we buy somebody an Apple Developer license?

**Comment by lexelby** [comment]
Do we need an apple developer license to be able to sign our app?

**Comment by wwderw** [comment]
I think for Apple and Windows require it.  When I converted my embTools program to C++/Qt, I noticed that with my Windows builds, kept on giving an error on first run about security concern and having to run anyway.  At least with running it on Win 8.1 and 10.

I think things are going to get more restrictive with Apple in the coming years, especially after Silicon takes hold, I wouldn't be surprised one bit about this requirement (dev license) being more of a necessity.

**Comment by lexelby** [comment]
In that case, donating an Apple developer license would be great!  I think we can't accept monetary donations because if we do, we lose our free JetBrains license.

**Comment by wwderw** [comment]
I would make sure on that.  Since a dev license does have a monetary value, that may still be considered getting a monetary donation.

**Comment by lexelby** [comment]
Fair point.

**Comment by tyrosinase** [comment]
OTOH I assume the dev license isn't granted to an organization but to a developer, so JetBrains can probably cope with an individual buying another individual a license, even if that second individual happens to be a volunteer developer for an organization. Certainly I'm not gonna insist that license to be used only for Ink/Stitch purposes.

**Comment by wwderw** [comment]
That would be even more reason to make sure about it.  
Who has the JetBrains license as well?  Is the JetBrains license individual or for the organization?

It never hurts to make sure everything is on the up and up.

**Comment by lexelby** [comment]
I checked, and JetBrains explicitly says that receiving donations via a donate button or the like is totally fine.  It wouldn't disqualify us from their open source program.

I also looked into the Apple stuff, and apparently, we will definitely need to pay them $99/yr if we want to avoid the unsigned app warnings.  What a racket.

Given that, it looks like we should set up a donate button.  I'm not sure how to do that and I probably won't have the time to look into it in the short term.

**Comment by kaalleen** [comment]
> Who has the JetBrains license as well? Is the JetBrains license individual or for the organization?

Sorry, I haven't answered it until now. I somehow missed it. For transparency reasons I should mention that I am using it too. Lex offered it to me and I was happy to have it.

@lexelby Are you thinking about "GitHub Sponsors"?

**Comment by lexelby** [comment]
Maybe!  I have no idea, to be honest.

I do still have a couple more JetBrains licenses that I can give to active developers on the project. If anyone is interested, hit me up at inkstitch at lex dot gd.

**Comment by wwderw** [comment]
As far as setting up a donation here on github, need to give your info to github for tax purposes, after a review process, if accept, should be able to add a funding.yaml file linked to the username that the sponsoring will be attached to inside the .github folder.

**Comment by lexelby** [comment]
Closing this for now, but still pondering the idea of a donate button

**Comment by chandraOloid** [comment]
@lexelby reopening this issue, as @Github is now part of @microsoft, maybe you can add that #Donate button. InkStitch is very useful and many people will be willing to contribute to your project in whatever small ways they can. Thanks

**Comment by lexelby** [comment]
Thanks!  We continue to discuss the idea behind the scenes.  We'll let you know if we decide to ask for donations, but I'm any case, Ink/Stitch is and always will be free to use :)
