### ISSUE TITLE
Inkstitch writing issues

### ISSUE THREAD

**Issue by mxwoodson** [inkstitch/inkstitch#956]
My operating system is Big Sur. When I try to run Inkstitch I get an error as follows:

"Inkscape has received additional data from the script excuted. The script did not return an error, but this may indicate the results will not be expected.  "Error writing to ./cityjpg.vp3: Read-only  file system."

What do I need to do to fix this? Please help!

**Comment by kaalleen** [comment]
Could you try to type the whole path to your file into the text field or try to save through File > Save Copy ... ?

**Comment by mxwoodson** [comment]
Thank you! I figured out what I did wrong!

**Comment by kaalleen** [comment]
What has been the issue?

**Comment by mxwoodson** [comment]
I would get an error every time I would use the ink stitch embroidery extender feature. It wouldn’t let me save the file.

**Comment by kaalleen** [comment]
Ok, thank you.

@lexelby we once planned to remove the embroider function completely. I believe it still has some options that the "save copy" way doesn't have?

**Comment by lexelby** [comment]
It has two options that are not available elsewhere:

1. Minimum stitch length that is converted to a jump stitch.
2. A couple of file formats are only available via Embroider (example: CSV)

For 1, I really want to have a way to specify options for an SVG.  We kind of already have that in the Print PDF settings, but it doesn't make sense to go there to change the jump stitch length.  I can think of at least one other setting to add: small stitch deletion.  Lots of digitizing software has that setting.

For 2, we can just add those formats to File -> Save As.  I can't think of a good reason not to.
