### ISSUE TITLE
Frame for stitching socks

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#957]
Hello folks,
I was trying to figure how to stitch socks on a typical consumer machine, that is without free arm. Personally, I do use a multi-needle machine with nice sock frames, but I would like help other people stitching socks. So I came up with the idea of creating a frame that inserts into an ordinary frame. The design will be creative commons, but before I release it I am looking for one or two persons who would be willing to test the idea and also willing to use/install OpenScad, define parameters and then print or laser a sock frame that fits into the frame of your machine. 
Someone here with too many ugly socks that need some decoration plus having a minimal experience with OpenScad and 3D printing or laser cutting ?
[sock-hoop-v0.9-7.scad.zip](https://github.com/inkstitch/inkstitch/files/5755813/sock-hoop-v0.9-7.scad.zip)

![sock_hoop_in_action](https://user-images.githubusercontent.com/2872643/103382436-58a85c80-4aef-11eb-9bcb-a5e78c06c6e3.jpg)
![sock_hoop_how_to-annotated](https://user-images.githubusercontent.com/2872643/103382438-5a722000-4aef-11eb-82d0-aa4322b8e473.jpg)
![open_scad_sock_frame-1](https://user-images.githubusercontent.com/2872643/103382443-5e9e3d80-4aef-11eb-8fd5-cb3e4ddf60fd.png)

PS: In case you need SVG/InkStitch emojis to stick onto your socks : https://edutechwiki.unige.ch/fr/InkStitch_-_broder_un_emoji (in french, but you should be able to find the SVG files to "save as" from your browser).

**Comment by danielkschneider** [comment]
PS to previous post: Picture shows an early 3d printed version (using 0.7 layers in 2 hours). I had to fix the sock with safety pins. The latest version doesn't need any.
![sock-tool-early-3d-version](https://user-images.githubusercontent.com/2872643/103382905-1849de00-4af1-11eb-93f5-91c4b80148a9.jpg)

**Comment by LochanLoch** [comment]
Ich finde das toll :-) - Danke.

**Comment by kaalleen** [comment]
Wow, this is really interesting. Great work!
Sadly I cannot laser cut or 3d print.

**Comment by danielkschneider** [comment]
> Wow, this is really interesting. Great work!
> Sadly I cannot laser cut or 3d print.

For you, I would make one next week since you do a lot for us, but you will have to measure out your frame and give me the numbers.  
![sock-hoop-measures](https://user-images.githubusercontent.com/2872643/103415284-bab1a200-4b81-11eb-98c9-eddfcb05278d.jpg)

**Comment by LochanLoch** [comment]
:-)
@kaalleen you are so lucky.
@danielkschneider I like it, but I found the _fretsaw_ from my old school days.

{ding: Laubsäge=fretsaw; coping saw or scroll saw; fretsaw; jig saw or jigsaw} xD

Happy New Year \o/

**Comment by danielkschneider** [comment]
@LochanLoch you actually need less, only 10 safety pins also do (sicherheitsnadeln).
![image](https://user-images.githubusercontent.com/2872643/103420395-31a56580-4b97-11eb-8282-c3f8614d01ca.png)
[More pictures](https://edutechwiki.unige.ch/fr/Cerceaux_et_stabilisateurs_en_broderie_machine#Broder_sur_des_chaussettes).
 
Anyhow, I first would just like to find 1-2 persons with a normal modern embroidery machine to test my design before I give away addons that will break them. I don't have access to such machines. I only got a [semi-pro](https://edutechwiki.unige.ch/en/Brother_PR1050X) with a sock frame and an [older ](https://edutechwiki.unige.ch/en/Elna_8300) much better consumer machine since it has somewhat of a free arm. I tested my sock frame with the Elna (the brother would have spit in my face).

After that, I can produce some more (right now I don't have easy access to a laser cutter that I master well).

**Comment by kaalleen** [comment]
> For you, I would make one next week since you do a lot for us

Whoa, what a great offer. Thank you so much for that.
I am actually considering to buy a laser cutter myself. I had several occasions lately when I thought it would be a great thing to have.
So maybe there is no need for you to send it over to me. Since I haven't made up my mind, I would like to come back to your offer if I decide against it. If that's ok.

Would it be ok to link to the files and/or the (not yet existent?) Edutech wiki page about the socks frame on the Ink/Stitch website once it is fully tested? It could be right next to the self made embroidery machine :)

**Comment by danielkschneider** [comment]
@kaalleen OK let me know if or when you still want one :)

For the links and document: Sure I will do a documentation (probably next week). Since this add-on might not work so well with normal embroidery machines and since the needle can run into its walls if the machine does some weird positioning, I would like to test the thing with at least one person before. @LochanLoch ?

- Daniel PS: 2 days ago I quick printed a version that I found OK for my personal use
![sock-frame-0-98 (1)](https://user-images.githubusercontent.com/2872643/103461000-38f57c00-4d1b-11eb-9a28-e0d1dc0097dc.jpg)
![sock-frame-0-98 (2)](https://user-images.githubusercontent.com/2872643/103461002-3bf06c80-4d1b-11eb-8112-701e4635fc07.jpg)

**Comment by lexelby** [comment]
This is so cool!

**Comment by danielkschneider** [comment]
Hello I finished documentation in both french and English and also adopted stable directories. I also uploaded the files to thingiverse, but their customizer doesn't seem to work. If you feel that this is of interest to the inkstitch community, feel free to copy anything you like

Files:

- http://tecfa.unige.ch/guides/embroid/sock-frame/
- http://tecfa.unige.ch/guides/embroid/sock-tool/

Documentation:

- https://edutechwiki.unige.ch/fr/Broder_sur_une_chaussette
- https://edutechwiki.unige.ch/en/Embroider_on_socks
- https://faclab.unige.ch/html/node/62

Most embroideries in the pictures were made with InkStitch, i.e. I [stitched emojis](https://edutechwiki.unige.ch/fr/InkStitch_-_broder_un_emoji ) as explained (in french): . The [English version](https://edutechwiki.unige.ch/en/InkStitch_-_emoji_embroidery) doesn't include the example SVGs.

**Comment by tungufoss** [comment]
This beyond cool. Something I'd like to bring to local FABLAB in the near future.

**Comment by kaalleen** [comment]
@danielkschneider thank you so much. I will add it to our website as soon as possible.

**Comment by lexelby** [comment]
@kaalleen Did we ever add this to the website?

@rlevine This is kind of adjacent to your interests...

**Comment by kaalleen** [comment]
> @kaalleen Did we ever add this to the website?

Yes

**Comment by LochanLoch** [comment]
> @kaalleen OK let me know if or when you still want one :)
> 
> For the links and document: Sure I will do a documentation (probably next week). Since this add-on might not work so well with normal embroidery machines and since the needle can run into its walls if the machine does some weird positioning, I would like to test the thing with at least one person before. @LochanLoch ?
> 
>     * Daniel PS: 2 days ago I quick printed a version that I found OK for my personal use
>       ![sock-frame-0-98 (1)](https://user-images.githubusercontent.com/2872643/103461000-38f57c00-4d1b-11eb-9a28-e0d1dc0097dc.jpg)
>       ![sock-frame-0-98 (2)](https://user-images.githubusercontent.com/2872643/103461002-3bf06c80-4d1b-11eb-8112-701e4635fc07.jpg)

Over two years later I notice that super socks frame. And I am so sorry that I am lost in WWW :-(
