### ISSUE TITLE
OSError: Could not find lib c or load any of its variants []. [1319] Failed to execute script inkstitch

### ISSUE THREAD

**Issue by dygrieve** [inkstitch/inkstitch#958]
Receive this error when I click on Inkscape > Extensions > Ink/Stitch > Params...

**Comment by kaalleen** [comment]
I believe you are on macOS Big Sur?
Read this step the additional installation steps for big sur here: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

**Comment by dygrieve** [comment]
Hi Kaalleen...Thank you for getting back so quickly.  I am sorry I should have said, Yes, I am running Inkscape on a MacBook Pro, macOS Big Sur, ver. 11.1.  I downloaded and installed Ink/Stitch (inkstitch-v1.29.1-osx-en_US.zip).  I watched the video (02 Install on macOS **OUTDATED** - Ink/Stitch Beginner Tutorial Series) and then I did what the link you sent states.  I went to my Terminal and entered the command (xattr -r -d com.apple.quarantine ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/) which is the correct path I believe for my machine.  My question is - After I type in this command and hit enter it seems to do something and I go back to a blank command prompt.  I also received the (cannot be opened, because the developer cannot be verified) message and I removed the inkstitch.bin/shapely.speedups._speedups.so file.  I checked and double checked to make sure the inkscape files are under the Extensions directory.  I am at a loss of what else to try.  Unless I am doing something wrong.  Please Help!  Thank you!

**Comment by dygrieve** [comment]
Hi again Kaalleen...I just realized I did not run the other command that you have listed where it says Users of "BIG SUR."  After I ran this it is now working!  I am sooooo sorry!  I admit I did skip over this step.  My bad!  I am good now!  Thank you for your time!

**Comment by kaalleen** [comment]
Thanks for you feedback. I am going to close it now. Please reopen if you encounter further problem with this issue.
