### ISSUE TITLE
unable to save pec/pes on mac format (High Sierra/Mojave)

### ISSUE THREAD

**Issue by KKamamalu** [inkstitch/inkstitch#965]
HI! Everything has been working great, but iʻm unable to save any pec or pes files. Has an error message usually involving a numbered ʻlineʻ and says invalid start byte. Is there a remedy for this? Iʻm using the Mac High sierra download. Thank you!

**Comment by ctekellogg** [comment]
I am having a similar issue, when trying to split and save an embroidery design that I obtained online. I get the following error: 
Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
    stdout = stdout.decode(sys.stdout.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 18: invalid start byte

I am using the Mojave version.

**Comment by kaalleen** [comment]
Hey there. Sorry for your trouble. We haven't been building for older macOS versions for a longer time. Right now we have a testrun to reintegrate a release for high sierra and mojave. If you are wanting to test if it's working (without your above described errors) we would be happy to hear from you.

**Download files:**
* English: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-en_US.zip
* French: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-fr_FR.zip
* German: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-de_DE.zip

**Comment by kaalleen** [comment]
Ink/Stitch v2.0.0 comes with an update for High Sierra/Mojave

**Comment by KKamamalu** [comment]
Aloha kaaleen-
I installed the latest extension and it was able to save a .pes file!!! Thank you so much!!! 


                              Kira Kamamalu
                         ***@***.***
                               808-938-5054   
               Fashion Line~  kkartclothing.com 
               Where Oral History Meets Design 
   Fine Art Web Gallery~ www.kira-    kamamalu-art.com
