### ISSUE TITLE
InkStitch 2.0 Embroidery on MAC OS (png to pes/vp3)

### ISSUE THREAD

**Issue by hanuta2021** [inkstitch/inkstitch#967]
Hey
My issue is about the process of turning a png into an embroidery file such as PES or VP3. Everything works fine but when it comes to embroidering the object( I click on extensions -  Ink/Stitch - visualize and Export - Embroider) it sends me this error: "Inscape has received additional data from the script executed. The script did not return an error, but this may indicate the results will not be as expected.  
Error writing to embroidery.pes: Read-only file system."
I already cleaned up the document and removed small strokes.

I would really appreciate it if someone helped me out! 
Thanks in advance
<img width="511" alt="Bildschirmfoto 2021-01-04 um 14 53 51" src="https://user-images.githubusercontent.com/76915178/103559032-ca005a80-4eb5-11eb-92ac-aab74b9821f4.png">

**Comment by kaalleen** [comment]
Thank you for reporting your issue here. Could you try to save your file through "File > Save a Copy..."?

**Comment by hanuta2021** [comment]
Thank you! I tried it and saved the copy as a svg file but I got this: "Error writing to ./embroidery.pes: Read-only file system“ 

Do you have any other ideas?

**Comment by kaalleen** [comment]
Which directory did you choose to save your file in (with copy as as)?

**Comment by kaalleen** [comment]
This error is not supposed to show up in the updated Ink/Stitch version. Therefore I'll close this issue. Please reopen, if you are still having issues.
