### ISSUE TITLE
Translate to french

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#968]
I never know when something new on Inkstitch needs to be translated to french. I discover today that this page
https://inkstitch.org/fr/docs/fill-tools/
 was not tranlated and even was not complete in english. Imagine : Today, somebody gives the link to the german page. The user turn to french and get english. Image and link are missing. 
It is not the first time. It would be nice to be able to be notified when there are changes to translate and to have the changes on the page.
I am not able to read the whole site to see if there are changes

**Comment by kaalleen** [comment]
Sorry fpr brevity. I am a bit short on time.
Have a look on This page: https://inkstitch.org/developers/localize/#franhttps://inkstitch.org/developers/localize/#français
It always lists every missing or outdated translation.
