### ISSUE TITLE
Error code when running params Mac big sur

### ISSUE THREAD

**Issue by smadison** [inkstitch/inkstitch#970]
I installed Inkstitch directly into my extensions folder and added the needed prompts in terminal and the options are no longer greyed out.  However, when I try to run params it gives me an error code that says Inkscape has received additional data from the script executed.  How do I fix this? I have tried deleting inkscape and inkstitch and redownloading them with no success, in fact when I delete and redownload, inkstitch is already on my inkscape without me redoing the install. 
<img width="1280" alt="Screen Shot 2021-01-04 at 5 30 59 PM" src="https://user-images.githubusercontent.com/76977092/103590258-fb2b5b80-4eb2-11eb-9d1b-a6560b49de14.png">

**Comment by JNeshat** [comment]
Same problem with mine too. Would be great to know the correct solution

**Comment by leanbop** [comment]
Same issue, any resolution?

**Comment by kaalleen** [comment]
This issue should be fixed with the newest Ink/Stitch update (v2.0.0). Therefore I am going to close this issue. If you are still having problems with Ink/Stitch, please reopen,
