### ISSUE TITLE
Additional steps for Big Sur are not working when put into terminal 

### ISSUE THREAD

**Issue by 5uazo** [inkstitch/inkstitch#971]
Im running Big Sur and when I run the script "xattr -r -d com.apple.quarantine ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/
" on terminal it responds "xattr: No such file:..." same for when I run "cd ~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/
cd inkstitch/bin
ln -s libpython2.7.dylib libc.dylib" so I assume that us my problem when I try to use params for my image and get this issue..did I plug the ink stitch in the wrong place or??? 
<img width="358" alt="Screen Shot 2021-01-06 at 5 02 47 AM" src="https://user-images.githubusercontent.com/77055156/103766810-b7cd0c00-4fdc-11eb-888a-f290137861fc.png">

**Comment by kaalleen** [comment]
Open the settings dialogue in Inkscape: Edit > Prefernces
Go to system and watch out for the user extensions folder.
Substitute  "~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape/extensions/" with the extensions folder location.

**Comment by 5uazo** [comment]
I mapped it to where it is at in my computer but shows the now




<img width="850" alt="Screen Shot 2021-01-08 at 4 10 56 PM" src="https://user-images.githubusercontent.com/77055156/104073997-51a6db80-51cc-11eb-8b76-fbd84b0849c5.png">
did I do something wrong?

**Comment by kaalleen** [comment]
Sorry, I am not very familiar with macOS issues. All I can see, that this is a privilege thing. Any macOS users here to help us out?

**Comment by Marif91** [comment]
![Capture d’écran 2021-01-19 à 22 42 19](https://user-images.githubusercontent.com/65076100/105096956-1ea3f800-5aa8-11eb-9a17-56a0ece890b4.png)
Je pense qu'il y a un problème de syntaxe, voici ce que je tape sous catalina, je n'ai pas les deux dernières [étapes] à effectuer...

**Comment by kaalleen** [comment]
No further feedback. I'll close this issue now. Please reopen, if you are still having issues installing Ink/Stitch.
