### ISSUE TITLE
Unit mismatch with manual install in inkscape 1.x

### ISSUE THREAD

**Issue by rumpeltux** [inkstitch/inkstitch#978]
I have an object of width 17.5mm in inkscape, but inkstitch consistently thinks it’s only 5.5mm wide, see this illustration:
![image](https://user-images.githubusercontent.com/200124/104820310-37a47300-5834-11eb-957c-fa502a3d7fc9.png)

You can also see that the stitch width is unproportionally wider than in inkscape (inkscape stroke width 2mm, inkstitch width 2mm), so that part seems to be correct, but the total object width isn’t.

This looks like a bug to me.

I guess as a workaround I can resize my working area in inkscape, but it’s still somewhat unexpected (and the distortion will be confusing).
This is in inkscape 1.0.1 with inkstitch from current master branch following the manual instructions.

**Comment by kaalleen** [comment]
Thank you for reporting this issue. Would it be possible to send the svg file (or a part?)

**Comment by rumpeltux** [comment]
This is actually reproducible in a fresh document. It’s only reproducible with the local installation. The prepackaged one works fine.
My hunch is that transformations (including the viewport one) don’t work correctly (inkstitch seems to scale a path with a matrix transform differently than one whose path points were scaled by inkscape, although they have the exact same dimensions).

**Comment by rumpeltux** [comment]
Also worth noting that I do see a lot of deprecation warnings related to the inkex functions.

```
inkstitch.py:44: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  extension.affect(args=remaining_args)
.local/lib/python2.7/site-packages/wx/core.py:2206: ImportWarning: Not importing directory '.local/lib/python2.7/site-packages/wx/locale': missing __init__.py
  import locale
Software/inkstitch/lib/extensions/base.py:157: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  if self.selected:
Software/inkstitch/lib/extensions/base.py:158: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  if node.get("id") in self.selected:
Software/inkstitch/lib/elements/element.py:270: DeprecationWarning: cubicsuperpath.parsePath -> None
  return cubicsuperpath.parsePath(d)
Software/inkstitch/lib/svg/path.py:13: DeprecationWarning: simpletransform.applyTransformToPath -> Path(path).transform(mat)
  simpletransform.applyTransformToPath(transform, path)
Software/inkstitch/lib/elements/element.py:312: DeprecationWarning: inkex.bezier.cspsubdiv -> Sub-divide cubic sub-paths
  cspsubdiv(path, 0.1)
```

**Comment by rumpeltux** [comment]
I downloaded inkscape 0.92.3 and did `cp inkscape-0.92.3/share/extensions/*.py .` which seems to have fixed the issue, so it looks indeed like there was some API change affecting the scaling somewhere…

**Comment by kaalleen** [comment]
Oh, now I see your scaling issue and it makes totally sense.
Maybe you want to checkout kaalleen/inkscape1.0

But it uses python 3 and is still in development status.

**Comment by kaalleen** [comment]
> I downloaded inkscape 0.92.3 and did cp inkscape-0.92.3/share/extensions/*.py . which seems to have fixed the issue, so it looks indeed like there was some API change affecting the scaling somewhere…

Ah, nevermind :D

**Comment by rumpeltux** [comment]
> Maybe you want to checkout kaalleen/inkscape1.0
> 
> But it uses python 3 and is still in development status.

Ha! I’ve been wondering if you’re already working on this. Thanks for the pointer. Tried it and works like a charm so far :-)

I guess we can close this one then.
