### ISSUE TITLE
Manual setup instructions outdated?

### ISSUE THREAD

**Issue by rumpeltux** [inkstitch/inkstitch#980]
Here are a few notes from me (I’m on a debian based system):

Using python-wxgtk3.0 doesn’t work, [since the wx package is the classic version](https://stackoverflow.com/questions/27102834/wxpython-how-to-import-the-wx-adv-module).

Using wxPython 4.1.1 (from current ubuntu) doesn’t seem to work as I get errors such as `Vertical alignment flags are ignored with wxEXPAND`

    python2 -m pip install --upgrade -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython

Using wxPython 4.0.7 (via the command listed on the official documentation for Ubuntu 16.04) works if you also install the libjpeg-turbo8. At least the UI now renders :-)

**Comment by kaalleen** [comment]
Nice, thanks for your input. Actually I planed to update the instructions after we've updated Ink/Stitch to run with python 3.
But since we've got your report, we can add it as well ;)

**Comment by rumpeltux** [comment]
After installing wxPython manually you’ll also need to remove it from requirements.txt.
I also needed to set numpy>=1.16.

Maybe most of this is obsolete after switching to python3.

**Comment by kaalleen** [comment]
Yes. Since you reported about all these deprecation messages I rather wait until the inkscape/python update release for the documentation.

But since you seem to have an insight of the build process, maybe you could help us out. The Inkscape1.0 branch has an issue with numpy installaion on linux. The build process only works for the windows release so far. macOS will complain with a "access to the screen" message.

**Comment by rumpeltux** [comment]
Happy to give it a try. How do I start / trigger the build process? Do you have a documentation reference?
In #880 the linux build seems to succeed?

**Comment by kaalleen** [comment]
Yes, you are right. The build succeeds, but it doesn't work :D If you rerun the last build it will actually succeed completly, it was just a timeout issue on the github actions side. It complains about numpy. I haven't figured it out yet. Something with the installation went wrong. Maybe we need an other version, I don't know.

I invited you to become a member of ink/stitch. Whenever you push to a branch the build process will be triggerd. You can find the build workflow in .github/workflows/build.yml

If you have questions don't mind asking... and thanks for your offer to help!

**Comment by kaalleen** [comment]
Do you think it could have something to do with the --strip option in bin/build-python?
I haven't tested it yet. I just remember that I've read something about it once. Can't find it anymore.

**Comment by rumpeltux** [comment]
By fixing numpy<=1.17.4 the error went away. And the extension at least loads.

I’m now getting a

> "TypeError: '<' not supported between instances of 'ParamsTab'"

IIRC in my previous pull from your branch I didn’t have that problem.

**Comment by kaalleen** [comment]
Works on my side. But I think you already fixed it? Thanks for your work on it! It's really good to have you here.

**Comment by rumpeltux** [comment]
Yes, fixed it in 76c1d4bf9ffe249bc41f7f4f6b57f34c721dd409 and PR #985

Looking forward to seeing the inkscape1.0 release soon.

**Comment by kaalleen** [comment]
> Looking forward to seeing the inkscape1.0 release soon.

Yes, that would be really great. But I am afraid we will have to fix the mac build first. I have no mac and cannot test anything here. I am told it has the "needs acces to the screen" error, which is common if pyinstaller isn't used with --windowed. But we do use it already, so I am really not sure what to do about it.

But it's great to see the linux build is working by now. Thanks for your work on it.

**Comment by kaalleen** [comment]
I think I found a way to run the new version on macOS without it complaining about not being able to access the screen (#986). It will hopefully be tested soon, then we will know.

**Comment by lexelby** [comment]
That ParamsTab TypeError is so weird.  This has worked for years.  I thought it just compared the id() of the objects, which worked fine.  I wonder what changed?

**Comment by rumpeltux** [comment]
Probably related to a wxPython change that was included due to version bump?

**Comment by kaalleen** [comment]
Documentation for manual install has been updated when Ink/Stitch branch for Inkscape 1.0 has been merged.
