### ISSUE TITLE
satin stitch on closed path

### ISSUE THREAD

**Issue by RobinTournemenne** [inkstitch/inkstitch#984]
(sorry if not the right place to ask, tell me if I am doing  a mistake). How should I do to create a satin column stitch for this shape:
<img width="498" alt="Capture d’écran 2021-01-19 à 21 51 03" src="https://user-images.githubusercontent.com/1475510/105091659-7474a200-5aa0-11eb-8618-8cbe94032aaf.png">

My first laborious guess is this one:
<img width="492" alt="Capture d’écran 2021-01-19 à 21 52 14" src="https://user-images.githubusercontent.com/1475510/105091794-ac7be500-5aa0-11eb-9388-02437117e795.png">

**Comment by MK-12-20MM** [comment]
That is the concept. But having it come to a point probably won't stitch out as you would think,  plus -can't tell if the pointed end is open.   Satin columns should be around 1.5 MM minimum (rails) in width as a generic rule of thumb.  Getting that small it won't look like a statin column do to density of the stitching.

**Comment by RobinTournemenne** [comment]
Got it. The pointed end is open. I suppose then that my approach is bad, I should choose another point or modify my original design? Any advice?

**Comment by MK-12-20MM** [comment]
Are you getting an error?  Or is simulation not as expected?   You might want to look on youtube as there is all kinds of videos on inkstitch statin columns.  Just from your pic your rails are right but having the rails coming to a point you might have crossover issues.

**Comment by Marif91** [comment]
Il est préférable, quand la colonne satin devient trop étroite, de finir avec un point droit paramétré en point triple par exemple.

**Comment by RobinTournemenne** [comment]
thanks @Marif91 and @MK-12-20MM! Everything was fine on the algorithmic side @MK-12-20MM, I wanted to get the embroider point of view that @Marif91 gave. Amazing community!
