### ISSUE TITLE
Autofill Stitch Gap

### ISSUE THREAD

**Issue by dmacias2785** [inkstitch/inkstitch#987]
Is there a way to edit the path of an autofill stitch. Inkscape likes to break up fill stitches into sections. The problem is that whenever two sections meet there is always a gap. I would love if it could autofill from top to bottom without jumping around. Perhaps a way go 1 extra row past the last line.

**Comment by kaalleen** [comment]
No sorry, I am afraid there is no option unless you try to break your fill shapes yourself into smaller parts.Usually it wouldn't give you a bad result (if you use a proper underlay and hoop your fabric well). Do you have a very big area to fill?
I'd be curious to see an image how it affects your embroidery. Would that be possible?

**Comment by dmacias2785** [comment]
I think during the process of meeting in the middle the fabric has slightly moved. It always looks like there is just 1 row missing. If I re-embroider that area and pull the fabric slightly I can usually fill in the gap.

**Comment by MK-12-20MM** [comment]
You need to use appropriate stabilizer for your project.  Usually cutaway vs tearaway works better to avoid fabric pull. Adhesive or fusible stabilizer even better.  Also for adjacent fills, changing fill stitch direction is helpful in avoiding fabric pull.

**Comment by kaalleen** [comment]
This is related to a new feature request (#1068).
That's why I will close this issue now. Please reopen, if you think, this issue is still relevant apart from the mentioned feature request.

**Comment by jamestebby** [comment]
I still have this issue it's very annoying that we can't atleast say move top to bottom or bottom to top for this block of colour and don't split it.

**Comment by george-steel** [comment]
You can attach autofill start and end commands to control the path of autofill.

**Comment by jamestebby** [comment]
Tried that trouble is when I ass more than 4 inkscape crashes
