### ISSUE TITLE
Bug "Border crosses itself" without crossing border

### ISSUE THREAD

**Issue by Rrreutel** [inkstitch/inkstitch#990]
I'm slowly getting to know Ink/Stich, very nice work!

I've been scratching my head trying to figure out "Border crosses itself" errors when troubleshooting objects, where I can find no fault in the design. The reason I think this is a bug, is that the error dissapears after slightly moving the entire object. Maybe it's a precision/rounding thing?

I've narrowed it down to a single object, included in the attached file test_overlap.svg

When you open the file, select the object in it, then select Ink/Stitch->troubleshoot->troubleshoot object, a "Border crosses itself" error is rendered into the troubleshoot layer. After slightly moving the object and checking again, the error is gone.

When you open the file:
![step1](https://user-images.githubusercontent.com/5664169/105606675-12b38100-5d9b-11eb-917b-8b4e4cd30a49.png)

...select the object in it, then select Ink/Stitch->troubleshoot->troubleshoot object...
![step2](https://user-images.githubusercontent.com/5664169/105606685-21019d00-5d9b-11eb-9b71-41d62045766b.png)

...a "Border crosses itself" error is rendered into the troubleshoot layer...
![step3](https://user-images.githubusercontent.com/5664169/105606693-29f26e80-5d9b-11eb-8b1b-46f0a59d29ed.png)

...with no apparent error in the path.
![step3a](https://user-images.githubusercontent.com/5664169/105606750-7d64bc80-5d9b-11eb-8bbf-5a82e850077e.png)

Then when moving the complete object slightly to a new position and checking again...
![step4](https://user-images.githubusercontent.com/5664169/105606701-324aa980-5d9b-11eb-9c46-e23cc6fa82e8.png)

...the error is now gone!
![step5](https://user-images.githubusercontent.com/5664169/105606706-3c6ca800-5d9b-11eb-91ef-94424ff6ce98.png)

**Comment by Rrreutel** [comment]
Can't seem to upload svg for some reason, I've put it in a zip: [test_overlap.zip](https://github.com/inkstitch/inkstitch/files/5860468/test_overlap.zip)

**Comment by Rrreutel** [comment]
Forgot versions:
InkScape 1.0.1 (3bc2e813f5, 2020-09-07) Windows 10
Ink/Stich 1.29.1

**Comment by kaalleen** [comment]
Thank you for your nice report including an svg. This is always very helpful to have.
Actually there are two nodes on top of each other in the shape and that's where the arrow is pointing to. We know that Ink/Stitch is very sensitive about these things and it can be annyoing if you just want to get your fill area right. Sometimes with circles it can even help to grab one node and hit escape to release it without changing it's position. This will cause Inscape to alter the path from absolute to relative and after that the shape will render correctly. I wrote up a some code to make Ink/Stitch less sensitive to these shapes. We will test it carefully and see if it is suitable for us. We had plans to run  "Fill tools > break apart fill objects" extension behind the scenes on every fill. So Ink/Stitch can handle crossing border shapes without any complaint. But this will take a while until we'll be able to work on it.

**Comment by Rrreutel** [comment]
Thanks for your answer, and for the tip of grabbing and releasing a single problem node. 

I didn't notice the 2 nodes overlapping in my own file, good find. It is still strange, because after moving the object it still has the same two overlapping nodes, but it does not longer produce an error. Sensitive I guess.

**Comment by kaalleen** [comment]
Our next release will hopefully handle this issue better. We just merged additional code to do so: #993
Therefore I am going to close the issue now. If you still encounter similar behaviour in the next release, please reopen the issue.
